AK/URL.cpp
AK/URL.h
AK/URLParser.cpp
AK/URLParser.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator.cpp
Tests/AK/TestURL.cpp
Userland/Libraries/LibGemini/GeminiJob.cpp
Userland/Libraries/LibHTTP/HttpJob.cpp
Userland/Libraries/LibHTTP/HttpsJob.cpp
Userland/Libraries/LibWeb/Bindings/LocationObject.cpp
Userland/Libraries/LibWeb/Bindings/WindowObjectHelper.h
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Userland/Libraries/LibWeb/URL/URL.cpp
Userland/Libraries/LibWeb/URL/URL.h
Userland/Libraries/LibWeb/URL/URL.idl
Userland/Libraries/LibWeb/URL/URLSearchParams.cpp
Userland/Libraries/LibWeb/URL/URLSearchParams.h
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Userland/Libraries/LibWebSocket/Impl/TCPWebSocketConnectionImpl.cpp
Userland/Libraries/LibWebSocket/Impl/TLSv12WebSocketConnectionImpl.cpp
Userland/Libraries/LibWebSocket/WebSocket.cpp

This is a complete implementation (apart from the still partial URLSearchParams class)

LibWeb+AK: Implement the URL built-in

---

Base/res/html/misc/computed-style.html
Userland/Libraries/LibWeb/CSS/ComputedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/StyleValue.h

This adds more computed styles, mostly ones that represent combined values and can be reassembled with recursive calls to `property`.

LibWeb: Add more computed styles

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

This fixes a few small issues with flexbox.
Mainly it fixes an infinite loop when the page is sufficiently weird.

Flexbox fixes

---

Userland/Libraries/LibJS/Parser.cpp

We were previously pushing a scope but forgetting to actually set it as
the current scope.
~~Note: currently waiting for test262 impact results :P~~
Update: No impact on test262.

LibJS: Use ScopePusher to correctly push the scope in for statements

---

Userland/Applications/PixelPaint/EllipseTool.cpp
Userland/Applications/PixelPaint/EllipseTool.h
Userland/Applications/PixelPaint/RectangleTool.cpp
Userland/Applications/PixelPaint/RectangleTool.h
Userland/Libraries/LibGfx/Point.cpp
Userland/Libraries/LibGfx/Point.h

https://user-images.githubusercontent.com/9910883/133528018-3cf23266-4e13-4eaa-8796-ad1289d518ae.mp4

PixelPaint: Allow drawing Rectangle/Ellipse with custom, fixed aspect ratio

---

Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/CSS/StyleValue.h
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Userland/Libraries/LibWeb/Layout/Node.cpp

This patch adds parsing support as well as all the needed stuctures all
over LibWeb to pass Transformations around.

LibWeb: Add transform property to the system

---

Userland/Applications/TextEditor/MainWidget.cpp
Userland/Applications/TextEditor/TextEditorWindow.gml
Userland/Libraries/LibGUI/TextEditor.cpp
Userland/Libraries/LibGUI/TextEditor.h

And put them in their own tidy segment

TextEditor: Show total character and word count without selection

---

Kernel/Bus/VirtIO/Device.cpp

Fixes https://github.com/SerenityOS/serenity/issues/9876 .

Kernel/VirtIO: Fix broken initialization logic for VirtIO devices.

---

Kernel/Syscalls/pipe.cpp

While working on a port, I saw a pipe creation fail due to missing
nonblock support in pipe syscall.

Kernel: Add support for O_NONBLOCK in pipe syscall

---

Userland/Libraries/LibWeb/CSS/StyleResolver.cpp

This doesn't capture the whole picture as shorthands are not considered
in a careful way.
A very dirty hack is included to not try to resolve 'font' as the amount
of debug spam it generated ("No inital value found for...") was
unhelpful.
Ideally this would move into set_property_expanding_shorthands where shorthands are expanded as needed and there we would resolve the inherit kexwork. For now this works reasonably well.

LibWeb: Resolve 'inherit' property-value somewhat

---

Userland/Utilities/checksum.cpp

Since we were just repeatedly calling `->open()` on the same Core::File no one was clearing it's internal buffer, which means hashing multiple files in one go would result in different hashes than hashing each file separately.
**Before:**
**After:**

checksum: Stop reusing the same Core::File for multiple files

---

Base/usr/share/man/man7/boot_parameters.md

Man pages: Update boot_parameters(7) manual page

---

Ports/neofetch/patches/fix-shebang.patch

Ports: Remove unnecessary patch from the neofetch port

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/Interpreter.cpp
Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/BoundFunction.cpp
Userland/Libraries/LibJS/Runtime/BoundFunction.h
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
Userland/Libraries/LibJS/Runtime/FunctionEnvironment.h
Userland/Libraries/LibJS/Runtime/FunctionObject.cpp
Userland/Libraries/LibJS/Runtime/FunctionObject.h
Userland/Libraries/LibJS/Runtime/FunctionPrototype.cpp
Userland/Libraries/LibJS/Runtime/GeneratorFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
Userland/Libraries/LibJS/Runtime/GeneratorObject.h
Userland/Libraries/LibJS/Runtime/NativeFunction.h
Userland/Libraries/LibJS/Runtime/Object.h
Userland/Libraries/LibJS/Runtime/ProxyObject.h
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/Runtime/Value.cpp
Userland/Libraries/LibJS/Runtime/Value.h
Userland/Libraries/LibJS/Tests/builtins/Symbol/Symbol.keyFor.js
Userland/Libraries/LibWeb/DOM/EventTarget.cpp
Userland/Libraries/LibWeb/HTML/GlobalEventHandlers.cpp
Userland/Libraries/LibWeb/HTML/WebSocket.cpp
Userland/Utilities/js.cpp

TL;DR: depending on [[BoundThis]] for arrow functions is the biggest :yakfire: I've ever seen.
This paves the way for some major refactorings of [[Call]] and [[Construct]].

LibJS: Untangle the mess that is FunctionObject

---

Kernel/Prekernel/Arch/aarch64/Mailbox.cpp
Kernel/Prekernel/Arch/aarch64/Mailbox.h
Kernel/Prekernel/Arch/aarch64/UART.cpp
Kernel/Prekernel/Arch/aarch64/UART.h
Kernel/Prekernel/Arch/aarch64/init.cpp
Kernel/Prekernel/CMakeLists.txt
Meta/run.sh

With this, `Meta/serenity.sh run aarch64` produces some output on the terminal :^)

Add a UART for aarch64

---

Documentation/AdvancedBuildInstructions.md

Add an explicit instruction on how to copy files from your local machine

Documentation: Add build file copy instruction

---

AK/StringUtils.cpp

We already know the length of these substrings, so there's no need to check their lengths using strlen in the StringView(char*) constructor.
This patch also removes an accidental 1-byte OOB read that was left over from when this method received null-terminated char pointers instead of string views, as well removes the unnecessary lambda call (two of the checks were impossible, and this was only called in one place, so we can just inline it)

AK: Eliminate avoidable strlen call in String::matches

---

Userland/Libraries/LibProtocol/RequestClient.cpp
Userland/Libraries/LibProtocol/RequestClient.h
Userland/Libraries/LibTLS/Socket.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Userland/Services/RequestServer/ClientConnection.cpp
Userland/Services/RequestServer/ClientConnection.h
Userland/Services/RequestServer/ConnectionCache.h
Userland/Services/RequestServer/RequestServer.ipc

blah blah, more faster loading
blah blah, more REEEEEEEEEEEEEEEEEEEEEEEEEquestServer spins.

RequestServer+LibWeb: Implement the dns-prefetch and preconnect link relationships

---

Userland/Services/RequestServer/ClientConnection.cpp

We need to set the root certificates, and tell the connection cache that
the preconnect job finished (otherwise it would spin forever, waiting
for us to tell it that).
(most likely) fixes the recent loading regressions.

RequestServer: Correctly start preconnected TLS sockets

---

Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/CSS/CSSConditionRule.cpp
Userland/Libraries/LibWeb/CSS/CSSConditionRule.h
Userland/Libraries/LibWeb/CSS/CSSConditionRule.idl
Userland/Libraries/LibWeb/CSS/CSSGroupingRule.cpp
Userland/Libraries/LibWeb/CSS/CSSGroupingRule.h
Userland/Libraries/LibWeb/CSS/CSSGroupingRule.idl
Userland/Libraries/LibWeb/CSS/CSSRuleList.cpp
Userland/Libraries/LibWeb/CSS/CSSRuleList.h
Userland/Libraries/LibWeb/CSS/CSSRuleList.idl
Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
Userland/Libraries/LibWeb/Dump.cpp

IDL files are included, though they're not actually wired-up at all.

LibWeb: Implement some CSS rule classes

---

Userland/Libraries/LibCore/NetworkJob.cpp
Userland/Libraries/LibCore/NetworkJob.h
Userland/Libraries/LibCore/Socket.cpp
Userland/Libraries/LibCore/Socket.h
Userland/Libraries/LibGemini/GeminiJob.cpp
Userland/Libraries/LibGemini/GeminiJob.h
Userland/Libraries/LibGemini/Job.h
Userland/Libraries/LibHTTP/HttpJob.cpp
Userland/Libraries/LibHTTP/HttpJob.h
Userland/Libraries/LibHTTP/HttpsJob.cpp
Userland/Libraries/LibHTTP/HttpsJob.h
Userland/Libraries/LibHTTP/Job.cpp
Userland/Libraries/LibHTTP/Job.h
Userland/Services/RequestServer/ClientConnection.cpp
Userland/Services/RequestServer/ConnectionCache.cpp
Userland/Services/RequestServer/ConnectionCache.h

This fixes a whole bunch of RS spins.

RequestServer: SpinNoMo* (most of the time)

---

AK/UFixedBigInt.h
Tests/Kernel/mprotect-multi-region-mprotect.cpp
Tests/LibWasm/test-wasm.cpp
Userland/Libraries/LibMarkdown/Text.cpp

That should solve this problem once and for all.

Fix the last few remaining typos!

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

If an element has a relative specified length on the cross axis, but in
the lineage there are no parents that have any fixed cross size, this
would have resulted in a 0 cross size.
We now catch that and check whether the relative length would result in
an actual definite length if resolved.

LibWeb: Flexbox: Check for relative resolvability on the cross axis

---

Base/res/html/misc/media-queries.html
Base/res/html/misc/welcome.html
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/CSS/CSSMediaRule.cpp
Userland/Libraries/LibWeb/CSS/CSSMediaRule.h
Userland/Libraries/LibWeb/CSS/MediaList.cpp
Userland/Libraries/LibWeb/CSS/MediaList.h
Userland/Libraries/LibWeb/CSS/MediaList.idl
Userland/Libraries/LibWeb/CSS/MediaQuery.cpp
Userland/Libraries/LibWeb/CSS/MediaQuery.h
Userland/Libraries/LibWeb/CSS/MediaQueryList.cpp
Userland/Libraries/LibWeb/CSS/MediaQueryList.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/DOM/Window.cpp
Userland/Libraries/LibWeb/Dump.cpp
Userland/Libraries/LibWeb/Dump.h
Userland/Libraries/LibWeb/Forward.h

This is only about parsing them, not about actually matching them or applying their contained rules to the document. That's next on my list, but this is getting chonky already.

LibWeb: Parse media queries

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

A flex-basis of zero doesn't actually mean that the preferred size of
the particular Box is 0. It means that the Box should take the least
amount of space possible while still accomodating the content inside.
We catch and circumvent this now right when the flex-basis property gets
read for the FlexFormattingContext.
This isn't mentioned anywhere in the seemingly relevant portions of the
spec, however thanks to this answer https://stackoverflow.com/a/47579078
(which is not entirely correct about width either) lead to the behavior
that is wanted and used by other Browsers.

LibWeb: Flexbox: Catch zero flex-basis and use width instead

---

Userland/Libraries/LibGL/GL/gl.h

LibGL: Remove duplicate GLboolean typedef

---

Userland/Libraries/LibTLS/Record.cpp
Userland/Libraries/LibTLS/Socket.cpp

Each TLS record has a limited max size, we should respect that and split
the packets.
Fixes RecordOverflow errors when a packet larger than 18432 bytes is
sent over.

LibTLS: Split large application data packets into chunks

---

.mailmap
Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h

I also added my copyright to some files where it was not present and probably got lost in the many rebasings of the scoping rewrite. I hope that's ok.

Everywhere: Use my awesome new serenityos email :^)

---

Meta/Lagom/CMakeLists.txt
Tests/LibJS/CMakeLists.txt
Tests/LibJS/test-invalid-unicode-js.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Interpreter.cpp
Userland/Libraries/LibJS/Lexer.cpp
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
Userland/Services/WebContent/WebContentConsoleClient.cpp
Userland/Utilities/js.cpp

I have also created a tests for the unicode issue fixed in #9947.
Most of these fixes are really stop-gap fixes to make things work until we have proper realm/executing context support.

LibWeb + LibJS: Further fixes after the scoping rework

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

Auto margins are still not supported at all, but this is a good start
into supporting margins on flex items.
The way cross-before (top for row, left for column) are handled is very
naive.

LibWeb: Flexbox: Care more about cross-axis margins

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

This makes http://wpt.live/css/css-flexbox/flexbox-flex-wrap-flexing.html pass and fixes incorrect behavior when flex-direction: wrap is specified

Flex shenanigans

---

Userland/Libraries/LibSQL/AST/AST.h
Userland/Libraries/LibSQL/AST/Expression.cpp
Userland/Libraries/LibSQL/AST/Select.cpp
Userland/Libraries/LibSQL/SQLClient.cpp
Userland/Libraries/LibSQL/SQLClient.h
Userland/Libraries/LibSQL/Tuple.cpp
Userland/Libraries/LibSQL/Tuple.h
Userland/Libraries/LibSQL/TupleDescriptor.h
Userland/Libraries/LibSQL/Type.h
Userland/Libraries/LibSQL/Value.h
Userland/Services/SQLServer/DatabaseConnection.cpp
Userland/Services/SQLServer/SQLClient.ipc
Userland/Services/SQLServer/SQLStatement.cpp
Userland/Utilities/sql.cpp

1. New features in ``sql`` utility: dot-commands to connect and disconnect from databases, and to read SQL files. Command line arguments for same.
2. Improve ``SELECT`` statement to allow column names and expressions in the column list where previously only ``SELECT *`` was allowed.

LibSQL+SQLServer+sql: Incremental improvements

---

Userland/Games/2048/Game.cpp
Userland/Games/2048/Game.h
Userland/Games/2048/main.cpp

Before game finish when a player has reached target tile,
Now player will be able to decide if he wants to continue or not.

2048: Let user decide if he wants to continue the game

---

Userland/Libraries/LibMarkdown/BlockQuote.cpp
Userland/Libraries/LibMarkdown/BlockQuote.h
Userland/Libraries/LibMarkdown/CMakeLists.txt
Userland/Libraries/LibMarkdown/ContainerBlock.cpp
Userland/Libraries/LibMarkdown/LineIterator.cpp
Userland/Libraries/LibMarkdown/LineIterator.h
Userland/Libraries/LibMarkdown/List.cpp

that is all.
TestCommonmark: 253/652 -> 271/652

LibMarkdown: Add Blockquotes

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp

Not much to say, this adds a checkbox to also show dotfiles in the project's tree view

HackStudio: Add 'Show Dotfiles' option

---

Userland/Libraries/LibJS/Runtime/BigInt.h
Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getNextTransition.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getPossibleInstantsFor.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getPreviousTransition.js

Ticks three checkboxes in #8982.

LibJS: Implement Temporal.TimeZone.prototype.get{PossibleInstantsFor,NextTransition,PreviousTransition}()

---

Userland/Applications/Spreadsheet/HelpWindow.cpp

Spreadsheet: Make the 'Help' window accessory

---

Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.h
Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/IteratorPrototype.h
Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
Userland/Libraries/LibJS/Runtime/ObjectConstructor.h
Userland/Libraries/LibJS/Runtime/ObjectPrototype.cpp
Userland/Libraries/LibJS/Runtime/ObjectPrototype.h
Userland/Utilities/js.cpp

I think these are the last usages of `JS_DECLARE/DEFINE_OLD_NATIVE_FUNCTION` in LibJS

LibJS: A few more ThrowCompletionOr conversions

---

Userland/Applications/Calculator/KeypadValue.cpp

Calculator: Improve KeypadValue conversion to handle integer values

---

Userland/Applications/Calculator/main.cpp

Thought it would be cool to add some useful constants to the calculator.

Calculator: Add Constants menu

---

Userland/Applications/SpaceAnalyzer/main.cpp

I was playing around with this app and the delay on startup for the initial scan before the window is opened bugged me. This patch opens a popup window to display the scan's progress whenever an analysis is triggered, including on startup. It counts each file scanned and at every multiple of `FILES_ENCOUNTERED_UPDATE_STEP_SIZE` it updates a label displaying the number of files encountered.

SpaceAnalyzer: Display scan progress with popup window during analysis

---

Userland/Utilities/less.cpp

Before this patch less would query the terminal geometry only at
startup and use this information to render the file when
appropriate. If the terminal is resized then the output is broken in
several different ways because of this.
This patch adds a SIGWINCH signal handler receive notification any
time the terminal is resized. This signal handler just sets a flag to
notify the main loop that a resize has occurred.
The main loop of the program just calls get_key_sequence() to get
input from the user, interpreting keystrokes as commands like scroll
up or down. The get_key_sequence() function has been changed to return
Optional<String>, so it either returns a keystroke from the user or it
returns nothing as an empty Optional.
While the user is not pressing any keys on the keyboard, the …

Userland: Handle terminal window resizing in less(1)

---

Userland/Services/FileOperation/main.cpp

For file copying, when there is a file with the same name in the destination directory, the file will be automatically renamed to "file-2.txt", for example. This change expands that special-case handling to file moving.

FileOperation: Deduplicate file names on move

---

AK/BumpAllocator.h

Fixes #10578.
I also implemented setting the pages to volatile while they're in the cache. However, this increases the running time of the `alternative_match_groups_benchmark` from about 2.1 seconds to "I got tired of waiting after several minutes". So I didn't make it part of this commit :D

AK: Make BumpAllocator work in multi-threaded environments

---

Kernel/Process.cpp

Dumping perfcore would always fail with EEXIST. This regressed in #10707 because of an incorrect indentation in the for loop.

Kernel: Do not try opening the same file when dumping perfcore

---

Ports/ffmpeg/package.sh

This makes ffmpeg build again!

Ports: Fix typo in ffmpeg dependencies

---

Ports/angband/package.sh
Ports/angband/patches/disable-accelerated-rendering.patch
Ports/angband/patches/use-sdl2-config.patch

This was split out of the original PR and on hold until the SDL prefix issues got sorted out.

Ports: Enable SDL support in Angband

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getInstantFor.js

LibJS: Implement Temporal.TimeZone.prototype.getInstantFor()

---

Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.add.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.subtract.js

Ticks off two checkboxes in #8982.

LibJS: Implement Temporal.PlainTime.prototype.{add,subtract}()

---

Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.dateAdd.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.add.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.subtract.js

Ticks two checkboxes in #8982.

LibJS: Implement Temporal.PlainDateTime.prototype.{add,subtract}()

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator.cpp

This is the last usage of old-style exceptions in the WrapperGenerator.

LibWeb: Convert is_named_property_exposed_on_object to ThrowCompletions

---

Kernel/Firmware/BIOS.cpp
Kernel/Firmware/BIOS.h
Kernel/GlobalProcessExposed.cpp
Kernel/Syscalls/ttyname.cpp
Kernel/TTY/MasterPTY.cpp
Kernel/TTY/MasterPTY.h
Kernel/TTY/SlavePTY.cpp
Kernel/TTY/SlavePTY.h
Kernel/TTY/TTY.cpp
Kernel/TTY/TTY.h
Kernel/TTY/VirtualConsole.cpp
Kernel/TTY/VirtualConsole.h

Kernel: Replace more usage of AK::String with Kernel::KString or AK::StringView

---

Meta/Lagom/Tools/ConfigureComponents/main.cpp

Found while working on #10748, but it's so off-topic that I want to put it as a separate PR.

ConfigureComponents: Reduce duplicated code

---

Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.add.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.subtract.js

Ticks two checkboxes in #8982.

LibJS: Implement Temporal.PlainDate.prototype.{add,subtract}()

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.toZonedDateTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.toZonedDateTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.toZonedDateTime.js

Ticks three checkboxes in #8982.

LibJS: Implement Temporal.Plain{Date,DateTime,Time}.prototype.toZonedDateTime()

---

Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.round.js

LibJS: Implement Temporal.PlainTime.prototype.round

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.hoursInDay.js

Ticks off one checkbox in #8982.

LibJS: Implement Temporal.ZonedDateTime.prototype.hoursInDay

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.startOfDay.js

Ticks off one checkbox in #8982.

LibJS: Implement Temporal.ZonedDateTime.prototype.startOfDay

---

Base/etc/LookupServer.ini
Base/etc/SystemServer.ini
Base/etc/WindowServer.ini
Base/home/anon/.config/FileManager.ini
Base/home/anon/.config/PixelPaint.ini
Base/home/anon/.config/SystemServer.ini
Base/home/anon/.config/TextEditor.ini
Userland/Libraries/LibCore/ConfigFile.cpp

Fixes #10640.
And yes, this time I tested it more, and compared the behavior to the behavior without this commit, although of course I can't easily check every single service that we run. :^)

Base+LibCore: Store booleans in human-readable format

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withCalendar.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withPlainDate.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withPlainTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withTimeZone.js

Ticks off four checkboxes in #8982.

LibJS: Implement Temporal.ZonedDateTime.prototype.with{PlainTime,PlainDate,TimeZone,Calendar}

---

Documentation/CodingStyle.md

Recently I wanted to link to a section like this, and found that it was missing.
So let's add it :^)

Documentation: Recommend a comment style

---

Documentation/VSCodeConfiguration.md

With these you'll only need 3 tasks to cover lagom and all of normal
build and launch with just 3 Tasks and two option menus.
@kleinesfilmroellchen

Documentation: Update and simplify VSCode Task recommendation

---

Userland/Applications/TextEditor/MainWidget.cpp

TextEditor: Fix hang on "Replace All"

---

Userland/DevTools/UserspaceEmulator/SoftCPU.h
Userland/DevTools/UserspaceEmulator/SoftFPU.cpp
Userland/DevTools/UserspaceEmulator/SoftFPU.h

A few oddities found after the recent FPU merge

UserspaceEmulator: FPU fixes

---

Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.with.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.with.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.with.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.with.js

Ticks four checkboxes in #8982.

LibJS: Implement Temporal.Plain{Date,DateTime,YearMonth,MonthDay}.prototype.with()

---

Userland/DevTools/UserspaceEmulator/Emulator.h
Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp

UserspaceEmulator: Add support for SC_uname and SC_sysconf syscalls

---

Userland/Utilities/pape.cpp

This changes adds an option to pape to switch the wallpaper to a random wallpaper which is not the currently selected one.

pape: add set-random option

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toJSON.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toLocaleString.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toString.js

Ticks off three checkboxes in #8982.

LibJS: Implement Temporal.ZonedDateTime stringifiers

---

Userland/Utilities/tar.cpp

This appears to be expected of tar extraction utilities, even if no directory entry is present in the file.
As an example, `binutils-2.37.tar.gz` will fail to extract otherwise due to multiple missing parent directories.

Utilities: tar: Always create parent directory when extracting

---

Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Runtime/Completion.cpp
Userland/Libraries/LibJS/Tests/syntax/async-await.js

Found 2 small issues while scrolling through the 3000 new :boom:s

LibJS: A couple of tiny async/await fixes

---

Userland/Utilities/cut.cpp

This PR also includes a bit of utility-internal refactoring, which made implementing these (and presumably other) options easier.

Utilities: cut: Implement field-based cutting

---

Base/usr/share/man/man7/Mitigations.md

Depends on #10821, hence the FIXME link.

Base: Document readonly atexit mitigation

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.compare.js

Ticks off one checkbox in #8982.

LibJS: Implement Temporal.Duration.compare

---

Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.add.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.subtract.js

Ticks off two checkboxes in #8982.

LibJS: Implement Temporal.ZonedDateTime.prototype.{add,subtract}

---

Meta/serenity_gdb.py
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.h
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/FunctionKind.h
Userland/Libraries/LibJS/Runtime/GeneratorFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
Userland/Libraries/LibJS/Runtime/GeneratorObject.h
Userland/Libraries/LibJS/Runtime/GeneratorObjectPrototype.cpp
Userland/Libraries/LibJS/Runtime/Promise.h
Userland/Libraries/LibTest/JavaScriptTestRunner.h
Userland/Utilities/js.cpp

I'm gonna call this good for now
Pretty sure it's got quite a few bugs, and some bits are still left unimplemented, but as it is, this _seems_ to be fixing around 3000 test262 tests (in bc mode obv)
changes from master: [diff.txt](https://github.com/SerenityOS/serenity/files/7521579/diff.txt)

LibJS: Async functions in bytecode

---

Userland/Utilities/tr.cpp

This is needed by some configure scripts.

Utilities/tr: Implement squeezing repeated characters

---

Userland/Utilities/grep.cpp

This is also needed by some configure scripts.

Utilities/grep: Implement line-counting mode

---

Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.with.js

LibJS: Implement Temporal.ZonedDateTime.prototype.with()

---

Userland/Utilities/grep.cpp

"Needed by some configure scripts" number three.
No changes to the manpages required (according to the regeneration script).

Utilities/grep: Implement using multiple patterns

---

Userland/Applications/Piano/Track.cpp
Userland/Libraries/LibAudio/ClientConnection.cpp
Userland/Libraries/LibAudio/FlacLoader.cpp
Userland/Libraries/LibAudio/FlacLoader.h
Userland/Libraries/LibAudio/Loader.h
Userland/Libraries/LibAudio/Sample.h
Userland/Libraries/LibAudio/WavLoader.h
Userland/Libraries/LibAudio/WavWriter.cpp
Userland/Libraries/LibAudio/WavWriter.h
Userland/Libraries/LibDSP/Music.h
Userland/Libraries/LibDSP/Track.h
Userland/Services/AudioServer/Mixer.cpp

This fixes all current code smells, bugs and issues reported by SonarCloud static analysis in the audio code. Other issues are almost exclusively false positives. This makes much code clearer, and some minor benefits in performance or bug evasion may be gained.
The second commit is some explanatory commentary for things I noticed were undocumented while going through the code smells.

Audio: Fix code smells and issues found by static analysis

---

Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp

LibJS: Use modulo() function in to_iso_day_of_week

---

AK/StringView.h
Userland/DevTools/Profiler/DisassemblyModel.cpp

Fixes some issues found while hunting #10628.

Profiler: Fix some disassembly bugs

---

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeNumberFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.h
Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.format.js
Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.formatToParts.js
Userland/Libraries/LibUnicode/Locale.h

Summary: Locales are weird man

LibJS: Implement compact formatting for Intl.NumberFormat

---

Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.since.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.until.js

Ticks off two checkboxes in #8982.

LibJS: Implement Temporal.PlainDate.prototype.{until,since}

---

Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp

This is an editorial change in the Temporal spec.
See: https://github.com/tc39/proposal-temporal/commit/3dd2397

LibJS: Use else-if's in Temporal.Duration.prototype.until

---

Userland/Libraries/LibHTTP/Job.cpp
Userland/Libraries/LibHTTP/Job.h
Userland/Libraries/LibWeb/Loader/FrameLoader.cpp

LibWeb+LibHTTP: Support multiple Set-Cookie response headers

---

Userland/Libraries/LibCore/LocalSocket.cpp

This fixes the build on FreeBSD by chagning `LOCAL_PEERPID` to `LOCAL_PEERCRED` inside a `#ifdef`
Note: to actually fix the build #10860 also has to be merged

LibCore: Fix `LocalSocket.cpp` build on FreeBSD

---

Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toZonedDateTimeISO.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.since.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.toZonedDateTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.until.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withCalendar.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withPlainDate.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withPlainTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.withTimeZone.js

I'm very bad at writing parsers, and it probably shows. I do like the public API I came up with however, ~~and given that it only relies on the `parse_*` function names internally, I'm sure incremental improvements or a full rewrite is possible if needed~~ Ali helped me making it nicer :^)
TL;DR:
```
Summary:
Diff Tests:
+305 ✅   +162 ❌   +0 ⚠️   +0 📄   +0 ⚙️   +0 💀    -32 💥️   +0 🐍    -435 📝
```

LibJS: Start implementing an ISO 8601 parser for Temporal

---

Userland/Applications/CrashReporter/main.cpp

This is useful when messing with memory allocation issues. :^)

CrashReporter: Show the available memory region information

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionConstructor.h
Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionPrototype.cpp
Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionPrototype.h
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/FunctionKind.h
Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Tests/syntax/async-await.js
Userland/Libraries/LibJS/Tests/syntax/async-generators.js

I wanted to implement async generator execution in bytecode but I still have to add a bunch of objects and prototypes so I wanted to start with this.
~Draft since I'm still checking some things
Also I need to add tests for async generator but since we can't execute them yet I'll have to do parse only tests for the time being.~ Done.

LibJS: Async arrow function and async generator parsing

---

AK/MemMem.h

Avoid including a per-translation unit copy of all these functions.
Also, drive-by two clang-tidy fixes for readability-qualified-auto and
readability-implicit-bool-conversion.

AK: Mark MemMem header-only functions as inline rather than static

---

Userland/Applications/3DFileViewer/CMakeLists.txt
Userland/Applications/3DFileViewer/main.cpp

Simplified one pledge() and five unveil() by using TRY().

3DFileViewer: Port to LibMain

---

Userland/Demos/Starfield/CMakeLists.txt
Userland/Demos/Starfield/Starfield.cpp

Simplified two pledge() by using TRY().

Starfield: Port to LibMain

---

Userland/Games/Minesweeper/CMakeLists.txt
Userland/Games/Minesweeper/main.cpp

Simplified two unveil() and two pledge() by using TRY().

Minesweeper: Port to LibMain

---

Userland/Applications/Piano/KeysWidget.cpp
Userland/Applications/Piano/KnobsWidget.cpp
Userland/Applications/Piano/KnobsWidget.h
Userland/Applications/Piano/MainWidget.cpp
Userland/Applications/Piano/Music.h
Userland/Applications/Piano/RollWidget.h
Userland/Applications/Piano/SamplerWidget.cpp
Userland/Applications/Piano/Track.cpp
Userland/Applications/Piano/Track.h
Userland/Applications/Piano/TrackManager.cpp
Userland/Applications/Piano/TrackManager.h
Userland/Applications/Piano/WaveWidget.cpp
Userland/Libraries/LibDSP/CMakeLists.txt
Userland/Libraries/LibDSP/Envelope.h
Userland/Libraries/LibDSP/Music.h
Userland/Libraries/LibDSP/ProcessorParameter.h
Userland/Libraries/LibDSP/Synthesizers.cpp
Userland/Libraries/LibDSP/Synthesizers.h

The last step of picking apart #10167.
This is a draft for now (doesn't compile), because it depends on other PRs. I'll update it accordingly when the other stuff is merged.

LibDSP+Piano: Replace Piano's synthesizer with a new LibDSP synthesizer "Classic"

---

Userland/Games/Breakout/CMakeLists.txt
Userland/Games/Breakout/main.cpp

Breakout: Port to LibMain

---

Userland/Games/2048/CMakeLists.txt
Userland/Games/2048/main.cpp

2048: Port to LibMain

---

Userland/Games/Chess/CMakeLists.txt
Userland/Games/Chess/main.cpp

Simplified two pledge() and five unveil() by using TRY().

Chess: Port to LibMain

---

Userland/Applications/Mail/CMakeLists.txt
Userland/Applications/Mail/main.cpp
Userland/Applications/PDFViewer/CMakeLists.txt
Userland/Applications/PDFViewer/main.cpp
Userland/Applications/Piano/CMakeLists.txt
Userland/Applications/Piano/main.cpp
Userland/Applications/PixelPaint/CMakeLists.txt
Userland/Applications/PixelPaint/main.cpp

Quick and easy ports of the programs Mail, PDFViewer, Piano and PixelPaint to use LibMain.

Mail+PDFViewer+Piano+PixelPaint: Port to LibMain

---

Userland/Games/FlappyBug/CMakeLists.txt
Userland/Games/FlappyBug/main.cpp

FlappyBug: Port to LibMain

---

Userland/Games/Spider/CMakeLists.txt
Userland/Games/Spider/main.cpp

Simplified two pledge() and two unveil() by using TRY()

Spider: Port to LibMain

---

Userland/Games/FlappyBug/main.cpp
Userland/Games/Spider/main.cpp

Update code to use Main:Arguments directly.

FlappyBug+Spider: Update GUI:Application::construct usage

---

Userland/Libraries/LibGUI/AutocompleteProvider.cpp

LibGUI: Support applying AutocompleteBox suggestions with mouse

---

Userland/Games/Hearts/CMakeLists.txt
Userland/Games/Hearts/main.cpp

Simplified one pledge() and two unveil() by using TRY().

Hearts: Port to LibMain

---

Userland/Games/Snake/CMakeLists.txt
Userland/Games/Snake/main.cpp

Snake: Port to LibMain

---

Userland/Games/Solitaire/CMakeLists.txt
Userland/Games/Solitaire/main.cpp

Solitaire: Port to LibMain

---

Userland/Games/GameOfLife/CMakeLists.txt
Userland/Games/GameOfLife/main.cpp

GameOfLife: Port to LibMain

---

Userland/Games/Pong/CMakeLists.txt
Userland/Games/Pong/main.cpp

Pong: Port to LibMain

---

Meta/CMake/unicode_data.cmake
Meta/Lagom/CMakeLists.txt
Meta/Lagom/Tools/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibUnicode/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeLocale.cpp
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeNumberFormat.cpp
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GeneratorUtil.h
Userland/Libraries/LibCore/DirIterator.cpp
Userland/Libraries/LibCore/DirIterator.h

Knocks off several calls to `release_value_but_fixme_should_propagate_errors`

LibUnicode+LibCore+Meta: Port Unicode generators to ErrorOr and LibMain

---

Userland/Games/FlappyBug/Game.cpp
Userland/Games/FlappyBug/Game.h

This change allows to play the game using the mouse.

FlappyBug: Support mouse clicks for flapping

---

Userland/Demos/CatDog/CMakeLists.txt
Userland/Demos/CatDog/main.cpp
Userland/Demos/Cube/CMakeLists.txt
Userland/Demos/Cube/Cube.cpp
Userland/Demos/Eyes/CMakeLists.txt
Userland/Demos/Eyes/main.cpp
Userland/Demos/Fire/CMakeLists.txt
Userland/Demos/Fire/Fire.cpp
Userland/Demos/LibGfxDemo/CMakeLists.txt
Userland/Demos/LibGfxDemo/main.cpp
Userland/Demos/LibGfxScaleDemo/CMakeLists.txt
Userland/Demos/LibGfxScaleDemo/main.cpp
Userland/Demos/Mandelbrot/CMakeLists.txt
Userland/Demos/Mandelbrot/Mandelbrot.cpp
Userland/Demos/ModelGallery/CMakeLists.txt
Userland/Demos/ModelGallery/GalleryWidget.cpp
Userland/Demos/ModelGallery/GalleryWidget.h
Userland/Demos/ModelGallery/main.cpp
Userland/Demos/Mouse/CMakeLists.txt
Userland/Demos/Mouse/main.cpp
Userland/Demos/Screensaver/CMakeLists.txt
Userland/Demos/Screensaver/Screensaver.cpp
Userland/Demos/Starfield/Starfield.cpp
Userland/Demos/WidgetGallery/DemoWizardDialog.cpp
Userland/Demos/WidgetGallery/GalleryWidget.cpp
Userland/Demos/WidgetGallery/main.cpp

Updated all remaining demos to support new LibMain features:
- changed `main` to `serenity_main`
- passing one arguments object if necessary
- made use of TRY with pledge and unveil 
I decided to squash those changes into one PR to not stress pipelines too much.

Demos: Use ErrorOr<T> syntax

---

Tests/LibCore/TestLibCoreArgsParser.cpp

Since we no longer populate a `Vector<String>` the lifetime of the strings
in all of these tests is now messed up, as the `Vector<StringView>` now
points to free'd memory.
We attempt to fix this for the unit tests, by saving the results in a
RAII type that should live as long as the test wants to validate some
output of the ArgParser.

Tests: Fix TestLibCoreArgsParser with add_positional_argument API change

---

Userland/Games/2048/main.cpp
Userland/Games/Breakout/main.cpp
Userland/Games/Chess/main.cpp
Userland/Games/FlappyBug/main.cpp
Userland/Games/GameOfLife/main.cpp
Userland/Games/Hearts/main.cpp
Userland/Games/Minesweeper/main.cpp
Userland/Games/Pong/main.cpp
Userland/Games/Snake/main.cpp
Userland/Games/Solitaire/main.cpp
Userland/Games/Spider/main.cpp

These changes make use of TRY() in all of the SerenityOS games.

Games: TRY() all the things in serenity_main() :^)

---

Kernel/Storage/StorageDevice.h
Kernel/Storage/StorageManagement.cpp

We had such functionality in the past, but it was regressed and now is
restored.

Kernel/Storage: Restore booting from MBR partitions functionality

---

Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.compare.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.add.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.subtract.js

```
Summary:
Diff Tests:
+39 ✅   +3 ❌   +0 ⚠️   +0 📄   +0 ⚙️   +0 💀   +0 💥️   +0 🐍    -42 📝 
```

LibJS: Implement parsing of TemporalDurationString

---

Base/res/html/misc/async-js.html
Base/res/html/misc/welcome.html
Userland/Libraries/LibJS/Runtime/Completion.cpp

Now it runs the (provided) test correctly.
Test262 reports no regression.

LibJS: Spin the event loop while waiting for async completion in `await`

---

Kernel/Debug.h.in
Kernel/Devices/Audio/AC97.cpp
Meta/CMake/all_the_debug_macros.cmake

Kernel: Fix AC'97 compatibility with multiscreen setup

---

Userland/Applications/Magnifier/CMakeLists.txt
Userland/Applications/Magnifier/main.cpp
Userland/Applications/ThemeEditor/CMakeLists.txt
Userland/Applications/ThemeEditor/main.cpp

Use LibMain and TRY construct in Magnifier and ThemeEditor.

Applications: Use LibMain in Magnifier & ThemeEditor

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIterator.cpp
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIterator.h
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.h
Userland/Libraries/LibJS/Runtime/AsyncIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/AsyncIteratorPrototype.h
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.h
Userland/Libraries/LibJS/Runtime/IteratorOperations.cpp
Userland/Libraries/LibJS/Runtime/IteratorOperations.h
Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
Userland/Libraries/LibJS/Runtime/PromiseReaction.h
Userland/Libraries/LibJS/Tests/loops/for-await-of.js

Since master has a broken Await AO this wont pass as many test as when #10933 is merged.
(Although that PR still isn't following the spec exactly I don't think we can actually do it as the spec says.)

LibJS: for-await-of

---

Kernel/Arch/x86/common/Interrupts.cpp
Kernel/Bus/PCI/SysFSPCI.cpp
Kernel/Devices/Device.cpp
Kernel/Devices/KCOVInstance.cpp
Kernel/FileSystem/FIFO.cpp
Kernel/FileSystem/InodeWatcher.cpp
Kernel/GlobalProcessExposed.cpp
Kernel/Heap/SlabAllocator.cpp
Kernel/Heap/SlabAllocator.h
Kernel/KString.cpp
Kernel/KString.h
Kernel/Process.cpp
Kernel/Process.h

More progress on OOM hardening (#6369)

Kernel: Add an error propagating KString::format(..) API, and start using it 

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Lexer.cpp
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Tests/classes/class-private-fields.js
Userland/Libraries/LibJS/Tests/classes/class-public-fields.js
Userland/Libraries/LibJS/Tests/object-basic.js
Userland/Libraries/LibJS/Tests/string-escapes.js
Userland/Libraries/LibJS/Tests/syntax/async-await.js
Userland/Libraries/LibJS/Tests/syntax/destructuring-assignment.js
Userland/Libraries/LibJS/Tests/syntax/generators.js
Userland/Libraries/LibJS/Tests/syntax/numeric-separator.js
Userland/Libraries/LibJS/Tests/syntax/slash-after-block.js
Userland/Libraries/LibJS/Tests/test-common.js
Userland/Libraries/LibJS/Token.cpp

Fixes #11078 
And much more
~Note this is incompatible with #11041 as is because I renamed a variable so one will need to be fixed up.~ Already merged

LibJS: A bunch of parser fixes

---

Documentation/Patterns.md

We have some new patterns, so lets document them for future contributors.

Documentation: Document the new TRY/MUST and serenity_main patterns :^)

---

Userland/Applications/SoundPlayer/CMakeLists.txt
Userland/Applications/SoundPlayer/main.cpp

Use LibMain and TRY in SoundPlayer. (:

SoundPlayer: Port to LibMain

---

Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp

Specifically these three commits:
- https://github.com/tc39/proposal-temporal/commit/516bf2442a0d344abbb4849e8f333bcfed952c9b
- https://github.com/tc39/proposal-temporal/commit/1f7e486c36ce0d59704b3f91e1c9fb42095ad52d
- https://github.com/tc39/proposal-temporal/commit/7207a1cd3e7ee1dba891c9310dde5cef7a39b5f2

LibJS: Reflect recent editorial changes in the Temporal spec

---

Userland/DevTools/Inspector/RemoteObjectGraphModel.h
Userland/DevTools/Inspector/RemoteProcess.h

Inspector: Remove unused includes

---

Userland/Applications/Mail/MailWidget.cpp
Userland/Applications/Mail/main.cpp

If there are no mail server configured, then the application will ask the
user, if they want to see the help man page.

Mail: Ask the user if they want to see the help man page

---

Kernel/KSyms.cpp

- dump_backtrace was using ebp instead of rbp on x86_64, only using the
lower 32-bits of rbp.
- The symbol loader was only fetching half of the pointer from the
symbol table. (8 chars instead of 16 chars)

Kernel: Fix backtrace dumping on x86_64

---

Userland/Shell/AST.cpp

This would show up when resolving aliases, when an alias contains a
sequence.
Fixes #11219.

Shell: Make the Join operation respect nodes that have a next chain

---

Documentation/Patterns.md

Hello friends!
I was browsing the patterns documentation and noticed this typo. Hoping to make code contributions in the future, but we all start somewhere. :^)

Documentation: Fix spelling error

---

Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp

Something about "the proper APIs" :laughing:

LibWeb: Use ByteBuffer::copy() instead of a manual copy in SubtleCrypto

---

Base/usr/share/man/man1/rm.md

Base: Add rm(1) manpage

---

Base/usr/share/man/man1/reboot.md
Base/usr/share/man/man1/shutdown.md

Add manual page for shutdown(1) and reboot(1).
Related to #11311.

Base: Add manual pages for two power management utilites

---

Userland/Libraries/LibGL/Tex/Sampler2D.cpp

Previously we multiplied the interpolated texture coordinates by
width - 1 and height - 1 instead of width and height which resulted in
some wrongly mapped textures, especially visible in the glquake light
maps.
This also corrects the wrap mode being wrongly swapped for s/t
coordinates.
The wrap mode calculation for mirrored wrap and clamp needed to be
adjusted to always return values < 1.0f to make sure we are not sampling
out of bounds.
Before:
After:

LibGL: Fix texture sampling texel coordinate calculation

---

Base/usr/share/man/man1/abench.md

Base: Add documentation for abench

---

Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.@@iterator.js

Test262 diff:
```
Summary:
Diff Tests:
+28 ✅    -28 ❌   +0 ⚠️   +0 📄   +0 ⚙️   +0 💀   +0 💥️   +0 🐍   +0 📝   
Diff Tests:
test/built-ins/ArrayIteratorPrototype/next/Uint8Array.js        ❌ -> ✅
test/language/statements/for-of/float32array.js                 ❌ -> ✅
test/language/statements/for-of/int8array-mutate.js             ❌ -> ✅
test/language/statements/for-of/float64array.js                 ❌ -> ✅
test/built-ins/ArrayIteratorPrototype/next/Uint8ClampedArray.js ❌ -> ✅
test/language/statements/for-of/float64array-mutate.js          ❌ -> ✅
test/language/statements/for-of/int8array.js                    ❌ -> ✅
test/language/statements/for-of/uint16array.js                  ❌ -> ✅
test/language/statements/for-of/uint16array-mutate.js           ❌ -> ✅ …
```

LibJS: Add TypedArray.prototype.@@iterator

---

Kernel/FileSystem/Ext2FileSystem.h
Kernel/Interrupts/SpuriousInterruptHandler.h
Kernel/Memory/PhysicalRegion.cpp
Kernel/Memory/PhysicalRegion.h
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp

All of these were found by PVS Studio.

IPCCompiler+Kernel: Small collection of uninitialized member variable fixes

---

Userland/Games/FlappyBug/Game.cpp
Userland/Games/FlappyBug/Game.h
Userland/Games/FlappyBug/main.cpp

Feedback is highly appreciated. I'm not sure whether `Bug` should become a class now (it's still basically a struct *except* for the fact that you should use `construct` to construct it - should I just make the constructor private?). I'm also not sure whether `construct` is the proper name for it.

FlappyBug: Propagate errors

---

Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl

https://html.spec.whatwg.org/multipage/canvas.html#the-canvas-state

LibWeb: Implement canvas state

---

Userland/DevTools/HackStudio/Dialogs/NewProjectDialog.cpp

Previously, if the parent directory didn't exist when making a project, it would say that the creation directory was 'invalid' which isn't necessarily true.
This pull request will prompt the user, asking if they would like to create the parent directory when creating a project, instead of treating it as an 'invalid' directory.

HackStudio: Ask to create a non-existent directory when creating a project 

---

Documentation/BareMetalInstallation.md

This should help others to not run into the same roadblocks with bare-metal that I ran into.

Documentation: Elaborate on GRUB image flashing and video-less debugging

---

Base/usr/share/man/man1/cut.md
Base/usr/share/man/man1/diff.md
Base/usr/share/man/man1/head.md
Base/usr/share/man/man1/rmdir.md

First batch of manpages. Missing manpages found in issue #11311.

Base: Add manpages for cut, diff, head & rmdir command line utilities

---

Kernel/Arch/x86/common/Processor.cpp

Kernel: Fix incorrect SFMASK MSR value clobbering reserved bits

---

Ports/tuxracer/patches/source.patch
Userland/Libraries/LibGL/GLContext.h
Userland/Libraries/LibGL/SoftwareGLContext.cpp
Userland/Libraries/LibGL/SoftwareGLContext.h
Userland/Libraries/LibGfx/Matrix.h
Userland/Libraries/LibGfx/Matrix3x3.h
Userland/Libraries/LibSoftGPU/Clipper.cpp
Userland/Libraries/LibSoftGPU/Device.cpp
Userland/Libraries/LibSoftGPU/Device.h
Userland/Libraries/LibSoftGPU/Enums.h
Userland/Libraries/LibSoftGPU/ImageFormat.h
Userland/Libraries/LibSoftGPU/Vertex.h

Lots of fixes, spec conformance improvements and new functionality. Tux Racer before:
Tux Racer after:

LibGL+LibSoftGPU: Implement further support for Tux Racer

---

Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl

LibWeb: Implement Element.getAttributeNames

---

Userland/Utilities/arp.cpp
Userland/Utilities/ifconfig.cpp
Userland/Utilities/lsirq.cpp
Userland/Utilities/lsof.cpp
Userland/Utilities/lsusb.cpp
Userland/Utilities/mount.cpp
Userland/Utilities/netstat.cpp
Userland/Utilities/notify.cpp

This is part of my crusade against `release_value_but_fixme_should_propagate_errors()`.

Utilities: Propagate errors

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h

The `to_reference()` change touches AST a lot so maybe this should be combined to not cause too many conflicts?

LibJS: Convert resolve_this_binding and to_reference to ThrowCompletionOr

---

Userland/Applications/VideoPlayer/CMakeLists.txt
Userland/Applications/VideoPlayer/main.cpp

VideoPlayer isn't exactly the most functional at the moment, but that doesn't mean that we shouldn't show it some of the LibMain love! :^)

VideoPlayer: Port VideoPlayer to LibMain

---

Userland/Applications/DisplaySettings/MonitorSettingsWidget.cpp

This isn't really the correct way to do this, but I couldn't resist while working on the taskbar 😅

DisplaySettings: Add 1440p ultrawide resolution

---

Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp

Although these are normative changes, our implementation wasn't really affected.

LibJS: Normative updates to Intl.NumberFormat

---

Kernel/Storage/StorageManagement.cpp

Since NVME devices end with a digit that indicates the node index we
cannot simply append a partition index. Instead, there will be a "p"
character as separator, e.g. /dev/nvme0n1p3 for the 3rd partition.
So, if the early device name ends in a digit we need to add this
separater before matching for the partition index.
If the partition index is omitted (as is the default) the root file
system is on a disk without any partition table (e.g. using QEMU).
This enables booting from the correct partition on an NVMe drive by
setting the command line variable root to e.g. root=/dev/nvme0n1p1

Kernel: Allow specifying partition index with NVMe devices

---

Kernel/Storage/StorageManagement.cpp

Previously we were enumerating multiple times for each storage type.
We can easily enumerate once instead.

Kernel: Enumerate PCI devices a single time in StorageManagement

---

Userland/Applets/Audio/main.cpp
Userland/Applets/Network/main.cpp
Userland/Applets/ResourceGraph/main.cpp

This is part of my crusade against `release_value_but_fixme_should_propagate_errors()`.

Applets: Propagate errors

---

Userland/Applications/Spreadsheet/SpreadsheetModel.cpp
Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Interpreter.cpp
Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/ArrayBufferConstructor.cpp
Userland/Libraries/LibJS/Runtime/AsyncFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/Completion.h
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/IteratorOperations.cpp
Userland/Libraries/LibJS/Runtime/MapConstructor.cpp
Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
Userland/Libraries/LibJS/Runtime/Promise.cpp
Userland/Libraries/LibJS/Runtime/PromiseJobs.cpp
Userland/Libraries/LibJS/Runtime/PromiseReaction.h
Userland/Libraries/LibJS/Runtime/SetConstructor.cpp
Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
Userland/Libraries/LibJS/Runtime/TypedArray.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/WeakMapConstructor.cpp
Userland/Libraries/LibJS/Runtime/WeakSetConstructor.cpp
Userland/Libraries/LibWeb/WebAssembly/WebAssemblyObject.cpp
Userland/Utilities/js.cpp

WIP. test-js is green, ~~haven't looked at test262 results yet at all~~.
---
libjs-test262 PR: https://github.com/linusg/libjs-test262/pull/48

LibJS: Update AST to use completions :^)

---

Kernel/FileSystem/Ext2FileSystem.cpp

This function was duplicated with ceil_div in AK.

Kernel: Replace divide_rounded_up uses with ceil_div in Ext2FileSystem

---

Kernel/Arch/x86/DescriptorTable.h
Kernel/Arch/x86/Processor.h
Kernel/Arch/x86/common/Processor.cpp
Kernel/Thread.h
Userland/Libraries/LibC/serenity.h

A couple of patches upstreamed from my WIP wine/LDT branch.

Kernel: Small tweaks and fixes

---

Kernel/API/KeyCode.h

This was not updated when the Menu button was added.

Kernel: Update key_code_count

---

Userland/Libraries/LibELF/DynamicLinker.cpp

The dynamic linker now supports having custom library paths
as specified by the user.

LibELF: Add `LD_LIBRARY_PATH` envvar support :^)

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Interpreter.cpp
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/IteratorOperations.cpp
Userland/Libraries/LibJS/Runtime/Promise.cpp
Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
Userland/Libraries/LibJS/Runtime/PromiseJobs.cpp
Userland/Libraries/LibJS/Runtime/PromiseReaction.h
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/Tests/labels.js
Userland/Libraries/LibWeb/WebAssembly/WebAssemblyObject.cpp
Userland/Utilities/js.cpp

Very much WIP. ~~Probably relies on everything *outside* of LibJS using throw completions instead of *just* throwing an exception, as that will no longer trigger any unwinding - that will be a separate PR though.~~ Current situation is actually quite good already!

LibJS: Replace the custom unwind mechanism with completions :^)

---

Userland/Utilities/du.cpp

For each directory, we now go through each file and sum-up the contents.
Fixes #4228

du: Display true size of directory instead of 4 KiB

---

Userland/Libraries/LibGUI/AboutDialog.cpp

LibGUI: Update the AboutDialog copyright year :^)

---

Meta/Lagom/CMakeLists.txt
Tests/LibSQL/TestSqlExpressionParser.cpp
Tests/LibSQL/TestSqlStatementExecution.cpp
Userland/Libraries/LibSQL/AST/AST.h
Userland/Libraries/LibSQL/AST/Expression.cpp
Userland/Libraries/LibSQL/AST/Parser.cpp
Userland/Libraries/LibSQL/CMakeLists.txt

LibSQL: Implement LIKE SQL expressions

---

Meta/Lagom/Fuzzers/FuzzJs.cpp
Meta/Lagom/Fuzzers/FuzzilliJs.cpp
Userland/Applications/Assistant/Providers.cpp
Userland/Applications/Spreadsheet/Spreadsheet.cpp
Userland/DevTools/HackStudio/Debugger/EvaluateExpressionDialog.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Interpreter.cpp
Userland/Libraries/LibJS/Interpreter.h
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibTest/JavaScriptTestRunner.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp
Userland/Services/WebContent/ClientConnection.cpp
Userland/Services/WebContent/WebContentConsoleClient.cpp
Userland/Utilities/js.cpp

libjs-test262 PR: https://github.com/linusg/libjs-test262/pull/49

LibJS: Retire & remove VM::{set_,}last_value()

---

Kernel/Bus/PCI/Access.cpp
Kernel/Bus/PCI/Access.h
Kernel/Bus/PCI/Controller/HostBridge.cpp
Kernel/Bus/PCI/Controller/HostBridge.h
Kernel/Bus/PCI/Controller/HostController.h
Kernel/Bus/PCI/Controller/MemoryBackedHostBridge.cpp
Kernel/Bus/PCI/Controller/MemoryBackedHostBridge.h
Kernel/Bus/PCI/Definitions.h
Kernel/Bus/PCI/Initializer.cpp
Kernel/CMakeLists.txt

This is a preparation to solve #11594.

Kernel/PCI: Split host bridge code from the Access singleton

---

Meta/Lagom/CMakeLists.txt
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Shell/CMakeLists.txt
Userland/Shell/main.cpp

Shell port to LibMain.
I also added a wrapper for setsid() to enforce the `TRY()` pattern.

Shell: Port to LibMain

---

Userland/Applications/3DFileViewer/main.cpp
Userland/Applications/Calculator/main.cpp
Userland/Applications/FontEditor/main.cpp
Userland/Applications/KeyboardMapper/main.cpp
Userland/Applications/Mail/main.cpp
Userland/Applications/PDFViewer/main.cpp
Userland/Applications/Piano/main.cpp
Userland/Applications/PixelPaint/main.cpp
Userland/Applications/SystemMonitor/main.cpp
Userland/Applications/TextEditor/main.cpp
Userland/Applications/VideoPlayer/main.cpp
Userland/Applications/Welcome/main.cpp
Userland/DevTools/HackStudio/Editor.cpp
Userland/DevTools/HackStudio/Editor.h
Userland/DevTools/HackStudio/EditorWrapper.cpp
Userland/DevTools/HackStudio/main.cpp
Userland/DevTools/Inspector/main.cpp

Most of these changes should be fairly uncontroversial, except for the `SystemMonitor` and `HackStudio` changes.

Userland: Propagate errors using try_set_main_widget instead of set_main_widget

---

Userland/Shell/AST.cpp
Userland/Shell/Builtin.cpp
Userland/Shell/Shell.cpp
Userland/Shell/Shell.h

Shell: Fix `last_return_code` shenanigans / Add a ':' builtin

---

Base/usr/share/man/man1/uniq.md

Adds manual page for `uniq` command. See  #11311.

Base: Add uniq(1) manpage

---

Userland/Libraries/LibGL/SoftwareGLContext.cpp
Userland/Libraries/LibGL/SoftwareGLContext.h
Userland/Libraries/LibSoftGPU/Device.cpp
Userland/Libraries/LibSoftGPU/Device.h

LibGL and LibSoftGPU learn how to properly viewport, allowing us to play tiny quake!

LibGL+LibSoftGPU: Implement viewport support

---

Userland/Applications/Spreadsheet/ImportDialog.cpp
Userland/Applications/Spreadsheet/ImportDialog.h
Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Userland/Applications/Spreadsheet/Workbook.cpp
Userland/Applications/Spreadsheet/Workbook.h

Spreadsheet: Properly pass parent window to Workbook

---

AK/StringView.cpp
AK/StringView.h
Kernel/Arch/x86/Processor.h
Kernel/Arch/x86/ProcessorInfo.h
Kernel/Arch/x86/common/Processor.cpp
Kernel/Arch/x86/common/ProcessorInfo.cpp
Kernel/FileSystem/DevPtsFS.cpp
Kernel/GlobalProcessExposed.cpp

More work to chip away at #6369

AK+Kernel: More OOM hardening,  and removal of allocations with new StringView::for_each_split_view API

---

Kernel/Arch/x86/ProcessorInfo.h
Kernel/Arch/x86/common/ProcessorInfo.cpp
Kernel/Bus/USB/SysFSUSB.cpp
Kernel/CommandLine.cpp
Kernel/CommandLine.h
Kernel/Coredump.cpp
Kernel/FileSystem/Custody.cpp
Kernel/FileSystem/Custody.h
Kernel/FileSystem/Ext2FileSystem.cpp
Kernel/FileSystem/Inode.cpp
Kernel/FileSystem/Inode.h
Kernel/FileSystem/InodeWatcher.cpp
Kernel/FileSystem/InodeWatcher.h
Kernel/FileSystem/Mount.cpp
Kernel/FileSystem/Mount.h
Kernel/GlobalProcessExposed.cpp
Kernel/KBufferBuilder.h
Kernel/KString.h
Kernel/Net/IPv4SocketTuple.h
Kernel/PerformanceEventBuffer.cpp
Kernel/PerformanceEventBuffer.h
Kernel/PerformanceManager.h
Kernel/Process.cpp
Kernel/ProcessSpecificExposed.cpp
Kernel/Storage/NVMe/NVMeNameSpace.cpp
Kernel/Syscalls/execve.cpp
Kernel/Syscalls/hostname.cpp
Kernel/Thread.cpp
Kernel/Thread.h
Userland/Applications/SystemMonitor/main.cpp

This is based on @bgianfo's #11785 PR, so that one should be merged before this.
(related to #6369)

Kernel: Some more String-related OOM hardening

---

Kernel/Bus/VirtIO/Console.cpp
Kernel/Bus/VirtIO/ConsolePort.cpp
Kernel/CommandLine.h
Kernel/FileSystem/Ext2FileSystem.cpp
Kernel/GlobalProcessExposed.cpp
Kernel/Graphics/VirtIOGPU/FramebufferDevice.cpp
Kernel/KString.h
Kernel/Memory/RingBuffer.cpp
Kernel/Memory/RingBuffer.h
Kernel/Process.cpp
Kernel/Process.h
Kernel/Storage/StorageManagement.cpp
Kernel/Syscalls/execve.cpp
Kernel/Syscalls/hostname.cpp
Kernel/Syscalls/uname.cpp

Kernel: Even more String-related OOM hardening

---

README.md

Meta: Add Xexxa's name to the contributors list

---

Userland/Applications/SystemMonitor/main.cpp

This looks much nicer than the current cramped single-row solution.

SystemMonitor: Split multi-core CPU usage graphs into multiple rows

---

Tests/Kernel/TestMemoryDeviceMmap.cpp

Tests: Unmap memory ranges on /dev/mem after testing mmap(2)

---

Base/res/js/Spreadsheet/runtime.js

My statistics course has gotten to me :^)

Spreadsheet: Implement the mode function

---

Userland/Applications/Assistant/Providers.cpp
Userland/Applications/Assistant/Providers.h
Userland/Applications/Assistant/main.cpp

Assistant: Fix crash in FileProvider background thread upon exit

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Runtime/AsyncFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/FunctionConstructor.h
Userland/Libraries/LibJS/Runtime/FunctionKind.h
Userland/Libraries/LibJS/Runtime/GeneratorFunctionConstructor.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/Tests/builtins/Function/Function.js
Userland/Libraries/LibJS/Tests/parser-line-terminators.js
Userland/Libraries/LibWeb/DOM/EventTarget.cpp

```
Diff Tests:
test/built-ins/AsyncGeneratorFunction/instance-await-expr-in-param.js                             📝 -> ❌
test/built-ins/Function/prototype/toString/GeneratorFunction.js                                   💥️ -> ❌
test/built-ins/GeneratorFunction/has-instance.js                                                  💥️ -> ✅
test/built-ins/GeneratorFunction/instance-construct-throws.js                                     💥️ -> ✅
test/built-ins/GeneratorFunction/instance-length.js                                               💥️ -> ✅
test/built-ins/GeneratorFunction/instance-name.js                                                 💥️ -> ✅
test/built-ins/GeneratorFunction/instance-prototype.js                                            💥️ -> ❌ …
```

LibJS: Spec compliant CreateDynamicFunction

---

Userland/Libraries/LibJS/Runtime/Date.cpp
Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
Userland/Libraries/LibJS/Runtime/DatePrototype.h
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCDate.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCFullYear.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCHours.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCMilliseconds.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCMinutes.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCMonth.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setUTCSeconds.js

Some low hanging fruit after #11913 :)

LibJS: Implement `Date.prototype.setUTC*`

---

Tests/LibSQL/TestSqlStatementExecution.cpp
Userland/Libraries/LibSQL/AST/Select.cpp
Userland/Libraries/LibSQL/CMakeLists.txt
Userland/Libraries/LibSQL/ResultSet.cpp
Userland/Libraries/LibSQL/ResultSet.h
Userland/Libraries/LibSQL/SQLResult.cpp
Userland/Libraries/LibSQL/SQLResult.h
Userland/Services/SQLServer/SQLStatement.cpp

``ORDER BY`` definitely isn't ready yet, but is perfectly usable. ``LIMIT/OFFSET`` is complete I believe.

New SQL features: ORDER BY and LIMIT/OFFSET

---

Userland/Libraries/LibJS/Runtime/VM.h
Userland/Utilities/js.cpp

LibJS: Fix that '_' no longer accessed the last value in the REPL

---

Base/root/generate_manpages.sh
Base/usr/share/man/man1/CharacterMap.md
Base/usr/share/man/man1/Eyes.md
Base/usr/share/man/man1/FontEditor.md
Base/usr/share/man/man1/Help.md
Base/usr/share/man/man1/ImageViewer.md
Base/usr/share/man/man1/Inspector.md
Base/usr/share/man/man1/Mail.md
Base/usr/share/man/man1/Playground.md
Base/usr/share/man/man1/Profiler.md
Base/usr/share/man/man1/Terminal.md
Base/usr/share/man/man1/TextEditor.md
Base/usr/share/man/man6/2048.md
Base/usr/share/man/man6/Breakout.md
Base/usr/share/man/man6/Chess.md
Base/usr/share/man/man6/FlappyBug.md
Base/usr/share/man/man6/GameOfLife.md
Base/usr/share/man/man6/Hearts.md
Base/usr/share/man/man6/Minesweeper.md
Base/usr/share/man/man6/Pong.md
Base/usr/share/man/man6/Snake.md

Differentiate GUI applications in man pages with icons.
Co-Authored-by: electrikmilk <brandonjordan124@gmail.com>
This is the revert of the revert commit, now that the icon processing
was fixed in 89c0f84a280778a877b89d1b5f3facf5020095fb.
Revert: dae298e9df23a2f2be7f1b5a5c4726096c310a58
Original: 74238d0abaac7c36c49e33e863c65eb6b199d9f3
CC: @electrikmilk

Base: Add icons to man pages for GUI applications

---

Userland/Utilities/disasm.cpp

Another one of these. In addition, let's convert disasm to use east-const and C++-style casts.

disasm: Don't fail when trying to disassemble empty files

---

Kernel/Storage/NVMe/NVMeController.cpp
Kernel/Storage/NVMe/NVMeController.h
Kernel/Storage/NVMe/NVMeDefinitions.h
Kernel/Storage/NVMe/NVMeNameSpace.cpp
Kernel/Storage/NVMe/NVMeQueue.cpp
Kernel/Storage/NVMe/NVMeQueue.h

This PR is a collection of some minor Fixes and an improvement in the NVMe driver. 
The only noticeable change is the addition of `NVMeSubmission` union.

Kernel/NVMe: Minor fixes and improvements

---

Userland/Libraries/LibJS/Runtime/Value.cpp

Performance of string concatenation regressed in a57e2f9. That commit
iterates over the LHS string to find the last code unit, to check if it
is a high surrogate. Instead, first look at the 3rd-to-last byte in the
UTF-8 encoded string to check if it is a 3-byte code point; then decode
just those bytes to check if we have a high surrogate. Similarly, check
the first 3 bytes of the RHS string to check if we have a low surrogate.

LibJS: Implement UTF-16 surrogate pair concatenation without iteration

---

Kernel/Firmware/SysFSFirmware.cpp
Kernel/Time/TimeManagement.cpp
Kernel/Time/TimeManagement.h

Kernel: Fixes for boot with acpi=off

---

Kernel/Bus/PCI/Controller/HostBridge.cpp
Kernel/Bus/PCI/Definitions.h

Another preparation before completely fixing #11594.

Kernel: PCI host bridge fixes before implementing VMD support

---

Userland/Applications/CrashReporter/main.cpp

Previously when opening a crash report for HackStudio, the
`unveil("/bin/HackStudio", "rx")` call was failing because of the
earlier `unveil(executable_path.characters(), "r")` call requesting only
"r" permissions for it. This patch handles this specific case, so you
can crash HackStudio to your heart's content. :^)
Also, we were unveiling the executable path twice, once manually and
once implicitly as part of the coredump's libraries, so we now check for
the latter and avoid it.
Thanks to Daniel for noticing what was right in front of me and I didn't
see!
Co-authored-by: Daniel Bertalan <dani@danielbertalan.dev>
Fixes #11971

CrashReporter: Don't crash when investigating a HackStudio crash

---

Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp

This fixes 1 test262 test case :^)

LibJS: Implement ECMA-402 compliant TypedArray.prototype.toLocaleString

---

Meta/Lagom/CMakeLists.txt
Userland/Libraries/LibCore/ArgsParser.cpp
Userland/Libraries/LibCore/ArgsParser.h
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Utilities/CMakeLists.txt
Userland/Utilities/adjtime.cpp

- New wrapper for adjtime
- Add ArgsParser::add_option for Optional double (NaN was signaling there was no argument parsed)

adjtime: Port to LibMain

---

Userland/Libraries/LibCore/Stream.cpp

This mirrors the previous default in Core::LocalSocket, and is the safer
default anyway. This prevents fds from living on in other processes when
exec() is called in certain programs such as Assistant.
Fixes #12029.

LibCore: Make sockets close-on-exec by default

---

Tests/LibRegex/Regex.cpp
Userland/Libraries/LibRegex/RegexMatcher.cpp
Userland/Libraries/LibRegex/RegexOptimizer.cpp
Userland/Libraries/LibRegex/RegexParser.cpp
Userland/Libraries/LibRegex/RegexParser.h

Fixes #12033
Fixes one point in #6042 
Fixes #11940

LibRegex: Small bunch of random fixes

---

Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setHours.js
Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.toLocaleDateString.js
Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.format.js
Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRange.js
Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRangeToParts.js
Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatToParts.js

Ran test-js under every time zone to find/fix these.

LibJS: Change test conditions to pass in all time zones

---

Userland/Utilities/ping.cpp

This is my first PR, apologies if I have missed following some guidelines. Tested it manually and it seems the occasional timeouts in receiving pongs is somehow resolved with this fix.
In this change, I have added handling support for the `internet header length` field in the ping utility.

ping: Handling optional field in the IPv4 Header

---

Kernel/Syscalls/execve.cpp

These checks in `sys$execve` could trip up the system whenever you try to execute an `.so` file. For example, double-clicking `libwasm.so` in Terminal crashes the kernel.
This changes the program header alignment checks to reflect the same checks in LibELF.
Thanks to @IdanHo

Kernel: Allow program headers to align on multiples of `PAGE_SIZE`

---

Userland/Utilities/find.cpp

find: Fix crash on missing arguments

---

Kernel/Storage/NVMe/NVMeQueue.cpp
Kernel/Storage/NVMe/NVMeQueue.h

A bunch of fixes before landing support for polling mode for NVMe devices to allow @tomuta machine to boot (#11594).

Kernel/Storage: Bring NVMe code closer to the repository programming style

---

Userland/Libraries/LibGUI/TextEditor.cpp

I was a bit too quick to commit in my last pr, this fixes a Bug found by @kennethmyhra, thanks!

LibGUI: Bugfix for TextEditor

---

Ports/fontconfig/patches/pkgconfig.in.patch
Ports/freetype/package.sh
Ports/halflife/package.sh

This adds partial menu support. Mouse input still doesn't work, but most other components I've tested work, including saving/loading games. There is also a fix for the freetype port.

Ports: Add menu support for Hλlf-Life port

---

Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormat.cpp
Userland/Libraries/LibJS/Runtime/NumberPrototype.cpp
Userland/Libraries/LibJS/Runtime/PromiseReaction.cpp
Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp

Credit to @linusg for the idea! Much nicer than needing to create a MVL manually :)

LibJS: Add templated overloads for the construct AO to create its MVL

---

.mailmap
Meta/Lagom/CMakeLists.txt
Tests/LibJS/CMakeLists.txt
Tests/LibJS/test-bytecode-js.cpp

Noticed that while github understood both of those commiters are me, the mail map didn't quite get it yet.
~I will add some bytecode tests to the repo on this PR or a later one but for now this will already fix the test262 disaster :laughing:~ :heavy_check_mark: Added.

LibJS+Meta: Add js bytecode tests and mailmap

---

Userland/Libraries/LibGUI/Button.cpp
Userland/Libraries/LibGUI/Button.h
Userland/Libraries/LibGUI/InputBox.cpp
Userland/Libraries/LibGUI/Window.cpp
Userland/Libraries/LibGUI/Window.h
Userland/Libraries/LibGfx/ClassicStylePainter.cpp
Userland/Libraries/LibGfx/ClassicStylePainter.h
Userland/Libraries/LibGfx/StylePainter.cpp
Userland/Libraries/LibGfx/StylePainter.h
Userland/Services/LoginServer/LoginWindow.cpp

https://user-images.githubusercontent.com/66646555/150999885-4a16693c-2bea-496d-b1ab-22fed8fe484f.mp4

LibGUI: Default return key buttons

---

Ports/.port_include.sh
Ports/README.md

Ports: Make 'package.sh dev' a bit more friendly when importing patches

---

Base/res/terminal-colors/Monokai.ini

Base: Add the Monokai terminal color scheme

---

Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/Intl/Intl.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.h
Userland/Libraries/LibJS/Runtime/Intl/PluralRules.cpp
Userland/Libraries/LibJS/Runtime/Intl/PluralRules.h
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesConstructor.cpp
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesConstructor.h
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.h
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.@@toStringTag.js
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.js
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.prototype.resolvedOptions.js
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.supportedLocalesOf.js
Userland/Utilities/js.cpp

This implements the constructor and the common Intl methods `supportedLocalesOf` and `resolvedOptions`.

 LibJS: Begin implementing Intl.PluralRules

---

Documentation/VirtualBox.md

Remove the note on updating the disk image by documenting setting UUID for VirtualBox VDI image.

Documentation: Document setting UUID for VDI image

---

Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
Userland/Libraries/LibJS/Runtime/NumberPrototype.cpp
Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp

Tell corporate this has been fully unit tested and undergone security review

LibJS: Update spec numbers for ECMA-402

---

Userland/Libraries/LibGUI/CommandPalette.cpp

LibGUI: Allow CommandPalette to distinguish radio buttons and checkboxes

---

Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.h
Userland/Libraries/LibJS/Runtime/Intl/Intl.cpp
Userland/Libraries/LibJS/Runtime/Intl/SegmentIterator.cpp
Userland/Libraries/LibJS/Runtime/Intl/SegmentIterator.h
Userland/Libraries/LibJS/Runtime/Intl/SegmentIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/SegmentIteratorPrototype.h
Userland/Libraries/LibJS/Runtime/Intl/Segmenter.cpp
Userland/Libraries/LibJS/Runtime/Intl/Segmenter.h
Userland/Libraries/LibJS/Runtime/Intl/SegmenterConstructor.cpp
Userland/Libraries/LibJS/Runtime/Intl/SegmenterConstructor.h
Userland/Libraries/LibJS/Runtime/Intl/SegmenterPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/SegmenterPrototype.h
Userland/Libraries/LibJS/Runtime/Intl/Segments.cpp
Userland/Libraries/LibJS/Runtime/Intl/Segments.h
Userland/Libraries/LibJS/Runtime/Intl/SegmentsPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/SegmentsPrototype.h
Userland/Libraries/LibJS/Tests/builtins/Intl/Segmenter/Segmenter.@@toStringTag.js
Userland/Libraries/LibJS/Tests/builtins/Intl/Segmenter/Segmenter.js
Userland/Libraries/LibJS/Tests/builtins/Intl/Segmenter/Segmenter.prototype.resolvedOptions.js
Userland/Libraries/LibJS/Tests/builtins/Intl/Segmenter/Segmenter.prototype.segment.js
Userland/Libraries/LibJS/Tests/builtins/Intl/Segmenter/Segmenter.supportedLocalesOf.js
Userland/Utilities/js.cpp

This implements essentially everything but the Segmentation itself, which will happen in a future PR (hopefully together with the https://github.com/tc39/ecma402/pull/653 related changes).

LibJS: Start implementing Intl.Segmenter

---

AK/Format.h
AK/NonnullOwnPtr.h
AK/OwnPtr.h
AK/RefPtr.h
AK/Trie.h
Documentation/SmartPointers.md
Kernel/Bus/VirtIO/Device.cpp
Kernel/Bus/VirtIO/Device.h
Kernel/Devices/VMWareBackdoor.cpp
Kernel/Interrupts/APIC.cpp
Kernel/Library/ThreadSafeNonnullRefPtr.h
Kernel/Library/ThreadSafeRefPtr.h
Kernel/Memory/PhysicalRegion.cpp
Kernel/Net/NetworkTask.cpp
Kernel/Storage/Partition/EBRPartitionTable.cpp
Kernel/Storage/Partition/GUIDPartitionTable.cpp
Kernel/Storage/Partition/MBRPartitionTable.cpp
Kernel/Thread.cpp

AK+Kernel: Some more OOM hardening

---

Userland/Utilities/run-tests.cpp

Among other things, this lets you run flaky tests to check if they are
still flaky. :^)
This is done in two ways: It makes should_skip_test() always return
false; and skips reading and generating the skipped-tests lists since
we won't use them.

Utilities/run-tests: Add command-line switch to also run "skipped" tests

---

AK/Bitmap.h

How did it even get to be there?...

AK: Remove commented-out code from Bitmap container

---

Base/usr/share/man/man1/less.md
Userland/Utilities/less.cpp

A quick PR to add support for these keys.

less: Add hotkeys f and b to scroll screen up/down

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/SVG/SVGPathElement.cpp

The colours are still wrong in places, but the rendering is a lot closer to what it should be. :^)

LibWeb: Implement SVG S (SmoothCurve) commands

---

Kernel/Syscalls/socket.cpp

Previously we would return a bytes written value of 0 if the writing end
of the socket was full. Now we either exit with EAGAIN if the socket
description is non-blocking, or block until the description can be
written to.
This is mostly a copy of the conditions in sys$write but with the "total
nwritten" parts removed as sys$sendmsg does not have that.

Kernel: Ensure socket is suitable for writing in sys$sendmsg

---

Userland/Applications/TextEditor/MainWidget.cpp
Userland/Libraries/LibGUI/TextEditor.cpp
Userland/Libraries/LibGfx/Palette.h

mm, this one had been bothering me...

LibGfx+LibGUI+TextEditor: Correct GUI::TextEditor clip rect, improve Line Highlighting

---

Userland/Libraries/LibWeb/CSS/Identifiers.json
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleValue.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp

I went through the CSS parser spam when discord loads, and found a few things that turned up repeatedly. These 3 are the easiest to fix, so here they are! :^)

LibWeb: 3 little CSS fixes

---

Userland/Libraries/LibCore/Stream.h

The previous method could block multiple times, leading to a completely
stuck/deadlocked read() call, and it could also consume data without
telling the user about it, which is Not A Good Thing :tm:.
This patch makes it block at most once, and fixes loading HTTP pages
with LibHTTP :^)

LibCore: Make BufferedHelper::read() block at most once per read

---

Userland/Services/RequestServer/ConnectionCache.h

`it.is_end()` could be updated to return false for a previously-invalid
iterator after we append a new socket, copy its value out to a local
variable to not hit this behaviour.

RequestServer: Avoid Vector OOB access in ConnectionCache

---

Kernel/kprintf.cpp
Userland/Libraries/LibC/stdio.cpp

The global variable use in these functions is super thread-unsafe and
means that any concurrent calls to sprintf or fprintf in a process
could race with each other and end up writing unexpected results.
We can just replace the function + global variable with a lambda that
captures the relevant argument when calling printf_internal instead.
There's still some issues with these functions not fixed  here, see #12372

LibC+Kernel: Remove global variable use from snprintf and fprintf

---

Userland/Libraries/LibSQL/AST/Parser.cpp

Add an entry for the new DESCRIBE TABLE statement
and add Oxford comma :^)

LibSQL: Update list of expected statements

---

AK/RedBlackTree.h
Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
Userland/Libraries/LibJS/Runtime/Map.cpp
Userland/Libraries/LibJS/Runtime/Map.h
Userland/Libraries/LibJS/Runtime/MapIterator.cpp
Userland/Libraries/LibJS/Runtime/MapIterator.h
Userland/Libraries/LibJS/Runtime/MapIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/MapPrototype.cpp
Userland/Libraries/LibJS/Runtime/Set.cpp
Userland/Libraries/LibJS/Runtime/Set.h
Userland/Libraries/LibJS/Runtime/SetIterator.cpp
Userland/Libraries/LibJS/Runtime/SetIterator.h
Userland/Libraries/LibJS/Runtime/SetIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/SetPrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/Set/Set.prototype.forEach.js
Userland/Utilities/js.cpp

AK+LibJS: Implement Sets&Maps with mutation-safe iterators

---

Kernel/Graphics/Console/TextModeConsole.cpp
Kernel/Graphics/Console/TextModeConsole.h
Kernel/Graphics/Console/VGAConsole.cpp
Kernel/Graphics/Console/VGAConsole.h
Kernel/Graphics/GraphicsManagement.cpp
Kernel/Graphics/VGACompatibleAdapter.cpp
Kernel/init.cpp
Kernel/kprintf.cpp

Kernel: Instantiate early text mode console if framebuffer isn't available

---

Base/usr/share/man/man1/js.md
Userland/Utilities/js.cpp

For example:
$ js -c "console.log(42)"
42

js: Add a command line argument to evaluate a string as a script

---

AK/RedBlackTree.h
Tests/AK/TestRedBlackTree.cpp
Userland/Libraries/LibJS/Runtime/Map.cpp
Userland/Libraries/LibJS/Runtime/Map.h
Userland/Libraries/LibJS/Tests/builtins/Map/Map.prototype.delete.js
Userland/Libraries/LibJS/Tests/builtins/Map/Map.prototype.set.js
Userland/Libraries/LibJS/Tests/builtins/Map/Map.prototype.values.js
Userland/Libraries/LibJS/Tests/builtins/Set/Set.prototype.add.js
Userland/Libraries/LibJS/Tests/builtins/Set/Set.prototype.values.js
Userland/Libraries/LibJS/Tests/test-common.js

Also added a bunch of tests to hopefully catch all the behavior (I kinda spread them over a bunch of files)
Fixes all regressions and one new fix of the Map rewrite.
The only thing I'm not sure about is the removal of the optional, feel like I'm missing a case but can't think of any.

AK+LibJS: Small fix for Map/Set

---

Userland/Applications/PixelPaint/CMakeLists.txt
Userland/Applications/PixelPaint/IconBag.cpp
Userland/Applications/PixelPaint/IconBag.h
Userland/Applications/PixelPaint/MainWidget.cpp
Userland/Applications/PixelPaint/MainWidget.h
Userland/Applications/PixelPaint/main.cpp

Implement IconBag method of organizing menubar icons. Thanks, @dykatz for the original implementation of this in the Browser.

PixelPaint: Implement IconBag to organize icons

---

Kernel/Devices/HID/I8042Controller.cpp

Kernel: Increase attempts count and delays when doing i8042 IO

---

Userland/Libraries/LibWeb/HTML/WebSocket.cpp

Support for websockets set to 'arraybuffer' mode, receiving non-text data. This is used by discord for communication with the backend.

LibWeb: Add support for 'arraybuffer' message types on WebSockets

---

Userland/Applications/PixelPaint/CMakeLists.txt
Userland/Applications/PixelPaint/FilterGallery.cpp
Userland/Applications/PixelPaint/FilterGallery.gml
Userland/Applications/PixelPaint/FilterGallery.h
Userland/Applications/PixelPaint/FilterPreviewWidget.cpp
Userland/Applications/PixelPaint/FilterPreviewWidget.h
Userland/Applications/PixelPaint/Filters/Bloom.cpp
Userland/Applications/PixelPaint/Filters/FastBoxBlur.cpp
Userland/Applications/PixelPaint/Filters/Filter.cpp
Userland/Applications/PixelPaint/Filters/Filter.h
Userland/Applications/PixelPaint/Filters/Sepia.cpp

Now Filter Gallery shows the preview of the currently selected filter
applied on the currently active layer
Screenshot:

PixelPaint: Add a preview in FilterGallery

---

Userland/Applications/FileManager/main.cpp

This mirrors the behaviour in Browser.

FileManager: Add F6 alternate shortcut to "location" action

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator.cpp
Userland/Libraries/LibWeb/URL/URLSearchParams.cpp
Userland/Libraries/LibWeb/URL/URLSearchParams.h
Userland/Libraries/LibWeb/URL/URLSearchParams.idl

LibWeb: Add support for the record variant of URLSearchParams

---

Kernel/Devices/HID/VMWareMouseDevice.cpp
Kernel/FileSystem/Inode.cpp
Kernel/FileSystem/Inode.h
Kernel/Memory/SharedInodeVMObject.cpp
Kernel/Syscalls/fork.cpp
Kernel/Syscalls/pledge.cpp

Partially co-authored by @ADKaster, @alimpfard, @sin-ack.

Kernel: Fix some more random OOM-related issues

---

Kernel/FileSystem/DevTmpFS.cpp
Userland/Services/SystemServer/main.cpp

Kernel: Honor permission mode when creating new directories in DevTmpFS

---

Userland/Libraries/LibWeb/Layout/Node.h

This change was to make DuckDuckGo usable. 
They use a lot of relative and absolute positioning which causes a complex stacking context arrangement to form. 
Only some of the hit_test paths could previously test elements inside a stacking context. 
With this change, elements which previously were not usable (hover or click) now respond correctly to both.

LibWeb: Allow hit testing to work with complex stacking contexts

---

Meta/Azure/Setup.yml

This should hopefully resolve a clang ICE seen in PR #12523.

Meta: Use clang-13 instead of clang-12 in Azure CI

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/Runtime/IndexedProperties.cpp
Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp
Userland/Libraries/LibJS/Tests/object-spread.js

LibJS: Small fix for spreading, optimisation for indexed properties

---

Meta/CMake/unicode_data.cmake
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
Tests/LibUnicode/TestUnicodeCharacterTypes.cpp
Userland/Applications/CharacterMap/CharacterMapWidget.cpp
Userland/Applications/CharacterMap/CharacterMapWidget.h
Userland/Applications/CharacterMap/CharacterMapWindow.gml
Userland/Applications/CharacterMap/main.cpp
Userland/Applications/FontEditor/FontEditor.cpp
Userland/Applications/FontEditor/FontEditor.h
Userland/Applications/FontEditor/FontEditorWindow.gml
Userland/Applications/FontEditor/main.cpp
Userland/Libraries/LibGUI/GlyphMapWidget.cpp
Userland/Libraries/LibGUI/GlyphMapWidget.h
Userland/Libraries/LibUnicode/CharacterTypes.cpp
Userland/Libraries/LibUnicode/CharacterTypes.h
Userland/Libraries/LibUnicode/Forward.h

Meta+LibUnicode+LibGUI+Apps: Allow sorting glyphs by Unicode block

---

Userland/Demos/Cube/Cube.cpp
Userland/Demos/Eyes/EyesWidget.cpp
Userland/Demos/Eyes/EyesWidget.h
Userland/Demos/Fire/Fire.cpp
Userland/Demos/LibGfxDemo/main.cpp
Userland/Demos/LibGfxScaleDemo/main.cpp
Userland/Demos/Screensaver/Screensaver.cpp
Userland/Demos/Starfield/Starfield.cpp
Userland/Demos/WidgetGallery/GalleryModels.h
Userland/Demos/WidgetGallery/GalleryWidget.cpp
Userland/Demos/WidgetGallery/GalleryWidget.h

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cother-other-default-operation-rules
"The compiler is more likely to get the default semantics right and
you cannot implement these functions better than the compiler."

Demos: Use default constructors/destructors

---

Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl

LibWeb: Support Element.closest(selectors)

---

Base/res/html/misc/progressbar.html
Base/res/html/misc/welcome.html
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.idl
Userland/Libraries/LibWeb/Layout/Progress.cpp
Userland/Libraries/LibWeb/Layout/Progress.h

Many things still has to be done, but i think it's good starting point.

Base+LibWeb: Add basic implementation of progress bar element

---

Userland/Games/2048/BoardView.cpp
Userland/Games/2048/BoardView.h
Userland/Games/Breakout/Game.cpp
Userland/Games/Breakout/Game.h
Userland/Games/Breakout/LevelSelectDialog.cpp
Userland/Games/Breakout/LevelSelectDialog.h
Userland/Games/Chess/ChessWidget.cpp
Userland/Games/Chess/ChessWidget.h
Userland/Games/GameOfLife/Board.cpp
Userland/Games/GameOfLife/Board.h
Userland/Games/GameOfLife/Pattern.cpp
Userland/Games/GameOfLife/Pattern.h
Userland/Games/Hearts/Game.cpp
Userland/Games/Hearts/Game.h
Userland/Games/Minesweeper/CustomGameDialog.cpp
Userland/Games/Minesweeper/CustomGameDialog.h
Userland/Games/Minesweeper/Field.cpp
Userland/Games/Minesweeper/Field.h
Userland/Games/Pong/Game.cpp
Userland/Games/Pong/Game.h
Userland/Games/Snake/SnakeGame.cpp
Userland/Games/Snake/SnakeGame.h
Userland/Games/Solitaire/Game.cpp
Userland/Games/Solitaire/Game.h
Userland/Games/Spider/Game.cpp
Userland/Games/Spider/Game.h

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cother-other-default-operation-rules
"The compiler is more likely to get the default semantics right and
you cannot implement these functions better than the compiler."

Games: Use default constructors/destructors

---

Ports/mpc/package.sh
Ports/patch/package.sh

Those were apparently missed during the initial migration.

Ports: Fix two missing config.sub paths

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLGenerators.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLParser.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLParser.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLTypes.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/main.cpp

Ask for one thing and get two (+a refactor) for free!

Meta: Split and refactor the WrapperGenerator a bit / WrapperGenerator: IDL interface mixins

---

Kernel/Devices/HID/HIDManagement.cpp
Kernel/Devices/HID/I8042Controller.cpp
Kernel/Devices/HID/I8042Controller.h

See messages in #bare-metal for more context :)

Kernel: Fix i8042 initialization on bare metal

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLGenerators.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLTypes.h
Userland/Libraries/LibWeb/CSS/MediaQueryList.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.h
Userland/Libraries/LibWeb/DOM/EventTarget.idl
Userland/Libraries/LibWeb/DOM/IDLEventListener.h
Userland/Libraries/LibWeb/Forward.h

Details in the individual commits :^)

LibWeb: Add support for the options variant of {add,remove}EventListener 

---

Base/usr/share/man/man1/ls.md
Userland/Utilities/ls.cpp

The option -1 should add a newline after each file that gets printed.

ls: Add option -1 which lists one file per line

---

Userland/Applications/HexEditor/HexEditorWidget.cpp
Userland/Applications/HexEditor/HexEditorWidget.h

This commit will show a special close icon in the window frame when a file is modified.

HexEditor: Use `Window::set_modified()`

---

Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

The entry we get from the active formatting elements list during the
Rewind step of "reconstruct the active formatting elements" can be a
marker. Previously we assumed it was not a marker, which can trigger
an assertion failure with certain malformed HTML.
If the entry in this step is a marker, the spec simply ignores it.
This is step 6 of the algorithm.
This also makes the index unsigned, as this algorithm is a no-op if
the list is empty.
Additionally, this also adds spec comments to this algorithm.
Fixes #12668.

LibWeb: Handle markers when reconstructing active formatting elements

---

Userland/Applications/Spreadsheet/Spreadsheet.cpp

Just gets rid of a lot of unnecessary spam

Spreadsheet: Remove Debug Statement

---

Userland/Libraries/LibJS/CyclicModule.cpp
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/Completion.cpp
Userland/Libraries/LibJS/Runtime/FunctionObject.cpp
Userland/Libraries/LibJS/Runtime/FunctionPrototype.cpp
Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
Userland/Libraries/LibJS/Runtime/NativeFunction.h
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/PromisePrototype.cpp
Userland/Libraries/LibJS/Runtime/PromiseReaction.cpp
Userland/Libraries/LibJS/Runtime/ProxyConstructor.cpp
Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Tests/builtins/Function/Function.prototype.toString.js

Apparently doesn't fix or break any test262 tests, even though plenty of things were incorrect/missing before. :thinking:

LibJS: Implement a somewhat sane CreateBuiltinFunction

---

Kernel/Bus/VirtIO/Console.cpp
Meta/run.sh

This actually allows local clipboard sharing to work on my configuration :^)

Meta+Kernel: Fix qemu SPICE configuration and multiport VirtIO console

---

Userland/Applications/Spreadsheet/Cell.cpp
Userland/Applications/Spreadsheet/Cell.h
Userland/Applications/Spreadsheet/SpreadsheetModel.cpp
Userland/Applications/Spreadsheet/SpreadsheetModel.h
Userland/Applications/Spreadsheet/SpreadsheetView.h
Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Userland/Applications/Spreadsheet/SpreadsheetWidget.h

Giving a little love to Spreadsheet in this PR.
This PR adds functionality for:
- Undo/Redo (this would close #4270).
- Add window()->set-modified if a change occurs.

Spreadsheet: Add undo/redo functionality

---

Kernel/Process.cpp
Kernel/Scheduler.cpp
Kernel/Thread.cpp

Kernel: Some signals-related fixes

---

Userland/Applications/CharacterMap/CharacterMapWindow.gml
Userland/Applications/FontEditor/FontEditorWindow.gml
Userland/Applications/Help/main.cpp
Userland/Applications/TextEditor/MainWidget.cpp
Userland/Applications/TextEditor/TextEditorWindow.gml
Userland/Demos/WidgetGallery/GalleryGML/BasicsTab.gml
Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/Libraries/LibGUI/Splitter.cpp
Userland/Libraries/LibGUI/Splitter.h

LibGUI+Apps: Splitter fixes

---

Userland/Applets/ClipboardHistory/ClipboardHistoryModel.cpp
Userland/Applets/ClipboardHistory/ClipboardHistoryModel.h
Userland/Applets/ClipboardHistory/main.cpp

Add a Time column to ClipboardHistory that shows the time when each
item in the list was copied.

ClipboardHistory: Add Time column

---

Userland/Libraries/LibGUI/TextEditor.cpp
Userland/Libraries/LibGUI/TextEditor.h
Userland/Libraries/LibGfx/BitmapFont.h
Userland/Libraries/LibGfx/Font.h
Userland/Libraries/LibGfx/TrueTypeFont/Font.h

LibGUI+LibGfx: Improve line height and ruler calculations in editors

---

Userland/Applications/HexEditor/GoToOffsetDialog.gml
Userland/Applications/HexEditor/HexEditorWindow.gml
Userland/Applications/TextEditor/MainWidget.cpp
Userland/Applications/TextEditor/MainWidget.h
Userland/Applications/TextEditor/TextEditorWindow.gml
Userland/Applications/TextEditor/main.cpp
Userland/DevTools/HackStudio/FindInFilesWidget.cpp
Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/Locator.cpp
Userland/Games/Solitaire/Solitaire.gml
Userland/Games/Spider/Spider.gml
Userland/Libraries/LibGUI/Button.cpp
Userland/Libraries/LibGUI/Statusbar.cpp
Userland/Libraries/LibGUI/Statusbar.h
Userland/Libraries/LibGUI/TextEditor.cpp
Userland/Libraries/LibGUI/TextEditor.h
Userland/Libraries/LibGfx/ClassicStylePainter.cpp
Userland/Libraries/LibSyntax/Highlighter.cpp
Userland/Libraries/LibSyntax/Highlighter.h

https://user-images.githubusercontent.com/66646555/155134257-86cf437e-5d11-4f16-9fc6-085df026622e.mp4

LibGUI: Comfy status bar buttons

---

Userland/Applets/Audio/main.cpp
Userland/Applications/Assistant/main.cpp
Userland/Libraries/LibGUI/CommandPalette.cpp
Userland/Libraries/LibGUI/Frame.cpp
Userland/Libraries/LibGfx/ClassicStylePainter.cpp
Userland/Libraries/LibGfx/StylePainter.h
Userland/Services/Taskbar/ClockWidget.cpp
Userland/Services/Taskbar/ClockWidget.h

LibGfx+LibGUI+Apps: New FrameShape::Window for frameless apps

---

Userland/Libraries/LibGUI/TextEditor.cpp

TextEditor: Fix highlighting issue in wrapping mode

---

Base/res/html/misc/pseudo-elements.html

Base: Make it obvious which pseudo-element tests are unimplemented

---

AK/Time.cpp
AK/Time.h
Kernel/API/POSIX/sys/resource.h
Kernel/API/Syscall.h
Kernel/CMakeLists.txt
Kernel/Process.h
Kernel/Syscalls/resource.cpp
Userland/Libraries/LibC/ulimit.cpp

Closes #1140
Add the getrusage() function for POSIX compliance

Kernel+LibC: Add getrusage()

---

Userland/Libraries/LibWeb/Bindings/WindowObject.cpp
Userland/Libraries/LibWeb/Bindings/WindowObject.h
Userland/Libraries/LibWeb/Origin.h

Added origin property to the window object
Just a small commit / PR to get the hang of making contributions.

LibWeb: Add origin property to window object

---

Base/res/html/misc/pseudo-elements.html

I didn't notice that CLion had auto-generated this, oops! As wonderful
as my web design skills are, I don't actually want to enshrine my name
at the top of this file for posterity.

Base: Remove my copyright from this HTML file

---

Base/home/anon/BrowserSettingsWidget.gml
Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/CMakeLists.txt
Userland/Applications/Browser/CookieJar.cpp
Userland/Applications/Browser/CookieJar.h
Userland/Applications/Browser/CookiesModel.cpp
Userland/Applications/Browser/CookiesModel.h
Userland/Applications/Browser/CookiesTab.gml
Userland/Applications/Browser/StorageWidget.cpp
Userland/Applications/Browser/StorageWidget.gml
Userland/Applications/Browser/StorageWidget.h
Userland/Applications/Browser/Tab.cpp
Userland/Applications/Browser/Tab.h

This PR adds ability to view site cookies directly in browser :^)

Browser: Add storage inspector

---

Userland/Applications/CharacterMap/CharacterMapWidget.cpp
Userland/Applications/CharacterMap/CharacterSearchWidget.cpp
Userland/Applications/FontEditor/FontEditor.cpp

https://user-images.githubusercontent.com/16520278/156659176-1ca6b5a4-aa1f-495b-a312-b22904564f1c.mp4

CharacterMap(+FontEditor): React on arrow key presses in Unicode blocks list and Character search

---

Userland/Libraries/LibGL/SoftwareGLContext.cpp
Userland/Libraries/LibSoftGPU/Device.cpp

* LibGfx: Prevent normalizing a zero `Vector`
* LibSoftGPU: Fix light attenuation
* LibGL: Implement additional lighting input parameter checking
This resolves some issues with the lighting in Grim Fandango, but I suspect all lighting will be affected. :^)
Before 1:
After 1:
Before 2:
After 2:

LibGL+LibSoftGPU+LibGfx: OpenGL lighting improvements

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLGenerators.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLParser.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLTypes.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl

The main thing to review here is the IDL overload resolution (which is the reason for these review requests :smile:)

LibWeb: Add all overloads of CanvasRenderingContext2D::drawImage()

---

Userland/Libraries/LibLine/Editor.cpp
Userland/Libraries/LibLine/SuggestionManager.cpp

Couple hotfixes for two things I had somehow missed :P

LibLine: Make sure suggestions have their *_views set correctly

---

Userland/Libraries/LibGUI/AbstractSlider.h
Userland/Libraries/LibGUI/Scrollbar.cpp
Userland/Libraries/LibGUI/Scrollbar.h

https://user-images.githubusercontent.com/30666851/157103057-c331dad7-b22d-4afc-8337-afbd7dee8d96.mp4

LibGUI: Animated smooth scroll interpolation

---

Userland/Libraries/LibSoftGPU/Sampler.cpp

Previously the test determining whether to use texture maginifaction or
texture minification was reversed. This commit fixes the test and also
provides an early out of the sampler in case of texture magnification
since magnification does not make use of mipmaps.

LibSoftGPU: Choose correct texture filter based on scale factor

---

Base/res/js/Spreadsheet/runtime.js
Userland/Applications/Spreadsheet/Tests/basic.js

Syntax: ```R`A0:B`.filter(c => c.value() % 2 === 1);```

Spreadsheet: Add SplitRange class and CommonRange#filter

---

AK/NonnullPtrVector.h
AK/ReverseIterator.h
AK/Vector.h
Tests/AK/TestVector.cpp
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp

- AK: Add generic reverse iterator for containers
- AK: Implement reverse iterator for Vector class

Implement ReverseIterator

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibWeb/Generate_CSS_PropertyID_cpp.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/Generate_CSS_PropertyID_h.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/Generate_CSS_ValueID_cpp.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/Generate_CSS_ValueID_h.cpp

A small change, but that's 4 less users of Core::File. :^)

Meta: Port Generate_CSS_Foo programs to LibMain/Core::Stream

---

Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTableSectionElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTableSectionElement.h
Userland/Libraries/LibWeb/HTML/HTMLTableSectionElement.idl

This gives us an extra point in Acid3.

LibWeb: insertRow()/deleteRow() and friends

---

Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.set.js

Let me know if this is enough, anything you think should be tested, let me know, if this is enough to remove the fixme, i can do that...

LibJS: Add some tests for TypedArray.prototype.set

---

Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Bytecode/Op.h

Tee-Ell-Dee-Arr:
+2311 ✅    -6149 ❌    -3 💀   +167 💥️   +3674 📝

LibJS: Some more random bytecode fixes

---

Userland/Libraries/LibJS/Bytecode/Pass/MergeBlocks.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h

Diff Tests:
+1053 ✅    -1102 💥️   +49 📝

LibJS/Bytecode: Two more fixes for the fix jar

---

Userland/Applications/Piano/Music.h
Userland/Applications/Piano/WaveWidget.cpp
Userland/Services/AudioServer/Mixer.h

This effectively makes all things louder, especially Piano. Several people have complained about this so it's prime time I fix it.

Audio: Decrease volume headrooms

---

Kernel/ProcessSpecificExposed.cpp

Just a small PR, to remove an 8 months old FIXME.
This also condenses the code a bit

Kernel: Bail out earlier from Process::lookup_stacks_directory

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp

```
Summary:
Diff Tests:
+121 ✅    -390 ❌   +2 💀    -156 💥️   +423 📝
```
I wasn't sure how to name the third commit, so if you have a better name, please say :^)

LibJS: Even more bytecode fixes

---

AK/Complex.h
AK/Math.h
Userland/DevTools/UserspaceEmulator/SoftFPU.cpp
Userland/Libraries/LibAudio/Sample.h
Userland/Libraries/LibDSP/FFT.h
Userland/Libraries/LibGfx/Matrix4x4.h

Some stuff that I found trying to find out why tgamma and Cube don't work propperly.
Sadly no fixes....
On the sincos thing:
I don't like the semantics, would a structured binding be appropriate here?

UE: Some more comments; AK: Add sincos helper

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLGenerators.cpp
Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.h
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Userland/Libraries/LibWeb/Layout/ButtonBox.cpp
Userland/Libraries/LibWeb/Layout/ButtonBox.h
Userland/Libraries/LibWeb/Layout/CheckBox.cpp
Userland/Libraries/LibWeb/Layout/CheckBox.h
Userland/Libraries/LibWeb/Layout/FormAssociatedLabelableNode.h
Userland/Libraries/LibWeb/Layout/Label.h
Userland/Libraries/LibWeb/Layout/RadioButton.cpp
Userland/Libraries/LibWeb/Layout/RadioButton.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
Userland/Libraries/LibWeb/Painting/ButtonPaintable.h
Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp
Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.h
Userland/Libraries/LibWeb/Painting/LabelablePaintable.cpp
Userland/Libraries/LibWeb/Painting/LabelablePaintable.h
Userland/Libraries/LibWeb/Painting/Paintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/ProgressPaintable.h
Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.cpp
Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.h
Userland/Libraries/LibWeb/Painting/TextPaintable.cpp
Userland/Libraries/LibWeb/Painting/TextPaintable.h

Two new Acid3 tests now pass, 80/100. :^)

LibWeb: Input event handling extravaganza

---

.github/workflows/libjs-test262.yml

Hopefully for the last time, copy the results to the right file.

Meta: Copy wasm results to the right file

---

Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp

This proposal was implemented in Stage 3 in commit:
6c67de8186e22d9c39c2fa1eec92de784669336f
It is now Stage 4 and has been merged into the main ECMA-262 spec:
https://github.com/tc39/ecma262/commit/0209d85

LibJS: Update specification steps for RegExp Match Indices

---

Tests/Spreadsheet/test-spreadsheet.cpp
Userland/Applications/Spreadsheet/Workbook.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Interpreter.cpp
Userland/Libraries/LibJS/Interpreter.h
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/SourceTextModule.cpp
Userland/Libraries/LibJS/SyntheticModule.cpp
Userland/Libraries/LibTest/JavaScriptTestRunner.h
Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
Userland/Libraries/LibWeb/HTML/Worker.cpp
Userland/Services/WebContent/WebContentConsoleClient.cpp

LibJS: Small refactor

---

Kernel/TTY/VirtualConsole.cpp
Userland/Libraries/LibVT/Attribute.h
Userland/Libraries/LibVT/Terminal.cpp
Userland/Libraries/LibVT/TerminalWidget.cpp

Noticed the TODO in `Attribute.h` and realized we have as solution
to this problem already. :^)

LibVT/Kernel: Make VT::Attribute::Flags enum class, use AK EnumBits

---

Kernel/Graphics/GraphicsManagement.cpp
Kernel/Graphics/GraphicsManagement.h

Kernel/Graphics: Don't declare VGA changing-state methods as const

---

Userland/Games/Solitaire/Game.cpp
Userland/Games/Spider/Game.cpp
Userland/Libraries/LibArchive/Zip.cpp
Userland/Libraries/LibArchive/Zip.h
Userland/Libraries/LibAudio/FlacLoader.cpp
Userland/Libraries/LibAudio/FlacTypes.h
Userland/Libraries/LibAudio/LoaderError.h
Userland/Libraries/LibAudio/SampleFormats.cpp
Userland/Libraries/LibAudio/SampleFormats.h
Userland/Libraries/LibCards/Card.cpp
Userland/Libraries/LibCards/Card.h
Userland/Libraries/LibCards/CardStack.cpp
Userland/Libraries/LibCards/CardStack.h

Additional type safety and consistency.

Libraries: Change enums to enum classes

---

Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Bytecode/Op.h

```
Summary:
Diff Tests:
+600 ✅   +14 ❌    -584 💥️    -30 📝
```

LIbJS: A couple of bytecode fixes

---

Userland/Libraries/LibProtocol/Request.cpp
Userland/Services/RequestServer/ConnectionFromClient.cpp
Userland/Utilities/pro.cpp

Add `pro -l` to follow Location headers, make it report progress nicely and fix a bug while we're at it.

pro: Optionally follow 3xx responses with a Location header / Some RS niceties

---

Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
Userland/Libraries/LibWeb/HTML/Parser/ListOfActiveFormattingElements.cpp
Userland/Libraries/LibWeb/HTML/Parser/ListOfActiveFormattingElements.h
Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.cpp
Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.h

This gets us 2 points on html5test.com :^)
- Before: https://html5te.st/4cf57659bc08272e (208)
- After: https://html5te.st/fb8a9259bda1c115 (210)

LibWeb: Implement the rest of the Adoption Agency Algorithm

---

Userland/Applications/Spreadsheet/CellType/Date.cpp
Userland/Applications/Spreadsheet/CellType/Date.h
Userland/Applications/Spreadsheet/CellType/Identity.cpp
Userland/Applications/Spreadsheet/CellType/Identity.h
Userland/Applications/Spreadsheet/CellType/Numeric.cpp
Userland/Applications/Spreadsheet/CellType/Numeric.h
Userland/Applications/Spreadsheet/CellType/String.cpp
Userland/Applications/Spreadsheet/CellType/String.h
Userland/Applications/Spreadsheet/CellType/Type.h
Userland/Applications/Spreadsheet/CellTypeDialog.cpp
Userland/Applications/Spreadsheet/Spreadsheet.cpp
Userland/Applications/Spreadsheet/SpreadsheetView.cpp

I was making a nice time table sheet when I realised that
- we couldn't load sheets that had functions defined in cells
- I couldn't make cells with random objects look pretty
- TOP CENTER DIDNT WORK??!???!?
this fixes that stuff :^)

Spreadsheet: Some improvements, and of course, boog fixes

---

Userland/Applications/FontEditor/FontEditor.cpp
Userland/Applications/FontEditor/FontEditor.h
Userland/Applications/FontEditor/UndoSelection.h
Userland/Libraries/LibGUI/GlyphMapWidget.cpp
Userland/Libraries/LibGUI/GlyphMapWidget.h

LibGUI+FontEditor: Autoscrolling, selection restore on undo, map context menu

---

Userland/Libraries/LibGfx/Painter.cpp

Clamp these coordinates based on the src_rect's top/right/bottom/left instead of assuming src_rect is positioned at 0,0.
Also splits up the interpolation into multiple lines to make it more readable.

LibGfx: Clamp coordinates for bilinear blending correctly

---

Meta/Lagom/CMakeLists.txt
Meta/run.sh

(I builds Intel serenity like everywhere else for now.)

Make serenity build and run on asahi linux.

---

Userland/Libraries/LibWeb/HTML/Parser/StackOfOpenElements.cpp
Userland/Libraries/LibWeb/Loader/Resource.cpp

LibWeb: Fix two issues encountered on jscrew.it

---

Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp

LibWeb: Don’t overlap table cells

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLGenerators.cpp
Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Userland/Libraries/LibWeb/HTML/HTMLOptionsCollection.cpp
Userland/Libraries/LibWeb/HTML/HTMLOptionsCollection.h
Userland/Libraries/LibWeb/HTML/HTMLOptionsCollection.idl
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl

LibWeb: Implement {HTMLOptionsCollection,HTMLSelectElement}.add()

---

Kernel/Arch/x86/CPUID.h
Kernel/Arch/x86/Processor.h
Kernel/Arch/x86/common/Processor.cpp

No functional changes, just a thing that bugged me...

Kernel: Add and use bitwise operators to CPUFeature

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

Following the  spec at https://www.w3.org/TR/css-flexbox-1/ to use *outer* sizes of flex items where appropriate.
It makes our Github page look marginally better:

LibWeb: Make margins in the main dimension work for flex items

---

Base/res/fortunes.json

Base: Add a quote from Ali, the mememaster extr'ordinaire

---

Userland/Utilities/sql.cpp

This fixes a bug in the SQL REPL where after a user enters an
unrecognized command, the REPL would not print another "> " prompt and
would not accept any more input.

sql: Re-prompt user for input after unrecognized command

---

Ports/powdertoy/.gitignore
Ports/powdertoy/cross_file-i686.txt
Ports/powdertoy/cross_file-x86_64.txt
Ports/powdertoy/package.sh

Sorry for making post-mortem changes to my port, but I have mistakenly left the cross-files ignored, and thus the port wouldn't build. I also added the icon.

Ports: Fix The Powder Toy port build and add icon

---

Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp

This fixes the placement of several background images on Acid2, most
notably the background of the eyes and the red rectangle near the bottom
of the head.
To help convince myself this was working as intended, I also tested with hard-coding the x-offset of the `eyes-a` object background image to 0 (it normally has an offset of 1, which is how the pixelation "cancels" out to show all yellow). When I do that, we see the pixelation again as expected:

LibWeb: Attach BackgroundAttachment::Fixed to the window view port

---

Kernel/GlobalProcessExposed.cpp
Kernel/TTY/SlavePTY.cpp
Kernel/TTY/SlavePTY.h
Kernel/TTY/TTY.h
Kernel/TTY/VirtualConsole.cpp
Kernel/TTY/VirtualConsole.h
Userland/Utilities/ps.cpp

Utilities/ps: Don't assume the kernel can provide real TTY paths

---

Userland/Libraries/LibAudio/FlacLoader.cpp
Userland/Libraries/LibAudio/FlacLoader.h
Userland/Libraries/LibAudio/FlacTypes.h

Continuation of #11360 . CC @maxtrussell

LibAudio: Implement seeking for FLAC

---

Userland/Libraries/LibChess/Chess.cpp

Chess: On pgn import avoid losing piece promotion info

---

Userland/Libraries/LibWeb/Crypto/Crypto.cpp
Userland/Libraries/LibWeb/Crypto/Crypto.h
Userland/Libraries/LibWeb/Crypto/Crypto.idl

LibWeb: Add Crypto.randomUUID()

---

Userland/Libraries/LibWeb/Page/EventHandler.cpp

This commit moves a couple more special cases in mouse event handling to
handle_mouseup. Additionally, it gets rid of the special casing with
should_dispatch_event and only fires a click event to the EventTarget
when the left mouse button is clicked. Finally it restores the link
context menu callback that was lost during 0fc8c65.

LibWeb: Consolidate mouse handling + only trigger event on left click

---

Userland/Libraries/LibELF/DynamicLoader.cpp
Userland/Libraries/LibELF/DynamicLoader.h
Userland/Libraries/LibELF/DynamicObject.cpp
Userland/Libraries/LibELF/Validation.h

I noticed a few issues while profiling `true` with UserSpace emulator.

LibELF: Small dynamic loader perf improvements

---

Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.toString.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.toString.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.toString.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.from.js

This includes all relevant Temporal spec changes merged today with the exception of https://github.com/tc39/proposal-temporal/commit/1f3fba8fd25ab775629d6b1161ae38e405ea3d75, which I'll do separately.
~~I expect to add more commits to this PR soon, just waiting for them to merge more approved changes:~~

LibJS: More Temporal spec changes

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Bytecode/Op.h

```
30172/45881 ( 65.76%) [ ✅ 30172 ❌ 4137  ⚙️ 112   💀 24    💥️ 2057  📝 9379  ]
Summary:
Diff Tests:
+702 ✅   +201 ❌    -192 💥️    -711 📝
```

LibJS: A couple more BC impls

---

Meta/lint-ports.py

Fix a small typo in the port linter.

Meta: Fix format-string in the port linter

---

Kernel/FileSystem/SysFS.cpp
Kernel/FileSystem/SysFSComponent.h
Kernel/Firmware/BIOS.h
Ports/dmidecode/patches/ReadMe.md
Ports/dmidecode/patches/dmidecode.patch

I tested the dmidecode and saw it had a bit of rot over it so I fixed it (as the person who ported it initially).
Very small fixes, nothing too much drastic, but this allows dmidecode to work properly :)

Kernel+Ports: Bunch of small fixes for dmidecode

---

Meta/serenity_gdb.py

Some tiny stuff that came up debugging something

Meta: Update gdb script for changes in HashTable / Meta: Avoid showing elements in extremely large vectors in gdb

---

Base/res/fortunes.json

Base: Add Andrew's very inspired musings to the fortunes database

---

Base/res/html/misc/flex-order.html
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h

This builds on the work done by #13385  
Implements flex reverse layouts by just reversing the order and the items within each order bucket.

LibWeb: Implement flex reverse layouts

---

README.md

The README was getting a bit outdated in places, and it didn't have its priorities straight (libc uwu, also we have browser no big deal). These changes are largely based on what was discussed among major contributors and maintainers, though I put in some extra stuff I'm bothered by.
The start of README is unchanged. The project blurb is probably its best part, both then and now, so it definitely stays. The FAQ is moved up under the About section because it's easier to find that way and makes more sense logically.
The Features section is a highly compressed version of the previous several features sections. Priorities are a big focus here: List what matters to a reader, what they will likely care about, what's impressive to them and what's probably not. The list therefore starts with the …

Meta: Completely overhaul the README

---

Userland/Utilities/top.cpp

This PR adds support for quitting `top` by pressing q. This was the behaviour I expected based on other "top"s

top: add support for quitting top by pressing q

---

Documentation/TransferringFiles.md

Describe how to enable OpenSSH package on SerenityOS and
of the proper usage of sftp client in order to transfer files.

Base: Add to documentation 4th method of transferring files

---

Base/usr/share/man/man1/netstat.md
Userland/Utilities/netstat.cpp

netstat: Resolve ports to service names

---

Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp

We had an issue with computing a width of a block in MaxContent
mode because we would set the width of the containing block to
infinity which would make everything in the try_compute_width
block infinity as well.
This adds a special case for width = 'auto' when
width_of_containing_block is infinity and removes the width of
containing block from the equation entirely.

LibWeb: Fix computing_width of a block when LayoutMode::MaxContent

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/CMakeLists.txt
Userland/Applications/Browser/LocalStorageModel.cpp
Userland/Applications/Browser/LocalStorageModel.h
Userland/Applications/Browser/StorageWidget.cpp
Userland/Applications/Browser/StorageWidget.h
Userland/Applications/Browser/Tab.cpp
Userland/Applications/Browser/Tab.h
Userland/Libraries/LibIPC/Decoder.h
Userland/Libraries/LibIPC/Encoder.h
Userland/Libraries/LibWeb/HTML/Storage.h
Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
Userland/Libraries/LibWeb/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc

Browser+LibWeb+WebContent: Add ability to inspect local storage

---

Userland/Applications/TextEditor/FileArgument.cpp

TextEditor: fix file opening at line and column position

---

Userland/Libraries/LibChess/UCICommand.h
Userland/Libraries/LibChess/UCIEndpoint.cpp
Userland/Libraries/LibCompress/Deflate.cpp
Userland/Libraries/LibCompress/Deflate.h

Libraries: Change enums to enum classes and constexpr variables

---

Kernel/Arch/x86/Processor.h
Kernel/Arch/x86/ProcessorInfo.h
Kernel/Arch/x86/common/Processor.cpp
Kernel/Arch/x86/common/ProcessorInfo.cpp
Kernel/GlobalProcessExposed.cpp
Userland/Applications/SystemMonitor/main.cpp
Userland/Utilities/lscpu.cpp

...and show it in lscpu, if applicable :^)

Kernel: Add hypervisor vendor ID to /proc/cpuinfo

---

Kernel/Arch/aarch64/dummy.cpp
Kernel/CMakeLists.txt
Kernel/Heap/kmalloc.cpp

Add kmalloc to the aarch64 build

Kernel: Add kmalloc.cpp to aarch64

---

Userland/Applications/ThemeEditor/main.cpp

Open theme files with ReadWrite in order to fix issue when saving. This is to address #13293

ThemeEditor: Open files with ReadWrite

---

Userland/Libraries/LibELF/DynamicLinker.cpp

dlsym() called with `RTLD_DEFAULT` (nullptr) should look up symbol in all global modules instead of only looking into the executable file

LibELF: Look up symbols in all global modules if no handle provided

---

Userland/Libraries/LibGfx/TrueTypeFont/Cmap.cpp

No behavior change for valid ttf files (which have a trailing
0xffff endCodes entry, and a sorted endCodes array).

LibGfx: Use binary search in glyph_id_for_code_point_table_4

---

Userland/Libraries/LibWeb/Bindings/ImageConstructor.cpp
Userland/Libraries/LibWeb/Bindings/OptionConstructor.cpp
Userland/Libraries/LibWeb/Bindings/OptionConstructor.h
Userland/Libraries/LibWeb/Bindings/WindowObjectHelper.h
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/HTMLOptionElement.h

This pull request adds spec comments to ImageConstructor and adds the OptionConstructor following the [spec](https://html.spec.whatwg.org/multipage/form-elements.html#dom-option)

LibWeb: Add spec comments to ImageConstructor and add OptionConstructor

---

AK/NonnullPtrVector.h
AK/Vector.h
Userland/Applications/SystemMonitor/ProcessModel.cpp
Userland/Applications/SystemMonitor/ProcessModel.h
Userland/Applications/SystemMonitor/SystemMonitor.gml
Userland/Applications/SystemMonitor/main.cpp
Userland/Libraries/LibGUI/AbstractTableView.cpp
Userland/Libraries/LibGUI/AbstractView.cpp
Userland/Libraries/LibGUI/AbstractView.h
Userland/Libraries/LibGUI/SortingProxyModel.h
Userland/Libraries/LibGUI/TreeView.cpp
Userland/Libraries/LibGUI/TreeView.h

SystemMonitor: Display processes and their threads in a tree :^)

---

AK/Array.h
Userland/Applets/Audio/main.cpp
Userland/Libraries/LibAudio/MP3Tables.h
Userland/Libraries/LibGL/Tex/Texture2D.h

This is the name that is used for every other collection type so let's
be consistent.

AK+Userland: Rename Array::front/back to first/last

---

Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimeConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimeConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimeConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp

LibJS: Consistently call observable Temporal AOs with undefined options

---

Userland/Libraries/LibX86/Instruction.cpp
Userland/Libraries/LibX86/Interpreter.h
Userland/Utilities/disasm.cpp

This tries to make us look a bit more like `objdump -d -Mintel`
Some differences I still could find are listed in the last commit
CC @skyrising I stole one of your commits from #13300, if you don't mind

LibX86+disasm: Look a bit more like objdump

---

Userland/Libraries/LibWeb/Page/EventHandler.cpp

Right clicking on an image in the browser causes two context menus to be shown. This PR ensures that only the most relevant one is rendered.
Previously, right clicking on an image shows both the Image context menu and the Page context menu:
Now only the image context menu is shown:
Right clicking on an image wrapped in an `<a>` tag shows both the **Link** context menu and the **Image** context menu:
Now only the link context menu is shown:
_Note: In this case, Chrome shows a context menu that includes actions for both link and image, which is a behaviour we could consider replicating:_
My first contribution to SerenityOS, so I'm open to constructive feedback `:^)`

LibWeb: Select correct context menu when right clicking image

---

CONTRIBUTING.md

It needs a plural instead of the possesive form.

Meta: Fix grammar in CONTRIBUTING.md

---

Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl

LibWeb: Implement/stub the CRC2D methods required by Google Maps

---

Userland/Applications/BrowserSettings/BrowserSettingsWidget.cpp

This PR adds basic URL validation upon applying browser settings.

BrowserSettings: Validate homepage URL

---

Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp

This is an editorial change in the Temporal spec.
See: https://github.com/tc39/proposal-temporal/commit/01714a5

LibJS: Update ZonedDateTime AO spec comments for structured headers

---

Userland/Games/Pong/Game.cpp
Userland/Games/Pong/Game.h
Userland/Games/Pong/main.cpp

This adds the ability to start a new game, similar to the one found in Minesweeper.
I am not sure if these commits should have been squashed. This is my first time contributing and I wanted them to be as insightful as possible.

Pong: Add "New Game" action

---

Base/usr/share/man/man1/su.md

Base: Add su(1) manpage

---

Base/etc/shellrc
Base/usr/share/shell/completion/builtin.sh
Base/usr/share/shell/completion/proxy.sh
Meta/lint-shell-scripts.sh
Userland/Libraries/LibLine/Editor.cpp
Userland/Libraries/LibLine/Editor.h
Userland/Libraries/LibLine/InternalFunctions.cpp
Userland/Libraries/LibLine/SuggestionManager.cpp
Userland/Libraries/LibLine/SuggestionManager.h
Userland/Shell/AST.cpp
Userland/Shell/AST.h
Userland/Shell/Formatter.cpp
Userland/Shell/NodeVisitor.cpp
Userland/Shell/Parser.cpp
Userland/Shell/Parser.h
Userland/Shell/Shell.cpp
Userland/Shell/Shell.h

Fun demo:
https://user-images.githubusercontent.com/14001776/163515283-20964418-9620-4d2e-a2cf-de87c865b281.mp4

LibLine+Shell: Fun things with completions and stuff

---

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp

Actually, I'll take the 66% mark, thank you test262.
TLDR:
```
30439/46029 ( 66.13%) [ ✅ 30439 ❌ 4029  ⚙️ 112   💀 9     💥️ 1995  📝 9445  ]
```

LibJS: Some more BC things

---

Userland/Libraries/LibWeb/DOM/Event.cpp
Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.cpp
Userland/Libraries/LibWeb/DOM/Node.cpp

This also implements a few more steps of compare_document_position,
and removes an invalid step from clone_node

LibWeb: Add more spec comments

---

Userland/Demos/Mandelbrot/Mandelbrot.cpp

Inspired by #13558 I added the option to export as QOI to the Mandelbrot demo. I added BMP as well for completeness.

Mandelbrot: Add BMP and QOI image formats as options for export

---

Kernel/Bus/VirtIO/Console.cpp
Kernel/Devices/AsyncDeviceRequest.h
Kernel/Devices/HID/PS2KeyboardDevice.cpp
Kernel/Graphics/VirtIOGPU/Console.cpp
Kernel/Storage/ATA/AHCIPort.cpp
Kernel/Storage/ATA/BMIDEChannel.cpp
Kernel/Storage/ATA/IDEChannel.cpp
Kernel/Storage/NVMe/NVMeInterruptQueue.cpp
Kernel/WorkQueue.cpp
Kernel/WorkQueue.h

Mainly a draft for now, but I will polish this a bit in the next few days.
Some places require us to handle such failure with specific hardware instructions to ensure next interactions with the hardware doesn't fail :)
cc @IdanHo

Kernel: Handle WorkQueue OOM cases

---

AK/URL.cpp
AK/URL.h
AK/Vector.h
Base/home/anon/.config/LaunchServer.ini
Userland/Applications/Help/MainWidget.cpp
Userland/Applications/Help/MainWidget.h
Userland/Applications/Help/main.cpp
Userland/Shell/AST.cpp
Userland/Shell/Builtin.cpp
Userland/Shell/Shell.cpp
Userland/Shell/Shell.h

https://user-images.githubusercontent.com/30666851/159205988-3cac21c3-7080-490a-96bb-7834c866320e.mp4

Shell+LaunchServer: Hyperlink help page for commands in shell

---

Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp

The browser demos didn't work, we can't have that now can we

LibWasm: Two tiny validation fixes

---

Meta/run.sh

This now also works on Windows and we rename it from KVM to Virtualization.

Meta: Generalize virtualization toggle

---

Ports/libyaml/package.sh

I'm not sure how the other link got into the commit.

Ports/libyaml: Fix download location

---

Ports/.hosted_defs.sh
Ports/.port_include.sh
Ports/build_installed.sh

And by yak-stension make .hosted_defs.sh usable outside of .port_includes.sh

Ports: Fix build_installed.sh script

---

Documentation/VSCodeConfiguration.md

This should make clangd work very well. I totally forgot to add this...

Documentation: Add more clangd configuration options

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp

HackStudio: Update window close button on document change

---

Userland/Libraries/LibCore/EventLoop.cpp

Forgot to remove it - this was resolved in commit f25123df66.

LibCore: Remove fixed EventLoop FIXME

---

Kernel/API/Syscall.h
Kernel/API/SyscallString.h
Tests/Kernel/fuzz-syscalls.cpp
Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp
Userland/Utilities/functrace.cpp
Userland/Utilities/strace.cpp
Userland/Utilities/syscall.cpp

Kernel: Stop requiring working malloc for syscall.h includes

---

Userland/Services/DHCPClient/DHCPv4Client.cpp

DHCPClient: Don't crash if DHCP options contain no gateway

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Date.cpp
Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/Value.cpp

Upstream changes from 2 Mar 2022 - Today

LibJS: Editorial changes, part 3

---

Documentation/EventLoop.md

This was long overdue; as of writing this I saw another question about something that seems obvious to me who spent a bunch of time with the system.
Hopefully this is generic enough so that we can change things without this getting out of date.

Documentation: Document how the event loop works & what it does

---

Userland/Services/WindowServer/Menu.cpp

|-|-|
| ![image](https://user-images.githubusercontent.com/19366641/166729483-aaa5e1c6-e359-42e7-a243-80f5b282ef2a.png) | ![image](https://user-images.githubusercontent.com/19366641/166730060-b519e6b8-14b1-4cf2-ab1f-aa2f8b1db8c6.png) |

WindowServer: Take vertical menu offset into account when adjusting pos

---

Kernel/Bus/PCI/IDs.h
Kernel/CMakeLists.txt
Kernel/Graphics/DisplayConnector.cpp
Kernel/Graphics/GraphicsManagement.cpp
Kernel/Graphics/VMWare/Console.cpp
Kernel/Graphics/VMWare/Console.h
Kernel/Graphics/VMWare/Definitions.h
Kernel/Graphics/VMWare/DisplayConnector.cpp
Kernel/Graphics/VMWare/DisplayConnector.h
Kernel/Graphics/VMWare/GraphicsAdapter.cpp
Kernel/Graphics/VMWare/GraphicsAdapter.h
Meta/run.sh

So after #13845 is merged, we can simply have support for VMWare SVGA 2 Graphics adapter :)

Kernel/Graphics: Add support for VMWare Graphics

---

Ports/libmad/package.sh

This fixes the build on MacOS.

Ports/libmad: Use fresh config.guess

---

Userland/Libraries/LibJS/Runtime/Date.h
Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Now.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp

Two fixes for spec bugs still outstanding. Knowingly regresses one test262 test, will be fixed with > 100 others in the next PR. :^)

LibJS: More Temporal editorial changes

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Token.cpp
Userland/Libraries/LibWeb/CSS/Selector.h

With this we now pass all An+B parsing tests on wpt.live 🎉

LibWeb: Various fixes to the An+B syntax

---

Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp

DisplaySettings: Make the copy action copy the background path as url

---

Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.cpp
Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.h

I'm a bit of a newbie in c++ so this code might be not good at all :) tried my best.

KeyboardSettings: Use double click on keymap list to activate keymap

---

AK/HashMap.h
AK/HashTable.h
AK/Vector.h
Userland/Libraries/LibGUI/ModelSelection.cpp
Userland/Libraries/LibGUI/ModelSelection.h

Saw it in a video the other day and decided to use it as a chance to contribute :^)

AK+LibGUI: Pass predicate to *_matching() methods by const reference

---

Base/usr/share/man/man5/GML-Widget-TabWidget.md
Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/BrowserWindow.gml
Userland/Applications/PixelPaint/MainWidget.cpp
Userland/Applications/PixelPaint/PixelPaintWindow.gml
Userland/Demos/WidgetGallery/GalleryGML/Window.gml
Userland/Demos/WidgetGallery/GalleryWidget.cpp
Userland/Libraries/LibGUI/TabWidget.cpp
Userland/Libraries/LibGUI/TabWidget.h

- close_button_enabled, to show 
- show_tab_bar
- reorder_allowed

LibGUI: Expose more TabWidget properties to GML

---

Userland/Libraries/LibSoftGPU/Device.cpp

According to the OpenGL spec, we're expected to clamp the fragment depth values to the range `0.f..1.f` for all polygons.
This fixes Z-fighting issues with the sky in Quake 3.
Before:
After:

LibSoftGPU: Clamp polygon depth values to `0.f..1.f`

---

.github/workflows/cmake.yml
.github/workflows/pvs-studio-static-analysis.yml
.github/workflows/sonar-cloud-static-analysis.yml
Meta/lint-ports.py
Toolchain/BuildIt.sh

This is getting embarrassing...

Toolchain+CI+Meta: Unbreak CI

---

Userland/Applications/PixelPaint/CMakeLists.txt
Userland/Applications/PixelPaint/IconBag.cpp
Userland/Applications/PixelPaint/IconBag.h
Userland/Applications/PixelPaint/Image.cpp
Userland/Applications/PixelPaint/Image.h
Userland/Applications/PixelPaint/Layer.cpp
Userland/Applications/PixelPaint/Layer.h
Userland/Applications/PixelPaint/MainWidget.cpp
Userland/Applications/PixelPaint/ResizeImageDialog.cpp
Userland/Applications/PixelPaint/ResizeImageDialog.gml
Userland/Applications/PixelPaint/ResizeImageDialog.h
Userland/Libraries/LibGUI/SpinBox.cpp
Userland/Libraries/LibGUI/SpinBox.h

This recycles @ClysmiC s PR from early April.

PixelPaint: Add Resize Image dialog

---

Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
Userland/Libraries/LibJS/Runtime/GlobalEnvironment.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/CalendarConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
Userland/Libraries/LibJS/Runtime/Temporal/InstantConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimeConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTimeConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimeConstructor.cpp
Userland/Libraries/LibJS/SyntheticModule.cpp

Would definitely appreciate help with the FIXME I left. Apply this diff on top of the PR to get the [implementation I was working on unsuccessfully](https://gist.github.com/linusg/a4543e5f554a615fd1c1ee5dc50790e9) (fails one test in test-js) - I'm sure it's a simple fix, but I can't figure it out right now.
https://gist.github.com/linusg/331993c1d3bc3bd6b04f73deca69013c

LibJS: ECMA-262 / Temporal editorial changes

---

Meta/build-manpages-website.sh
Meta/convert-markdown-links.lua

Meta: Update manpages website build script to handle non-icon images

---

Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.cpp
Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.h

SoundPlayer: Replace hideous toolbar buttons

---

Ports/.strip_env.sh

For all the people that don't like plain `vi` for editing patches.

Ports: Don't unset `EDITOR`

---

Kernel/Net/NetworkTask.cpp

For the same reason we ignore interfaces without an IP address when
choosing where to send a route, we should also ignore interfaces without
IP addresses when updating the ARP table on incoming packets from
local addresses.
On an interface with a null address, the mask checking would always
result in zero, which resulted in the system updating the ARP table on
almost every incoming packet from any address (private or public).
This patch fixes this behavior by only applying this check to interfaces
with valid addresses and now the ARP table won't get constantly
hammered.
Closes #13713

Kernel: Ignore interfaces without an IP address when updating ARP

---

Userland/Applets/Keymap/KeymapStatusWindow.cpp
Userland/Applets/Keymap/main.cpp
Userland/Applets/WorkspacePicker/DesktopStatusWindow.cpp
Userland/Applets/WorkspacePicker/main.cpp
Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.h
Userland/Libraries/LibGUI/CMakeLists.txt
Userland/Libraries/LibGUI/ConnectionToWindowManagerServer.cpp
Userland/Libraries/LibGUI/ConnectionToWindowManagerServer.h
Userland/Libraries/LibGUI/Event.h
Userland/Libraries/LibGUI/Window.cpp
Userland/Services/Taskbar/TaskbarButton.cpp
Userland/Services/Taskbar/TaskbarWindow.cpp
Userland/Services/Taskbar/TaskbarWindow.h
Userland/Services/Taskbar/main.cpp
Userland/Services/WindowServer/WindowManager.cpp
Userland/Services/WindowServer/WindowManager.h
Userland/Services/WindowServer/WindowManagerClient.ipc

This PR adds the super+D keyboard shortcut. This has the same effect as clicking the "Show Desktop" button from the taskbar. This shortcut already exists in Windows.

Taskbar+Desktop: Add super+D keyboard shortcut

---

Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp

Accessing last() if there are no elements makes the browser crash :^)

LibWeb: Fix Array OOBs in the HTMLTokenizer

---

Userland/Libraries/LibWeb/DOM/Node.cpp

In this case, "Do nothing" means do nothing *extra* aside from creating a new instance.

LibWeb: Support DocumentFragments in Node.prototype.cloneNode

---

Userland/Applications/MouseSettings/CMakeLists.txt
Userland/Applications/MouseSettings/Highlight.gml
Userland/Applications/MouseSettings/HighlightPreviewWidget.cpp
Userland/Applications/MouseSettings/HighlightPreviewWidget.h
Userland/Applications/MouseSettings/HighlightWidget.cpp
Userland/Applications/MouseSettings/HighlightWidget.h
Userland/Applications/MouseSettings/main.cpp
Userland/Libraries/LibCore/ConfigFile.cpp
Userland/Libraries/LibCore/ConfigFile.h
Userland/Services/WindowServer/Compositor.cpp
Userland/Services/WindowServer/ConnectionFromClient.cpp
Userland/Services/WindowServer/ConnectionFromClient.h
Userland/Services/WindowServer/ScreenBackend.h
Userland/Services/WindowServer/WindowManager.cpp
Userland/Services/WindowServer/WindowManager.h
Userland/Services/WindowServer/WindowServer.ipc

**Demo**
https://user-images.githubusercontent.com/11597044/172023449-8435cc1c-d1e3-4e44-9b36-d9f1a1956736.mp4
Antialiased, of course.

LibCore+WindowServer+MouseSettings: Add cursor highlighting!

---

Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp

Previously, floating elements computed the width by only using the `width` property. Now, they will also use the `min-width` and `max-width` properties. :^)
The new steps are from “[10.4. Minimum and maximum widths: ‘min-width’ and ‘max-width’](https://drafts.csswg.org/css2/#min-max-widths)” in the CSS 2 spec.
Found it when looking at curl.se.
master | this
:-:|:-:

LibWeb: Calculate floating elements width using min- and max-width

---

Base/etc/motd

It is already the middle of 2022, motd needs some lovin' ;)

Base: Update /etc/motd (c) from 2018-2021 to 2018-2022

---

Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp

LibWeb+LibGfx: Paint background border radius antialiased

---

Kernel/API/POSIX/netinet/in.h
Ports/.port_include.sh
Userland/Libraries/LibC/ctype.h
Userland/Libraries/LibC/ucontext.h
Userland/Libraries/LibELF/DynamicLinker.cpp
Userland/Libraries/LibPthread/semaphore.cpp

This PR Splits out the serenity fixes from @TSultanov 's port of OpenJDK (and my adaptation of the same)

Kernel+Libraries: Assorted patches required by OpenJDK

---

Base/res/html/misc/border-radius.html
Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
Userland/Libraries/LibGfx/AntiAliasingPainter.h
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
Userland/Libraries/LibWeb/Painting/BackgroundPainting.h
Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
Userland/Libraries/LibWeb/Painting/BorderPainting.h
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h

**Demo:**
__Left:__ Google Chrome | __Middle:__ MDN (Chrome again) | __Right:__ LibWeb
It's a very close match :^)

LibWeb+LibGfx: Support elliptical border radii :^)

---

Base/usr/share/man/man1/pwd.md

This patch adds a manual page for pwd(1).
Related to #11311.

Base: Add a man-page for pwd(1)

---

Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
Userland/Libraries/LibGfx/AntiAliasingPainter.h
Userland/Libraries/LibWeb/Painting/BorderPainting.cpp

|  Before                                                                                                                                       | After                                                                                                                                         |
|-----------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot from 2022-06-18 01-57-39](https://user-images.githubusercontent.com/11597044/174416526-0f9921de-58e4-429f-a491-2afa7a68a393.png) | ![Screenshot from 2022-06-18 …

LibWeb+LibGfx: Actually dot dotted borders :^)

---

Userland/Libraries/LibGUI/Dialog.cpp

When a dialog is created the position is checked against the Desktop's
rect and repositioned to be entirely visible. If the dialog is larger
than the desktop's rect it is just centered.
Before (repro by starting serenity, opening ImageViewer and then File->Open): 
After:

LibGUI: Prevent CenterWithinParent Dialogs from appearing offscreen

---

Base/usr/share/man/man7/proc.md

(Added this and forgot about the man pages :sweat_smile:)

Base: Document /proc/{pid}/children in proc(7) manpage

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp

Hello all!
This is my first commit to SerenityOS, so let me know if there is anything I should fix or change for this commit, even if it's just a single line change. :)
Thank you!

LibWeb/CSS: Check for NULL block statement when parsing font-face rule

---

Userland/Shell/Shell.cpp

As noted by the comment, a stray SIGCHLD can make the shell go into an
infinite loop, pretend the signal doesn't exist after trying 10 times in
5ms.

Shell: Ignore SIGCHLD after a few unsuccessful attempts at handling it

---

Userland/Libraries/LibGfx/Filters/FastBoxBlurFilter.cpp

Change from 4 vectors of u8 to a single vector of a struct of 4
u8. Since all the accesses are on the same indicies into each vector
the cache pressure is decreased by co-locating the data.
When scrolling up and down in the `box-shadow` example page the
profile changes from about 75% of the function calls being in
`apply_single_pass()` to only about 70% on my machine.

LibGfx: Increase cache-friendliness in FastBoxBlurFilter

---

SECURITY.md

Meta: Add a security policy

---

AK/IntegralMath.h
AK/Math.h
Userland/Libraries/LibGfx/CMakeLists.txt
Userland/Libraries/LibGfx/Filters/StackBlurFilter.cpp
Userland/Libraries/LibGfx/Filters/StackBlurFilter.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp

| Before                                                                                                                                        | After                                                                                                                                         | Chromium                                                                                                                                      |
|-----------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------- …

LibWeb+LibGfx: Implement StackBlurFilter and use for shadow painting (and some fun fixes)

---

Userland/DevTools/SQLStudio/MainWidget.cpp
Userland/DevTools/SQLStudio/MainWidget.h

Adds button to execute scripts and a table to display the results.

SQLStudio: Execute scripts and show results

---

Userland/Utilities/js.cpp

js: Pretty-printing refactor, fixes, and additions

---

AK/AllOf.h
AK/AnyOf.h
AK/Base64.h
AK/BinaryHeap.h
AK/BinarySearch.h
AK/BitCast.h
AK/BitStream.h
AK/Find.h

- AllOf
- AnyOf
- Base64
- BinaryHeap
- BinarySearch
- BitCast
- BitStream
- Find

AK: Add `nodiscard` attribute

---

Documentation/FAQ.md

The original wording had a different meaning, that I'm pretty sure was not the intended one. :^)

Documentation: Improve grammar in 2 paragraphs

---

Kernel/CMakeLists.txt
Kernel/Storage/ATA/AHCIController.cpp
Kernel/Storage/ATA/AHCIController.h
Kernel/Storage/ATA/AHCIInterruptHandler.cpp
Kernel/Storage/ATA/AHCIInterruptHandler.h
Kernel/Storage/ATA/AHCIPort.cpp
Kernel/Storage/ATA/AHCIPort.h
Kernel/Storage/ATA/AHCIPortHandler.cpp
Kernel/Storage/ATA/AHCIPortHandler.h

I started this evening to work on cleanup on the AHCI code. This is all part of a process I do before #11081 can be really merged.
There will be probably more cleanups in the near future :)

Kernel: Small AHCI cleanups

---

Meta/CMake/Superbuild/CMakeLists.txt
Meta/build-image-qemu.sh
Userland/Applications/Terminal/main.cpp
Userland/DevTools/HackStudio/main.cpp
Userland/Services/TelnetServer/main.cpp
Userland/Shell/Shell.cpp

Meta(+Userland): First batch of "Serenity on Serenity" build system changes

---

Userland/Applications/FileManager/DirectoryView.cpp

Processes spawned by FileManager (e.g. through double-click) now set their PGID to that of the session leader. It allows the filemanage instance to be killed without propagating the signal to the new process
Closes #5306

FileManager: Change PGID of spawned processes

---

Base/usr/share/man/man1/uptime.md

Base: Add uptime(1) manpage

---

Tests/LibRegex/Regex.cpp
Userland/Libraries/LibRegex/RegexByteCode.cpp
Userland/Libraries/LibRegex/RegexOptimizer.cpp

Fixes :star: stuff :star: :P
This makes my life more difficult with the unicodeSets proposal, but fixing bugs is more important than implementing a proposal right now.
cc @Lubrsi

LibRegex: Treat inverted Compare entries as disjunctions 

---

Userland/Libraries/LibGfx/PNGWriter.cpp

This should make the CI happier now.
Marking as draft because i very don't trust myself.

LibGfx: Initialize dummy scanline using memset

---

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodePluralRules.cpp
Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Intl/PluralRules.cpp
Userland/Libraries/LibJS/Runtime/Intl/PluralRules.h
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.h
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.prototype.selectRange.js
Userland/Libraries/LibUnicode/PluralRules.cpp
Userland/Libraries/LibUnicode/PluralRules.h

`selectRange` is part of the NumberFormat v3 proposal:
https://github.com/tc39/proposal-intl-numberformat-v3

LibJS: Implement Intl.PluralRules.prototype.selectRange

---

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.h
Userland/Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormatPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.js
Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.format.js
Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.formatToParts.js
Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.resolvedOptions.js
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.js
Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.prototype.resolvedOptions.js
Userland/Utilities/js.cpp

It's a pretty big proposal, so this starts with just parsing the new options and a couple of low hanging fruit.

LibJS: Begin implementing Intl.NumberFormat V3

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/main.cpp
Userland/Libraries/LibCore/ArgsParser.cpp
Userland/Libraries/LibCore/ArgsParser.h
Userland/Libraries/LibCore/File.cpp
Userland/Libraries/LibCore/File.h
Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp
Userland/Shell/Builtin.cpp
Userland/Utilities/cp.cpp
Userland/Utilities/du.cpp
Userland/Utilities/grep.cpp
Userland/Utilities/nl.cpp
Userland/Utilities/pro.cpp
Userland/Utilities/profile.cpp
Userland/Utilities/run-tests.cpp
Userland/Utilities/test-unveil.cpp
Userland/Utilities/top.cpp
Userland/Utilities/wasm.cpp
Userland/Utilities/watch.cpp

(Hopefully) one less port that is needed for self-hosting.

cp+LibCore: Implement the granular `--preserve` flag

---

Userland/Libraries/LibVT/TerminalWidget.cpp

LibVT: Show application display name when hovered over, if available

---

Userland/Applications/BrowserSettings/BrowserSettingsWidget.gml
Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.gml
Userland/Applications/CrashReporter/CrashReporterWindow.gml
Userland/Applications/KeyboardSettings/Keyboard.gml
Userland/Applications/KeyboardSettings/KeymapDialog.gml
Userland/Applications/MailSettings/MailSettingsWidget.gml
Userland/Applications/MouseSettings/Highlight.gml
Userland/Applications/MouseSettings/Mouse.gml
Userland/Applications/MouseSettings/Theme.gml
Userland/Applications/PixelPaint/FilterGallery.gml
Userland/Services/Taskbar/TaskbarWindow.cpp

This fixes some regressions (particularly that the task bar buttons were not centered vertically) and improves overall consistency in other places.
This has really shown me that we ought to write some UI guidelines at some point.

Userland: Layout fixes and improvements

---

Userland/Libraries/LibGUI/ColorPicker.cpp

LibGUI: Sync ColorPicker's color slider with other color widgets

---

Toolchain/BuildMold.sh

Toolchain: Update mold to 1.3.1

---

Userland/Libraries/LibWeb/DOM/Node.cpp

Step 19 of node removal was missing, which allows the mutations of the
descendants of the removed node to still be observed by the parent.
Step 20 of node removal queued the mutation record for the removed
node instead of it's parent. Since queuing takes place after the node
is removed from the tree, the mutation record would be lost as the only
inclusive ancestor of the node at this point is only the node itself.
Fixes #14567.
New test results:

LibWeb: Fix queuing mutation records for node removal

---

AK/BumpAllocator.h
AK/StackInfo.cpp
Userland/Libraries/LibCore/DateTime.cpp
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibGfx/Bitmap.cpp
Userland/Libraries/LibJS/Bytecode/BasicBlock.cpp

This does not *entirely* supersede #14369, as I'm only concerned with what's necessary to get Ladybird to run on FreeBSD.
See https://github.com/awesomekling/ladybird/issues/19
These commits should probably be squashed...

[WIP] Get LibWeb compiling on FreeBSD

---

Kernel/Locking/Mutex.cpp

The interrupts enabled check in the Kernel mutex is there so that we don't lock mutexes within a spinlock, because mutexes reenable interrupts and that will mess up the spinlock in more ways than one if the thread moves processors. This check is guarded behind a debug flag because it's too hard to fix all the problems at once, but we regressed and weren't even getting to init stage 2 with it enabled. With this commit, we get to stage 2 again. In early boot, there are no interrupts enabled and spinlocks used, so we can sort of kind of safely ignore the interrupt state. There might be a better solution with another boot state flag that checks whether APs are up (because they have interrupts enabled from the start) but that seems overkill.
This PR makes the Kernel progress back into init …

Kernel: In Mutexes, don't check that interrupts are enabled during early boot

---

Documentation/QtCreatorConfiguration.md
Documentation/README.md

Back by popular demand*, it's #14295! Fixed up the links that had changed, and rearranged a couple of them.
<small>* For very small values of "popular"</small>

Documentation: Add a table of contents for Documentation

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator/IDLGenerators.cpp

This fixes a bug where an ArrayBuffer passed to the Blob constructor would just be stringified to: "[object ArrayBuffer]".

LibWeb/IDL: Handle passing ArrayBuffer to an IDL union type

---

Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.round.js

Implements these two changes:
- https://github.com/tc39/proposal-temporal/commit/6f04074
- https://github.com/tc39/proposal-temporal/commit/374305c

LibJS: Implement a couple of normative Temporal changes

---

Base/usr/share/man/man1/du.md
Userland/Utilities/du.cpp

Now we no longer try to fit Serenity into a 30MB disk image.

du: More bug fixes

---

Base/res/html/misc/border-radius.html
Userland/Libraries/LibWeb/Painting/CanvasPaintable.cpp
Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h

| Before                                                                                                                                        | After                                                                                                           |
|-----------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![Screenshot from 2022-07-26 20-36-14](https://user-images.githubusercontent.com/11597044/181100878-5d3dba87-3585-4a05-94d8-72601458c7ea.png) | ![image](https://user-images.githubusercontent.com/11597044/181100831-c41dea18-ffaf-48a4-92c4-b92f1258abbe.png) |
| …

LibWeb+Base: More more more border-radius fixes

---

Base/usr/share/man/man5/af.md
Base/usr/share/man/man5/font.md
Base/usr/share/man/man5/ini.md
Base/usr/share/man/man5/ipc.md
Base/usr/share/man/man5/pp.md

Documentation: Better file formats documentation

---

Userland/Utilities/lsusb.cpp

In case we failed to open /res/usb.ids or the user requested to not use
that file, we simply don't try to resolve the USB IDs and print them
without any identification.

Utilities/lsusb: Allow the utility to work without existing USB IDs file

---

Base/usr/share/man/man1/About.md
Base/usr/share/man/man1/AnalogClock.md
Base/usr/share/man/man1/Assistant.md
Base/usr/share/man/man1/Browser.md
Base/usr/share/man/man1/Calculator.md
Base/usr/share/man/man1/Calendar.md

Two months ago I started writing manpages with the intention of writing up all the manpages missing from the system. That got boring really quickly and I forgot about them soon after. I have no intention of writing any more at this time, so I'm just submitting what I have. 
Related to #11311

Base: Add more manpages

---

Userland/Libraries/LibC/time.cpp
Userland/Libraries/LibCore/DateTime.cpp

This also avoids all the BSD issues we were having with `timezone` / `altzone` / `daylight` in `Core::DateTime`

LibC+LibCore: Use tm_isdst to handle time zone offsets in DST

---

Userland/Applications/HexEditor/HexEditor.cpp
Userland/Applications/HexEditor/HexEditor.h
Userland/Applications/HexEditor/HexEditorWidget.cpp

Noticed an issue while trying to use Hex Editor... and then found some more issues whilst looking at the code!

HexEditor: A random assortment of improvements

---

Userland/Libraries/LibMarkdown/CodeBlock.cpp
Userland/Libraries/LibMarkdown/CodeBlock.h
Userland/Libraries/LibMarkdown/ContainerBlock.cpp
Userland/Libraries/LibMarkdown/Heading.cpp

LibMarkdown: Improvements

---

Userland/Applications/FileManager/FileManagerWindow.gml
Userland/Applications/FontEditor/FontEditorWindow.gml
Userland/Applications/Help/HelpWindow.gml
Userland/Libraries/LibGUI/Splitter.cpp
Userland/Libraries/LibGUI/Splitter.h

LibGUI+Applications: Govern Splitter resizing by opportunistic growth

---

AK/NumberFormat.h
Userland/Games/Minesweeper/CMakeLists.txt
Userland/Games/Minesweeper/CustomGameDialog.cpp
Userland/Games/Minesweeper/Field.cpp
Userland/Games/Minesweeper/MinesweeperCustomGameWindow.gml
Userland/Games/Minesweeper/MinesweeperWindow.gml
Userland/Games/Minesweeper/main.cpp
Userland/Libraries/LibGUI/ImageWidget.cpp

Minesweeper: Update GML and fix layout issues 

---

Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp

Draft until https://github.com/tc39/proposal-temporal/pull/2370 is merged, as I don't want to make another PR.

LibJS: Correct BalanceDurationRelative algorithm

---

Kernel/Arch/aarch64/RPi/UART.cpp
Kernel/Arch/aarch64/RPi/UART.h
Kernel/Arch/aarch64/linker.ld

I've had these changes laying around for quite sometime, but never upstreamed them, so here we go!
These 2 commits do not completely fix the boot of the aarch64 kernel for bare-metal, IIRC there are some still alignment issues to be ironed out. But at least we are closer now :)

Kernel: Some small fixes found when running the aarch64 kernel bare-metal

---

Kernel/Memory/MemoryManager.cpp

This deadlock was introduced with the creation of this API. The lock
order is such that we always need to take the page directory lock
before we ever take the MM lock.
This function violated that, as both Region creation and region
destruction require the pd and mm locks, but with the mm lock
already acquired we deadlocked with SMP mode enabled while other
threads were allocating regions.
With this change SMP boots to the desktop successfully for me,
(and then subsequently has other issues). :^)

Kernel: Fix SMP deadlock in MM::allocate_contiguous_physical_pages

---

Kernel/Process.cpp
Kernel/Syscalls/alarm.cpp
Kernel/Thread.cpp
Kernel/TimerQueue.cpp

A few small things I had lying around.

Kernel: A few minor fixes

---

Userland/DevTools/HackStudio/EditorWrapper.cpp
Userland/DevTools/HackStudio/HackStudio.h
Userland/DevTools/HackStudio/HackStudioWidget.h
Userland/DevTools/HackStudio/main.cpp

HackStudio: Fix update modified document on tab widget

---

Base/usr/share/man/man1/Browser.md
Userland/Applications/Browser/main.cpp

This lets you run `br example.com wikipedia.org some/local/file.html` in one go and have them all opened as tabs.

Browser+Base: Allow opening multiple URLs at once from command line

---

Userland/Applications/FileManager/main.cpp

This adds a much quicker way to set the background image.

FileManager: Add 'Set as Desktop Wallpaper' action to file context menu

---

Kernel/Arch/Spinlock.h
Kernel/Arch/aarch64/RPi/Timer.cpp
Kernel/Arch/aarch64/TrapFrame.h
Kernel/Arch/aarch64/init.cpp
Kernel/Arch/aarch64/kprintf.cpp
Kernel/CMakeLists.txt
Kernel/Graphics/Console/BootFramebufferConsole.cpp
Kernel/Graphics/Console/BootFramebufferConsole.h

Kernel: Add aarch64 support to `BootFramebufferConsole`

---

Kernel/Memory/AddressSpace.cpp

At the point at which we try to map the Region it was already added to the Process region tree, so we have to make sure to remove it before freeing it in the mapping failure path, otherwise the tree will contain a dangling pointer to the free'd instance.
This fixes the original kernel panic which resulted in the newly added InodeVMObject purging mechanism.

Kernel: Remove regions from the region tree after failing to map them

---

Userland/Applications/TextEditor/MainWidget.cpp
Userland/Applications/TextEditor/MainWidget.h

ShowMessageIfNoResutls -> ShowMessageIfNoResults

TextEditor: Correct typo in MainWidget.{cpp,h}

---

Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

This is a basic attempt at trying to handle parent container case `justify-content: flex-end`.

LibWeb: Render flex line items RTL (reversed items) for FlexEnd

---

Userland/Services/WindowServer/Menu.cpp
Userland/Services/WindowServer/MenuManager.cpp
Userland/Services/WindowServer/MenuManager.h

This guy was always pretty annoying at the edge of the screen:
Now:
https://user-images.githubusercontent.com/66646555/184892536-2eca8a43-135e-4b67-b1ec-1c7b400a0fe1.mp4

WindowServer: Improved submenu ergonomics

---

Kernel/Memory/AddressSpace.cpp

Kernel/Memory: Use scope guard to clean a region if failed to map it

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Runtime/MathObject.cpp
Userland/Libraries/LibJS/Tests/builtins/Math/Math.cosh.js
Userland/Libraries/LibJS/Tests/classes/class-inheritance.js

The class fix is a temporary fix until we rewrite class_definition_evaluation.

LibJS: Fix Math.cosh extreme values and class fix

---

Base/res/themes/Chillychilly.ini

This is the calming blue-green desktop background I'm going for when designing Chillychilly.
Updating theme to sport the proper background color.

Base: Update Chillychilly theme use calming background

---

Userland/Libraries/LibCore/SharedCircularQueue.h

This deadlock would incorrectly change the queue from almost empty to full on dequeue because someone else could empty the queue after we had checked its non-emptyness. The test would deadlock on this, which doesn't happen anymore.

LibCore: Fix deadlock in SharedSingleProducerCircularQueue

---

Userland/Applications/PixelPaint/Image.cpp
Userland/Applications/PixelPaint/Layer.cpp

Saw Andreas latest video ([https://www.youtube.com/watch?v=V8jpvQsVAKQ](link)) and thought of a way to reduce the verbosity :^)

PixelPaint: Reduce verbosity of crop to content feature

---

Base/usr/share/man/man1/Eyes.md
Userland/Demos/Eyes/EyesWidget.h
Userland/Demos/Eyes/main.cpp

This clip should speak to the important of this feature:
[screen-capture - 2022-08-24T211528.530.webm](https://user-images.githubusercontent.com/11597044/186517342-1262af3d-1ddc-4b2e-8c3d-2d5800426504.webm)

Eyes: Add an option to show/hide the window frame

---

Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Userland/Libraries/LibGUI/ConnectionToWindowManagerServer.cpp
Userland/Libraries/LibGUI/ConnectionToWindowManagerServer.h
Userland/Libraries/LibGUI/Event.h
Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp
Userland/Services/Taskbar/TaskbarWindow.cpp
Userland/Services/Taskbar/WindowList.h
Userland/Services/WindowServer/ConnectionFromClient.cpp
Userland/Services/WindowServer/WMConnectionFromClient.cpp
Userland/Services/WindowServer/Window.cpp
Userland/Services/WindowServer/WindowManager.cpp
Userland/Services/WindowServer/WindowManager.h
Userland/Services/WindowServer/WindowManagerClient.ipc
Userland/Services/WindowServer/WindowSwitcher.cpp

WindowServer+Elsewhere: Modal fix-ups

---

Tests/LibCrypto/TestBigInteger.cpp
Tests/LibWasm/test-wasm.cpp
Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.cpp
Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.h
Userland/Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
Userland/Libraries/LibCrypto/BigInt/UnsignedBigInteger.h
Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
Userland/Libraries/LibJS/Runtime/BigInt.cpp
Userland/Libraries/LibJS/Runtime/Intl/MathematicalValue.cpp
Userland/Libraries/LibJS/Runtime/NumberConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Now.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibWeb/WebAssembly/WebAssemblyObject.cpp

Since these are mostly used by Temporal let me know if I'm messing things up there.

LibCrypto + LibJS: Add more BigInt <-> Double conversions and use them

---

Base/usr/share/man/man1/Terminal.md

Simplify terminal document by focusing on relevant information.

Base: Update Terminal's help documentation

---

Base/usr/share/man/man1/Mouse.md
Base/usr/share/man/man1/MouseSettings.md

Base: Add new Mouse + MouseSettings help

---

Base/usr/share/man/man1/Magnifier.md

Base: Add new Magnifier help documentation

---

.prettierignore
AK/JsonParser.cpp
Tests/AK/TestJSON.cpp
Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
Userland/Libraries/LibJS/Runtime/ModuleEnvironment.cpp
Userland/Libraries/LibJS/Runtime/ModuleEnvironment.h
Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp
Userland/Libraries/LibJS/SourceTextModule.cpp
Userland/Libraries/LibJS/Tests/loops/for-await-of.js
Userland/Libraries/LibJS/Tests/modules/accessing-lex-import-before-decl.mjs
Userland/Libraries/LibJS/Tests/modules/accessing-var-import-before-decl.mjs
Userland/Libraries/LibJS/Tests/modules/anon-func-decl-default-export.mjs
Userland/Libraries/LibJS/Tests/modules/basic-modules.js
Userland/Libraries/LibJS/Tests/modules/default-and-star-export-indirect-string.mjs
Userland/Libraries/LibJS/Tests/modules/exporting-from-failing.mjs
Userland/Libraries/LibJS/Tests/modules/exporting-nothing-from-failing.mjs
Userland/Libraries/LibJS/Tests/modules/failing.mjs
Userland/Libraries/LibJS/Tests/modules/importing-failing-module.mjs
Userland/Libraries/LibJS/Tests/modules/multiple-star-imports.mjs
Userland/Libraries/LibJS/Tests/modules/namespace-order.mjs
Userland/Libraries/LibJS/Tests/modules/re-export-namespace-via-binding.mjs
Userland/Libraries/LibJS/Tests/modules/string-import-namespace-indirect.mjs

I found a bunch of mistakes/todos in module code
Also includes JSON parsing????

LibJS(+AK): Fix most remaining module problems

---

Meta/grub-ebr.cfg
Meta/grub-gpt.cfg
Meta/grub-mbr.cfg
Meta/run.sh

Meta: Use correct boot device selections when using GRUB images

---

Toolchain/Dockerfile

Toolchain: Update Dockerfile to ubuntu:22.10

---

Userland/Libraries/LibGUI/ColumnsView.cpp
Userland/Libraries/LibGUI/ColumnsView.h

This pull request adds the ability to select multiple entries in a column using a rubber band selection.
Currently the implementation is lacking support for expanding a selection using the ctrl modifier.
https://user-images.githubusercontent.com/42888162/188320097-ac63d4f4-f6c3-41b4-b185-73d639bf2d8c.mp4

LibGUI: Implement basic rubber band selections in ColumnsView 

---

Base/.gitignore
Meta/CMake/unicode_data.cmake

Meta: Don't generate emoji.txt into the source tree

---

Userland/Libraries/LibGfx/Painter.cpp

Our bilinear scaling logic worked well for upscaling, but during downscaling the bitmap was often shifted one pixel to the bottom right. This is a common problem, described here in more detail:
https://bartwronski.com/2021/02/15/bilinear-down-upsampling-pixel-grids-and-that-half-pixel-offset/
The symptoms can be seen in these scaled mipmap textures; the lower resolution versions shift down and to the right:
https://user-images.githubusercontent.com/3210731/188633333-56429673-f35e-4f70-b2a4-805435a9a931.mp4
Fix it by calculating coordinate shift values that align the pixel's boundaries between the source and target pixels before selecting the source pixels to interpolate.
---
Example downscale using this updated algorithm:
Source image:
Old behavior, scaled down to 17%:
New behavior, …

LibGfx: Correctly shift pixels during bilinear blend

---

Userland/Libraries/LibGUI/CMakeLists.txt
Userland/Libraries/LibGUI/EmojiInputDialog.cpp
Userland/Libraries/LibGUI/EmojiInputDialog.gml
Userland/Libraries/LibGUI/EmojiInputDialog.h

LibGUI: Wrap the EmojiInputDialog in a scrollable container and add a search box

---

Userland/Applications/Browser/BookmarksBarWidget.cpp
Userland/Libraries/LibGUI/AbstractButton.cpp
Userland/Libraries/LibGUI/Button.cpp
Userland/Libraries/LibGUI/Button.h
Userland/Libraries/LibGUI/Menu.cpp
Userland/Libraries/LibGUI/Menu.h
Userland/Libraries/LibGUI/Statusbar.cpp
Userland/Libraries/LibGUI/Toolbar.cpp
Userland/Services/Taskbar/TaskbarButton.cpp
Userland/Services/WindowServer/ConnectionFromClient.cpp
Userland/Services/WindowServer/ConnectionFromClient.h
Userland/Services/WindowServer/Menu.cpp
Userland/Services/WindowServer/Menu.h
Userland/Services/WindowServer/WindowFrame.cpp
Userland/Services/WindowServer/WindowServer.ipc

LibGUI+Elsewhere: Buncha button blemishes

---

Userland/Libraries/LibSoftGPU/Device.cpp

OpenGL allows GPUs to approximate a triangle's maximum depth slope which prevents a number computationally expensive instructions. On my machine, this gives me +6% FPS in Quake III.

LibSoftGPU: Use approximation for maximum depth slope

---

Meta/CMake/unicode_data.cmake
Meta/Lagom/Tools/CodeGenerators/LibUnicode/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
Userland/Libraries/LibGUI/EmojiInputDialog.cpp
Userland/Libraries/LibGUI/EmojiInputDialog.gml
Userland/Libraries/LibGUI/EmojiInputDialog.h
Userland/Libraries/LibUnicode/CMakeLists.txt
Userland/Libraries/LibUnicode/Emoji.cpp
Userland/Libraries/LibUnicode/Emoji.h
Userland/Libraries/LibUnicode/Forward.h

LibGUI+LibUnicode: Display emoji in Unicode order, and support filtering emoji by group

---

Userland/Libraries/LibGUI/ComboBox.cpp
Userland/Libraries/LibGUI/CommandPalette.cpp
Userland/Libraries/LibGUI/ConnectionToWindowServer.cpp
Userland/Libraries/LibGUI/ConnectionToWindowServer.h
Userland/Libraries/LibGUI/Dialog.cpp
Userland/Libraries/LibGUI/Window.cpp
Userland/Libraries/LibGUI/Window.h
Userland/Libraries/LibGUI/WindowMode.h
Userland/Services/WindowServer/Menu.cpp
Userland/Services/WindowServer/Menu.h
Userland/Services/WindowServer/MenuManager.cpp
Userland/Services/WindowServer/MenuManager.h
Userland/Services/WindowServer/Window.cpp
Userland/Services/WindowServer/WindowClient.ipc
Userland/Services/WindowServer/WindowFrame.cpp
Userland/Services/WindowServer/WindowManager.cpp
Userland/Services/WindowServer/WindowManager.h
Userland/Services/WindowServer/WindowMode.h

Anticipating #15129 and generally to make CaptureInput more reliable outside combo boxes

LibGUI+WindowServer: Some Dialog fixes

---

Meta/CMake/unicode_data.cmake
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
Userland/Libraries/LibGUI/ConnectionToWindowServer.cpp
Userland/Libraries/LibGUI/EmojiInputDialog.cpp
Userland/Libraries/LibGUI/EmojiInputDialog.h
Userland/Libraries/LibGUI/TextEditor.cpp
Userland/Libraries/LibGUI/TextEditor.h
Userland/Libraries/LibGUI/Widget.h
Userland/Libraries/LibUnicode/Emoji.h
Userland/Libraries/LibVT/TerminalWidget.cpp

LibGUI+LibUnicode: Support emoji with multiple code points, category Serenity-custom emoji

---

Kernel/Arch/aarch64/Dummy.cpp
Kernel/Arch/aarch64/PageDirectory.cpp
Kernel/Arch/aarch64/Processor.cpp
Kernel/Arch/aarch64/Processor.h
Kernel/Arch/aarch64/init.cpp
Kernel/Arch/aarch64/kprintf.cpp
Kernel/CMakeLists.txt
Kernel/Memory/MemoryManager.cpp
Kernel/Multiboot.h

Additionally, this PR also includes some already compiling parts of the kernel into `init.cpp` such as `DeviceManagement` and `CommandLine`.

Kernel: Basic MemoryManager support on aarch64 

---

Tests/LibJS/test262-runner.cpp
Userland/Libraries/LibWeb/DOM/Event.cpp
Userland/Libraries/LibWeb/DOM/Event.h
Userland/Libraries/LibWeb/DOM/NonElementParentNode.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContext.h
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.h

Related to #15217
also has a compat fix for our version of the test262 runner
CC @Lubrsi @davidot

LibWeb: Some missing edge visitation fixes

---

Tests/AK/TestFixedArray.cpp

This caused the m_allocation_enabled_previously member to be technically uninitialized when the compiler emits the implicit destructor call for stack allocated classes.
This was pointed out by gcc on lagom builds, no clue how this was flying under the radar for so long and is not triggering CI.
----
CC @alimpfard @kleinesfilmroellchen

AK+Tests: Don't double-destroy NoAllocationGuard in TestFixedArray

---

Userland/Libraries/LibGfx/Font/TrueType/Glyf.h

Instead of just trying to rasterize a composite glyph normally, recurse until a simple glyph is found.
This fixes a bug in ladybird where it was crashing while rendering characters like ščćž in the Noto Sans Regular font.
That font renders those characters as a composite where the caret has numberOfContours = -1. When using the rasterize_impl simple path for that, it would negatively overflow the offsets.

LibGfx: When rasterizing composite glyphs recurse until a simple glyph is found

---

Base/usr/share/man/man1/Magnifier.md

From : 
For users with sight impairment, it has the facility to apply several filters on the captured image.
To: 
For users with slight visual impairment, Magnifier can apply several filters to the captured image.
Facilitated by Discord discussion on #serenityos -> https://discord.com/channels/830522505605283862/830522505605283866/1015176434827923456

Base: Update Magnifier.md use visual impairment vs sight impaired

---

Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp

Rather than invoking AK::Time::from_timestamp at runtime, we can do so at compile time. This reduces invoking TimeZone::get_time_zone_offset 100,000 times in a loop from about 7 seconds to 30 milliseconds.

LibTimeZone: Generate DST rule timestamps at compile time

---

Ports/.port_include.sh
Ports/binutils/patches/ReadMe.md
Toolchain/Patches/binutils.patch
Toolchain/Patches/gcc/0001-Add-a-gcc-driver-for-SerenityOS.patch
Toolchain/Patches/gcc/0002-fixincludes-Skip-for-SerenityOS-targets.patch
Toolchain/Patches/gcc/0003-libgcc-Build-for-SerenityOS.patch
Toolchain/Patches/gcc/0004-libgcc-Do-not-link-libgcc_s-to-LibC.patch
Toolchain/Patches/gcc/0005-i386-Disable-math-errno-for-SerenityOS.patch
Toolchain/Patches/gcc/0006-libstdc-Support-SerenityOS.patch
Toolchain/Patches/gcc/ReadMe.md
Toolchain/Patches/llvm/0001-Support-Add-support-for-building-LLVM-on-SerenityOS.patch
Toolchain/Patches/llvm/0002-Triple-Add-triple-for-SerenityOS.patch
Toolchain/Patches/llvm/0003-Driver-Add-support-for-SerenityOS.patch
Toolchain/Patches/llvm/0004-Driver-Default-to-ftls-model-initial-exec-on-Serenit.patch
Toolchain/Patches/llvm/0005-libc-Add-support-for-SerenityOS.patch
Toolchain/Patches/llvm/0006-compiler-rt-Build-crtbegin.o-crtend.o-for-SerenityOS.patch
Toolchain/Patches/llvm/0007-cmake-Allow-undefined-symbols-on-SerenityOS.patch
Toolchain/Patches/llvm/0008-cmake-Support-building-shared-libLLVM-and-libClang-f.patch
Toolchain/Patches/llvm/0009-compiler-rt-llvm-Enable-profile-instrumentation-for-.patch
Toolchain/Patches/llvm/ReadMe.md

A bunch of quality-of-life changes, most importantly for not mangling certain patches, for not accidentally throwing away all of ones work, and for keeping the generated patches more consistent.

Ports: Various improvements to `./package.sh dev`

---

Userland/Applets/Network/main.cpp
Userland/Applets/ResourceGraph/main.cpp

Plus some other minor clean-up while I was there.

Applets: Port to Core::Stream

---

AK/FuzzyMatch.cpp
AK/FuzzyMatch.h
Userland/Libraries/LibGUI/EmojiInputDialog.cpp

This allows the user to have slight typos in their search query.

LibGUI: Use fuzzy matching when searching for emoji by name

---

Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Meta/Lagom/Tools/CodeGenerators/LibEDID/GeneratePnpIDs.cpp
Meta/Lagom/Tools/CodeGenerators/StateMachineGenerator/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/StateMachineGenerator/main.cpp
Userland/Applications/PixelPaint/Image.cpp
Userland/Applications/PixelPaint/Image.h
Userland/Applications/Run/RunWindow.cpp
Userland/Applications/Run/RunWindow.h
Userland/Applications/SoundPlayer/M3UParser.cpp
Userland/Applications/SoundPlayer/M3UParser.h
Userland/DevTools/Profiler/Profile.cpp
Userland/DevTools/Profiler/SourceModel.cpp
Userland/Games/MasterWord/WordGame.cpp
Userland/Libraries/LibCore/File.h

These are some simpler cases, because I was in the mood for simple.

Everywhere: Some Core::File -> Core::Stream::File conversions

---

Meta/Lagom/Tools/CodeGenerators/StateMachineGenerator/main.cpp

This fixes build on MacOS m1 arch.

Tools: Remove unused variable

---

Meta/CMake/unicode_data.cmake
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GeneratorUtil.h

https://unicode.org/versions/Unicode15.0.0/

LibUnicode: Update to Unicode version 15.0.0

---

Userland/Applications/ClockSettings/TimeZoneSettingsWidget.gml
Userland/Libraries/LibGUI/ComboBox.cpp
Userland/Libraries/LibGUI/ComboBox.h
Userland/Libraries/LibGUI/ListView.cpp
Userland/Libraries/LibGUI/ListView.h
Userland/Libraries/LibGUI/Window.cpp

LibGUI: Couple of ComboBox corrections

---

Userland/Libraries/LibWeb/Painting/StackingContext.cpp

(This fixes an edge case I forgot to handle in #15354)

LibWeb: Fix edge case in transform/opacity painting 

---

Userland/Libraries/LibGUI/EditingEngine.cpp

There's a big comment explaining it because it's somewhat confusing, but the behavior I'm copying from other editors is, when you repeatedly press the `Home` key:
1. Go to the start of the visual line, where it wraps.
2. Go to the first non-whitespace character on the logical line, which is what happens in non-wrapped lines.
3. Go to column 0.
4. GOTO 2

LibGUI: Make "Home" key behavior comfier on wrapped lines :^)

---

Userland/Libraries/LibC/locale.cpp

LibC: Allow detection of supported locales through setlocale

---

Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Op.cpp
Userland/Libraries/LibJS/Bytecode/Op.h

Also hopefully includes a fix for #12127

LibJS: More spreading support for the Bytecode-VM

---

AK/PrintfImplementation.h
Kernel/Bus/PCI/Access.cpp

Fix two comment typos

---

Userland/Applications/Magnifier/main.cpp

https://youtu.be/CIhkdtQZuw0?t=665

Magnifier: Don't error if cancelling capture save

---

Base/res/html/misc/transform.html
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/TransformFunctions.json
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

https://user-images.githubusercontent.com/25595356/193376980-2155cd27-53d2-4c3c-aabb-a24995165967.mp4

LibWeb: Implement rotation and matrix3d transform functions from css-transforms-2

---

Userland/Games/Snake/SnakeGame.cpp
Userland/Games/Snake/SnakeGame.h

Previously the game would immediately reset on game over, but now it'll pause the game and show a message box with your score :-)

Snake: Show message box on game over

---

Base/usr/share/man/man1/test.md
Userland/Utilities/test.cpp

- test: Print the correct operator on error
- test: Support more options

test: Bugfix + additional options

---

Userland/Utilities/mount.cpp

Being unable to `open` on the source caused mount to crash. The error is now properly reported to the user.
Fixes #15048

mount: Report error instead of crashing on failure

---

Userland/Libraries/LibWasm/Parser/Parser.cpp
Userland/Libraries/LibWasm/Printer/Printer.cpp

LibWasm: Some minor cleanups

---

Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.h

Renames, and a tiny amount of tweaking because I can't help myself.
And yes, this really has sat in my to-do list since December. :sweat_smile:

LibWeb: Finally implement CSS-SYNTAX-3 changes from December 2021

---

Userland/Applications/Calculator/CMakeLists.txt
Userland/Applications/Calculator/CalculatorWidget.cpp
Userland/Applications/Calculator/CalculatorWidget.h
Userland/Applications/Calculator/Keypad.cpp
Userland/Applications/Calculator/Keypad.h
Userland/Applications/Calculator/RoundingDialog.cpp
Userland/Applications/Calculator/RoundingDialog.h
Userland/Applications/Calculator/main.cpp

Last part of #11623 !
This patch adds a few ways to interact with those brand-new infinite precision numbers by adding some rounding abilities.
Finally, fixes #14062

Calculator: Add a Rounding menu

---

Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.cpp
Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.gml
Userland/Applications/CalendarSettings/CalendarSettingsWidget.gml
Userland/Applications/KeyboardSettings/Keyboard.gml
Userland/Applications/MouseSettings/Highlight.gml
Userland/Applications/MouseSettings/Mouse.gml
Userland/Applications/TerminalSettings/TerminalSettingsView.gml

One of those inconsistencies that once you notice it, you can't un-notice it

Applications: Use title-case for group box titles in settings

---

Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
Userland/Libraries/LibWeb/Fetch/Request.cpp
Userland/Libraries/LibWeb/Fetch/Request.h
Userland/Libraries/LibWeb/Fetch/Response.cpp
Userland/Libraries/LibWeb/Fetch/Response.h
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/HTML/BrowsingContextContainer.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContextContainer.h
Userland/Libraries/LibWeb/HTML/NavigationParams.h
Userland/Libraries/LibWeb/Loader/FrameLoader.cpp

More preparation for `fetch()`.

LibWeb: Make Fetch::Infrastructure::{Request,Response} ref-counted

---

Userland/DevTools/HackStudio/Editor.cpp
Userland/DevTools/HackStudio/Editor.h

HackStudio: Use a single global tooltip window 

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibIDL/Types.h
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Fetch/Response.cpp
Userland/Libraries/LibWeb/Fetch/Response.h
Userland/Libraries/LibWeb/Geometry/DOMPoint.cpp
Userland/Libraries/LibWeb/Geometry/DOMPoint.h
Userland/Libraries/LibWeb/Geometry/DOMPoint.idl
Userland/Libraries/LibWeb/Geometry/DOMPointReadOnly.cpp
Userland/Libraries/LibWeb/Geometry/DOMPointReadOnly.h
Userland/Libraries/LibWeb/Geometry/DOMPointReadOnly.idl
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h

This is a resurrection of some work I started in April. Since then, DOMPoint got added already, so the only new thing added to that is `fromPoint()`.
Otherwise, there are some improvements to BindingsGenerator.

LibWeb+LibIDL+BindingsGenerator: DOMPoint Stuff and Things

---

Base/res/html/misc/backdrop-filter.html
Userland/Libraries/LibGfx/Filters/HueRotateFilter.h
Userland/Libraries/LibGfx/Filters/MatrixFilter.h
Userland/Libraries/LibGfx/Filters/SaturateFilter.h
Userland/Libraries/LibWeb/Painting/FilterPainting.cpp

Another lovely and aesthetic filter effect :^)
| LibWeb                                                                                                          | Chrome                                                                                                          |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/11597044/193666426-276f5a5e-4c8d-404e-a792-b4f4b28d5f1a.png) | ![image](https://user-images.githubusercontent.com/11597044/193666625-e4470750-e6b4-4f18-9ad1-001719287291.png) |

LibWeb+LibGfx: Implement the `saturate()` filter effect

---

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
Tests/LibUnicode/TestUnicodeCharacterTypes.cpp

FIXME: Petition the Unicode org to put this in a UCD file instead of a PDF

LibUnicode: Update code point ideographic replacements for Unicode 15

---

Userland/Libraries/LibWeb/Painting/GradientPainting.cpp

~~I'm not sure of the exact cause of this, but it seems on i686 the gradiant location goes to (for example) 25 % 25 = 0 and wraps like expected, but on x64 it goes 24.9999999 % 25 = 24.99999999.~~
~~My little hack fix here to to round to the nearest 0.01, which gives the expected results.~~
The glitches were my fault, it just so happened they did not show up on i686 due to a tiny difference in values.
This should now implement the correct behaviour.
Example of the glitches (pixels off-by-one):

LibWeb: Fix wrapping glitches on `repeating-linear-gradient()`s

---

Documentation/Kernel/GraphicsSubsystem.md

This is an attempt of me trying to document the recent development of what came to be the kernel graphics subsystem.
This is only the start, and future PRs might address things like explaining specific drivers, or reasons to usage of spinlocks vs mutexes in various places.
Fixes, notes and suggestions are always appreciated :)

Documentation: Add initial document about the Kernel graphics subsystem

---

Base/usr/share/man/man1/checksum.md
Userland/Utilities/checksum.cpp

This commit also updates 'checksum' to use the Core::Stream::File API.

checksum: Support the '--check' option

---

Userland/Applications/Browser/Browser.h
Userland/Applications/Browser/Tab.cpp
Userland/Applications/Browser/main.cpp
Userland/Libraries/LibWeb/HTML/Navigator.cpp
Userland/Libraries/LibWeb/HTML/Navigator.h
Userland/Libraries/LibWeb/HTML/Navigator.idl
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageHost.cpp
Userland/Services/WebContent/PageHost.h
Userland/Services/WebContent/WebContentServer.ipc

LibWeb: Implement navigator.webdriver

---

Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDate.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateISO.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTimeISO.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainTimeISO.js

I think this is my first normative update so let me know if the message needs more explanation
(Github doesn't like this long branch name...)
Fixes one of the comments mentioned in #15525

LibJS: One normative update + big nanosecond addition fix

---

Userland/Libraries/LibTLS/Certificate.h
Userland/Libraries/LibTLS/TLSv12.cpp
Userland/Utilities/headless-browser.cpp

headless-browser: Add ca-certs-path options

---

Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
Userland/Libraries/LibWeb/Fetch/Request.cpp
Userland/Libraries/LibWeb/Fetch/Request.h
Userland/Libraries/LibWeb/Fetch/Request.idl

What did I get myself into lol

LibWeb: Fetch spec changes

---

Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Adds a tick to issue #15551 @AtkinsSJ

WebDriver: Implement `POST /session/{id}/refresh` endpoint

---

Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Implements two tasks in issue https://github.com/SerenityOS/serenity/issues/15551 @AtkinsSJ

WebDriver: Implement POST /session/{id}/back and  POST /session/{id}/forward endpoints

---

Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Cookie/Cookie.cpp
Userland/Libraries/LibWeb/Cookie/Cookie.h
Userland/Services/WebDriver/CMakeLists.txt
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Another tick for issue https://github.com/SerenityOS/serenity/issues/15551 @AtkinsSJ

WebDriver: Add Get All Cookies Endpoint

---

Documentation/FAQ.md

We've had this discussion at least three times now so I wrote something to hopefully discourage any further discussions.

Documentation: Add FAQ regarding MP3 patents

---

Userland/DevTools/GMLPlayground/main.cpp

Previously, Playground would always preview the rendered GML in a frame next to the editor. This can be annoying when trying to work with small or large widget hierarchies since the size of the preview is tied to the size of the editor. Now there is a view menu which allows you to toggle between the frame or a separate window which can be resized independent of the editor.
Demo:
https://user-images.githubusercontent.com/14025038/196000346-584814d2-04b6-4179-aaf1-19259d219565.mp4

GMLPlayground: Allow previewing GML in a separate window

---

Base/usr/share/man/man7/proc.md
Kernel/GlobalProcessExposed.cpp

This node is not used anymore by anything, so let's remove it.

Kernel+Base: Remove unused /proc/devices node

---

Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.from.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toZonedDateTimeISO.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.toZonedDateTime.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.from.js

Ticks off four items in #15525.

LibJS: Implement the Temporal fast path changes

---

Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp

LibJS: Rename Get{IANA => Named}TimeZone{Next,Previous}Transition 

---

Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Cookies are delicious
More for #15551  :^)

WebDriver: GET named cookie

---

Userland/Libraries/LibJS/Runtime/RegExpConstructor.cpp
Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
Userland/Libraries/LibJS/Runtime/RegExpObject.h
Userland/Libraries/LibJS/Runtime/StringPrototype.cpp

Preparation for #15585. cc @leeight

LibJS: Implement the RegExpAlloc AO

---

AK/Platform.h
Kernel/Arch/TrapFrame.h
Kernel/Arch/aarch64/CrashHandler.cpp
Kernel/Arch/aarch64/Dummy.cpp
Kernel/Arch/aarch64/Interrupts.cpp
Kernel/Arch/aarch64/PageDirectory.cpp
Kernel/Arch/aarch64/PageDirectory.h
Kernel/Arch/aarch64/Processor.cpp
Kernel/Arch/aarch64/Processor.h
Kernel/Arch/aarch64/RegisterState.h
Kernel/Arch/aarch64/SafeMem.cpp
Kernel/Arch/aarch64/ScopedCritical.cpp
Kernel/Arch/aarch64/init.cpp
Kernel/Arch/x86/common/Interrupts.cpp
Kernel/Arch/x86/common/Processor.cpp
Kernel/Arch/x86/i386/InterruptEntry.cpp
Kernel/Arch/x86/i386/Processor.cpp
Kernel/Arch/x86/x86_64/SyscallEntry.cpp
Kernel/Assertions.h
Kernel/Scheduler.cpp
Kernel/Syscall.cpp
Kernel/Thread.cpp

For the most part this just adds a bunch of boring macros and stubs for AARCH64.

Kernel: More stubs for AARCH64 (part 2)

---

Userland/Services/SystemServer/main.cpp

I know we should not encounter such case, but when I worked on #15593, I managed to remove the `/proc/system_mode` but replaced it with nothing so `SystemServer` launched `WindowServer` which crashed because it didn't know what to do without reading `system_mode`.

 SystemServer: Make system-mode=text the default in case of read failure

---

Userland/Libraries/LibThreading/Thread.cpp

pthread_setname_np is a can of worms for portability. Linux, macOS, and the BSDs all do it differently.
Also fix adding the tid as an inspectable Core::Object property on systems where pthread_t is a pointer.

LibThreading: Only set pthread name on Serenity

---

Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp

LibJS: Sync the set of rounding modes

---

Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Adds the last of the Cookie endpoints to @AtkinsSJ 's #15551 list :^)

WebDriver: Implement `POST /session/{id}/cookie` endpoint

---

Userland/Utilities/route.cpp

Now that the IPv4Address has the ability to generate valid IP addresses from CIDR notations, this provides a nicer interface to the user when specifying the network address.
For example:
`$ route add --net 8.8.8.0/24 --gateway 192.168.86.1 --interface ep0s8`

route: Accept CIDR notation when specifying network

---

Userland/Games/2048/CMakeLists.txt
Userland/Games/2048/GameSizeDialog.cpp
Userland/Games/2048/GameSizeDialog.gml
Userland/Games/2048/GameWindow.gml
Userland/Games/2048/main.cpp

This PR converts 2048 to use GML and fixes a bug where the target tile would decrease each time that the settings window was opened.

2048: Convert to GML + Bugfix

---

Userland/Applications/PixelPaint/Tools/WandSelectTool.cpp

Before this commit, when the wand select tool was used on a layer that was moved, it would make the selection relative to the image, and not relative to the layer. 
Before this commit:
https://user-images.githubusercontent.com/7570033/196451756-17b6aed1-c64c-4372-a818-a4afdacaf638.mp4
After this commit:
https://user-images.githubusercontent.com/7570033/196451810-e0099f1d-2272-451c-ae1e-4d4164a0fe1f.mp4

PixelPaint: Make Wand Select tool select correctly on moved layers

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/Tab.h
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Webdriver Get attribute

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp

We were mistakenly treating these as `for (x of obj)`. By reorganizing the code a little bit, we actually support both kinds of iteration with less duplication. :^)
Fixes 17 tests in test262.

LibJS: Support `for (x in obj)` iteration in bytecode VM

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp

Fixes 39 tests in test262 and a handful in test-js. :^)

LibJS: Support non-base-10 BigInt literals in bytecode VM

---

Userland/Services/WebDriver/CMakeLists.txt
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h
Userland/Services/WebDriver/TimeoutsConfiguration.cpp
Userland/Services/WebDriver/TimeoutsConfiguration.h

Ticks off two more boxes in #15551

WebDriver: Timeouts

---

Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

WebDriver: Implement `GET /session/{session id}/window/handles` endpoint

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/Tab.h
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

With  JS-induced headache, I present this PR!
It allows for the getting of properties!
One more for #15551

Webdriver get property

---

Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h

LibJS: A couple of Temporal editorial simplifications

---

Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp

Ticks off one box in https://github.com/SerenityOS/serenity/issues/15525

LibJS: Refactor CalendarFields for better linearity

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/Tab.h
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

Webdriver get element css value

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/Tab.h
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverEndpoints.h

This moves the Functions that until now lived in Tab.h into a dedicated class.
Once #15713 is merged, this can be rebased...

Webdriver endpoints in tab

---

Kernel/Arch/aarch64/Dummy.cpp
Kernel/Arch/aarch64/Processor.h
Kernel/CMakeLists.txt
Kernel/Heap/Heap.h
Kernel/Random.cpp

Also adds 2 additional commits, which bring us closer to running `Scheduler::initialize()`.

Kernel/aarch64: Stub more functions to build {Thread, Process, Random}.cpp

---

Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibWeb/Fetch/BodyInit.idl

LibIDL: Resolve typedefs in UnionType members recursively

---

Userland/Games/Snake/SnakeGame.cpp

This is a follow up to https://github.com/SerenityOS/serenity/pull/15708, I spent a few hours looking up more animals snakes eat and drawing emoji for them (https://github.com/SerenityOS/serenity/pull/15734).
Enjoy!

Snake: Add 18 new animals for the snake to eat

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

One more for #15551 
Once  #15719 is merged I will rebase this and use the very nice changes :^)

Webdriver element tag name

---

Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp

Ticks off two boxes in https://github.com/SerenityOS/serenity/issues/15525

LibJS: Validation of NanosecondsToDays and getOffsetNanoseconds

---

Kernel/Bus/USB/UHCI/UHCIDescriptorTypes.h

This fixes the problem of USB not working on 64-bit Systems. As per @b14ckcat's idea in discord, the bookkeeping data inside of the descriptors has been moved into a struct that is allocated when the descriptor itself is created.

Kernel+USB: Fix USB on 64-bit platforms

---

Kernel/FileSystem/BlockBasedFileSystem.cpp
Kernel/FileSystem/BlockBasedFileSystem.h
Kernel/FileSystem/Ext2FileSystem.cpp
Kernel/FileSystem/Ext2FileSystem.h
Kernel/FileSystem/FATFileSystem.cpp
Kernel/FileSystem/FATFileSystem.h
Kernel/FileSystem/FileBackedFileSystem.cpp
Kernel/FileSystem/FileBackedFileSystem.h
Kernel/FileSystem/FileSystem.cpp
Kernel/FileSystem/FileSystem.h
Kernel/FileSystem/ISO9660FileSystem.cpp
Kernel/FileSystem/ISO9660FileSystem.h
Kernel/FileSystem/OpenFileDescription.cpp
Kernel/FileSystem/OpenFileDescription.h
Kernel/FileSystem/Plan9FileSystem.cpp
Kernel/FileSystem/Plan9FileSystem.h
Kernel/FileSystem/VirtualFileSystem.cpp
Kernel/FileSystem/VirtualFileSystem.h
Kernel/GlobalProcessExposed.cpp
Kernel/Storage/StorageManagement.cpp
Kernel/Syscalls/chown.cpp
Kernel/Syscalls/execve.cpp
Kernel/Syscalls/inode_watcher.cpp
Kernel/Syscalls/mmap.cpp
Kernel/Syscalls/mount.cpp

Kernel: Refactor Filesystem-Mounts hierarchy design

---

Ports/.port_include.sh

We already have something similar for the toolchain builds. This makes it easier to identify which build step is currently running.

Ports: Prefix output with the build step and port name

---

Meta/Lagom/CMakeLists.txt
Meta/run.sh
Meta/serenity.sh
Userland/Libraries/LibCore/CMakeLists.txt

Authored and tested entirely on SerenityOS. :^)

Meta: More changes for self-hosting compatibility

---

Userland/DevTools/HackStudio/Locator.cpp
Userland/Libraries/LibGUI/AutocompleteProvider.cpp
Userland/Libraries/LibGUI/ComboBox.cpp
Userland/Services/WindowServer/WindowManager.cpp
Userland/Services/WindowServer/WindowManager.h
Userland/Services/WindowServer/WindowType.h

https://user-images.githubusercontent.com/388571/197605103-accd1171-71c9-4ec2-849b-5a095aad9ccb.mp4

LibGUI: Make sure combobox list windows can't be moved

---

Base/usr/share/man/man2/scheduler_get_parameters.md
Base/usr/share/man/man2/scheduler_set_parameters.md
Kernel/API/POSIX/sched.h
Kernel/API/Syscall.h
Kernel/Process.h
Kernel/Syscalls/sched.cpp
Kernel/Thread.h
Tests/LibC/CMakeLists.txt
Tests/LibC/TestPThreadPriority.cpp
Userland/DevTools/UserspaceEmulator/Emulator.h
Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp
Userland/Libraries/LibC/pthread.cpp
Userland/Libraries/LibC/sched.cpp
Userland/Libraries/LibC/sched.h

This PR contains :skeleyak: fixups, bugfixes, new syscalls, a full LibC+Kernel rebuild and POSIX compliance!

Kernel+LibC: Implement Pthread scheduler priority APIs and other shenanigans

---

Userland/Utilities/ntpquery.cpp

It wouldn't even start. Now it does.

ntpquery: Fix pledge and unveil invocations

---

.ycm_extra_conf.py
Documentation/VimConfiguration.md

YouCompleteMe is a plugin for Vim which provides code-completion functionality. This change adds a configuration file which makes YouCompleteMe aware of which compile flags to use with clangd.
https://user-images.githubusercontent.com/388571/197971914-7a05979b-9f0f-489e-b099-589cc689a516.mp4

Meta: Add configuration file for YouCompleteMe

---

Userland/Libraries/LibArchive/Tar.cpp
Userland/Libraries/LibArchive/Tar.h
Userland/Libraries/LibArchive/TarStream.cpp
Userland/Libraries/LibArchive/TarStream.h
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Utilities/tar.cpp

- Refactor/bugfix of null-terminators in fields
- Support for longer filenames
- Support for creating archives with symlinks
fixes #15641

Utilities+LibArchive: Miscellaneous tar improvements

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

WebDriver: Implement get_element_text

---

Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/Locale.cpp
Userland/Libraries/LibJS/Tests/builtins/Intl/DurationFormat/DurationFormat.prototype.format.js
Userland/Libraries/LibJS/Tests/builtins/Intl/DurationFormat/DurationFormat.prototype.formatToParts.js

The DurationFormat change will regress one test262 test, they haven't updated test262 with this change yet.

LibJS: Couple of normative Intl proposal changes

---

AK/ByteBuffer.h
Userland/Libraries/LibSQL/BTree.h
Userland/Libraries/LibSQL/Heap.cpp
Userland/Libraries/LibSQL/Heap.h
Userland/Libraries/LibSQL/Serializer.h
Userland/Libraries/LibSQL/TreeNode.cpp

Some red-herrings I came across while trying to figure out #15844.

AK+LibSQL: Miscellaneous cleanups resulting from chasing down a bug 

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/Tab.h
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h
Userland/Services/WebDriver/main.cpp

[Screencast from 2022-11-02 13-20-02.webm](https://user-images.githubusercontent.com/5600524/199558333-bdfdbff9-5d4b-472d-8d7d-c65ed62e09e5.webm)
Ref #15551

WebDriver: Implement GET `/session/{id}/screenshot`

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/BrowserWindow.h
Userland/Applications/Browser/Tab.cpp

[Screencast from 2022-11-02 14-13-07.webm](https://user-images.githubusercontent.com/5600524/199569508-b18bc383-5e5a-416f-a1b9-36d60e2a68eb.webm)

Browser: Add a context menu item to take a screenshot of the current tab

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h
Userland/Services/WebDriver/WebDriverError.cpp
Userland/Services/WebDriver/WebDriverError.h

[Screencast from 2022-11-02 18-52-32.webm](https://user-images.githubusercontent.com/19366641/199580239-61380c93-46dd-4fb7-8c2c-0b3845422302.webm)
Ref #15551

WebDriver: Let's run some JavaScript!

---

AK/LexicalPath.h
AK/URL.h

First time committing to this project, so forgive me if I messed things up.
After some help on the Serenity discord, I finally managed to cross-compile ladybird to our own LibC. It only required 2 changes to the source code, which I'm adding in this PR. In the future, I plan on porting ladybird to our own operating system too, which might come with some more code changes, but we'll see about that when we get there.

AK: Add support for mlibc

---

Documentation/VSCodeConfiguration.md

This is something minor that bugged me more than it probably should have when setting up a new environment a few weeks ago.
PR:ing it now as to not effect last month's hacktoberfest in any way.

Documentation: Give collapsed sections consistent headers

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
Userland/Libraries/LibWeb/DOM/ShadowRoot.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

[Screencast from 2022-11-02 20-32-08.webm](https://user-images.githubusercontent.com/5600524/199627101-0c971b25-5303-4c63-8b6b-deeb064c0814.webm)
Ref #15551

WebDriver: Implement `GET /session/{id}/source`

---

Base/res/html/misc/button.html
Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

[Screencast from 2022-11-03 13-33-51.webm](https://user-images.githubusercontent.com/5600524/199793897-5d8b6302-65ed-400a-ab4a-e6f6014fcdbe.webm)
Ref #15551

WebDriver: Implement `GET /session/{id}/element/{id}/[rect,enabled]`

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

[Screencast from 2022-11-03 17-03-51.webm](https://user-images.githubusercontent.com/5600524/199834170-68db1510-7d34-4ac1-9c75-60be05db6e23.webm)
Ref #15551

WebDriver: Implement `GET /session/{id}/element/{id}/selected`

---

Userland/Applications/FileManager/DirectoryView.cpp

Previously we'd try to disown() the newly created process even if posix_spawn() had failed.

FileManager: Improve error handling when posix_spawn() fails

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/WebDriverConnection.cpp
Userland/Applications/Browser/WebDriverConnection.h
Userland/Applications/Browser/WebDriverEndpoints.h
Userland/Applications/Browser/WebDriverSessionClient.ipc
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h

[Screencast from 2022-11-04 19-58-53.webm](https://user-images.githubusercontent.com/5600524/200091074-e483068c-a5d3-4ec0-b777-ad3b4b339429.webm)
Ref #15551

WebDriver+Browser: Implement `GET /session/{id}/element/{id}/screenshot`

---

Userland/Applications/Browser/Tab.cpp
Userland/Applications/Browser/Tab.gml
Userland/Applications/Browser/Tab.h
Userland/Applications/Browser/main.cpp

Browser: Add a banner to tabs controlled by WebDriver

---

Userland/Libraries/LibWeb/Painting/GradientPainting.cpp

This commit tweaks gradients so resolve_color_stop_positions() no longer cares about the actual length of the gradient. All stops are resolved to relative positions along the gradient line (between 0 and 1), and are only scaled back to pixels (if required) during the actual painting.
This has no immediate benefit right now, but it might make using CSS pixels for gradients easier :^)
cc @AtkinsSJ

LibWeb: Use relative units for gradients until painting

---

Userland/Libraries/LibJS/Runtime/Date.cpp
Userland/Libraries/LibJS/Runtime/Date.h
Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.h
Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp

LibJS: Change ToLocalTime to use epoch nanoseconds

---

Base/etc/shellrc
Base/res/apps/Piano.af
Base/res/apps/SoundPlayer.af
Base/res/apps/VideoPlayer.af
Base/res/icons/SystemMenu.ini
Ports/milkytracker/package.sh
Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
Userland/Applications/VideoPlayer/VideoPlayerWidget.h
Userland/Applications/VideoPlayer/main.cpp

VideoPlayer was a bit behind in terms of basic functionality compared to our other apps, so I feel like we should show it some love.
It now shows up in the "Media" (used to be "Sound") category, and has 'Quit' and 'Help' actions like most other apps should.
VideoPlayer is also missing a snazzy icon like our other apps, but that isn't my place of specialty, if someone else would be able to make an icon, that would be great!

VideoPlayer: More basic improvements

---

Base/usr/share/man/man1/stat.md
Base/usr/share/man/man1/which.md

Added manpages for which(1) and stat(1)

Base: Added manpages for which(1) and stat(1)
