SerenityOS/serenity

- Userland/Libraries/LibGUI/Dialog.cpp
Fixes a typo in a comment (introduced by me 😅)
> LibGUI: Fix a typo

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
This makes hovering over the link in the following HTML snippet work, i.e. the tooltip is shown and the link target is shown at the bottom of the browser window:
```html
<html lang="en"><head><style>
.site-link{display:inline-block}
.site-link:before{content:"derp"}
.site-link::after{content:"";display:block}
</style></head><body><a class="site-link" href="#" title="Tooltip, maybe!"></a>
```
> LibWeb: Pick the correct DOM node for mouse-move events

- Userland/Libraries/LibC/pwd.cpp
- Userland/Libraries/LibC/pwd.h
> LibC: Implement getpwent_r

- Userland/Libraries/LibIDL/IDLParser.cpp
> LibIDL: Also handle anonymous union types in resolve_typedef()

- Userland/Libraries/LibWeb/Fetch/BodyInit.h
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.idl
Made sure to verify that osnews.com loads so Andreas still can read his OS news in Ladybird :^)
> LibWeb: Implement support for DOM::Document in XHR::send()

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Runtime/EnvironmentCoordinate.h
- Userland/Libraries/LibJS/Runtime/GlobalEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/ObjectEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/Reference.cpp
Here are four optimizations towards making global variable access faster.
- The first two make non-strict mode accesses faster by combining the HasProperty and Get/Set operations.
- Then we implement `EnvironmentCoordinate` caching for lookups that end up searching the = global environment.
- Finally, `Identifier::execute()` is tweaked to take advantage of the coordinate cache already present in `Identifier`.
> LibJS: Some optimizations for global variable access

- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
> WebDriver: Implement `POST /session/{id}/window/fullscreen` endpoint

- AK/JsonArray.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
- Userland/Services/WebDriver/Session.cpp
- Userland/Services/WebDriver/Session.h
- Userland/Services/WebDriver/main.cpp
Some prep work to make WebDriver feasible in Ladybird
> LibWeb: Re-implement WebDriver endpoint handling within Web::WebDriver

- Userland/Applications/Piano/CMakeLists.txt
:greenlinus:
(Chunk 4 of #16049)
> Piano: Alphabetize sources

- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/main.cpp
Makes it easier to see when you're running a window as root
https://i.imgur.com/zE7EBFe.png
> WindowServer: Add "[user]" to titlebar when uid differs from login user

- Userland/Libraries/LibWeb/CSS/StyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Libraries/LibWeb/HTML/HTMLBodyElement.cpp
This will make a website like https://buzzybuzz.biz/ work on the browser.
https://user-images.githubusercontent.com/19346060/198888156-d8b078cb-cc8a-4fe0-8909-2266ba28f5ea.mp4
> LibWeb: Support animated backgrounds

- Kernel/Syscalls/jail.cpp
We now disallow jail creation from a process within a jail because there is simply no valid use case to allow it, and we will probably not enable this behavior (which is considered a bug) again.
Although there was no "real" security issue with this bug, as a process would still be denied to join that jail, there's an information reveal about the amount of jails that are or were present in the system.
> Kernel: Disallow jail creation from a process within a jail

- Userland/Applications/SoundPlayer/AlbumCoverVisualizationWidget.cpp
- Userland/Applications/SoundPlayer/AlbumCoverVisualizationWidget.h
- Userland/Applications/SoundPlayer/CMakeLists.txt
- Userland/Applications/SoundPlayer/Player.cpp
- Userland/Applications/SoundPlayer/Player.h
- Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.h
- Userland/Applications/SoundPlayer/main.cpp
- Userland/Libraries/LibAudio/FlacLoader.cpp
- Userland/Libraries/LibAudio/FlacLoader.h
- Userland/Libraries/LibAudio/GenericTypes.h
- Userland/Libraries/LibAudio/Loader.h
- Userland/Libraries/LibCore/MemoryStream.h
Who would have guessed that files from the FLAC test-suite contain such cute pictures?
> SoundPlayer+LibAudio: Load and display cover image from flac files

- Userland/Applications/Browser/WebDriverSessionServer.ipc
This was missed in 7972916be789e1ff7ce9ac8cadd37e512f92e11a
> Browser: Remove unused WebDriverSessionServer.ipc

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
[Screencast from 2022-11-14 19-55-40.webm](https://user-images.githubusercontent.com/5600524/201799971-55eb8bbd-abe4-4dd1-a20a-d312d463ecc9.webm)
Ref #15551
> LibWeb+WebContent+WebDriver: Implement shadow root commands

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibJS/Tests/classes/class-private-fields.js
- Userland/Libraries/LibJS/Tests/syntax/function-hoisting.js
- Userland/Libraries/LibJS/Tests/syntax/functions-in-tree-order-non-strict.js
- Userland/Libraries/LibJS/Tests/syntax/functions-in-tree-order-strict.js
- Userland/Libraries/LibJS/Tests/test-common.js
- Userland/Libraries/LibTest/JavaScriptTestRunner.h
Also now throwing in test-js at the top level gets you a nice stack trace, but inside a describe or test doesn't. :yakbait: anyone?
Fixes 1 annexB test262 test.
Order verified against: v8 and sm
> LibJS: Some scoping and related fixes

- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
- Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp
You'll now get a "Could not match capabilities" if you request a capability that could not be matched.
> LibWeb: Implement most of WebDriver capability matching

- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateDateTimeFormatData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateLocaleData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateNumberFormatData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GeneratePluralRulesData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateRelativeTimeFormatData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GeneratorUtil.h
This is entirely just to avoid headaches for myself next a UCD/CLDR/TZDB version is released :upside_down_face:
> Meta: Do not hard-code index types for UCD/CLDR/TZDB code generators

- Userland/Applications/Magnifier/MagnifierWidget.h
- Userland/Applications/Magnifier/main.cpp
- Userland/Applications/ThemeEditor/MainWidget.cpp
- Userland/Applications/ThemeEditor/PreviewWidget.cpp
- Userland/Applications/ThemeEditor/PreviewWidget.h
- Userland/Applications/ThemeEditor/ThemeEditor.gml
- Userland/Libraries/LibGUI/Action.cpp
- Userland/Libraries/LibGUI/Action.h
- Userland/Libraries/LibGUI/CMakeLists.txt
- Userland/Libraries/LibGUI/ColorFilterer.h
- Userland/Libraries/LibGUI/ComboBox.cpp
- Userland/Libraries/LibGUI/CommonMenus.cpp
- Userland/Libraries/LibGUI/Menu.h
- Userland/Libraries/LibGUI/Menubar.cpp
- Userland/Libraries/LibGUI/Menubar.h
- Userland/Libraries/LibGUI/Shortcut.cpp
- Userland/Libraries/LibGUI/SpinBox.cpp
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGUI/Window.h
> LibGUI+Magnifier+ThemeEditor: Share Accessibility CommonMenu, polish GML, bug fixes

- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
This pull requests largely adds spec comments to some more functions in TypedArray, and also makes some minor fixes to comply with the specification.
- A number of TRYs have been changed to MUSTs
- Some missing asserts have been added
> LibJS: Some spec comments & compliance in TypedArray

- Userland/Applications/CharacterMap/CharacterMapWidget.cpp
- Userland/Applications/FontEditor/GlyphEditorWidget.cpp
- Userland/Applications/FontEditor/GlyphEditorWidget.h
- Userland/Applications/FontEditor/MainWidget.cpp
- Userland/Applications/FontEditor/MainWidget.h
- Userland/Applications/FontEditor/UndoSelection.h
- Userland/Libraries/LibGUI/GlyphMapWidget.cpp
- Userland/Libraries/LibGUI/GlyphMapWidget.h
- Userland/Libraries/LibGfx/Font/BitmapFont.h
- Userland/Libraries/LibGfx/Font/Font.h
- Userland/Libraries/LibGfx/Font/ScaledFont.h
> LibGUI+LibGfx+FontEditor: Toggle system emoji, new Layout menu options, bug fixes

- Userland/Applications/PDFViewer/PDFViewer.cpp
- Userland/Applications/PDFViewer/PDFViewerWidget.cpp
- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/CommonNames.h
- Userland/Libraries/LibPDF/DocumentParser.cpp
- Userland/Libraries/LibPDF/Filter.cpp
- Userland/Libraries/LibPDF/Filter.h
- Userland/Libraries/LibPDF/Parser.cpp
- Userland/Libraries/LibPDF/Reader.h
Continuing my work on PDF support, I came across lots of issues that I would like to ~~partially~~ fix with this PR.
In LibPDF, these mainly have to do with filters, which still need lots of work. I also made some small changes to PDFViewer to improve error handling a bit.
This is part of a larger effort to support more complex documents, I already have some exciting new features queued up that very much depend on these changes.
> PDFViewer+LibPDF: Bug fixes and quality of life improvements

- Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
- Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
This ticks three boxes in #15525:
https://github.com/tc39/proposal-temporal/commit/f2d564238f79b2664b00026741d698b9e46fda31
https://github.com/tc39/proposal-temporal/commit/07673d3dfc8aab49164893ce958a033986e73978
https://github.com/tc39/proposal-temporal/commit/8e80575ad918a0f31b9e888e856f198227722ab0
Note that this last one seems to supersede some of the changes from the other revisions.
> LibJS/Temporal Reorder and Unroll Accesses to Fields

- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
The net result is some nice simplification of the prepare algorithm and a bit of initial scaffolding for import maps support.
> LibWeb: Update HTMLScriptElement prepare and execute to latest HTML spec

- AK/Function.h
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
Much nicer than a buncha `time.sleep()` in my driver script :)
[Screencast from 2022-11-21 11-25-36.webm](https://user-images.githubusercontent.com/5600524/203107630-a23a683c-3ab4-4c9e-a534-097d8a3ba4eb.webm)
> WebContent: Implement WebDriver's implicit timeout for finding elements

- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Small improvements for width sizing. I checked they don't regress Acid2 :)
> LibWeb: Small width sizing improvements

- Userland/Libraries/LibIPC/Connection.cpp
Reading from a socket with a dead peer returns the `ECONNRESET` error code in some cases on Linux. This commit changes LibIPC to gracefully shut down the socket if that happens, fixing an occasional crash in Ladybird.
Fixes SerenityOS/ladybird#116
> LibIPC: Handle `ECONNRESET` when reading from the IPC socket

- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Fixes https://github.com/SerenityOS/serenity/issues/16082
> LibWeb: Flex container should not create BFC

- Meta/Lagom/Fuzzers/FuzzMatroskaReader.cpp
- Tests/LibVideo/TestVP9Decode.cpp
- Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
- Userland/Applications/VideoPlayer/VideoPlayerWidget.h
- Userland/Applications/VideoPlayer/main.cpp
- Userland/Libraries/LibVideo/CMakeLists.txt
- Userland/Libraries/LibVideo/Containers/Demuxer.h
- Userland/Libraries/LibVideo/Containers/Matroska/Document.h
- Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.cpp
- Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.h
- Userland/Libraries/LibVideo/Containers/Matroska/Reader.cpp
- Userland/Libraries/LibVideo/Containers/Matroska/Reader.h
- Userland/Libraries/LibVideo/PlaybackManager.cpp
- Userland/Libraries/LibVideo/PlaybackManager.h
- Userland/Libraries/LibVideo/Sample.h
- Userland/Utilities/matroska.cpp
The main features this PR implements are:
- Seeking with an optional fast mode in the Video Player user interface
- Parsing the Matroska Cue element for faster keyframe lookup
- Error handling for the Matroska parser
- A whole lot of cleanup in the Matroska parser as well
A screenshot for your viewing pleasure:
This screenshot may be a little misleading, though. The default is to do accurate seeking, since the bundled test video has only two cue points. :^)
> VideoPlayer/LibVideo: Implement seeking

- .github/workflows/wasm.yml
- AK/Platform.h
- AK/StackInfo.cpp
- Meta/Lagom/CMakeLists.txt
- Meta/Lagom/Wasm/js_repl.cpp
- Tests/LibJS/test262-runner.cpp
- Userland/Libraries/LibCompress/BrotliDictionary.cpp
- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibCore/MappedFile.cpp
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Print.cpp
- Userland/Libraries/LibJS/Print.h
- Userland/Libraries/LibTest/CrashTest.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyInstanceObject.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyObject.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyObject.h
- Userland/Utilities/js.cpp
Makes libjs.dev/repl happen.
TODO:
> Meta+LibWasm: Infra for wasm js repl

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
This implementation only works for cloning Numbers.
Co-Authored-By: Andrew Kaster <akaster@serenityos.org>
Semi-revival of https://github.com/SerenityOS/serenity/pull/13526 ~~but the  comments on that PR are not addressed yet.~~
> LibWeb: Add initial implementation of structured clone

- AK/Math.h
- Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
- Userland/Libraries/LibGfx/AntiAliasingPainter.h
- Userland/Libraries/LibGfx/FillPathImplementation.h
The lack of antialiasing for our antialiased lines was bugging me, so I tried to come up with a fix... It's not _perfect_ (there's a few edge cases), but I think it generally looks nicer.
This is not any 'proper' algorithm, this was just a shower thought idea. There probably is a better algorithm to achieve the same effect out there, if someone knows of one please replace this code :^).
This works by rendering the line a scanline at a time, which avoids repainting over any pixel on the line (so opacity now works with AA lines). This generally seems to achieve a much nicer looking line.
I've not done any proper benchmarking of this, but some little messing around showed that this new implementation was a little faster than the old one too, so that's a nice little bonus.
Anyway lets look at …
> LibGfx: Implement nicer antialiased lines

- Userland/Libraries/LibPDF/Renderer.cpp
Paths rendering was buggy because the map() function that translates points from user space to bitmap space applied the vertical flip conversion that the current transformation matrix already considers; Hence, all paths were upside down. The only exception was the "re" instruction, which manually adjusted the Y coordinate of its points to be flipped again (and had a FIXME saying that this should be unnecessary).
This commit fixes the map() function that maps userspace points to bitmap coordinates. The "re" operator implementation has also been simplified creating a rectangle first and mapping *that* instead of mapping each point individually.
> LibPDF: Fix path coordinates calculation

- Tests/LibSQL/TestSqlStatementExecution.cpp
- Userland/Libraries/LibSQL/BTree.cpp
- Userland/Libraries/LibSQL/BTree.h
- Userland/Libraries/LibSQL/BTreeIterator.cpp
- Userland/Libraries/LibSQL/Database.cpp
- Userland/Libraries/LibSQL/HashIndex.cpp
- Userland/Libraries/LibSQL/Heap.h
- Userland/Libraries/LibSQL/Serializer.h
- Userland/Libraries/LibSQL/TreeNode.cpp
- Userland/Libraries/LibSQL/Tuple.cpp
- Userland/Libraries/LibSQL/Tuple.h
> LibSQL: Prevent BTree corruption on node split

- Userland/Utilities/hexdump.cpp
Previously, hexdump used Core::File to read input into a fixed buffer. This PR rewrites the file handling to use the more modern Core::Stream::File, which reads data into spans. By using spans, we can also simplify the rest of the code, which previously used memcpy for array manipulation and relied on manual bookkeeping to keep track of offsets.
> hexdump: Replace Core::File with Core::Stream::File

- Userland/DevTools/Profiler/DisassemblyModel.cpp
- Userland/DevTools/UserspaceEmulator/Emulator.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.h
- Userland/Libraries/LibX86/Disassembler.h
- Userland/Libraries/LibX86/Instruction.cpp
- Userland/Libraries/LibX86/Instruction.h
- Userland/Utilities/disasm.cpp
This is a rebased branch of #13300.
Still need to look into the comments of what the original author had to do and fix to ensure it's ready for merging.
> LibX86+disasm: Support x86-64 (attempt #2)

- Userland/Applications/Assistant/Providers.h
- Userland/Applications/Assistant/main.cpp
[assistant.webm](https://user-images.githubusercontent.com/66646555/204097129-17c1d967-cbc7-409a-ad45-8c367a357851.webm)
> Assistant: Slightly more tactile, slightly more assistive

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
"Implements" another endpoint in https://github.com/SerenityOS/serenity/issues/15551. (half a tick less??)  @trflynn89  :^))
> WebDriver: Add stub for `/session/{id}/print` endpoint

- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/CyclicModule.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
For the spec issue see also https://github.com/tc39/ecma262/issues/2823 , which I'll try to fix myself later
The last commit fixes a recent regression of a test262 test
> LibJS: Fix some module related issues

- Userland/Applications/PixelPaint/Tools/EllipseTool.cpp
- Userland/Applications/PixelPaint/Tools/LassoSelectTool.cpp
- Userland/Applications/PixelPaint/Tools/LassoSelectTool.h
- Userland/Applications/PixelPaint/Tools/LineTool.cpp
- Userland/Applications/PixelPaint/Tools/PolygonalSelectTool.cpp
- Userland/Applications/PixelPaint/Tools/RectangleTool.cpp
- Userland/Libraries/LibGfx/Filters/TintFilter.h
This just fixes a few :pinching_hand:  small things I noticed when using PixelPaint :^)
> PixelPaint: A collection of small tweaks and fixes

- Userland/Libraries/LibCore/DateTime.cpp
> LibCore: Add %l conversion specification to DateTime

- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Had a few minutes for FIXME roulette, landed a real tough one :wink:
> LibWeb: Remove outdated FIXME regarding application cache selection

- Userland/Games/Flood/Board.cpp
- Userland/Games/Flood/Board.h
- Userland/Games/Flood/BoardWidget.cpp
- Userland/Games/Flood/main.cpp
No longer does a new game need to be started to apply the chosen color scheme.
A few refactors are also included to clean up the code.
> Flood: Apply the color scheme immediately after closing settings

- Userland/Libraries/LibGUI/Label.cpp
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/Painter.h
> LibGfx+LibGUI: Use constant for line spacing instead of magic number

- Tests/LibSQL/TestSqlDatabase.cpp
- Tests/LibSQL/TestSqlStatementExecution.cpp
- Userland/DevTools/SQLStudio/MainWidget.cpp
- Userland/Libraries/LibSQL/AST/AST.h
- Userland/Libraries/LibSQL/AST/CreateSchema.cpp
- Userland/Libraries/LibSQL/AST/CreateTable.cpp
- Userland/Libraries/LibSQL/AST/Delete.cpp
- Userland/Libraries/LibSQL/AST/Describe.cpp
- Userland/Libraries/LibSQL/AST/Insert.cpp
- Userland/Libraries/LibSQL/AST/Select.cpp
- Userland/Libraries/LibSQL/AST/Statement.cpp
- Userland/Libraries/LibSQL/CMakeLists.txt
- Userland/Libraries/LibSQL/Database.cpp
- Userland/Libraries/LibSQL/Database.h
- Userland/Libraries/LibSQL/Row.cpp
- Userland/Libraries/LibSQL/Row.h
- Userland/Libraries/LibSQL/Tuple.cpp
- Userland/Libraries/LibSQL/Tuple.h
- Userland/Libraries/LibSQL/Value.cpp
- Userland/Services/SQLServer/ConnectionFromClient.cpp
- Userland/Services/SQLServer/ConnectionFromClient.h
- Userland/Services/SQLServer/DatabaseConnection.cpp
- Userland/Services/SQLServer/DatabaseConnection.h
- Userland/Services/SQLServer/SQLServer.ipc
- Userland/Utilities/sql.cpp
Stuff needed for storing cookies in the Browser
> LibSQL: Partially implement the DELETE command, and other cleanups

- Base/res/html/misc/input.html
- Userland/Libraries/LibWeb/CSS/Default.css
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/Dump.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
[Screencast from 2022-11-30 22-06-58.webm](https://user-images.githubusercontent.com/5600524/205066234-4f0d2fb1-919c-4013-ab72-95089e1975b5.webm)
> LibWeb: Support displaying HTMLInputElement placeholder values

- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.from.js
Just two of many, slowly chipping away. Ref #15525.
> LibJS: Moar temporal normative changes

- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Bytecode/Pass/GenerateCFG.cpp
- Userland/Libraries/LibJS/Bytecode/Pass/MergeBlocks.cpp
- Userland/Libraries/LibJS/Bytecode/Pass/UnifySameBlocks.cpp
- Userland/Utilities/js.cpp
Current state:
~~`-3 ✅    -1021 ❌   +1024 💥️`~~
Done
> LibJS: Fix Bytecode optimizations for real this time

- .github/workflows/libjs-test262.yml
- Tests/LibJS/test262-runner.cpp
Co-req: linusg/libjs-test262#64
Co-req: linusg/libjs-website#26
> test262-runner: Add option to enable bytecode optimizations

- Base/usr/share/man/man1/strings.md
- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/strings.cpp
Based on the work of @checksum-fail (#16013) - it was almost ready for merging.
Let's try to get this merged again.
> Utilities: Add strings

- Kernel/Heap/Heap.h
- Kernel/Heap/kmalloc.cpp
This patch adds a way to ask the allocator to skip its internal scrubbing memset operation. Before this change, kcalloc() would scrub twice: once internally in kmalloc() and then again in kcalloc().
The same mechanism already existed in LibC malloc, and this patch brings it over to the kernel heap allocator as well.
This solves one FIXME in kcalloc(). :^)
> Kernel: Don't memset() allocated memory twice in kcalloc()

- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.h
This PR implements all the `PUSH seg` instructions as well as `MOV` in and out of segment registers.
> UserspaceEmulator: Implement various segment register access instructions

- Userland/Libraries/LibGfx/AntiAliasingPainter.cpp
- Userland/Libraries/LibGfx/AntiAliasingPainter.h
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/Painter.h
- Userland/Libraries/LibWeb/PixelUnits.h
Splitting up https://github.com/SerenityOS/serenity/pull/15989 into pieces. First, some adjustments to the Painter classes, and the introduction of the new pixel types.
> LibGfx+LibWeb: CSS Pixels part 1

- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
These changes make Acid2 boy chin to completely appear :-)
> LibWeb: Table formatting tweaks

- Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
- Userland/Applications/SpaceAnalyzer/TreeMapWidget.h
- Userland/Applications/SpaceAnalyzer/main.cpp
> SpaceAnalyzer: Add tooltips, and put the current path in the window title :trumpet: :lips: 

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/Namespaces.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/Range.cpp
- Userland/Libraries/LibWeb/DOM/Range.h
- Userland/Libraries/LibWeb/DOM/Range.idl
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Selection/Selection.cpp
- Userland/Libraries/LibWeb/Selection/Selection.h
https://user-images.githubusercontent.com/25595356/206780693-d5a4d2ee-6ad6-4308-8213-6b9685409e95.mp4
https://user-images.githubusercontent.com/25595356/206780759-22ce8f16-198a-4884-9af9-8067c61f5f25.mp4
> LibJS+LibWeb: Implement enough to load Discord messages and send GIFs :^)

- Userland/Applications/SystemMonitor/ProcessModel.cpp
- Userland/Demos/CatDog/CatDog.cpp
- Userland/Demos/CatDog/CatDog.h
- Userland/DevTools/Profiler/main.cpp
- Userland/Libraries/LibCore/ProcessStatisticsReader.cpp
- Userland/Libraries/LibCore/ProcessStatisticsReader.h
- Userland/Libraries/LibCore/SessionManagement.cpp
- Userland/Libraries/LibGUI/RunningProcessesModel.cpp
- Userland/Services/WindowServer/Window.cpp
- Userland/Utilities/killall.cpp
- Userland/Utilities/lsof.cpp
- Userland/Utilities/netstat.cpp
- Userland/Utilities/pgrep.cpp
- Userland/Utilities/pidof.cpp
- Userland/Utilities/pkill.cpp
- Userland/Utilities/ps.cpp
- Userland/Utilities/top.cpp
- Userland/Utilities/w.cpp
One down, approximately five million to go.
> LibCore: Use `Core::Stream` for `ProcessStatisticsReader`

- AK/Endian.h
- Meta/Lagom/Fuzzers/FuzzGzipDecompression.cpp
- Tests/LibCompress/TestGzip.cpp
- Userland/Libraries/LibCompress/Gzip.cpp
- Userland/Libraries/LibCompress/Gzip.h
- Userland/Libraries/LibCore/Stream.cpp
- Userland/Libraries/LibCore/Stream.h
- Userland/Libraries/LibCoredump/Reader.cpp
- Userland/Libraries/LibHTTP/Job.cpp
- Userland/Utilities/gunzip.cpp
- Userland/Utilities/gzip.cpp
- Userland/Utilities/tar.cpp
Not sure about the `WrapInAKStream` name, but other than that I think this is in pretty good shape. :^)
> AK+LibCore+LibCompress: Port `GzipDecompressor` to `Core::Stream`

- .github/workflows/lintcommits.yml
- Meta/lint-commit.sh
I hope that will reduce the number of human written message to request a rebase instead.
> CI: Add a check to report git merge commit

- Kernel/Thread.cpp
The two "hostile" flags I can think of are DF (direction flag) and TF (trap flag).
DF defines data direction for x86 string instructions, and is required to be 0 by the ABI. Not doing so will break any code that uses string instructions and expects it to be 0.
TF is a debugging feature that basically means "issue #DB exception after each instruction". Accepting a signal with TF being set will cause the thread to crash after executing the first instruction of the signal trampoline.
The latter makes it impossible to delegate sanitizing flags to a signal trampoline, thus doing it in kernel is necessary.
> Kernel: Set EFLAGS/RFLAGS to a known-good value on signal entry

- .github/workflows/lintcommits.yml
I really hope that this is the last one
> CI: Third time the charm

- Meta/Lagom/CMakeLists.txt
- Userland/Libraries/LibCore/StandardPaths.cpp
- Userland/Libraries/LibCore/StandardPaths.h
- Userland/Libraries/LibIPC/MultiServer.h
- Userland/Libraries/LibSQL/SQLClient.cpp
- Userland/Libraries/LibSQL/SQLClient.h
- Userland/Services/SQLServer/DatabaseConnection.cpp
- Userland/Services/SQLServer/DatabaseConnection.h
- Userland/Utilities/sql.cpp
Ladybird PR: https://github.com/SerenityOS/ladybird/pull/148
[Screencast from 2022-12-09 15-32-49.webm](https://user-images.githubusercontent.com/5600524/206804015-1593b627-101f-4f29-872c-afa815f37d85.webm)
> LibSQL: Support launching a singleton SQLServer instance for Lagom hosts

- AK/Checked.h
- AK/DeprecatedString.h
- AK/Error.h
- AK/Format.cpp
- AK/Format.h
- AK/Forward.h
- AK/HashMap.h
- AK/NonnullRefPtr.h
- AK/Optional.h
- AK/StringBuilder.cpp
- AK/StringBuilder.h
- AK/StringView.h
- AK/TypeCasts.h
- AK/Variant.h
- AK/WeakPtr.h
Port over all the (useful) extensions made in Jakt.
This is a requirement for https://github.com/SerenityOS/jakt/pull/1284.
> Stop! AK + Jakt Time! (part 1 of N)

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
This makes the shadows between the keys on https://codepen.io/fossheim/pen/BaKQGZJ _mostly_ work :^)
| Before                                                                                                          | After                                                                                                           |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/11597044/206876604-a8528ac6-8e94-49b2-827c-d49eb103a479.png) | ![image](https://user-images.githubusercontent.com/11597044/206876389-d050a329-6c14-4ca1-b3c2-3f37f9063a3e.png) |
> LibWeb: Support `calc()` values in `background-position`

- Userland/Shell/main.cpp
This also disables the full suite of interactive stuff in LibLine.
cc @ADKaster
> Shell: Disable interactive mode on '-c'

- AK/Platform.h
- AK/Random.h
Except Time.cpp, which is not needed for Jakt so I don't care :P
> AK: Two tiny changes to make it compile on windoze

- Userland/Libraries/LibCore/Stream.cpp
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibCore/System.h
Take care of the last (if we consider open PR) FIXME in `LibCore::Stream`
> LibCore: Add a wrapper in `Core::System` and use it in `Stream`

- AK/Concepts.h
- Tests/LibCompress/TestDeflate.cpp
- Userland/Libraries/LibAudio/FlacLoader.cpp
- Userland/Libraries/LibAudio/MP3Loader.cpp
- Userland/Libraries/LibCompress/Brotli.cpp
- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
- Userland/Libraries/LibCompress/Gzip.cpp
- Userland/Libraries/LibCompress/Gzip.h
- Userland/Libraries/LibCompress/Zlib.cpp
- Userland/Libraries/LibCore/InputBitStream.h
- Userland/Libraries/LibCore/Stream.h
- Userland/Libraries/LibHTTP/Job.cpp
- Userland/Utilities/unzip.cpp
> LibCompress(+LibCore): Port `DeflateCompressor` to `Core::Stream`

- AK/Atomic.h
- AK/DeprecatedString.h
- AK/Format.h
- AK/Function.h
- AK/OwnPtr.h
- AK/RefPtr.h
- AK/StdLibExtras.h
- AK/TypedTransfer.h
- AK/Types.h
- AK/WeakPtr.h
- Kernel/Library/LockRefPtr.h
- Kernel/Library/LockWeakPtr.h
- Tests/AK/TestTypeTraits.cpp
- Tests/LibAudio/TestFLACSpec.cpp
- Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.cpp
- Userland/Applications/Presenter/Presentation.cpp
- Userland/DevTools/Profiler/Profile.h
- Userland/Libraries/LibCore/System.h
- Userland/Libraries/LibCrypto/ASN1/DER.cpp
- Userland/Libraries/LibCrypto/ASN1/DER.h
- Userland/Libraries/LibGUI/FileIconProvider.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Heap/GCPtr.h
- Userland/Libraries/LibJS/SafeFunction.h
- Userland/Libraries/LibPDF/Value.cpp
- Userland/Libraries/LibPDF/Value.h
- Userland/Libraries/LibSQL/SQLClient.cpp
This should be the last of them :tm:!
> Everywhere: !USING_AK_GLOBALLY (Jakt integration part 4 of 4)

- Userland/Demos/CatDog/CatDog.cpp
- Userland/Demos/CatDog/CatDog.h
- Userland/Demos/CatDog/main.cpp
- Userland/Games/Minesweeper/Field.cpp
- Userland/Games/Minesweeper/Field.h
- Userland/Games/Minesweeper/main.cpp
- Userland/Games/Snake/SnakeGame.cpp
- Userland/Games/Snake/SnakeGame.h
- Userland/Games/Snake/main.cpp
Trying to make a dent in the FIXME count.
> Snake+CatDog+Minesweeper: Propagate errors while loading UI bitmaps

- Userland/Libraries/LibArchive/TarStream.cpp
- Userland/Libraries/LibArchive/TarStream.h
- Userland/Utilities/tar.cpp
Also included: Some error propagation.
> LibArchive: Port `TarOutputStream` to `Core::Stream`

- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Implement the values 'space-between' and 'space-around' of the 'align-content' flexbox property.
The following WPT tests now pass:
- http://wpt.live/css/css-flexbox/align-content-004.htm
- http://wpt.live/css/css-flexbox/align-content-005.htm
> LibWeb: Implement more values of flexbox align-content

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
left a couple FIXMEs. it looks like the `multiple` attribute is not implemented yet, so I did not handle that case for the email type, and also sometimes there are 53 weeks in a year.
> Implement remaining value sanitation algorithms

- Base/usr/share/man/man1/dd.md
Hello, I'm a first time contributor 👋
This PR adds a man page for the `dd` command, I found it mentioned in #11311 
Let me know if anything looks off!
> Base: Add man page for the dd command

- Userland/Demos/VirGLDemo/VirGLDemo.cpp
- Userland/Demos/VirGLDemo/Widget.cpp
- Userland/Demos/VirGLDemo/Widget.h
This removes a measly 1 FIXME :))
> VirGLDemo: Make a factory function for Demo and propagate errors

- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
I thought this was going to be more exciting
> LibJS: Intl spec comment updates

- Userland/Applications/ClockSettings/TimeZoneSettingsWidget.cpp
- Userland/Applications/ClockSettings/TimeZoneSettingsWidget.h
- Userland/Applications/ClockSettings/main.cpp
- Userland/Libraries/LibGUI/SettingsWindow.h
This removes an unbelievable 4 FIXMEs :))
> Propagate errors in ClockSettings

- Userland/DevTools/HackStudio/Debugger/DebugInfoWidget.cpp
- Userland/DevTools/HackStudio/Debugger/DebugInfoWidget.h
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.h
- Userland/DevTools/HackStudio/main.cpp
- Userland/Libraries/LibGUI/TabWidget.h
After this PR we do error propagation in the DebugInfoWidget creation and as a result we get rid of 4 FIXMEs :)
> Propagate errors in Hackstudio's DebugInfoWidget

- Kernel/Net/Intel/E1000NetworkAdapter.cpp
This allows to handle errors on the adapter's creation and removes two FIXME's :))
> Kernel: Add a factory function for E1000NetworkAdapter

- Userland/Libraries/LibCore/DateTime.cpp
When we encounter an explicit timezone, we shift the time to UTC. Because we rely on `mktime`, we need to shift it to the local time before proceeding. If no explicit timezone is provided, local timezone is assumed.
This fixes the "timezone-offset extension" LibJS test running on machines with a non-UTC timezone offset.
> LibCore: Convert explicit timezone to local in `DateTime::parse`

- Meta/Lagom/CMakeLists.txt
- Userland/Applications/Browser/InspectorWidget.cpp
- Userland/Applications/Browser/InspectorWidget.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentServer.ipc
These changes are required for the Ladybird DOM inspector: https://github.com/SerenityOS/ladybird/pull/152 :^)
> LibWeb+Browser: Fix up several DOM inspector crashes and issues 

- Userland/Games/Snake/SnakeGame.cpp
- Userland/Games/Snake/SnakeGame.h
- Userland/Games/Snake/main.cpp
* Add pause/continue game menu action
* Don't hardcode the snake painting logic
* Add snake color chooser game menu action
*  Ignore default keydown events 
:^)
EDIT: Should be maybe change the default snake color? (maybe to green? although I'm definitely not a snake expert :))
> Snake improvements

- Userland/Applications/TextEditor/MainWidget.cpp
- Userland/Libraries/LibSyntax/Highlighter.cpp
- Userland/Libraries/LibSyntax/Highlighter.h
https://user-images.githubusercontent.com/16520278/208302192-d6daa153-bb64-49cb-a782-cea3e04fc906.mp4
> TextEditor+LibSyntax: Suggest saving new files with an extension from highlighter

- AK/Base64.cpp
- AK/Base64.h
- AK/UUID.cpp
- AK/UUID.h
- Tests/AK/TestBase64.cpp
- Userland/Applications/PixelPaint/Image.cpp
- Userland/Libraries/LibCore/Account.cpp
- Userland/Libraries/LibCrypt/crypt.cpp
- Userland/Libraries/LibHTTP/HttpRequest.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
- Userland/Libraries/LibWebSocket/WebSocket.cpp
- Userland/Services/WebServer/Client.cpp
- Userland/Utilities/useradd.cpp
> AK: De-`DeprecatedString`-ize `UUID` and Base64 encoding

- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Applications/PixelPaint/MainWidget.h
- Userland/Applications/PixelPaint/main.cpp
This fixes a dozen release_value_but_fixme_should_propage_errors
> PixelPaint: Propagate errors when creating images or layers

- Userland/Applications/FileManager/FileOperationProgressWidget.cpp
Before this patch we created ByteBuffer with the help of the VERIFY macro that could cause a crash of FileManager in case of memory allocation failures.
Now we propagate the error to a caller instead of using the `release_value_but_fixme_should_propagate_errors()` method.
> FileManager: Handle possible ByteBuffer allocation failure

- Meta/CMake/utils.cmake
Especially unicode.org likes to be down occasionally, so let's retry downloads from the Web Archive automatically if downloading from the primary URL failed.
> CMake: Fall back to the Web Archive when downloading files

- Kernel/FileSystem/VirtualFileSystem.cpp
Also, try to resolve the target path and check if it is allowed to be accessed under the unveil rules.
Related to #15996, although this case was not explicitly stated in the report. This fixes the third case though ("Bypass using coredumps").
> Kernel/FileSystem: Prevent symlink creation in veiled directory paths

- Base/usr/share/man/man7/Mitigations.md
> Base: Mention new immutable memory mappings security feature

- Userland/Applications/FileManager/main.cpp
- Userland/Games/GameOfLife/main.cpp
- Userland/Services/Taskbar/main.cpp
> FileManager+GameOfLife+Taskbar: Propagate errors while loading bmp

- Userland/Libraries/LibGfx/BMPLoader.cpp
- Userland/Libraries/LibGfx/DDSLoader.cpp
- Userland/Libraries/LibGfx/GIFLoader.cpp
- Userland/Libraries/LibGfx/JPGLoader.cpp
> LibGfx: propagate errors

- Userland/DevTools/HackStudio/Git/GitWidget.cpp
- Userland/DevTools/HackStudio/Git/GitWidget.h
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
Fixes: https://github.com/SerenityOS/serenity/issues/15715
> HackStudio: Make a new ProjectBuilder object when opening a project

- Ladybird/CMakeLists.txt
- Ladybird/DOMNodeProperties.h
- Ladybird/InspectorWidget.cpp
- Ladybird/InspectorWidget.h
- Ladybird/ModelTranslator.cpp
- Ladybird/ModelTranslator.h
- Ladybird/WebContentView.cpp
- Ladybird/WebContentView.h
I'm going to _presumptuously_ tag this as maintainer approved as this was merged into the ladybird repo (https://github.com/SerenityOS/ladybird/pull/152), but missed the boat for the initial import into the monorepo :^)
> Ladybird: Import the DOM inspector changes too

- Base/usr/share/man/man2/pledge.md
I forgot about this pledge promise I created, so here I leave a fix for my mistake :)
> Base: Mention pledge promise for jail-specific syscalls

- Userland/Applications/PixelPaint/LayerListWidget.cpp
- Userland/Applications/PixelPaint/LayerListWidget.h
- Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp
- Userland/Libraries/LibGUI/AbstractScrollableWidget.h
- Userland/Libraries/LibGUI/AbstractView.cpp
- Userland/Libraries/LibGUI/AbstractView.h
- Userland/Libraries/LibGUI/GlyphMapWidget.cpp
- Userland/Libraries/LibGUI/GlyphMapWidget.h
- Userland/Libraries/LibGUI/IconView.cpp
- Userland/Libraries/LibGUI/IconView.h
- Userland/Libraries/LibGUI/Scrollbar.cpp
- Userland/Libraries/LibGUI/Scrollbar.h
- Userland/Libraries/LibGUI/TextEditor.cpp
- Userland/Libraries/LibGUI/TextEditor.h
- Userland/Libraries/LibGUI/Window.cpp
[Untitled.webm](https://user-images.githubusercontent.com/66646555/209416827-a9dd2890-28cf-46dd-9d96-5eac9c6d55d2.webm)
> LibGUI: Snappier, standardized automatic selection scrolling for TextEditor/GlyphMapWidget

- Userland/Services/WebServer/Client.cpp
- Userland/Services/WebServer/Client.h
- Userland/Services/WebServer/Configuration.cpp
- Userland/Services/WebServer/Configuration.h
- Userland/Services/WebServer/main.cpp
This PR tries to move away from `DeprecatedString` as much as possible without causing too much pain.
Any suggestions welcome!
Hope this is mostly a good change :^)
> WebServer: Small code improvements + Introducing String

- Userland/Utilities/strace.cpp
> strace: Propagate errors

- Base/res/html/misc/margin-collapse-3.html
- Base/res/html/misc/margin-collapse-4.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
> LibWeb: Implement margin collapsing between parent and first child

- Kernel/Arch/aarch64/ASM_wrapper.h
- Kernel/Arch/aarch64/Processor.h
- Userland/Libraries/LibC/fenv.cpp
> Kernel/aarch64: Make the ARM Kernel build with Clang

- Ladybird/WebDriver/main.cpp
- Ladybird/cmake/EnableLagom.cmake
- Userland/Libraries/LibGfx/ICCProfile.cpp
- Userland/Libraries/LibGfx/ICCProfile.h
- Userland/Utilities/icc.cpp
…and add rendering intent dumping to `icc`.
> LibGfx+icc: Parse and print rendering intent from ICCProfile header

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
- Userland/Libraries/LibWeb/Loader/FrameLoader.h
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
> LibWeb: Implement enough stuff to be able to login to Twitter :^)

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/CMakeLists.txt
- Userland/Applications/Browser/History.cpp
- Userland/Applications/Browser/History.h
- Userland/Applications/Browser/History/HistoryModel.cpp
- Userland/Applications/Browser/History/HistoryModel.h
- Userland/Applications/Browser/History/HistoryWidget.cpp
- Userland/Applications/Browser/History/HistoryWidget.gml
- Userland/Applications/Browser/History/HistoryWidget.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
This PR adds ability to view history directly in browser :^)
**NOTE:** Currently it only shows history for current active tab.
> Browser: Add window to inspect history

- Base/usr/share/man/man1/ldd.md
- Userland/Libraries/LibELF/DynamicLinker.cpp
- Userland/Libraries/LibELF/DynamicLinker.h
- Userland/Utilities/ldd.cpp
This utility lets a user to figure out what are the dependency libraries
for an ELF dynamic object, whether it's a dynamically loaded executable
or dynamically loaded library.
cc @ADKaster
> Utilities: Introduce the ldd utility

- Userland/Libraries/LibGfx/ICCProfile.cpp
- Userland/Libraries/LibGfx/ICCProfile.h
- StringView as requested by a bunch of people
- VERIFY_NOT_REACHED
> Increase code Q u a l i t y in ICC code

- LICENSE
- Userland/Libraries/LibGUI/ColorPicker.cpp
- Userland/Libraries/LibGUI/OpacitySlider.cpp
- Userland/Libraries/LibGUI/OpacitySlider.h
This pull request makes the OpacitySlider in ColorPickers react to the color chosen in the widget :^)
This pull request also bumps to date range in LICENSE to go to 2023, happy new year!
Master:
https://user-images.githubusercontent.com/42888162/210158779-681b5f1d-2871-4568-9d8b-c3948e689a07.mp4
This pull request:
https://user-images.githubusercontent.com/42888162/210158766-89fa0f44-3622-4115-a351-08b742b8e4c1.mp4
> LibGUI: Make color picker opacity sliders react to the chosen color

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Ticking away some more boxes in https://github.com/SerenityOS/serenity/issues/15525 :^)
> LibJS: More Temporal refactoring

- Userland/Libraries/LibGfx/Painter.cpp
Same visual improvement as #16056, but for filled ellipses
> LibGfx: Improve non-antialiased and filled ellipse rendering

- .github/CODEOWNERS
For example, I had no idea 16687 was open and needed review.
> Meta: Mark myself a CODEOWNER of some paths to be alerted of related PRs

- Kernel/PerformanceManager.h
- Kernel/Process.h
- Kernel/Thread.h
- Userland/Libraries/LibCrypto/Hash/MD5.h
- Userland/Libraries/LibCrypto/Hash/SHA1.h
- Userland/Libraries/LibCrypto/Hash/SHA2.h
- Userland/Libraries/LibGfx/FillPathImplementation.h
- Userland/Libraries/LibRegex/C/Regex.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Utilities/touch.cpp
> Minor cleanups around `inline` and `static`

- Ports/libmpg123/patches/0001-Teach-the-multiple-configure-files-that-serenity-is-.patch
Hello friends! :^) One of the libmpg123 patches do not apply cleanly since b49c4eb94f27f8ad67a16c6a58003de33a9d5f2b. This PR fixes it.
> Ports: Fix the libmpg123 patch

- Userland/Applications/SoundPlayer/main.cpp
Otherwise running "SoundPlayer --help" on the terminal tries to open a file named "--help".
> SoundPlayer: Parse Main::Arguments with Core::ArgsParser

- Userland/Applications/SystemMonitor/main.cpp
Previously the stats was only updated once the first callback from refresh_timer fired.
It now makes an early stats update on launch, so something will appear in the graphs.
> SystemMonitor: Update stats/graph immediately on launch

- Userland/Libraries/LibCrypto/Hash/HashFunction.h
- Userland/Libraries/LibCrypto/Hash/MD5.cpp
- Userland/Libraries/LibCrypto/Hash/MD5.h
- Userland/Libraries/LibCrypto/Hash/SHA1.cpp
- Userland/Libraries/LibCrypto/Hash/SHA1.h
- Userland/Libraries/LibCrypto/Hash/SHA2.cpp
- Userland/Libraries/LibCrypto/Hash/SHA2.h
- Userland/Libraries/LibGfx/ICCProfile.cpp
- Userland/Libraries/LibGfx/ICCProfile.h
- Userland/Utilities/icc.cpp
> LibGfx+icc: Print profile id

- Meta/build-manpages-website.sh
Yes, I forgot. This includes bonus goodies like removing duplicated code and running pandoc in parallel!
> Meta: Overhaul the build-manpages-website.sh script to support nested sections

- Userland/DevTools/GMLPlayground/main.cpp
> GMLPlayground: Fill preview window with background color

- Base/usr/share/man/man7/boot_parameters.md
- Documentation/NetworkBoot.md
- Kernel/Arch/x86_64/ISABus/I8042Controller.cpp
- Kernel/Arch/x86_64/ISABus/I8042Controller.h
- Kernel/CommandLine.cpp
- Kernel/CommandLine.h
- Kernel/Devices/HID/HIDManagement.cpp
> Kernel: Fix i8042 scan code setting sequence for bare metal hardware

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimeConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimeConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthConstructor.cpp
Ticking away 3 more boxes in https://github.com/SerenityOS/serenity/issues/15525 :^)
> LibJS: Temporal changes

- Userland/Libraries/LibGfx/ICCProfile.cpp
…and some even smaller tweaks.
> LibGfx: Verify reserved ICC header bytes are zero

- Base/res/devel/templates/serenity-application/main.cpp
Applies changes as seen in https://github.com/SerenityOS/serenity/commit/0c24522635ec7f07e1fb69d9e1cd350d81e2248f.
I swear i was already writing a comment on a pr when it got merged
> Base: Make the serenity-application HackStudio template build again

- Userland/Applications/ThemeEditor/MainWidget.cpp
- Userland/Applications/ThemeEditor/MainWidget.h
- Userland/Applications/ThemeEditor/main.cpp
Last port to `Core::Stream` PR of the day
> ThemeEditor: Port to `Core::Stream`

- Meta/Lagom/Fuzzers/FuzzZip.cpp
- Userland/Libraries/LibArchive/Tar.cpp
- Userland/Libraries/LibArchive/Tar.h
- Userland/Libraries/LibArchive/TarStream.cpp
- Userland/Libraries/LibArchive/TarStream.h
- Userland/Libraries/LibArchive/Zip.cpp
- Userland/Libraries/LibArchive/Zip.h
- Userland/Utilities/tar.cpp
- Userland/Utilities/unzip.cpp
- Userland/Utilities/zip.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53913
> LibArchive: Stop using DeprecatedString + Fix OSS-Fuzz bug

- Userland/Utilities/blockdev.cpp
Lets use more of the fallible and modern Serenity APIs.
> blockdev: Use fallible and modern Serenity APIs

- Userland/Libraries/LibGUI/CommonLocationsProvider.cpp
- Userland/Libraries/LibGUI/CommonLocationsProvider.h
... and additionally port it to Core::Stream. :^)
> LibGUI: Make CommonLocationsProvider::load_from_json() failable

- AK/Math.h
Without i686 we can remove some implementations for sqrt and round_to.
---
Shouldn't have changed the functionality of the AARCH build, but would be nice if someone with an M1 or the like could verify that
> AK: Reoder AK/Math after the removal of i686

- .github/CODEOWNERS
Some relevant paths that I'd always like to review
> Meta: Add myself to CODEOWNERS

- Userland/Applications/VideoPlayer/CMakeLists.txt
- Userland/Applications/VideoPlayer/VideoFrameWidget.cpp
- Userland/Applications/VideoPlayer/VideoFrameWidget.h
- Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
- Userland/Applications/VideoPlayer/VideoPlayerWidget.h
- Userland/Applications/VideoPlayer/VideoPlayerWindow.gml
- Userland/Applications/VideoPlayer/main.cpp
- Userland/Libraries/LibGUI/Slider.cpp
This also improves error propagation in ```VideoPlayerWidget::initialize_menubar```.
> VideoPlayer: Port to GML

- Kernel/FileSystem/VirtualFileSystem.cpp
Resolves an issue where a kernel panic would occur if the file system failed to initialize or mount, due to how the FileSystem was already added to VFS's list. The newly-created FileSystem's destructor would fail as the object went out of scope (as the `TRY` returned an error), as a result of the object still remaining in the IntrusiveList.
This update makes `VirtualFileSystem::mount()` and `VirtualFileSystem::unmount()` symmetric in terms of their management of the file system lists.
1. Add a new block device (`-drive` in QEMU) that is _not_ formatted as an ext2 file system.
2. Mount with:
```
mkdir /tmp/drive
mount /dev/hdb /tmp/drive
```
3. PANIC:
```
24.746 [mount(52:52)]: Ext2FS: Bad super block magic
[mount(52:52)]: ASSERTION FAILED: !is_in_list()
[mount(52:52)]: …
```
> Kernel/FileSystem: Fix kernel panic during File System initialization or mount failure

- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Ticking away one more box in #15525 :^)
> LibJS: Update ISODaysInMonth in Calendar.cpp

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
This regressed in 6e93d89ee3108873a30bd0178b0f84fff3db3315.
> LibWeb: Ensure legacy constructors are defined on the global object

- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibCore/EventLoop.h
This hopefully makes EventLoop easier to understand.
> LibCore: Explain EventLoop and reorder some members in the header

- Userland/Applications/ThemeEditor/MainWidget.cpp
- Userland/Applications/ThemeEditor/MainWidget.h
- Userland/Applications/ThemeEditor/PreviewWidget.cpp
- Userland/Applications/ThemeEditor/PreviewWidget.h
- Take drop events from the whole window
- Fully load files on drop events
- Warn about unsaved changes on file drop
> ThemeEditor: Improve handling of file drops

- Ladybird/BrowserWindow.cpp
- Ladybird/BrowserWindow.h
- Ladybird/WebContentView.cpp
- Ladybird/WebContentView.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentServer.ipc
[zooooooom.webm](https://user-images.githubusercontent.com/19366641/212096195-73e27435-fed2-4e2e-a54f-d539ac50c45c.webm)
> LibWeb+Ladybird: Implement zoom :^)

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
> Browser: Implement zoom :^)

- Kernel/Syscalls/setpgid.cpp
- Userland/Applets/Audio/main.cpp
- Userland/Applications/3DFileViewer/main.cpp
- Userland/Applications/Browser/main.cpp
- Userland/Applications/Help/main.cpp
- Userland/Applications/HexEditor/main.cpp
- Userland/Applications/Magnifier/main.cpp
- Userland/Applications/Mail/main.cpp
- Userland/Applications/NetworkSettings/main.cpp
- Userland/Applications/PDFViewer/main.cpp
- Userland/Applications/PixelPaint/main.cpp
- Userland/Applications/Spreadsheet/main.cpp
- Userland/Applications/Terminal/main.cpp
- Userland/Applications/TextEditor/main.cpp
- Userland/Applications/ThemeEditor/main.cpp
- Userland/Applications/Welcome/main.cpp
- Userland/Demos/Eyes/main.cpp
- Userland/Demos/WidgetGallery/main.cpp
- Userland/DevTools/GMLPlayground/main.cpp
- Userland/Games/Chess/main.cpp
- Userland/Services/LoginServer/main.cpp
- Userland/Services/SpiceAgent/main.cpp
- Userland/Services/WebContent/main.cpp
- Userland/Services/WebDriver/main.cpp
- Userland/Utilities/aplay.cpp
- Userland/Utilities/logout.cpp
Complementary to [5dcc58d54ac7057f092ac9287a853e78015007c8](https://github.com/SerenityOS/serenity/commit/5dcc58d54ac7057f092ac9287a853e78015007c8).
> Kernel+Userland: Require "stdio" pledge promise for get_root_session_id, remove unveil calls on /sys/kernel/processes 

- Userland/Applications/GamesSettings/CardSettingsWidget.cpp
- Userland/Applications/GamesSettings/CardSettingsWidget.gml
- Userland/Applications/GamesSettings/CardSettingsWidget.h
- Userland/Applications/GamesSettings/main.cpp
> GamesSettings: Draw one of the previewed cards as "highlighted"

- AK/CircularBuffer.cpp
- AK/CircularBuffer.h
- Tests/AK/TestCircularBuffer.cpp
- Userland/Libraries/LibCore/Stream.h
This is preliminary work to ease the introduction of #16437.
cc @timschumi
> LibCore: Refactor in Core::Stream

- Userland/Utilities/df.cpp
- Userland/Utilities/du.cpp
- Userland/Utilities/ls.cpp
Such options existed in linux utilities of the same names.
> df+du+ls: Add an option to print the human readable sizes in powers of 10

- Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Ticking away two more boxes in https://github.com/SerenityOS/serenity/issues/15525 :^)
> LibJS: More catch-ups to Temporal changes

- Userland/Applications/Presenter/Presentation.cpp
- Userland/Applications/Presenter/Presentation.h
- Userland/Applications/Presenter/PresenterWidget.cpp
- Userland/Applications/Presenter/PresenterWidget.h
> Presenter: Disable "Next" and "Previous" actions when non-applicable

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
This adds a missing endpoint in #15551.
> WebDriver: Add computedrole endpoint

- Userland/Applications/Presenter/PresenterWidget.cpp
> Presenter: Restructure menu, increase minimum size

- Userland/Applications/SoundPlayer/PlaybackManager.cpp
- Userland/Applications/SoundPlayer/PlaybackManager.h
- Userland/Applications/SoundPlayer/Player.cpp
- Userland/Libraries/LibAudio/MP3Loader.cpp
- Userland/Libraries/LibAudio/MP3Loader.h
Various improvements to seeking accuracy and stability, particularly with playing MP3 files.
> LibAudio+SoundPlayer: Fix up general and MP3-specific seeking behavior

- AK/String.cpp
- AK/String.h
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateLocaleData.cpp
- Tests/AK/TestString.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Intl/CollatorCompareFunction.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatFunction.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DisplayNamesPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/ListFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/ListFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/LocalePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormatFunction.cpp
- Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormat.h
- Userland/Libraries/LibJS/Runtime/Promise.cpp
- Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibLocale/DateTimeFormat.cpp
- Userland/Libraries/LibLocale/Locale.cpp
- Userland/Libraries/LibLocale/Locale.h
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/Fetch/Body.cpp
Mostly Intl related, but also a couple other cases.
> AK+LibJS+LibLocale: Some more `DeprecatedString` -> `String` conversion

- Userland/DevTools/HackStudio/Debugger/VariablesModel.cpp
- Userland/DevTools/Profiler/DisassemblyModel.cpp
- Userland/Libraries/LibCoredump/Backtrace.cpp
- Userland/Libraries/LibDebug/DebugInfo.cpp
- Userland/Libraries/LibDebug/DebugInfo.h
- Userland/Libraries/LibDebug/Dwarf/AbbreviationsMap.cpp
- Userland/Libraries/LibDebug/Dwarf/AbbreviationsMap.h
- Userland/Libraries/LibDebug/Dwarf/AddressRanges.cpp
- Userland/Libraries/LibDebug/Dwarf/AddressRanges.h
- Userland/Libraries/LibDebug/Dwarf/AttributeValue.cpp
- Userland/Libraries/LibDebug/Dwarf/AttributeValue.h
- Userland/Libraries/LibDebug/Dwarf/CompilationUnit.cpp
- Userland/Libraries/LibDebug/Dwarf/CompilationUnit.h
- Userland/Libraries/LibDebug/Dwarf/DIE.cpp
- Userland/Libraries/LibDebug/Dwarf/DIE.h
- Userland/Libraries/LibDebug/Dwarf/DwarfInfo.cpp
- Userland/Libraries/LibDebug/Dwarf/DwarfInfo.h
- Userland/Libraries/LibDebug/Dwarf/DwarfTypes.h
- Userland/Libraries/LibDebug/Dwarf/Expression.cpp
- Userland/Libraries/LibDebug/Dwarf/Expression.h
- Userland/Libraries/LibDebug/Dwarf/LineProgram.cpp
- Userland/Libraries/LibDebug/Dwarf/LineProgram.h
- Userland/Libraries/LibSymbolication/Symbolication.cpp
Making the constructors fallible I'll leave to someone else.
> LibDebug: `Core::Stream` and error propagation

- AK/String.cpp
Saving the world one byte at a time
> AK: Reduce String's allocated data by one byte

- Userland/Libraries/LibJS/Runtime/JSONObject.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
> LibJS: Use is_unicode_surrogate more

- Ladybird/CMakeLists.txt
- Ladybird/LocationEdit.cpp
- Ladybird/LocationEdit.h
- Ladybird/Tab.cpp
- Ladybird/Tab.h
> Ladybird: Add LocationEdit Highlighting

- Kernel/FileSystem/VirtualFileSystem.cpp
- Userland/Applications/FileManager/DirectoryView.cpp
- Userland/Applications/SpaceAnalyzer/main.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/Libraries/LibCore/File.cpp
- Userland/Libraries/LibCore/File.h
Based on the work in #15093.
I fixed the issues that were raised by @linusg comments, so I think we could merge this right now :)
> Kernel+LibCore+FileManager+HackStudio+SpaceAnalyzer: Sticky bit fixes

- Userland/Applications/PixelPaint/Layer.cpp
This PR expands the functionality of the "Crop Image to Content" and "Crop Layer to Content" features by allowing them to detect and crop the background color of an image instead of just cropping transparent pixels.
The background color is determined by looking at the corner pixels of the image. If no background color is found, the old behavior of cropping transparent pixels is retained.
Video:
https://user-images.githubusercontent.com/2817754/213524406-a02ed9a0-ad8c-40a8-9b5f-c9c4c95a051b.mp4
> PixelPaint: Use background color when cropping layer to content

- Userland/Libraries/LibCpp/AST.cpp
- Userland/Libraries/LibCpp/AST.h
- Userland/Libraries/LibCpp/Parser.cpp
- Userland/Libraries/LibCpp/Parser.h
- Userland/Libraries/LibCpp/Tests/parser/using-namespace.ast
- Userland/Libraries/LibCpp/Tests/parser/using-namespace.cpp
This gets us a little bit closer to a fully capable C++ parser.
> LibCpp: Parse 'using namespace' declarations

- Userland/Libraries/LibWeb/DOM/NodeFilter.h
- Userland/Libraries/LibWeb/DOM/NodeIterator.cpp
- Userland/Libraries/LibWeb/DOM/TreeWalker.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
A very small step towards making "element click" work, but I realised that further progress requires a bunch of infrastructure we're missing. (And possibly rearranging how our webdriver code is split across processes. :grimacing:)
> WebDriver+WebContent+LibWeb: Progress towards clicking

- Userland/Libraries/LibGfx/JPGLoader.cpp
Most jpegs that use multi-tag ICCs are in CMYK format, so running `icc` on them still produces
Runtime error: Unsupported number of components in SOF
but it no longer prints several
jpg: Ignoring ICC profile spanning several chunks (1/9)
lines before that.
(And if I manually comment out that error message, the profile is printed fine. But we can't decode the actual pixel data yet.)
> LibGfx: Support ICCs in JPEGs that are split across several tags

- Userland/Libraries/LibLine/Editor.cpp
Previously we were crashing, which was excessive, if we can't read anymore, we should just return with an error.
> LibLine: Quit event loop when an error occurs on update

- Meta/Lagom/ReadMe.md
The document wasn't updated in 9c2211f246b.
> Meta: Derust fuzzer build docs

- Userland/Services/ConfigServer/main.cpp
- Userland/Services/SystemServer/Service.cpp
- Userland/Services/SystemServer/Service.h
- Userland/Services/SystemServer/main.cpp
Even if it's unintentional, it has some behaviour changes as it stopped leaking an unveiled path.
> SystemServer: Propagate errors

- Ladybird/Utilities.cpp
- Ladybird/Utilities.h
- Ladybird/main.cpp
If a setting is checked (true by default), then when starting up Ladybird go to the homepage.
> Ladybird: Go to homepage on init

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Element.idl
- Userland/Libraries/LibWeb/DOM/Event.cpp
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
- Userland/Libraries/LibWeb/DOM/ShadowRoot.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.idl
- Userland/Libraries/LibWeb/HTML/Focus.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Userland/Services/WebContent/WebDriverConnection.cpp
i was originally trying to implement CustomElements but uhh i underestimated the work needed for that so i picked something easier to cheer me up. haha
> LibWeb: Implement Element.attachShadow and Element.shadowRoot

- Userland/Applications/Piano/MainWidget.cpp
- Userland/Applications/Piano/MainWidget.h
- Userland/Applications/Piano/PlayerWidget.cpp
- Userland/Applications/Piano/PlayerWidget.h
- Userland/Applications/Piano/main.cpp
This is a fix-up of #16706. It's now rebased, and propagates more errors.
> Piano: Propagate errors in PlayerWidget

- Userland/Libraries/LibVideo/VP9/BitStream.cpp
- Userland/Libraries/LibVideo/VP9/Decoder.cpp
- Userland/Libraries/LibVideo/VP9/Decoder.h
- Userland/Libraries/LibVideo/VP9/LookupTables.h
- Userland/Libraries/LibVideo/VP9/SyntaxElementCounter.cpp
- Userland/Libraries/LibVideo/VP9/SyntaxElementCounter.h
- Userland/Libraries/LibVideo/VP9/TreeParser.cpp
After fixing a few regressions from the refactor and a few old issues, I'm able to play the rickroll :partyak:
https://user-images.githubusercontent.com/3149592/216525146-f5a87b9f-e326-48f7-ab27-90eef78d0987.mp4
> Video/VP9: The pull request in which I rickroll myself

- Ladybird/BrowserWindow.cpp
- Ladybird/Settings.cpp
- Ladybird/Settings.h
- Ladybird/SettingsDialog.cpp
- Ladybird/SettingsDialog.h
- Ladybird/main.cpp
- Ladybird: Design settings layout in horizzontal
- Ladybird: Add setting for page to open on new tab
> Ladybird: Add setting for page to open on new tab

- Userland/Applications/TextEditor/MainWidget.cpp
- Userland/Applications/TextEditor/MainWidget.h
- Userland/Applications/TextEditor/main.cpp
It also takes care of a simple fixme and add some error propagations.
> TextEditor: Port to Core::Stream

- Userland/Applications/SpaceAnalyzer/CMakeLists.txt
- Userland/Applications/SpaceAnalyzer/ProgressWindow.cpp
- Userland/Applications/SpaceAnalyzer/ProgressWindow.h
- Userland/Applications/SpaceAnalyzer/Tree.h
- Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
- Userland/Applications/SpaceAnalyzer/TreeMapWidget.h
- Userland/Applications/SpaceAnalyzer/main.cpp
(Not actually 🇵🇱)
This is mostly refactoring. I had other intentions but oh boy is TreeMapWidget tricky to wrap my head around. I'm quite tired already. :sleeping: 
- Propagate more errors
- Rename some things to match the code style and be more understandable
- Stop leaking a Tree object
> SpaceAnalyzer: Add polish 🇵🇱

- Documentation/LadybirdBuildInstructions.md
Instead of explaining custom build directories first and then following that up with a an explainer that Meta/serenity.sh is the easiest way to get the browser up and running to try it out was not very ergonmic.
Also reorganize some of the per-distro documentation to put the compiler requirements front and center.
Should address #16858
> Documentation: Reorganize Ladybird build docs to put easy path first

- Userland/Libraries/LibGUI/TextDocument.cpp
- Userland/Libraries/LibVT/TerminalWidget.cpp
Instead of iterating through the needle being searched one byte at a time (like an ascii string), we calculate its unicode code points first and then iterate through those.
> LibGUI+LibVT: Handle utf-8 search strings in find

- Userland/Games/Chess/ChessWidget.cpp
- Userland/Games/Chess/ChessWidget.h
- Userland/Libraries/LibChess/Chess.cpp
- Userland/Libraries/LibChess/Chess.h
Recycling some of my old branches :sweat_smile:
Not much but still some improvements
> Chess: Baby steps towards error propagations and String

- AK/Format.cpp
- Kernel/API/Syscall.h
- Kernel/FileSystem/SysFS/Subsystems/Kernel/Processes.cpp
- Kernel/Memory/MemoryManager.cpp
- Kernel/PerformanceEventBuffer.cpp
- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/Syscalls/execve.cpp
- Kernel/Syscalls/fork.cpp
- Kernel/Syscalls/inode_watcher.cpp
- Kernel/Syscalls/kill.cpp
- Kernel/Syscalls/pledge.cpp
- Kernel/Syscalls/process.cpp
- Kernel/Syscalls/thread.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
This takes 6 syscalls away from the big process lock. Most of them already had enough of their own lock protection, as far as I can tell. They're all fairly simple ones, but since this is new to me, beware of goofs!
> Kernel: Rescue some syscalls from the clutches of THE BIG LOCK :scream: 

- Userland/Applications/About/main.cpp
- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/WindowActions.cpp
- Userland/Applications/Browser/WindowActions.h
- Userland/Libraries/LibGUI/AboutDialog.cpp
- Userland/Libraries/LibGUI/AboutDialog.gml
- Userland/Libraries/LibGUI/AboutDialog.h
- Userland/Libraries/LibGUI/CMakeLists.txt
- Userland/Libraries/LibGUI/CommonActions.cpp
This manages to be an increase in line count, mostly because GML uses so many lines.
> LibGUI+About+Browser: Modernize AboutDialog

- Kernel/Syscalls/ptrace.cpp
- Kernel/Thread.cpp
- Userland/Applications/Debugger/main.cpp
- Userland/Libraries/LibDebug/DebugSession.cpp
- Userland/Libraries/LibDebug/DebugSession.h
> Debugger: Attach to process

- Kernel/CMakeLists.txt
- Kernel/FileSystem/Ext2FS/Inode.cpp
- Kernel/FileSystem/OpenFileDescription.cpp
~~Depends on #17264, so this is a draft.~~
> Kernel: Use `AK::Stream` to write packed binary data

- Userland/Applications/Piano/AudioPlayerLoop.cpp
- Userland/Applications/Piano/AudioPlayerLoop.h
- Userland/Applications/Piano/CMakeLists.txt
- Userland/Applications/Piano/ExportProgressWidget.gml
- Userland/Applications/Piano/ExportProgressWindow.cpp
- Userland/Applications/Piano/ExportProgressWindow.h
- Userland/Applications/Piano/main.cpp
This exposes that the export is pretty slow, but it's much nicer than having the GUI lock up for 20s :^)
> Piano: Show a progress window when exporting WAV

- Userland/Libraries/LibWeb/Fetch/Headers.cpp
- Userland/Libraries/LibWeb/Fetch/Headers.h
- Userland/Libraries/LibWeb/Fetch/Headers.idl
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
> LibWeb: Implement Headers.getSetCookie()

- Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Somehow I overlooked these in #16356.
> LibWeb: Use 'auto& vm =' once at beginning to reduce noise

- Userland/Libraries/LibWeb/CSS/Parser/ComponentValue.cpp
- Userland/Libraries/LibWeb/CSS/Parser/ComponentValue.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Token.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Token.h
- Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
String, string, string, string, everybody loves string!
> LibWeb: Convert CSS Token to new String classes

- Tests/LibRegex/Regex.cpp
- Userland/Libraries/LibC/bits/regex_defs.h
- Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
- Userland/Libraries/LibRegex/RegexByteCode.cpp
- Userland/Libraries/LibRegex/RegexOptimizer.cpp
- Userland/Libraries/LibRegex/RegexOptions.h
> LibRegex: Some moar fixes

- Userland/Libraries/LibGfx/ICC/Profile.cpp
- Userland/Libraries/LibGfx/ICC/Profile.h
> LibGfx: Tweak how ICC::Profile gets constructed

- Userland/Libraries/LibGfx/QOIWriter.cpp
- Userland/Libraries/LibGfx/QOIWriter.h
> LibGfx: Move QOIWriter implementation-only things into cpp file

- Userland/Libraries/LibGUI/TextBox.cpp
- Userland/Libraries/LibGUI/TextBox.h
- Userland/Libraries/LibGUI/TextEditor.cpp
Note: This is ported from the ladybird version #17077
> LibGUI: Add highlighting to `UrlBox`

- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Applications/PixelPaint/PaletteWidget.cpp
- Userland/Applications/PixelPaint/Tools/GradientTool.cpp
- Userland/Applications/PixelPaint/Tools/GradientTool.h
- Userland/Applications/PixelPaint/Tools/TextTool.cpp
- Userland/Applications/PixelPaint/Tools/TextTool.h
- Userland/Applications/PixelPaint/Tools/Tool.h
https://user-images.githubusercontent.com/16520278/218553187-9b2c8671-7950-4217-9da6-25f70635c055.mp4
> PixelPaint: Add an option for making a Gradient with a secondary color

- Userland/Libraries/LibGfx/BMPLoader.cpp
Also add a spec link and slightly more BMP_DEBUG output.
> LibGfx: Read embedded ICC profiles in .bmp files

- AK/SIMDMath.h
- Tests/AK/CMakeLists.txt
- Tests/AK/TestSIMD.cpp
- Userland/Libraries/LibSoftGPU/Device.cpp
- Userland/Libraries/LibSoftGPU/Device.h
Takes care of a `FIXME` and shows some minor improvements in profiles of Tux Racer.
> AK+LibSoftGPU: Faster fog

- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
This is how I originally wrote this class's conversion to String before hitting #17141
> LibJS: Use substrings-with-superstrings in Intl.NumberFormat's grouping

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMediaFeatureID.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOMParsing/XMLSerializer.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/NoSniffBlocking.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLStyleElement.cpp
It doesn't behave differently for now, but will do once we start using the new string types which use Unicode definitions of case sensitivity.
> LibWeb: Use is_ascii_case_insensitive_match() where the spec says to

- Base/usr/share/man/man6/BrickGame.md
~~I hope the piece names are not copyright infringement.~~
> Base: Improve BrickGame documentation

- Userland/Libraries/LibGUI/Clipboard.cpp
My attempt to implement #16875 
This PR allows items with no associated data to be copied to the clipboard, which fixes an issue in Spreadsheet where empty cells could not be copied and pasted.
> LibGUI: Allow clipboard items to have no associated data

- Userland/Libraries/LibGfx/JPEGLoader.cpp
> LibGfx: Rename all `JPG_*` macros to `JPEG_*` in JPEGLoader

- AK/StackInfo.cpp
StackInfo currently doesn't provide a OpenBSD implementation.
Ladybird compiles and starts without StackInfo,but it crashes frequently.
This change makes it a lot more stable on OpenBSD,works just as good as on FreeBSD now.
> AK/StackInfo: Add support for OpenBSD pthreads

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
This adds a missing endpoint in #15551.
> WebDriver: Add computedlabel endpoint

- Kernel/CMakeLists.txt
- Kernel/Graphics/Definitions.h
- Kernel/Graphics/DisplayConnector.cpp
- Kernel/Graphics/DisplayConnector.h
- Kernel/Graphics/Intel/Definitions.h
- Kernel/Graphics/Intel/DisplayConnectorGroup.cpp
- Kernel/Graphics/Intel/DisplayConnectorGroup.h
- Kernel/Graphics/Intel/NativeDisplayConnector.cpp
- Kernel/Graphics/Intel/NativeDisplayConnector.h
- Kernel/Graphics/Intel/NativeGraphicsAdapter.cpp
- Kernel/Graphics/Intel/NativeGraphicsAdapter.h
- Kernel/Graphics/Intel/Plane/DisplayPlane.cpp
- Kernel/Graphics/Intel/Plane/DisplayPlane.h
- Kernel/Graphics/Intel/Plane/G33DisplayPlane.cpp
- Kernel/Graphics/Intel/Plane/G33DisplayPlane.h
- Kernel/Graphics/Intel/Transcoder/AnalogDisplayTranscoder.cpp
- Kernel/Graphics/Intel/Transcoder/AnalogDisplayTranscoder.h
- Kernel/Graphics/Intel/Transcoder/DisplayTranscoder.cpp
- Kernel/Graphics/Intel/Transcoder/DisplayTranscoder.h
- Kernel/Graphics/Intel/Transcoder/PLL.cpp
- Kernel/Graphics/Intel/Transcoder/PLL.h
Another PR being related to #15502.
This time, I try to make the Intel GPU driver more sophisticated so we can add more Intel iGPUs as "being supported" to the actual hardware-supported list of this driver.
cc @ADKaster
> Kernel: Make foundations for expansion to support modern generations of Intel iGPU

- Userland/Libraries/LibGfx/JPEGLoader.cpp
- Userland/Libraries/LibGfx/JPEGLoader.h
No functional changes intended
> LibGfx: Spec link + more rename/cleanup

- Userland/DevTools/HackStudio/Editor.cpp
- Userland/Libraries/LibGUI/TextDocument.cpp
- Userland/Libraries/LibGUI/TextEditor.cpp
- Userland/Libraries/LibGUI/TextEditor.h
`TextEditor::paint_event()` is still a bit of a beast, but this helps a little bit.
> LibGUI: Simplify TextEditor in a few ways

- AK/HashTable.h
- Tests/AK/TestHashTable.cpp
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Utilities/tsort.cpp
+ 2 smaller changes to make the code a bit nicer
> AK: Update HashTables head and tail when shifting during deletion

- Userland/Libraries/LibGUI/TextEditor.cpp
We would previously count the width of all individual code points in multi-code point emoji for wrapping, thus not use all of the available space:
[te_word_before.webm](https://user-images.githubusercontent.com/5600524/220626684-1ef40e0b-5cf5-46d5-87ad-fe0d7d262754.webm)
<br />We would also happily break up emoji when wrapping "anywhere":
[te_any_before.webm](https://user-images.githubusercontent.com/5600524/220626771-ca01daed-64fe-4cb7-8f5c-f5a754312085.webm)
<br />Now we use Unicode word boundaries and respect emoji length:
[te_word_after.webm](https://user-images.githubusercontent.com/5600524/220626867-83192691-1ac3-4c32-aed9-17750aac02dd.webm)
<br />And don't break in the middle of an emoji:
[te_any_after.webm](https://user-images.githubusercontent.com/5600524/220626971-0ff17d4a-a7b2-4 …
> LibGUI: Wrap words at word break boundaries and don't break up emoji

- Userland/Libraries/LibGfx/Font/Emoji.cpp
Keycap emoji, for example, begin with ASCII digits. Instead, check the first code point for the Emoji Unicode property.
On a profile of scrolling around on the welcome page in the Browser, this raises the runtime percentage of Font::glyph_or_emoji_width from about 0.8% to 1.3%.
> LibGfx: Do not exclude all ASCII code points from emoji lookups

- Ladybird/InspectorWidget.cpp
- Ladybird/InspectorWidget.h
- Ladybird/WebContentView.cpp
- Meta/Lagom/CMakeLists.txt
This allows viewing the ARIA accessibility tree Epigenetic added in https://github.com/SerenityOS/serenity/pull/16430, but now in Ladybird!
> Ladybird: Support inspecting the accessibility tree 

- Kernel/Graphics/VirtIOGPU/GPU3DDevice.cpp
Before doing a check if offset_in_region + num_bytes of the transfer descriptor are together more than NUM_TRANSFER_REGION_PAGES * PAGE_SIZE, check that addition of both of these parameters will not simply overflow which could lead to out-of-bounds read/write.
Fixes #17518.
> Kernel: Prevent out-of-bounds read/write in VirtIO GPU3DDevice::ioctl

- Meta/Azure/Setup.yml
Let's see what the ol `brew doctor` has to say about this broken homebrew package.
> CI: Make sure to brew update in macOS Azure setup

- Userland/Libraries/LibGfx/ICC/BinaryWriter.cpp
We could make UnknownTagData hold on to undecoded, raw input data and write that back out when serializing. But for now, we don't.
On the flipside, this _does_ write unknown tags that have known types. We could have a mode where we drop unknown tags with known types. But for now, we don't have that either.
With this, we can for example reencode
/Library/ColorSync/Profiles/WebSafeColors.icc and icc (and other tools) can dump the output icc file. The 'ncpi' tag with type 'ncpi' is dropped while writing it, while the unknown tag 'dscm' with known type 'mluc' is written to the output. (That file is a v2 file, so 'desc' has to have type 'desc' instead of type 'mluc' which it would have in v4 files -- 'dscm' emulates an 'mluc' description in v2 files.)
> LibGfx: Drop tags of unknown type instead of writing invalid icc files

- Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
- Userland/Libraries/LibDeviceTree/FlattenedDeviceTree.cpp
No functional changes (on the happy path)
> AFewPlaces: Propagate errors from for_each_split_view()

- Userland/Libraries/LibGfx/WebPLoader.cpp
This reorganizes things so that:
* When initially decoding chunks, we only store pointers to their data and don't look at the contents
* We allow pausing decoding after decoding the first chunk, since that's where the dimensions are stored, and we don't need to read more than that if we only care about dimensions. (Currently inconsequential, but maybe we want to get dimensions after receiving the first few bytes off the network in the future.)
* We then have separate methods to interpret chunk data (only for the first few bytes which store the size, so far.)
---
Exciting screenshot:
```
% Build/lagom/file Tests/LibGfx/test-inputs/extended-lossless.webp
Tests/LibGfx/test-inputs/extended-lossless.webp: WebP image data, 417 x 223
```
> LibGfx: Decode WebP canvas size

- Tests/LibGfx/TestImageDecoder.cpp
> Tests: Use MUST more in TestImageDecoder

- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibUnicode/Emoji.cpp
- Userland/Libraries/LibUnicode/Emoji.h
> LibGfx+LibUnicode: Render text presentation emoji as text if we have its glyph

- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
This prevents us setting up the document of a removed browsing context container (BCC, e.g. <iframe>), which will cause a crash if the document contains a script that inserts another BCC as this will use the stale browsing context it previously set up, even if it's reinserted.
Required by Prebid.js, which does this by inserting an `<iframe>` into a `<div>` in the active document via innerHTML, then transfers it to the `<html>` element:
https://github.com/prebid/Prebid.js/blob/7b7389c5abdd05626f71c3df606a93713d1b9f85/src/utils.js#L597
This is done in the spec by removing all tasks and aborting all fetches when a document is destroyed:
https://html.spec.whatwg.org/multipage/document-lifecycle.html#destroy-a-document
See the code comments for a simplified example.
> LibWeb: Bail FrameLoader's load callbacks if associated BC is discarded (The Great Upstream 11/n)

- Userland/Libraries/LibWeb/DOM/Position.cpp
- Userland/Libraries/LibWeb/DOM/Position.h
- Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
- Userland/Libraries/LibWeb/Page/EditEventHandler.h
Support for moving across and deleting whole grapheme clusters in editable boxes
[Screencast from 2023-03-01 07-47-45.webm](https://user-images.githubusercontent.com/5600524/222144000-ca81bfe4-4656-42ee-8a42-12abcdff947e.webm)
> LibWeb: Some grapheme cluster handling

- Userland/Libraries/LibWeb/WebIDL/ExceptionOr.h
This reduces the size of `WebIDL::ExceptionOr<T>` as follows for a few different `T`s:
`WebIDL::ExceptionOr<void>`: 48 bytes to 40 bytes
`WebIDL::ExceptionOr<JS::Value>`: 48 bytes to 40 bytes
`WebIDL::ExceptionOr<String>`: 56 bytes to 40 bytes
> LibWeb: Store all members of WebIDL::ExceptionOr<T> in a single Variant

- Userland/Libraries/LibGfx/Font/ScaledFont.cpp
- Userland/Libraries/LibGfx/Painter.cpp
Particularly an improvement for LibWeb, where we weren't handling emoji widths in scaled fonts at all, nor was the LibWeb-specific text drawing API handling emoji widths:
[before.webm](https://user-images.githubusercontent.com/5600524/222438245-72fae64b-16c1-4556-ba7a-a66be7d97083.webm)
All comfy now:
[after.webm](https://user-images.githubusercontent.com/5600524/222438278-b0bcf833-ee41-4774-87ab-4d06c07db51e.webm)
> LibGfx: A couple more emoji glyph fixes

- Userland/Libraries/LibGUI/TextEditor.cpp
For vector fonts in particular, we need to take care to compute offsets using floating point math. For example, with Berkeley Mono at font size 16, with syntax highlighting enabled, we are currently truncating these offsets to integers. This results in a leftward-drift when we paint the text.
This changes the rect in which we paint syntax-highlighted text spans to a float rect. As we traverse the spans, we now no longer truncate any of the text offsets, and we draw the text in the correct positions.
This is likely not a complete solution. TextEditor blindly casts ints to floats all over, and we will want to make all of these (hundred+) float- aware. But this should be a step in the right direction and makes vector fonts immediately more comfortable to use.
Before: …
> LibGUI: Compute syntax-highlighted visual text spans using float rects

- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateEmojiData.cpp
This sorts the array of generated emoji data by code point (first by code point length, then by code point value). This lets us use a binary search to find emoji data, rather than the current linear search.
In a profile of scrolling around /home/anon/Documents/emoji.txt, this reduces the runtime of `Gfx::Emoji::emoji_for_code_points` from 69.03% to 28.42%. Within that, `Unicode::find_emoji_for_code_points` reduces from 28.42% to just 1.95%.
> LibUnicode: Use binary search for lookups into the generated emoji data

- Userland/Libraries/LibGfx/ICC/WellKnownProfiles.cpp
The values aren't 100% self-consistent, but it probably doesn't make a difference for u8 color data. Good enough for now. See all the links on #17714 for some more background.
> LibGfx: Fill in remaining values in built-in sRGB profile

- Tests/LibUnicode/TestEmoji.cpp
- Userland/Libraries/LibGUI/Action.cpp
- Userland/Libraries/LibGUI/Action.h
- Userland/Libraries/LibGUI/EmojiInputDialog.cpp
- Userland/Libraries/LibGUI/Toolbar.cpp
- Userland/Libraries/LibUnicode/Emoji.cpp
See also: https://github.com/SerenityOS/serenity/pull/15179#issuecomment-1242250434
> LibGUI: Paint emoji using text in the EmojiInputDialog

- Userland/Applications/VideoPlayer/VideoFrameWidget.cpp
- Userland/Applications/VideoPlayer/VideoFrameWidget.h
- Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
- Userland/Applications/VideoPlayer/VideoPlayerWidget.h
- Userland/Applications/VideoPlayer/VideoPlayerWindow.gml
Create submenu to set sizing mode, also add icon to the sizing mode cycling button.
> VideoPlayer: Create submenu to set sizing mode

- Kernel/Memory/ScopedAddressSpaceSwitcher.cpp
- Kernel/Time/TimeManagement.h
The aarch64 build on master right now is in a bit of a sad state, as it doesn't build without doing some hacks on the local.
These commits don't fix it completely, but they solve 2 issues that came up thanks to commit 4536b80
> Some fixes for the aarch64 build

- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
Implements https://w3c.github.io/webdriver/#dfn-waiting-for-the-navigation-to-complete
which is another thing I found missing trying to run WPT.
> WebContent: Wait for navigation to complete in WebDriver

- Kernel/Arch/x86_64/PCI/IDELegacyModeController.cpp
> Kernel: Fix variable shadowing issue in PCIIDELegacyModeController

- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Removal of dummy execution context in
9aca54091a53b5b287096311a6bbcfdd21f42d2f caused a crash in `execute_async_script` because of empty execution contexts stack during `create_resolving_functions` call.
> WebDriver: Fix crash in async execute script endpoint

- Userland/Libraries/LibGfx/FillPathImplementation.cpp
Previously, this would paint scanlines one pixel too long and segfault when painting AA scanlines that were <= 1px long.
No idea who did this, but if we find out we should revoke their coding license!
> LibGfx: Fix segfault and painting off-by-one in fill_path()

- Userland/Libraries/LibCompress/Deflate.cpp
This is performance-neutral, but Instruments.app had a hard time visualizing the very deeply nested stack frames here.
> LibCompress: Make DeflateCompressor::write() use loop, not recursion

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Don't try to reserve capacity for a variadic arguments list unless we actually have enough arguments to fill it with anything. Otherwise we may overflow to an extremely large size if, e.g., the argument count is 0 and the start of the variadic arguments is index 1.
> LibWeb: Prevent variadic arguments from reserving heaps of memory

- Ladybird/WebContent/main.cpp
- Meta/Lagom/Fuzzers/FuzzJs.cpp
- Meta/Lagom/Fuzzers/FuzzilliJs.cpp
- Meta/Lagom/Wasm/js_repl.cpp
- Tests/LibJS/test-bytecode-js.cpp
- Tests/LibJS/test262-runner.cpp
- Userland/Applications/Assistant/Providers.cpp
- Userland/Applications/Spreadsheet/Workbook.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.h
- Userland/Libraries/LibWeb/HTML/Worker.cpp
- Userland/Services/WebContent/main.cpp
- Userland/Utilities/js.cpp
This is sort of progress towards the end goal of this discussion:
<https://discord.com/channels/830522505605283862/830525031720943627/1085670094698455080>
I'm not sure yet if the VM is where those strings will end up, but since this creation is fallible anyways, we can get this out of the way regardless.
> LibJS+LibWeb: Fallible VM creation

- Meta/Azure/Lagom.yml
- Meta/Azure/Serenity.yml
- Meta/Azure/Setup.yml
- Meta/Lagom/Fuzzers/FuzzilliJs.cpp
Also fix the CI so that we can't miss failures like this again.
> Fuzzers: Use correct type name in FuzzilliJs fuzzer

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
This fix addresses issue where, if request headers contain "Connection: keep-alive", we keep socket open without letting client know that we support keep-alive connections. This can result in a large number of open and unused sockets.
> LibWeb: Add keep-alive in response if it present in request

- Userland/Libraries/LibJS/Runtime/Array.cpp
- Userland/Libraries/LibJS/Runtime/Array.h
- Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
This proposal has been merged into the main ECMA-262 spec. See:
https://github.com/tc39/ecma262/commit/4a32716
Note this includes some editorial changes made when the proposal was merged into the main spec, but are not in the proposal spec.
> LibJS: Update spec numbers / text for the Change Array by Copy proposal

- Base/etc/posixshrc
- Userland/Shell/AST.cpp
- Userland/Shell/ImmediateFunctions.cpp
- Userland/Shell/PosixLexer.h
- Userland/Shell/PosixParser.cpp
- Userland/Shell/Shell.h
- Userland/Shell/main.cpp
The power of mafs is truly horrifying
> Shell: Add support for POSIX-y arithmetics

- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
CORS cross-origin responses in the No CORS request mode provide an opaque filtered response, which is the original response with certain attributes removed/changed.
The relevant effect it has is setting the body to `null`, which means `body_bytes` has `Empty` in the process_response_consume_body callback. This effectively disables cross-origin linked resources (e.g. stylesheets).
However, the web actually depends on this, especially for stylesheets retrieved from a cross-origin CDN. For example, Shopify websites request stylesheets from `cdn.shopify.com` and Substack websites request stylesheets from `substackcdn.com`.
This makes this a specification bug, as this code was written from it.
The workaround is to read the actual body from the unfiltered response and then call …
> LibWeb: Add workaround to restore cross-origin stylesheet functionality

- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/ListFormat.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibTimeZone/TimeZone.cpp
Nothing exciting, but big normative merges are way easier to deal with with these out of the way
> LibJS: Couple of small Intl editorials

- Userland/Libraries/LibThreading/BackgroundAction.h
This change ensures that a reference to the BackgroundAction is held until after the error callback has executed on the event loop.
This fixes an intermittent crash in Assistant :^)
> LibThreading: Resolve BackgroundAction error callback use-after-free

- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Fixes parsing error on:
http://wpt.live/css/CSS2/positioning/position-relative-nested-001.xht
> LibWeb: Run XML parser input through encoding decoder

- Userland/Libraries/LibCore/DateTime.cpp
- Userland/Libraries/LibCore/DateTime.h
- Userland/Services/WebServer/Client.cpp
- Userland/Services/WebServer/Client.h
- **WebServer: Handle incomplete HTTP requests**
Makes WebServer actually work again.
- **WebServer: Use relative URLs for the directory listing**
Makes the links work correctly on @linusg 's Serenity web server.
- **LibCore: Add DateTime::to_string()**
Noticed this was missing when working on the next commit.
- **WebServer: Propagate more errors**
Yay error propagation!
> WebServer: Fix some things

- Tests/LibWeb/Layout/expected/flex-column-item-with-auto-height-depending-on-auto-width.txt
- Tests/LibWeb/Layout/input/flex-column-item-with-auto-height-depending-on-auto-width.html
- Userland/Libraries/LibWeb/Layout/AvailableSpace.h
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
This required a bunch of prep work to avoid regressing our existing layout tests. (Yay existing layout tests!)
> LibWeb: Handle flex column items with auto height that depends on auto width

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementName.cpp
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementName.h
> LibWeb: Implement custom element name validation and fix bug in element name validation

- AK/DeprecatedString.h
Tiny change to make https://github.com/SerenityOS/jakt/pull/1419 work.
> AK: Add DeprecatedString::from_utf8(StringView)

- Tests/LibWeb/Layout/expected/position-absolute-ignores-padding-of-position-relative-floating-parent.txt
- Tests/LibWeb/Layout/input/position-absolute-ignores-padding-of-position-relative-floating-parent.html
Adds a layout test for the fix in 488a979.
> Tests/LibWeb: Add layout test for layout fix in PR #15780

- Userland/Shell/PosixParser.cpp
- Userland/Shell/main.cpp
This gets us a bit further in LLVMs `config.guess`.
> Shell: Various fixes for POSIX boogs

- Userland/Libraries/LibCrypto/Checksum/CRC32.cpp
This implements Intel's slicing-by-8 algorithm for CRC checksums (only little endian CPUs for now, as I don't have a way to test big endian).
The original paper for this algorithm seems to have disappeared, but Intel's source code is still available as a reference:
https://sourceforge.net/projects/slicing-by-8/
As well as other implementations for reference:
https://docs.rs/slice-by-8/latest/src/slice_by_8/algorithm.rs.html
Using the "enwik8" file as a test (100MB uncompressed, commonly used in benchmarks: https://www.mattmahoney.net/dc/enwik8.zip), decompression time decreases from:
4.89s to 3.52s on Serenity (cold)
1.72s to 1.32s on Serenity (warm)
1.06s to 0.92s on Linux
> LibCrypto: Implement little endian CRC using the slicing-by-8 algorithm

- Userland/Applications/CrashReporter/main.cpp
Warn the user about seemingly known malloc() and free() patterns in the fault address.
This brings back the functionality that was removed recently in the 5416a37fdea815b2fc18c35a60d173f8cfa67709 commit, but this time we detect these patterns in userspace code and not in kernel code.
Closes #17651.
cc @ADKaster
> CrashReporter: Warn about malloc and free patterns in fault address

- Userland/Libraries/LibCompress/Deflate.cpp
...by removing `else` after `return`.
> LibCompress: Reduce indentation in CompressedBlock::try_read_more()

- Tests/LibWeb/Layout/expected/grid/auto-fill.txt
- Tests/LibWeb/Layout/expected/grid/auto-fit.txt
- Tests/LibWeb/Layout/expected/grid/basic.txt
- Tests/LibWeb/Layout/expected/grid/different-column-sizes.txt
- Tests/LibWeb/Layout/expected/grid/gap.txt
- Tests/LibWeb/Layout/expected/grid/image-in-grid.txt
- Tests/LibWeb/Layout/expected/grid/min-max-content.txt
- Tests/LibWeb/Layout/expected/grid/minmax.txt
- Tests/LibWeb/Layout/expected/grid/named-tracks.txt
- Tests/LibWeb/Layout/expected/grid/positions-and-spans.txt
- Tests/LibWeb/Layout/expected/grid/repeat.txt
- Tests/LibWeb/Layout/expected/grid/template-areas.txt
- Tests/LibWeb/Layout/input/grid/auto-fill.html
- Tests/LibWeb/Layout/input/grid/auto-fit.html
- Tests/LibWeb/Layout/input/grid/basic.html
- Tests/LibWeb/Layout/input/grid/different-column-sizes.html
- Tests/LibWeb/Layout/input/grid/gap.html
- Tests/LibWeb/Layout/input/grid/image-in-grid.html
- Tests/LibWeb/Layout/input/grid/min-max-content.html
- Tests/LibWeb/Layout/input/grid/minmax.html
- Tests/LibWeb/Layout/input/grid/named-tracks.html
- Tests/LibWeb/Layout/input/grid/positions-and-spans.html
- Tests/LibWeb/Layout/input/grid/repeat.html
- Tests/LibWeb/Layout/input/grid/template-areas.html
- Tests/LibWeb/Layout/layout_test.sh
Add the ability in layout_test.sh to pick up tests in subdirectories and add grid tests to try it out :^)
> LibWeb+Tests: Allow subdirectories in layout_test.sh and add grid tests

- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
> LibCompress: Make CanonicalCode::from_bytes() return ErrorOr<>

- Kernel/Arch/aarch64/Processor.cpp
- Kernel/Arch/aarch64/Processor.h
- Kernel/Arch/aarch64/RegisterState.h
- Kernel/Arch/aarch64/TrapFrame.cpp
- Kernel/Arch/aarch64/TrapFrame.h
- Kernel/Arch/aarch64/vector_table.S
- Kernel/Arch/x86_64/Processor.cpp
- Kernel/Arch/x86_64/Processor.h
- Kernel/CMakeLists.txt
- Kernel/Syscalls/execve.cpp
- Kernel/Syscalls/fork.cpp
With this (and with a couple local hacks to start things like the Finalization thread, which I believe is covered by #18131) SystemServer is able to start, mount the file systems, and start a couple other services before crashing :slightly_smiling_face:
> Kernel: Add AArch64 support to sys$fork & sys$execve

- Meta/debug-kernel.sh
- Toolchain/BuildIt.sh
Previously, we would unconditionally build GDB from source for the AArch64 toolchain. This commit makes it possible to use the system's `gdb` binary if it supports the architecture, or `aarch64-elf-gdb` if such a package is installed.
An `aarch64-elf-gdb` package will be available through Homebrew once this PR is merged: https://github.com/Homebrew/homebrew-core/pull/127323
> Toolchain+Meta: Support kernel debugging with host AArch64 GDB

- Kernel/Arch/aarch64/Processor.cpp
- Kernel/Arch/aarch64/Processor.h
This doesn't get us any further in the boot process, however, I saw a low hanging fruit and decided to implement it :)
> Kernel/aarch64: Implement `Processor::time_spent_idle()`

- Kernel/API/Syscall.h
- Kernel/Devices/SelfTTYDevice.cpp
- Kernel/FileSystem/SysFS/Subsystems/Kernel/Processes.cpp
- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/ProcessGroup.cpp
- Kernel/ProcessGroup.h
- Kernel/Syscalls/faccessat.cpp
- Kernel/Syscalls/fork.cpp
- Kernel/Syscalls/setpgid.cpp
- Kernel/TTY/SlavePTY.cpp
- Kernel/TTY/SlavePTY.h
Today: TTY stuff, session management, process groups, etc
> Kernel: More work towards LockRefPtr and big lock removal

- AK/CircularBuffer.cpp
- AK/CircularBuffer.h
- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Lzma.cpp
- Userland/Utilities/lzcat.cpp
- Userland/Utilities/tar.cpp
- Userland/Utilities/xzcat.cpp
Included for free are one or two small bugfixes.
> AK+LibCompress+Utilities: Speed up LZMA/XZ decompression to 1/10th of the time

- Userland/Libraries/LibJS/Runtime/Intl/Intl.cpp
This proposal has been merged into the main ECMA-402 spec. See:
https://github.com/tc39/ecma402/commit/81856b3
> LibJS: Update spec numbers for the Intl Enumeration proposal

- Base/res/html/misc/video-webm.html
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h
- Userland/Libraries/LibWeb/HTML/VideoTrack.cpp
- Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
- Userland/Libraries/LibWeb/Painting/VideoPaintable.h
- Userland/Libraries/LibWeb/WebIDL/Promise.h
https://user-images.githubusercontent.com/5600524/230734615-8d7a62b9-a8c0-4eec-a9e5-1efe4177a644.mp4
> LibWeb: Implement HTMLVideoElement `load`, `play`, `pause` and draw some basic controls

- Kernel/Memory/MemoryManager.cpp
- Kernel/Syscalls/mmap.cpp
- Userland/Libraries/LibELF/DynamicLoader.cpp
Just a couple of patches I had laying around and never actually PRed.
> Kernel & DynamicLoader: A couple of small fixes

- Meta/debug-kernel.sh
- Toolchain/BuildIt.sh
Otherwise, we end up building GDB without actually having to do so.
> Meta+Toolchain: Fix up detection of already installed compatible GDBs

- Kernel/Memory/MemoryManager.cpp
> Kernel/Memory: Explain better why we dont use the first 1 MiB on x86_64

- Base/usr/share/man/man2/readlink.md
- Ladybird/main.cpp
- Meta/Lagom/Tools/ConfigureComponents/main.cpp
- Tests/Kernel/TestKernelFilePermissions.cpp
- Tests/LibC/TestIo.cpp
- Tests/LibC/TestLibCMkTemp.cpp
- Tests/LibELF/test-elf.cpp
- Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.cpp
- Userland/Applications/Piano/AudioPlayerLoop.cpp
- Userland/Applications/Piano/AudioPlayerLoop.h
- Userland/Applications/Piano/main.cpp
- Userland/Libraries/LibAudio/WavWriter.cpp
- Userland/Libraries/LibAudio/WavWriter.h
- Userland/Libraries/LibCpp/Tests/parser/strace.ast
- Userland/Libraries/LibCpp/Tests/parser/strace.cpp
Part (2/n)
Trying to do this in chunks, so it's easier to review. If these need to have more changes or broader commits, let me know.
Found an issue in Piano where the exported WAV is corrupted on master. However, my changes have not affected the issue (I will make an issue if needed).
> Everywhere: Convert more stuff to `LibFileSystem`/`Core::File`

- Userland/Applications/SystemMonitor/ProcessModel.cpp
SystemMonitor had a bug in which it would crash in case there are zombie processes left in the system.
The fix for this is to check if a process has no threads (which will indicate that the process is a zombie and is waiting to be reaped), and if that's the case, artificially create a thread row that is just enough to represent the zombie process.
Fixes #18200.
> SystemMonitor: Handle zombie processes properly

- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
This will examine the algorithm known as "the end" from the HTML specification, which executes when parsing HTML markup has completed, and it's potential to observably run script or change certain attributes.
This currently executes in our engine when parsing HTML received from the internet during navigation, using document.{open,write,close}, setting the innerHTML attribute or using DOMParser. The latter two are only possible by executing script.
This has been causing some issues in our engine, which will be shown later, so we are considering removing the call to "the end" for these two cases.
Spoiler: the implications of running "the end" for DOMParser will be considered in the future. It is the only script-created HTML/XML parser remaining after this commit that uses "the end", …
> LibWeb: Return from "the end" during HTML fragment parsing

- AK/StdLibExtras.h
- Userland/Libraries/LibGfx/ICC/TagTypes.h
> LibGfx/ICC: Use mix() in CurveTagData::evaluate() 

- AK/ByteBuffer.h
- AK/FixedPoint.h
- Documentation/Links.md
- Userland/Libraries/LibGfx/GradientPainting.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
- Userland/Utilities/sed.cpp
> Everywhere: Fix a few typos

- Userland/Libraries/LibJS/Runtime/SetConstructor.cpp
- Userland/Libraries/LibJS/Runtime/SetPrototype.cpp
- Userland/Libraries/LibJS/Runtime/StringConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Symbol.cpp
- Userland/Libraries/LibJS/Runtime/Symbol.h
- Userland/Libraries/LibJS/Runtime/SymbolConstructor.cpp
- Userland/Libraries/LibJS/Runtime/SymbolPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/WeakMapConstructor.cpp
- Userland/Libraries/LibJS/Runtime/WeakMapPrototype.cpp
- Userland/Libraries/LibJS/Runtime/WeakRefConstructor.cpp
- Userland/Libraries/LibJS/Runtime/WeakRefPrototype.cpp
- Userland/Libraries/LibJS/Runtime/WeakSetConstructor.cpp
- Userland/Libraries/LibJS/Runtime/WeakSetPrototype.cpp
> LibJS: Comment all the things

- Userland/Applications/DisplaySettings/EffectsSettings.gml
- Userland/Applications/DisplaySettings/EffectsSettingsWidget.cpp
- Userland/Applications/DisplaySettings/EffectsSettingsWidget.h
- Userland/Libraries/LibGfx/Rect.h
- Userland/Services/WindowServer/Animation.cpp
- Userland/Services/WindowServer/Animation.h
- Userland/Services/WindowServer/Compositor.cpp
- Userland/Services/WindowServer/Compositor.h
- Userland/Services/WindowServer/ConnectionFromClient.cpp
- Userland/Services/WindowServer/ConnectionFromClient.h
- Userland/Services/WindowServer/Overlays.cpp
- Userland/Services/WindowServer/Overlays.h
- Userland/Services/WindowServer/SystemEffects.h
- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/WindowFrame.cpp
- Userland/Services/WindowServer/WindowFrame.h
- Userland/Services/WindowServer/WindowManager.cpp
- Userland/Services/WindowServer/WindowManager.h
- Userland/Services/WindowServer/WindowServer.ipc
https://user-images.githubusercontent.com/10320822/229683449-91f74331-ef66-41d0-8cd2-cb2ef95a969a.mp4
> WindowServer: Implement tile window overlay

- Kernel/Arch/aarch64/ASM_wrapper.h
- Kernel/Arch/aarch64/RPi/Framebuffer.cpp
- Kernel/Arch/aarch64/Registers.h
- Kernel/WorkQueue.cpp
This PR contains two fixes that make it possible to boot to the Desktop! Since a video says more than a thousand words:
https://user-images.githubusercontent.com/18349222/231252178-5d1c9739-9ca2-4c87-8919-b0a8a99fc0ed.mov
---
One commit adds the `volatile` modifier to various inline assembly statements, as this was causing a reordering of instructions that led to a crash. See the commit message for more details. And another commit changes the pixel order of the framebuffer to BGR, as that is the format that the WindowServer actually expects.
---
I actually had to disable the booting of the Terminal application, as well as the Taskbar applets, as this currently causes the system to deadlock. See the following patch:
<details><summary>Patch</summary>
```patch
diff --git …
```
> Kernel/aarch64: First sign of life of the Desktop and Taskbar

- AK/Math.h
- Kernel/Arch/aarch64/Processor.h
With these changes we are now able to successfully boot to the graphical environment with the aarch64 build! We are not able to interact with the system yet, since there is no mouse/keyboard support yet, but this is really awesome!
---
https://user-images.githubusercontent.com/18349222/231842074-accc87f5-8bec-4b32-8e51-ade95631f2f6.mov
---
Note: The patches in #18291 are also needed to get to this state.
> Kernel+AK/aarch64: Successfully boot to the graphical environment

- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
This change adds rules for background-attachment, background-clip, background-image, background-origin, background-position, background-repeat and background-size.
As a result, `Window.getComputedStyle()` will no longer return empty strings on these properties after a page is loaded, and the background shorthand will show the resolved values instead of the default ones. :^)
> LibWeb: Resolve more background-related properties

- Userland/Applications/PixelPaint/Tools/GradientTool.cpp
Updates gradient tool to correctly display preview when the active layer is smaller than the image by scaling and translating the gradient tool's preview according to the active layer. Changing the offset values for the gradient and its handles to be translated by the active layer's location rather than a default value of (0, 0) allows the gradient to be generated correctly when the active layer is either the size of the full image or smaller than it.
Updated version of #18277  . Closed that PR because I'm new to git and got myself into a bit of a mess with branches and such, got so messy I thought it would just be better to close that one and start from scratch. 
Fixes #18030
> PixelPaint: Correct gradient tool's position during preview

- Tests/LibCompress/TestLzma.cpp
Continuing from #18347, this hand-calculated test case (_someone_ should really write an LZMA compressor!) ensures that reading just-written data from the dictionary works fine in the context of LZMA decompression. The correctness of the test has been validated using XZ utils, which yields the exact same output.
> Tests: Add a test for LZMA repetition lengths beyond the distance

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/DocumentState.cpp
- Userland/Libraries/LibWeb/HTML/DocumentState.h
- Userland/Libraries/LibWeb/HTML/History.cpp
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.cpp
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.h
I would like to start incrementally merging parts of navigables refactor https://github.com/SerenityOS/serenity/pull/18219 and this is the first chunk of this work.
These commits are from Andreas's branch where he started working on navigables. I just rebased them. I am not really feeling comfortable with PR that consists 99% of someone else's work but all my further changes will be based on Andreas's branch so I need help with getting them merged first :)
> LibWeb: Introduce DocumentState and update SessionHistoryEntry

- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/MapPrototype.cpp
- Userland/Libraries/LibJS/Runtime/MathObject.cpp
- Userland/Libraries/LibJS/Runtime/NumberConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ObjectPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ProxyConstructor.cpp
- Userland/Libraries/LibJS/Runtime/StringObject.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
Continuation of #16405, #16455, #17209, #18336.
> LibJS: Comment all the things (continued)

- Userland/Libraries/LibVideo/PlaybackManager.cpp
- Userland/Libraries/LibVideo/PlaybackManager.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h
- Userland/Libraries/LibWeb/HTML/VideoTrack.cpp
- Userland/Libraries/LibWeb/HTML/VideoTrack.h
- Userland/Libraries/LibWeb/Painting/PaintContext.cpp
- Userland/Libraries/LibWeb/Painting/PaintContext.h
- Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
https://user-images.githubusercontent.com/5600524/231310908-ede52697-6ea4-404a-99d1-fdf9f274a420.mp4
<br />This also gives us looping:
https://user-images.githubusercontent.com/5600524/231310927-77644388-e02c-4ce0-8840-033c6e6245a9.mp4
> LibWeb: Begin implementing media resource seeking

- Userland/Games/MasterWord/MasterWord.gml
- Userland/Games/MasterWord/WordGame.cpp
- Userland/Games/MasterWord/main.cpp
- Userland/Games/Minesweeper/Field.cpp
- Userland/Games/Minesweeper/Field.h
- Userland/Games/Minesweeper/main.cpp
- Userland/Libraries/LibGUI/Statusbar.cpp
> MasterWord+Minesweeper: Use auto shrink, fix window dimensions

- Kernel/Storage/SD/Commands.h
- Kernel/Storage/SD/PCISDHostController.cpp
- Kernel/Storage/SD/Registers.h
- Kernel/Storage/SD/SDHostController.cpp
- Kernel/Storage/SD/SDHostController.h
- Kernel/Storage/SD/SDMemoryCard.cpp
Known issues:
* 64 bit addressing mode is not detected on qemu
* 64 bit does not seem to work when hardwired to do so
Any way, this is done now
> Kernel: Add ADMA support to the SD card driver

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/Focus.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.h
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
it's a part of https://github.com/SerenityOS/serenity/pull/18219
patches from Andreas's navigables work I need to get merge :)
> LibWeb: Introduce navigable and traversable

- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchController.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchController.h
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchParams.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
With these, Steam trailer videos can play (and auto-transition between trailers) :^)
https://user-images.githubusercontent.com/5600524/233092029-2d582be7-c4db-473d-bafe-2ff81750ade4.mp4
> LibWeb: Implement HTMLMediaElement features needed for Steam

- Base/res/html/misc/video-webm.html
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h
- Userland/Libraries/LibWeb/HTML/VideoTrack.cpp
- Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
https://user-images.githubusercontent.com/5600524/233369820-5a69eda4-be0c-4930-9e82-b4fbd549ebbc.mp4
> LibWeb: Implement the HTMLVideoElement poster attribute

- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Necessary but not sufficient for #18456.
> LibGfx/JPEG: Make non-zero-terminated APPn starts non-fatal

- Kernel/FileSystem/InodeWatcher.cpp
- Kernel/FileSystem/InodeWatcher.h
> Kernel: Road to remove LOCK_IN_CRITICAL_DEBUG flag (part 1)

- Userland/Utilities/adjtime.cpp
- Userland/Utilities/arp.cpp
- Userland/Utilities/asctl.cpp
- Userland/Utilities/chown.cpp
- Userland/Utilities/cksum.cpp
- Userland/Utilities/cmp.cpp
- Userland/Utilities/config.cpp
- Userland/Utilities/copy.cpp
- Userland/Utilities/dd.cpp
- Userland/Utilities/hexdump.cpp
- Userland/Utilities/kill.cpp
- Userland/Utilities/killall.cpp
- Userland/Utilities/ls.cpp
- Userland/Utilities/lsof.cpp
- Userland/Utilities/ntpquery.cpp
- Userland/Utilities/pro.cpp
- Userland/Utilities/readelf.cpp
- Userland/Utilities/sort.cpp
- Userland/Utilities/stty.cpp
- Userland/Utilities/touch.cpp
- Userland/Utilities/tr.cpp
- Userland/Utilities/useradd.cpp
- Userland/Utilities/wc.cpp
Some DeprecatedString migration and a couple of other minor things.
(Previously also: removing a bunch of libc includes.)
> Utilities: Some modernisation

- Ladybird/WebContent/main.cpp
- Userland/Applications/Browser/Browser.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/main.cpp
- Userland/Applications/BrowserSettings/AutoplaySettingsWidget.cpp
- Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.cpp
- Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.gml
- Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.h
- Userland/Applications/BrowserSettings/main.cpp
- Userland/Libraries/LibWeb/Loader/ContentFilter.cpp
- Userland/Libraries/LibWeb/Loader/ContentFilter.h
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/WebContentServer.ipc
Things I came across when making the autoplay allowlist
> Browser+Ladybird+LibWeb: Prevent infinite growth of content filters, port to String, propagate errors

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
A part of https://github.com/SerenityOS/serenity/pull/18219
> LibWeb: Implement getting navigable's traversable and top-level traversable

- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
> LibGfx: Decrease indent in ImageDecoder::try_create_for_raw_bytes() some

- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
A part of https://github.com/SerenityOS/serenity/pull/18219
> LibWeb: Implement Node::navigable()

- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
The lowest of hanging fruits I had a bit of time for
> LibWeb: Implement the HTMLMediaElement fastSeek method

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/WindowProxy.cpp
- Userland/Libraries/LibWeb/HTML/WindowProxy.h
> LibWeb: Implement "create a new browsing context and document" and supporting code

- AK/JsonArray.h
- AK/JsonParser.cpp
- Userland/Applications/Browser/BookmarksBarWidget.cpp
- Userland/Applications/Browser/BookmarksBarWidget.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Applications/BrowserSettings/BrowserSettingsWidget.cpp
- Userland/Applications/BrowserSettings/BrowserSettingsWidget.h
- Userland/Applications/BrowserSettings/main.cpp
- Userland/Applications/KeyboardMapper/KeyboardMapperWidget.cpp
- Userland/Applications/Spreadsheet/ExportDialog.cpp
- Userland/Applications/Spreadsheet/Spreadsheet.cpp
- Userland/DevTools/SQLStudio/MainWidget.cpp
- Userland/DevTools/SQLStudio/MainWidget.h
- Userland/DevTools/SQLStudio/main.cpp
- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibCore/Object.h
- Userland/Libraries/LibGUI/JsonArrayModel.cpp
- Userland/Libraries/LibGUI/JsonArrayModel.h
- Userland/Libraries/LibGUI/Layout.cpp
- Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebDriver/Session.cpp
- Userland/Shell/Shell.cpp
- Userland/Shell/Shell.h
Quite the Yakhole was explored here. Initially started off trying to `Convert JsonArrayModel to use Core::File` but these changes made it a lot easier to do so.
> AK+Everywhere: Add new failable JsonArray::{append/set} functions

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h
Implement https://github.com/whatwg/fetch/commit/ca10f49748f2289433ce75dcf1f2fcf451f4f24f
Fixes the issue I found while working on navigation: https://github.com/whatwg/fetch/issues/1629
> LibWeb/Fetch: Pass recursive=false to manual navigation redirect

- CONTRIBUTING.md
you may not like it, but this is what peak punctuation looks like
> Meta: Do not not contract the "not" in "don'ts"

- Userland/Applications/GamesSettings/ChessSettingsWidget.cpp
- Userland/Games/Chess/ChessWidget.cpp
- Userland/Libraries/LibChess/Chess.cpp
- Userland/Libraries/LibChess/Chess.h
- Userland/Libraries/LibChess/UCICommand.cpp
- Userland/Libraries/LibChess/UCICommand.h
- Userland/Libraries/LibChess/UCIEndpoint.cpp
- Userland/Services/ChessEngine/ChessEngine.cpp
Bugs fixed:
- We interpreted the `debug off` command as `debug on`
- We never included pawn positions in the FEN export, making it invalid
> LibChess: Fix some bugs, migrate to new String, and minor code cleanup

- Userland/Libraries/LibVideo/VP9/Parser.cpp
Previously, the `Parser::decode_tiles()` function wouldn't wait for the tile-decoding workers to finish before exiting the function, which could mean that the data the threads are working with could become invalid if the decoder is deleted after an error is encountered.
> LibVideo/VP9: Wait for workers to finish when there are decoding errors

- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/EventLoop/Task.h
- Userland/Libraries/LibWeb/HTML/HistoryHandlingBehavior.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/POSTResource.h
- Userland/Libraries/LibWeb/ReferrerPolicy/ReferrerPolicy.cpp
- Userland/Libraries/LibWeb/ReferrerPolicy/ReferrerPolicy.h
> LibWeb: Start fleshing out Navigable::navigate()

- Userland/Libraries/LibVideo/PlaybackManager.cpp
- Userland/Libraries/LibVideo/PlaybackManager.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
A little bit of cleanup we can do after #18493
> LibWeb+LibVideo: Remove hook to override LibVideo's playback timers

- Kernel/FileSystem/VirtualFileSystem.cpp
The log message can be hard to spot in a sea of debug messages. Colorize it to make the message more immediately pop out.
> Kernel: Colorize log message for paths which haven't been unveiled

- Userland/Libraries/LibWeb/HTML/BrowsingContextGroup.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContextGroup.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Implement creation of fresh top-level traversables 

- Ports/taskwarrior/package.sh
Simplifys the script and builds faster :)
cc @BenWiederhake
> Ports: Cleanup the build process a bit for taskwarrior

- Userland/Applications/DisplaySettings/MonitorWidget.cpp
A logical change following 7b10c8048cd1b6c6050aba2159e6a1f05c8e92f2.
> DisplaySettings: Show bilinear filtered wallpaper in `MonitorWidget`

- Tests/LibWeb/Layout/expected/table/rows-height-distribution-1.txt
- Tests/LibWeb/Layout/expected/table/rows-height-distribution-2.txt
- Tests/LibWeb/Layout/expected/table/rows-height-distribution-3.txt
- Tests/LibWeb/Layout/expected/table/rows-height-distribution-4.txt
- Tests/LibWeb/Layout/expected/table/zero-columns-gridmax.txt
- Tests/LibWeb/Layout/input/table/rows-height-distribution-1.html
- Tests/LibWeb/Layout/input/table/rows-height-distribution-2.html
- Tests/LibWeb/Layout/input/table/rows-height-distribution-3.html
- Tests/LibWeb/Layout/input/table/rows-height-distribution-4.html
- Tests/LibWeb/Layout/input/table/zero-columns-gridmax.html
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
- Calculate final table height
- Resolve percentage height of cells and rows using final table height
- Distribute avilable height to table rows
> LibWeb: Implement height to rows distribution in TFC 

- Userland/Applications/Spreadsheet/Cell.cpp
- Userland/Applications/Spreadsheet/Cell.h
- Userland/Applications/Spreadsheet/Spreadsheet.cpp
- Userland/Applications/Spreadsheet/Spreadsheet.h
- Userland/Applications/Spreadsheet/SpreadsheetModel.cpp
- Userland/Applications/Spreadsheet/SpreadsheetModel.h
- Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Undo and redo filling in color in Spreadsheet.
https://user-images.githubusercontent.com/60057590/229401577-02a31d77-05a4-42b0-9cc9-681c1033f6ad.mp4
> Spreadsheet: Enable undo/redo of bucket color fill

- Userland/Libraries/LibVideo/VP9/Decoder.cpp
Some occasional cases could cause the accumulator to overflow and have
an incorrect result. It would be nice to use a smaller accumulator, but
it seems not to be correct. :^(
> LibVideo/VP9: Make inter-prediction fast path accumulators 32-bit

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/Display.h
- Userland/Libraries/LibWeb/CSS/Identifiers.json
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/DisplayStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/DisplayStyleValue.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
This PR adds the parsing and conversion for the display multi-keyword syntax.
> LibWeb: multi-keyword support for display property

- Userland/Applications/HexEditor/HexEditorWidget.cpp
The "Toolbar" and "Bytes Per Row" actions were the only ones in the menu which had their state stored in the configuration.
Now, all of the layout options will be restored when you re-open HexEditor, how neat! :^)
> HexEditor: Remember all of the layout options in the configuration

- Userland/Utilities/profile.cpp
This pr fixes a fixme and improves a warning message in the profile utility.
> profile: Small improvements to the profile utility

- Userland/Applications/PixelPaint/Tools/GradientTool.cpp
| Before                                                                                                          | After                                                                                                           |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/11597044/236308606-173b472d-307e-415b-a3c4-d921a05aad24.png) | ![image](https://user-images.githubusercontent.com/11597044/236308706-1364cf72-915a-441a-8338-5581529f26c0.png) |
> PixelPaint: Minor gradient tool fixes 

- Userland/Applications/Piano/MainWidget.cpp
- Userland/Applications/Piano/MainWidget.h
- Userland/Applications/Piano/PlayerWidget.cpp
- Userland/Applications/Piano/PlayerWidget.h
- Userland/Applications/Piano/RollWidget.cpp
- Userland/Applications/Piano/TrackControlsWidget.cpp
- Userland/Applications/Piano/TrackControlsWidget.h
- Userland/Applications/Piano/TrackManager.h
- Userland/Libraries/LibDSP/Track.h
This makes Piano exactly as usable as when I started the large refactor some years ago, which *sounds* like I'm a terrible person but now it (1) looks nicer and (2) has a flexible backend that can already deal with aribtrary kinds of processors on any track.
Long demo:
https://user-images.githubusercontent.com/28656157/221591954-6720794d-ce4b-40f2-8018-ca37ed86ae5a.mp4
> Piano: Allow per-track controls (again)

- Userland/Libraries/LibGUI/ImageWidget.cpp
- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.h
- Userland/Libraries/LibGfx/ImageFormats/DDSLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/DDSLoader.h
- Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/GIFLoader.h
- Userland/Libraries/LibGfx/ImageFormats/ICOLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/ICOLoader.h
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
- Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/PNGLoader.h
- Userland/Libraries/LibGfx/ImageFormats/PortableImageMapLoader.h
- Userland/Libraries/LibGfx/ImageFormats/QOILoader.h
- Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/TGALoader.h
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.h
[apng_support.webm](https://user-images.githubusercontent.com/10320822/230774085-7a51908a-f95a-4264-8301-01013016c227.webm)
> LibGfx: Add support for animated PNG images

- Ladybird/CMakeLists.txt
- Ladybird/Icons/back.svg
- Ladybird/Icons/forward.svg
- Ladybird/Icons/reload.svg
- Ladybird/Settings.cpp
- Ladybird/Settings.h
- Ladybird/SettingsDialog.cpp
- Ladybird/SettingsDialog.h
- Ladybird/Tab.cpp
- Ladybird/Tab.h
- Ladybird/ladybird.qrc
- Ladybird/main.cpp
- Meta/Azure/Setup.yml
The icons can be refined, but we have to start somewhere :^)
> Ladybird: Vector icons in the toolbar + remove outdated "home" button

- Userland/Libraries/LibWeb/CSS/PercentageOr.h
- Userland/Libraries/LibWeb/CSS/Position.cpp
- Userland/Libraries/LibWeb/CSS/Size.cpp
- Userland/Libraries/LibWeb/CSS/Size.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
- Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
See individual commits for description.
> LibWeb: Miscellaneous layout cleanups & a boog fix

- Base/usr/share/man/man7/Tips-and-Tricks.md
The [very useful instructions](https://github.com/SerenityOS/serenity/blob/master/Documentation/TransferringFiles.md#method-1-webserver) on how to transfer files from QEMU to your host machine via the built-in web server are worthy of being included in the [Tips & Tricks man page](https://man.serenityos.org/man7/Tips-and-Tricks.html).
> Base: Add web server tip to Tips-and-Tricks(7)

- Base/usr/share/man/man1/netstat.md
- Userland/Utilities/netstat.cpp
This PR adds information about the user owning the process to our netstat output.
It also fixes multiple bugs that are the result of upstream changes in JsonObject.
> netstat: Add -e argument and fix multiple bugs

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
See also:
36ff6187f6f5e67ba3f2085b5257ec1de10cf79b
https://github.com/SerenityOS/serenity/pull/18682#issuecomment-1537249544
CC @trflynn89
> LibJS: Revert to original text in spec

- Userland/Libraries/LibWeb/DOM/Element.cpp
Layout will be identical for both of those values, so only a repaint is necessary. If it changes to/from "collapse" however, we do need to relayout. This means we can't simply use the "affects-layout" mechanism. We have to write a little bit of custom code.
This makes Google Groups (and surely many other sites) significantly more responsive by avoiding large amounts of layout work.
> LibWeb: Don't relayout when visibility changes between visible/hidden

- Tests/AK/TestJSON.cpp
At an attempt to detect future regressions in AK/JsonArray, this snapshot adds additional tests for it to TestJSON.cpp.
See https://github.com/SerenityOS/serenity/issues/18618 for more context.
> Tests: Add more tests for `JsonArray`

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Implement "populate session history entry" step in Navigable::navigate()

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/Layout/ImageBox.cpp
- Userland/Libraries/LibWeb/Layout/ImageBox.h
- Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
- Userland/Libraries/LibWeb/Painting/ImagePaintable.h
> LibWeb: Fix issue with GIF animations not starting until window is scrolled or resized

- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/main.cpp
> HexEditor: Add list of recently opened files

- Userland/Libraries/LibTextCodec/Decoder.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.h
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
- Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.cpp
- Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.h
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
> LibWeb+LibTextCodec: Implement fetching classic scripts using Fetch infrastructure

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
See individual commits for descriptions.
test262 says +4/-4. The new failures look like things that were incorrectly passing before.
> LibJS/Bytecode: Some improvements to exception handling

- Userland/Libraries/LibGfx/Painter.cpp
...and instead assume it's BGRx8888 or BGRA8888, for now. Always treating the target as BGRA8888 leads to the alpha channel being interpreted incorrectly sometimes (as can be seen with WindowServer overlays).
Fixes #18749
> LibGfx: Stop assuming the target format is always BGRA8888

- Userland/Libraries/LibWeb/HTML/Location.cpp
- Userland/Libraries/LibWeb/HTML/Location.h
- Userland/Libraries/LibWeb/HTML/Location.idl
Required by Steam to redirect you after a successful QR code login:
https://github.com/SerenityOS/serenity/assets/25595356/808dfb84-5b85-48e5-b59c-b23515838a0a
> LibWeb: Implement location.assign

- Base/usr/share/man/man1/ps.md
- Userland/Utilities/ps.cpp
`POSIX++`
There are of course [more options left](https://pubs.opengroup.org/onlinepubs/009695299/utilities/ps.html#tag_04_104_04) that Dr Posix demands, but this is already stretching my understanding of how processes work, so let's leave it here for now. :sweat_smile:
> ps: Add `-A`, `-a`, `-p`, and `-u` options, plus various other updates and improvements

- Ladybird/Tab.cpp
- Ladybird/Tab.h
- Ladybird/WebContentView.cpp
- Ladybird/WebContentView.h
- Userland/Applications/Browser/Tab.cpp
https://github.com/SerenityOS/serenity/assets/5600524/bd9fe4d3-438c-4be6-b091-e6ab1dff7ee7
> Ladybird: Add screenshot actions to the page context menu

- Userland/Applications/FontEditor/GlyphEditorWidget.cpp
- Userland/Applications/FontEditor/GlyphEditorWidget.h
- Userland/Applications/FontEditor/MainWidget.cpp
- Userland/Applications/FontEditor/MainWidget.h
- Userland/Applications/FontEditor/UndoSelection.h
- Userland/Applications/FontEditor/main.cpp
Hooks up a few of the newer UI flourishes
> FontEditor: Undo/Redo action text, Recently opened files, BitmapFont FileTypeFilter

- Userland/Applications/ImageViewer/main.cpp
- Userland/Applications/PixelPaint/LayerListWidget.cpp
- Userland/Applications/PixelPaint/ResizeImageDialog.cpp
- Userland/Applications/PixelPaint/ResizeImageDialog.gml
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/Painter.h
- Userland/Libraries/LibGfx/Rect.h
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
- Userland/Libraries/LibWeb/Painting/CanvasPaintable.cpp
- Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
- Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
> LibGfx+LibWeb+PixelPaint+ImageViewer: Implement box sampling

- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Avoid possible null optional dereference when creating border radius clipper, and avoid creating clipper if the clip rect is empty (which prevents some debug spam). Also remove an unnecessary lambda.
> LibWeb: Tidy up apply_clip_overflow_rect() a little

- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
Case-preserving behavior matches observed behavior of other browsers and the specification.
> LibWeb: Preserve case for key events

- Userland/Libraries/LibVideo/VP9/BooleanDecoder.cpp
- Userland/Libraries/LibVideo/VP9/BooleanDecoder.h
> A few tiny tweaks to VP9/BooleanDecoder

- Userland/Libraries/LibWeb/Fetch/Body.cpp
Resolves #18913, fixes the crash on `seenthis.se`
I hope that's what the suggestion in the issue meant
> LibWeb: Handle invalid UTF-8 in Fetch's Body#text()

- Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
Implied point = point created by two subsequent "off curve" points.
Fixes following issues in function that builds glyph path from points:
- If first point is "off curve" it was wrongly treated as "on curve" which caused wrong first point position in the path.
- If both first and last points in the path are "off curve" implied point was not created between them which caused wrong path shape in the end of the path.
Before:
After:
> LibGfx: Fix glyph render to create implied points in start/end of path

- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.js
The USV string proposal has landed, and an array buffer size check.
> LibJS: Couple of recent normative ECMA-262 changes

- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/ImageFormats/BooleanDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/BooleanDecoder.h
- Userland/Libraries/LibVideo/CMakeLists.txt
- Userland/Libraries/LibVideo/VP9/BooleanDecoder.h
- Userland/Libraries/LibVideo/VP9/Context.h
- Userland/Libraries/LibVideo/VP9/Parser.cpp
As discussed on Discord; somewhat temporary.
@Zaggy1024
> Prepare for using VP9 EntropyDecoder in WebPLoaderLossy.cpp

- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Some obvious cases where we can avoid a lot of unnecessary work.
> LibWeb: Invalidate style/layout a little less in common situations

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultController.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultController.h
- Userland/Libraries/LibWeb/Streams/UnderlyingSource.cpp
- Userland/Libraries/LibWeb/Streams/UnderlyingSource.h
We finally have enough of a stream implementation to begin running the [WPT streams tests](https://github.com/web-platform-tests/wpt/tree/master/streams), which helped me diagnose all of the behavior issues in this PR (I'm sure there are more than these!).
> LibWeb: Fix incorrect field types in Stream + misc behavior fixes

- Userland/Libraries/LibWeb/SVG/AttributeParser.cpp
Previously, this would blindly use `parse_number()` without checking if there was a number to parse. 
This meant we would crash on transforms like: `rotate(BAD 32 0)`
Now the attribute just gracefully fails to parse.
> LibWeb: Make SVG transform parser less crashy

- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
This PR corrects the signs of the start/end points that are passed to the elliptical_arc_to(), it also removes the bogus path.close() after creating the arc. Now .arc() seems to work correctly.
**Before (very goofy):**
**After:**
> LibWeb: Fix goofy CRC2D.arc() behaviour

- Ladybird/LocationEdit.cpp
This should add more polish to the browser :+1:
> Ladybird: Add placeholder to LocationEdit

- AK/Error.h
- Userland/Applications/DisplaySettings/ThemesSettingsWidget.cpp
- Userland/Applications/SpaceAnalyzer/Tree.cpp
- Userland/Applications/Terminal/main.cpp
- Userland/Libraries/LibCore/DirIterator.cpp
- Userland/Libraries/LibCore/Directory.cpp
- Userland/Libraries/LibCore/Directory.h
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibCore/System.h
A lot of this is yaks to get SpaceAnalyzer ported.
> Applications: Migrate to Core::Directory::for_each_entry()

- Userland/Libraries/LibJS/Runtime/Error.cpp
Previously, source_range() could crash attempting to read from a null unrealized->source_code pointer. It looks like the previous behaviour here was to return a dummy source range, so this commit restores that.
With this loading https://github.com/SerenityOS/serenity works again.
> LibJS: Fix crash when trying to get source range

- Userland/Utilities/watch.cpp
Previously `usleep()` was being used, which was being passed a 32-bit signed integer as a parameter. This caused an overflow for intervals larger than 2147 seconds.
Video showing the issue:
https://github.com/SerenityOS/serenity/assets/2817754/0361d919-40a0-4634-95f0-972569653a13
> watch: Avoid overflow for large interval values

- Tests/LibGfx/TestImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossyTables.h
This could be a bit prettier, but it works :^)
> WebP/Lossy: Implement prediction and inverse DCT

- Userland/Shell/Shell.cpp
This also avoids a few copies, so perhaps it runs marginally faster now.
Advances #17129.
> Shell: Migrate from DeprecatedFile to File and FileSystem

- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Before execute_async_script supported returning value from script to
/execute/async caller only if script returns promise that resolves into
returned value. This change fixes execute_async_script to also support
returning value to caller using callback that is always passed to
script as a last argument.
Now both scripts will return value:
`{"script":"arguments[arguments.length - 1](\"hello callback\");","args":[]}` - /execute/async body that uses callback to return value
`{"script":"return new Promise((resolve) => resolve(\"hello promise\"))","args":[]}` - /execute/async body that returns promise to return value.
> LibWeb/WebDriver:  Support resolve with callback in execute_async_script

- Userland/Libraries/LibWeb/CSS/Angle.cpp
- Userland/Libraries/LibWeb/CSS/Frequency.cpp
- Userland/Libraries/LibWeb/CSS/Resolution.cpp
- Userland/Libraries/LibWeb/CSS/Time.cpp
https://www.w3.org/TR/cssom-1/#serialize-a-css-component-value
> LibWeb: Serialize some CSS units according to spec

- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Wpt tests depend on this to work
> LibWeb: Allow calculated values in transform

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
https://drafts.csswg.org/css-values-4/#comp-func
> LibWeb: Implement CSS comparison functions

- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
This patch removes a long time remnant of the pre-`AK::Error` era.
> LibGfx/JPEG: Use `Error` to propagate errors

- Userland/Libraries/LibLine/Editor.cpp
A missing history file is just an empty history, so ignore that error and replace it with an empty array.
This fixes Shell not saving its history on a clean disk image, which regressed in f93ee3142d2ca4329d989dd917fc27c912b60806.
> LibLine: Ignore ENOENT errors when loading old history

- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
This was needed for some wpt test pages
> LibWeb: Resolve the `transition-delay` property

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
... instead of crashing :^)
Makes https://www.jetbrains.com/ work again.
> LibWeb: Detect and reject math functions with no resolved type

- .gitignore
- Documentation/HelixConfiguration.md
> Documentation: Add documentation for configuring the Helix editor

- Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
- Userland/Libraries/LibGfx/Font/PathRasterizer.cpp
- Userland/Libraries/LibGfx/Path.cpp
- Userland/Libraries/LibGfx/Path.h
(No functional changes [intended])
> LibGfx: Simplify segmentizing paths

- Ladybird/ladybird.nix
- Toolchain/serenity.nix
See https://github.com/SerenityOS/serenity/pull/19224#pullrequestreview-1460162578
> Toolchain+Ladybird: Declare dependencies in correct nix file 

- Userland/Libraries/LibC/string.cpp
- Userland/Libraries/LibC/string.h
https://linux.die.net/man/3/memmem
> LibC: Fix memmem signature compliance

- Userland/Utilities/js.cpp
Added option to disable debug output (unhandled Promise rejections, etc) to the JS repl.
> js: Add --disable-debug-output option

- Userland/Utilities/js.cpp
Add --test262-global option to expose the test262 global object instead of normal script object.
> js: Add --test262-global option

- Userland/Libraries/LibC/sys/time.h
- Userland/Libraries/LibC/time.cpp
> LibC: Add `lutimes(2)` and `futimes(2)` implementations

- Userland/Utilities/dd.cpp
> dd: Small statistics improvements (show elapsed time and write speed, and print it also on interrupts)

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Layout/expected/flex/flex-shorthand-flex-basis-zero-percent.txt
- Tests/LibWeb/Layout/input/flex/flex-shorthand-flex-basis-zero-percent.html
- Tests/LibWeb/Text/expected/url-search-params-iterator-iterator.txt
- Tests/LibWeb/Text/input/url-search-params-iterator-iterator.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Element.idl
See individual commits for descriptions.
Before:
After:
> LibWeb: Fix things until we can read web platform docs on MDN :^)

- Tests/LibWeb/Layout/expected/flex/automatic-minimum-size-with-explicit-flex-basis-and-flex-container-with-max-content-main-size.txt
- Tests/LibWeb/Layout/expected/resolve-cyclic-percentage-against-zero-when-available-size-is-min-content.txt
- Tests/LibWeb/Layout/input/flex/automatic-minimum-size-with-explicit-flex-basis-and-flex-container-with-max-content-main-size.html
- Tests/LibWeb/Layout/input/resolve-cyclic-percentage-against-zero-when-available-size-is-min-content.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
See individual commits for description.
Before:
After:
> LibWeb: Make the Lufthansa website look better :^)

- .github/workflows/libjs-test262.yml
- .github/workflows/wasm.yml
- Ladybird/CMakeLists.txt
- Meta/Azure/Lagom.yml
- Meta/Lagom/CMakeLists.txt
- Meta/check-markdown.sh
- Meta/lint-ci.sh
- Meta/lint-gml-format.sh
- Meta/serenity.sh
- Tests/LibWeb/Layout/layout_test.sh
- Tests/LibWeb/Text/text_test.sh
- Userland/Utilities/markdown-check.cpp
> Meta+Lagom: Enable CMAKE_BUILD_WITH_INSTALL_RPATH

- Tests/LibWeb/Layout/expected/table/bottom-caption.txt
- Tests/LibWeb/Layout/expected/table/long-caption-increases-width.txt
- Tests/LibWeb/Layout/input/table/bottom-caption.html
- Tests/LibWeb/Layout/input/table/long-caption-increases-width.html
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Adds layout support and the CSS caption-side property.
> LibWeb: Add support for table caption

- Userland/Applications/CalendarSettings/CalendarSettingsWidget.cpp
- Userland/Applications/CalendarSettings/CalendarSettingsWidget.h
- Userland/Applications/ClockSettings/ClockSettingsWidget.cpp
- Userland/Applications/ClockSettings/ClockSettingsWidget.h
- Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.cpp
- Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.h
- Userland/Applications/MailSettings/MailSettingsWidget.cpp
- Userland/Applications/MailSettings/MailSettingsWidget.h
- Userland/Applications/MouseSettings/HighlightWidget.cpp
- Userland/Applications/MouseSettings/HighlightWidget.h
- Userland/Applications/MouseSettings/MouseWidget.cpp
- Userland/Applications/MouseSettings/MouseWidget.h
- Userland/Applications/MouseSettings/ThemeWidget.cpp
- Userland/Applications/MouseSettings/ThemeWidget.h
- Userland/Applications/NetworkSettings/NetworkSettingsWidget.cpp
- Userland/Applications/NetworkSettings/NetworkSettingsWidget.h
- Userland/Applications/TerminalSettings/TerminalSettingsWidget.cpp
- Userland/Applications/TerminalSettings/TerminalSettingsWidget.h
Contributes to https://github.com/SerenityOS/serenity/issues/17130
> Userland: Convert all settings widgets to a failable factory

- Userland/Libraries/LibC/string.cpp
- Userland/Libraries/LibC/string.h
For better code clarity, also reformatted how strcpy increments pointers.
This is needed for the SuperTuxKart port.
thanks to @linusg and @n0toose for ~~helping~~ emotional support :3
> LibC: Implement stpcpy

- Userland/Applications/3DFileViewer/main.cpp
- Userland/Applications/CertificateSettings/CertificateStoreWidget.cpp
- Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
- Userland/Applications/FontEditor/MainWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/ImageViewer/main.cpp
- Userland/Applications/PDFViewer/PDFViewerWidget.cpp
- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Applications/Presenter/PresenterWidget.cpp
- Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
- Userland/Applications/ThemeEditor/MainWidget.cpp
- Userland/Applications/VideoPlayer/VideoPlayerWidget.cpp
- Userland/DevTools/GMLPlayground/MainWidget.cpp
- Userland/Games/Chess/main.cpp
- Userland/Libraries/LibFileSystemAccessClient/Client.cpp
- Userland/Libraries/LibFileSystemAccessClient/Client.h
<table>
<tr>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/6549a407-301d-4c33-ac8f-c9be2134f53e>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/a6f43c48-f058-47e3-8e6e-22bea5916109>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/ac30e781-60f2-4273-bab8-02f30f09994f>
<tr>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/83b049bf-513b-409f-abd4-de140dd6d1d6>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/e4589fad-a91d-4aba-94fa-98cd40cd8f5e>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/24323da7-7237-4c84-91dc-e29d5a3345f1>
<tr>
<td><img src=https://github.com/SerenityOS/serenity/assets/16520278/23cc986d-5be5-4ac5-be1c-b318e57b4d53>
<td><img …
> Userland+LibFSAC: Filter out unsupported file types in open dialogs in more apps

- Tests/LibWeb/Layout/expected/grid/minmax-auto-track-definition.txt
- Tests/LibWeb/Layout/input/grid/minmax-auto-track-definition.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Fix crash on https://beta.w3.org/
> LibWeb: Add GridTrack::create_from_definition() in GFC

- Userland/Libraries/LibJS/Runtime/GlobalEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
See individual commits for descriptions.
> LibJS: Two minor performance tweaks

- Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
> LibGfx/PNG: Cleanup

- .github/workflows/cmake.yml
- .github/workflows/pvs-studio-static-analysis.yml
- .github/workflows/sonar-cloud-static-analysis.yml
- Documentation/CLionConfiguration.md
- Meta/Azure/Caches.yml
- Meta/serenity.sh
- Toolchain/BuildGNU.sh
Bring it in line with `Toolchain/BuildClang.sh`.
> Meta: Rename `BuildIt.sh` to `BuildGNU.sh`

- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
GridItem is simple enough to be a struct. No behavior change.
> LibWeb: Transform GridItem from a class to a struct in GFC

- Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
It seems for very narrow tall paths it is possible for the dxdy value to round to a value (that after many repeated additions) overshoots the desired end x. This caused a (rather rare) crash on this 3D canvas demo: https://www.kevs3d.co.uk/dev/html5logo/. For now, lets just avoid a crash here. This does not make any noticeable visual differences on the demos I tired.
> LibGfx: Avoid fill_path() crashes due to rounding errors

- Ladybird/WebContentView.cpp
This change makes pages that use CSS rules like '@media (max-device-width: 600px)' render more correctly.
Without this change device-width and height queries would return 0.
I tried adding a test for this but since the tests are run on headless-browser which has no screens this can't be tested right now.
> Ladybird: Update screen rects on client creation

- Meta/Azure/Setup.yml
Let's see if `brew install --overwrite` helps..
> CI: Try to fix macOS CI

- Tests/LibSQL/TestSqlHeap.cpp
- Userland/Libraries/LibSQL/Database.cpp
- Userland/Libraries/LibSQL/Heap.cpp
- Userland/Services/SQLServer/DatabaseConnection.cpp
> LibSQL+SQLServer: Fix crash related to cookies when reopening Ladybird

- Userland/Libraries/LibRegex/RegexParser.cpp
This is undefined according to the spec, but glibc ignores the backslash and some applications seem to prefer this behaviour (e.g. sed).
> LibRegex: Treat \<ORD_CHAR> as unescaped in POSIX BRE/ERE

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
https://drafts.csswg.org/css-values-4/#sign-funcs
> LibWeb: Implement CSS sign related functions

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
https://drafts.csswg.org/css-values-4/#calc-constants
> LibWeb: Parse css math constants

- Userland/Libraries/LibWeb/CSS/Angle.cpp
- Userland/Libraries/LibWeb/CSS/Angle.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
https://drafts.csswg.org/css-values-4/#trig-funcs
> LibWeb: Implement CSS trigonometric functions

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
See individual commits.
test262 says:
+29 ✅    -7 ❌    -22 💥️
> LibJS/Bytecode: Two bytecode fixes

- Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt
- Tests/LibWeb/Layout/input/table/border-collapse-is-inherited.html
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
Move it to the inherited section of ComputedValues.
> LibWeb: Make border-collapse actually inherited

- Ladybird/Tab.cpp
- Ladybird/Tab.h
- Userland/Applications/Browser/IconBag.cpp
- Userland/Applications/Browser/IconBag.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Libraries/LibWeb/HTML/AudioTrack.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentServer.ipc
> Ladybird+LibWeb: Add context menu support for audio elements

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
See individual commits.
Not too exciting on test262:
+2 ✅    -2 ❌   
But the diffstat is nice:
8 files changed, 106 insertions(+), 156 deletions(-)
> LibJS/Bytecode: Do BlockDeclarationInstantiation in C++ and also a bugfix for GetById

- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
> LibWeb: Handle calculated `vertical-align`

- Userland/Libraries/LibGfx/Path.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Result:
[screen-capture - 2023-06-17T002339.778.webm](https://github.com/SerenityOS/serenity/assets/11597044/12181334-0c02-433b-8211-245d4cb4b5b5)
Before:
> LibWeb: Apply canvas transform while building paths

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Op.cpp
This time over fiiiiiiive hundred tests fixed. :^)
> LibJS/Bytecode: Another couple fixes for test262

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
https://drafts.csswg.org/css-values-4/#round-func
Waiting for https://github.com/SerenityOS/serenity/pull/19166 to be merged first
> LibWeb: Implement CSS stepped value functions

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Should get us 46 more passes on test262 :^)
> LibJS/Bytecode: Two more boog fixes

- Meta/Lagom/CMakeLists.txt
- Userland/Libraries/LibCpp/AST.cpp
- Userland/Libraries/LibCpp/AST.h
- Userland/Libraries/LibCpp/Parser.cpp
- Userland/Libraries/LibCpp/Parser.h
- Userland/Libraries/LibCpp/Preprocessor.cpp
Tiny improvement for <https://github.com/SerenityOS/jakt/pull/1449> :P
> LibCpp: Build for Lagom / type aliases

- Userland/Utilities/chmod.cpp
Previously, the program would exit immediately if there was an error changing file permissions. We now print an error to stderr and continue when an error occurs.
Example:
> chmod: Don't bail immediately on error

- Userland/Utilities/chown.cpp
Previously, the program would exit immediately if there was an error changing file ownership. We now print an error to stderr and continue when an error occurs.
This is essentially the same change as was made in #19449.
Example:
> chown: Don't bail immediately on error

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Start fleshing out "apply the history step" for traversables

- Tests/LibGfx/TestImageDecoder.cpp
No real behavior change, mostly a code size reduction. (Some tests check some more things now.)
> Tests: Factor out some repetitive code in TestImageDecoder.cpp

- Userland/Libraries/LibAudio/WavLoader.cpp
- Max size of a wav is u32::MAX, so file/data size will never be larger
> LibAudio: Remove redundant checks in WavLoader

- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Implement "traverse the history by delta" for traversables

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Implement reload for navigables

- Meta/serenity_gdb.py
I guess that the image is pretty explicit:
> Meta: Add a pretty-printer for `Optional`

- .github/workflows/wasm.yml
- AK/StringView.h
- Documentation/BuildInstructions.md
- Documentation/BuildInstructionsLadybird.md
- Meta/Lagom/BuildFuzzers.sh
- Meta/serenity.sh
We require clang-15 for consteval.
> Meta: Document that clang-15 is required, and update the compiler check

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Implement most of "destroy a top-level traversable"

- Ladybird/AudioCodecPluginLadybird.cpp
When the default audio device changes on the host, it's convenient to automatically switch to that device rather than 
needing to reload the page to update.
Note I was only able to get this to work on macOS, on Linux I never receive the `audioOutputsChanged` signal. But it looks like that'll be fixed in an upcoming released, this commit just went into Qt yesterday: https://github.com/qt/qtmultimedia/commit/7b75983575518109a4630058149d74819bf0cf64
> Ladybird: Detect changes to the default audio device

- Base/usr/share/man/man1/checksum.md
This makes it render correctly in the graphical `Help` application and in other HTML-based contexts. Rendering it correctly in the Terminal will require a LibMarkdown bugfix, since breaks in paragraphs seem to simply get discarded there.
> Base: Insert newlines in the `checksum(1)` synopsis

- Userland/Utilities/touch.cpp
Previously, `touch` would exit immediately if there was an error changing file permissions. We now print an error to stderr and continue when an error occurs.
Example:
> touch: Don't bail immediately on error

- Userland/Utilities/ping.cpp
This change adds the TTL value of the inbound packet to the output of the userland ping program, bringing it more in line with other common ping utilities. It also adds the (optional) -t option to configure the TTL of the outgoing packet if desired.
> Ping: Add TTL config option and value to output

- Ladybird/AudioCodecPluginLadybird.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
- Userland/Libraries/LibWeb/Painting/MediaPaintable.h
- Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.cpp
- Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h
- Userland/Services/WebContent/AudioCodecPluginSerenity.cpp
Audio:
https://github.com/SerenityOS/serenity/assets/5600524/a57ad7f2-988e-418a-a5b1-e1a40bfe25d6
Video:
https://github.com/SerenityOS/serenity/assets/5600524/a09fd668-84d7-4c06-8ab2-407b63de1239
> LibWeb: Implement scrubbing of the media element timeline and volume 

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
Equivalent of `choose_a_browsing_context` for navigables.
> LibWeb: Start fleshing out Navigable::choose_a_navigable()

- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
> LibWeb: Respect "no-store" directive in cache-control header

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
This gives anonymous functions the name from the LHS they are being assigned to.
171 new passes on test262. :^)
> LibJS/Bytecode: Add codegen for "named evaluation if anonymous function"

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
> LibWeb: Add API for finding NavigableContainer by content navigable

- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
> LibWeb: Implement "destroy the child navigable" on navigable containers

- Base/res/fortunes.json
> Base: Add a new quote to the fortunes database

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
> LibJS/Bytecode: Support destructuring in try..catch

- Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp
This solution is a middle ground between re-computing `cos` every time and a much more mathematically complicated approach (as we have in the decoder).
While being still far from optimal is already give us a 10x improvement, not that bad :^)
> LibGfx/JPEG: Use a look-up table for cosine values

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
> LibJS/Bytecode: Actually exit `switch` statement's lexical scope

- Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp
- Userland/Libraries/LibWeb/WebSockets/WebSocket.h
This is the start of moving WebSocket closer to spec.
> LibWeb: Move WebSocket constructor steps closer to spec

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Also adds a big FIXME, to outline what is still wrong
---
Just one small fix and a bit onto the roadmap
> LibJS: Replace invalid escapes in TemplateLiterals with undefined in BC

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
If destructuring didn't exhaust the iterator, we have to manually close the iterator.
155 new passes on test262. :^)
> LibJS/Bytecode: Ensure iterator is closed after array destructuring

- Tests/LibGfx/TestICCProfile.cpp
- Userland/Libraries/LibGfx/ICC/TagTypes.cpp
Having those trailing nuls is invalid per spec, but it happens in practice (in already checked-in test files, no less).
> ICC: Strip trailing nul characters from MultiLocalizedUnicodeTagData

- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
If an exception is thrown by FunctionDeclarationInstantiation for an async or async-generator function, we still need to return a promise. We can't just throw the exception.
81 new passes on test262. :^)
> LibJS/Bytecode: Propagate FunctionDeclarationInstantiation exceptions

- Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
24 new passes on test262. :^)
cc @Hendiadyoin1
> LibJS: Have AsyncFunctionDriverWrapper unwrap promises before returning

- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
```
Summary:
Diff Tests:
+391 ✅   +15 ❌   +2 💥️    -408 📝
```
> LibJS/Bytecode: Implement for await of

- Meta/serenity_gdb.py
> Meta: Add a gdb pretty-printer for `FixedArray`

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
```
Summary:
Diff Tests:
+1 ✅    -1 ❌   
```
> LibJS/Bytecode: Implement Annex B Initializers in ForIn Statement Heads

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
We do this by moving the `LoadImmediate undefined` instruction to a separate basic block which jumps to the case's block unconditionally. We enter a case initially using this wrapper, but when falling through, we directly jump to the next case's block.
```
Summary:
Diff Tests:
+11 ✅    -11 ❌   
```
> LibJS/Bytecode: Keep completion value of switch case if falling through

- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
No functional changes intended, mostly just adding spec comments, along
with some asserts.
> LibJS: Implement SetValueInBuffer closer to spec

- Ladybird/ladybird.nix
See a34e3692523aa7d2cc3f94d8dc7345dfedaad03d
> Ladybird: Add qt6.qtmultimedia to dependencies in nix-shell script

- Userland/Libraries/LibJS/Print.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
[Proposal Link](https://tc39.es/proposal-arraybuffer-transfer/)
> LibJS: Implement the rest of the ArrayBuffer transfer proposal

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.round.js
```
Summary:
Diff Tests:
+19 ✅    -19 ❌   
```
> LibJS: Fix sanitizer issues discovered via test262

- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Before this change, we only blurred the shadows which would've been generated without blur. This meant that we didn't generate a shadow when the offset was zero, even with blur. However, other browsers generate a shadow when blur is set.
Instead, always generate a rectangular contour of sufficient thickness, blur it if needed and blit it into the right position at the very end. Thanks to the blur radius, we'll have a shadow even when the offset is zero.
> LibWeb: Fix inset shadow with zero offset and blur

- Userland/Shell/Parser.cpp
- Userland/Shell/PosixParser.cpp
This turns all errors into either "OOM" or a proper shell error (if propagation is impossible or meaningless).
Fixes `echo -en '\xfe\x4a' | $SHELL` crashing.
> Shell: Handle (most) errors in the parsers

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/Intrinsics.cpp
- Userland/Libraries/LibJS/Runtime/SharedArrayBufferConstructor.cpp
- Userland/Libraries/LibJS/Runtime/SharedArrayBufferConstructor.h
- Userland/Libraries/LibJS/Runtime/SharedArrayBufferPrototype.cpp
- Userland/Libraries/LibJS/Runtime/SharedArrayBufferPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/SharedArrayBuffer/SharedArrayBuffer.js
- Userland/Libraries/LibJS/Tests/builtins/SharedArrayBuffer/SharedArrayBuffer.prototype.byteLength.js
- Userland/Libraries/LibJS/Tests/builtins/SharedArrayBuffer/SharedArrayBuffer.prototype.slice.js
None of the actual sharing is implemented yet, but this is enough for most basic functionality.
Diff Tests:
+260 ✅    -262 ❌   +2 💀
> LibJS: Add initial implementation for SharedArrayBuffer

- Base/home/anon/.config/SearchEngines.json
Wiby.me is a search engine that focuses on indexing and discovering retro-style, static websites. It aims to capture the nostalgia and simplicity of early internet websites. Wiby.me provides a unique browsing experience by allowing users to explore a curated collection of websites reminiscent of the early days of the web.
Unlike traditional search engines that prioritize dynamic and frequently updated content, Wiby.me emphasizes static websites that are often handcrafted and have a distinct aesthetic. It aims to showcase the creativity and diversity of the web landscape before the dominance of dynamic content and complex web technologies.
Users can search for websites on Wiby.me using keywords or browse through different categories. The search results display a brief description of each …
> Base: Add "Wiby.me" To "SearchEngines.json"

- Base/res/html/misc/new-tab.html
When opening a new tab, users now have the option to utilize Wiby, a search engine, to explore the internet.
> Base: Add Wiby Search To New Tab Page

- Userland/Applications/3DFileViewer/main.cpp
Also fix a bug that ENOENT was not properly handled, so running "3DFileViewer foo" crashed the application
> 3DFileViewer: Use ArgsParser

- Userland/Libraries/LibDiff/Format.cpp
- Userland/Libraries/LibDiff/Format.h
- Userland/Libraries/LibDiff/Hunks.h
- Userland/Utilities/diff.cpp
> LibDiff+diff: Add support for writing diffs in context format

- Ladybird/WebContentView.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
- Userland/Services/WebContent/AudioCodecPluginSerenity.cpp
Some quality of life changes to control media elements with a keyboard (seeking, volume, playback state, etc.).
https://github.com/SerenityOS/serenity/assets/5600524/81b59a4f-9268-497e-9ae5-5468ea32223f
> LibWeb: Keyboard controls for media elements

- Meta/CMake/locale_data.cmake
https://cldr.unicode.org/index/downloads/cldr-43#h.qobmda543waj
> LibLocale: Update to CLDR version 43.1.0

- Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
- Ports/SuperTuxKart/patches/0001-Add-build-system-support-for-Serenity.patch
- Ports/SuperTuxKart/patches/0002-Fixup-Vulkan-SDL-platform-quirks.patch
- Ports/SuperTuxKart/patches/0003-Remove-IPv6-support.patch
cc @sdomi (can't select you as a reviewer)
> Ports/SuperTuxKart: A couple of small patch tweaks

- Ports/SuperTuxKart/package.sh
> Ports/SuperTuxKart: Set app icon

- .github/workflows/libjs-test262.yml
Just for convenience to more easily see what is not working in bytecode.
> CI: Show comparison of test262 AST results to bytecode results

- Userland/Libraries/LibJS/Bytecode/Op.cpp
The previous ad-hoc implementation ignored the non-enumerable flag.
```
Summary:
Diff Tests:
+20 ✅    -19 ❌    -1 💀   
```
> LibJS/Bytecode: Use CopyDataProperties AO for destructuring

- Userland/Libraries/LibDiff/Format.cpp
- Userland/Libraries/LibDiff/Format.h
- Userland/Libraries/LibDiff/Forward.h
- Userland/Utilities/diff.cpp
> diff: Only output a unified/context header if there is a diff

- Userland/Libraries/LibVideo/VP9/Decoder.cpp
This allows us to play back videos on ~all~ some Steam store pages ~(hopefully)~ (in cases where they used VP9), since those use lossless frames to encode a fully black frame, it seems like.
> LibVideo/VP9: Implement lossless residual decoding

- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableRowElement.cpp
> LibWeb: Support background attribute on table elements

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
> LibWasm: Make the main module's functions addressable by globals

- Base/res/html/misc/key-logger.html
- Kernel/API/KeyCode.h
- Kernel/Devices/HID/KeyboardDevice.cpp
- Ladybird/WebContentView.cpp
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.h
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.idl
https://github.com/SerenityOS/serenity/assets/5600524/7a58e06f-d10d-462f-b5a6-f3a842ad82b6
> LibWeb+Ladybird+Kernel: Implement `KeyboardEvent.{key,code,location}` according to the spec

- AK/Math.h
This uses a 4th degree Taylor approximation with an error of less than 0.0016, this is still a bit to much to migrate the x86 implementation to, so there is still room to improve.
---
Also some free constants, and other logarithms as collateral "damage"
> AK: Add a generic version of log2

- Tests/LibWeb/Text/expected/window-proxy-property-inline-cache.txt
- Tests/LibWeb/Text/input/window-proxy-property-inline-cache.html
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/Shape.cpp
- Userland/Libraries/LibJS/Runtime/Shape.h
- Userland/Libraries/LibJS/Tests/inline-cache-edge-cases.js
- Userland/Libraries/LibWeb/HTML/WindowProxy.cpp
See commits for details & tests.
> LibJS+LibWeb: Fix two boogs related to inline caching

- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
Implements https://html.spec.whatwg.org/multipage/document-sequences.html#create-a-new-child-navigable
> LibWeb: Implement "create a new child navigable" and supporting code

- Userland/Libraries/LibPDF/Document.cpp
- Userland/Libraries/LibPDF/Document.h
- Userland/Libraries/LibPDF/DocumentParser.cpp
- Userland/Libraries/LibPDF/DocumentParser.h
- Userland/Utilities/pdf.cpp
Screenshot (with other pending and local PRs):
```
% Build/lagom/bin/pdf ~/Downloads/encryption_nocopy.pdf
PDF Version: 1.7
Number of pages: 1
Title: This is a test document
Author: van der Knijff
Subject: 
Keywords: 
Creator: Acrobat PDFMaker 9.1 voor Word
Producer: Acrobat Distiller 9.5.2 (Windows)
Creation date: D:20121123170139+01'00'
Modification date: D:20121123170633+01'00'
```
> LibPDF+pdf: Print PDF version; tweak output

- Base/usr/share/man/man1/nohup.md
- Userland/Utilities/nohup.cpp
This snapshot implements the nohup command-line utility.
Running it in a directory with root permissions while being anon:
> Utilites: Implement nohup

- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Tweak grammar a bit while here too.
> LibWeb: Fix a few comment typos

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
- Userland/Libraries/LibJS/Runtime/PromiseConstructor.h
- Userland/Libraries/LibJS/Tests/builtins/Promise/Promise.withResolvers.js
https://github.com/tc39/proposal-promise-with-resolvers
> LibJS: Implement the Promise.withResolvers proposal

- Userland/Applications/Calendar/main.cpp
- Userland/Libraries/LibGUI/Calendar.cpp
- Userland/Libraries/LibGUI/Calendar.h
- Userland/Services/Taskbar/ClockWidget.cpp
- Userland/Services/Taskbar/ClockWidget.h
This PR makes the calendar widget scrollable and includes some related refactoring.
> LibGUI: Make the calendar widget scrollable

- Ports/.port_include.sh
Found while doing some larger changes, decided to PR it in advance.
> Ports: Remove a few semi-dead code branches

- Userland/Libraries/LibJS/Bytecode/BasicBlock.cpp
Using mmap was quite punishing on inputs with lots of basic blocks, such as test262 tests with eval() in a loop that goes 64k times..
~27% speed-up on language/literals/regexp/S7.8.5_A2.1_T2.js but presumably everything everywhere will benefit from this. :^)
> LibJS/Bytecode: Use malloc instead of mmap for BasicBlock buffers

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
CreateVariable is not needed for locals because they are not stored in environment and created binding will not be used. Also if all variables in loop initialization sections are local then CreateLexicalEnvironment and LeaveLexicalEnvironment can also be ommitted.
> LibJS/Bytecode: Skip CreateVariable in "for" loops init for locals

- AK/Format.h
The array which contains the actual parameters is always located
immediately after the base `TypeErasedFormatParams` object of
`VariadicFormatParams`. Hence, storing a pointer to it inside a `Span`
is redundant. Changing it to a zero-length array saves 8 bytes.
Secondly, we limit the number of parameters to 256, so `m_size` and
`m_next_index` can be stored in a smaller data type than `size_t`,
saving us another 8 bytes.
This decreases the size of a single-element `VariadicFormatParams` from
48 to 32 bytes, thus reducing the code size overhead of setting up
parameters for `dbgln()`.
Note that [arrays of length zero][1] are a GNU extension, but it's used
elsewhere in the codebase already and is explicitly supported by Clang
and GCC.
[1]: https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html
> AK: Remove redundant information from TypeErasedFormatParams

- Userland/Libraries/LibRegex/RegexByteCode.cpp
- Userland/Libraries/LibRegex/RegexByteCode.h
- Userland/Libraries/LibRegex/RegexMatch.h
- Userland/Libraries/LibRegex/RegexOptimizer.cpp
- Userland/Libraries/LibRegex/RegexParser.cpp
TLDR: This is a performance improvement of about 10%.
> LibRegex: Perf milking time!

- Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.splice.js
Revision of #20046
Fixes failing test262 tests. Adds a basic test to LibJS to cover the problem.
> LibJS: Align array splice with spec

- Ports/jfduke3d/package.sh
* Ports/jfduke3d: Install into '/usr/local/share/games/jfduke3d'
* Ports/jfduke3d: Add game icon
* Ports/jfduk3d: Add post_install() section
* Adds a post_install() section printing out useful information on how to install the game files.
> Ports/jfduke3d: Add post_install() section + game icon + install into /usr/local/share/games/jfduke3d

- Meta/Lagom/Fuzzers/FuzzBMPLoader.cpp
- Meta/Lagom/Fuzzers/FuzzGIFLoader.cpp
- Meta/Lagom/Fuzzers/FuzzICOLoader.cpp
- Meta/Lagom/Fuzzers/FuzzJPEGLoader.cpp
- Meta/Lagom/Fuzzers/FuzzPBMLoader.cpp
- Meta/Lagom/Fuzzers/FuzzPGMLoader.cpp
- Meta/Lagom/Fuzzers/FuzzPNGLoader.cpp
- Meta/Lagom/Fuzzers/FuzzPPMLoader.cpp
- Meta/Lagom/Fuzzers/FuzzQOILoader.cpp
- Meta/Lagom/Fuzzers/FuzzTGALoader.cpp
- Meta/Lagom/Fuzzers/FuzzWebPLoader.cpp
- Tests/LibGfx/TestICCProfile.cpp
- Tests/LibGfx/TestImageDecoder.cpp
- Userland/Libraries/LibGUI/FileIconProvider.cpp
- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.h
- Userland/Libraries/LibGfx/ImageFormats/DDSLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/DDSLoader.h
- Userland/Libraries/LibGfx/ImageFormats/ICOLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/ICOLoader.h
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
- Userland/Libraries/LibGfx/ImageFormats/PortableImageMapLoader.h
- Userland/Libraries/LibGfx/ImageFormats/QOILoader.h
- Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/TGALoader.h
- Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.h
- Userland/Libraries/LibPDF/Filter.cpp
~~Draft as based on #20074.~~
Final step for - fixes #19893.
> LibGfx: Refactor ImageDecodePlugin's interface

- Userland/Libraries/LibPDF/Encryption.cpp
- `encrypt()` will always fill a multiple of block size, `decrypt()` might produce less data. But other than that, the middle span isn't modified even though it's a reference. So pass the ByteBuffer to assign() (kind of like before 5998072f153bf, but pass-by-move())
- In the encryption code path, assign a single buffer for IV and data instead of awkwardly copying the data around later.
Thanks to CxByte for suggesting most of this!
No intentional behavior change.
> LibPDF: Simplify AESV2 code a bit

- Documentation/SpiceIntergration.md
Only covers Ubuntu for now (since that's what I use), thought it might be good to put this somewhere, since I had to search around for the setup.
cc @AtkinsSJ (since these steps _kinda_ work, I thought it might be of some use to add them :smile:)
> Documentation: Add a rough guide on setting up SPICE on Ubuntu

- Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn
This ports the following commits:
a8587fe54e14e106b03a2c1c47829962078cc9ba
9d7215c636eebfb03c0f9dc6e5be25d66e82d1b5
> Meta: Port recent LibWeb and LibJS changes to gn build

- Tests/LibJS/test-js.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGenerator.h
- Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
- Userland/Libraries/LibJS/Runtime/GeneratorObject.h
- Userland/Libraries/LibJS/Tests/builtins/FinalizationRegistry/FinalizationRegistry.prototype.cleanupSome.js
- Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.prototype.set.js
- Userland/Libraries/LibJS/Tests/builtins/WeakSet/WeakSet.prototype.add.js
> LibJS: Handful of improvements for test-js in bytecode mode

- Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.h
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatFunction.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.js
- Userland/Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.js
This will cause a couple test262 failures until https://github.com/tc39/test262/pull/3879 is merged.
> LibJS: A couple of editorial/normative ECMA-402 changes

- Userland/Libraries/LibPDF/Renderer.cpp
Fixes a crash rendering page 819 of ISO_32000-2-2020_sponsored.pdf which contains an uncompressed 2x2 1bpp grayscale bitmap.
> LibPDF: Don't crash on images without /Filter

- Userland/Utilities/pdf.cpp
Tries to render all pages of a PDF and then produces a report on which unimplemented things were encountered. Example, for pdf_reference_1-7.pdf:
113 times: Rendering of feature not supported: Type0 font not implemented yet
on pages: 170 (3x) 217 (2x) 250 (9x) 252 (2x) 329 (6x)...
21 times: Rendering of feature not supported: unknown color space
on pages: 489 (4x) 490 (5x) 491 (3x) 492 (5x) 493 (4x)
4 times: Rendering of feature not supported: CCITTFaxDecode Filter is unsupported
on pages: 494 (4x)
(Actually, rendering crashes for some page in that file at the moment. This was with a local change to only render the first 800 pages to work around that. So this is also good for finding crashes.)
> pdf: Add a --debugging-stats flag

- Userland/Libraries/LibWeb/Layout/LayoutState.h
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Add the element type and grid position to the algorithm and change the
table borders painting to apply the new criteria to corners as well.
> LibWeb: Complete table border conflict resolution

- Userland/Services/FileOperation/main.cpp
Previously, all files and folders copied with FileManager would be created with the default mode bits set and would have the same uid and gid as the currently logged in user.
Before:
https://github.com/SerenityOS/serenity/assets/2817754/ac3a3f30-914c-4a32-a460-b5cda09c76a0
After:
https://github.com/SerenityOS/serenity/assets/2817754/02259c2b-973c-401f-b50c-a33bef72dc59
> FileOperation: Preserve mode bits and owner when copying files

- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Before this change, we would process each image as it finished downloading. This often led to a situation where we'd decode 1 image, schedule a layout, do the layout, then decode another image, schedule a layout, do the layout, etc. Basically decoding and layouts would get interleaved even though we had multiple images fetched and ready for decoding.
This patch adds a simple BatchingDispatcher thingy that HTMLImageElement uses to batch the handling of successful fetches.
With this, the number of layouts while loading https://shopify.com/ goes from 48 to 6, and the page loads noticeably faster. :^)
> LibWeb: Batch processing of successfully downloaded images

- Ports/cavestory/package.sh
Updated the version of Cave Story that is pulled from my repo. The original port of this was missing game files that would've been extracted on first boot.
> Ports: Update Cave Story version

- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateLocaleData.cpp
Some low hanging fruit to make GenerateLocaleData a bit faster. The biggest speedup is replacing `Vector::contains_slow` lookups into large lists with a `HashMap` cache.
These changes reduce the runtime of GenerateLocaleData from 2.32s to 1.09s on my machine (about a 53% improvement).
> LibLocale: Improve build-time performance of GenerateLocaleData

- Userland/Libraries/LibWeb/CSS/CalculatedOr.cpp
- Userland/Libraries/LibWeb/CSS/CalculatedOr.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
- Userland/Libraries/LibWeb/HTML/SourceSet.cpp
- Userland/Libraries/LibWeb/HTML/SourceSet.h
- Make responsive images react to changes in size viewport
- Allow `calc()` values in image `sizes` attribute
> LibWeb: Responsive image improvements

- Userland/Libraries/LibWeb/DOM/Element.cpp
Stacking context tree rebuild can be avoided if opacity value changes within the range below 1.
> LibWeb: Optimize stacking context rebuilds on opacity change

- Kernel/Net/IPv4Socket.cpp
- Kernel/Net/IPv4Socket.h
- Kernel/Net/NetworkTask.cpp
- Kernel/Net/TCPSocket.cpp
- Kernel/Net/TCPSocket.h
- Kernel/Net/UDPSocket.cpp
- Kernel/Net/UDPSocket.h
- Userland/Libraries/LibC/complex.h
- Userland/Libraries/LibC/sys/select.h
- Userland/Utilities/strace.cpp
Well hello friends! :^)
The main fix here is "Kernel/Net: Rework ephemeral port allocation", cc @stelar7 for that. The rest should too be nice little improvements.
> Net misc fixes

- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Some images (like https://www.w3.org/Press/Stock/Berners-Lee/2001-europaeum-eighth.jpg) embed a non-compliant ICC profile. Instead of rejecting the image, we can simply discard the color profile and resume the decoding of the bitmap.
@nico
> LibGfx/JPEG: Don't fail to decode images with non-compliant ICC profile

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
This patch makes us pass the first test of JPEG XL's conformance test suite :tada:!
Before someone asks me why I didn't include a test, I'm unable to generate an image that the decoder is capable of decoding. But it looks like easy things to implement, so that will probably be done soon in a follow-up PR.
---
**LibGfx/JPEGXL: Create `Image` with the correct number of channel**
As a quick and dirty implementation, we used to assume that the final
image was always composed of three channels of the same size. However,
JPEG XL has support for more than three channels and extra channels can
have a smaller size. With this patch, we now create the image with the
correct number of channel and with their respective sizes.
**LibGfx/JPEGXL: Include the alpha channel in the output bitmap**
Now that …
> LibGfx/JPEGXL: Add support for an alpha channel

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/SVG/SVGGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGradientElement.h
- Userland/Libraries/LibWeb/SVG/SVGLinearGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGLinearGradientElement.h
- Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.h
Progression on Inkscape camera.svg:
> LibWeb: Two small SVG fixes

- AK/DisjointChunks.h
- AK/Trie.h
- Tests/LibRegex/Regex.cpp
- Userland/DevTools/Profiler/Profile.cpp
- Userland/Libraries/LibRegex/RegexByteCode.cpp
- Userland/Libraries/LibRegex/RegexByteCode.h
- Userland/Libraries/LibRegex/RegexMatch.h
- Userland/Libraries/LibRegex/RegexMatcher.cpp
- Userland/Libraries/LibRegex/RegexMatcher.h
- Userland/Libraries/LibRegex/RegexOptimizer.cpp
- Userland/Libraries/LibRegex/RegexParser.h
TLDR, this is about a 20% performance increase in our regex test suite, and a whopping 1.19s time save in test262.
> LibRegex: Milk some more performance

- Tests/LibWeb/Layout/expected/css-values/comparison-functions.txt
- Tests/LibWeb/Layout/expected/css-values/exponential-functions.txt
- Tests/LibWeb/Layout/expected/css-values/numeric-constants.txt
- Tests/LibWeb/Layout/expected/css-values/sign-related-functions.txt
- Tests/LibWeb/Layout/expected/css-values/stepped-value-functions.txt
- Tests/LibWeb/Layout/expected/css-values/trigonometric-functions.txt
- Tests/LibWeb/Layout/input/css-values/comparison-functions.html
- Tests/LibWeb/Layout/input/css-values/exponential-functions.html
- Tests/LibWeb/Layout/input/css-values/numeric-constants.html
- Tests/LibWeb/Layout/input/css-values/sign-related-functions.html
- Tests/LibWeb/Layout/input/css-values/stepped-value-functions.html
- Tests/LibWeb/Layout/input/css-values/trigonometric-functions.html
Our sin/cos/tan values dont quite match the spec, but thats a 🦬 for a later time
> LibWeb: Add tests for calc function nodes

- Ladybird/BrowserWindow.cpp
- Ladybird/BrowserWindow.h
- Ladybird/Tab.cpp
- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/BrowserWindow.h
- Userland/Applications/Browser/Tab.cpp
boog:
https://github.com/SerenityOS/serenity/assets/16520278/4e617b6c-b106-4c9d-8860-a07241451287
> Ladybird+Browser: Update zoom text on menu after clicking zoom button

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
Rework the write_if_changed logic to properly truncate the output file. The original logic would not truncate the file, leading to extra junk at the end of files if the IDL files shrunk between builds.
> BindingsGenerator: Only truncate generated files if they have changed

- Userland/Applications/Spreadsheet/HelpWindow.cpp
- Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Fixes #20307 + a small inconsistency fix.
> Spreadsheet: Fix a crash when opening help window twice

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
**LibGfx/JPEGXL: Add support for the self-correcting predictor**
This predictor is much more complicated than the others. Indeed, to be
computed, it needs its own value but for other pixels. As you can guess,
implementing it involved the introduction of a structure to hold that
data.
Fundamentally, this predictor uses the value of the error between the
predicted value and the true value (aka decoded value) of pixels around.
One of this computed error (namely max_error) is used as a property, so
this patch also solves a FIXME in `get_properties`.
To ease the access to value that are close in the channel and moving
their values around, this patch adds a `Neighborhood` struct which holds
this data. It has been used in `prediction()` and it allowed to simplify
the signature and to remove the …
> LibGfx/JPEGXL: Add support for the self-correcting predictor

- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Reactive images that had an image source selected based on viewport size would only update when the images were first fetched, meaning the last valid image source would become stuck in an image element. By implementing the last step for reacting to environment changes, we can run the proper updates even when the image does not need to be fetched.
This solves an issue where the last image in [this page](https://mdn.github.io/learning-area/html/multimedia-and-embedding/mdn-splash-page-finished/index.html) would be stuck displaying its portrait image source instead of switching back to the landscape one after shrinking and then growing the window.
Before:
https://github.com/SerenityOS/serenity/assets/3149592/9646b663-0b06-4db2-982c-d93d49906069
After: …
> LibWeb: Update reactive images according to spec after fetches finish

- Ladybird/WebContentView.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
> Ladybird: Fix scroll step size 

- AK/String.cpp
- AK/String.h
- Userland/Games/2048/BoardView.cpp
- Userland/Games/2048/main.cpp
- Userland/Games/Chess/ChessWidget.cpp
- Userland/Games/Chess/ChessWidget.h
- Userland/Games/Chess/Engine.cpp
- Userland/Games/Chess/Engine.h
- Userland/Games/Chess/main.cpp
Contributes to #17128.
First PR here, I'll be more than happy to correct any mistakes, if any. :)
> 2048+Chess: Replace DeprecatedString with String

- Userland/Libraries/LibGUI/FilePicker.cpp
Previously, typing e.g. `/home/anon` in the filename field of the FilePicker resulted in an error for applications expecting an existing file to open. Intuitively I expected the file picker to navigate to the directory I typed there, similar to what we have with the location text box at the top, so I changed it to do exactly that :^)
Before:
<video src="https://github.com/SerenityOS/serenity/assets/3210731/868a3695-6ed9-4fcd-8968-8f22f3682748" width="320"></video>
After:
<video src="https://github.com/SerenityOS/serenity/assets/3210731/109575bd-79f6-4f04-a4dd-89b71cccec05" width="320"></video>
> LibGUI: Traverse into directory upon filename entry in FilePicker

- Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
A typo in the changes to our userland timekeeping classes caused us to make a syscall every time we want to check whether a timer is ready to fire in `EventLoopManagerUnix::wait_for_events()`. Instead, only use coarse time, and get it immediately before it is used in both cases.
This reduces CPU usage by an (eyeballed) 20-30% while playing back
video with VideoPlayer.
> LibCore: Only use coarse time in the Unix event loop wait_for_events()

- Base/etc/fstab
- Meta/build-root-filesystem.sh
- Ports/.port_include.sh
- Ports/README.md
- Ports/build_installed.sh
- Userland/Libraries/LibMarkdown/Table.h
- Userland/Libraries/LibMarkdown/Text.cpp
- Userland/Libraries/LibMarkdown/Text.h
- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/pkg/AvailablePort.cpp
- Userland/Utilities/pkg/AvailablePort.h
- Userland/Utilities/pkg/CMakeLists.txt
- Userland/Utilities/pkg/InstalledPort.cpp
- Userland/Utilities/pkg/InstalledPort.h
- Userland/Utilities/pkg/MarkdownTableFinder.h
- Userland/Utilities/pkg/main.cpp
> Utilities: Add basic PackageManager skeleton program

- Userland/Applications/Browser/CookieJar.cpp
- Userland/Applications/Browser/Database.h
Since SQLServer is inherently asynchronous, database statements can run in parallel. Our `CookieJar` did not require synchronous actions on the database for its cookies, resulting in cookies not being set immediately. This resulted in a bug that could be exposed by setting `document.cookie` and immediately querying its value, revealing that the cookie was not yet persisted.
Solve this by requiring all database statements to be executed synchronously. Ideally SQLServer has a mechanism to determine interquery dependencies and blocks until dependent queries are fully executed, but until we have that, this works around that limitation.
Ladybird running with `--enable-sql-database` at `https://www.google.com`, before:
After:
> Browser: Synchronize database statements used for cookies

- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/Layout/Box.cpp
- Userland/Libraries/LibWeb/Layout/Box.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/PaintContext.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Some progress on making scrollable boxes work correctly.
> LibWeb: Support "overflow: auto" and painting fixes for scrollables.

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
#20271 is needed to render the image from https://jpegxl.info/art/ and the test case
---
**LibGfx/JPEGXL: Store distributions in a `Variant`**
JPEG XL supports two types of entropy encoding: the first one is
Huffman-based (Brotli) and the second one is based on ANS. To introduce
the latter, we start by storing the `Vector` of distributions in a
`Variant`. This will allow us to choose which entropy decoder we use
during execution.
**LibGfx/JPEGXL: Implement the ANS decoder**
This allows us to read much more images. This decoder is one of the two
possibilities (along Brotli) that can be used for modular images. All
the logic is directly taken from the spec.
One of the image that can now be decoded is "Lucifer's Dominion:
Synthesis" that can be found on `https://jpegxl.info/art/`, it also …
> LibGfx/JPEGXL: Implement the ANS decoder

- Userland/BuggieBox/main.cpp
Now, in the help text the names of all the supported utilities are dynamically generated with a macro so that if new utilities get added in the future they will get included automatically.
These utilities are printed in table-like format for some "aesthetics".
---
Before:
After:
> Userland: Pretty print the help text in BuggieBox

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
We don't do anything particular with images that contain a custom ColourEncoding yet, but at least it allows us to know how to decode the metadata of such images.
---
This makes us progress a little bit further on [lz77_flower](https://github.com/libjxl/conformance/blob/master/testcases/lz77_flower/input.jxl).
> LibGfx/JPEGXL: Allow `ColourEncoding` bundles with custom values

- Base/res/html/misc/canvas-text.html
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/CSS/StyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.idl
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
I have add the font property to the Canvas Context2D Context.
To do this I had to split some font finding logic in `StyleComputer::compute_font` to another function that I called `StyleComputer::compute_font_for_style_values`. This is probably done quite badly and someone with more experience with C++ and `AK` has probably a better architecture in mind, please tell me then we can update it a bit.
I also moved some logic of the font strech StyleValue to `StyleValue::to_font_stretch_width()` like `to_font_weight` functions to reduce the size of the new `StyleComputer::compute_font_for_style_values` function.
Right now on every call to `fill_text()` and `measure_text()`, the function `current_font()` is called that returns the current loaded font. When the font property is set the next font …
> LibWeb: Add Canvas Context2D basic font property support

- CONTRIBUTING.md
Hopefully this makes it more clear what the intended action is. For a lot of people "squashing" means combining multiple commits into one, which is a common practice when merging to a branch.
> Docs: Use the term 'amend' instead of 'squash' in `CONTRIBUTING.md`

- Tests/LibWeb/Layout/expected/grid/order.txt
- Tests/LibWeb/Layout/input/grid/order.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Closes https://github.com/SerenityOS/serenity/issues/20434
> LibWeb: Support "order" property for items in GridFormattingContext

- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Element.idl
Particularly needed by xkcd's Right Click comic. https://xkcd.com/1975/
> LibWeb: Implement Element.hasAttributeNS

- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
https://drafts.csswg.org/css-transforms/#SkewDefined
> LibWeb: Support skew{X,Y} in stacking context transforms

- Userland/Applications/FileManager/main.cpp
This PR adds an action with label "Copy Path" to the context menus of directory_view, tree_view and file_view
which copies the absolute path of the entry in the global clipboard `GUI::Clipboard::the()`.
Note: If the user selects multiple entries, only the 0th index is used.
The selected path can be used to open a browser or the path required in a terminal running in a different directory.
> FileManager: Add "Copy Path" action to the context menus

- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
> LibJS: Handful of minor cleanups after AST interpreter removal

- Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
- Tests/LibWeb/Layout/expected/table/table-cell-not-paintable.txt
- Tests/LibWeb/Layout/input/block-and-inline/button-with-multiple-words-text-node-label.html
- Tests/LibWeb/Layout/input/block-and-inline/button-with-text-node-label.html
- Tests/LibWeb/Layout/input/table/table-cell-not-paintable.html
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
> LibWeb: Fix buttons with TextNode label

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
While being way less frequent than for classical JPEG images, JPEG XL images can use the YCbCr color space. Supporting it makes us properly decode the "Smoking Machine" image of https://jpegxl.info/jxl-art.html.
> LibGfx/JPEGXL: Support images encoded with the YCbCr color space

- Toolchain/BuildClang.sh
- Toolchain/BuildQemu.sh
- Toolchain/CMake/LLVMConfig.cmake
- Toolchain/Patches/llvm/0003-Driver-Add-support-for-SerenityOS.patch
- Toolchain/Patches/llvm/0004-Driver-Default-to-ftls-model-initial-exec-on-Serenit.patch
- Toolchain/Patches/llvm/0005-libc-Add-support-for-SerenityOS.patch
- Toolchain/Patches/llvm/0008-cmake-Support-building-shared-libLLVM-and-libClang-f.patch
> Toolchain: Support RISC-V in QEMU and Clang

- Ports/build_all.sh
The main point is that all shellcheck errors have been corrected, and output and code are now easier to read. Now, you can use the '**failfast**' option to immediately terminate the script when an error is reported for the first time.
> Ports: Improve build_all.sh script

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
**LibGfx/JPEGXL: Support images with the `have_crop` option in FrameHeader**
This commit only allows us to read these values. The decoder will still
output the image as if no cropping was requested.
**LibGfx/JPEGXL: Put frame's image inside the `Frame` struct**
The image was previously managed as an output parameter of the
`read_frame` function. This reorganisation also brings us closer to the
spec. As it is specified that each frame have its own image that will
later on compose a greater bitmap.
**LibGfx/JPEGXL: Add support for cropped images**
Due to the way JPEG XL encodes its lossless images, it is sometimes
interesting to embed a large image and crop the result at the end. This
patch adds the functionality to crop a frame.
Note that JPEG XL supports image composition (almost like …
> LibGfx/JPEGXL: Support cropped images

- Userland/Libraries/LibGUI/Splitter.cpp
- Userland/Libraries/LibGUI/Splitter.h
one year ago i bring great dishonor to code base, @nico san
> LibGUI: Fix typo

- Tests/LibWeb/Layout/expected/block-and-inline/float-max-content-containing-block-flex-display.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-max-content-containing-block.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-max-content-containing-block-flex-display.html
- Tests/LibWeb/Layout/input/block-and-inline/float-max-content-containing-block.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Fixes layout of page toolbar on Wikipedia.
> LibWeb: Fix handling of max-content containing block for floating box

- Userland/Applications/Calendar/CalendarWidget.cpp
| Before: | After: |
| --- | --- |
| <video src="https://github.com/SerenityOS/serenity/assets/36564831/d6d86140-79c3-4ffd-b6f3-b061c1d94c7c"> | <video src="https://github.com/SerenityOS/serenity/assets/36564831/12c92855-73c0-4be5-baa3-3f695b21c836"> |
> Calendar: Make on_month_click capture the view_month_action's RefPtr

- .github/workflows/libjs-test262.yml
We weren't actually using the caches at all for this job after some path changes recently.
> CI: Specify SERENITY_CACHE_DIR for test262 job

- Tests/LibWeb/Ref/manifest.json
- Tests/LibWeb/Ref/opacity-stacking-ref.html
- Tests/LibWeb/Ref/opacity-stacking.html
(Also explicitly set the background color)
> Tests/LibWeb: Add opacity-stacking.html test to manifest.json

- Userland/Applications/Calendar/CalendarWidget.cpp
- Userland/Applications/FileManager/main.cpp
- Userland/Applications/FontEditor/MainWidget.cpp
- Userland/Applications/Help/MainWidget.cpp
- Userland/Applications/ImageViewer/main.cpp
- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/DevTools/GMLPlayground/MainWidget.cpp
- Userland/Games/GameOfLife/main.cpp
- Userland/Libraries/LibGUI/Toolbar.cpp
- Userland/Libraries/LibGUI/Toolbar.h
> LibGUI+Userland: Remove Toolbar::try_add_{action,separator}()

- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
- Userland/Libraries/LibWeb/Layout/LineBuilder.h
Also remove unused method from LineBuilder.
> LibWeb: Remove unused argument of InlineLevelIterator::next

- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- border-spacing
- text-decoration
- text-decoration-color
- text-decoration-thickness
- text-indent
- text-justify
Sloooowly chipping away at these.
> LibWeb: Add some more computed values for CSS properties

- Userland/Utilities/top.cpp
This PR re-enables non-blocking I/O on stdin for `top`. Using blocking I/O was causing updates to stop until a key was pressed.
NB: This change reintroduces the old undesirable behavior that terminating the program with an untrappable signal (e.g: SIGKILL) would cause the terminal to close unexpectedly (#13418).
Fixes: #20592
> top: Re-enable non-blocking I/O on stdin

- Ports/.strip_env.sh
> Ports: Don't set previously unset environment variables

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> LibWeb: Implement navigation to a fragment for navigables

- Tests/LibWeb/Layout/expected/table/missing-cells-with-span.txt
- Tests/LibWeb/Layout/expected/table/missing-cells.txt
- Tests/LibWeb/Layout/input/table/missing-cells-with-span.html
- Tests/LibWeb/Layout/input/table/missing-cells.html
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
- Userland/Libraries/LibWeb/Layout/TableGrid.cpp
- Userland/Libraries/LibWeb/Layout/TableGrid.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.h
> LibWeb: Implement table missing cells fixup

- Kernel/Devices/AsyncDeviceRequest.h
- Kernel/FileSystem/Ext2FS/FileSystem.cpp
- Kernel/Syscalls/SyscallHandler.cpp
- Kernel/Tasks/PowerStateSwitchTask.cpp
- Kernel/Tasks/PowerStateSwitchTask.h
Originally started in #20588, this completely fixes the shutdown procedure, without going for the architectural changes first.
Fixes #20560.
> Kernel: Fix the shutdown procedure

- Tests/LibWeb/Text/expected/HTML/StructuredClone-object-primitives.txt
- Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
- Userland/Libraries/LibJS/Heap/Handle.h
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
Add some more tests while we're at it :^)
> LibWeb: Add spec steps to StructuredSerialize and implement it for BigIntObject and Symbol

- Userland/Libraries/LibWeb/HTML/Location.cpp
- Userland/Libraries/LibWeb/HTML/Location.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
These are some commits that can be reviewed and merged separately from #18219 without breaking our current navigation implementation.
> LibWeb: Preparation work before switching to Navigables

- Userland/Libraries/LibWeb/DOM/Attr.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
- Userland/Libraries/LibWeb/DOM/QualifiedName.h
- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTableRowElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTableSectionElement.h
Two optimizations made while debugging why some of the WebKit performance tests (https://github.com/WebKit/WebKit/tree/main/PerformanceTests) crash.
2.4x and 3.2x speed-up respectively.
> LibWeb: Two trivial but powerful optimizations

- Tests/LibWeb/Layout/expected/table/border-attribute-overridden-by-css.txt
- Tests/LibWeb/Layout/expected/table/border-attribute.txt
- Tests/LibWeb/Layout/input/table/border-attribute-overridden-by-css.html
- Tests/LibWeb/Layout/input/table/border-attribute.html
- Tests/LibWeb/Layout/input/table/rowspan.html
- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.h
> LibWeb: Support border attribute on the table element

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
These are some commits that can be reviewed and merged separately from https://github.com/SerenityOS/serenity/pull/18219 without breaking our current navigation implementation.
> LibWeb: Preparation work before switching to Navigables (2/N)

- Userland/Applications/PixelPaint/HistogramWidget.cpp
- Userland/Applications/PixelPaint/HistogramWidget.h
- Userland/Applications/PixelPaint/ImageMasking.cpp
- Userland/Applications/PixelPaint/ImageMasking.h
- Userland/Applications/PixelPaint/Layer.cpp
- Userland/Applications/PixelPaint/Layer.h
- Userland/Applications/PixelPaint/LevelsDialog.cpp
- Userland/Applications/PixelPaint/LevelsDialog.h
- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Applications/PixelPaint/ScopeWidget.cpp
- Userland/Applications/PixelPaint/ScopeWidget.h
- Userland/Applications/PixelPaint/VectorscopeWidget.cpp
- Userland/Applications/PixelPaint/VectorscopeWidget.h
This pr adds some optimizations regarding editing masks and histogram/vector scope processing. See individual commits for details.
> PixelPaint: Small performance optimizations

- Tests/LibWeb/Layout/expected/table/keyword-value-does-not-constrain-column.txt
- Tests/LibWeb/Layout/input/table/keyword-value-does-not-constrain-column.html
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Adjust implementation to reflect the CSS 2.1 definition of width.
> LibWeb: Fix table column constrainedness

- Userland/Utilities/ps.cpp
Just like on Linux, we can easily print the process creation time. The format of a printed time is either "hour:minute" if the process started today, or "short_month_name:day_of_the_month" (for example, "Aug26").
> Utilities/ps: Add process start time column in full format mode

- Documentation/BuildInstructionsLadybird.md
- Meta/serenity.sh
This lets us switch between the AppKit and Qt chromes more easily.
> Meta: Add and document convenient method to build non-Qt Ladybird chrome

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
> LibWeb: Miscellaneous paint tree bug fixes

- Kernel/Arch/riscv64/boot.S
- Kernel/Arch/riscv64/linker.ld
- Kernel/CMakeLists.txt
> Kernel: add riscv64 linker script and boot.S

- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
Reflect expectations of its only call site.
> LibWeb: Simplify table_containing_cell signature and implementation

- Meta/Lagom/CMakeLists.txt
- Userland/Libraries/LibWebView/CMakeLists.txt
This lets us add new sources to LibWebView in a single location.
> Meta: Replace Lagom's LibWebView setup with LibWebView's CMakeLists.txt

- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.idl
This still can't do anything useful as the read steps have not been implemented yet, but these commits are some steps towards that.
> LibWeb: Some steps towards implementing ReadableStreamBYOBReader interface

- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/AST.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/AST.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/ASTPrinting.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/CMakeLists.txt
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/CompilerPass.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/GenericASTPass.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/GenericASTPass.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Forward.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
No functional changes :(
In case anyone wants to take a look on how this code will be used, there is `future` branch in my fork.
> JSSpecCompiler: Add infrastructure to run compiler passes

- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Token.cpp
> LibJS: Two tiny optimizations for Kraken/imaging-darkroom.js, 2% speed-up each

- Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
> LibWeb: Fix two small things caught by UBSAN

- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Producing incorrect layout for table cells is better than crashing :)
> LibWeb: Print FIXME if vertical-align value is not supported in TFC

- Userland/Applications/Maps/main.cpp
> Maps: Add pledge and unveils

- Userland/Libraries/LibCore/Process.cpp
This implements #20327 for the FreeBSD platform.
It compiles fine and I think it should theoretically work fine,but unfortunately I couldn't find out how to bring it into that state where it waits for a debugger,so I couldn't really try it.
Never worked with debuggers before.
Would be nice if someone could tell me how to try it or try it for me.
I don't expect any issues,however,as it is nearly identical to the MacOS implementation.
> LibCore: Implement waiting for the debugger on FreeBSD

- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.idl
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
- Userland/Libraries/LibWeb/DOM/MutationRecord.cpp
- Userland/Libraries/LibWeb/DOM/MutationRecord.h
- Userland/Libraries/LibWeb/DOM/MutationRecord.idl
- Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
- Userland/Libraries/LibWeb/DOM/NamedNodeMap.h
- Userland/Libraries/LibWeb/DOM/NamedNodeMap.idl
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawPath.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasText.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
> LibWeb: Port 4 more IDL files from DeprecatedString to String

- Userland/Games/Snake/Game.cpp
- Userland/Games/Snake/Game.h
- Userland/Games/Snake/Skins/ImageSkin.cpp
- Userland/Games/Snake/Skins/ImageSkin.h
- Userland/Games/Snake/main.cpp
This is my first PR here. Any suggestions are highly appreciated, feel free to point out any areas that can be improved.
Contributes to #17128
> Snake: Replace DeprecatedString with String

- Userland/Libraries/LibWebSocket/WebSocket.cpp
- Userland/Libraries/LibWebSocket/WebSocket.h
LibWebSocket: Adds capability for receiving fragmented WebSocket messages.
Resolves issues on https://www.podatki.wtf and other Blazor Server websites.
> LibWebSocket: Adds capability for receiving fragmented messages

- Ladybird/WebContent/main.cpp
- Tests/LibAudio/TestPlaybackStream.cpp
- Userland/Libraries/LibAudio/CMakeLists.txt
- Userland/Libraries/LibAudio/PlaybackStream.cpp
- Userland/Libraries/LibAudio/PlaybackStreamAudioUnit.cpp
- Userland/Libraries/LibAudio/PlaybackStreamAudioUnit.h
https://github.com/SerenityOS/serenity/assets/5600524/db230879-771b-4476-adb7-66494e0bbe82
> Ladybird+LibAudio: Implement PlaybackStream for macOS using Audio Unit framework

- Tests/LibWeb/Text/expected/HTML/StructuredClone-object-primitives.txt
- Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
And fix some boogs along the way.
> LibWeb: Implement StructuredSerialize for RegExpObject and ArrayBuffer

- Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp
- Userland/Libraries/LibWeb/Cookie/ParsedCookie.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.h
Porting over this IDL interface from DeprecatedString is going to be a bit chonky, these are some small standalone steps working towards that goal :^)
> LibWeb: Small steps towards porting Document from DeprecatedString

- Userland/Games/2048/main.cpp
This change also ensures that the redo stack is cleared when a move is made, so that it isn't possible to redo a previous move after having made a new one.
> 2048: Disable the undo and redo actions when unavailable

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
These are some commits from #18219 that could be merged separately from navigables WIP branch.
> LibWeb: Preparation work before switching to Navigables (3/N)

- Meta/CMake/commonmark_spec.cmake
- Meta/CMake/pnp_ids.cmake
Now one can run `./Meta/serenity.sh rebuild` successfully without internet connection. :^)
> Meta: Download `commonmark.spec.json` and `pnp_ids.html` to the cache directory

- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
These are some commits from https://github.com/SerenityOS/serenity/pull/18219 that could be merged separately from navigables WIP branch.
> LibWeb: Preparation work before switching to Navigables (4/N)

- Userland/Applications/CrashReporter/main.cpp
- Userland/Applications/FileManager/PropertiesWindow.cpp
- Userland/Applications/Piano/MainWidget.cpp
- Userland/Applications/ThemeEditor/MainWidget.cpp
- Userland/Demos/ModelGallery/GalleryWidget.cpp
- Userland/Demos/WidgetGallery/GalleryWidget.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/DevTools/Profiler/main.cpp
- Userland/Libraries/LibGUI/SettingsWindow.h
- Userland/Libraries/LibGUI/TabWidget.h
Note: This PR changes usages of `TabWidget::try_add_tab()`. `SettingsWidget::add_tab()` is still fallible
Contributes to #20557
> LibGUI+Applications: Make creation of tabs non-fallible

- Userland/Services/FileOperation/main.cpp
This ensures that file permissions are correctly preserved.
The issue this PR fixes can be seen here:
https://www.youtube.com/watch?v=54wL_OgKU9I&t=284s
NB: This will also preserve SUID and SGID bits. I'm not sure if this is desirable or not.
> FileOperation: Set umask to 0 when creating new files or directories

- Userland/Libraries/LibWeb/DOM/DOMImplementation.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/DOMParser.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/WindowEnvironmentSettingsObject.cpp
- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
Leaving 4 more interfaces left :^)
> LibWeb: Port Document interface from DeprecatedString to String 

- Userland/Libraries/LibWeb/DOM/Attr.h
- Userland/Libraries/LibWeb/DOM/CDATASection.h
- Userland/Libraries/LibWeb/DOM/Comment.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/DocumentFragment.h
- Userland/Libraries/LibWeb/DOM/DocumentType.h
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
- Userland/Libraries/LibWeb/DOM/ProcessingInstruction.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.h
- Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Userland/Libraries/LibWeb/DOM/Text.h
- Userland/Libraries/LibWeb/Dump.cpp
- Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
- Userland/Services/WebContent/WebDriverConnection.cpp
Which is fortunately quite straight forward :^)
This leaves only 3 interfaces left.
> LibWeb: Port Node interface from DeprecatedString to String

- Userland/Libraries/LibELF/DynamicObject.cpp
This is necessary on riscv64, as sometimes a `PT_RISCV_ATTRIBUTES` PHDR element might be the first one, which has a `p_vaddr` of 0, resulting in a negative base address.
Also, even on x86_64 the first element is quite often a `PT_PHDR`, not a `PT_LOAD` element.
> LibELF: Use the first `PT_LOAD` element to calculate base address

- Userland/Utilities/pkg/AvailablePort.cpp
- Userland/Utilities/pkg/main.cpp
> PackageManager: Fix runtime errors

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/NavigateEvent.h
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.h
- Userland/Libraries/LibWeb/HTML/NavigationParams.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
I started this branch trying to add the NavigateEvent AOs to fire the event so I could write tests, but ended up doing all this cleanup instead :upside_down_face:
> LibWeb: Align NavigationParams and the creation AOs to the spec 

- Userland/Libraries/LibWeb/HTML/History.cpp
- Userland/Libraries/LibWeb/HTML/History.h
- Userland/Libraries/LibWeb/HTML/NavigateEvent.cpp
- Userland/Libraries/LibWeb/HTML/NavigateEvent.h
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.h
- Userland/Libraries/LibWeb/HTML/NavigationDestination.h
- Userland/Libraries/LibWeb/WebIDL/Promise.cpp
- Userland/Libraries/LibWeb/WebIDL/Promise.h
Next step: Update Navigable, TraversibleNavigable and friends to actually fire this event. History as well, for push/pop state.
> LibWeb: Implement the algorithms required to fire NavigateEvent

- Ports/.port_include.sh
- Ports/gn/package.sh
We now support submodules _and_ put the working copy into the correct directory.
> Ports: Small Git-related updates

- Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
In OpenType code, replace unsafe `Span::offset_pointer` with `Span::offset`, which includes bounds checks.
This can prevent trying to access memory beyond what was allocated such as reported in issue #18304.
> AK: Replace unsafe Span::offset_pointer usage in OpenType code

- Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
- Userland/Applications/Maps/CMakeLists.txt
- Userland/Applications/Maps/MapWidget.cpp
- Userland/Applications/Maps/MapWidget.h
- Userland/Applications/Maps/SearchPanel.cpp
- Userland/Applications/Maps/SearchPanel.gml
- Userland/Applications/Maps/SearchPanel.h
- Userland/Applications/Maps/UsersMapWidget.cpp
- Userland/Applications/Maps/UsersMapWidget.h
- Userland/Applications/Maps/main.cpp
- Userland/Libraries/LibGUI/ListView.h
I have added a basic search panel to the Maps application. I've used the new GMLCompiler and add some stuff to it so that `SearchPanel.gml` compiles fully. I also have added some more customization options for `ListView`.
https://github.com/SerenityOS/serenity/assets/19894029/73e730a5-ef78-457c-ab0d-0d5a22dbc22b
*This is SerenityOS x86_64 running on a ARM64 platform so the performance looks worse then it is*
Looking forward to feedback :)
> Maps: Add search panel

- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.h
These are two small changes I had lying around in a branch working towards implementing ReadableStreamBYOBReader
> LibWeb/Streams: Two small more steps towards implementing BYOB reader

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
When there is no `catch` parameter to bind the error, we don't need to allocate an environment, since there's nothing to add to it.
This avoids one environment allocation every time we catch like this:
try {
...
} catch {
...
}
> LibJS: Avoid creating empty environment for `catch` without parameter

- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.cpp
- Userland/Libraries/LibWeb/DOM/Position.cpp
- Userland/Libraries/LibWeb/DOM/Position.h
- Userland/Libraries/LibWeb/Fetch/FetchMethod.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
- Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.h
- Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
- Userland/Libraries/LibWeb/Page/EditEventHandler.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
This is a bunch of fixes to make us leak less of GC-allocated objects :)
> LibWeb: Fix a bunch of GC-allocated objects leaks

- Userland/Utilities/du.cpp
Previously, the same file would be counted more than once if its containing directory was visited multiple times, or there were multiple hard links pointing to it.
We now keep track of every visited inode to ensure that files aren't evaluated multiple times. This matches the behavior of `du` on FreeBSD and Linux.
Example:
> du: Prevent multiple counting of the same file

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.h
- Userland/Libraries/LibWeb/DOM/MutationObserver.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
This is a bunch of fixes for GC object leaks I found in https://browserbench.org/Speedometer2.0/
> LibWeb: Fix more of GC leaks

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/DocumentObserver.cpp
- Userland/Libraries/LibWeb/DOM/DocumentObserver.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGUseElement.cpp
These are fixes for some of GC leaks I found while browsing https://twinings.co.uk/ :)
> LibWeb: Fix more leaks of GC-allocated objects

- Ladybird/AppKit/UI/Tab.mm
A small pr with a small change
CC: @trflynn89
> Ladybird/AppKit: Move frameAutosaveName inside if block

- Documentation/Patterns.md
The `Menubar::add_menu()` call used in the previous code snippet no longer returns `ErrorOr`, which defeats the purpose of the example.
> Documentation: Replace `TRY()` example in `Patterns.md`

- Ladybird/Android/src/main/cpp/JNIHelpers.cpp
- Ladybird/Android/src/main/cpp/JNIHelpers.h
- Ladybird/Android/src/main/cpp/LadybirdActivity.cpp
- Ladybird/Android/src/main/cpp/WebContentServiceJNI.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.h
- Ladybird/Android/src/main/cpp/WebViewImplementationNativeJNI.cpp
- Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdActivity.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebView.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebViewImplementation.kt
- Ladybird/Android/src/main/res/layout/activity_main.xml
- Ladybird/Android/src/main/res/values-night/themes.xml
- Ladybird/Android/src/main/res/values/colors.xml
- Ladybird/Android/src/main/res/values/strings.xml
- Ladybird/Android/src/main/res/values/themes.xml
- Ladybird/CMakeLists.txt
- Ladybird/WebContent/CMakeLists.txt
https://github.com/SerenityOS/serenity/assets/8388494/2933170e-8e56-4d31-a4b5-8b3c7602cdcd
> Ladybird/Android: Add EditText for URL bar and attach to native WebView

- Userland/Applications/Maps/MapWidget.cpp
The information the user is most interested in is usually in the center, so we should start loading tiles from the center and move outwards. Since tiles are loaded in draw order, simply drawing them in this order achieves the desired effect. The current center-outwards loading algorithm is a basic spiral algorithm, but others may be evaluated later.
> Maps: Load tiles starting from center
