Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Grid areas are accessed by their name (string) so HashMap is more appropriate data structure to store them.
=> LibWeb: Use HashMap instead of Vector to store grid areas in GFC

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Unlike DOM mutations, CSS animations don't affect the style of the entire subtree of the element being animated. This means we only have to recompute style for the animating element, which is significantly faster than doing the whole subtree.
This takes idle CPU usage on https://shopify.com/ from 100% to 30% on my (not massively powerful) laptop. :^)
=> LibWeb: Only update style for the element being animated by CSS

Userland/Applications/ThemeEditor/main.cpp, Userland/Libraries/LibFileSystemAccessClient/Client.cpp, Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp, Userland/Services/FileSystemAccessServer/ConnectionFromClient.h, Userland/Services/FileSystemAccessServer/FileSystemAccessServer.ipc
The server cannot use these values anywhere, because this method always sets `prompt = ShouldPrompt::No`. This saves a bunch of roundtrips for all clients that use FSAS to read abritrary files.
Found while looking at IPC traffic using #19047.
This affects for example Ladybird on every single `file://` resource.
=> FileSystemAccessServer: Don't transmit unused data

Userland/Applets/Audio/main.cpp
In Serenity, we have many calls like `Config::read_i32("Foo"sv, "Bar"sv, "baz"sv, 0xC0FFEE)` with inline constants. This can easily lead to conflicting defaults, which already is the case(!) for a handful of places. I want to get to a point where there is exactly one single source of truth for each config value. This PR is a pilot to determine where exactly we want to go, and to avoid conflicting defaults.
The simplest way to store a single source of truth seems in my eyes to be a single `static constexpr` like in this PR, or in those places where it's really necessary, a `FooSettings/Defaults.h` file that is shared by `Foo` and `FooSettings`.
This PR:
- Merges two accesses to the AudioApplet>Applet>ShowPercent into one.
- Instead of having the default value somewhere as a literal in the …
=> Audio: Merge config default values into single source of truth

AK/MemoryStream.cpp, AK/MemoryStream.h, Tests/AK/TestMemoryStream.cpp
=> AK: Fix two edge-cases in AllocatingMemoryStream

Userland/Utilities/userdel.cpp
`userdel -r nona` used to fail with the following error:
```
19.242 [#0 userdel(49:49)]: Rejecting path '/home/nona' because it hasn't been unveiled with 'r' or 'b' permissions
19.242 [#0 userdel(49:49)]: Kernel + 0x0000000000ab1381  Kernel::VirtualFileSystem::validate_path_against_process_veil(Kernel::Process const&, AK::StringView, int) [clone .localalias] +0x611
…
```
This PR fixes that.
We don't really have much use for userdel in the moment, but if we keep it then it should also be kept working, so that's what this PR does.
=> userdel: Removal of files does not require creation rights

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Our workarounds for extracting CORS cross-origin response bodies in `processResponseConsumeBody` is no longer required.
Note that this fix unfortunately did not help the `processResponse` callback, which is triggered just before Fetch extracts the internal response. So HTMLMediaElement and HTMLImageElement still require their workarounds. I opened https://github.com/whatwg/fetch/issues/1664 to ask about that.
=> LibWeb: Handover the fetch response's internal response upon completion

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.h, Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossyTables.h
This basically adds the line
u8 token = TRY(
tree_decode(decoder, COEFFICIENT_TREE,
header.coefficient_probabilities[plane][band][tricky],
last_decoded_value == DCT_0 ? 2 : 0));
and calls it once for the 16 coefficients of a discrete cosine transform
that covers a 4x4 pixel subblock.
And then it does this 24 or 25 times per macroblock, for the 4x4 Y
subblocks and the 2x2 each U and V subblocks (plus an optional Y2 block
for some macroblocks).
It then adds a whole bunch of machinery to be able to compute `plane`,
`band`, and in particular `tricky` (which depends on if the
corresponding left or above subblock has non-zero coefficients).
(It also does dequantization, and does an inverse Walsh-Hadamard
transform when needed, to end up with complete DCT coefficients
in all cases.)
=> WebP/Lossy: Implement macroblock coefficient decoding

Userland/Applications/Browser/CookiesModel.cpp, Userland/Applications/Browser/CookiesModel.h, Userland/Applications/Browser/History/HistoryModel.cpp, Userland/Applications/Browser/History/HistoryModel.h, Userland/Applications/Browser/StorageModel.cpp, Userland/Applications/Browser/StorageModel.h, Userland/Applications/Help/MainWidget.cpp, Userland/Applications/Help/ManualModel.cpp, Userland/Applications/Help/ManualModel.h, Userland/Demos/ModelGallery/BasicModel.cpp, Userland/Demos/ModelGallery/BasicModel.h, Userland/Libraries/LibGUI/CommandPalette.cpp, Userland/Libraries/LibGUI/FilteringProxyModel.cpp, Userland/Libraries/LibGUI/FilteringProxyModel.h, Userland/Libraries/LibGUI/ItemListModel.h, Userland/Libraries/LibGUI/Model.h
This PR improves the search view in Help by introducing the following changes:
* A fuzzy match is now used to match against page titles. This allows for slight misspellings.
* Pages with matching titles now appear at the top of the search results.
Before:
After:
=> LibGUI+Help: Improve search functionality

Tests/LibWeb/Layout/expected/block-and-inline/block-with-max-content-width.txt, Tests/LibWeb/Layout/expected/block-and-inline/block-with-min-content-width.txt, Tests/LibWeb/Layout/input/block-and-inline/block-with-max-content-width.html, Tests/LibWeb/Layout/input/block-and-inline/block-with-min-content-width.html, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
We're gonna need to handle this in many more places, these patches only
add it to calculate_inner_width() which covers block and inline layout.
=> LibWeb: Support {min,max}-content for {,min-,max-}width

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
This if-statement was erroneously dropped in commit 8ff8309.
=> LibWeb: Restore protection against empty HTMLImageElement resources

Tests/LibWeb/Layout/expected/inset-shorthand-property.txt, Tests/LibWeb/Layout/input/inset-shorthand-property.html, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This adds another shorthand property that was missing in a website I was testing!
Before:
After:
=> LibWeb: Add support for parsing 'inset' shorthand CSS property

Userland/Libraries/LibJS/Runtime/MathObject.cpp
I somehow noticed this very very slight difference when looking at this file
to the spec.
This is not an observable difference. Nonetheless, it seems like a good idea
to be as close to the spec as possible, so let's do that (and add some
spec comments while at it)
=> LibJS: Align MathObject::atan2 (ever so slightly) closer to spec

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
https://html.spec.whatwg.org/multipage/input.html#common-input-element-events says that 
```
while text input might not have an explicit commit step, selecting a date from the drop down calendar and then dismissing the drop down would be a commit action.
```
So we remove the commit event from the text change listener.
It goes on to say
```
The change event fires when the value is committed, if that makes sense for the control, or else when the control loses focus.
```
So we need to emit an event when we lose focus
=> LibWeb: Adjust change event timing for text input elements

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h
Add matching on family name, style and weight. This improves the fonts used by the MDN examples.
=> LibWeb: Make font selection closer to specification

.github/workflows/cmake.yml
The AArch64 port is still unstable, and in some cases, we may encounter a kernel panic or Shell crash that prevents `test-results.log` from being written to disk. The CI job would fail when we tried to print out the contents of this non-existent file. We have been ignoring its contents anyway, so let's not read it at all.
=> CI: Do not expect `test-results.log` to exist on AArch64

Userland/Libraries/LibWeb/Loader/FrameLoader.h, Userland/Libraries/LibWeb/Loader/Resource.cpp, Userland/Libraries/LibWeb/Loader/Resource.h, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Services/WebContent/WebDriverConnection.cpp
This fixes the timeout while running WPT tests that was caused by requestAnimationFrame() that queued callbacks on page that is navigated from which in turn was caused by wait_for_navigation_to_complete() that doesn't actually wait for page to load.
=> WebContent: Wait for Resource to load in wait_for_navigation_to_complete

Userland/Utilities/killall.cpp
This PR introduces 2 behavior changes to `killall`
* If a call to `Core::System::kill()` fails, the program no longer stops, but will continue killing matching processes
* Specifying SIGINVAL/INVAL is no longer equivalent to the null signal (signal 0)
=> killall: Continue killing processes if `kill()` call fails

Base/usr/share/man/man1/pgrep.md, Userland/Utilities/pgrep.cpp
This PR adds the following options to `pgrep`:
* `-c`: Shows the number of matched processes
* `-l`: Shows the name of the matched process in addition to its pid
* `-U`: Filter processes by a list of UIDs / user names
* `-x`: Match the given pattern exactly
Examples of the new functionality:
=> pgrep: Add `-c`, `-l`, `-U` and `-x` options

Tests/LibWeb/Layout/expected/acid1.txt, Tests/LibWeb/Layout/expected/flex-item-vertical-padding-relative-to-flex-container-width.txt, Tests/LibWeb/Layout/expected/flex-shrink-2.txt, Tests/LibWeb/Layout/expected/grid/borders.txt, Tests/LibWeb/Layout/expected/grid/grid-gap-2.txt, Tests/LibWeb/Layout/expected/grid/grid-item-percentage-width.txt, Tests/LibWeb/Layout/expected/vertical-padding-relative-to-cb-width.txt, Userland/Libraries/LibWeb/CSS/Angle.cpp, Userland/Libraries/LibWeb/CSS/Angle.h, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Frequency.cpp, Userland/Libraries/LibWeb/CSS/Frequency.h, Userland/Libraries/LibWeb/CSS/Number.h, Userland/Libraries/LibWeb/CSS/Percentage.h, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp, Userland/Libraries/LibWeb/CSS/Time.cpp, Userland/Libraries/LibWeb/CSS/Time.h, Userland/Libraries/LibWeb/Painting/StackingContext.cpp
The wpt tests need more precision than a float can offer
=> LibWeb: Change calc node representation from float to double

Userland/Libraries/LibVideo/PlaybackManager.cpp
Previously, we would unwrap the duration value even when it contained an error, causing an assertion failure.
Later, we should change it to return the last known sample timestamp in the media data, allowing for example live-streamed video to have a semi-useful duration. In general, though, this is not used by players in the wild, so we can leave it for now.
=> LibVideo/PlaybackManager: Return duration zero when an error occurs

Ladybird/HelperProcess.cpp
Currently, we only look at the relative path `./{helper}/{helper}`, which fails if the working directory is not the same as the directory where the ladybird binary lives.
Don't know if we actually need the first/third checks here at all.
The relative `./{helper}/{helper}` seems to be unnecessary, since we now check the absolute path.
Not sure when `./{helper}` will ever find anything?
=> Ladybird: Look for helper processes at `{app_dir}/{helper}/{helper}`.

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp
`predicted_y_above` is initialized to a row of 127s, so we can just read from it even in the first macroblock row.
=> WebP/Lossy: Remove an unnecessary branch

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp
The spec has that clamp at the end of
https://datatracker.ietf.org/doc/html/rfc6386#section-12.2:
The exact algorithm is as follows:
[...]
b[r][c] = clamp255(L[r]+ A[c] - P);
For the test images I'm looking at, it doesn't seem to make a dramatic difference, but omitting it in `B_TM_PRED` did make a dramatic difference, so add it. (Also, the spec demands it.)
=> WebP/Lossy: Add a missing clamp() in `TM_PRED` prediction

Userland/Libraries/LibAudio/CMakeLists.txt, Userland/Libraries/LibAudio/RIFFTypes.cpp, Userland/Libraries/LibAudio/RIFFTypes.h, Userland/Libraries/LibAudio/WavLoader.cpp, Userland/Libraries/LibAudio/WavLoader.h
To make this less painful, this commit also greatly modernizes the WAV loader.
=> LibAudio: Implement metadata loading for WAV

Userland/Applications/KeyboardMapper/main.cpp
Without it, KeyboardMapper crashes as soon as you try to open a file.
=> KeyboardMapper: Do not drop the `unix` pledge

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp
I accidentally inserted a bunch of code in between.
=> WebP/Lossy: Move two enums closer to the struct that uses them

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp
The first commit technically changes behavior (and makes things more correct), but it doesn't seem to have a noticeable effect on the images I tried (or the images covered by automated tests).
The second commit has no measurable performance benefit, but it makes the code look a bit more "normal", so that's nice I suppose.
(The 2nd commit message is only true now that #19180 is in.)
=> WebP/Lossy: Clamp right after summing IDCT output, instead of later; use 8-bit buffers for prediction and YUV data

Userland/Libraries/LibGfx/Painter.cpp
The glyph bitmap is a grayscale image that is multiplied with the requested color provided to `Gfx::Painter::draw_glyph()` to get the final glyph bitmap that can be blitted.
Using `Gfx::Color::multiply()` is unnecessary however: by simply taking the destination color and copying over the glyph bitmap's alpha value, we can prevent four multiplications and divisions per pixel.
In an artifical benchmark I wrote, this improved glyph rendering performance by ~9%.
<details>
<summary>The benchmark in question</summary>
```cpp
auto bitmap = TRY(Gfx::Bitmap::create(Gfx::BitmapFormat::BGRA8888, { 800, 600 }));
Gfx::Painter painter { bitmap };
String text = TRY(String::from_utf8("This is a test"sv));
auto text_view = text.code_points();
auto font = Gfx::FontDatabase::the().get_by_name("Arial 14 400 …
```
=> LibGfx: Improve glyph rendering speed for vector fonts

AK/Complex.h
C++11 has been a requirement for some time now, no need to bother the preprocessor with it.
=> AK: Remove conditional `noexcept` from `Complex`

Userland/DevTools/GMLPlayground/MainWidget.cpp, Userland/Libraries/LibGUI/TextEditor.cpp, Userland/Libraries/LibGUI/TextEditor.h
We had support for going to a specific line before, but now we support jumping around using the `line:column` format :^)
=> LibGUI: Add support for jumping to a line and column in TextEditor

Userland/Libraries/LibWeb/DOM/Node.cpp
The textContent setter changes the structure of the DOM, therefore the layout tree becomes invalid.
=> LibWeb: Invalidate layout tree in textContent setter

Base/home/anon/Tests/run-tests-and-shutdown.sh, Userland/Libraries/LibC/crt0.cpp, Userland/Libraries/LibELF/Image.cpp, Userland/Utilities/run-tests.cpp
This PR resolves an OOM crash that was caused by us leaking coredumps, stop backtrace collection from reading past `_start`'s stack frame and fixes backtrace symbolication issues. See commit messages and comments for details.
=> Solve some AArch64 CI flakes (and make debugging them slightly nicer)

Tests/LibWeb/Layout/expected/place-content-shorthand-property.txt, Tests/LibWeb/Layout/input/place-content-shorthand-property.html, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/PlaceContentStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/PlaceContentStyleValue.h, Userland/Libraries/LibWeb/Forward.h
This adds support for expanding the `place-content` shorthand CSS property as seen here: https://www.w3.org/TR/css-align-3/#place-content.
This is my first contribution in a long while and my first CSS-related PR, exciting :^)
=> LibWeb: Add support for parsing place-content shorthand CSS property

Tests/LibWeb/Layout/expected/line-height-calc-number.txt, Tests/LibWeb/Layout/input/line-height-calc-number.html, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
This is used on GitHub and many other websites.
=> LibWeb: Support `line-height: calc(...)` values that resolve to number

Userland/Libraries/LibGfx/Painter.cpp
When the background color has an alpha < 255, we can't copy over the pixel alpha.
=> LibGfx: Multiply alpha channels for vector fonts, when necessary

Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Now that we allocate an oversized backing store during resizing of the viewport, we need to constrain the source rect used when drawing a scaled version of the content in the special mode used by Presenter.
Regressed with 85c542ab009ca7aea95f7a7503990c26ed27a123.
cc @GMTA @AtkinsSJ
=> LibWebView: Unbreak content-scales-to-viewport mode for Presenter

Userland/Libraries/LibGfx/Painter.cpp
For some reason, we were decoding the source color twice for every pixel in the inner-most loop of `blit_filtered`. This makes sure we only decode the source color once, and rearranges the code to improve readability.
For my synthetic font rendering benchmark, this improves glyph rendering performance by ~9%.
=> LibGfx: Optimize `Painter::blit_filtered()`

Userland/Libraries/LibWeb/DOM/EventTarget.cpp, Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp, Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/HTML/Window.h
This fixes an interaction on https://wpt.live/tools/runner/index.html, where you could not open the test runner window due to the popup blocker
Also fixes the fact that we wrongly hit step 7 in `choose_a_browsing_context`, and returned the current window, when we want to open a new window
=> LibWeb: Make popup blocker less strict by implementing `has_transient_activation`

Userland/Libraries/LibGfx/Color.h
I could not discover proof that this is actually faster than the non-SSE version. In addition, for these relatively simple structures, the compiler is often sufficiently smart to generate SSE code itself.
For a synthetic font benchmark I wrote, this results in a nice 11% decrease in runtime.
=> LibGfx: Remove SSE version of `Color::blend()`

Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossy.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossyTables.h
Nothing super remarkable.
Technically makes the lossy decoder ever more spec compliant, but the new code path is never hit in practice for my test images.
=> WebP: Some minor tweaks and cleanups

Tests/LibWeb/Layout/expected/acid1.txt, Tests/LibWeb/Layout/expected/grid/unresolvable-percentage-track.txt, Tests/LibWeb/Layout/expected/tolerate-css-percentage-overshoot.txt, Tests/LibWeb/Layout/input/tolerate-css-percentage-overshoot.html, Userland/Libraries/LibWeb/CSS/Length.cpp
This is a hack to emulate the behavior of other engines that use fixed-point math. By rounding to 3 decimals, we retain a fair amount of detail, while still allowing overshooting 100% without breaking lines.
This is both gross and slow, but it fixes real sites. Notably, the popular Bootstrap library uses overshooting percentages in their 12-column grid system.
This hack can be removed when CSSPixels is made a fixed-point type.
Before:
After:
=> LibWeb: Round lengths to 3 decimals after resolving from percentage

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/IntegerStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/IntegerStyleValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/NumberStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/NumberStyleValue.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/Layout/Node.cpp
`<integer>` and `<number>` are distinct types in CSS, and we now know which one we want while parsing, so let's use that knowledge to clarify the types we use.
This may or may not exist to make my life easier when reimplementing bounds-checking. :sweat_smile: 
cc @awesomekling: I have a very vague understanding of what the z-index problem was before, is my change there correct?
=> LibWeb: Split NumericStyleValue into NumberStyleValue and IntegerStyleValue

Userland/Services/WindowServer/ConnectionFromClient.cpp, Userland/Services/WindowServer/SystemEffects.h
We used to trust user-provided values blindly, technically leading to UB when `static_cast<ShowGeometry>(geometry)` runs, and in practice crashing in `WindowManager::apply_system_effects` when a too short vector is provided.
Let's be more resilient than that: WindowManager now kicks any client trying to misbehave using this IPC call.
=> WindowServer: Don't crash when trying to set invalid effects

Userland/Libraries/LibCrypto/Hash/PBKDF2.h
A reference to the current stack frame becomes invalid after returning, so returning Bytes is pointless.
I don't understand why this wasn't discovered earlier, but [it caused some CI problems for me](https://github.com/SerenityOS/serenity/pull/19209#issuecomment-1572599912), so I fixed it.
Don't take this as encouragement to break master! :^)
=> LibCrypto: Don't return reference to stack frame in PBKDF

Tests/LibC/TestMemalign.cpp
In AArch CI, this test alone takes up 110.6 seconds. In x86_64 CI, it takes up 68.4 seconds. There is no reason to spend this much time and this many trials on this.
Let's reduce the number of iterations to 500. This should still surface any misalignment with high probability, and should speed up the CI time from minutes to seconds.
=> LibC+Tests: Reduce fuzz iteration in TestMemalign to speed up CI

Tests/LibWeb/Layout/expected/text-align-overflow.txt, Tests/LibWeb/Layout/input/text-align-overflow.html, Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Previously, we would always respect the `text-align` property, even if the text being aligned was too long for its line box and would be clipped. This led to seeing the clipped middle/end of strings when we should instead always see the beginning of the text.
Before:
After:
=> LibWeb: Avoid text-aligning content that is too long for its line box

Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
Somewhere the path bounding box in the layout and the actual draw path are getting slightly mismatched. This results in partly clipped bits of SVGs. The paths are already clipped to the containing SVG, and the size of the path in the layout is computed from the bounding box, so it is probably safe just to remove this clipping for now.
**Before**
**After**
=> LibWeb: Remove per path clipping for SVGGeometryPaintable

Kernel/Arch/x86_64/linker.ld
This had only been in use for architecture detection before the removal of 32 bit x86.
=> Kernel: Remove unused Platform.h include in linker script

Ladybird/ImageCodecPluginLadybird.cpp, Userland/Services/WebContent/ImageCodecPluginSerenity.cpp
If an image had a valid header and valid metadata, but decoding the
image frame data failed, the renderer used to crash.
The crash only happened in SerenityOS, because there
ImageCodecPluginSerenity returned nullptr bitmaps.  Instead, return
{} like ImageCodecPluginLadybird already does if there's a nullptr
frame.
Fixes #19141.
Loading #19141 in the browser satisfyingly also serves as a manual
test for the bug.  (No automated test since we don't run layout
tests within SerenityOS on the bots.)
=> WebContent: Prevent renderer crash on partially invalid image

Userland/Libraries/LibWeb/Layout/Viewport.cpp, Userland/Libraries/LibWeb/Painting/StackingContext.cpp, Userland/Libraries/LibWeb/Painting/StackingContext.h
Stacking contexts are sorted after building a tree of them. They are sorted by `z-index` first, DOM tree order second.
Sorting was previously *very* slow on pages with many stacking contexts. That was because the `sort()` function used `Node::is_before()` in the `quick_sort` comparator to see if one StackingContext was before another. `is_before()` does tree traversal and can take quite a long time per call.
This patch avoids all that by letting `StackingContext` know its index among all `StackingContext`s within the same document in tree order. There's a noticeable snappiness increase on the [CSS-FLEXBOX-1](https://www.w3.org/TR/css-flexbox-1/) spec page, for instance. :^)
=> LibWeb: Make StackingContext sorting a lot faster

Tests/LibWeb/Layout/expected/flex/flex-item-with-calc-main-size-and-layout-dependent-containing-block-size.txt, Tests/LibWeb/Layout/input/flex/flex-item-with-calc-main-size-and-layout-dependent-containing-block-size.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
If a flex item's main size is a CSS calc() value that resolves to a length and contains a percentage, we can only resolve it when we have the corresponding reference size for the containing block.
Nice progression on https://arstechnica.com/
Before:
After:
=> LibWeb: Support flex items with calc() main size containing percentages

Kernel/FileSystem/VirtualFileSystem.cpp, Userland/Utilities/userdel.cpp
When deleting a directory, the rmdir syscall should fail if the path was unveiled without the 'c' permission. This matches the same behavior that OpenBSD enforces when doing this kind of operation.
When deleting a file, the unlink syscall should fail if the path was unveiled without the 'w' permission, to ensure that userspace is aware of the possibility of removing a file only when the path was unveiled as writable.
Closes #19125.
=> Kernel+Userland: Ensure proper unveil permissions when deleting files/directories

Tests/LibWeb/Layout/expected/grid/track-size-calc-with-percentage.txt, Tests/LibWeb/Layout/input/grid/track-size-calc-with-percentage.html, Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
Use contains_percentage() that works for calc() values instead of is_percentage().
This fixes issue when tracks with calc() that has percentages where considered as "fixed" tracks with resolvable size which led to incorrectly resolved infinite final track sizes.
Fixes crash on https://www.imdb.com
=> LibWeb: Fix crashing when grid track size is calc() with percentage

Tests/LibWeb/Layout/expected/css-font-size-calc.txt, Tests/LibWeb/Layout/input/css-font-size-calc.html, Userland/Libraries/LibWeb/CSS/Length.cpp, Userland/Libraries/LibWeb/CSS/Length.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Add a way to resolve `calc()` length values without having a layout node.
Then use it to support `font-size: calc(...)` :^)
Nice progression on the Microsoft Edge homepage.
Before:
After:
=> LibWeb: Support font-size: calc()

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Userland/Libraries/LibWeb/CSS/Properties.json
All but 1 of these are the infinite range `[-∞,∞]`, so adding that doesn't change the behaviour, but does make it clear that we know what the range is, and haven't missed it out unintentionally.
I did intentionally miss out the ranges for the `grid` properties because wow that spec is confusing and I don't want to spend several hours understanding it just for a tiny change like this. :sweat_smile:
=> LibWeb: Add missing value ranges to (most) CSS properties 

Userland/Libraries/LibCore/File.cpp, Userland/Libraries/LibCore/File.h, Userland/Services/SpiceAgent/SpiceAgent.cpp, Userland/Services/SpiceAgent/main.cpp
SpiceAgent is one of possibly few applications which doesn't need to create files if they don't exist before reading or writing to them. Unfortunately, `OpenMode::ReadWrite` assumes that you want the `O_CREAT` privilege too, which isn't indicated by its name. In order to not break everyone that uses `Core::File` already, I think an opt-out approach might be the best here?
Previous discussion about this on Discord, never exactly got to a definite conclusion:
https://discord.com/channels/830522505605283862/830739873119207426/1106704476443779132
=> LibCore+SpiceAgent: Add `Core::File::OpenMode::DontCreate`

Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Identifiers.json, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/ListItemMarkerBox.cpp, Userland/Libraries/LibWeb/Layout/ListItemMarkerBox.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp, Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp, Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp, Userland/Services/WebContent/ConnectionFromClient.cpp
This adds the disclosure `list-style-type`s used for details elements and positions them according to `list-style-position`.
This PR also makes pseudo-elements inspectable because it was useful for debugging ::marker positioning.
=> LibWeb: Improve <details> element rendering

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/DOM/Element.h, Userland/Libraries/LibWeb/DOM/ElementFactory.cpp, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/HTMLDetailsElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLDetailsElement.h, Userland/Libraries/LibWeb/HTML/HTMLSummaryElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLSummaryElement.h
This does not make the \<details> element display as it should, only implement its behaviour
=> LibWeb: Implement the <summary> element behaviour

Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
To abort the processing of any nested invocations of the tokenizer, just return is enough in this case.
During the process of pending parsing blocking script, the is_ready_to_be_parser_executed() check should be applied on the blocking script, not the original script.
Fix the case:
```
<!doctype html>
<html>
<head>
<script>
document.write('<script type="text/javascript" src="https://test_url.js"><\/script>')
</script>
</head>
<body>
</body>
</html>
```
=> LibWeb: Don't let it crash when document.write a script with src attr

Ladybird/Tab.cpp
Allowing for easily pasting into ladybird the path to some HTML file (as an example).
This behavior matches chrome and firefox handling.
=> Ladybird: Assume file:// URL when URL starts with '/'

Userland/Services/SystemServer/Service.cpp, Userland/Services/SystemServer/Service.h
~~Instead just spawn one instance per user like for example an AudioServer per session.
This lets the user to run the pro utility with root permissions without making SystemServer choking on failing to set the correct UID/GID when trying to lazily spawn instances for each possible client.~~
~~Taken from #18944, this allows a user to run `pls pro https://google.com` without crashing due to failing to trying "dropping privileges" when lazily spawning new instances of `RequestServer`.~~
=> SystemServer: Don't exit new service if dropping privileges failed when running as non-root user

Ports/zig/patches/0012-Implement-SerenityOS-support-in-std.patch
After b98f537, the Zig port's types for Serenity no longer matched what Serenity actually returned from LibC; this caused weird errors due to stat() not returning valid values anymore.
Tested that `./package.sh` compiles and installs a working version of Zig; can be merged without waiting for checks.
=> Ports: Update the Zig port's Serenity type definitions

Tests/LibWeb/Layout/expected/block-and-inline/block-with-negative-margin-and-no-intruding-floats.txt, Tests/LibWeb/Layout/input/block-and-inline/block-with-negative-margin-and-no-intruding-floats.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
If a box has a negative margin-left, it may have a negative effective offset within its parent BFC root coordinate system.
We can account for this when calculating the amount of left-side float intrusion by flooring the X offset at 0.
Fixes a goofy layout issue seen on https://xkcd.com/
Closes #19067 
Before:
After:
=> LibWeb: Account for negative margins when calculating float intrusion

Userland/Applications/PixelPaint/Image.cpp, Userland/Applications/PixelPaint/MainWidget.cpp
This PR modifies the behavior of the "Crop Image to Selection" and "Crop Image to Content" actions, so that they work when an image has multiple disjoint layers that don't cover the entire image.
Previously these actions wouldn't work if the selection did not encompass all the layers in the image.
NB: Crop Image to Selection will now delete layers that fall entirely outside of the current selection. This matches how GIMP behaves (I also tried this in Photoshop, which doesn't delete these layers, but resizes them to 0x0.)
Video:
https://user-images.githubusercontent.com/2817754/221109059-18d80d54-e27d-4783-a664-dc4bbd332826.mp4
=> PixelPaint: Make image cropping actions work with multiple layers

Userland/Libraries/LibGUI/TextEditor.cpp
When a text file has only 1 line with long text auto-scroll to the top will no longer loop over and set the cursor to the end of the line.
Before the fix:
[Screencast from 2023-05-12 14-09-59.webm](https://github.com/SerenityOS/serenity/assets/1913834/8d4a5d25-c833-4504-b390-dc4e9d7e160b)
After:
[Screencast from 2023-05-12 14-10-44.webm](https://github.com/SerenityOS/serenity/assets/1913834/5ddbdaca-0ee9-4461-81f2-8b52a2e85dd8)
=> TextEditor: Prevent autoscroll looping over

Tests/LibWeb/Text/expected/css/legacy-color-value.txt, Tests/LibWeb/Text/input/css/legacy-color-value.html
I was not aware of this framework back when implementing this back in bc54560e5942c9ff4b9049c034ad09a9f8446fb6. Add in some basic tests for this now that we are compliant with the specification.
=> Tests/LibWeb: Add some text tests for 'parsing a legacy color value'

Base/res/apps/VideoPlayer.af
Video Player can play VP9 videos inside Matroska. Double-clicking on such files in File Manager will now open this application.
=> Base: Add .mkv file association to Video Player

Userland/Shell/Builtin.cpp, Userland/Shell/Shell.h
This patch adds an alias to the source builtin when an user types ".". We cannot just add an enumeration entry using `__ENUMERATE_SHELL_BUILTIN` because "." is not a valid name in a function.
This patch adds handling similarly to the name rewriting of ":".
Note that this adds the alias in non-posix mode as well, not sure if that is wanted?
Fixes #19089 
First contribution to serenity :^)
=> Shell: Add a "." builtin that aliases to "source"

Tests/LibWeb/Layout/expected/img-with-box-sizing-border-box-and-padding.txt, Tests/LibWeb/Layout/input/img-with-box-sizing-border-box-and-padding.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
This fixes an issue where images with padding and/or border did not have their size adjusted for `border-box`, thereby becoming larger than intended by the author.
Improves https://videolan.org/
Before:
After:
=> LibWeb: Take box-sizing into account when sizing replaced elements

Kernel/CMakeLists.txt, Userland/Applications/PartitionEditor/PartitionModel.cpp, Userland/Applications/PartitionEditor/PartitionModel.h, Userland/Libraries/LibPartition/CMakeLists.txt, Userland/Libraries/LibPartition/EBRPartitionTable.cpp, Userland/Libraries/LibPartition/EBRPartitionTable.h, Userland/Libraries/LibPartition/GUIDPartitionTable.cpp, Userland/Libraries/LibPartition/GUIDPartitionTable.h, Userland/Libraries/LibPartition/MBRPartitionTable.cpp, Userland/Libraries/LibPartition/MBRPartitionTable.h, Userland/Libraries/LibPartition/PartitionTable.cpp, Userland/Libraries/LibPartition/PartitionTable.h, Userland/Libraries/LibPartition/PartitionableDevice.cpp, Userland/Libraries/LibPartition/PartitionableDevice.h
This is a mess, because an MBRPartitionTable really can appear stand- alone (and strongly hold on to a Core::File instance), or might appear as one of many MBRPartitionTable instances inside of an EBRPartitionTable.
The implemented cloning mechanism should be sound:
- If a child MBRPartitionTable exists, then its parent EBRPartitionTable must still be alive, and therefore hasn't closed the fd yet. Thus, we don't have a use-after-close.
- Likewise, if the EBRPartitionTable is destroyed, the fd will be closed. Thus, we don't leak a fd.
However, I don't like this approach at all. If you have any better approach, please improve this code.
CC @supercomputer7: It seems like you wrote this code originally. I don't really feel like I know all the edge cases that apply here. What do you think, how …
=> LibPartition: Migrate from DeprecatedFile to File

Userland/Applications/Browser/BrowserWindow.cpp, Userland/Applications/Browser/DownloadWidget.cpp, Userland/Applications/Browser/Tab.cpp, Userland/Applications/Browser/main.cpp, Userland/Applications/BrowserSettings/AutoplaySettingsWidget.cpp, Userland/Applications/BrowserSettings/BrowserSettingsWidget.cpp, Userland/Applications/BrowserSettings/ContentFilterSettingsWidget.cpp, Userland/Applications/BrowserSettings/Defaults.h
Note that this fixes contradictory default values for group "Preferences", key "Home", and unifies the definition of the default value for all other values into a single source of truth. This is exactly the kind of errors I want to prevent with this new style. Here's a screenrecording of the confusion solved in this PR:
https://github.com/SerenityOS/serenity/assets/2690845/b43a21b5-224c-4db6-8a03-c27c14712d63
The hope is that this can later be used to:
- verify that all accesses to the same key use the same default value,
- and extract the default values more easily.
See also: #19080
=> Browser: Store default config values in a single place

Tests/LibC/CMakeLists.txt, Tests/LibC/TestEnvironment.cpp, Userland/Libraries/LibC/stdlib.cpp
Dr. POSIX says:
Although the space used by string is no longer used once a new
string which defines name is passed to putenv(), if any thread in
the application has used getenv() to retrieve a pointer to this
variable, it should not be freed by calling free(). If the changed
environment variable is one known by the system (such as the locale
environment variables) the application should never free the buffer
used by earlier calls to putenv() for the same variable.
Applications _should_ not free the data passed to `putenv`, but they _could_ in practice. I found that our Quake II port misbehaves in this way, but does not crash on other platforms because glibc/musl `putenv` does not assume that environment variables are correctly formatted.
The new behavior ignores environment variables …
=> LibC: Do not crash if value passed to `putenv` was freed

Userland/Libraries/LibGfx/AntiAliasingPainter.cpp, Userland/Libraries/LibGfx/AntiAliasingPainter.h, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/Path.h
Finally, I can be happy with the SVG rasterization! Note: There's still a bunch of TODOs (e.g. implement line joins other than round, wire up using paint styles with strokes, and probably fix bugs and optimise things).
| Old                                                                                                                                 | New                                                                                                                                 |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| …
=> LibGfx: Convert strokes to fills => Nice stroke rendering for free!

Userland/Libraries/LibWeb/Loader/ImageResource.cpp, Userland/Libraries/LibWeb/Loader/ImageResource.h, Userland/Libraries/LibWeb/Loader/Resource.h
This will allow for SVGs to be loaded when used in CSS rules.
For example:
```html
<style>
.rect {
background: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" /></svg>');                      
width: 100px;
height: 100px;
}
</style>
<div class="rect"></div>
```
This PR will allow the square to be displayed as the background image!
=> LibWeb: Allow loading of SVGs in ImageResource

Tests/LibC/TestEnvironment.cpp, Userland/Libraries/LibC/stdlib.cpp
Depending on stack values being correctly and deterministically overwritten was a bit too optimistic, to be honest. This new logic uses a value on the heap.
=> Tests: Un-flake the recent `TestEnvironment` addition

Meta/run.sh
This results in significant performance improvements in both sequential and random disk reading and writing.
Some benchmarks on my machine, all run on a fresh boot of SerenityOS:
|Benchmark|ATA|NVME|
|---|---:|---:|
|`dd if=/dev/zero of=./output.file bs=64k count=1600`|8602 ms|3131 ms (-64%)|
|`dd if=./output.file bs=64k of=/dev/null`|10223 ms|3988 ms (-61%)|
|`find / 2>&1 >/dev/null`|1075 ms|500 ms (-54%)|
=> Meta: Enable NVME by default

Kernel/Arch/aarch64/RPi/Mailbox.cpp, Kernel/Arch/aarch64/RPi/Mailbox.h, Kernel/Arch/init.cpp
Instead of having a single available memory range that encompasses the
whole 0x00000000-0x3EFFFFFF range of physical memory, create a separate
reserved entry for the RAM range used by the VideoCore. This fixes a
crash that happens when we try to allocate physical pages in the GPU's
reserved range.
This will eventually be replaced with parsing the data from the device
tree, but for now, this should solve some of the recurring CI failures.
=> Kernel/aarch64: Account for reserved VideoCore range in the memory map

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
The function stopped copying data from a subimage when the _y_ value exceeded the image _width_ value, resulting in an incomplete image.
test image: https://images.videolan.org/images/icons/platform-sprite.png
before | after
---|---
=> LibGfx: Fix partial loading of tall and interlaced PNG files

Meta/Lagom/Tools/CodeGenerators/LibEDID/GeneratePnpIDs.cpp, Meta/check-style.py, Userland/Applications/Piano/RollWidget.cpp, Userland/Libraries/LibGfx/Font/OpenType/Tables.h, Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.cpp
This is about the third time we have weirdly-ordered includes, so let's add a lint that prevents these from being introduced. I don't like that we rely on weird "local include but resolve using system include paths" quirks.
While this does introduce significant overhead in terms of percentage, I think that an additional 10ms on huge commits (or less on smaller commits) are acceptable:
```
hyperfine -w1 './Meta/check-style.py AK/*.h AK/*.cpp' # Before this PR
Benchmark 1: ./Meta/check-style.py AK/*.h AK/*.cpp
Time (mean ± σ):      20.3 ms ±   0.4 ms    [User: 17.1 ms, System: 3.5 ms]
Range (min … max):    19.5 ms …  21.6 ms    128 runs
hyperfine -w1 './Meta/check-style.py AK/*.h AK/*.cpp' # After this PR
Benchmark 1: ./Meta/check-style.py AK/*.h AK/*.cpp
Time (mean ± σ):      32.3 ms ± …
```
=> Meta: Make sure that our includes are properly formatted

Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h
These images can't contain any meaningful information, so no need to try to decode them. Doing so result in a `SIGFPE`, as we divide by this value later on.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57434&sort=-opened&can=1&q=proj%3Aserenity
=> LibGfx/PortableFormat: Reject images with a maximum value of 0

Userland/Libraries/LibGUI/TextDocument.cpp, Userland/Libraries/LibGUI/TextDocument.h, Userland/Libraries/LibGUI/TextEditor.cpp
When you undo some forward delete shortcuts like `<Del>` or `<Ctrl-Del>`, the cursor will be put at the end of the text deleted, while the right position should be the start of those text.
Before:
https://github.com/SerenityOS/serenity/assets/57862491/c8d4de0c-d522-4aad-b569-ba468c7fe152
After:
https://github.com/SerenityOS/serenity/assets/57862491/c22d1aa1-c200-4ddc-a6f0-a4177fece62d
=> LibGUI: Fix wrong cursor position after undoing `RemoveTextCommand`

Userland/Libraries/LibC/signal.cpp, Userland/Libraries/LibC/string.cpp, Userland/Utilities/kill.cpp
This PR fixes a few issues around signal name parsing:
* Giving an invalid signal name no longer results in a segfault.
* We now disallow sending SIGCANCEL, as it is intended for internal use only. Attempting to send SIGCANCEL previously resulted in a segfault.
* Specifying SIGINVAL/INVAL is no longer equivalent to the null signal (signal 0). The user can still specify signal 0; this is often used to determine whether a given pid exists or not.
* Numerical signals with more than one digit are now parsed correctly. Previously, only the first digit was taken into account.
* SIGINVAL and SIGCANCEL are no longer shown in the signal list given by `kill -l`.
Before:
After:
=> kill: Don't crash when given an invalid signal

Userland/Applications/SystemMonitor/main.cpp
The minimal build configuration doesn't include HackStudio and SystemMonitor refused to run after trying to unveil a not exiting file.
This change will just ignore this specific error for this specific file as if nothing really happened.
The ability to quickly debug a process in HackStudio is not the main feature of the application and HackStudio itself is rather heavy to be put in the minimal configuration.
Additionally, I find it unnecessary to disable/hide the 'Debug in HackStudio' action because build configurations are mostly for testing purposes anyway. You will get a 'No such file or directory' error in the console after activating the action though. :^)
=> SystemMonitor: Ignore unveil error about unexisting HackStudio binary

Base/usr/share/man/man1/Applications.md, Base/usr/share/man/man1/Applications/3DFileViewer.md, Base/usr/share/man/man1/Applications/Assistant.md, Base/usr/share/man/man1/Applications/CatDog.md, Base/usr/share/man/man1/Applications/CertificateSettings.md, Base/usr/share/man/man7/Tips-and-Tricks.md
Add application manpages for:
- 3D File Viewer
- CatDog
- Certificate Settings
This contributes towards #11311
Also
- Update `Applications.md` to reflect these new pages and add previously missing pages.
- Update `Assistant.md` with instructions for:
- Running terminal commands. Reflect this in the sister section in `Tips-and-Tricks.md` 
- Launching applications with arguments.
=> Base: Add/update some application manpages (Part 1)

Userland/Utilities/mknod.cpp
This patch fixes the todo of implement file permissions for the `mknod` command.
https://man7.org/linux/man-pages/man1/mknod.1.html
=> mknod: Use ArgsParser and add option for specifying file permissions

Userland/Libraries/LibCore/File.cpp
The if statement for setting the O_NONBLOCK flag was written the other way around, causing Core::File to open files in non-blocking mode, when we didn't actually specify it.
---
I did find that this "fixes" reading FIFOs with cat(1), but I'm making it draft anyway because I feel that further investigation should be done on how this affects the system.
Before|After
---|---
=> LibCore: Fix logic deciding when to open files in non-blocking mode

Base/res/html/misc/svg-gradients.html, Userland/Libraries/LibGfx/AntiAliasingPainter.cpp, Userland/Libraries/LibGfx/AntiAliasingPainter.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
=> LibWeb/SVG: Support url() in the stroke attribute

Userland/Libraries/LibWeb/CSS/ComputedValues.h
CSS text-shadow is an inherited property, so we have to make sure it's part of the inherited substructure in ComputedValues, otherwise it gets incorrectly reset in children.
Not testable with our current infrastructure.
Visible progression on https://igalia.com/ (note the text on top of images)
Before:
After:
=> LibWeb: Make text-shadow inherited in CSS::ComputedValues

Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
For https://fjord.dropboxstatic.com/warp/conversion/dropbox/warp/en-us/dropbox/Integrations_4@2x.png?id=ce8269af-ef1a-460a-8199-65af3dd978a3&output_type=webp :
Before:
After:
=> WebP/Lossy+Alpha: Implement filtering_method for ALPH chunk

Tests/LibWeb/Layout/expected/block-and-inline/margin-padding-block-inline.txt, Tests/LibWeb/Layout/input/block-and-inline/margin-padding-block-inline.html, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Like other logical properties, we just alias these to the LTR TB default properties for now.
Nice visual progression on Apple Security blogs.
Before:
After:
=> LibWeb: Add naive support for margin-{block,inline} and padding-{block,inline} properties

Tests/LibWeb/Layout/expected/grid/negative-grid-item-column-index.txt, Tests/LibWeb/Layout/input/grid/negative-grid-item-column-index.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
This changes grid items position storage type from unsigned to signed integer so it can represent negative offsets and also updates placement for grid items with specified column to correctly handle negative offsets.
=> LibWeb: Add support for grid items with negative column-start in GFC

Tests/LibWeb/Layout/expected/grid/all-implicit-rows.txt, Tests/LibWeb/Layout/input/grid/all-implicit-rows.html, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp, Userland/Libraries/LibWeb/CSS/GridTrackSize.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleValues/GridTrackSizeListStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/GridTrackSizeListStyleValue.h
This fixes the issue that currently we use "auto" as initial value for grid-template-column and grid-template-rows although spec says it should be "none". This makes a lot of difference for these properties because currently we represent "auto" as a list with one auto-sized track which means initial value for grid-template-column defines one "explicit" track while it should define none of them.
This change makes grid-auto-columns/rows be applied to the correct tracks when initial values is used for grid-template-column/rows.
=> LibWeb: Use none as initial value for grid-template-column/rows

Tests/LibWeb/Layout/expected/grid/distribute-extra-space-across-spanned-tracks.txt, Tests/LibWeb/Layout/input/grid/distribute-extra-space-across-spanned-tracks.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
This fixes the issue when functions that distribute base_size or growth_limit to tracks only considered *affected* spanned tracks while calculating left extra that is available for distribution while indeed it should be just *all* spanned track by specific item that extra space size.
=> LibWeb: Consider all spanned tracks while finding extra space in GFC

Userland/Libraries/LibCore/System.cpp
When called with `SearchInPath::Yes`, calls to `Core::System::exec()` would fail. The value returned from
`resolve_executable_from_environment()` was assigned to a StringView, but the original reference was not kept, causing the StringView to appear empty.
This was causing scripts that use `env` to fail.
Tested with the following script:
```sh
#!/usr/bin/env Shell
echo "Hello"
```
Prior to this PR, the above would fail with: `exec: No such file or directory (errno=2)`.
=> LibCore: Ensure `exec()` keeps a reference to the executable path

Base/res/html/misc/canvas-gradients.html, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
A gradient stroke:
\+ A few small fixes/tweaks I noticed while adding the above.
=> LibWeb: Allow paint style fills for CRC2D strokes (and other tweaks)

Ladybird/BrowserWindow.cpp, Tests/LibWeb/Text/expected/title.txt, Tests/LibWeb/Text/input/title.html, Userland/Applications/Browser/Tab.cpp, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWebView/WebContentClient.cpp
The main differences between our current implementation and the spec
are:
* The title element need not be a child of the head element.
* If the title element does not exist, the default value should be the empty string - we currently return a null string.
* We've since added AOs for several of the spec steps here, so we do not need to implement those steps inline.
=> LibWeb: Implement the document title attribute closer to the spec

Base/home/anon/Tests/run-tests-and-shutdown.sh
These might be the cause of CI failures.
=> CI: Don't run known-failing tests on Aarch

Meta/Lagom/Tools/CodeGenerators/LibEDID/GeneratePnpIDs.cpp
The PNP IDs data file was recently updated with an accidental duplicate entry (HONOR Device Co., Ltd.). Rather than breaking everyone's build, let's just ignore duplicates.
=> LibEDID: Ignore duplicate PNP IDs

Meta/run.sh
This broke in c2e24a2fa19f442e6285fc3b96b69cf0f97115e5 where the boot drive was removed from `SERENITY_MACHINE`. We now add the boot drive to the common Qemu arguments, so it gets included in the aarch64 run configuration as well.
=> Meta: Re-add boot drive to aarch64 run configuration

Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h
This implements a change from the updated 2023-06-02 CSS Animations 2 spec. ([Link](https://www.w3.org/TR/2023/WD-css-animations-2-20230602/#changes-recent)) There are several changes there, and this only implements one, but I think the others don't affect us yet.
=> LibWeb: Allow `auto` as `animation-duration` and make that the default

Kernel/FileSystem/ProcFS/Inode.cpp, Kernel/Tasks/Process.cpp, Kernel/Tasks/Process.h
With this PR, processes now store their creation time. I have used this to set the ProcFS `atime`, `ctime` and `mtime` initial values to the time the process was created. 
Before:
After:
=> Kernel: Store process creation time and use it in ProcFS

Kernel/Syscalls/execve.cpp, Kernel/Syscalls/fork.cpp, Kernel/Tasks/Process.h
These 4 fields were made `Atomic` in
c3f668a758addcf80154d42e95a701edce4bbe59, at which time these were still accessed unserialized and TOCTOU bugs could happen. Later, in 8ed06ad814734430193f3673b5e00861eda9aa47, we serialized access to these fields in a number of helper methods, removing the need for `Atomic`.
=> Kernel: De-atomicize fields for promises in `Process`

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/SVGTextBox.cpp, Userland/Libraries/LibWeb/Layout/SVGTextBox.h, Userland/Libraries/LibWeb/Painting/SVGTextPaintable.cpp, Userland/Libraries/LibWeb/Painting/SVGTextPaintable.h, Userland/Libraries/LibWeb/SVG/AttributeNames.h, Userland/Libraries/LibWeb/SVG/SVGTextContentElement.cpp, Userland/Libraries/LibWeb/SVG/SVGTextContentElement.h
The implementation of painting for SVG text follows the same pattern as the implementation of painting for SVG geometries. However, instead of reusing the existing PaintableWithLines to draw text, a new class called SVGTextPaintable is introduced. because everything that is painted inside an SVG is expected to inherit from SVGGraphicsPaintable. Therefore reusing the text painting from regular text nodes would require significant refactoring.
=> LibWeb: Implement painting for svg text

AK/IPv6Address.h, Tests/AK/TestIPv6Address.cpp, Userland/Libraries/LibC/arpa/inet.cpp, Userland/Libraries/LibWeb/SecureContexts/AbstractOperations.cpp
Hi!
commit ada1b4a and commit 45ee7dc introduces and uses `IPv6Address::loopback()`, so one can compare against the loopback address without parsing addresses and introducing strings at all.
commit 81d8de7 :
>Change the name and return type of `IPv6Address::to_deprecated_string()` to `IPv6Address::to_string()` with return type `ErrorOr<String>`.
>
> It will now propagate errors that occur when writing to the StringBuilder.
>
> There are two users of `to_deprecated_string()` that now use `to_string()`:
>
> 1. `Formatted<IPv6Address>`: it now propagates errors.
>
> 2. `inet_ntop`: doesn't propgate errors. I first thought about setting `ENOSPC`, but that would be wrong, as that error refers to the buffer provided by the user. Since the user has provided a buffer to write into, ideally, there …
=> AK: Get rid of some DeprecatedStrings — IPv6Address::to_deprecated_string()

Userland/Libraries/LibWebView/ViewImplementation.cpp
We now check if the WebContent is executable before passing it to the valgrind wrapper. We can't rely on exec() to fail here, since it will always succeed even when passing a bad WebContent path to valgrind.
=> LibWebView: Unbreak spawning WebContent process with valgrind

Ladybird/CMakeLists.txt
This now matches the Lagom-based Ladybird build and the SerenityOS build.
This fixes a build issue when building with the standalone Ladybird CMakeLists.txt.
=> Ladybird: Add `Userland` to the list of include directories

Tests/LibWeb/Layout/expected/grid/row-span-2-with-gaps.txt, Tests/LibWeb/Layout/input/grid/row-span-2-with-gaps.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
This fixes the issue when left free space is calculated incorrectly because for_each_spanned_track_by_item does not include gap tracks.
=> LibWeb: Include gaps in for_each_spanned_track_by_item in GFC

Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
With this, the play button is nicely antialiased.
=> LibWeb: Use fill_path() to paint <video> play buttons

Tests/LibWeb/Layout/expected/table/colspan-width-distribution.txt, Tests/LibWeb/Layout/input/table/colspan-width-distribution.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
* Fix upper limit of span when computing column measures
* Distribute cell contribution to all spanned columns
More details are in the commit messages.
=> LibWeb: Fixes for table width with spanning columns

Base/usr/share/man/man1/pgrep.md, Kernel/FileSystem/SysFS/Subsystems/Kernel/Processes.cpp, Userland/Libraries/LibCore/ProcessStatisticsReader.cpp, Userland/Libraries/LibCore/ProcessStatisticsReader.h, Userland/Utilities/pgrep.cpp
This PR adds the following options to `pgrep`:
* `-n`: Select the newest matching process.
* `-o`: Select the oldest matching process.
* `-O`: Select processes older than the given number of seconds.
The `creation_time` field was added to `/sys/kernel/processes` to support this.
Example usage:
=> Kernel+pgrep: Add `-n`, `-o` and `-O` options to filter processes by age

Userland/Utilities/man.cpp
This fixes an issue where man breaks if you symlink `sh` to a different shell.
Unveiling `/usr/local/bin` is not sufficient as only `/bin/Shell` understand the
`--skip-shellrc` flag that it currently requires.
I think this replacing "sh" with "/bin/Shell" as the executable (but not argv[0])
is the least broken man can be for the time being.
=> man: Specify full path for Shell

Userland/Libraries/LibJS/Lexer.cpp, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Parser.h, Userland/Libraries/LibJS/Tests/modules/basic-modules.js, Userland/Libraries/LibJS/Tests/modules/default-regexp-export.mjs, Userland/Libraries/LibJS/Tests/syntax/slash-after-block.js
Previously we were unable to parse code like `yield/2` because `/2` was parsed as a regex. At the same time `for (a in / b/)` was parsed as a division.
This is solved by defaulting to division for any IdentifierName and telling the lexer to `force_slash_as_regex()` whenever the name is used as a keyword instead of an identifier.
=> LibJS: Parse slashes after reserved identifiers correctly

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
This patch reduces both memory usage and time by roughly 10%.
=> LibGfx/JPEG: Improve input data access

Base/usr/share/man/man1/pkill.md, Userland/Utilities/pkill.cpp
This PR adds 3 new options to `pkill`:
* `-c`: Prints a count of the number of matched processes. Note: processes that fail to be killed are counted in this total.
* `-U`: Filter processes by a comma-separated list of UIDs or login names
* `-x`: Match the given pattern exactly
`pkill` will now also output the reason for failure when killing a process fails.
Video showing the new functionality:
https://github.com/SerenityOS/serenity/assets/2817754/413451a4-36e8-4f10-b986-b353240a6dd6
=> pkill: Add `-c`, `-U` and `-x` options

Tests/LibWeb/Layout/expected/table/border-conflict-resolution-with-col.txt, Tests/LibWeb/Layout/input/table/border-conflict-resolution-with-col.html, Userland/Libraries/LibWeb/Dump.cpp, Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/Layout/LayoutState.cpp, Userland/Libraries/LibWeb/Layout/LayoutState.h, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h, Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.h
Makes the [structuring planet data](https://mdn.github.io/learning-area/html/tables/assessment-finished/planets-data.html) example on MDN a bit closer to correct.
Before:
After:
=> LibWeb: Add partial implementation of border conflict resolution

Tests/LibWeb/Layout/expected/css-ex-unit.txt, Tests/LibWeb/Layout/expected/text-align-justify-with-forced-break.txt, Tests/LibWeb/Layout/input/css-ex-unit.html, Tests/LibWeb/Layout/input/text-align-justify-with-forced-break.html, Tests/LibWeb/rebaseline-libweb-test, Userland/Libraries/LibGfx/Font/OpenType/Font.cpp, Userland/Libraries/LibGfx/Font/OpenType/Tables.h, Userland/Libraries/LibGfx/Font/ScaledFont.cpp, Userland/Libraries/LibGfx/Font/VectorFont.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/LineBox.h, Userland/Libraries/LibWeb/Layout/LineBuilder.cpp, Userland/Libraries/LibWeb/Layout/LineBuilder.h
Two main fixes here:
- Actually fetch the x-height from OpenType fonts so that CSS `ex` length units work as expected.
- Don't justify text on the last line before a forced break.
Nice progression on https://browser.engineering/
Before:
After:
=> LibGfx+LibWeb: Make the browser book (browser.engineering) a bit more browsable

Tests/LibWeb/Text/expected/link-element-media-attribute.txt, Tests/LibWeb/Text/input/body-background-color-red.css, Tests/LibWeb/Text/input/link-element-media-attribute.html, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Otherwise, we will treat the loaded style sheet as if it had media="all" which is not always appropriate.
Nice progression on https://w3.org/
Before:
After:
=> LibWeb: Forward media attribute from link element to loaded style sheet

Kernel/Tasks/Thread.h, Userland/Applications/SystemMonitor/ProcessModel.cpp, Userland/Applications/SystemMonitor/ProcessModel.h, Userland/Libraries/LibCore/ProcessStatisticsReader.cpp, Userland/Libraries/LibCore/ProcessStatisticsReader.h
This PR changes the byte counts shown in the `ProcessStateWidget` to be 64 bit.
This allows IPv4/Unix sockets and file I/O to exceed 4GiB without overflowing. 
The statistics are now shown in a human-readable format with thousands separators.
Tested with the following command: `dd if=/dev/zero of=/home/anon/large.test bs=8M count=1024`
I also tested with: `pro -O http://speed.hetzner.de/10GB.bin`. I managed to download more than 4GiB, but I didn't wait for the entire file to download.
> **Note**
> You need to create a larger disk image than usual to test this, I used: `export SERENITY_DISK_SIZE_BYTES=20000000000`  to create a 20GB image.
Example `dd` command:
Example RequestServer statistics:
=> Kernel+SystemMonitor: Make thread statistics human-readable and avoid overflow

Base/res/html/misc/svg-gradients.html, Userland/Libraries/LibGfx/AntiAliasingPainter.cpp, Userland/Libraries/LibGfx/AntiAliasingPainter.h, Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp, Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h, Userland/Libraries/LibGfx/Painter.h, Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathClipper.cpp, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
This allows filling/stroking paths with a paint style and apply an opacity (and hooks it up for SVG paintables):
=> LibWeb+LibGfx: Allow filling/stroking with a paint style and opacity

Userland/Libraries/LibWeb/SVG/SVGTextContentElement.cpp
Acid3 sets 1em as the y coordinate of one of external SVG fonts, we don't support that yet. Ignore unsupported unit instead of crashing.
=> LibWeb: Avoid crash for unsupported length unit in SVG elements

Userland/Shell/Shell.cpp, Userland/Shell/Shell.h
=> Shell: Reset the custom Shell keybinds before calling Editor::get_line()

Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt, Tests/LibWeb/Layout/input/table/row-span-and-nested-tables.html, Userland/Libraries/LibWeb/Layout/AvailableSpace.cpp, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/LayoutState.cpp, Userland/Libraries/LibWeb/Layout/LayoutState.h, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
1. Add logic to compute {min, max}-height.
2. Use min-height when calculating table height, per specifications.
3. Fix table width algorithm when available space is a constraint.
Fixes some issues with phylogenetic tree visualizations on Wikipedia.
=> LibWeb: Some row span fixes when combined with nested tables

Tests/LibWeb/Layout/expected/grid/grid-row-height-affected-by-item-margins.txt, Tests/LibWeb/Layout/expected/grid/grid-template-columns-with-min-css-function.txt, Tests/LibWeb/Layout/input/grid/grid-row-height-affected-by-item-margins.html, Tests/LibWeb/Layout/input/grid/grid-template-columns-with-min-css-function.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
* **LibWeb: Support more CSS functions in grid track size lists**
Instead of hard-coding a check for `"calc"`, we now call out to `parse_dynamic_value()` which allows use of other functions like `min()`, `max()`, `clamp()`, etc.
* **LibWeb: Use grid item *outer* size when calculating minimum contribution**
Previously we used the border box, which meant that tracks did not grow to accommodate item margins.
=> LibWeb: Two CSS grid fixes

AK/FlyString.h, AK/String.h, Userland/Applications/GamesSettings/ChessSettingsWidget.cpp, Userland/Applications/Help/MainWidget.cpp, Userland/Applications/HexEditor/FindDialog.cpp, Userland/DevTools/SQLStudio/MainWidget.cpp, Userland/DevTools/SQLStudio/ScriptEditor.cpp, Userland/Libraries/LibCore/System.cpp, Userland/Libraries/LibGUI/CommonActions.cpp, Userland/Libraries/LibGUI/Statusbar.cpp, Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Shell/AST.cpp, Userland/Shell/Formatter.cpp, Userland/Shell/ImmediateFunctions.cpp, Userland/Shell/Parser.cpp, Userland/Utilities/cal.cpp
Let's just stop lying about types, hiding the fact that we are using deprecated APIs,
also this actually removes some falsely marked `from_deprecated_string`s, so:
`from_deprecated_(fly_)?string`: +19-5 = +14
`from_utf8`: +5
=> AK: Forbid calling `from_utf8` and `from_deprecated_{fly_|}string` with unintended types

Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Previously, the `image-rendering` property was ignored for contexts that were scaled using CSS transforms.
Ignore the unrelated scaling-related goof. The lower example scales the `<img>` element with the usual `width` and `height` properties, and the upper example uses CSS `scale(2)` instead.
Before:
After:
The difference can be observed well on [pixel.vkoskiv.com](https://pixel.vkoskiv.com), which makes heavy use of dynamic CSS transforms to scale the canvas:
Before:
After:
The test pages are available here:
[img dimension scale](https://gist.github.com/vkoskiv/8e0978a06bcc73f03bbacaa3382e52ba)
[CSS transform scale](https://gist.github.com/vkoskiv/a45d52c0b0731afc64a0ae4fac9eb5bb)
=> LibWeb: Teach CSS transformed StackingContexts about image-rendering

Userland/Services/SystemServer/Service.cpp, Userland/Services/SystemServer/Service.h
We used to call `did_exit()` directly with the status returned from
`waitpid` but the function expected an exit code. We now use several
of `wait`-related macros to deduce the correct information.
=> SystemServer: Handle waitpid's status correctly

AK/Vector.h
We don't need to do `max(4, ...)` if the RHS always adds 4.
=> AK: Simplify `Vector::padded_capacity`

Tests/LibWeb/Layout/expected/svg/dont-stretch-fit-svg-with-indefinite-containing-block-width.txt, Tests/LibWeb/Layout/input/svg/dont-stretch-fit-svg-with-indefinite-containing-block-width.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
The spec says the result of this algorithm is undefined in such cases, and it appears that other engines yield a zero size.
More importantly, this prevents us from leaking a non-finite value into the layout tree.
=> LibWeb: Make stretch-fit return 0 when the available size is indefinite

Ports/nlohmann-json/package.sh
CMAKE_INSTALL_DATADIR is used to define the install base dir for
pkgconf files. In this case it defaulted to /usr/local/share/pkgconf
which is not a location searched by default.
See https://github.com/nlohmann/json/blob/a0c1318830519eac027a31edec1a99ce1ae5670e/CMakeLists.txt#L69
=> Ports/nhlohmann-json: fix pkgconf install path

Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-auto-margins-in-inline-axis.txt, Tests/LibWeb/Layout/input/block-and-inline/abspos-with-auto-margins-in-inline-axis.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Specifically, we now handle cases where all three of `left`, `width` and `right` are non-`auto`.
Fixes the misaligned search box on https://bing.com/
Before:
After:
=> LibWeb: Resolve auto margins on abspos elements in more cases

Userland/Libraries/LibWeb/FileAPI/Blob.cpp, Userland/Libraries/LibWeb/FileAPI/Blob.h, Userland/Libraries/LibWeb/FileAPI/Blob.idl, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/EventLoop/Task.h, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp, Userland/Libraries/LibWeb/Streams/AbstractOperations.h
There are still plenty more cases to handle, but this does allow us to
handle the basic scenario of getting a readable stream from a blob, and
reading all of the data from that stream until it is done.
I've tried adding tests to go along with these changes, but ran into: https://github.com/SerenityOS/serenity/issues/19359
Ideas to fix my above problem appreciated!
=> LibWeb: Implement FileAPI::Blob::stream()

Tests/LibRegex/Regex.cpp, Userland/Libraries/LibRegex/RegexOptimizer.cpp
This fixes <https://github.com/tc39/test262/blob/55658a4fa23442e0bb537f04ca1bfbb84b90723e/test/built-ins/RegExp/S15.10.2.7_A3_T12.js> (test262: fixes 5 tests), and throws a random free fix on top.
=> LibRegex: Do not treat repeats followed by fallthroughs as atomic / Make append_alternation() actually skip the common blocks

.gitignore, Meta/Azure/Lagom.yml, Meta/check-markdown.sh, Tests/LibWeb/WPT/concat-extract-metadata.py, Tests/LibWeb/WPT/include.ini, Tests/LibWeb/WPT/ladybird_runner.patch, Tests/LibWeb/WPT/metadata.txt, Tests/LibWeb/WPT/run.sh
Introduce very initial and basic support for running Web Platform Tests for Ladybird. This change includes simple bash script that currently works only on Debian and could run tests with patched runner.
For now script to run WPT is not integrated in CI.
There is also a bunch of metadata required to run WPT. To avoid introducing thousands of files in the initial commit for now it is limited to run only css/CSS2/floats tests subdirectory.
=> LibWeb: Add a script to run Web Platform Tests

Userland/Libraries/LibGfx/Bitmap.cpp, Userland/Libraries/LibGfx/Bitmap.h, Userland/Utilities/image.cpp
Allows running `Build/lagom/image --strip-alpha ~/Downloads/Integrations_4@2x.webp -o tmp-rgb.png` and `Build/lagom/image --move-alpha-to-rgb ~/Downloads/Integrations_4@2x.webp -o tmp-a.png` on this file
to learn that its RGB looks like
and its alpha like
(It however doesn't tell you that the lossless webp that stores the alpha channel actually looks like
since that information is lost during webp decoding.)
(Can be used with any image with an alpha channel of course, not just webps.)
=> image: Add --strip-alpha, --move-alpha-to-rbg flags

Tests/LibWeb/Layout/expected/block-and-inline/block-with-hidden-overflow-after-float.txt, Tests/LibWeb/Layout/input/block-and-inline/block-with-hidden-overflow-after-float.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h, Userland/Libraries/LibWeb/Layout/FormattingContext.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
The margin from the containing blocks shouldn't be included in the amount by which we increment x after a float was places. That coordinate should be relative to the containing block.
Fixes the comments layout on https://lobste.rs.
=> LibWeb: Fix the x coordinate of a block after a float

Tests/LibWeb/Layout/expected/percentage-max-height-when-containing-block-has-indefinite-height.txt, Tests/LibWeb/Layout/input/percentage-max-height-when-containing-block-has-indefinite-height.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Layout/Node.h, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Fixes #19371
Nice progression on https://www.freecodecamp.org (the yellow "Get started (it's free)" button)
Before:
After:
=> LibWeb: Treat % max-height as none when containing block size indefinite

Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibCore/MimeData.h, Userland/Services/LaunchServer/Launcher.cpp, Userland/Services/LaunchServer/Launcher.h, Userland/Utilities/file.cpp
This is just #17266 rebased on `master`. It was blocked at the time, but the issue was resolved by f31bd190b0f746a8e304a4eeb79ce9c002e656d0
=> Remove uses of DeprecatedString in file utility. (Attempt 2)

Tests/LibWeb/Layout/expected/img-with-percentage-max-width-and-indefinite-containing-block-width.txt, Tests/LibWeb/Layout/input/img-with-percentage-max-width-and-indefinite-containing-block-width.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
This is technically "undefined behavior" per CSS 2.2, but it seems sensible to mirror the behavior of max-height in the same situation. It also appears to match how other engines behave.
Fixes #19242
=> LibWeb: Treat % max-width as none when containing block size indefinite

Userland/Libraries/LibWeb/SVG/AttributeParser.cpp
This now allows `v 1 2 3` or `h 1 2 3`, which are treated like `v 1 v 2 v 3` and `h 1 h 2 h 3` respectively. This fixes the freeCodeCamp SVG logo.
| Before                                                                                                                              | After                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot from 2023-06-14 21-30-22](https://github.com/SerenityOS/serenity/assets/11597044/5049812d-403a-479 …
=> LibWeb: Support SVG vertical/horizontal lineto with multiple parameters

Userland/Applications/Browser/StorageWidget.cpp, Userland/Applications/Browser/Tab.cpp, Userland/Libraries/LibGUI/Clipboard.cpp, Userland/Libraries/LibLine/Editor.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp, Userland/Services/WindowServer/WindowManager.cpp
This is similar to #19298 in that we remove another bunch of unnecessary copies.
Unnecessary copies mean unnecessary memory consumption, running time, and risk of OOM. So let's do fewer of those.
=> Userland: Avoid even more unnecessary copies

Userland/Libraries/LibGUI/Action.h, Userland/Libraries/LibIDL/IDLParser.cpp, Userland/Libraries/LibJS/MarkupGenerator.cpp, Userland/Libraries/LibJS/MarkupGenerator.h, Userland/Libraries/LibWeb/DOM/Node.cpp
This PR, removes some places where copy-construct and copy-assign is unnecessary, and probably even unintentional.
My long-term quest is to make HashTable/HashMap OOM-safe, by removing infallible copy-construct and copy-assign. (`HashMap::clone` already exists, `HashTable::clone` comes in a future PR.) For this, I want to reduce the callers to copy-construct and copy-assign.
For example, printing cyclic or redundant values in the Browser JS Console. Before:
After:
=> Userland: Avoid some unnecessary copies, repair cycle detection in LibJS value printing

Tests/LibWeb/Layout/expected/div_align.txt, Tests/LibWeb/Layout/expected/div_align_nested.txt, Tests/LibWeb/Layout/input/div_align.html, Tests/LibWeb/Layout/input/div_align_nested.html, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Identifiers.json, Userland/Libraries/LibWeb/HTML/HTMLDivElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLDivElement.h, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
This PR improves layout correctness for websites that use the align attribute on divs.
The result of the test in `div_align.html`:
| Before | After | Reference (Firefox) |
| ---------- | ------- | --------------------------- |
|![before](https://github.com/SerenityOS/serenity/assets/15140758/0775622a-e116-4d6f-bf50-a49b3d6a3bef) | ![after](https://github.com/SerenityOS/serenity/assets/15140758/c9017e98-bc3c-42ae-8e42-80dcd17af8fb) | ![firefox_reference](https://github.com/SerenityOS/serenity/assets/15140758/fde40d78-aa13-42dd-8565-8d1f72eee63b) |
=> LibWeb: Implement the align attribute for divs

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
This gets rid of a couple of FIXMEs in Properties.json :^)
Also, resolve the fill and stroke properties so I could more easily check that they're working.
=> LibWeb: Add parsing for CSS <paint> values

Base/usr/share/man/man1/pkill.md, Userland/Utilities/pkill.cpp
This PR adds the following options to `pkill`:
* `-n`: Select the newest matching process.
* `-o`: Select the oldest matching process.
* `-O`: Select processes older than the given number of seconds.
Signals can now also be specified by name as well as number (e.g: `-sKILL` or `-sSIGKILL`, as well as `-s9`)
I also fixed a silly issue where I didn't initialize the `display_number_of_matches` variable. Causing the option to always be enabled :man_facepalming:.
Example:
https://github.com/SerenityOS/serenity/assets/2817754/a658b754-4e61-415b-aaab-f58f36862cbb
=> pkill: Add -n, -o and -O options to filter processes by age

Userland/Libraries/LibGUI/TextDocument.cpp
I've been playing with TextEditor and writing some C code recently in SerenityOS :^)
This PR fixes what #18605 (by me) left off and sorry for the misses.
The bug in short:
If the previous content before the cursor is `[Punctuation|Seperator]+` (in regular expression),
`<Ctrl-Backspace>` will cause a crash or stuck. 
For instance, `##!`, `#!#` and `!@#` are possible combinations.
=> LibGUI: Fix more crashes/stucks on deleting word backward

Ladybird/AudioCodecPluginLadybird.cpp, Ladybird/AudioCodecPluginLadybird.h, Userland/Libraries/LibWeb/HTML/AudioTrack.cpp, Userland/Libraries/LibWeb/HTML/AudioTrack.h, Userland/Libraries/LibWeb/HTML/HTMLAudioElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLAudioElement.h, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl, Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp, Userland/Libraries/LibWeb/Painting/MediaPaintable.h, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h, Userland/Services/WebContent/AudioCodecPluginSerenity.cpp, Userland/Services/WebContent/AudioCodecPluginSerenity.h
https://github.com/SerenityOS/serenity/assets/5600524/a34eb5b5-68c3-40d5-b578-160b61f00a06
And how it looks on video elements, which will typically have more width:
=> LibWeb: Implement and add controls for the HTMLMediaElement volume and muted IDL attributes

Tests/LibWeb/Layout/expected/img-with-percentage-max-width-and-indefinite-containing-block-width.txt, Tests/LibWeb/Layout/expected/img-with-percentage-max-width-and-min-content-containing-block-width.txt, Tests/LibWeb/Layout/input/img-with-percentage-max-width-and-indefinite-containing-block-width.html, Tests/LibWeb/Layout/input/img-with-percentage-max-width-and-min-content-containing-block-width.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
When resolving a percentage `min-width` or `min-height` size against a containing block currently under a `min-content` constraint, we should act as if the containing block has zero size in that axis.
Visual progression on https://null.com/
Before:
After:
=> LibWeb: Resolve % min-sizes against 0 while under min-content constraint

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Previously, using an identifier color like `currentColor` would fail to parse, since we look at ident tokens (and reject unrecognised ones) before trying to parse colors.
This fixes GitHub's SVG icons, which use `fill: currentColor;` a lot.
=> LibWeb: Parse identifiers last in `parse_paint_value()`

Userland/Libraries/LibWeb/CSS/Default.css
I went through chapter 15 of the spec and updated the corresponding CSS for all sections where changes were made and removed the rules that were accidentally duplicated for 15.3.8.
After browsing around for a bit I didn't spot any obvious rendering regressions and all tests still pass but it's not impossible that something will break.
=> LibWeb/CSS: Update Default.css from the HTML specification

Userland/Libraries/LibXML/Parser/Parser.cpp
This fixes parsing for example https://wpt.live/css/reference/ref-filled-green-100px-square.xht
=> LibXML: Fix parser not leaving self-closing tags

Userland/Libraries/LibCompress/Gzip.cpp, Userland/Libraries/LibCompress/Gzip.h, Userland/Utilities/file.cpp
=> LibCompress/Gzip: Replace usage of DeprecatedString

Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Now that we support audio, we can start correctly reporting we support certain audio mime types!
Required by certain sites like Gartic Phone, which fails to load audio because we didn't return a non-empty string for `audio/mpeg`:
```
"https://garticphone.com/sounds/turnundefined", Error: Load failed: 404
```
```js
(new Audio).canPlayType("audio/mpeg") && (this._extension = ".mp3"),
```
=> LibWeb: Add audio mime types to HTMLMediaElement.canPlayType

Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
(Note that GitHub mutes videos by default)
https://github.com/SerenityOS/serenity/assets/25595356/07966d5e-1e44-416b-955f-5cb630ce03b9
=> LibWeb: Create an audio document for `audio/` MIME types on navigation

Ladybird/BrowserWindow.cpp, Ladybird/BrowserWindow.h, Ladybird/ConsoleWidget.cpp, Ladybird/Tab.cpp, Ladybird/Tab.h, Ladybird/WebContent/main.cpp, Ladybird/WebContentView.cpp, Ladybird/WebContentView.h, Ladybird/main.cpp, Tests/LibJS/test-bytecode-js.cpp, Tests/LibJS/test262-runner.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp, Userland/Libraries/LibWebView/OutOfProcessWebView.cpp, Userland/Libraries/LibWebView/OutOfProcessWebView.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Utilities/headless-browser.cpp
This required quite a bit of plumbing, but now you can run
ladybird --use-bytecode
=> Ladybird+LibJS: Add CLI option to run browser with LibJS bytecode VM

AK/SourceGenerator.h, Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp, Meta/Lagom/Tools/CodeGenerators/LibGL/GenerateGLAPIWrapper.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEnums.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMediaFeatureID.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSTransformFunctions.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSValueID.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GeneratorUtil.h, Meta/Lagom/Tools/CodeGenerators/StateMachineGenerator/main.cpp, Tests/AK/TestSourceGenerator.cpp
This only fully migrates the CSS code generators because they're the ones I'm familiar with, and CLion's code comprehension is currently refusing to work on `Meta/Lagom` code files for some reason, so it's a bit unpleasant to work on. :upside_down_face:
You would not believe how many TRYs you can fit in this bad boy!
=> AK+CodeGenerators: Migrate to String and propagate errors

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Tests/syntax/new-with-optional-chaining.js
=> LibJS: Correctly handle parentheses and `new Object`

Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp
```
Summary:
Diff Tests:
+24 ✅   +8 ❌    -32 📝   
Diff Tests:
test/intl402/DateTimeFormat/prototype/format/temporal-objects-resolved-time-zone.js                📝 -> ❌
test/intl402/DateTimeFormat/prototype/format/timedatestyle-en.js                                   📝 -> ✅
test/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-resolved-time-zone.js           📝 -> ❌
test/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-resolved-time-zone.js    📝 -> ❌
test/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-resolved-time-zone.js         📝 -> ❌
test/language/expressions/optional-chaining/call-expression.js                                     📝 -> ✅
test/language/expressions/optional-chaining/eval-optional-call.js                                  📝 …
```
=> LibJS/Bytecode: Implement optional chaining + fix a silly super computed property bug

Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-percentage-height-resolved-against-padding-box-of-containing-block.txt, Tests/LibWeb/Layout/input/block-and-inline/abspos-with-percentage-height-resolved-against-padding-box-of-containing-block.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Absolutely positioned elements should have their percentage sizes resolved against the padding box of the containing block, not the content box.
From CSS-POSITION-3 <https://www.w3.org/TR/css-position-3/#def-cb>
"..the containing block is formed by the padding edge of the ancestor.."
=> LibWeb: Use correct reference for abspos elements with % height sizes

Userland/Applications/HexEditor/HexEditorWidget.cpp, Userland/Applications/SpaceAnalyzer/main.cpp, Userland/Applications/ThemeEditor/CMakeLists.txt, Userland/Applications/ThemeEditor/MainWidget.cpp, Userland/Applications/ThemeEditor/MainWidget.h, Userland/Applications/ThemeEditor/ThemeEditor.gml, Userland/Applications/ThemeEditor/main.cpp, Userland/DevTools/GMLPlayground/GMLPlaygroundWindow.gml, Userland/DevTools/GMLPlayground/MainWidget.cpp, Userland/DevTools/GMLPlayground/MainWidget.h, Userland/Games/GameOfLife/main.cpp, Userland/Games/MasterWord/main.cpp, Userland/Games/Snake/main.cpp, Userland/Libraries/LibGUI/Application.cpp
- Show "Open /path/to/file" as the status bar tip for recent-file actions.
- Add Statusbars to GMLPlayground and ThemEditor.
- Show recent files in ThemeEditor.
- Show status tips in the Statusbar for... lots of things that had Statusbars.
=> LibGUI+Userland: Give more apps Statusbars, and make Statusbar usage better

AK/URL.cpp, AK/URL.h, Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp, Userland/Libraries/LibWeb/WebSockets/WebSocket.h, Userland/Libraries/LibWeb/WebSockets/WebSocket.idl
For convenience wire up a to_string() method which returns a new String.
=> AK+LibWeb: Migrate WebSockets::WebSocket to String

Base/res/html/misc/svg-gradients.html, Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.cpp
The translation to the bounding box location is handled by the gradient transform, also doing it here breaks things.
This fixes the MDN `<radialGradient>` example.
**Before**
**After**
=> LibWeb: Fix end position for objectBoundingBox SVG <radialGradient>s

Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
In compute_table_box_width_inside_table_wrapper, we should only consider available_width when it's valid. Values which come from {min, max}-content constraints aren't meaningful and shouldn't be considered for the cap.
=> LibWeb: Don't cap used width by available width from a constraint

Userland/Libraries/LibWeb/Bindings/ExceptionOrUtils.h, Userland/Libraries/LibWeb/Fetch/FetchMethod.cpp, Userland/Libraries/LibWeb/FileAPI/Blob.cpp, Userland/Libraries/LibWeb/FileAPI/Blob.h, Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp, Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
After adding ReadableStreamDefaultReader::read_all_bytes, all of the
pieces are in place to implement these functions to spec!
=> LibWeb: Implement Blob::text and Blob::array_buffer to spec

AK/BufferedStream.h, AK/CircularBuffer.h, AK/Noncopyable.h, AK/SourceGenerator.h, Kernel/Library/KBufferBuilder.h, Tests/AK/TestQuickSort.cpp, Tests/AK/TestTuple.cpp, Tests/AK/TestVariant.cpp, Userland/Libraries/LibCore/SecretString.h, Userland/Libraries/LibCore/System.h, Userland/Libraries/LibCore/ThreadEventQueue.cpp, Userland/Libraries/LibDSP/Music.h, Userland/Libraries/LibSQL/Result.h, Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.h, Userland/Utilities/sed.cpp
There were a couple of incomplete or manually-written default (re-)implementations of move-constructors and move-assigns. This PR fixes them, and offers a new macro `AK_MAKE_DEFAULT_MOVABLE` that solves this problem.
I found these instances by looking for `AK_MAKE_NON*`, and taking a close look at all classes that use `NONCOPYABLE` but not `NONMOVABLE`. A bunch of classes has a good reason to use non-default move-semantics, and I left these alone. If in doubt, I didn't change anything. In particular, I only touched classes where move-semantics were already mentioned in some form, *and* `NONCOPYABLE` is used. (I don't see a point in touching the countless cases where we have perfectly fine default move-semantics like e.g. in InputBufferedSeekable.)
Let me know if you wish the commits to be …
=> AK+Everywhere: Introduce AK_MAKE_DEFAULT_MOVABLE to simplify default-move implementations

Tests/LibWeb/Layout/expected/misc/grid-template-block-components-whitespace-crash.txt, Tests/LibWeb/Layout/input/misc/grid-template-block-components-whitespace-crash.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
We're already handling whitespace between components, do the same for leading whitespace. Fixes crash on https://distill.pub/2021/gnn-intro.
=> LibWeb: Handle leading whitespace in grid-template-* block components

AK/URLParser.cpp, Tests/AK/TestURL.cpp
The added test case illustrates the issue pretty well. Basically, before this fix, all assets that had a relative URL in a document loaded from a `file://` failed to load.
=> AK+Browser+Ladybird: Fix relative file URL completion

Tests/LibWeb/Layout/expected/block-and-inline/percentage-min-height-with-containing-block-padding.txt, Tests/LibWeb/Layout/expected/block-and-inline/percentage-min-height.txt, Tests/LibWeb/Layout/input/block-and-inline/percentage-min-height-with-containing-block-padding.html, Tests/LibWeb/Layout/input/block-and-inline/percentage-min-height.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
From CSS-POSITION-3 <https://www.w3.org/TR/css-position-3/#def-cb>
"..the containing block is formed by the padding edge of the ancestor.."
Fixes crash on Acid2 test.
=> LibWeb: Use padding box of containing block to resolve % height size

Base/res/html/misc/canvas-global-alpha.html, Base/res/html/misc/welcome.html, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibWeb/HTML/Canvas/CanvasCompositing.h, Userland/Libraries/LibWeb/HTML/Canvas/CanvasCompositing.idl, Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
This resurrects #18924 and fixes up the changes so `globalAlpha` works for images, gradients, and patterns too.
=> LibWeb: Add initial implementation of CRC2D.globalAlpha

Ports/gettext/package.sh
`ftpmirror.gnu.org` does not seem to have the `/pub/gnu` folder structure, all files are in `/gnu` instead.
This regressed in 41f7f821f6bc2380e7b4d2db5ee5a8737aea1281.
=> Ports: Point to the correct subdirectory for `gettext`

Tests/LibWeb/Layout/expected/table/multi-line-cell.txt, Tests/LibWeb/Layout/input/table/multi-line-cell.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
With multi-line text cells, we don't reliably know the height would stay the same as the one set by the independent format context run. In such situations, we can end up with a table box which is sized inconsistently with the grid boxes of the table due to differences in line breaks.
=> LibWeb: Skip separate height computation for tables

Userland/Libraries/LibTextCodec/Decoder.cpp, Userland/Libraries/LibTextCodec/Decoder.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.h, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h, Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp, Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.h, Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h, Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h, Userland/Libraries/LibWeb/HTML/HTMLButtonElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLButtonElement.h, Userland/Libraries/LibWeb/HTML/HTMLElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLElement.h, Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLFormElement.h, Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl, Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp, Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.h, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
This fixes several things, such as:
- Don't include none submitter buttons
- Use type_state() instead type() to avoid direct string comparisons
- Support the hidden _charset_ input
- Get form associated element's value directly instead of via the value attribute
- Split line break normalization into a separate function so that it can also be used by form submission.
- Support multipart/form-data and and text/plain in form submission
- Support ftp, javascript, data and mailto schemes
- Support targeting form submission to a specific browsing context/navigable (unfortunately improves Facebook tracking, which submits to the tracker in a hidden iframe via HTMLFormElement.target and submit())
- Support no opener for form submission
- Support setting the method, action, encoding type and target …
=> LibWeb: Bring form submission more up to spec

Userland/Applications/Browser/DownloadWidget.cpp, Userland/Applications/Browser/DownloadWidget.h, Userland/Libraries/LibCore/NetworkJob.cpp, Userland/Libraries/LibCore/NetworkJob.h, Userland/Libraries/LibHTTP/Job.cpp, Userland/Libraries/LibHTTP/Job.h, Userland/Libraries/LibProtocol/Request.cpp, Userland/Libraries/LibProtocol/Request.h, Userland/Libraries/LibProtocol/RequestClient.cpp, Userland/Libraries/LibProtocol/RequestClient.h, Userland/Libraries/LibWeb/Loader/ResourceLoader.h, Userland/Libraries/LibWebView/RequestServerAdapter.cpp, Userland/Services/RequestServer/GeminiRequest.cpp, Userland/Services/RequestServer/HttpCommon.h, Userland/Services/RequestServer/Request.cpp, Userland/Services/RequestServer/Request.h, Userland/Services/RequestServer/RequestClient.ipc, Userland/Utilities/pro.cpp
This PR changes the variables used to represent the size and progress of downloads from `u32` to `u64`. This allows `pro` and `Browser` to report the total size and progress of a download correctly for downloads larger than 4GiB.
I haven't been able to test a download larger than 4GiB in the Browser, as the download fails before completion. I believe the reasons for this are unrelated to this PR, as this also happens on `master`. I have verified that the Browser's progress bar shows the correct value, whereas previously it always showed 0% for downloads >4GiB.
Before (this 5GiB download has completed; the number shown overflowed at 4GiB):
After:
=> Browser+pro: Correctly report progress of downloads larger than 4GiB

Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
There was a TODO questioning whether breaking on >4bpp images was the correct behaviour when RLE4 was detected. There is no indication in the spec that RLE4 can be used with anything >4bpp, so I believe this doesn't require additional follow-up.
MS Spec:
https://learn.microsoft.com/en-us/windows/win32/gdi/bitmap-compression
=> LibGfx: Remove unneeded TODO in BMPLoader

Userland/Utilities/ping.cpp
This PR fixes 2 issues with `ping`:
* Intervals specified with the `-i` option no longer overflow if they are larger than 4294 seconds (it turns out `useconds_t` is `u32` not `u64`, oops...)
* We no longer wait for an extra interval before displaying the closing statistics and exiting.
Before:
After:
=> ping: Avoid potential interval overflow and don't wait before exiting

Tests/LibWeb/Layout/expected/table/table-formation-with-rowspan-in-the-middle.txt, Tests/LibWeb/Layout/input/table/table-formation-with-rowspan-in-the-middle.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
The algorithm which finds the first free slot must run for every cell, not for every row.
=> LibWeb: Fix empty slot finding in table formation algorithm

Tests/LibWeb/Layout/expected/table/clip-spans-to-table-end.txt, Tests/LibWeb/Layout/input/table/clip-spans-to-table-end.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
This occurs on Wikipedia for tournament brackets, for example: https://en.wikipedia.org/wiki/2022%E2%80%9323_UEFA_Champions_League_knockout_phase
=> LibWeb: Clip cell spans past the end of the table

Kernel/Net/TCPSocket.cpp, Kernel/Net/TCPSocket.h
During receive_tcp_packet(), we now set m_send_window_size for the socket if it is different from the default.
This removes one FIXME from TCPSocket.h.
=> Kernel/TCPSocket: Read window size from peer

Meta/Lagom/BuildFuzzers.sh
This was overlooked in 71b184a, which broke the oss-fuzz configuration.
=> Fuzzers: Update the path to fuzzer binaries

Userland/Libraries/LibWeb/WebDriver/Client.cpp
Fixes the bug that currently we don't ever close webdriver client connection socket when header "Connection: keep-alive" is specified.
This allows to run more WPT tests without running out of free file descriptors :)
=> LibWeb/WebDriver: Close client connection socket when EOF is reached

Ladybird/Tab.cpp, Userland/Applications/Browser/IconBag.cpp, Userland/Applications/Browser/IconBag.h, Userland/Applications/Browser/Tab.cpp, Userland/Libraries/LibCore/MimeData.cpp
After commit 7ec7015750a8760c124cba0b4c759f4b08078390, we can open audio documents directly. This adds
content menu items to do so, similar to images and videos.
=> Ladybird: Add context menu items to directly open audio files

Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp, Userland/Libraries/LibJS/Runtime/ArrayBuffer.h, Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
Currently we do not support Shared Data Block so that part is not yet implemented.
=> LibJS: Partially implement AO CopyDataBlockBytes

Userland/Applications/Browser/DownloadWidget.cpp
This fixes a typo from #19462.
:man_facepalming:
=> Browser: Set DownloadWidget progress bar minimum value correctly

Tests/LibWeb/Layout/expected/flex/inline-flex-with-main-axis-margin-on-flex-container.txt, Tests/LibWeb/Layout/input/flex/inline-flex-with-main-axis-margin-on-flex-container.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
The part in FFC where we ask the parent formatting context to size the flex container midway through layout is really weird, but let's at least be consistently weird for BFC and IFC. Since IFC always works within its parent BFC, it can simply forward these requests to the BFC.
This fixes an issue where inline-flex containers incorrectly had main axis margins subtracted from their content size.
Visual progression on https://www.ohne-makler.net/
Before:
After:
=> LibWeb: Allow IFC to size inline-flex boxes midway through flex layout

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
If we use a rounded rect we'll clip off subpixels around the edge.
Fixes this icon on GitHub (at certain window sizes):
=> LibWeb: Use enclosing (rather than rounded) rect for overflow clipping

AK/Function.h, Kernel/CMakeLists.txt, Userland/Libraries/LibJS/Heap/HeapBlock.h
Previously `AK::Function` and `LibJS` were using `alignof(BaseClass)` to align inline storage areas, this would always resolve to 8-bytes regardless of which subclass ended up being stored. This does not fix any issues now, it is possible to break these assumptions (e.g. you could capture by value a `long double` in a `AK::Function`). 
(This is just something that looked fishy to me while perusing AK :smile:)
=> AK+LibJS+Kernel: Fix some (technically) incorrect alignment assumptions 

Base/usr/share/man/man1/rmdir.md, Userland/Utilities/rmdir.cpp
This PR adds the following options to `rmdir`:
* `-p`: Remove all directories in each given path. e.g: `rmdir -p foo/bar/baz/` would remove `foo/bar/baz/`, `foo/bar/` and `foo/`
* `-v`: Print a message before removing each directory
Example usage:
=> rmdir: Add `-p` to remove parent directories and `-v` to be verbose

Meta/lint-ports.py
This reduces the runtime of `lint-ports` from 72s down to 0.5s on my computer (a reduction of ~99.2%)! While it may not be as accurate as running `package.sh showproperty` it makes using `precommit` while editing ports much nicer!
=> Meta: Speed up `lint-ports` by ~99.2%

Userland/Utilities/CMakeLists.txt, Userland/Utilities/pixelflut.cpp
Pixelflut is a dead-simple TCP-based protocol for setting pixels on a server's canvas, and that canvas is shared between all clients. It's a <https://justforfunnoreally.dev> hacker battling ground.
This basic SerenityOS CLI client sends an image to the server in a loop, pixels are sent ordered and unthreaded. It is currently smart enough to resize the image to fit the canvas, but it doesn't (yet) provide manual positioning and rescaling functionality.
Here's a screenshot of the client running against [pixelpwner-server](https://github.com/timvisee/pixelpwnr-server/), where the banner takes ~6s to appear fully and the client manages to push out a maximum of 1.3 Mb/s, about 1% of the network bandwidth of VM host to server.
An interesting "real" use case of this application is end-to-end …
=> Utilities: Add pixelflut, a Pixelflut protocol client 

Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Always use `would_be_fully_clipped_by_painter` to check painting can be avoided.
This allows to quickly find all the places where this check happens and also removes incosistency that before we checked for intersection with viewport rect in some places and for intersection with painter clip rect in other places.
=> LibWeb: Use PaintContext::would_be_fully_clipped_by_painter() everywhere

Tests/LibWeb/Layout/expected/table/border-spacing-colspan.txt, Tests/LibWeb/Layout/expected/table/clip-spans-to-table-end.txt, Tests/LibWeb/Layout/expected/table/colspan-weighted-width-distribution.txt, Tests/LibWeb/Layout/expected/table/colspan-width-distribution.txt, Tests/LibWeb/Layout/input/table/colspan-weighted-width-distribution.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Compute the contributions to a spanning cell width from each cell in the span. This better handles uneven column widths, since each cell contribution is proportional with its own width as opposed to the own width of the first cell in the span.
This better matches the behavior of other browsers and further aligns with the specification.
=> LibWeb: Improve span column width distribution

Tests/LibWeb/Layout/expected/svg/svg-as-image-implicit-viewbox.txt, Tests/LibWeb/Layout/expected/svg/svg-as-image.txt, Tests/LibWeb/Layout/input/svg/svg-as-image-implicit-viewbox.html, Tests/LibWeb/Layout/input/svg/svg-without-viewbox.svg, Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp, Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp, Userland/Libraries/LibWeb/SVG/SVGSVGElement.h, Userland/Utilities/headless-browser.cpp
On the wild web, there are many SVG files with `width` and `height` on the `svg` element, but no `viewBox`.
Other browsers handle this by creating an implicit `viewBox="0 0 width height"`, so this PR makes us do the same thing.
I also had to fix an issue with the test runner in order to make a test. :^)
Visual progression on https://www.ohne-makler.net (and countless other websites)
Before:
After:
=> LibWeb: Infer SVG viewBox from width & height if viewBox attribute is absent

Userland/Libraries/LibWeb/SVG/AttributeNames.h, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
This is simply converted to an equivalent CSS `opacity` property value.
Note the icons in the screenshots below:
Before:
After:
=> LibWeb: Honor the `opacity` attribute on SVG graphics elements

Tests/LibWeb/Layout/expected/flex/align-self-end-crash.txt, Tests/LibWeb/Layout/input/flex/align-self-end-crash.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
We were missing the code to convert this to `align-items: end`.
Fixes an assertion failure when resizing the window on https://www.kde.org/
=> LibWeb: Don't assert when flex-item has `align-self: end`

Tests/LibWeb/Layout/expected/abspos-flex-container-with-auto-height.txt, Tests/LibWeb/Layout/input/abspos-flex-container-with-auto-height.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h
While CSS 2.2 does tell us to use the "auto height for BFC roots"
calculation when resolving auto heights for abspos elements, that
doesn't make sense for other formatting context roots, e.g flex.
In lieu of implementing the entire new absolute positioning model from
CSS-POSITION-3, this patch borrows one small nugget from it: using
fit-content height as the auto height for non-BFC-root abspos elements.
Fixes the cookie popup on https://www.ohne-makler.net/
Before:
After:
=> LibWeb: Don't use BFC automatic height algorithm for abspos elements that don't form a BFC

Userland/Libraries/LibWeb/CSS/CSSFontFaceRule.cpp
- The check for `local()` sources wasn't working, and output `local()` every time. Since we don't parse `local()` yet, let's just always output a regular URL source.
- Put a space between the URL and the `format()`.
- Stop double-quoting the format string.
=> LibWeb: Fix serialization of CSSFontFaceRule

Tests/LibWeb/Layout/expected/table/inline-table-width.txt, Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
The shortcut we put in place didn't resolve percentage widths and ignored border spacing. We can still return early after we compute the width per the specifications.
=> LibWeb: Don't skip width computation for intrinsic table width

Tests/LibWeb/Layout/expected/svg/svg-with-zero-intrinsic-size-and-no-viewbox.txt, Tests/LibWeb/Layout/input/svg/svg-with-zero-intrinsic-size-and-no-viewbox.html, Tests/LibWeb/Layout/input/svg/svg-with-zero-intrinsic-size-and-no-viewbox.svg, Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp
The fix here has two parts:
1. Don't use the fallback viewBox at all if we're not in SVG-as-image.
2. Don't make a fallback viewBox with zero width and/or height.
This fixes a crash on Bandcamp pages. Thanks Tim Flynn for reporting!
=> LibWeb: Don't infer SVG viewBox if width and/or height is zero

Tests/LibWeb/Layout/expected/floating-non-replaced-element-percentage-padding-against-indefinite-width.txt, Tests/LibWeb/Layout/expected/floating-replaced-element-percentage-padding-against-indefinite-width.txt, Tests/LibWeb/Layout/expected/non-floating-non-replaced-element-percentage-padding-against-indefinite-width.txt, Tests/LibWeb/Layout/input/floating-non-replaced-element-percentage-padding-against-indefinite-width.html, Tests/LibWeb/Layout/input/floating-replaced-element-percentage-padding-against-indefinite-width.html, Tests/LibWeb/Layout/input/non-floating-non-replaced-element-percentage-padding-against-indefinite-width.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
In particular, in BFC:
- Non-floating, non-replaced elements
- Floating, non-replaced elements
- Floating, replaced elements
The first two regressed in https://github.com/SerenityOS/serenity/commit/1d76126abe9dd65251bd28a381350f70083b50f7
The third one seems to have been introduced by this regression, as it was seemingly copied from compute_width_for_floating_box in https://github.com/SerenityOS/serenity/commit/7f9ede07bcf287a2b16ff29c1ebbcf64c47a221f
=> LibWeb: Resolve padding against 0 and not inf for indefinite width more

Ladybird/AudioCodecPluginLadybird.cpp, Ladybird/AudioCodecPluginLadybird.h, Ladybird/WebContent/main.cpp, Meta/check-style.py, Userland/Libraries/LibWeb/HTML/AudioTrack.cpp, Userland/Libraries/LibWeb/HTML/AudioTrack.h, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.cpp, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h, Userland/Services/WebContent/AudioCodecPluginSerenity.cpp, Userland/Services/WebContent/AudioCodecPluginSerenity.h, Userland/Services/WebContent/main.cpp
The main thread in the WebContent process is often busy with layout and running JavaScript. This can cause audio to sound jittery and crack. To avoid this behavior, we now drive audio on a secondary thread.
Note: Browser on Serenity uses AudioServer, the connection for which is already handled on a secondary thread within LibAudio. So this only applies to Lagom.
Rather than using LibThreading, our hands are tied to QThread for now. Internally, the Qt media objects use a QTimer, which is forbidden from running on a thread that is not a QThread (the debug console is spammed with messages pointing this out). Ideally, in the future AudioServer will be able to run for non-Serenity platforms, and most of this can be aligned with the Serenity implementation.
Here's what bandcamp (which does …
=> Ladybird+LibWeb+WebConent: Drive audio in Ladybird off the main thread

Tests/LibWeb/Layout/expected/grid/minmax-with-max-function-inside.txt, Tests/LibWeb/Layout/input/grid/minmax-with-max-function-inside.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Makes grid size parser to handle not only calc() but min(), max() and other CSS functions we support.
=> LibWeb: Support CSS functions other than calc() for grid sizes

Tests/LibWeb/Layout/expected/css-pseudo-element-should-not-be-affected-by-presentational-hints.txt, Tests/LibWeb/Layout/expected/table/border-spacing-with-percentage-width.txt, Tests/LibWeb/Layout/expected/table/columns-width-distribution-1.txt, Tests/LibWeb/Layout/expected/table/long-caption-increases-width.txt, Tests/LibWeb/Layout/expected/table/table-width.txt, Tests/LibWeb/Layout/input/table/border-spacing-with-percentage-width.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Adding undistributable space right before setting the content width is incorrect when it's a percentage. Follow the specification and add it to GRIDMIN and GRIDMAX instead.
=> LibWeb: Add undistributable space to GRID{MIN, MAX} instead of content

Userland/Services/WebServer/main.cpp
Specifying port 0 on the command line causes WebServer to select a random available port. We now show the port WebServer is actually using rather than assuming it is the same as the command line argument.
Example:
https://github.com/SerenityOS/serenity/assets/2817754/4dc2edef-aba3-4ede-b071-54c3e4173711
=> WebServer: Show the correct port when using port 0

Base/usr/share/man/man8/groupadd.md, Userland/Utilities/groupadd.cpp
This PR adds the `-U` option, which allows the user to specify a comma-separated list of usernames; these are used as the initial members of the new group.
Example usage:
=> groupadd: Add `-U` option for adding members to a new group

Meta/serenity.sh
GCC's build fails in `libisl`'s configure step if `CC` is set to Homebrew Clang with the message "Link Time Optimisation is not supported". This is likely due to the fact that it tries to use ranlib from Xcode, which is not compatible with the newer LLVM version's bitcode format.
The toolchain build runs after `pick_host_compiler` is called, which selects Homebrew Clang if the installed Xcode version is too old. We need to unset `CC` and `CXX` for the toolchain build to sidestep the issue.
=> Meta: Always use the default host compiler for the toolchain on macOS

Userland/Utilities/sed.cpp
`FileSystem::absolute_path()` does `stat` the file, this commit runs all `absolute_path` calls before touching the veil to make sure this works as intended.
Closes  #19364
=> sed: Fix `unveil` error for every run

Tests/LibWeb/Layout/expected/svg/svg-as-image-invalid.txt, Tests/LibWeb/Layout/input/svg/svg-as-image-invalid.html, Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Return error when input svg is not valid and SVGSVGElement is not present in the tree instead of doing svg_root nullptr dereference.
Fixes crash on https://apps.kde.org/en-gb/
=> LibWeb: Do not crash inside SVGDecodedImageData on invalid SVG input

Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Instead of a custom struct, use an AK::Variant for flex-basis. A flex-basis is either `content` or a CSS size value, so we don't need anything custom for that.
By using a CSS size, we also avoid having to convert in and out of size in various places, simplifying the code.
This finally gets rid of the "Unsupported main size for flex-basis" debug spam. :^)
=> LibWeb: Modernize handling of the CSS flex-basis property

Kernel/Devices/HID/KeyboardDevice.cpp
This resurrects #19069. I was about to fix this before I noticed someone else already did it! 
I've taken the commit from @hojelse and reformatted the commit message.
Fixes #19034
=> Kernel: Fix panic when switching to out-of-bounds console

Userland/Utilities/pro.cpp
The `report_time_in_ms` and `speed_update_time_in_ms` variables
weren't previously being respected. This was causing the progress
display to update too frequently, making it difficult to read.
The download speed reporting interval has also been reduced from 4000ms to 1000ms.
NB: The downloads in the videos below are a bit stuttery. This is caused by socket receive buffer filling up, writing the output to `/tmp` makes this issue slightly less apparent, but it definitely needs further investigation.
Before:
https://github.com/SerenityOS/serenity/assets/2817754/fe092d8e-1ac8-4111-9ef8-862e6b31e32b
After:
https://github.com/SerenityOS/serenity/assets/2817754/40ed04f5-08b8-4e3f-ae05-94f3065cc86a
=> pro: Ensure that progress reporting intervals are respected

Tests/LibWeb/Layout/expected/grid/grow-beyond-limits.txt, Tests/LibWeb/Layout/input/grid/grow-beyond-limits.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Implements "Distribute space beyond limits" step from: https://www.w3.org/TR/css-grid-2/#distribute-extra-space
=> LibWeb: Implement distributing space to tracks beyond limits in GFC

Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp, Userland/Libraries/LibWeb/Streams/AbstractOperations.h, Userland/Libraries/LibWeb/Streams/QueuingStrategy.h, Userland/Libraries/LibWeb/Streams/QueuingStrategy.idl, Userland/Libraries/LibWeb/Streams/ReadableStream.cpp, Userland/Libraries/LibWeb/Streams/ReadableStream.h, Userland/Libraries/LibWeb/Streams/WritableStream.cpp, Userland/Libraries/LibWeb/Streams/WritableStream.h, Userland/Libraries/LibWeb/Streams/WritableStream.idl
Ready now that https://github.com/SerenityOS/serenity/pull/19455 is merged!
These set of changes aim to implement the `optional QueuingStrategy strategy = {}` argument in the constructor of both ReadableStream and WritableStream - and the AO's required to implement that.
=> LibWeb: Implement QueuingStrategy for WritableStream and ReadableStream

Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
On bandcamp, this missing invocation would cause a playlist to loop one single track indefinitely.
=> LibWeb: Add missing invocation to forget a media element's tracks

Ladybird/AudioCodecPluginLadybird.cpp
For example, on https://xboygeniusx.bandcamp.com/album/the-record, a song with a duration of 03:52 would actually complete in 03:33 on my machine. This issue only affects Ladybird on Lagom; on Serenity, we already take the entire 03:52 to play the song.
=> Ladybird: Set the sample rate on the audio device's audio format

Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp, Userland/Libraries/LibWeb/Painting/MediaPaintable.h
It's a little bit of a battle to fit all of the media controls in the
available width of the media element. We currently cram everything on
one horizontal line. We've made adjustments to be able to fit it all,
but the controls (in particular the media timeline) are rather squished.
This paints the timeline above the other media controls now. This
provides much more granular control over the playback position when
scrubbing, and makes it much more likely for the timeline to render at
all.
Audio:
Video:
=> LibWeb: Paint the media timeline above the other media controls

AK/MemoryStream.cpp, AK/MemoryStream.h, Userland/Libraries/LibGfx/ImageFormats/PBMLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PGMLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PPMLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h
These two patches already reduce execution time by more than 30%.
Many low-hanging fruits remain tho
=> LibGfx/PortableFormat: Easy optimisations

Base/usr/share/man/man1/mkdir.md, Userland/Utilities/mkdir.cpp
=> mkdir: Add `-v` option to print a message for each created directory

Base/usr/share/man/man1/dirname.md, Userland/Utilities/dirname.cpp
This PR adds the following to `dirname`:
* Multiple paths can now be given. Results are separated by a newline unless `-z` is specified.
* The `-z` option separates each result with a `\0` instead of a newline (useful for things like `xargs -0`).
Example usage:
=> dirname: Add `-z` option for null terminated output and support multiple paths

AK/MaybeOwned.h
- Explicitly delete copy constructors (@nico just tripped over this)
- Simplify and optimize NonNullOwnPtr constructor
=> AK: Two small fixes to MaybeOwned

Userland/Libraries/LibWeb/DOM/Node.h, Userland/Libraries/LibWeb/SVG/SVGUseElement.h
is<SVGUseElement> quite hot in profiles
=> LibWeb: Add fast_is<T>() for SVGUseElement

Tests/LibWeb/Layout/expected/table/stretch-to-fixed-height.txt, Tests/LibWeb/Layout/input/table/stretch-to-fixed-height.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Track table grid height stretched to the specified height and use it to set the final box height in TFC.
Fixes #19563.
=> LibWeb: Take specified height into account for automatic table height

Base/usr/share/man/man1/wc.md, Userland/Utilities/wc.cpp
If more than one file is specified on the command line and the `-L` option is used, the totals field will show the longest line encountered; it is not a sum like the other values.
Example usage:
=> wc: Add `-L` option to show the length of the longest line

Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Otherwise there's a mismatch between which interpreter we use. This fixes a regression in the AST interpreter score on test262.
=> LibJS: Use bytecode for generator function default parameters

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h
This is accomplished with two new instructions:
- GetPrivateById
- PutPrivateById
test262 says:
+1616 ✅   +160 ❌   +288 💥️    -2064 📝
=> LibJS/Bytecode: Support private class fields

Tests/LibWeb/Layout/expected/table/propagate-style-update-to-wrapper.txt, Tests/LibWeb/Layout/input/table/propagate-style-update-to-wrapper.html, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Layout/Node.h, Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
On style update, we have to preserve the invariant established when we built the layout tree - some properties are applied to the table wrapper and the table box values are reset to their initial values.
This also ensures that the containing block of a table box is always a table wrapper, which isn't the case if we set absolute position on the box instead of the wrapper.
Fixes #19452.
=> LibWeb: Fix style updates for table box nodes

Tests/LibJS/test262-runner.cpp
There are hundreds of test262 tests with the following metadata line:
flags: []
Other engine runners are apparently able to ignore those lines, so we should as well.
```
Diff Tests:
+9 ✅   +249 ❌    -258 📄
```
=> LibJS: Do not fail a test if the flags list is empty

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
This makes it possible to call private member functions.
347 new passes on test262. :^)
=> LibJS/Bytecode: Emit GetPrivateById for private member expressions

Tests/LibRegex/Regex.cpp, Userland/Libraries/LibJS/Runtime/RegExpConstructor.cpp, Userland/Libraries/LibJS/Runtime/RegExpObject.cpp, Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp, Userland/Libraries/LibJS/Runtime/RegExpStringIterator.cpp, Userland/Libraries/LibJS/Runtime/RegExpStringIteratorPrototype.cpp, Userland/Libraries/LibRegex/RegexParser.cpp
Plus a crash fix:
```
Diff Tests:
test/built-ins/RegExp/prototype/unicodeSets/breaking-change-from-u-to-v-03.js 💥 -> ✅
```
=> LibJS: Update spec numbers/steps for RegExp unicode sets flag proposal

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Fixes 4 test262 tests :^)
```
Summary:
Diff Tests:
+4 ✅    -4 📝   
Diff Tests:
test/language/expressions/class/elements/grammar-private-field-optional-chaining.js 📝 -> ✅
test/language/expressions/class/elements/private-field-after-optional-chain.js      📝 -> ✅
test/language/statements/class/elements/grammar-private-field-optional-chaining.js  📝 -> ✅
test/language/statements/class/elements/private-field-after-optional-chain.js       📝 -> ✅
```
=> LibJS/Bytecode: Support private identifiers in optional chaining

Ladybird/BrowserWindow.cpp, Userland/Applications/Browser/BrowserWindow.cpp
Add shortcuts from Ladybird SerenityOS to Ladybird QT.
Also change "Enable Same Origin Policy" in Ladybird SerenityOS to "Enable Same-Origin Policy" from Ladybird QT because of consistency and because it looked better in Ladybird QT.
=> Ladybird+Browser: Make things more consistent

Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Previously, an audio loader could succeed for an HTMLVideoElement that contains a video file, which caused the duration to be set to the bogus duration of the audio loader instead of the correct duration from the video container. Instead of setting the duration based on audio always, set it to the video duration if we are creating a video element.
Before:
After:
=> LibWeb: Prioritize video duration when loading video element media

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/Runtime/VM.cpp, Userland/Libraries/LibJS/Runtime/VM.h
To reduce code duplication, I've added new `VM::execute_ast_node()` helper that handles bytecode compilation if needed.
918 new passes on test262. :^)
=> LibJS/Bytecode: Support destructuring function parameters

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp, Userland/Libraries/LibJS/Runtime/AbstractOperations.h, Userland/Libraries/LibJS/SourceTextModule.cpp
- Codegen for `ImportCall`
- Codegen for `ExportStatement`
- Actually compiling & running bytecode for `SourceTextModule`
test262 says:
`+358 ✅   +146 ❌    -194 💥️    -310 📝`
=> LibJS/Bytecode: Some work towards module support

AK/BigIntBase.h, AK/Platform.h
**AK: Prefer `__builtin_{subc,addc}` intrinsics to x86-specific ones**
GCC 14 (https://gcc.gnu.org/g:2b4e0415ad664cdb3ce87d1f7eee5ca26911a05b)
has added support for the previously Clang-specific add/subtract with
borrow builtins. Let's use `__has_builtin` to detect them instead of
assuming that only Clang has them. We should prefer these to the
x86-specific ones as architecture-independent middle-end optimizations
might deal with them better.
As an added bonus, this significantly improves codegen on AArch64
compared to the fallback implementation that uses
`__builtin_{add,sub}_overflow`.
For now, the code path with the x86-specific intrinsics stays so as to
avoid regressing the performance of builds with GCC 12 and 13.
A codegen comparison can be viewed here: …
=> AK: Prefer __builtin_{subc,addc} intrinsics to x86-specific ones  (and fix an Apple Clang miscompilation!)

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Tests/operators/delete-global-variable.js
Fixes the bug in bytecode interpreter when cached environment coordinate is not invalidated after `delete` operator usage on global `this`.
=> LibJS: Invalidate cached environment coordinate after delete in global

Userland/Libraries/LibDiff/Format.cpp, Userland/Libraries/LibDiff/Format.h, Userland/Utilities/diff.cpp, Userland/Utilities/headless-browser.cpp
Apart from reducing duplication, this should also make it easier in the future to change what the underlying representation of a hunk is.
=> diff+headless-browser+LibDiff: Extract out a common hunk normal diff print function

Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
| Before                                                                                                                              | After                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot from 2023-06-24 16-54-45](https://github.com/SerenityOS/serenity/assets/11597044/e17a5eb2-9392-4dd8-a87b-e2ea38dd7f9e) | ![Screenshot from 2023-06-24 16-54-10](https://github.com/SerenityOS/serenity/assets/11597044/135cc4e1-fdd2-4d8b-92f7-de220f …
=> LibWeb+LibGfx: Close all subpaths before filling SVG paths

Userland/Libraries/LibGUI/Window.cpp, Userland/Libraries/LibGUI/Window.h, Userland/Services/WindowServer/Compositor.cpp, Userland/Services/WindowServer/ConnectionFromClient.cpp, Userland/Services/WindowServer/ConnectionFromClient.h, Userland/Services/WindowServer/Menu.cpp, Userland/Services/WindowServer/Window.cpp, Userland/Services/WindowServer/Window.h, Userland/Services/WindowServer/WindowFrame.cpp, Userland/Services/WindowServer/WindowFrame.h, Userland/Services/WindowServer/WindowServer.ipc
I first spotted `WindowServer::Window::opacity()` and the corresponding setter while studying how `WindowServer::Compositor` works. I immediately found it a bit weird that we have special way to set that globally when we already have more fine-grained control over window opacity.
Then I found out the *only* place that actually made use of window-global opacity was... `WindowServer` itself! Specifically, the wonderfully subtle fade-out animation in `WindowServer::Menu::start_activation_animation()` that happens when you select a menu item that makes the menu disappear. You can see a demo of it in #5988 where it was added.
This was also hooked up to `LibGUI::Window::set_opacity()`, but that wasn't used anywhere.
I refactored this animation to blit the fade-out animation directly instead. …
=> WindowServer+LibGUI: Remove rendundant global opacity facilities from Window and WindowFrame

Base/home/anon/.config/SystemServer.ini, Userland/Applets/Audio/main.cpp, Userland/Libraries/LibAudio/CMakeLists.txt, Userland/Libraries/LibAudio/ConnectionToManagerServer.cpp, Userland/Libraries/LibAudio/ConnectionToManagerServer.h, Userland/Libraries/LibAudio/ConnectionToServer.cpp, Userland/Libraries/LibAudio/ConnectionToServer.h, Userland/Services/AudioServer/AudioClient.ipc, Userland/Services/AudioServer/AudioManagerClient.ipc, Userland/Services/AudioServer/AudioManagerServer.ipc, Userland/Services/AudioServer/AudioServer.ipc, Userland/Services/AudioServer/CMakeLists.txt, Userland/Services/AudioServer/ConnectionFromClient.cpp, Userland/Services/AudioServer/ConnectionFromClient.h, Userland/Services/AudioServer/ConnectionFromManagerClient.cpp, Userland/Services/AudioServer/ConnectionFromManagerClient.h, Userland/Services/AudioServer/Mixer.cpp, Userland/Services/AudioServer/Mixer.h, Userland/Services/AudioServer/main.cpp, Userland/Utilities/asctl.cpp
This is a sensible separation of concerns that mirrors the WindowServer IPC split. On the one hand, there is the "normal" audio interface, used for clients that play audio, which is the primary service of AudioServer. On the other hand, there is the management interface, which, like the WindowManager endpoint, provides higher-level control over clients and the server itself.
The reasoning for this split are manifold, as mentioned we are mirroring the WindowServer split. Another indication to the sensibility of the split is that no single audio client used the APIs of both interfaces. Also, useless audio queues are no longer created for managing clients (since those don't even exist, just like there's no window backing bitmap for window managing clients), eliminating any bugs that may …
=> AudioServer+Userland: Separate audio IPC into a "normal" client and a manager client

Meta/lint-ports.py
I don't know how often this has been a problem, but hey, it's happened once (#19595) and it's simple enough to check for it.
=> Meta: Add lint check that ports have an executable package.sh

Tests/LibWeb/Layout/expected/css-pseudo-element-should-not-be-affected-by-presentational-hints.txt, Tests/LibWeb/Layout/expected/percentage-max-height-when-containing-block-has-indefinite-height.txt, Tests/LibWeb/Layout/expected/table/align-top-and-bottom.txt, Tests/LibWeb/Layout/expected/table/border-spacing-and-borders-table-width.txt, Tests/LibWeb/Layout/expected/table/border-spacing-colspan.txt, Tests/LibWeb/Layout/expected/table/border-spacing-rowspan.txt, Tests/LibWeb/Layout/expected/table/border-spacing.txt, Tests/LibWeb/Layout/expected/table/borders.txt, Tests/LibWeb/Layout/expected/table/colspan-weighted-width-distribution.txt, Tests/LibWeb/Layout/expected/table/colspan-width-distribution.txt, Tests/LibWeb/Layout/expected/table/columns-width-distribution-1.txt, Tests/LibWeb/Layout/expected/table/long-caption-increases-width.txt, Tests/LibWeb/Layout/expected/table/multi-line-cell.txt, Tests/LibWeb/Layout/expected/table/nested-table-box-width.txt, Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt, Tests/LibWeb/Layout/expected/table/stretch-to-fixed-height.txt, Tests/LibWeb/Layout/expected/table/table-formation-with-rowspan-in-the-middle.txt, Tests/LibWeb/Layout/expected/table/table-width.txt, Tests/LibWeb/Layout/input/table/border-spacing-and-borders-table-width.html, Tests/LibWeb/Layout/input/table/nested-table-box-width.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Addresses some issues with borders using up padding and not being accounted as part of the table box width in containing blocks.
=> LibWeb: Table width fixes related to borders

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h
=> LibJS/Bytecode: Throw on destructuring object assignment to nullish LHS

Userland/Libraries/LibJS/Bytecode/Op.cpp
This avoids invoking `valueOf()` on the values, which is observable.
48 new passes on test262. :^)
=> LibJS/Bytecode: Use ToString instead of generic add() in ConcatString

Tests/LibWeb/Text/expected/css/box-shadow-resolves-length-functions.txt, Tests/LibWeb/Text/input/css/box-shadow-resolves-length-functions.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/CSS/StyleValues/ShadowStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/ShadowStyleValue.h, Userland/Libraries/LibWeb/Layout/Node.cpp
The CSS box-shadow property takes 2-4 properties that are `<length>`s, those being:
- offset-x
- offset-y
- blur-radius
- spread-radius
Previously these were resolved directly to concrete Lengths at parse time, but now they will be parsed as LengthStyleValues and/or CalculatedStyleValues and be stored that way until styles are later resolved.
Note: Optimally the test's expected value (`#000000ff 0px calc(5px + (0 - 10px)) 0px calc(2px + 3px)`) would definitely have the `calc(...)`'s resolved, but I'm unsure if this is a flaw in my patch or our current implementation of `getComputedStyle`. If it's the latter, I think this test can simply be updated later with the correctly resolved values.
Before:
After:
=> LibWeb: Support calc(...) in box-shadow's values of type Length

AK/URLParser.cpp, AK/URLParser.h, Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLFormElement.h, Userland/Libraries/LibWeb/URL/URLSearchParams.cpp, Userland/Libraries/LibWeb/URL/URLSearchParams.h
Still left to be implemented are the encoding steps inside of percent_encode_after_encoding
=>  LibWeb: Implement Web::URL::url_encode closer to spec

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
=> LibJS/Bytecode: Transfer binding pattern aliases to function names

Userland/Libraries/LibJS/Contrib/Test262/$262Object.cpp
=> LibJS: Make $262.evalScript() work in bytecode mode

Tests/LibWeb/Layout/expected/table/stretch-to-fixed-height.txt, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Subtract borders and padding from specified height before comparing to the used content height.
=> LibWeb: Adjust specified table height

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
=> LibJS/Bytecode: Handle object destructuring to member expression

Userland/Libraries/LibJS/Bytecode/Op.cpp
By converting the excluded names to PropertyKey before filtering, we ensure that non-string keys get excluded as needed.
14 new passes on test262. :^)
=> LibJS/Bytecode: Fix non-string keys not being excluded in rest object

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Runtime/VM.cpp
Instead of assuming that there's an active AST interpreter, this code now takes VM& everywhere and invokes the appropriate interpreter.
92 new passes on test262. :^)
=> LibJS: Make class definition evaluation work in bytecode mode

Userland/Libraries/LibJS/Bytecode/Op.cpp
The fact that side effects clobbers the accumulator isn't just annoying inside the instruction handler, but also really counter-intuitive in the bytecode program itself.
17 new passes on test262. :^)
=> LibJS/Bytecode: Don't clobber accumulator in Put/Delete instructions

Userland/Libraries/LibJS/Bytecode/Op.cpp
=> LibJS/Bytecode: Don't assert on eval() without arguments

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
=> LibJS/Bytecode: Transfer object expression property names to functions

Userland/Libraries/LibVideo/PlaybackManager.cpp, Userland/Libraries/LibVideo/PlaybackManager.h
`seek_demuxer_to_most_recent_keyframe()` wasn't correctly returning in cases where an error was thrown by the demuxer. To avoid this, the function now returns the error, and the playback state handler must act on it instead, allowing it to exit the seeking state early.
=> LibVideo/PlaybackManager: Don't crash when demuxer seek throws an error

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
```
Summary:
Diff Tests:
+16 ✅    -16 ❌   
Diff Tests:
test/language/statements/do-while/S12.6.1_A3.js                    ❌ -> ✅
test/language/statements/do-while/S12.6.1_A5.js                    ❌ -> ✅
test/language/statements/do-while/S12.6.1_A7.js                    ❌ -> ✅
test/language/statements/do-while/S12.6.1_A8.js                    ❌ -> ✅
test/language/statements/do-while/cptn-abrupt-empty.js             ❌ -> ✅
test/language/statements/do-while/cptn-normal.js                   ❌ -> ✅
test/language/statements/if/cptn-no-else-true-abrupt-empty.js      ❌ -> ✅
test/language/statements/switch/cptn-a-abrupt-empty.js             ❌ -> ✅
test/language/statements/switch/cptn-b-abrupt-empty.js             ❌ -> ✅
test/language/statements/switch/cptn-dflt-abrupt-empty.js          ❌ -> ✅ …
```
=> LibJS/Bytecode: Return the proper result for iteration statements + fix for catch blocks

AK/Assertions.h
The Windows CRT definition of assert() is not noreturn, and causes compile errors when using it as the backing for VERIFY() in debug configurations of applications like the Jakt compiler.
=> AK: Never use assert() when targeting Windows platforms

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
=> LibJS/Bytecode: Use LHS identifier as function name on logical assign

Userland/Libraries/LibJS/Runtime/Value.cpp
The exponent might be larger than the range of values representable by an i32, so we have to use the `fmod` function instead of the modulo operator.
This fixes 3 test262 tests on AArch64. No changes on x86-64.
=> LibJS: Fix integer overflow in Number::exponentiate

Tests/LibWeb/Layout/expected/table/row-outer-size-with-computed-size.txt, Tests/LibWeb/Layout/input/table/row-outer-size-with-computed-size.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
This ensures that min-content contributions from cells with no content are computed using their calculated values, which are never considered for min-content before then. The specification diverges from column measures algorithm, which doesn't use specified width of cells anywhere.
=> LibWeb: Fix min-content initialization for row measures

Base/usr/share/man/man1/chgrp.md, Userland/Utilities/chgrp.cpp
=> chgrp: Add support for multiple file paths

Userland/DevTools/HackStudio/EditorWrapper.cpp, Userland/DevTools/HackStudio/Git/DiffViewer.cpp, Userland/DevTools/HackStudio/Git/DiffViewer.h, Userland/Libraries/LibCpp/SemanticSyntaxHighlighter.cpp, Userland/Libraries/LibDiff/Generator.cpp, Userland/Libraries/LibDiff/Generator.h, Userland/Libraries/LibDiff/Hunks.cpp, Userland/Libraries/LibDiff/Hunks.h, Userland/Utilities/diff.cpp, Userland/Utilities/headless-browser.cpp
Ready now that https://github.com/SerenityOS/serenity/pull/19530 is merged.
=> LibDiff+HackStudio+diff: Remove use of DeprecatedString in LibDiff (and diff)

Base/usr/share/man/man1/env.md, Userland/Libraries/LibC/stdlib.cpp, Userland/Utilities/env.cpp
This PR adds the `-u` option to `env`.  This removes the given variable from the environment if it is present; the option may be specified more than once.
I also made a small change to the `unsetenv()` function in LibC. `EINVAL` is now returned if it is given an empty string or a string containing an "=" character. This brings it in line with the POSIX specification.
Example usage:
=> env: Add `-u` option to unset environment variables

Base/usr/share/man/man1/strings.md, Userland/Utilities/strings.cpp
This PR makes the following changes to the `strings` utility:
* Add the `o` option: This is an alias for `-t o`, which prepend each string with an offset in octal.
* Add `--bytes` and `--radix` as aliases for `-n` and `-t` respectively.
* Replace `-p` option with `-f`: This prepends each string with the file name, rather than showing the file name before any strings.
* Continue if an error is encountered processing a file.
These changes make `strings` behave more like the implementation on Linux and FreeBSD.
Example usage:
=> strings: Add `-o` option to display octal offsets and replace `-p` with `-f`

Base/usr/share/man/man8/usermod.md, Userland/Libraries/LibCore/Account.cpp, Userland/Libraries/LibCore/Account.h, Userland/Utilities/usermod.cpp
This PR adds the following options to `usermod`:
* `-G`: Set the supplementary groups for a given user. By default, the user is removed from any groups they are a part of that are not specified.
* `-a`: Append to the given user's list of supplementary groups.
* `-r`: Remove the user from the given supplementary groups if they are a member of them.
In addition to these changes, group names as well as numbers may be specified with the `-g` option A sanity check has also been added to ensure that the `-L` and `-U` options cannot be used at the same time.
Example usage:
=> usermod: Add `-r`, `-a` and `-G` options for changing supplementary groups

Base/usr/share/man/man1/cut.md, Userland/Utilities/cut.cpp
This PR brings `cut` closer to the POSIX specification by making the following changes:
* Lines containing no field delimiters are now passed through unmodified by default. Specifying the `-s` option causes these lines to be ignored.
* Field specifiers containing multiple consecutive commas or dashes (e.g: `-f1,,2`, `-f2--5`) are now treated as invalid.
* Empty fields on a line are no longer treated as though they aren't present. For example, a line such as `\t\tThis line has 3 fields`, previously had its first 2 empty fields ignored.
* A trailing newline before EOF is now ignored, rather than an empty line being printed.
Example usage:
=> cut: Bring closer to POSIX specification and add `-s` option

Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWebView/AccessibilityTreeModel.cpp
(Or any document with aria-hidden=true on the root)
=> LibWeb: Prevent crash when inspecting SVG documents

Tests/LibJS/test262-runner.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Utilities/js.cpp
This is going to look a bit silly on the libjs.dev graphs 😬 
```
Summary:
Diff Tests:
-11778 ✅   +945 ❌   +2864 ⚙️   +9299 💥️    -1330 📝   
```
=> test262-runner+js: Respect the bytecode optimizations enabled flag

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
=> LibJS/Bytecode: Prefer alias over name in object pattern bindings

Meta/Lagom/Fuzzers/FuzzFlacLoader.cpp, Meta/Lagom/Fuzzers/FuzzMP3Loader.cpp, Meta/Lagom/Fuzzers/FuzzQOALoader.cpp, Meta/Lagom/Fuzzers/FuzzWAVLoader.cpp, Tests/LibAudio/TestFLACSpec.cpp, Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/FlacLoader.h, Userland/Libraries/LibAudio/Loader.cpp, Userland/Libraries/LibAudio/Loader.h, Userland/Libraries/LibAudio/MP3Loader.cpp, Userland/Libraries/LibAudio/MP3Loader.h, Userland/Libraries/LibAudio/QOALoader.cpp, Userland/Libraries/LibAudio/QOALoader.h, Userland/Libraries/LibAudio/WavLoader.cpp, Userland/Libraries/LibAudio/WavLoader.h
This removes a lot of duplicated stream creation code from the plugins, and also simplifies the way that the appropriate plugin is found. This mirrors the ImageDecoderPlugin design and necessitates new sniffing methods on the loaders.
=> LibAudio: Extract loader stream creation from the plugins

Userland/Applets/ClipboardHistory/ClipboardHistoryModel.cpp, Userland/Applets/ClipboardHistory/ClipboardHistoryModel.h, Userland/Applications/Browser/BrowserWindow.cpp, Userland/Applications/Browser/BrowserWindow.h, Userland/Applications/FileManager/DirectoryView.cpp, Userland/Applications/FileManager/DirectoryView.h, Userland/Applications/FileManager/main.cpp, Userland/Applications/Terminal/main.cpp, Userland/Games/Chess/ChessWidget.cpp, Userland/Games/Chess/ChessWidget.h, Userland/Games/Snake/Game.cpp, Userland/Games/Snake/Game.h, Userland/Libraries/LibCards/CardGame.cpp, Userland/Libraries/LibCards/CardGame.h, Userland/Libraries/LibConfig/Listener.cpp, Userland/Libraries/LibConfig/Listener.h, Userland/Libraries/LibGUI/Calendar.cpp, Userland/Libraries/LibGUI/Calendar.h, Userland/Services/Taskbar/QuickLaunchWidget.cpp, Userland/Services/Taskbar/QuickLaunchWidget.h, Userland/Services/Taskbar/TaskbarWindow.cpp, Userland/Services/Taskbar/TaskbarWindow.h
The immutability of the string is not relevant here, since the string we're given was allocated in the IPC serialization layer and will be destroyed shortly afterwards. Additionally, noone relies on DeprecatedString-specific functionality. This will make it easier to convert the IPC layer itself to String later on.
The second commit is a trivial FIXME resolution I stumbled over.
=> Userland: Convert config listener callbacks to use StringView

Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
There is nothing to do here at runtime as imports are handled in `Interpreter::run`.
```
Summary:
Diff Tests:
+79 ✅   +33 ❌   +1 💥️    -113 📝   
```
=> LibJS/Bytecode: Handle ImportStatement in codegen

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
This adds support for exporting class expressions, which was previously TODO'd.
We now correctly set the binding name of exports to `"*default*"` if they are unnamed. I'm not sure what the difference between the `InitializationMode` kinds is, but using `Initialize` fixes a bunch of tests.
Note that some export tests (e.g. `eval-export-dflt-expr-cls-named.js`) still fail, as we don't set the "name" property of exported classes correctly.
176 new passes on test262
```
Summary:
Diff Tests:
+176 ✅    -152 ❌    -24 💥️   
```
=> LibJS/Bytecode: Improve export statement handling

Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.slice.js, Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.splice.js, Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.toSpliced.js
Now that serenity is 64 bit only these tests no longer need to be skipped :^)
=> LibJS/Tests: Enable some now passing Array length tests

Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
Fix caret icon displaying in some situations
```
.triangle {
width: 0;
height: 0;
border-top: 50px solid skyblue;
border-right: 50px solid transparent;
border-left: 50px solid transparent;
}
<div class="triangle"></div>
```
Before
After
=> LibWeb: Make two borders joints part painting work

Tests/LibWeb/Layout/expected/table/width-distribution-and-constrained-columns.txt, Tests/LibWeb/Layout/input/table/width-distribution-and-constrained-columns.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Bring our implementation closer to the specification, which distributes excess width to unconstrained columns first.
=> LibWeb: Don't distribute excess width to constrained columns

AK/StringView.h
oss-fuzz ships a pre-release commit of clang-15 for all of their build bots. Until they update to a release of clang-15 that includes the fix for this bug, or a later release, we need to keep the workaround in place.
#19482 introduced this bug by enabling consteval for clang on linux platforms. This is the second workaround we've had to add for oss-fuzz's bespoke clang-15 release, the first being #18708.
=> AK: Re-enable consteval StringView literal workaround for oss-fuzz

Tests/LibWeb/Layout/expected/table/percentage-width-columns.txt, Tests/LibWeb/Layout/input/table/percentage-width-columns.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Cell percentage widths are relative to table width, not containing block width. If the table width is auto, there isn't a normative specification, only a brief mention that the user agent should try to meet it.
As a starting point, we increase the width of the table such that it's sufficient to cover min-width of cells with a percentage width. This matches the behavior of other browsers, at least for simple cases.
=> LibWeb: Make cell percentage widths relative to table

AK/StdLibExtraDetails.h, AK/TypeList.h
These recursive templates have a measurable impact on the compile speed of Variant-heavy code like LibWeb. Using these builtins leads to a 2.5% speedup for the measured compilation units.
=> AK: Use compiler builtins for `MakeIntegerSequence`/`TypeListElement`

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp, Userland/Libraries/LibWeb/Page/EventHandler.cpp
This pr allows for javascript urls to be executed without crashing the browser! :^)
Example:
```html
<a href="javascript:alert(1)">javascript url</a>
```
=> LibWeb: Fix js execution for js urls in anchor tags href

Userland/Libraries/LibJS/Runtime/PromiseCapability.cpp, Userland/Libraries/LibJS/Runtime/PromiseCapability.h
See https://github.com/tc39/ecma262/commit/874ecf9
After this refactoring, we now correctly handle non-function / non-undefined objects being passed multiple times: instead of skipping assignment to promiseCapability altogether and failing with a NotAFunction error in the end; on the second time the executor closure is called, we return GetCapabilitiesExecutorCalledMultipleTimes.
This fixes the 7 `capability-executor-called-twice.js` test262 tests.
```
Summary:
Diff Tests:
+7 ✅    -7 ❌   
Diff Tests:
test/built-ins/Promise/all/capability-executor-called-twice.js            ❌ -> ✅
test/built-ins/Promise/allSettled/capability-executor-called-twice.js     ❌ -> ✅
test/built-ins/Promise/any/capability-executor-called-twice.js            ❌ -> ✅ …
```
=> LibJS: Align NewPromiseCapability with spec changes

Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h
This makes them trivially copyable, which is an assumption multiple optimizations use when rebuilding the instruction stream.
This fixes most optimized crashes in the test262 suite.
----
Fixes #19690
----
This puts the interning quite early if it is deemed to be better, I can move it into the the `emit_named_evaluation_if_anonymous_function` function and Co, which would most likely decrease the lines changed as well
=> LibJS: Use the IdentifierTable for NewFunction and NewClass lhs names

Tests/LibWeb/Layout/expected/cell-relative-to-specified-table-width.txt, Tests/LibWeb/Layout/input/cell-relative-to-specified-table-width.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Computing the table width algorithm bifurcates based on whether table-root width is auto. We only adjust the used table width based on cell percentage widths on the auto branch, thus the same check is needed when we initialize cell widths.
=> LibWeb: Check whether table box width is auto when resolving cell width

Kernel/Net/TCPSocket.cpp
When initiating a connection termination, the FIN should be sent with a ACK from the last received segment even if that ACK already been sent.
This is fixing a problem where a connected remote host wouldn't receive the FIN packet from the SerenityOS host initiating the disconnection. QEMU's hostfwd feature uses libslirp which won't forward a segment when initiating a close if it only has the FIN flag set. (https://gitlab.freedesktop.org/slirp/libslirp/-/blob/master/src/tcp_input.c#L1347).
While at this point I can't find a specific location and explanation in an RFC/spec that says we should do so, most RFCs and documentation show diagrams where the first FIN is sent with an ACK (even if a previous packet with the same ACK has already been sent):
* …
=> Kernet/Net: Close a TCP connection using FIN|ACK instead of just FIN.

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Op.cpp
This change replaces usage of `execute_ast_node` to evaluate super expression in NewClass by generating instructions instead.
=> LibJS: Stop using execute_ast_node in NewClass instruction

Userland/Libraries/LibJS/Runtime/PromiseCapability.cpp
I introduced this copy-paste mistake in c21255d.
Gets rid of 7 assertion failures on test262.
=> LibJS: Fix incorrect `is_function()` check in NewPromiseCapability

Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
This makes JS backtraces actually show the filename of scripts correctly again (instead of the URL of the document that loaded them).
=> LibWeb: Use the script's own URL as filename for fetched classic script

AK/String.h, Meta/Lagom/BuildFuzzers.sh
This was missed in 02b74e5a70e1eef2fe3123fe8aa157301424783a
We need to disable consteval in AK::String as well as AK::StringView, and we need to disable it when building both the tools build and the fuzzer build.
Verified by changing the Dockerfile in oss-fuzz/projects/serenity to point to my fork and this branch, and running
```
python3 infra/helper.py build_image serenity
python3 infra/helper.py build_fuzzers serenity
python3 infra/helper.py check_build serenity
```
After this, FuzzCSSParser and FuzzShell complain that they crash wayyy to early in the bad build checks.
=> AK+Meta: Disable consteval completely when building for oss-fuzz

Userland/Libraries/LibWeb/HTML/EventLoop/Task.h
In the merging of an extremely large navigables PR, a task queue source was added after the unique task source start value that was supposed to remain last in the enum.
=> LibWeb: Place the unique task source used by media elements last

Ports/ffmpeg/package.sh
This fixes build error: relocation R_X86_64_PC32 against symbol `ff_pw_5' can not be used when making a shared object; recompile with -fPIC
Contributing to issue #18238
=> Ports/ffmpeg: build shared libraries by using --enable-shared configure option

Kernel/Devices/Storage/SD/Registers.h, Kernel/Devices/Storage/SD/SDHostController.cpp, Kernel/Devices/Storage/SD/SDHostController.h
This PR fixes a few logic bugs that didn't manifest when running under Qemu, only when trying to boot on the Raspberry Pi from the SD card.
@mrkct
=> Kernel: Fixes for bare metal SD Card I/O

AK/StackInfo.h, Meta/Azure/Lagom.yml, Userland/Libraries/LibJS/Heap/Heap.cpp, Userland/Libraries/LibJS/Heap/Heap.h
Fixes #17163
With clang 15.0.7, this provides the following diff-tests for libjs-test262 with ASAN and UBSAN on:
```
Duration:
-23.55s
Summary:
Diff Tests:
+21 ✅   +33 ❌   +17 💀    -71 💥️  
```
With the sanitizer settings
```
ASAN_OPTIONS=strict_string_checks=1:check_initialization_order=1:strict_init_order=1:detect_stack_use_after_return=1
UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1
```
And run with a 120s timeout:
```
python3 main.py --libjs-test262-runner ./Build/_deps/lagom-build/bin/test262-runner --test262-root ./test262/  --per-file asan-120s.json --memory-limit -1 --timeout 120
```
Note that the diff between this PR with ASAN and master without ASAN is like so:
```
Duration:
+2456.43s
Summary:
Diff Tests:
-188 ✅    -48 ❌   +24 💀   +212 💥️   
```
So still …
=> AK+LibJS: ASAN fixes for detect_stack_use_after_return

Ladybird/BrowserWindow.cpp, Ladybird/BrowserWindow.h
This commit adds basic functionality to zoom in/out using the Ctrl+Scroll shortcut.
=> Ladybird: Add initial support for Ctrl+Scroll to zoom in/out

Tests/LibWeb/Layout/expected/cell-relative-to-specified-table-width.txt, Tests/LibWeb/Layout/expected/table/basic.txt, Tests/LibWeb/Layout/expected/table/border-spacing-colspan.txt, Tests/LibWeb/Layout/expected/table/border-spacing-rowspan.txt, Tests/LibWeb/Layout/expected/table/border-spacing.txt, Tests/LibWeb/Layout/expected/table/borders.txt, Tests/LibWeb/Layout/expected/table/bottom-caption.txt, Tests/LibWeb/Layout/expected/table/inline-table-width.txt, Tests/LibWeb/Layout/expected/table/long-caption-increases-width.txt, Tests/LibWeb/Layout/expected/table/multi-line-cell.txt, Tests/LibWeb/Layout/expected/table/nested-table-box-width.txt, Tests/LibWeb/Layout/expected/table/row-outer-size-with-computed-size.txt, Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt, Tests/LibWeb/Layout/expected/table/rowspan.txt, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
tr y offset is not being computed correctly, causing errors in hit testing
=> LibWeb: Add vertical border heights to tr

Tests/LibWeb/Layout/expected/block-and-inline/percentage-min-width-with-max-content-containing-block-width.txt, Tests/LibWeb/Layout/input/block-and-inline/percentage-min-width-with-max-content-containing-block-width.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Fixes an assertion when loading https://bun.sh/
=> LibWeb: Treat non-finite containing block width as zero for percentages

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Runtime/Value.cpp, Userland/Libraries/LibJS/Runtime/Value.h
- One ~17% speed-up for the bytecode VM. This one benefits basically all workloads.
- One ~9% speed-up for all VMs. (Fast path for bitwise ops on two Int32 values)
=> LibJS: Two little optimizations for Kraken

Tests/LibGfx/TestRect.cpp, Userland/Libraries/LibGfx/Rect.h
Assertion fails if the point is outside of the rect. This was introduced in introduced in #18970 and causes serenity to crash when changing to 2x resolution for a monitor, if the cursor after resizing is outside of the new screen.
Added test to reproduce.
=> LibGfx: Fix error & crash in Rect::closest_to

Base/usr/share/man/man1/asctl.md, Ladybird/AudioCodecPluginLadybird.cpp, Userland/Applications/Piano/AudioPlayerLoop.cpp, Userland/Applications/Piano/AudioPlayerLoop.h, Userland/Applications/Piano/Music.h, Userland/Applications/SoundPlayer/PlaybackManager.cpp, Userland/Applications/SoundPlayer/PlaybackManager.h, Userland/Applications/SoundPlayer/Player.cpp, Userland/Libraries/LibAudio/ConnectionToServer.cpp, Userland/Libraries/LibAudio/ConnectionToServer.h, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.cpp, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h, Userland/Services/AudioServer/AudioServer.ipc, Userland/Services/AudioServer/ConnectionFromClient.cpp, Userland/Services/AudioServer/ConnectionFromClient.h, Userland/Services/AudioServer/Mixer.cpp, Userland/Services/AudioServer/Mixer.h, Userland/Services/WebContent/AudioCodecPluginSerenity.cpp, Userland/Services/WebContent/AudioCodecPluginSerenity.h, Userland/Utilities/aplay.cpp
Depends on #17656
This change was a long time in the making ever since we obtained sample rate awareness in the system. Now, each client has its own sample rate, accessible via new IPC APIs, and the device sample rate is only accessible via the management interface. AudioServer takes care of resampling client streams into the device sample rate. Therefore, the main improvement introduced with this commit is full responsiveness to sample rate changes; all open audio programs will continue to play at correct speed with the audio resampled to the new device rate.
The immediate benefits are manifold:
- Gets rid of the legacy hardware sample rate IPC message in the non-managing client
- Removes duplicate resampling and sample index rescaling code everywhere
- Avoids potential sample index …
=> AudioServer+Userland: Decouple client sample rates from device rate

Userland/Libraries/LibAudio/MP3HuffmanTables.h, Userland/Libraries/LibAudio/MP3Loader.cpp
There are at most 576 granule samples/frequency lines, but the side data
can specify that the big_values granule type take up to 1024 samples.
The spec says in 2.4.3.4.6 that we should always stop reading Huffman
data once we have 576 samples, so that is what this change does. I also
add some useful spec comments while I'm here.
=> LibAudio: Fix both fuzzer-found MP3 bugs

Base/usr/share/man/man2/accept.md, Userland/Utilities/markdown-check.cpp
This man page was referenced from some places. This is mostly a condensed version of the POSIX behavior that the system call implementation already has, only documenting the obviously visible errors (in source code) we do actually report.
=> Base: Add accept(2) man page

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
=> LibJS/Bytecode: Make sure empty `with` statement results in `undefined`

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
While the completion value of a variable declaration is specified to be empty, we might already have a completion value in the accumulator from a previous statement. Preserve it so as to avoid clobbering it.
This fixes 6 tests on test262.
```
Summary:
Diff Tests:
+6 ✅    -6 ❌   
Diff Tests:
test/language/eval-code/direct/cptn-nrml-empty-var.js   ❌ -> ✅
test/language/eval-code/indirect/cptn-nrml-empty-var.js ❌ -> ✅
test/language/statements/const/cptn-value.js            ❌ -> ✅
test/language/statements/for-of/scope-head-var-none.js  ❌ -> ✅
test/language/statements/let/cptn-value.js              ❌ -> ✅
test/language/statements/variable/cptn-value.js         ❌ -> ✅
```
=> LibJS/Bytecode: Do not clobber completion value with VariableDeclaration

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Also, don't assert while dumping an AST with this construct.
7 new passes on test262. :^)
=> LibJS/Bytecode: Support using MemberExpression as rest property

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
```
Summary:
Diff Tests:
+5 ✅    -5 ❌   
Diff Tests:
test/language/expressions/class/elements/class-name-static-initializer-default-export.js ❌ -> ✅
test/language/expressions/dynamic-import/eval-export-dflt-cls-anon.js                    ❌ -> ✅
test/language/expressions/dynamic-import/eval-export-dflt-expr-cls-anon.js               ❌ -> ✅
test/language/module-code/eval-export-dflt-cls-anon.js                                   ❌ -> ✅
test/language/module-code/eval-export-dflt-expr-cls-anon.js                              ❌ -> ✅
```
=> LibJS/Bytecode: Infer name of anonymous exported classes when possible

Userland/Libraries/LibJS/Bytecode/BasicBlock.h, Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Heap/Heap.cpp, Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
Since the relationship between `VM` and `Bytecode::Interpreter` is now clear, we can have `VM` ask the `Interpreter` for roots in the GC marking pass. This avoids having to register and unregister `Handle`s and `MarkedVectors` over and over.
Since `GeneratorObject` can also own a `RegisterWindow`, we share the code in a `RegisterWindow::visit_edges()` helper.
~4% speed-up on Kraken/stanford-crypto-ccm.js :^)
=> LibJS/Bytecode: Make Bytecode::Interpreter participate in GC marking

Userland/Libraries/LibLine/Editor.cpp
Previously we were mashing all the registered signal handlers into a global map and invoking them all immediately, which could lead to inconsistencies with how EventLoops block each other. This commit runs signals' handlers whenever the event loop itself is capable of processing events, which fixes a crash in LibLine when Shell is in the middle of executing a process and has given away the ownership of stdin/stdout to the process.
cc @awesomekling - your boog report.
=> LibLine: Defer handling SIGWINCH and SIGINT

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/BasicBlock.h, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Bytecode/Pass/LoadElimination.cpp
- Remove unnecessary fidgeting with the var environment in `Bytecode::Interpreter`
- Don't make a new `Array` for every function call (unless the call has spread arguments)
=> LibJS/Bytecode: Two little optimizations for Kraken

Tests/LibWeb/Layout/expected/block-and-inline/float-4.txt, Tests/LibWeb/Layout/input/block-and-inline/float-4.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
The "y" check for when to reset float side positioning was comparing an offset that included the border, while the offset of the other side does not.
=> LibWeb: Fix alternating-sides float positioning

Meta/serenity.sh
It's possible that the entire "if" can be removed, I am not sure if the FIXME is still relevant. I tried running it without the "cd" and it seemed to work fine, but since I don't know what used to not work I did not remove it.
=> Meta: Update path to ladybird in gdb invocation

Userland/DevTools/HackStudio/Editor.cpp, Userland/DevTools/HackStudio/Git/DiffViewer.cpp, Userland/DevTools/HackStudio/Git/GitRepo.cpp, Userland/Libraries/LibCpp/SemanticSyntaxHighlighter.cpp, Userland/Libraries/LibDiff/Format.cpp, Userland/Libraries/LibDiff/Format.h, Userland/Libraries/LibDiff/Generator.cpp, Userland/Libraries/LibDiff/Generator.h, Userland/Libraries/LibDiff/Hunks.cpp, Userland/Libraries/LibDiff/Hunks.h, Userland/Utilities/diff.cpp, Userland/Utilities/headless-browser.cpp
The existing hunk data structure does not contain any way to easily
store information about context surrounding the additions and removals
in a hunk. While this does work fine for normal diffs (where there is
never any surrounding context) this data structure is quite limiting for
other use cases.
Without support for surrounding context it is not possible to:
* Add support for unified or context format to the diff utility to
output surrounding context.
* Be able to implement a patch utility that uses the surrounding context
to reliably locate where to apply a patch when a hunk range does not
apply perfectly.
This patch changes Diff::Hunk such that its data structure more closely
resembles a unified diff. Each line in a hunk is now either a change,
removal, addition or context. (unlocking …
=> LibDiff+diff+headless-browser: Support unfied hunks with context

AK/NumericLimits.h, Userland/Libraries/LibJS/Runtime/NumberConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Number/Number-constants.js
**AK: Disambiguate miniumum normal and denormal value in NumericLimits**
The STL is a bit confusing in this regard, `numeric_limits<FloatT>::min`
refers to the smallest normalized value, while `denorm_min()` returns
the smallest denormalized value. We should explicitly force users to
think about which one is appropriate for their use case.
**LibJS: Make Number.MIN_VALUE a denormal**
The standard implies that `MIN_VALUE` should be a denormalized value if
denormal arithmetic is supported. This is the case on x86-64 and AArch64
using standard GCC/Clang compilation settings.
test262 checks whether `Number.MIN_VALUE / 2.0` is equal to 0, which
only holds if `MIN_VALUE` is the smallest denormalized value.
```
Diff Tests:
test/language/expressions/division/S11.5.2_A4_T10.js      ❌ -> ✅ …
```
=> AK+LibJS: Make `Number.MIN_VALUE` a denormal

Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Tests/builtins/Symbol/Symbol.js
This makes the behavior of `Symbol` correct in strict mode, wherein if the receiver is a symbol primitive, assigning new properties should throw a TypeError.
```
Summary:
Diff Tests:
+2 ✅    -2 ❌   
Diff Tests:
test/built-ins/Symbol/auto-boxing-strict.js                                    ❌ -> ✅
test/built-ins/Symbol/prototype/toString/toString-default-attributes-strict.js ❌ -> ✅
```
=> LibJS/Bytecode: Do not coerce the receiver to Object for internal_set

Userland/Libraries/LibCore/ArgsParser.cpp, Userland/Libraries/LibCore/ArgsParser.h, Userland/Libraries/LibMarkdown/Document.cpp, Userland/Libraries/LibMarkdown/Document.h, Userland/Utilities/man.cpp, Userland/Utilities/md.cpp
Related to #17128
This pull request requires the minimum set of patches that I could think of to remove `DeprecatedString` from the `man` utility.
This includes:
* Adding `String` variants to `add_option` and `add_positional_argument` in the `ArgsParser`
* Converting `render_to_terminal` from `DeprecatedString` to `ErrorOr<String>` (which meant also changing the `md` utility)
* Removing all of the `DeprecatedString` from `man`
When converting `render_to_terminal` to `ErrorOr<String>` I made a conscious decision to ignore the other methods on the class, even if they would have been simple to convert, in order to keep the patch as small as possible.
As discussed on the Discord another possible improvement here would be to have a version of `Core::System::posix_spawnp` that can take …
=> man: Remove DeprecatedString

Ports/libgd/package.sh
Making port libgd (and also npiet) build again
Contributing to #18238
=> Ports/libgd: Added --without-x to prevent linking against /usr/lib

Tests/LibWeb/Layout/expected/anonymous-wrappers-continue-to-inherit-style-after-change.txt, Tests/LibWeb/Layout/input/anonymous-wrappers-continue-to-inherit-style-after-change.html, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/Layout/Node.cpp
Anonymous wrapper boxes inherit style from their layout tree parent, and since style data is per-layout-node, we have to manually sync them from parent to anonymous children when something changes.
This is not very elegant or efficient, so I've left a FIXME about solving it in a nicer way.
This fixes horizontal dog alignment on https://waffles.dog/ :^)
=> LibWeb: Update anonymous wrappers when applying style changes

Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Bytecode/Pass/LoadElimination.cpp
Otherwise we could forget to emit stores those registers, thinking that they are only directly accessed.
----
Fixes all optimized bytecode regressions caused by c37b204
=> LibJS: Handle `Call`s argument range during `EliminateLoads` pass

Userland/Libraries/LibLine/Editor.cpp
This can only realistically happen when the terminal no longer exists, so quitting with an error here is the better solution as the application will soon be killed anyway.
Fixes #19742.
Fixes #19017.
=> LibLine: Handle any errors propagated through refresh_display()

Userland/Libraries/LibCore/ArgsParser.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.h, Userland/Utilities/image.cpp
--quality 1:
--quality 10:
--quality 75 (default):
=> LibGfx/JPEG+image: Allow the user to choose JPEG's encoding quality

Kernel/Devices/Audio/Channel.h, Kernel/Devices/Audio/Controller.h, Kernel/Devices/Audio/IntelHDA/Controller.cpp, Kernel/Devices/Audio/IntelHDA/Controller.h, Kernel/Devices/Audio/IntelHDA/Stream.cpp, Kernel/Devices/Audio/IntelHDA/Stream.h, Kernel/Devices/Audio/Management.cpp, Kernel/Devices/Audio/Management.h, Userland/Services/AudioServer/Mixer.cpp
We used to not care about stopping an audio output stream for Intel HDA since AudioServer would continuously send new buffers to play. Since 707f5ac150ef858760eb9faa52b9ba80c50c4262 however, that has changed.
Intel HDA now uses interrupts to detect when each buffer was completed by the device, and uses a simple heuristic to detect whether a buffer underrun has occurred so it can stop the output stream.
This was tested on Qemu's Intel HDA (Linux x86_64) and a bare metal MSI Starship/Matisse HD Audio Controller.
CC @kleinesfilmroellchen
=> Kernel+AudioServer: Use interrupts for Intel HDA audio buffer completion

Userland/Libraries/LibCore/ArgsParser.cpp, Userland/Libraries/LibCore/ArgsParser.h
depends on https://github.com/SerenityOS/serenity/pull/19382 (contains commits from this PR)
This change comes from some comments on the PR this depends on that it would be good to make both `ArgsParser::Option::accept_value` and `ArgsParser::Arg::accept_value` return an `ErrorOr` instead of just a `bool`.
I have decided to make these functions return an `ErrorOr<bool>` instead of an `ErrorOr<void>` because I noticed going through these functions that there seem to be two failure states
1. A "system" error/bug in `SerenityOS` that is realistically unrecoverable by the user
2. The user provided invalid input. This will usually result in the program help being printed so that the user can correct the mistake
=> LibCore: Make ArgsParser accept_value return ErrorOr

Tests/LibWeb/Layout/expected/block-and-inline/relpos-block.txt, Tests/LibWeb/Layout/expected/block-and-inline/relpos-float.txt, Tests/LibWeb/Layout/expected/flex/relpos-flex-item.txt, Tests/LibWeb/Layout/expected/grid/relpos-grid-item.txt, Tests/LibWeb/Layout/input/block-and-inline/relpos-block.html, Tests/LibWeb/Layout/input/block-and-inline/relpos-float.html, Tests/LibWeb/Layout/input/flex/relpos-flex-item.html, Tests/LibWeb/Layout/input/grid/relpos-grid-item.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
This makes the game carousel work on https://null.com/ :^)
Before:
After:
=> LibWeb: Resolve used insets for more than just abspos elements

Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/FlacLoader.h, Userland/Libraries/LibAudio/GenericTypes.cpp, Userland/Libraries/LibAudio/GenericTypes.h
Most of them are non-critical overflow bugs that can only happen on invalid inputs anyways. However, there's one heap buffer overflow that could be exploitable together with a bug in an image decoder, as it allowed the image decoder to read 4 x (description length) past the end of the picture data.
An LPC predictor (fixed or not) contains as many warm-up samples as its
order. Therefore, the corresponding subframe must have at least this
many samples.
This turns this fuzzer-found crash into a handleable format error.
Although this sample rate is more or less bogus, we might as well not
crash.
The fuzzer found one heap buffer overflow here due to confusion between
u32* and u8* (the given size is for bytes, but we used it for 32-bit
elements, quadrupling it), and it looks like there's an …
=> LibAudio: Fix all current fuzzer-found FLAC issues

Tests/LibWeb/Layout/expected/table/td-valign.txt, Tests/LibWeb/Layout/input/table/td-valign.html, Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
This presentational hint maps to the CSS `vertical-align` property.
Fixes #19786.
=> LibWeb: Support `valign` attribute on `td` elements

Userland/Applications/FileManager/DirectoryView.cpp
Print the correct error from Core::System::chdir() instead of errno, and display the error in the DirectoryView instead of continuing to show the previous location's contents.
This regressed in 1dc3ba6ed5bfbb0055d9335a32f580a73f3ab254.
(Side note: Having to warnln() and dbgln() feels a bit silly, but that's what perror() does. Should we automatically output warnln() to the debug console as well?)
=> FileManager: Restore inline message behavior for inaccessible dirs

Userland/Libraries/LibWeb/CSS/Selector.cpp, Userland/Libraries/LibWeb/CSS/Selector.h, Userland/Libraries/LibWeb/Dump.cpp
fixes sites like github where they use a selector that includes they selection pseudo element
=> LibWeb: Add ::selection to pseudo elements

Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-align-items.txt, Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt, Tests/LibWeb/Layout/expected/font-with-many-normal-values.txt, Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-align-items.html, Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-justify-content.html, Tests/LibWeb/Layout/input/font-with-many-normal-values.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Improvements to `align-items` and `justify-content` for absolutely positioned children of a flex container, and a `font` parsing fix.
Sam before:
Sam after:
=> LibWeb: Some layout & CSS parsing fixes for Mastodon

AK/NonnullRefPtr.h, AK/RefPtr.h, Userland/Libraries/LibC/time.cpp
We don't seem to be using it there.
=> AK+LibC: Remove `AK/Atomic.h` includes from our `RefPtr`s

Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/Loader.cpp, Userland/Libraries/LibAudio/LoaderError.h, Userland/Libraries/LibAudio/MP3Loader.cpp, Userland/Libraries/LibAudio/QOALoader.cpp, Userland/Libraries/LibAudio/WavLoader.cpp
It's no longer needed now that this code uses ErrorOr instead of Result.
Ran:
rg -lw LOADER_TRY Userland/Libraries/LibAudio \
| xargs sed -i '' 's/LOADER_TRY/TRY/g'
...and then manually fixed up Userland/Libraries/LibAudio/LoaderError.h
to not redefine TRY but instead remove the now-unused LOADER_TRY,
and ran clang-format.
=> LibAudio: Stop using and remove LOADER_TRY 

Ports/OpenJDK/patches/0008-java.base-Enable-java.lang.Process-on-serenity.patch
When removing DeprecatedFile, I overlooked that it's still used in OpenJDK. Now it compiles again, although it's still not usable:
That sounds like a separate issue, so let's handle it separately.
=> Ports: Avoid using DeprecatedFile in OpenJDK

Userland/Libraries/LibJS/Parser.cpp
The flag indicating the presence of an await expression should be passed up to the parent scope until the nearest function scope is reached. This resolves several problems related to identifying top-level awaits, which are currently not recognized correctly when used within a nested scope.
+37 ✅   +12 ❌  -49 💥️
=> LibJS: Propagate "contains await" flag to parent scope in ScopePusher

Userland/Games/BrickGame/BrickGame.cpp, Userland/Games/BrickGame/BrickGame.h
Getting familiar with Serenity patterns, replaces some `release_value_but_fixme_should_propagate_errors` in BrickGame.
=> BrickGame: Propagate errors

Userland/Libraries/LibManual/SectionNode.cpp
Prior to this commit if you tried to access section 0 of the man page (`man 0 ls`) the application would just crash with an array out of bounds style error.
This commit just ensures that we return an explicit and helpful error message when you try to request the 0th section, instead of crashing.
|--------|--------|
| ![image](https://github.com/SerenityOS/serenity/assets/3310215/3abb2470-e851-4ebd-bacd-dd8fad2834a1) | ![image](https://github.com/SerenityOS/serenity/assets/3310215/d6ce06ab-72f9-48f5-9d0e-ed3ef597b495) |
=> LibManual: Error on section_number 0 instead of crashing

Kernel/Arch/aarch64/Registers.h
This resolves the various "implicit truncation from int to a one-bit wide bit-field changes value from 1 to -1" warnings produced by Clang 16+ when assigning to single-bit bitfields.
=> Kernel/aarch64: Use unsigned values in the register bitfields

Userland/Libraries/LibWeb/HTML/HTMLTableRowElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLTableRowElement.h
=> LibWeb: support bgcolor attribute on tr elements

Base/usr/share/man/man1/diff.md, Userland/Utilities/diff.cpp
Add the options '-C','--context' and '-U','--unified', which can be used
to ask diff to write a diff in that format with a given number of
context lines surrounding the diff.
Also update diff(1) to showcase the new unified and context options
which have been added to this utility.
=> diff: Allow configurable context for unified and context diffs

Userland/Applications/Mail/MailboxTreeModel.cpp
When we moved from NonnullRefPtrVector<T> to Vector<NonnullRefPtr<T>> in commit 8a48246ed1a93983668a25f5b9b0af0e745e3f04, the `at()` function started returning a NonnullRefPtr<T>& instead of T&.
The code calling create_index() was not then updated and ended up taking a pointer to a temporary NonnullRefPtr<>, instead of an actual object, leading to a crash after logging in.
=> Mail: Fix crash caused by migration from NonnullRefPtrVector

AK/URLParser.cpp
Add a whole heap of spec comments to this function. Adding these spec comments uncovered some bugs in the implementation (i.e not matching the spec), as well as some places that are missing functionality. This MR fixes some of those issues, as well as implementing some of those missing cases.
=> AK: Add a whole bunch of spec comments to 'basic' URL parser, and fix some issues that finds

Meta/Lagom/Fuzzers/AudioFuzzerCommon.h, Meta/Lagom/Fuzzers/FuzzFlacLoader.cpp, Meta/Lagom/Fuzzers/FuzzMP3Loader.cpp, Meta/Lagom/Fuzzers/FuzzQOALoader.cpp, Meta/Lagom/Fuzzers/FuzzWAVLoader.cpp
Apart from the class used audio fuzzers have identical behavior: Create a memory stream from the fuzzer input and pass this to the loader, then try to load audio until an error occurs. Since the loader plugins need to have the same static create() function anyways for LibAudio itself, we can unify the fuzzer implementations and reduce code duplication.
=> Meta/Fuzzers: Extract common audio fuzzing code

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Fix this image:
I have modified this file for a few months now, but `clang-format` decided to come out of hibernation today and moved some `const` to the east. Hence, the second commit :tada:
=> LibGfx/JPEG: Teach JPEGLoader how to be patient with non-compliant images [3/N]

Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
=> LibWeb: Support cellspacing attribute on table elements

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h
```
Summary:
Diff Tests:
+31 ✅    -20 ❌    -11 📝   
Diff Tests:
test/language/expressions/in/private-field-presence-accessor-shadowed.js 📝 -> ✅
test/language/expressions/in/private-field-presence-accessor.js          📝 -> ✅
test/language/expressions/in/private-field-presence-field-shadowed.js    📝 -> ✅
test/language/expressions/in/private-field-presence-field.js             📝 -> ✅
test/language/expressions/in/private-field-presence-method-shadowed.js   📝 -> ✅
test/language/expressions/in/private-field-presence-method.js            📝 -> ✅
test/language/expressions/in/private-field-rhs-await-absent.js           📝 -> ✅
test/language/expressions/in/private-field-rhs-await-present.js          📝 -> ✅ …
```
=> LibJS/Bytecode: Mixed bag of bytecode codegen fixes

Ports/.port_include.sh
Even if the file was already downloaded, we were trying to perform a relatively slow HTTPS-call.
=> Ports: Do not perform slow `curl` check if download already exists

Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt, Tests/LibWeb/Layout/expected/flex/flex-column-item-with-natural-aspect-ratio-and-automatic-cross-size.txt, Tests/LibWeb/Layout/expected/flex/justify-content-1.txt, Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-justify-content.html, Tests/LibWeb/Layout/input/flex/flex-column-item-with-natural-aspect-ratio-and-automatic-cross-size.html, Tests/LibWeb/Layout/input/flex/justify-content-1.html, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Identifiers.json, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Determine flex item automatic cross size from aspect ratio & main size when applicable.
- Add support for `justify-content: space-evenly` in flex layout.
Visual progression on https://twitter.com/ (note bird logo and alignment of cookie banner):
Before:
After:
=> LibWeb: Two fixes for the twitter.com front page

Ports/boost/package.sh
Building Boost failed in at least 2 cases using Python 3.11. Since there is currently no known usage of Boost's Python binding by ports, we drop the dependency to make the port install successfully again.
cc @gmta @BenWiederhake 
Makes `boost` build for #18238
=> Ports: Drop Python bindings for Boost

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Forward.h, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Parser.h, Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h, Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp, Userland/Libraries/LibJS/Runtime/ExecutionContext.h, Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp, Userland/Libraries/LibJS/Runtime/FunctionObject.h, Userland/Libraries/LibJS/SourceTextModule.cpp, Userland/Libraries/LibWeb/DOM/EventTarget.cpp, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Implements https://github.com/SerenityOS/serenity/issues/17968
Kraken tests:
ai-astar.js
before: 16.64s after: 12.23s
stanford-crypto-aes.js
before: 3.81s, after: 2.93s
stanford-crypto-pbkdf2.js
before: 7.69s after: 5.48s
=> LibJS: Make local variables faster by avoiding the environment when possible

Userland/Libraries/LibJS/Parser.cpp
This fixes crashing when current scope pusher is null during identifier parsing.
=> LibJS: Null check current scope pusher before register_identifier call

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
It was setting the definite flag for height.
=> LibWeb: Set the definite width flag in set_max_content_width

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Bytecode/Pass/LoadElimination.cpp, Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
LibJS/Bytecode: Use proper this for receiver in get/set for super expr
```
Summary:
Diff Tests:
+14 ✅    -2 ❌    -12 📝
```
-----
LibJS: Avoid RequireObjectCoercible when creating super references
This is part of an old normative change that happened soon after
Andreas made `super` closer to spec in https://github.com/SerenityOS/serenity/commit/1270df257bd043e3b9970d47784bfaf77cc3edf1.
See https://github.com/tc39/ecma262/pull/2267
This was introduced into bytecode by virtue of copy and paste :^)
Bytecode results:
```
Summary:
Diff Tests:
+2 ✅    -2 ❌
```
=> LibJS/Bytecode: Use proper this for receiver in get/set for super expr and avoid RequireObjectCoercible when creating super references 

Tests/LibWeb/Layout/expected/flex/intrinsic-height-of-flex-container-with-svg-item-that-only-has-natural-aspect-ratio.txt, Tests/LibWeb/Layout/input/flex/intrinsic-height-of-flex-container-with-svg-item-that-only-has-natural-aspect-ratio.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
When sizing under a max-content constraint, we allow flex lines to have an infinite amount of "remaining space", but we shouldn't let infinity leak into the geometry of items. So treat it as zero in arithmetic.
This fixes an issue where inline SVGs with natural aspect ratio (from viewBox) but no natural width or height could get an infinite size as flex items.
=> LibWeb: Don't let items flex to infinite size in column layout

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/CSSNumericType.cpp, Userland/Libraries/LibWeb/CSS/CSSNumericType.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
This is not the end result, and we still have the `ResolvedType` enum around which should disappear eventually. However, after a lot of trial and error (and confusion) I've decided the best way to continue is to implement simplification, and then remove all this not-to-spec value-resolving stuff. That's going to be quite a big change, and this is already over 1000 lines, so let's break here. :^)
=> LibWeb: First steps towards proper calc() typing

Userland/Libraries/LibJS/Bytecode/Op.cpp
Invariants 5 and 6 of the `EnumerateObjectProperties` AO mean that we
must not include an enumerate property if there is a non-enumerable
property higher up the prototype chain with the same name. The previous
implementation did not adhere to this, as `EnumerableOwnPropertyNames`
does not carry information about present but non-enumerable properties.
```
Summary:
Diff Tests:
+2 ✅    -2 ❌   
Diff Tests:
test/language/statements/for-in/12.6.4-2.js                  ❌ -> ✅
test/language/statements/for-in/order-enumerable-shadowed.js ❌ -> ✅
```
---
This PR removes a pointless check about the uniqueness of property keys: this invariant is enforced by virtue of `items` being a HashTable.
=> LibJS/Bytecode: Handle shadowed non-enumerable properties in for-in loops

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Layout/LayoutState.cpp, Userland/Libraries/LibWeb/Layout/LayoutState.h, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h, Userland/Libraries/LibWeb/Painting/PaintableBox.h, Userland/Libraries/LibWeb/Painting/StackingContext.cpp, Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp, Userland/Libraries/LibWeb/Painting/TableBordersPainting.h
This centers borders on grid lines and avoids visual bugs due to rendering borders on each side of an edge. It's improving the appearance of all tables in collapsed borders mode I've looked at. There are still missing pieces and corners cut, but the outcome looks useful so far and paves the way for subsequent work to fully align with the specification.
Goes some way towards fixing #19647.
=> LibWeb: Some improvements for painting of collapsed table borders

Ports/imagemagick/package.sh
... to prevent linking against libs from build host. I.e. if Ports/fontconfig is already installed imagemagick tries to link against it in /usr/local/lib and fails to build.
Also removed superfluous --host parameter since this will already be added by ../.port_include.sh
Contributing to #18238
=> Ports/imagemagick: Added --with-sysroot

Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/Loader.cpp, Userland/Libraries/LibAudio/Loader.h, Userland/Libraries/LibAudio/MultiChannel.h
With this, we should be the most compliant decoder by numbers alone, with one mild crash and a few not-quite-right outputs, but no proper glitches or hard crashes.
A missing sign extension and a wrong data type broke these before.
Especially FLAC had an issue here before, but the loader infrastructure
itself wouldn't handle end of stream properly if the "available samples"
information didn't match up.
We downsample multi-channel files into stereo for now, which at least
makes the other channels listenable. The new multi-channel downmix
helper is intended to be used for other formats with the same or similar
channel arrangement, such as QOA.
=> LibAudio: Three fixes for spec compliance

Userland/Applications/Terminal/main.cpp
- Replace C with C++
- Use Core::System, Core::Account and Core::Process wrappers
- Remove DeprecatedString
- Remove invalid close() call to the pts file descriptor in the shell child (the fd cannot be valid there anymore since it's an automatically-closing fd, we just previously ignored this error)
=> Terminal: Modernize

Userland/Applications/SystemMonitor/ProcessModel.cpp, Userland/Applications/SystemMonitor/ProcessModel.h
SystemMonitor was reading a lot of process statistics data from the sysfs and procfs, and much of it was done non-optimally. This PR improves that by reducing normal SystemMonitor load over 50%.
- Don't reopen the process list file every time it is read. Opening files is not exactly the cheapest operation.
- Don't read a process's command line every update, and don't read a command line which we know we're not allowed to access. This is the big one, previously it accounted for close to 50% of total SystemMonitor runtime.
=> SystemMonitor: Improve performance via reduced file I/O

Meta/Lagom/Tools/CodeGenerators/LibWeb/CMakeLists.txt, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateAriaRoles.cpp, Userland/Applications/Browser/InspectorWidget.cpp, Userland/Applications/Browser/InspectorWidget.h, Userland/Applications/Browser/Tab.cpp, Userland/Libraries/LibWeb/ARIA/ARIAMixin.cpp, Userland/Libraries/LibWeb/ARIA/ARIAMixin.h, Userland/Libraries/LibWeb/ARIA/AriaData.cpp, Userland/Libraries/LibWeb/ARIA/AriaData.h, Userland/Libraries/LibWeb/ARIA/AriaRoles.json, Userland/Libraries/LibWeb/ARIA/RoleType.cpp, Userland/Libraries/LibWeb/ARIA/RoleType.h, Userland/Libraries/LibWeb/ARIA/StateAndProperties.cpp, Userland/Libraries/LibWeb/ARIA/StateAndProperties.h, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/DOM/Element.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWebView/AriaPropertiesStateModel.cpp, Userland/Libraries/LibWebView/AriaPropertiesStateModel.h, Userland/Libraries/LibWebView/CMakeLists.txt, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/WebContentClient.ipc, Userland/Services/WebContent/WebContentServer.ipc
This PR adds support for the WAI-ARIA role model. This allows us to determine what state and properties are supported/required/prohibited on a given element, as well as providing default values for some properties and state. You can view this information in the new ARIA tab on the widget inspector:
By doing this, we have now implemented the last major piece of the ARIA standards suite before we can start thinking about using this data outside the browser :^)
=> Browser: Implent the ARIA Role Model

.devcontainer/features/serenity/install.sh, Documentation/BuildInstructionsLadybird.md
Replaced the `gcc-12` requirement with that of `g++-12` because without `g++-12`+ (or `clang-15`+), Ladybird doesn't build.
Added `ccache` as a build requirement for QOL.
Synced up the Devcontainer `install.sh` and the Ladybird build instructions by adding the missing `qt6-multimedia-dev`.
https://github.com/SerenityOS/serenity/issues/19706
=> Ladybird+Meta: Minor build instruction modifications

Tests/LibWeb/Layout/expected/block-and-inline/percentage-padding-on-inline-block-with-indefinite-containing-block-size.txt, Tests/LibWeb/Layout/input/block-and-inline/percentage-padding-on-inline-block-with-indefinite-containing-block-size.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
When the containing block has an indefinite width, any descendants with a percentage size should resolve that against 0, not infinity.
Fixes an assertion failure when loading https://www.gnu.org/
=> LibWeb: Resolve inline-block percentage padding against 0, not infinity

Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/GenericTypes.cpp
The FLAC loader did not properly handle files in which there was no seek table. This PR fixes the following:
- Seek table would return a sample after the target seek point if there exists no seek point before the target.
- The FLAC loader would not skip samples forward to the target seek point if it determined that the loader's current position is closer to the target than the found seek point.
- The seek point distance calculation treated a missing previous seek point as a seek point at sample 0, meaning that it would never insert a seek point at 0.
- Seeking used a "tolerance" value to get close enough to the target sample, but we can just seek accurately to the frame containing the target sample instead.
**Old summary:**
> The FLAC loader would often fail to seek back to the start of …
=> LibAudio: Fixes for seeking in a FLAC file with no seek table

Ports/acpica-tools/patches/0001-Stop-compiler-warnings-on-dangling-pointer.patch
Extended the existing patch to cover all occurences of assigning &CurrentSp to a non-local variable. Keeps the Port build from failing.
Contributing to issue #18238
=> Ports/acpica-tools: Prevent dangling pointer compiler warning

Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/FlacLoader.h, Userland/Libraries/LibAudio/MultiChannel.h
- Pre-allocate and reuse sample decompression buffers. In many FLAC
files, the amount of samples per frame is either constant or the
largest frame will be hit within the first couple of frames. Also,
during audio output, we need to move and combine the samples from the
decompression buffers into the final output buffers anyways. Avoiding
the reallocation of these large buffers provides an improvement from
16x to 18x decode speed on strongly compressed but otherwise usual
input.
- Leave a FIXME for a similar improvement that can be made in the
residual decoder.
- Pre-allocate audio chunks if frame size is known.
- Use reasonable inline capacities in several places where we know the
maximum or usual capacity needed.
=> LibAudio: Optimize FlacLoader by avoiding allocations

Tests/LibCore/TestLibCoreStream.cpp, Userland/Libraries/LibCore/File.cpp, Userland/Libraries/LibCore/File.h
Keep track of a file offset to avoid performing a system call for tell().
=> LibCore: Optimize File::tell()

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Fetch/Body.cpp, Userland/Libraries/LibWeb/Fetch/FetchMethod.cpp, Userland/Libraries/LibWeb/FileAPI/Blob.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Userland/Libraries/LibWeb/HTML/Scripting/TemporaryExecutionContext.cpp, Userland/Libraries/LibWeb/HTML/Scripting/TemporaryExecutionContext.h, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
We've peppered this workaround around the code base as needed in a few
different ways. This adds a helper class to perform this workaround in
order to simplify doing so, and ensure cleanup occurs in a RAII fashion.
This also makes it easier to grep for places where this workaround is
employed.
=> LibWeb: Add a helper class to work around empty execution context stack

Userland/Libraries/LibJS/Runtime/Reference.h, Userland/Libraries/LibJS/Tests/operators/delete-basic.js
These are not strictly unresolvable references. Treating them as such fails an assertion in the `delete UnaryExpression` semantic (which is Reference::delete_ in our implementation) - we enter the unresolvable, which then asserts that the [[Strict]] slot of the reference is false.
AST test262 diff:
```
Diff Tests: +7 ✅  -6 ❌  -1 💥
test/language/expressions/assignment/target-super-computed-reference-null.js   ❌ -> ✅
test/language/expressions/assignment/target-super-identifier-reference-null.js ❌ -> ✅
test/language/expressions/delete/super-property-null-base.js                   💥 -> ✅
test/language/expressions/super/prop-dot-cls-null-proto.js                     ❌ -> ✅
test/language/expressions/super/prop-dot-obj-null-proto.js                     ❌ -> ✅ …
```
=> LibJS: Do not coerce nullish references to unresolvable references

Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
Since `max_fd_added` and `max_fd` are initialized to -1 and 0 respectively the former could never be greater than the latter.
=> LibCore: Remove some dead code in wait_for_events

Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Bytecode/Pass/LoadElimination.cpp, Userland/Libraries/LibJS/Forward.h, Userland/Libraries/LibJS/Runtime/Reference.cpp
Bytecode test262 diff:
```
Diff Tests:
test/language/expressions/delete/super-property-method.js    📝 -> ✅
test/language/expressions/delete/super-property-null-base.js 📝 -> ✅
test/language/expressions/delete/super-property.js           📝 -> ✅
```
We now pass all tests in `test/language/expressions/delete` in bytecode mode :)
=> LibJS/Bytecode: Generate bytecode for deleting super properties

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Using local variables to store function parameters makes Kraken tests
run 7-10% faster.
For now this optimization is limited to only be applied if:
- Parameter does not use destructuring assignment
- None of the function params has default value
- There is no access to "arguments" variable inside function body
```
stanford-crypto-aes.js               before: 2.93s  after: 2.62s
stanford-crypto-sha256-iterative.js  before: 1.80s  after: 1.66s
ai-astar.js                          before: 12.48s after: 11.34s
```
=> LibJS: Use local variables to store function parameters in some cases 

Userland/Libraries/LibC/string.cpp
`memcpy()` and `memmove()` are functionally equivalent if the source and destination memory regions do not overlap. If this is the case, we should prefer `memcpy()` as it's implemented in a simpler and faster way. As our `memcpy()` starts copying from the lowest address first, relaxing a `memmove()` call to `memcpy()` is safe if the destination
- starts at a lower address than the source
- starts at a higher address than the source's end
=> LibC: Relax `memmove()` to `memcpy()` in more cases

Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/BMPLoader.h, Userland/Libraries/LibGfx/ImageFormats/DDSLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/DDSLoader.h, Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/GIFLoader.h, Userland/Libraries/LibGfx/ImageFormats/ICOLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/ICOLoader.h, Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h, Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h, Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGLoader.h, Userland/Libraries/LibGfx/ImageFormats/PortableImageMapLoader.h, Userland/Libraries/LibGfx/ImageFormats/QOILoader.cpp, Userland/Libraries/LibGfx/ImageFormats/QOILoader.h, Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp, Userland/Libraries/LibGfx/ImageFormats/TGALoader.h, Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.h, Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoader.h
These methods are unused so let's remove them.
=> LibGfx: Remove `ImageDecoder::set_[non]volatile()`

Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Since AST interpreter switches to bytecode to execute generator functions, arguments stored in local variables always need to be initialized for such functions.
=> LibJS: Always init arguments stored in locals for generator functions

Userland/Utilities/headless-browser.cpp
On systems with the default ulimit for open files <= 256 (default on some systems) the LibWeb tests were crashing because the input file handles are not closed in headless-browser.
Explicit closing might not be the right way to solve the issue, I was not sure how exactly to debug why these are not correctly destructed (cpp knowledge lacking). Am of course willing to change this to a proper fix if someone has a pointer to what could be happening.
=> headless-browser: Ensure IPC::File is closed after sending

Tests/LibWeb/Layout/expected/abspos-not-replaced-multiple-auto-variants.txt, Tests/LibWeb/Layout/expected/flex-abspos-item-with-preceding-whitespace.txt, Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-align-items.txt, Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt, Tests/LibWeb/Layout/expected/position-absolute-from-edges.txt, Tests/LibWeb/Layout/input/abspos-not-replaced-multiple-auto-variants.html, Tests/LibWeb/Layout/input/flex-abspos-item-with-preceding-whitespace.html, Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-align-items.html, Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-justify-content.html, Tests/LibWeb/Layout/input/position-absolute-from-edges.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
The first commit in this PR changes slightly a few of the absolute positioning tests to highlight current bugs in the layouting. Many subtle errors were hidden by the 1px wide border and become more visible with thicker borders.
The screenshots at the bottom show the current behavior of those tests.
The subsequent commits implement the missing specification chapters that deal with replaced absolute elements, and attempt to fix some of the existing issues. 
The calculated insets and margins from the `compute_height_for_absolutely_positioned_replaced_element` & co were being ignored by the final method deciding the layout, `layout_absolutely_positioned_element`. This contained ad-hoc code that re-attempted to assign margins and insets. I have attempted to clean up the spec methods and …
=> LibWeb: Absolute positioning fixes

Tests/LibWeb/Layout/expected/abspos-with-percentage-insets.txt, Tests/LibWeb/Layout/input/abspos-with-percentage-insets.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
This makes cookie banner buttons show up on Linktree again. :^)
Regressed in fd37ad3a84e9330e89ce9aee22500e4c82144a8f
=> LibWeb: Resolve % top and bottom insets against containing block height

Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Parser.h, Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp, Userland/Libraries/LibJS/Tests/functions/function-default-parameters.js
This change fixes an issue where identifiers used in default function parameters were being "registered" in the function's parent scope instead of its own scope. This bug resulted in incorrectly detected local variables. (Variables used in the default function parameter expression should be considered 'captured by nested function'.)
To resolve this issue, the function scope is now created before parsing function parameters. Since function parameters can no longer be passed in the constructor, a setter function has been introduced to set them later, when they are ready.
Fixes crash on https://www.apple.com/
=> LibJS: Fix scope detection for ids in default function params

Userland/Libraries/LibArchive/CMakeLists.txt, Userland/Libraries/LibArchive/Zip.cpp, Userland/Libraries/LibArchive/Zip.h, Userland/Utilities/CMakeLists.txt, Userland/Utilities/zip.cpp
*This is a re-do of #18107.*
We now have helper functions in `ZipOutputStream` for adding files (via `AK::Stream`) to a zip. This should allow other applications to add files to a zip archive with ease (and not have to invoke `zip` when doing so).
The `zip` utility has been updated to use these new helpers.
=> LibArchive+zip: Add helper functions for adding members to a `ZipOutputStream`

Userland/Libraries/LibJS/Parser.cpp
Initially, the usage of local variables for parameters had to be disabled when default values were used because there was a bug that didn't allow to correctly find the scope to which identifiers used within the default parameter expression belonged, and hence correctly identify if a variable can be local. However, this bug was fixed in 2f85faef0ff1cc823d4021dd3f3af589d6fc850f, so now this restriction is no longer needed.
=> LibJS: Allow usage of locals if function parameters have default values

Userland/Services/SpiceAgent/main.cpp
Without this the spice agent can't create files on drag/drop.
=> SpiceAgent: Pledge cpath

Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/ICOLoader.cpp
**LibGfx/ICO: Fix an erroneous condition**
This is a remaining of the conversion to `ErrorOr` done in 492d5d7c.
**LibGfx/BMP: Move some `const` to the east**
=> LibGfx: 2 miscallenous patches

AK/Concepts.h, AK/Function.h, Tests/LibCore/CMakeLists.txt, Tests/LibCore/TestLibCorePromise.cpp, Userland/Applications/Browser/CookieJar.cpp, Userland/Libraries/LibCore/Forward.h, Userland/Libraries/LibCore/Promise.h, Userland/Libraries/LibCore/ThreadEventQueue.cpp, Userland/Libraries/LibIMAP/Client.cpp, Userland/Libraries/LibThreading/BackgroundAction.h, Userland/Services/WebDriver/Session.cpp
The previous iteration of this API was somewhat odd and rough in random places, which degraded usability and made less than perfect sense. This commit reworks the API to be a little closer to more conventional promise APIs (a la javascript promises).
Also adds a test to ensure the class even works.
cc @Zaggy1024.
=> LibCore: Slightly rework the Core::Promise API

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Since it is not possible for delete operator to return true when it is
applied to local variable, DeleteVariable can safely always return
false for locals.
This also fixes operators/delete-local-variable.js in test-js.
=> LibJS/Bytecode: Always return false on attempt to delete local variable

Tests/LibWeb/Layout/expected/table/border-conflict-resolution-with-col.txt, Tests/LibWeb/Layout/expected/table/borders.txt, Userland/Libraries/LibWeb/Layout/LayoutState.h, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.h
When using the collapsing border model, cells on either side of the edge get half the specified width of the border for their box model.
=> LibWeb: Adjust border widths for tables using collapsing borders

Meta/build-image-extlinux.sh, Meta/build-image-grub.sh, Meta/build-image-limine.sh, Meta/build-image-qemu.sh, Meta/build-native-partition.sh, Meta/build-root-filesystem.sh, Meta/shell_include.sh
This MR fixes the build scripts on Alpine w/o coreutils (and other distros without GNU and sudo :p)
Firstly, we depend on GNU-specific du switch `--apparent-size`. Busybox has
this implemented, but as `-b` instead.
Secondly, there's now logic to detect if your system has doas instead of sudo.
If the user has neither, we bail out quickly instead.
=> Meta: Improve portability with compat for non-GNU, non-sudo systems

Documentation/BuildInstructionsLadybird.md
The documentation for building Ladybird gives a list of packages to install under openSUSE, but is missing the Qt6 Multimedia development package, ``qt6-multimedia-devel``.
Include it.
=> Note that Ladybird build requires qt6-multimedia-devel on openSUSE

Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
In order to ease the removal of this function, let's provide a no-op default implementation so decoders can stop implementing it one by one.
First step of #19893
=> LibGfx: Provide a default implementation for `ImageDecoder::initialize`

Userland/Applications/Spreadsheet/JSIntegration.cpp, Userland/Applications/Spreadsheet/JSIntegration.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Executable.h, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Runtime/ArgumentsObject.cpp, Userland/Libraries/LibJS/Runtime/ArgumentsObject.h, Userland/Libraries/LibJS/Runtime/IndexedProperties.h, Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp, Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.h, Userland/Libraries/LibJS/Runtime/Object.cpp, Userland/Libraries/LibJS/Runtime/Object.h, Userland/Libraries/LibJS/Runtime/PropertyDescriptor.h, Userland/Libraries/LibJS/Runtime/ProxyObject.cpp, Userland/Libraries/LibJS/Runtime/ProxyObject.h, Userland/Libraries/LibJS/Runtime/TypedArray.h, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h, Userland/Libraries/LibWeb/HTML/Location.cpp, Userland/Libraries/LibWeb/HTML/Location.h, Userland/Libraries/LibWeb/HTML/WindowProxy.cpp, Userland/Libraries/LibWeb/HTML/WindowProxy.h
This has two steps:
1. We teach `Object::internal_get()` to inform callers about *where* the property was found. In this first version, we only reveal the property offset for own properties. Properties found in the prototype chain are ignored for now.
2. We give each `GetById` and `GetByIdWithThis` instruction a corresponding inline cache (stored in `Bytecode::Executable` so the instruction itself just has an index into a vector of caches). The cache remembers the last seen `JS::Shape` and property offset. When executed and the base object has the same shape as before, we reuse the property offset and call `Object::get_direct()`, bypassing the lookup machinery.
~23% speedup on Kraken/ai-astar.js (and many other tests) :^)
This is work towards #17984
=> LibJS: Inline caching for same-shape property accesses

AK/Array.h
We are copying here, so there is no need to require a non-const Span.
=> AK: Let `Array::from_span` take a readonly Span

Userland/Libraries/LibJS/AST.cpp
No need to create bindings for local variables as their values are not stored in an environment.
=> LibJS: Skip bindings creation for locals during block declaration init

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h
When building an object from an object expression, we don't want to go through the full property setting machinery. This patch adds a new `PropertyKind::DirectKeyValue` for `PutById` which guarantees that the property becomes an own property.
This fixes an issue where setting the `__proto__` property in object expressions wasn't working right.
12 new passes on test262. :^)
```
Summary:
Diff Tests:
+12 ✅    -12 ❌   
Diff Tests:
test/built-ins/Array/prototype/indexOf/15.4.4.14-9-b-i-6.js           ❌ -> ✅
test/built-ins/Array/prototype/lastIndexOf/15.4.4.15-8-b-i-6.js       ❌ -> ✅
test/intl402/Collator/taint-Object-prototype.js                       ❌ -> ✅
test/intl402/DateTimeFormat/taint-Object-prototype.js                 ❌ -> ✅
test/intl402/NumberFormat/taint-Object-prototype.js …
```
=> LibJS/Bytecode: Always make own properties in object expressions

Ports/alpine/package.sh, Ports/alpine/patches/0001-Update-pith-Makefile.in-to-compile-helpers-for-build.patch, Ports/alpine/patches/0002-Add-serenity-as-OS-type-in-Alpine.patch, Ports/alpine/patches/ReadMe.md
Required to ensure that all autogenerated files are compatible with the verions of autotools installed on the build system. Resolves SerenityOS/serenity#19891.
Verification:
* Rebuild alpine package from scratch (`cd Ports/Alpine; ./package.sh`) and ensured Alpine launched successfully.
* Equivalent patch tested by @BenWiederhake in #19891 on a system where the build previously failed (due to mismatch between libtool in the generated files and local build system).
=> Ports/alpine: Force re-generation of all autotools files after patch

Userland/Libraries/LibPDF/Encryption.cpp, Userland/Libraries/LibPDF/Reference.h
It's just two bugs.
With this and #19923:
```
% Build/lagom/bin/pdf ~/Downloads/pdf_reference_1-7.pdf 
1310 pages
Title: PDF Reference, version 1.7
Author: Adobe Systems Incorporated
Subject: Adobe Portable Document Format (PDF)
Creator: FrameMaker 7.2
Producer: Acrobat Distiller 7.0.5 (Windows)
Creation date: D:20061017081020Z
Modification date: D:20061118211043-02'30'
```
@mattco98
=> LibPDF: Fix enough issues that pdf_reference_1-7.pdf can be loaded by `pdf`

Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Document.cpp, Userland/Libraries/LibPDF/Document.h, Userland/Utilities/pdf.cpp
It'd be nicer to show this metadata in the GUI too at some point, probably behind an "I" info toolbar button in the PDF viewer, and maybe in a tab in the file viewer properties window.
@mattco98 for LibPDF.
@AtkinsSJ who might be interested in doing the GUI integration once this is in :)
=> LibPDF+pdf: Print PDF metadata

Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Fixes a couple of weirder interactions between justify-content and flex-direction related to reverse direction packing and how margins are set.
Before (ladybird & chromium):
After:
=> LibWeb: Fix flex & abspos alignment issues

AK/MemoryStream.cpp
**AK: Don't reuse chunks in `AllocatingMemoryStream`**
As confusing as it may sound, reusing them is terrible performance wise.
When profiling the PNG decoder, the result (which is dominated by the
Zlib decompression) shows that the `cleanup_unused_chunks()` function
represented 14.26% of the profile before this patch and only 7.7%
afterward.
On the same 6.5 Mo PNG image, it reduces the decompression time by more
than 5%.
**AK: Move chunks a single time in `cleanup_unused_chunks()`**
All elements of the vector were moved to the left, for each element to
remove. This patch make the function move each element exactly once.
On the same test case than the previous commit, it makes the function
disappear of the profile. These two commits combined reduce the
execution time by 12%.
---
cc …
=> AK: Rewrite `cleanup_unused_chunks` or how to optimize PNG decoding without touching LibGfx

Kernel/Syscalls/execve.cpp, Kernel/Tasks/Process.h, Userland/Libraries/LibELF/Image.cpp, Userland/Libraries/LibELF/Validation.cpp, Userland/Libraries/LibELF/Validation.h
Previously, we started parsing the ELF file again in a completely different place, and without the partial mapping that we do while validating.
Instead of doing manual parsing in two places, just capture the requested stack size right after we validated it.
=> Kernel: Consolidate finding the ELF stack size with validation

Kernel/FileSystem/FATFS/FileSystem.cpp, Kernel/FileSystem/FATFS/FileSystem.h
Resolves an issue where file system access to FAT file systems would result in hitting a `VERIFY_NOT_REACHED()` in `directory_entry_type_from_posix()`:
https://github.com/SerenityOS/serenity/blob/d7644d1d864d51244e552889173d70bdd6d9180d/Userland/Libraries/LibCore/DirectoryEntry.cpp#L36
This was the result of `FATFS` not implementing `FileSystem::internal_file_type_to_directory_entry_type` to convert its internal file types ("attributes" in FAT parlance) into the standard `DT_` types.
1. Created a FAT file system image using a loopback device.
2. Passed image to qemu by adding:
```
+SERENITY_BOOT_DRIVE="$SERENITY_BOOT_DRIVE -drive file=fat32.img,format=raw,index=2,media=disk"
```
4. Mounted file system with:
```
su
mkdir /tmp/fat
mount -t /dev/hda /tmp/fat
```
5. Verified that directory …
=> FileSystem/FATFS: Convert internal FAT inode attributes to dirent types

Kernel/CMakeLists.txt, Kernel/Memory/RingBuffer.h, Kernel/Net/NetworkingManagement.cpp, Kernel/Net/VirtIO/VirtIONetworkAdapter.cpp, Kernel/Net/VirtIO/VirtIONetworkAdapter.h
It can be exercised by setting `SERENITY_ETHERNET_DEVICE_TYPE=virtio-net-pci`.
=> Kernel: Add an initial implementation of virtio-net driver.

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp, Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
There were two issues here:
- Intersection observers were using an incorrectly offset viewport to check for intersections, causing them to fire at unexpected locations.
- `HTMLImageElement.complete` was not taking the state of the image requests into account.
=> LibWeb: Make images load on the Twinings website :^)

Base/usr/share/man/man1/ps.md, Userland/Utilities/ps.cpp
This PR adds the following options to `ps`:
* `-t`: Select processes associated with a given terminal. A space or comma separated list is used. Short or long form names can be used (i.e: `pts:0` or `/dev/pts/0`). This option can be specified multiple times.
* `--ppid`: Select processes with the given PPID. A space or comma separated list is used. This option can be specified multiple times.
This PR also changes the behavior of filtering options (`-p`, `-u`, `-t` and `--ppid`) so that they can be combined. For example, a command such as `ps -U anon -p 123` would select all processes associated with `anon` and PID 123. Combining the `-q` option with any of the aforementioned filtering options is now explicitly forbidden. These changes match the behavior of `ps` on Linux and FreeBSD.
Example …
=> ps: Add `-t` and `--ppid` options to filter by TTY and PPID

Tests/LibWeb/Layout/expected/cell-auto-max-width-table-percentage-width.txt, Tests/LibWeb/Layout/input/cell-auto-max-width-table-percentage-width.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Max width shouldn't be tied to min width, commit d33b99d went too far and made them the same when the table-root had a specified percentage width.
Fixes #19940.
=> LibWeb: Use max width from content for cells unless length is specified

Ports/quake/package.sh
Without this, the port failed to verify the download.
=> Ports: Add archive hash to Quake port

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
https://www.haiku-os.org/images/bg-page.png has a size of 0 for example.
Just ignoring the chunk instead of assuming that the image is sRGB and has Perceptual rendering intent matches what libpng does (cf `png_handle_sRGB()`), so let's do that too.
(All other chunk handlers are still strict about size.)
=> LibGfx/PNG: Make invalid sRGB chunk size non-fatal

Userland/Libraries/LibGfx/ImageFormats/PBMLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PGMLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PPMLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h, Userland/Libraries/LibGfx/ImageFormats/PortableImageMapLoader.h
**LibGfx/PortableFormat: Remove `PortableImageDecoderPlugin::initialize()`**
**LibGfx/PortableFormat: Extract header reading in its own function**
**LibGfx/PortableFormat: Simplify the State enum**
This enum used to store very precise state about the decoding process,
let's simplify that by only including two steps: HeaderDecoder and
BitmapDecoded.
**LibGfx/PortableFormat: Read the header during initialization**
=> LibGfx/PortableFormat: Refactor the plugin interface

Userland/Libraries/LibJS/Runtime/AbstractOperations.h, Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp, Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h, Userland/Libraries/LibJS/Runtime/MapConstructor.cpp, Userland/Libraries/LibJS/Runtime/MapConstructor.h, Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp, Userland/Libraries/LibJS/Runtime/ObjectConstructor.h, Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype-generic-functions.js, Userland/Libraries/LibJS/Tests/builtins/Map/Map.groupBy.js, Userland/Libraries/LibJS/Tests/builtins/Object/Object.groupBy.js
This got conditional stage 3 approval in today's TC39 meeting, including confirmation of the `groupBy` name.
=> LibJS: Re-implement the Array Grouping proposal as static methods

Userland/Libraries/LibCore/EventLoop.cpp
This keeps WebContent from staying open if it's spinning forever trying to load a page.
fixes #11854
=> LibCore: Exit EventLoop::spin_until() when exit requested

Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp
One scanline is width pixels long, not height pixels.
No measurable performance difference, but it annoys me every time I look at this file.
=> LibGfx/PNGWriter: Use a better limit for scanline capactiy

Tests/LibWeb/Layout/expected/block-and-inline/max-width-must-not-expand-element.txt, Tests/LibWeb/Layout/input/block-and-inline/max-width-must-not-expand-element.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
This fixes #18778. Using the availlable space as the used with cased it to be infinite and makes no sense.
=> LibWeb: Prevent max-with expanding the width

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/DocumentObserver.h, Userland/Libraries/LibWeb/SVG/SVGElement.cpp, Userland/Libraries/LibWeb/SVG/SVGUseElement.cpp
This prevents SVG elements referenced by "use" being repeatedly cloned in many redundant cases. 
This allows ladybird to load pages that use a large SVG "sprite" that then is referenced many times with "use" elements. (This would otherwise either load extremely slowly, or crash the page.)
=> LibWeb: Remove many redundant SVGUseElement clone calls

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Executable.h, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Parser.h, Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp, Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h, Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
Using a special instruction to access global variables allows skipping the environment chain traversal for them and going directly to the module/global environment. Currently, this instruction only caches the offset for bindings that belong to the global object environment. However, there is also an opportunity to cache the offset in the global declarative record.
This change results in a 57% increase in speed for imaging-gaussian-blur.js in Kraken.
=> LibJS: Add optimized GetGlobal instruction to access global variables

AK/Error.h
...instead of manually marking all methods returning Error nodiscard.
No real behavior change.
=> AK: Mark Error nodiscard

Userland/Libraries/LibPDF/Error.h
No behavior change. Prevents mistakes like the one fixed in 26de2fd0b2.
=> LibPDF: Mark PDF::Error nodiscard

Userland/Libraries/LibPDF/Reader.h
With this, looking at page 2 of pdf_reference_1-7.pdf no longer crashes.
Why did it crash in the first place? Because due to this bug, CFF.cpp failed to parse the font program for the font used to render the `®` character. `Renderer::render()` adds all errors that are encounterd to an `errors` object but continues rendering. That meant that the previous font was still active, and that didn't have a width for that symbol in its width table.
SimpleFont::draw_string() falls back to get_glyph_width() if there's no entry for a character for a symbol. `Type1Font::get_glyph_width()` always dereferences `m_font` in that method, even if the font has a font program (and m_font is hence nullptr).
With the off-by-one fixed, the second font is successfully installed as current font, and the second …
=> LibPDF: Fix off-by-one in Reader

Userland/Applications/MailSettings/MailSettingsWidget.cpp
The window by default showed port 993 with TLS unchecked, which was slightly misleading as port 993 uses implicit TLS connections and cleartext is on port 143.
This change also makes it consistent with the Mail app, as its fallback value is also set to true:
https://github.com/SerenityOS/serenity/blob/c006a1ef41b2d7b4920e6513671c3cb6d3b9b4e5/Userland/Applications/Mail/MailWidget.cpp#L110-L112
=> MailSettings: Make TLS option checked by default

Userland/Libraries/LibJS/Bytecode/Register.h
A trivial change for 2% speed-up on Kraken/ai-astar.js :^)
=> LibJS/Bytecode: Make Bytecode::Register constexpr

Userland/Libraries/LibJS/Runtime/Iterator.cpp, Userland/Libraries/LibJS/Runtime/Iterator.h, Userland/Libraries/LibJS/Runtime/IteratorConstructor.cpp, Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.from.js
This is a normative change in the Iterator Helpers spec. See:
https://github.com/tc39/proposal-iterator-helpers/commit/3e275cf
=> LibJS: Avoid creating String object wrappers in iterator helpers

Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp, Userland/Libraries/LibGfx/ImageFormats/TGALoader.h
~~Depends on #19894.~~ Merged!
Contributes to #19893
---
**LibGfx/TGA: Default initialize the `TGAHeader` in the context**
**LibGfx/TGA: Make `TGAImageDecoderPlugin::decode_tga_header()` fallible**
**LibGfx/TGA: Decode the header in `create()` and remove `initialize()`**
**file: Register the "image/x-targa" mime-type**
=> LibGfx/TGA: Refactor the plugin interface

Userland/Libraries/LibJS/Runtime/Iterator.cpp, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.from.js, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.flatMap.js
Matches other usages in e.g. Temporal now.
=> LibJS: Change error message for non-objects in GetIteratorFlattenable

Userland/Libraries/LibIPC/File.h, Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp, Userland/Utilities/headless-browser.cpp
This prevents fd leaks when the user of the API forgets to pass CloseAfterSending to IPC::File. Since we are calling leak_fd in the constructor, we want it to also take care of closing.
Fixes at least 1 leak in `WebContentView::notify_server_did_request_file` that causes ladybird to silently crash / not load anymore after loading `ulimit -a` files from disk (256 or 2048 seem to be popular defaults).
This is a better fix related to the fd leak in headless-browser that was crashing the tests if the open file limit was 256, (PR #19853).
=> LibIPC: Do not leak the Core::File fd by default

Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
We now track it in the graphics state. It isn't used for anything yet. Fixes the one thing that rendering the first 100 pages of pdf_reference_1-7.pdf complains about.
=> LibPDF: Implement set_flatness_tolerance

Userland/Libraries/LibJS/Parser.cpp
This change speeds up the process of checking variable declaration within the scope by replacing the iteration through all declared variables (without the ability to exit early from the loop) with hash map lookups.
This change cuts google maps loading by 17s on my computer.
=> LibJS: Speed up has declaration check in ScopePusher

Tests/LibGfx/TestRect.cpp, Userland/Libraries/LibGfx/Rect.h, Userland/Libraries/LibWeb/Dump.cpp, Userland/Libraries/LibWeb/Layout/LayoutState.cpp, Userland/Libraries/LibWeb/Layout/LineBox.h, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.h, Userland/Services/WebContent/PageHost.cpp
Fixes the clipping of fundraising amounts on https://haiku-os.org/
(Yes, the text is still in the wrong place, but that's a separate issue :^)
Before:
After:
=> LibGfx+LibWeb: Improve scrollable overflow measurement + fix old stacking context clipping bug

Userland/Libraries/LibXML/Parser/Parser.cpp
Previously here missed a equal sign parsing, which will break XML file parsing.
=> LibXML: Parser handle standalone declaration

Userland/Utilities/less.cpp
This PR makes 2 changes to less related to signal handling:
* The original terminal state is now restored when a `SIGTERM` is received, in the same way that it is when you exit the program normally.
* `SIGINT` is now ignored. This matches the behavior of `less` on Linux and FreeBSD.
Before:
https://github.com/SerenityOS/serenity/assets/2817754/0807e2f0-e21c-4974-8d76-6da7e80ab9c3
After:
https://github.com/SerenityOS/serenity/assets/2817754/fd66bf6b-3bf8-4f46-86bc-b29ee4c980f0
=> less: Restore original terminal state when SIGTERM is received

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Runtime/EnvironmentCoordinate.h, Userland/Libraries/LibJS/Runtime/GlobalEnvironment.cpp, Userland/Libraries/LibJS/Runtime/Reference.cpp
This optimization was no longer helpful after the bug fix for missing invalidation on global delete was introduced in 331f6a9e6, since we now have to check bindings for presence in the global environment every time anyway.
Since the bytecode VM now has fast GetGlobal in most cases, let's not even worry about this and just remove the unhelpful "optimization".
In fact, removing this is actually an *optimization*, since we avoid a redundant has_binding() check on every global variable access. :^)
=> LibJS: Remove unhelpful environment lookup optimization for globals

Userland/Libraries/LibDiff/Applier.cpp, Userland/Libraries/LibDiff/Applier.h, Userland/Libraries/LibDiff/CMakeLists.txt, Userland/Libraries/LibDiff/Forward.h, Userland/Libraries/LibDiff/Hunks.cpp, Userland/Libraries/LibDiff/Hunks.h, Userland/Libraries/LibFileSystem/FileSystem.cpp, Userland/Libraries/LibFileSystem/FileSystem.h, Userland/Utilities/CMakeLists.txt, Userland/Utilities/patch.cpp
This is still very bare bones, and there is _much_ more to still
handle. However, this implements enough functionality to parse a single
unified patch read from stdin, and apply it to a file.
=> patch: Add the beginnings of a patch utility

Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Defer conversion to device pixels until we need to paint. This helps borders of cells with different spans align, since rounding early makes addition non-associative.
=> LibWeb: Compute border rectangles using CSSPixels

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Executable.h, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Bytecode/RegexTable.cpp, Userland/Libraries/LibJS/Bytecode/RegexTable.h, Userland/Libraries/LibJS/CMakeLists.txt
The `RegExpLiteral` AST node already has the parsed `regex::Parser::Result` so let's plumb that over to the bytecode executable instead of reparsing the regex every time `NewRegExp` is executed.
~12% speed-up on language/literals/regexp/S7.8.5_A2.1_T2.js in test262.
=> LibJS/Bytecode: Don't reparse regular expressions on instantiation

Tests/LibWeb/Layout/expected/grid/item-span-exceeds-columns-size.txt, Tests/LibWeb/Layout/input/grid/item-span-exceeds-columns-size.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
This change implements following paragraph from placement algorithm in the spec:
"If the largest column span among all the items without a definite column position is larger than the width of the implicit grid, add columns to the end of the implicit grid to accommodate that column span."
There were places in the grid implementation code with copies of this text, but those were completely unrelated to the code where they were being pasted so I removed them.
Fixes infinite spinning on https://www.thunderbird.net/en-GB/
=> LibWeb: Adjust grid columns size to fit spanning items

Userland/Libraries/LibPDF/Document.cpp, Userland/Libraries/LibPDF/Document.h, Userland/Libraries/LibPDF/ObjectDerivatives.cpp, Userland/Utilities/pdf.cpp
This now prints the page stream's dict in addition to the stream contents, and also all objects referenced from there.
Demo (note how it prints the font and procset referenced from the page object):
```
% time Build/lagom/bin/pdf --dump-contents ~/Downloads/sample.pdf
obj 4 0
<<
/Contents 5 0 R
/Type /Page
/Resources   <<
/Font     <<
/F1 9 0 R
>>
/ProcSet 8 0 R
>>
/MediaBox [
0
0
612
792
]
/Parent 3 0 R
>>
endobj
obj 5 0
<<
/Length 1074
>>
stream
2 J
BT
0 0 0 rg
/F1 0027 Tf
57.3750 722.2800 Td
( A Simple PDF File ) Tj
...snip...
69.2500 557.1360 Td
( text. And more text. And more text. Even more. Continued on page 2 ...) Tj
ET
endstream
endobj
obj 9 0
<<
/Type /Font
/Encoding /WinAnsiEncoding
/Subtype /Type1
/BaseFont /Helvetica
/Name /F1
>>
endobj
obj 8 0
[
/PDF
/Text
]
endobj
```
=> pdf: Make --dump-contents print all objects referenced by a given page

Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp, Userland/Libraries/LibJS/Runtime/PrimitiveString.h
When someone calls PrimitiveString::utf16_string() on a rope string, we know for sure that the client wants a UTF-16 string and may not be interested in a UTF-8 version at all.
To avoid round-tripping through UTF-8 in this scenario, callers can now inform resolve_rope_if_needed() about their preferred encoding, should rope resolution take place. The UTF-16 case is actually a lot simpler than the UTF-8 case, since we can simply ask for UTF-16 data for each fiber of the rope, and then concatenate all the fibers.
Since LibJS always uses UTF-16 for regular expression matching, this avoids round-tripping through UTF-8 whenever the input to a regex test is already UTF-16. :^)
=> LibJS: Resolve rope strings directly to UTF-16 when preferable

.github/workflows/cmake.yml, Meta/gn/build/toolchain/BUILD.gn, Meta/gn/secondary/Ladybird/BUILD.gn, Meta/gn/secondary/Meta/Lagom/Tools/CodeGenerators/LibWeb/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibIPC/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibWeb/ARIA/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn, Meta/lint-ci.sh, Meta/lint-gn.sh
This adds an app bundle to the gn build for ladybird.  It includes all the libraries, dependent apps and resource files. 
One can now open the ladybird.app app bundle on macOS, use Xcode tools like Instruments on the applications in the app bundle, and even install the app bundle into /Applications :^)
As I asked on the gn mailing list, there's no real "nice" way to currently bundle all the dependent libraries without listing them twice. Perhaps @nico will have a simpler solution :^)
https://groups.google.com/a/chromium.org/g/gn-dev/c/qU5xchay4OE
=> Meta: Add a macOS bundle to gn build for ladybird 

Tests/LibWeb/Layout/expected/css-logical-inset-properties.txt, Tests/LibWeb/Layout/input/css-logical-inset-properties.html, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This patch adds the following properties:
- `inset-inline`
- `inset-inline-start`
- `inset-inline-end`
- `inset-block`
- `inset-block-start`
- `inset-block-end`
Visual progression on https://thunderbird.net/
Before:
After:
=> LibWeb: Add logical CSS properties for insets

Userland/Libraries/LibJS/Runtime/Object.h, Userland/Libraries/LibWeb/DOM/Node.h
Solves problem that is<DOM::Node, JS::Object>() is quite hot in profiles while loading https://www.postgresql.org/about/featurematrix/.
=> LibJS+LibWeb: Add fast_is<DOM::Node> for JS::Object

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Runtime/VM.cpp, Userland/Libraries/LibJS/Runtime/VM.h, Userland/Libraries/LibJS/SourceTextModule.h
this is my first time doing something with the browser engine, so I am not sure if this is the correct implementation(getting the actual import.meta is taken from ast), or if it was ok that I removed ``Badge<MetaProperty>`` from set_import_meta, I removed it because and it was causing a compilation issue and it doesn't seem to do anything.
all import.meta tests now pass for bytecode
=> LibJS: implement import.meta for bytecode

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
Contributes to #19893 and fixes #19815
---
**LibGfx/JPEG: Remove the unused method `initialize()`**
**LibGfx/JPEG: Decode the header in `create()`**
=> LibGfx/JPEG: Refactor the plugin interface

Userland/Libraries/LibGfx/ImageFormats/QOILoader.cpp, Userland/Libraries/LibGfx/ImageFormats/QOILoader.h
Contributes to #19893 
---
**LibGfx/QOI: Remove useless parameters from member functions**
Both `decode_[header,image]_and_update_context()` used to take a
`Stream&` as parameter, but they are always called with the field
`m_context.stream` so no need to take it as a parameter.
**LibGfx/QOI: Decode the header in `create()` and remove `initialize()`**
=> LibGfx/QOI: Refactor the plugin interface

Userland/Libraries/LibPDF/Encryption.cpp, Userland/Libraries/LibPDF/Encryption.h
This detects AESV3, and copies over the spec comments explaining what needs to be done, but doesn't actually do it yet.
AESV3 is technically PDF 2.0-only, but
https://cipa.jp/std/documents/download_e.html?CIPA_DC-007-2021_E has a 1.7 PDF that uses it.
Previously we'd claim that we need a password to decrypt it. Now, we cleanly crash with a TODO() \o/
=> LibPDF: Some preparatory work for AESV3

Userland/Applications/ImageViewer/ViewWidget.cpp, Userland/Applications/ImageViewer/ViewWidget.h, Userland/Applications/ImageViewer/main.cpp, Userland/Libraries/LibGUI/FileSystemModel.cpp, Userland/Libraries/LibGfx/AffineTransform.cpp, Userland/Libraries/LibGfx/AffineTransform.h, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h, Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.h, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/VectorGraphic.cpp, Userland/Libraries/LibGfx/VectorGraphic.h
This PR updates `ImageViewer` to fully support vector graphics, and display them nicely at any size (while flipping or rotating them):
https://github.com/SerenityOS/serenity/assets/11597044/d3e28474-7817-4079-b1a5-69539e2461e7
It also improves thumbnails for vector graphics (by passing the ideal size while requesting the bitmap).
All (currently one format) vector graphics in LibGfx now implement `Gfx::VectorGraphic`, which allows generically handling them (similar to `Gfx::Bitmap`), though currently this class is ultra bare-bones.
=> LibGfx+LibGUI+ImageViewer: Support displaying vector graphics (at arbitrary scales) 

Userland/Applications/FileManager/PropertiesWindow.cpp, Userland/Applications/FileManager/PropertiesWindow.h, Userland/Libraries/LibGUI/RegularEditingEngine.cpp, Userland/Libraries/LibGUI/TextEditor.cpp, Userland/Libraries/LibGUI/VimEditingEngine.cpp
**LibGUI: Don't call `on_escape_pressed` from EditingEngines**
The call will be handled in `TextEditor::keydown_event`, just after that
`EditingEngine::on_key()` is called.
**LibGUI: Bubble up Key_Escape if no hook is plugged in TextEditor**
The TextEditor widget was always accepting the Key_Escape event, even if
the `on_escape_pressed` was empty. In other words, it was discarding the
event.
This behavior prevented shortcuts to be activated at a higher level.
**FileManager: Return a StringView from PropertiesWindow::get_description**
**FileManager: Exit the properties window on escape**
=> FileManager: Close the properties window on escape

Userland/Libraries/LibRegex/RegexByteCode.cpp
This simple change is a nice 9% speedup on the regex test suite :^)
=> LibRegex: Still milking for performance :P

Userland/Libraries/LibPDF/ObjectDerivatives.cpp
DeprecatedString::substring() makes a copy of the substring.
Instead, use a StringView, which can make substring views in constant
time.
Reduces time for `pdf --dump-contents image-based-pdf-sample.pdf` to
2.2s (from not completing for 1+ minutes).
That file contains a 221 kB jpeg.
Find it on the internet here:
https://nlsblog.org/wp-content/uploads/2020/06/image-based-pdf-sample.pdf
=> LibPDF: Fix quadratic runtime in stream dumping

Userland/Libraries/LibJS/Bytecode/BasicBlock.h, Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
If the exception from the `try` block has already been caught by `catch`, we need to clear the saved exception before entering `finally` so that ContinuePendingUnwind will not re-throw it.
9 new passes on test262 :^)
```
Summary:
Diff Tests:
+9 ✅    -9 ❌   
Diff Tests:
test/built-ins/Array/fromAsync/non-iterable-input-does-not-use-array-prototype.js ❌ -> ✅
test/language/statements/try/S12.14_A10_T2.js                                     ❌ -> ✅
test/language/statements/try/S12.14_A10_T3.js                                     ❌ -> ✅
test/language/statements/try/S12.14_A11_T2.js                                     ❌ -> ✅
test/language/statements/try/S12.14_A11_T3.js                                     ❌ -> ✅
test/language/statements/try/S12.14_A12_T2.js                                     ❌ …
```
=> LibJS/Bytecode: Do not rethrow caught exception from `finally`

Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibCore/MimeData.h, Userland/Utilities/file.cpp
Currently we have three lists, the first one associate mime-types to file extension, the second one to magic bytes and the last one to a small description.
This PR merge these three lists.
cc @AtkinsSJ, @vkoskiv
=> LibCore: Untriplicate the mime-type list

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/Instruction.h, Userland/Libraries/LibJS/Bytecode/Op.cpp, Userland/Libraries/LibJS/Bytecode/Op.h, Userland/Libraries/LibJS/Bytecode/Pass/GenerateCFG.cpp, Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp, Userland/Libraries/LibJS/Runtime/AsyncGenerator.h, Userland/Libraries/LibJS/Runtime/AsyncGeneratorPrototype.cpp, Userland/Libraries/LibJS/Runtime/AsyncGeneratorPrototype.h, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Userland/Libraries/LibJS/Tests/builtins/AsyncGenerator/AsyncGenerator.prototype.next.js, Userland/Libraries/LibJS/Tests/builtins/AsyncGenerator/AsyncGenerator.prototype.return.js, Userland/Libraries/LibJS/Tests/builtins/AsyncGenerator/AsyncGenerator.prototype.throw.js
Bytecode diff:
```
Summary:
Diff Tests:
+3960 ✅ (8.018%) +32 ❌ (0.064%) -3992 📝 (8.082%)
```
Tests passing: 47122/49388 (95.4%)
AST diff:
```
Summary:
Diff Tests:
+3964 ✅ (8.026%) +27 ❌ (0.056%) +1 💥️ (0.002%) -3992 📝 (8.082%)
```
Tests passing: 47322/49388 (95.8%)
https://www.youtube.com/watch?v=_ovdm2yX4MA
=> LibJS/Bytecode: Implement async generators

Userland/Libraries/LibWeb/Painting/Paintable.cpp, Userland/Libraries/LibWeb/Painting/Paintable.h, Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Since we deliberately skip positioned elements in `paint_descendants()`, we have to make sure we actually paint them in the subsequent `paint_internal()` pass.
Before this change, we were only painting positioned elements whose paintable was a `PaintableBox`, neglecting inline-level relpos elements.
Visual progression on https://thunderbird.net/
Before:
After:
=> LibWeb: Paint relatively positioned inline-level elements

Userland/Libraries/LibGfx/Bitmap.h, Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoader.h
**LibGfx/WebP: Decode the first chunk in `create()`**
And remove `initialize()`.
**LibGfx/WebP: Remove a typo**
:redthakis:
**LibGfx: Register WebP as a supported image format**
Basically, it means that we now render a thumbnail for WebP images.
---
cc @nico
=> LibGfx/WebP: Refactor the plugin interface

Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/GIFLoader.h
**LibGfx/GIF: Don't read the header twice**
This is already done in `load_gif_frame_descriptors()`. As the method
`initialize()` is now empty, we can delete it.
**LibGfx/GIF: Only use a `FixedMemoryStream`**
This allows us to drop the data pointer in the `GIFLoadingContext`.
**LibGfx/GIF: Move the code to read the header to its own function**
By header, I include the logical screen descriptor here, so all the
information that is not specific to each frame.
**LibGfx/GIF: Decode the header in `create()`**
Again, header includes the logical screen descriptor here. This is done
as a part of #19893.
=> LibGfx/GIF: Refactor the plugin interface

AK/URL.cpp, AK/URLParser.cpp, AK/URLParser.h, Tests/AK/TestURL.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp, Userland/Libraries/LibWeb/Fetch/Request.cpp, Userland/Libraries/LibWeb/Fetch/Response.cpp, Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp, Userland/Libraries/LibWeb/HTML/Location.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Userland/Libraries/LibWeb/URL/URL.cpp, Userland/Libraries/LibWeb/URL/URL.h, Userland/Utilities/xml.cpp
Add an interface for `concept-url-parser` as a step towards implementing the File API spec "Blob URL store"
Also implement steps for state override in URL parser while we are at it .
=> LibWeb: Add interface for 'concept-url-parser'

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
**LibJS/Bytecode: Do not unwind eagerly after throwing `Await`**
If an exception was thrown while evaluating the argument of an `await` expression, we should jump to the continuation block instead of eagerly rejecting the caller async function.
This restores the behavior prior to the addition of the separate `Await` instruction in d66eb4e3.
**LibJS/Bytecode: Correctly rethrow exception in `await` expression**
We were implicitly converting the throw completion's value into a normal completion in `AsyncFunctionDriverWrapper::continue_async_execution`, which meant the routine generated by `generate_await` didn't know that the value had to be thrown when execution resumed.
Without this change, we mistakenly pass 13 tests for `Array.fromAsync`, which we do not implement yet. But even with that …
=> LibJS/Bytecode: Correctly rethrow exception in `await` expression

Tests/LibWeb/Layout/expected/transform-calc-length-values.txt, Tests/LibWeb/Layout/input/transform-calc-length-values.html, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/Painting/StackingContext.cpp
There are two parts to this fix:
- First, StyleProperties::transformations() would previously omit calc() values entirely when returning the list of transformations. This was very confusing to StackingContext which then tried to index into the list based on faulty assumptions. Fix this by emitting calc values.
- Second, StackingContext::get_transformation_matrix() now always calls resolve() on length-percentages. This takes care of actually resolving calc() values. If no reference value for percentages is provided, we default to 0px.
This stops LibWeb from asserting on websites with calc() in transform values, such as https://qt.io/ :^)
Here's what the Qt website looks like after it loads. Not awful, but we've got more work to do 😅
=> LibWeb: Resolve calc() values in CSS transform

Tests/LibWeb/Layout/expected/block-and-inline/inline-block-with-max-width-fit-content.txt, Tests/LibWeb/Layout/input/block-and-inline/inline-block-with-max-width-fit-content.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
This fixes an issue where `max-width: fit-content` (and other layout-dependent values) were treated as 0 on inline-blocks.
Visual progression on https://qt.io/
Before:
After:
=> LibWeb: Fully resolve max-width values on inline-block elements

Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Subtract the scroll offset translation from the position when checking for intersection between boxes within fixed position nodes.
This fixes not working clicking on button inside header on https://webengineshackfest.org/2023/, https://www.igalia.com/ and many other websites.
=> LibWeb: Fix hit testing for fixed position nodes

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h
This function became unused after the only place where it was used was refactored in  7af7e90e3f148954b77e07d05bf679fab9ab3bba
=> LibJS: Delete for_each_lexical_function_declaration_in_reverse_order()

AK/Format.h, Userland/Applications/FileManager/DirectoryView.cpp, Userland/Libraries/LibC/stdio.cpp
As (briefly) discussed in #19607. For applications that we don't run inside Terminal, any logged warn()s and warnln()s are lost, which could be useful for debugging. People had to remember to add a duplicate `dbgln()` call any time they wanted to see the error in the console.
So, let's print all warnings to the debug console too!
Specifically, this makes `warn()` and `warnln()` send the same output to the debug console. I experimented with instead intercepting `stderr` output in `vout()`, which seems cleaner and more thorough, but it would panic the kernel every time I booted, so I gave up on that. :sweat_smile:
=> AK: Automatically copy all warn/warnln logs to debug console

Tests/LibWeb/Layout/expected/svg-transforms-and-viewboxes.txt, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/Path.h
See commits for details. Using beziers for arcs greatly simplifies transforming paths. 
This fixes a few cases that have bugged me for a while (and probably more I've not spotted):
|                                      | Before                                                                                                                              | After                                                                                                                               |
|--------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------| …
=> LibGfx: Approximate elliptical arcs with cubic beziers (and fix transforming arcs)

Tests/LibWeb/Layout/expected/block-and-inline/inline-block-with-percentage-height-and-auto-height-of-containing-block.txt, Tests/LibWeb/Layout/input/block-and-inline/inline-block-with-percentage-height-and-auto-height-of-containing-block.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
If an inline-block has a percentage height that relies on the auto height of the containing block, it should always resolve to the automatic height of the box, regardless of the percentage value. This change may seem confusing, but it aligns with the behavior of other engines.
This change resolves the issue of non-clickable links in the header of https://www.alpinelinux.org/
=> LibWeb: Fix inline-block percentage height calculation

Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp, Userland/Libraries/LibJS/Runtime/ArrayConstructor.h, Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h, Userland/Libraries/LibJS/SourceTextModule.cpp, Userland/Libraries/LibJS/Tests/builtins/Array/Array.fromAsync.js
Diff Tests:
+90 ✅    -90 ❌
There are four failing tests that are left failing in test262 that I have tried debugging. They are all likely for the same reason:
```
test262/test/built-ins/Array/fromAsync/asyncitems-array-add-to-singleton.js
test262/test/built-ins/Array/fromAsync/asyncitems-array-mutate.js
test262/test/built-ins/Array/fromAsync/asyncitems-array-remove.js
test262/test/built-ins/Array/fromAsync/asyncitems-array-add.js
```
The issue seems potentially related to the spec bug, as all of the tests that fail are going through that same code path as that spec issue. It could also be bytecode/ast related? Spent quite a while debugging that one, but don't have much of idea of what root cause would be as of yet.
=> LibJS: Implement Array.fromAsync

Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
Added the spec copy for array splice to the method.
Tweaked variable names and logic to align closer with the specs.
=> LibJS: Align array splice with spec

Meta/build-image-extlinux.sh, Meta/build-image-grub.sh, Meta/build-image-limine.sh, Meta/build-image-qemu.sh, Meta/build-native-partition.sh
fddbd11baa97295d903834bacf7280857256b1ba made it so the command executed read `sh -c -- '"script" args*'`, the -- in this command is redundant as the script name never starts with a dash and can never be interpreted as an option or a flag.
The actually meaningful placement for -- here is after `$SUDO`, to make sure `$SUDO` does not incorrectly treat `-c` as an option to itself, and `$SHELL` cannot be interpreted as an option/flag in the extremely unlikely event that it starts with a dash.
=> Meta: Pass -- to sudo instead of '$SHELL -c' in build scripts

Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.h
**LibGfx/TinyVG: Decode the header in `create()` and remove `initialize()`**
---
cc @MacDue
~~This will unfortunately conflict with #19870, I tried to cherry-pick the commit: [LibGfx: Lazily load TinyVG image data](https://github.com/SerenityOS/serenity/pull/19870/commits/80d2aa4b4fa9e15d56c369758f9319441db6de97), but it depends on previous commit of the same PR.~~ Rebased!
=> LibGfx/TinyVG: Refactor the plugin interface

Userland/Libraries/LibJS/Print.cpp, Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp, Userland/Libraries/LibJS/Runtime/GeneratorObject.h, Userland/Libraries/LibJS/Runtime/GeneratorPrototype.cpp, Userland/Libraries/LibJS/Runtime/IteratorHelper.cpp, Userland/Libraries/LibJS/Runtime/IteratorHelper.h, Userland/Libraries/LibJS/Runtime/IteratorHelperPrototype.cpp, Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.drop.js, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.filter.js, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.flatMap.js, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.map.js, Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.take.js
This is the last piece of the Iterator Helpers proposal.
```
Diff Tests:
+20 ✅  -20 📝 
```
=> LibJS: Implement %IteratorHelperPrototype%.return

Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/BMPLoader.h, Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
**LibGfx: Don't assume that image decoder plugin creation succeeds**
An image with an incorrect header should fail at this step, so we have
to handle that without crashing.
**LibGfx/BMP: Decode the header in `create()` and remove `initialize()`**
=> LibGfx/BMP: Refactor the plugin interface

Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibGfx/ImageFormats/DDSLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/DDSLoader.h
**LibGfx/DDS: Don't double-check the magic number**
This is already done in `decode_dds()`.
**LibGfx/DDS: Only use a `FixedMemoryStream`**
This allows us to drop the data pointer in the `DDSLoadingContext`.
**LibGfx/DDS: Save the format in the context**
This allows us to simplify the signature of a few functions.
**LibGfx/DDS: Move the code to read the header in its own function**
**LibGfx/DDS: Prefer `static constexpr Array` over `Vector<u32>`**
**LibGfx/DDS: Read the header in `create()` and remove `initialize()`**
**LibCore: Register the image/vnd.ms-dds mime type**
=> Userland+LibGfx: Register the dds mime-type and give the DDS decoder a little refresh

AK/URLParser.cpp, Tests/AK/TestURL.cpp
This is just a straight (and fairly inefficient) implementation of IPv6 parsing and serialization from the URL spec.
Note that we don't use AK::IPv6Address here because the URL spec requires a specific serialization behavior.
=> AK: Implement IPv6 host parsing in URLParser

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGLoader.h
**LibGfx/PNG: Use PNG specific vocabulary over a generic name**
**LibGfx/PNG: Don't try to guess if IHDR has been decoded**
**LibGfx/PNG: Decode the header in `create()` and remove `initialize()`**
This is done as a part of #19893. As `create()` is now the last user of
`decode_png_ihdr()`, we can easily make it return an `ErrorOr`.
**LibGfx/PNG: Don't use a loop to read chunks in `decode_png_ihdr()`**
This chunk is the first one, so we can remove that loop.
**LibGfx/PNG: Reject files that doesn't start with a IHDr chunk**
**LibGfx/PNG: Remove the useless `HeaderDecoded` state**
=> LibGfx/PNG: Refactor the plugin interface

Tests/LibWeb/Layout/expected/flex/flex-item-min-width-fit-content.txt, Tests/LibWeb/Layout/input/flex/flex-item-min-width-fit-content.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
We do this by piggybacking on `FormattingContext` helpers instead of reinventing the wheel in `FlexFormattingContext`.
This fixes an issue where `min-width: fit-content` (and other layout-dependent values) were treated as 0 on flex items.
This makes the cookie banners look okay on https://microsoft.com/ :^)
Before:
After:
=> LibWeb: Fully resolve min- and max-sizes for flex items

Userland/Libraries/LibJS/Tests/syntax/async-await.js
This test passes when running in the AST interpreter, but fails when running for bytecode.
=> LibJS/Tests: Add a test for an async function which returns a thenable

Base/res/html/misc/background-position-xy.html, Tests/LibWeb/Text/expected/background-position-xy.txt, Tests/LibWeb/Text/input/background-position-xy.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
When specifying `background-position-x: right` or `background-position-y: bottom` the case where no offset value was provided did not work.  This now creates the EdgeStyleValue setting the edge with an offset of 0 pixels.
Test added, but the output is identical with and without this fix as it does not include information about the background-position-xy offset.
=> LibWeb: Create EdgeStyleValue for BackgroundPositionXY with no offset

Userland/Libraries/LibWeb/Layout/LineBox.cpp, Userland/Libraries/LibWeb/Layout/LineBox.h, Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
The LineBoxFragment::Type enum was used earlier in the inline layouting, but in the current algorithm there is a single type of LineBoxFragment.
=> LibWeb: Remove unused code

Tests/LibWeb/Layout/expected/grid/place-items-center.txt, Tests/LibWeb/Layout/input/grid/place-items-center.html, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/PlaceItemsStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/PlaceItemsStyleValue.h, Userland/Libraries/LibWeb/Forward.h
Adds support for place-items property which allows to specify both align-items and justify-items in a single declaration.
=> LibWeb: Add support for "place-items" CSS property

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibGfx/ImageFormats/ICOLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/ICOLoader.h
**LibGfx/ICO: Decode the header in `create()` and remove `initialize()`**
**LibGfx: Register the mime type image/x-icon**
=> LibGfx/ICO: Refactor the plugin interface

Tests/LibWeb/Layout/expected/pre.txt, Tests/LibWeb/Layout/input/pre.html, Userland/Libraries/LibWeb/Layout/LineBox.cpp
Whitespace at the end of line should only be trimmed when 'white-space' is set to 'normal', 'nowrap', or 'pre-line'.
=> LibWeb: Fix whitespace getting trimmed incorrectly

Meta/lint-ports.py
Missed this edge case previously. Now correctly parses the following as valid
```sh
files="
URL
"
```
=> Meta: Don't finish lines with only one character in `lint-ports.py`

Userland/Libraries/LibPDF/DocumentParser.cpp
This allows us to open the now-publicly-available PDF 2.0 spec!
=> LibPDF: Fix incorrectly parsing xref stream subsections

Tests/LibWeb/Layout/expected/flex/flex-column-item-with-percentage-max-width.txt, Tests/LibWeb/Layout/input/flex/flex-column-item-with-percentage-max-width.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h
Once we've resolved the used flex item width & height, we should allow percentage flex item sizes to resolve against them instead of forcing flex items to always treat percentages as auto while doing intrinsic sizing layout.
Regressed in 8dd489da61362738a39ec938732e3d054ff5da8b.
=> LibWeb: Resolve flex item percentages against used flex container sizes

Base/res/html/misc/border-radius.html, Userland/Libraries/LibWeb/Painting/BorderPainting.cpp, Userland/Libraries/LibWeb/Painting/BorderPainting.h
The refactor of the border painting mainly to handle:
1. single border with minor border radius
2. different border widths and border colors joined way
This refactor only apply to solid border
Before:
After:
=> LibWeb: Paint border to handle more cases

Tests/LibGfx/TestImageDecoder.cpp
Reordering these calls allow us to ensure that all encoders are able to return the size of the image before they are requested to decode the whole bitmap.
=> Tests/LibGfx: Call `ImageDecoder::size()` before `frame()`

Userland/Applications/SoundPlayer/PlaylistWidget.cpp
The previous code would format 5400 seconds as "1:90:00", when it should be "1:30:00".
=> SoundPlayer: Correct formatting of PlaylistModel duration text

Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
This resolves a problem where the kerning value multiplied by the scale is stored in the cache, even though the code retrieving the value from the cache does not anticipate it to be scaled. As a result, it leads to a buggy double multiplication by the scale.
=> LibGfx: Fix double x_scale multiply when glyph kerning is cached 

Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp
Both width and height are stored in an u16 inside the TGA header, computing the total number of pixel without using another type can easily lead to overflows.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55309&q=serenity&can=2
=> LibGfx/TGA: Compute the number of pixels with a wider type

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Runtime/AbstractOperations.h, Userland/Libraries/LibJS/Runtime/AggregateErrorConstructor.cpp, Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp, Userland/Libraries/LibJS/Runtime/IteratorOperations.cpp, Userland/Libraries/LibJS/Runtime/IteratorOperations.h, Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp, Userland/Libraries/LibJS/Runtime/SetPrototype.cpp, Userland/Libraries/LibJS/Runtime/TypedArray.cpp, Userland/Libraries/LibJS/Runtime/TypedArrayConstructor.cpp, Userland/Libraries/LibJS/Runtime/VM.cpp, Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
This is a set of editorial changes to split `GetIterator` into 2 AOs, followed by a normative change in the Set Methods proposal to make use of one of the new AOs.
There's a few downstream consumers of these AOs that have not been updated. I'll be making spec issues / just fixing them when I get a chance later.
=> LibJS: Refactor GetIterator, and replace Set's GetKeysIterator AO with GetIteratorFromMethod

Toolchain/BuildClang.sh, Toolchain/BuildGNU.sh, Userland/Libraries/LibC/arpa/inet.h, Userland/Libraries/LibC/bits/getopt.h, Userland/Libraries/LibC/fcntl.h, Userland/Libraries/LibC/getopt.h, Userland/Libraries/LibC/langinfo.h, Userland/Libraries/LibC/netdb.h, Userland/Libraries/LibC/netinet/in.h, Userland/Libraries/LibC/pthread.h, Userland/Libraries/LibC/sched.h, Userland/Libraries/LibC/semaphore.h, Userland/Libraries/LibC/signal.h, Userland/Libraries/LibC/spawn.h, Userland/Libraries/LibC/stdio.h, Userland/Libraries/LibC/stdlib.h, Userland/Libraries/LibC/string.h, Userland/Libraries/LibC/sys/resource.h, Userland/Libraries/LibC/sys/select.h, Userland/Libraries/LibC/sys/socket.h, Userland/Libraries/LibC/sys/time.h, Userland/Libraries/LibC/sys/wait.h, Userland/Libraries/LibC/time.h, Userland/Libraries/LibC/unistd.h, Userland/Libraries/LibC/wchar.h, Userland/Libraries/LibC/wctype.h
This fixes the `openssl` and `cmake` ports, and probably a few others as well.
=> LibC+Toolchain: Various header compliance fixes

Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
The spec was corrected here:
https://github.com/w3c/csswg-drafts/commit/de4119a6e3f27a21f18293ad19aa4e5413c76cc4
=> LibWeb: Update spec comments for math function determined types

Base/usr/share/man/man1/ps.md, Userland/Utilities/ps.cpp
This option allows the user to change which colums are displayed
by giving comma or space separated list of column format specifiers.
A column format specifier is of the form: `COLUMN_NAME[=COLUMN_TITLE]`.
Where `COLUMN_NAME` is any of: uid, pid, ppid, pgid, sid, state, tty,
or cmd. Specifying a `COLUMN_TITLE` will change the name shown in the
column header.
`COLUMN_TITLE` may be blank. If all given column titles
are blank, the header is omitted.
I'm also using this PR to sneak in a fix for a bug I introduced in aeb87d6e :see_no_evil:.
This caused the `-q` option to break, as the filtering logic allowed processes
to be selected that the user didn't specify.
Example usage:
=> ps: Add the `-o` option to specify a user-defined column format

AK/String.h, AK/StringView.h
Android isn't shipping clang-15 yet in any NDK, so use the existing workaround on that platform.
=> AK: Enable consteval workaround for Android NDK

Userland/Applications/SoundPlayer/PlaylistWidget.cpp, Userland/Applications/SoundPlayer/PlaylistWidget.h, Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.cpp, Userland/Games/Solitaire/main.cpp, Userland/Games/Spider/main.cpp
Use this handy AK function instead of reimplementing the formatting code several times. The one minor difference is that now, hours are only shown if the duration is at least an hour long, but that seems like an improvement to me. :^)
=> Userland: Use AK::human_readable_digital_time() instead of custom code

Userland/DevTools/GMLPlayground/MainWidget.cpp, Userland/DevTools/GMLPlayground/MainWidget.h
Previously, the Save action held a reference to the local variable for the Save As action, which goes out of scope at the end of `initialize_menubar()`. This meant that if you tried to Save a new file, it would instead crash and yeet your work into the abyss.
=> GMLPlayground: Keep a RefPtr to the "Save As..." action

Userland/Libraries/LibCrypto/Cipher/Mode/Mode.h, Userland/Libraries/LibPDF/Encryption.cpp, Userland/Libraries/LibPDF/Encryption.h
This is a step towards AESV3 support for PDF files.
The straight-forward way of writing this with our APIs is pretty
allocation-heavy, but this code won't run all that often for the
regular "open PDF, check password" flow.
=> LibPDF: Implement 7.6.4.3.4 Algorithm 2.B: Computing a hash

Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h
No behavioral changes intended
(no change in bytecode test262)
⚙️=112, ✅=47247, ❌=2010, 💀=2, 💥️=14, 📝
=> LibJS: Deduplicate continue & break bytecode generation

Userland/Libraries/LibGfx/Font/ScaledFont.cpp, Userland/Libraries/LibGfx/ICC/WellKnownProfiles.h, Userland/Libraries/LibPDF/ColorSpace.cpp, Userland/Libraries/LibPDF/ColorSpace.h, Userland/Libraries/LibPDF/Fonts/PDFFont.h, Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp, Userland/Libraries/LibPDF/Fonts/TrueTypeFont.h, Userland/Libraries/LibPDF/Fonts/Type0Font.cpp, Userland/Libraries/LibPDF/Fonts/Type0Font.h, Userland/Libraries/LibPDF/Fonts/Type1Font.cpp, Userland/Libraries/LibPDF/Fonts/Type1Font.h, Userland/Libraries/LibPDF/Renderer.cpp
Page 1 of the PDF 2.0 spec:
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
</details> 
cc @nico for the ICC stuff. Turns out the ICC changes don't actually do anything to contribute to the images above. I thought it did, and then implemented it all only to find out I misinterpreted the color information I was seeing from the PDF. But if it looks ok, might as well merge it.
=> LibPDF: Fix text/line matrices not being retroactively applied to font size + using LibGfx::ICC

Userland/Applications/FileManager/CMakeLists.txt, Userland/Applications/FileManager/PropertiesWindow.cpp, Userland/Applications/FileManager/PropertiesWindow.h, Userland/Applications/FileManager/PropertiesWindowAudioTab.gml, Userland/Applications/FileManager/PropertiesWindowFontTab.gml, Userland/Applications/FileManager/PropertiesWindowGeneralTab.gml, Userland/Applications/FileManager/PropertiesWindowImageTab.gml, Userland/Libraries/LibAudio/Loader.cpp, Userland/Libraries/LibAudio/Loader.h, Userland/Libraries/LibAudio/WavLoader.cpp, Userland/Libraries/LibAudio/WavLoader.h, Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibGfx/Font/FontStyleMapping.h, Userland/Libraries/LibGfx/ICC/Profile.cpp, Userland/Libraries/LibGfx/ICC/Profile.h
The "General" tab on this window felt lonely, and it's nice to be able to view some basic information about a file, beyond its size, modification date, and that it is a file. So, this PR adds some tabs for Image, Audio, and Font files to give more information.
There are a few random other changes in related libraries too.
My concern with this is, it means decoding these files inside FileManager, which is one of the more dangerous applications to become compromised since it can see the whole filesystem that the user can. Also it does slow down opening the properties window a bit. Maybe in future it could lazy-load the files when you open the file-type-specific tab.
=> FileManager: Show information about image, audio, and font files in Properties window

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h
Fixes leaking of DOM::Document by capturing it into JS::SafeFunction callback when using Platform::Timer for style and layout update timers.
=> LibWeb: Use Core::Timer for style and layout update timers in Document

Userland/Libraries/LibJS/AST.cpp, Userland/Libraries/LibJS/AST.h, Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp, Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Userland/Libraries/LibJS/SourceTextModule.cpp
Deletes following functions in Declaration class because those mostly clone similar iteration functions but for identifiers.
- for_each_name
- for_each_lexically_declared_name
- for_each_var_declared_name
=> LibJS: Replace for_each_bound_name with for_each_bound_identifier

Userland/Libraries/LibJS/Bytecode/Pass/GenerateCFG.cpp
This is just something I spotted looking around the code, previously the PassPipelineExecutable was passed by value to
generate_cfg_for_block, which generated the CFG then just dropped it on the floor. Making this a reference results in the CFG actually getting generated.
=> LibJS: Actually generate the bytecode CFG

Userland/Libraries/LibPDF/Fonts/Type1Font.cpp, Userland/Libraries/LibPDF/Fonts/Type1Font.h
LibGfx's ScaledFont doesn't do this, but in ScaledFont m_x_scale and m_y_scale are immutable once the class is created, so it can get away with not doing it.
In Type1Font, `width` changes in different calls to Type1Font::draw_glyph(), so we need to make it part of the cache key.
Fixes rendering of the word "Version" on the first page of pdf_reference_1-7.pdf.
=> LibPDF: Include `width` in Type1Font glyph cache key

Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Layout/Node.h, Userland/Libraries/LibWeb/Layout/SVGTextBox.cpp, Userland/Libraries/LibWeb/Painting/SVGTextPaintable.cpp, Userland/Libraries/LibWeb/SVG/AttributeParser.h, Userland/Libraries/LibWeb/SVG/SVGElement.h, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp, Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp, Userland/Libraries/LibWeb/SVG/SVGTextContentElement.cpp, Userland/Libraries/LibWeb/SVG/SVGTextContentElement.h
See commits for details. This make the badges on Serenity's GitHub look a fair bit nicer :^) 
**Before:**
**After:**
=> LibWeb: Improve SVG `<text>` element support (font-size, scaling, and `text-anchor`)

Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Encryption.cpp, Userland/Libraries/LibPDF/Encryption.h
Demo:
```sh
% Build/lagom/bin/pdf /Users/thakis/Downloads/CIPA_DC-007-2021_E.pdf
PDF Version: 1.7
Number of pages: 63
Title: CIPA DC-007-Translation-2021 Multi-Picture Format.
Author: CIPA
Subject: 
Keywords: 
Creator: Word 用 Acrobat PDFMaker 17
Producer: Adobe PDF Library 17.11.238
Creation date: D:20211224140020+09'00'
Modification date: D:20211224140459+09'00'
```
"LibPDF: Implement 7.6.4.3.3 Algorithm 2.A: Retrieve file encryption key" is the most interesting commit. The commit message is fairly detailed. The rest is fairly straightforward. (That commit is also fairly straightforward, but a bit longer.)
=> LibPDF: Implement rest of AESV3 support :^)

Userland/Libraries/LibPDF/Document.cpp
An indirect object starts `42 0 obj`, not `obj 42 0`.
=> LibPDF: Fix dumping of toplevel indirects

AK/FixedArray.h, Userland/Libraries/LibCompress/Brotli.cpp, Userland/Libraries/LibCompress/Brotli.h, Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibGUI/FileTypeFilter.h, Userland/Libraries/LibGfx/Bitmap.h, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.h
JPEG-XL is a new image format standardized by the same committee as the
original JPEG image format. It has all the nice feature of recent
formats, and great compression ratios. For more details, look at:
https://jpegxl.info/
This decoder is far from being feature-complete, as it features a grand
total of 60 FIXMEs and TODOs, but anyway, it's still a good start.
I developed this decoder in the Serenity way, I just try to decode a
specific image while staying as close as possible to the specification.
Considering that the format supports a lot of options, and that we
basically support only one possibility for each of them, I'm pretty sure
that we can only decode the image I've developed this decoder for.
Which is:
0aff 3ffa 9101 0688 0001 004c 384b bc41
5ced 86e5 2a19 0696 03e5 4920 8038 …
=> LibGfx/JPEGXL: Add a JPEG-XL decoder :^) 

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Bytecode/Register.h, Userland/Libraries/LibJS/Tests/try-return-finally.js
This fixes an issue where returning inside a `try` block and then calling a function inside `finally` would clobber the saved return value from the `try` block.
Note that we didn't need to change the base of register allocation, since it was already 1 too high.
With this fixed, https://microsoft.com/edge loads in bytecode mode. :^)
Thanks to Luke for reducing the issue!
=> LibJS/Bytecode: Keep saved return value in call frame register

Base/usr/share/man/man1/file.md, Userland/Utilities/file.cpp
=> file: Add `-b` option to omit file name from output

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Instead of rejecting them, we truncate each value to 8 bits. This is
clearly a hack, but given the lack of support of variable bit-depth in
`Bitmap` this is the only sensible change.
This allows us to display "Iceberg" on https://jpegxl.info/art/.
---
I bet you can't see that in your daily browser:
=> LibGfx/JPEGXL: Accept images with high bit depth

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
This is something I missed when I ported the JPEG XL decoder to the new plugin interface (decoding the header at creation). First sorry because that's entirely my fault, second sorry because a test should have caught that.
=> LibGfx/JPEGXL: Don't decode the header twice

Userland/Libraries/LibCompress/Brotli.cpp, Userland/Libraries/LibCompress/Brotli.h
This function was used in a single place and don't provide a huge benefit over simply recreating the object.
=> LibCompress/Brotli: Remove `CanonicalCode::clear()`

Ladybird/WebContentView.cpp, Ladybird/WebContentView.h, Userland/Libraries/LibWebView/OutOfProcessWebView.cpp, Userland/Libraries/LibWebView/OutOfProcessWebView.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Utilities/headless-browser.cpp
WebView::ViewImplementation now remembers which JS interpreter it started with, and uses the same setting if the WebContent process crashes and we have to spawn a new one.
=> Ladybird+LibWebView: Respawn with same JS interpreter after crash

Userland/Applications/SystemMonitor/ProcessModel.cpp
This commit addresses an issue when 'Zombie' threads are included in CPU % calculation. This caused negative time_scheduled_diff, resulting in a data type overflow.
Fixes https://github.com/SerenityOS/serenity/issues/19842
=> System Monitor: Fix calculation of CPU percentage

AK/Format.h, Userland/Applications/FileManager/DirectoryView.cpp, Userland/Libraries/LibC/stdio.cpp
Reverting until we come up with a better way of detecting what exactly should be copied, to prevent stuff like this:
=> AK: Revert "AK: Automatically copy all warn/warnln logs to debug console"

Userland/Libraries/LibPDF/Fonts/PDFFont.h, Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp, Userland/Libraries/LibPDF/Fonts/SimpleFont.h, Userland/Libraries/LibPDF/Fonts/Type0Font.cpp, Userland/Libraries/LibPDF/Fonts/Type0Font.h, Userland/Libraries/LibPDF/Renderer.cpp
This helps a little bit with justifying the text on page 2 of pdf_reference_1-7.pdf, but doesn't fully fix it.
=> LibPDF: Correctly make text look justified on page 2 of the PDF 1.7 spec

Userland/Libraries/LibPDF/Operator.h, Userland/Libraries/LibPDF/Parser.cpp
It's `"`, not `''`.
Now the `text_next_line_show_string_set_spacing` gets called and logs a TODO at page render time if `"` is used in a PDF:
warning: Rendering of feature not supported:
draw operation: text_next_line_show_string_set_spacing
It caused a parse error (also at page render time) previously:
[parse_value @ .../LibPDF/Parser.cpp:104]
Parser error at offset 611: Unexpected char """
=> LibPDF: Fix symbol for text_next_line_show_string_set_spacing operator

Tests/LibWeb/Text/expected/HTML/StructuredClone-primitives.txt, Tests/LibWeb/Text/input/HTML/StructuredClone-primitives.html, Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Adds support for Undefined, Null, Boolean, BigInt, and String to AOs StructuredSerializeInternal and StructuredDeserialize.
~~To trivially serialize and deserialize Undefined and Null `JS::Value::tag()` and constructor `JS:Value(u64 tag, u64 value)` has been exposed publicly.~~
EDIT: `Undefined` and `Null` is serialized by only indicating their `[[Type]]`, there is no need to serialize any `[[Value]]`.
=> LibWeb+LibJS: Add primitive support to Structured{Serialize,Deserialize} 

Meta/Lagom/CMakeLists.txt, Tests/LibJS/test-js.cpp, Userland/Libraries/LibJS/Tests/builtins/DisposableStack/DisposableStack.prototype.@@dispose.js, Userland/Libraries/LibJS/Tests/builtins/Error/Error.prototype.stack.js, Userland/Libraries/LibJS/Tests/builtins/FinalizationRegistry/FinalizationRegistry.prototype.cleanupSome.js, Userland/Libraries/LibJS/Tests/builtins/ShadowRealm/ShadowRealm.prototype.importValue.js, Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.prototype.set.js, Userland/Libraries/LibJS/Tests/builtins/WeakSet/WeakSet.prototype.add.js, Userland/Libraries/LibJS/Tests/invalid-lhs-in-assignment.js, Userland/Libraries/LibJS/Tests/loops/for-in-basic.js, Userland/Libraries/LibJS/Tests/loops/for-of-basic.js, Userland/Libraries/LibJS/Tests/modules/basic-modules.js, Userland/Libraries/LibJS/Tests/object-basic.js, Userland/Libraries/LibJS/Tests/object-spread.js, Userland/Libraries/LibJS/Tests/operators/delete-basic.js, Userland/Libraries/LibJS/Tests/strict-mode-errors.js, Userland/Libraries/LibJS/Tests/syntax/async-await.js, Userland/Libraries/LibJS/Tests/tagged-template-literals.js, Userland/Libraries/LibJS/Tests/test-common.js, Userland/Libraries/LibJS/Tests/using-declaration.js, Userland/Libraries/LibJS/Tests/using-for-loops.js, Userland/Libraries/LibTest/JavaScriptTestRunner.h, Userland/Libraries/LibTest/Results.h, Userland/Libraries/LibTest/TestRunner.h, Userland/Utilities/run-tests.cpp
The motivation for this change is the fourth commit in particular, where the test does not work in AST mode, but does for bytecode mode. I then figured that using this functionality, this should also allow us to run test-js in bytecode mode in CI.
=> LibJS/Tests: Enable running bytecode tests in CI

Meta/Lagom/CMakeLists.txt, Tests/LibXML/TestParser.cpp, Userland/Libraries/LibXML/Parser/Parser.cpp
Previously, we were returning `Well hello , , , , and !` as a content of a root element of `<a>Well hello &amp;, &lt;, &gt;, &apos;, and &quot;!</a>`.
=> LibXML: Actually append resolved references when parsing content

Tests/LibWeb/Layout/expected/table/colspan-percentage-width.txt, Tests/LibWeb/Layout/input/table/colspan-percentage-width.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Follow the computing column measures section of the specification, which gives an algorithm for setting intrinsic percentage widths when spanning columns are involved.
=> LibWeb: Implement iterative percentage size for spanning table cells

Userland/Libraries/LibPDF/ColorSpace.cpp
That way, we render an incomplete page and log a message instead of crashing the viewer application.
Lets us survive e.g. page 489 of pdf_reference_1-7.pdf.
=> LibPDF: Replace two TODO()s with Error returns

Userland/Libraries/LibWeb/CSS/Default.css, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
effect of an afternoon hacking session w/ @linusg :^)
my favourite fix is probably the stylesheet one, which makes this page render properly:
=> LibWeb: Minor rendering fixes

Userland/Libraries/LibPDF/Filter.cpp
Instead, they're now turned into a diagnostic like other rendering problems, looking like so:
Internal error while processing PDF file:
Unsupported chroma subsampling factors
Makes us no longer crash rendering page 1141 of pdf_reference_1.7-pdf.
=> LibPDF: Make JPEG decoding errors not assert

Userland/Applications/Magnifier/main.cpp, Userland/Applications/PixelPaint/PaletteWidget.cpp, Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp, Userland/Games/Snake/Game.h, Userland/Games/Snake/main.cpp, Userland/Libraries/LibGUI/ColorInput.cpp, Userland/Libraries/LibGUI/ColorPicker.cpp, Userland/Libraries/LibGUI/ColorPicker.h
I added a callback to `GUI::ColorPicker` that clients can optionally use to receive real-time color updates, and applied this new feature to every location in the system that uses it, namely:
* Spreadsheet
* PixelPaint
* Magnifier
* Snake
* `LibGUI` itself, in `GUI::ColorInput`, which is used in many more places.
Quick demo:
https://github.com/SerenityOS/serenity/assets/20117975/b65fe275-59e7-4d8c-a609-4bb63172ebc9
=> LibGUI+Userland: Make `GUI::ColorPicker` interactive

Tests/LibCore/TestLibCorePromise.cpp, Userland/Libraries/LibCore/Promise.h
Returning a reference resulted in Mail's use of Promise causing a crash. Also, awaiting an already-awaited promise is an odd thing to do anyway, so let's just make it release the resolved/rejected value instead of returning a reference to it.
cc @vkoskiv.
=> LibCore: Move the Promise::await() result instead of returning a ref

Userland/Libraries/LibPDF/Document.cpp, Userland/Libraries/LibPDF/Document.h, Userland/Libraries/LibPDF/Encryption.cpp, Userland/Libraries/LibPDF/Parser.cpp
Makes it possible to render more than 0 pages of CIPA_DC-003-2020_E.pdf
=> LibPDF: Don't crash on encrypted files with streams with filter arrays

Userland/Libraries/LibPDF/ColorSpace.cpp, Userland/Libraries/LibPDF/ColorSpace.h, Userland/Libraries/LibPDF/CommonNames.h
None of the methods actually do anything, but we now create an
actual SeparationColorSpace object for /Separation color spaces.
This fixes a crash on page 810 of pdf_reference_1-7.pdf.
Previously, we'd log a "separation color space not supported" error,
which would lead to Renderer not updating its current color space.
It'd stay a DeviceCYMK color space, which would then later assert
when it got a 1-argument array as color (which now the
SeparationColorSpace gets instead, which logs an "unimplemented"
error for that instead of asserting).
=> LibPDF: Add smoke-and-mirror implementation of SeparationColorSpace

Userland/Libraries/LibPDF/ColorSpace.cpp, Userland/Libraries/LibPDF/CommonNames.h
Makes them easier to interpret in `pdf --debugging-stats` output.
=> LibPDF: Dedicated messages for Indexed and Pattern spaces

Userland/DevTools/HackStudio/CodeDocument.h, Userland/DevTools/HackStudio/Editor.cpp, Userland/DevTools/HackStudio/Editor.h, Userland/DevTools/HackStudio/EditorWrapper.cpp, Userland/Libraries/LibGUI/TextDocument.h, Userland/Libraries/LibGUI/TextEditor.cpp
Before:
After:
While I was trying to search for the cause of this bug, I noticed a few places where the Editor and friends reimplement things that TextEditor already does, and removed them.
=> HackStudio: Fix code-folding bug, and remove some duplicate code

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
This makes our css-animations.html test file actually parse :^)
=> LibWeb: Ignore whitespace around easing function argument values

Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Fonts/Type0Font.cpp, Userland/Libraries/LibPDF/Fonts/Type0Font.h
Type0 fonts can be either CFF-based or TrueType-based. Create a subclass for each, put in some spec text, and give each case a dedicated error code, so that `--debugging-stats` can tell me which branch is more common.
=> LibPDF: Sketch out Type0 font support some more

AK/URL.cpp, AK/URL.h, AK/URLParser.cpp, Tests/AK/TestURL.cpp
I misunderstood the spec step for checking whether the host 'ends with a
number'. We can't simply check for it if ends with a number, this check
is actually an algorithm which is required to avoid detecting hosts that
end with a number from an IPv4 host.
Implement this missing step, and add a test to cover this.
Also add some spec comments to URL::serialize as I'm currently debugging
why browser seems to be crashing in data URL serialization when browsing Jira instances
=> AK: Fix url host parsing check for 'ends in a number'

Tests/LibWeb/Layout/expected/block-and-inline/inline-block-baseline-1.txt, Tests/LibWeb/Layout/expected/block-and-inline/inline-block-baseline-2.txt, Tests/LibWeb/Layout/expected/block-and-inline/margin-collapse-5.txt, Tests/LibWeb/Layout/input/block-and-inline/inline-block-baseline-1.html, Tests/LibWeb/Layout/input/block-and-inline/inline-block-baseline-2.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h
Before this change, we always derived a box's baseline from its last child, even if the last child didn't have any line boxes inside.
This caused baselines to slip further down vertically than expected.
There are more baseline alignment issues to fix, but this one was responsible for a fair chunk of trouble. :^)
Visual progression on https://www.ekioh.com/flow-browser/
Before:
After:
=> LibWeb: Derive box baseline from last child *with line boxes*

Tests/LibWeb/Layout/expected/flex/justify-content-space-between-single-item.txt, Tests/LibWeb/Layout/input/flex/justify-content-space-between-single-item.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
This change fixes division by zero in case flex container has "justify-content: space-between" and only single item.
Fixes UBSAN error on https://www.ekioh.com/flow-browser/
=> LibWeb: Fix division by zero in distribute_any_remaining_free_space

Tests/LibWeb/TestCSSPixels.cpp, Userland/Libraries/LibWeb/PixelUnits.cpp
Fixes overflow bug found by UBSAN.
=> LibWeb: Implement subtraction using saturated_addition in CSSPixels

Tests/LibWeb/Text/expected/window-proxy-numeric-own-property.txt, Tests/LibWeb/Text/input/window-proxy-numeric-own-property.html, Userland/Libraries/LibWeb/HTML/WindowProxy.cpp
This fixes an assertion on https://amazon.com/ since `WindowProxy` would advertise "0" as an own property key, but then act like it was a bogus property when actually queried for it directly.
=> LibWeb: Implement basic support for window[number]

Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
Fixes broken border-radius painting because of lost precision while converting back and forth between double and CSSPixels.
Fixed example:
```html
<style>
div {
border-radius: 9999px;
background: orange;
padding: 10px;
}
</style><div>huh</div>
```
=> LibWeb: Remove casting to double in normalized_border_radii_data

Ladybird/main.cpp, Meta/Lagom/CMakeLists.txt, Userland/Applications/Browser/BrowserWindow.cpp, Userland/Applications/Browser/BrowserWindow.h, Userland/Applications/Browser/Tab.cpp, Userland/Applications/Browser/Tab.h, Userland/Applications/Browser/main.cpp, Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp, Userland/Libraries/LibWebView/OutOfProcessWebView.cpp, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/ConnectionFromClient.h, Userland/Services/WebContent/WebContentServer.ipc, Userland/Utilities/headless-browser.cpp, Userland/Utilities/js.cpp
Summary of changes:
- The `ladybird`, `Browser`, `headless-browser`, `js` and `test-js` programs now use the LibJS bytecode VM by default.
- The AST interpreter is still available behind a new `--ast` flag.
- `test-js` now runs in bytecode mode when part of the `run-tests` battery.
While there are still a handful of test262 and test-js tests that are passing in AST but not BC, it's already the case that many websites work significantly better in bytecode mode.
We can deal with the remaining failures over time, but let's switch the default so we get more testing of the new VM. :^)
=> Run with the JavaScript bytecode VM by default

Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
In c66dbc99ee69995c09e08b5e137b2096f694959c GFC was updated to use -1 as special value for the infinite growth limit. However, using Optional instead reduces the risk of accidentally using -1 special value in layout calculations.
=> LibWeb: Use empty Optional to represent infinte growth limit in GFC

Tests/LibWeb/Layout/expected/flex/inf-available-space-with-auto-margins.txt, Tests/LibWeb/Layout/input/flex/inf-available-space-with-auto-margins.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
After switching to fixed-point arithmetic in CSSPixels, it no longer supports representing infinite values, which was previously the case for remaining_free_space in FFC. Using Optional that is not empty only when value is finite to store remaining_free_space ensures that infinity is avoided in layout calculations.
Fixes hanging on https://twinings.co.uk
=> LibWeb: Avoid leaking infinite remaining_free_space in FFC calculation

Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/EventHandler.h
Click event logic should start as false, and after checking if the mousedown and subsequent mouseup have been on the same element, and if the node dispatches events it can become true.
This fixes the issue that clicking anywhere on the page, then dragging the mouse on top of a link or button, then releasing triggers the link. This is also happening when selecting text, if the selection stops over a link, the page navigates.
The first commit also removes 2 unused methods.
=> LibWeb: Do not fire click event if mouseup/down elements do not match

Userland/Libraries/LibTLS/Certificate.h, Userland/Libraries/LibTLS/TLSv12.cpp
This follows the pattern of every other singleton in the system.
Also, remove use of AK::Singleton in place of a function-scope static. There are only three uses of that class outside of the Kernel, and all the remaining uses are suspect. We need it in the Kernel because we want to avoid global destructors to prevent nasty surprises about expected lifetimes of objects. In Userland, we have normal thread-safe statics available. 7d11edbe1 attempted to standardize the pattern, but it seems like more uses of awkward singleton creation have crept in or were missed back then.
Side note, this fixes a linker error for Lagos WebContent on macOS with `-g -O0`
=> LibTLS: Move singleton for DefaultRootCACertificates out of line

Tests/LibWeb/Layout/expected/flex/justify-content-1.txt, Tests/LibWeb/Layout/expected/flex/justify-content-with-margin-auto-child.txt, Tests/LibWeb/Layout/input/flex/justify-content-with-margin-auto-child.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
This fixes layout issues related to row-reverse and column-reverse, as well as children being positioned outside of their parent when the parent has justify-content and the child has auto margin(s).
This is my first time playing around with serenity (and browser dev), so I apologize if I got something wrong! Hopefully I'm not way off :slightly_smiling_face: 
_justify-content on the parent and auto margins on the children_
=> LibWeb: Handle flex reverse and auto margins with justify-content

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp, Tests/LibUnicode/TestUnicodeCharacterTypes.cpp, Userland/Libraries/LibUnicode/CharacterTypes.cpp, Userland/Libraries/LibUnicode/CharacterTypes.h
We currently produce a single table for all categories of code point
properties (GeneralCategory, Script, etc.). Each row contains a field
indicating the range of code points to which that property applies. At
runtime, we then do a binary search through that table to decide if a
code point has a property.
This changes our approach to generate a 2-stage lookup table for each of
those categories. There is an in-depth explanation of these tables above
the new `create_code_point_tables` method. The end effect is that code
point property lookup is reduced from a binary search to constant-time
array lookups.
In total, this change:
* Increases the size of libunicode.so from 2.7 MB to 2.9 MB.
* Reduces the runtime of the new benchmark test case added here from
3.576s to 1.020s (a 3.5x speedup).
* …
=> LibUnicode: Perform code point property lookups in constant time

Tests/LibWeb/Layout/expected/table/basic.txt, Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt, Tests/LibWeb/Layout/expected/table/border-conflict-resolution-with-col.txt, Tests/LibWeb/Layout/expected/table/border-conflict-resolution-with-row.txt, Tests/LibWeb/Layout/expected/table/border-conflict-resolution-with-rowgroup.txt, Tests/LibWeb/Layout/expected/table/border-spacing-colspan.txt, Tests/LibWeb/Layout/expected/table/border-spacing-rowspan.txt, Tests/LibWeb/Layout/expected/table/border-spacing.txt, Tests/LibWeb/Layout/expected/table/borders.txt, Tests/LibWeb/Layout/expected/table/bottom-caption.txt, Tests/LibWeb/Layout/expected/table/clip-spans-to-table-end.txt, Tests/LibWeb/Layout/expected/table/colspan-width-distribution.txt, Tests/LibWeb/Layout/expected/table/columns-width-distribution-1.txt, Tests/LibWeb/Layout/expected/table/fixed-margins.txt, Tests/LibWeb/Layout/expected/table/long-caption-increases-width.txt, Tests/LibWeb/Layout/expected/table/multi-line-cell.txt, Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt, Tests/LibWeb/Layout/expected/table/rows-height-distribution-1.txt, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Improves precision of height and width distribution.
=> LibWeb: Convert divisor to double in TableFormattingContext

Base/res/html/misc/border-radius.html, Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
When joined border width is zero width, then the midpoint of the joined corner is no longer need to be computed anymore. Just set the mid point to be the endpoint of the corner.
fix https://github.com/SerenityOS/serenity/issues/20164
=> LibWeb: Fix border painting with border-radius and zero-width sides 

Userland/Utilities/truncate.cpp
The base 2 size suffixes: 'K', 'M' and 'G' may now be used when specifying a file size with the `-s` option.
I also made a small behavioral change where attempting to reduce a file to a size < 0 will now produce an empty file rather than an error. This matches the behavior of `truncate` on Linux and FreeBSD.
Example usage:
=> truncate: Allow size suffixes to be used with the `-s` option

Meta/lint-ci.sh, Userland/Utilities/markdown-check.cpp
When markdown-check is built, it outputs hundreds of lines of "ignoring this and that link because reasons". This is extremely not helpful when trying to figure out exactly which check failed on your commit. Also remove the timing numbers from lint-ci.sh These are just noise and also don't help to figure out which pre-commit check failed. Ideally the output on fail should be "[OK]: Check A" for all the passing checks and "[FAIL] Check N" with the required context for the failed check.
This should avoid this ridiculous output from one of my local branches where the pre-commit checks dumped literally 1000 lines of verbose output to my terminal when I had one line in one python file to fix. See if you can spot the actual error amid this forest of log lines. …
=> Meta+Utilities: Make pre-commit checks significantly less verbose

Meta/Lagom/Fuzzers/FuzzPDF.cpp
Without calling `initialize()`, the page count is 0, so the loop never ran and we never actually tested any of the code in `get_page()`.
Having to call `initialize()` at all is awkward, but seems necessary at the moment because of how providing a password works.
=> FuzzPDF: Initialize document so page count is accurate

Userland/DevTools/GMLPlayground/MainWidget.cpp, Userland/Libraries/LibGUI/TextDocument.cpp, Userland/Libraries/LibGUI/TextDocument.h, Userland/Libraries/LibGUI/TextEditor.cpp, Userland/Libraries/LibGUI/TextEditor.h
Previously, this was reimplementing the same thing by removing all the
document text and then inserting the new text - which internally would
insert each code-point individually and fire change notifications for
each one. This made the "Reformat GML" button very slow, since it not
only had to recalculate the visual lines of the document each time, but
also rebuild the preview GUI.
The reason not to use `set_text()` is that it would throw away the undo
stack, since it always behaved as if the text is a new document. So,
let's add a parameter to disable that behaviour.
This takes the time for reformatting a ~200 line GML file from several
seconds, to basically instantaneous. :^)
=> LibGUI: Use set_text() for ReplaceAllTextCommand

Meta/Azure/Lagom.yml
This disables running benchmark test cases on Lagom in CI. When we run unit tests on-board Serenity, run-tests sets this environment variable. We do not use that utility to run unit tests on Lagom, so we've been running benchmark tests unnecessarily.
=> CI: Set TEST_ONLY mode for unit tests on Lagom

Tests/LibWeb/Layout/expected/table/avoid-div-by-zero-in-table-measures.txt, Tests/LibWeb/Layout/input/table/avoid-div-by-zero-in-table-measures.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
For malformed tables which only have cells with span greater than 1, the content sizes for row and column aren't initialized to non-zero values. Avoid undefined behavior in such cases, which sometimes show up on Wikipedia.
=> LibWeb: Avoid division by zero when computing table measures

Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp, Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Correctly compute the maximum possible width and height for corners_bitmap_size by considering all pair combinations of corners.
Fixes issue https://github.com/SerenityOS/serenity/issues/20205
=> LibWeb: Fix calculation of bitmap size in BorderRadiusCornerClipper

AK/MemoryStream.cpp, AK/MemoryStream.h, Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp, Userland/Libraries/LibGfx/ImageFormats/TGALoader.h, Userland/Libraries/LibVideo/VP9/Context.h
The conversion to AK::Stream makes everything much more straightforward and understandable now, because we remove the custom reader we had. Because AK::Stream is more tested, it means that the code should be now more robust against bugs as well.
cc @LucasChollet
=> LibGfx/TGA: Simplify the code by converting it to use AK::Stream

Userland/Applications/NetworkSettings/NetworkSettingsWidget.cpp
NetworkSettings normally filters out `loop` when populating its list of adapters. However, when checking if there aren't any adapters it did not take this into account. This causes it to crash later when trying to set the selected index of an empty combo box.
This moves the check for no adapters to after filtering the list, so that shows the error message and exits.
=> NetworkSettings: Don't assert when there are no network adapters

Userland/Libraries/LibWeb/CMakeLists.txt
The bindings generator already produces a depfile of IDL files for each JS binding class, so we do not need to manually define these as sources.
=> LibWeb: Remove IDL files from CMake SOURCES

Tests/LibWeb/Layout/expected/grid/align-items.txt, Tests/LibWeb/Layout/expected/grid/align-self.txt, Tests/LibWeb/Layout/input/grid/align-items.html, Tests/LibWeb/Layout/input/grid/align-self.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Add support for `align-items` and `align-self` in CSS grid. Follows the same pattern as for `justify-items` and `justify-self`. 
The `baseline` alignment is not implemented. 
Using 2 items in the tests because otherwise the alignment differences are not visible.
=> LibWeb: Add support for `align-items` and `align-self` in CSS grid

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp, Tests/LibUnicode/TestUnicodeCharacterTypes.cpp, Userland/Libraries/LibUnicode/UnicodeUtils.cpp
First commit is a compile-time performance improvement to cut the runtime of GenerateUnicodeData from
3.4 seconds to 1.2 seconds.
Next is replacing the lookup tables for case information (which we currently binary-search at runtime) with 2-stage, constant-time lookup tables. Not *as* much of a win as code point property tables, but still a measurable improvement, and it's nice to have these tables all behave the same:
In total, this change:
* Does not change the size of libunicode.so (which is nice because,
generally, the 2-stage lookup tables are expected to trade a bit
of size for performance).
* Reduces the runtime of the new benchmark test case added here from
1.383s to 1.127s (about an 18.5% improvement).
=> LibUnicode: Perform code point case conversion lookups in constant time

Tests/LibWeb/Layout/expected/flex/list-container-display-contents.txt, Tests/LibWeb/Layout/input/flex/list-container-display-contents.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
This change makes tree builder omit elements with "display: contents" from the layout tree during construction. Their child elements are instead directly appended to the parent element in layout tree.
Visual progression on apple.com
Before:
After:
=> LibWeb: Add support for "display: contents"

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/HTMLMetaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMetaElement.h
Required by Atlassian to continue to their authorization process. Also used by the SerenityOS FAQ redirect on the website, the Bootstrap documentation for going to older versions from the dropdown and likely several other sites.
Demo:
https://github.com/SerenityOS/serenity/assets/25595356/f235e524-d6bf-4ed6-ad55-a8ebd03196e1
To try out Atlassian for yourself, you'll have to apply this patch. Note that it isn't a proper solution, it's only to make progress on Atlassian.
```patch
diff --git a/Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp b/Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
index 2b370ea4de..a2e3ece7a2 100644
--- a/Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
+++ b/Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
@@ -1235,6 +1235,7 @@ WebIDL::ExceptionOr<void> …
```
=> LibWeb: Implement `<meta http-equiv="Refresh">`

Tests/LibWeb/Layout/expected/block-and-inline/block-with-hidden-overflow-after-float.txt, Tests/LibWeb/Layout/expected/block-and-inline/block-with-hidden-overflow-after-sibling-float.txt, Tests/LibWeb/Layout/input/block-and-inline/block-with-hidden-overflow-after-float.html, Tests/LibWeb/Layout/input/block-and-inline/block-with-hidden-overflow-after-sibling-float.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h
Allow the left margin of a box which creates a block formatting context to overlap with left floating boxes which are siblings in the document tree.
Fixes #20233 and the comment layout on https://lobste.rs.
=> LibWeb: Handle overlapping floating box and left margin

AK/IntegralMath.h, Kernel/FileSystem/BlockBasedFileSystem.cpp, Kernel/FileSystem/BlockBasedFileSystem.h, Kernel/FileSystem/Ext2FS/FileSystem.cpp, Kernel/FileSystem/Ext2FS/FileSystem.h, Kernel/FileSystem/Ext2FS/Inode.cpp, Kernel/FileSystem/FATFS/FileSystem.cpp, Kernel/FileSystem/FATFS/Inode.cpp, Kernel/FileSystem/FileSystem.h, Kernel/FileSystem/ISO9660FS/DirectoryIterator.cpp, Kernel/FileSystem/ISO9660FS/FileSystem.cpp, Kernel/FileSystem/ISO9660FS/Inode.cpp, Kernel/FileSystem/SysFS/Subsystems/Kernel/DiskUsage.cpp, Kernel/Syscalls/statvfs.cpp, Tests/AK/TestIntegerMath.cpp
These superblocks and BGDTs are often referred to as "shadow" copies. They serve as backups in the case of corruption of the primary (or other) copies, since these datastructures are so essential. We were previously just ignoring them, so let's at least make sure they're consistent.
This should hopefully allow fsck (and other tooling) to more easily recover our file systems in case the driver does something stupid. For now, we don't actually consider the copies for recovering a broken file system, since we can't really do that anyways.
This change was heavily stress-tested with adding and removing plenty files, regular tests, whole-filesystem scans courtesy of SpaceAnalyzer, etc. No noticeable performance difference was observed.
=> Kernel/Ext2: Write redundant superblocks and block group descriptor tables

Tests/LibWeb/Layout/expected/flex/box-baseline-with-inline-flex-empty-child.txt, Tests/LibWeb/Layout/expected/input-element-with-display-inline.txt, Tests/LibWeb/Layout/expected/svg/svg-negative-elliptical-arg-number.txt, Tests/LibWeb/Layout/expected/svg/svg-path-with-implicit-lineto.txt, Tests/LibWeb/Layout/expected/svg/svg-with-css-variable-in-presentation-hint.txt, Tests/LibWeb/Layout/expected/svg/text-fill-none.txt, Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt, Tests/LibWeb/Layout/expected/table/inline-table-width.txt, Tests/LibWeb/Layout/input/flex/box-baseline-with-inline-flex-empty-child.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
If none of the box children have a baseline set, the bottom margin edge of the box is used as the baseline.
This was causing alignment issues for elements using `inline-flex` and empty children (eg. whitespace). 
Before/after screenshots for the `border-collapse-is-inherited.txt` test that has been updated (see top margin).
**After (Chrome + Ladybird)**
=> LibWeb: Only derive baseline from children with a non-empty line box

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibJS/Bytecode/Op.cpp
Because "this" value cannot be changed during function execution it is safe to compute it once and then use for future access.
This optimization makes ai-astar.js run 8% faster.
=> LibJS: Add caching of this value in ResolveThisBinding instruction

Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
A small workaround is needed here as \<stop\> elements don't create a layout node, so we can't get the current color from value->to_color().  
This fixes the gradients in the Atlassian logo and icons. 
| Before                                                                                                                              | After                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot from 2023-07-28 …
=> LibWeb: Resolve currentColor when used for SVG gradient <stop>s

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Checking if CSSPixels contains a finite value is no longer makes sense after converting to fixed-point arithmetics. Instead there should assertion that used value is not saturated.
=> LibWeb: Verify that value is not saturated in set_content_width/height

Tests/LibWeb/Text/expected/HTML/StructuredClone-object-primitives.txt, Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html, Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Adds support for serializing and deserializing standard built-in objects:
- Boolean object
- Number object
- String object
- Date object
I left out `BigIntObject` since the BigInt constructor returns primitive values of type BigInt, and the constructor can only be called without new, see extracted note from MDN:
> Note: BigInt() can only be called without new. Attempting to construct it with new throws a TypeError.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/BigInt
=> LibWeb: Serialize and deserialize standard built-in objects

Ladybird/FontPluginQt.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Tests/LibWeb/Layout/expected/css-all-unset.txt, Tests/LibWeb/Layout/expected/css-revert.txt, Tests/LibWeb/Layout/input/css-all-unset.html, Tests/LibWeb/Layout/input/css-revert.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/CSS/StyleValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/RevertStyleValue.h
Three things:
- Stop asking Qt about default fonts since it gets most answers wrong anyway. We get better results by just using our default fallback lists.
- Implement CSS `all` property keyword
- Implement CSS `revert` value keyword
Before:
After:
=> LibWeb+Ladybird: Better looking text on Twinings :^)

Meta/generate-libwasm-spec-test.py
This fixes the multiple "E721 do not compare types" failures that appeared during CI runs.
=> Meta: Use `is` instead of `==` to compare types

Userland/DevTools/HackStudio/HackStudioWidget.cpp, Userland/DevTools/HackStudio/HackStudioWidget.h
This feature is similar to Clion's "Open files with Single Click" which allows user to open file without double clicking it.
Note: This option is available under "View" menu.
=> HackStudio: Add option to open file in single click

Tests/Utilities/CMakeLists.txt, Tests/Utilities/TestPatch.cpp, Userland/Libraries/LibDiff/Hunks.cpp, Userland/Libraries/LibDiff/Hunks.h, Userland/Utilities/patch.cpp
Two more options taking steps to more useful patch implementation
Next steps after this, supporting multiple patches in the same patch file, and support adding a file from scratch.
=> LibDiff+patch: Add support for --strip, --directory, and add some tests

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
The three first commits are bugfixes and the last four are enhancements.
We are now failing at the image composition with the file [alpha_nonpremultiplied](https://github.com/libjxl/conformance/tree/master/testcases/alpha_nonpremultiplied).
---
**LibGfx/JPEGXL: Use the correct condition to read `save_before_ct`**
During the original implementation, I mixed the condition for
`save_before_ct` and the one for `save_before_ct`, resulting in a bogus
code. That's fixed now!
**LibGfx/JPEGXL: Perform size computation in a floating point type**
The computation was copied from the spec, but I forgot that they mention
that every "/" should be performed without truncation or rounding. Let's
use `double`s instead of integers.
**LibGfx/JPEGXL: Consider the HfGlobal section of the TOC**
There is always …
=> LibGfx/JPEGXL: Enough things to handle the header of one of the image of the compliance testsuite

Tests/Utilities/TestPatch.cpp, Userland/Libraries/LibDiff/Hunks.cpp, Userland/Libraries/LibDiff/Hunks.h, Userland/Utilities/patch.cpp, Userland/Utilities/run-tests.cpp
And a small bug fix for `run-tests` I noticed while testing this.
=> LibDiff+patch: Support creating a file, and parsing multiple patches in a patch file

Userland/Libraries/LibJS/Tests/syntax/async-await.js
The first test crashes in AST, and fails in bytecode, so the best thing which we can do here without complicated test setup logic is to just skip this test for now. Interestingly, this crashing test is very similar to the existing thenable test case, and only differs in the way that the thenable is given to the async function.
The next two tests are effectively the same as the above two mentioned tests, with the only different being that the thenable calls the fulfill function. For the test case that crashes in AST mode, doing that appears to fix the test case for AST mode (but both still fail in bytecode).
=> LibJS: Add three more await thenable tests

Ladybird/CMakeLists.txt, Ladybird/TVGIconEngine.cpp, Ladybird/TVGIconEngine.h, Ladybird/Tab.cpp, Ladybird/Tab.h, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibGfx/Painter.h
Rather than blit the icons to 16x16 bitmaps use a custom `QIconEngine` that keeps them as vector graphics.
**Before (2x)**
**After (2x)**
=> Ladybird: Keep toolbar icons crisp on high-DPI displays 

Tests/LibWeb/Layout/expected/css-calc-border-width.txt, Tests/LibWeb/Layout/input/css-calc-border-width.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
If a math function resolves to `<length>` or `<percentage>`, then it will by definition also resolve to `<length-percentage>`. (Same for any other basic types.) Since we were checking `<length-percentage>` first and then bailing if no given properties could accept that, math functions would always fail to match a property that just accepts a non `-percentage` type.
The whole way we match a calculated value against properties is quite awkward and probably needs a rethink, but at least this makes it work. :sweat_smile:
=> LibWeb: Match math function values to properties in correct order

Ladybird/WebContent/CMakeLists.txt, Ladybird/WebContent/main.cpp
Now that we no longer use QFont from LibWeb, we can also stop using QGuiApplication in the WebContent process entirely.
This removes a whole bunch of unnecessary work from the event loop, and also allows nice things like running headless-browser while *actually* headless. :^)
=> Ladybird: Use plain QCoreApplication in WebContent process

AK/MemoryStream.cpp, AK/MemoryStream.h, Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp, Userland/Libraries/LibVideo/VP9/Context.h
These methods are slightly more convenient than storing the Bytes separately. However, it it feels unsanitary to reach in and access this data directly. Both of the users of these already have the [Readonly]Bytes available in their constructors, and can easily avoid using these methods, so let's remove them entirely.
=> AK+Libraries: Remove `FixedMemoryStream::[readonly_]bytes()`

Userland/Applications/FileManager/CMakeLists.txt, Userland/Applications/FileManager/PropertiesWindow.cpp, Userland/Applications/FileManager/PropertiesWindow.h, Userland/Applications/FileManager/PropertiesWindowArchiveTab.gml, Userland/Applications/FileManager/PropertiesWindowPDFTab.gml, Userland/Libraries/LibArchive/Statistics.h, Userland/Libraries/LibArchive/Zip.cpp, Userland/Libraries/LibArchive/Zip.h, Userland/Utilities/file.cpp, Userland/Utilities/unzip.cpp
A couple more file types you can now inspect. For ZIP, I left things so they could apply to other kinds of archive, we just don't have a convenient way to scan through them to get statistics yet.
=> FileManager: Add file properties tabs for ZIP and PDF files

Tests/LibWeb/Layout/expected/css-snap-a-length-as-a-border-width.txt, Tests/LibWeb/Layout/input/css-snap-a-length-as-a-border-width.html, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/Layout/LayoutState.cpp, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp, Userland/Libraries/LibWeb/Painting/BorderPainting.cpp, Userland/Libraries/LibWeb/Painting/PaintContext.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
...and a couple of tweaks to the internals.
**Before:**
**After:**
**Firefox:**
=> LibWeb: Add and use the "snap a length as a border width" algorithm

AK/LexicalPath.h, Meta/CMake/libweb_generators.cmake, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp, Meta/gn/secondary/Userland/Libraries/LibWeb/generate_idl_bindings.gni
This reduces the number of tasks to schedule, and the complexity of the
build system integrations for the BindingsGenerator. As a bonus, we move
the "only write if changed" feature into the generator to reduce the
build system load on generated files for this generator.
cc @nico
=> Meta+BindingsGenerator: Only invoke BindingsGenerator once per IDL file

Ladybird/TVGIconEngine.cpp, Ladybird/TVGIconEngine.h, Ladybird/Tab.cpp
Rather than set a hacky scale factor on our QIconEngine, just set the icon size for the toolbar icons. This avoids the icons being unnecessarily scaled in other places (i.e. the context menu).
**Before:**
**After:**
=> Ladybird: Fix silly tiny back/forward/reload icons in context menu

AK/Math.h
These are useful in other algorithms, so lets move them up
These are useful in some algorithms, which require specific rounding.
Both GCC and Clang inline this function to use bit-wise logic and/or
appropriate instructions even on -O0 and allow their use in a constexpr
context, see
<https://godbolt.org/z/de1393vha>
We were using the double ones, forcing casts to and from them for floats
=> AK: Steps towards more general Math, starting with fmod/remainder

Tests/LibWeb/Text/expected/css/element-opacity-change-invalidation.txt, Tests/LibWeb/Text/input/css/element-opacity-change-invalidation.html, Userland/Libraries/LibWeb/DOM/Element.cpp
...since they can also be percentages. Better to resolve them to a pair of absolute values, and then compare those. :^)
Regressed in 921aee8c666fbab2dcdba27cbefc942f1a144180.
=> LibWeb: Don't assume opacity values are CSS numbers

Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
When a cell spans the entire width or height of a table, create its border from the table box.
=> LibWeb: Fix border for cells spanning entire table width or height

Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
This patch changes the way StructuredSerializeInternal() serialize strings by storing four bytes into a 32-bit entry, instead of one code point per 32-bit entry.
StructuredDeserialize() has also been changed to deserialize strings by the same ruleset.
=> LibWeb: Serialize strings into a more storage efficient format

Userland/Utilities/nohup.cpp
A little oopsie that I forgot to account for in #19743.
Since we may redirect stdout, stderr, or both to the file description referring to the nohup.out file, there is no need to keep the fd that created that file description around.
=> nohup: Don't leak fd used to open nohup.out

Documentation/README.md
New docs get added but they do not get mentioned in `Documentation/README.md`.
Check that new links are under the right category.
Sub-directories should probably have their own `README.md`. And maybe more sub-directories/categories should me made.
=> Documentation: Add links of all docs that aren't mentioned anywhere

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
There's no advantage to writing more than one file, and it lets the depfile work with older versions of ninja.
=> Meta: Only write first output file to depfile

Ladybird/FontPluginLadybird.cpp, Ladybird/FontPluginLadybird.h, Ladybird/WebContent/CMakeLists.txt, Ladybird/WebContent/main.cpp, Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
The Qt relationship was removed in de31a8a4, so let's acknowledge that and make it clearer to potential non-Qt ports that this file is usable by them :^).
=> Ladybird: Rename FontPluginQt -> Ladybird as it is unrelated to Qt now

Kernel/API/Syscall.h, Kernel/Syscalls/poll.cpp
I verified that everything that looks sensible was accessed through a mutex or a spinlock, so I guess that's okay, but I'm pretty sure someone with more kernel experience wants to give it a close look.
=> Kernel: Mark sys$poll as not needing the big lock

Ladybird/ConsoleWidget.cpp
Do not try to navigate JS console history forward when it is empty. A crash was occurring because of size_t underflow.
=> Ladybird: Fix JS console crash when history is empty

Ladybird/HelperProcess.cpp, Ladybird/HelperProcess.h
The spawn_helper_process method was introduced together with get_paths_for_helper_process but was only ever used briefly to spawn WebContent. Other helper processes (SqlServer, headless_browser etc) are either execed or spawned with their own helpers & custom arguments.
=> Ladybird: Remove unused spawn helper

Userland/Libraries/LibWeb/CSS/CSSRuleList.cpp, Userland/Libraries/LibWeb/CSS/CSSRuleList.h, Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
CSSStyleSheet now caches the CSSNamespaceRule for the default namespace, which is the only one we currently care about. This saves us from iterating over its list of rules every time we want to know what that default namespace is.
The spec dictates that `@namespace` rules are only valid near the start of a stylesheet, so we also take advantage of that to quit searching for namespaces as soon as we see a non-import rule.
Also renamed `namespace_filter()` to `default_namespace()` since that's what it actually returns.
This makes github.com/serenityos/serenity snappy again. :^)
=> LibWeb: Speed up CSS namespace checking

AK/URLParser.cpp, Tests/AK/TestURL.cpp
By not clearing the buffer, we were leaking the path part of a URL into the query for URLs without an authority component (no '//host').
This could be seen most noticeably in mailto: URLs with header fields set, as the query part of `mailto:user@example.com?subject=test` was parsed to `user@example.comsubject=test`.
data: URLs didn't have this problem, because we have a special case for parsing them.
=> AK: Clear buffer after leaving CannotBeABaseUrlPath in URLParser

AK/URL.cpp, AK/URL.h, AK/URLParser.cpp, AK/URLParser.h, Tests/AK/TestURL.cpp, Userland/Applications/Spreadsheet/HelpWindow.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp, Userland/Libraries/LibWeb/Loader/Resource.cpp, Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
as hinted in https://github.com/SerenityOS/serenity/pull/19850 :)
first, remove unnecessary calls to specific data: url functions, where calling process_data_url() would be inefficient:
- **LibWeb: Remove checking for AllowedDataUrlType**
CSS shouldn't probably check if a MIME type in the 'data:' URL is correct or not. Every URL gets sent to a ResourceLoader so a client can just validate if got file with correct media type.
This also makes loading 'data:' URLs in @​import work now, as we didn't have AllowedDataUrlType for stylesheets.
- **LibWeb: Set Content-Type for data: URLs instead of checking MIME on load**
This makes the loader more agnostic.
Additionally, this allows us to load tab in Ladybird with a 'data:' URL containing parameters, as a Resource will now call …
=> AK+Userland: Parse 'data:' URLs like every other URL and decode them (when needed) to a separate class

Tests/LibWeb/Layout/expected/grid/row-1fr.txt, Tests/LibWeb/Layout/input/grid/row-1fr.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Fixes the issue that before "automatic minimum size" were used to size flexible tracks even though specification says is should be "minimum contribution"
=> LibWeb: Use item minimum contribution while sizing "fr" track in GFC

Userland/Libraries/LibWeb/Layout/VideoBox.cpp, Userland/Libraries/LibWeb/Layout/VideoBox.h, Userland/Libraries/LibWeb/Painting/AudioPaintable.cpp, Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
This lets us go wild and have a video and audio element on one page:
https://github.com/SerenityOS/serenity/assets/5600524/bc9f4333-97ae-45e6-93b3-86c0bd0bb91f
=> LibWeb: Clip rect fixes for media elements

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Selector.cpp, Userland/Libraries/LibWeb/CSS/Selector.h, Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp, Userland/Libraries/LibWeb/Dump.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
These all affect `<video>` and `<audio>` elements. 
- `:playing`
- `:paused`
- `:seeking`
- `:muted`
- `:volume-locked` (This refers to a UA feature allowing the user to lock the volume on a media element so that nothing can modify it. We don't support that, so it's always false.)
- `:buffering`
- `:stalled` (We don't implement the stall timeout, so this is always false.)
The lack of WPT tests, and other-browser support for these means I'm not certain I'm doing things correctly for all of these pseudo-classes, but they seem right. :sweat_smile:
=> LibWeb: Implement media-related pseudo-classes

Tests/LibWeb/Layout/expected/flex/flex-column-container-with-max-width-max-content.txt, Tests/LibWeb/Layout/input/flex/flex-column-container-with-max-width-max-content.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Properties like min-width, max-width, etc, should be ignored while we're trying to determine the intrinsic size of a flex container.
This fixes an infinite recursion when using an intrinsic size keyword as the max-width of a flex column container.
Note that this behavior is marked as AD-HOC in code comments because specs don't tell us how to achieve intrinsic sizing.
We can now load product pages on the Twinings site, such as https://twinings.co.uk/products/earl-grey-100-tea-bags :^)
Screenshot:
=> LibWeb: Ignore flex container size constraints during intrinsic sizing

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h
This allows JS access in fetch CORS requests to headers listed in Access-Control-Expose-Headers. 
Also moved some of the existing header-value list parsing into extract_header_values. This part isn't a full implementation, but works for the headers we currently use and tidies up the existing parsing into once place.
Resolves #18626
=>  LibWeb: Support Access-Control-Expose-Headers in Fetch

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp, Userland/Libraries/LibWeb/FileAPI/BlobURLStore.cpp, Userland/Libraries/LibWeb/FileAPI/BlobURLStore.h, Userland/Libraries/LibWeb/URL/URL.cpp, Userland/Libraries/LibWeb/URL/URL.h, Userland/Libraries/LibWeb/URL/URL.idl
Tested with the following HTML running on a local server:
```html
<html>
<body>
<script type="text/javascript">
async function test() {
const response = await fetch('./90s-bg.png');
const data = await response.blob();
return URL.createObjectURL(data);
}
test().then(url => {
let image = new Image(240, 240)
image.src = url;
image.onload = () => {
URL.revokeObjectURL(image.src);
};
document.body.appendChild(image);
});
</script>
</body>
</html>
```
This test isn't added in-tree because CORS prevents the `fetch` invocation from working on `file://` URLs.
=> LibWeb: Implement an ephemeral `URL.createObjectURL`

Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
This fixes the "last changed" time for files on GitHub. Note that this appears to be in accordance with the shadow DOM specification, but I can't find a line that neatly says it. Though on Google's post about shadow DOM v1 it says:
> "the element's shadow DOM is rendered in place of its children."
https://web.dev/shadowdom-v1/#creating-shadow-dom-for-a-custom-element
Progression on GitHub:
**Before:**
**After:**
=> LibWeb: Don't lay out light DOM children of elements with a shadow root 

Tests/LibWeb/Layout/expected/block-and-inline/max-width-for-box-with-inline-children.txt, Tests/LibWeb/Layout/input/block-and-inline/max-width-for-box-with-inline-children.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
max-width for boxes with inline children can only be applied after inside layout is done and width of box content is known.
Fixes https://github.com/SerenityOS/serenity/issues/20235
=> LibWeb: Set max-width for inline child boxes after inside layout

Userland/Applications/Mail/MailWidget.cpp, Userland/Libraries/LibIMAP/Objects.cpp
> [6.4.5. ](https://www.rfc-editor.org/rfc/rfc9051#section-6.4.5)[FETCH Command](https://www.rfc-editor.org/rfc/rfc9051#name-fetch-command)
>
> <dl>
> <dt>BODY[&lt;section&gt;]&lt;&lt;partial&gt;&gt;
> <dd> [...]<br>
>    The \Seen flag is implicitly set; if this causes the flags to change, they SHOULD be included as part of the FETCH responses.
> <dt>BODY.PEEK[&lt;section&gt;]&lt;&lt;partial&gt;&gt;
> <dd>An alternate form of BODY[&lt;section&gt;] that does not implicitly set the \Seen flag.
> </dl>
:p
=> Mail+LibIMAP: Don't set the whole mailbox as read

Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/MediaFeatures.json, Userland/Libraries/LibWeb/CSS/TransformFunctions.json
Mostly this is about 2-space indentation, but we now also only have one key:value pair per line.
As pointed out by @TobyAsE!
The transform function definitions ended up more verbose, but eh.
=> LibWeb: Reformat inconsistent CSS JSON files

Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
If we do not recognize the Type being serialized make sure we always fallback to setting m_error to "Unsupported type".
=> LibWeb: Make sure we fallback to "Unsupported type" if type unrecognized
