SerenityOS/serenity

- Tests/LibWeb/Layout/expected/css-pseudo-element-should-not-be-affected-by-inline-style.txt
- Tests/LibWeb/Layout/expected/css-pseudo-element-should-not-be-affected-by-presentational-hints.txt
- Tests/LibWeb/Layout/expected/position-empty-pseudo-elements.txt
- Tests/LibWeb/Layout/expected/pseudo-element-with-custom-properties-2.txt
- Tests/LibWeb/Layout/expected/pseudo-element-with-custom-properties.txt
- Tests/LibWeb/Layout/input/position-empty-pseudo-elements.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Layout/TextNode.cpp
- Userland/Libraries/LibWeb/Layout/TextNode.h
- **Revert "LibWeb: Make TextNode::ChunkIterator emit an empty chunk for content:"""**
This reverts commit b062a0fb7cb44036d16a36269164c537b137c3a4.
This made a calculation of pseudo-elements' height incorrect when they had `height` set to `auto` and used other techniques (like setting `padding-top`) to set height, as it was now also adding an empty line.
Additionally, the case didn't work for content containing whitespace characters, so a pseudo-element with `content: " "` didn't have *this* particular problem.
- **LibWeb: Include anonymous boxes with no lines into computing BFC height**
Pseudo-elements like `::before` and `::after` were discarded when their content property was an empty string (ignoring whitespace), because they are anonymous containers, with no lines.
Our previous way …
> LibWeb: Don't ignore pseudo-elements when computing BFC height

- Ladybird/RequestServer/CMakeLists.txt
Ladybird's RequestServer needs to depend on its generated IPC header files to ensure they are generated before RequestServer is compiled. We currently bundle the IPC headers into LibWebView, so the easiest method would be to make RequestServer depend on LibWebView. This would be a bit awkward though, because there's no reason for RequestServer to depend on all other things in LibWebView just for these headers.
So this breaks the RequestServer IPC headers into an INTERFACE library, and makes Ladybird's RequestServer depend on it. This can be changed to a normal library if any .cpp sources are added in the future.
> Ladybird: Ensure RequestServer depends on its generated sources

- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
This fixes an issue with some typefaces where the space character has an advance width, but no glyf entry (and thus no ascent/descent). Before this change, we'd render whitespace with zero advance in such cases.
Visual progression on a website that uses DIN fonts:
Before:
After:
> LibGfx/OpenType: Return metrics from hmtx even if there is no glyf entry

- Base/res/html/misc/inline-node.html
- Base/res/html/misc/outline.html
- Base/res/html/misc/welcome.html
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/Dump.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
- Userland/Libraries/LibWeb/Painting/BorderPainting.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Chrome on the left, Ladybird on the right:
Chrome on the left, Ladybird on the right:
(They're really showing off with that waviness on the green outline!)
> LibWeb: Implement `outline` and its related properties

- Userland/Libraries/LibCore/DirIterator.cpp
- Userland/Libraries/LibCore/DirectoryEntry.cpp
- Userland/Libraries/LibCore/DirectoryEntry.h
Solaris/Illumos does not have a d_type in its dirent struct, so building on Solaris was broken since March 5.
See here: https://software.cfht.hawaii.edu/man/solaris/dirent(4)
(I initially thought it would work on Solaris when I submitted a patch only for OpenBSD, but I was wrong)
Now, months after maintaining my ugly local hack that always returns DirectoryEntry::Type::Unknown, I finally wrote a clean solution that falls back to using fstat on Solaris, and possibly other OSes that don't have d_type (are there any?).
I verified that Ladybird builds and runs fine on Solaris with this change.
I also verified that I haven't broken it for other operating systems by building that change on FreeBSD.
> LibCore: Fallback to fstat() on systems without d_type support

- Userland/Libraries/LibWebView/ViewImplementation.cpp
This helps the GTK version of Ladybird to import them into the GTK rendering machinery, since [`GdkMemoryFormat`](https://docs.gtk.org/gdk4/enum.MemoryFormat.html) supports [BGRA](https://docs.gtk.org/gdk4/enum.MemoryFormat.html#b8g8r8a8) and [BGR](https://docs.gtk.org/gdk4/enum.MemoryFormat.html#b8g8r8), but not BGRx. ~~This also makes it possible to properly render HTML content with an otherwise transparent background.~~
cc @ADKaster @Zaggy1024
> LibWebView: Create BGRA bitmaps instead of BGRx

- Tests/LibWeb/Layout/expected/grid/two-items-spanning-one-1fr-row.txt
- Tests/LibWeb/Layout/input/grid/two-items-spanning-one-1fr-row.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Fixes bug when planned_increase is not reset after adding it to base_size.
> LibWeb: Reset planned_increase while distributing space to "fr" tracks

- Meta/gn/build/BUILD.gn
The GCC build is extremely noisy without -Wno-literal-suffix. (Tested on GCC12)
> Meta: Port GCC compile option from cmake to gn

- Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
I found a visual glitch on a Dutch tech website (https://tweakers.net/). In the search bar button the text label "Zoeken" = "Search" was visible over the search icon.
On the `input type="submit"` the CSS propeties `text-indent: -1000px` with `overflow: hidden` are used to move the text outside of the button. I have added the code to read the `text-indent` and move the text label inside the button in `ButtonPaintable.cpp`.
Before:
After:
This is my first commit to SerenityOS so probably there is a lot wrong with my changes
I am looking forward to your feedback ;)
> LibWeb: Use CSS text-indent property on input type="submit" elements text

- Userland/Utilities/watch.cpp
This matches the behavior of watch on Linux.
Example usage:
https://github.com/SerenityOS/serenity/assets/2817754/ea93e3c9-0d54-4de5-b5b4-6a428a069c72
> watch: Use alternate buffer to display output

- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
And fix a missing GC `visit_edges()` while we're passing through `CSSStyleSheet`.
> LibWeb: Some low-hanging performance fruit on the Discord web interface

- .github/workflows/cmake.yml
For some reason, the tests are flaky for the aarch64 architecture when running on a CI runner. This causes a lot of unnecessary red crosses for PRs and since the test outcome doesn't seem to be too trustworthy, we are better off not running these tests for now.
> CI: Disable aarch64 tests

- Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
- Userland/Libraries/LibWeb/HTML/EventLoop/Task.h
- Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.h
- Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.idl
- **LibWeb: Implement HTMLCanvasElement.toDataUrl() closer to spec**
- Requesting an unsupported image type will now fallback to PNG,
- Errors should return 'data:,' instead of empty string,
- Added spec comments
- **LibWeb: Implement HTMLCanvasElement.toBlob()**
- **LibWeb: Add support for encoding Canvas to JPEG**
- **Meta: Add ImageFormats/JPEGWriter.cpp to gn build**
> LibWeb: Improve HTMLCanvasElement.toDataUrl(), implement .toBlob(), and support encoding to JPEG

- Userland/Shell/PosixLexer.cpp
- Userland/Shell/PosixLexer.h
- Userland/Shell/PosixParser.cpp
- Userland/Shell/PosixParser.h
Previously any expansion closing sequence would've caused the entire
expansion chain to be terminated, fix this by keeping track of active
expansions and running the parser in 'skip' mode.
Fixes #19110.
> Shell: A couple tiny POSIX fixes

- Userland/Applications/PixelPaint/CMakeLists.txt
- Userland/Applications/PixelPaint/ColorMasking.gml
- Userland/Applications/PixelPaint/ImageEditor.cpp
- Userland/Applications/PixelPaint/ImageEditor.h
- Userland/Applications/PixelPaint/ImageMasking.cpp
- Userland/Applications/PixelPaint/ImageMasking.h
- Userland/Applications/PixelPaint/ImageProcessor.cpp
- Userland/Applications/PixelPaint/Layer.cpp
- Userland/Applications/PixelPaint/Layer.h
- Userland/Applications/PixelPaint/LuminosityMasking.gml
- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Applications/PixelPaint/MainWidget.h
- Userland/Libraries/LibGUI/CMakeLists.txt
- Userland/Libraries/LibGUI/RangeSlider.cpp
- Userland/Libraries/LibGUI/RangeSlider.h
- Userland/Services/WindowServer/Menu.cpp
This pr has the following new functions for editing masks:
- adds a option to make editing masks visible so that it's easier to make changes to the masks
- adds a "Luminisity Masking" function that can be used to refine editing masks to certain luminosity values of the content image
- adds a "Color Masking" function that can be used to refine editing masks based in the color of the content pixels
- filter gallery makes changes only to masked regions if a editing mask is defined
- makes image editing with PixelPaint more brrrr
Preview Luminosity Masking:
Preview Color Masking:
> PixelPaint: Add luminosity and color masking for editing masks

- Userland/Applications/Piano/MainWidget.cpp
- Userland/Applications/Piano/Music.h
- Userland/Applications/Piano/WaveWidget.cpp
- Userland/Applications/Piano/WaveWidget.h
- Userland/Libraries/LibAudio/Sample.h
- Userland/Libraries/LibDSP/Track.cpp
- Userland/Libraries/LibDSP/Track.h
It did not call `PlayerWidget.initialize()` which caused a crash every time a new track was added. Additionally the wave form could not be drawn anymore since the logic was moved to LibDSP. And lastly it wasn't possible to remove any notes as the clicked mouse button is not available within `mousemove_event`.
> Piano: Fix creation of PlayerWidget, drawing of wave form and removing of notes

- Userland/Libraries/LibMarkdown/CodeBlock.cpp
Specifically, `CodeBlock::render_lines_for_terminal()` eats up blank lines because it uses `DeprecatedString::split()` without the `SplitBehavior::KeepEmpty` enum. Easy fix: use the enum.
Before:
After:
Discovered while working on #20348.
> LibMarkdown: Preserve blank lines in `CodeBlock`s

- Tests/LibWeb/Layout/expected/abspos-box-with-replaced-element.txt
- Tests/LibWeb/Layout/expected/image-with-multiple-constraint-violations.txt
- Tests/LibWeb/TestCSSPixels.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/PixelUnits.cpp
Use 64 bit integer for the intermediate value in the multiplication of CSSPixels to avoid overflow and change associativity in computing of replaced element size to improve precision of division.
Fixes vertically squashed image from Mozilla splash page MDN example.
> LibWeb: Improve precision when computing size of replaced elements

- Ports/glm/package.sh
Previously, the `glm` port would not build from a clean state, as this directory does not exist by default.
> Ports/glm: Create `/usr/local/include` if it doesn't exist

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
3dd3120a8a15bdafc3d884878b52de37f3b60ec5 changed open mode from Write to ReadWrite, which stopped truncating files.
This could be noticed by building a slightly older branch, as compiling it gave compile errors.
> Meta: Truncate generated IDL source files

- Userland/Utilities/sed.cpp
This solves an issue where user and permissions where lost after using `pls sed -i s/foo/bar/g` on a file.
Permissions of 777 still get mangled to 755, but that seems to be an issue with `FileSystem::copy_file()`.
CC @ADKaster @kleinesfilmroellchen
> sed: Keep correct owner and permissions with `sed -i`

- Ladybird/CMakeLists.txt
- Ladybird/EventLoopImplementationQt.cpp
- Ladybird/EventLoopImplementationQt.h
- Ladybird/EventLoopImplementationQtEventTarget.cpp
- Ladybird/EventLoopImplementationQtEventTarget.h
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/WebContent/main.cpp
- Meta/Lagom/CMakeLists.txt
- Tests/LibCore/CMakeLists.txt
- Tests/LibCore/TestLibCorePromise.cpp
- Userland/Libraries/LibAudio/CMakeLists.txt
- Userland/Libraries/LibAudio/Forward.h
- Userland/Libraries/LibAudio/PlaybackStream.cpp
- Userland/Libraries/LibAudio/PlaybackStream.h
- Userland/Libraries/LibAudio/PlaybackStreamPulseAudio.cpp
- Userland/Libraries/LibAudio/PlaybackStreamPulseAudio.h
- Userland/Libraries/LibAudio/PulseAudioWrappers.cpp
- Userland/Libraries/LibAudio/PulseAudioWrappers.h
- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibCore/EventLoop.h
- Userland/Libraries/LibCore/Forward.h
- Userland/Libraries/LibCore/ThreadedPromise.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
- Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.h
This adds an abstract audio output interface to LibAudio that allows applications to play back audio without needing to be aware of the platform on which they are running. The only implementation currently is for PulseAudio, but an implementation for Serenity should not be difficult to add.
The interface is used by a new Ladybird audio output plugin which will eventually replace the existing plugins, once platform support is good enough.
The benefits over the current Qt-based audio playback plugin in Ladybird are:
- Low latency: With direct access to PulseAudio, we can ask for a small 100ms latency to output to allow minimal delay when pausing or seeking a stream.
- Accurate timestamps: The Qt audio playback API does not expose audio time properly. When we have access directly to …
> Ladybird/LibAudio: Use PulseAudio APIs directly for Lagom audio output

- Userland/Shell/AST.cpp
Before, if a bareword wasn't a runnable program's filename it got colored red and white otherwise. Now, additionally it will be checked if it is a "prefix" of a possible command and colored yellow if it is and red if not.
Coloring this way provides another "feedback" to the user: If while typing out a command name the color changes from yellow to red then a typo occurred :^)
To check if a bareword is a prefix the `Shell::complete_program_name()` function is utilized (if pressing tab gives you some suggestions then it is a prefix).
---
"se" is a prefix of "sed" and "sep" is not a command.
---
But... is checking for completions for every letter typed worth it for this feature?
---
When i first used serenity's terminal i thought of this feature. After looking around at wrong places …
> Shell: Color bareword yellow if it's a prefix of at least one command

- Meta/serenity_gdb.py
The pretty-print gdb helpers were not updated since the DeprecatedString change. This commit introduces a new printer for String and renames the old one to DeprecatedString.
StringImpl and StringView were also displayed character-by-character in the pretty printer. This is now changed to properly show the full "concatenated" string.
> Meta: Implement support for the new String in the gdb formatter

- Ports/freetype/package.sh
- Ports/freetype/patches/0001-libtool-Enable-shared-library-support-for-SerenityOS.patch
- Ports/freetype/patches/ReadMe.md
- Ports/gettext/package.sh
- Ports/gettext/patches/0001-Stub-out-some-wctype-functions.patch
- Ports/gettext/patches/0002-libtool-Enable-shared-library-support-for-SerenityOS.patch
- Ports/gettext/patches/ReadMe.md
- Ports/zlib/package.sh
These just happen to work right now because our compilers default to compiling every object with `-fPIC`. I would like to change this to `-fPIE` in the next toolchain update, which only permits the object to be linked into an executable (and produces better code as a result). Libtool automatically adds the necessary compiler flags when building a shared object, we just need to tell it that we support those. See also #14178 and #6694.
**Ports/zlib: Do not manually link zlib into a shared library**
Instead, pass our system name to its (non-autotools) configure script.
Tell it to include a SONAME to avoid breaking dependent ports when
updating zlib.
**Ports: Replace manually linking freetype with a libtool patch**
**Ports/gettext: Replace manually linking libintl with a libtool patch**
The …
> Ports: Remove the remaining instances of linking static libraries into shared libraries

- Ladybird/WebContentView.cpp
- Userland/Services/WebContent/ConnectionFromClient.cpp
Rather than directing mouse wheel events to the QAbstractScrollArea,
send them to the WebContent process, allowing it to determine if they
should be consumed by the element or used for page scrolling.
> Ladybird: Send mouse wheel events to WebContent process

- Userland/Libraries/LibWeb/SVG/SVGRectElement.cpp
Previously, this would treat having both rx and ry set as if just rx was set. The checks are now updated to match the spec comments above them :).
Small progression on Inkscape camera.svg:
**Before**
**After**
> LibWeb: Fix calculating the corner radius values for SVG <rect>

- Userland/Applications/Spreadsheet/Workbook.cpp
- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/Error.cpp
- Userland/Libraries/LibJS/Runtime/Error.h
- Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
- Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/SourceRange.h
This loosens the connection to the AST interpreter and will allow us to generate SourceRanges for the Bytecode interpreter in the future as well
Moves UnrealizedSourceRanges from TracebackFrame to the JS namespace for this
---
Next step would be figuring out a way to correlate instructions to source ranges
> LibJS: Capture UnrealizedSourceRanges in ExecutionContext, not ASTNodes

- Tests/LibWeb/Layout/expected/block-and-inline/min-width-for-box-with-inline-children.txt
- Tests/LibWeb/Layout/input/block-and-inline/min-width-for-box-with-inline-children.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
min-width for boxes with inline children can only be applied after inside layout is done and width of box content is known.
> LibWeb: Set min-width for inline child boxes after inside layout

- Tests/LibWeb/Layout/expected/table/percentage-width-columns.txt
- Tests/LibWeb/Layout/expected/table/percentage-width-max-width-columns.txt
- Tests/LibWeb/Layout/expected/table/sum-of-percentage-column-widths-less-than-100.txt
- Tests/LibWeb/Layout/input/table/percentage-width-max-width-columns.html
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Use the max-width of percentage cells instead of min-width as the reference to be used to compute the total table width. The specification only suggests that the UA should try to satisfy percentage constraints and this behavior is more consistent with other browsers.
> LibWeb: Improve adjustment of automatic table width with percentages

- Ports/vim/package.sh
`vim` does not use a mechanism like `config.sub` for determining the canonical system name from the `--target` triple passed to `configure`. Instead, it directly executes the `uname` executable on the host. This leads to it trying to build macOS-specific files on Mac hosts even if we are compiling for a different platform. To make cross-compilation possible, developers added a way to override `uname`'s output with environment variables. Let's set these.
See vim/vim#9338
Obsoletes #11426
> Ports/vim: Override `uname` output to fix compilation on macOS

- Tests/LibWeb/Layout/expected/flex/intrinsic-height-of-column-items-with-different-kinds-of-width.txt
- Tests/LibWeb/Layout/input/flex/intrinsic-height-of-column-items-with-different-kinds-of-width.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
This stuff is pretty hairy since the specifications don't give any guidance on which widths to use when calculating the intrinsic height of flex items in a column layout.
However, our old behavior of "treat anything indefinite as fit-content" was definitely not good enough, so this patch improves the situation by considering values like `min-content`, `max-content` and `fit-content` separately from `auto`, and making the whole flex layout pipeline aware of them (in the cross axis context).
Visual progression on Bandcamp ("Listen now" buttons)
Before:
After:
> LibWeb: Support more kinds of indefinite widths on flex column items

- Userland/Utilities/top.cpp
This means we no longer show any characters the user types while top is running.
Disabling line buffering has the same effect as enabling non-blocking I/O, but it doesn't crash the terminal when we exit the program without restoring stdin to its original state. This would previously happen when a SIGKILL signal was received, for example.
Video showing the issues fixed by this PR:
https://github.com/SerenityOS/serenity/assets/2817754/423220d1-bff9-4b35-b8da-408c505df2ad
> top: Disable echo and line buffering on startup

- Ports/potrace/package.sh
This allows the `potrace` port to build from a clean state.
> Ports/potrace: Add zlib dependency

- Ladybird/WebContentView.cpp
Documentation says that pixelDelta() is not reliable across platforms so always using angleDelta() should produce more predictable scrolling behaviour.
> Ladybird: Do not try to use pixelDelta() to calculate wheel offset

- Tests/LibWeb/Layout/expected/css-host-selector-gets-parsed.txt
- Tests/LibWeb/Layout/input/css-host-selector-gets-parsed.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/Dump.cpp
We were already parsing non-function-syntax `:host`, so let's also do the `:host(...)` variant. Note that we don't have matching for these yet.
This fixes many issues on sites generated by Wix, as they often have selector lists that include some `:host()` selector, and we'd reject the entire rule after failing to parse it.
This makes it much easier to contact my local pizza place!
Before:
After:
> LibWeb: Parse :host() selector

- Base/res/html/misc/canvas-text.html
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.idl
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.idl
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
I have added basic support for the Canvas Context2D text rendering text alignment and text baseline. I'm not really super familiar with the LibWeb source code yet but I did my best ;)
The only issue I have is that when I put the enum `CanvasTextAlign` in `CanvasTextDrawingStyles.idl` I can't use it or include it in C++, but for now I have put it in `CanvasRenderingContext2D.idl` like `ImageSmoothingQuality`.
I have only implemented top, middle and bottom for text baseline because to my knowledge the `draw_text` function in LibGfx doesn't support precise baseline positioning at the moment.
Right now only the `ctx.fillText()` function uses these new values we need to expand that in the future.
Before:
After:
I'm looking forward to your feedback
> LibWeb: Add Canvas Context2D basic text align and text baseline support

- Base/usr/share/man/man1/fortune.md
- Userland/Utilities/fortune.cpp
This changes the default behavior, so that, by default, color codes, hyperlinks and additional spacing are only emitted when standard output is connected to a terminal.
The default coloring behavior can be overridden with the `--color` option. Valid arguments for this option are: 'always', 'never' and 'auto' (default).
My motivation for doing this was to improve the formatting of `fortune | cowsay`.
Before:
After:
> fortune: Use simple formatting when stdout isn't connected to a terminal

- Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
- Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h
This allows avoiding accumulating values we know will be zero, this is not a huge speedup but does shave off a few %.
> LibGfx: Track edge extent in EdgeFlagPathRasterizer

- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibCore/Object.cpp
- Userland/Libraries/LibCore/Object.h
- Userland/Libraries/LibGUI/CMakeLists.txt
- Userland/Libraries/LibGUI/Forward.h
- Userland/Libraries/LibGUI/GML/AutocompleteProvider.cpp
- Userland/Libraries/LibGUI/Layout.cpp
- Userland/Libraries/LibGUI/Layout.h
- Userland/Libraries/LibGUI/Object.cpp
- Userland/Libraries/LibGUI/Object.h
- Userland/Libraries/LibGUI/Property.cpp
- Userland/Libraries/LibGUI/Property.h
- Userland/Libraries/LibGUI/ScrollableContainerWidget.cpp
- Userland/Libraries/LibGUI/Widget.cpp
- Userland/Libraries/LibGUI/Widget.h
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGUI/Window.h
- Userland/Libraries/LibThreading/Thread.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Shell/Shell.h
- Userland/Utilities/js.cpp
Since Core::Object properties are really only used by GML now that the
Inspector is long gone, there's no need for these to pollute
Core::Object.
This patch adds a new GUI::Object class to hold properties, and makes
it the new base class of GUI::Window, GUI::Widget and GUI::Layout.
The "instantiate an object by name" mechanism that GML uses is also
hoisted into GUI::Object as well.
...and also some tangential removal of unused code. :^)
> LibGUI+LibCore: Move GML property system from LibCore to LibGUI

- Ports/nesalizer/patches/0001-Add-Serenity-to-Makefile.patch
- Ports/nesalizer/patches/ReadMe.md
Previously, we were relying on the host's SDL2 headers. If none were present the build would fail.
Contributes to #18238
> Ports/nesalizer: Add SDL2 header include path to Makefile

- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
- Userland/Libraries/LibWeb/Painting/MediaPaintable.h
The volume control's slider is drawn in a rectangle shrunken by its slider handle's size, so the handle did not move 1:1 with the user's mouse movement.
To fix this, it will now check for a mousedown in the volume control with a rectangle sized to fit any possible position of the handle, but the volume value result will be calculated based on the center of the handle instead. This allows it to move 1:1 with the mouse cursor.
Before:
https://github.com/SerenityOS/serenity/assets/3149592/0358b36a-965a-445b-90e9-f9854058265c
After:
https://github.com/SerenityOS/serenity/assets/3149592/7d854f38-4b0d-472f-8509-8d285770b198
cc @trflynn89
> LibWeb: Move the media volume slider 1:1 with the mouse cursor

- Tests/LibWeb/Layout/expected/misc/scroll.txt
- Tests/LibWeb/Layout/input/misc/scroll.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/Dump.cpp
- Userland/Libraries/LibWeb/Layout/Box.cpp
- Userland/Libraries/LibWeb/Layout/Box.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Userland/Libraries/LibWeb/Layout/Viewport.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Implements very basic support for scrolling "overflow: scroll" boxes.
Following improvements are made:
- Painting takes in account scroll offset
- Scrollable overflow rectangle limits from `scrollable_overflow_rect()` are taken in account now.
- Scroll offset state is moved from layout tree to dom tree
- EventHandler does slightly better work at finding scrollable target to trigger wheel event handling
There still many things left to implement in the future:
- Layout tree nodes still have functions to get/set scroll offset although they should not
- Scroll offset doesn't behave right when resize happens
- Event handler works very naive when it comes to finding target for wheel events
- Many other things
Example that allows to test improvements made with these changes:
```html
<!DOCTYPE …
```
> LibWeb: Make boxes with "overflow: scroll" actually scrollable

- Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Before painting the borders, build a grid snapped to device pixels and use it to construct the rectangles for the cell edges. Also adjust their starting coordinate and size such that they join correctly without overhangs. This approach works at all zoom levels.
> LibWeb: Snap table grid to device pixels in collapsed borders mode

- Ladybird/CMakeLists.txt
With the CMake build, the ladybird binary ends up in $build/bin/ladybird.app/Contents/MacOS. Which is a bit unfortunate for a few reasons, but the main one is that --enable-lagom-networking doesn't work with ./Meta/serenity.sh run lagom ladybird.
Let's copy the file to the expected location. There's very likely better solutions we can use in the future.
> Ladybird: Copy cacert.pem into the expected build-time path on macOS

- Meta/Azure/Setup.yml
- Meta/Lagom/CMakeLists.txt
- Tests/LibAudio/CMakeLists.txt
- Tests/LibAudio/TestPlaybackStream.cpp
- Userland/Libraries/LibAudio/PlaybackStreamPulseAudio.cpp
- Userland/Libraries/LibAudio/PlaybackStreamPulseAudio.h
- Userland/Libraries/LibAudio/PulseAudioWrappers.cpp
- Userland/Libraries/LibAudio/PulseAudioWrappers.h
- Userland/Libraries/LibThreading/BackgroundAction.h
- Userland/Libraries/LibThreading/Thread.cpp
- Userland/Libraries/LibThreading/Thread.h
This PR does the following:
- Adds `libpulse-dev` to CI to allow PulseAudio classes in LibAudio to build on CI.
- Makes creating, detaching and then destructing a `RefPtr<Threading::Thread>` safe by keeping the `Thread` alive until its action completes.
- Fixes numerous issues with the `PulseAudioWrappers.cpp` classes and `PlaybackStreamPulseAudio` when destructing a stream. Streams will now successfully shut down and free all memory, and the PulseAudio context will successfully disconnect, be freed, and then when necessary it will be instantiated and connected again.
> LibAudio/LibThreading: Clean up PulseAudio API objects properly and add a test for PlaybackStream

- Documentation/Troubleshooting.md
In distributions with newer versions of OpenSSL, when you run `Meta/serenity.sh rebuild-toolchain` you'll get `curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled`. This is because OpenSSL was compiled with legacy renegotiation disabled by default. I've added instructions to `Documentation/BuildInstructions.md` to solve this issue.
> BuildDocs: Add intructions to enable legacy renegotiation

- Ladybird/main.cpp
- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibCore/Process.h
The helper method can be used to force the current process to sleep, waiting for a debugger to attach. On attach, the debugger breaks at the callsite
directly.
[Clion debugging demo gif](https://github.com/SerenityOS/serenity/assets/74406/2df2f1f6-d520-441a-8cf2-f3df90d86a58)
[Gdb in the terminal (lldb works too on macOS)](https://github.com/SerenityOS/serenity/assets/74406/4e070d63-4576-487d-bac6-6ffbb48a7d5e)
> LibCore: Implement a helper that waits for a debugger then breaks

- Userland/Libraries/LibLine/InternalFunctions.cpp
Even though case-change operations set `m_refresh_needed` to `true`, `Editor::refresh_display()` doesn't redraw the line or a part of it. Setting `m_chars_touched_in_the_middle` to a non-zero value results in redrawing of the line; Fixing the issue of the line not being refreshed after a case-change operation.
---
I can't figure out what `m_chars_touched_in_the_middle` actually does (why is it an int if it is used as a bool?) but i am guessing it is for marking the index of the start of the line change. Starting from that index till the cursor is what got changed and *only that* part should be redrawn.
Was this (Meta+u, Meta+l, and Meta+c) broken for 2.5 years?? I think the delta refresh logic was forgotten and never got implemented. Missing FIXME? (in `Editor::refresh_display()`)
But …
> LibLine: Fix case-change operations

- Ladybird/Qt/SettingsDialog.cpp
We could probably do more here, like refuse to accept() the ok button if the url is invalid, but this prevents a garbage setting from being input if you just open the Settings Dialog and close it without interacting with it.
> Ladybird: Ensure selected new tab URL is a valid URL before saving

- Userland/Libraries/LibJS/Heap/GCPtr.h
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
**LibJS+LibWeb: Apply the Rule of Zero to `{Nonnull,}GCPtr<T>`**
The compiler-generated copy constructor and copy assignment operator
already do the right thing (which is to simply copy the underlying
pointer).
The [Itanium C++ ABI][1] treats any class with non-trivial copy/move
constructors and destructors as non-trivial for the purposes of calls --
even if they are functionally identical to the compiler-generated ones.
If a class is non-trivial, it cannot be passed or returned in registers,
only via an invisible reference, which is worse for codegen. This commit
makes `{Nonnull,}GCPtr` trivial.
As the compiler can be sure that capturing a `GCPtr` by value has no
side effects, a few `-Wunused-lambda-capture` warnings had to be
addressed in LibWeb.
**LibJS+LibWeb: Mark …
> LibJS+LibWeb: Make `JS::GCPtr` cheaper

- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Tests/parser-unary-associativity.js
When determining the precedence of the + and - operators, the parser always returned the precedence using these operators in a binary expression (lower than division!). Since + and - can be used in both unary and binary expressions, the context of whether the operator is used in a unary or binary expression must be taken into account.
> LibJS: Apply the correct precedence for unary + and - operators

- Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
- Userland/Libraries/LibWeb/Painting/BorderPainting.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
- Userland/Libraries/LibWeb/Painting/TableBordersPainting.h
Build a grid snapped to device pixels and use it to construct the rectangles for the cell edges, same as for collapsed borders. This is especially important when border-spacing is set to 0 since it avoids gaps between adjacent cells which have borders set.
> LibWeb: Snap table grid to device pixels in separate borders mode

- Userland/Libraries/LibJS/Tests/test-common-tests.js
- Userland/Libraries/LibJS/Tests/test-common.js
This argument allows optionally specifying a number of decimal places that must be equal for 2 numbers to be considered close.
> LibJS: Add an optional precision argument to toBeCloseTo test function

- Tests/LibJS/test262-runner.cpp
This scripts have been updated to not use this option.
> LibJS: Remove bytecode option from the test262 runner

- Userland/Libraries/LibAudio/WavWriter.cpp
- Userland/Utilities/shot.cpp
After not so successful https://github.com/SerenityOS/serenity/pull/20363 (🫣), I decided to look if we're using the `ReadWrite` mode correctly in other places of the system.
It turns out that WavWriter and the shot utility open files with this mode and never truncate the files, which might leave some contents of a previous file during overwriting.
It seems to me that changing the mode to just `Write` is correct, as these tools always write to files.
> Userland: Open files for save in write-only mode

- Userland/Utilities/usermod.cpp
This PR modifies `usermod` to not immediately exit if not run as root. This allows non-root users to run `--help` for example.
Rather than a "not running as root" message, a "Permission denied" message is now shown. This is similar to what is shown in Linux.
Example usage:
> usermod: Don't exit immediately for non-root users

- Tests/LibWeb/Layout/expected/css-namespace-tag-name-selector.txt
- Tests/LibWeb/Layout/expected/css-namespace-universal-selector.txt
- Tests/LibWeb/Layout/input/css-namespace-tag-name-selector.html
- Tests/LibWeb/Layout/input/css-namespace-universal-selector.html
- Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.h
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
- Userland/Libraries/LibWeb/Dump.cpp
Fully supported:
- Namespaces in universal selectors. (`*|*`, `foo|*`, `|*`)
- Namespaces in tag-name selectors. (`*|a`, `foo|a`, `|a`)
Parsed but not functional:
- Namespaces in attribute selectors. (`[*|bar]`, `[|bar]`)
Also fix a couple of bugs with `@namespace` rules that I ran into.
> LibWeb: Add namespace support to CSS selectors

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/Tab.cpp
Plus a fix to make sure the main process exits if the JS console is open when the last tab is closed.
> Ladybird: Add the select-all action to the JS console

- Userland/Libraries/LibC/pthread_integration.cpp
tl;dr: This fixes deadlocks that would occur in most applications in Serenity when SMP was enabled.
As an optimization to `pthread_mutex_unlock()`, if only one thread holds a mutex lock, it will avoid calling `futex()` to wake, since no threads are actually waiting in `futex()`.
If a thread manages to synchronously unlock and relock the same mutex, the state will be set to indicate that a wake is not needed, regardless of whether any other threads are waiting for the lock. This should be fine, as a thread that is waiting will set the mutex to needing a wake and check if it is unlocked to unblock itself in the same atomic operation.
However, when `pthread_mutex_lock()` was called with only one thread holding the mutex lock, instead of telling `futex()` to atomically sleep the thread if the …
> LibC: Expect mutexes to be locked and needing wake when calling futex()

- AK/URLParser.cpp
- Base/res/html/misc/new-tab.html
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/main.cpp
- Ladybird/WebDriver/main.cpp
- Userland/Applications/Browser/main.cpp
- Userland/Services/WebDriver/main.cpp
When we launch Ladybird, we currently:
1. Create a BrowserWindow, whose constructor navigates to the configured
new tab page URL.
2. Then navigate to either "about:blank" or whatever URL is provided via
the command line.
This patch removes step 2 and forwards the URL from the command line (if
any) to BrowserWindow. BrowserWindow's constructor then either navigates
to that URL or the new tab page URL.
> Ladybird+WebDriver: Only load a single URL at launch

- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
This causes the background to scroll along with the element's contents.
Example from `backgrounds.html` with all other examples removed so we don't scroll the page instead:
> LibWeb: Implement `background-attachment: local`

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
**LibGfx/JPEGXL: Support clusters with a single distribution**
This type of cluster is an exception and has specific rules (but
simpler) to be read. This is a requirement to support complex
distributions as they use a symbol decoder initialized with a single
distribution.
**LibGfx/JPEGXL: Add support for complex distribution clustering**
Complex distribution - distributions that are encoded using an internal
symbol decoder with a single distribution, are very often used for lz77
compressed images. This is a requirement for the lz77_flower test case.
---
Again, this is not useful on its own, but a requirement for lz77_flower and probably many other images.
> LibGfx/JPEGXL: Add support for complex distribution clustering

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Turns out I only decoded square images until now, which make this code work. A bit ashamed to have written that bug.
---
In another reality, this commit is named "Embarrass JPEGXLLoader's original author"
> LibGfx/JPEGXL: Compute the position inside the channel correctly

- Userland/Libraries/LibGfx/ImageFormats/ExifOrientedBitmap.h
- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Yay! It looks pretty good to me!
---
**LibGfx: Add `ExifOrientedBitmap`**
The idea behind this class is to provide an abstraction for decoders.
It allows them to use the class as if it was a normal `Bitmap`, however,
under the hood, this class will honor a given orientation, as specified
by the Exif standard. This class is introduced to be used within the
JPEG XL decoder, but it should be possible to use it for every
Exif-compatible format.
**LibGfx/JPEGXL: Honor the orientation parameter**
Since the introduction of the JPEG XL decoder, we always read the
`orientation` field in the `ImageMetadata` bundle. This patch allows us
to render the bitmap accordingly to this transformation.
> LibGfx/JPEGXL: Honor the orientation parameter

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Settings.cpp
- Ladybird/Qt/Settings.h
- Ladybird/Qt/main.cpp
Currently the Ladybird browser window always opens with the small window size of 800x600. So every time I resize the window to something larger to open the website I want to test. This is annoying so I have added the code that the window remembers it's last position and size on close so that it can be restored when the browser is restarted.
I have not test this code with multi monitor setup so it may not work with that for now.
> Ladybird: Remember window position and size on close

- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Some websites (like Reddit) like to instantiate "components" by setting innerHTML to a huge chunk of stuff. Sometimes those huge chunks of stuff contain inline style sheets (i.e `<style>` elements).
Before this change, we would end up parsing the CSS in those elements multiple times, because we had no way of knowing that we were within a fragment parser's temporary document.
This patch avoids the extra CSS parsing work by adding adding a flag to Document that tells us it's being used by the fragment parser. Then, we simply avoid parsing CSS for style elements in such documents. The CSS then gets parsed immediately upon insertion into the proper DOM.
> LibWeb: Don't parse inline style sheets during HTML fragment parsing

- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
By using fetch, the request now also follows redirects, which in the end makes the 'Polyfilled Features' section on https://github.github.com/browser-support/ load :^)
---|---
> LibWeb: Implement more steps in 'fetching a single module script'

- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
This patch now triggers a collection when the memory usage doubles (since the last collection) instead of every 100k allocations. 
This dynamic approach is inspired by some other GCs like [Golang's](https://tip.golang.org/doc/gc-guide#GOGC) and [Lua's](https://www.lua.org/wshop18/Ierusalimschy.pdf) and improves performance in memory heavy applications because  marking must visit old objects which will dominate the marking phase if the GC is invoked too often.
Loading the page in ladybird, we can almost half (reduce by ~48%) the time spent on collection.
| Loading Google Maps | before | after |
|--------|--------|--------|
| Number of Collections | 76 | 28 |
| Total time spent collecting | 2034 ms | 1061 ms |
| Mean pause times | 26 ms | 37 ms |
<details><summary>How to measure …
> LibJS: Improve garbage collection trigger condition

- Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
- Tests/LibWeb/Layout/input/block-and-inline/button-should-have-vertically-aligned-content.html
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Add functionality to vertically align content within a button tag.
This fixes the "direction" arrow in the search box of google maps.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/SerenityOS/serenity/assets/45781926/a6836b65-0376-4e90-ba95-caad73901d1b"></td>
<td><img src="https://github.com/SerenityOS/serenity/assets/45781926/35414cd8-60fb-4409-9428-a5a998fcbaa9"></td>
</tr>
</table>
> LibWeb: Vertically align HTML Button content

- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
- Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamGenericReader.cpp
- Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.cpp
- Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.h
Three little fixes to stop the intermittent CI flaking on streams-related tests :^)
> LibWeb/Streams: Fix GC related crashes seen on CI

- Ports/SDL2/patches/0002-audio-Avoid-accumulation-errors-in-resampler.patch
- Ports/SDL2/patches/ReadMe.md
This adds a patch to the SDL2 port to fix a segfault which occurs in
the resampler.
Taken from this upstream commit:
https://github.com/libsdl-org/SDL/commit/78f9710
This fixes a crash we were seeing in the julius port.
> Ports/SDL2: Avoid accumulation errors in resampler

- Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
- Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.h
Otherwise it UAFs the intersection root. Not sure how this didn't cause a lot of crashes!
> LibWeb: Unregister IntersectionObserver in finalize, not the destructor

- Tests/LibWeb/Layout/expected/grid/item-min-max-percentage-width.txt
- Tests/LibWeb/Layout/expected/grid/justify-start-min-width.txt
- Tests/LibWeb/Layout/expected/grid/min-max-content.txt
- Tests/LibWeb/Layout/input/grid/item-min-max-percentage-width.html
- Tests/LibWeb/Layout/input/grid/justify-start-min-width.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Closes https://github.com/SerenityOS/serenity/issues/20432
> LibWeb: Use root content width as automatic width if children inline

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
- Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.h
- Userland/Libraries/LibJS/Tests/builtins/AsyncGenerator/AsyncGenerator.prototype.next.js
- Userland/Libraries/LibJS/Tests/syntax/async-await.js
Fixes #20275
```
Summary:
Diff Tests:
+4 ✅    -4 ❌   
Diff Tests:
test/built-ins/Array/fromAsync/non-iterable-input-with-thenable-async-mapped-awaits-callback-result-once.js ❌ -> ✅
test/language/expressions/await/async-await-interleaved.js                                                  ❌ -> ✅
test/language/expressions/await/await-awaits-thenables-that-throw.js                                        ❌ -> ✅
test/language/expressions/await/await-awaits-thenables.js                                                   ❌ -> ✅
```
> LibJS: Implement await properly for async functions

- Tests/LibWeb/Layout/expected/table/table-cell-not-paintable.txt
- Tests/LibWeb/Layout/input/table/table-cell-not-paintable.html
- Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Replicate the more conservative way it's done for other nodes, for which we verify whether they have a paintable before doing painting-related operations with it.
Fixes crash on https://www.haiku-os.org/.
> LibWeb: Verify that table cells have a paintable when collecting them

- Userland/Libraries/LibGfx/Rect.h
- Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
Preciously we were casting to float, round and cast back, which actually
might loose precision and was quite ugly.
----
@MacDue
> LibWeb: Allow direct rouding of CSSPixelRects to CSSPixelRects

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
**LibGfx/JPEGXL: Make `EntropyDecoder::read_config()` static**
This function will soon be used for the LZ77 decoder with a different
parameter than `m_log_alphabet_size`.
**LibGfx/JPEGXL: Use a wider type for the context id**
These numbers can be way bigger than 255, let's use a `u32` instead of a
`u8`, which is what other decoders do.
**LibGfx/JPEGXL: Factorize the code to read symbols from distributions**
This will soon be used by the LZ77 decoder, so let's avoid some
duplication.
**LibGfx/JPEGXL: Add support for LZ77 encoded stream**
On top of the Brotli/ANS compression, the entropy stream can have
another compression layer, this time using LZ77. This patch adds support
for this last layer, which makes us decode the `lz77_flower` test. This
double-compression is also often used for ICC …
> LibGfx/JPEGXL: Add support for LZ77 encoded streams

- Ports/README.md
Was recommended in pull request #20444 to use single quotes around non-interpolated strings. This updates the package.sh example in the ports documentation to match the recommendation.
> Documentation: Update Ports package.sh example to use single quotes

- Kernel/Arch/mcontext.h
- Kernel/Arch/riscv64/mcontext.h
- Toolchain/Patches/binutils/0001-Add-support-for-SerenityOS.patch
- Toolchain/Patches/gcc/0001-Add-a-gcc-driver-for-SerenityOS.patch
- Toolchain/Patches/gcc/0003-libgcc-Build-for-SerenityOS.patch
This makes `ARCH=riscv64 Toolchain/BuildGNU.sh` work, but the patches might not be completely correct.
> Toolchain: Add (basic) support for riscv64

- Ports/.port_include.sh
A bug was introduced in commit #20413, where the `clean_dist` function was missed from refactoring to the new "files" format. This PR aims to fix this issue.
> Ports: Fix `clean_dist` function in .port_include.sh

- Tests/LibWeb/Layout/expected/grid/min-max-content.txt
- Userland/Libraries/LibWeb/CSS/Length.cpp
CSSPixels uses fixed point now.
> LibWeb: Remove 3 decimal places rounding hack in Length::percentage_of

- Userland/Shell/Builtin.cpp
- Userland/Shell/Shell.cpp
- Userland/Shell/Shell.h
The new builtin command "reset" now resets the entire internal state by virtually destructing the Shell state and re-constructing it.
This helps for example when setting a new hostname and wanting to view it in the current Shell program.
cc @alimpfard
> Shell: Add builtin command to reset the internal state

- Tests/LibWeb/Layout/expected/table/columns-width-distribution-1.txt
- Tests/LibWeb/Layout/expected/table/infinite-padding.txt
- Tests/LibWeb/Layout/input/table/infinite-padding.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Using avilable space directly while resolving table container width allows to avoid assigning it to table wrapper box content width which sometimes involves infinite (saturated) values.
Also this allows to get rid of set_max_content_width() which is a hack that allows to bypass set_content_width() to assign infinite (saturated) width to a box.
Closes https://github.com/SerenityOS/serenity/issues/19521
> LibWeb: Use available space to resolve table container width

- Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
These two variables are already fields of `Frame`, they make no sense at the context scope.
> LibGfx/JPEGXL: Remove unused variables in `JPEGXLLoadingContext`

- Ports/mgba/package.sh
Previously, some optional dependencies could be unintentionally included if they were present on the host machine.
The build was previously failing on my machine, as it was attempting to build the QT frontend as well as the SDL one.
> Ports/mgba: Explicitly exclude optional dependencies

- Ports/poppler/package.sh
Previously, the optional `gpgme` and `nss3` dependencies could be unintentionally included if they were present on the host machine.
The build was failing on my machine due to `gpgme` being detected somewhere.
> Ports/poppler: Explicitly exclude optional dependencies

- Userland/Utilities/man.cpp
`String::repeated()` returns a `ErrorOr<String>`, so wrap it in `TRY()`.
This fixes a glitch in the title formatting (`{}` not removed if `ErrorOr<String>` is directly passed to `outln()`).
Before:
After:
Regressed in #19382.
Discovered while working on #20348.
> Utilities: Fix title formatting in `man`

- Ladybird/WebContent/CMakeLists.txt
- Ladybird/cmake/InstallRules.cmake
This should allow out of tree chromes to prototype other LibWeb platform plugins easier when using Lagom as a find_package dependency.
> Ladybird: Install an impl library for WebContent when ENABLE_QT=OFF

- AK/URL.cpp
- AK/URL.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/Dump.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
...not *much* backing infrastructure, because I got very lost in the yaks, confused myself, and gave up. :sweat_smile: As such, we don't set the target element most of the time, and so this doesn't really function *yet*, but it will once we have a more complete Navigables implementation.
> LibWeb: Implement `:target` selector and some backing infrastructure

- Meta/Lagom/Wasm/js_repl.cpp
- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
There is no need to check if bytecode interpreter exists after we
switched away from AST interpreter.
> LibJS: Remove usage of bytecode_interpreter_if_exists()

- Kernel/Devices/PCISerialDevice.h
Add the device ID for PCI serial port cards that use the WCH CH351
chip. This device has been tested with real hardware where the serial
debug output could succesfully be received.
> Kernel: Add PCISerialDevice WCH CH351 IDs

- Ports/wayland/package.sh
This allows `wayland` to build from a clean state.
> Ports/wayland: Add `libffi` dependency

- Tests/LibWeb/Layout/expected/table/inline-table-width.txt
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Changing `calculate_min_content_heigh()` and
`calculate_min_content_heigh()` to accept width as `CSSPixels`, instead of `AvailableSize` that might be indefinite, makes it more explicit that width is supposed to be known by the time height is measured.
This change has a bit of collateral damage which is rows height calculation regression in `table/inline-table-width` that worked before by accident.
> LibWeb: Forbid usage of indefinite width in calculate_min{max}_height

- Meta/CMake/libweb_generators.cmake
- Meta/Lagom/Tools/CodeGenerators/LibWeb/CMakeLists.txt
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp
- Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/PseudoClasses.json
- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/Dump.cpp
I got fed up with having to remember to edit so many places to add a pseudo-class, so now we have a JSON file which the boilerplate is generated from. :^)
A couple of small functional changes related to `:host` / `:host()`:
- Make the parameter a `<compound-selector>`, instead of a `<selector-list>`.
- Hack it in to the "serialize a simple selector" algorithm.
> LibWeb: Generate PseudoClass metadata

- Userland/Libraries/LibWeb/CSS/CSSImportRule.cpp
This makes importing Google Fonts via @import rule actually work. :^)
> LibWeb: Fetch CSS @font-face fonts in @import'ed style sheets

- CMakeLists.txt
- Kernel/CMakeLists.txt
- Meta/CMake/serenity_compile_options.cmake
Two non-functional changes:
- Remove pointless `-latomic` flag. It was specified via
`add_compile_options`, which only affects compilation and not linking,
so the library was never actually linked into the kernel. In fact, we
do not even build `libatomic` for our toolchain.
- Do not disable `-Wnonnull`. The warning-causing code was fixed at some
point.
This commit also removes `-mstrict-align` from the userland. Our target
AArch64 hardware natively supports unaligned accesses without a
significant performance penalty. Allowing the compiler to insert
unaligned accesses into aligned-as-written code allows for some
performance optimizations in fact. We keep this option turned on in the
kernel to preserve correctness for MMIO, as that might be sensitive to
alignment.
---
While LLD and mold …
> CMake: Clean up some flags related to the AArch64 build

- Documentation/Kernel/DevelopmentGuidelines.md
The following changes take effect:
1. Annotate FixedStringBuffer => `FixedStringBuffer` in many places.
2. Remove non-existing helpers for FixedStringBuffers. I added them previously but even then they were removed in a following fixup so these references were never valid. Therefore let's just put a vague reference to the fact that we have some helpers for this class in the Kernel, and let people to figure out quickly by themselves for this topic.
3. Put a sentence to explain that FixedStringBuffer objects are not only being used in syscall handling code, but also for storing actual data in both the Thread and Process classes as well.
> Documentation: Update the kernel development guide on FixedStringBuffer

- AK/FixedStringBuffer.h
- AK/StringBuilder.cpp
- AK/StringBuilder.h
- Kernel/Net/Intel/E1000ENetworkAdapter.cpp
- Kernel/Net/Intel/E1000ENetworkAdapter.h
- Kernel/Net/Intel/E1000NetworkAdapter.cpp
- Kernel/Net/Intel/E1000NetworkAdapter.h
- Kernel/Net/LoopbackAdapter.cpp
- Kernel/Net/LoopbackAdapter.h
- Kernel/Net/NetworkAdapter.cpp
- Kernel/Net/NetworkAdapter.h
- Kernel/Net/NetworkingManagement.cpp
- Kernel/Net/NetworkingManagement.h
- Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
- Kernel/Net/Realtek/RTL8168NetworkAdapter.h
- Kernel/Net/VirtIO/VirtIONetworkAdapter.cpp
- Kernel/Net/VirtIO/VirtIONetworkAdapter.h
The goal of this PR is to remove some extra heap allocations.
Instead, we could use a FixedStringBuffer to store a string with up to 16 chars for network adapters' names.
> Kernel/Net: Don't allocate memory for adapters' names 

- Userland/Libraries/LibWeb/Layout/AvailableSpace.h
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
- Userland/Libraries/LibWeb/Layout/LineBox.h
- Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
- Userland/Libraries/LibWeb/Layout/LineBuilder.h
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
This layout code refactoring replaces usage of `to_px()` with `to_px_or_zero()` that prevents leakage of saturated (infinite) values into layout calculations.
> LibWeb: Get rid of `AvailableSize::to_px()` usage

- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Glyf.h
- Userland/Libraries/LibGfx/Font/WOFF2/Font.cpp
- Userland/Libraries/LibGfx/Font/WOFF2/Font.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Here goes an implementation of the WOFF2 spec: https://www.w3.org/TR/WOFF2/
The implementation was started by Luke last year, and then ended up in the infamous git stash. At some point, I asked for a branch, and implemented the rest.
It's a bit sloppy and needs love & cleanup work, but let's get it in and continue iterating in-tree :^)
Closes #18552
> LibGfx+LibWeb: Add support for WOFF2 compressed web fonts

- Userland/Services/AudioServer/CMakeLists.txt
- Userland/Services/AudioServer/ClientAudioStream.cpp
- Userland/Services/AudioServer/ClientAudioStream.h
- Userland/Services/AudioServer/FadingProperty.h
- Userland/Services/AudioServer/Mixer.cpp
- Userland/Services/AudioServer/Mixer.h
Preparation for more resampling / GUI mixer work.
This class will only grow, and it should really have its own files.
- Use Optional references instead of pointers
- Clean up some const and nullability weirdness
- Use proper error return value for get_next_sample
> AudioServer: A few cleanups

- Userland/Libraries/LibWeb/HTML/NavigatorID.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Before, `navigator.platform` would always report the platform as "SerenityOS", regardless of whether or not that was true. It also did not include the architecture, which Firefox and Chrome both do. Now, it can report either "Linux x86_64" or "SerenityOS AArch64".
> LibWeb: Use current platform for navigator.platform

- .github/workflows/cmake.yml
- CMakeLists.txt
- Documentation/AdvancedBuildInstructions.md
- Ladybird/CMakeLists.txt
- Meta/Azure/Serenity.yml
- Meta/CMake/common_options.cmake
- Meta/Lagom/CMakeLists.txt
- Userland/Libraries/LibSanitizer/UBSanitizer.cpp
I tried to summarize most of the information in the commit messages, but see the "Making LibWeb less heavy on the linker" thread for more background.
~~I've yet to test this with GCC, waiting for results right now.~~
---
**LibSanitizer: Abort on unrecoverable UBSan errors**
There is no sensible recovery possible from non-void functions that
fail to return a value, or from `__builtin_unreachable()` being reached,
all bets are off once they happened. This is why LLVM's libsanitizer
treats these as always fatal, even if all other UBSan checks are made
recoverable with `-fsanitize-recover`. The codegen already assumes that
these handlers will not return.
**LibSanitizer: Add `_abort` variants of UBSan handlers**
These variants make the choice to terminate the process a compile-time
decision …
> LibSanitizer+CMake+CI: Add non-recoverable UBSan support and use it on CI

- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/gunzip.cpp
This utility is actually a symlink to the gunzip utility. The gunzip utility is modified to enable writing to stdout when running through the zcat symlink, to emulate the same behavior on other OSes.
In addition to that, the gunzip utility is now required on a default installation as it could be a vital utility under some conditions (for example, downloading source code in a tar.gz file).
> Utilities: Add zcat

- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
This is a temporary hack until navigables are used to load pages, which uses fetch infrastructure that does this according to spec.
> LibWeb: Add hack for computing the request referer during load

- Ladybird/Qt/BrowserWindow.cpp
This fixes a bug where the reload button does not work on the page that was initially loaded
> Ladybird: add initial page to history

- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/CyclicModule.h
- Userland/Libraries/LibJS/Heap/Cell.h
- Userland/Libraries/LibJS/Heap/MarkedVector.h
- Userland/Libraries/LibJS/Runtime/Array.h
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
- Userland/Libraries/LibJS/Runtime/Environment.h
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ObjectEnvironment.h
These cases were found with GCC's `-Wsuggest-final-{types,methods}` warnings, which catch calls that could have been devirtualized had we declared the functions `final` in the source.
To reproduce, Link Time Optimization needs to be enabled. The easiest way to achieve this is to set the `CMAKE_INTERPROCEDURAL_OPTIMIZATION` cache variable to `ON`. The `.incbin` directive in LibCompress' Brotli decompressor might needs to be changed to an absolute path for this to work.
This commit also removes a pair of unused virtual functions.
> LibJS: Mark classes and virtual functions `final` where possible

- Userland/Applications/Calendar/CalendarWidget.cpp
- Userland/Applications/Calendar/CalendarWidget.h
Otherwise, it would get destroyed after exiting the create() function.
| Before: | After: |
| --- | --- |
| <video src="https://github.com/SerenityOS/serenity/assets/36564831/48e7e2ff-160c-45d8-b801-90740af3f061"> | <video src="https://github.com/SerenityOS/serenity/assets/36564831/bee6adfd-d707-4353-82f9-19d93fcff556"> |
> Calendar: Promote view_type ActionGroup to CalendarWidget's member

- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
The only non-default use of this parameter was removed in 980e7164fe.
> Ladybird: Remove unused LoadType parameter from Tab::navigate

- Tests/LibWeb/Ref/manifest.json
- Tests/LibWeb/Ref/square-flex.html
- Tests/LibWeb/Ref/square-ref.html
- Userland/Utilities/headless-browser.cpp
The ref tests runner takes screenshots of both the input page and the expected page, then compares them. Ref testing allows us to catch painting bugs, which cannot be detected with the layout and text tests we already have.
With ref tests, we'll likely want to reuse the same expectation page for multiple inputs. Therefore, there's a `manifest.json` file that describes the relationship between inputs and expected outputs.
> headless-browser: Add ref tests support

- .github/workflows/cmake.yml
This is taking over 4 minutes to run on CI, and checks only a dozen manpages, which is of limited benefit.
Leaving the manpage-generation code in place for now.
> Meta: Remove "Check manpages for completeness" CI step

- Ports/vitetris/package.sh
There is an icon in the `vitetris` repository, but I decided against using it. It's an odd size, which results in our resized icon looking a little :yakid2:.
> Ports/vitetris: Use correct launcher command path

- Ports/nyancat/package.sh
This PR updates the `nyancat` port to use the correct `launcher_command` path. It also now fetches from a specific commit (the latest) rather than the `master` branch` to avoid potential future sha256 mismatches.
> Ports/nyancat: Use the correct launcher command path

- Ports/ja2/package.sh
This PR adds a launcher icon to the Jagged Alliance 2 port. It also ensures that the build is done in parallel by not overwriting the default `makeopts`.
> Ports/ja2: Add launcher icon

- Tests/LibWeb/Layout/expected/css-invalid-psuedo-compound-selector.txt
- Tests/LibWeb/Layout/input/css-invalid-psuedo-compound-selector.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Reduced from a crash on: https://github.com/SerenityOS/serenity/pulls
Fixes #20568
> LibWeb: Fix crash parsing an invalid pseudo compound selector

- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.h
Previously stacking contexts were only painted in steps 3, 8, and 9. These steps are only meant to cover positioned elements (as per https://www.w3.org/TR/CSS22/zindex.html). This meant that elements with opacity (which forms a stacking context) could end up painted above elements that actually occlude them.
Progression on camera.svg:
**Before:**
**After:**
> LibWeb: Don't paint all stacking contexts like positioned elements

- Tests/LibWeb/Layout/expected/table/inline-table-width.txt
- Tests/LibWeb/Layout/expected/table/multi-line-cell.txt
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Overall available width should only affect later stages of the table layout algorithm and have no impact on cell measures.
> LibWeb: Use cell width instead available width to compute height

- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
I started a branch for type0 fonts a while ago. It's a mess and things aren't fully working locally and I haven't touched it in a few weeks, but I figured upstreaming the spec comments is maybe somewhat useful.
> LibPDF: Add some scaffolding and FIXMEs for type0 cidfonttype2 fonts

- Tests/LibWeb/Text/expected/link-element-search.txt
- Tests/LibWeb/Text/input/link-element-search.html
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
Regressed in 21fe86d235845626383fc321d1125d4a2c6db98a
`is_null() != has_value()` - forgetting to add `!` in the port `DeprecatedString` to `Optional` :(
> LibWeb: Fix typo in query of link elements search params

- Userland/Libraries/LibGUI/Calendar.cpp
| Before: | After: |
| --- | --- |
| <video src="https://github.com/SerenityOS/serenity/assets/36564831/b9133343-163a-4044-a1cd-6d3883f18a59"> | <video src="https://github.com/SerenityOS/serenity/assets/36564831/d0c360fa-460d-491d-8588-e9b8ab12260f"> |
> Calendar: Use proper tile information when painting tiles after January

- Ladybird/CMakeLists.txt
- Ladybird/WebContent/main.cpp
This will allow us to bring the WebContent process into non-Qt macOS chromes. This branch is only reached when creating an `<audio>` element, so while the chrome is heavily under development, we can just avoid these elements.
CC @ADKaster
> Ladybird: Create a runtime error for unknown audio codec plugins

- AK/FixedPoint.h
- AK/Format.cpp
- Tests/AK/TestFixedPoint.cpp
- Tests/LibEDID/TestEDID.cpp
- Userland/Libraries/LibEDID/DMT.cpp
We now preform the multiplication in a widened type which makes it
overflow-safe and use the correct bit for rounding direction detection.
This allows us to shift first and then divide, preserving more precision
This matches what floats do.
Also fix typo `trunk`->`trunc`
`rint` is a more accurate name for the roudning mode as the fixme above
stated
> AK: FixedPoint fixes 

- Tests/LibWeb/Ref/opacity-stacking-ref.html
- Tests/LibWeb/Ref/opacity-stacking.html
Now that we can test this, let's add a test, as mentioned in: https://github.com/SerenityOS/serenity/pull/20559#issuecomment-1677126697
(I confirmed this test failed before #20559)
> LibWeb: Add ref test for opacity (stacking context) paint order

- Base/res/html/directory.html
- Base/res/html/error.html
- Ladybird/WebContent/main.cpp
- Meta/gn/secondary/Userland/Libraries/LibWeb/Loader/BUILD.gn
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Loader/FileDirectoryLoader.cpp
- Userland/Libraries/LibWeb/Loader/FileDirectoryLoader.h
- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
- Userland/Libraries/LibWeb/Loader/FrameLoader.h
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Currently when you visit a local directory with the file scheme you get an error. I have added some code that generates a basic directory listings page. So you can traverse your file system inside Ladybird. This feature exists in many other browsers like Firefox and Chrome.
I have added the `FrameLoader::set_resource_directory_url()` API where `Ladybird/main.cpp` can set the relative `file://` path URL to the `Base/res.` That variable is used in the internal HTML pages (`error.html`, `directory.html`) to point to the right image files.
| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2023-08-09 at 10 24 39](https://github.com/SerenityOS/serenity/assets/19894029/c8b560d0-8180-4713-917c-85d52f6ef885) | ![Screenshot 2023-08-10 at 11 49 …
> LibWeb: Add directory entries page when visiting a local directory

- Ports/stb/package.sh
Previously, the `stb` port would not build from a clean state, as this directory does not exist by default.
> Ports/stb: Create `/usr/local/include` if it doesn't exist

- Ports/klong/patches/0001-Patch-Makefile.patch
Previously, the `klong` port would not build from a clean state, as this directory does not exist by default.
> Ports/klong: Create `/usr/local/bin` if it doesn't exist

- Base/usr/share/man/man1/checksum.md
EDIT 2: I've reverted the PR back to its original form. More work is needed to render styled markdown correctly.
~~EDIT: I have updated this PR to include fixes that ensure multi-line code blocks with a style are rendered correctly, see below for more info~~
This PR updates the `checksum(1)` man page to use multi-line code blocks, this is consistent with other man pages and makes the synopsis render correctly in the terminal.
This doesn't fix the underlying rendering issue detailed in #19534. I've included an explanation of what I believe the underlying problem to be on that issue.
Before:
After:
> Base: Render checksum man page synopsis using a multi-line code block

- AK/Statistics.h
- Userland/Libraries/LibAudio/FlacWriter.cpp
- Userland/Libraries/LibAudio/FlacWriter.h
The estimation for this is fast but not very accurate, meaning we save around 5-10% storage space. (We also don’t try other channel coupling methods, but I am sceptical of how much benefit that actually provides.)
> LibAudio: Use channel coupling for FLAC encoding

- Userland/Libraries/LibGfx/Font/WOFF2/Font.cpp
It wasn't enough to do it only for simple glyphs, we need to do it for composite glyphs as well.
Fixes an issue where some glyph data was misaligned in the output and thus ended up rendered incorrectly or not at all.
Visual progression on https://twinings.co.uk/
Before:
After:
> LibGfx/WOFF2: Align all reconstructed glyf entries to 4 bytes

- Tests/LibWeb/Ref/css-gradient-currentcolor-ref.html
- Tests/LibWeb/Ref/css-gradient-currentcolor.html
- Tests/LibWeb/Ref/manifest.json
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/AbstractImageStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/ConicGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/ConicGradientStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.h
- Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
- Userland/Libraries/LibWeb/Painting/GradientPainting.h
We now keep the color value as a StyleValue up until we go to paint the gradient, which makes `currentColor` work, along with any other color values that can't be immediately converted into a `Gfx::Color` while parsing.
With this test page:
```html
<html>
<style>
div {
color: green;
width: 200px;
height: 200px;
background: linear-gradient(currentColor, white);
}
</style>
<div></div>
</html>
```
**Before:**
**After:**
> LibWeb: Allow any valid `<color>` in CSS gradients

- Userland/Libraries/LibGUI/TextEditor.cpp
If we double-click on a TextEditor that has spans, but the click itself was not on a span, fall back to the without-spans behavior. Previously the cursor would instead jump to the end of the document.
> LibGUI: Fall back to words when double-clicking TextEditor with spans

- Tests/LibWeb/Layout/expected/table/percentage-width-for-nested-table-is-like-auto.txt
- Tests/LibWeb/Layout/input/table/percentage-width-for-nested-table-is-like-auto.html
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
If the width is a percentage but the parent isn't resolved yet, take the same path as for auto width.
> LibWeb: Use the auto table width formula if it cannot be resolved

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
This would cause a nullptr-deref during painting of invalid linear-gradients, such as `linear-gradient(top, #f8f9fa, #ececec)` found in googles sign-in button
---
Fixes #20599
> LibWeb: Reject `nullptr` StyleValues as invalid ColorStops

- Userland/Demos/Mandelbrot/Mandelbrot.cpp
Crash Reporter was very helpful.
> Mandelbrot: Pledge `unix` to enable image export

- Userland/Libraries/LibWeb/HTML/Worker.cpp
Trying to run a worker right now just results in the WebContent process asserting down the road, so let's throw and log a FIXME instead. This makes it easier to see what's failing. We'll obviously remove this once we get workers working correctly. :^)
> LibWeb: Throw on attempt to create a Worker for now

- Tests/LibWeb/Text/expected/canvas/basic.txt
- Tests/LibWeb/Text/input/canvas/basic.html
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
Fixes an issue where setting CRC2D.font to an unparseable value would assert due to a null dereference.
> LibWeb: Null check fonts after parsing them in CRC2D.font assignment

- Userland/Applications/DisplaySettings/MonitorWidget.cpp
- Userland/Libraries/LibGfx/Point.h
- Userland/Libraries/LibGfx/Rect.h
- Userland/Libraries/LibGfx/Size.h
- Userland/Libraries/LibGfx/VectorGraphic.cpp
- Userland/Libraries/LibVideo/VP9/Decoder.cpp
Ignoring Size for a second, we currently have:
Rect::scale_by
Rect::scaled
Point::scale_by
Point::scaled
In Size, before this patch, we have:
Size::scale_by
Size::scaled_by
This aligns Size to use the same method name as Rect and Point. While
subjectively providing API symmetry, this is mostly to allow using this
method in templated helpers without caring what the exact underlying type
is.
> LibGfx: A bit of API symmetry for Rect, Point, and Size

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
We had `parse_calculated_value()` which parsed the contents of `calc()`, and `parse_dynamic_value()` which parsed any math function, both of which produce a CalculatedStyleValue, but return a plain StyleValue. This was confusing, so let's combine them together, and return a CalculatedStyleValue.
This also makes the other math functions work in `StyleComputer::expand_unresolved_values()`.
And it's 49 fewer lines. Not much but it's something!
> LibWeb: Deduplicate calc-parsing code

- Tests/LibWeb/Layout/expected/svg-transforms-and-viewboxes.txt
- Tests/LibWeb/Layout/expected/svg/svg-different-types-of-opacity.txt
- Tests/LibWeb/Layout/expected/svg/svg-g-with-opacity.txt
- Tests/LibWeb/Layout/expected/svg/svg-inside-svg.txt
- Tests/LibWeb/Layout/input/svg/svg-different-types-of-opacity.html
- Tests/LibWeb/Layout/input/svg/svg-g-with-opacity.html
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Set the size of the SVG G container and its offset based on the size of its children. This fixes a bug with the duckduckgo logo.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/SerenityOS/serenity/assets/45781926/a6feb7b0-ce84-4ebd-888d-3b17b9956097"></td>
<td><img src="https://github.com/SerenityOS/serenity/assets/45781926/2cda96ff-431c-440b-8f23-34943f4b4cb2"></td>
</tr>
</table>
> LibWeb: Size SVG G container according to its children

- Ladybird/Qt/BrowserWindow.cpp
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
- Userland/Libraries/LibJS/Heap/HeapRootTypeOrLocation.h
- Userland/Libraries/LibJS/Heap/MarkedVector.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/SafeFunction.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
This change introduces a very basic GC graph dumper. The `dump_graph()`
function outputs JSON data that contains information about all nodes in
the graph, including their class types and edges.
Root nodes will have a property indicating their root type or source
location if the root is captured by a SafeFunction. It would be useful
to add source location for other types of roots in the future.
Outout JSON dump have following format:
```json
"4908721208": {
"class_name": "Accessor",
"edges": [
"4909298232",
"4909297976"
]
},
"4907520440": {
"root": "SafeFunction Optional Optional.h:137",
"class_name": "Realm",
"edges": [
"4908269624",
"4924821560",
"4908409240",
"4908483960",
"4924527672"
]
},
"4908251320": {
"class_name": "CSSStyleRule",
"edges": [
"4908302648",
"4925101656",
"4908251192" …
```
> LibJS: Add GC graph dumper

- Userland/Libraries/LibWeb/Layout/AvailableSpace.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
Small refactoring to remove floating-point things from the layout code, which became irrelevant after switching to fixed-point math.
> LibWeb/Layout: Get rid of `isinfinite()` and `INFINITY`

- Tests/LibWeb/Layout/expected/block-and-inline/inline-block-percentage-max-width.txt
- Tests/LibWeb/Layout/input/block-and-inline/inline-block-percentage-max-width.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
When a box is sized under max-content constraint, any percentage value set for max-width should be considered as if it were infinite. In other words, it should have no effect on restricting the box's width.
> LibWeb: Ignore % max-width if box is sized under max-content constraint

- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
On Serenity and on my Linux machine, we have a 1:1 CSS-to-device pixel
ratio. On macOS, we have a 2:1 ratio. This did not effect the Qt chrome,
because we are ignoring this position and placing the context menu at
the globally-accessible mouse position. The AppKit chrome will be using
this position, though.
> WebContent: Convert image/media context menu positions to device pixels

- AK/RecursionDecision.h
- AK/StringUtils.cpp
- AK/StringUtils.h
- AK/StringView.h
- Userland/Libraries/LibXML/DOM/Node.h
- Userland/Libraries/LibXML/Parser/Parser.cpp
- Userland/Libraries/LibXML/Parser/Parser.h
These are (hopefully) noncontroversial changes I needed to make while working on `JSSpecCompiler`. They will be used in the future initial `JSSpecCompiler` PR. Feel free to ask me to add tests (however, note that LibXML mostly doesn't have tests).
This allows to get rid of a lot of `Variant::visit` calls, thus makes interaction with LibXML much nicer.
Recording nodes' location makes possible to generate nice error "stacktraces" when one parses information from XML-like format.
Looks like an oversight, but pinging @alimpfard if this is intentional.
> AK+LibXML: Quality of life changes

- Documentation/BuildInstructions.md
The qemu-system-x86 package is a dependency of the qemu-desktop package both on Arch and Manjaro Linux so there is no need to install it explicitly.
> Documentation: Remove qemu-system-x86 from explicit dependencies on Arch

- Tests/LibWeb/Layout/expected/display-table-inline-children.txt
- Tests/LibWeb/Layout/expected/grid/floating-table-wrapper-width.txt
- Tests/LibWeb/Layout/input/grid/floating-table-wrapper-width.html
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Fixes #20385 and some Wikipedia pages, for example: https://en.wikipedia.org/wiki/2022%E2%80%9323_UEFA_Champions_League_knockout_phase
> LibWeb: Set table wrapper width from the table box

- Kernel/Devices/Storage/NVMe/NVMeInterruptQueue.cpp
- Kernel/Devices/Storage/NVMe/NVMePollQueue.cpp
- Kernel/Devices/Storage/NVMe/NVMeQueue.h
This was the root cause of zombie processes showing up randomly and disappearing after some disk activity, such as running shell commands - The NVMeIO AsyncBlockDeviceRequest member simply held a pointer to a Process object, therefore it could keep it alive a for a long time after it ceased to actually function at all.
This has to be merged before #20588 could be merged.
> Kernel/Storage: Properly free unused NVMeIO AsyncBlockDeviceRequest

- Kernel/Devices/Storage/NVMe/NVMeController.cpp
- Kernel/Devices/Storage/NVMe/NVMeController.h
- Kernel/Devices/Storage/NVMe/NVMeDefinitions.h
- Kernel/Devices/Storage/NVMe/NVMeInterruptQueue.cpp
- Kernel/Devices/Storage/NVMe/NVMeInterruptQueue.h
- Kernel/Devices/Storage/NVMe/NVMePollQueue.cpp
- Kernel/Devices/Storage/NVMe/NVMePollQueue.h
- Kernel/Devices/Storage/NVMe/NVMeQueue.cpp
- Kernel/Devices/Storage/NVMe/NVMeQueue.h
Shadow doorbell feature was added in the NVMe spec to improve
the performance of virtual NVMe devices. [1]
Typically, ringing a doorbell involves writing to an MMIO register in
QEMU, which can be expensive as there will be a trap for the VM.
Shadow doorbell mechanism was added for the VM to communicate with the guest OS
when it needs to do an MMIO write, thereby avoiding it when it is not
necessary.
There is **no performance improvement** with this support in Serenity
**at the moment** because of the block layer constraint of not batching
multiple IOs. Once the **command batching** support is added to the block
layer, **shadow doorbell support can improve performance** by avoiding many
MMIO writes.
[1] https://www.collabora.com/news-and-blog/blog/2016/08/23/increased-performance-of-emulate …
> Kernel: Add NVMe shadow doorbell support

- Documentation/BuildInstructionsOther.md
Add `qemu-audio-pa` for the audio driver, change qemu `i386` with `x86_64` and mention `fuse2fs` for building.
> Documentation: Add dependencies for building on alpine linux

- Tests/LibWeb/TestCSSPixels.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
We had the same issue as discovered in #20529 in CSSPixels aswell....
CC @ronak69
> LibWeb: Fix a rounding issue on CSSPixels multiplication

- Ports/backward-cpp/patches/0002-backward-Pretend-to-be-Linux-with-some-modifications.patch
- Ports/backward-cpp/patches/0003-Link-to-zstd-library.patch
- Ports/backward-cpp/patches/ReadMe.md
- Ports/binutils/package.sh
This PR makes 2 separate, but related changes:
The first change ensures `backward-cpp` links against `zstd` if it is installed. This fixes an issue where `backward-cpp` previously wouldn't build when `zstd` was installed. This change could probably be upstreamed. The only reason that I'm hesitant to do so is that this only affects `backward-cpp` when using a static `libbfd` from `binutils` >= 2.4.0. I'm not sure how common this kind of setup is outside of what we're doing.
The second change includes `zstd` as a dependency of `binutils`. This ensures that `binutils` is built with `zstd` support, which it has had since version 2.4.0.
Making both of these changes at the same time means that `zstd` will always be linked against when we build `backward-cpp`.
> Ports/backward-cpp: Link against zstd if present

- AK/Function.h
- Userland/Libraries/LibJS/Heap/Cell.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
- Userland/Libraries/LibJS/Heap/HeapFunction.h
- Userland/Libraries/LibJS/Heap/HeapRootTypeOrLocation.h
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.h
This change introduces HeapFunction, which is intended to be used as a
replacement for SafeFunction. The new type behaves like a regular
GC-allocated object, which means it needs to be visited from
visit_edges, and unlike SafeFunction, it does not create new roots for
captured parameters.
Co-Authored-By: Andreas Kling <kling@serenityos.org>
> AK+LibJS: Introduce JS::HeapFunction

- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicLoader.h
- Userland/Libraries/LibELF/DynamicObject.h
This reduces the startup time of LibWeb by 10%, and eliminates 156'000 of the total 481'000 global symbol lookups during a self-test run.
> LibELF: Cache consecutive lookups for the same symbol

- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/WebContentView.cpp
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
We have `on_navigate_back` + `on_back_button` and `on_navigate_forward` + `on_forward_button`. Remove the `*_button variants`.
> LibWebView+Ladybird: Remove duplicate WebContent callback

- Userland/Services/WebDriver/Client.cpp
This allows the session to reject the request with "no such window", instead of crashing by assuming the JSON value was already a string.
> WebDriver: Coerce window handles to strings when activating a tab

- AK/StringView.h
- Documentation/Patterns.md
- Meta/Lagom/ReadMe.md
The proper syntax for defining user-defined literals does not require a space between the `operator""` token and the operator name:
> error: identifier 'sv' preceded by whitespace in a literal operator
>        declaration is deprecated
---
Please wait for CI to pass, I don't know how older Clang/GCC versions will react to this change.
> AK: Fix Clang 18 `-Wdeprecated-literal-operator` warning

- Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
Callbacks registered within the SharedImageRequest can be removed after the request has been completed. This resolves the GC memory leak issue that occurs due to a cyclic dependency, where the callback captures the image request while being owned by the image request at the same time.
> LibWeb: Clear callbacks in `SharedImageRequest` after request is done

- Userland/Libraries/LibCore/ArgsParser.cpp
Inspired by #20641, detect when adding an option that its long and short names are both unique. If they are not, print a warning and crash.
> LibCore: Prevent duplicate ArgsParser option names

- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Using `Core::Timer` that doesn't implicitly convert callback to `JS::SafeFunction` fixes the bug when `BrowsingContext` is never destroyed because of cyclic dependency between callback and `BrowsingContext`.
> LibWeb: Use `Core::Timer` for cursor blink timer in `BrowsingContext`

- Ladybird/CMakeLists.txt
- Meta/Azure/Setup.yml
- Meta/serenity.sh
- Tests/LibWeb/WPT/run.sh
We should be documenting required pacakges elsewhere and installing them
in the setup step of CI.
This also fixes a problem where the run script would fail if you already
had a cloned wpt directory.
> Meta+LibWeb: Make WPT run script runnable anywhere, remove apt installs

- Ladybird/RequestServer/CMakeLists.txt
Adding RequestServer to Ladybird broke building on Solaris as it wasn't linked to Solaris networking libraries (libnsl and libsocket) which resulted in "Undefined symbol gethostbyname errors"
This change links RequestServer to libnsl and libsocket on Solaris, making sure that gethostbyname and other networking-related functions are found here.
> Ladybird: Link libnsl and libsocket to RequestServer on Solaris

- Tests/LibWeb/WPT/Add-Ladybird-WebDriver-runner.patch
- Tests/LibWeb/WPT/run.sh
Instead of assuming that the WebDriver binary is in PATH or the two most common build directories for our scripts, add a command line argument to the script to pass a WebDriver binary.
> Tests: Convert WebDriver patch to a git patch and clean up assumptions

- Tests/LibWeb/Ref/manifest.json
- Tests/LibWeb/Ref/svg-symbol-ref.html
- Tests/LibWeb/Ref/svg-symbol.html
- Userland/Libraries/LibWeb/SVG/SVGSymbolElement.cpp
Reopening of #20655 because I've removed the commit and the PR closed itself. A rookie mistake :^(
Fixes a couple SVGs on ex. https://www.jetbrains.com/clion/
| --- | --- |
| ![obraz](https://github.com/SerenityOS/serenity/assets/36564831/ca0f2808-a8aa-4368-aa0e-8e49e7104fb5) | ![obraz](https://github.com/SerenityOS/serenity/assets/36564831/c7ce8f26-f942-4fbc-b376-373751b65426) |
> LibWeb: Add Base::apply_presentational_hints call to <symbol> element

- Userland/Libraries/LibWeb/CSS/Angle.cpp
- Userland/Libraries/LibWeb/CSS/Angle.h
- Userland/Libraries/LibWeb/CSS/Frequency.cpp
- Userland/Libraries/LibWeb/CSS/Frequency.h
- Userland/Libraries/LibWeb/CSS/Length.cpp
- Userland/Libraries/LibWeb/CSS/Length.h
- Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Token.h
- Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.h
- Userland/Libraries/LibWeb/CSS/Percentage.h
- Userland/Libraries/LibWeb/CSS/Ratio.cpp
- Userland/Libraries/LibWeb/CSS/Ratio.h
- Userland/Libraries/LibWeb/CSS/Resolution.cpp
- Userland/Libraries/LibWeb/CSS/Resolution.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/Time.cpp
- Userland/Libraries/LibWeb/CSS/Time.h
- Userland/Libraries/LibWeb/Layout/Box.cpp
The red wiggly underlines have been bothering me for ages, so let's actually fix the clangd warnings about float->double promotion by not downgrading to float only to later promote to double again.
Also, remove the integer constructors for dimension types, because we no longer need them.
> LibWeb: Consistently use doubles in CSS

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
> LibWeb: Implement getting "ancestor navigables" of a document

- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
This fixes bug introduced in bdd3a16b16c99bd6342ad34b629b89a510942699 that `m_body` is not visited because `BodyType` variant has `JS::NonnullGCPtr` instead of `JS::GCPtr`.
> LibWeb: Fix `Request::visit_edges` to actually visit `m_body`

- Tests/LibWeb/Layout/expected/flex/align-items-normal.txt
- Tests/LibWeb/Layout/expected/height-min-max-fit-content.txt
- Tests/LibWeb/Layout/input/flex/align-items-normal.html
- Tests/LibWeb/Layout/input/height-min-max-fit-content.html
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Visual progression on https://developer.mozilla.org/en-US/
Before:
After:
> LibWeb: Two layout fixes for MDN

- Userland/Libraries/LibWeb/CSS/Parser/Token.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This is all of them currently, except Length, because we lack the needed
information to be able to expand font-relative lengths.
The whole way `expand_unresolved_values()` works is awkward, but at some
point we'll be able to run the simplification algorithm on the
calculation, which will either return a single value, or a new
calculation that's simplified as much as possible.
Mostly I just wanted that FIXME log message to go away, because it's
overwhelming on certain sites.
> LibWeb: Fill in missing kinds of calc() expansion in StyleComputer

- Userland/Libraries/LibGUI/TextEditor.cpp
- Userland/Libraries/LibGUI/TextEditor.h
This feature is similar(somewhat) to the Clion's highlight all occurances of word under caret.
> HackStudio: Highlight all the occurances of selected text in editor

- Ladybird/Qt/WebContentView.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Since #20380 and #20383 the scrolling in Ladybird on macOS is very slow and its kind of broken. You need to scroll super far to scroll a little bit on the web page. This change uses the Qt `pixelData()` function on macOS because that is uses the systems pixel scroll offsets. This fixes most scroll issues for me. But I love to here from others that have macOS if this works for them.
> Ladybird: Use pixelDelta() on supported platforms for better scrolling

- Kernel/Devices/HID/KeyboardDevice.cpp
https://github.com/SerenityOS/serenity/pull/19892/commits/afc572a19eb7206a020a3bc4b86ca3fa8859d791 caused several keys that have the same scan codes as keys on the numpad to be considered _on_ the numpad, which broke shortcuts that include those keys.
The difference in scan codes is the presence of the e0 prefix. Note that numpad's `/` and `Enter` have the e0 prefix, but other numpad keys don't.
Comparison of the detected keys, by the html page added in the PR that included https://github.com/SerenityOS/serenity/pull/19892/commits/afc572a19eb7206a020a3bc4b86ca3fa8859d791. Keys pressed in bottom to top order:
`Numpad 0`, `Numpad .`, `Numpad Enter`, `Numpad 1`, `Numpad 2`, `Numpad 3`, `Numpad 4`, `Numpad 5`, `Numpad 6`, `Numpad 7`, `Numpad 8`, `Numpad 9`, `Numpad +`, `Numpad -`, `Numpad *`, …
> Kernel: Stop overeagerly adding a Keypad modifier + add it to the numpad Enter key

- Kernel/Devices/HID/KeyboardDevice.cpp
- Kernel/Devices/HID/Management.cpp
- Kernel/Devices/HID/Management.h
Previously we would set the KeyCode correctly to the appropriate extended keys values, like `Home` and `End`, but keep the code point of the original keys, like `1`, `2`, `3`, etc. Because of this, the keys would just print the original keys, instead of behaving like the extended ones.
In the After video, at 0:19 you can see me turning the Num Lock off and then using numpad keys to navigate through the file (you can also use the `.` key as a `Delete` but I forgot to record that :P).
This is not possible in the Before video, the keys still print the numbers after turning Num Lock off.
| --- | --- |
| <video src="https://github.com/SerenityOS/serenity/assets/36564831/f0b1b8bb-84d1-4b42-920f-97f8f05878d0"> | <video …
> Kernel: Change the code point of numpad keys to 0, when Num Lock is off

- Userland/Libraries/LibCore/System.cpp
Errno::from_syscall doesn't exist so the build aborts with an error on FreeBSD and NetBSD.
By changing Errno to Error,like it already is at all other places,the build succeeds here.
> LibCore: Change Errno to Error in FreeBSD and NetBSD-specific functions

- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
- Tests/LibUnicode/TestUnicodeCharacterTypes.cpp
- Userland/Libraries/LibUnicode/CharacterTypes.cpp
- Userland/Libraries/LibUnicode/CharacterTypes.h
- Userland/Libraries/LibUnicode/Forward.h
This will let us examine code points to determine the rtl/ltr direction of a piece of text.
> LibUnicode: Generate data for bidirectional character types

- AK/Assertions.h
- AK/BuiltinWrappers.h
- AK/Platform.h
This PR adds the necessary macros to AK for riscv64 support for further riscv64 serenity patches.
The second commit of this PR makes `bit_scan_forward` not use `__builtin_ffs` on GCC without the Zbb "Basic bit-manipulation" extension. Otherwise it would redirect it to `ffs`, causing a linker error.
> AK: Add riscv64 support

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp
- Tests/LibWeb/Layout/expected/css-dir-selector.txt
- Tests/LibWeb/Layout/input/css-dir-selector.html
- Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Userland/Libraries/LibWeb/CSS/PseudoClasses.json
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/Dump.cpp
~~Relies on #20532.~~
Obviously, we don't render RTL text properly, but we do now detect it! Here's a screenshot of the test file:
|Firefox|Ladybird|
|---|---|
| ![image](https://github.com/SerenityOS/serenity/assets/222642/27573125-99d4-4ff7-9127-0a92864624fc) | ![image](https://github.com/SerenityOS/serenity/assets/222642/044fe47f-918e-4d10-8186-ede95cac868d) |
> LibWeb: Add the `:dir()` selector pseudo-class

- Tests/LibWeb/Ref/img-srcset-viewport-relative-sizes-ref.html
- Tests/LibWeb/Ref/img-srcset-viewport-relative-sizes.html
- Tests/LibWeb/Ref/manifest.json
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/SourceSet.cpp
We still don't know how to resolve font-relative lengths in `<img sizes>` since we don't always have font size information available at this stage in the pipeline, but we can at least handle viewport-relative lengths.
This fixes an issue on many websites where low-resolution images were loaded (appropriate for a small viewport) even when the viewport is big.
Visual progression on https://twinings.co.uk/ (note quality of background image!)
Before:
After:
> LibWeb: Resolve viewport-relative `<img sizes>` values

- Ports/libuuid/package.sh
Having this option enabled made `libuuid` link to `libintl` only when the `gettext` port was installed. This made the `taskwarrior` port fail to build when `gettext` was installed prior to `libuuid`.
The only ports which rely on `libuuid` are `taskwarrior` and `python3`. Both build and run fine after this change.
> Ports/libuuid: Disable natural language support

- Tests/LibWeb/Layout/expected/nowrap-and-no-line-break-opportunity.txt
- Tests/LibWeb/Layout/expected/space-is-soft-line-break-opportunity.txt
- Tests/LibWeb/Layout/expected/table/line-breaking-in-cells.txt
- Tests/LibWeb/Layout/input/nowrap-and-no-line-break-opportunity.html
- Tests/LibWeb/Layout/input/space-is-soft-line-break-opportunity.html
- Tests/LibWeb/Layout/input/table/line-breaking-in-cells.html
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
Check the width of the next token after white space to decide line breaks. The next width can also be the total width of multiple tokens. This better follows the CSS Text specification and matches behavior of other browsers.
Fixes #20388.
> LibWeb: Improve the line breaking algorithm

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
Cherry-picked the non-CSS commits from #19448
This lets 
```
SERENITY_SOURCE_DIR=/home/andrew/serenity \
python3 ./wpt/wpt run \
--webdriver-binary /home/andrew/serenity/Build/lagom/bin/WebDriver \
--no-fail-on-unexpected \
--no-fail-on-unexpected-pass  \
--skip-timeout \
--log-raw-level DEBUG --log-raw wpt.log \
ladybird   xhr/xmlhttprequest-eventtarget.htm
```
actually open the test, but it doesn't actually close the browser at the end of the test (for reasons?)
EDIT: Oh, all you need is `--no-pause-after-test` and we complete the test run :grimacing:
> LibWeb: Enable running WPT testharness

- Ports/prboom-plus/package.sh
This fixes an issue where `prboom-plus` wouldn't build if the `make` port was installed. Including this also makes some manually specified paths unnecessary.
> Ports/prboom-plus: Add `CMAKE_TOOLCHAIN_FILE` to `configopts`

- Tests/LibWeb/Layout/expected/table/forced-break-stops-non-whitespace-sequence.txt
- Tests/LibWeb/Layout/input/table/forced-break-stops-non-whitespace-sequence.html
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
This avoids a crash since such items don't have a node nor CSS properties. Fixes crashes on Wikipedia pages which contain preformatted code.
> LibWeb: Stop collecting lookahead items on forced break

- .clang-format
- Ladybird/AppKit/Application/Application.h
- Ladybird/AppKit/Application/Application.mm
- Ladybird/AppKit/Application/ApplicationDelegate.h
- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/Application/EventLoopImplementation.h
- Ladybird/AppKit/Application/EventLoopImplementation.mm
- Ladybird/AppKit/System/Carbon.h
- Ladybird/AppKit/System/Cocoa.h
- Ladybird/AppKit/System/CoreFoundation.h
- Ladybird/AppKit/System/Detail/Footer.h
- Ladybird/AppKit/System/Detail/Header.h
- Ladybird/AppKit/UI/Event.h
- Ladybird/AppKit/UI/Event.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/AppKit/UI/Tab.h
- Ladybird/AppKit/UI/Tab.mm
- Ladybird/AppKit/UI/TabController.h
- Ladybird/AppKit/UI/TabController.mm
- Ladybird/AppKit/Utilities/Conversions.h
- Ladybird/AppKit/Utilities/Conversions.mm
- Ladybird/AppKit/Utilities/URL.h
- Ladybird/AppKit/Utilities/URL.mm
- Ladybird/AppKit/main.mm
- Ladybird/CMakeLists.txt
- Meta/Azure/Lagom.yml
- Meta/check-style.py
This adds an alternative Ladybird chrome for macOS using the AppKit framework. Just about everything needed for normal web browsing has been implemented. This includes:
* Tabbed, scrollable navigation
* History navigation (back, forward, reload)
* Keyboard / mouse events
* Favicons
* Context menus
* Cookies (with SQLServer storage)
* Dialogs (alert, confirm, prompt)
* WebDriver support
This does not include debugging tools like the JavaScript console and inspector, nor theme support.
The Qt chrome is still used by default. To use the AppKit chrome, set the ENABLE_QT CMake option to OFF.
> Ladybird: Implement an AppKit chrome for macOS :^)

- Tests/LibWeb/Layout/expected/block-and-inline/button-baseline-align.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-block-content-baseline-align.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label-and-font-size.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
- Tests/LibWeb/Layout/expected/input-text-node-invalidation-on-value-change.txt
- Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt
- Tests/LibWeb/Layout/expected/table/inline-table-width.txt
- Tests/LibWeb/Layout/expected/table/nested-table-box-width.txt
- Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt
- Tests/LibWeb/Layout/input/block-and-inline/button-baseline-align.html
- Tests/LibWeb/Layout/input/block-and-inline/button-with-block-content-baseline-align.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Make the existing algorithm recursive, accounting for boxes which contain line boxes indirectly. Fixes some button alignment issues on Wikipedia.
> LibWeb: Derive baseline from rightmost descendant

- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateDateTimeFormatData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateLocaleData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateNumberFormatData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateRelativeTimeFormatData.cpp
- Tests/LibLocale/TestDateTimeFormat.cpp
- Tests/LibLocale/TestLocale.cpp
- Userland/Applications/ClockSettings/TimeZoneSettingsWidget.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DisplayNames.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DisplayNamesPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/Locale.cpp
- Userland/Libraries/LibJS/Runtime/Intl/Locale.h
- Userland/Libraries/LibJS/Runtime/Intl/LocaleConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/LocalePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormat.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibLocale/DateTimeFormat.cpp
- Userland/Libraries/LibLocale/DateTimeFormat.h
- Userland/Libraries/LibLocale/Locale.cpp
- Userland/Libraries/LibLocale/Locale.h
- Userland/Libraries/LibLocale/NumberFormat.cpp
- Userland/Libraries/LibLocale/NumberFormat.h
- Userland/Libraries/LibLocale/RelativeTimeFormat.cpp
- Userland/Libraries/LibLocale/RelativeTimeFormat.h
These APIs only perform small allocations, and are only used by LibJS.
Callers which could only have failed from these APIs are also made to
be infallible here.
Work towards #20449.
> LibLocale+LibJS: Make locale APIs infallible

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentServer.ipc
Right now we directly pass theme colours to web content, so that it matches native SerenityOS widgets. That's not quite what websites expect, and some websites (like example.com) are illegible when using dark themes.
Implementing the User CascadeOrigin is a first step to fixing this: We use more expected colours by default, and then let Help and other users of OOPWV manually set a user style-sheet that matches the desktop theme.
This PR just implements the User CascadeOrigin, and doesn't make anything use it.
> LibWeb+LibWebView+WebContent: Add support for "User" CascadeOrigin

- Ports/.port_include.sh
This ensures that the correct index is always used when selecting an image of a particular size.
This fixes an issue with the `lite-xl` port where the wrong size icon was being used. This issue only affects users of ImageMagick 7.x. 
Before:
After:
> Ports: Simplify the output from `identify` when installing icons

- Userland/Libraries/LibWeb/SVG/SVGUseElement.cpp
| --- | --- |
| <video src="https://github.com/SerenityOS/serenity/assets/36564831/4de5cd10-7b80-4b55-af8c-7983ca1e4446"> | <video src="https://github.com/SerenityOS/serenity/assets/36564831/d42aea1e-ef07-47a9-984b-f6c5fd31693b"> |
Previously we would only update the shadow tree if the original \<symbol\> element or any of its children were changed or when the document was loaded. Coincidentally, there was an issue that if for some reason the document is already loaded when `initialize()` of the \<use\> element is called, or the document never finishes loading (due to a bug probably, I didn't figure out which option is actually occurring), the shadow tree is never populated. So this might be papering over some other issue... but either way, some SVGs on the …
> LibWeb: Update <use> visuals after changing the referenced element

- Meta/Lagom/Fuzzers/FuzzBrotli.cpp
- Meta/Lagom/Fuzzers/FuzzZlibDecompression.cpp
- Tests/LibCompress/TestBrotli.cpp
- Tests/LibCompress/TestZlib.cpp
- Userland/Libraries/LibCompress/Brotli.cpp
- Userland/Libraries/LibCompress/Brotli.h
- Userland/Libraries/LibCompress/Gzip.cpp
- Userland/Libraries/LibCompress/Gzip.h
- Userland/Libraries/LibCompress/Zlib.cpp
- Userland/Libraries/LibCompress/Zlib.h
- Userland/Libraries/LibGfx/Font/WOFF/Font.cpp
- Userland/Libraries/LibGfx/Font/WOFF2/Font.cpp
- Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
- Userland/Libraries/LibHTTP/Job.cpp
These I had made when starting to try and untangle LibHTTP's decompressor setup, but that ultimately got nowhere. Still, these three commits are useful on their own.
> LibCompress: Port `ZlibDecompressor` to `AK::Stream` (and other small changes)

- .clang-tidy
This flags nearly every static function, so let's disable it
> Meta: Disable misc-use-anonymous-namespace clang-tidy warning

- Userland/Games/Flood/CMakeLists.txt
- Userland/Games/Flood/FloodWindow.gml
- Userland/Games/Flood/MainWidget.h
- Userland/Games/Flood/SettingsDialog.cpp
- Userland/Games/Flood/SettingsDialog.h
- Userland/Games/Flood/SettingsWidget.gml
- Userland/Games/Flood/SettingsWidget.h
- Userland/Games/Flood/main.cpp
- Flood: Propagate errors when creating SettingsDialog
- Flood: Use the new GML compiler
- Flood: Replace usage of DeprecatedString
Contributes to #17128 and #20518.
> Flood: Modernization

- Ports/libgd/package.sh
Previously, building `libgd` with `fontconfig` already installed would cause the build to fail.
~~Currently, we are building `libgd` without JPEG and TIFF support. These could be included, but currently the only port that makes use of this library (`npiet`) doesn't use this functionality.~~
> Ports/libgd: Explicitly specify which dependencies to include

- Kernel/TTY/MasterPTY.cpp
As "\n" is translated to "\r\n" in TTYs, the condition for a write to succeed on a pseudoterminal should check if the underlying buffer has 2 bytes empty rather than 1.
Fixes SerenityOS#18888
> Kernel: Fix condition for write to succeed on pseudoterminal

- Ports/build_all.sh
The script previously failed early after building `mandoc`, as it failed to switch to the correct directory for the next port. With this change, the script now runs to completion.
> Ports/build_all: Read port directory names into an array immediately 

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/WebContentView.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Utilities/headless-browser.cpp
This continues the work started by #18893, with the goal of reducing the amount of copy-paste duplication across every `ViewImplementation`. The savings here aren't *as* huge as that PR, but the duplication did stick out to me nonetheless while bringing up the AppKit chrome.
> Ladybird+LibWebView: Continue work to reduce duplcation betwen browser implementations

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/WebContentView.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Utilities/headless-browser.cpp
Continuing #18893 and #20723. Again, the de-deduplication is not *as* large as the first PR, but now all GUI hooks are propagated in a uniform manner.
> Ladybird+LibWebView: Migrate remaining notifications to LibWebView callbacks

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
- Userland/Libraries/LibWeb/Layout/VideoBox.cpp
- Userland/Libraries/LibWeb/Layout/VideoBox.h
- Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
- Userland/Libraries/LibWeb/Painting/ImagePaintable.h
With this change, elements that want to receive viewport rect updates will need to register on document instead of the browsing context.
This change solves the problem where a browsing context for a document is guaranteed to exist only while the document is active so browsing context might not exit by the time DOM node that want to register is constructed.
This is a part of preparation work before switching to navigables where this issue becomes more visible.
> LibWeb: Move viewport subscriptions from BrowsingContext to Document

- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Regressed in 2a067b5601681fdb643732ac319a42f8b006300e.
I could not find anything obviously broken by this, but it definitely was unintentional on my part.
> LibWeb: Fix accidentally skipping post-paint actions for positioned SCs

- Ladybird/AppKit/Application/EventLoopImplementation.mm
- Ladybird/AppKit/UI/LadybirdWebView.mm
Once we are done with our references to some CoreFoundation types, we must be sure to manually release those references.
> Ladybird: Ensure we release CoreFoundation references

- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
As it turns out, there are popular User-Agent blacklists out there with the string "LibWeb" in them. Such entries have been added long before our LibWeb existed, so "LibWeb" has presumably been used by some bot that people got tired of.
Trying to chase down everyone who has installed these blacklists is obviously a losing battle, so this patch simply removes the engine part of our default UA string.
> LibWeb: Remove "LibWeb+LibJS/1.0" from the default User-Agent string

- Ports/dtc/package.sh
Previously, the install step was failing on my machine when the `python3` port was installed.
> Ports/dtc: Specify `NO_PYTHON` when running `make install`

- Ports/aria2/package.sh
- Ports/libssh2/package.sh
This PR makes 3 separate, but related changes:
* Use OpenSSL instead of `libgcrypt` as the crypto backend for `libssh2`. Openssl takes precedence if both are found, so preferring it makes sense.
* Don't use `c-ares` in `aria2`: This was causing the build to fail if the `c-ares` port was installed prior to `aria2`
* Don't use `sqlite3` in `aria2`: This disables Firefox/Chromium cookie support in aria2, which isn't that useful in SerenityOS, but makes the build consistent, regardless of whether the `sqlite` port is installed or not.
I made the `libssh2` changes at the same time as `aria2` because `aria2` is the only thing that depends on `libssh2`.
> Ports/aria2: Explicitly disable some optional dependencies

- Tests/LibWeb/Ref/grid-items-painting-order-ref.html
- Tests/LibWeb/Ref/grid-items-painting-order.html
- Tests/LibWeb/Ref/item-with-negative-z-index-ref.html
- Tests/LibWeb/Ref/item-with-negative-z-index.html
These two ref-tests involve two boxes positioned in the same place, with outlines. Outlines always have a border-radius, meaning that the corner pixels are not 100% opaque. (It seems to be 254 instead of 255.) With the test files painting two outlines, and the ref test only painting one, slight changes in the background color of the page would make that slight variation visible sometimes. So, let's avoid that inconsistency by always painting one outline instead of two.
> LibWeb: Adjust ref-tests to reduce flakiness

- Userland/Libraries/LibGfx/Font/FontDatabase.cpp
- Userland/Libraries/LibGfx/Font/FontDatabase.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Fixes a performance regression from 69a81243f5a602e5994258bc10af132f008d5858.
> LibGfx+LibWeb: Avoid looping through every system font repeatedly during CSS font fallback

- Userland/Libraries/LibWeb/Painting/BorderPainting.h
This function is used to calculate a matching radius that goes inside or outside of the border. For example, if the border-radius is 10px and we are 5px further out, the radius needs to be 15px to look right. However, if the radius is 0 it isn't rounded, and we want to keep the same sharp corner no matter how far we go.
This makes our outline rendering better match Chrome and Firefox.
> LibWeb: When growing or shrinking a border-radius, ignore it if it's 0

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/FontCache.cpp
- Userland/Libraries/LibWeb/FontCache.h
In case we've looked up the family name before and cached the result of font fallback, we now invalidate any cached entries with the same family name so that the next lookup may consider the newly downloaded font.
> LibWeb: Invalidate font cache when web fonts are downloaded

- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibCore/System.cpp
Solaris doesn't support the sysctl command and doesn't have a sys/syctl.h header file,which seems to be common on other Unix variants.
Trying to include this file for AK_OS_BSD_GENERIC makes the build fail on Solaris currently.
The current_executable_path function in System.cpp is already implemented in a way that doesn't need sysctl on Solaris.
The is_being_debugged function in Process.cpp is not yet implemented for Solaris,but will have to be done in a non-sysctl way as that simply doesn't exist on Solaris.
> LibCore: Don't include sys/sysctl.h on Solaris

- Tests/LibWeb/CMakeLists.txt
- Tests/LibWeb/Layout/expected/table/colspan-with-trailing-characters.txt
- Tests/LibWeb/Layout/expected/table/rowspan-with-trailing-characters.txt
- Tests/LibWeb/Layout/input/table/colspan-with-trailing-characters.html
- Tests/LibWeb/Layout/input/table/rowspan-with-trailing-characters.html
- Tests/LibWeb/TestNumbers.cpp
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
- Userland/Libraries/LibWeb/HTML/Numbers.cpp
- Userland/Libraries/LibWeb/HTML/Numbers.h
The spec [1] says the `colspan` and `rowspan` attributes should be valid
numbers. However, all major browsers ignore tailing non-numeric
characters and we should do the same.
This patch changes the `HTMLTableCellElement::col_span` and
`HTMLTableCellElement::row_span` methods to use a more relaxed number
parsing mode (`NumericParseMode::IgnoreTrailingCharacters`).
[1] https://html.spec.whatwg.org/multipage/tables.html#attr-tdth-colspan
Fixes #19937
> LibWeb: Improve table colspan and rowspan spec alignment

- Userland/Libraries/LibWeb/CSS/Default.css
This property was removed from the CSS specs, and efforts to correct the HTML spec have stalled. For now, let's comment them out so that I don't get spammed with the meaningless log warnings that they didn't parse, every time I launch Ladybird. :^)
> LibWeb: Comment out invalid `display-outside` rules from Default.css

- Userland/Libraries/LibGUI/PasswordInputDialog.cpp
missed it in https://github.com/SerenityOS/serenity/pull/14172
> LibGUI: Use default button in PasswordInputDialog

- Userland/Applications/Browser/Tab.cpp
Trailing whitespace in the source view is not actionable, so there's no benefit to showing it.
See here:
Now:
> Browser: Do not visualize trailing whitespace in the source viewer

- Tests/LibWeb/TestHTMLTokenizer.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.h
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
- Userland/Libraries/LibWeb/HTML/SyntaxHighlighter/SyntaxHighlighter.cpp
The details are in the commit messages, but a couple are easy to see with a theme that shows attributes/values clearly.
For example, in this self-closing `meta` tag, the attribute name `charset` (colored green) captures the attribute value as well:
Now we properly set the attribute name's end position to not consume the attribute value:
Another example: Previously, we didn't highlight valueless attributes at all, and were off-by-one on the attribute name of any subsequent attribute:
Now we detect the valueless attribute correctly:
> LibWeb: A couple of HTMLTokenizerFixes

- Tests/LibWeb/Text/expected/css/font-face-src-local-serialization.txt
- Tests/LibWeb/Text/input/css/font-face-src-local-serialization.html
- Userland/Libraries/LibWeb/CSS/CSSFontFaceRule.cpp
- Userland/Libraries/LibWeb/CSS/FontFace.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/Dump.cpp
There were two issues here:
- We did not include a `Referer` header with CSS font HTTP requests. This made apple.com respond with 404 (wat)
- We rejected CSS `@font-face` rules with `src: local(...), ...` which they use for what appears to be some kind of compatibility hack.
Visual progression on https://apple.com/
Before:
After:
> LibWeb: Make custom fonts load on apple.com

- Kernel/FileSystem/BlockBasedFileSystem.cpp
- Kernel/FileSystem/BlockBasedFileSystem.h
- Kernel/FileSystem/Ext2FS/FileSystem.cpp
- Kernel/FileSystem/Ext2FS/FileSystem.h
- Kernel/FileSystem/FileSystem.h
- Kernel/FileSystem/Inode.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
- Kernel/Tasks/PowerStateSwitchTask.cpp
Attempting to solve a FIXME which would allow flush_writes() to return ErrorOr<void>. Apologies for making a second pull request about this, deleted the previous one due to silly reasons. I also made the changes recommended by @ADKaster. For the changes I made in Inode.cpp and VirtualFileSystem.cpp I was unsure if it would be ok to add VERIFY_NOT_REACHED() macro as the if statement is currently empty and I was cautious about causing a kernel panic as I was warned about previously.
> Kernel: Allow Ext2FS::flush_writes() to return ErrorOr<void>

- Kernel/FileSystem/Inode.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
Fixes bad formatting in commit abcf05801ad259c06197b9ef54a76e58cf319509.
> Kernel: Run clang-format on a couple of FileSystem sources

- Ladybird/CMakeLists.txt
Without setting the --resources flag, headless-browser defaults to /res for all resources it tries to find, including the theme. It will not find this path on Lagom, so our attempt to load the default theme does not accomplish anything.
> LibWeb: Ensure layout/text/ref tests run with the desired default theme

- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.h
Replaces `load_src()` with `process_the_iframe_attributes()`. Both load document of iframe but the latter is defined in spec.
> LibWeb: Call process_the_iframe_attributes if iframe attribute changed

- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigateEvent.cpp
- Userland/Libraries/LibWeb/HTML/NavigateEvent.h
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.h
- Userland/Libraries/LibWeb/HTML/Navigation.idl
First, fixup Navigate event. Every property in an IDL dictionary is implied to be optional, unless it
is marked as required. If a dictionary is passed to a method with
optional, but it has at least one required or defaulted member, the
bindings will skip the optionality of the parameter and always pass a
struct with the required parameters filled in.
Next, onto navigation.navigate()
The implementation is incomplete, because our Navigable::navigate
implementation is missing the navigationAPIState parameter.
It also cannot actually be called without crashing the browser, because
Navigables are not fully hooked up yet to all navigation. The node
navigable for most documents is nullptr, which breaks an assumption in
the algorithm.
> LibWeb: Implement navigation.navigate()

- AK/NonnullOwnPtr.h
- Tests/AK/TestNonnullOwnPtr.cpp
- Tests/LibWeb/Layout/expected/media-query-resolution.txt
- Tests/LibWeb/Layout/input/media-query-resolution.html
- Tests/LibWeb/Text/expected/css/media-query-serialization-basic.txt
- Tests/LibWeb/Text/input/css/media-query-serialization-basic.html
- Userland/Libraries/LibWeb/CSS/Resolution.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
> LibWeb+AK: Load high resolution images on apple.com when running on high-DPI display

- Tests/LibWeb/Text/expected/HTML/Navigation-object-properties.txt
- Tests/LibWeb/Text/input/HTML/Navigation-object-properties.html
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
The invariants for these property getters are supposed to be checked by the has_entries_and_events_disabled AO, but we don't have all the plumbing hooked up between Navigables and Navigation yet.
Add a test to make sure that these methods don't assert when calling them on a fresh page.
Fixes #20778
> LibWeb: Don't assert when calling navigation properties

- Tests/LibWeb/Layout/expected/grid/named-tracks.txt
- Tests/LibWeb/Layout/expected/grid/template-lines-and-areas.txt
- Userland/Libraries/LibWeb/CSS/GridTrackPlacement.cpp
- Userland/Libraries/LibWeb/CSS/GridTrackPlacement.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
- Ambiguous `raw_value()` method is replaced with `line_number()` and `span()`.
- `line_name()` that before returned either line name or area name is replaced with `line_name()` and `area_name()`.
- `Position` type is replaced with `Line` and `Area` type so we don't have to guess while doing layout.
Affected test expectations:
- `template-lines-and-areas` - improvement over what we had before.
- `named-tracks` - rebaseline a giant test. will have to split it into smaller tests in the future.
> LibWeb: Disambiguate GridTrackPlacement API

- Userland/Libraries/LibGUI/AbstractView.cpp
This is a minor GUI bug fix in the "search by typing" feature of AbstractView. Here, the highlighted text shown in items' title wouldn't match the search query if the search query contained whitespace.
The difference can be seen in the following images, which show what happens when typing `"foo "` in FileManager:
It also works with multibyte UTF-8 code points and multiple lines. :^) Here's the result of typing `"æøå æøå æøå æ"`:
_NOTE: This PR was originally marked stale and closed due to inactivity a while ago (see #17340), so I'm trying again here with some minor updates and extra checks._
> LibGUI: Minor search highlighting bug fix

- Kernel/TTY/TTY.cpp
- Kernel/TTY/TTY.h
- Kernel/TTY/VirtualConsole.cpp
- Kernel/TTY/VirtualConsole.h
These options are not relevant and are actually meaningless on pure TTY devices, as they are meant to be effective only for the VirtualConsole devices.
This also removes the virtual marking from two methods because they're no longer declared in the TTY class as well.
Taken originally from #20761.
> Kernel: Remove KDSETMODE and KDGETMODE ioctl options from the TTY class

- Tests/LibWeb/Layout/expected/block-and-inline/list-markers-intruded-by-float.txt
- Tests/LibWeb/Layout/input/block-and-inline/list-markers-intruded-by-float.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Visual progression on https://www.bell-labs.com/usr/dmr/www/
Before:
After:
> LibWeb: Account for float intrusions in list marker x offset

- Userland/Libraries/LibAudio/MP3Loader.cpp
- Userland/Libraries/LibAudio/MP3Loader.h
- Userland/Libraries/LibAudio/MP3Types.h
To allow the recent [Changelog Interview with Andreas](https://changelog.com/podcast/554) to play in LibWeb, this implements a few fixes for `MP3Loader`:
- Parse the size of the ID3 tags from the header to skip past all the data before finding an MP3 frame sync code. Since the podcast MP3 file has a large PNG image for its album art, some of its data would be recognized as an MP3 frame, causing errors trying to play it back.
- Use the correct frame header size to skip the exact size of a frame when calculating the duration of audio and creating the seek table. Previously, it would skip to 2 bytes before the next frame when skipping a frame that has no CRC16 checksum, meaning that if it appears to have a sync code in those 2 bytes before the next frame, it will cause it to skip the frame …
> LibAudio: A few fixes for MP3Loader to play The Changelog podcast

- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
My first commit to `LibWeb`!
Used the following references:
- https://fetch.spec.whatwg.org/#cross-origin-embedder-policy-allows-credentials
- https://html.spec.whatwg.org/multipage/browsers.html#concept-origin
- https://fetch.spec.whatwg.org/#concept-request-current-url
- https://fetch.spec.whatwg.org/#concept-request-url-list (to make sure the `current_url()` call returns at least 1 element)
> LibWeb/Fetch: Use origins in Cross-Origin-Embedder-Policy algorithm

- Base/usr/share/man/man8/useradd.md
- Userland/Utilities/useradd.cpp
Previously, only the group number could be used.
Example usage:
> useradd: Allow group name or number to be used with the `-g`option

- Ports/mc/package.sh
This PR removes `libtool` as a dependency for `mc` and adds `--with-sysroot` to `configopts`, to prevent any host libraries affecting the build.
These changes were made in an effort to solve what turned out to be an unrelated issue. My testing shows that these changes have no negative impact on the `mc` port, so I believe they are worth doing.
> Ports/mc: Remove `libtool` dependency

- Ports/glib/package.sh
Previously, if `pcre2` was not installed before `glib`, the meson script would download its own version and use that.
> Ports/glib: Specify `pcre2` as a dependency instead of `pcre`

- Tests/LibWeb/Layout/expected/grid/place-items-center-nested-grids.txt
- Tests/LibWeb/Layout/input/grid/place-items-center-nested-grids.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
When the grid layout gets to
`resolve_items_box_metrics(GridDimension::Column)`, we've already determined the width of each column. However, the widths of the individual grid items themselves haven't been set. Rather than using `get_available_space_for_item()`, which returns an indefinite size if an item's width/height hasn't been set, we should use the already known track width as the available size to calculate the fit-content width.
> LibWeb: Use containing block width to measure fit-content width in GFC

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
Show files that are readable, writable or executable by the current user.
Example usage:
> find: Add the `-readable`, `-writable` and `-executable` options

- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTimeISO.js
This test has been flaky for quite some time. Disable it for now, and revisit once we've caught up with the Temporal spec.
> LibJS: Disable Temporal custom time zone test

- Base/usr/share/man/man1/sort.md
- Userland/Utilities/sort.cpp
This PR does two separate but related things: 
* Add the `-z` option for sorting null terminated input
* Allow multi-character separators to be used with the `-t` option
Example usage:
> sort: Add `-z` option to handle null terminated input

- Kernel/Net/TCPSocket.cpp
- Kernel/Net/TCPSocket.h
These were using real time as a mistake before; changing the system time during ongoing TCP connections shouldn’t break them.
This is an initial implementation, about as basic as intended by the RFC, and not configurable from userspace at the moment. It should reduce the amount of low-sized packets sent, reducing overhead and thereby network traffic.
Fixes #192
> Kernel/Net: Two TCP fixes

- Userland/Libraries/LibCore/ArgsParser.cpp
- Userland/Libraries/LibCore/Version.cpp
Instead of grabbing `uname -vr` on non-Serenity platforms, let's just hardcode a version. This prevents Lagom builds of applications like Shell or Ladybird from reporting their version as that of the host OS.
cc @kleinesfilmroellchen
> LibCore: Add default version for Lagom applications

- Tests/LibWeb/Layout/expected/grid/placement-using-named-tracks-1.txt
- Tests/LibWeb/Layout/expected/grid/placement-using-named-tracks-2.txt
- Tests/LibWeb/Layout/expected/grid/placement-using-named-tracks-3.txt
- Tests/LibWeb/Layout/input/grid/placement-using-named-tracks-1.html
- Tests/LibWeb/Layout/input/grid/placement-using-named-tracks-2.html
- Tests/LibWeb/Layout/input/grid/placement-using-named-tracks-3.html
- Userland/Libraries/LibWeb/CSS/GridTrackPlacement.cpp
- Userland/Libraries/LibWeb/CSS/GridTrackPlacement.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
This fixes regression introduced in
c03e025a324d2c8582d3c675b49c61274b7ff0fb by assuming that it is possible to determine whether identifier stands for line or area during parsing.
> LibWeb: Define if identifier represent area or line during layout [GFC]

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.h
- Userland/Libraries/LibWeb/HTML/Navigation.idl
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
The proper abstract operations on Navigable and TraversableNavigable are
not quite ready to call from Navigation. With this patch all of the
user-facing APIs of Navigation are in place, and the stage should be set
to implement the parts of the navigation and traversal AOs that need to
interact with the Navigation object.
> LibWeb: Implement navigation.reload, traverseTo, back, and forwards

- Userland/Utilities/find.cpp
This follows on from changes made in #20805.
Following discussion with @alimpfard  on Discord, it was decided that `PosixExtended` syntax would be a better choice, as it is closer, although not identical, to the `emacs` syntax used in `findutils`.
> find: Use `PosixExtended` regex syntax instead of `PosixBasic`

- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
The FIXME here describes an old constraint on JS Interpreters which no longer holds. It hails from a time when we had the global object and JS realm attached to the document.
> LibWeb: Remove outdated old_queue_global_event_with_document

- Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
- Userland/Libraries/LibJS/Tests/builtins/Array/Array.fromAsync.js
This is a normative change in the array from async proposal, see:
https://github.com/tc39/proposal-array-from-async/commit/49cfde2
It fixes a double construction when Array.fromAsync is given an array
like object.
Two test262 tests will now fail, as they have not (currently) been updated to match the updated spec.
> LibJS: Avoid double construction in Array.fromAsync

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
The argument supplied to the `-size` option may now be one of the following suffixes:
* b: 512-byte blocks. This is the default unit if no suffix is used.
* c: bytes
* w: two-byte words
* k: kibibytes (1024 bytes)
* M: mebibytes (1024 kibibytes)
* G: gibibytes (1024 mebibytes)
Sizes are rounded to the specified unit before comparison. The unit 
suffixes are case-sensitive.
Example usage:
> find: Allow unit suffixes to be used with the `-size` option

- Tests/LibWeb/Layout/expected/table/sum-of-percentage-column-widths-less-than-100.txt
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
If the table used width has to be adjusted because of a cell with percentage width, add back the undistributable space due to border spacing. This is consistent with the width distribution algorithm, which sets aside the undistributable space and the behavior of other browsers.
> LibWeb: Add back undistributable space when adjusting table width

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/DocumentState.h
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/Location.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
- Userland/Libraries/LibWeb/HTML/Navigation.h
- Userland/Libraries/LibWeb/HTML/NavigationParams.h
- Userland/Libraries/LibWeb/HTML/SandboxingFlagSet.h
- Userland/Libraries/LibWeb/HTML/SourceSnapshotParams.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/XHR/FormData.h
- Userland/Libraries/LibWeb/XHR/FormDataEntry.h
A few parameters and step renumberings have happened since we first
implemented this algorithm.
Also add some scaffolding and cleanup to other classes to make the implementation easier.
> LibWeb: Update Navigable::navigate() to the current state of the spec

- Userland/DevTools/HackStudio/Git/GitWidget.cpp
Change the foreground color of staged and unstaged file list in the git tab to green and red respectively
> HackStudio: Change fg color of staged/unstaged file list in Git tab

- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.replace.js
When a substitution refers to a 2-digit capture group that doesn't exist we need to check if the first digit refers to an existing capture group. In other words, '$10' should be treated as capture group #1, followed by the literal '0' if 1 is a valid capture group but 10 is not.
This makes the Dromaeo "dom-query" subtest run to completion.
> LibJS: Behave like major engines when substituting missing capture group

- Tests/LibC/CMakeLists.txt
- Tests/LibC/TestLibCNetdb.cpp
- Userland/Libraries/LibC/netdb.cpp
- Userland/Libraries/LibC/netdb.h
These patches make `getaddrinfo()` MT-Safe by:
1. Implementing and making use of `gethostbyname_r()`, as the former implementation of `getaddrinfo()` used `gethostbyname()` which isn't MT-Safe.
2.  Removing dependency of `getservbyname()` in `getaddrinfo()`, which now gets the required information by searching the `/etc/services`  file.
Some test cases are also added for both `gethostbyname_r()` and `getaddrinfo()`.
This closes issue #7686
> LibC: Make getaddrinfo() MT-Safe

- Tests/LibWeb/Layout/expected/grid/auto-flow-column-spanning-item.txt
- Tests/LibWeb/Layout/input/grid/auto-flow-column-spanning-item.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
We need to start looking from the beginning of current row if adding new implicit column track made enough space to accomodate spanning item
This fixes placement for spanning grid items when `grid-auto-flow` is specified to `column`.
> LibWeb: Reset auto_placement_cursor_x after adding new column in GFC

- Tests/LibWeb/Layout/expected/dont-crash-on-relayout-that-rewraps-text.txt
- Tests/LibWeb/Layout/input/dont-crash-on-relayout-that-rewraps-text.html
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
When text paintables shift around in the tree due to line wrapping, we may end up in a situation where some text node does not generate a paintable (due to being all whitespace, for example), even though in the previous layout pass, it *did* generate a paintable.
To prevent holding on to old paintables in such cases, we now do a pass in LayoutState::commit() where we explicitly detach all old paintables from the layout tree.
> LibWeb: Prune old paintable pointers from layout tree after relayout

- Userland/Utilities/find.cpp
For example: `find . -group -1` will now result in an error being displayed. Previously the negative number was converted to unsigned and treated as valid.
Note: the above command would succeed in theory if you had a group called '-1', but the `groupadd` comand doesn't currently allow you to create such a group.
> find: Don't allow negative GIDs to be passed to the `-group` option

- Userland/Libraries/LibWeb/HTML/EventLoop/Task.h
Also add a separator to make it clearer that it must remain last.
> LibWeb: Move the unique task source start to be last in `Task::Source`

- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Tests/builtins/Array/array-spread.js
- Userland/Libraries/LibJS/Tests/object-spread.js
See: https://tc39.es/ecma262/#sec-runtime-semantics-propertydefinitionevaluation
PropertyDefinition : ... AssignmentExpression
Also add a test for this in array spreading, which already had this in place.
> LibJS: Allow assignment expression in spreading property definition

- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Tests/object-spread.js
This is not we're supposed to do according to https://tc39.es/ecma262/#sec-runtime-semantics-propertydefinitionevaluation
Furthermore, this was observable by ToPrimitive looking up toString and
valueOf and potentially calling them if they exist. The big ticket
issue however is that for objects without toString and valueOf, such as
null-proto objects, this would unexpectedly throw.
> LibJS: Avoid ToPropertyKey for spreading in PutByValue(WithThis)

- Userland/Applications/Browser/Database.cpp
- Userland/Applications/Browser/Database.h
All SQL callbacks here were already moving the to-be-executed callback out of its storage before executing it, except for on_next_result(). This makes on_next_result() do the same move to ensure we do not later attempt to move it while the callback is executing.
> Browser: Prevent moving a Database callback while it is executing

- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/Console.h
- Ladybird/AppKit/UI/Console.mm
- Ladybird/AppKit/UI/ConsoleController.h
- Ladybird/AppKit/UI/ConsoleController.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/Tab.h
- Ladybird/AppKit/UI/Tab.mm
- Ladybird/AppKit/UI/TabController.mm
- Ladybird/CMakeLists.txt
- Ladybird/Qt/ConsoleWidget.cpp
- Ladybird/Qt/ConsoleWidget.h
- Ladybird/Qt/Tab.cpp
- Meta/Lagom/CMakeLists.txt
- Userland/Applications/Browser/ConsoleWidget.cpp
- Userland/Applications/Browser/ConsoleWidget.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWebView/CMakeLists.txt
- Userland/Libraries/LibWebView/ConsoleClient.cpp
- Userland/Libraries/LibWebView/ConsoleClient.h
- Userland/Libraries/LibWebView/Forward.h
This extracts the console functionality that is currently doubly implemented in the Serenity and Qt chromes (some of which the Qt chrome is missing) into a `WebView::ConsoleClient` class. This class handles all of the JS execution and message receiving, letting the chromes focus solely on their UI.
Then this adds such a UI to the AppKit chrome :^)
> Ladybird: Implement a JavaScript console for the AppKit chrome

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
Currently doesn't handle the mouse leaving and entering the window per the spec, and uses clientX/Y instead of screenX/Y. See FIXMEs.
> LibWeb: Partially implement MouseEvent.movementX/movementY

- Base/home/anon/.config/FileManager.ini
- Userland/Applications/FileManager/main.cpp
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGUI/Window.h
I have added the three functions to `LibGUI::Window`. You can use this function to easily save and restore the window state of your application:
```cpp
void restore_size_and_position(StringView domain, StringView group = "Window"sv, Optional<Gfx::IntSize> fallback_size = {}, Optional<Gfx::IntPoint> fallback_position = {});
void save_size_and_position(StringView domain, StringView group = "Window"sv) const;
void save_size_and_position_on_close(StringView domain, StringView group = "Window"sv);
```
You can use the `restore` and `save` functions to easily restore the window state from config. The `save_size_and_position_on_close` can be called when the window is initializing, it sets some state that when the window is closed the current window state is saved to config. This is a small …
> LibGUI: Add window remember state feature

- Userland/Libraries/LibWebView/ConsoleClient.cpp
- Userland/Libraries/LibWebView/ConsoleClient.h
If we set m_waiting_for_messages to true for the intial message request, we might never receive a response, and block the console from requesting any more messages indefinitely. Instead, issue a non-blocking initial request, which is how the Qt and Serenity chromes behaved before the ConsoleClient abstraction.
This also changes ConsoleClient::clear() to use run_javascript() rather than js_console_input(), as that is also how the chromes used to behave.
> LibWebView: Do not block the console for the initial message request

- Tests/LibWeb/Layout/expected/acid1.txt
- Tests/LibWeb/Layout/expected/block-and-inline/small-percentage-margin.txt
- Tests/LibWeb/Layout/input/block-and-inline/small-percentage-margin.html
- Userland/Libraries/LibWeb/CSS/PercentageOr.cpp
- Userland/Libraries/LibWeb/CSS/PercentageOr.h
- Userland/Libraries/LibWeb/CSS/Size.cpp
- Userland/Libraries/LibWeb/CSS/Size.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Since we always pass the px value as an argument to resolved(), we can pass it directly as CSSPixels instead of wrapping it in Length. This approach allows us to avoid converting to a double, resulting in fewer precision issues.
> LibWeb: Add `Length::resolved()` overload for CSSPixels

- Tests/LibWeb/Ref/border-radius-shrink-zero-sized-box-ref.html
- Tests/LibWeb/Ref/border-radius-shrink-zero-sized-box.html
- Tests/LibWeb/Ref/manifest.json
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
This class will allow us to compare the ratio of two `CSSPixels` values losslessly.
Not only that, but an operation like `a * (b / c)` should no longer be lossy, since the operation can be implicitly carried out as `(a * b) / c` instead. This part is demonstrated by adding parentheses to a calculation in `FormattingContext::solve_replaced_size_constraint()` to cause it to make use of the new `operator*(CSSPixels, CSSPixelFraction)`.
-------
This was created specifically to allow the changes that were initially implemented by @MacDue in the now-closed https://github.com/SerenityOS/serenity/pull/20759 to be done losslessly, rather than converting to and from floating point.
-------
Also included is a change to make `FormattingContext` use the new multiply-by-fraction mentioned above, …
> LibWeb: Add a CSSPixelFraction class to allow comparison of fractions

- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
> LibWeb: Create IdentifierStyleValue for fit-content size declarations

- Userland/Applications/Mail/InboxModel.cpp
- Userland/Applications/Mail/InboxModel.h
- Userland/Applications/Mail/MailWidget.cpp
- Userland/Applications/Mail/MailWidget.h
- **Mail: Fetch mails with their sequence number**
The FETCH response doesn't have return the sequence in order, or at very least one of my mail providers doesn't do it.
- **Mail: Get message date using INTERNALDATE**
Parsing mail headers and its date format is a rather tedious task, especially if you want to support the obsolete syntax <sup>([trust me](https://gist.github.com/krkk/4621cff3522e842643eb75874ab67477))</sup>, so let's ask the server to do it for us!
This will convert the date to our local time and display it in a sortable and fixed-width format "%Y-%m-%d %H:%M:%S".
- **Mail: Make Date the first column**
- **Mail: Use set_activates_on_selection and on_activation callback**
Preparation for a sortable mailbox. Otherwise the model would resort itself and select mail again …
> Mail: Allow sorting columns (plus some cleanup)

- Kernel/Devices/Device.h
- Kernel/FileSystem/DevPtsFS/FileSystem.cpp
- Kernel/TTY/MasterPTY.cpp
- Kernel/TTY/SlavePTY.cpp
- Kernel/TTY/SlavePTY.h
No other device needs to store the UID/GID of the process that created them, so only store these values within the SlavePTY class.
> Kernel: Move m_uid and m_gid from the Device class to SlavePTY

- Tests/LibWeb/Layout/expected/block-and-inline/html-element-height-quirks-mode-off.txt
- Tests/LibWeb/Layout/expected/block-and-inline/html-element-height-quirks-mode-on.txt
- Tests/LibWeb/Layout/expected/viewport-overflow-propagation-2.txt
- Tests/LibWeb/Layout/input/block-and-inline/html-element-height-quirks-mode-off.html
- Tests/LibWeb/Layout/input/block-and-inline/html-element-height-quirks-mode-on.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Previously we always set the height of the HTML element equal to the viewport height but now this will only happen in quirks mode as it is intended. Otherwise the html element height will be computed as auto.
> LibWeb: Bring html element height calculation closer to the spec

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
We now have functions for parsing integers in an HTML spec-compliant way. This PR gets rid of two FIXME comments.
> LibWeb: Improve spec alignment around integer parsing

- Tests/LibWeb/Ref/clip-ref.html
- Tests/LibWeb/Ref/clip.html
- Tests/LibWeb/Ref/manifest.json
- Userland/Libraries/LibWeb/CSS/EdgeRect.cpp
- Userland/Libraries/LibWeb/CSS/EdgeRect.h
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
https://github.com/SerenityOS/serenity/commit/d06d4eb388bfeb8c20c14c23d9da78c8c43ce85f made the `clip` property apply to children of an absolute-positioned element, but caused it not to be applied to the element the property was applied to directly.
To fix this, apply the clip in new `before_paint()` and `after_paint()` functions. Doing so keeps painter state from leaking from `paint()`, but still allows subclasses of `PaintableBox` clip their contents correctly without repeating the application of the clip rectangle.
In addition to that change, I've made the CSS `rect` representation not convert to floating point so that we can avoid converting it back to CSSPixels again in the painter.
> LibWeb: Apply CSS `clip` property to an element as well as its children 

- Userland/Libraries/LibCore/EventReceiver.cpp
If stop_timer() is called from ~EventReceiver(), then the virtual functions will end up calling the overload from the base class. As EventReceiver::class_name() is pure virtual, this calls __cxa_pure_virtual and crashes. We should not be calling virtual functions from the destructor, and especially not pure virtual ones.
This "fixes" a crash in Piano, but the root cause of the problem is still unfixed.
Related to #20513
The root cause in Piano is not this virtual though. As I noted in the issue, we start a Core::Timer in the AudioPlayerLoop's secondary thread, and stop it in the main thread. This doesn't actually work because timers are registered per-thread.
We should probably add some asserts to make sure you don't try to do this, and figure out why we are starting a timer but not …
> LibCore: Don't print class_name() from EventReceiver::stop_timer()

- Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.h
There is only one, width/height -> aspect-ratio. This brings us very slightly closer to spec and triggers a re-layout after updating these values from JavaScript, which wasn't the case before.
Here, I used the width() and height() values exposed by HTMLCanvasElement, which convert the strings to unsigned integers using `to_uint()` and provides default to values of 300x150, I am not sure however this if meets the [spec rules for parsing non-negative integers](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#rules-for-parsing-non-negative-integers), if this is a concern I will correct it.
> LibWeb: Add presentation hints to the canvas element

- AK/Assertions.cpp
- AK/Assertions.h
- Meta/Lagom/CMakeLists.txt
On platforms that support it, enable using ``<execinfo.h>`` to get backtrace(3) to dump a backtrace on assertion failure. This should make debugging things like WebContent crashes in Lagom much easier.
> AK: Always use our assertion failure method, and add backtrace to it

- Documentation/BuildInstructionsOther.md
- Toolchain/.gitignore
- Toolchain/flake.lock
- Toolchain/flake.nix
- Toolchain/serenity.nix
Add a nix flake to `Toolchain/` that wraps the existing nix derivation
`Toolchain/serenity.nix`. This also comes with a lockfile making the nix
developer enviornment setup more reproducible.
We also update the documentation for "other builds" to mention the
flake.
xlibswrapper is removed from `Toolchain/serenity.nix` as it is a
wrapper package and has been deprecated. We don't use it in the build
anyway.
This fixes https://github.com/SerenityOS/serenity/issues/19286
During the build, python3 is required so we add `python3` as a build
dependency.
> Toolchian: Add nix flake; Fix nix build deps

- Tests/LibWeb/Layout/expected/flex/br-element-does-not-get-blockified-by-itself.txt
- Tests/LibWeb/Layout/input/flex/br-element-does-not-get-blockified-by-itself.html
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/HTML/HTMLBRElement.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Two issues here:
- `<br>` elements should never be blockified.
- Multiple consecutive inline-level children of flex containers should be collected into a single anonymous wrapper.
Visual progression on https://lillanapoli.se/
Before:
After:
> LibWeb: Two fixes for inline children of flex containers

- Tests/Kernel/TestEmptyPrivateInodeVMObject.cpp
- Tests/Kernel/TestEmptySharedInodeVMObject.cpp
- Tests/Kernel/TestPrivateInodeVMObject.cpp
- Tests/Kernel/TestSharedInodeVMObject.cpp
- Tests/Kernel/elf-execve-mmap-race.cpp
- Tests/Kernel/mmap-write-into-running-programs-executable-file.cpp
- Tests/LibC/TestIo.cpp
- Userland/Libraries/LibCore/AnonymousBuffer.cpp
- Userland/Libraries/LibELF/DynamicLoader.cpp
MAP_FILE is not in POSIX, and is simply in most LibCs as a "default" mode. Our own LibC defines it as 0, meaning "no flags". It is also not defined in some OS's, such as Haiku. Let's be more portable and not use the unnecessary flag.
> Userland+Tests: Don't use MAP_FILE when mmap-ing

- Userland/Libraries/LibAudio/FlacTypes.h
> LibAudio: Fix uncommon 16-bit block size symbol

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
These return true if the last modification time, last access time or creation time of a file is greater than the given reference file.
If the `-L` option is in use and the given reference file is a symbolic link then the timestamp of the file pointed to by the symbolic link will be used.
Example usage:
> find: Add the `-newer`, `-anewer` and `-cnewer` options

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
This returns true for empty regular files or directories.
Example usage:
> find: Add the `-empty` option

- Userland/Libraries/LibWeb/DOM/Attr.cpp
- Userland/Libraries/LibWeb/DOM/Attr.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
These are a bit different than the existing `get/set_attribute`, and are meant to be used by our `Reflect` implementation. These are not used here, but just making a PR for @alimpfard.
> LibWeb: Define getting and setting an attribute value

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/Error.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
- Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Tests/builtins/Error/Error.prototype.stack.js
- Userland/Utilities/js.cpp
This works by adding source start/end offset to every bytecode instruction. In the future we can make this more efficient by keeping a map of bytecode ranges to source ranges in the Executable instead, but let's just get traces working first.
> LibJS: Add file & line number to bytecode VM stack traces :^)

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
I am not sure on how to write tests for this given that this requires user interaction, ideas on how to do this welcome!
> LibWeb: Support `readonly` attribute for HTMLInputElement

- Userland/Applications/About/CMakeLists.txt
A tiny little change 🐭
Before, when looking in `/bin` in File Manager, the About application's icon was missing. Now that it's a `serenity_app` instead of `serenity_bin` the icon is visible!
**Before:**
**After:**
> About: Display Application's Icon in File Manager

- Userland/Libraries/LibC/assert.cpp
- Userland/Libraries/LibC/unistd.cpp
- Userland/Libraries/LibELF/DynamicLinker.cpp
The arguments are passed on registers, so if we pass only 3 defined arguments then the fourth argument for the prctl syscall could have garbage value within it.
To avoid possible bugs, always pass 3 arguments to a raw syscall prctl call in addition to the prctl option.
This was found after I looked on my patches in #20666 and realized that raw prctl calls are used in the codebase.
> Userland: Always call syscall(SC_prctl, ...) with 4 arguments

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
Instead of trying to keep a live reference to the bytecode interpreter's current instruction stream iterator, we now simply copy the current iterator whenever pushing to the ExecutionContext stack.
This fixes a stack-use-after-return issue reported by ASAN.
> LibJS: Only update EC instruction pointer when pushing to EC stack

- Userland/Libraries/LibWeb/DOM/Attr.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
The goal here is to consolidate all attribute change handling in a single location, as doing so was missed when adding a new attribute setter method in 720f7ba7463c67fe205cedfce7bde6a6ba3b14c8. To actually work though, this brings in a normative DOM spec change to ensure we fire the change handlers *after* the attribute is actually changed. This also lets us implement some attribute setters closer to the spec overall.
> LibWeb: Invoke our internal attribute change handler from Attr

- Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
We would start the timer to send playback time updates to the element before playback had started, so in cases where the `HTMLMediaElement` (incorrectly) creates both an `AudioTrack` and `VideoTrack`, it will not cause the seek bar to flicker between the current video position and zero.
> LibWeb: Don't send audio time updates until audio is playing

- AK/Assertions.cpp
While macOS backtrace(3) puts a space directly after the mangled symbol name, some versions of glibc put a + directly after it. This new logic accounts for both situations when trying to demangle.
> AK: Demangle symbols on assertion failure on Linux as well

- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.idl
This makes https://null.com/ load instead of throwing a React internal error and showing a black background.
> LibWeb: Stub out HTMLDialogElement APIs

- Userland/Libraries/LibC/limits.h
All supported targets use an LP64 ABI, where both `long` and `long long` are 64 bits wide.
We might consider using built-in macros to avoid such issues in the future.
> LibC: Set `(U)LONG_WIDTH` correctly for 64-bit

- Tests/LibWeb/Layout/expected/block-and-inline/button-baseline-align.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-image-only.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-should-have-vertically-aligned-content.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-abspos-pseudo-element.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-block-content-baseline-align.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label-and-font-size.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
- Tests/LibWeb/Layout/expected/table/table-cell-not-paintable.txt
- Tests/LibWeb/Layout/input/block-and-inline/button-with-abspos-pseudo-element.html
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Using flex layout inside button solves the issue with wrongly calculated
height when it has: pseudo element and whitespaces inside.
Also using flex instead of a table layout allows for the same vertical
alignment but with fewer layout nodes: a flex container and anonymous
wrapper for content instead of a table wrapper, table, row, and cell.
> LibWeb: Use flex layout for button content alignment

- Userland/Libraries/LibCore/MimeData.cpp
This allows opening the WPT .xht files directly with ladybird.
> LibCore: Recognize .xht as an HTML document

- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h
> LibGfx: Remove maximum size limit for decoded images 

- Tests/LibWeb/Layout/expected/flex/abspos-flex-child-with-auto-height.txt
- Tests/LibWeb/Layout/input/flex/abspos-flex-child-with-auto-height.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
There's a particularly awkward case where the static position of an abspos child of a flex container is dependent on its height. This can happen when `align-items: center` is in effect, as we have to adjust the abspos child's Y position by half of its height.
This patch solves the issue by reordering operations in the abspos height resolution algorithm, to make sure that height is resolved before the static position is calculated.
Visual progression on https://null.com/
Before:
After:
> LibWeb: Handle case where abspos flex child position depends on height

- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.h
We should not GC allocate in the constructors of GC-allocated objects because a new allocation might trigger garbage collection, which in turn might access not fully initialized objects.
> LibWeb: Remove GC allocations in FetchAlgorithms constructor

- Meta/CMake/serenity_compile_options.cmake
We currently only use frame pointer-based backtrace generation.
This option is necessary for RISC-V as otherwise the compiler doesn't save `fp` most of the time.
I made this flag not riscv64 exclusive, as we should do everything to make that kind of backtrace generation work.
See [this discussion](https://discord.com/channels/830522505605283862/1139481927594803260/1148020960499351643) for reference.
> Meta: Add `-fno-omit-frame-pointer` flag

- Userland/Libraries/LibWasm/WASI/Wasi.cpp
- Userland/Libraries/LibWasm/Wasi.h
This makes it so we don't rely on e.g. u64 to have an 8-byte alignment, fixing breakage on i686 systems.
> LibWasm: Explicitly place the paddings in the WASI API types

- Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
- Tests/LibWeb/Layout/expected/grid/image-in-grid.txt
- Tests/LibWeb/Layout/expected/replaced-within-max-content.txt
- Tests/LibWeb/Layout/input/replaced-within-max-content.html
- Userland/Libraries/LibWeb/CSS/Ratio.h
- Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.cpp
- Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.h
- Userland/Libraries/LibWeb/HTML/DecodedImageData.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
- Userland/Libraries/LibWeb/Layout/Box.cpp
- Userland/Libraries/LibWeb/Layout/Box.h
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/ImageProvider.h
- Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
- Userland/Libraries/LibWeb/Layout/SVGSVGBox.h
- Userland/Libraries/LibWeb/Layout/VideoBox.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
This fixes a crash on https://varberg.se/, a site I was pointed to by @kalenikaliaksandr. There is an `<img>` element for the top left logo with a `min-width` set and a `src` of an SVG with no intrinsic sizing, which is contained within an element with `float: left`. That containing element would attempt to lay out its children to determine the maximum content width, but the `<img>` element has no intrinsic size, so the tentative size would be undefined by spec and would default to zero in our implementation for both dimensions. We would then use those tentative size to calculate an aspect ratio to maintain in the sizes that resolve the sizing constraints of the element, but since the tentative size is zero in both dimensions, that would result in a division by zero.
To fix this, let's …
> Aspect ratio fixes

- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateNumberFormatData.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.format.js
- Userland/Libraries/LibLocale/NumberFormat.h
When formatting a currency style pattern with compact notation, we were
(trying to) doubly insert the currency symbol into the formatted string.
We would first look up the currency pattern in GetNumberFormatPattern
(for the en locale, this is "¤#,##0.00", which our generator transforms
to "{currency}{number}").
When we hit the "{number}" field, NumberFormat will do a second lookup
for the compact pattern to use for the number being formatted. By using
the currency compact patterns, we receive a second pattern that also has
the currency symbol (for the en locale, if formatting the number 1000,
this is "¤0K", which our generator transforms to
"{currency}{number}{compactIdentifier:0}". This second lookup is not
supposed to have currency symbols (or any other symbols), thus we hit a …
> LibJS: Use decimal compact patterns for currency style sub-patterns

- Ladybird/AppKit/main.mm
- Ladybird/Qt/main.cpp
- Userland/Applications/Browser/main.cpp
This is never meant to be passed by a human, it is created and passed by WebDriver only. Hide it from the --help menu to avoid confusion.
> Ladybird: Hide the WebDriver-to-WebContent IPC path from the help menu

- Tests/LibWeb/Layout/expected/font-size-zero.txt
- Tests/LibWeb/Layout/expected/table/table-fixup-font-size-and-line-height.txt
- Tests/LibWeb/Layout/input/font-size-zero.html
- Tests/LibWeb/Layout/input/table/table-fixup-font-size-and-line-height.html
- Userland/Libraries/LibGfx/Font/Typeface.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Allow `font-size: 0px` since that's a valid value.
- Propagate `font-size` (and `line-height` too!) to generated table boxes.
Visual progression on https://varberg.se/
Before:
After:
> LibWeb: Two CSS font-size fixes for varberg.se

- AK/FlyString.cpp
- AK/FlyString.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSValueID.cpp
- Tests/LibWeb/Ref/css-attr-basic.html
- Tests/LibWeb/Ref/css-attr-fallback.html
- Tests/LibWeb/Ref/css-attr-ref.html
- Tests/LibWeb/Ref/css-attr-typed-fallback.html
- Tests/LibWeb/Ref/css-attr-typed-ref.html
- Tests/LibWeb/Ref/css-attr-typed.html
- Tests/LibWeb/Ref/manifest.json
- Userland/Libraries/LibWeb/CSS/Parser/Function.h
- Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Parser/Token.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
This lets you specify what type to parse the attribute's contents as. For example, this HTML (from a new test):
```html
<!doctype html>
<style>
div {
width: 100px;
height: 20px;
border: 1px solid black;
}
.string::before {
content: attr(foo string);
}
.length {
width: attr(foo length);
}
.px {
width: attr(foo px);
}
.color {
background-color: attr(foo color);
}
</style>
<div class="string" foo="WHF!"></div>
<div class="length" foo="200px"></div>
<div class="px" foo="200"></div>
<div class="color" foo="lime"></div>
<div class="color" foo="#00ff00"></div>
```
...looks like this!
Can't currently compare this with any other browsers, because [they don't support it](https://caniuse.com/?search=attr()). :buffie:
> LibWeb: Implement attr() types :^)

- Userland/Applications/Calendar/AddEventDialog.cpp
- Userland/Applications/Calendar/EventCalendar.cpp
This PR introduces the ability to save calendar event time and adds functionality for displaying saved times in the calendar. Additionally, it addresses the issue where changes to the time value in the dropdown were not being saved.
> Calendar: Save time of the event and display it in Calendar

- Ladybird/CMakeLists.txt
Building Ladybird is currently broken on Solaris and FreeBSD (both confirmed) and probably also all other platforms (not confirmed) due to #20955 adding a include(use_linker) into the CMakeLists.txt above configuring the include directories.
This change moves the line after setting the CMAKE_MODULE_PATH and fixes the Cmake error message for me on both Solaris and FreeBSD.
> Ladybird: Fix the include of use_linker in CMakeLists.txt

- AK/Random.h
All BSD/Unix-derived operating systems, including Solaris and MacOS, support the arc4random_buf() function.
When doing my big Haiku pull request (#20808), it was suggested that this is the preferred way to get random data, since the other way with getentropy() is called a "fallback" in the code.
I tested this change on Solaris and FreeBSD and it works as expected here.
I can't test on MacOS but the documentation says that it works the same way there.
I also can't test OpenBSD and NetBSD as building is currently broken on them (Clang 13 on OpenBSD is too old and NetBSD lacks the qt6-qtmultimedia package), but again the documentation says that it works the same way there.
> AK: Use arc4random_buf() for Random on all BSDs

- AK/Assertions.cpp
- AK/Platform.h
- AK/Random.h
- AK/StackInfo.cpp
- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibFileSystem/FileSystem.cpp
- Userland/Libraries/LibTimeZone/TimeZone.cpp
* get rid of not one, but two `PATH_MAX` usages 🎉
* note: `realpath(..., nullptr)` used to be a glibc extension, but it's in POSIX now, so we should be able to just use it
* enable `arc4random_buf()` on recent glibc versions
* gate some things that are glibc-specific, not Linux-specific, on the new `AK_LIBC_GLIBC`
This is in preparation for adding support for a certain OS that uses glibc, but not Linux 😉
> glibc-related improvements

- Userland/Libraries/LibMarkdown/Text.cpp
Absolute paths in man page links such as
```
[some link](/foo/bar)
```
Were being interpreted as relative paths when rendered in HTML. This issue was observed in #20889 and #20041.
The fix is to make sure we don't leave any absolute paths when parsing links. Instead we check if a directory is absolute (by checking for `/`) and add `file://` accordingly. This turns the above link into:
```
[some link](file:///foo/bar)
```
Which does get interpreted correctly when rendered as HTML.
- fixes #20889
- fixes #20041
Before this patch, opening the Help application would raise an error. Now all the pictures in the man pages render correctly.
> Userland: Fix absolute paths in man page links

- Ladybird/Android/build.gradle.kts
- Meta/Azure/Lagom.yml
- Meta/Azure/Setup.yml
Also run the APK in the android simulator to make sure we can actually boot the thing.
> Meta: Run Android CI via gradle wrapper instead of via CMake

- AK/Platform.h
- Tests/LibJS/test262-runner.cpp
- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibCore/Socket.cpp
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibDNS/Answer.cpp
- Userland/Libraries/LibELF/Validation.cpp
- Userland/Libraries/LibTest/CrashTest.cpp
- Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
- Userland/Services/LookupServer/MulticastDNS.h
- Userland/Utilities/ntpquery.cpp
[GNU Hurd](https://www.gnu.org/software/hurd/) is the GNU project's kernel (actually a microkernel system on top of Mach). Contrary to the popular belief, the Hurd is not dead, not a failure, and works very well 😄
GNU/Hurd is the GNU operating system using Hurd as its kernel (just like GNU/Linux and GNU/kFreeBSD). It is the very same system as GNU/Linux, except for the kernel which is Hurd and not Linux. In particular GNU/Hurd is too built with the GNU toolchain (GCC & binutils), is too using glibc (everyone's favorite libc!), Bash, Nano, and all the other GNU (and non-GNU) software.
So, since Lagom has already been ported to GNU/Linux and doesn't really do much of kernel-specific things such as direct syscalls, one would think that it would just build & work on the Hurd. That is true to …
> Port Lagom to GNU/Hurd :^)

- Documentation/BuildInstructionsLadybird.md
The path to the ladybird executable in the documentation in `BuildInstructionsLadybird.md` was outdated after some build files had been moved around.
> Documentation: Fix Ladybird executable path in `BuildInstructionsLadybird.md`

- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
Before page_did_create_main_document() only initialized ConsoleClient for top-level browsing context which means that nested browsing context could not print into the console.
With this change, ConsoleClient is initialized for documents created for nested browsing context too. One ConsoleClient is shared between all browsing contexts within the same page.
> LibWeb+WebContent: Set ConsoleClient for nested browsing contexts

- Userland/Shell/Builtin.cpp
- Userland/Shell/Shell.cpp
- Userland/Shell/Shell.h
This allows the prompt to be dynamically configurable, making it possible to display various bits of information in the prompt.
I'm personally quite fond of this now:
<details><summary>Expand for demo</summary>
```sh
blue="\x1b[34m"
green="\x1b[32m"
purple="\x1b[35m"
red="\x1b[31m"
bold="\x1b[1m"
reset="\x1b[0m"
gitq() {
if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = true ] {
x='@'
if not git diff --quiet {
x='*'
}
echo -n " $x$purple$(git branch --show-current)$reset on $blue$(git rev-parse --show-toplevel)$reset"
}
}
PROMPT() {
echo -n <<~PROMPT
$bold$green-- prompt at $(date +%H:%M:%S)$reset$(gitq)
[$blue$(whoami)$reset@$green$(hostname)$reset] $purple$(pwd)$reset
$blue❯ $reset
PROMPT
}
```
which looks something like this:
</details>
> Shell: Allow the user to set the prompt using PROMPT()

- Kernel/Arch/riscv64/SBI.cpp
- Kernel/Arch/riscv64/SBI.h
- Kernel/CMakeLists.txt
This PR adds a simple interface (which uses a namespace per SBI extension) for the RISC-V Supervisor Binary Interface (SBI).
This will later be needed for printing messages and setting up timer interrupts.
This is my first C++ contribution to this project, so I hope that I followed your code style correctly.
I am also not *that* happy with how the code turned out (one file with multiple namespaces), but I honestly think it's the best solution.
> Kernel/riscv64: Add basic SBI support

- Ladybird/Android/BuildLagomTools.sh
- Ladybird/Android/build.gradle.kts
- Meta/find_compiler.sh
- Meta/serenity.sh
This lets us select a proper host compiler version if cc/cxx are not
suitable for building Lagom.
> Ladybird: Move host build into its own shell script 

- Userland/Libraries/LibWeb/CSS/Default.css
- Userland/Libraries/LibWeb/DOM/Text.cpp
- Userland/Libraries/LibWeb/DOM/Text.h
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
This makes `<textarea>` actually editable by giving it a shadow tree. It's still lacking a lot but it's still a step forward and I've just been distracted by a CSS feature that would make the `rows` and `cols` attributes a lot nicer to implement, so submitting this now.
> LibWeb: Flesh out HTMLTextAreaElement

- Userland/Libraries/LibGfx/Point.h
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Length.cpp
- Userland/Libraries/LibWeb/CSS/Position.cpp
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
This is the first in a possible series of PRs to remove unnecessary usages of things like `CSSPixels(float)` and `CSSPixels::nearest_value_for()`. Thus far, I haven't observed any actual changes in test pages that I've examined with these changes applied.
As an extra little change, calculating a radial gradient's size should call `sqrt()` less often, since it was previously using actual distances instead of squared distances to compare.
> LibWeb: Reduce `CSSPixels` -> `float` round trips

- Tests/LibWeb/Layout/expected/textarea-content.txt
- Tests/LibWeb/Layout/input/textarea-content.html
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
If an element is created from JS, it might have its contents modified before it is inserted into the document. In this case, we don't have a shadow tree yet and so trying to set m_text_node's text content would cause a null dereference. So let's not do that. :^)
That case also means that by the time we do create the shadow tree, we have the text content already, so we can set it there.
Added a test to verify that we don't crash, and that the text content appears in the textarea whether it was inserted by JS or by the HTML parser.
Fixes #20993.
> LibWeb: Stop crashing when textarea element is modified before insertion

- Documentation/BuildInstructionsOther.md
Corrected link to point to 'flake.nix' rather than 'serenity.nix'.
> Correct link in BuildInstructionsOther.md

- Tests/LibWeb/Layout/expected/block-and-inline/float-should-avoid-inline-block.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-should-avoid-inline-block.html
- Userland/Libraries/LibWeb/Layout/LineBox.cpp
- Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Before, we were using the line height from NodeWithStyle::line_height()
to calculate the y offset for floats inside the IFC. However, this
value doesn't always correspond to the actual height of a line box. For instance, adding a fragment for an inline-block might change the height of the line box. With this change, we recalculate the height of the line box after adding a new fragment and use this recalculated height value to determine the y position for floats.
Fixes https://github.com/SerenityOS/serenity/issues/20982
> LibWeb: Use actual line height to calculate float y in IFC

- Kernel/Devices/GPU/Console/Console.h
- Kernel/Devices/GPU/Console/GenericFramebufferConsole.cpp
- Kernel/Devices/GPU/Console/GenericFramebufferConsole.h
- Kernel/Devices/GPU/Console/VGATextModeConsole.cpp
- Kernel/Devices/GPU/Console/VGATextModeConsole.h
The current implementation handles newlines but simply wraps back up to the top if it reaches the bottom end of the console, creating some very unreadable messages if we get a panic while booting and looking at the debug console, like this:
I choose to move the new line handling and  handle the scrolling in `write(char ch, bool critical)` because:
1. Currently it's the only overload that's ever called with `critical = true` and
2. I don't think that anything that writes to a specific x and y would want the console to potentially scroll
> Kernel: Implement scrolling for critical messages in `VGATextConsole` and `GenericFramebufferConsole`

- Base/usr/share/man/man7/sys.md
There's no constants directory anymore under /sys/kernel, so bring all the described nodes back to the "kernel" directory entries list.
Also, the /sys/kernel/variables directory was renamed to /sys/kernel/conf so let's fix this as well.
> Base: Fix sys(7) manual page

- Ladybird/Android/src/main/AndroidManifest.xml
- Ladybird/Android/src/main/cpp/WebContentService.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentService.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentServiceConnection.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebView.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebViewImplementation.kt
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/cmake/InstallRules.cmake
This will let us spawn a new process for an Android Service to handle all our WebContent needs. The ServiceConnection is manged by each WebView. The lifecycle of the Service is not quite clear yet, but each bindService call will get a unique Messenger that can be used to transfer the WebContent side of the LibIPC socketpair we use in other ports.
> Ladybird: Add WebContentService for Android port

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
> find: Add `!` operator to negate the following command

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
The presence of this prefix denotes that the value being tested is strictly greater than or less than the given numeric value.
Example usage:
> find: Allow '+' and '-' prefix for `-links` and `-size` options

- Userland/Applications/Mail/MailWidget.cpp
- Userland/Libraries/LibIMAP/Objects.h
- Userland/Libraries/LibIMAP/Parser.cpp
Overall we weren't parsing `body-ext-1part` for any mime type but `text/`, and parsing steps for `message/rfc822` were incomplete.
---
Mail no longer crashes when trying to view following emails:
<table><tr><td>
```eml
MIME-Version: 1.0
Date: Sun, 3 Sep 2023 00:00:00 +0200
Subject: transparent png
Content-Type: image/png
Content-Transfer-Encoding: base64
iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAA
AABJRU5ErkJggg==
```
<td>
```eml
MIME-Version: 1.0
Date: Sun, 3 Sep 2023 01:32:21 +0200
Subject: email in email what!!
Content-Type: message/rfc822
Date: Sun, 3 Sep 2023 00:00:00 +0200
Subject: Subject Subject
:^)
```
</table>
> LibIMAP: Don't crash on mails with attachments

- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/AST.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/AST.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/ASTPrinting.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/CMakeLists.txt
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/FunctionCallCanonicalizationPass.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/FunctionCallCanonicalizationPass.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/GenericASTPass.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/GenericASTPass.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/IfBranchMergingPass.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/IfBranchMergingPass.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Forward.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/TextParser.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/TextParser.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
I don't want to overcomplicate already complicated enough expression parser, so there is some cleanup needed to make function calls nice to work with. Additionally, if-elseif-else chains also need some love after parsing.
> JSSpecCompiler: Add our first two passes :^)

- AK/StdLibExtraDetails.h
Someone requested this over on Discord.
This is a port of [`rstd::core::cxxstd::invoke_result_t`](https://github.com/bugaevc/rstd/blob/25d9f4a1fe4dbb5828334350e99243cb8df3ff9e/include/rstd/core/cxxstd.hpp#L56-L79), except it's simpler because it doesn't do the `forward`'ing. Based on a conversation with @alimpfard, this is because our `declval<T>()` returns `T`, not `T&&`. Based on some research, _that_ in turn is because returning `T` wouldn't work pre-C++17, which STL and rstd support, but AK does not have to.
> Add AK::InvokeResult

- Documentation/BuildInstructionsLadybird.md
- Toolchain/flake.nix
Add another nix dev shell to `Toolchain/flake.nix` called `ladybird.nix` that pulls in the dependencies for building Ladybird.
Also update the documentation to mention building with a flake.
I've tested this and I am able to build and run Ladybird.
> Ladybird: Add ladybird.nix to nix flake in Toolchain/

- AK/Checked.h
- Userland/Libraries/LibAudio/FlacLoader.cpp
- Userland/Libraries/LibAudio/GenericTypes.cpp
- Userland/Libraries/LibAudio/MP3Loader.cpp
- Userland/Libraries/LibAudio/QOATypes.cpp
Saturating arithmetic leads to less screwed up audio in these cases.
One was missed in the previous fix
This can happen with some weird inputs, so instead, return an error; we
need at least one “effective” bit per sample so the bits per sample
cannot be less than or equal to the wasted bits per sample.
These were intentionally set up to be at the end of the granule size,
but since the stereo intensity loop is intentionally using a <= end
comparison (that’s how the scale factor bands work), we must skip these
dummy bands which would otherwise cause an out-of-bounds index.
> LibAudio: Fix various fuzzer-found bugs

- Meta/find_compiler.sh
In bd7d01e9, Meta/serenity.sh started checking cc and cxx if CC or CXX respectively are not set in the environment. My machine does not have cxx symlink in PATH, so every invocation of the script resulted in the "cxx: command not found" message outputted to stderr, and that became quite annoying.
> Meta: Do not spam "<compiler-name>: command not found"

- AK/Math.h
- Userland/Applications/Maps/MapWidget.cpp
- Userland/Applications/PixelPaint/ImageMasking.cpp
- Userland/Applications/PixelPaint/Tools/GradientTool.cpp
- Userland/Games/ColorLines/HueFilter.h
- Userland/Libraries/LibGL/Matrix.cpp
- Userland/Libraries/LibGfx/DeltaE.cpp
- Userland/Libraries/LibGfx/Filters/HueRotateFilter.h
- Userland/Libraries/LibGfx/GradientPainting.cpp
- Userland/Libraries/LibGfx/Gradients.h
- Userland/Libraries/LibSoftGPU/Device.cpp
- Userland/Libraries/LibWeb/CSS/Angle.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
- Userland/Libraries/LibWeb/Geometry/DOMMatrix.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
This adds the `to_radians` and `to_degrees` functions to AK math, I have also updated all instances in the codebase where degrees where converted to radians and reverse, maybe I missed some then they can also be added to this commit.
These functions make the code a little bit easier to read.
> AK: Add to_radians and to_degrees math functions

- Userland/Applications/Maps/MapWidget.cpp
- Userland/Applications/Maps/MapWidget.h
**Maps**
- Tiles were downloaded in parallel, but without any limit. This implements a tile queue and limits the parallel downloads to 8 and by doing so, prevents hanging because of a file descriptor shortage.
- During zooming in and out, if we do not yet have a cached tile available, we composite a tile preview using cached tiles from higher and/or lower zoom levels.
- Double clicking anywhere on the map zooms in or out on that location.
_Demo_
https://github.com/SerenityOS/serenity/assets/3210731/42df8f36-d0e4-46d6-81eb-676186c80468
Note: those gray tiles in the demo seem to be caused by some peculiarities in RequestServer / our TCP stack.
CC @bplaat
> Maps: Fix a hang, use cached tiles from other zoom levels, and zoom on doubleclick

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Userland/Libraries/LibWeb/CSS/Display.cpp
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Most of the time the resolved value is the computed value, which we already have. So let's use that!
The shorthands missing from this list (according to debug logging) are currently:
- 'animation'
- 'flex'
- 'flex-flow'
- 'font'
- 'gap'
- 'grid'
- 'grid-gap'
- 'inset'
- 'inset-block'
- 'inset-inline'
- 'list-style'
- 'margin-block'
- 'margin-inline'
- 'overflow'
- 'padding-block'
- 'padding-inline'
- 'place-content'
- 'place-items'
- 'place-self'
Which is a much nicer list than the 39 (or more?) we were missing previously.
> LibWeb: Use computed values where appropriate in ResolvedCSSStyleDeclaration

- Userland/Libraries/LibWeb/DOM/CharacterData.cpp
- Userland/Libraries/LibWeb/DOM/ChildNode.h
- Userland/Libraries/LibWeb/DOM/DocumentFragment.idl
- Userland/Libraries/LibWeb/DOM/NodeOperations.cpp
- Userland/Libraries/LibWeb/DOM/NodeOperations.h
- Userland/Libraries/LibWeb/DOM/NonElementParentNode.h
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.h
- Userland/Libraries/LibWeb/SVG/SVGGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
This leaves 5 more interfaces to be ported over from DeprecatedString.
Also includes one commit to closer match the spec for CharacterData - which will also make it easier to port that interface from DeprecatedString in the future.
> LibWeb: Port DocumentFragment from DeprecatedString to String

- Tests/LibWeb/Layout/expected/block-and-inline/button-baseline-align.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-image-only.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-abspos-pseudo-element.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-after-pseudo.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-before-pseudo.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-multiple-words-text-node-label.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label-and-font-size.txt
- Tests/LibWeb/Layout/expected/block-and-inline/button-with-text-node-label.txt
- Tests/LibWeb/Layout/input/block-and-inline/button-with-after-pseudo.html
- Tests/LibWeb/Layout/input/block-and-inline/button-with-before-pseudo.html
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
LibWeb: Add boxes for before/after pseudos post button layout tweak
When a button should use flex for alignment and also has ::before
and/or ::after, we previously did the following:
1. Prepended/appended the button's children with boxes for
pseudo-elements.
2. Replaced the button's direct children with a flex container that
contains its children.
As a result, the generated boxes for ::before/::after ended up as
children of the generated flex item, instead of being direct children
of the button layout box as they were supposed to be.
This change reverses these steps, ensuring that boxes for
pseudo-elements are generated only after modifications inside the
button layout are completed.
Before:
After:
> LibWeb: Set children of button layout box to be non-inline

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/main.cpp
This is a small change that enables Ladybird to open multiple URLs supplied as command-line-arguments. Each URL is opened in a separate tab on startup, and the active tab is the first URL supplied.
This mirrors the behavior of other browsers like Chromium and Firefox (and the Serenity browser! :^)).
> Ladybird: Allow opening multiple URLs at once from the command line

- AK/BufferedStream.h
This reverts commit 13573a6c4bc0311f91371fd4563bc930d4811682.
Some clients of `BufferedStream` expect a non-blocking read by `read_some` which the commit above made impossible by potentially performing a blocking read. For example, the following command hangs:
pro http://ipecho.net/plain
This is caused by the HTTP job expecting to read the body of the response which is included in the active buffer, but since the buffered data size is less than the buffer passed into `read_some`, another blocking read is performed before anything is returned.
By reverting this commit, all tests still pass and `pro` no longer hangs. Note that because of another bug related to `stdout` / `stderr` mixing and the absence of a line ending, there is no output to the command above except a progress update.
CC …
> Revert "AK: Refill a BufferedStream when it has less than the requested size"

- Tests/LibWeb/Layout/expected/block-and-inline/block-level-floating-box-with-clearance.txt
- Tests/LibWeb/Layout/expected/block-and-inline/floats-with-negative-percentage-margins.txt
- Tests/LibWeb/Layout/input/block-and-inline/block-level-floating-box-with-clearance.html
- Tests/LibWeb/Layout/input/block-and-inline/floats-with-negative-percentage-margins.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Before, we completely ignored clearance for block-level boxes if they were floated. This was incorrect because it is valid for a block-level box to be floated and still have clearance. However, unlike clearance on normal flow boxes, clearance on floating boxes does not affect the y-position of subsequent normal flow boxes. Instead, it pushes the box's position to the very beginning of an edge.
> LibWeb: Allow block level boxes to be floated and have clearance

- Userland/Libraries/LibJS/Position.h
- Userland/Libraries/LibJS/SourceCode.cpp
- Userland/Libraries/LibJS/SourceCode.h
- Userland/Libraries/LibJS/SourceRange.h
Instead of caching start-of-line offsets, we now cache byte offsets at regular intervals. This fixes an issue where we had terrible performance on large minified JS, since that often means one very, VERY long line (with no line endings to cache).
My machine was spending ~35ms per stack frame when throwing errors on some heavy minified websites, and after this patch, we now spend <1ms per stack frame.
> LibJS: Make line-and-column resolution fast for large minified JS

- Userland/Games/GameOfLife/BoardWidget.cpp
- Userland/Games/GameOfLife/main.cpp
Previously, when there were more rows or columns than the BoardWidget could contain, nothing was displayed. The BoardWidget minimum size is now set whenever the number of rows or columns changes.
Video:
https://github.com/SerenityOS/serenity/assets/2817754/826ca9a0-e669-40e1-8111-23c4e437151c
> GameOfLife: Ensure BoardWidget can always contain the board

- Tests/LibWeb/Text/expected/HTML/StructuredClone-array-buffer-views.txt
- Tests/LibWeb/Text/input/HTML/StructuredClone-array-buffer-views.html
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
Also lay the groundwork for the object property, map, etc serializations by making recursive calls to serialize/deseriualize not terrible.
> LibWeb: Add {de}serialization steps for TypedArrayBuffers and DataViews

- Tests/LibWeb/Ref/css-open-closed-selectors.html
- Tests/LibWeb/Ref/reference/css-open-closed-selectors-ref.html
- Userland/Libraries/LibWeb/CSS/PseudoClasses.json
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h
I may have been waiting in anticipation of the `<details>` PR getting merged just so I could add more pseudo-classes. :sweat_smile: 
`<details>` works. `<dialog>` and `<select>` should also work with these once they actually get implemented - all the selector-side stuff is implemented.
> LibWeb: Implement the :open and :closed pseudo-classes

- Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.cpp
- Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.h
- Ladybird/Android/src/main/cpp/JNIHelpers.h
- Ladybird/Android/src/main/cpp/LadybirdActivity.cpp
- Ladybird/Android/src/main/cpp/TimerExecutorService.cpp
- Ladybird/Android/src/main/cpp/WebContentService.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
- Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdActivity.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/TimerExecutorService.kt
- Ladybird/CMakeLists.txt
- Ladybird/WebContent/CMakeLists.txt
Timers run in their own thread, to take advantage of existing Java Executor features. By hooking into ALooper, we can spin the main Activity's UI thread event loop without causing a fuss, or spinning the CPU by just polling our event loop constantly.
> Ladybird/Android: Add EventLoopImplementation for ALooper

- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/TabController.h
- Ladybird/AppKit/UI/TabController.mm
- Ladybird/Qt/BrowserWindow.cpp
- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Libraries/LibWebView/CMakeLists.txt
- Userland/Libraries/LibWebView/UserAgent.cpp
- Userland/Libraries/LibWebView/UserAgent.h
This PR brings the debug menu of the AppKit chrome to near feature-parity with that of the Qt chrome. In addition, this PR allows the list of user agent strings to be shared across different chromes.
> Ladybird: Add more items to the debug menu of the AppKit chrome

- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
This could mean that the picked encoding was not being set to UTF-8 if the documents encoding was 'replacement', 'utf-16le' or 'utf-16be'.
> LibWeb: Fix missing 'get an output encoding' step in HTMLFormElement

- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Op.h
Instead of running a big switch statement on the opcode when checking how long an instruction is, we now simply store that in a member variable at construction time for instant access.
This yields a 10.2% speed-up on Kraken/ai-astar :^)
> LibJS: Store bytecode instruction length in instruction itself

- Tests/LibWeb/Layout/expected/br-should-not-generate-pseudo-before.txt
- Tests/LibWeb/Layout/input/br-should-not-generate-pseudo-before.html
- Userland/Libraries/LibWeb/Layout/BreakNode.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
We shouldn't be putting generated pseudo elements inside elements that can't have children in the first place.
This patch fixes two issues:
- We stop generating pseudo elements for layout nodes that can't have children anyway.
- We mark Layout::BreakNode as not being able to have children.
Visual progression on the Dark Souls wiki (https://darksouls.wiki.fextralife.com/Titanite+Chunk)
Before:
After:
> LibWeb: Don't generate ::before/::after for BR elements

- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/DOM/DocumentLoading.h
- Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
- Userland/Libraries/LibWeb/MimeSniff/MimeType.h
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.idl
I have added the XMLHttpRequest Document response type. XMLHttpRequest is quite a large codebase so maybe I did something quite wrong, looking forward to feedback :^)
I could not figure out howto cast a `JS::Value` in `XMLHttpRequest::response_xml()` to `JS::GCPtr<DOM::Document>`. So right now I put that `GCPtr` in `m_response_document`, this works but is maybe not what we want.
> LibWeb: Add XMLHttpRequest Document response type

- CONTRIBUTING.md
It seems that it was supposed to be updated in 388d4555752b85419b9b78d38fc5ff0996cd08a8 but was missed.
> Documentation: Update clang-format version where it was missed

- Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
- Userland/Applications/FontEditor/MainWidget.cpp
- Userland/Applications/PixelPaint/main.cpp
- Userland/Libraries/LibGUI/UIDimensions.h
- Userland/Services/DeviceMapper/DeviceEventLoop.cpp
- Userland/Utilities/cal.cpp
- Userland/Utilities/pkg/AvailablePort.cpp
- Userland/Utilities/pkg/InstalledPort.cpp
> Userland: Don't use `String::from_utf8()` for literal strings

- Tests/LibWeb/Text/expected/css/style-sheet-with-byte-order-mark.txt
- Tests/LibWeb/Text/expected/scripted-dom-insertion-during-html-parse.txt
- Tests/LibWeb/Text/input/css/style-sheet-with-byte-order-mark.html
- Tests/LibWeb/Text/input/include.js
- Tests/LibWeb/Text/input/link-element-media-attribute.html
- Tests/LibWeb/Text/input/link-element-onload-attribute.html
- Tests/LibWeb/Text/input/link-element-rel-preload-load-event.html
- Tests/LibWeb/Text/input/link-element-search.html
- Tests/LibWeb/Text/input/scripted-dom-insertion-during-html-parse.html
- Userland/Libraries/LibWeb/Internals/Internals.cpp
- Userland/Libraries/LibWeb/Internals/Internals.h
- Userland/Libraries/LibWeb/Internals/Internals.idl
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Utilities/headless-browser.cpp
Previously, we used `on_load_finish` to determine when the text test
was completed. This method did not allow testing of async functions
because there was no way to indicate that the runner should wait for
the async call to end.
This change introduces a function in the `internals` object that is
intended to be called when the text test execution is completed. The
text test runner will now ignore `on_load_finish` which means a test
will timeout if this new function is never called.
`test(f)` function in `include.js` has been modified to automatically
terminate a test once `load` event is fired on `window`.
new `asyncTest(f)` function has been introduces. `f` receives function
that will terminate a test as a first argument.
Every test is expected to call either `test()` or `asyncTest()` to …
> LibWeb+WebContent+headless-browser: Support async text tests

- Tests/LibWeb/Text/expected/set-timeout-with-no-active-script.txt
- Tests/LibWeb/Text/input/set-timeout-with-no-active-script.html
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
Implements https://github.com/whatwg/html/pull/9712
Fixes https://github.com/SerenityOS/serenity/issues/20970
-----
LibWeb: Default ScriptFetchOptions parser metadata to NotParserInserted
See: https://html.spec.whatwg.org/multipage/webappapis.html#default-classic-script-fetch-options
> LibWeb: Fix setTimeout() when there's no active script

- Userland/Libraries/LibJS/Heap/Heap.cpp
for_each_cell_among_possible_pointers() was taking HashTable by value instead of by const reference for no reason.
The copying was soaking up ~4% of CPU time while loading https://x.com/
> LibJS: Avoid pointless HashTable copying during GC mark phase

- Tests/LibRegex/Regex.cpp
- Userland/Libraries/LibRegex/RegexOptimizer.cpp
This was causing the calculated jump target to become invalid, leading to possibly invalid optimisations and (more likely) crashes.
Fixes #21047.
> LibRegex: Don't add the Repeat instruction size to its jump target

- Tests/LibWeb/Layout/expected/font-fractional-size.txt
- Tests/LibWeb/Layout/input/font-fractional-size.html
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Fixes an issue where relative font sizes would "snap" to integer sizes in an unpleasant-looking way while resizing on some websites.
> LibWeb: Allow fractional font sizes in CSS

- Meta/CMake/unicode_data.cmake
- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
- Tests/LibUnicode/TestSegmentation.cpp
- Userland/Libraries/LibUnicode/Segmentation.cpp
https://unicode.org/versions/Unicode15.1.0/
This update includes a new set of code point properties, Indic Conjunct Break. These may have the values Consonant, Linker, or Extend. These are used in text segmentation to prevent breaking on some extended grapheme cluster sequences.
Note: The following test262 tests will fail due to code point property changes, until test262 updates their tests for this release:
```
test/built-ins/RegExp/property-escapes/generated/Alphabetic.js                      ✅ -> ❌
test/built-ins/RegExp/property-escapes/generated/Assigned.js                        ✅ -> ❌
test/built-ins/RegExp/property-escapes/generated/General_Category_-_Letter.js       ✅ -> ❌
test/built-ins/RegExp/property-escapes/generated/General_Category_-_Other.js        ✅ -> ❌ …
```
> LibUnicode: Update to Unicode version 15.1.0

- Kernel/Arch/aarch64/RPi/Mailbox.cpp
- Kernel/Arch/aarch64/RPi/MiniUART.cpp
- Kernel/Arch/aarch64/RPi/UART.cpp
- Kernel/Arch/x86_64/DebugOutput.cpp
- Kernel/Arch/x86_64/Time/APICTimer.cpp
- Kernel/Devices/SerialDevice.cpp
- Kernel/Net/Intel/E1000ENetworkAdapter.cpp
- Kernel/Net/Intel/E1000NetworkAdapter.cpp
- Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
This gives the processor the hint that it is in a hot loop and allows us to do other work in between
---
also simplifies the E1000E read_eprom code
> Kernel: Use Processor::wait_check in loops waiting for HW to respond

- AK/URL.cpp
- AK/URL.h
- Tests/LibWeb/Text/expected/URL/strip_trailing_spaces_from_opaque_path.txt
- Tests/LibWeb/Text/input/URL/strip_trailing_spaces_from_opaque_path.html
- Userland/Libraries/LibWeb/URL/URL.cpp
- Userland/Libraries/LibWeb/URL/URL.h
Adds https://url.spec.whatwg.org/#potentially-strip-trailing-spaces-from-an-opaque-path.
Tested the code paths in `set_search()` and `set_hash()`  and they appear fine, though I think the design may be questionable, specifically with exposing more methods and delegating the work in those methods to `AK::URL`.
> LibWeb/URL: Add `strip_trailing_spaces_from_an_opaque_path()`

- Base/res/html/misc/mouse-events.html
- Ladybird/AppKit/UI/Event.h
- Ladybird/AppKit/UI/Event.mm
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/Qt/WebContentView.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.h
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
- Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/WheelEvent.h
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/WebContentServer.ipc
I have fixed many spec issues with the `MouseEvent` and `WheelEvent`:
- I have added the `screenX` and `screenY` properties
- I have reordered the properties to resemble the spec
- I have removed items from `MouseEventInit` that where not in spec
- I have added modifier keys support to `MouseEvent` and `WheelEvent`
This is quite a large change so careful feedback would be nice.
This pull request changes the `WebContent` IPC a bit. I have updated the Ladybird Qt, Appkit and SerenityOS Browser chromes. Other chromes like the GTK4 that are out of tree need to add the screen_position to mouse events otherwise you get errors.
https://github.com/SerenityOS/serenity/assets/19894029/eec00f76-b286-48c5-851e-f7a73545de07
> LibWeb: Add MouseEvent screenX,Y, modifier keys and follow spec more

- Userland/Games/GameOfLife/main.cpp
This prevents the menu and toolbar action state getting out of sync, which could happen previously. The menu item also now shows the appropriate icon rather than a checkbox.
> GameOfLife: Use the same play/pause action in the menu and toolbar

- Base/usr/share/man/man1/less.md
- Userland/Utilities/less.cpp
This PR continues work started in #20121 to add the `-N` option to `less`. This option displays the line number before each line of text.
I've included @supercomputer7 as co-author, as this PR is based off of his work.
Demo:
https://github.com/SerenityOS/serenity/assets/2817754/6f9b7180-360a-4bfa-8b68-c93156120af1
> less: Add `-N` option to show line numbers

- Userland/Applications/3DFileViewer/WavefrontOBJLoader.cpp
This change also improves error handling if the given .obj file contains malformed floating point numbers.
> 3DFileViewer: Remove DeprecatedString usage in object loader

- Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
- Userland/Libraries/LibJS/Tests/builtins/RegExp/RegExp.js
We were translating the pattern [\⪾-\⫀] to [\\u2abe-\\u2ac0], which is a very different pattern; as a code unit converted to the \uhhh format has no meaning when escaped, this commit makes us simply skip escaping it when translating the pattern.
> LibJS: Unescape incorrectly escaped code units in regex patterns

- Tests/LibWeb/Layout/expected/block-and-inline/atomic-inline-with-white-space-nowrap.txt
- Tests/LibWeb/Layout/input/block-and-inline/atomic-inline-with-white-space-nowrap.html
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Visual progression on https://substack.com/
Before:
After:
> LibWeb: Don't break for atomic inline elements in `white-space: nowrap`

- Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.cpp
Changes to fix LibJSGCVerifier build with llvm version used in BuildClang.sh
> Meta: Update LibJSGCVerifier to build with llvm 16.0.6

- Userland/Libraries/LibGfx/Path.cpp
- Userland/Libraries/LibGfx/Path.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.idl
This patch adds initial CanvasPath arcTo support for when working with canvas 2D rendering contexts
https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-arcto
Example:
```
<canvas style="border: 1px solid black" width=200 height=200 id="canvas"></canvas>
<script>
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.moveTo(10, 25);
ctx.arcTo(75, 25, 75, 60, 20);
ctx.stroke();
</script>
```
Before:
After:
Philip html5 canvas test suite (https://philip.html5.org/tests/canvas/suite/tests/index.2d.path.arcTo.html):
Before:
After:
> LibWeb: Add initial CanvasPath arcTo support

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentConsoleClient.h
Fixes regression introduced in b4fe118dff6c1bd839f0443f9d822ae078895814
The `WebContentConsoleClient` needs to be created not just once, but for every new document. Although the JS Console window allows communication only with the active document associated with the top-level browsing context, we still need a console client for each iframe's document to ensure their console logs are printed.
In the future, we might consider adding the ability to switch which document the JS Console window communicates with.
Fixes https://github.com/SerenityOS/serenity/issues/21117
> LibWeb: Create `WebContentConsoleClient` for every new document

- Userland/Libraries/LibJS/MarkupGenerator.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Shape.cpp
- Userland/Libraries/LibJS/Runtime/Shape.h
- Userland/Libraries/LibJS/Runtime/StringObject.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.h
- Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.cpp
This allows us to get rid of property_table_ordered() which was a heavy-handed way of iterating properties in insertion order by first copying them to a sorted Vector.
Clients can now simply iterate property_table() directly.
3% speed-up on Kraken/ai-astar.js :^)
> LibJS: Use OrderedHashMap for the Shape property table

- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/TabController.mm
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Userland/Applications/Mail/MailWidget.cpp
- Userland/Applications/Presenter/PresenterWidget.cpp
- Userland/Applications/TextEditor/MainWidget.cpp
- Userland/DevTools/HackStudio/Editor.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/WebContentServer.ipc
After moving to navigables, we started reusing the code that populates
session history entries with the srcdoc attribute value from iframes
in `Page::load_html()` for loading HTML.
This change addresses a crash in `determine_the_origin` which occurred
because this method expected the URL to be `about:srcdoc` if we also
provided HTML content (previously, it was the URL passed along with the
HTML content into `load_html()`).
> Userland+Ladybird: Always specify url to be about:srcdoc in load_html()

- AK/Platform.h
- AK/Random.h
- AK/StackInfo.cpp
- Documentation/BuildInstructionsLadybird.md
- Ladybird/CMakeLists.txt
- Ladybird/RequestServer/CMakeLists.txt
- Meta/Lagom/CMakeLists.txt
- Userland/Libraries/LibCore/Account.cpp
- Userland/Libraries/LibCore/DirIterator.cpp
- Userland/Libraries/LibCore/DirectoryEntry.cpp
- Userland/Libraries/LibCore/Group.cpp
- Userland/Libraries/LibCore/Group.h
- Userland/Libraries/LibCore/LocalServer.cpp
- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibCore/Socket.cpp
- Userland/Libraries/LibCore/StandardPaths.cpp
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibCore/System.h
- Userland/Libraries/LibCore/TCPServer.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
This set of patches makes Ladybird build (but not yet run) successful on Haiku, the open-source successor of BeOS.
Most fixes are at the same locations where patches were already required for the BSDs.
Additionally, I took a lot of inspiration from https://github.com/haikuports/haikuports/blob/897726483669e0f4f4df26f388b901d841ebf40d/www-client/ladybird/patches/serenity-pre20220728.patchset but also a lot has changed since that year.
Building Ladybird on Haiku was impossible for the last year due to the old compiler versions, GCC 13 has only become available here a few days ago which makes building Ladybird possible again.
This is currently work on progress, it builds successfully and the Ladybird window opens, but the WebContent process crashes immediately for an unknown reason.
> Everywhere: Add support for the Haiku platform

- Toolchain/BuildClang.sh
The Clang toolchain build fine without `gnu-sed` installed. It is required to build some ports, but not to build the toolchain. Removing the dependency precedes adding it as a [dependency](https://github.com/SerenityOS/serenity/pull/20888/files#r1314309614) IMO.
Closes: #20888
> Toolchain: Remove dependency on `gnu-sed` for Clang on Darwin

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
The `-maxdepth` option limits the number of levels `find` will descend into the file system for each given starting point.
The `-mindepth` option causes commands not to be evaluated until the specified depth is reached.
Example `-maxdepth` usage:
Example `-mindepth` usage:
> find: Add the `-maxdepth` and `-mindepth` options

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
This PR adds the `-gid` and `-uid` options to filter files by user and group ID. Both of these options can be prefixed with '+' or '-' to return files with an ID greater than or less than the given value.
Example usage:
> find: Add `-gid` and `-uid` options to filter files by group and user ID

- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/SharedArrayBufferPrototype.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
ArrayBuffer no longer stores a plain ByteBuffer internally, but a DataBlock instead, which encapsulated the ByteBuffer together with information if it is shared or not.
> LibJS+LibWeb: Track SharedArrayBuffers' shared state

- Ports/julius/package.sh
The CMake-generated Makefile's install target is also no longer used, as the `julius` binary is the only file we actually need to copy.
> Ports/julius: Add a launcher entry and setup instructions

- Userland/Games/GameOfLife/BoardWidget.cpp
- Userland/Games/GameOfLife/BoardWidget.h
- Userland/Games/GameOfLife/GameOfLife.gml
- Userland/Games/GameOfLife/main.cpp
The counter is incremented after each new generation and reset whenever any cell on the board is toggled. Resizing the board does not reset the tick count.
> GameOfLife: Add a tick counter to the status bar

- Userland/Libraries/LibWeb/Loader/FileDirectoryLoader.cpp
- Userland/Services/WebServer/Client.cpp
This PR makes the following changes to `WebServer`:
* Sizes displayed by the directory listing are now human readable for files. Size for directories is now left blank. 
* Files are no longer displayed in the directory view if their corresponding `stat` call fails. For example, it was previously possible to crash the program if there was a symlink that pointed outside the permitted directory
* A 403 is now returned when trying to access non-readable files or non-searchable directories.
WebServer:
**EDIT**: I've now implemented human readable sizes for the directory listing in Ladybird as well
Ladybird:
> LibWeb+WebServer: Use human-readable sizes on directory listing

- AK/MemoryStream.cpp
- Tests/AK/TestMemoryStream.cpp
The seek offset is still applied positively when seeking from the end;
see the Kernel's seek implementation.
> AK: Fix MemoryStream seek from end

- Base/usr/share/man/man6/FlappyBug.md
- Base/usr/share/man/man6/Snake.md
- Userland/Games/Solitaire/main.cpp
These commits contribute towards #21091:
* Update the Snake & Flappy Bug manpages to read better with more detail
* Rearrange Solitaire's `Help` menu so the actions are in the same order as other application's Help menus
**Before:**
**After:**
> Base+Solitaire: Update Snake & Flappy Bug manpages + Rearrange Solitaire Help Menu

- Ladybird/AppKit/UI/Tab.mm
Remember Ladybird Appkit chrome last window position and size. Fortunately, this can be done in macOS with one line of code 🎉
CC: @trflynn89
> Ladybird/Appkit: Remember last window position and size

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
We were parsing these all right, but ignoring them in StyleComputer.
No test unfortunately, since we don't currently have a way to delay the load event until a @font-face has been fully loaded. (Any test of this right now would be flaky.)
Visual progression on the https://substack.com/ front page.
Before:
After:
> LibWeb: Handle custom ident values for the CSS font-family property

- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Tests/functions/function-default-parameters.js
If identifier represents local variable we should get its value from `local_variables` in `ExecutionContext` instead of environment.
> LibJS: Get initial_value from local variables if id represents a local

- Tests/LibWeb/Layout/expected/grid/placement-1.txt
- Tests/LibWeb/Layout/expected/grid/placement-2.txt
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Also contains a drive-by expression simplification, and accidental double truncation, but does not seem to affect layout according to the current tests
> LibWeb: Use more CSSPixelFractions in GFC::expand_flexible_tracks

- Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
- Tests/LibWeb/Text/expected/HTML/navigator-beacon.txt
- Tests/LibWeb/Text/input/HTML/navigator-beacon.html
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/Navigator.h
- Userland/Libraries/LibWeb/HTML/Navigator.idl
- Userland/Libraries/LibWeb/HTML/NavigatorBeacon.cpp
- Userland/Libraries/LibWeb/HTML/NavigatorBeacon.h
- Userland/Libraries/LibWeb/HTML/NavigatorBeacon.idl
I have added basic support for the `Navigator` `sendBeacon` method. Until today I didn't now this method exists. But it is an entry on [html5test.com](https://html5test.com/), an older but still useful basic web test that gives your browser a score.
The API is mostly used by Trackers and funny enough my uBlock Origin extension in Firefox blocks all `sendBeacon` requests 😆. But we still need to implemented this web API. With content filtering we can disable maybe it in the future again.
> LibWeb: Add basic Navigator send beacon support

- Kernel/Arch/aarch64/linker.ld
- Kernel/Arch/init.cpp
- Kernel/Arch/riscv64/linker.ld
- Kernel/Arch/x86_64/linker.ld
- Kernel/Bus/USB/Drivers/USBDriver.h
- Kernel/Bus/USB/USBDevice.cpp
- Kernel/Bus/USB/USBDevice.h
- Kernel/Bus/USB/USBHub.cpp
- Kernel/Bus/USB/USBInterface.h
- Kernel/Bus/USB/USBManagement.cpp
- Kernel/Bus/USB/USBManagement.h
Rebased and adapted from @Quaker762's branch
Q: Should I move the driver registration function storage into unmap_after_init?
CC: @supercomputer7 @Quaker762
> Kernel/USB: Add a basic Driver interface

- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/Inspector.h
- Ladybird/AppKit/UI/Inspector.mm
- Ladybird/AppKit/UI/InspectorController.h
- Ladybird/AppKit/UI/InspectorController.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/Tab.h
- Ladybird/AppKit/UI/Tab.mm
- Ladybird/AppKit/Utilities/Conversions.h
- Ladybird/AppKit/Utilities/Conversions.mm
- Ladybird/AppKit/Utilities/NSString+Ladybird.h
- Ladybird/AppKit/Utilities/NSString+Ladybird.mm
- Ladybird/CMakeLists.txt
This implementation contains the DOM tree and CSS style table (computed properties, resolved properties, and variables). You can click nodes in the inspector's DOM tree to further inspect them, or right-click on elements on the page to inspect them from the context menu.
> Ladybird: Implement an Inspector window for the AppKit chrome

- Userland/Applications/Maps/MapWidget.cpp
- Userland/Applications/Maps/MapWidget.h
I have added a contextmenu to the Maps application with an option to:
- copy the current selected location to clipboard
- open the current selected location in OpenStreetMap, Google Maps, Bing Maps and DuckDuckGo Maps
- center the map widget around the selected location
**Also the "Open in ..." buttons won't work because of a unveil issue but a bugfix exists in #21013**
https://github.com/SerenityOS/serenity/assets/19894029/37d8cd8d-ef07-45a6-87f2-b98ba2d7af0b
*This is SerenityOS x86_64 running on a ARM64 platform so the performance looks worse then it is*
Looking forward to feedback :^)
> Maps: Add context menu to the map widget

- Documentation/BuildInstructions.md
- Documentation/NvimConfiguration.md
- Documentation/RunningOnRaspberryPi.md
- Documentation/Troubleshooting.md
Unless a new toolchain update has been merged, users should not need to rebuild their toolchain. Yet, the first thing they see in the build documentation is to run `Meta/serenity.sh rebuild-toolchain`, which might incorrectly lead them to use it whenever they encounter an error. This is a waste of time and causes frustration.
Move any mentions of this option to `Troubleshooting.md` and add a note to `BuildInstructions.md` about the toolchain build being a one-time endeavor.
> Documentation: Hide `Meta/serenity.sh rebuild-toolchain`

- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
This change moves steps that can be executed only once and then reused in subsequent function instantiations from
`function_declaration_instantiation` to the ECMAScriptFunctionObject constructor:
- Determine if there are any parameters with duplicate names.
- Determine if there are any parameters with expressions.
- Determine if an arguments object needs to be created.
- Create a list of distinct function names for which bindings need to be created.
- Create a list of distinct variable names for which bindings need to be created.
This change makes React-Redux-TodoMVC test in Speedometer run 10% faster :)
> LibJS: Run reusable steps of FunctionDeclarationInstantiation only once

- Userland/Libraries/LibWeb/URL/URL.cpp
Since in the previous snapshot we were using the hostname setter's spec URL.
> LibWeb/URL: Use the correct spec URL comment for `URL::port()`

- Userland/Libraries/LibWeb/DOM/CharacterData.cpp
- Userland/Libraries/LibWeb/DOM/CharacterData.h
- Userland/Libraries/LibWeb/DOM/CharacterData.idl
- Userland/Libraries/LibWeb/DOM/ChildNode.h
- Userland/Libraries/LibWeb/DOM/Comment.cpp
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Position.cpp
- Userland/Libraries/LibWeb/DOM/ProcessingInstruction.cpp
- Userland/Libraries/LibWeb/DOM/Range.cpp
- Userland/Libraries/LibWeb/DOM/Text.cpp
- Userland/Libraries/LibWeb/DOMParsing/XMLSerializer.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TextNode.cpp
- Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
The existing implementation has some pre-existing issues where it is
incorrectly assumes that byte offsets are given through the IDL instead
of UTF-16 code units. While making these changes, leave some FIXMEs for
that.
Leaves only two interfaces left.
> LibWeb: Port CharacterData from DeprecatedString to String

- AK/URL.cpp
There was a spec issue using bullets for steps instead of it being numbered, but has since been resolved in https://github.com/whatwg/url/pull/787/commits/ce9e37fb1d4d699715aecedaaec6086bfc0a5937.
> AK: Number the spec step comments in `URL::serialize_path()`

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
With these changes the Ladybird AppKit chrome sends mouse wheel events to webcontent process.
With this OpenStreetMap.org starts to work:
https://github.com/SerenityOS/serenity/assets/19894029/a84c85ba-b5a4-4226-9315-d09d44e02ceb
CC: @trflynn89
> Ladybird/AppKit: Add mouse wheel events

- Tests/LibWeb/Layout/expected/grid/should-not-hang-in-size-distribution.txt
- Tests/LibWeb/Layout/input/grid/should-not-hang-in-size-distribution.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
This change is https://github.com/SerenityOS/serenity/commit/bd85e1b30b57e89ec058ef61833f7562514b3c9c ported from base size to growth limit distribution.
Fixes https://github.com/SerenityOS/serenity/issues/21056
@Zaggy1024 any chance you know less ugly way to fix the issue?
> LibWeb: Fix infinite loop in GFC growth limit distribution

- Tests/LibWeb/Text/expected/css/attr-serialization.txt
- Tests/LibWeb/Text/input/css/attr-serialization.html
- Userland/Libraries/LibWeb/CSS/Parser/Function.cpp
Otherwise `attr(|name, "fallback")` becomes `attr(| name ,  "fallback")`
This makes exactly one more test on https://goose.icu/attr pass.
> LibWeb: Stop adding extra whitespace when serializing CSS Functions

- Userland/Services/SystemServer/main.cpp
This fixes regression made in 446200d6f3bcf3a828e23902e9dbbb44702135d0
> SystemServer: Use correct unix device numbers for null, full and random

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Tests/loops/for-in-basic.js
- Userland/Libraries/LibJS/Tests/loops/for-of-basic.js
Our implementation of environment.CreateImmutableBinding(name, true)
in this AO was not correctly initializing variables in strict mode.
This would mean that constant declarations in for loop bodies would not
throw if they were modified.
To fix this, add a new parameter to CreateVariable to force strict mode.
This fixes two of our test-js tests, no change to test262.
Not too happy with this fix right now, feels like there is a better approach,
open to ideas here!
> LibJS: Create const variables in ForIn/OfBodyEvaluation in strict mode

- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
- Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
This was a remnant from the AST/BC hybrid interpreter times. We've had
a VERIFY in here for weeks now that would catch anything depending on
this behavior, and nothing has hit it, so let's remove the unnecessary
code (but leave the VERIFY) :^)
+ two follow-on cleanups.
> LibJS: Remove automatic ExecutionContext creation in BC interpreter

- Tests/LibWeb/Layout/expected/block-and-inline/flex-container-should-avoid-overlapping-floats.txt
- Tests/LibWeb/Layout/expected/block-and-inline/grid-container-should-avoid-overlapping-floats.txt
- Tests/LibWeb/Layout/input/block-and-inline/flex-container-should-avoid-overlapping-floats.html
- Tests/LibWeb/Layout/input/block-and-inline/grid-container-should-avoid-overlapping-floats.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Before, we only ensured that boxes establishing BFC did not overlap with floats because that is what CSS 2.2 specification says. However, we should also apply the same for boxes establishing FFC or GFC as this aligns with the behavior of other browsers.
Fixes https://github.com/SerenityOS/serenity/issues/21095
> LibWeb: Boxes that establish FFC or GFC should avoid overlapping floats

- AK/Function.h
Instead of ballooning the size of the Function object, simply place the
callable on the heap with a properly aligned address.
This brings the alignment of Function down from ridiculous sizes like 64
bytes down to a manageable 8 bytes.
cc @kleinesfilmroellchen (your bug report, kinda), @MacDue (reverting your change).
> AK: Use outline Function storage if alignment requirements are not met

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
- Tests/LibWeb/Text/expected/HTML/Window-named-properties-elements.txt
- Tests/LibWeb/Text/expected/HTML/Window-named-properties-iframe.txt
- Tests/LibWeb/Text/expected/HTML/Window-prototype.txt
- Tests/LibWeb/Text/input/HTML/Window-named-properties-elements.html
- Tests/LibWeb/Text/input/HTML/Window-named-properties-iframe.html
- Tests/LibWeb/Text/input/HTML/Window-prototype.html
- Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.cpp
- Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/Window.idl
- Userland/Libraries/LibWeb/HTML/WindowProxy.cpp
- Userland/Libraries/LibWeb/WebIDL/AbstractOperations.cpp
- Userland/Libraries/LibWeb/WebIDL/AbstractOperations.h
First, implement document-tree child navigable target name property set on Window. This AO allows accessing child navigables by their name as named properties on the WindowProxy object.
Next, add the named properties object to the Window prototype chain, and add the required getter AOs to window. 
These allow accessing embeds, forms, images and objects with a given
name attribute, and any element with a given id attribute, as top level
properties on the global object.
It also allows accessing NavigableContainers by target name as top level
properties on the global object.
The current implementation feels very expensive. It's likely that
these values will need smarter caching in the future.
> LibWeb: Implement named property access AOs on Window

- Meta/CMake/libweb_generators.cmake
- Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
- Tests/LibWeb/Layout/expected/svg/svg-symbol-with-viewbox.txt
- Tests/LibWeb/Layout/expected/svg/svg-with-zero-intrinsic-size-and-no-viewbox.txt
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/SVG/Default.css
- Userland/Libraries/LibWeb/SVG/SVGSymbolElement.cpp
For now, part of this is commented-out. Our current implementations of
`<mask>` and `<symbol>` rely on creating layout nodes, so they can't be
`display: none`.
> LibWeb: Include standard SVG user agent style sheet

- Tests/LibWeb/Text/expected/navigation/history-pushstate.txt
- Tests/LibWeb/Text/input/navigation/history-pushstate-iframe.html
- Tests/LibWeb/Text/input/navigation/history-pushstate.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/History.cpp
- Userland/Libraries/LibWeb/HTML/History.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Update `HTML::History` to have index and length like latest specification says
- Make `shared_history_push_replace_state()` to actually add/replace session history entry
- Update URL in UI when `pushState()` or `replaceState()` happens
- Add test for `pushState()` :)
Fixes https://github.com/SerenityOS/serenity/issues/21185
> LibWeb: Update session history when History entry is pushed/replaced 

- Base/usr/share/man/man1/ls.md
- Userland/Utilities/ls.cpp
This option will override the `-t` option and vice-versa.
Example usage:
> ls: Add the `-S` option to sort files by size

- Userland/Libraries/LibCore/ArgsParser.h
- Userland/Utilities/grep.cpp
- Userland/Utilities/ls.cpp
- Userland/Utilities/strings.cpp
Previously, argument-less options could only set a boolean to true. This
lets them also set an enum variable to a specific value, as is currently
done by the `ls` utility.
Inspired by the recent changes in #21208.
> LibCore: Add ArgsParser::add_option for setting enum values from a flag

- Kernel/Bus/VirtIO/Console.cpp
- Kernel/Bus/VirtIO/Console.h
- Kernel/Bus/VirtIO/Device.cpp
- Kernel/Bus/VirtIO/Device.h
- Kernel/Bus/VirtIO/RNG.cpp
- Kernel/Bus/VirtIO/RNG.h
- Kernel/Bus/VirtIO/Transport/Entity.cpp
- Kernel/Bus/VirtIO/Transport/Entity.h
- Kernel/Devices/GPU/VirtIO/GraphicsAdapter.cpp
- Kernel/Devices/GPU/VirtIO/GraphicsAdapter.h
- Kernel/Net/VirtIO/VirtIONetworkAdapter.cpp
- Kernel/Net/VirtIO/VirtIONetworkAdapter.h
Taken as a task from this comment ([here](https://github.com/SerenityOS/serenity/pull/19757#discussion_r1259259110), by @ADKaster).
> Kernel/VirtIO: Ensure proper error propagation in core methods

- Ladybird/AppKit/UI/ConsoleController.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/AppKit/UI/TabController.mm
It was a pain but I found the bugs:
- First the AppKit chrome didn't listen for dpi changes so if you opend the browser in a low dpi screen and moved it to a high dpi screen the `device_pixel_ratio` was in correct
- `m_viewport_rect` contains real pixels so that needs to be converted to device pixels when adding the scroll delta in `on_scroll_by_delta`. There was a fixme about it, that I forgot to see last time 😳
> Ladybird/AppKit: Fix scrolling issues caused in #21124

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Calendar/main.cpp
- Userland/Applications/FontEditor/main.cpp
- Userland/Applications/HexEditor/main.cpp
- Userland/Applications/KeyboardMapper/main.cpp
- Userland/Applications/Mail/main.cpp
- Userland/Applications/Piano/main.cpp
- Userland/Applications/PixelPaint/main.cpp
- Userland/Applications/Presenter/main.cpp
- Userland/Applications/Spreadsheet/main.cpp
- Userland/Applications/SystemMonitor/main.cpp
- Userland/Applications/TextEditor/main.cpp
- Userland/Applications/ThemeEditor/main.cpp
- Userland/DevTools/GMLPlayground/main.cpp
- Userland/DevTools/HackStudio/main.cpp
- Userland/DevTools/Profiler/main.cpp
- Userland/DevTools/SQLStudio/main.cpp
A few weeks a go I have added a API for windows to easily remember it state (#20769).
I have now updated all productivity / editor applications to use this feature. This gives the system more premium feel because all the application windows opens up in the old position it was closed. So less annoying initial dragging and resizing has to be done by the user 🎉.
> Userland: Remember window state of productivity / editor applications

- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGUI/Window.h
- Userland/Services/WindowServer/ConnectionFromClient.cpp
- Userland/Services/WindowServer/ConnectionFromClient.h
- Userland/Services/WindowServer/WindowServer.ipc
Previously, exiting a fullscreen application when
`save_size_and_position_on_close()` was used would lead to the application having an unexpectedly large size when it was reopened. 
Exiting a maximized application would lead to the restore button not working as expected when the application was reopened.
The following scenarios have been tested:
1. Open Maps.
2. Press F11 to toggle Full Screen.
3. Press Alt+Tab to select another window, then right click the Maps application on the taskbar and click Close to exit.
4. Relaunch Maps - previously, the application would start with a window larger than the screen.
and
1. Open Maps.
2. Toggle Maximize.
3. Exit Maps.
4. Relaunch Maps - previously, the application would start maximized, but the restore button would have no effect.
> WindowServer+LibGUI: Use floating rect when saving window state on exit

- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
- Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
Before this change, whenever ImageStyleValue had a non-null `m_image_request`, it was always leaked along with everything related to the document to which this value belongs. The issue arises due to the use of `JS::Handle` for the image request, as it introduces a cyclic dependency where `ImageRequest` prevents the `CSSStyleSheet`, that owns `ImageStyleValue`, from being deallocated:
- ImageRequest
- FetchController
- FetchParams
- Window
- HTMLDocument
- HTMLHtmlElement
- HTMLBodyElement
- Text
- HTMLHeadElement
- Text
- HTMLMetaElement
- Text
- HTMLTitleElement
- Text
- HTMLStyleElement
- CSSStyleSheet
This change solves this by visiting `m_image_request` from `visit_edges` instead of introducing new heap root by using `JS::Handle`.
> LibWeb: Fix memory leak in CSS::ImageStyleValue

- Userland/Libraries/LibJS/Heap/DeferGC.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
This should stop some GC bugs/crashes form happening
> LibJS: Defer GC during cell construction

- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
The SVGDecodedImageData creates a new Page and replaces its document with a new one that contains SVG content. This change adds a destroy call on the replaced document. Without this addition, all tasks scheduled on the event loop during navigation, initiated while the page's traversable is being created, will never execute, as the initial replaced document will become inactive. This leads to a document leak because the tasks use JS::Handle to hold document pointer. Making the destroy call resolves the issue because it removes all tasks associated with the destroyed document from the queue.
> LibWeb: Fix document leak in SVGDecodedImageData

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/DOM/Attr.cpp
- Userland/Libraries/LibWeb/DOM/Attr.h
- Userland/Libraries/LibWeb/DOM/Attr.idl
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
- Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
- Userland/Libraries/LibWeb/DOM/NamedNodeMap.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/QualifiedName.cpp
- Userland/Libraries/LibWeb/DOM/QualifiedName.h
- Userland/Libraries/LibWeb/DOMParsing/InnerHTML.cpp
- Userland/Libraries/LibWeb/DOMParsing/InnerHTML.h
- Userland/Libraries/LibWeb/DOMParsing/XMLSerializer.cpp
- Userland/Libraries/LibWeb/HTML/AttributeNames.h
- Userland/Libraries/LibWeb/HTML/HTMLHeadingElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.cpp
- Userland/Libraries/LibWeb/SVG/SVGGradientElement.cpp
- Userland/Services/WebContent/WebDriverConnection.cpp
There are an unfortunate number of DeprecatedString conversions required here, but these should all fall away and look much more pretty again when other places are also ported away from DeprecatedString.
Leaves only the Element IDL interface left :^)
> LibWeb: Port Attr interface from DeprecatedString to String

- Base/usr/share/man/man1/Applications.md
- Base/usr/share/man/man1/Applications/Maps.md
- Userland/Applications/Maps/main.cpp
Also, list Maps in `Applications.md` and add a link to the manpage in Map's Help menu.
Contributes towards #21091
> Base+Maps: Add manpage for Maps

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
aafef1e92d8e750b8abd2100e5896df75505e2a1 broke this while trying to make the global import available in initialisation, this commit makes sure we place the module's own functions after all resolved imports.
> LibWasm: Make sure to place imported functions before the module's

- Base/usr/share/man/man1/ls.md
- Userland/Utilities/ls.cpp
This overrides the `-F` option and vice-versa.
Example usage:
> ls: Add the `-p` option to append a trailing slash to directories

- Tests/LibWeb/Text/expected/setInterval.txt
- Tests/LibWeb/Text/expected/setTimeout.txt
- Tests/LibWeb/Text/input/setInterval.html
- Tests/LibWeb/Text/input/setTimeout.html
- Userland/Libraries/LibJS/Heap/HeapFunction.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Timer.cpp
- Userland/Libraries/LibWeb/HTML/Timer.h
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
This change implements a step from the document's destroy procedure in
the specification, saying that all active timers should be cleared.
By doing this, we also fix the leaking of a document in case where we
have navigated away from a page that has scheduled timers that haven't
yet been triggered.
> LibWeb: Fix GC-leaks caused by HTML::Timer

- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/ParsingContext.cpp
- Userland/Libraries/LibWeb/CSS/Parser/ParsingContext.h
- Userland/Libraries/LibWeb/SVG/SVGElement.h
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp
When parsing these, <number> is allowed anywhere that would usually allow a `<length>`, `<length-percentage>`, or `<angle>`. The spec is not clear on exactly how this should work (see w3c/svgwg#792 ) so I'm using some artistic license until things are clearer:
- If we expected a `<length>`, treat the `<number>` as pixels.
- If we expected an `<angle>`, treat the `<number>` as degrees.
- Only allow direct `<number>` tokens, not calc() or other functions.
From what I can tell this is what the spec *intended* but I may be very wrong. In any case, telling the ParsingContext whether we're parsing one of these attributes is a cleaner approach and more correct than temporarily enabling quirks mode, which we did previously.
> LibWeb: Add SVG-presentation-attribute-parsing mode to CSS parser

- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
While making these consistent and removing some unnecessary null/invalid-value checks, I noticed that actually, we would be manually constructing ShorthandStyleValues over and over... and could just use our existing functions that tell you what longhands a shorthand has. So, let's do that!
We should now be producing a value for every style property! :tada:
Actually serializing these correctly has a long way to go unfortunately, and will require a fair bit of manual code in `ShorthandStyleValue::to_string()` unless someone has a better idea. :yakbait:
Fixed up some property data while I was at it, partly to stop the automatic shorthand code exploding. `ShorthandStyleValue::to_string()` expects certain longhands to be present, so if we're automatically constructing the ShorthandStyleValue, …
> LibWeb: Handle shorthands in ResolvedCSSStyleDeclaration generically

- Userland/Libraries/LibELF/DynamicObject.cpp
The `DT_RELASZ` dynamic tag in riscv64's `libgcc_s.so` contains the total size of both non-PLT and PLT relocation entries. Serenity currently expects that `RELASZ` contains the size of only non-PLT entries. Both behaviors are apparently correct according to the ELF spec.
- https://www.github.com/llvm/llvm-project/issues/39026#issuecomment-981005259
- https://sourceware.org/pipermail/binutils/2023-August/128935.html
> LibELF: Calculate size of relocation table correctly in all cases

- Ladybird/Qt/Tab.cpp
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentServer.ipc
This adds support for color picker input elements. Currently it is primitively shown as a button, the visuals I plan to improve later. On frontends that support it, which are currently Browser LibGUI and Ladybird Qt, pressing it will open the system color picker, it is modeled after the behavior of Firefox, where the changes are only committed after confirming the selection.
HTMLInputElement has a new function did_pick_color which is called by the relevant logic in Page.cpp, where a new type of "non-blocking dialog" is handled by keeping track of the target HTMLInputElement and functions did_request_color_picker and color_picker_closed (This is meant to be expandable for implementing a file picker). In current implementations in Browser and Ladybird, the color dialog is modal, however …
> LibWeb and friends: Add support for the color picker input

- Userland/Games/GameOfLife/BoardWidget.cpp
- Userland/Games/GameOfLife/BoardWidget.h
- Userland/Games/GameOfLife/main.cpp
This PR makes the following changes to pattern placement in `GameOfLife`:
* Holding Ctrl when placing a pattern allows that same pattern to be placed again, previously the pattern had to be selected again. A hint has also been added to the status bar describing this feature, when a pattern is selected.
* When the game starts running, the selected pattern is now cleared
* Dragging the mouse to toggle cells is now disabled when a pattern is selected. It was previously very easy to inadvertently toggle cells when placing patterns.
Demo:
https://github.com/SerenityOS/serenity/assets/2817754/60486364-9947-4beb-898c-c48ea09d7f42
> GameOfLife: Allow ctrl+click to place multiple patterns

- Base/usr/share/man/man1/ls.md
- Userland/Utilities/ls.cpp
This PR makes the following changes to `ls`:
* The `-n` and `-o` options now imply long mode should be used.
* Adds the `-g` option, displays results in long mode but hides owner information.
* Owner and group information are now left justified in long mode. This means users/groups of different lengths line up nicely. 
Example usage:
> ls: Add the `-g` option to omit owner information in long format

- Base/usr/share/man/man1/less.md
- Userland/Utilities/less.cpp
> less: Add the `-F` option to quit if the input fits on one screen

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
Fixes https://github.com/SerenityOS/serenity/issues/21205
Fixes https://github.com/SerenityOS/serenity/issues/21240
> LibWeb: Null check container while creating srcdoc navigation params

- Userland/Libraries/LibWeb/HTML/HTMLBodyElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLBodyElement.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
ImageStyleValue has a visit_edges() method, although it is not a GC-allocated object. This is necessary because it owns a GC-allocated ImageRequest that we want to visit, instead of using JS::Handle, to avoid leaks. In the future, we might want to make StyleValue be GC-allocated.
For now, this change adds missing visit_edges() calls for objects that own ImageStyleValue.
> LibWeb: Add missing visit_edges() for ImageStyleValue

- Userland/Libraries/LibJS/Bytecode/BasicBlock.cpp
- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
This reduces the minimum size of a basic block from 4 KiB to 0 bytes. With this change, memory usage at the end of Speedometer is 1.2 GiB, down from 1.8 GiB.
> LibJS: Use a Vector<u8> for BasicBlock instruction storage

- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Tests/exponentiation-basic.js
- Userland/Libraries/LibJS/Tests/syntax/syntax-error-unary-expression-before-exponentiation.js
This change makes LibJS correctly report a syntax error when a unary expression is followed by exponentiation, as the spec requires. Apparently this is due to that expression being ambiguous ordering.
Strangely this check does not seem to apply in the same way for '++' and '--' for reasons that I don't fully understand. For example
```
let x = 5;
++x ** 2
```
Since `--5` and `++5` on it's own results in a syntax error anyway, it seems we do not need to perform this exponentiation check in those places.
Diff Tests:
+6 ✅    -6 ❌
> LibJS: Syntax error for a unary expression followed by exponentiation

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Op.h
The bytecode instruction storage may resize while generating bytecode, so it's not safe to take the address of an instruction and use it later.
Thankfully, we don't actually need to do that, so this PR removes the APIs that allowed you to do it.
> LibJS: Stop vending unstable pointers to instructions while generating bytecode

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
We can use `ensure_capacity` for binding vectors if we know their sizes
in advance. This ensures that binding vectors aren't reallocated during
the `function_declaration_instantiation` execution.
With this change, `try_grow_capacity()` and `shrink_to_fit()` are no
longer visible in the `function_declaration_instantiation()` profiles
when running React-Redux-TodoMVC from Speedometer.
> LibJS: Pre-calculate the number of bindings for function environments

- Userland/Libraries/LibGfx/ICC/Profile.cpp
There's probably a nicer way of doing this where we don't need to expand
the gray value into a full Vector3, but for now this is good enough.
Makes PDFs written by macOS 13.5.2's "Save as PDF..." feature show up.
---
Before:
After:
(This is with a PDF that I made in TextEdit by typing in "Test" and then using either File->Export as PDF… or File->Print…->PDF->Save as PDF…)
> ICC: Implement Profile::to_pcs() for grayscale colors

- Ports/openssh/ReadMe.md
- Ports/openssh/package.sh
In the current state, during OpenSSH installation, the host keys are generated and stored in the disk image.
Since storing fixed keys in the image is not a good security practice in case you need to distribute the image, I think it would be a better approach to generate the keys via a service.
This is what is done in Arch Linux [1], for example.
\[1\]: https://gitlab.archlinux.org/archlinux/packaging/packages/openssh/-/blob/9.3p1-2/sshdgenkeys.service
> Ports: Generate OpenSSH host keys using a service

- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/AbstractOperations.h
This function is no longer used anywhere after we removed AST interpreter.
> LibJS: Remove unused make_super_property_reference()

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/CSSNumericType.cpp
- Userland/Libraries/LibWeb/CSS/CSSNumericType.h
- Userland/Libraries/LibWeb/CSS/Flex.cpp
- Userland/Libraries/LibWeb/CSS/Flex.h
- Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
- Userland/Libraries/LibWeb/CSS/GridTrackSize.h
- Userland/Libraries/LibWeb/CSS/Parser/Dimension.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/FlexStyleValue.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
This replaces the manual check for a "fr" dimension in `Parser::parse_grid_size()`, and also means we can have `attr()` and `calc()` return `<flex>` values.
Much of this we can't properly test, since nothing takes a plan `<flex>` as a value, but it's there if and when a property needs it. The `grid-*` properties do use `<flex>`, but I do not at all understand how that all works so I don't want to go messing with it too much.
> LibWeb: Implement a `<flex>` dimension type

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/Utilities/Conversions.h
- Ladybird/AppKit/Utilities/Conversions.mm
I have added color picker support to the Ladybird AppKit chrome, to complete #20951.
Mostly based on this code: https://github.com/chromium/chromium/blob/master/components/remote_cocoa/app_shim/color_panel_bridge.mm#L104
https://github.com/SerenityOS/serenity/assets/19894029/70432a38-4568-4c84-8136-a45af98fe847
> Ladybird/AppKit: Add color picker support

- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
This matches HTMLInputElement, and fixes the crash when focusing a textarea.
> LibWeb: Use correct realm when focusing HTMLTextAreaElement

- AK/Assertions.cpp
- Meta/Lagom/CMakeLists.txt
This change implements #20852 for the Haiku platform.
Haiku has execinfo in a extra library, like the BSDs.
> AK: Add support for backtraces on Haiku

- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Comment and rearrange the list of properties according to the list [here](https://www.w3.org/TR/cssom-1/#resolved-values), and then fill-in the missing properties that we currently support.
Also, some related tidying-up:
- Remove some manual code we don't need.
- Make the other manual code for shorthands use the normal code path to get their longhands, instead of manually creating StyleValues for them.
There's still work to do here to make it match the spec fully, but we're getting there, and it's now more obvious where we're lacking.
> LibWeb: Spec-comment and fill in more of StyleValue resolution

- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Tests/LibWeb/Text/input/css/getComputedStyle-print-all.html
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.idl
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Today in "Sam edits this same file over and over":
- Make ResolvedCSSStyleDeclaration iterable. This exposes the list of longhand and custom properties, though currently just longhands.
- Add a test that prints out the contents of `getComputedStyle(document.body)` as a general sanity check for StyleValue serialization. As expected, some are wrong. I originally wanted to catch weirdness with shorthand serialization but that isn't actually possible so we'll see.
> LibWeb: Implement more of getComputedStyle(), and test it!

- Kernel/Bus/USB/Drivers/MassStorage/MassStorageDriver.cpp
- Kernel/Bus/USB/Drivers/MassStorage/MassStorageDriver.h
- Kernel/Bus/USB/USBClasses.h
- Kernel/Bus/USB/USBConfiguration.cpp
- Kernel/Bus/USB/USBController.cpp
- Kernel/Bus/USB/USBController.h
- Kernel/Bus/USB/USBDevice.cpp
- Kernel/Bus/USB/USBHub.cpp
- Kernel/Bus/USB/USBInterface.h
- Kernel/Bus/USB/USBPipe.cpp
- Kernel/Bus/USB/USBPipe.h
- Kernel/Bus/USB/USBTransfer.cpp
- Kernel/Bus/USB/USBTransfer.h
- Kernel/CMakeLists.txt
- Kernel/Devices/Storage/StorageManagement.cpp
- Kernel/Devices/Storage/StorageManagement.h
- Kernel/Devices/Storage/USB/BulkSCSIInterface.cpp
- Kernel/Devices/Storage/USB/BulkSCSIInterface.h
- Kernel/Devices/Storage/USB/Codes.h
- Kernel/Devices/Storage/USB/SCSIComands.h
- Kernel/FileSystem/SysFS/Subsystems/Devices/Storage/DeviceDirectory.cpp
We will need these when plugging in USB drives
This field is in a packed struct, which makes it possibly misaligned.
This knowledge is lost when invoking `dbgln` triggering an unaligned
access to it, aka UB. By explicitely copying it we avoid this issue.
Transfers functions
These will be useful for directly accessing the destination buffer,
without going through a third buffer first.
---
The only interface supported right now is BulkOnly with SCSI
to test this I booted the q35 mashine with the following adjustments to the run script and mounted the newly appearing `hdb` drive
```diff
diff --git a/Meta/run.sh b/Meta/run.sh
index a2dd7308be..fad557014e 100755
--- a/Meta/run.sh
+++ b/Meta/run.sh
@@ -398,7 +398,7 @@ $SERENITY_EXTRA_QEMU_ARGS
-device vmware-svga
-device …
```
> Kernel/USB: Add a crude USB MassStorage driver :^)

- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
This change adds a check to discard pointers that are lower than the minimum address of all allocated blocks or higher than the maximum address of all blocks. By doing this we avoid executing plenty of set() operations on the HashMap in the add_possible_value().
With this change gather_conservative_roots() run 10x times faster in Speedometer React-Redux-TodoMVC test.
> LibJS: Early reject pointers outside of allocated blocks range in GC

- Kernel/Arch/aarch64/linker.ld
This subtraction is necessary to ensure that the section has the correct address. Also, without this change, the Kernel ELF binary would explode in size. This was forgotten in a0dd6ec6b1a70e750dc9e504a648e967f4c5119e.
> Kernel/aarch64: Subtract KERNEL_MAPPING_BASE from driver_init section

- AK/CMakeLists.txt
- AK/HashMap.h
- AK/HashTable.h
- AK/IPv4Address.h
- AK/IPv6Address.h
- AK/SipHash.cpp
- AK/SipHash.h
- AK/StringHash.h
- AK/Traits.h
- Kernel/CMakeLists.txt
- Tests/AK/TestHashFunctions.cpp
Our current hash function is fast, simple and deterministic, plus it fulfils all standard desirable properties (uniformity, surjectivity). However, since it's deterministic and easily reversible it allows an attacker which has control over keys in a hash table (e.g. routing table entries) to cause many hash collisions, which is logically known as a HashDoS attack. As a solution there's algorithms like SipHash which are non-deterministic by using a random seed key at startup, and trickier to reverse (while not cryptographically secure). An attacker doesn't know a key's hash from the start (it's different for every time the program starts up) so they first have to leak that information somehow, and then also reverse the seed key from one or more value-hash pairs, which even if possible, …
> AK: Use SipHash-1-3 as the default hash function for increased security

- Kernel/FileSystem/InodeMetadata.h
- Userland/Utilities/stat.cpp
Previously, `st_dev` was always set to 0, which caused an issue in `du` where files with the same inode number on different devices weren't counted correctly.
This probably isn't the most correct way to do this, but I believe the `fsid` we generate satisfies the requirements for `st_dev`, namely that `st_dev` and `st_ino` taken together can uniquely identify a file on the local machine.
Before:
After:
> Kernel+stat: Populate `stat.st_dev` with `fsid` and show it in `stat`

- Userland/Applications/Assistant/main.cpp
This fixes an issue in Assistant where the selected result index would be reset to 0 when the file cache finished building and the results list updated.
Tested with the following steps:
1. Enter 'A' as a query (or anything really).
2. Quickly press the down arrow to select the second result.
3. Wait a moment for the file cache to finish building.
4. The second result should remain selected. Previously, the selected result would change back to the first one.
> Assistant: Remember currently selected result when updating results

- AK/URLParser.cpp
Since the spec renamed it to make it easier to read.
The change was made in https://github.com/whatwg/url/commit/9057992dd6a050fb8af01fffb4d3c9df1ab89b70.
> AK: Rename `URLParser:parse_host()` param is_not_special to is_opaque

- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Previously, it was possible to pass JPEGLoader a crafted input which would read past the end of the stream. We now return an error in such cases.
This fixes oss-fuzz issue: [62584](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62584&sort=-opened&can=1&q=proj%3Aserenity) (and possibly other JPEGLoader issues).
> LibGfx: Don't read past EOF in JPEGLoader

- Userland/Shell/Builtin.cpp
- Userland/Shell/PosixLexer.cpp
- Userland/Shell/PosixLexer.h
- Userland/Shell/PosixParser.cpp
- Userland/Shell/Shell.h
Just a bunch of misc work, the Shell can now parse configure scripts - but running it no worky yet:
```
❯ $SHELL --posix configure
Parameter expansion range 17-9 is out of bounds for '$as_unset'
Parameter expansion range 10-9 is out of bounds for '$as_unset'
Parameter expansion range 78- is out of bounds for '`(set) 2>&1 |
sed -n 's/^ac_env_([a-zA-Z_0-9]*)_set=.*/1/p'`'
Parameter expansion range 84- is out of bounds for '`echo "testingc" 2>/dev/null; echo 1,2,3`,`echo -n testing 2>/dev/null; echo 1,2,3`'
Parameter expansion range 35-14 is out of bounds for '$ac_config_sub'
Parameter expansion range 29- is out of bounds for '`echo "$0" |sed 's,.*[/],,'`'
$as_unset: Command not found.
$as_unset: Command not found.
turingcomplete-MkII
Shell: Job 3 (uname -n) exited
Shell: No command given to …
```
> Shell: Make configure parse in POSIX mode

- Userland/Libraries/LibGUI/TableView.cpp
This PR attempts to solve the same issue as #19800.
A key press, which is an ASCII control character will no longer cause
TableView to begin editing.
This fixes an issue in Spreadsheet where navigating to a cell then pressing escape would cause a that cell's text to be set to a non-printable value.
I couldn't find any other key (on my keyboard) that causes a non-printable character to be printed in Spreadsheet. This solution may not work for non-ascii, non-printable, non-control characters :shrug:.
> LibGUI: Don't enter TableView edit mode when a control key is pressed

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
By loading only the fonts actually used on a page, we can often avoid making a lot of unnecessary requests and style invalidations.
This change makes initial loading of apple.com much faster.
Fixes https://github.com/SerenityOS/serenity/issues/20747
> LibWeb: Implement CSS fonts lazy loading

- Userland/Applications/ImageViewer/ViewWidget.cpp
- Userland/Applications/PixelPaint/Image.cpp
- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
- Userland/Libraries/LibImageDecoderClient/Client.cpp
- Userland/Libraries/LibImageDecoderClient/Client.h
- Userland/Services/WebContent/ImageCodecPluginSerenity.cpp
- Userland/Utilities/pixelflut.cpp
This fixes the following oss-fuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62541&sort=-opened&can=1&q=proj%3Aserenity
I also fixed a crash that happened when attempting to load the test file with `ImageViewer`.
> LibGfx: Check bounds of color table accesses in BMPLoader

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
- Userland/Libraries/LibWeb/HTML/Worker.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Fixes https://github.com/SerenityOS/serenity/issues/21290
> LibWeb/Fetch: Include body and headers in Response for failed requests 

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Fixes https://github.com/SerenityOS/serenity/issues/21304
> LibWeb: Exit event handlers if active document is not fully active

- Userland/Applications/Maps/MapWidget.cpp
There were two issues with the way we generated MapWidget's tile coordinates.
**Maps before:**
**Maps after:**
CC @kleinesfilmroellchen @bplaat
> Maps: Fix occasional gray/missing tiles

- Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp
This fixes oss-fuzz issue [62047](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62047&q=proj%3Aserenity&can=2&sort=-reported).
> LibGfx: Check bounds of color table access in TinyVGLoader

- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/Tab.mm
- Ladybird/AppKit/UI/TabController.mm
- Userland/Libraries/LibWeb/HTML/HTMLMetaElement.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentClient.ipc
These patches add basic support for `<meta name="theme-color">` and a way to update the browser chrome color based on it.
In the menu bar, if the color is very bright we decrease its hsb brightness to 75% so that we have enough contrast for the buttons (see yellow sample below).
This patch has the added benefit of making it so that we get a more natural border color when resizing the window (if the site uses the meta tag that is).
```html
<html>
<head>
<meta name="theme-color" content="#ffe072">
<title>#ffe072</title>
<style>
body {
display: flex;
justify-content: center;
align-items: center;
}
html, body {
margin: 0;
height: 100%;
}
h1 {
font-family: sans-serif;
}
</style>
</head>
<body style="background-color:#ffe072;">
<h1 style="color:black">#ffe072</h1>
</body> …
```
> LibWeb&Friends: Add support for `<meta name="theme-color">`

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
This PR adds the `-ok` option to `find`. This behaves identically to the `-exec` option but prompts the user for confirmation before executing the specified command.
A command is executed if a line beginning with 'y' or 'Y' is entered  by the user. This matches the behavior of `find` on Linux and FreeBSD  when using the POSIX locale.
This PR also fixes 2 issues with related to the terminating semicolon used by `-exec` and `-ok`:
* An error is now shown and the program will exit if terminating semicolon is not present.
* The terminating semicolon must be seperate from other arguments. Previously, a command such as: `find -exec echo {} \;invalid` would have treated the entire last argument as a valid terminator. 
**EDIT:** It looks like `find` on FreeBSD behaves as we did prior to this …
> find: Add the `-ok` option

- Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
- Userland/Libraries/LibWeb/MimeSniff/MimeType.h
Should implement all the missing MIME type check algorithms from the [MIME type groups section](https://mimesniff.spec.whatwg.org/#mime-type-groups).
I tried to have the implementation mimic the wording I found in the spec, so you will see a both `String::is_one_of()` and `==` used when comparing a single MIME type essence.
> LibWeb/MimeSniff: Implement the rest of the MIME type checks

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
The following snippet would cause "i" to be incremented twice(!):
let a = []
let i = 0
a[++i] += 0
This patch solves the issue by remembering the base object and property name for computed MemberExpression LHS in codegen. We the store the result of the assignment to the same object and property (instead of computing the LHS again).
3 new passes on test262. :^)
```
Summary:
Diff Tests:
+3 ✅    -3 ❌   
Diff Tests:
test/language/expressions/logical-assignment/lgcl-and-assignment-operator-lhs-before-rhs.js     ❌ -> ✅
test/language/expressions/logical-assignment/lgcl-nullish-assignment-operator-lhs-before-rhs.js ❌ -> ✅
test/language/expressions/logical-assignment/lgcl-or-assignment-operator-lhs-before-rhs.js      ❌ -> ✅
```
> LibJS: Don't evaluate computed MemberExpression LHS twice in assignments

- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
If response object is empty we should return nullptr.
Fixes crash on https://store.steampowered.com/
> LibWeb: Fix crash in XMLHttpRequest::response_xml() if response empty

- Userland/Games/Hearts/Game.cpp
- Userland/Libraries/LibCards/CardStack.cpp
Noticed while playing around with the cards settings, that some background colours made things invisible or very hard to see. This PR fixes that by using lighter colours on dark backgrounds, and darker on lights. The luminosity values were chosen via trial and error to look about right to me.
> LibCards+Hearts: Keep markings visible on very dark or light backgrounds

- Base/usr/share/man/man1/pkg.md
- Base/usr/share/man/man5/installed.md
- Userland/Utilities/pkg/InstalledPort.cpp
- Userland/Utilities/pkg/InstalledPort.h
- Userland/Utilities/pkg/main.cpp
This mainly makes pkg actually capable of reading `dependency` lines, and fixes an oversight in the file name. I also took this opportunity and refactored how dependencies are stored internally, since it makes more semantical sense this way.
CC @supercomputer7
The access() check was on the wrong file previously.
The "dependency" lines really belong to the main port entry, it doesn't
make sense logically to represent them separately and handling them
together will also allow easier dependency management later on. This
commit greatly simplifies the port database parsing to facilitate this,
and removes the -d option from the command line. Instead, ports are
listed with their dependencies, if they have any.
> pkg: Fix reading the installed package database and improve dependency parsing

- .github/CODEOWNERS
I'll continue to do reviews in a normal capacity, it just feels kind of dishonest to be listed as a codeowner if I'm way out of my depth half of the time. :^)
Adding Daniel to `readelf.cpp` in my place I have discussed with him in advance.
> Meta: Remove myself from LibELF-related CODEOWNERS entries

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Runtime/ArgumentsObject.h
- Userland/Libraries/LibJS/Runtime/IndexedProperties.h
- Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.h
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ProxyObject.h
- Userland/Libraries/LibJS/Runtime/StringObject.h
- Userland/Libraries/LibJS/Runtime/TypedArray.h
- Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.h
- Userland/Libraries/LibWeb/HTML/AudioTrackList.h
- Userland/Libraries/LibWeb/HTML/Location.h
- Userland/Libraries/LibWeb/HTML/VideoTrackList.h
- Userland/Libraries/LibWeb/HTML/WindowProxy.h
This yields a whopping 28.4% speed-up on the entire Kraken benchmark:
```
Suite    Test                                   Speedup  Old Std Dev (%)    New Std Dev (%)    Old CI               New CI
-------  -----------------------------------  ---------  -----------------  -----------------  -------------------  -------------------
Kraken   ai-astar.js                           1.13818   1.69%              1.64%              6.895094-9.357817    6.994254-7.285441
Kraken   audio-beat-detection.js               1.77504   1.76%              1.90%              6.809037-9.358706    4.446562-4.661837
Kraken   audio-dft.js                          1.31805   2.04%              1.63%              3.818871-5.534287    3.476439-3.619786
Kraken   audio-fft.js                          1.7694    1.54% …
```
> LibJS: Add fast paths for array-like Get/Put with Int32 indexes

- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/AtomicsObject.cpp
Two patches for 4% speed-up on Octane/gbemu.js each. :^)
> LibJS: Avoid ByteBuffer copying in RawBytesToNumeric and NumericToRawBytes

- Base/usr/share/man/man1/grep.md
- Userland/Utilities/grep.cpp
- **Add comment describing why we take leading characters from paths**
- **Remove separate stdin handling logic**
Previously we had two somewhat duplicated methods: one just for handling stdin with the standard C API, and the other one used for everything else with our Core::File class. By using always Core::File, the code should be now a little bit cleaner.
Additionally, grep will now use the standard input when it finds a '-' argument (previously it tried to open a file with that name.)
- **Don't end the program early after failing to grep a file**
We should still try to read remaining files.
- **Return exit code '2' on error**  
- **Print filenames when counting lines and path size is less than 2**
`grep --count --recursive foo` doesn't specify any file, but we should show the paths …
> grep: Hyperlink filenames in tty & other small fixes found along the way

- Ladybird/Qt/BrowserWindow.cpp
This change makes it possible to open a specific tab by using Ctrl/Command plus the number key corresponding to its position in the tab row.
This mirrors the behavior of other browsers like Chromium and Firefox (and the Serenity browser! :^)).
> Ladybird: Add keyboard shortcuts for jumping to a specific tab

- Kernel/Devices/Storage/SD/Registers.h
This view is really nice to check flags, but when clearing them we must make sure that we only ever try to set 1 bit at a time, which makes setting bits through the structured view a footgun, as that fetches, ors in and then sets, potentially resetting other flags.
---
Some time ago I learned, you can mark struct member declarations as `const`
> Kernel: Mark SDHC InterruptStatus structured view as const

- AK/PrintfImplementation.h
- Tests/LibC/TestSnprintf.cpp
We previously ignored the "presence" of the precision if not at least one number or an asterisk follows.
Fixes #623. Or rather, puts in the last missing piece.
> AK: Implement printf's "period without precision value" correctly

- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Previously this simply added the widths of each glyph, not accounting for glyph spacing. For now this fixes only that issue.
> LibWeb/Canvas: Calculate text width for measureText correctly

- Userland/Libraries/LibHTTP/HttpRequest.cpp
- Userland/Libraries/LibHTTP/HttpRequest.h
This fixes oss fuzz issue [62046](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62046)
Tested by feeding the fuzzer test case into the following program:
```c++
#include <LibMain/Main.h>
#include <LibHTTP/HttpRequest.h>
ErrorOr<int> serenity_main(Main::Arguments)
{
auto stdin = TRY(Core::File::standard_input());
auto data = TRY(stdin->read_until_eof());
auto request_wrapper = HTTP::HttpRequest::from_raw_request(data);
if (request_wrapper.is_error())
return Error::from_string_literal("Task failed successfully!");
auto& request = request_wrapper.value();
VERIFY(request.method() != HTTP::HttpRequest::Method::Invalid);
return 0;
}
```
> LibHTTP: Return an error if HTTP request URL is not valid UTF-8

- Userland/Libraries/LibGUI/FileSystemModel.cpp
- Userland/Libraries/LibGUI/FileSystemModel.h
Instead of updating the UI after each thumbnail is generated, we now only update the UI every 100ms. This improves the responsiveness of FileManager when navigating directories with lots of small thumbnails.
There are still opportunities to improve performance further here, but this change at least makes `/res/emoji` navigable, whereas previously it would lock up the system for a significant amount of time.
Demo (from a cold reboot):
https://github.com/SerenityOS/serenity/assets/2817754/75d449b8-5e69-413c-933b-2cff403834e3
Fixes #20906
> LibGUI: Improve responseiveness when generating lots of thumbnails

- Tests/LibIMAP/TestQuotedPrintable.cpp
- Userland/Libraries/LibIMAP/QuotedPrintable.cpp
This fixes oss fuzz issues: [62064](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62064), [42993](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42993) and [40909](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40909).
Tested by feeding fuzzer test cases into the following program:
```c++
#include <LibMain/Main.h>
#include <LibIMAP/QuotedPrintable.h>
ErrorOr<int> serenity_main(Main::Arguments)
{
auto stdin = TRY(Core::File::standard_input());
auto data = TRY(stdin->read_until_eof());
TRY(IMAP::decode_quoted_printable(data));
return 0;
}
```
> LibIMAP: Handle invalid escape sequences in Quoted-Printable parser 

- Userland/Libraries/LibTLS/TLSv12.h
This changes the order of ciphersuites we send to servers, so that we sent the strongest suites first.
Order is taken from https://ssl-config.mozilla.org/guidelines/5.7.json, the latest version of [Mozilla recommended suites](https://wiki.mozilla.org/Security/Server_Side_TLS)
`configurations->old->ciphers->iana`
> LibTLS: Reorder supported ciphers

- Userland/Libraries/LibGfx/ICC/Profile.cpp
Fixes oss fuzz issues [62030](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62030), [60281](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60281) and [57461](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57461)
> LibGfx/ICC: Avoid overflow when checking tag bounds

- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
The functions for registering and unregistering MarkedVector, Handle, etc. were quite prominent in benchmark profiles.
4% speed-up on the entire Kraken benchmark :^)
(including: 7% speed-up on Kraken/imaging-gaussian-blur.js, the current slowest subtest)
> LibJS: Move Heap intrusive list manipulation inline

- Userland/Games/GameOfLife/BoardWidget.cpp
- Userland/Games/GameOfLife/BoardWidget.h
- Userland/Games/GameOfLife/CMakeLists.txt
- Userland/Games/GameOfLife/GameOfLife.gml
- Userland/Games/GameOfLife/MainWidget.h
- Userland/Games/GameOfLife/main.cpp
- Userland/Libraries/LibGUI/Statusbar.h
This PR makes the following changes to `GameOfLife`:
* The GML compiler is now used to construct the main widget. This required a small change to LibGUI to make `Statusbar::set_segment_count` public so that the GML compiler can use it. Making this method public also allows the segement count to be changed at runtime.
* The game board is now in focus on startup. Interacting with the game board now sets focus on it. This makes single key shortcuts work again.
* Pressing escape with a pattern selected now clears that pattern.
> GameOfLife: Make single key shortcuts work again

- Userland/Shell/AST.h
- Userland/Shell/PosixLexer.cpp
- Userland/Shell/PosixLexer.h
- Userland/Shell/PosixParser.cpp
- Userland/Shell/PosixParser.h
This is currently only allowed in assignments, where x=(...) is parsed as the assignment of the list (...) to the variable x.
> Shell: Add support for the bashy list literals in POSIX mode

- Userland/Libraries/LibWeb/DOM/Document.cpp
This change fixes the bug where navigable containers related to a document, but not present in the tree, were never destroyed.
Fixes https://github.com/SerenityOS/serenity/issues/21364
> LibWeb: Destroy navigable containers not inserted into document tree

- Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-padding-on-flex-container.txt
- Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-padding-on-flex-container.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
We were incorrectly offsetting the static position of abspos children of flex containers by the padding twice. This was a misguided attempt to adjust to the abspos containing block being the padding box, not the content box.
Fixes #21344.
> LibWeb: Don't offset abspos children of flex container by padding twice

- Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
This PR also removes redundant bit depth validation added in #21316. Bit depth validation was already done later on, but adding it earlier masked the underlying issue, which this PR fixes.
This fixes oss fuzz issue [63052](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63052).
> LibGfx/PNGLoader: Don't allow multiple consecutive IHDR chunks

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
When we hit the cache in GetGlobal, we don't need the identifier string at all, so let's defer fetching it until after the cache miss.
7% speed-up on Kraken/imaging-gaussian-blur.js :^)
> LibJS: Avoid IdentifierTable lookup in cached GetGlobal op

- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
Navigable should be created for an iframe only, if after insertion, its root is the document.
Fixes https://github.com/SerenityOS/serenity/issues/21374
> LibWeb: Create navigables only for iframe in a document tree

- AK/Format.cpp
- Tests/AK/TestFormat.cpp
This fixes oss fuzz issue [57633](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57633)
> AK: Avoid overflow when passing i64 minimum value to `vformat()`

- Userland/Libraries/LibJS/Forward.h
Turns out this was hurting performance instead of helping it. By removing the inline capacity, we shrink the size of ExecutionContext by 512 bytes, which substantially reduces the stack pressure created by JS recursion (each call creates a new ExecutionContext on the stack).
4.4% speed-up on the entire Kraken benchmark :^)
> LibJS: Remove inline capacity from MarkedVector

- README.md
Due to the removal of libjs.dev, replace the test262 link with the
test262.fyi counterpart and remove WASM link.
GitHub allows relative paths to be used to display images, this should
make the image continue working even when viewing the README from an
earlier commit of the repo in case the location of screenshots is moved.
This is also just a cleaner way to do this.
> Meta: Misc README fixes

- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
I solemnly swear that I stumbled upon this randomly while participating in a CTF.
> LibCompress: Fix a typo in `m_read_final_block`

- Tests/LibCompress/TestDeflate.cpp
- Userland/Libraries/LibCompress/Deflate.cpp
Previously, decompressing a DEFLATE stream an invalid canonical Huffman code could cause a buffer overrun. We now return an error in this case.
This bug frequently crashes both `FuzzGzipDecompression` and `FuzzZlibDecompression`, so this fix should allow both fuzzers to make more progress.
This fixes oss fuzz issues:  [62027](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62027), [58967](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58967) and [59770](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59770).
> LibCompress: Avoid buffer overrun when building canonical Huffman code

- AK/MemoryStream.h
- Tests/AK/TestMemoryStream.cpp
- Tests/LibGfx/TestFontHandling.cpp
- Userland/Applications/FontEditor/MainWidget.cpp
- Userland/Applications/FontEditor/NewFontDialog.cpp
- Userland/Applications/FontEditor/UndoSelection.h
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibCore/System.h
- Userland/Libraries/LibGfx/Font/BitmapFont.cpp
- Userland/Libraries/LibGfx/Font/BitmapFont.h
- Userland/Libraries/LibGfx/Font/Font.h
I found it a bit spooky how much manual pointer manipulation was happening in `BitmapFont::load_from_memory(u8*)` (and the fact that it had zero bounds checking) so let's fix that! Its fields are now Span/Bytes, we load using streaming methods so we don't have to keep track of offsets, and besides being safe from buffer overruns, we also make sure there's no data left over.
To help with this, I've added a couple of methods to FixedMemoryStream to read values "in place", meaning we get some kind of pointer into the fixed memory instead of making a copy of it.
There are also a few other small changes to things while I was at it.
> LibGfx: Replace raw pointers in BitmapFont code, and other tidying up

- Meta/Lagom/Contrib/MacPDF/CMakeLists.txt
- Meta/Lagom/Contrib/MacPDF/MacPDFOutlineViewDataSource.h
- Meta/Lagom/Contrib/MacPDF/MacPDFOutlineViewDataSource.mm
- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.h
- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
Follow-up to #21361.
In addition to things I'm confused about in comments and commit descriptions, I also was a bit confused by the layout constraints system (which NSSplitViewController requires). Initially, I made the NSOutlineView the only view in the left sidebar. But since the outline has a preferred size, that apparently gets translated into hard constraints, and the window height then snaps to the height of the outline and the height can no longer be changed when resizing the window. If the current PDF had no outline, that had the effect of snapping the window to a very small height. So the outline has to be put in a containing view, but `autoresizingMask` defaults to NSViewNotSizable, so nothing showed up at first. (Beginner mistake, but hey.) And debugging constraints isn't very …
> MacPDF: Show PDF outline in sidebar view

- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
I broke this when moving from a xib file to creating the UI in code (…in #21361).
https://developer.apple.com/documentation/appkit/nsuserinterfaceitemidentification/1396829-identifier says:
"Identifiers are used during window restoration operations to uniquely identify the windows of the application. [...] If you create an item in Interface Builder and do not set a value for this string, a unique value is created for the item when the nib file is loaded. For programmatically created views, you typically set this value after creating the item but before adding it to a window."
Without this, encodeRestorableStateWithCoder: / restoreStateWithCoder: in MacPDFView weren't getting called.
> MacPDF: Unbreak persisting the current page

- Userland/Libraries/LibVideo/VP9/Decoder.cpp
- Userland/Libraries/LibVideo/VP9/Parser.cpp
This PR makes 3 simple changes to VP9 decoding.
* We now return an error when the color config for a frame has an invalid chroma subsampling format. I left the FIXME in place here, as what it says is still true. I had a quick look at `libvpx` and it also [returns an error in this case](https://github.com/webmproject/libvpx/blob/7c31749387e0297a16289ba851559df4fd2f935d/vp9/decoder/vp9_decodeframe.c#L2615)
* Overflow is now avoided when performing in place butterfly rotation.
* A check for an invalid block size is now performed after calling `Parser::get_subsampled_block_size()`
Fixes oss fuzz issues: [62054](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62054), [60386](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60386), …
> LibVideo/VP9: Fix some simple fuzzer issues

- Tests/LibWeb/Layout/expected/block-and-inline/inline-node-not-inserted-into-generated-box.txt
- Tests/LibWeb/Layout/input/block-and-inline/inline-node-not-inserted-into-generated-box.html
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
493dd5d93cce6ec2afd9c49bf0e67d78247a1191 caused the `::before` pseudo-element node to be inserted before the element's content, which caused issues with how we determine where to insert inline nodes into the layout tree. At the time, I noticed the issue with contents of flex containers, and prevented them from merging into a `::before` box.
However, a similar situation happens when we're not in a flex container, but the pseudo-element has `display: block`. This commit fixes that situation by using the same logic in both places, so a similar mistake can't be made again.
This fixes the tab text being invisible on GitHub project pages. :^)
> LibWeb: Stop inserting inline nodes into a generated wrapper box

- Tests/LibWeb/Layout/expected/calc-with-fr.txt
- Tests/LibWeb/Layout/input/calc-with-fr.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Fixes crash on https://signal.org/
> LibWeb/CSS: Parser should treat calc() with flex values as invalid

- Meta/Lagom/CMakeLists.txt
- Tests/LibTLS/CMakeLists.txt
- Tests/LibTLS/TestTLSCertificateParser.cpp
- Userland/Libraries/LibTLS/Certificate.cpp
This allows the decoder to fail gracefully when reading a partial or malformed TBSCertificate. We also now ensure that the certificate data is valid before making a copy of it.
This fixes oss fuzz issue [62026](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62026)
Tested by feeding the fuzzer test case into the following program:
```c++
#include <LibMain/Main.h>
#include <LibTLS/Certificate.h>
ErrorOr<int> serenity_main(Main::Arguments)
{
auto stdin = TRY(Core::File::standard_input());
auto data = TRY(stdin->read_until_eof());
TRY(TLS::Certificate::parse_certificate(data));
return 0;
}
```
> LibTLS: Don't attempt to read past EOF when parsing TBSCertificate

- Userland/Libraries/LibVideo/VP9/Parser.cpp
This fixes oss fuzz issue [63182](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63182)
> LibVideo/VP9: Ensure color space is not set to reserved value

- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
This fixes oss fuzz issues [63177](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63177) and [60465](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60465)
> LibGfx/BMPLoader: Ensure data offset cannot point past EOF

- AK/BuiltinWrappers.h
The original doc comment was mistakenly copy-pasted from count_leading_zeroes_safe, and incorrect. The function is doing something else: it's counting _trailing_ zeroes instead of _leading_ ones.
> AK: Fix doc comment for bit_scan_forward

- Meta/CMake/use_linker.cmake
When this feature was finally merged, the serenity_option in lagom_options.cmake had the unintended side effect of always setting the cache variable to "" in the initial cache. In order to actually set the linker to use to be lld or mold, we need to set with the FORCE flag in the use_linker.cmake file.
Found by checking with the CMake variable_watch() function.
This will stop the build from spamming the "Using LLD to link Lagom" message all over the place :^)
> CMake: Actually set the LAGOM_USE_LINKER option automatically

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Userland/Libraries/LibWeb/HTML/Location.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
Using structs makes the navigate() calls looks cleaner. No change in behavior is intended.
> LibWeb: Use struct to pass Navigable::navigate() params

- Meta/Lagom/Contrib/MacPDF/MacPDFView.h
- Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.h
- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
- Meta/Lagom/Contrib/MacPDF/MainMenu.xib
When the outline has focus, arrow keys navigate the outline instead
of changing the current page.
Add opt-up and opt-down as a way to move by one page even when the
outline has focus. (This matches Preview.app.)
Also make up and down flip pages when the pdf view has focus,
in addition to left/right and opt-up / opt-down.
> MacPDF: Make opt-up and opt-down always go to previous / next page

- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Painting/FilterPainting.cpp
- Userland/Libraries/LibWeb/Painting/FilterPainting.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Instead of resolving lengths used in the backdrop-filter during painting, we can do that earlier in apply_style().
This change moves us a bit closer to the point when the stacking context tree will be completely separated from the layout tree :)
> LibWeb: Resolve backdrop filter length in apply_style()

- Userland/Applets/ClipboardHistory/ClipboardHistoryModel.cpp
- Userland/Libraries/LibGUI/Clipboard.cpp
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGfx/Bitmap.cpp
- Userland/Libraries/LibGfx/Bitmap.h
- Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/ShareableBitmap.cpp
- Userland/Services/WindowServer/ConnectionFromClient.cpp
- Userland/Utilities/image.cpp
These are only used by the BMP image decoder, which already has a path for decoding to BGRA8888 which we can simply reuse for every input format.
> LibGfx: Remove indexed palette formats from Bitmap and Painter

- Userland/Libraries/LibWeb/SVG/SVGUseElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGUseElement.h
We currently store a `StringView` into the `DeprecatedString` provided to `SVGUseElement::attribute_changed`. This is a temporary string created by `String::to_deprecated_string`, so this `StringView` is always a dangling pointer.
Instead, since this string value is an ID and is primarily used as a `FlyString`, store it as a `FlyString` from the get-go.
Fixes #21413.
> LibWeb: Store the SVG `<use>` element's referenced ID as a FlyString

- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Now that we implement this member function, let's use it to keep things DRY.
> LibWeb/HTML: Use MimeType::is_xml() in HTMLObjectElement for DRYness

- Userland/Libraries/LibC/crt0.cpp
- Userland/Libraries/LibC/libcinit.cpp
- Userland/Libraries/LibC/stdlib.cpp
- Userland/Libraries/LibELF/DynamicLinker.cpp
- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicObject.cpp
- Userland/Libraries/LibELF/DynamicObject.h
This PR makes `exit()` correctly call all destructors according to https://www.sco.com/developers/gabi/latest/ch5.dynamic.html#init_fini.
The `_init()` and `_fini()` in crt0.cpp and stdlib.cpp's `exit()` are unnecessary as we call them in the dynamic linker and we don't care about statically linked executables anymore.
> LibC+LibELF: Call destructors on `exit` and clean up crt0

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
We'd unconditionally get the int from a Variant<int, float> here, but PDFs often have a float for defaultWidthX and nominalWidthX.
Fixes crash opening Bakke2010a.pdf from pdffiles (but while the file loads ok, it looks completely busted).
> LibPDF: Don't crash on files with float CFF defaultWidthX

- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/AppKit/UI/TabController.mm
This lets the user zoom in and out on a web page using the View menu or keyboard shortcuts. This does not implement zooming with ctrl+scroll.
In the future, it'd be nice to embed the zoom level display inside the location toolbar. But to do that, we will need to invent our own custom search field and all of the UI classes (controller, cell, etc.) to draw the field. So for now, this places the zoom level display to the right of the location toolbar.
https://github.com/SerenityOS/serenity/assets/5600524/690b79dc-5f6f-415a-92b5-c779a13f1538
> Ladybird: Implement content zooming in the AppKit chrome

- Userland/Applications/Mail/MailWidget.cpp
- Userland/Libraries/LibIMAP/Objects.h
- Userland/Libraries/LibIMAP/Parser.cpp
- Userland/Libraries/LibIMAP/Parser.h
- Userland/Utilities/test-imap.cpp
This makes the parser more resilient to invalid IMAP messages.
Usages of `Optional` have also been removed where the empty case is equivalent to an empty object.
Let me know if I should split the removal of the `Optional` types into a separate commit. I ended up doing everything together to avoid changing the same code more than once in the same PR.
I tested this against a new `outlook.com` email address I set up, with a few plain-text only emails. Trying to log in to my gmail account failed (with 2 factor authentication + app passwords). I also set up a new gmail account and tried that with a normal password; this also failed.
The Mail application can quite easily hang when navigating around different folders and messages. I don't think those issues are related to this change though, as …
> LibIMAP: Stop parsing immediately on error

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
HTTP methods are case sensitive and the Fetch layer treats it as such. For example, http_redirect_fetch case sensitively checks if the method is "POST" to change the method to "GET" and nullify the body. https://github.com/SerenityOS/serenity/blob/9d7e2175663eff6a00b176d4e1873b10836ee992/Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp#L1125-L1135
Fixes https://github.com/SerenityOS/serenity/issues/21347
> LibWeb: Use "POST" instead of "post" for POST resources in navigables

- Userland/Libraries/LibWeb/DOM/Node.cpp
Regression/typo from aeee98b, this lead to a crash when opening the DOM inspector.
> LibWeb: Fix null optional dereference in Node::name_or_description()

- Userland/Libraries/LibWeb/DOM/Element.cpp
The UnicodeData header cannot be included by any file other than .cpp files within LibUnicode itself. Outside users cannot assume the header will exist, as it will not be generated if the CMake option to do so is disabled (ENABLE_UNICODE_DATABASE_DOWNLOAD).
Should fix a GN dependency issue Andrew ran into.
> LibWeb: Remove use of UnicodeData header from DOM::Element

- Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
This fixes oss fuzz issue: [62033](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62033)
> LibGfx/ILBM: Avoid buffer overrun when reading header chunk

- Kernel/Arch/init.cpp
Moving the DeviceManagement initialization, which is only needed by
userland in the first place, to after interrupt and time management
initialization (like other things that require randomness) allows the
SipHash initialization to access good randomness without problems.
Note: There currently is another, unrelated boot problem on aarch64,
which is not caused by SipHash as far as we know. This commit therefore
only fixes the SipHash regression.
> Kernel: Fix SipHash aarch64 boot regression

- Userland/Applications/3DFileViewer/main.cpp
- Userland/Libraries/LibGL/GLContext.cpp
- Userland/Libraries/LibGL/GLContext.h
- Userland/Libraries/LibGL/Matrix.cpp
- Userland/Libraries/LibGL/Vertex.cpp
- Userland/Libraries/LibGPU/Device.h
- Userland/Libraries/LibSoftGPU/Clipper.cpp
- Userland/Libraries/LibSoftGPU/Device.cpp
- Userland/Libraries/LibSoftGPU/Device.h
- Userland/Libraries/LibVirtGPU/Device.cpp
- Userland/Libraries/LibVirtGPU/Device.h
* 3DFileViewer: Show the correct frame rate, try to run at 60 FPS
* LibGL+Lib*GPU: Optimize normal transformation calculation
* LibGL & LibSoftGPU: Optimize vertex appends by performing safe unchecked appends
On my machine this yields some small FPS improvements:
| Game | Old FPS | New FPS |
| --- | --- | ---
| glquake | 20.4 | 21.4 (+5%) |
| quake3 | 10.7 | 11.1 (+4%) |
| tuxracer | 25.6 | 26.1 (+2%) |
> 3DFileViewer+LibGL+Lib*GPU: Small performance improvements

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
first_sid has type SID (aka u16), so don't store it in an u8.
This fixes (among other things) page 24 on the PDF 1.7 spec.
-----
(Also requires the fixes from #21436, else all the spaces on that page are replaced with small superscript 1s.)
> LibPDF: Don't overflow SIDs in type 1 charset parsing (and implement type 2)

- Userland/Libraries/LibGUI/FileSystemModel.cpp
- Userland/Libraries/LibGUI/FileSystemModel.h
Previously, the null state of m_root_path was use to (subtly) mark the parent of the root. The empty path is always replaced with "." so after aeee98b there was no "parent of root" node. This lead to the file manager crashing when opened.
> LibGUI: Fix FileSystemModel/FileManager after aeee98b

- Tests/LibGfx/TestGfxBitmap.cpp
- Userland/Libraries/LibGfx/Bitmap.cpp
a396bb0 removed the palette field but did not update the allocation size in `Bitmap::serialize_to_byte_buffer()`. This led to a few crashes (I noticed this from a drag/drop crash in the file manager).
Fixes #21434
> LibGfx: Fix serializing Gfx::Bitmaps

- Base/usr/share/man/man7/boot_parameters.md
- Kernel/Arch/x86_64/ISABus/I8042Controller.cpp
- Kernel/Boot/CommandLine.cpp
- Kernel/Boot/CommandLine.h
- Kernel/Bus/USB/Drivers/HID/Codes.h
- Kernel/Bus/USB/Drivers/HID/MouseDriver.cpp
- Kernel/Bus/USB/Drivers/HID/MouseDriver.h
- Kernel/Bus/USB/UHCI/UHCIController.cpp
- Kernel/Bus/USB/USBTransfer.cpp
- Kernel/CMakeLists.txt
- Kernel/Devices/HID/Device.h
- Kernel/Devices/HID/Management.cpp
- Kernel/Devices/HID/Management.h
- Kernel/Devices/HID/USB/MouseDevice.cpp
- Kernel/Devices/HID/USB/MouseDevice.h
To test this, add the following parameters to `run.sh`:
```
-M pc,i8042=off
-machine vmport=off
-device usb-mouse
```
Derived from #18673. We can get this merged quite quickly and later on figure out the details for HID keyboards, including USB ones.
cc @FireFox317
> Kernel: Add USB mouse support

- Ports/curl/package.sh
According to the issue https://github.com/curl/curl/issues/12093 the curl build doesn't properly detect that Serenity has getaddrinfo() and outputs the following:
```
Performing Test HAVE_H_ERRNO_ASSIGNABLE
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
HAVE_H_ERRNO_ASSIGNABLE_EXITCODE (advanced)
```
Setting the CMake cache variable HAVE_GETADDRINFO_THREADSAFE=1 solves the mentioned error.
Also see: https://github.com/curl/curl/pull/12094
> Ports/curl: Set CMake cache variable HAVE_GETADDRINFO_THREADSAFE to 1

- Userland/Libraries/LibWeb/CSS/Default.css
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Instead of a plain ButtonBox, it now appears as a color well styled after the buttons.
https://github.com/SerenityOS/serenity/assets/39885272/62cf2e14-7fe1-4ff6-bb9c-d0470f271d09.mp4
> LibWeb/HTMLInputElement: Improve appearance of color picker

- AK/DeprecatedString.cpp
Prior to this commit, constructing a DS from a null DFS would cause a nullptr deref, which broke (at least) Profiler.
This commit converts the null DFS to an empty DS, avoiding the nullptr deref (until DFS loses its null state, or we decide to not make it convertible to a DS).
cc @gmta @tcl3 (thanks for boog report)
> AK: Avoid nullptr deref in DeprecatedString(DeprecatedFlyString const&)

- Tests/LibWeb/Layout/expected/block-and-inline/inline-block-contained-by-abspos-element.txt
- Tests/LibWeb/Layout/input/block-and-inline/inline-block-contained-by-abspos-element.html
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
If inline-block is sized under min-content width constraint we should use its min-content width instead of max-content width like it was before.
> LibWeb: Fix min-content width calculation in dimension_box_on_line()

- Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Previously, the decoder would crash in this case.
This fixes oss fuzz issue: [63296](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63296).
> LibGfx/ILBM: Explicitly fail decoding if body chunk isn't present

- Kernel/Arch/init.cpp
- Kernel/Devices/Storage/StorageManagement.cpp
- Kernel/Devices/Storage/StorageManagement.h
- Meta/run.sh
This gives us enough time to discover more devices, such as USB drives
---
This allows us to boot from USB drives
to test this apply the following patch
(No fancy test mode included as of yet)
```diff
diff --git a/Meta/run.sh b/Meta/run.sh
index a2dd7308be..ebb3a86f49 100755
--- a/Meta/run.sh
+++ b/Meta/run.sh
@@ -240,22 +240,27 @@ if [ -z "$SERENITY_QEMU_DISPLAY_DEVICE" ]; then
fi
fi
-if [ "$SERENITY_ARCH" = 'aarch64' ]; then
-    SERENITY_BOOT_DRIVE="-drive file=${SERENITY_DISK_IMAGE},if=sd,format=raw"
-elif [ -z "${SERENITY_NVME_ENABLE}" ] || [ "${SERENITY_NVME_ENABLE}" -eq 1 ]; then
-    # NVME is enabled by default; disable by setting SERENITY_NVME_ENABLE=0
-    SERENITY_BOOT_DRIVE="-drive file=${SERENITY_DISK_IMAGE},format=raw,index=0,media=disk,if=none,id=disk"
- …
```
> Kernel: Enable boot from USB

- Userland/Libraries/LibTest/Macros.h
Previously VERIFY et al. was redefined inside tests to not abort and instead fail the test. This wouldn't apply to non-header code though, and was not helpful, as it prevented you from easily attaching gdb near the abort.
After this removal tests can still use the EXPECT family of macros, but VERIFY will behave like it does in the rest of the codebase (abort etc.).
> LibTest: Remove the redefinition of VERIFY family of macros

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
- Userland/Libraries/LibWeb/HTML/SharedImageRequest.h
This change addresses the bug where images unable to load when the reload button in the UI is clicked repeatedly. Before this fix, it was possible to use SharedImageRequests across multiple documents. However, when the document that initiated the request is gone, tasks scheduled on the event loop remain in the fetching state because the originating document is no longer active. Furthermore, another reason to prohibit the sharing of image requests across documents is that the "Origin" header in an image request is dependent on the document.
> LibWeb: Forbid sharing image requests across documents

- Userland/Libraries/LibPDF/Fonts/PS1FontProgram.cpp
https://adobe-type-tools.github.io/font-tech-notes/pdfs/T1_SPEC.pdf :
"Using charstring subroutines is not a requirement of a Type 1 font program."
And some versions of Computer Modern do in fact not contain a Subrs array.
Together with #21473, makes Problemset.pdf from the pdffiles repro render ok instead of crashing.
> LibPDF: Make Subrs optional in PS1FontProgram

- Userland/Libraries/LibPDF/Reader.h
CFF::parse_index_data() calls move_to() to put the reader's current position behind the index data.
In several PDFs, the PrivDictOperator::Subrs case in CFF::create() sets up a span that contains exactly the Subrs data and nothing after it, so that finale move_to() call in parse_index_data() would cause an assert.
This is similar to fe3612ebcb5, where the caller was also in CFF. So maybe CFF just has a different view of what valid values to pass to Reader are, compared to the rest of the code? But having an iterator point to one past the valid data in a container is common, so maybe this is the Right Fix after all.
Fixes a crash opening 411_getting_started_with_instruments.pdf (and a whole bunch of other WWDC slides). Rendering is pretty glitchy and we still crash on page 14, but at least …
> LibPDF: Allow moving Reader::move_to() to end of data stream

- Base/usr/share/man/man1/find.md
- Userland/Utilities/find.cpp
These options behave the same way as `-name` and `-iname` but match the full file path instead of just the basename.
Example usage:
> find: Add the `-path` and `-ipath` options

- Userland/Libraries/LibGfx/Bitmap.cpp
- Userland/Libraries/LibGfx/Bitmap.h
- Userland/Libraries/LibPDF/Renderer.cpp
Size of smask and image aren't guaranteed to be equal by the spec (...except for /Matte, see page 555 of the PDF 1.7 spec, but we don't implement that), and in pratice they sometimes aren't.
Fixes an assert on page 4 of
https://devstreaming-cdn.apple.com/videos/wwdc/2017/821kjtggolzxsv/821/821_get_started_with_display_p3.pdf We now make it all the way to page 43 of 64 before crashing.
> LibPDF: If softmask has different size than target bitmap, resize it

- Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
- Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.h
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
- Userland/Libraries/LibWeb/Painting/ShadowPainting.h
Painting optimizations to do less unnecessary work.
> LibWeb/Painting: Do not clip border radius when it is out of viewport

- Base/usr/share/man/man1/du.md
- Userland/Utilities/du.cpp
> du: Add `-x` option to not traverse directories across filesystems

- Userland/Libraries/LibPDF/Renderer.cpp
- Userland/Libraries/LibPDF/Renderer.h
Implements the `ri` operator, and the `RI` key in a graphics state dictionary.
We don't do anything yet with the color rendering intent except store it.
No behavior change except removing a few "not yet implemented" messages.
> LibPDF: Implement color_rendering_intent operator

- Meta/Lagom/Contrib/MacPDF/AppDelegate.mm
I would've expected that there's some way to have this work automatically in an NSDocument-based application, but I haven't found it yet. So manually implement the delegate for now.
> MacPDF: Make "Open With" and dropping files on dock tile work

- Userland/Libraries/LibPDF/Fonts/PDFFont.cpp
Liberation*-BoldItalic.ttf apparently self-identifies as "Bold Italic", not "BoldItalic".
> LibPDF: Fix lookup of built-in Bold Italic strings

- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Fixes two places in child navigable destroy procedure where we used content navigable instead of container's navigable.
With this change, iframe's nested histories are actually destroyed along with the document that created them.
> LibWeb: Fix spec implementation mistakes in destroy_the_child_navigable

- Ladybird/AppKit/UI/TabController.mm
- Ladybird/Qt/LocationEdit.cpp
- Userland/Applications/Browser/CMakeLists.txt
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Applications/Browser/URLBox.cpp
- Userland/Applications/Browser/URLBox.h
- Userland/Libraries/LibGUI/Forward.h
- Userland/Libraries/LibGUI/TextBox.cpp
- Userland/Libraries/LibGUI/TextBox.h
- Userland/Libraries/LibWebView/URL.cpp
- Userland/Libraries/LibWebView/URL.h
> Ladybird+LibWebView: Use Public Suffix List for deciding eTLD+1, and highlight AppKit's URL bar

- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/ColorSpace.h
- Userland/Libraries/LibPDF/CommonNames.h
- Userland/Libraries/LibPDF/Renderer.cpp
We now no longer crash on images that use an ICC-based color space.
Reduces number of crashes on 300 random PDFs from the web (the first 300
from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/)
from 81 (27%) to 64 (21%).
Also fixes all remaining crashes in
411_getting_started_with_instruments.pdf and
513_high_efficiency_image_file_format.pdf.
---
Note that `DCTDecode` (ie jpegs) early-exit before this code runs, so jpegs in PDFs currently aren't color-managed.
> LibPDF: Implement ICCBasedColorSpace::number_of_components(), and other minor image tweaks

- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
...which causes us to not render these fonts instead of crashing.
Reduces number of crashes on 300 random PDFs from the web (the first 300 from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/) from 64 (21%) to 42 (14%).
> LibPDF: Replace TODO()s in Type0Font code with Errors

- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/ColorSpace.h
- Userland/Libraries/LibPDF/Renderer.cpp
Per spec:
"If the color space is one that can be specified by a name and no
additional parameters (DeviceGray, DeviceRGB, DeviceCMYK, and certain
cases of Pattern), the name may be specified directly."
We still don't implement /Pattern color spaces, but now we no longer
crash trying to look up the potentially-nonexistent /ColorSpace
dictionary on the page object when /Pattern is used directly as color
space name.
On top of https://github.com/SerenityOS/serenity/pull/21514, reduces number of crashes on 300 random PDFs from the
web (the first 300 from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/)
from 42 (14%) to 34 (11%).
> LibPDF: Allow /Pattern to be used directly as a color space name

- AK/URLParser.cpp
~~Might as well complete `is_url_code_point()` while we're at it since it is used in one spec step.~~
~~Manually tested the code paths by manipulating this URL that contains an opaque host (thanks to the URL spec for the example):~~
~~`git://github.com/whatwg/url.git`~~
Edit: Given feedback, this PR only adds spec comments to `parse_opaque_host()` instead of implementing the two missing spec steps and implements `is_url_code_point()` to meet the spec.
> AK/URLParser: Complete implementation of `is_url_code_point()`

- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/ColorSpace.h
- Userland/Libraries/LibPDF/Renderer.cpp
- Userland/Libraries/LibPDF/Renderer.h
Not used terribly often, but e.g. used in 000333.pdf page 17 in
stillhq.com-pdfdb.
---
Before:
After:
> LibPDF: Implement text_next_line_show_string_set_spacing

- Tests/LibWeb/Layout/expected/grid/container-min-height.txt
- Tests/LibWeb/Layout/input/grid/container-min-height.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
If the first pass of rows sizing results in the container's automatic height being less than the specified min-height, we need to run a second pass using the updated available space.
> LibWeb: Rerun rows sizings if grid auto height is less than min-height

- Tests/LibWeb/Layout/expected/grid/abspos-item-aligned-center.txt
- Tests/LibWeb/Layout/input/grid/abspos-item-aligned-center.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Grid items should respect alignment properties if top/right/bottom/left are not specified.
This change adds a separate implementation of
layout_absolutely_positioned_element that is extended with support for alignment.
> LibWeb: Support alignment of abspos grid items

- Userland/Libraries/LibPDF/Renderer.cpp
Like ca1a98ba9f2, but for stroke color.
> LibPDF: Replace another TODO with a message

- Meta/test_pdf.py
The rendering happens only in-memory, so this is only useful for looking at the crash rate and the reports of missing features.
To actually see the output of a file, use
pdf --render out.png --page N path/to/input.pdf
instead.
> Meta: Add a script for rendering many PDFs in parallel

- Userland/Libraries/LibPDF/DocumentParser.cpp
- Userland/Libraries/LibPDF/Parser.h
Reduces number of crashes on 300 random PDFs from the
web (the first 300 from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/)
from 34 (11%) to 29 (9%).
Fixes most crashes looking like:
```
unsupported graphics symbol x
VERIFICATION FAILED: false at /Users/thakis/src/serenity/Meta/Lagom/../../Userland/Libraries/LibPDF/Operator.h:113
0   liblagom-core.0.0.0.dylib           0xc3ns0r3d ak_verification_failed + 136
1   liblagom-pdf.0.0.0.dylib            0xc3ns0r3d PDF::Operator::operator_type_from_symbol(AK::StringView) + 5856
```
(A few remain, these are because we also interpret inline image data from BI / ID / EI as operands. That's for another PR.)
> LibPDF: Fix corner case where we sometimes failed to decompress compressed streams

- Userland/Libraries/LibPDF/Document.cpp
Makes 0000847.pdf, 0000327.pdf, 0000124.pdf from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/
assert later when rendering them, instead of when building the outline.
> LibPDF: Fix rare assertions when constructing outlines

- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
- Userland/Services/WebContent/PageHost.cpp
There is only one usage of ClearRect command and it could be replaced with FillRect to make set of commands in RecordingPainter smaller.
> LibWeb: Remove ClearRect command in RecordingPainter

- Userland/Libraries/LibPDF/Renderer.cpp
If a PDF uses `/CustomName cs` and `/CustomName` then points at just a name like `/DeviceGray` instead of an array, that's ok. Just using `/DeviceGray cs` is simpler, so this extra level of indirection is somewhat rare in practice, but it's valid and it does happen. So support it.
We already have a helper that does the right thing that we just need to call.
Together with #21524 and #21525, reduces number of crashes on 300 random PDFs from the web (the first 300 from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/) from 29 (9%) to 25 (8%).
> LibPDF: Don't assert on named simple color space

- AK/StringUtils.cpp
- Tests/AK/TestStringUtils.cpp
Fixed the issue in StringUtils::convert_to_floating_point() where the end pointer of the trimmed string was not being passed, causing the function to consistently return 'None' when given strings with trailing whitespaces.
This PR Fixes #21428
> AK: Pass correct length to convert_to_floating_point()

- Userland/Shell/Shell.cpp
> Shell: Don't try to cast NonnullRefPtrs when priting debug output

- Tests/LibWeb/Layout/expected/grid/template-areas-1.txt
- Tests/LibWeb/Layout/expected/grid/template-areas-2.txt
- Tests/LibWeb/Layout/expected/grid/template-areas-3.txt
- Tests/LibWeb/Layout/input/grid/template-areas-1.html
- Tests/LibWeb/Layout/input/grid/template-areas-2.html
- Tests/LibWeb/Layout/input/grid/template-areas-3.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Rewrites the grid area building to accurately identify areas that span multiple rows. Also now we can recognize invalid areas but do not handle them yet.
> LibWeb: Fix building of areas spanning multiple rows in GFC

- Userland/Libraries/LibGfx/Font/OpenType/Tables.h
- Userland/Libraries/LibGfx/Font/WOFF/Font.cpp
- Userland/Libraries/LibGfx/Font/WOFF2/Font.cpp
Because having a `Header` struct and reading it with `stream.read_value<Header>()` is much less error-prone than reading each field individually using a specific byte-offset.
Should be no behaviour changes. But we don't seem to have any font tests so I've just been using `Base/res/html/misc/font-face.html`. :sweat_smile:
> LibGfx: Replace a bunch of manual byte-offset fiddling in WOFF/WOFF2 with structs and streams

- Userland/Libraries/LibJS/Runtime/Date.cpp
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.UTC.js
As of https://tc39.es/ecma262/#sec-yearfromtime, YearFromTime(t) should
return `y` such that `TimeFromYear(YearFromTime(t)) <= t`. This wasn't
held, since the approximation would only go the desired direction once.
Adapted from Kiesel:
https://codeberg.org/kiesel-js/kiesel/commit/6548a857439ca175d4254c880442bb5267e92a04
Fixes #21533.
> LibJS/Date: Ensure `YearFromTime(t)` holds invariant after approximation

- Userland/Libraries/LibPDF/Parser.cpp
Makes 0000607.pdf from 0000.zip from the pdfa dataset load.
> LibPDF: Tolerate comments after dict values

- Userland/Libraries/LibPDF/Filter.cpp
Makes us die with a better error message for some PDFs.
> LibPDF: Use TRY() to get decompression result

- Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp
- Userland/Libraries/LibPDF/Fonts/SimpleFont.h
- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.h
- Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
- Userland/Libraries/LibPDF/Fonts/Type1Font.h
Type 1 fonts usually have a m_font_program and no m_font -- they only have m_font if we're using a replacement font for the fonts that were built-in to PDFs before Acrobat 4.0 (and must still work to show existing files).
However, SimpleFont::get_glyph_width() used to always return a float, which in Type1Font was only implemented if m_font was set.
Per spec, we're supposed to just use /MissingWidth for fonts that are missing an entry in the descriptor's /Width array. However, for built-in fonts, no explicit /Width array is needed (PDF 1.7 spec, Appendix H.3, 5.5.1). So if we just always use /MissingWidth, then PDFs that use a built-in font draw all their text on top of each other (e.g. 000333.pdf from stillhq.com-pdfdb).
So change get_glyph_width() to return Optional<float>, return it …
> LibPDF: Don't crash on fixed-width type 1 fonts that use /MissingWidth

- Userland/Libraries/LibPDF/Page.cpp
A page's /Contents can be an array of streams, and the page's contents are then as if those streams are concatenated.
Most of the time, a stream ends with whitespace. But in some cases (e.g. 0000642.pdf from 0000.zip from the pdfa dataset), the first stream ends with an operator (`Q`) and the next stream starts with one (`q`), and the concatenation would form a new, unkonwn operator (`Qq`). Separate the streams' contents with a space to prevent that.
Reduces numbers of PDF files we fail to open in the -n 500 case from 11 to 10 (in either case, we then crash on 18 of the PDFs that we do manage to open).
> LibPDF: Don't accidentally form new tokens on pages with contents arrays

- Userland/Libraries/LibGUI/ComboBox.cpp
Without ENABLE_TIME_ZONE_DATA the user is able to update the time zone selection in TimeZoneSettingsWidget when using "on_mousewheel" or "on_{up,down}_pressed" even though UTC is supposed to be the only option. Due to an invalid model index, the selection is set to "[null]".
Prior to this patch, the ComboBox text in "selection_updated" is set at each call.
> LibGUI: Don't update ComboBox text when model index is invalid

- Kernel/FileSystem/Ext2FS/FileSystem.cpp
- Kernel/FileSystem/Ext2FS/Inode.cpp
- Meta/build-root-filesystem.sh
- Tests/Kernel/CMakeLists.txt
- Tests/Kernel/TestExt2FS.cpp
Previously, attempting to write a UID or GID larger than 65535 would overflow. We now write the high bits of UIDs and GIDs to the same place that Linux does within the `osd2` struct.
Before:
After:
NB: I also tested creating a new file as the `not_root` user. I had to do this with `bash` though, as `Shell` crashed when I ran `su not_root` :shrug:.
> Kernel/Ext2: Avoid overflow when updating UID and GID values

- Tests/LibWeb/Layout/expected/grid/item-max-width.txt
- Tests/LibWeb/Layout/expected/grid/item-min-width.txt
- Tests/LibWeb/Layout/input/grid/item-max-width.html
- Tests/LibWeb/Layout/input/grid/item-min-width.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Now min-width and max-width properties affect resulting width of grid item instead of being ignored.
> LibWeb: Resolve grid item's min-width and max-width in GFC

- Tests/LibWeb/Layout/expected/grid/items-min-content-size-should-account-paddings.txt
- Tests/LibWeb/Layout/input/grid/items-min-content-size-should-account-paddings.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
As spec comment in the code says we should use item’s max-content contribution to calculate flex fraction.
Likely, it was calculate_max_content_size() because we didn't have calculate_max_content_contribution() when this function was implemented initially.
> LibWeb: Use max content contribution in flex_fraction in GFC

- Userland/Libraries/LibWeb/HTML/AttributeNames.h
- Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLDataListElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLFieldSetElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLLegendElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLMeterElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLOptGroupElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLOptionElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLOutputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLProgressElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
This month I want to make the form elements more spec compliant. My workflow mostly consist of finding FIXME's in the IDL files and implementing missing methods and/or getters and setters. Most of the form elements IDL files where not based on the spec so I copied most IDL spec definitions and added fixme's of all the stuff that is not implemented. That way we can implement stuff along the way 🎉
Maybe I forgot something so a nice review is needed.
> LibWeb: Fix input and form elements IDL definitions

- Documentation/Links.md
- Meta/Lagom/ReadMe.md
`libjs.dev` is down, and `test262.fyi` looks to be the replacement.
I deleted the notes on WASM because I didn't find a replacement. Let me  know if I should keep some notes on them.
> Meta: Update libjs.dev links to test262.fyi

- Documentation/RunningTests.md
- Meta/run.sh
`-nographic` additionally reconfigures the Terminal, which clears the previous scrollback and (ocasionally) breaks line wrapping. This is probably not something that we want, so only ask for the redirection behavior.
> Meta: Manually redirect CI serial output to stdout

- AK/Assertions.cpp
The log message can be hard to spot in a sea of debug messages. Colorize it to make the message more immediately pop out.
> AK: Colorize log message for failed assertions

- Documentation/RunningTests.md
- Meta/run.sh
`-serial mon:stdio` passes through all kinds of key combinations, `-serial stdio` doesn't. This probably isn't something that we want while running tests or CI, so switch to the non-passing variant.
aarch64 actually failed to run due to this, since it already had `-serial stdio` in its arguments, causing a conflict. This is why that entry is now gone entirely.
> Meta: Don't pass ^C through the serial console on CI

- Userland/Libraries/LibPDF/Reader.h
No behavior change, just simpler and less surprising.
----
I've had this sitting in a local branch for a while now and haven't found a PR where it fits in. I figured I'd just send it out, even though it's tiny.
> LibPDF: Make Reader::move_by() parameter more truthful

- Userland/Libraries/LibPDF/DocumentParser.cpp
Several files have a comment after the trailer dict and the `startxref` after it.
We really should add a consume_whitespace_and_comments() function and call that in most places we currently call consume_whitespace().
But in this case, for non-linearized files, we first jump to the end of the file, read `startxref`, then jump to `xref` from the offset there, and then read the trailer after the `xref`, only to read `startxref` again. So we can just not do that.
(For linearized files, we now completely ignore `startxref`. But we don't use the data in `startxref` in linearized files anyways, so it's fine to not read it there too.)
Reduces number of crashes on 300 random PDFs from the web (the first 300 from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/) …
> LibPDF: Don't check for `startxref` after trailer dict

- Userland/Libraries/LibWeb/DOM/Element.cpp
We perform such a check in other users of the paintable box in this file as the box may be null before layout completes. This prevents UB seen in some CI runs.
> LibWeb: Protect ad-hoc `scroll` against a potentially null paintable box

- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/ColorSpace.h
Actually using separation color spaces still doesn't work, but we now no longer assert on them when they're used.
Fixes 2 crashes on the `-n 500` 0000.zip pdfa dataset.
> LibPDF: Implement two SeparationColorSpace methods

- Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
By storing painting command coordinates relative to the nearest stacking context we can get rid of the Translate command.
Additionally, this allows us to easily check if the bounding rectangles of the commands cover or intersect within a stacking context. This should be useful if we decide to optimize by avoiding the execution of commands that will be overpainted by the results of subsequent commands.
> LibWeb: Record painting commands in coordinates of stacking context

- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Removing State and Restore reduces painting commands count by 30-50% on an average website.
Due to this change, it was also necessary to replace AddClipRect with SetClipRect command.
> LibWeb/Painting: Remove Save and Restore commands in RecordingPainter

- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/CppASTConverter.cpp
I've found out these do not have any dependencies on yet unmerged commits. Also, who does not like `1 file changed, 45 insertions(+), 1 deletion(-)`?
> JSSpecCompiler: Support Cpp::{BinaryExpression,StringLiteral} in C++ AST converter (simple to review!)

- Userland/Libraries/LibPDF/Document.cpp
- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
- Userland/Libraries/LibPDF/Renderer.cpp
Except when explicitly noticed, every value in a PDF document can be an indirect reference (`42 0 R`) to an indirect object (`42 0 obj ... endobj`), and the value's contents is then the indirect object's reference.
Use the right methods to make this work in a few more places.
Also, make ints in outline item colors work.
> LibPDF: Support indirect references in more places

- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/ColorSpace.h
- Userland/Libraries/LibPDF/CommonNames.h
- Userland/Libraries/LibPDF/Parser.cpp
Same as other recent color spaces: Enough to make us not assert,
but not enough to actually produce color.
Fixes 2 asserts on the `-n 500` 0000.zip pdfa dataset.
> LibPDF: Sketch out Lab color space

- Documentation/BuildInstructionsLadybird.md
- Ladybird/CMakeLists.txt
- Meta/Azure/Lagom.yml
- Meta/serenity.sh
The Qt chrome is still available and may be enabled with CMake.
> Ladybird+Meta: Make the AppKit chrome the default on macOS

- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Libraries/LibPDF/ColorSpace.h
- Userland/Libraries/LibPDF/CommonNames.h
Documents using them now show render-time diagnostics instead of asserting that number of parameters passed to a color don't match whatever number of channels the previously-set color space had.
Fixes two asserts on the `-n 500` 0000.zip test set.
> LibPDF: Sketch out DeviceN color spaces a bit

- Userland/Libraries/LibGUI/FileSystemModel.cpp
These changes make it possible for GUI applications to react to more changes to the file system, and for their view of the state of the file system to be as accurate as possible.
This includes:
- Preserving correct file order when a new file is created
- Reacting when file metadata changes
- Keeping track of changes to newly created files
This responsiveness can be most clearly seen in FileManager:
https://github.com/SerenityOS/serenity/assets/58829763/d9fce887-7b75-49e8-9671-03c809c7c959
> LibGUI: Make GUI applications more responsive to file system changes

- Userland/Libraries/LibGUI/GlyphMapWidget.cpp
- Userland/Libraries/LibGUI/GlyphMapWidget.h
Currently finding a particular glyph with a given code point is a bit tedious as it requires clicking on the glyph to update the status bar and display the glyph's name and codepoint. A more convenient way to know where we are in the Glyph Map is by seeing a tooltip over the glyph where the mouse is currently hovering over. This patch adds that support by setting the Widget tooltip with the glyph found at the current position in GlyphMapWidget::mousemove_event.
> Userland: Draw tooltip over glyph to show UTF-8 code point in Font Editor

- Userland/Shell/Builtin.cpp
- Userland/Shell/Shell.h
I'm sick of GNU parallel, so here's a better option.
> Shell: Add a 'in_parallel' builtin for easy concurrency

- .github/workflows/libjs-test262.yml
See:
https://github.com/SerenityOS/libjs-test262-data/commit/75f5027d5e4f92db6aed60d4f5e69b8cb6f98fe9
> CI: Remove git LFS tracking of test262 data

- Base/usr/share/man/man7/Shell-vars.md
- Userland/Shell/Shell.cpp
This pull request adds more formatting options to the `$PROMPT` variable, that is used to set the shell prompt. I've tried to copy what [Bash](https://www.gnu.org/software/bash/manual/bash.html#Controlling-the-Prompt) and [Zsh](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html) is doing as much as possible. Where they disagree with each other, I've made my own decision for how Shell should act.
New special characters:
- `\t`: Current time in the 24-hour format HH:MM:SS
- `\T`: Current time in the 12-hour format HH:MM
- `\@`:  Current time in the 12-hour format HH:MM AM/PM
- `\D{format}`: Current time, where the string _format_ is passed on to `Core::DateTime::to_string`. If _format_ is empty, a default format string is chosen.
- `\j`: The number of jobs currently managed by the …
> Shell: Expand prompt formatting options

- Documentation/Patterns.md
This is the only instance of `*OS's` in the repo that does not use `s` after the apostrophe.
Generally, the saxon genitive for singular nouns is always written as `'s` even if they end in `s`.
> Documentation: SerenityOS' => SerenityOS's in Patterns.md

- Ports/devilutionX/package.sh
This was replaced by SDL_audiolib a couple of versions ago
> Ports/devilutionX: Remove SDL2_mixer dependency

- Meta/Lagom/CMakeLists.txt
- Tests/LibTest/CMakeLists.txt
- Tests/LibTest/TestGenerator.cpp
- Userland/Libraries/LibTest/Macros.h
- Userland/Libraries/LibTest/Randomized/Chunk.h
- Userland/Libraries/LibTest/Randomized/Generator.h
- Userland/Libraries/LibTest/Randomized/README.md
- Userland/Libraries/LibTest/Randomized/RandomRun.h
- Userland/Libraries/LibTest/Randomized/RandomnessSource.h
- Userland/Libraries/LibTest/Randomized/Shrink.h
- Userland/Libraries/LibTest/Randomized/ShrinkCommand.h
- Userland/Libraries/LibTest/TestCase.h
- Userland/Libraries/LibTest/TestResult.h
- Userland/Libraries/LibTest/TestSuite.cpp
- Userland/Libraries/LibTest/TestSuite.h
Add a way to run randomized tests (commonly called "property-based"): that is, tests that generate random data to run the test case with, and if they find a failure they shrink the input to a minimal failing example before reporting it to the user.
See [README.md](https://github.com/SerenityOS/serenity/pull/21191/files#diff-db605979eb83d9ca5b80e9a4ec840b9db3870a805117e0e9f2bc97829a0294eb) for more in-depth description.
```cpp
// Tests/LibCompress/TestGzip.cpp
// This test didn't find anything but shows off a very common property we can test with this.
RANDOMIZED_TEST_CASE(roundtrip)
{
GEN(buffer, Gen::vector(2048,[](){return (u8)Gen::unsigned_int(255);}));
auto const compressed = MUST(Compress::GzipCompressor::compress_all(buffer));
auto const decompressed = …
```
> LibTest: Add support for randomized tests

- Documentation/Links.md
- Meta/Lagom/ReadMe.md
- README.md
This partially reverts dacf7265 and 67ca5d65.
> Meta+Documentation: Restore links to LibJS website

- Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp
Fixes asserts when rendering 0000037.pdf, 0000116.pdf, 0000463.pdf,
0000483.pdf, 0000506.pdf, and 0000938.pdf in 0000.zip from the
pdfa dataset.
---
And some minor tweaks in the area.
> LibGfx: Fix off-by-one in opentype cmap format 6 parsing

- Userland/Libraries/LibGfx/Font/WOFF/Font.cpp
- Userland/Libraries/LibGfx/Font/WOFF2/Font.cpp
This guards against undefined behavior when zero is given as an argument.
This fixes oss fuzz issues: [63635](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63635) and  [63637](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63637)
> LibGfx: Use safe version of `count_leading_zeroes()` in WOFF parsers

- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
A part of post navigables cleanup.
> LibWeb: Remove unused append_child and remove_child in BrowsingContext

- Tests/LibWeb/Layout/expected/grid/item-with-min-width-and-place-self-start.txt
- Tests/LibWeb/Layout/input/grid/item-with-min-width-and-place-self-start.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Changing `try_compute_width()` to return width and margins, instead of mutating them in the box's state makes it works in cases when box has min-width or max-width and this function needs to be called multiple times.
Fixes https://github.com/SerenityOS/serenity/issues/21598
> LibWeb: Fix box alignment when it has min-width or max-width in GFC

- Userland/Libraries/LibPDF/Document.cpp
Nothing in PDF 1.7 spec 8.2.1 Destinations mentions the page being `null`, but it happens in 0000372.pdf (for the root outline element) and in 0000776.pdf (for every outline element, which looks like a bug in the generator maybe) of 0000.zip from the pdfa dataset.
> LibPDF: Don't assert on outline destinations that use `null` as page

- Ladybird/CMakeLists.txt
> Ladybird: Install the ImageDecoder binary to the macOS app bundle

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/JIT/Compiler.cpp
- Userland/Libraries/LibJS/JIT/NativeExecutable.cpp
- Userland/Libraries/LibJS/JIT/NativeExecutable.h
- Userland/Libraries/LibX86/Instruction.cpp
This avoids the need for redirecting stdout to a file and using ndisasm, which can lead to problems if other things are printed.
Also fixes a decoding bug for imm64 MOVs in LibX86.
> LibJS/JIT: Dump disassembly of generated code using LibX86

- AK/Assertions.cpp
The backtrace execinfo API takes the number of addresses the result buffer can hold instead of its size, for some reason. Previously backtraces larger than 256 frames deep would write past the end of the result buffer.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63214 & https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62263
> AK: Use array element count instead of memory size in backtrace call

- AK/IntegralMath.h
- Tests/AK/TestIntegerMath.cpp
Previously, integral `exp2()` would produce the incorrect result for exponents above 31.
This fixes oss fuzz issue [53793](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53793)
> AK: Use correct type when calculating integral `exp2()`

- Userland/Libraries/LibJIT/Assembler.h
- Userland/Libraries/LibJS/JIT/Compiler.cpp
This replaces the existing sized immediate operands with a unified immediate operand that leaves the size handling to the assembler, instead of the user.
This has 2 benefits:
1. The user doesn't need to know which specific operand size the instruction expects when using it
2. The assembler automatically chooses the minimal operand size that fits the given value, resulting in smaller code size without any additional effort from the user. While the change is small, it still has a noticeable effect on performance (since it increases the I$ hit rate), resulting in 5% speedup on kraken a-star.
> LibJIT+LibJS: Consolidate sized immediate assembler operands

- Userland/Libraries/LibJIT/Assembler.h
Instead of adjusting the stack pointer before/after making native calls, just make sure we come out of `enter()` with the stack pointer aligned for making calls.
This is strictly a code size reduction. :^)
> LibJIT: Keep the stack pointer aligned for making native calls

- Userland/Libraries/LibJS/JIT/Compiler.cpp
- Userland/Libraries/LibJS/JIT/Compiler.h
This fixes 1 of the 2 remaining failing test-js tests.
> LibJS: Execute the finalizer when returning from a try block in the JIT

- Kernel/Arch/CPUID.h
- Kernel/Arch/FPUState.h
- Kernel/Arch/Processor.h
- Kernel/Arch/RegisterState.h
- Kernel/Arch/ThreadRegisters.h
- Kernel/Arch/TrapFrame.h
- Kernel/Arch/riscv64/CPUID.h
- Kernel/Arch/riscv64/CSR.h
- Kernel/Arch/riscv64/FPUState.h
- Kernel/Arch/riscv64/Processor.cpp
- Kernel/Arch/riscv64/Processor.h
- Kernel/Arch/riscv64/RegisterState.h
- Kernel/Arch/riscv64/ThreadRegisters.h
- Kernel/Arch/riscv64/TrapFrame.h
- Kernel/CMakeLists.txt
- Kernel/Library/Assertions.h
- Userland/Libraries/LibC/sys/arch/regs.h
- Userland/Libraries/LibC/sys/arch/riscv64/regs.h
This an initial implementation of a RISC-V processor class.
Note that this PR won't yet compile though, as many headers are still missing on riscv64.
I am not completely happy with CSR.h, but this is the best way of implementing that header I could think of.
> Kernel/riscv64: Add RISC-V Processor class

- Userland/Libraries/LibWeb/Forward.h
In the running for possibly the most exciting PR of 2023.
> LibWeb: Stop forward-declaring NavigationParams twice

- Userland/Libraries/LibPDF/DocumentParser.cpp
Previously, an xref stream with a field with larger than 8 would result in an undefined shift occurring. We now ensure that each field width is a number and is less than or equal to 8.
I looked at a few PDF libraries and none of them perform this check. All the implementations I looked at [shifted the value one byte at a time](https://github.com/ArtifexSoftware/mupdf/blob/384425820b0ed144758c6d237911cbadb7aa4f3b/source/pdf/pdf-xref.c#L1363), but as far as I can tell, this could still result in an overflow.
No change in `test_pdf` output with a selection of 776 random PDFs from my local machine.
This fixes oss fuzz issue: [63232](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63232)
> LibPDF: Ensure xref stream field widths are within expected range
