Base/res/fortunes.json

Base: Add an ISO C++-compliant quote to the fortunes database

---

Meta/Lagom/Contrib/MacPDF/MainMenu.xib

I forgot to rename it there, whoops.

MacPDF: Use "MacPDF" in MainMenu.xib

---

Userland/Applications/SpaceAnalyzer/CMakeLists.txt
Userland/Applications/SpaceAnalyzer/MainWidget.h
Userland/Applications/SpaceAnalyzer/SpaceAnalyzer.gml
Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
Userland/Applications/SpaceAnalyzer/main.cpp

SpaceAnalyzer: Port to GML compiler

---

Userland/Games/MasterWord/CMakeLists.txt
Userland/Games/MasterWord/MainWidget.h
Userland/Games/MasterWord/MasterWord.gml
Userland/Games/MasterWord/WordGame.cpp
Userland/Games/MasterWord/main.cpp

**Contributes to #20518**
This PR is my attempt to port the existing MasterWord application to the new GML compiler. 
If my approach is correct, I would be happy to continue looking at some of the other applications that need to be ported. 
Please do let me know if you would like me to make any changes.

MasterWord: Use GML compiler

---

Userland/Libraries/LibArchive/TarStream.h

This resolves oss-fuzz issues [62048](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62048&sort=-opened&can=1&q=proj%3Aserenity) and [62016](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62016&sort=-opened&can=1&q=proj%3Aserenity).

LibArchive: Ensure tar extended header length is within expected range

---

Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp

This PR adds support for the `CAMG` IFF chunk that contains information about the hardware video mode that's required for the image. Only EHB bit is checked for now but HAM support will be added in an upcoming PR.

LibGfx/ILBMLoader: add support for EHB mode

---

Kernel/Arch/init.cpp
Kernel/Devices/Audio/AC97/AC97.cpp
Kernel/Devices/Audio/AC97/AC97.h
Kernel/Devices/HID/PS2/KeyboardDevice.cpp
Kernel/Memory/MemoryManager.cpp
Kernel/Prekernel/boot.S
Kernel/Prekernel/init.cpp
Kernel/Prekernel/multiboot.S

With this patch set I could boot into serenity on chromebook Elemi via Tianocore (EFI). Internal drive and keyboard work. Special keyboard combinations don't work. Touchpad (Elan I2C) doesn't. Screen is stuck in the same resolution. Sound (Intel SOF) doesn't work. USB (XHCI) doesn't work, as well as Bluetooth and Webcam that rely on it. MicroSD doesn't work

Add basic support for Chromebook Elemi

---

Userland/Libraries/LibJS/Bytecode/IdentifierTable.cpp
Userland/Libraries/LibJS/Bytecode/StringTable.cpp
Userland/Libraries/LibJS/Runtime/MathObject.cpp
Userland/Libraries/LibJS/Runtime/Value.cpp

- 2.3% speed-up on Kraken/imaging-gaussian-blur.js :^)
- 5% speed-up on Kraken/imaging-gaussian-blur.js :^)
- 4.4% speed-up on Kraken/stanford-crypto-ccm.js :^)

LibJS: Three little speed-ups for Kraken

---

Userland/Utilities/open.cpp

Previously, the error given for any non-existent file was: "Failed to open ':'".

open: Display a meaningful error if the specified file doesn't exist

---

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp

Permitted bit depth and color type combinations were obtained from [the PNG specification](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html)
This fixes oss fuzz issue [62371](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62371&sort=-reported%20-opened&q=proj%3Aserenity&can=1)

LibGfx/PNGLoader: Add validation for IHDR width, height and bit depth

---

Tests/LibWeb/Layout/expected/calc-font-size-with-percentages.txt
Tests/LibWeb/Layout/input/calc-font-size-with-percentages.html
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h

Fixes crashing on https://react.dev/

LibWeb: Resolve percentages in calc() for font-size

---

Userland/Utilities/find.cpp

This change brings our `find` implementation in line with the [POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html), which says:
> Each path operand shall be evaluated unaltered as it was provided, including all trailing <slash> characters; all pathnames for other files encountered in the hierarchy shall consist of the concatenation of the current path operand, a <slash> if the current path operand did not end in one, and the filename relative to the path operand. The relative portion shall contain no dot or dot-dot components, no trailing <slash> characters, and only single <slash> characters between pathname components.
The `find` programs on Linux and FreeBSD also behave this way.
This change affects the behavior of all commands which work on the …

find: Don't canonicalize path operands

---

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp

If we have a cached environment coordinate that hasn't been screwed by eval(), we can get the value directly without instantiating a Reference.
15% speed-up on Octane/zlib.js :^)

LibJS: Do less work in successfully cached GetByValue* ops

---

Userland/Libraries/LibJS/Bytecode/Executable.cpp
Userland/Libraries/LibJS/Bytecode/Executable.h
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/DOMParser.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/NavigateEvent.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/Worker.h
Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp

- **LibWeb: Don't include Window.h in Element.h and Document.h**
Window.h is a rather heavy file, so let's try not to include it in header files when we can!
Element.h now also includes LibWeb/Bindings/Intrinsics.h, but that's just out of my laziness. Most if not all objects call `Bindings::ensure_web_prototype<>()` anyway, so I don't think we would gain much by sticking the header to source files instead.
- **LibJS: Forward-declare RegexTable and BasicBlock in Executable.h**
Previously every file that included Executable.h (which is pretty much most LibJS and LibHTML files, given that VM.h needs it) had the whole definition of LibRegex, which was slowing down source parsing.
For example, the diff of a include tree for HTMLHRElement.h looks like this:
<details><summary>compared output of …

LibJS+LibWeb: Slightly improve compilation time

---

Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp

fixes oss fuzz issue [57974](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57974)

LibGfx/BMPLoader: Ensure DIB size and offset are within expected range

---

Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

Previously, every time a page switched fonts, we'd completely re-parse the font.
Now, we cache fonts in Renderer, effectively caching them per page.
It'd be nice to have an LRU cache across pages too, but that's a bigger change, and this already helps a lot.
Font size is part of the cache key, which means we re-parse the same font at different font sizes. That could be better too, but again, it's a big help as-is already.
Takes rendering the 1310 pages of the PDF 1.7 reference with
Build/lagom/bin/pdf --debugging-stats \
~/Downloads/pdf_reference_1-7.pdf
from 71 s to 11s :^)
Going through pages especially in the index is noticeably snappier.
(On the PDF 2.0 spec, ISO_32000-2-2020_sponsored.pdf, it's less dramatic: From 19s to 16s.)

LibPDF: Cache fonts per page

---

Userland/Applications/GamesSettings/CardSettingsWidget.cpp
Userland/Applications/GamesSettings/CardSettingsWidget.gml
Userland/Applications/GamesSettings/CardSettingsWidget.h
Userland/Libraries/LibCards/CardGame.cpp
Userland/Libraries/LibCards/CardPainter.cpp
Userland/Libraries/LibCards/CardPainter.h
Userland/Libraries/LibCards/CardStack.h

A very nice visual improvement to our card games, courtesy of @cubiclove's beautiful artwork. :^)

LibCards: Paint images and number pips on card fronts :^)

---

Meta/CMake/libweb_generators.cmake
Meta/Lagom/CMakeLists.txt

And a QOL feature for linking against Lagom libraries.

Lagom: Fix using LibWeb/LibWebView headers from an installed lagom tree

---

Userland/Utilities/pdf.cpp

It calls render() N times instead of just once. Useful for benchmarking.

pdf: Add a --render-repeats=N flag

---

Userland/Libraries/LibELF/DynamicLoader.cpp

GNU ld for some reason might put R_*_TLSDESC relocations in .rela.plt.

LibELF: Handle TLSDESC relocations in .rela.plt for GNU ld

---

Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp

Two bugs:
1. We decoded a u32, not an i32 as the spec wants
2. (minor) Our fixed-point divisor was off by one
Fixes text rendering in Bakke2010a.pdf in pdffiles, and rendering of other fonts with negative width adjustments from optcode 255. That PDF was produced by "Apple pstopdf" and uses font SFBX1200, which is apparently a variant of Computer Modern. So maybe this helps with lots of PDFs produced from TeX files, but I haven't checked that.

LibPDF: Fix sign (and fixed point) in glyph decoding opcode 24

---

Userland/DynamicLoader/main.cpp

If the user runs /usr/lib/Loader.so and pass a second string to argv, we will try to run it as if it was running that program without invoking the dynamic loader explicitly.

DynamicLoader: Add an option to explicitly run an ELF executable binary

---

Userland/Shell/Builtin.cpp
Userland/Shell/PosixParser.cpp
Userland/Shell/Shell.h

Shell: Implement the '$*' special variable in the POSIX parser 

---

Ladybird/FontPlugin.cpp
Ladybird/Utilities.cpp
Meta/Lagom/Contrib/MacPDF/AppDelegate.mm
Tests/LibGfx/TestFontHandling.cpp
Userland/Libraries/LibCore/CMakeLists.txt
Userland/Libraries/LibCore/Forward.h
Userland/Libraries/LibCore/Resource.cpp
Userland/Libraries/LibCore/Resource.h
Userland/Libraries/LibCore/ResourceImplementation.cpp
Userland/Libraries/LibCore/ResourceImplementation.h
Userland/Libraries/LibCore/ResourceImplementationFile.cpp
Userland/Libraries/LibCore/ResourceImplementationFile.h
Userland/Libraries/LibGfx/Font/FontDatabase.cpp
Userland/Libraries/LibGfx/Font/FontDatabase.h
Userland/Utilities/headless-browser.cpp
Userland/Utilities/pdf.cpp

The first implementation is simply raw files.
The next commit uses this for font loading.

LibCore: Add Resource for platform agnostic application resource loading

---

.github/workflows/cmake.yml
Base/home/anon/Tests/run-tests-and-shutdown.sh
Kernel/Bus/USB/Drivers/HID/MouseDriver.cpp
Kernel/Bus/USB/Drivers/MassStorage/MassStorageDriver.cpp
Kernel/Bus/USB/USBManagement.cpp
Kernel/Bus/USB/USBManagement.h

Only with a smoke test, however.
At the same time, fix "the PCI boot bug".

CI: Re-enable booting aarch64 in CI self-test mode on CI

---

Tests/LibGfx/TestFontHandling.cpp
Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp

Implements algorithm suggested by @nico in https://github.com/SerenityOS/serenity/issues/20179

LibGfx: Fix crash during rasterizing glyphs containing only one point

---

Userland/Libraries/LibPDF/Renderer.cpp

Previously, if one operator returned an error, the TRY() would cause us to return without restoring the outer graphics state, leading to problems such as handing a 3-tuple to a grayscale color space (because the inner object set up a grayscale color space that we failed to dispose of).
Makes us crash later on page 43 of
https://devstreaming-cdn.apple.com/videos/wwdc/2017/821kjtggolzxsv/821/821_get_started_with_display_p3.pdf

LibPDF: Use a RAII object to restore state in recursive render

---

Userland/Libraries/LibPDF/Renderer.cpp

Follow-up to #21489. There, I made us use a RAII object.
That's great, but if the embedded instruction stream pushes its own graphics state, then an early return would cause us to not process graphics state pop instructions in the embedded stream.
To fix this, remember the graphics stack depth before entering the nested instruction stream, and explicitly shrink the stack back to that size upon exit.
Enables us to render all pages of
https://devstreaming-cdn.apple.com/videos/wwdc/2017/821kjtggolzxsv/821/821_get_started_with_display_p3.pdf
without crashing.

LibPDF: Try harder to use a RAII object to restore state

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

This fixes oss fuzz issues: [59785](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59785) and [62997](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62997)

LibGfx/JPEGLoader: Check array access bounds when building lookup table

---

Userland/Libraries/LibPDF/Parser.cpp

Inline images can contain arbitrary binary data in the operator stream, greatly confusing the operator parser.
Just skip them for now. They'll produce a
`Rendering of feature not supported: draw operation: inline_image_begin` diag as usual, so we won't forget about it.
After #21536, reduces number of crashes on 300 random PDFs from the web (the first 300 from 0000.zip from
https://pdfa.org/new-large-scale-pdf-corpus-now-publicly-available/) from 23 (7%) to 22 (7%).
On a larger sample (`Meta/test_pdf.py -n 500 ~/Downloads/0000`), reduces number of crashes from 53 (10.6%) with 36 distinct crash stacks to 46 (9.2%) with 33 distinct stacks.

LibPDF: Skip inline image data in operator stream

---

Ladybird/AppKit/Application/ApplicationDelegate.mm
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/Settings.cpp
Ladybird/Qt/Tab.cpp
Ladybird/Qt/Tab.h
Userland/Applications/Browser/IconBag.cpp
Userland/Applications/Browser/IconBag.h
Userland/Applications/Browser/Tab.cpp
Userland/Applications/Browser/Tab.h
Userland/Libraries/LibWebView/SearchEngine.cpp
Userland/Libraries/LibWebView/SearchEngine.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h

AKA adding a feature I use 1 million times a day in other browsers
https://github.com/SerenityOS/serenity/assets/5600524/89af0fb6-1544-4266-ac05-14dda632aa3e

Ladybird: Add a context menu item to search the currently selected text

---

Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
Userland/Games/Minesweeper/CMakeLists.txt
Userland/Games/Minesweeper/CustomGameDialog.cpp
Userland/Games/Minesweeper/CustomGameDialog.h
Userland/Games/Minesweeper/CustomGameWidget.gml
Userland/Games/Minesweeper/CustomGameWidget.h
Userland/Games/Minesweeper/MainWidget.gml
Userland/Games/Minesweeper/MainWidget.h
Userland/Games/Minesweeper/main.cpp
Userland/Libraries/LibGUI/UIDimensions.h

This patch ports minesweeper to GML compilation, and introduces
a few changes made to associated files.
It contributes to https://github.com/SerenityOS/serenity/issues/20518

Minesweeper: Port to GML compilation

---

Userland/Libraries/LibPDF/Parser.cpp
Userland/Libraries/LibPDF/Parser.h

LibPDF: Be more robust against invalid string literals

---

Tests/LibWeb/Layout/expected/grid/item-fit-content-width.txt
Tests/LibWeb/Layout/input/grid/item-fit-content-width.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Fixes https://github.com/SerenityOS/serenity/issues/21569

LibWeb: Handle fit-content in calculate_max_content_contribution in GFC

---

Tests/LibWeb/Ref/text-shadow.html

Missing input file for e48b3b39cff37d0e469ca20af64e1ba5e8443f1c

Tests/LibWeb: Add missing test-shadow.html

---

Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Userland/Services/WebContent/PageHost.cpp

Decoupling painting command executor from RecordingPainter allows to introduce painters other than CPU Gfx::Painter :)

LibWeb/Painting: Introduce PaintingCommandExecutor

---

Base/res/html/misc/cookie.html
Meta/Lagom/Tools/CodeGenerators/LibWebView/GeneratePublicSuffixData.cpp
Userland/Libraries/LibWebView/CookieJar.cpp
Userland/Libraries/LibWebView/URL.cpp
Userland/Libraries/LibWebView/URL.h

Removing a FIXME I added 2.5 years ago 86bdfa1edf21293e2c0f3ca8b31808a21882cb99
:upside_down_face:

LibWebView: Reject cookies whose domain is on the Public Suffix List

---

Userland/Applications/Calendar/AddEventDialog.cpp
Userland/Applications/Calendar/AddEventDialog.gml
Userland/Applications/Calendar/AddEventDialog.h
Userland/Applications/Calendar/CMakeLists.txt

This is building toward a week/day view showing events similar to the macos calendar app

Calendar: Add end date/time to events

---

Ladybird/CMakeLists.txt
Ladybird/Info.plist
Ladybird/cmake/InstallRules.cmake

Ladybird: Fix capitalization in AppKit menu bar

---

.github/workflows/wasm.yml
AK/SipHash.cpp
Meta/Lagom/Wasm/js_repl.cpp

Note that this will fail until we add a "libjs-wasm" branch to github.com/serenityos/libjs-test262-data

Meta: Restore the LibJS Wasm build

---

Documentation/BuildInstructionsLadybird.md
Ladybird/WebDriver/main.cpp
Meta/gn/secondary/BUILD.gn
Meta/gn/secondary/Ladybird/BUILD.gn
Userland/Services/WebDriver/Client.cpp

Fallout from 01feae2
These places referred to the filaname "ladybird" directly, but we
changed the OUTPUT_NAME of ladybird to "Ladybird".
Fixes the WPT CI job

Meta+Documentation+Ladybird: Update places that used ladybird filename

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp

This restores the bytecode interpreter's original call exception throwing behaviour to the JIT.
This also fixes 8 of the 10 failing test-js tests when running with the JIT enabled.

LibJS: Pass the expression string to cxx_call as a stack argument 

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

LibJS/JIT: Some code size optimizations :^)

---

Tests/LibWeb/Ref/reference/svg-stroke-paintstyle-with-opacity-ref.html
Tests/LibWeb/Ref/svg-stroke-paintstyle-with-opacity.html
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp

LibWeb: Fix `stroke-opacity` for stroked paths that use PaintStyles

---

Tests/LibCompress/TestXz.cpp
Userland/Libraries/LibCompress/Xz.cpp
Userland/Libraries/LibCompress/Xz.h

Time to get back to finalizing XZ decompression.

LibCompress: Implement the XZ delta filter

---

AK/CMakeLists.txt
AK/Slugify.cpp
AK/Slugify.h
Base/usr/share/man/man1/slugify.md
Tests/AK/CMakeLists.txt
Tests/AK/TestSlugify.cpp
Userland/Libraries/LibCore/ArgsParser.cpp
Userland/Libraries/LibCore/ArgsParser.h
Userland/Libraries/LibMarkdown/CMakeLists.txt
Userland/Libraries/LibMarkdown/Heading.cpp
Userland/Utilities/CMakeLists.txt
Userland/Utilities/slugify.cpp

AK / LibMarkdown: Render slugified anchor tag in heading

---

Userland/Utilities/js.cpp

If we invoke the exit native function from within the exit builtin, the native call will then invoke global destructors. This ultimately ends up deleting the JS::NativeFunction that defines the exit builtin, thus we try to delete the AK::Function held inside the NativeFunction while that AK::Function is executing. This is explicitly forbidden by AK::Function.
Instead, simply set a flag to exit the REPL after the builtin executes.
Fixes #21670

js: Implement the exit builtin without calling the native exit function

---

Userland/Utilities/headless-browser.cpp

Remove the ad-hoc sanitization in favor of LibWebView. This was missed after commit 191e20d639b578bb431b23318e7310b800b0013f.

headless-browser: Use LibWebView to sanitize input URLs

---

Ladybird/Android/src/main/AndroidManifest.xml
Ladybird/Android/src/main/cpp/ImageDecoderService.cpp
Ladybird/Android/src/main/cpp/LadybirdServiceBaseJNI.cpp
Ladybird/Android/src/main/cpp/WebContentService.cpp
Ladybird/Android/src/main/cpp/WebContentService.h
Ladybird/Android/src/main/cpp/WebContentServiceJNI.cpp
Ladybird/Android/src/main/java/org/serenityos/ladybird/ImageDecoderService.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdActivity.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentService.kt
Ladybird/ImageCodecPlugin.cpp
Ladybird/ImageDecoder/CMakeLists.txt
Ladybird/WebContent/CMakeLists.txt
Ladybird/cmake/InstallRules.cmake
Userland/Libraries/LibAccelGfx/Context.h
Userland/Libraries/LibJS/JIT/NativeExecutable.cpp
Userland/Services/WebContent/CMakeLists.txt
Userland/Services/WebContent/PageHost.cpp

... and like a dozen other fixes for the Android build.

Ladybird/Android: Create a service for ImageDecoder 

---

AK/JsonParser.cpp

This code was quite unwieldy and repetitive.
The long `if(next_is('X'))` chain is now a small `switch`. I also reinstated the fast path for long sequences of literal characters, which was partially broken with the introduction of `GenericLexer`.
I also added some spec comments, and implementation notices
---
I know bad commit title, but could not think of something better

AK: Refactor `JSONParser::consume_and_unescape_string` a bit

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/HackStudioWidget.h

| Demo |
| --- |
| <video src="https://github.com/SerenityOS/serenity/assets/36564831/4d0ad011-bad5-4d44-93bb-bf1ddcb27434"> |

HackStudio: Add an 'Auto Save before Build or Run' option

---

Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp

See https://github.com/whatwg/html/pull/9904

LibWeb: Do not unload during same-document history step application

---

Userland/Utilities/ls.cpp

Most implementations of ls have an indicator for pipes and sockets, namely `|` and `=`.
I added these indicators. I also gave pipes a yellow color like similar special files.
I am not sure how to write tests for this yet.
If someone could guide me in the right direction?

ls: use indicator for sockets and pipes

---

.github/workflows/libjs-test262.yml

This will let us have more :yakgraph:s!

Meta: Run test262 with JIT compilation enabled in CI

---

.github/workflows/libjs-test262.yml

This will allow BuggieBot to display both results from the /test262 command on Discord.

CI: Ensure test262 and test262-jit results are stored in the same file

---

AK/URLParser.cpp
Tests/AK/TestURL.cpp

Previously, `URLParser` was constructing a new String for every character of the URL's username and password. This change improves performance by eliminating those unnecessary String allocations.
A URL with a 100,000 character password can now be parsed in ~30ms vs ~8 seconds previously on my machine.
This fixes OSS fuzz issue: [60428](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60428)

AK: Avoid unnecessary String allocations for URL username and password 

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibGfx/Painter.cpp
Userland/Libraries/LibGfx/Path.cpp
Userland/Libraries/LibGfx/TextLayout.cpp
Userland/Libraries/LibGfx/TextLayout.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h

See commits description for details.

LibWeb: Implement text run painting in GPU painter

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/HTML/button-attributes.txt
Tests/LibWeb/Text/input/HTML/button-attributes.html
Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibIDL/IDLParser.h
Userland/Libraries/LibIDL/Types.h
Userland/Libraries/LibWeb/HTML/HTMLButtonElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLButtonElement.h
Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl
Userland/Libraries/LibWeb/HTML/Scripting/Fetching.idl
Userland/Libraries/LibWeb/SVG/SVGScriptElement.idl

Fixes https://github.com/SerenityOS/serenity/issues/21778

LibWeb/LibIDL/Meta: Implement more correct parsing of reflected DOMString

---

Userland/Libraries/LibJS/JIT/Compiler.cpp

Fixes test262 regression in 24d507052053fc5c1c45dc7f1f8dd5d3a3369be2

LibJS/JIT: Bail in UnsignedRightShift fast path if result is negative

---

Userland/Applications/Assistant/Providers.cpp

If a query exactly matches an app name or a file name (case-insensitive), that result is now ranked highest.
Tested with the following queries:
* "maps" - would previously rank `Maps Settings` above `Maps`
* "/bin/ls" - the actual `ls` program was not previously in the top 6 results. `/bin/CppLanguageServer` would appear first.

Assistant: Prioritize results which exactly match a query

---

Userland/Libraries/LibJS/Parser.cpp

Before usage of GetGlobal was prevented whenever eval() is present in the scope chain.
With this change GetGlobal is emitted for `g` in the following program:
```js
function screw_everything_up() {
eval("");
}
var g;
g;
```
It makes Octane/mandreel.js benchmark run 2x faster :)
js-benchmarks result (without JIT):
```
SunSpider   3d-cube.js                               1      0.060 ± 0.060 … 0.060        0.060 ± 0.060 … 0.060
SunSpider   3d-morph.js                              1      0.070 ± 0.070 … 0.070        0.070 ± 0.070 … 0.070
SunSpider   3d-raytrace.js …
```

LibJS: Make eval() prevent GetGlobal usage less aggressively

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

For now only solid line style is supported.

LibAccelGfx+LibWeb: Add basic line painting support

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/Animation.h
Userland/Libraries/LibWeb/Animations/Animation.idl
Userland/Libraries/LibWeb/Animations/AnimationPlaybackEvent.cpp
Userland/Libraries/LibWeb/Animations/AnimationPlaybackEvent.h
Userland/Libraries/LibWeb/Animations/AnimationPlaybackEvent.idl
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/idl_files.cmake

LibWeb: Implement some Animation methods and add AnimationPlaybackEvent

---

Tests/LibPDF/TestPDF.cpp
Userland/Libraries/LibPDF/Function.cpp

I didn't find example code for this and the AI assistant did very poorly on this as well. So I had to write it all by myself!
It can be much more efficient I think, but I think the overall shape is maybe roughly fine.

LibPDF: Make SampledFunction::evaluate() work for n-dimensional input

---

Userland/Libraries/LibPDF/CommonNames.h
Userland/Libraries/LibPDF/Filter.cpp
Userland/Libraries/LibPDF/Filter.h

LibPDF: Add support for the LZW Filter

---

Userland/Libraries/LibPDF/ColorSpace.cpp

For valid PDFs, this makes no difference.
For invalid PDFs, we now assert during the cast in resolve_to() instead of returning a PDFError. However, most PDFs are valid, and even for invalid PDFs, we'd previously keep the old color space around when getting the PDF error and then usually assert later when the old color space got passed a color with an unexpected number of components (since the components were for the new color space).
Doesn't affect any of the > 2000 PDFs I use for testing locally, is less code, and should make for less surprising asserts when it does happen.

LibPDF: In ColorSpace creation code, use resolve_to() more

---

Userland/Libraries/LibPDF/Filter.cpp
Userland/Libraries/LibPDF/Reader.cpp
Userland/Libraries/LibPDF/Reader.h

This filter is used in the first page of https://w3-o.cs.hm.edu/users/ruckert/public_html/compiler/ThinkingInPostScript.pdf
@nico

LibPDF: Fix some bugs in `Filter::decode_ascii85()`

---

Userland/Shell/Shell.cpp

This makes it so program-provided completions don't have to worry about escaping, making the Shell the only authority on escaping.
Fixes the issue mentioned in https://github.com/SerenityOS/serenity/pull/21923#issuecomment-1810711516

Shell: Escape program-provided completions unless they're marked as code

---

Userland/Applications/Calculator/CalculatorWidget.cpp
Userland/Applications/Calculator/CalculatorWidget.h
Userland/Applications/Calculator/Keypad.cpp
Userland/Applications/Calculator/Keypad.h

Contributes to https://github.com/SerenityOS/serenity/issues/17128

Calculator: Convert DeprecatedString to String

---

Userland/Libraries/LibTimeZone/TimeZone.cpp

On my mac, the zoneinfo location is /usr/share/zoneinfo.default. This breaks our implementation for finding the system time zone, which was assuming the zoneinfo location contains "/zoneinfo/". This patch makes the implementation a bit more lenient.
This didn't break tests on CI because we fallback to UTC, which is the time zone CI machines are in anyways.

LibTimeZone: Handle systems with varying zoneinfo file locations

---

Userland/Libraries/LibPDF/Renderer.cpp

They just get upsampled to 8 bits per pixel images.

LibPDF: Support images with 1, 2, 4 bits per pixel

---

Meta/gn/build/extract_archive_contents.py
Meta/gn/secondary/Tests/BUILD.gn
Meta/gn/secondary/Tests/LibJS/BUILD.gn
Meta/gn/secondary/Tests/unittest.gni
Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibLocale/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibTimeZone/BUILD.gn

And some changes to support it + bring the GN build up-to-date with related features.

Meta: Add test-js to the GN build

---

Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/Animation.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h

LibWeb: Implement Animation's update finished state procedure

---

Userland/Libraries/LibAccelGfx/GL.cpp
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

For now corners antialiasing is missing.

LibAccelGfx+LibWeb: Implement rounded corners rectangle painting

---

Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp

This doesn't implement any missing features, but fills out the methods to make actually doing the right thing :tm: easier for a future patch.

LibWeb: Update window.open and choose a navigable to match the current spec steps

---

Userland/Libraries/LibGfx/TIFFGenerator.py

Unbreaks building with macOS 13 system python, and is less code too. No behavior change.

LibGfx: Unbreak building with Python 3.9

---

Userland/Libraries/LibGfx/TIFFGenerator.py

LibGfx/TIFF: Rename `BitPerSample` => `BitsPerSample`

---

Userland/Libraries/LibAccelGfx/GL.cpp
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp

With this change color blending for gradients matches CPU painter.

LibAccelGfx: Premultiply linear gradient colors by alpha

---

Userland/Libraries/LibGfx/TIFFGenerator.py

This will become handy really soon :^)

LibGfx/TIFF: Automatically export all enums associated with tags

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp

This makes us decode `quad-lzw.tif` from libtiff's test suite: https://libtiff.gitlab.io/libtiff/images.html

LibGfx/TIFF: Support TIFF 5.0 LZW images

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp

This change doesn't change much on its own. The idea behind this refactoring is to separate the sample reading from the decoding step. The decoder returning data byte per byte was fine as we only support 8 bits images, but this assumption won't hold for a long time. So let's decode everything beforehand and strictly partition the sample reading code somewhere else.
---
Note that https://github.com/SerenityOS/serenity/pull/22076 also move towards this direction.

LibGfx/TIFF: Decode all PackedBits beforehand

---

Base/res/html/inspector/inspector.css
Base/res/html/inspector/inspector.js
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/BrowserWindow.cpp
Userland/Applications/Browser/BrowserWindow.cpp
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWebView/InspectorClient.cpp

Plus a couple of changes to support it. 
We should add some knurling to the draggable separator, but my mental drawing energy is pretty low today, so TODO 🙃 
https://github.com/SerenityOS/serenity/assets/5600524/b67a5b03-616c-48e9-a077-7fbdbb5d4ef3
https://github.com/SerenityOS/serenity/assets/5600524/90a07905-cd24-4acd-9632-eaa60e04792d

LibWebView: Add a draggable separator between the two Inspector panes

---

Tests/LibWeb/Text/expected/DOM/createElement-with-emoji-in-tag-name.txt
Tests/LibWeb/Text/expected/DOM/setAttribute-with-emoji-in-attribute-name.txt
Tests/LibWeb/Text/expected/HTML/FormData-append-with-emoji-in-name.txt
Tests/LibWeb/Text/input/DOM/createElement-with-emoji-in-tag-name.html
Tests/LibWeb/Text/input/DOM/setAttribute-with-emoji-in-attribute-name.html
Tests/LibWeb/Text/input/HTML/FormData-append-with-emoji-in-name.html
Userland/Libraries/LibWeb/Infra/Strings.cpp

Added tests for each one, too :^)

LibWeb: Fix three StringBuilder misuse boogs in HTML string infra

---

Base/res/html/inspector/inspector.css
Userland/Libraries/LibWebView/InspectorClient.cpp

LibWebView: Draw some knurling on the draggable Inspector separator

---

Ladybird/Qt/AutoComplete.cpp
Ladybird/Qt/AutoComplete.h
Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/InspectorWidget.cpp
Ladybird/Qt/InspectorWidget.h
Ladybird/Qt/LocationEdit.cpp
Ladybird/Qt/Settings.cpp
Ladybird/Qt/SettingsDialog.cpp
Ladybird/Qt/SettingsDialog.h
Ladybird/Qt/StringUtils.cpp
Ladybird/Qt/StringUtils.h
Ladybird/Qt/Tab.cpp
Ladybird/Qt/Tab.h
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebSocketImplQt.cpp
Ladybird/Qt/main.cpp
Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn

This PR includes:
* String management improvements (make infallible [ref #20405], reduce unneeded API duplication)
* Qt widget management - don't doubly-own objects, make sure things are consistently owned by Qt

Ladybird/Qt: Some memory management improvements

---

Userland/Libraries/LibPDF/ColorSpace.cpp

Gfx::ICC::Profile's current API takes bytes, so we need to do some contortions for LAB values to go through.
This will probably become nicer once we implement all the backward transforms in Gfx::ICC::Profile, but for now let's hack it in on the LibPDF side.
Makes colors in 0000651.pdf looks good, especially on pages 1 and 7-12.

LibPDF: Convert LAB values to bytes differently

---

Userland/Games/Snake/CMakeLists.txt
Userland/Games/Snake/Game.cpp
Userland/Games/Snake/MainWidget.h
Userland/Games/Snake/Snake.gml
Userland/Games/Snake/main.cpp

My attempt at porting the Snake game to GML.
Let me know if I need to make any updates.

Snake: Use new GML compiler

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp

When all the variables in a for..in/of block's lexical scope have been turned into locals, we don't need to create and immediately abandon an empty environment for them.
This avoid environment allocation in cases like this:
function foo(a) {
for (const x of a) {
}
}

LibJS: Elide empty lexical environment in for..in/of blocks

---

Ladybird/Android/src/main/cpp/RequestServerService.cpp
Ladybird/Android/src/main/cpp/WebSocketService.cpp
Ladybird/RequestServer/main.cpp
Ladybird/Utilities.cpp
Ladybird/WebSocket/main.cpp
Meta/Lagom/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/simple.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/simple.cpp.expectation
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
Meta/check-style.py
Tests/JSSpecCompiler/CMakeLists.txt
Tests/JSSpecCompiler/test-runner.cpp
Userland/Libraries/LibCore/Process.cpp
Userland/Libraries/LibCore/Process.h
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp
Userland/Utilities/pdf.cpp

JSSpecCompiler: Road to testing (part 3 out of 2)

---

Tests/LibWeb/CMakeLists.txt
Tests/LibWeb/TestMimeSniff.cpp
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
Userland/Libraries/LibWeb/MimeSniff/MimeType.h
Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
Userland/Libraries/LibWeb/MimeSniff/Resource.h

See https://mimesniff.spec.whatwg.org/#resource
This implements most of the pattern matching algorithms (including the image and audio or video context sniffing algos).

LibWeb/MimeSniff: Implement `Resource`

---

Tests/LibWeb/TestConfig.ini
Userland/Utilities/headless-browser.cpp

headless-browser: Add ability to skip tests

---

Ladybird/AppKit/UI/Inspector.mm
Ladybird/Qt/InspectorWidget.cpp
Ladybird/Qt/InspectorWidget.h
Userland/Applications/Browser/InspectorWidget.cpp
Userland/Applications/Browser/InspectorWidget.h
Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Libraries/LibWebView/InspectorClient.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc

https://github.com/SerenityOS/serenity/assets/5600524/f2df5a41-fe34-470d-84ef-4fd11a72ff73

LibWebView: Add Inspector actions to create and clone DOM nodes

---

Tests/LibGfx/TestImageDecoder.cpp

No need to panic the executable on a test failure.

Tests: Use `TRY_OR_FAIL` instead of `MUST` in TestImageDecoder.cpp

---

Kernel/Tasks/CrashHandler.cpp

Display some helpful information about crashes even before the first process is started.
This was quite helpful while debugging RISC-V startup.

Kernel: Make `CrashHandler` more useful before `init_stage2`

---

Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

5% speedup on Octane/mandreel.js :^)

LibJS/JIT: Add fast path for UnaryMinus on Int32

---

Meta/Lagom/Tools/CodeGenerators/LibWebView/GeneratePublicSuffixData.cpp

LibWeb: Do not treat a prefix of public suffix as a valid public suffix

---

Userland/Libraries/LibELF/DynamicLoader.cpp

It's possible for a malloc inside load_program_headers() to steal the reserved memory space we created for the program headers. Remove the reservation later in the method.

LibELF: Remove loader reservation after most allocating operations

---

Userland/Services/RequestServer/ConnectionCache.cpp
Userland/Services/RequestServer/ConnectionCache.h

Prior to this commit, it was possible to get a socket stuck in a state with enqueued entries, waiting for a nonexistent request to finish. This state could be entered by issuing a request immediately after the completion of another one, and before deferred_invoke execution in the event loop.
This commit closes this hole by making sure the socket is never in a state where it can queue requests without an active job.

RequestServer: Avoid race condition between cached request end/start

---

Ladybird/Qt/WebContentView.cpp

Fixes regression introduced in b73ae80d8b1577d583235005831bc623ac00fad7

Ladybird/Qt: Apply to_content_position after scaling event coordinates

---

Tests/LibWeb/Layout/expected/grid/auto-fit-empty-container.txt
Tests/LibWeb/Layout/input/grid/auto-fit-empty-container.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Fixes https://github.com/SerenityOS/serenity/issues/22319

LibWeb: Fix division by zero in auto-fit/fill track calculation in GFC

---

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h

Step towards making the paintable tree independent of the layout tree.

LibWeb: Resolve box shadow data for paintable boxes during layout

---

Tests/LibPDF/TestPDF.cpp
Userland/Libraries/LibPDF/Document.cpp
Userland/Libraries/LibPDF/Parser.cpp
Userland/Libraries/LibPDF/Parser.h
Userland/Libraries/LibPDF/Renderer.cpp

I had hoped to get the actual drawing of inline images out this evening, but debugging other issues and bisecting regressions took too long. Here are some prep commits for it though.

LibPDF: Some prep for inline images

---

Tests/LibWeb/Ref/overflow-hidden-2.html
Tests/LibWeb/Ref/overflow-hidden.html
Tests/LibWeb/Ref/reference/overflow-hidden-2-ref.html
Tests/LibWeb/Ref/reference/overflow-hidden-ref.html

Adds ref-tests from pages used in the following PRs: https://github.com/SerenityOS/serenity/pull/16035
https://github.com/SerenityOS/serenity/pull/17591

Tests/LibWeb: Add ref-tests for "overflow: hidden"

---

Tests/LibWeb/Text/input/get-bounding-client-rect.html
Tests/LibWeb/Text/input/include.js
Userland/Utilities/headless-browser.cpp

This fixes the hangs for me. :^) Second commit is there more as a "just in case" measure.

LibWeb: Fix freeze when running tests, and clear the current document between each one

---

Userland/Libraries/LibGfx/TIFFGenerator.py

LibGfx: Do not use double negation in TIFFGenerator.py

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibJS/Heap/CellAllocator.cpp
Userland/Libraries/LibJS/Heap/CellAllocator.h
Userland/Libraries/LibJS/Heap/Heap.cpp
Userland/Libraries/LibJS/Heap/Heap.h
Userland/Libraries/LibJS/Heap/HeapBlock.cpp
Userland/Libraries/LibJS/Heap/HeapBlock.h
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormatFunction.cpp
Userland/Libraries/LibJS/Runtime/Intl/NumberFormatFunction.h
Userland/Libraries/LibJS/Runtime/Symbol.cpp
Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/CSS/CSSFontFaceRule.cpp
Userland/Libraries/LibWeb/FileAPI/FileList.cpp
Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
Userland/Libraries/LibWeb/HTML/HTMLDataListElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLDocument.cpp
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Userland/Libraries/LibWeb/HTML/ListOfAvailableImages.cpp
Userland/Libraries/LibWeb/HTML/ListOfAvailableImages.h
Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
Userland/Libraries/LibWeb/HTML/SharedImageRequest.h
Userland/Libraries/LibWeb/HTML/TrackEvent.cpp

LibJS+LibWeb: Some GC bug fixes

---

Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp

This was a normative change in the Array.fromAsync spec which we already implemented :^). See:
https://github.com/tc39/proposal-array-from-async/commit/689d0d
I've left a FIXME in there for some other bug which we have which is causing some test262 test cases to fail.

LibJS: Update spec comments in Array.fromAsync

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h

More refactoring, nothing particularly exciting. A slight increase in code from all the `transaction.commit()`s.
The remaining properties are grid-related, which confuse me a lot, so this seemed like a good place to submit a PR. I'd actually finished all of this except the last commit over 2 weeks ago, oops. :sweat_smile:

LibWeb: Parse more CSS properties using TokenStreams

---

Userland/Applications/Calendar/CMakeLists.txt
Userland/Applications/Calendar/CalendarWidget.cpp
Userland/Applications/Calendar/main.cpp

Contributes towards: https://github.com/SerenityOS/serenity/issues/21091

Calendar: Add a link to the Manual in Help Menu

---

Kernel/API/Syscall.h
Kernel/Syscalls/execve.cpp
Kernel/Syscalls/fork.cpp
Kernel/Syscalls/ioctl.cpp
Kernel/Syscalls/mmap.cpp
Kernel/Syscalls/socket.cpp
Kernel/Syscalls/thread.cpp
Kernel/Tasks/Process.h
Kernel/Tasks/Thread.cpp
Kernel/Tasks/Thread.h

~8~7 syscalls down, ~20~21 more to go.

Kernel: Mark a bunch of syscalls as not needing the big process lock.

---

Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp

Fixes https://github.com/SerenityOS/serenity/issues/22451

LibWeb: Skip erroneous blit/sample corner commands in RecordingPainter

---

Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Services/WebContent/WebContentServer.ipc

LibWebView+WebContent: Make some browser -> WebContent IPCs async

---

Kernel/KSyms.cpp

This PR fixes generation of backtraces for RISC-V, as RISC-V uses a different convention of storing frame records.
Dumping backtraces currently won't work while the initial stack in front of the kernel image is in use, as `dump_backtrace_impl` checks if `stack_ptr` is less than `kernel_mapping_base`.
The naming of the variables doesn't really match RISC-V (`stack_ptr` isn't really the stack pointer on RISC-V), but this is the best way of keeping the backtrace dumping code in one function. Although we maybe should consider moving the code into `Arch/`.
The layout of the stack frame record is documented [here](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#frame-pointer-convention)

Kernel/riscv64: Fix backtrace generation on RISC-V

---

Tests/LibRegex/Regex.cpp
Userland/Libraries/LibRegex/RegexParser.cpp

LibRegex: Error out on Eof when parsing nonempty class range elements

---

Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp

Now that https://github.com/whatwg/html/issues/9686 is fixed, let's fix it the exact same way in our implementation. :^)

LibWeb: Update create_new_child_navigable() after spec fix

---

Userland/Libraries/LibCrypto/Authentication/GHash.cpp
Userland/Libraries/LibTLS/Record.cpp
Userland/Libraries/LibTLS/Socket.cpp
Userland/Libraries/LibTLS/TLSv12.h

Transfer of a local 64M file, 55s -> 1.2s :P

LibTLS+LibCrypto: Make RS go faster as if by magic

---

Tests/LibWeb/Layout/expected/grid/justify-content.txt
Tests/LibWeb/Layout/input/grid/justify-content.html
Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Fixes https://github.com/SerenityOS/serenity/issues/22555

LibWeb: Add support for start, center and end justify-content in GFC

---

Userland/Libraries/LibWeb/DOM/Document.cpp

The entire subtree of an element with display:none is irrelevant for purposes of layout and/or paint invalidation.
We now simply ignore invalidation triggers inside such subtrees.
This avoids a *lot* of redundant busywork when running CSS animations inside not-even-rendered content. As an example, this avoids repainting YouTube embeds repeatedly due to animating-but-hidden progress indicators.
Note that the subtree *root* (i.e the `display:none` element itself) still gets to trigger invalidation, since we may need to rebuild the layout tree when the `display` property changes.

LibWeb: Ignore layout/paint invalidations in subtree under display:none

---

Tests/LibWeb/Layout/expected/grid/auto-fill-and-named-line-placement.txt
Tests/LibWeb/Layout/expected/grid/columns-auto-fill-with-gap.txt
Tests/LibWeb/Layout/input/grid/auto-fill-and-named-line-placement.html
Tests/LibWeb/Layout/input/grid/columns-auto-fill-with-gap.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

Fixes https://github.com/SerenityOS/serenity/issues/22603

LibWeb: Account for gap in auto-fill columns count calculation in GFC

---

Documentation/FAQ.md

Explain a bit about what pkg is and what it isn't, and clarify that
while Serenity kinda-sorta has the beginnings of a "package manager",
it's not exactly like a typical Linux package manager with binary
software.

Documentation: Expand package manager FAQ with pkg info

---

Userland/Applications/HexEditor/HexEditor.cpp

I meant to start working on adding annotations, but got a bit distracted, so here are some assorted tweaks that won't belong in that PR, whenever it happens.

HexEditor: Minor tweaks

---

Userland/Applications/Calendar/AddEventDialog.cpp
Userland/Applications/Calendar/AddEventDialog.gml
Userland/Applications/Calendar/AddEventDialog.h
Userland/Applications/Calendar/CalendarWidget.cpp
Userland/Applications/Calendar/CalendarWidget.h
Userland/Applications/Calendar/EventCalendar.cpp
Userland/Applications/Calendar/EventManager.cpp
Userland/Applications/Calendar/EventManager.h
Userland/Applications/Calendar/main.cpp
Userland/Libraries/LibCore/DateTime.cpp
Userland/Libraries/LibCore/DateTime.h
Userland/Libraries/LibGUI/CMakeLists.txt
Userland/Libraries/LibGUI/Calendar.cpp
Userland/Libraries/LibGUI/Calendar.h
Userland/Libraries/LibGUI/DatePicker.cpp
Userland/Libraries/LibGUI/DatePicker.h
Userland/Libraries/LibGUI/DatePickerDialog.gml
Userland/Libraries/LibGUI/Forward.h

This PR contains some small improvements for the calendar application:
- Added a date picker dialog to make selecting dates easier
- Refactored the code a little bit to make calendar events easier to work with
- Removed some unused code
- Ask about unsaved changes when attempting to close the window (fixes #21713)

Calendar improvements

---

LICENSE

I'd forgotten to add this in #22625 and it was already merged by the time I'd realised my mistake!
Let me know if there's anything else that needs the year range updated

Meta: Update the year range in LICENSE

---

Tests/LibGfx/TestImageDecoder.cpp

Tests/LibGfx: Fix a typo

---

Userland/Games/Hearts/CMakeLists.txt
Userland/Games/Hearts/Game.cpp
Userland/Games/Hearts/Hearts.gml
Userland/Games/Hearts/MainWidget.h
Userland/Games/Hearts/main.cpp

Hearts: Port to GML compiler

---

Userland/Applications/Escalator/CMakeLists.txt
Userland/Applications/Escalator/Escalator.gml
Userland/Applications/Escalator/EscalatorWindow.cpp
Userland/Applications/Escalator/EscalatorWindow.h
Userland/Applications/Escalator/MainWidget.h
Userland/Applications/Escalator/main.cpp

Contributes to: https://github.com/SerenityOS/serenity/issues/20518

Escalator: Port Escalator to GML Compiler

---

Userland/Services/RequestServer/ConnectionCache.cpp
Userland/Services/RequestServer/ConnectionCache.h

This really only implements a heuristic, assuming that HTTP/1.0 servers cannot handle having multiple active connections; this assumption has lots of false positives, but ultimately HTTP/1.0 is an out-of-date HTTP version and people using it should just switch to a newer standard anyway.
Specifically, python's "SimpleHTTPRequestHandler" utilises a single-threaded HTTP/1.0 server, which means no keepalive and more importantly, hangs and races with more than a single connection present. This commit makes it so we serialise all requests to servers that are known to serve only a single request per connection (aka HTTP/1.0 with our setup, as we unconditionally request keepalive)

RequestServer: Avoid multiple connections to incompatible servers

---

Userland/Libraries/LibPDF/Renderer.cpp

An image mask is a 1-bit-per-pixel bitmap that's black where the current color should be painted, and white where it should be transparent (think: like ink).
load_image() already converts images like this into 8-bit-per-pixel images that have 0xff, 0xff, 0xff in rgb for opaque (originally 0 bit) pixels and 0, 0, 0 in rgb for transparent pixels.
So we just move copy the image mask's image data into the alpha channel and replace rgb with the current color, and then draw it like a regular bitmap.

LibPDF: Add support for image masks

---

Base/usr/share/man/man5/GML/Widget/NumericInput.md
Userland/Applications/PDFViewer/CMakeLists.txt
Userland/Applications/PDFViewer/PDFViewerWidget.cpp
Userland/Applications/PDFViewer/PDFViewerWidget.h
Userland/Libraries/LibGUI/CMakeLists.txt
Userland/Libraries/LibGUI/NumericInput.cpp
Userland/Libraries/LibGUI/NumericInput.h

I wanted to use it in HexEditor, so here we go!

LibGUI+PDFViewer: Move NumericInput into LibGUI, and improve it a little

---

Userland/Applications/SystemMonitor/ProcessModel.cpp

This PR makes it so that the Idle Task is no longer displayed in the Processes tab and is not included in the process count in the status bar.
Andreas had previously mentioned in a video that he didn't expect the Idle Task to appear in the Processes tab.
I've also included a non functional change that replaces a for loop with a range-based for loop in `ProcessModel::update()`. This prevents a counter variable being shadowed and improves readability.

SystemMonitor: Don't include the Idle Task in process statistics

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

Fixes oss-fuzz issue [65500](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65500)
The two last commits are things that I found on my own while looking at the code. The last would also fix the oss-fuzz issue.

LibGfx/TIFF: Another round of fixes for a fuzzer-found bug

---

Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp

We were (again) throwing even though the image could be decoded: only 1 image out of 9 could be decoded properly from the [samples](https://netghost.narod.ru/gff/sample/images/iff/index.htm) on this page.
Before:
After:

LibGfx/ILBMLoader: Don't throw too early when decoding bitplanes

---

Base/usr/share/man/man5/GML/Widget/NumericInput.md

I forgot to do this when I added them.

Base: Document NumericInput properties

---

Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp

No need to walk the NamedNodeMap twice for these. Also, for the "id" attribute, we can use the cache in Element::id().

LibWeb: Combine has_attribute/attribute calls in HTMLFormElement

---

Userland/Libraries/LibGfx/ICC/Profile.cpp
Userland/Libraries/LibGfx/ICC/Profile.h
Userland/Libraries/LibPDF/ColorSpace.cpp
Userland/Libraries/LibPDF/ColorSpace.h
Userland/Libraries/LibPDF/Renderer.cpp

See #22700 for numbers. This is "icc-fastererer" from the table over there. All numbers in the commit descriptions are for workload 1 described over there.

LibGfx/ICC+LibPDF: Speedups, round 3

---

Kernel/CMakeLists.txt
Kernel/Devices/HID/AllMiceDevice.cpp
Kernel/Devices/HID/AllMiceDevice.h
Kernel/Devices/HID/Management.cpp
Kernel/Devices/HID/Management.h
Kernel/Devices/HID/MouseDevice.cpp
Userland/Services/SystemServer/main.cpp
Userland/Services/WindowServer/EventLoop.cpp
Userland/Services/WindowServer/EventLoop.h

Kernel+Userspace: Add simplistic USB mouse hotplug capability for userspace

---

Userland/Utilities/pixelflut.cpp

Using our client in practice some more, here’s two ways of making it more competitive without fixing the kernel networking stack.
Very contested servers are likely to cause EAGAIN socket errors on the
client. Since these errors are not supposed to be fatal, just try
sending the pixel again.
This was tested successfully against massively contested 37c3 pixelflut
servers.
These allow column-wise, traditional scanline, or random pixel flooding.
Depending on the use case and amount of contestion, any of the
strategies may work best, as tested on 37c3.

pixelflut: Two improvements from 37c3

---

Userland/Libraries/LibCore/DirIterator.cpp

LibCore: Avoid running fstatat on skipped entries in DirIterator

---

Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/BrowserWindow.h
Userland/Applications/Browser/main.cpp

Browser: Add help menu item

---

Userland/Applications/Calendar/AddEventDialog.cpp
Userland/Applications/Calendar/AddEventDialog.gml
Userland/Applications/Calendar/AddEventDialog.h

Fixes #22620, fixes #22621, closes #22623.

Calendar: Fix issues and implement duration feature in AddEventDialog

---

Base/usr/share/man/man1/Applications/About.md
Base/usr/share/man/man1/Applications/AnalogClock.md
Base/usr/share/man/man1/Applications/Assistant.md

Base: Improve About, AnalogClock & Assistant manpages

---

Tests/LibWeb/Text/expected/DOM/Element-getAttributeNS.txt
Tests/LibWeb/Text/input/DOM/Element-getAttributeNS.html
Userland/Libraries/LibWeb/DOM/DOMImplementation.cpp
Userland/Libraries/LibWeb/DOM/DOMImplementation.h
Userland/Libraries/LibWeb/DOM/DOMImplementation.idl
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Document.idl
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl
Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp

As part of digging into trying to get attribute namespaces working better (not being applied as expected in certain cases)

LibWeb: Implement Element.getAttributeNS

---

Userland/DevTools/HackStudio/Editor.cpp
Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/LanguageServers/ConnectionFromClient.cpp
Userland/DevTools/HackStudio/ProjectTemplate.cpp
Userland/DevTools/HackStudio/ProjectTemplate.h
Userland/DevTools/HackStudio/main.cpp

...and convert `ProjectTemplate::create_project()` to `ErrorOr` to make that easier.

HackStudio: Use Core::System APIs where possible

---

Userland/Libraries/LibVideo/Containers/Matroska/Document.h
Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.cpp
Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.h
Userland/Libraries/LibVideo/Containers/Matroska/Reader.cpp
Userland/Utilities/matroska.cpp

Work on https://github.com/SerenityOS/serenity/issues/22447

LibVideo: Replace DeprecatedFlyString with FlyString

---

Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/AST.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/ASTPrinting.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/CompilerPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/CFGBuildingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/DeadCodeEliminationPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/DeadCodeEliminationPass.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/ReferenceResolvingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/ReferenceResolvingPass.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/SSABuildingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/StronglyConnectedComponents.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Forward.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/CppASTConverter.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/simple.cpp.expectation
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp

While DCE is not strictly necessary, it aids debugging experience and is a net addition of only 130 lines of code.

JSSpecCompiler: The last PR upstreaming code I wrote in August

---

Userland/Libraries/LibC/arch/riscv64/setjmp.S
Userland/Libraries/LibC/setjmp.h

This implementation passes TestLibCSetjmp, so it should hopefully be correct.

LibC: Implement setjmp and longjmp for riscv64

---

Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Object.h
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.h
Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.round.js

Going through some places and bulk updating them, leaving around plenty of FIXMEs.
Appears to fix four crashes, and four timeouts by updating the RoundDuration AO specifically.
Have some other changes sitting around locally implementing calendar record, but that seems like it will involve updating a lot of places to use it.
Diff Tests:
+8 ✅    -4 💀    -4 💥️

LibJS: Catch up to some temporal spec changes

---

Meta/run.py

System python on macOS is python 3.9, so make run.py work with that. Luckily, the changes needed for that aren't super terrible.

Make run.py work with python 3.9

---

Userland/Libraries/LibPDF/Filter.cpp

The predictor code assumed that all stream data is image data (...which would make sense: trailing data there is wasted space).
But some PDFs have trailing data there, e.g. 0000257.pdf, so be forgiving about it.

LibPDF: Be more forgiving about trailing image data

---

Meta/run.py

"Setup" is the noun, "to set up" is the verb.

Meta/run.py: Fix grammar in method names

---

Tests/LibWeb/Ref/reference/transform-2d-translate-ref.html
Tests/LibWeb/Ref/transform-2d-translate.html
Userland/Libraries/LibWeb/CSS/Transformation.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Userland/Libraries/LibWeb/Painting/StackingContext.h

Fixes https://github.com/SerenityOS/serenity/issues/22797

LibWeb: Resolve CSS transform lengths against padding rect

---

Tests/LibWeb/Layout/expected/grid/intrinsic-sizing-should-account-for-gaps.txt
Tests/LibWeb/Layout/input/grid/intrinsic-sizing-should-account-for-gaps.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Fixes https://github.com/SerenityOS/serenity/issues/22804

LibWeb: Account for gaps in grid container's intrinsic size calculation

---

Userland/Applications/KeyboardSettings/CMakeLists.txt
Userland/Applications/KeyboardSettings/Keyboard.gml
Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.cpp
Userland/Applications/KeyboardSettings/KeyboardSettingsWidget.h
Userland/Applications/KeyboardSettings/KeymapDialog.gml
Userland/Applications/KeyboardSettings/KeymapDialog.h
Userland/Applications/KeyboardSettings/main.cpp

KeyboardSettings: Port to GML compiler

---

Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
Userland/Applications/TerminalSettings/CMakeLists.txt
Userland/Applications/TerminalSettings/MainWidget.cpp
Userland/Applications/TerminalSettings/MainWidget.h
Userland/Applications/TerminalSettings/TerminalSettingsMain.gml
Userland/Applications/TerminalSettings/TerminalSettingsView.gml
Userland/Applications/TerminalSettings/ViewWidget.cpp
Userland/Applications/TerminalSettings/ViewWidget.h
Userland/Applications/TerminalSettings/main.cpp

Contributes to: https://github.com/SerenityOS/serenity/issues/20518

TerminalSettings: Port to GML Compiler

---

Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/AST.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/ASTPrinting.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/CompilerPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/GenericASTPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/FunctionCallCanonicalizationPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/FunctionCallCanonicalizationPass.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/ReferenceResolvingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/SSABuildingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/DiagnosticEngine.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/DiagnosticEngine.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Forward.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/CppASTConverter.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/Lexer.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/Lexer.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/ParseError.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/ParseError.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/TextParser.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/TextParser.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/simple.cpp.expectation
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/spec-no-new-line-after-dot.xml
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/spec-no-new-line-after-dot.xml.expectation
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/spec-single-function-simple.xml
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Tests/spec-single-function-simple.xml.expectation
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
Tests/JSSpecCompiler/test-runner.cpp

I also stopped trying to make diff ~250 lines since I doubt it significantly influences review time. But in case I'm wrong I'll happily continue my practice of submitting moderately small PRs.

JSSpecCompiler: Work on the `-xspec` parser (and a test for it!)

---

Userland/Shell/AST.cpp

This PR replaces the custom `find_reverse()` function used for searching backwards through string-based history events with reverse iterators + `find_if()`

Shell: Use reverse iterators for string-based history event searches

---

Userland/Utilities/disasm.cpp

This is part 2 of a long chain of PRs and commits that add RISC-V disassembly support. Today: Two changes to disasm that (1) improve and fix the way symbols are printed and (2) allow just one symbol to be printed.
We now split up symbols into zero-sized symbols that label single
instructions (no need to separate them by newlines; they are used for
jump labels and relocation targets within a larger block of code) and
ranged symbols that label functions. Empty symbols are discarded since
at least RISC-V ELF files contain quite a few of those. Zero-sized
symbols and ranged symbols are handled almost the same, but this way we
can make sure that zero-sized symbols don't interfere with ranged
symbol's newline separation logic. For zero-sized symbols, the "symbol
contains address" logic is …

 RISC-V disassembly, part 2/N: disasm: All-around better symbol handling

---

Userland/Applications/Welcome/CMakeLists.txt
Userland/Applications/Welcome/WelcomeWidget.cpp
Userland/Applications/Welcome/WelcomeWidget.h
Userland/Applications/Welcome/WelcomeWindow.gml
Userland/Applications/Welcome/main.cpp

Contributes to: https://github.com/SerenityOS/serenity/issues/20518

Welcome: Port Welcome to GML Compiler

---

Userland/Utilities/headless-browser.cpp

This is the same feature that run-tests has on Serenity.

headless-browser: Add option to filter which tests are run with a glob

---

Meta/gn/secondary/Userland/Libraries/LibWeb/SVG/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Tests/LibWeb/Text/expected/Streams/init-from-fetch.txt
Tests/LibWeb/Text/input/Streams/init-from-fetch.html
Userland/Libraries/LibWeb/Fetch/BodyInit.cpp

LibWeb: Set up the Fetch response's body with the appropriate stream

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/BrowserWindow.cpp
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Userland/Applications/Browser/BrowserWindow.cpp
Userland/Applications/Browser/Tab.cpp
Userland/Applications/Browser/Tab.h
Userland/Libraries/LibSQL/Value.cpp
Userland/Libraries/LibSQL/Value.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/Loader/LoadRequest.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/CookieJar.cpp
Userland/Libraries/LibWebView/CookieJar.h
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Services/WebContent/WebDriverConnection.cpp
Userland/Utilities/headless-browser.cpp

Ladybird+LibWebView: Port the CookieJar and Cookie IPCs to String

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

LibGfx/JPEGLoader: Extract inverse_dct_8x8() function

---

Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
Tests/LibWeb/Text/expected/Streams/ReadableByteStream-byob-tee.txt
Tests/LibWeb/Text/expected/Streams/ReadableByteStream-default-tee.txt
Tests/LibWeb/Text/expected/Streams/ReadableStream-default-tee.txt
Tests/LibWeb/Text/input/Streams/ReadableByteStream-byob-tee.html
Tests/LibWeb/Text/input/Streams/ReadableByteStream-default-tee.html
Tests/LibWeb/Text/input/Streams/ReadableStream-default-tee.html
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h
Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.h
Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
Userland/Libraries/LibWeb/Streams/ReadableStream.h
Userland/Libraries/LibWeb/Streams/ReadableStream.idl

:sleeping: 
Teeing has been a big ol' FIXME for a while, and we recently butted heads against it, so let's implement it!

LibWeb: Implement and utilize support for teeing streams

---

Kernel/Arch/riscv64/PageDirectory.cpp

Most of this code is just copy-pasted from aarch64 with minor changes for RISC-V.
The next big step to progress further in the boot process is context switching.

Kernel/riscv64: Implement everything in PageDirectory.cpp

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

LibGfx/JPEGLoader: Use ceil_div

---

Tests/LibWeb/Text/expected/Streams/ReadableStreamBYOBReader-respondWithNewView.txt
Tests/LibWeb/Text/input/Streams/ReadableStreamBYOBReader-respondWithNewView.html
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.h
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.idl

The AO behind this prototype was added in commit ed1076d9ca12d3ec3492fc8dd6fbfbf5f3cc3c19,
so we can now trivially expose the prototype as well.

LibWeb: Implement ReadableStreamBYOBRequest.respondWithNewView

---

Userland/Services/Taskbar/TaskbarWindow.cpp

**had to open the pr again because it seems like i messed up my previous fork? 😅😅
Just discovered and tried out the system today, and then I stumbled upon the fact that it didnt showed the classical context menu when i right clicked the taskbar. I found it quite unexpected, so i decided to implement one myself.
And thus this pr, which aims to add just that, came to be. It adds a simple context menu when the user clicks with the right button on the taskbar.
Right now its pretty simple and straight forward, but the idea can be easily expanded upon. Hope you guys like it :^)

Userland/TaskbarWindow: Show context menu on right click

---

Tests/Kernel/TestTCPSocket.cpp

We should wait for a server thread to actually listen(2) a server socket before trying to connect to it. This hopefully should make the test less flaky.

Tests/Kernel: Properly synchronize threads in TestTCPSocket

---

Userland/Libraries/LibCore/DateTime.cpp
Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js

LibJS+LibCore: Support more weird date formats found on the web

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Runtime/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
Userland/Libraries/LibJS/Runtime/Intl/ListFormat.cpp
Userland/Libraries/LibJS/Runtime/Iterator.cpp
Userland/Libraries/LibJS/Runtime/Iterator.h
Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
Userland/Libraries/LibJS/Runtime/SetConstructor.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/Value.h
Userland/Libraries/LibJS/Runtime/WeakSetConstructor.cpp

A bit of a refactor in ECMA-262.

LibJS: Implement and use the IteratorStepValue AO

---

Tests/LibWeb/Text/expected/HTML/Form-named-property-access.txt
Tests/LibWeb/Text/expected/HTML/form-implicit-submission.txt
Tests/LibWeb/Text/input/HTML/Form-named-property-access.html
Tests/LibWeb/Text/input/HTML/form-implicit-submission.html
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp

https://github.com/SerenityOS/serenity/assets/5600524/eb9512d4-1f54-45cc-abc6-03a8f3c02eb4
Fixes #23008, fixes #22537, fixes #22705

LibWeb: Implement implicit submission of HTMLFormElement

---

Meta/CMake/time_zone_data.cmake
Meta/gn/secondary/Userland/Libraries/LibTimeZone/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/MimeSniff/BUILD.gn

https://mm.icann.org/pipermail/tz-announce/2024-February/000081.html

LibTimeZone: Update to TZDB version 2024a

---

AK/Assertions.h
Tests/LibJS/test262-runner.cpp
Userland/Libraries/LibDSP/MDCT.h
Userland/Utilities/tsort.cpp

A, should not be controversial, part of https://github.com/SerenityOS/serenity/pull/21995

Everywhere: Prefer `VERIFY` over `assert()`

---

Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
Userland/Libraries/LibWeb/Animations/AnimationEffect.h
Userland/Libraries/LibWeb/Animations/AnimationPlaybackEvent.cpp
Userland/Libraries/LibWeb/Animations/AnimationPlaybackEvent.h
Userland/Libraries/LibWeb/Animations/AnimationTimeline.h
Userland/Libraries/LibWeb/Animations/DocumentTimeline.cpp
Userland/Libraries/LibWeb/Animations/DocumentTimeline.h
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp

A host of very simple fixes found while trying to integrate Web Animations into StyleComputer.
Word towards #21570.

LibWeb: A bunch of misc Animation fixes

---

Userland/Libraries/LibJS/Runtime/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.since.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.until.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.since.js
Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.until.js

LibJS: Some temporal spec updates to fix some roundingMode issues

---

Userland/Applications/Presenter/CMakeLists.txt
Userland/Applications/Presenter/PresenterWidget.cpp
Userland/Applications/Presenter/main.cpp

Presenter: Add Manual link in help menu

---

Userland/Libraries/LibGfx/Font/OpenType/Font.cpp

See #17189 -- this confused me for a bit.

LibGfx: Add a comment to Font::try_load_from_offset()

---

Userland/Utilities/cp.cpp

- Add interactive flag which tells `cp` to prompt before overwriting files
- Accept 'yes', 'no', 'n', and 'y' as input, all other inputs will result in the prompt being shown again

cp: add `--interactive`/`-i` flag

---

Userland/Libraries/LibAudio/FlacTypes.h
Userland/Libraries/LibAudio/FlacWriter.cpp
Userland/Libraries/LibAudio/FlacWriter.h
Userland/Libraries/LibAudio/GenericTypes.cpp
Userland/Libraries/LibAudio/GenericTypes.h

This contains a seekpoint every 2 seconds, allowing our own players to work better.

LibAudio: Automatically write a FLAC seektable

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

JPEGStream::byte_offset() now returns an offset relative to the start of the stream, instead of relative to the buffered part.
No behavior change except if JPEG_DEBUG is set.

LibGfx/JPEGLoader: Make byte_offset() return offset from start of stream

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

That means that we only need to wait for @nico to finish `LibPDF` and a program to extract all tags from the spec file to support all Exif tags :tada:

LibGfx/TIFF: Explore underlying IFDs

---

Tests/LibWeb/Text/expected/PerformanceObserver/PerformanceObserver_basic.txt
Tests/LibWeb/Text/input/PerformanceObserver/PerformanceObserver_basic.html
Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HighResolutionTime/TimeOrigin.cpp
Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp

[Peek 2024-02-04 21-19.webm](https://github.com/SerenityOS/serenity/assets/11597044/c04ae3c9-f51b-435a-b494-55c22029a2b2)
Fixes #23004

LibWeb: Fix playing SVG animations (i.e. LottieFiles)

---

Userland/Libraries/LibPDF/Fonts/Type0Font.cpp

This is very similar to SimpleFont::draw_string() for now, but it'll become a bit different when we add support for vertical text.
CIDFontType now only needs to draw single glyphs. Neither of the subclasses can do that yet, so no behavior change yet.
---
More scaffolding for type0 fonts.

LibPDF: Add string drawing code for Type0Fonts

---

Ladybird/WebDriver/main.cpp
Meta/Azure/Lagom.yml
Tests/LibWeb/WPT/0001-tools-Pass-product-name-to-update-metadata-fallback-.patch
Tests/LibWeb/WPT/metadata.txt
Tests/LibWeb/WPT/run.sh

It's a bit awkward to pass these as --webdriver-arg, but that's life.
Perhaps we should do this in the ladybird.py script 🤷

LibWeb: Pass certificates to WebDriver and update WPT Metadata

---

Userland/Libraries/LibWeb/Animations/Animatable.cpp
Userland/Libraries/LibWeb/Animations/Animatable.h
Userland/Libraries/LibWeb/Animations/Animatable.idl
Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/Animation.h
Userland/Libraries/LibWeb/Animations/Animation.idl
Userland/Libraries/LibWeb/Animations/AnimationTimeline.cpp
Userland/Libraries/LibWeb/Animations/AnimationTimeline.h
Userland/Libraries/LibWeb/Animations/DocumentTimeline.cpp
Userland/Libraries/LibWeb/Animations/DocumentTimeline.h
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/Forward.h

Work towards #21570. ~~Independent of #23184~~ Actually they'll have merge conflicts, but they're at least conceptually independent and can be reviewed separately.

LibWeb: Add Animation::play() and add the Animatable interface

---

Userland/Utilities/headless-browser.cpp

Before this change, the rebaseline script would generate test reference based on 'about:blank' (at least running it on my macOS system). This commit allows 'about:blank' through the assertion and only dumps the layout tree when the loaded URL matches the one we are interested in.

LibWeb: Only dump layout and text tree for the desired URL

---

Userland/Libraries/LibPDF/Fonts/Type0Font.cpp

Of my 1000 test files, 73 have stream Type0 truetype fonts with stream CIDToGIDMaps. This makes that work.
(With this patch, the number of files in my 1000 test files complaining "Font is missing Name" increases from 41 to 75, so a bit under half of the fonts using stream CIDToGIDMaps also have no 'name' table. So that's next.)
Increases files without issues from 652 to 681.

LibPDF: Implement stream CIDToGIDMaps for Type0 CIDFontType2 fonts

---

Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
Userland/Libraries/LibWasm/AbstractMachine/Operators.h
Userland/Libraries/LibWasm/Types.h
Userland/Utilities/wasm.cpp

5.4k more passing tests :P
`Tests:       18762 failed, 1735 skipped, 31043 passed, 51540 total`

LibWasm: Implement a lot more SIMD instructions

---

Ladybird/AppKit/UI/LadybirdWebView.mm

Ladybird/AppKit: Fix select dropdown position high dpi bug

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp

Let's do the world a favor and start cleaning up IDLGenerators.cpp :upside_down_face:  The repetition we have for integral types jumped out at me recently, so this is a quick patch to reduce that.

LibWeb: Extract common integral IDL generators to a helper

---

Tests/LibWeb/WPT/run.sh

Tests/LibWeb: Make the WPT runner grab only the one commit it needs

---

Userland/Applications/ImageViewer/ViewWidget.cpp
Userland/Applications/ImageViewer/ViewWidget.h
Userland/Libraries/LibGfx/Point.cpp
Userland/Libraries/LibGfx/Point.h
Userland/Libraries/LibGfx/TIFFGenerator.py
Userland/Libraries/LibImageDecoderClient/Client.cpp
Userland/Libraries/LibImageDecoderClient/Client.h
Userland/Services/ImageDecoder/ConnectionFromClient.cpp
Userland/Services/ImageDecoder/ImageDecoderServer.ipc

ImageViewer: Transform the image's dimension accordingly to the metadata

---

Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp

We only need to know that the Global Object of the environment is an event target in order to dispatch an event on it. This resolves a FIXME where we assumed that the only type of Global in LibWeb is HTML::Window.
Fixes #23271
This will fix the assertion from 23271, but I'm not quite sure how to test it independently of that.

LibWeb: Treat global as EventTarget in notify_about_rejected_promises

---

Kernel/Devices/GPU/Management.cpp

This will add support for PCI-attached graphics adapters on RISC-V, once we reach this code and #22948 is merged.
On aarch64 `Access::is_disabled` will return true, so there shouldn't be any reason to only support PCI graphics adapters on x86.

Kernel/Graphics: Probe PCI graphics adapters on all architectures

---

Tests/LibWeb/Text/expected/DOM/Element-set-scroll-left.txt
Tests/LibWeb/Text/expected/resize-scrollable-box.txt
Tests/LibWeb/Text/input/DOM/Element-set-scroll-left.html
Tests/LibWeb/Text/input/resize-scrollable-box.html
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

LibWeb: Fix scroll offset clamping in couple of places

---

Kernel/Bus/USB/EHCI/EHCIController.cpp
Kernel/Bus/USB/EHCI/EHCIController.h

Kernel/USB: Handle non-page aligned EHCI controller BARs correctly

---

Ports/milkytracker/package.sh

Not my finest moment, I messed this up in my previous commit :^)

Ports: Fix broken syntax in Milkytracker package script

---

Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp

The old implementation of PassMode has only been tested with a single image, and let's say that it didn't survive long in the wild. A few cases were not considered:
- We only supported VerticalMode right after PassMode.
- It can happen that token need to be used but not consumed from the reference line.
With that fix, we are able to decode every single PDF file from the
1000-file zip "0000" (except 0000871.pdf, which uses byte alignment).
This is massive progress compared to the hundred of errors that we were
previously receiving.
---
The results were generated while using #23301, however the fix is independant.
Before (#23301):
```
Internal error while processing PDF file: Write of entire buffer ends past the memory area, in 14 files, on 113 pages, 200 times
0000/0000209.pdf 1 2 3 (2x) 4 …
```

LibGfx/CCITT: Reimplement PassMode in a less naive way

---

Userland/Applications/Assistant/Providers.cpp
Userland/Applications/Assistant/Providers.h
Userland/Applications/Assistant/main.cpp
Userland/Libraries/LibDesktop/AppFile.cpp
Userland/Libraries/LibDesktop/AppFile.h
Userland/Services/Taskbar/main.cpp

Allows commands that require escalation to be escalated from Assistant. One small command about something needing doing after PR #22560 is merged but this should still work as expected

Escalate from assistant

---

Userland/Utilities/useradd.cpp

This makes useradd follow the behavior of it's unix counterpart.

useradd: Don't error out on `-m` if directory already exists

---

Userland/Libraries/LibPDF/Parser.cpp

I said I'd look into unifying Filter::decode_ascii_hex() and Parser::parse_hex_string() at some point somewhere iirc. This is a small step towards that.

LibPDF: Minor, mostly-noop cleanups around hex conversion

---

Tests/LibWeb/Text/expected/IntersectionObserver/implicit-root-after-originating-iframe-is-removed-from-dom.txt
Tests/LibWeb/Text/input/IntersectionObserver/implicit-root-after-originating-iframe-is-removed-from-dom.html
Userland/Libraries/LibGfx/Size.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
Userland/Utilities/headless-browser.cpp

Making progress on making puter.com usable in Ladybird..
See individual commits for details :^)

LibWeb: Mixed improvements for puter.com

---

AK/ByteString.cpp
AK/ByteString.h
AK/DeprecatedFlyString.cpp
AK/DeprecatedFlyString.h
Userland/Libraries/LibC/netdb.cpp
Userland/Libraries/LibIPC/Decoder.cpp
Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp
Userland/Libraries/LibJS/Runtime/PropertyKey.h
Userland/Libraries/LibJS/Runtime/StringOrSymbol.h
Userland/Libraries/LibJS/SourceTextModule.cpp

Not sure how to comprehensively test all these libjs changes but I don't regress test262 and in-tree tests.

AK+Userland: Remove null state of DFS and raw usage of StringImpl

---

Kernel/FileSystem/Ext2FS/Inode.cpp
Kernel/FileSystem/InodeFile.cpp
Kernel/FileSystem/RAMFS/Inode.cpp
Userland/Utilities/tail.cpp

This is work towards #23097
CC: @ADKaster

Kernel+tail: Handle truncation in follow mode

---

Kernel/Net/NetworkTask.cpp

RFC9293 states that a closed socket should reply to all non-RST packets with an RST. This change implements this behaviour as specified in section 3.5.2 in bullet point 1.

Kernel/Net: Send RST packet when socket receives in closed state

---

Userland/Utilities/mktemp.cpp

Previously, using the `--tmpdir` option with a template containing a
path didn't work correctly, as the template path would be discarded.
Examples of the `--tmpdir`/`-p` option being used after this fix:

mktemp: Ensure `--tmpdir` and template paths are concatenated correctly 

---

Userland/Libraries/LibGfx/Color.h
Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
Userland/Libraries/LibWeb/Animations/AnimationEffect.h
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/Animations/TimingFunction.cpp
Userland/Libraries/LibWeb/Animations/TimingFunction.h
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h

This PR fixes all but one issue seen in the demo I posted in [this comment](https://github.com/SerenityOS/serenity/pull/23311#issuecomment-1961601978). Here is a new demo:
https://github.com/SerenityOS/serenity/assets/28801118/3ab9bb12-78d0-4bcf-9dff-ab1d45be1366

LibWeb: Fix most issues in web-animations.html demo

---

Userland/Libraries/LibELF/Image.cpp

These symbols describe the boundaries between code and data.
They will incorrectly show up in backtraces, if we don't ignore these symbols during symbolication, just like we already do on aarch64.

LibELF: Ignore mapping symbols when symbolicating RISC-V ELFs

---

Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
Userland/Applications/PDFViewer/PDFViewer.cpp
Userland/Libraries/LibGfx/Bitmap.cpp
Userland/Libraries/LibGfx/Bitmap.h
Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h
Userland/Utilities/pdf.cpp

pdf+MacPDF: Honor page rotation

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/Runtime/Completion.h
Userland/Libraries/LibJS/Runtime/Realm.h

Couple things while looking at https://cyxx.github.io/another_js/

LibJS: Small bag of optimizations for the bytecode interpreter

---

Userland/Libraries/LibGfx/AffineTransform.cpp
Userland/Libraries/LibGfx/AffineTransform.h
Userland/Libraries/LibWeb/CSS/Length.cpp
Userland/Libraries/LibWeb/CSS/Length.h
Userland/Libraries/LibWeb/CSS/PercentageOr.h
Userland/Libraries/LibWeb/Painting/InlinePaintable.h
Userland/Libraries/LibWeb/Painting/Paintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/SVGPaintable.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp

Knocking out a bunch of little profile items in the 1-3% range.
Individually they are not super impressive, but altogether it's a nice chunk :^)

LibWeb: Pile of small things found while profiling hover on ziglang.org

---

Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp

Skipping all stacking contexts with a size larger than 10000px in one dimension was a mistake because it also affects pages that are simply tall due to having a lot of content. Instead, we only need to skip if the stacking context requires the allocation of a framebuffer that could possibly fail.
Fixes https://github.com/SerenityOS/serenity/issues/23397

LibWeb: Skip large stacking context in gpu painter only if it allocates

---

Userland/Libraries/LibWeb/Painting/StackingContext.cpp

This allows us to avoid the need for costly traversals to gather boxes that have been saved during the construction of the stacking context tree.
No behavior change intended.

LibWeb: Use a precalculated list of positioned descendants for painting

---

Userland/Applications/Escalator/EscalatorWindow.cpp

Good for keyboard driven users :)

Escalator: Set focus to password input automatically

---

Userland/Libraries/LibGfx/CMYKBitmap.cpp

Fixes oss-fuzz issue 66629.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66629

LibGfx: Prevent overflow when creating CMYKBitmaps

---

Tests/LibWeb/Text/expected/WebAnimations/animation-properties/currentTime.txt
Tests/LibWeb/Text/expected/WebAnimations/animation-properties/effect.txt
Tests/LibWeb/Text/expected/WebAnimations/animation-properties/finished.txt
Tests/LibWeb/Text/expected/WebAnimations/animation-properties/timeline.txt
Tests/LibWeb/Text/input/WebAnimations/animation-properties/currentTime.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/effect.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/finished.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/timeline.html
Userland/Libraries/LibWeb/Animations/Animatable.cpp
Userland/Libraries/LibWeb/Animations/Animatable.h
Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/Animation.h
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
Userland/Libraries/LibWeb/DOM/Element.cpp

Turns out, tests are actually good for something! I've been a bit light on those, so I'm going to try to add a test for all of the properties/methods, since the algorithms are quite complex (but mostly because I'd like to stop causing regressions).

LibWeb: Add some Animation property tests, and fix a few bugs along the way

---

Ladybird/Qt/WebContentView.cpp

LibWeb: Allow CR inside of elements title attributes

---

AK/FlyString.cpp
AK/FlyString.h
AK/StringBase.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h
Userland/Libraries/LibWeb/DOM/Element.cpp

See individual commits for details :^)

LibWeb+AK: Some speedups for GitHub repo pages

---

Kernel/Net/TCPSocket.cpp
Kernel/Net/TCPSocket.h

RFC9293 states that from the TimeWait state the TCPSocket should wait the MSL (2mins chosen from the standard) for delayed segments to expire so that their sequence numbers do not clash with a new connection's sequence numbers using the same IP address and port number. The wait also ensures the remote TCP peer has received the ACK to their FIN segment.
This partly addresses issue #13684

Kernel/Net: Add TCPSocket timer for TimeWait moving to Closed

---

AK/HashMap.h
AK/HashTable.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h
Userland/Libraries/LibWeb/DOM/Attr.cpp
Userland/Libraries/LibWeb/DOM/Attr.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
Userland/Libraries/LibWeb/DOM/NamedNodeMap.h
Userland/Libraries/LibWeb/Dump.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Userland/Libraries/LibWeb/HTML/HTMLTitleElement.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Userland/Libraries/LibWeb/Layout/LineBuilder.h

Various things identified by profiling the loading & idle state of our main GitHub repo page.

LibWeb: More mixed GitHub performance improvements

---

Tests/LibWeb/Text/expected/wheel-events-consumed-by-scrollable-should-not-be-propagated-to-body-2.txt
Tests/LibWeb/Text/input/wheel-events-consumed-by-scrollable-should-not-be-propagated-to-body-2.html
Userland/Libraries/LibWeb/Page/EventHandler.cpp

Leftover from 90879a07ba6ab3cf61c52b3d601f1ed5052b807c

LibWeb: Skip page scrolling for wheel events consumed by scrollable box

---

Tests/LibWeb/Layout/expected/border-radius-invalid-corner-sampling-config.txt
Tests/LibWeb/Layout/input/border-radius-invalid-corner-sampling-config.html
Tests/LibWeb/Text/expected/SVG/svg-viewbox-zero-height.txt
Tests/LibWeb/Text/expected/overflow-with-zero-sized-box.txt
Tests/LibWeb/Text/input/SVG/svg-viewbox-zero-height.html
Tests/LibWeb/Text/input/overflow-with-zero-sized-box.html
Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

This PR consists of a few simple fixes for issues found by the Domato fuzzer.
See the individual commits for details.

LibWeb: Some fixes for issues found by Domato 

---

Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h

Another pile of little things found while sifting through profiles of browsing our GitHub repo.

LibWeb: More smol CSS optimizations for GitHub

---

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp

If a lossless webp has 3 or 4 colors, it uses 2 bits per pixel to store an offset into a "color index" (which the spec explicitly does not call palette since it says the 'color cache' is more like that). This way, it can pack 4 pixels into a single pixel.
If the width of the output image wasn't evenly divisble by 4, we used to write out-of-bounds in the last few columns of each row, since we used to always write all 4 pixels.
Found by clusterfuzz. Probably fixes
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66082
While here, spruce up the comments very slightly.

LibGfx/WebPLossless: Fix out-of-bounds write in color indexing transform

---

Tests/LibWeb/Text/expected/WebAnimations/misc/animating-unresolved-properties-crash.txt
Tests/LibWeb/Text/expected/css/animating-unresolved-properties-crash.txt
Tests/LibWeb/Text/input/WebAnimations/misc/animating-unresolved-properties-crash.html
Tests/LibWeb/Text/input/css/animating-unresolved-properties-crash.html
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h

LibWeb: Handle UnresolvedStyleValue in keyframe rules and effects

---

Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/Tab.cpp
Ladybird/cmake/ResourceFiles.cmake
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
Userland/Libraries/LibWeb/Page/EditEventHandler.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Page/EventHandler.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc

Text can be pasted by pressing Ctrl/Cmd+V or by using button in the context menu. For now only the Qt client is supported.

LibWeb+WebContent+Ladybird: Add ability to paste text from clipboard

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

See here:
https://github.com/SerenityOS/serenity/issues/22739#issuecomment-1890599116

LibGfx/JPEG: Add a comment to inverse_dct_8x8()

---

Tests/LibWeb/Layout/expected/css-degenerate-aspect-ratio.txt
Tests/LibWeb/Layout/input/css-degenerate-aspect-ratio.html
Tests/LibWeb/Text/expected/DOM/CDATASection-assignedSlot.txt
Tests/LibWeb/Text/expected/HTML/HTMLSelectElement-with-detached-option.txt
Tests/LibWeb/Text/expected/SVG/svg-circle-detached.txt
Tests/LibWeb/Text/input/DOM/CDATASection-assignedSlot.html
Tests/LibWeb/Text/input/HTML/HTMLSelectElement-with-detached-option.html
Tests/LibWeb/Text/input/SVG/svg-circle-detached.html
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/Layout/Box.cpp
Userland/Libraries/LibWeb/SVG/SVGCircleElement.cpp

This PR fixes issues found by Domato. These were the most common crashes I found. Of the 100 test files I generated, these issues affected 20 of them.

LibWeb: Fix more domato issues

---

Tests/LibCrypto/TestRSA.cpp
Userland/Libraries/LibCrypto/ASN1/DER.cpp
Userland/Libraries/LibCrypto/PK/PK.h

Fixes https://github.com/SerenityOS/serenity/issues/23657

LibCrypto: Add roundtrip test for RSA parsing

---

Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/AST/ASTPrinting.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/ReferenceResolvingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/SSABuildingPass.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Forward.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/CppASTConverter.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecificationClause.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecificationFunction.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecificationParsing.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/TextParser.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/TextParser.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Printer.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/Cell.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/Object.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/Object.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/ObjectType.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/ObjectType.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/Realm.cpp
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Runtime/Realm.h
Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
Tests/JSSpecCompiler/test-runner.cpp

"Remotely useful" == pretending to be IDL and generating headers.
~~First two commits are from #23545, thus draft.~~

JSSpecCompiler: Pave a way for doing something remotely useful

---

Tests/LibWeb/Text/expected/WebAnimations/misc/animation-single-iteration-no-repeat.txt
Tests/LibWeb/Text/input/WebAnimations/misc/animation-single-iteration-no-repeat.html
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

LibWeb: Fix StyleComputer calling Animation::play() too often

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/Dump.cpp
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Userland/Libraries/LibWeb/HTML/Navigation.cpp
Userland/Libraries/LibWeb/HTML/NavigationHistoryEntry.cpp
Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.cpp
Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.h
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp

Refactoring. No behaviour change intended.

LibWeb: Transform SessionHistoryEntry from a struct to a class

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Userland/Libraries/LibWeb/DOM/DocumentLoading.h
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/HTML/HistoryHandlingBehavior.h
Userland/Libraries/LibWeb/HTML/Location.cpp
Userland/Libraries/LibWeb/HTML/Location.h
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/Navigable.h
Userland/Libraries/LibWeb/HTML/Navigation.cpp
Userland/Libraries/LibWeb/HTML/Navigation.h
Userland/Libraries/LibWeb/HTML/NavigationParams.h
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.h

Some changes from https://github.com/SerenityOS/serenity/pull/23009 that should be safe to merge without breaking anything.

LibWeb: Progress towards bringing navigables up to date with the latest spec

---

Tests/LibWeb/Layout/expected/css-transition-none.txt
Tests/LibWeb/Layout/input/css-transition-none.html
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

Fixes a crash when loading https://soundcloud.com/

LibWeb: Don't fall apart on `transition: none` in CSS

---

Userland/Libraries/LibXML/Parser/Parser.cpp

This prevented loading SVGs such as:
https://mdn.github.io/learning-area/html/multimedia-and-embedding/mdn-splash-page-finished/mdn.svg
Where the DTD is not in the hardcoded unified DTD in LibWeb. It also prevented loading any SVG with a broken link for a DTD, which other browsers just seem to ignore.

LibXML: Don't emit a parser error for failing to resolve DTD URI

---

Tests/LibWeb/Text/expected/WebAnimations/animation-effect/get-computed-timing.txt
Tests/LibWeb/Text/expected/WebAnimations/animation-effect/get-timing.txt
Tests/LibWeb/Text/expected/WebAnimations/animation-effect/update-timing.txt
Tests/LibWeb/Text/expected/WebAnimations/animation-properties/currentTime.txt
Tests/LibWeb/Text/input/WebAnimations/animation-effect/get-computed-timing.html
Tests/LibWeb/Text/input/WebAnimations/animation-effect/get-timing.html
Tests/LibWeb/Text/input/WebAnimations/animation-effect/update-timing.html
Tests/LibWeb/Text/input/WebAnimations/animation-methods/cancel.html
Tests/LibWeb/Text/input/WebAnimations/animation-methods/finish.html
Tests/LibWeb/Text/input/WebAnimations/animation-methods/pause.html
Tests/LibWeb/Text/input/WebAnimations/animation-methods/persist.html
Tests/LibWeb/Text/input/WebAnimations/animation-methods/reverse.html
Tests/LibWeb/Text/input/WebAnimations/animation-methods/updatePlaybackRate.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/currentTime.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/finished.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/pending-and-ready.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/replaceState.html
Tests/LibWeb/Text/input/WebAnimations/animation-properties/startTime.html
Tests/LibWeb/Text/input/WebAnimations/misc/animation-single-iteration-no-repeat.html
Tests/LibWeb/Text/input/include.js
Tests/LibWeb/Text/input/request-animation-frame-order.html
Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp

Also adds some nice testing utilities and removes a few `FIXME`s

LibWeb: Add AnimationEffect tests

---

Tests/LibWeb/Text/expected/HTML/cross-origin-window-properties.txt
Tests/LibWeb/Text/expected/WebAnimations/misc/animate-no-window.txt
Tests/LibWeb/Text/expected/Worker/Worker-performance.txt
Tests/LibWeb/Text/input/HTML/cross-origin-window-properties.html
Tests/LibWeb/Text/input/WebAnimations/misc/animate-no-window.html
Tests/LibWeb/Text/input/Worker/Worker-performance.html
Tests/LibWeb/Text/input/Worker/worker-performance.js
Userland/Libraries/LibWeb/Animations/DocumentTimeline.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/HTML/Window.idl
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.idl
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
Userland/Libraries/LibWeb/HighResolutionTime/Performance.cpp
Userland/Libraries/LibWeb/HighResolutionTime/Performance.h
Userland/Libraries/LibWeb/NavigationTiming/PerformanceTiming.cpp
Userland/Libraries/LibWeb/NavigationTiming/PerformanceTiming.h

This PR fixes issues found by Domato.

LibWeb: More fixes for crashes found by Domato

---

Userland/Libraries/LibCore/DateTime.cpp
Userland/Libraries/LibCore/DateTime.h
Userland/Libraries/LibCore/Resource.cpp
Userland/Libraries/LibCore/Resource.h
Userland/Libraries/LibCore/ResourceImplementation.cpp
Userland/Libraries/LibCore/ResourceImplementation.h
Userland/Libraries/LibCore/ResourceImplementationFile.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Document.idl
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp

Further work towards: https://github.com/SerenityOS/serenity/issues/23632
Need to figure out a good way to add tests for this (perhaps somewhere in a test harness can set mtime on a file?)

LibWeb: Add support for document.lastModified

---

Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/JobCallback.cpp
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
Userland/Libraries/LibWeb/ResizeObserver/ResizeObservation.cpp
Userland/Libraries/LibWeb/ResizeObserver/ResizeObserverEntry.cpp

LibJS+LibWeb: Add missing visits found by LibJSGCVerifier

---

Userland/Libraries/LibJS/Runtime/PromisePrototype.cpp
Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/PendingResponse.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/PendingResponse.h
Userland/Libraries/LibWeb/FileAPI/Blob.cpp
Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Userland/Libraries/LibWeb/WebIDL/Promise.cpp
Userland/Libraries/LibWeb/WebIDL/Promise.h

Fixing more JS realm leaks that popped up while running our test suite.

LibJS+LibWeb: Mixed bag of GC leak fixes

---

Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
Userland/Applications/Browser/main.cpp
Userland/Libraries/LibWebView/CMakeLists.txt
Userland/Libraries/LibWebView/Platform/ProcessInfo.h
Userland/Libraries/LibWebView/Platform/ProcessStatistics.h
Userland/Libraries/LibWebView/Platform/ProcessStatisticsNoop.cpp
Userland/Libraries/LibWebView/Platform/ProcessStatisticsSerenity.cpp
Userland/Libraries/LibWebView/ProcessManager.cpp
Userland/Libraries/LibWebView/ProcessManager.h

Loosely based on SystemMonitor's ProcessModel code.

LibWebView+Browser: Collect memory and cpu usage for helpers on Serenity

---

Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-sign.txt
Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-verify.txt
Tests/LibWeb/Text/input/Crypto/SubtleCrypto-sign.html
Tests/LibWeb/Text/input/Crypto/SubtleCrypto-verify.html
Userland/Libraries/LibCrypto/Curves/SECPxxxr1.h
Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.h
Userland/Libraries/LibWeb/Crypto/KeyAlgorithms.cpp
Userland/Libraries/LibWeb/Crypto/KeyAlgorithms.h
Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Userland/Libraries/LibWeb/Crypto/SubtleCrypto.h
Userland/Libraries/LibWeb/Crypto/SubtleCrypto.idl

Part 1 of X
Next part: [deriveKey](https://github.com/stelar7/serenity/tree/subtlecrypto-derive-key)

LibWeb: Some work on SubtleCrypto (sign/verify)

---

Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
Userland/Libraries/LibWebView/CMakeLists.txt
Userland/Libraries/LibWebView/Platform/ProcessStatisticsLinux.cpp

LibWebView: Collect memory and cpu usage for helpers on Linux

---

Userland/Libraries/LibPDF/Renderer.cpp

Fixes #23824, a regression from the first commit in #23781.

LibPDF: Invert image masks used as alpha too

---

Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp

See commit description for details.

LibWeb: A couple navigation fixes

---

Tests/LibWeb/Text/expected/navigation/history-replace-push-state-race-2.txt
Tests/LibWeb/Text/input/navigation/history-replace-push-state-race-2.html
Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Userland/Libraries/LibWeb/HTML/NavigableContainer.h
Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.h
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.h

See commit descriptions for details.

LibWeb: Get rid of hack to force session history traversal queue processing

---

Meta/Lagom/Tools/LibJSGCVerifier/CMakeLists.txt
Meta/Lagom/Tools/LibJSGCVerifier/README.md
Meta/Lagom/Tools/LibJSGCVerifier/src/main.py

LibJSGCVerifier: Support building & running with the Lagom build

---

Userland/Libraries/LibCrypto/ASN1/DER.cpp
Userland/Libraries/LibCrypto/PK/PK.h
Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp

Work towards https://github.com/SerenityOS/serenity/issues/23484

LibWeb: Improve RSAOAEP.exportKey with spki and pkcs8

---

Base/usr/share/man/man1/tail.md
Userland/Utilities/tail.cpp

This PR implements a mode to `tail` that works on bytes instead of lines.
It also contains a bonus commit that fixes some edge cases in our line based implementation.

tail: Support byte mode (+1 bugfix)

---

Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Libraries/LibWeb/HTML/NavigatorConcurrentHardware.h

Further work towards: https://github.com/SerenityOS/serenity/issues/23632

LibWeb: Fill out implementation for navigator.hardwareConcurrency

---

Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp

LibWeb: Fix out of order spec step numbers in "create child navigable"

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp

Fixes oss-fuzz 66587.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66587&sort=-opened&q=proj%3Aserenity%20TIFF&can=1

LibGfx/TIFF: Prevent recursion when following IFD pointers

---

Ports/gpgme/package.sh
Ports/poppler/package.sh

This PR improves our `poppler` port by including a lot more of its optional dependencies.
Followup of #23289

Ports: Improve poppler

---

Userland/Applications/GamesSettings/CardSettingsWidget.cpp
Userland/Applications/GamesSettings/ChessSettingsWidget.cpp
Userland/Applications/MouseSettings/ThemeWidget.cpp
Userland/Applications/MouseSettings/ThemeWidget.h
Userland/Applications/NetworkSettings/NetworkSettingsWidget.cpp
Userland/Libraries/LibGUI/ComboBox.cpp

LibGUI: Call on_change when set_text is called on ComboBox

---

Tests/LibWeb/Text/expected/navigation/run-script-from-about-blank-iframe.txt
Tests/LibWeb/Text/input/navigation/run-script-from-about-blank-iframe.html
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp

Fixes https://github.com/SerenityOS/serenity/issues/23836
See for details https://github.com/whatwg/html/issues/10261

LibWeb: Allow executing scripts for iframes with src=about:blank

---

AK/Function.h
Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.cpp
Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.h
Userland/Applications/Assistant/main.cpp
Userland/DevTools/HackStudio/Project.h
Userland/DevTools/HackStudio/ProjectBuilder.h
Userland/DevTools/HackStudio/ProjectDeclarations.cpp
Userland/Libraries/LibGUI/Model.h
Userland/Libraries/LibGfx/Font/FontDatabase.h
Userland/Libraries/LibJS/Runtime/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/Completion.cpp
Userland/Libraries/LibJS/Runtime/Object.h
Userland/Libraries/LibJS/Runtime/Realm.h
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibTest/Randomized/RandomnessSource.h
Userland/Libraries/LibWeb/Bindings/MainThreadVM.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.h
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.h
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Platform/EventLoopPlugin.h

LibJSGCVerifier: Warn when capturing a stack-allocated value by reference

---

Userland/Libraries/LibWebView/ProcessManager.cpp

Suggested-By: Timothy Flynn <trflynn89@pm.me>

LibWebView: Respect dark mode/light mode TaskManager windows

---

Tests/LibWeb/Text/expected/HTML/outerHTML.txt
Tests/LibWeb/Text/input/HTML/outerHTML.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h

This makes (among many other things) image carousels work on https://utah.edu/
Before:
After:

LibWeb: Implement Element.outerHTML

---

Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.cpp
Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.h
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.h

- Add missing visit of a navigable in SHTQ entry
- Use HeapFunction instead of SafeFunction for entry callback

LibWeb: Make SessionHistoryTraversalQueue GC-allocated

---

Userland/Libraries/LibWeb/Page/Page.cpp

LibWeb: Add a workaround for excessive memory usage in Page::load_html

---

Meta/gn/secondary/Userland/Libraries/LibGL/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
Tests/LibWeb/Layout/expected/html-dimensions.txt
Tests/LibWeb/Layout/input/html-dimensions.html
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.h
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h

LibWeb: Support dimension attributes on HTMLVideoElement

---

Tests/LibWeb/Text/expected/DOM/Element-removeAttributeNode.txt
Tests/LibWeb/Text/input/DOM/Element-removeAttributeNode.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl
Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
Userland/Libraries/LibWeb/DOM/NamedNodeMap.h
Userland/Libraries/LibWeb/HTML/AttributeNames.h
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLElement.h
Userland/Libraries/LibWeb/HTML/HTMLElement.idl
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl

Bunch of quick fixes to at the very least log a FIXME when some common unimplemented APIs are used.

LibWeb: Stub out a bunch of stuff and implement some trivial APIs

---

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp

Read through this code today, and noticed these two small things.

LibGfx/WebP: Two tiny cleanups

---

Tests/LibWeb/Text/expected/object-with-unsupported-type-in-data-attribute.txt
Tests/LibWeb/Text/input/object-with-unsupported-type-in-data-attribute.html
Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Userland/Libraries/LibWeb/DOM/DocumentLoading.h
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp

Progress on fixing regressed Acid2.

LibWeb: Run <object> fallback steps if data type is not supported

---

Kernel/Arch/riscv64/Interrupts.cpp

This otherwise caused a race condition between the signal dispatcher (which sets sepc to the signal trampoline) and sepc being updated in the trap handler.
We obviously have to keep the sepc set by the signal dispatcher and not increment it afterwards.

Kernel/riscv64: Increment sepc before re-enabling interrupts

---

Base/usr/share/man/man1/Applications/Screenshot.md

Base: Add manpage for Screenshot

---

.github/workflows/cmake.yml

https://github.blog/changelog/2024-04-02-github-actions-hardware-accelerated-android-virtualization-now-available/

CI: Enable KVM on Github Actions runners

---

Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Userland/Libraries/LibWeb/Clipboard/Clipboard.cpp
Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Range.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/Task.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/Task.h
Userland/Libraries/LibWeb/FileAPI/Blob.cpp
Userland/Libraries/LibWeb/FileAPI/FileReader.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Userland/Libraries/LibWeb/HTML/Navigation.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp

Didn't notice these when porting `queue_a_microtask()`.

LibWeb: Port queue_global_task() and queue_fetch_task() to take a JS::HeapFunction

---

AK/BufferedStream.h
Tests/AK/TestMemoryStream.cpp

These changes allow lines of arbitrary length to be read with
BufferedStream. When the user supplied buffer is smaller than
the line, it will be resized to fit the line. When the internal
buffer in BufferedStream is smaller than the line, it will be
read into the user supplied buffer chunk by chunk with the
buffer growing accordingly.
Other behaviors match the behavior of the existing read_line method.

 AK: Add methods to BufferedStream to resize the user supplied buffer

---

Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp

This just reuses the layout to compute the bounding box rather than implementing the full bounding box algorithm, which is likely the slower option, but also much simpler to implement.
This is enough to fix the faces on https://zengm.com/facesjs/.
**Before:**
**After:**

LibWeb: Add an initial implementation of the SVG `.getBBox()` method

---

Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateDateTimeFormatData.cpp
Userland/Libraries/LibUnicode/String.cpp
Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
Userland/Libraries/LibWeb/CSS/StyleSheetList.h
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp

Bunch of string stuff, and also not sorting StyleSheetList for no reason on removal.

LibWeb+LibUnicode+LibLocale: Back again with another pile of small GitHub speedups

---

Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h

Half this PR has been sitting on my PC, forgotten, since December. :sweat_smile: So enjoy.
It's an ongoing refactor, with a fair bit left to do, but will make the CSS parsing logic a lot more consistent and hopefully less error-prone to write.

LibWeb: Parse more CSS things using TokenStreams

---

Userland/Libraries/LibELF/DynamicLoader.cpp

Weak symbols can be left unresolved, and code is supposed to check if they're null at runtime before using them. Handle them appropriately instead of refusing to load.
Together with #24072 we now succesfully boot to a graphical desktop on RISC-V :slightly_smiling_face:

DynamicLoader: Resolve missing weak absolute symbols to null

---

Kernel/Arch/riscv64/PCI/Initializer.cpp
Kernel/Bus/PCI/Access.cpp
Kernel/Bus/PCI/Access.h
Kernel/Bus/PCI/Controller/HostController.cpp
Kernel/Bus/PCI/Controller/HostController.h
Kernel/Bus/PCI/Definitions.h
Kernel/Devices/Storage/NVMe/NVMeController.cpp
Kernel/Devices/Storage/NVMe/NVMeController.h
Kernel/Devices/Storage/NVMe/NVMeDefinitions.h
Meta/debug-kernel.sh
Meta/run.py

Instead of immediately crashing due to a missing graphics card (due to broken PCI), we now boot succesfully to the desktop.

Kernel: A bunch of PCI (& other random) fixes to get us further in the RISC-V boot

---

Userland/Libraries/LibWeb/HTML/AudioTrack.cpp
Userland/Libraries/LibWeb/HTML/AudioTrackList.cpp
Userland/Libraries/LibWeb/HTML/AudioTrackList.h
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
Userland/Libraries/LibWeb/HTML/VideoTrack.cpp
Userland/Libraries/LibWeb/HTML/VideoTrackList.cpp
Userland/Libraries/LibWeb/HTML/VideoTrackList.h

Ref #20449
Ref https://github.com/SerenityOS/serenity/pull/23936#discussion_r1565572350

LibWeb: Remove OOM error propagation from HTMLMediaElement (and friends)

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Text.h
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/HTML/Focus.cpp
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/Navigable.h
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
Userland/Libraries/LibWeb/Page/EditEventHandler.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Page/EventHandler.h
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWeb/Painting/LabelablePaintable.cpp
Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/TextPaintable.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp

Move some stuff around and realign various things with the spec.

LibWeb: Fix a bunch of BrowsingContext and Navigable FIXMEs

---

Tests/LibWeb/Ref/reference/svg-foreign-object-mask-ref.html
Tests/LibWeb/Ref/svg-foreign-object-mask.html
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
Userland/Libraries/LibWeb/Layout/Node.h
Userland/Libraries/LibWeb/Layout/SVGForeignObjectBox.cpp
Userland/Libraries/LibWeb/Layout/SVGForeignObjectBox.h
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/SVGMaskBox.h
Userland/Libraries/LibWeb/Painting/SVGForeignObjectPaintable.cpp
Userland/Libraries/LibWeb/Painting/SVGForeignObjectPaintable.h
Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.cpp
Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.h
Userland/Libraries/LibWeb/Painting/SVGMaskable.cpp
Userland/Libraries/LibWeb/Painting/SVGMaskable.h
Userland/Libraries/LibWeb/SVG/SVGForeignObjectElement.cpp

LibWeb: Add mask support for SVGForeignObjectElement 

---

Base/res/apps/Browser.af
Userland/Applications/Browser/main.cpp
Userland/Applications/FileManager/DirectoryView.cpp
Userland/Libraries/LibDesktop/AppFile.cpp
Userland/Libraries/LibDesktop/AppFile.h
Userland/Libraries/LibDesktop/Launcher.cpp
Userland/Libraries/LibDesktop/Launcher.h
Userland/Services/LaunchServer/Launcher.cpp
Userland/Services/LaunchServer/Launcher.h
Userland/Services/Taskbar/QuickLaunchWidget.cpp
Userland/Services/Taskbar/TaskbarWindow.cpp

Plus some AppFile-related changes to make it work more nicely with e.g. the quick launch icon, so that a new window is  requested (once new windows actually work).
https://github.com/SerenityOS/serenity/assets/5600524/ee474625-766b-4e47-95b5-19f3df3ca48e

Browser: Add support for a singleton chrome process

---

Userland/Libraries/LibCore/Socket.cpp

This can cause issues with older versions of glibc warning when not initializing the flexible array member for CMSG_DATA. Such as glibc shipped with Ubuntu 20.04.
Fixes oss-fuzz build_fuzzers and check_build with the latest gcr.io/oss-fuzz-base/base-builder tag. Well. except for FuzzCSSParser, but we know that one is broken.
Unblocks https://github.com/google/oss-fuzz/pull/11874

LibCore: Don't use designated initializers for struct cmsghdr

---

Tests/LibWeb/Text/expected/XHR/XMLHttpRequest-responseURL.txt
Tests/LibWeb/Text/input/XHR/XMLHttpRequest-responseURL.html
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.idl

This was used on https://twinings.co.uk/ so let's support it :^)

LibWeb: Implement XMLHttpRequest.responseURL

---

Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp

LibGfx/WebP: Rename two variables to be a bit clearer

---

Userland/Libraries/LibGUI/DynamicWidgetContainerControls.gml

I hope you can contain your excitement!

LibGUI: Add tooltips to DynamicWidgetContainer control buttons

---

Userland/Libraries/LibWeb/Painting/SVGMaskable.cpp

This makes sure `get_mask_type_of_svg()` finds the mask or clipPath by looking at its child layout nodes. Previously, it went via the DOM node of the mask or clipPath, which is not always correct as there is not a 1-to-1 mapping from mask DOM node to SVGMaskBox (or SVGClipBox).
Fixes #24186

LibWeb: Fix null layout node dereference in SVGMaskable

---

Documentation/AndroidStudioConfiguration.md
Ladybird/Android/build.gradle.kts
Ladybird/Android/gradle/wrapper/gradle-wrapper.properties
Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.cpp
Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.h
Ladybird/Android/src/main/cpp/ImageDecoderService.cpp
Ladybird/Android/src/main/cpp/LadybirdActivity.cpp
Ladybird/Android/src/main/cpp/LadybirdServiceBase.h
Ladybird/Android/src/main/cpp/LadybirdServiceBaseJNI.cpp
Ladybird/Android/src/main/cpp/RequestServerService.cpp
Ladybird/Android/src/main/cpp/TimerExecutorService.cpp
Ladybird/Android/src/main/cpp/WebContentService.cpp
Ladybird/Android/src/main/cpp/WebContentService.h
Ladybird/Android/src/main/cpp/WebContentServiceJNI.cpp
Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
Ladybird/Android/src/main/cpp/WebViewImplementationNative.h
Ladybird/Android/src/main/cpp/WebViewImplementationNativeJNI.cpp
Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdServiceBase.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdServiceConnection.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/TimerExecutorService.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/WebContentService.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/WebView.kt
Ladybird/Android/src/main/java/org/serenityos/ladybird/WebViewImplementation.kt
Ladybird/ImageDecoder/CMakeLists.txt
Meta/Azure/Lagom.yml

Also update to the latest gradle plugin versions and other dependencies as recommended by Android Studio Jellyfish.

Ladybird: Update Android build to work with current LibWebView/LibCore

---

Userland/Games/Chess/ChessWidget.cpp
Userland/Games/Chess/ChessWidget.h
Userland/Games/Chess/main.cpp

This commit replaces the `import_pgn` implementation with a more resiliant parser to handle various edge cases and give helpful error messages instead of crashing.

Chess: Improve PGN importing

---

Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp

Most of this code (VP8X chunk writing) will be used for writing animated webp files too.

LibGfx/WebPWriter: Implement ICC color profile data writing

---

Tests/LibGfx/TestImageWriter.cpp

They all pass, but maybe they'll help someone in the future.

TestImageWriter: Add tests for most other image writers

---

Base/res/ladybird/newtab.html

https://github.com/SerenityOS/serenity/assets/168300808/d8ee9f59-ebb0-4918-b433-60f07ab0a410

Ladybird: Add Wikipedia search button to newtab.html

---

Userland/Libraries/LibWeb/SVG/SVGTransform.cpp
Userland/Libraries/LibWeb/SVG/SVGTransform.h
Userland/Libraries/LibWeb/SVG/SVGTransform.idl

LibWeb/SVG: Stub SVGTransform functions

---

Base/usr/share/man/man8/ping.md
Userland/Utilities/ping.cpp

Add support for adaptive ping, flood ping and waittime.

Utilities: Add support for various ping flags

---

Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp

See commits' description for details.

LibGfx/GIF: Bag of small tweaks

---

Userland/Libraries/LibJS/Runtime/ProxyObject.cpp

Instead of relying on native stack overflows to kick us out of circular proxy chains, we now keep track of the recursion depth and kick ourselves out if it exceeds 10'000.
This fixes an issue where compiler tail/sibling call optimizations would turn infinite recursion into infinite loops, and thus never hit a stack overflow to kick itself out.
For whatever reason, we've only seen the issue on SerenityOS with UBSAN, but it could theoretically happen on any platform.

LibJS: Manually limit the recursion depth in Proxy

---

Userland/Libraries/LibWebView/SearchEngine.cpp

LibWebView: Add Wikipedia to builtin search engines list

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
Userland/Libraries/LibJS/Runtime/Environment.cpp
Userland/Libraries/LibJS/Runtime/Environment.h

Two quick and obvious optimizations that make the "Clusters" demo at https://ventrella.com/Clusters/ a bit more bearable.
It's still really bad though :sweat_smile:

LibJS: Two optimizations for "Clusters" web demo

---

Tests/LibWeb/Text/expected/DOM/Element-toggleAttribute-xml-doc-html-ns.txt
Tests/LibWeb/Text/input/DOM/Element-toggleAttribute-xml-doc-html-ns.html
Userland/Libraries/LibWeb/DOM/Document.idl
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.idl
Userland/Libraries/LibWeb/DOM/ParentNode.cpp
Userland/Libraries/LibWeb/DOM/ParentNode.h
Userland/Libraries/LibWeb/DOM/Range.h
Userland/Libraries/LibWeb/HTML/HTMLAllCollection.h

Resolve four very trivial fixmes that each didn't really seem like they needed an individual PR. Descriptions per commit.

LibWeb: Resolve four minor FIXMEs

---

Tests/LibWeb/Text/expected/UIEvents/WheelEvent-construction.txt
Tests/LibWeb/Text/input/UIEvents/WheelEvent-construction.html
Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
Userland/Libraries/LibWeb/UIEvents/WheelEvent.h
Userland/Libraries/LibWeb/UIEvents/WheelEvent.idl

This makes https://profiler.firefox.com/ progress much further in
loading :^)

LibWeb: Add constructor for WheelEvent, and a boog fix

---

Tests/LibWeb/Text/expected/WebAudio/AudioBuffer-copyFromChannel.txt
Tests/LibWeb/Text/input/WebAudio/AudioBuffer-copyFromChannel.html
Userland/Libraries/LibWeb/WebAudio/AudioBuffer.cpp

Progress towards: https://github.com/SerenityOS/serenity/issues/23632

LibWeb: Implement AudioBuffer.copyFromChannel

---

Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp

A handful of things to improve performance further on Another World JS (at https://cyxx.github.io/another_js/)
We're already doing pretty well with all the recent improvements, but there were still some generally useful improvements :)

LibJS+LibWeb: Some optimizations for Another World JS

---

Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
Userland/Libraries/LibWeb/HTML/HTMLAreaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h
Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h

LibWeb: Return NonnullGCPtr<DOMTokenList> from `relList` getters

---

Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/Tests/try-return-finally.js

LibJS: Prepare yield object before re-routing it through finally

---

Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
Userland/Libraries/LibWeb/HTML/HTMLAreaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h
Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp

Courtesy of the clang plugins :smile:

LibWeb: Add a few missing visits to m_rel_list members

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/css/FontFaceSet-setlike.txt
Tests/LibWeb/Text/input/css/FontFaceSet-setlike.html
Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibIDL/IDLParser.h
Userland/Libraries/LibIDL/Types.h
Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
Userland/Libraries/LibWeb/CSS/FontFaceSet.h
Userland/Libraries/LibWeb/CSS/FontFaceSet.idl

This required some IDLGenerators wrangling and a lot of spec interpreting.

LibWeb: Mark FontFaceSet as a setlike IDL interface 

---

Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp

See commits description for details.

LibWeb: Couple of small painting optimizations

---

Userland/Libraries/LibWasm/Parser/Parser.cpp

The WebAssembly spec never relies on host system information, like size_t. For consistency's sake, we should stick to the usage of u32's instead of size_t's. This didn't cause issues before because LEB128-encoded u64's are a superset of LEB128-encoded u32's.
There's also a usage of ssize_t in the parser, but I didn't want to change that yet. It's only used when reading blocktypes, but I didn't want to touch it yet because the [encoding of blocktypes](https://webassembly.github.io/spec/core/binary/instructions.html#binary-blocktype) is a huge headache in the specification. Let me know if I should change it to an i32. I think it should actually be an i33 (or s33 in spec terms), but I think that's worth a separate discussion.

LibWasm: Use u32's instead of size_t's when reading LEB128 numbers

---

Tests/LibWeb/Text/expected/css/animating-transform-with-calc-crash.txt
Tests/LibWeb/Text/input/css/animating-transform-with-calc-crash.html
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

LibWeb: Use LengthPercentage for calc values in Transformation matrix

---

Tests/LibWeb/Text/expected/HTML/form-element-enctype.txt
Tests/LibWeb/Text/input/HTML/form-element-enctype.html
Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl

These were seen getting called on netflix.com

LibWeb: Implement HTMLFormElement.enctype & encoding

---

Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/WebAudio/AudioBuffer.cpp
Userland/Libraries/LibWeb/WebAudio/AudioBuffer.h
Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.idl

This is a simple factory function which effectively just calls the AudioBuffer constructor.

LibWeb: Implement BaseAudioContext.createBuffer

---

Userland/Libraries/LibGfx/Color.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebWorker/PageHost.cpp

Draft until @nico fixes the WebP test.

LibGfx: Make Color::NamedColor be an enum class 

---

Tests/LibWeb/Text/expected/DOM/HTMLCollection-empty-string-as-property-name.txt
Tests/LibWeb/Text/expected/HTML/Element-insertAdjacentHTML-documentElement.txt
Tests/LibWeb/Text/input/DOM/HTMLCollection-empty-string-as-property-name.html
Tests/LibWeb/Text/input/HTML/Element-insertAdjacentHTML-documentElement.html
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp

Fixes for:
- wpt/dom/collections/HTMLCollection-empty-name.html
- wpt/domparsing/insert_adjacent_html.html

LibWeb: Two random WPT fixes

---

Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebContentView.h
Userland/Libraries/LibWeb/CSS/Screen.cpp
Userland/Libraries/LibWeb/CSS/Screen.h
Userland/Libraries/LibWeb/CSS/Screen.idl

Ticks off three more boxes towards https://github.com/SerenityOS/serenity/issues/23632

LibWeb: Stub out Window-Management proposal extensions to Screen API

---

Tests/LibGfx/TestImageWriter.cpp
Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.h

…and a tiny tiny performance improvement.

LibGfx/WebP: Minor tweaks around setting "is alpha used" hint bit in VP8L headers

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/WebAnimations/animation-properties/timeline.txt
Tests/LibWeb/Text/expected/WebAnimations/misc/invalid-values.txt
Tests/LibWeb/Text/expected/geometry/domrect-create.txt
Tests/LibWeb/Text/input/WebAnimations/animation-properties/timeline.html
Tests/LibWeb/Text/input/WebAnimations/misc/invalid-values.html
Tests/LibWeb/Text/input/geometry/domrect-create.html
Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibIDL/Types.h
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibWeb/Animations/Animatable.cpp
Userland/Libraries/LibWeb/Animations/Animatable.h
Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/Animations/KeyframeEffect.h

These changes should fix most of the issues listed in https://wpt.stelar7.no/wpt/web-animations/interfaces/Animatable/animate.html

LibWeb: Misc animation fixes + unrestricted floating point types in IDLGenerator

---

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/Navigation.cpp
Userland/Libraries/LibWeb/HTML/Navigation.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/WebDriver/Client.cpp
Userland/Libraries/LibWeb/WebDriver/Client.h
Userland/Services/WebContent/WebDriverClient.ipc
Userland/Services/WebContent/WebDriverConnection.cpp
Userland/Services/WebContent/WebDriverConnection.h
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.h

Follow-up to #24437
cc @jamierocks

LibWeb: Implement consume user activation AO

---

Meta/gn/secondary/Ladybird/BUILD.gn
Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/Painting/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/WebAudio/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni

* We no longer need QtSvg
* We don't need QtMultimedia if we have pulse audio

Meta: Some GN fixes for Linux on a fresh system

---

Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Utilities/CMakeLists.txt
Userland/Utilities/shred.cpp

Initial implementation of shred. Missing things:
* `--force`, change permissions to allow writing if necessary,
* `--size=N`, shred this many bytes,
* `--zero`, add a final overwrite with zeros to hide shredding.

Utilities: Add shred utility

---

Base/usr/share/man/man1/shred.md

cc @AtkinsSJ 
Related to #23700.

Base: Add a manual page for the shred utility

---

Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp

The ThreadData still has a lifetime a longer than the thread it was created for, but at least now it's not leaked at process exit.
This fixes the GCC ASAN CI test leaks

LibCore: Don't leak EventLoopImplementationUnix's ThreadData

---

AK/String.h
Ladybird/AppKit/UI/LadybirdWebView.h
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/AppKit/UI/SearchPanel.mm
Ladybird/Qt/FindInPageWidget.cpp
Ladybird/Qt/FindInPageWidget.h
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Tests/AK/TestString.cpp
Userland/Libraries/LibUnicode/CharacterTypes.cpp
Userland/Libraries/LibUnicode/CharacterTypes.h
Userland/Libraries/LibUnicode/String.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc

We now search with case-insensitivity by default, and add checkboxes to enable case-sensitivity
https://github.com/SerenityOS/serenity/assets/5600524/a55aba89-4415-41ea-9735-7a0a75776337

Ladybird+LibWeb: Support (and default to) case-insensitive find-in-page

---

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp

The spec and implementation's comments had diverged a little, this brings them in line :)

LibWeb/Fetch: Update "HTTP fetch" algorithm to latest spec comments

---

Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/MixedContent/BUILD.gn
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp
Userland/Libraries/LibWeb/MixedContent/AbstractOperations.h

See https://w3c.github.io/webappsec-mixed-content/.

LibWeb: Implement Mixed Content spec :)

---

Tests/LibWeb/TestConfig.ini

Issue: https://github.com/LadybirdWebBrowser/ladybird/issues/100 (cherry picked from commit LadybirdBrowser/ladybird@533eea1958032c)
---
Timed out e.g. here: https://github.com/SerenityOS/serenity/actions/runs/9438153528/job/25994851987?pr=24553

Tests: Skip Text/input/HTML/form-image-submission.html (flaky)

---

Meta/CMake/wasm_spec_tests.cmake
Meta/generate-libwasm-spec-test.py
Tests/LibWasm/test-wasm.cpp
Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
Userland/Libraries/LibWasm/AbstractMachine/Validator.h
Userland/Libraries/LibWasm/Parser/Parser.cpp
Userland/Libraries/LibWasm/Types.h

LibWasm: Sync with ladybird

---

Userland/Utilities/pkg/AvailablePort.h
Userland/Utilities/pkg/AvailablePortDatabase.cpp
Userland/Utilities/pkg/AvailablePortDatabase.h
Userland/Utilities/pkg/CMakeLists.txt
Userland/Utilities/pkg/InstalledPort.cpp
Userland/Utilities/pkg/InstalledPort.h
Userland/Utilities/pkg/InstalledPortDatabase.cpp
Userland/Utilities/pkg/InstalledPortDatabase.h
Userland/Utilities/pkg/main.cpp

This PR is handing some basic changes so I could continue working on the package management system I try to bring-up.
Actual progress is done in out-of-tree branch, if someone is interested in viewing what I try to do:
https://github.com/supercomputer7/serenity/tree/build-essential-port

Utilities/pkg: Change handling of files, before implementing packages (part 1/N)

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Executable.h
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Tests/async-this-value.js

Cherry-picks commits from:
* https://github.com/LadybirdBrowser/ladybird/pull/222
* https://github.com/LadybirdBrowser/ladybird/pull/165

LibJS: Cherry-pick upstream correctness fix and performance patches

---

Userland/Libraries/LibWeb/CSS/MediaQuery.cpp
Userland/Libraries/LibWeb/CSS/MediaQuery.h
Userland/Libraries/LibWeb/HTML/EventNames.h
Userland/Libraries/LibWeb/HTML/HTMLStyleElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLStyleElement.h
Userland/Libraries/LibWeb/HTML/HTMLStyleElement.idl
Userland/Libraries/LibWeb/IndexedDB/IDBOpenDBRequest.cpp
Userland/Libraries/LibWeb/IndexedDB/IDBOpenDBRequest.h
Userland/Libraries/LibWeb/IndexedDB/IDBOpenDBRequest.idl
Userland/Libraries/LibWeb/IndexedDB/IDBRequest.cpp
Userland/Libraries/LibWeb/IndexedDB/IDBRequest.h
Userland/Libraries/LibWeb/IndexedDB/IDBRequest.idl

Cherry-picks the commits from https://github.com/LadybirdBrowser/ladybird/pull/242

Cherry-pick "LibWeb: Some FIXME hunting :^)"

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/PropertyAttributes.h
Userland/Libraries/LibJS/Runtime/PropertyDescriptor.h
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp

Cherry-picks the commits from https://github.com/LadybirdBrowser/ladybird/pull/136

Cherry-pick "LibJS+LibIDL+LibWeb: Reduce [FIXME] attribute unintended side effects"

---

Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/SecureContexts/AbstractOperations.cpp

This cherry-picks LadybirdBrowser/ladybird#129

Cherry-pick "LibWeb: Block file: and resource: URLs on websites (and make resource: work on file: pages)"

---

Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/Animations/TimingFunction.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/106

Cherry-pick "LibWeb: Misc animation fixes pt 4"

---

Meta/Lagom/CMakeLists.txt
Tests/LibURL/TestURL.cpp
Userland/Libraries/LibURL/Parser.cpp
Userland/Libraries/LibWebView/URL.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/127

Cherry-pick "LibWebView: Don't query public suffix list when sanitizing URLs"

---

Meta/gn/secondary/Userland/Libraries/LibWeb/SVG/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni

Meta: Port recent changes to the GN build

---

Tests/LibWeb/Text/expected/UIEvents/auxevent.txt
Tests/LibWeb/Text/input/UIEvents/auxevent.html
Userland/Libraries/LibWeb/Internals/Internals.cpp
Userland/Libraries/LibWeb/Internals/Internals.h
Userland/Libraries/LibWeb/Internals/Internals.idl
Userland/Libraries/LibWeb/Page/EventHandler.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/238

Cherry-pick "LibWeb: Fire auxclick event on middle click"

---

Userland/Libraries/LibCrypto/Checksum/CRC32.cpp

The `__builtin_arm_*` intrinsics don't exist on all ARMv8 systems, e.g. the compilation failed on my Rockchip RK3399 system (Gentoo, GCC 13).
I propose to use the standardized [ARM C Language Extensions (ACLE)](https://developer.arm.com/documentation/ihi0053/latest/) intrinsics, instead.
-----
This is a copy of LadybirdBrowser/Ladybird#397 and has not been tested in SerenityOS, because I don't have a system running SerenityOS.

LibCrypto: Use ARM C Language Extensions (ACLE) for CRC32 intrinsics

---

.github/CODEOWNERS

It's a bit redundant to be notified of changes both here and on Ladybird.

Meta: Remove myself from CODEOWNERS

---

Userland/Applications/PixelPaint/MainWidget.cpp
Userland/Applications/PixelPaint/MainWidget.h

PixelPaint: Disable Crop to Selection if empty

---

Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.h
Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.idl

(cherry picked from commit 8d593bcfeb96a3058abeec7bb772579e0c33fcb2)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/458

Cherry-pick "LibWeb: Add customElements.getName"

---

Userland/Libraries/LibWeb/CSS/Properties.json

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/442

Cherry-pick "LibWeb/CSS: Use correct initial values for CSS properties"

---

Tests/LibWeb/Layout/expected/block-and-inline/out-of-flows-not-inserted-into-generated-box.txt
Tests/LibWeb/Layout/input/block-and-inline/out-of-flows-not-inserted-into-generated-box.html
Userland/Libraries/LibWeb/Layout/Node.h
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/443

Cherry-pick "LibWeb: Fix layout issues with floats and block level pseudo elements"

---

Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/464

Cherry-pick "LibWeb: Check for failed response when fetching images and favicons"

---

Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt
Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.idl

(cherry picked from commit ccb3a2f7add22105a92ca997b67bbe02ec65b535)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/392

Cherry-pick "LibWeb: Add initial implementation of global.reportError()"

---

Tests/LibWeb/Ref/css-color-functions.html
Tests/LibWeb/Ref/reference/css-color-functions-ref.html
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/385

Cherry-pick "LibWeb/CSS: Add support for hwb, oklab and oklch color functions"

---

Tests/LibWeb/Layout/expected/css-line-height-zero.txt
Tests/LibWeb/Layout/input/css-line-height-zero.html
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/496

Cherry-pick "LibWeb: Ensure normal line-height on inputs and remove unused method"

---

Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Runtime/AbstractOperations.h
Userland/Libraries/LibJS/Runtime/KeyedCollections.cpp
Userland/Libraries/LibJS/Runtime/KeyedCollections.h
Userland/Libraries/LibJS/Runtime/MapPrototype.cpp
Userland/Libraries/LibJS/Runtime/Set.cpp
Userland/Libraries/LibJS/Runtime/Set.h
Userland/Libraries/LibJS/Runtime/SetPrototype.cpp
Userland/Libraries/LibJS/Runtime/SetPrototype.h
Userland/Libraries/LibJS/Runtime/ValueTraits.h

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/560

Cherry-pick "LibJS: Update specification steps for the Set Methods proposal"

---

Tests/LibWeb/Layout/expected/input-as-button-align-center.txt
Tests/LibWeb/Layout/expected/input-as-button-shrink-to-fit.txt
Userland/Libraries/LibWeb/CSS/Default.css
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/Page/EventHandler.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/601

Cherry-pick "LibWeb: Don't dispatch click events to disabled FormAssociatedElements"

---

Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/EmbedderPolicy.cpp
Userland/Libraries/LibWeb/HTML/EmbedderPolicy.h
Userland/Libraries/LibWeb/HTML/PolicyContainers.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h

(cherry picked from commit 190a41971569ad90c26662d7e7e850a61c55c8dd)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/515

Cherry-pick "LibWeb: Implement EmbedderPolicy struct"

---

Tests/LibWeb/Text/expected/set-selection-inside-shadow-root.txt
Tests/LibWeb/Text/input/set-selection-inside-shadow-root.html
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Selection/Selection.cpp

Cherry-pick https://github.com/LadybirdBrowser/ladybird/pull/359

Cherry-pick "LibWeb: Make text selection work inside shadow roots"

---

Tests/LibWeb/Text/expected/SVG/svg-className-attribute.txt
Tests/LibWeb/Text/input/SVG/svg-className-attribute.html
Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
Userland/Libraries/LibWeb/HTML/MessageEvent.h
Userland/Libraries/LibWeb/HTML/MessageEvent.idl
Userland/Libraries/LibWeb/SVG/AttributeNames.cpp
Userland/Libraries/LibWeb/SVG/AttributeNames.h
Userland/Libraries/LibWeb/SVG/SVGElement.cpp
Userland/Libraries/LibWeb/SVG/SVGElement.h
Userland/Libraries/LibWeb/SVG/SVGElement.idl
Userland/Libraries/LibWeb/SVG/SVGGeometryElement.idl

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/539

Cherry-pick "LibWeb: MessageEvent.initMessageEvent & SVGElement attributes"

---

Base/res/ladybird/templates/error.html
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/Navigable.h
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.cpp
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/209

Cherry-pick "LibWeb: Display error message on error page + error passing changes"

---

Tests/LibWeb/Text/expected/UIEvents/MouseEvent-bubbling.txt
Tests/LibWeb/Text/expected/UIEvents/WheelEvent-bubbling.txt
Tests/LibWeb/Text/input/UIEvents/MouseEvent-bubbling.html
Tests/LibWeb/Text/input/UIEvents/WheelEvent-bubbling.html
Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp

Cherry-picks LadybirdBrowser/ladybird#667

Cherry-pick "LibWeb: Restore event characteristics of MouseEvents"

---

Kernel/Library/KBuffer.h
Kernel/Syscalls/execve.cpp
Kernel/Tasks/Process.h
Userland/Libraries/LibELF/DynamicLoader.cpp
Userland/Libraries/LibELF/Image.cpp
Userland/Libraries/LibELF/Validation.cpp
Userland/Libraries/LibELF/Validation.h
Userland/Utilities/elfdeps.cpp
Userland/Utilities/file.cpp
Userland/Utilities/readelf.cpp

Fixes #24762.
Paired with #24761, it should be quite easy to test this :)

Kernel+Userland: Simplify loading of an ELF interpreter path

---

Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

https://github.com/LadybirdBrowser/ladybird/pull/735

Cherry-pick "LibWeb: Mixed bag of little optimizations to make loading canned Reddit less painful"

---

Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/CSS/StyleValues/StringStyleValue.h

https://github.com/LadybirdBrowser/ladybird/pull/681

Cherry-pick "LibWeb/CSS: Make StringStyleValue hold a FlyString"

---

Tests/LibWeb/Text/expected/DOM/CharacterData-replaceData-break-surrogate-pair.txt
Tests/LibWeb/Text/expected/DOM/DOMStringMap-setter-with-invalid-name.txt
Tests/LibWeb/Text/expected/HTML/maxed-out-dimension-value.txt
Tests/LibWeb/Text/expected/HTML/short-legacy-color-value.txt
Tests/LibWeb/Text/expected/Selection-setBaseAndExtent-without-common-root.txt
Tests/LibWeb/Text/input/DOM/CharacterData-replaceData-break-surrogate-pair.html
Tests/LibWeb/Text/input/DOM/DOMStringMap-setter-with-invalid-name.html
Tests/LibWeb/Text/input/HTML/maxed-out-dimension-value.html
Tests/LibWeb/Text/input/HTML/short-legacy-color-value.html
Tests/LibWeb/Text/input/Selection-setBaseAndExtent-without-common-root.html
Userland/Libraries/LibWeb/DOM/CharacterData.cpp
Userland/Libraries/LibWeb/HTML/DOMStringMap.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/Selection/Selection.cpp

https://github.com/LadybirdBrowser/ladybird/pull/721

Cherry-pick "LibWeb: Fix 5 random bugs found by fuzzing with Domato"

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibWeb/DOM/Node.idl
Userland/Libraries/LibWeb/DOM/Text.idl
Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
Userland/Libraries/LibWeb/HighResolutionTime/Performance.idl
Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.h
Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.idl
Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
Userland/Libraries/LibWeb/UIEvents/UIEvent.h

https://github.com/LadybirdBrowser/ladybird/pull/682

Cherry-pick "LibWeb: Stub/implement some missing attributes/functions"

---

Userland/Libraries/LibJS/Runtime/Intrinsics.cpp
Userland/Libraries/LibJS/Runtime/Iterator.cpp
Userland/Libraries/LibJS/Runtime/Iterator.h
Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/IteratorPrototype.h
Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.@@toStringTag.js
Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.constructor.js

https://github.com/LadybirdBrowser/ladybird/pull/663

Cherry-pick "LibJS: Implement Iterator.prototype [ @@toStringTag ] and Iterator.prototype.constructor according to spec"

---

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h

https://github.com/LadybirdBrowser/ladybird/pull/265

Cherry-pick "LibWeb: Fire input event on user interaction with input element buttons"

---

Tests/LibWeb/Text/expected/DOM/Node-isEqualNode.txt
Tests/LibWeb/Text/input/DOM/Node-isEqualNode.html
Userland/Libraries/LibWeb/DOM/DocumentType.idl
Userland/Libraries/LibWeb/DOM/Node.cpp

https://github.com/LadybirdBrowser/ladybird/pull/705

Cherry-pick "LibWeb: An assortment of fixes for DOM::Node"

---

Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.h
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.h

https://github.com/LadybirdBrowser/ladybird/pull/673

Cherry-pick "LibWeb/Fetch: Implement fetch record and fetch group"

---

Tests/LibWeb/Text/expected/HTML/relList-attribute.txt
Tests/LibWeb/Text/expected/SVG/svg-ownerSVGElement-attribute.txt
Tests/LibWeb/Text/input/HTML/relList-attribute.html
Tests/LibWeb/Text/input/SVG/svg-ownerSVGElement-attribute.html
Userland/Libraries/LibWeb/SVG/SVGAElement.cpp
Userland/Libraries/LibWeb/SVG/SVGAElement.h
Userland/Libraries/LibWeb/SVG/SVGAElement.idl
Userland/Libraries/LibWeb/SVG/SVGElement.cpp
Userland/Libraries/LibWeb/SVG/SVGElement.h
Userland/Libraries/LibWeb/SVG/SVGElement.idl
Userland/Libraries/LibWeb/SVG/SVGGradientElement.cpp
Userland/Libraries/LibWeb/SVG/SVGGradientElement.h
Userland/Libraries/LibWeb/SVG/SVGGradientElement.idl
Userland/Libraries/LibWeb/SVG/SVGScriptElement.cpp
Userland/Libraries/LibWeb/SVG/SVGScriptElement.h
Userland/Libraries/LibWeb/SVG/SVGScriptElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/666

Cherry-pick "LibWeb/SVG: SVGElement.ownerSVGElement, SVGAElement.* attributes, SVGURIReference includes"

---

Tests/LibWeb/Text/expected/DOM/Node-isDefaultNamespace.txt
Tests/LibWeb/Text/expected/DOM/Node-lookupNamespaceURI.txt
Tests/LibWeb/Text/input/DOM/Node-isDefaultNamespace.html
Tests/LibWeb/Text/input/DOM/Node-lookupNamespaceURI.html
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/DOM/Node.idl

https://github.com/LadybirdBrowser/ladybird/pull/693

Cherry-pick "LibWeb: Add 2 missing methods to DOM::Node"

---

Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Userland/Libraries/LibWeb/HTML/History.idl
Userland/Libraries/LibWeb/SVG/SVGLength.idl
Userland/Libraries/LibWeb/SVG/SVGSymbolElement.cpp
Userland/Libraries/LibWeb/SVG/SVGSymbolElement.h
Userland/Libraries/LibWeb/SVG/SVGSymbolElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/744

Cherry-pick "LibWeb: Stub missing attributes in SVGLength & HTMLImageElement"

---

Tests/LibWeb/Layout/expected/svg/svg-viewbox-zero-width.txt
Tests/LibWeb/Layout/input/svg/svg-viewbox-zero-width.html
Tests/LibWeb/Text/expected/Element-scrollby-negative-scroll-offset-crash.txt
Tests/LibWeb/Text/expected/SVG/svg-getbbox-transform-with-no-inverse.txt
Tests/LibWeb/Text/input/Element-scrollby-negative-scroll-offset-crash.html
Tests/LibWeb/Text/input/SVG/svg-getbbox-transform-with-no-inverse.html
Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp

This PR fixes a few crashes found via DOM fuzzing with [Domato](https://github.com/googleprojectzero/domato).
See individual commits for details.<hr>Cherry-picks LadybirdBrowser/ladybird#758<br><sub>Generated with LBSync, did I do well?</sub>

Cherry-pick "LibWeb: Fix a few crashes found by Domato"

---

Tests/LibWeb/Text/expected/DOM/getElementById-empty-string.txt
Tests/LibWeb/Text/expected/DOM/getElementsByClassName-empty-string.txt
Tests/LibWeb/Text/expected/DOM/getElementsName-empty-string.txt
Tests/LibWeb/Text/input/DOM/getElementById-empty-string.html
Tests/LibWeb/Text/input/DOM/getElementsByClassName-empty-string.html
Tests/LibWeb/Text/input/DOM/getElementsName-empty-string.html
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Document.idl
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/ParentNode.cpp
Userland/Libraries/LibWeb/DOM/ParentNode.h

Cherry-picks LadybirdBrowser/ladybird#773<br><sub>Generated with LBSync, did I do well?</sub>

Cherry-pick "LibWeb: A handful of fixes for some element querying methods"

---

Tests/LibWeb/Text/expected/DOM/Text-wholeText.txt
Tests/LibWeb/Text/input/DOM/Text-wholeText.html
Userland/Libraries/LibWeb/DOM/Text.cpp
Userland/Libraries/LibWeb/DOM/Text.h
Userland/Libraries/LibWeb/DOM/Text.idl

Cherry-picks LadybirdBrowser/ladybird#725<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: Implement Text.wholeText"

---

Tests/LibWeb/Layout/expected/css-content-visibility.txt
Tests/LibWeb/Layout/expected/details-closed.txt
Tests/LibWeb/Layout/input/css-content-visibility.html
Tests/LibWeb/Ref/reference/webkit-box-shadow.html
Tests/LibWeb/Ref/reference/webkit-text-fill-color.html
Tests/LibWeb/Ref/webkit-box-shadow.html
Tests/LibWeb/Ref/webkit-text-fill-color.html
Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleInvalidation.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/HTML/HTMLDetailsElement.cpp
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

Cherry-picks LadybirdBrowser/ladybird#502<br>Cherry-picks LadybirdBrowser/ladybird#501<br>Cherry-picks LadybirdBrowser/ladybird#267<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick 3 PRs from Ladybird

---

Tests/LibWeb/Text/expected/HTML/Element-checkVisibility.txt
Tests/LibWeb/Text/input/HTML/Element-checkVisibility.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl

(cherry picked from commit 5f154ba372f9a667351a026aa4a31306c45fd2a5)
---
https://github.com/LadybirdBrowser/ladybird/pull/717

Cherry-pick "LibWeb: Implement Element::check_visibility"

---

Userland/Libraries/LibIMAP/Parser.cpp

This PR avoids crashing the parser when a group address is encountered, and keeps the Mail reader happy :^).
Eventually, when we are able to send messages, we may want some kind of GroupAddress object, but for now this should be ok.

LibIMAP: Avoid crashing on Group Addresses

---

Tests/LibGfx/TestImageWriter.cpp
Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp

Add support for writing the subtract green transform, and use it for constant-alpha grayscale images, but also by default for all non-color-indexing-transformed images.
This makes some images larger, but it's on average better than
not doing it: When compressing all images in:
* Base/res/wallpapers
* qoi_benchmark_suite/screenshot_web
* qoi_benchmark_suite/textures_photo
...this reduces the combined output size from 105M to 88M (16%).
See PR for details on reproducing this.
(Runtime for compressing all images increases from a little under
4.4s to a little over 4.4s, so no big per cost either.)
For the images in those directories, it's even always a win.
The size of qoi_benchmark_suite/textures_pk01/pk01_floor01_local.png
increases from 366K to 375K (2.5%), so it's not _always_ a win. …

LibGfx/WebPWriterLossless: Subtract green transform

---

Ladybird/AppKit/Application/ApplicationDelegate.h
Ladybird/AppKit/Application/ApplicationDelegate.mm
Ladybird/AppKit/UI/TabController.h
Ladybird/AppKit/UI/TabController.mm
Ladybird/AppKit/main.mm

https://github.com/LadybirdBrowser/ladybird/pull/536

Cherry-pick "UI/AppKit: Port --allow-popups and --force-new-process CLI options"

---

Userland/Libraries/LibIMAP/Parser.cpp

This PR fixes truncation of quoted strings containing escaped quotes, which were not being handled properly by the parser, resulting in occasional crashes.

LibIMAP: Handle escaped quotes in parse_quoted_string()

---

Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp

(cherry picked from commit 6e77fff698e1bbb5443c7071d81cb26aaf5f5153)
---
https://github.com/LadybirdBrowser/ladybird/pull/822

Cherry-pick "LibWeb: Bring 'construct_entry_list' closer to specs"

---

Tests/LibWeb/Layout/expected/host-pseudo-class-basic.txt
Tests/LibWeb/Layout/input/host-pseudo-class-basic.html
Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Userland/Libraries/LibWeb/CSS/SelectorEngine.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/ParentNode.cpp

https://github.com/LadybirdBrowser/ladybird/pull/790

Cherry-pick "LibWeb: Implement :host and :host(<compound-selector>) selector matching"

---

Tests/LibWeb/Text/expected/HTML/HTMLSelectElement-options-available-after-add.txt
Tests/LibWeb/Text/expected/HTML/HTMLSelectElement-options-available-at-load.txt
Tests/LibWeb/Text/input/HTML/HTMLSelectElement-options-available-after-add.html
Tests/LibWeb/Text/input/HTML/HTMLSelectElement-options-available-at-load.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp

https://github.com/LadybirdBrowser/ladybird/pull/812

Cherry-pick "LibWeb: Fix <select> element behavior when its changed from JavaScript"

---

Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp
Userland/Libraries/LibWeb/Bindings/PlatformObject.h
Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
Userland/Libraries/LibWeb/DOM/HTMLCollection.h

This makes https://wpt.fyi/ load today instead of tomorrow, although there's a lot of room for improvement still.
(cherry picked from commit 4d78c66b3d0092d0e6137a11d55e59a6b8bfc5b1)
---
https://github.com/LadybirdBrowser/ladybird/pull/823

Cherry-pick "LibWeb: Cache name->element mappings in HTMLCollection"

---

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.h

https://github.com/LadybirdBrowser/ladybird/pull/770

Cherry-pick "LibWeb: Append fetch record to client's fetch group when request is a subresource"

---

Tests/LibWeb/Layout/expected/grid/fit-content-1.txt
Tests/LibWeb/Layout/expected/grid/fit-content-2.txt
Tests/LibWeb/Layout/input/grid/fit-content-1.html
Tests/LibWeb/Layout/input/grid/fit-content-2.html
Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
Userland/Libraries/LibWeb/CSS/GridTrackSize.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FormattingContext.h
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

https://github.com/LadybirdBrowser/ladybird/pull/815

Cherry-pick "LibWeb: Support grid template function fit-content"

---

Tests/LibWeb/Text/expected/DOM/Node-nodeName.txt
Tests/LibWeb/Text/input/DOM/Node-nodeName.html
Userland/Libraries/LibWeb/DOM/DocumentType.h

https://github.com/LadybirdBrowser/ladybird/pull/838

Cherry-pick "LibWeb: Make DocumentType::node_name() return DocumentType::name()"

---

Tests/LibWeb/Text/expected/DOM/CDATASection-cloneNode.txt
Tests/LibWeb/Text/expected/DOM/Range-containing-CDATASection.txt
Tests/LibWeb/Text/input/DOM/CDATASection-cloneNode.html
Tests/LibWeb/Text/input/DOM/Range-containing-CDATASection.html
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h

https://github.com/LadybirdBrowser/ladybird/pull/798

Cherry-pick "LibWeb: A few more DOM::Node fixes"

---

Tests/LibWeb/Text/expected/HTML/HTMLMediaElement-addTextTrack.txt
Tests/LibWeb/Text/input/HTML/HTMLMediaElement-addTextTrack.html
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
Userland/Libraries/LibWeb/HTML/TextTrack.cpp
Userland/Libraries/LibWeb/HTML/TextTrack.h
Userland/Libraries/LibWeb/HTML/TextTrack.idl

https://github.com/LadybirdBrowser/ladybird/pull/836

Cherry-pick "LibWeb/HTML: Implement HTMLMediaElement.addTextTrack"

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
Tests/LibWeb/Layout/expected/css-counters/basic.txt
Tests/LibWeb/Layout/expected/css-counters/counters-function.txt
Tests/LibWeb/Layout/expected/css-counters/hidden-elements.txt
Tests/LibWeb/Layout/input/css-counters/basic.html
Tests/LibWeb/Layout/input/css-counters/counters-function.html
Tests/LibWeb/Layout/input/css-counters/hidden-elements.html
Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/CSS/CSSNumericType.cpp
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/CountersSet.cpp
Userland/Libraries/LibWeb/CSS/CountersSet.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/CSS/StyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValue.h
Userland/Libraries/LibWeb/CSS/StyleValues/CounterDefinitionsStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CounterDefinitionsStyleValue.h
Userland/Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

https://github.com/LadybirdBrowser/ladybird/pull/720

Cherry-pick "LibWeb: First pass at CSS counters"

---

Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/CSS/FontFace.cpp
Userland/Libraries/LibWeb/CSS/Parser/Helpers.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.h
Userland/Libraries/LibWeb/CSS/SyntaxHighlighter/SyntaxHighlighter.cpp
Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h
Userland/Libraries/LibWeb/HTML/SourceSet.cpp

https://github.com/LadybirdBrowser/ladybird/pull/846

Cherry-pick "LibWeb/CSS: Make CSS Parser construction infallible"

---

Userland/Libraries/LibWeb/HTML/AttributeNames.h
Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl
Userland/Libraries/LibWeb/HTML/HTMLMarqueeElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMarqueeElement.h
Userland/Libraries/LibWeb/HTML/HTMLMarqueeElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/608

Cherry-pick "LibWeb: Implement some obsolete attributes"

---

Ladybird/AppKit/main.mm
Ladybird/Qt/main.cpp
Userland/Applications/Browser/main.cpp
Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Libraries/LibWebView/ChromeProcess.cpp
Userland/Libraries/LibWebView/ChromeProcess.h

https://github.com/LadybirdBrowser/ladybird/pull/764

Cherry-pick "LibCore+LibWebView+UI: Raise the chrome process open file limit"

---

Meta/gn/secondary/Userland/Libraries/LibWeb/WebAudio/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.cpp
Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.h
Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.idl
Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.cpp
Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.h
Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.idl
Userland/Libraries/LibWeb/WebAudio/AudioNode.cpp
Userland/Libraries/LibWeb/WebAudio/AudioNode.h
Userland/Libraries/LibWeb/WebAudio/AudioNode.idl
Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.cpp
Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.h
Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.idl
Userland/Libraries/LibWeb/WebAudio/GainNode.cpp
Userland/Libraries/LibWeb/WebAudio/GainNode.h

https://github.com/LadybirdBrowser/ladybird/pull/867

Cherry-pick "More WebAudio Stubbing"

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Tests/for-loop-per-iteration-env-bug.js

Cherry-picks LadybirdBrowser/ladybird#804<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibJS: Fix crash in bytecode generator on https://twinings.co.uk/"

---

Userland/Libraries/LibWeb/WebIDL/OverloadResolution.cpp

Cherry-picks LadybirdBrowser/ladybird#803<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: WebIDL::OverloadResolution::resolve_overload, add dbgln FIXMEs"

---

Userland/Libraries/LibWeb/DOM/Document.cpp

Cherry-picks LadybirdBrowser/ladybird#699<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb/DOM: Avoid repeated calls to Node::navigable"

---

AK/LEB128.h
AK/SIMDExtras.h
Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
Userland/Libraries/LibWasm/AbstractMachine/Configuration.cpp
Userland/Libraries/LibWasm/AbstractMachine/Operators.h
Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
Userland/Libraries/LibWasm/AbstractMachine/Validator.h
Userland/Libraries/LibWasm/Opcode.h
Userland/Libraries/LibWasm/Parser/Parser.cpp
Userland/Libraries/LibWasm/Printer/Printer.cpp
Userland/Libraries/LibWasm/Printer/Printer.h
Userland/Libraries/LibWasm/Types.h
Userland/Libraries/LibWasm/WASI/Wasi.cpp
Userland/Libraries/LibWasm/Wasi.h
Userland/Utilities/wasm.cpp

LibWasm: Sync!

---

Documentation/BuildInstructions.md

build instructions --> Build Instructions

Documentation: Fix BuildInstructions.md capitialization

---

Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp

Cherry-picks LadybirdBrowser/ladybird#732<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibGfx: Handle UTF-16-encoded OpenType font names"

---

Kernel/Memory/Region.cpp

Writes to SharedInodeVMObjects could cause a Protection Violation if a page was marked as dirty by a different process.
This happened due to a combination of 2 things:
* handle_dirty_on_write_fault() was skipped if a page was already marked as dirty
* when a page was marked as dirty, only the Region that caused the page fault was remapped
This commit:
* fixes the crash by making handle_fault() stop checking if a page was marked dirty before running handle_dirty_on_write_fault()
* modifies handle_dirty_on_write_fault() so that it always marks the page as dirty and remaps the page (this avoids a 2nd bug that was never hit due to the 1st bug)
This fixes issue #24801

Kernel/Memory: Fix crash on writes to shared file mmaps

---

Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp

Before, we would compute and store the output of each predictor,
then pick the best one, and then copy its data.
Now, we compute the output of each predictor but only compute its
score and do not store the predicted data. We then pick the best
one, and do a second pass that re-computes the output of the best
predictor, and stores it.
Instead of computing the output of the 5 different predictors, we now
compute the output of the 5 different predictors, and then the output of
one of them again. In exchange, we only write each output row once
instead of 5 times. (We also have to read the input row twice instead of
once, but the second time round it'll come from L1 or L2.)
Making the simplifying assumption that each predictor takes the same
time to compute, this increases compute to 6/5th, …

LibGfx/PNGWriter: Compute which predictor to use first, store data then

---

Userland/Libraries/LibURL/Parser.cpp
Userland/Libraries/LibURL/URL.cpp
Userland/Libraries/LibURL/URL.h
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/CSS/Angle.cpp
Userland/Libraries/LibWeb/CSS/Angle.h
Userland/Libraries/LibWeb/CSS/Frequency.cpp
Userland/Libraries/LibWeb/CSS/Frequency.h
Userland/Libraries/LibWeb/CSS/Length.cpp
Userland/Libraries/LibWeb/CSS/Length.h
Userland/Libraries/LibWeb/CSS/PercentageOr.cpp
Userland/Libraries/LibWeb/CSS/PercentageOr.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/CSS/Time.cpp
Userland/Libraries/LibWeb/CSS/Time.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/HTML/HTMLBodyElement.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp

Cherry-picks LadybirdBrowser/ladybird#935<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb+LibURL: Handful of patches to make CSS data structures use way less memory"

---

Base/res/ladybird/inspector.css
Base/res/ladybird/inspector.js

Cherry-picks LadybirdBrowser/ladybird#934<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWebView: Improve scrolling of Inspector content containers"

---

Base/res/ladybird/inspector.js

Cherry-picks LadybirdBrowser/ladybird#931<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWebView: Sort vendor-prefixed properties last in the inspector"

---

Userland/Libraries/LibWeb/WebAssembly/Table.cpp
Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp

Cherry-picks LadybirdBrowser/ladybird#909<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: No longer return `undefined` on null table entry in Wasm API"

---

Tests/LibWeb/Ref/reference/scrollable-contains-table-ref.html
Tests/LibWeb/Ref/scrollable-contains-table.html
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

Cherry-picks LadybirdBrowser/ladybird#902<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: Apply scroll offset and clip rectangle to table borders"

---

Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h

Cherry-picks LadybirdBrowser/ladybird#913<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: Keep Wasm-imported functions alive"

---

Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp

One minor thing, and another thing that happens to reduce output size by ~5%, for a 2-3% runtime cost:
We were computing abs(sum(signed_pixels)), while the comment says
that sum(abs(signed_pixels)) works well. Change the code to match
the comment. (While I did tweak this code recently, as far as I can
tell the code hasn't matched the comment from when it was originally
added.)
Using the benchmarking script and same inputs as in #24819, just changed
to write .png files with different --png-compression-level values:
level 0: 390M -> 390M (no change)
level 1:  83M ->  78M (6% smaller)
level 2:  73M ->  69M (5.8% smaller at default compression level)
level 3:  71M ->  67M (5.6% smaller)
Sizes as computed by `du -hAs`. (`-A` prints apparent size on macOS.
It's important to use that flag to get …

LibGfx/PNGWriter: Some final (?) cleanups

---

Userland/Applications/PDFViewer/CMakeLists.txt
Userland/Applications/PDFViewer/PDFViewer.h
Userland/Applications/PDFViewer/PDFViewerWidget.cpp
Userland/Applications/PDFViewer/PDFViewerWidget.h
Userland/Applications/PDFViewer/SidebarWidget.cpp
Userland/Applications/PDFViewer/SidebarWidget.h
Userland/Applications/PDFViewer/ThumbnailsListView.cpp
Userland/Applications/PDFViewer/ThumbnailsListView.h
Userland/Applications/PDFViewer/ThumbnailsModel.cpp
Userland/Applications/PDFViewer/ThumbnailsModel.h

This PR adds thumbnail previews and navigation to PDFViewer :^)

PDFViewer: Implement thumbnail previews

---

Userland/Applications/TextEditor/CMakeLists.txt
Userland/Applications/TextEditor/MainWidget.cpp
Userland/Applications/TextEditor/MainWidget.h
Userland/Applications/TextEditor/TextEditorWindow.gml
Userland/Applications/TextEditor/main.cpp

TextEditor: Port TextEditor to GML Compiler

---

Tests/LibCompress/TestDeflate.cpp

- Use TRY_OR_FAIL() instead of MUST() in a few places
- Use for-each loop in two tests
- Use StringView literals instead of u8 arrays in a few places

Tests: Modernize TestDeflate a bit

---

Base/etc/shellrc

Just a little QoL improvement for muscle memory :^)

Base: Add poweroff alias to shellrc

---

AK/Coroutine.h
AK/StreamBuffer.h
Userland/Libraries/LibHTTP/Http11Connection.cpp
Userland/Libraries/LibHTTP/Job.cpp

Just some random fixes from my local dev branch I'm tired of carrying around and rebasing.
----
Hmm, not sure about "the best reviewer", maybe @alimpfard

AK: Miscellaneous coroutine fixes

---

Kernel/FileSystem/Ext2FS/Inode.cpp

This PR has commits with the following changes:
* Reduce the number of `kmalloc()` an `kfree()` calls in `Ext2FSInode::compute_block_list_impl()` by reducing the number of times `ByteBuffer`s are created and destroyed.
* Add a new test case for writes and reads to Ext2FS files.

Kernel/Ext2FS: Reduce allocations in compute_block_list_impl()

---

Userland/Libraries/LibWeb/Painting/Command.cpp
Userland/Libraries/LibWeb/Painting/PaintOuterBoxShadowParams.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp

Cherry-picks LadybirdBrowser/ladybird#94<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: Remove unused members in PaintOuterBoxShadowParams"

---

Userland/Libraries/LibWeb/Page/EventHandler.cpp

Cherry-picks LadybirdBrowser/ladybird#54<br>Cherry-picks LadybirdBrowser/ladybird#61<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick 2 PRs from Ladybird

---

Userland/Libraries/LibWeb/Painting/Command.cpp
Userland/Libraries/LibWeb/Painting/Command.h
Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/CommandList.h
Userland/Libraries/LibWeb/Painting/PaintBoxShadowParams.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Userland/Libraries/LibWeb/Painting/ShadowPainting.h

Cherry-picks LadybirdBrowser/ladybird#98<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb: Implement rejection by bounding box for PaintInnerBoxShadow"

---

Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/Navigable.h
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Userland/Services/WebContent/PageClient.cpp

Cherry-picks LadybirdBrowser/ladybird#123<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>

Cherry-pick "LibWeb+WebContent: Move PageClient::paint() into TraversableNavigable"

---

Userland/Applications/HexEditor/HexEditorWidget.cpp

Fixes https://github.com/SerenityOS/serenity/issues/17487

HexEditor: Replace newlines with space character in the value inspector

---

Tests/LibGfx/CMakeLists.txt
Tests/LibGfx/TestPath.cpp
Userland/Libraries/LibGfx/Path.cpp
Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

LibPDF+LibGfx: Plumb through line cap style, fix infinite loop in butt line cap drawing

---

Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/1018

Cherry-pick "LibWeb/CSS: Use TokenStream in more places"

---

Documentation/Browser/CSSGeneratedFiles.md
Documentation/README.md

(cherry picked from commit 71d977b79127434e9b8feef5dc73bce0f421b450; amended to resolve minor conflict in README.md)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/1370

Cherry-pick "Documentation: Document the CSS JSON files and what they do"

---

Tests/LibWeb/Text/expected/css/update-pseudo-elements-on-hover.txt
Tests/LibWeb/Text/input/css/update-pseudo-elements-on-hover.html
Userland/Libraries/LibWeb/CSS/StyleInvalidation.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h

Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/888

Cherry-pick "LibWeb: Update pseudo-elements on hover, fixing Acid2 nose"

---

Ladybird/AppKit/Application/ApplicationDelegate.h
Ladybird/AppKit/Application/ApplicationDelegate.mm
Ladybird/AppKit/UI/LadybirdWebView.h
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
Ladybird/AppKit/UI/LadybirdWebViewBridge.h
Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/WebContentView.h
Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/CSS/PreferredContrast.cpp
Userland/Libraries/LibWeb/CSS/PreferredContrast.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Services/WebWorker/PageHost.cpp
Userland/Services/WebWorker/PageHost.h

(cherry picked from commit ee6468456580fa0380daeb0b9ab0bdf2832f9dcf)
---
https://github.com/LadybirdBrowser/ladybird/pull/146

Cherry-pick "LibWeb: Add Contrast preference"

---

Ladybird/Qt/FindInPageWidget.cpp
Ladybird/Qt/FindInPageWidget.h
Ladybird/Qt/Tab.cpp
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/WebContentClient.ipc

https://github.com/LadybirdBrowser/ladybird/pull/121/

Cherry-pick "LibWeb+WebContent+UI/Qt: Provide feedback on find in page requests"

---

Ladybird/AppKit/UI/LadybirdWebView.h
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/AppKit/UI/SearchPanel.h
Ladybird/AppKit/UI/SearchPanel.mm
Ladybird/AppKit/UI/Tab.mm

(cherry picked from commit 54183b8eef601a0bed3b3680de5468a9521db7c7)
---
https://github.com/LadybirdBrowser/ladybird/pull/135
(Needed to make another cherry pick apply more cleanly)

Cherry-pick "UI/AppKit: Display query results on the find-in-page panel"

---

Kernel/Bus/USB/xHCI/xHCIController.cpp

This makes bulk transfers work on my pc.

Kernel/USB: Correct the calculation of the xHCI TD Size Normal TRB field

---

Userland/Libraries/LibWeb/CSS/StyleInvalidation.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

https://github.com/LadybirdBrowser/ladybird/pull/908

Cherry-pick "LibWeb: Be smarter about pseudo-element style invalidation"

---

Tests/LibWeb/Layout/expected/css-dir-selector.txt
Tests/LibWeb/Layout/expected/writing-modes-direction-flex.txt
Tests/LibWeb/Layout/expected/writing-modes-direction-inline.txt
Tests/LibWeb/Layout/input/writing-modes-direction-flex.html
Tests/LibWeb/Layout/input/writing-modes-direction-inline.html
Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
Userland/Libraries/LibWeb/Layout/Node.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1060

Cherry-pick "LibWeb: Begin support for direction property"

---

Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebWorker/PageHost.h

https://github.com/LadybirdBrowser/ladybird/pull/208

Cherry-pick "LibWeb: Respect selected painter in SVGDecodedImageData"

---

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
Userland/Libraries/LibWeb/Layout/Node.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1156

Cherry-pick "LibWeb: Support parsing multicol CSS properties"

---

Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
Userland/Libraries/LibWeb/CSS/StyleSheetList.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
Userland/Libraries/LibWeb/Dump.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1139

Cherry-pick "LibWeb: Some optimizations to spend much less time in style update"

---

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1331

Cherry-pick "LibJS: Add "month day, year" support to Date.parse"

---

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js

(cherry picked from commit a3472aef2401d6b550207475d60f1d5b336254dd)
---
https://github.com/LadybirdBrowser/ladybird/pull/1459

Cherry-pick "LibJS: Extend supported date string formats"

---

Meta/Lagom/Tools/CodeGenerators/LibTextCodec/GenerateEncodingIndexes.cpp
Tests/LibTextCodec/CMakeLists.txt
Tests/LibTextCodec/TestTextEncoders.cpp
Userland/Libraries/LibTextCodec/CMakeLists.txt
Userland/Libraries/LibTextCodec/Encoder.cpp
Userland/Libraries/LibTextCodec/Encoder.h
Userland/Libraries/LibURL/CMakeLists.txt
Userland/Libraries/LibURL/Parser.cpp
Userland/Libraries/LibURL/Parser.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
Userland/Libraries/LibWeb/DOMURL/DOMURL.h
Userland/Libraries/LibWeb/DOMURL/URLSearchParams.cpp
Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp

https://github.com/LadybirdBrowser/ladybird/pull/975

Cherry-pick "LibTextCodec: Implement legacy encoders"

---

.github/actions/cache-restore/action.yml
Toolchain/BuildJakt.sh

This is probably a bit too permissive, but should be fine.

Toolchain: Skip building jakt if commit hash hasn't changed

---

Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.idl
Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/1052

Cherry-pick "LibWeb/HTML: Implement HTML{IFrame,Image}Element.longDesc"

---

Userland/Libraries/LibWeb/HTML/AttributeNames.h
Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl
Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/1058

Cherry-pick "LibWeb: Some small obsolete IDL property changes"

---

AK/String.cpp
AK/String.h
Tests/AK/TestString.cpp
Tests/LibWeb/Text/expected/URL/search-params-with-invalid-utf8.txt
Tests/LibWeb/Text/expected/URL/search-params-with-plus-in-value.txt
Tests/LibWeb/Text/input/URL/search-params-with-invalid-utf8.html
Tests/LibWeb/Text/input/URL/search-params-with-plus-in-value.html
Userland/Libraries/LibTextCodec/Decoder.cpp
Userland/Libraries/LibURL/Parser.cpp
Userland/Libraries/LibURL/URL.cpp
Userland/Libraries/LibURL/URL.h
Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
Userland/Libraries/LibWeb/DOMURL/URLSearchParams.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
Userland/Libraries/LibWeb/ReferrerPolicy/AbstractOperations.cpp
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1023
https://github.com/LadybirdBrowser/ladybird/pull/1038

Cherry-pick "LibWeb: Actually run UTF-8 decode without BOM for URLSearchParams" + followup

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/input-image.txt
Tests/LibWeb/Text/expected/usvstring-url-reflection.txt
Tests/LibWeb/Text/expected/video-canceled-load.txt
Tests/LibWeb/Text/expected/video-failed-load.txt
Tests/LibWeb/Text/input/input-image.html
Tests/LibWeb/Text/input/usvstring-url-reflection.html
Tests/LibWeb/Text/input/video-canceled-load.html
Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.idl
Userland/Libraries/LibWeb/HTML/HTMLEmbedElement.idl
Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl
Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.idl
Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.idl
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.idl
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl
Userland/Libraries/LibWeb/HTML/HTMLSourceElement.idl
Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/1059

Cherry-pick "LibWeb: Change IDL attribute type to USVString where applicable"

---

Userland/Libraries/LibWeb/Animations/Animatable.cpp
Userland/Libraries/LibWeb/Animations/Animatable.h
Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

https://github.com/LadybirdBrowser/ladybird/pull/921

Cherry-pick "LibWeb: Add slots for pseudo-elements animation cache in Animatable"

---

Userland/Libraries/LibWebView/ProcessManager.cpp

(cherry picked from commit a0874dc870ea5746c33165c56532480670d55492)
---
Sneak commit without PR: https://github.com/LadybirdBrowser/ladybird/commit/a0874dc870ea5746c33165c56532480670d55492

Cherry-pick "LibWebView: Remove ProcessManager debug spam"

---

AK/CopyOnWrite.h
Userland/Libraries/LibURL/URL.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h

https://github.com/LadybirdBrowser/ladybird/pull/1359

Cherry-pick "LibWeb: Make CSS::StyleProperties copy-on-write internally"

---

Tests/LibWeb/Layout/expected/css-round-function-with-percentage-value.txt
Tests/LibWeb/Layout/input/css-round-function-with-percentage-value.html
Userland/Libraries/LibWeb/CSS/PercentageOr.h
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h

https://github.com/LadybirdBrowser/ladybird/pull/1420

Cherry-pick "LibWeb: Use correct resolved type for round() CSS function"

---

Tests/LibWeb/Text/expected/HTML/History-scrollRestoration.txt
Tests/LibWeb/Text/input/HTML/History-scrollRestoration.html
Userland/Libraries/LibWeb/HTML/History.cpp
Userland/Libraries/LibWeb/HTML/History.h
Userland/Libraries/LibWeb/HTML/History.idl

(cherry picked from commit 2106617f5b97dd2e3c4aea11ef26685f43e75261)
---
https://github.com/LadybirdBrowser/ladybird/pull/1595

Cherry-pick "LibWeb: Implement `history.scrollRestoration`"

---

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/Layout/Node.cpp

(cherry picked from commit 68a28ff33abe29376cea009e24c406d3a23d4890)
---
https://github.com/LadybirdBrowser/ladybird/pull/1560

Cherry-pick "LibWeb/CSS: Parse the tab-size property"

---

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Runtime/Object.cpp

1.25x speed-up on this microbenchmark:
let o = { get x() { return 1; } };
for (let i = 0; i < 10_000_000; ++i)
o.x;
I looked into this because I noticed getter invocation when profiling long-running WPT tests. We already had the mechanism for non-getter properties, and the change to support getters turned out to be trivial.
(cherry picked from commit 3c5819a6d27883907237bf8137fd4dc24ed04e72)
---
https://github.com/LadybirdBrowser/ladybird/pull/1843

Cherry-pick "LibJS: Allow GetById to cache getters"

---

Userland/Libraries/LibJS/Print.cpp

Printing the whole array causes wpt
console/console-log-large-array.any.html to crash. This limits logged arrays to 100 elements and
truncates the rest with ...
(cherry picked from commit 9650cf8b15a941aaf71c8a4d7db6ee899e367cbd)
---
https://github.com/LadybirdBrowser/ladybird/pull/1705

Cherry-pick "LibJS: Do not print large arrays"

---

Tests/LibWeb/Layout/expected/border-spacing-calc-dont-crash.txt
Tests/LibWeb/Layout/expected/css-rect-value-with-calc-dont-crash.txt
Tests/LibWeb/Layout/input/border-spacing-calc-dont-crash.html
Tests/LibWeb/Layout/input/css-rect-value-with-calc-dont-crash.html
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/Layout/Node.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1698

Cherry-pick "Fix issues that were causing WPT to crash in /quirks/unitless-length"

---

Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/Layout/Node.cpp

(cherry picked from commit 537cbf55c36c14247d027f0495d595eb357dd84d)
---
https://github.com/LadybirdBrowser/ladybird/pull/1911

Cherry-pick "LibWeb: Add letter-spacing css property to Node"

---

Userland/Libraries/LibWeb/CSS/Selector.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1341

Cherry-pick "LibWeb: Some juicy speedups for selector matching on vercel.com and Tailwind CSS sites in general"

---

Ladybird/AppKit/Application/ApplicationDelegate.mm
Ladybird/AppKit/Application/EventLoopImplementation.h
Ladybird/AppKit/Application/EventLoopImplementation.mm
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/EventLoopImplementationQt.cpp
Ladybird/Qt/EventLoopImplementationQt.h
Userland/Libraries/LibProtocol/RequestClient.cpp

Cherry-picks the first four commits from https://github.com/LadybirdBrowser/ladybird/pull/319
(The fifth is the actual change. It's harder to cherry-pick because we don't have https://github.com/LadybirdBrowser/ladybird/pull/284 and hence still use still have register_with_process_manager, and we don't have https://github.com/LadybirdBrowser/ladybird/pull/233, in particular the "hand pid" commit. The third commit is what causes most merge conflicts though, so getting just the first four unblocks some other things. Eventually we'll want the other two commits too.)

Cherry-pick prep for "Ladybird: Manage processes in LibWebView in a more comprehensive way"

---

Userland/Libraries/LibWeb/CSS/CSSRule.cpp
Userland/Libraries/LibWeb/CSS/CSSRule.h
Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleRule.h
Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Userland/Libraries/LibWeb/CSS/SelectorEngine.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h

https://github.com/LadybirdBrowser/ladybird/pull/1345

Cherry-pick "LibWeb: More work on making style updates faster"

---

Ladybird/Qt/FindInPageWidget.cpp

(cherry picked from commit 8c2f1fd68f616ba859d26aeb6b1ecbb7c300fca6)
---
https://github.com/LadybirdBrowser/ladybird/pull/36

Cherry-pick "Ladybird/Qt: Set find in page query to selected text on initial focus"

---

Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/Tab.cpp
Ladybird/Qt/Tab.h

https://github.com/LadybirdBrowser/ladybird/pull/70

Cherry-pick "UI/Qt: Set debug menu options across all tabs"

---

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

Once we know the final value of the `content` property for a pseudo-element, we can bail early if the value is `none` or `normal` (note that `normal` only applies to ::before and ::after).
In those cases, no pseudo-element will be generated, so everything that follows in StyleComputer would be wasted work.
This noticeably improves performance on many pages, such as https://tailwindcss.com/ where style updates go from 360ms -> 250ms.
(cherry picked from commit d22228ab93b387e043b5bce29f79ef5ffa7c0f9d)
---
https://github.com/LadybirdBrowser/ladybird/pull/1361

Cherry-pick "LibWeb: Bail early from doomed pseudo-element style computation"

---

Documentation/VirtualBox.md

i tested AHCI(SATA) mode on windows(virtualbox 6.1.12) and linux(virtualbox 7.0.6)  . but PIIX4 is not worked.

Document: Modify the storage type of VirtualBox

---

Ladybird/AppKit/Application/ApplicationDelegate.mm
Ladybird/AppKit/UI/TabController.h
Ladybird/AppKit/UI/TabController.mm

(cherry picked from commit 98e1ae49f5288c9f25ad018b13b106369af8f75c)
---
https://github.com/LadybirdBrowser/ladybird/pull/528

Cherry-pick "Ladybird/AppKit: Add actions to set navigator compatibility mode"

---

Userland/Libraries/LibWeb/DOM/Document.cpp

Previously, the find in page function would fail to find text which was split across multiple text nodes. For example, given the following markup: `WH<span>F` the query `WHF` would previously fail to be matched.
This is done by traversing all of the document's text nodes - constructing a complete string to query against and keeping track of the locations where that string is split across multiple nodes.
(cherry picked from commit ec4d29849dc1d0357c73690722aea1a7802dd0bc)
---
https://github.com/LadybirdBrowser/ladybird/pull/156

Cherry-pick "LibWeb: Support finding text split across multiple text nodes"

---

Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Services/WebContent/ConnectionFromClient.cpp

https://github.com/LadybirdBrowser/ladybird/pull/171

Cherry-pick "LibWeb: Rerun find in page query when navigating between URLs"

---

Meta/CMake/ca_certificates_data.cmake
Meta/CMake/public_suffix.cmake

(cherry picked from commit 9af91eb6228831570bef59bfd9bf0ef46d140382)
---
https://github.com/LadybirdBrowser/ladybird/pull/60

Cherry-pick "Meta: ENABLE_NETWORK_DOWNLOADS for ca_certificates and public_suffix"

---

Tests/LibWeb/Text/expected/HTML/Window-find.txt
Tests/LibWeb/Text/input/HTML/Window-find.html
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/HTML/Window.idl
Userland/Libraries/LibWeb/Layout/Viewport.cpp
Userland/Libraries/LibWeb/Layout/Viewport.h
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h

https://github.com/LadybirdBrowser/ladybird/pull/216
https://github.com/LadybirdBrowser/ladybird/pull/262
https://github.com/LadybirdBrowser/ladybird/pull/293
https://github.com/LadybirdBrowser/ladybird/pull/311

Cherry-pick a few find-in-page-related PRs

---

Ladybird/Qt/Application.cpp
Ladybird/Qt/Application.h
Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/main.cpp
Ladybird/WebDriver/main.cpp

https://github.com/LadybirdBrowser/ladybird/pull/187

Cherry-pick "UI/Qt+WebDriver: Add --allow-popups option and make WebDriver use it"

---

Ladybird/Qt/AutoComplete.cpp
Ladybird/Qt/AutoComplete.h

https://github.com/LadybirdBrowser/ladybird/pull/299

Cherry-pick "UI/Qt: Reduce flicker when populating autocomplete"

---

Userland/Libraries/LibJS/Lexer.cpp
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h
Userland/Libraries/LibJS/Token.h

https://github.com/LadybirdBrowser/ladybird/pull/1247

Cherry-pick "LibJS: Make JS lexer handle 2 and 3 character tokens faster"

---

Ladybird/AppKit/UI/Event.mm
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/Page/EventHandler.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1284

Cherry-pick "LibWeb: Selection improvements for editable text nodes"

---

Meta/Lagom/ClangPlugins/LibJSGCPluginAction.cpp
Userland/Libraries/LibJS/Heap/Cell.h
Userland/Libraries/LibWeb/HTML/DragEvent.cpp
Userland/Libraries/LibWeb/HTML/DragEvent.h

Not the CI part thought – just the DragEvent missing visit really.
---
https://github.com/LadybirdBrowser/ladybird/pull/837

Cherry-pick two commits from "CI: Enable Clang plugins for Linux Clang job"

---

Tests/LibWeb/Text/expected/HTML/HTMLTrackElement-readyState-attribute.txt
Tests/LibWeb/Text/input/HTML/HTMLTrackElement-readyState-attribute.html
Userland/Libraries/LibWeb/HTML/HTMLTrackElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTrackElement.h
Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl

https://github.com/LadybirdBrowser/ladybird/pull/977

Cherry-pick "LibWeb: Implement HTMLTrackElement.readyState"

---

Userland/Utilities/xxd.cpp

The hex-value and the value are both colored with the same color depending upon the hex-value:
1. `0x00` = white
2. `0xFF` = blue
3. printable characters = green
4. tabs and linebreaks = yellow
5. non-printable characters = red

Utilities/xxd: Colorize output

---

Ladybird/AppKit/UI/Palette.mm
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h

https://github.com/LadybirdBrowser/ladybird/pull/1365

Cherry-pick "LibWeb: Some styling fixes for input[type=range]"

---

Tests/LibWeb/Text/expected/unclosed-body-element.txt
Tests/LibWeb/Text/expected/unclosed-html-element.txt
Tests/LibWeb/Text/input/unclosed-body-element.html
Tests/LibWeb/Text/input/unclosed-html-element.html
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp

https://github.com/LadybirdBrowser/ladybird/pull/894

Cherry-pick "LibWeb+LibWebView+WebContent: Some fixes for attributes with < in their names"

---

Tests/LibWeb/Text/expected/HTML/HTMLInputElement-cloning-steps.txt
Tests/LibWeb/Text/expected/HTML/HTMLTextAreaElement-cloning-steps.txt
Tests/LibWeb/Text/input/HTML/HTMLInputElement-cloning-steps.html
Tests/LibWeb/Text/input/HTML/HTMLTextAreaElement-cloning-steps.html
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h

https://github.com/LadybirdBrowser/ladybird/pull/1185

Cherry-pick "LibWeb: Implement cloning steps for HTMLInputElement and HTMLTextAreaElement"

---

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h

https://github.com/LadybirdBrowser/ladybird/pull/606

Cherry-pick "LibWeb: Add missing fetch step & update for spec change"

---

Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/Tab.cpp
Ladybird/Qt/Tab.h
Userland/Libraries/LibWeb/HTML/NavigatorID.cpp
Userland/Libraries/LibWeb/HTML/NavigatorID.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Userland/Libraries/LibWeb/Loader/UserAgent.h
Userland/Services/WebContent/ConnectionFromClient.cpp

https://github.com/LadybirdBrowser/ladybird/pull/347

Cherry-pick "LibWeb: Support Gecko and WebKit navigator compatibility modes"

---

Tests/LibWeb/Text/expected/DOM/FormAssociatedElement-setRangeText.txt
Tests/LibWeb/Text/input/DOM/FormAssociatedElement-setRangeText.html
Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
Userland/Libraries/LibWeb/Page/EventHandler.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1223

Cherry-pick "LibWeb: Implement setRangeText for input and textarea elements"

---

Tests/LibWeb/Layout/expected/flex/flex-column-reverse-constrained-wrap.txt
Tests/LibWeb/Layout/expected/flex/flex-constrained-wrap-reverse.txt
Tests/LibWeb/Layout/expected/flex/flex-item-on-row-with-intrinsic-size.txt
Tests/LibWeb/Layout/expected/flex/flex-item-percentage-main-size-during-min-content-sizing.txt
Tests/LibWeb/Layout/expected/flex/flex-row-reverse-constrained-wrap.txt
Tests/LibWeb/Layout/expected/flex/intrinsic-cross-size-contribution-with-main-size-constraint.txt
Tests/LibWeb/Layout/input/flex/flex-column-reverse-constrained-wrap.html
Tests/LibWeb/Layout/input/flex/flex-constrained-wrap-reverse.html
Tests/LibWeb/Layout/input/flex/flex-item-on-row-with-intrinsic-size.html
Tests/LibWeb/Layout/input/flex/flex-item-percentage-main-size-during-min-content-sizing.html
Tests/LibWeb/Layout/input/flex/flex-row-reverse-constrained-wrap.html
Tests/LibWeb/Layout/input/flex/intrinsic-cross-size-contribution-with-main-size-constraint.html
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Userland/Libraries/LibWeb/Layout/ImageBox.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1012
https://github.com/LadybirdBrowser/ladybird/pull/1154
https://github.com/LadybirdBrowser/ladybird/pull/1255
https://github.com/LadybirdBrowser/ladybird/pull/1650

Cherry-pick a few flex-related PRs

---

Meta/check-debug-flags.sh

This change updates the Meta/check-debug-flags.sh script to avoid an apparent Bach 3.2 parser bug. Specifically, it takes a comment and some code of a process substitution and moves it into a separate function.
Otherwise, without this change, trying to run the check-debug-flags.sh script with Bash 3.2 fails with the following error:
line 39: bad substitution: no closing `)' in <(
...apparently because Bash 3.2 chokes on the comment (and doesn’t choke if the comment is completely removed).
Relates to https://github.com/LadybirdBrowser/ladybird/issues/283
(cherry picked from commit 15d67f0da2083c0a39964f8fc6bdcbbd4907b2ed)
---
https://github.com/LadybirdBrowser/ladybird/pull/659

Cherry-pick "Meta: Make check-debug-flags.sh runnable in Bash 3.2"

---

Ladybird/AppKit/main.mm
Ladybird/HelperProcess.cpp
Ladybird/Qt/main.cpp
Ladybird/Types.h
Ladybird/WebContent/main.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp

https://github.com/LadybirdBrowser/ladybird/pull/248

Cherry-pick "LibWeb: Implement very basic in-memory HTTP caching"

---

Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.sort.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.add.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.and.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.compareExchange.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.exchange.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.or.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.sub.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.xor.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.copyWithin.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.reverse.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.toReversed.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.with.js
Userland/Libraries/LibJS/Tests/object-spread.js
Userland/Libraries/LibJS/Tests/test-common.js
Userland/Libraries/LibWeb/Layout/Viewport.cpp

https://github.com/LadybirdBrowser/ladybird/pull/49
https://github.com/LadybirdBrowser/ladybird/pull/531

Cherry-pick two ladybird PRs

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebContentView.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc

https://github.com/LadybirdBrowser/ladybird/pull/368

Cherry-pick "LibWeb+UI/Qt: Display 'title' tooltips only when the mouse stops moving"

---

Tests/LibWeb/Text/expected/HTML/a-element-set-protocol-on-href.txt
Tests/LibWeb/Text/input/HTML/a-element-set-protocol-on-href.html
Userland/Libraries/LibJS/Console.cpp
Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/Layout/LineBox.cpp
Userland/Libraries/LibWebView/InspectorClient.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1007
https://github.com/LadybirdBrowser/ladybird/pull/1009
https://github.com/LadybirdBrowser/ladybird/pull/1016
https://github.com/LadybirdBrowser/ladybird/pull/1013
https://github.com/LadybirdBrowser/ladybird/pull/1001

Cherry-pick 5 ladybird PRs

---

Userland/Libraries/LibWebView/SourceHighlighter.cpp

The behavior chosen here (fixed-width counters, alignment, etc.) matches Firefox.
(cherry picked from commit c1b0e180ba64d2ea7e815e2c2e93087ae9a26500)
---
https://github.com/LadybirdBrowser/ladybird/pull/892

Cherry-pick "LibWebView: Insert line numbers before each line in about:srcdoc"

---

Tests/LibWeb/Layout/expected/svg/inline-svg-with-zero-intrinsic-size-and-no-viewbox.txt
Tests/LibWeb/Text/expected/HTML/HTMLProgressElement-set-attributes.txt
Tests/LibWeb/Text/expected/css/attribute-selector-case-sensitivity.txt
Tests/LibWeb/Text/input/HTML/HTMLProgressElement-set-attributes.html
Tests/LibWeb/Text/input/css/attribute-selector-case-sensitivity.html
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/AttributeNames.h
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/HTML/Canvas/CanvasFilters.idl
Userland/Libraries/LibWeb/HTML/Canvas/CanvasShadowStyles.idl
Userland/Libraries/LibWeb/HTML/Canvas/CanvasUserInterface.idl
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
Userland/Libraries/LibWeb/HTML/CrossOrigin/Reporting.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContext.idl
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextOverloads.idl
Userland/Services/WebContent/PageClient.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1118
https://github.com/LadybirdBrowser/ladybird/pull/1116
https://github.com/LadybirdBrowser/ladybird/pull/1115
https://github.com/LadybirdBrowser/ladybird/pull/1098
https://github.com/LadybirdBrowser/ladybird/pull/1028

Cherry-pick 5 ladybug PRs

---

Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt
Tests/LibWeb/Layout/expected/flex/justify-content-1.txt
Tests/LibWeb/Layout/expected/flex/justify-content-with-margin-auto-child.txt
Tests/LibWeb/Layout/expected/grid/fit-content-2.txt
Tests/LibWeb/Layout/expected/grid/fit-content-3.txt
Tests/LibWeb/Layout/expected/grid/fixed-tracks-followed-by-repeat-auto-fill.txt
Tests/LibWeb/Layout/expected/grid/justify-content.txt
Tests/LibWeb/Layout/expected/grid/justify-items.txt
Tests/LibWeb/Layout/expected/grid/justify-self.txt
Tests/LibWeb/Layout/expected/grid/min-height-from-text.txt
Tests/LibWeb/Layout/expected/grid/restart-fr-algorithm-if-less-than-base-size.txt
Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-justify-content.html
Tests/LibWeb/Layout/input/flex/justify-content-1.html
Tests/LibWeb/Layout/input/flex/justify-content-with-margin-auto-child.html
Tests/LibWeb/Layout/input/grid/fit-content-3.html
Tests/LibWeb/Layout/input/grid/fixed-tracks-followed-by-repeat-auto-fill.html
Tests/LibWeb/Layout/input/grid/justify-content.html
Tests/LibWeb/Layout/input/grid/justify-items.html
Tests/LibWeb/Layout/input/grid/justify-self.html
Tests/LibWeb/Layout/input/grid/min-height-from-text.html
Tests/LibWeb/Layout/input/grid/restart-fr-algorithm-if-less-than-base-size.html
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

https://github.com/LadybirdBrowser/ladybird/pull/1232
https://github.com/LadybirdBrowser/ladybird/pull/1279
https://github.com/LadybirdBrowser/ladybird/pull/1334
https://github.com/LadybirdBrowser/ladybird/pull/1348
https://github.com/LadybirdBrowser/ladybird/pull/1338

Cherry-pick 5 grid-related ladybird PRs

---

Tests/LibWeb/Text/expected/css/calc-missing-context.txt
Tests/LibWeb/Text/input/css/calc-missing-context.html
Userland/Libraries/LibWeb/CSS/Length.h
Userland/Libraries/LibWeb/CSS/StyleValues/CSSMathValue.cpp

(cherry picked from commit 4408ea7c9be1b3faefb5d68871ddd60f912a431b)
---
https://github.com/LadybirdBrowser/ladybird/pull/1827

Cherry-pick "LibWeb: Handle calculations without a context better"

---

Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn

Added in 7d4fd29673a375c5 in #25322.

Meta: Add ConsoleObjectPrototype.cpp to GN build

---

Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.cpp
Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.h
Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.idl

https://github.com/LadybirdBrowser/ladybird/pull/1196

Cherry-pick "LibWeb: Implement ServiceWorkerContainer.on{message,messageerror}"

---

Userland/Applications/Screenshot/MainWindow.cpp
Userland/Applications/Screenshot/MainWindow.h
Userland/Applications/Screenshot/Screenshot.gml

Screenshot: Add checkbox to copy screenshot to clipboard

---

Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/Tab.cpp
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebContentView.h
Tests/LibWeb/Layout/expected/srcset-sizes-crash.txt
Tests/LibWeb/Layout/input/srcset-sizes-crash.html
Tests/LibWeb/Text/expected/console/console-to-string-tag.txt
Tests/LibWeb/Text/input/console/console-to-string-tag.html
Userland/Libraries/LibJS/Runtime/ConsoleObject.cpp
Userland/Libraries/LibWasm/Parser/Parser.cpp
Userland/Libraries/LibWasm/Types.h
Userland/Libraries/LibWeb/HTML/SourceSet.cpp

~~https://github.com/LadybirdBrowser/ladybird/pull/1002~~
~~https://github.com/LadybirdBrowser/ladybird/pull/1003~~
https://github.com/LadybirdBrowser/ladybird/pull/1008
~~https://github.com/LadybirdBrowser/ladybird/pull/1021~~
https://github.com/LadybirdBrowser/ladybird/pull/1022
~~https://github.com/LadybirdBrowser/ladybird/pull/1026~~
https://github.com/LadybirdBrowser/ladybird/pull/1015
https://github.com/LadybirdBrowser/ladybird/pull/1047
https://github.com/LadybirdBrowser/ladybird/pull/1045
https://github.com/LadybirdBrowser/ladybird/pull/1046

Cherry-pick 6 ladybird PRs

---

AK/StackInfo.cpp
Ladybird/AppKit/UI/TabController.mm
Userland/Libraries/LibCore/ThreadEventQueue.cpp
Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/ClassFieldDefinition.h
Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/ErrorConstructor.cpp
Userland/Libraries/LibJS/Runtime/ErrorConstructor.h
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Value.cpp
Userland/Libraries/LibJS/Runtime/Value.h
Userland/Libraries/LibJS/Tests/builtins/Error/Error.isError.js
Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.replace.js
Userland/Services/WebContent/ConnectionFromClient.cpp

https://github.com/LadybirdBrowser/ladybird/pull/2255
https://github.com/LadybirdBrowser/ladybird/pull/2265
https://github.com/LadybirdBrowser/ladybird/pull/2268

Cherry-pick 3 ladybird PRs

---

Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibTLS/TLSv12.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Userland/Libraries/LibWebView/UserAgent.cpp
Userland/Libraries/LibWebView/UserAgent.h

https://github.com/LadybirdBrowser/ladybird/commit/fce4739d3eab2c88e432c74590a3cc200664a392
https://github.com/LadybirdBrowser/ladybird/commit/a2a9a11466aba1ab357922e8bd0338222e3f4179
https://github.com/LadybirdBrowser/ladybird/commit/5056bda043984953685bb4284fc698ab42418045
https://github.com/LadybirdBrowser/ladybird/commit/ac48222ed7b497b13343ec79a234ba432ffd29e2
https://github.com/LadybirdBrowser/ladybird/commit/56e1c0e7eec813c311c41696063a3a31b4b14f0d

Cherry-pick 5 sneaky PR-less ladybird commits

---

Meta/check-idl-files.py
Meta/lint-ci.sh
Userland/Libraries/LibWeb/CSS/AnimationEvent.idl
Userland/Libraries/LibWeb/CSS/CSSAnimation.idl
Userland/Libraries/LibWeb/CSS/CSSTransition.idl
Userland/Libraries/LibWeb/Crypto/CryptoKey.idl
Userland/Libraries/LibWeb/Crypto/SubtleCrypto.idl
Userland/Libraries/LibWeb/HTML/CloseWatcher.idl
Userland/Libraries/LibWeb/HTML/HTMLAllCollection.idl
Userland/Libraries/LibWeb/HTML/HashChangeEvent.idl
Userland/Libraries/LibWeb/HTML/ImageData.idl
Userland/Libraries/LibWeb/HTML/PopStateEvent.idl
Userland/Libraries/LibWeb/NavigationTiming/PerformanceNavigation.idl
Userland/Libraries/LibWeb/SVG/SVGAnimatedTransformList.idl
Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.idl
Userland/Libraries/LibWeb/SVG/SVGLinearGradientElement.idl
Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.idl
Userland/Libraries/LibWeb/SVG/SVGSVGElement.idl
Userland/Libraries/LibWeb/SVG/SVGStopElement.idl
Userland/Libraries/LibWeb/SVG/SVGStyleElement.idl
Userland/Libraries/LibWeb/SVG/SVGTransformList.idl
Userland/Libraries/LibWeb/SVG/SVGUseElement.idl
Userland/Libraries/LibWeb/Streams/ReadableStream.idl

https://github.com/LadybirdBrowser/ladybird/pull/1358

Cherry-pick "Meta: Add script for checking WebIDL files"

---

Userland/Libraries/LibJS/Contrib/Test262/262Object.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.h
Userland/Libraries/LibJS/Runtime/Realm.cpp
Userland/Libraries/LibJS/Runtime/Realm.h
Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
Userland/Libraries/LibJS/Runtime/ShadowRealm.h
Userland/Libraries/LibJS/Runtime/ShadowRealmConstructor.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/Runtime/WrappedFunction.cpp
Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h

https://github.com/LadybirdBrowser/ladybird/pull/1927
https://github.com/LadybirdBrowser/ladybird/pull/2116

Cherry-pick 2 ladybird PRs

---

Meta/Lagom/ClangPlugins/LibJSGCPluginAction.cpp
Userland/Libraries/LibJS/Heap/GCPtr.h
Userland/Libraries/LibJS/Heap/Heap.cpp
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Tests/syntax/slash-after-block.js
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h

https://github.com/LadybirdBrowser/ladybird/pull/2286
https://github.com/LadybirdBrowser/ladybird/pull/2287, first 3 commits

Cherry-pick 1.75 ladybird PRs

---

Userland/Libraries/LibWeb/CSS/FontFace.h
Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
Userland/Libraries/LibWeb/CSS/FontFaceSet.h

https://github.com/LadybirdBrowser/ladybird/pull/1539
https://github.com/LadybirdBrowser/ladybird/pull/1613

Cherry-pick 2 ladybird FontFaceSet PRs

---

Tests/LibWasm/test-wasm.cpp
Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
Userland/Libraries/LibWasm/AbstractMachine/Configuration.cpp
Userland/Libraries/LibWasm/AbstractMachine/Configuration.h
Userland/Libraries/LibWasm/Printer/Printer.cpp
Userland/Libraries/LibWasm/Printer/Printer.h
Userland/Libraries/LibWasm/WASI/Wasi.cpp
Userland/Libraries/LibWeb/WebAssembly/Table.cpp
Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
Userland/Utilities/wasm.cpp

https://github.com/LadybirdBrowser/ladybird/pull/960

Cherry-pick "LibWasm: Bytecode interpreter performance pack"

---

Ports/AvailablePorts.md
Ports/lolcat/package.sh
Ports/lolcat/patches/0001-Remove-unnecessary-headers.patch
Ports/lolcat/patches/ReadMe.md

Ports: Add lolcat

---

AK/JsonParser.cpp
Tests/AK/TestJSON.cpp
Userland/Libraries/LibWeb/WebDriver/Client.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1546

Cherry-pick "AK+LibWeb: A mix of bug fixes and performance improvements for WebDriver", first 3 commits

---

Tests/LibURL/TestURL.cpp
Userland/Libraries/LibURL/Parser.cpp
Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h

https://github.com/LadybirdBrowser/ladybird/pull/1879

Cherry-pick "LibWeb+LibURL: Use correct encoding for URL fragments"

---

Meta/Lagom/CMakeLists.txt
Userland/Libraries/LibCore/System.cpp

https://github.com/LadybirdBrowser/ladybird/pull/71, last two commits (we don't want the first three)

Cherry-pick 2 ladybird commits

---

Ladybird/AppKit/Application/ApplicationBridge.cpp
Ladybird/HelperProcess.cpp
Ladybird/HelperProcess.h
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/main.cpp
Ladybird/WebDriver/main.cpp
Ladybird/WebWorker/CMakeLists.txt
Ladybird/WebWorker/main.cpp
Tests/LibWeb/WPT/run.sh

https://github.com/LadybirdBrowser/ladybird/pull/441
---
Not something we really want to use long-term, but it helps with cherry-picking, and upstream has removed this again, so we'll get to that eventually too.

Cherry-pick "WebDriver: Add option to use Qt networking"

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/Tab.cpp
Meta/gn/secondary/Userland/Libraries/LibSyntax/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
Userland/Libraries/LibWeb/HTML/SyntaxHighlighter/SyntaxHighlighter.cpp
Userland/Libraries/LibWeb/HTML/SyntaxHighlighter/SyntaxHighlighter.h
Userland/Libraries/LibWebView/CMakeLists.txt
Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Libraries/LibWebView/SourceHighlighter.cpp
Userland/Libraries/LibWebView/SourceHighlighter.h

https://github.com/LadybirdBrowser/ladybird/pull/1513

Cherry-pick "LibWebView: Use LibSyntax for view-source highlighting, so CSS and JS get highlighted!

---

Tests/LibRegex/Regex.cpp
Userland/Libraries/LibRegex/RegexOptimizer.cpp
Userland/Libraries/LibWeb/HTML/History.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/Selection/Selection.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1144
https://github.com/LadybirdBrowser/ladybird/pull/2380
https://github.com/LadybirdBrowser/ladybird/pull/2367
https://github.com/LadybirdBrowser/ladybird/pull/2396

Cherry-pick 4 ladybird PRs

---

Meta/lb-cherry-picks.py

Also implement a consistency check for never_merge_commits, and move one commit from it to never_merge_prs that was failing that check.

Meta: Add more commits and PRs to lb-cherry-picks.py

---

Tests/LibWeb/Text/expected/HTML/MessagePort-MessageEvents-should-be-trusted.txt
Tests/LibWeb/Text/expected/HTML/Window-MessageEvents-should-be-trusted.txt
Tests/LibWeb/Text/input/HTML/MessagePort-MessageEvents-should-be-trusted.html
Tests/LibWeb/Text/input/HTML/Window-MessageEvents-should-be-trusted.html
Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp

https://github.com/LadybirdBrowser/ladybird/pull/2366

Cherry-pick "LibWeb: Make MessageEvents from {Window,MessagePort}.postMessage trusted"

---

Tests/LibWeb/Text/expected/canvas/pattern-from-video.txt
Tests/LibWeb/Text/input/canvas/pattern-from-video.html
Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.cpp
Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.h
Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.idl
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h

(cherry picked from commit abe1172d7097ddae2aff2ddd839b96ed90ba7a13)
---
https://github.com/LadybirdBrowser/ladybird/pull/1635

Cherry-pick "LibWeb: Make HTMLVideoElement part of CanvasImageSource union"

---

AK/FlyString.cpp
AK/FlyString.h
AK/String.cpp
AK/String.h
Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn
Tests/AK/TestString.cpp
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CSSColor.h
Userland/Libraries/LibWeb/CSS/StyleValues/CSSColorValue.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
Userland/Libraries/LibWeb/DOM/ParentNode.cpp
Userland/Libraries/LibWeb/FileAPI/Blob.cpp
Userland/Libraries/LibWeb/HTML/DataTransfer.cpp
Userland/Libraries/LibWeb/HTML/DataTransferItemList.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Userland/Libraries/LibWeb/Infra/Strings.cpp

https://github.com/LadybirdBrowser/ladybird/pull/1796 2nd commit
https://github.com/LadybirdBrowser/ladybird/pull/2003
~~https://github.com/LadybirdBrowser/ladybird/pull/1915~~

Cherry-pick "LibWeb/CSS: Start parsing the color() function" + 1 prep commit

---

Kernel/CMakeLists.txt
Kernel/FileSystem/FATFS/Inode.cpp
Kernel/FileSystem/FATFS/Inode.h
Kernel/FileSystem/FATFS/SFNUtilities.cpp
Kernel/FileSystem/FATFS/SFNUtilities.h
Tests/Kernel/CMakeLists.txt
Tests/Kernel/TestSFNUtilities.cpp

This PR includes some more FATFS fixes, and also some tests for the SFN helpers (as discussed in #24976.)

Kernel/FATFS: More fixes + tests

---

Tests/LibWeb/Layout/expected/grid/align-content.txt
Tests/LibWeb/Layout/expected/grid/justify-content-cols.txt
Tests/LibWeb/Layout/input/grid/align-content.html
Tests/LibWeb/Layout/input/grid/justify-content-cols.html
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

https://github.com/LadybirdBrowser/ladybird/pull/1593
https://github.com/LadybirdBrowser/ladybird/pull/1656

Cherry-pick "LibWeb/Layout: Implement justify-content for column spacing in grid", "LibWeb/Layout: Implement align-content for grid layout"

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FormattingContext.h
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.h
Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/TableFormattingContext.h

https://github.com/LadybirdBrowser/ladybird/pull/1367

Cherry-pick "LibWeb: Skip abspos boxes layout in intrinsic sizing mode"

---

Meta/gn/secondary/Userland/Libraries/LibWeb/WebDriver/BUILD.gn
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/UIEvents/MouseButton.h
Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
Userland/Libraries/LibWeb/WebDriver/Actions.cpp
Userland/Libraries/LibWeb/WebDriver/Actions.h
Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp
Userland/Libraries/LibWeb/WebDriver/ElementReference.h
Userland/Libraries/LibWeb/WebDriver/InputSource.cpp
Userland/Libraries/LibWeb/WebDriver/InputSource.h
Userland/Libraries/LibWeb/WebDriver/InputState.cpp
Userland/Libraries/LibWeb/WebDriver/InputState.h
Userland/Libraries/LibWeb/WebDriver/Properties.h
Userland/Services/WebContent/WebDriverConnection.cpp
Userland/Services/WebContent/WebDriverConnection.h
Userland/Services/WebContent/WebDriverServer.ipc
Userland/Services/WebDriver/Client.cpp
Userland/Services/WebDriver/Session.cpp
Userland/Services/WebDriver/Session.h
Userland/Services/WebDriver/WebContentConnection.cpp
Userland/Services/WebDriver/WebContentConnection.h

https://github.com/LadybirdBrowser/ladybird/pull/1546, 4th commit (first 3 were in #25391)
https://github.com/LadybirdBrowser/ladybird/pull/1566

Cherry-pick 1.25 ladybird PRs

---

Ladybird/HelperProcess.cpp
Userland/Libraries/LibIPC/File.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/PageHost.h
Userland/Services/WebContent/WebContentClient.ipc

https://github.com/LadybirdBrowser/ladybird/pull/233 commits 1 and 4
https://github.com/LadybirdBrowser/ladybird/pull/284 commits 1 and 3
(In both cases, we very likely don't want all of the commits, but these look harmless and apply cleanly.)

Cherry-pick 4 ladybird commits

---

Userland/Libraries/LibGfx/TextLayout.cpp
Userland/Libraries/LibJS/Lexer.cpp
Userland/Libraries/LibRegex/RegexByteCode.cpp
Userland/Libraries/LibUnicode/CharacterTypes.cpp
Userland/Libraries/LibUnicode/CharacterTypes.h
Userland/Libraries/LibUnicode/Emoji.cpp
Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp

Kind of cherry-picks the API changes of the first 2 commits of https://github.com/LadybirdBrowser/ladybird/pull/239/ (but not the ICU dep). See commit description for details. No behavior change.

LibUnicode: Tweak property and general category APIs a bit

---

Tests/LibWeb/TestFetchURL.cpp
Tests/LibWeb/TestMimeSniff.cpp
Userland/Libraries/LibWeb/Clipboard/Clipboard.cpp
Userland/Libraries/LibWeb/Fetch/Body.cpp
Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
Userland/Libraries/LibWeb/Fetch/Infrastructure/URL.cpp
Userland/Libraries/LibWeb/FileAPI/Blob.cpp
Userland/Libraries/LibWeb/FileAPI/File.cpp
Userland/Libraries/LibWeb/FileAPI/FileReader.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
Userland/Libraries/LibWeb/MimeSniff/MimeType.h
Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
Userland/Libraries/LibWeb/MimeSniff/Resource.h
Userland/Libraries/LibWeb/Page/DragAndDropEventHandler.cpp
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.h

https://github.com/LadybirdBrowser/ladybird/pull/1796/
commit 2 was in #25436. commit 1 needs some more cleanups in serenity, so I'll put it in a dedicated PR.

Cherry-pick "AK+LibWeb: Mixed bag of tiny-OOM-propagation removal", commits 3-8

---

Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp

computed type != supplied type
(cherry picked from commit 47992f7b39a69cbb927d281cdfd3e818af068bde)
---
https://github.com/LadybirdBrowser/ladybird/pull/2207

Cherry-pick "LibWeb: Compute mimetype when loading a document"

---

Tests/LibWeb/Text/expected/localStorage.txt
Tests/LibWeb/Text/input/localStorage.html
Userland/Libraries/LibWeb/HTML/Storage.cpp
Userland/Libraries/LibWeb/HTML/Storage.h

https://github.com/LadybirdBrowser/ladybird/pull/1846

Cherry-pick "LibWeb: Implement indexed property support for HTML::Storage"

---

Meta/Lagom/CMakeLists.txt

Meta: Add serenity sed to lagom

---

Ports/bash/package.sh

No version update, just add menu entry of Bash

Ports: Add bash to menu entry

---

Ports/zsh/package.sh

No version update, just add Zsh to menu entry

Ports: Add Zsh to menu entry

---

Ports/tcl/package.sh

Add menu entry for Tcl. No change in current version.

Ports: Add menu entry for Tcl

---

Ports/lua/package.sh

No change in current version. Just added the menu entry.

Ports: Add menu entry for Lua

---

Userland/Libraries/LibGfx/GlassWindowTheme.cpp

This patch clips any parts of the frame gradient obscured by the window contents.

LibGfx: Improve glass window theme performance

---

Userland/Applications/ThemeEditor/CMakeLists.txt
Userland/Applications/ThemeEditor/MainWidget.cpp
Userland/Applications/ThemeEditor/MainWidget.h
Userland/Applications/ThemeEditor/WindowThemeProperty.gml
Userland/Libraries/LibGUI/Variant.h
Userland/Libraries/LibGfx/Palette.h

This PR adds the "WindowTheme" property to the general section and the "TitleButtonInactiveAlpha" property to the "Inactive Window" section.

ThemeEditor: Add new system theme properties 

---

Userland/Libraries/LibCrypto/Hash/SHA1.cpp
Userland/Libraries/LibCrypto/Hash/SHA2.cpp

in portable version of SHA-1, SHA-256 and SHA-512.

LibCrypto: Smaller stack usage

---

Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp

Remember more data during first pass to reduce recomputation in second pass.
(This isn't a performance thing: The motivation is that the two loops had some repetitive setup code, and this way we repeat it less.)

LibGfx/JPEG2000: Slightly reorganize read_one_packet_header()

---

Kernel/Devices/GPU/VirtIO/Console.cpp
Kernel/Devices/GPU/VirtIO/GraphicsAdapter.cpp

The old timeout was too small when running in QEMU inside VirtualBox.

Kernel/VirtIOGPU: Increase the command timeout to 200 ms

---

Kernel/Bus/USB/USBDevice.cpp
Kernel/Bus/USB/xHCI/xHCIController.cpp

My keyboard responds with STALLs when issuing a SET_INTERFACE request.

Kernel/USB: Handle SET_INTERFACE STALLs

---

Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.h
Userland/Libraries/LibPDF/Filter.cpp

LibGfx/CCITT: Support byte-aligned EOFB

---

Tests/LibPDF/CMakeLists.txt
Tests/LibPDF/shade-function.pdf
Userland/Libraries/LibPDF/Shading.cpp

I haven't seen these in the wild at all, but they're easy to implement and it's fun way to write some (subset of) postscript code to generate graphics :)

LibPDF: Implement support for function-based shadings

---

CMakeLists.txt
Documentation/AdvancedBuildInstructions.md
Meta/build-image-grub-uefi.sh

This script is mostly based on build-image-grub.sh.
Unlike that script, it uses the EFIPrekernel instead of the multiboot
prekernel.

Meta: Add a script for building x86-64 UEFI GRUB disk images

---

Kernel/FileSystem/FATFS/FileSystem.cpp
Kernel/FileSystem/FATFS/FileSystem.h
Kernel/FileSystem/FATFS/Inode.cpp
Kernel/FileSystem/FATFS/Inode.h

This should improve performance across the board, as operations such as traversing directories (especially those containing large files), truncating and writing should now be much more efficient.

Kernel/FATFS: Various performance improvements

---

Userland/Utilities/mkfs.fat.cpp

We really only need to make sure that all reserved sectors, the FAT region, and the root directory sectors/cluster are empty, and the total disk space used by these structures is usually significantly less than 34 MiB.

mkfs.fat: Don't wipe the first 34 MiB if we don't need to

---

Ports/llvm/package.sh

Looks like this was missed in #25757

Ports: Update LLVM sha256sum

---

AK/FixedArray.h
Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/PortableFormatWriter.cpp
Userland/Libraries/LibMedia/Video/VP9/Context.h
Userland/Libraries/LibMedia/Video/VP9/Parser.cpp
Userland/Libraries/LibPDF/Filter.cpp
Userland/Utilities/aconv.cpp

AK: Add an implicit conversion operator from FixedArray to Span

---

AK/SyncGenerator.h
Tests/AK/CMakeLists.txt
Tests/AK/TestSyncGenerator.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEG2000ProgressionIterators.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEG2000ProgressionIterators.h

Nico's commit but now powered by the proper asynchronous primitive!

LibGfx/JPEG2000: Use Generator for LRCP iterator

---

Ladybird/Qt/EventLoopImplementationQt.cpp
Ladybird/Qt/TabBar.h
Ladybird/Qt/main.cpp
Ladybird/RequestServer/main.cpp
Meta/CMake/common_compile_options.cmake
Meta/CMake/serenity_compile_options.cmake

I'm building this locally, but I haven't tried every combination either. So, while there are more stuff to share, I'm upstreaming commits one by one.
---
Related to #25759

Meta: Share a lot more warnings between Lagom and Serenity

---

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp

This was obviously very naive, pre-allocating the array makes it a lot faster (~1.56 times faster, on the JPEG XL logo image [1]).
Before:
Benchmark 1: image JPEGXL/logo.jxl --no-output
Time (mean ± σ):     922.2 ms ±  18.4 ms
Range (min … max):   891.9 ms … 945.4 ms    10 runs
After:
Benchmark 1: image JPEGXL/logo.jxl --no-output
Time (mean ± σ):     585.4 ms ±  10.0 ms
Range (min … max):   570.5 ms … 597.9 ms    10 runs
[1] https://jpegxl.info/old/logo.jxl

LibGfx/JPEGXL: Avoid allocations in the hot path

---

AK/ConstrainedStream.cpp
Tests/AK/CMakeLists.txt
Tests/AK/TestConstrainedStream.cpp

@timschumi as you added the equal in d1f6a28f

AK: Allow ConstrainedStream to discard bytes until the limit

---

Userland/Libraries/LibGfx/ImageFormats/JPEGXLChannel.h
Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp

These are the simplest commits from my dev branch, that I can also upstream without much context. They are all required for further progress but don't provide anything on their own.

LibGfx/JPEGXL: Handful of small patches

---

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp

LibGfx/JPEGXL: Compare both dimensions when checking the channel size

---

Userland/Libraries/LibGfx/ImageFormats/JPEGXLChannel.h
Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp

This PR finally allows us to decode this [image](https://github.com/libjxl/conformance/tree/master/testcases/delta_palette):

LibGfx/JPEGXL: Enough progress to decode a nice flower :^)

---

Userland/Libraries/LibGfx/ImageFormats/JPEGXLEntropyDecoder.cpp

Some entropy decoder have this option, of course the test image that I generated needs it :disappointed:.
The two functions are provided by the spec, so that was easy.

LibGfx/JPEGXL: Honor the use_mtf option when reading clustering maps

---

AK/SyncGenerator.h
Tests/AK/TestSyncGenerator.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEG2000ProgressionIterators.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEG2000ProgressionIterators.h

~~Testing system~~ CI is for ~~testing~~ doing CI (I didn't run even full Lagom test suite locally)

AK: Address SyncGenerator review comments from #25797

---

Tests/LibC/TestScanf.cpp
Userland/Libraries/LibC/scanf.cpp

Some OSS (e.g. cairo) require width specifiers to parse strings.

LibC: Support width specifiers for scanf

---

AK/Optional.h
AK/StdLibExtraDetails.h
Tests/AK/TestOptional.cpp
Tests/AK/TestSyncGenerator.cpp

This should finally fix the move count in TestSyncGenerator
---
@DanShaders
@ADKaster

AK: Better move for Optional

---

Userland/Libraries/LibGfx/Painter.cpp

This limits the subdivision of the curve to segments with length of at least ~0.5px. This prevents us from getting stuck endlessly splitting, and could also reduce segment count in some cases.
Fixes #23620

LibGfx: Limit curve split depth based on approximate curve length

---

Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp
Userland/Applications/DisplaySettings/ThemesSettingsWidget.cpp
Userland/Libraries/LibGUI/SettingsWindow.h

See commits for details. I was promoted to prod this from looking at #25859.

DisplaySettings: Fixes for some ancient regressions 

---

Userland/Libraries/LibC/inttypes.cpp
Userland/Libraries/LibC/inttypes.h

https://pubs.opengroup.org/onlinepubs/9699919799/functions/imaxabs.html

LibC: Add imaxabs

---

Userland/Utilities/lspci.cpp

Summary of changes:
- Use `TRY(buf.slice)` instead of `MUST(buf.slice)` in `read_hex_string_from_bytebuffer`
- Change `read_hex_string_from_bytebuffer` from returning `u32` to `ErrorOr<u32>`
- Check the optional returned by `AK::StringUtils::convert_to_uint_from_hex` and return an error if there is no result
- Wrap the calls to `read_hex_string_from_bytebuffer` in a `TRY`

lspci: Propagate errors

---

AK/Function.h

Previously, heap-allocated `CallableWrapper` objects were destroyed in a very roundabout way: `AK::Function` would call a virtual `destroy()` method, which then invoked delete manually. This was unnecessary, since `CallableWrapper` already has a virtual destructor — deleting it through a `CallableWrapperBase*` correctly calls the closure's destructor.
This fixes GCC `-Wfree-nonheap-object` false positive warnings (#4721) and coincidentally removes 8 KB of vtable entries (and the corresponding relative relocations) from LibJS.
(cherry picked from commit 33dbe385cec8edd62425d7d722082dcd907d5cd3)
---
Ref: https://github.com/LadybirdBrowser/ladybird/pull/4792
only removed the Block function parts

AK: Replace `CallableWrapper::destroy()` with a destructor

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/WebContentView.cpp
Meta/Lagom/Contrib/MacPDF/MacPDFView.mm

Cherry-picks the commit from https://github.com/LadybirdBrowser/ladybird/pull/1145 and the middle commit from https://github.com/LadybirdBrowser/ladybird/pull/294.

Cherry-pick two ladybird PRs and use CGColorSpaceCreateWithName(kCGColorSpaceSRGB) for MacPDF

---

AK/NoAllocationGuard.h
Userland/Libraries/LibC/assert.cpp
Userland/Libraries/LibC/bits/pthread_cancel.h
Userland/Libraries/LibC/bits/pthread_integration.h
Userland/Libraries/LibC/bits/utimens.h
Userland/Libraries/LibC/dlfcn.cpp
Userland/Libraries/LibC/libcinit.cpp
Userland/Libraries/LibC/malloc.cpp
Userland/Libraries/LibC/mallocdefs.h
Userland/Libraries/LibC/pthread.cpp
Userland/Libraries/LibC/pthread_tls.cpp
Userland/Libraries/LibC/sys/internals.h

LibC: Improve symbol visibility and naming consistency

---

Userland/Libraries/LibPDF/Shading.cpp

Plumb component bounds around and use them for clamping, which fixes three FIXMEs.
This is only needed because due to aliasing, the barycentric coordinates in GouraudPaintStyle sometimes create coefficents slightly below 0 or above 1. We used to just clamp function bounds to [0, 1], which does the wrong thing if those aren't the function bounds.

LibPDF: Clamp shading types 4-7 with functions to correct bounds

---

Documentation/BuildInstructions.md

Documentation: Update Ubuntu dependencies

---

Userland/Utilities/pdf.cpp

I merged `print_document_info_dict` and `print_document_info` into a single function (it seems cleaner).

pdf: Add --json for pdf no arg output

---

Tests/LibPDF/transform.pdf
Userland/Libraries/LibGfx/Path.cpp
Userland/Libraries/LibPDF/Renderer.cpp

...and other small tweaks :)
Fixes: https://github.com/SerenityOS/serenity/issues/25988

LibPDF: Transform paths before painting (rather at construction)

---

CONTRIBUTING.md

@kalenikaliaksandr @tcl3 Per your messages on Discord. Easy to add you back quickly when desired :)

Meta: Remove two inactive maintainers

---

Userland/Libraries/LibPDF/Renderer.cpp

LibPDF: Shorten Renderer::set_blend_mode() a bit with an IIFE

---

.github/FUNDING.yml

It only contained polar, and polar no longer has an issue bounty system.

Meta: Remove FUNDING.yml again

---

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp

No intended behavior change.
---
Quick follow-up to #26046 -- achieves the same fix with less and arguably easier-to-understand code.

LibGfx/JBIG2: Simplify composite_bitbuffer() a bit

---

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Userland/Utilities/image.cpp

I've been cherry-picking the 2nd one across branches locally for a while. Easier to just merge it.

LibGfx/JBIG2+image: Two teeny tiny tweaks

---

Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp

`take_first()` on a Vector is O(n), meaning this function used to have O(n^2) behavior in the width of an image.
We can just use a span instead, which can be be advanced in O(1) time.
Makes
pdf --debugging-stats ~/Downloads/ignition.pdf
go from 10.2s to 6.7s, 34% faster.
Makes the first 50 pages of
pdf --debugging-stats pdf-stuff/Mellor_ACTITC_10.pdf
go from 65.9s to 13.2s, 80% faster.
Fixes #26082.

LibGfx/CCITT: Make decoding of wide ccitt3-2d and ccitt-4 images faster

---

Kernel/Memory/MemoryManager.cpp
Kernel/Memory/MemoryManager.h

Just some small things I noticed while looking at MM code.

Kernel/MM: Miscellaneous cleanups

---

Tests/LibGfx/TestImageDecoder.cpp
Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp

Re-does #26097, and adds some spec comments.

LibGfx/JBIG2+Tests: Minor tweaks

---

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp

The self-predictor state is quite expensive to maintain, so try to skip the work when possible. Note that this includes both the 'max_error' property and the 'Self-correcting' predictor.
This gives us nice performance improvement on '2022-11-iceberg.jxl' (from the JXL art page):
Benchmark 1: Before
Time (mean ± σ):      1.260 s ±  0.008 s
Range (min … max):    1.251 s …  1.277 s    10 runs
Benchmark 1: After
Time (mean ± σ):      1.044 s ±  0.002 s
Range (min … max):    1.040 s …  1.047 s    10 runs

LibGfx/JPEGXL: Skip self-predictor computation when possible

---

Kernel/Bus/USB/UHCI/UHCIController.cpp
Kernel/Bus/USB/xHCI/xHCIController.cpp

I've occasionally been seeing crashes like the following when testing emulated x86_64 on macOS (which happen on both UHCI and xHCI since they use a very similar pattern), and finally got around to fixing them:
```
0.313 [#0 init_stage2(1:1)]: UHCI: Started
[UHCI Hot Plug Task(7:7)]: ASSERTION FAILED: !PtrTraits::is_null(bits)
[UHCI Hot Plug Task(7:7)]: Kernel/Library/LockRefPtr.h:447 in T *AK::LockRefPtr<Kernel::USB::Hub>::as_nonnull_ptr(FlatPtr) const [T = Kernel::USB::Hub, PtrTraits = AK::LockRefPtrTraits<Kernel::USB::Hub>]
[UHCI Hot Plug Task(7:7)]: KERNEL PANIC! :^(
[UHCI Hot Plug Task(7:7)]: Aborted
[UHCI Hot Plug Task(7:7)]: at Kernel/Library/Assertions.cpp:38 in void abort()
```
Tested with the following script (overwrites `Base/etc/SystemServer.ini`):
```sh
#!/bin/sh
set -eu
cat …
```

Kernel/USB: Avoid race conditions in hot plug tasks

---

Userland/Applications/FileManager/PropertiesWindow.cpp
Userland/Libraries/LibGfx/ImageFormats/DICOMLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/DICOMLoader.h

I won't share my test case here, and I don't know how to create a file with metadata (that being said, I haven't checked anything else than Gimp).

FileManager+LibGfx/DICOM: Display basic metadata for DICOM files

---

Userland/Libraries/LibShell/Builtin.cpp

LibShell: Don't forcefully make absolute paths relative in builtin_cd

---

Userland/Libraries/LibHTTP/Job.cpp

I ran into this while playing with clang's -Wunreachable-code-aggressive locally.
Before the last commit in #24513, there was a continue somewhere in the loop and the unconditional break-at-end-of-loop made sense.
After that change, looping until everything was flushed blocked all downloads.
Rewrite this as an if statement to make the intent more clear.

LibHTTP: Fix a -Wunreachable-code-loop-increment warning

---

Kernel/Tasks/WaitQueue.cpp

If the current thread unblocked itself, then the thread is effectively running, and not just runnable.
(Noticed this while looking at some WIP `FUSEDevice` stuff. Setting this to `Runnable` caused a kernel panic [here](https://github.com/SerenityOS/serenity/blob/97f470bc94478b12d98ff01085f68097cf0aa880/Kernel/Tasks/Thread.cpp#L136).)

Kernel: Handle unblocking properly in WaitQueue
