Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp

This is a subset of https://github.com/SerenityOS/serenity/pull/21484: Type 2 CFFs never use the special subrs,
so stop doing them for type 2 at least for now.
Fixes an assert in https://github.com/SerenityOS/serenity/commit/000006419712e266f149b80d173c6bb2ad1b3026.pdf in 0000.zip in the pdfa dataset
(a stack underflow because a subr is supposed to push a bunch of
stuff, but instead it ran one of the built-in routines instead of
the subr from the font file).
As discussed in https://github.com/SerenityOS/serenity/pull/21484, this isn't right for type 1 CFFs either,
but just removing the code there regresses Tests/LibPDF/type1.pdf.
A slightly more involved thing is needed there; I added a FIXME
for that here.
---
Also add a dbgln() call.
In addition to fixing an assert, also sometimes a …

LibPDF: Don't do special subr processing for type 2 CFFs

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.h

By moving it to a non-extended register instead of R13, we can use the ModR/M encoding without displacement for offset 0.
And the VM accumulator register is at offset 0, so this is *very* common. :^)

LibJS+LibJIT: Put VM register array base in RBX so we can access it without ModR/M displacement

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

Just a couple of random instructions that were showing up a lot in test-js compilation failures.

LibJS: Compile the NewBigInt & CallWithArgumentArray bytecode instructions

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

This code size optimization saves 2.08MiB on Kraken/ai-astar.js

LibJS/JIT: Consolidate exception handling code

---

Userland/Libraries/LibJS/JIT/Compiler.cpp

This fixes regression introduced in b2d8d0c270

LibJS/JIT: Fix crash in CallWithArgumentArray

---

Base/usr/share/man/man5/Shell.md
Userland/Shell/Parser.cpp
Userland/Shell/Parser.h

This stops the shell from always interpreting '#' as the start of a comment in non-Posix mode.
Fixes #21650.

Shell: Remove '#' from the list of acceptable bareword characters

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

This adds support for `ConcatString`, `CreateVariable` and `NewClass`.
Also includes a fix for a bug in exception handling, which was uncovered after implementing CreateVariable.

LibJS/JIT: Compile 3 more Instructions

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

This uses the 32-bit registers to perform the addition and bail if the overflow flag (OF) is set.

LibJS/JIT: Add fast path for Add Int32, Int32

---

Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp

After 4318bcf447ecb97b867af13dfcba1b72de107049 RecordingPainter is suppoed to write commands in coordinate system of stacking context.
This commit adds missing translation for FillRect command.

LibWeb/Painting: Fix translation for FIllRect command

---

Tests/LibWeb/Layout/expected/grid/floating-item.txt
Tests/LibWeb/Layout/input/grid/floating-item.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

Grid items with float property not equal to none should not be treated as "out of flow".

LibWeb: Inhibit floats in GFC

---

Tests/LibWeb/Text/expected/css/transform-origin-serialization.txt
Tests/LibWeb/Text/input/css/transform-origin-serialization.html
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp

Passing a value of a type different than number or length-percentage to transform-origin returned a null pointer, and we didn't take care of that path before.
This patch fixes a crash caused by an incorrect CSS declaration, such as `transform-origin: "center"`.
Fixes #21609

LibWeb: Bail parsing transform-origin if the parsed value is null

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp

While investigating some (unfruitful) micro-optimizations, I noticed that the jump conditions are determined according to (I believe) 4 bits of the opcode. We can leverage that to provide one function that uses an enum to implement all conditional jump instructions at once instead of creating individual functions for them, i.e.:
```cpp
m_assembler.jump_if(
Assembler::Operand::Register(dst),
Assembler::Condition::NotEqualTo,
Assembler::Operand::Imm(BOOLEAN_TAG),
slow_case);
```
The nibble that contains the condition of the jump instruction appears to also be consistent between `CMOVcc` and `SETcc`, so those can be implemented very easily using the same enum. I've created those locally, but since there are currently no uses for those instructions, I've omitted them here.

LibJIT/LibJS: Unify the multiple `jump_if_*()` functions into one `jump_if()`

---

Userland/Libraries/LibJIT/Assembler.h

This also widens the argument coverage of some helpers, to allow
memory offsets, this also consolidates the displacement size choosing.
This also stops us from some out argument ordering bugs, as we now just
need to look up the correct calling convention and call the correct
function.
This makes the code a bit more readable and in conjunction with the
ModRM helper should prevent some operand ordering bugs.
This also includes one incidental bugfix:
`sign_extend_32_to_64_bits`, was not setting the `REX.R` bit when
appropriate,
And one size obvious optimization:
We may now elide the REX prefix on `xor eax, eax` as storing to a 32 bit
register clears the upper 32 bit of said register, which is wanted here.
---
Lets see if Co-Pilot can handle this

LibJIT: Add and use helpers for ModRM byte and REX prefix emission

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h

This allows the JPEG fuzzer to make progress.

LibGfx/JPEG: Propagate errors when creating `JPEGLoadingContext`

---

Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

There are 5 instructions remaining:
- PushDeclarativeEnvironment: Never generated. Should this be deleted?
- Await & Yield: I'll leave those to someone more familiar with how the continuations work.
- EnterObjectEnvironment: I have an implementation, but it fails one test in test-js (with-basic/restores lexical environment even when exception is thrown)
- ScheduleJump: Somewhat complicated control flow, possibly affected by #21506 / #21653
I couldn't really test `GetMethod` and `AsyncIteratorClose`, since those rely on `Yield` being compilable.

LibJS/JIT: Compile 11 more bytecode instructions

---

Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

In most cases, this op will do nothing, as it is running on an the accumulator while it already contains a number. Let's avoid doing that native call.

LibJS: Add an inline JIT fast path when `ToNumeric` has nothing to do

---

Meta/Websites/man.serenityos.org/add-anchors.lua
Meta/build-manpages-website.sh

This is _somewhat_ similar to #21245, but for man pages.

Meta: Add anchors to headings of man pages

---

Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Enums.json
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.h
Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.cpp

This PR add support for the object-position property.
As I recently built the object-fit property, this seemed like a logical next step.
With object-position you can tell your image how you want to paint it, very useful in combination with the object-fit!
I introduced the object-position property and a "Position Identifier", which can hold the different identifiers that are valid for the property. The rendering is then just a sea of pain with offsets and pixel-math.
This implementation looks the same in Ladybird and Firefox :^)

LibWeb: Support Object-position CSS property

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/BasicBlock.cpp
Userland/Libraries/LibJS/Bytecode/BasicBlock.h
Userland/Libraries/LibJS/Bytecode/Executable.h
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibJS/Tests/try-finally-break.js

This PR implements static exception handler resolution for the LibJS JIT compiler on top of #21506.
As a side effect, the compiler becomes somewhat smaller. And also we no longer use one
of the registers.
Hope, I haven't interrupted someone's progress on this but this seemed
really interesting to implement... And also that's my first contribution :D
Depends on #21506

LibJS/JIT: Static unwinding

---

Userland/Libraries/LibJS/JIT/Compiler.cpp

The remaining difference compared to the Bytecode interpreter:
```
Summary:
Diff Tests:
-2 ✅   +2 ❌   
Diff Tests:
test/language/statements/try/S12.14_A13_T3.js                       ✅ -> ❌
test/language/statements/try/completion-values-fn-finally-normal.js ✅ -> ❌
```

LibJS/JIT: Fix most test262 regressions

---

Userland/Libraries/LibCrypto/Curves/SECP256r1.cpp
Userland/Libraries/LibCrypto/Curves/SECP256r1.h
Userland/Libraries/LibTLS/HandshakeClient.cpp
Userland/Libraries/LibTLS/HandshakeServer.cpp
Userland/Libraries/LibTLS/TLSv12.cpp
Userland/Libraries/LibTLS/TLSv12.h

This is a revival of @msvisser 's #13163
Now with cert validation!
Unfortunately this doesn't actually solve #21211, as https://rsms.me uses a SECP384r1 curve.
Work towards #14160
And probably other issues about ECDSA that have crept up over the years :)
cc @stelar7

LibTLS: Add certificate verification for ECDSA with SECP256r1 curves

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h

Noticed we were no longer getting the favicon for display on serenityos.org :^(
Before:
After:

LibWeb: Implement loading a favicon in absence of a <link> icon element

---

Tests/LibWeb/Layout/expected/css-namespace-tag-name-selector.txt
Tests/LibWeb/Layout/expected/svg-text-with-viewbox.txt
Tests/LibWeb/Layout/expected/svg/text-fill-none.txt
Tests/LibWeb/Layout/input/svg-text-with-viewbox.html
Tests/LibWeb/Ref/reference/simple-svg-mask-ref.html
Tests/LibWeb/Ref/simple-svg-mask.html
Tests/LibWeb/Ref/svg-alpha-mask.html
Tests/LibWeb/Ref/svg-mask-in-defs.html
Tests/LibWeb/Ref/svg-mask-maskUnits-userSpaceOnUse.html
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/SVGGeometryBox.cpp
Userland/Libraries/LibWeb/Layout/SVGGeometryBox.h
Userland/Libraries/LibWeb/Layout/SVGTextBox.cpp
Userland/Libraries/LibWeb/Layout/SVGTextBox.h
Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.cpp
Userland/Libraries/LibWeb/Painting/SVGGeometryPaintable.h
Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.h
Userland/Libraries/LibWeb/Painting/SVGTextPaintable.cpp
Userland/Libraries/LibWeb/Painting/SVGTextPaintable.h
Userland/Libraries/LibWeb/SVG/SVGTextContentElement.cpp
Userland/Libraries/LibWeb/SVG/SVGTextContentElement.h

Previously, both SVG `<text>` and geometry elements were doing some awkward hacks to do (or re-do) layout work during painting. Geometry elements would re-compute the transform applied during layout in a hacky way, and `<text>` had no layout computed, which meant they were zero-sized, and could not correctly compute the `viewBox` transform. 
This PR moves all the SVG text layout and sizing logic into the `SVGFormattingContext`, and the SVG path and transform state into the `LayoutState` and `Paintables`. So now text scales with the `viewBox` correctly, and SVG geometry layout is a little simpler. 
This should also make implementing relative-sized geometry elements (e.g. `width="50%"`), and future work on masking simpler.
---
Progression on MDN SVG `<text>` example (with a `viewBox` that …

LibWeb: Stop doing SVG layout during painting and get `<text>` elements to respect the `viewBox`

---

AK/Format.cpp
AK/Format.h
Tests/AK/TestFormat.cpp
Userland/Libraries/LibPDF/Document.h

Previously we assumed a default precision of 6, which made the printed values quite odd in some cases.
This commit changes that default to print them with just enough precision to produce the exact same float when roundtripped.
Samples (printed as `{:'28}`):
```
[src             ] old                          // new                         
[10.3f           ] 10.3                         // 10.3                        
[123e4f          ] 1,230,000                    // 1,230,000                   
[1.23e4f         ] 12,300                       // 12,300                      
[134232544.4365f ] 134,232,544                  // 134,232,540                 
[1.43e24         ] 9,223,372,036,854,775,808.000001 // 1.43e+24                    
[1.43e-24        ] 0                            // …
```

AK: Make AK::Format print floats in a roundtrip-safe way by default

---

Userland/Libraries/LibTLS/TLSv12.h

The ED curve is INTRINSIC/ED25519, not INTRINSIC/ECDSA
See https://datatracker.ietf.org/doc/html/rfc8422#section-5.1.3 for more info.

LibTLS: Fix supported signature algorithms typo

---

Documentation/AdvancedBuildInstructions.md
Meta/CMake/accelerated_graphics.cmake
Meta/CMake/common_options.cmake
Userland/Libraries/LibAccelGfx/CMakeLists.txt
Userland/Libraries/LibWeb/CMakeLists.txt

Also add a flag to turn off accelerated graphics entirely.
This uses <https://cmake.org/cmake/help/latest/module/FindOpenGL.html>

CMake: Use a helper file to find GL and EGL in a platform agonstic way

---

Userland/Libraries/LibGfx/Font/OpenType/Font.cpp

Previously, an offset that was equal to the size of the file would cause a crash.
Found through local fuzzing. The fuzzer was crashing on this a lot, so this fix will allow more progress to be made.

LibGfx/OpenType: Ensure offsets are strictly less than the file size

---

Userland/Applications/ClockSettings/TimeZoneSettingsWidget.cpp

The time zones were stored as a static Span until commit 0bc401a1d653f487738e05e8677dfe5167fc5a36, and are now stored in a Vector. By continuing to tell the ItemListModel that the container is a Span, we create a temporary Span in its constructor, which the model tries to hold a constant reference to. Use the default Vector container type now instead to prevent creating such temporaries.
Fixes #21710

ClockSettings: Use a Vector as the time zone model's container type

---

Tests/LibWeb/Layout/expected/table/table-max-content-width.txt
Tests/LibWeb/Layout/input/table/table-max-content-width.html
Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp

If the width of the table container is specified as max-content, then it seems sensible to resolve it as the sum of the maximum widths of the columns.
Visual progression on GitHub profile page.
Before:
After:

LibWeb: Set table width to GRIDMAX if calculated value is max-content

---

AK/FPControl.h
AK/FloatingPoint.h

The fun pattern of `union { struct { u32 a : 1; u64 b : 7; }; u8 x; }` produces complete garbage on windows, this commit fixes the two instances of those that exist in AK.
This commit also makes sure that the generated unions have the correct size (whereas FloatExtractor<f32> previously did not!) by adding some nice static_asserts.

AK: Ensure unions with bitfield structs actually have correct sizes

---

Userland/Games/FlappyBug/Game.cpp
Userland/Games/FlappyBug/Game.h

Previously we would display the score rounded to the nearest integer, but save the high score by using a static_cast<u32>, which would always round the score down. This could lead to the final score being higher than the new high score, when they should be equal. Now we always round the score to the nearest integer.
| What could happen before: |
| --- |
| ![obraz](https://github.com/SerenityOS/serenity/assets/36564831/75f6bd66-b80f-4937-9cd0-1864dc89edba) |

FlappyBug: Unify the way of getting the final score

---

Userland/DevTools/HackStudio/EditorWrapper.cpp
Userland/DevTools/HackStudio/EditorWrapper.h
Userland/DevTools/HackStudio/HackStudioWidget.cpp

This PR fixes two issues with the unsaved changes warning dialog in HackStudio:
1. When trying to run with unsaved changes, HackStudio asks about whether you want to save the changes. If you selected "Yes", but cancelled the file picker, HackStudio would crash, since we expected a file to be picked if the dialog was opened. Now, the action that triggered the save request is cancelled.
2. Running with unsaved changes previously didn't ask at all whether you want to save. It now follows the same behavior as when building.

HackStudio: Fix unsaved changes warning dialog behavior

---

Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp

This is the type 2 equivalent to type2 othersubr, from what I can tell.
See "4.1 Path Construction Operators" in 5177.Type2.pdf,
"The Type 2 Charstring Format".
Makes text show up alright on
https://developer.apple.com/library/archive/documentation/mac/pdf/Text.pdf

LibPDF: Implement type 2 flex, hflex, hflex1, flex1 operators

---

Userland/Libraries/LibPDF/ColorSpace.cpp

This code was advertised in #7675 / 3896a897168c as "This isn't tested all that well".
I'm not sure it's tested much more thoroughly now, but at least it manages to map 1, 1, 1 to white for https://developer.apple.com/library/archive/documentation/mac/pdf/Text.pdf :)

LibPDF: Improve CalRGB color space handling

---

Tests/LibWeb/Layout/expected/grid/item-with-box-sizing-border-box.txt
Tests/LibWeb/Layout/input/grid/item-with-box-sizing-border-box.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Visual improvement on (now there is a gap between grid items): https://twinings.co.uk/collections/earl-grey-tea

LibWeb: Account for box-sizing in grid-items width calculation

---

Meta/Lagom/Wasm/js_repl.cpp
Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
Userland/Applications/Spreadsheet/Spreadsheet.cpp
Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/JIT/NativeExecutable.cpp
Userland/Libraries/LibJS/JIT/NativeExecutable.h
Userland/Libraries/LibJS/Runtime/Error.cpp
Userland/Libraries/LibJS/Runtime/Error.h
Userland/Libraries/LibJS/Runtime/ExecutionContext.h
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibJS/Tests/builtins/Error/Error.prototype.stack.js
Userland/Libraries/LibWeb/HTML/Scripting/ExceptionReporter.cpp
Userland/Utilities/js.cpp

The previous implementation was calling `backtrace()` for every function call, which is quite slow.
I noticed while running `Kraken/imaging-gaussian-blur` which took ages.
With these changes it's back to ~20s on my machine.

LibJIT+LibJS+Embedders: Lazily collect stack traces

---

Userland/Libraries/LibAccelGfx/CMakeLists.txt
Userland/Libraries/LibAccelGfx/Context.cpp
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibAccelGfx/Program.cpp
Userland/Libraries/LibAccelGfx/Program.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Services/WebContent/PageHost.cpp
Userland/Services/WebContent/PageHost.h

With these changes besides rectangles we can paint images using accelerated painter.
Also there are rearrangements in the painter to compile all required shaders only once.

LibAccelGfx: Implement draw_scaled_bitmap()

---

Userland/Libraries/LibJS/Runtime/Error.cpp

We were trying to stringify the stack trace without the last element, leading to a loop bound of (size_t)(0 - 1) and accessing m_traceback[0] out-of-bounds.
Instead, just return an empty string in that case.
Fixes #21747

LibJS: Avoid crash on empty stack trace

---

Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/DOM/AccessibilityTreeNode.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/DOM/NonElementParentNode.h
Userland/Libraries/LibWeb/DOM/ShadowRoot.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/SVG/SVGElement.cpp
Userland/Libraries/LibWeb/SVG/SVGSymbolElement.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/WebDriverConnection.cpp

Noticed element ID attribute lookups in a profile, so I made a stress test to isolate some of the issues and burn them down.
The main solution to all the problems is basically to cache the `id` attribute value as an `Optional<FlyString>` on `Element`. This makes checking an element's ID O(1) instead of O(n), which is very useful in a number of places.
The stress test creates a 3000-deep DOM tree and runs two selectors against a bunch of the elements.
```
BEFORE:
Single descendant: 404ms
Double descendant: 744ms
AFTER:
Single descendant: 96ms
Double descendant: 112ms
```
So basically a 4x speed-up the single-descendant selector, and 6.5x on the double-descendant one.
Here's the stress test:
```html
<script>
document.addEventListener("DOMContentLoaded", function() {
let insertionPoint = …
```

LibWeb: Make element ID matching faster

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

We now use a dedicated physical register to store the bytecode accumulator, instead of loading and storing it to the memory everytime.
This results in a small speedup (up to 8%) in most Kraken tests, and no regression in the rest.
```
Suite    Test                                   Speedup  Old (Mean ± Range)        New (Mean ± Range)
-------  -----------------------------------  ---------  ------------------------  ------------------------
Kraken   ai-astar.js                              1.011  6.180 ± 6.150 … 6.200     6.110 ± 6.010 … 6.290
Kraken   audio-beat-detection.js                  1.051  3.900 ± 3.850 … 3.940     3.710 ± 3.670 … 3.750
Kraken   audio-dft.js                             1.01   3.273 ± 3.190 … 3.350     3.240 ± 3.200 … 3.270
Kraken   audio-fft.js …
```

LibJS: Store the bytecode accumulator in a dedicated physical register

---

Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibJS/JIT/NativeExecutable.cpp
Userland/Libraries/LibJS/JIT/NativeExecutable.h

This leaves 2 instructions to do: EnterObjectEnvironment & ScheduleJump

LibJS/JIT: Compile Await & Yield, remove PushDeclarativeEnvironment

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

Nice incremental speed-up across the Kraken tests:
```
Suite    Test                                   Speedup  Old (Mean ± Range)        New (Mean ± Range)
-------  -----------------------------------  ---------  ------------------------  ------------------------
Kraken   ai-astar.js                              1.028  3.500 ± 3.480 … 3.520     3.403 ± 3.390 … 3.430
Kraken   audio-beat-detection.js                  1.01   1.967 ± 1.940 … 1.980     1.947 ± 1.920 … 1.980
Kraken   audio-dft.js                             1.055  1.803 ± 1.800 … 1.810     1.710 ± 1.700 … 1.720
Kraken   audio-fft.js                             1.004  1.820 ± 1.800 … 1.830     1.813 ± 1.790 … 1.830
Kraken   audio-oscillator.js                      1.051  2.760 ± 2.720 … 2.780     2.627 ± 2.620 … 2.630
Kraken …
```

LibJS+LibJIT: Add fast paths for more binary ops with (Int32 op Int32)

---

Ports/php/package.sh

I'd say the majority of people who use PHP need CURL.

Ports/php: Enable curl

---

Userland/DevTools/HackStudio/Debugger/VariablesModel.cpp

Fixes #21642
Previously, we tried to store `VariableInfo` to `ModelIndex` internal data, but accidently stored address of wrapper class `NonnullOwnPtr`. When we retrieved it later in `VariablesModel::data()` it made program to crash.
This allows us to run debug normally after setting any break point in `HackStudio`.

HackStudio: Pass the correct `VariableInfo` address to `create_index`

---

Userland/Libraries/LibJS/Bytecode/Register.h
Userland/Libraries/LibJS/JIT/Compiler.cpp

This kills 2 birds with one stone:
1. It makes sure generated check_exception() calls in the finalizer don't mis-read the pending exception as caused by their matching operation.
2. It implicitly ensures that terminated finally blocks (by a return statement) overwrite any pending exceptions, since they will never execute the ContinuePendingUnwind operation that restores the stashed exception.
This additional logic is required in the JIT (as opposed to the interpreter), since the JIT uses the exception register to store and check the possibly-exceptional results from each individual operation, while the interpreter only modifies it when an operation has thrown an exception.

LibJS: Stash thrown exception in a register before executing finalizer 

---

Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Slottable.cpp

For example, on https://html.spec.whatwg.org/, there are hundreds of
thousands of nodes. Traversing the entire tree as each of them become
inserted takes a prohibitively long time.

LibWeb: Skip assigning slottables inserting nodes under non-shadow roots

---

Kernel/Syscalls/socket.cpp

From `listen(3p)`: "If listen() is called with a backlog argument value that is less than 0, the function behaves as if it had been called with a backlog argument value of 0."

Kernel: Allow negative value for backlog in sys$listen

---

Tests/LibWeb/Layout/expected/table/colgroup-with-two-cols.txt
Tests/LibWeb/Layout/input/table/colgroup-with-two-cols.html
Userland/Libraries/LibWeb/Layout/TableGrid.cpp
Userland/Libraries/LibWeb/Layout/TableGrid.h

We should take in account <col> elements in column groups while finding number of columns in a table.

LibWeb: Consider colgroups while calculating table grid size

---

Tests/LibWeb/Layout/expected/textnode-width-bitmap-font.txt
Tests/LibWeb/Layout/input/textnode-width-bitmap-font.html
Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp

When calculating the width of text using a SerenityOS bitmap font, a glyph spacing is added at the end of each fragment (so that adjacent fragments are properly spaced). This includes the last one, with no adjacent fragment, this meant that everything was 1 pixel too long. This bug did not affect vector fonts, and tests thus don't need to be rebaselined.

LibWeb: Fix width of text when using bitmap fonts being 1 pixel too long

---

AK/GenericLexer.cpp
AK/GenericLexer.h
Tests/AK/TestGenericLexer.cpp
Userland/Libraries/LibCore/DateTime.cpp
Userland/Libraries/LibCore/SystemServerTakeover.cpp

Let's not use this C API, we have better alternatives! This will also simply conversion to new a `String` in the future, since strtol requires null-terminated strings.

AK+LibCore: Remove calls to `strtol` in LibCore

---

Userland/Libraries/LibELF/ELFABI.h
Userland/Libraries/LibELF/Validation.cpp

This is part 1 of a long chain of PRs and commits that add RISC-V disassembly support. Today:
An almost-minimal patchset to get RISC-V ELF files to pass validation. Unlike other architectures, eflags are actually used here.

RISC-V disassembly, part 1/N: LibELF: Add initial RISC-V support

---

Userland/Services/NotificationServer/NotificationWindow.cpp
Userland/Services/NotificationServer/NotificationWindow.h

- NotificationServer: Make notifications not overlap when they appear
- NotificationServer: Don't shuffle notifications on first hover

NotificationServer: Two display fixes

---

Kernel/Net/TCPSocket.cpp

It seems like the current implementation returns 0 in case we do not have enough data for a whole packet yet. The 0 value gets propagated to the return value of the syscall which according to the spec should return non-zero values for non-errors cases. This causes panic, as there is a VERIFY guard checking that more than > 0 bytes are written if no error has occurred.
Fixes https://github.com/SerenityOS/serenity/issues/21320

Kernel: fix panic for Nagel's algorithm

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Tests/builtins/Symbol/Symbol.js
Userland/Libraries/LibJS/Tests/object-basic.js
Userland/Libraries/LibJS/Tests/strict-mode-errors.js
Userland/Libraries/LibJS/Tests/syntax/slash-after-block.js

- Removes accidental `source_range.realize()`
- Allows `this / 10`
- Assigns name of `{get func() {}}` properly
- Improves error for `(123).foo = "bar"` and friends

LibJS: Miscellaneous fixes

---

Ladybird/AppKit/Application/EventLoopImplementation.mm
Meta/CMake/common_compile_options.cmake
Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp
Userland/Services/RequestServer/ConnectionCache.h

This PR works around a compiler bug (https://github.com/llvm/llvm-project/issues/67260) and resolves two improved warnings.
Note that there is still a crash that affects the AppKit chrome. A PR with a fix is on the way: https://github.com/llvm/llvm-project/pull/71321
@ADKaster

Build fixes and workarounds for Clang trunk

---

Userland/Libraries/LibPDF/ColorSpace.cpp

* Compare array size to 3 and 4, not 4 and 5
* Fix literal typo in error message
Fixes crash processing 0000906.pdf from 0000.zip from the pdf/a dataset.

LibPDF: Fix typos in DeviceN colorspace scaffolding

---

Userland/Libraries/LibPDF/CMakeLists.txt
Userland/Libraries/LibPDF/ColorSpace.cpp
Userland/Libraries/LibPDF/ColorSpace.h
Userland/Libraries/LibPDF/CommonNames.h
Userland/Libraries/LibPDF/Function.cpp
Userland/Libraries/LibPDF/Function.h
Userland/Libraries/LibPDF/Reader.h

When printing, a separation color space is the name of one ink and an amount.
When drawing to a screen, that amount gets converted by a PDF function to inputs of an alternate color space.
This PR adds the separation color space bits for drawing to a screen, and starts implementing PDF functions. For now, it implements one of four possible function types (the one used in 66% of separation color spaces, in my test set).

LibPDF: Start implementing separation color spaces

---

Kernel/Syscalls/ptrace.cpp

Previously root (euid=0) was not able to ptrace any dumpable process as expected. This change fixes this.

Kernel/Syscalls: Allow root to ptrace any process

---

Userland/Libraries/LibJIT/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.h

#21679 inadvertently disabled the JIT on all platforms because it made the inclusion of the Assembler header dependent on a macro from that header.

LibJS/JIT: Make the JIT available again

---

Userland/Libraries/LibTest/TestCase.h

The original value 15 was too little: it made our
`weighted_boolean_fair_false` test fail every now and then.
This is because a fair coin (P(false) = 0.5) will hit the same value 15 times in a row with a probability (1/2)^15: around once in a 32k tries.
With the bumped up value, this is now once in 1 billion tries. Should lower the test flakiness enough (if our random number generator is truly uniform), while 30 tries is still an OK amount of computation for randomized tests to do, compared to 15.

LibTest: Bump up MAX_GEN_ATTEMPTS_PER_VALUE to 30

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Executable.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/JIT/Compiler.cpp

Instead of passing identifier and cache indexes from jitted code to C++ helpers, resolve them to pointer addresses directly in the JIT compiler instead.
Looks like 1-3% speed-ups across the board on Kraken and Octane :^)

LibJS/JIT: Resolve various pointers at JIT time

---

Base/usr/share/man/man7/Shell-vars.md
Userland/Shell/Shell.cpp

This PR makes it possible for the `$PROMPT` formatting option `\w`, which normally shows the current working directory, to shorten the path if an integer is provided after the backslash.
The way the path is shortened is based on whether 'w' or 'W' is used in the option. This is a mixture of how [Bash ](https://www.gnu.org/software/bash/manual/bash.html#Controlling-the-Prompt)and [Zsh](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html) implement this feature.

Shell: Add path shortening in prompt formatting option

---

AK/Optional.h
AK/StdLibExtras.h
AK/Vector.h
Userland/Libraries/LibJIT/X86_64/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibJS/JIT/NativeExecutable.cpp
Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
Userland/Libraries/LibJS/Runtime/Environment.h
Userland/Libraries/LibJS/Runtime/EnvironmentCoordinate.h
Userland/Libraries/LibJS/Runtime/ExecutionContext.h

When we have a cached `EnvironmentCoordinate` for a `GetVariable` instruction, we can stay in machine code and avoid the expensive call to C++.
20% speed-up on Octane/zlib.js :^)

LibJS+LibJIT+AK: Compile GetVariable fast path in the JIT

---

AK/FlyString.cpp
AK/FlyString.h
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
Userland/Libraries/LibWeb/CSS/Parser/Declaration.h
Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/Token.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleProperty.h
Userland/Libraries/LibWeb/DOM/Attr.cpp
Userland/Libraries/LibWeb/DOM/DOMImplementation.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Userland/Libraries/LibWeb/HTML/HTMLSlotElement.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp

After these changes, there are only two explicit usages of DeprecatedFlyString left in LibWeb. The two left are used as a result of LibJS's DeprecatedString usage, and should fall away with LibJS porting.

LibWeb: Remove remaining DeprecatedFlyString instances (almost)

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibWeb/Animations/AnimationTimeline.cpp
Userland/Libraries/LibWeb/Animations/AnimationTimeline.h
Userland/Libraries/LibWeb/Animations/AnimationTimeline.idl
Userland/Libraries/LibWeb/Animations/DocumentTimeline.cpp
Userland/Libraries/LibWeb/Animations/DocumentTimeline.h
Userland/Libraries/LibWeb/Animations/DocumentTimeline.idl
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Document.idl
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/idl_files.cmake

This PR just includes the `AnimationTimeline` and `DocumentTimeline` IDL objects. These objects are responsible for propagating a particular time through the animation hierarchy, as each animation will have one associated timeline. In practice, the only timeline that will be used is the `DocumentTimeline`, as it's the only inheritor. 
Work towards #21570

LibWeb: Begin implementing the Web Animations spec

---

Userland/Applications/GamesSettings/ChessSettingsWidget.cpp
Userland/Games/Chess/ChessWidget.cpp
Userland/Games/Chess/ChessWidget.h

*Imagine an explosion here. It crashes.*
Gets rid of a couple of fixmes in GamesSettings where we had errors we couldn't do anything with.

Chess+GamesSettings: Be more resilient to missing chess-piece graphics

---

Meta/CMake/pnp_ids.cmake
Meta/Lagom/Tools/CodeGenerators/LibEDID/GeneratePnpIDs.cpp

The PNP ID file is now a CSV file. Update the generator to handle the new format.

LibEDID: Replace the HTML-based PNP ID parser with a CSV-based parser

---

Userland/Libraries/LibVideo/VP9/Context.h

This fixes oss fuzz issue: [60262](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60262)

LibVideo/VP9: Ensure range decoder size is within expected range

---

AK/Time.h
Meta/Lagom/CMakeLists.txt
Tests/LibCore/CMakeLists.txt
Tests/LibCore/TestLibCoreDateTime.cpp
Tests/LibJS/test-js.cpp
Userland/Libraries/LibCore/DateTime.cpp
Userland/Libraries/LibCore/DateTime.h
Userland/Libraries/LibCore/System.cpp
Userland/Libraries/LibCore/System.h
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Userland/Libraries/LibTimeZone/CMakeLists.txt
Userland/Libraries/LibTimeZone/DateTime.cpp
Userland/Libraries/LibTimeZone/DateTime.h

All in the name of:
```
Diff Tests:
test/built-ins/Date/parse/zero.js  ❌ -> ✅
```
This extends `Core::DateTime::parse` to support parsing time zone names and wildcard-skipping characters, and adds implementation-defined format string to `Date.parse` in LibJS to parse the output of `Date.prototype.toString` and `Date.prototype.toUTCString`.

LibJS+LibCore+LibTimeZone: Support round-trip parsing of `Date.prototype.to*String` output

---

Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Runtime/AtomicsObject.cpp
Userland/Services/WebContent/PageHost.cpp

These few tiny changes make the Qt Ladybird build and somewhat work for me on 32-bit Debian GNU/Hurd!
If you want to reproduce my results, I'm actually building with the following additional patch:
```patch
diff --git a/Meta/CMake/lagom_compile_options.cmake b/Meta/CMake/lagom_compile_options.cmake
index 40f646766c..9db1d514a4 100644
--- a/Meta/CMake/lagom_compile_options.cmake
+++ b/Meta/CMake/lagom_compile_options.cmake
@@ -6,6 +6,7 @@ add_compile_options(-fsigned-char)
add_compile_options(-g1)
add_compile_options(-ggnu-pubnames)
add_compile_options(-O2)
+add_compile_options(-mstack-alignment=16)
if (NOT WIN32)
add_compile_options(-fPIC)
endif()
diff --git a/Userland/Libraries/LibCore/System.cpp b/Userland/Libraries/LibCore/System.cpp
index 935a4b73f5..e4d241dabe 100644
--- …
```

Some more 32-bit & Hurd fixes

---

Userland/Libraries/LibIMAP/Parser.cpp
Userland/Libraries/LibIMAP/Parser.h

We now return an error where `parse_atom()` would have previously returned an empty StringView. This is consistent with RFC3501, which says that an atom consists of one or more characters.
This prevents a few cases where parsing an invalid atom could lead to an infinite loop.
Fixes oss fuzz issue: [63920](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63920)

LibIMAP: Make parsing of atom data fallible

---

Meta/Lagom/Fuzzers/FuzzDNSPacket.cpp
Meta/Lagom/Fuzzers/fuzzers.cmake
Userland/Libraries/LibDNS/Name.cpp
Userland/Libraries/LibDNS/Name.h
Userland/Libraries/LibDNS/Packet.cpp
Userland/Libraries/LibDNS/Packet.h
Userland/Services/LookupServer/DNSServer.cpp
Userland/Services/LookupServer/LookupServer.cpp
Userland/Services/LookupServer/MulticastDNS.cpp
Userland/Utilities/test-fuzz.cpp

This PR makes the following changes to LibDNS:
* Adds a fuzzer for `DNS::Packet`, which should cover the majority of LibDNS.
* Replaces raw pointer usages with Spans and C-style casts with `bit_cast`.
* Prevents some buffer overflows found via local fuzzing. I'm including these in this PR since they stop the fuzzer making much progress.
I tried to replace the casting entirely by using streams, but IMO this made the code less easy to follow, so I didn't include it.

LibDNS+Fuzzers: Add a DNS packet fuzzer and prevent some buffer overflows

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/HTML/Window-postMessage.txt
Tests/LibWeb/Text/input/HTML/Window-postMessage.html
Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
Userland/Libraries/LibWeb/HTML/MessageEvent.h
Userland/Libraries/LibWeb/HTML/MessageEvent.idl
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/HTML/Window.idl

The main issues are using Structured{Serialize,Deserailize} instead of
Structured{Serialize,Deserialize}WithTransfer and the temporary
execution context usage for StructuredDeserialize.
Allows Discord to load once again, as it uses a postMessage scheduler
to render components, including the main App component. The callback
checked the (previously) non-existent source attribute of the
MessageEvent and returned if it was not the main window.
Fixes the Twitch cookie consent banner saying "failed integrity check"
for unknown reasons, but presumably related to the source and origin
attributes.

LibWeb: Make Window.postMessage closer to the spec

---

Userland/Shell/PosixLexer.cpp

Previously, the shell would enter an infinite loop when attempting to parse a heredoc entry within a `$(` command substitution.
For example, when entering the following into the shell: `$(cat << EOF )`, typing the closing parenthesis would cause the  infinite loop.
Using heredocs in POSIX mode causes the shell to crash at the moment (see #21837). This PR doesn't affect that behavior.
This fixes* oss fuzz issue: [63093](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63093)
\* Running the test case through the fuzzer with this fix applied results in [this memory leak](https://gist.github.com/tcl3/77f66c0d22d639f18a4ca78a5b3f5556). I'm not sure if this has anything to do with my change, as testing with something simpler doesn't cause a memory leak.

Shell: Avoid infinite loop when parsing heredoc entry in POSIX mode

---

Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

So far only `less_than` was using a fast path. This commits uses the same path for `less_than_equals`, `greater_than` and `greater_than_equals`.
PS: Thanks for the awesome YouTube series, I learned quite a lot!

LibJS/JIT: Add fast path for number comparisons

---

Userland/Applications/3DFileViewer/CMakeLists.txt
Userland/Applications/3DFileViewer/main.cpp
Userland/Applications/Calculator/CMakeLists.txt
Userland/Applications/Calculator/main.cpp
Userland/Games/Spider/CMakeLists.txt
Userland/Games/Spider/main.cpp

I have added Help Entries the Context menus of 3DFileViewer, Calculator and Spider, advancing progress on issue: #21091

Add Manual Links to the help entry of the Context menus of 3DFileViewer, Calculator and Spider

---

AK/MemoryStream.cpp
AK/MemoryStream.h
Tests/AK/TestMemoryStream.cpp
Tests/LibCore/TestLibCoreMappedFile.cpp
Userland/Libraries/LibAudio/Loader.cpp
Userland/Libraries/LibCompress/LZWDecoder.h
Userland/Libraries/LibCore/MappedFile.cpp
Userland/Libraries/LibCore/MappedFile.h
Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp

These commits are preliminary work towards LZW support in TIFF. As we are two PRs away from being in the state of adding LZW to the TIFF decoder, I decided to split independent changes.
This PR is fairly simple, it moves the LZW decoder to its own file and use LittleEndianInputBitStream instead of manually implementing the logic.

LibGfx/GIF: Extract the LZW decoder

---

AK/Utf16View.h
Tests/LibRegex/Regex.cpp
Userland/Libraries/LibRegex/RegexByteCode.cpp
Userland/Libraries/LibUnicode/CharacterTypes.cpp
Userland/Libraries/LibUnicode/CharacterTypes.h
Userland/Libraries/LibUnicode/String.cpp

```
Diff Tests:
test/built-ins/RegExp/unicode_full_case_folding.js     ❌ -> ✅
test/language/literals/regexp/u-case-mapping.js        ❌ -> ✅
```

LibRegex: Support non-ASCII case-insensitive character comparisons

---

Userland/Libraries/LibJIT/X86_64/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp

LibJS/JIT: Fast path for decrement & better opcodes

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h

If the property for GetByValue in Generator::load_from_reference is a calculated value this would be stored in an allocated register and returned from the function. Not all callers want this information however, so now only give it out when asked for.
Reduced the instruction count for Kraken/ai-astar.js function "neighbours" from 214 to 192.

LibJS: Remove redundant Store op

---

AK/Endian.h
Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp

LibGfx: Ensure const-correctness when reading from the GPOS byte stream

---

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

Reduction of bug:
```html
<!DOCTYPE html><style>
html {
overflow-x: hidden;
overflow-y: scroll;
}
div {
background: orange;
height: 1000px;
width: 500px;
}
</style><body><div>
```
Fixes https://github.com/SerenityOS/serenity/issues/21690 and painting on many other websites (null.com, servo.org).

LibWeb: Ignore document's box during overflow clip rect calculation

---

Userland/Libraries/LibAccelGfx/Painter.cpp

This fixes bug when tiny slice of another glyph appearing along with the required glyph.

LibAccelGfx: Add 1px padding between glyphs in prepare_glyph_texture()

---

AK/Span.h
Tests/LibPDF/TestPDF.cpp
Userland/Libraries/LibPDF/Function.cpp

Includes a tokenizer and interpreter for the subset of PostScript
supported in PDF type 4 functions.
---
Used mostly in DeviceN color spaces, but sometimes in Separation color spaces as well. Possibly in gradients too, but I haven't done gradients yet.
It has conditionals, but no loops.

LibPDF: Implement PostScriptCalculatorFunction

---

Tests/LibWeb/Text/expected/canvas/export.txt
Tests/LibWeb/Text/input/canvas/export.html
Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp

LibGfx/JPEGWriter: Fix crash on macOS when csize coefficient is 0

---

Userland/Libraries/LibWeb/Animations/Animation.cpp
Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
Userland/Libraries/LibWeb/Animations/AnimationEffect.h

These are precursor functions for `transformed_progress()`, which is the value that is actually used for CSS value interpolation. I chose to save that implementation for the next PR since it requires the timing function. 
Work towards #21570

LibWeb: Implement functions required for calculating AnimationEffect's transformed progress

---

Userland/Applications/Terminal/main.cpp
Userland/Libraries/LibGfx/Font/Font.h
Userland/Libraries/LibGfx/Font/Typeface.cpp

Terminal zoom was failing due to not being able to find a font of the exact requested size. This PR fixes that by allowing it to find a font of a close size in the right direction according to if the user requested to zoom in or out.

Fix terminal zoom

---

Base/res/html/misc/lists.html
Tests/LibWeb/Layout/expected/ordered-list.txt
Tests/LibWeb/Layout/input/ordered-list.html
Userland/Libraries/LibWeb/HTML/AttributeNames.h
Userland/Libraries/LibWeb/HTML/HTMLLIElement.h
Userland/Libraries/LibWeb/HTML/HTMLLIElement.idl
Userland/Libraries/LibWeb/HTML/HTMLOListElement.h
Userland/Libraries/LibWeb/HTML/HTMLOListElement.idl
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Userland/Libraries/LibWeb/Layout/TreeBuilder.h

I have added support for the `<ol>` start and `<li>` value attributes. These attributes are used to change the default index order of ordered lists:
```html
<ol start="20">
<li>Item 20</li>
<li>Item 21</li>
<li>Item 22</li>
</ol>
<ol>
<li>Item 1</li>
<li value="5">Item 5</li>
<li>Item 6</li>
<li>Item 7</li>
</ol>
```
Looking forward to the review :^)

LibWeb: Add ol start and li value attributes support

---

Userland/Libraries/LibPDF/ColorSpace.cpp
Userland/Libraries/LibPDF/ColorSpace.h

DeviceNColorSpace is very similar to SeparationColorSpace (#21810) except that more than one ink can be mentioned at once.
If `NChannel` is set, it can also be a general multi-channel additive color space.
But the "pass coordinates to tint transform and pass output to alternateSpace" rendering method is still one of the possible valid rendering methods, so let's go with that, since we have the plumbing in place for it. (Evaluating the channels one-by-one is another, and maybe we want to look into other approaches in the future.)

LibPDF: Implement DeviceNColorSpace

---

Base/home/anon/.config/Taskbar.ini
Userland/Libraries/LibDesktop/AppFile.cpp
Userland/Libraries/LibDesktop/AppFile.h
Userland/Libraries/LibDesktop/CMakeLists.txt
Userland/Libraries/LibGUI/ConnectionToWindowManagerServer.cpp
Userland/Libraries/LibGUI/ConnectionToWindowManagerServer.h
Userland/Libraries/LibGUI/Event.h
Userland/Libraries/LibGUI/Window.cpp
Userland/Libraries/LibGUI/Window.h
Userland/Services/Taskbar/QuickLaunchWidget.cpp
Userland/Services/Taskbar/QuickLaunchWidget.h
Userland/Services/Taskbar/TaskbarWindow.cpp
Userland/Services/WindowServer/ConnectionFromClient.cpp
Userland/Services/WindowServer/ConnectionFromClient.h
Userland/Services/WindowServer/Window.cpp
Userland/Services/WindowServer/Window.h
Userland/Services/WindowServer/WindowManager.cpp
Userland/Services/WindowServer/WindowManager.h
Userland/Services/WindowServer/WindowManagerClient.ipc
Userland/Services/WindowServer/WindowServer.ipc

This PR improves the `QuickLaunchWidget` in the Taskbar. Mainly, you can now add applications to Quick Launch via the "Add to Quick Launch" action in the context menu of their windows. In addition, it is now possible to reorder the Quick Launch entries.
For the window action I am passing the PID of the process that created the window to `WindowServer` in the `create_window()` IPC route, after which it is stored in `WindowServer::Window`. Then, when clicking the context menu action, an `AddToQuickLaunch` event is sent with the PID from the window. The Taskbar receives the event and forwards the PID to `QuickLaunchWidget`. It finally uses `/sys/kernel/processes` to get the required information for the PID and adds it to its entries.
For the reordering I had to change the way Quick Launch …

Taskbar/QuickLaunchWidget: Make adding entries easier + reordering

---

Meta/Lagom/CMakeLists.txt

Ran into this with the new EAP for CLion Nova. When using Ladybird as source directory, we would recursively look in Ladybird --> Lagom --> Ladybird when exporting components. This seems to be because ENABLE_LAGOM_LADYBIRD is set to ON by Ladybird's CMakeLists and something about their build, when invoked from their IDE, has buggy behavior around the SUBDIRECTORIES directory property.

CMake: Don't recursively include Ladybird/Lagom in buggy CMake versions

---

Userland/Libraries/LibTLS/Record.cpp
Userland/Libraries/LibTLS/TLSv12.h

There's a good chance the TLS socket instance will be deleted before the deferred invocation fires, and there's no real reason to defer flushes of alerts anyway as they are usually sent on errors. Fixes #21800.

LibTLS: Do not defer flushing alert packets

---

Meta/Lagom/CMakeLists.txt

Fix the recursive directory bug in CLion Nova EAP's CMake version in a way that doesn't also break `./Meta/serenity.sh run lagom ladybird`.
This brings the Lagom minimum required closer to the Serenity minimum required. Which is still fine, because the serenity.sh script knows how to build CMake from source if a developer's local copy is too old.

CMake: Bump CMake minimum up to 3.21 to work around CLion bug

---

Userland/Libraries/LibJIT/X86_64/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibX86/Instruction.h

LibJS/JIT: Add fast-path for float arithmetic

---

Userland/Libraries/LibPDF/CommonNames.h
Userland/Libraries/LibPDF/Function.cpp

We're going to need this once we add support for gradients.
With this and #21818, we have implementations for all PDF function types :^)
(…but SamplingFunction is still a bit incomplete even after #21818.)

LibPDF: Implement StitchingFunction

---

Userland/Libraries/LibPDF/Function.cpp

Since positive offsets roll to the right, it makes more sense to do the big reverse first. Gets rid of an awkward minus sign.
(Covered by existing tests, too.)

LibPDF: Tweak implementation of postscript `roll` op

---

Meta/test_pdf.py
Userland/Utilities/pdf.cpp

The main change is that it now groups by feature first, filename second instead of the other way round.
To make this easier, give `pdf` a `--json` flag to control the `-debugging-stats` output.
Demo:
```% time Meta/test_pdf.py -n 20 ~/Downloads/0000
11 distinct issues, in 13 files (65.0%):
Rendering of feature not supported: Type0 font CIDFontType2 not implemented yet, in 7 files, on 26 pages, 2283 times
/Users/thakis/Downloads/0000/0000994.pdf 2 4 (2x) 5 (3x) 8 (9x) 9 (4x) 11 (6x) 12 (7x) 13 (11x) 14 (9x) 15 (9x) 16 (10x) 17 (9x) 18 (10x) 19 (9x) 20 (8x)
/Users/thakis/Downloads/0000/0000641.pdf 1 (91x) 2 (128x) 3 (16x) 4 (18x)
/Users/thakis/Downloads/0000/0000405.pdf 1 (16x) 2 (14x) 3 (10x)
/Users/thakis/Downloads/0000/0000834.pdf 1 (138x)
/Users/thakis/Downloads/0000/0000765.pdf 1 (44x) …
```

pdf+test_pdf.py: Tweak output of test_pdf.py

---

Userland/Libraries/LibCrypto/Curves/SECP256r1.cpp

This PR contains some clean-up of the SECP256r1 curve implementation that I did a while ago. These clean-ups are mostly to improve readability and to make the code more generic in preparation for the SECP384r1 implementation.
Most significantly, the large list of `u256` constants at the top of the file is now reduced to 4 constants, which are taken directly from the curve specification. All the other constants are now calculated instead.

LibCrypto: Some clean-up of the SECP256r1 curve implementation

---

Tests/Kernel/crash.cpp
Tests/Kernel/elf-symbolication-kernel-read-exploit.cpp
Userland/Applications/CrashReporter/main.cpp
Userland/Applications/Debugger/main.cpp
Userland/DevTools/HackStudio/Debugger/RegistersModel.cpp
Userland/DynamicLoader/main.cpp
Userland/Libraries/LibC/arch/riscv64/setjmp.S
Userland/Libraries/LibC/crt0.cpp
Userland/Libraries/LibC/fenv.cpp
Userland/Libraries/LibC/math.cpp
Userland/Libraries/LibC/setjmp.h
Userland/Libraries/LibC/sys/arch/regs.h
Userland/Libraries/LibCoredump/Backtrace.cpp
Userland/Libraries/LibDebug/DebugInfo.cpp
Userland/Libraries/LibDebug/DebugSession.cpp
Userland/Libraries/LibDebug/DebugSession.h
Userland/Libraries/LibELF/Arch/riscv64/entry.S
Userland/Libraries/LibELF/Arch/riscv64/plt_trampoline.S
Userland/Libraries/LibELF/DynamicLinker.cpp
Userland/Libraries/LibELF/ELFABI.h
Userland/Libraries/LibJS/Runtime/Value.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Userland/Utilities/functrace.cpp
Userland/Utilities/strace.cpp

This PR makes Userland and Tests compile under riscv64.
I didn't include my DynamicLoader related patches, as I will refactor them.
To compile this PR using the riscv64 clang toolchain you can use [this patch](https://gist.github.com/spholz/feac2d166fa8c1bc1330726a7c275aae), which disables building the kernel and adds the necessary kernel syscall API.
Compiling using GCC doesn't yet work, as you would get a lot of undefined references to `__atomic` functions (this will be fixed in a later PR). It also throws a lot of `-Wcast-align` warnings (which shouldn't really matter).

Userland+Tests: Add initial riscv64 support

---

Userland/Libraries/LibAccelGfx/CMakeLists.txt
Userland/Libraries/LibAccelGfx/Canvas.cpp
Userland/Libraries/LibAccelGfx/GL.cpp
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibAccelGfx/Program.cpp
Userland/Libraries/LibAccelGfx/Program.h

This change introduces GL.h with error check wrappers for all the OpenGL functions we used so far.
For now, the error check is simply:
`VERIFY(glGetError() == GL_NO_ERROR);`
but that is better than continuing execution after encounting an error.

LibAccelGfx: Use wrapping functions with error check for OpenGL calls

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibIDL/Types.cpp
Userland/Libraries/LibIDL/Types.h
Userland/Libraries/LibWeb/WebIDL/OverloadResolution.cpp

Aside from the obvious performance benefits, this will allow us to properly handle dictionary types. (whose dictionary-ness is only known at build-time)
Much of the rest of the overload resolution algorithm steps can (and should) be evaluated at build-time as well, but this is a good first step.

LibIDL+LibWeb: Resolve distinguishing argument index at build time

---

Tests/LibWeb/Text/expected/HTML/get-innerHTML.txt
Tests/LibWeb/Text/input/HTML/get-innerHTML.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.h

I started these changes trying to figure out why some namespaces weren't being set on some attributes like I expected. I didn't figure out what was causing that, and in that investigation, ended up adding some spec comments to the HTML parser, and removing some FIXME's for how attributes are serialized (as far as I can tell, we already serialize these properly). So here's that PR!

LibWeb: Remove some FIXME's for serialization of HTML attributes

---

Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp

Previously, a crash would occur if a font file had an invalid IndexToLocFormat value.
Tested with 462 `.ttf` files on my local machine
This fixes oss fuzz issue [64035](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64035)

LibGfx/OpenType: Add validation for OpenType head table values

---

Userland/Libraries/LibIDL/IDLParser.cpp

Makes the IDLGenerator reject the syntax errors that are fixed in #21882. Requires that PR to go in first, since otherwise the build would break.

LibIDL: Disallow invalid nullable types; require 'attribute' keyword

---

Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/Runtime/Value.h

I don't think this would have an observable difference on any normal benchmark, but the always-false branch seemed sad

LibJS: Skip an always-false branch in the JIT to_boolean slow case

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Tests/eval-aliasing.js

When overriding 'eval' to a non-function value, the interpreter would
crash. Now it handles this case swiftly, throwing a TypeError.

LibJS/Bytecode: Check if eval function is a function

---

AK/UFixedBigInt.h
Userland/Libraries/LibCrypto/CMakeLists.txt
Userland/Libraries/LibCrypto/Curves/SECP256r1.cpp
Userland/Libraries/LibCrypto/Curves/SECP256r1.h
Userland/Libraries/LibCrypto/Curves/SECP384r1.cpp
Userland/Libraries/LibCrypto/Curves/SECP384r1.h
Userland/Libraries/LibTLS/HandshakeServer.cpp
Userland/Libraries/LibTLS/TLSv12.cpp
Userland/Libraries/LibTLS/TLSv12.h

This PR adds an implementation for the SECP384r1 curve and adds support to LibTLS for this curve. This should fix the issues people are having when trying to load websites which send certificates with SECP384r1 signatures.
Currently this implementation is basically a copy-paste of the SECP256r1 implementation with some minor replacements. I would prefer to merge the code for these two curves in the future as they are basically identical, but for now this gets us a working SECP384r1 implementation.
I've currently only tested this implementation through "TestTLSHandshake", which seems to work fine. However, if someone could check by building the full system and using Ladybird, I would appreciate it.
This should fix #21211 and possibly more issues.

LibCrypto+LibTLS: Implement SECP384r1

---

Userland/Shell/Shell.cpp

Fixes #21884 
Look like we forgot to pass `m_is_interactive` when we parse command every time user hit Enter, that produces inconsistent  AST.
Here's the AST dump for `echo !*` after it get parsed:
```
339.128 Shell(41:41): echo !*
339.128 Shell(41:41): Execute at 0:7 (from 0.0 to 0.7)
339.135 Shell(41:41):   Sequence at 0:7 (from 0.0 to 0.7)
339.135 Shell(41:41):     CastToCommand at 0:7 (from 0.0 to 0.7)
339.143 Shell(41:41):       ListConcatenate at 0:7 (from 0.0 to 0.7)
339.148 Shell(41:41):         BarewordLiteral at 0:4 (from 0.0 to 0.4)
339.153 Shell(41:41):           echo
339.153 Shell(41:41):         Glob at 5:7 (from 0.5 to 0.7)
339.160 Shell(41:41):           !*
339.160 Shell(41:41): --------------------
339.165 Shell(41:41): echo !*
339.168 Shell(41:41): Execute at 0:7 (from …
```

Shell: Allow to parse command interactively when hitting Enter key

---

Tests/LibWeb/Text/expected/HTML/StructuredClone-object-primitives.txt
Tests/LibWeb/Text/expected/HTML/Window-postMessage.txt
Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HighResolutionTime/Performance.cpp
Userland/Libraries/LibWeb/UserTiming/PerformanceMark.cpp

This unbreaks Acid 3 after #21823.
The last commit is kinda large, but it's mostly the added support for true nested deserialization (which is required for all 4)

LibWeb: Support [de]serialization for {Error, Map, Set, Object, Array} objects

---

Tests/LibTTF/TestCmap.cpp
Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp

Previously, a file with a Cmap subtable record offset greater than the Cmap table size would cause a crash.
Found via local fuzzing.

LibGfx/OpenType: Ensure Cmap subtable offset is within expected range

---

Tests/LibWeb/Layout/expected/svg/svg-with-zero-sized-viewBox.txt
Tests/LibWeb/Layout/input/svg/svg-with-zero-sized-viewBox.html
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp

Now https://www.fandom.com/fancentral/home loads and displays:
...before hanging... but progress :)

LibWeb: Check for invalid SVG viewBox sizes 

---

Userland/Libraries/LibAudio/PlaybackStreamSerenity.cpp
Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp

Audio loaders currently always output two channels, even if they were encoded as mono. Therefore, we have to hardcode the channel count in our audio plugin to avoid crashing until we can handle mono or multi-channel audio better.
Fixes #21898
I've also added an assertion that prevents us from creating Serenity playback streams with a channel count other than 2, since the audio server doesn't know about non-stereo audio.

LibWeb: Output audio in stereo regardless of the encoded channel count

---

Userland/Libraries/LibGfx/ICC/TagTypes.cpp

Previously, it was possible for a `MultiLocalizedUnicodeTagData` object with a incorrect length or offset fields to cause a buffer overflow.
This PR also fixes another buffer overflow when creating a `TextDescriptionTagData` object with an incorrect Macintosh ScriptCode description length.
Fixes oss fuzz issue [64079](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64079)

LibGfx/ICC: Avoid overflow when creating MultiLocalizedUnicodeTagData

---

Userland/Libraries/LibLine/Editor.cpp

Otherwise a subsequent event (^C or resize) will make LibLine use the previous origin instead of the real current one.
(fix for the bug #21765 was trying to fix)

LibLine: Capture the current origin immediately after ^C

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.h
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

This allows us to JIT code that uses the `with` statement.

LibJS/JIT: Support the EnterObjectEnvironment instruction + minor cleanups

---

Tests/LibWeb/Ref/svg-alpha-mask-attribute.html
Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp

Progression on [discord](https://discord.com/):
**Before:**
**After:**

LibWeb: Support `mask-type` style attribute for SVGs 

---

Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibJS/Runtime/Array.cpp
Userland/Libraries/LibJS/Runtime/Object.h

Combined, these yield a strong ~2.7x speed-up on Kraken/ai-astar.js :^)

LibJS/JIT: Fast paths for object==object and Array.length

---

Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

Since we already call `Painter::flush()` in `PageHost::paint()` we do not need to do that again in `PaintingCommandExecutorGPU` destructor.
This makes GPU painting run noticeably faster because `flush()` does expensive `glReadPixels()` call.

LibWeb: Remove redundant flush() call in PaintingCommandExecutorGPU

---

Userland/Libraries/LibPDF/ColorSpace.cpp

Namely, for CalGrayColorSpace, CalRGBColorSpace, LabColorSpace.
Fixes a crash rendering any page of Adobe's 5014.CIDFont_Spec.pdf (which uses CalRGBColorSpace with an indirect dict: The dict is object `92 0`, and many color spaces are inline objects referring to it).

LibPDF: Tolerate an indirect object as dict for CIE-based color spaces

---

Userland/Libraries/LibJS/JIT/Compiler.cpp

```
Kraken      ai-astar.js                              1.189  1.197 ± 1.170 … 1.220     1.007 ± 1.000 … 1.010
Kraken      audio-beat-detection.js                  1.312  1.360 ± 1.360 … 1.360     1.037 ± 1.030 … 1.050
Kraken      audio-dft.js                             1.342  0.863 ± 0.860 … 0.870     0.643 ± 0.640 … 0.650
Kraken      audio-fft.js                             1.711  1.243 ± 1.240 … 1.250     0.727 ± 0.720 … 0.730
Kraken      audio-oscillator.js                      1.431  2.677 ± 2.640 … 2.750     1.870 ± 1.850 … 1.890
Kraken      imaging-darkroom.js …
```

LibJS/JIT: Remove incorrect check for empty tag

---

Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Tests/parser-invalid-destructuring-assignment-target.js

Previously, certain crafted input could cause the JS parser to hang, as it repeatedly tried to parse an EOF token after hitting an "invalid destructuring assignment target" error. This change ensures that we stop parsing after hitting this error condition.
I was able to reduce the oss fuzz test case to the following JS snippet:
```js
[[function=a{1,}=
```
I wasn't able to come up with a more realistic example though; not all cases where this error was hit would cause the parser to hang.
By including this snippet in a HTML page, Ladybird would also hang:
```html
<html><script>[[function=a{1,}=</script>this text should appear</html>
```
There is no change to test262 parser tests output, but none of the tests seem to hit the code path I changed.
This fixes oss fuzz issue: …

LibJS: Don't hang when parsing invalid destructuring assignment target

---

AK/JsonValue.h
Kernel/FileSystem/ProcFS/ProcessExposed.cpp

JsonValue can store JsonObject which uses DS for keys, so it is not safe to use it in the kernel even with the double/String guards.

AK: Ban JsonValue from the kernel and remove ifdef guards

---

Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
Userland/Libraries/LibPDF/Fonts/Type1FontProgram.h

Per 5177.Type2.pdf 3.1 "Type 2 Charstring Organization", a glyph's charstring looks like:
w? {hs* vs* cm* hm* mt subpath}? {mt subpath}* endchar
The `w?` is the width of the glyph, but it's optional. So all possible commands after it (hstem* vstem* cntrmask hintmask moveto endchar) check if there's an extra number at the start and interpret it as a width, for the very first command we read.
This was done by having an `is_first_command` local bool that got set to false after the first command. That didn't work with subrs: If the first command was a call to a subr that just pushed a bunch of numbers, then the second command after it is the actual first command.
Instead, move that bool into the state. Set it to false the first time we try to read a width, since that means we just read a …

LibPDF: Change how CFF optional width prefix is stored

---

Meta/Lagom/Fuzzers/FuzzDNSPacket.cpp
Userland/Libraries/LibDNS/Name.cpp
Userland/Libraries/LibDNS/Name.h
Userland/Libraries/LibDNS/Packet.cpp
Userland/Libraries/LibDNS/Packet.h
Userland/Services/LookupServer/DNSServer.cpp
Userland/Services/LookupServer/LookupServer.cpp
Userland/Services/LookupServer/MulticastDNS.cpp

The DNS parser will now fail to parse a packet with any invalid name parts, rather than returning a packet with an empty name.
Previously, the DNS packet parser would happily parse a DNS packet containing an arbitrarily large domain name. We now limit each segment of a domain name to 63 characters and the total domain name length to 253 characters. This is consistent with RFC1035, which specifies that the maximum name length is 255 octets. This includes the initial length byte and final null byte, which are not displayed and account for the 2 byte difference.
This fixes oss fuzz issue: [64145](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64145)

LibDNS: Ensure DNS name and label sizes are within expected limits

---

Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp

Also adds a commit that has `MimeType::create()` match its forward declaration.

LibWeb: Validate `MimeType(String, String)` arguments correctly

---

Userland/Shell/AST.cpp
Userland/Shell/Builtin.cpp
Userland/Shell/Shell.cpp
Userland/Shell/Shell.h

These changes ensure that the glob `*/` only expands to directories, and that the parent and base directories are also included in the glob `.*`, which is in line with how POSIX handle globs. 
They also include a bunch of error propagation improvements in Shell. Please let me know if these don't belong in this PR, then I'll put them in a separate PR. :)

Shell: Improve directory glob expansion

---

.gitignore

Otherwise, opening any folder under Base in Finder on macOS may create a tracked .DS_Store file, which we don't want committed to the repo.

Meta: Move .DS_Store rule to the bottom of the .gitignore file

---

Userland/Applications/Browser/BookmarksBarWidget.cpp
Userland/Applications/Browser/BookmarksBarWidget.h

Since none of `BookmarksBarWidget`'s methods use this enum class any longer, let's just move it to the anonymous namespace so that `BookmarkEditor` can still make use of it.

Browser: Move `BookmarksBarWidget::PerformEditOn` to anon namespace

---

Tests/LibWeb/Layout/expected/block-and-inline/abspos-grid-with-definite-width.txt
Tests/LibWeb/Layout/input/block-and-inline/abspos-grid-with-definite-width.html
Userland/Libraries/LibWeb/Layout/FormattingContext.cpp

By using available_inner_space_or_constraints_from(available_space), we ensure that the available space used to calculate the min/max content height is constrained by the width specified for the box itself (I know that at least GFC always expects available width to be constrained by specified width if there is any).
This change improves layout in "Recent news" block on https://telegram.org/

LibWeb: Use inner available space to calculate auto height of abspos

---

Documentation/HelixConfiguration.md

Helix 23.10 made breaking changes to the way lsp configuration works, so update documentation to reflect the new structure.

Documentation: Update Helix editor documentation

---

Meta/gn/secondary/Ladybird/BUILD.gn
Meta/gn/secondary/Ladybird/WebWorker/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/Scripting/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/Worker/BUILD.gn
Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp

The condition for checking if a script has a JS MIME type is currently
flipped. Extract the check to a local to make it a bit easier to reason
about at quick glance.
Seen trying to login to https://www.strava.com/login which uses web workers (still can't log in due to a 500 error 😞)

LibWeb: Don't reject worker scripts with a JavaScript MIME type

---

Tests/LibWeb/Layout/expected/block-and-inline/abspos-only-with-inset-left.txt
Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-bottom-right-insets-relative-to-box-with-paddings.txt
Tests/LibWeb/Layout/expected/block-and-inline/abspos-without-insets-relative-top-box-with-padding-top.txt
Tests/LibWeb/Layout/expected/block-and-inline/abspos-without-insets.txt
Tests/LibWeb/Layout/input/block-and-inline/abspos-only-with-inset-left.html
Tests/LibWeb/Layout/input/block-and-inline/abspos-with-bottom-right-insets-relative-to-box-with-paddings.html
Tests/LibWeb/Layout/input/block-and-inline/abspos-without-insets-relative-top-box-with-padding-top.html
Tests/LibWeb/Layout/input/block-and-inline/abspos-without-insets.html
Userland/Libraries/LibWeb/Layout/FormattingContext.cpp

When a box does not have a top, left, bottom, or right, there is no need to adjust the offset for positioning relative to the padding edge, because the box remains in the normal flow.

LibWeb: Do not compensate padding for abspos boxes with static position

---

Userland/Libraries/LibJIT/X86_64/Assembler.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

```
Kraken      ai-astar.js                              0.963  1.400 ± 1.360 … 1.420     1.453 ± 1.400 … 1.510
Kraken      audio-beat-detection.js                  1.024  1.283 ± 1.280 … 1.290     1.253 ± 1.250 … 1.260
Kraken      audio-dft.js                             0.92   0.767 ± 0.750 … 0.790     0.833 ± 0.810 … 0.860
Kraken      audio-fft.js                             0.993  1.003 ± 0.990 … 1.010     1.010 ± 0.970 … 1.070
Kraken      audio-oscillator.js                      0.963  2.240 ± 2.210 … 2.270     2.327 ± 2.220 … 2.400
Kraken      imaging-darkroom.js …
```

LibJS/JIT: Add a fast path for floating point comparisons

---

Userland/Libraries/LibJS/Parser.cpp
Userland/Libraries/LibJS/Parser.h

When deciding whether we need to create a full-blown `arguments` object, we look at various things, starting as early as in the parser.
Until now, if the parser saw the identifier `arguments`, we'd decide that it's enough of a clue that we should create the `arguments` object since somebody is obviously accessing it.
However, that missed the case where someone is just accessing a property named `arguments` on some object. In such cases (`o.arguments`), we now hold off on creating an `arguments` object.
~11% speed-up on Octane/typescript.js :^)

LibJS: Don't create `arguments` object due to `o.arguments` access

---

Meta/CMake/accelerated_graphics.cmake
Userland/Libraries/LibAccelGfx/Context.cpp
Userland/Libraries/LibAccelGfx/Context.h
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp

With these changes it is now possible to create OpenGL context on macOS and run GPU-painter. For now only QT client has a CLI param that turns it on though.
@ADKaster could you have a look please?

LibAccelGfx+WebContent: Add GPU painter support on macOS

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

Linear gradient painting is implemented in the following way:
1. The rectangle is divided into segments where each segment represents a simple linear gradient between an adjacent pair of stops.
2. Each quad is filled separately using a fragment shader that interpolates between two colors.
For now `angle` and `repeat_length` parameters are ignored.

LibAccelGfx+LibWeb: Add basic support for linear gradients painting

---

Base/usr/share/man/man1/head.md

The shorthand for the ‘--bytes’ flag is ‘-c’, not ‘-b’.

head(1): Fix typo in flag name

---

Base/usr/share/shell/completion/builtin.sh

This adds a completion function for cd that only returns directories, instead of the default completion that also suggests files, which doesn't make sense for cd.
I am still not quite sure about the significance of some of the values in the JSON-object. These values seem to work, but I am open to feedback. :) 
Depends on #21922

Base: Add completion for cd that suggests only directories

---

Meta/CMake/common_compile_options.cmake
Meta/gn/build/BUILD.gn

FP contraction is a standard-conforming behavior which allows the compiler to calculate intermediate results of expressions containing floating point numbers with a greater precision than the expression type allows. And in theory, it enables additional optimizations, such as replacing `a * b + c` with `fma(a, b, c)`.
Unfortunately, it is extremely hard to predict when the contraction will happen. For example, Clang 17 on x86_64 with the default options will use FMA only for constant-folded non-constexpr expressions. So, in practice, FP contraction leads to hard-to-find bugs and inconsistencies between executables compiled with different toolchains or for different OSes. And we had two instances of this happening last week.
Since we did not ever used -mfma on x86_64, this patch can only …

Meta: Globally disable floating point contraction

---

Userland/Libraries/LibTextCodec/Decoder.cpp
Userland/Libraries/LibTextCodec/Decoder.h
Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
Userland/Libraries/LibWeb/DOM/DocumentLoading.h
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp

LibWeb: Reject improperly encoded XML documents as not well-formed

---

Userland/Services/WindowServer/Window.cpp
Userland/Services/WindowServer/Window.h

The roll-up feature allows the user to set the window content to be hidden, while retaining the window title bar visibility. While in roll-up mode, the window height size is not changeable. However, tiling the window or maximizing (as well as unmaximize) it will instruct exiting the roll-up mode.
The idea for this feature is from my Xfce desktop - I really like this feature and use it sometimes to better organize the currently open windows on the screen.

WindowServer: Introduce the window roll-up feature

---

Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
Userland/Libraries/LibJIT/X86_64/Assembler.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Builtins.cpp
Userland/Libraries/LibJS/Bytecode/Builtins.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/CMakeLists.txt
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibJS/Runtime/MathObject.cpp
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Object.h
Userland/Libraries/LibJS/Runtime/Realm.h

I originally planned the name "intrinsic", but that term is already used by ECMA-262 and having two different kinds of intrinsics stored on the Realm would have been confusing.
```
----------  -----------------------------------  ---------  ---------------------------  ------------------------
SunSpider   3d-cube.js                               1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   3d-morph.js                              1      0.040 ± 0.040 … 0.040        0.040 ± 0.040 … 0.040
SunSpider   3d-raytrace.js                           1.071  0.050 ± 0.050 … 0.050        0.047 ± 0.040 … 0.050
SunSpider   access-binary-trees.js                   1 …
```

LibJS: Add a builtin for Math.abs

---

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/PNGLoader.h
Userland/Libraries/LibGfx/ImageFormats/PNGShared.h
Userland/Libraries/LibPDF/Filter.cpp
Userland/Libraries/LibPDF/Filter.h

C O D E   R E U S E, and also fixes a bug where the copy in LibPDF did this incorrectly.
Incrementally makes the LibPDF version look more like the LibGfx version until they look pretty similar and it's clear what the bug is, then switches LibPDF over to the LibGfx version in the last commit.

LibPDF: Use PNG unfilter code from LibGfx

---

Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

In the main page contents, /T0 might refer to a different font than it might refer to in an XObject. So don't use the `Tf` argument as font cache key. Instead, use the address of the font dictionary object.
Fixes false cache sharing, and also allows us to share cache entries if the same font dict is referred to by two different names.
Fixes a regression from 2340e834cd (but keeps the speed-up intact).

LibPDF: Use font dictionary object as cache key, not resource name

---

Documentation/BuildInstructionsLadybird.md
Ladybird/AppKit/main.mm

We call `[NSApp activateIgnoringOtherApps:YES]` to ensure the application
is brought into view and focused when launched from a terminal. But in
a macOS environment, we're better off using the `open` command to launch
the application (in which case, it does take foreground focus).

Ladybird/AppKit: Remove explicit application activation

---

Tests/LibWeb/Text/expected/get-bounding-client-rect.txt
Tests/LibWeb/Text/input/get-bounding-client-rect.html
Userland/Libraries/LibWeb/DOM/Element.cpp

This change fixes regressed Acid2 test and now we at least can see the face after clicking "Take The Acid2 Test" link.

LibWeb: Flesh out "scroll a target into view" spec implementation

---

Userland/Libraries/LibPDF/CMakeLists.txt
Userland/Libraries/LibPDF/CommonNames.h
Userland/Libraries/LibPDF/Fonts/PDFFont.cpp
Userland/Libraries/LibPDF/Fonts/PDFFont.h
Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp
Userland/Libraries/LibPDF/Fonts/SimpleFont.h
Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
Userland/Libraries/LibPDF/Fonts/TrueTypeFont.h
Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
Userland/Libraries/LibPDF/Fonts/Type0Font.h
Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
Userland/Libraries/LibPDF/Fonts/Type1Font.h
Userland/Libraries/LibPDF/Fonts/Type3Font.cpp
Userland/Libraries/LibPDF/Fonts/Type3Font.h
Userland/Libraries/LibPDF/Parser.cpp
Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

This is a very inefficient implementation: Every time a type 3 font
glyph is drawn, we parse its operator stream and execute all the
operators therein.
We'll want to instead cache the glyphs in bitmaps (at least in most
cases), like we do for other fonts. But it's a good first step, and
all the coordinate math seems to work in the files I've tested.
Good test files from pdfa dataset 0000.zip:
- `0000559.pdf` page 1 (and 2): Has a non-default font matrix;
text appears mirrored if the font matrix isn't handled correctly
- `0000425.pdf`, page 1: Draws several glyphs in a single run;
glyphs overlap if Renderer::render_type3_glyph() ignores the
passed-in point
- `0000211.pdf`, any page: Uses type 3 glyphs for all text.
Good perf test (already "reasonably fast")
- `0000521.pdf`, page 5 (or 7 or …

LibPDF: Add an initial implementation of type 3 glyph rendering

---

Userland/Libraries/LibPDF/CommonNames.h

The file wasn't quite decided if it wanted to sort by ascii value or by case folding. Now it uses ascii value, thanks to vim's `:'<,'>sort`.

LibPDF: Consistently asciibetize CommonNames.h

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
Userland/Libraries/LibPDF/Filter.cpp

This is a hack: Ideally we'd have a CMYK Bitmap pixel format, and we'd convert to rgb at blit time. Then we could also apply color profiles (which for CMYK images are CMYK-based).
Also, the colors for our CMYK->RGB conversion are off for PDFs, and we have distinct codepaths for this in Gfx::Color (for paths) and JPEGs. So when we fix that, we'll have to fix it in two places.
But this doesn't require a lot of code and it's a huge visual progression, so let's go with it for now.

LibPDF+LibGfx: Don't invert CMYK channels in JPEG data in PDFs

---

Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

This will not meaningfully affect short array literals, but it does give us a bit of extra perf when evaluating huge array expressions like in the Kraken imaging-* tests (where it eliminates KiBs of generated code)
```
Suite    Test                                   Speedup  Old (Mean ± Range)     New (Mean ± Range)
-------  -----------------------------------  ---------  ---------------------  ---------------------
Kraken   ai-astar.js                              1.011  1.144 ± 1.140 … 1.150  1.132 ± 1.120 … 1.140
Kraken   audio-beat-detection.js                  1.008  0.960 ± 0.950 … 0.980  0.952 ± 0.940 … 0.970
Kraken   audio-dft.js                             1.003  0.652 ± 0.650 … 0.660  0.650 ± 0.640 … 0.660
Kraken   audio-fft.js                             0.997  0.708 ± 0.690 … …
```

LibJS: Instantiate primitive array expressions using a single operation

---

Meta/Lagom/Fuzzers/FuzzBase64Roundtrip.cpp
Meta/Lagom/Fuzzers/FuzzGzipRoundtrip.cpp
Meta/Lagom/Fuzzers/fuzzers.cmake
Tests/AK/TestAllOf.cpp
Tests/AK/TestAnyOf.cpp
Tests/AK/TestBinaryHeap.cpp
Tests/AK/TestBinarySearch.cpp
Tests/AK/TestBitStream.cpp
Tests/AK/TestBitmap.cpp
Tests/AK/TestBuiltinWrappers.cpp
Tests/AK/TestCharacterTypes.cpp
Userland/Libraries/LibTest/Randomized/Generator.h
Userland/Utilities/test-fuzz.cpp

Let me know if you want some of these split into separate PRs!
I have more tests to write, I'm going through the current test suites alphabetically. Probably to come in separate PRs.
What I have right now:
> dec(enc(x)) == x
- LibCompress/Gzip - `decompress_all`, `compress_all` (fuzzer)
- AK/Base64 - `decode_base64`, `encode_base64` (fuzzer)
- AK/BitStream - `read_bits`, `write_bits` (randomized test, ⚠️ on a single call though, BitStream behaves weird when multiple reads and writes happen)
> my_impl(x) == definitely_correct_impl(x)
- CharacterTypes
- `isascii` == `is_ascii` in the UNICODE char range
- `tolower` == `to_ascii_lowercase` in the UNICODE char range
- `toupper` == `to_ascii_uppercase` in the UNICODE char range
> Safety = "doesn't do the wrong thing"
> Liveness = "does the …

AK, LibCompress: Add randomized tests

---

Userland/Applications/DisplaySettings/BackgroundSettingsWidget.cpp

The problem is that if the user selects an non-image file as their background, then at next startup the desktop crashes.
A simple fix of not allowing the user to select non-image file types works for now.
The only problem is if the user has a file with an extension not in the supported list but is in the form of a supported image file.
Please let me know is there is any tests that I can / should implement.
Thanks,
Lachlan Jowett.

DisplaySettings: Prevent user from making background non-image type

---

Ladybird/CMakeLists.txt
Meta/Azure/Lagom.yml
Userland/Utilities/headless-browser.cpp

When the `--dump-failed-ref-tests` flag is provided, screenshots of the actual and reference pages will be placed in
`Build/lagom/ladbybird/test-dumps`. This makes it a lot easier to spot what's wrong with a failing test. :^)

headless-browser: Add flag to dump screenshots of failing ref-tests

---

Userland/Shell/AST.cpp
Userland/Shell/ImmediateFunctions.cpp
Userland/Shell/PosixParser.cpp

Shell: Expand for loop's iterated expr before iterating over it

---

Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/Page/EventHandler.cpp

With these changes we no longer crash on Acid2 after reload button is pressed.

LibWeb: Fix crashing when reload button is pressed after fragment navigation

---

Userland/Libraries/LibLine/Editor.cpp

This is my attempt to fix #21978
If there's any suggestion on how we should fix this issue, please let me know.
Thank you
> While parsing DSR response, we might encounter invalid characters, for example, when we `cat` a binary file. Previously, we just pushed those characters in `m_incomplete_data` buffer, which worked fine until we didn't get a terminating character. We kept increasing coordinate value and crashed in following assertion.

LibLine: Reset state after invalid character in DSR response

---

AK/MaybeOwned.h
Userland/Libraries/LibGfx/Matrix4x4.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

The current set of stacking context commands do not encode the information needed to correctly paint the stacking context, instead, they're based on the limitations of the current CPU renderer.
Stacking contexts should be able to be transformed by an arbitrary 3D transformation matrix, not just scaled from a source to a destination rect. The `_with_mask()` stacking context also should not be separate from the regular stacking context.
```c++
push_stacking_context(
bool semitransparent_or_has_non_identity_transform,
float opacity, Gfx::FloatRect const& source_rect,
Gfx::FloatRect const& transformed_destination_rect,
Gfx::IntPoint const& painter_location);
pop_stacking_context(
bool semitransparent_or_has_non_identity_transform,
Gfx::Painter::ScalingMode scaling_mode); …
```

LibWeb: Don't encode painting limitations in RecordingPainter API

---

Tests/LibWeb/Text/expected/Streams/ReadableStreamBYOBReader-read.txt
Tests/LibWeb/Text/input/Streams/ReadableStreamBYOBReader-read.html
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.h
Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.h
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.idl

This series of commits builds up to implementing reading into TypedArray buffers for BYOB streams (data views are still to be supported). I've been slowly chipping away at this in other MRs for a while - this MR finally gets us to the level where we can start adding tests for our BYOB support.

LibWeb: (partially) Implement ReadableStreamBYOBReader::read

---

Tests/LibPDF/type3.pdf

A manual test, but better than nothing.
I hand-wrote the file, and used mutool to fix up xref and stream lengths:
mutool clean Tests/LibPDF/type3.pdf Tests/LibPDF/type3.pdf
The file contains one `d1` character which per spec shouldn't contain color statements, and if it does it should be ignored, and one `d0` character which can contain color.
The text then sets a color before rendering the text.
Per spec, the text color should affect the `d1` character but not the `d0` one. We get this wrong, but so does Preview.app. (PDFium gets it right.)
But independent of the colors, just rendering the glyphs at all at the right position is already good :^)

Tests: Add a type3 test pdf

---

Userland/Libraries/LibGfx/Path.cpp

As suggested by @DanShaders this fixes a crash on macOS without messing up with the compiler flags.
This avoids rounding problems which made Ladybird crash with some SVGs on macOS/Clang.
When opening `https://warpdesign.fr/tests/crash.svg` this now display the same thing as Chrome instead of crashing.
Ladybird
Chrome
Fixes #21723

LibGfx/Path: Round numerator in elliptical_arc_to

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/Runtime/ExecutionContext.h

This one was hard to benchmark for me again, since the benchmarks didn't have meaningful differences (i might need to lock the CPU frequency or something). So here is a synthetic benchmark:
```js
for(let n = 0.0; n < 1000000000; n+=2) {
}
```
PR:
```
Benchmark 1: js ./test.js
Time (mean ± σ):      3.422 s ±  0.019 s    [User: 3.411 s, System: 0.002 s]
Range (min … max):    3.401 s …  3.466 s    10 runs
```
Master:
```
Benchmark 1: js ./test.js
Time (mean ± σ):     21.617 s ±  0.277 s    [User: 21.538 s, System: 0.007 s]
Range (min … max):   21.305 s … 22.208 s    10 runs
```

LibJS/JIT: Add fastpath for set variable

---

Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.cpp
Userland/Libraries/LibWeb/DOM/EventTarget.h
Userland/Libraries/LibWeb/DOM/MutationObserver.cpp
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
Userland/Libraries/LibWeb/HTML/HTMLButtonElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLButtonElement.h
Userland/Libraries/LibWeb/HTML/HTMLElement.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLSlotElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLSlotElement.h
Userland/Libraries/LibWeb/HTML/HTMLSummaryElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLSummaryElement.h

tl;dr a bunch of incremental changes that add up to making `HTMLDivElement` take 456 bytes (down from 896 bytes, so just over 50% reduction in size)
Given that each HeapBlock has 4032 bytes of usable space, this means we can fit 8 divs per block now, up from 4 before.

LibWeb: Make DOM elements use less memory

---

Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/Tests/try-return-finally.js

LibJS/JIT: Continue to outer `finally` before returning

---

Kernel/FileSystem/Ext2FS/Inode.cpp
Kernel/FileSystem/Inode.cpp

When the FileSystem does a sync, it gathers up all the inodes with dirty metadata into a vector. The inode mutex is not held while checking the inode dirty bit, which can lead to a kernel panic due to concurrent inode modifications.
Fixes: #21796
This is my first Serenity contribution, so let me know if I'm missing something important!

Kernel/FS: Fix check-then-act concurrency bug in FileSystem/Inode

---

Userland/Libraries/LibJS/AST.h
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp

Alternative implementation of #21998

LibJS: Cache bytecode executables on the corresponding AST nodes

---

Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/Painting/BorderPainting.cpp
Userland/Libraries/LibWeb/Painting/BorderPainting.h
Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
Userland/Libraries/LibWeb/Painting/BordersData.cpp
Userland/Libraries/LibWeb/Painting/BordersData.h
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp

These changes introduce new special painting command for borders and add simple implementation for GPU executor that does not support corner radius.

LibWeb: Add basic borders painting support in GPU executor

---

Userland/Shell/PosixParser.cpp

This fixes an unfortunate typo where we would parse the `OR_IF` token as an `AST::And` node. Now, it is parsed into an `AST::Or` node :^).
This fixes #19324.

Shell/PosixParser: Correctly parse the OR_IF token

---

Tests/LibWeb/Text/expected/MutationObserver/removing-a-node.txt
Tests/LibWeb/Text/input/MutationObserver/removing-a-node.html
Userland/Libraries/LibWeb/DOM/Node.cpp

Instead of blindly dereferencing m_registered_observer_list, just use the add_registered_observer() helper.
Fixes #22005

LibWeb: Fix null pointer dereference in DOM::Node::remove()

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

With basic PushStackingContext and PopStackingContext commands implementation scrolling works again after changes being made in: https://github.com/SerenityOS/serenity/commit/4e04f81626cf3a5e1bea52ae26bb17f40695ad78

LibAccelGfx+LibWeb: Fix scrolling in GPU painter

---

Meta/Lagom/Contrib/MacPDF/MacPDFOutlineViewDataSource.mm
Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm

* Use correct(ish) encoding
* Show tooltip with full title when it's elided
* Less janky look for outline titles with newlines

MacPDF: Three outline fixes

---

Tests/LibWeb/Layout/expected/font-size-legacy.txt
Tests/LibWeb/Layout/expected/table/internal-alignment.txt
Tests/LibWeb/Layout/expected/table/nested-table-alignment.txt
Tests/LibWeb/Layout/expected/table/table-align-center-with-margin.txt
Tests/LibWeb/Layout/expected/table/table-align-center.txt
Tests/LibWeb/Layout/expected/table/table-cellpadding.txt
Tests/LibWeb/Layout/expected/table/tr-valign.txt
Tests/LibWeb/Layout/input/font-size-legacy.html
Tests/LibWeb/Layout/input/table/internal-alignment.html
Tests/LibWeb/Layout/input/table/nested-table-alignment.html
Tests/LibWeb/Layout/input/table/table-align-center-with-margin.html
Tests/LibWeb/Layout/input/table/table-align-center.html
Tests/LibWeb/Layout/input/table/table-cellpadding.html
Tests/LibWeb/Layout/input/table/tr-valign.html
Tests/LibWeb/Ref/body-link-attribute.html
Tests/LibWeb/Ref/reference/body-link-attribute-ref.html
Userland/Libraries/LibWeb/CSS/StyleValues/IdentifierStyleValue.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/HTML/HTMLFontElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLTableElement.h
Userland/Libraries/LibWeb/HTML/HTMLTableRowElement.cpp

Visual progression on http://www.slackware.com:
Before:
After:

LibWeb: Improvements to table layout

---

Tests/LibWeb/Layout/expected/css-values/rect-non-token-contents-crash.txt
Tests/LibWeb/Layout/expected/grid/grid-area-non-token-parts-crash.txt
Tests/LibWeb/Layout/expected/grid/grid-column-non-token-parts-crash.txt
Tests/LibWeb/Layout/expected/grid/grid-row-start-non-token-parts-crash.txt
Tests/LibWeb/Layout/expected/grid/minmax-non-token-contents-crash.txt
Tests/LibWeb/Layout/expected/grid/repeat-non-token-contents-crash.txt
Tests/LibWeb/Layout/input/css-values/rect-non-token-contents-crash.html
Tests/LibWeb/Layout/input/grid/grid-area-non-token-parts-crash.html
Tests/LibWeb/Layout/input/grid/grid-column-non-token-parts-crash.html
Tests/LibWeb/Layout/input/grid/grid-row-start-non-token-parts-crash.html
Tests/LibWeb/Layout/input/grid/minmax-non-token-contents-crash.html
Tests/LibWeb/Layout/input/grid/repeat-non-token-contents-crash.html
Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp

It's rare that we'd encounter invalid CSS in the wild, but we shouldn't crash when we do!
This fixes several cases where we blindly get the Token from a ComponentValue, without checking that it's holding a Token first.
Also, use the `is_function("..."sv)` and `is_ident("..."sv)` helper methods more, which is what made me notice the incorrectness in the first place. They simplify things so the code is more readable.

LibWeb: Stop a bunch of CSS parser crashes from invalid inputs

---

Userland/Libraries/LibPDF/Parser.cpp

Necessary to be able to open and render
https://github.com/pdf-association/pdf20examples/blob/master/pdf20-utf8-test.pdf

LibPDF: Tolerate comment after last dict item and before drawing operators

---

Tests/LibWeb/Text/expected/IntersectionObserver/unobserve-element-without-matching-observe.txt
Tests/LibWeb/Text/input/IntersectionObserver/unobserve-element-without-matching-observe.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
Userland/Libraries/LibWeb/IntersectionObserver/IntersectionObserver.h

It's perfectly possible for JavaScript to call unobserve() on an element
that hasn't been observed. Let's stop asserting if that happens. :^)
Fixes #22020

LibWeb: Don't assume IO.unobserve() called on observed element

---

Userland/Libraries/LibGfx/Bitmap.h
Userland/Libraries/LibPDF/Renderer.cpp

SMasks are greyscale images that get used as alpha channel for a different image.
JPEGs in PDFs are stored as streams with /DCTDecode filters, and we have a separate code path for loading those in the PDF renderer. That code path just calls our JPEG decoder, which creates bitmaps with format BGRx8888.
So when we process an SMask for such a bitmap, we have to change the bitmap's format to BGRA8888 in addition to setting alpha values on all pixels.

LibPDF+LibGfx: Make SMasks on jpeg images work

---

Userland/Libraries/LibAudio/WavWriter.cpp
Userland/Libraries/LibAudio/WavWriter.h

We were calling write syscall twice for every sample, which effectively hurt the writer's performance.
With this change exporting a melody in the Piano app now takes less than a second, which previously took about 20 seconds on my machine.
Additionally, I've removed an unused `WavWriter::file()` getter.

LibAudio: Speed up WavWriter by buffering output data

---

AK/Complex.h
Tests/AK/TestComplex.cpp

There were two issues:
1) the `C+=R` and `C-=R` operators expected arithmetic types to have `.real()`
2) the `R+C`, `R-C`, `R*C` and `R/C` operators applied the operation in wrong
order (did `C+R`, `C-R`, `C*R` and `C/R` instead). This wouldn't matter for
`+` and `*` which are commutative, but is incorrect for `-` and `/`.

AK: Fix bugs in Complex += -= + - * / operators

---

Userland/Libraries/LibAccelGfx/Canvas.h
Userland/Libraries/LibAccelGfx/GL.cpp
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibAccelGfx/Program.cpp
Userland/Libraries/LibAccelGfx/Program.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Services/WebContent/PageHost.cpp
Userland/Services/WebContent/PageHost.h

For each stacking context with an opacity less than 1, we create a
separate framebuffer. We then blit the texture attached to this
framebuffer with the specified opacity.
To avoid the performance overhead of reading pixels from the texture
into Gfx::Bitmap, a new method that allows for direct blitting from
the texture is introduced, named blit_scaled_texture().

LibAccelGfx+LibWeb: Add support for stacking context opacity

---

AK/Span.h
Base/res/html/misc/worker.js
Base/res/html/misc/worker_parent.html
Tests/LibWeb/Text/expected/Worker/Worker-echo.txt
Tests/LibWeb/Text/input/Worker/Worker-echo.html
Tests/LibWeb/Text/input/Worker/worker.js
Tests/LibWeb/Text/input/include.js
Userland/Libraries/LibWeb/HTML/Worker.cpp
Userland/Libraries/LibWeb/HTML/Worker.h
Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp
Userland/Libraries/LibWeb/HTML/WorkerAgent.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.idl
Userland/Services/WebWorker/ConnectionFromClient.cpp
Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Userland/Services/WebWorker/DedicatedWorkerHost.h

This implementation completely ignores MessagePorts, and manually plumbs
data through LocalSockets.

LibWeb+WebWorker: Implement a first cut of post_message for Workers 

---

Userland/Libraries/LibGfx/Font/OpenType/DataTypes.h
Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp
Userland/Libraries/LibGfx/Font/WOFF/Font.cpp
Userland/Libraries/LibGfx/Font/WOFF2/Font.cpp
Userland/Libraries/LibGfx/FourCC.h
Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp

A fairly minor change, but does make the code a little nicer.

LibGfx: Use the FourCC struct for OpenType tags

---

Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h

CSSNamespaceRule returns a copy of a DeprecatedString, meaning that the view returned by the namespace in CSSStyleSheet is into a temporary string.

LibWeb: Fix UAF in CSSStyleSheet

---

Userland/Games/Spider/CMakeLists.txt
Userland/Games/Spider/Game.cpp
Userland/Games/Spider/Game.h
Userland/Games/Spider/MainWidget.h
Userland/Games/Spider/Spider.gml
Userland/Games/Spider/main.cpp
Userland/Libraries/LibCards/Card.cpp
Userland/Libraries/LibCards/Card.h
Userland/Libraries/LibCards/CardPainter.cpp
Userland/Libraries/LibCards/CardPainter.h
Userland/Libraries/LibCards/CardStack.cpp
Userland/Libraries/LibCards/CardStack.h

Previously, it was sort of difficult to tell which cards can be moved at a glance. Now, the cards that can't be moved are rendered darker, which makes it much easier to tell what can be moved and to where, making the game a bit easier on the eyes!
This is done by rendering a rectangle with a transparent color on top of the card images in `CardPainter`. `Card`s now keep track of whether they are "disabled", in which case they are rendered darker as shown above. I then added a helper in `CardStack` to update that flag depending on a given `MovementRule`. This works by searching for the last card that is in order from the bottom up, and making all cards above disabled.
In addition, I also added a small helper in `CardPainter` that makes painting and accessing the caches a bit easier, and I …

Spider: Highlight cards that can't be moved

---

AK/StdLibExtras.h
Meta/CMake/common_compile_options.cmake
Userland/Libraries/LibJS/Bytecode/Builtins.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/Runtime/MathObject.cpp
Userland/Libraries/LibJS/Runtime/MathObject.h

Note that none of the builtins being added here have machine code fast paths (yet).
We still gain a nice improvement simply by avoiding the heavy function call setup (ExecutionContext, etc)
2.917x on Kraken/audio-oscillator.js is notable :smile:
```
Kraken      ai-astar.js                              1.012  0.860 ± 0.860 … 0.860        0.850 ± 0.850 … 0.850
Kraken      audio-beat-detection.js                  1.045  0.465 ± 0.460 … 0.470        0.445 ± 0.440 … 0.450
Kraken      audio-dft.js                             1      0.345 ± 0.340 … 0.350        0.345 ± 0.340 …
```

LibJS/JIT: Add more Math builtins

---

Kernel/Arch/riscv64/linker.ld

The linker would otherwise put those sections after `end_of_kernel_image`.
These `.s*` "small data" sections don't seem to exist for x86_64 and aarch64, so only include them in the riscv64 linker script.

Kernel/riscv64: Add missing input sections to linker script

---

Kernel/CMakeLists.txt

This is necessary for being able to use the qemu `-kernel` option. The QEMU virt machine uses OpenSBI's FW_DYNAMIC feature to pass the kernel entry address, which is the virtual entry point address specified in the kernel ELF. If we instead `objcopy` the kernel into a raw binary, OpenSBI will jump to the physical kernel load address, which is what we want it to do.

Kernel/riscv64: Generate Kernel.bin from kernel ELF

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Meta/gn/build/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibWeb/WebIDL/BUILD.gn

This matches the negation of the vertical scroll delta value. This makes
the scroll events behave as follows on macOS:
Natural scrolling enabled:
* Scrolling up on the trackpad scrolls down on the page.
* Scrolling right on the trackpad scrolls left on the page.
Natural scrolling disabled:
* Scrolling up on the trackpad scrolls up on the page.
* Scrolling right on the trackpad scrolls right on the page.
Fixes #21749

Ladybird/AppKit: Invert the horizontal delta scroll value 

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
Ladybird/AppKit/UI/LadybirdWebViewBridge.h
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Services/WebContent/PageHost.cpp

Ran into some funky scrolling behavior in the inspector, seen here:
https://github.com/SerenityOS/serenity/assets/5600524/509d4778-42ac-45a0-a4ce-05c078beafc1
With these, we handle scrolling to the inspected element in the inspector better:
https://github.com/SerenityOS/serenity/assets/5600524/72637ba4-c6d9-461d-b92b-ab8ef5f34b94

LibWeb+LibWebView: A couple of scrolling fixes

---

AK/JsonObject.cpp
AK/JsonObject.h
Userland/Applications/Browser/InspectorWidget.cpp
Userland/Applications/Maps/FavoritesPanel.cpp

Previously, we were returning an empty optional if key contained a numerical value which was not stored as double. Stop doing that and rename the method to signify the change in the behavior.
Apparently, this fixes bug in an InspectorWidget in Ladybird on Serenity: it showed 0 for element's boxes with integer sizes.
-------
Other `get_x` methods fail if numerical value stored in `JsonValue` is out of range for the expected type. So method rename, while not strictly necessary, makes JsonObject API somewhat more consistent.  It also now explicitly signify possible precision loss, which aligns with my plans of enabling FP conversion warnings and making all FP precision casts explicit.
The patch also removes one more user of questionable `JsonValue::{is,as}_{double,i32,u32,i64,u64}` APIs.

AK+Applications: Return value from JsonObject::get_double more often (and fix Inspector on Serenity)

---

Tests/LibWeb/Text/expected/anchor-element-with-javascript-url-href.txt
Tests/LibWeb/Text/input/anchor-element-with-javascript-url-href.html
Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp

This early return is no longer needed because Navigable::navigate() can process `javascript:` urls.
Fixes https://github.com/SerenityOS/serenity/issues/22052

LibWeb: Remove exit for javascript urls in anchor activation_behavior()

---

Kernel/Net/LoopbackAdapter.cpp
Kernel/Syscalls/socket.cpp

The first commit fixes https://github.com/SerenityOS/serenity/issues/21793, the second commit fixes a different bug I encountered while testing the first one.

Kernel: Treat a backlog argument of 0 to listen() as if it was 1

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Runtime/TypedArray.h

Solid improvement on Octane (`gbemu.js`, `mandreel.js` and `zlib.js` specifically)
```
----------  -----------------------------------  ---------  ---------------------------  ------------------------
Kraken      ai-astar.js                              0.994  0.850 ± 0.850 … 0.850        0.855 ± 0.840 … 0.870
Kraken      audio-beat-detection.js                  1      0.445 ± 0.440 … 0.450        0.445 ± 0.440 … 0.450
Kraken      audio-dft.js                             1      0.345 ± 0.340 … 0.350        0.345 ± 0.340 … 0.350
Kraken      audio-fft.js                             1.016  0.325 ± 0.320 … 0.330        0.320 ± 0.320 … 0.320
Kraken      audio-oscillator.js …
```

LibJS: Add common fast paths for GetByValue and PutByValue with TypedArray

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibGfx/CMakeLists.txt
Userland/Libraries/LibGfx/Forward.h
Userland/Libraries/LibGfx/ImmutableBitmap.cpp
Userland/Libraries/LibGfx/ImmutableBitmap.h
Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.cpp
Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.h
Userland/Libraries/LibWeb/HTML/DecodedImageData.h
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
Userland/Libraries/LibWeb/Layout/ImageProvider.h
Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h

This change introduces a texture cache for immutable bitmaps in the
GPU painter. The cache is persisted across page repaints, so now, on
page scroll repaint, in many cases, we won't need to upload any new
textures. Also, if the same image is painted more than once on a page,
its texture will only be uploaded once.
Generally, the GPU painter works much faster with this change on all
pages that have images.

LibAccelGfx+LibWeb: Add texture cache for immutable bitmaps

---

Userland/Libraries/LibWeb/WebIDL/AbstractOperations.cpp

No longer throws after abcf71a8ca169d8dec43c7da4028349d57c45e55.

LibWeb: Remove now-unneeded TypedArray OOM propagation

---

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLImageElement.h

Fixes crashing on https://discord.com/login

LibWeb: Add missing nullptr check in `HTMLImageElement::bitmap()`

---

Userland/Libraries/LibAccelGfx/CMakeLists.txt
Userland/Libraries/LibAccelGfx/GlyphAtlas.cpp
Userland/Libraries/LibAccelGfx/GlyphAtlas.h
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

This change noticeably improves GPU painter performance on many websites.

LibAccelGfx: Skip glyph atlas rebuild if all needed glyphs are present 

---

Userland/Libraries/LibPDF/Renderer.cpp

Page 1 of 0000277.pdf does:
BT 22 0 0 22  59  28 Tm /TT2 1 Tf
(Presented at Photonics West OPTO, February 17, 2016) Tj ET
BT 32 0 0 32 269 426 Tm /TT1 1 Tf
(Robert W. Boyd) Tj ET
BT 22 0 0 22 253 357 Tm /TT2 1 Tf
(Department of Physics and) Tj ET
BT 22 0 0 22 105 326 Tm /TT2 1 Tf
(Max-Planck Centre for Extreme and Quantum Photonics) Tj ET
Every line begins a text operation, then updates the font matrix,
selects a font (TT2, TT1, TT2, TT1), draws some text and ends the text
operation.
`Tm` (which sets the font matrix) contains a scale, and uses that
to update the font size of the currently-active font (cf #20084).
But in this file, we `Tm` first and `Tf` (font selection) second,
so this updates the size of the old font. So when we pull it out
of the cache again on line 3, it would still …

LibPDF: Update font size after getting font from cache

---

Userland/Libraries/LibCrypto/Hash/HashManager.h
Userland/Libraries/LibTLS/Handshake.cpp
Userland/Libraries/LibTLS/HandshakeClient.cpp
Userland/Libraries/LibTLS/HandshakeServer.cpp
Userland/Libraries/LibTLS/TLSv12.h

While trying to figure out why a specific website was not working with LibTLS, I got convinced that we were missing an extension which the server required. The `extended_master_secret` extension was the only one not implemented in LibTLS, which was implemented in curl. So, I implemented this extension for LibTLS. In the end this extension was not actually the problem, but now we have an implementation anyway. :^)
The only thing I'm not quite sure about is adding the `copy()` method to `Crypto::Hash::Manager`. This is required as I need `m_context.handshake_hash` without modifying it. If there is a nicer way I would love to change this.

LibTLS: Implement the `extended_master_secret` extension

---

Meta/Lagom/CMakeLists.txt
Meta/Lagom/Contrib/VideoPlayerSDL/CMakeLists.txt
Meta/Lagom/Contrib/VideoPlayerSDL/main.cpp

Adds a simple SDL2 application for testing `LibVideo` on the host system / via lagom.
I chose `Meta/Lagom/Contrib` as the directory, since `MacPDF` sits there aswell

Meta: Add a minimal SDL2 based videoplayer for Lagom

---

Kernel/Syscalls/execve.cpp
Userland/DynamicLoader/main.cpp
Userland/Libraries/LibELF/DynamicLinker.cpp
Userland/Libraries/LibELF/DynamicObject.cpp
Userland/Libraries/LibELF/DynamicObject.h

When we run directly the dynamic loader, we shouldn't rely on the passed program path to be run, but rather on whether the main program fd number is not -1, because the kernel will set it to a non-negative number if it exists.
To test that the heuristic is working correctly, the /usr/lib/Loader.so file can be copied to /tmp/Loader.so and then be invoked from that path.

DynamicLoader: Make heuristic for running directly actually correct

---

Kernel/Arch/init.cpp
Kernel/Boot/CommandLine.cpp
Meta/build-root-filesystem.sh

This doesn't affect system functionality, but somewhat reduces the
reliance on complicated hardcoded paths. It also allows the user to
simply link /init (which is normally a symbolic link) to another program
to run it instead of SystemServer as the default option.
This kind of functionality is present on linux systems, and is considered a good preparation if we want an init(ram)fs functionality as well.
Old filesystems such as [BFS](https://www.kernel.org/doc/html/latest/filesystems/bfs.html) (known as BootFS, not to be confused with BeFS from BeOS) also don't support directories, so if we choose that filesystem or another simplistic design for an initramfs (so we can simply don't care about directories), this can help as well.

Kernel: Switch init boot argument to "/init"

---

Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
Userland/Libraries/LibWeb/Painting/AudioPaintable.cpp
Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
Userland/Libraries/LibWeb/Painting/CanvasPaintable.cpp
Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp
Userland/Libraries/LibWeb/Painting/FilterPainting.cpp
Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintContext.cpp
Userland/Libraries/LibWeb/Painting/PaintContext.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/ProgressPaintable.cpp
Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.cpp
Userland/Libraries/LibWeb/Painting/SVGPathPaintable.cpp
Userland/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Userland/Libraries/LibWeb/Painting/TableBordersPainting.cpp
Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp
Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp

Using recording_painter() as a name is less misleading, indicating the painter in stacking context traversal doesn't perform actual painting commands.

LibWeb: Rename painter() to recording_painter() in PaintContext

---

AK/String.cpp
Tests/AK/TestString.cpp

If we assign to an existing non-short string, we must dereference its StringData object to prevent leaking that data.

AK: Ensure assigned-to Strings are dereferenced if needed

---

AK/Optional.h

This is an extension of cc0b970d but for the reference-handling specialization of Optional.
This basically allow us to write code like:
```cpp
Optional<u8&> opt;
opt = OptionalNone{};
```
@alimpfard

AK: Allow `Optional<T&>` to be constructed by `OptionalNone()`

---

Userland/Libraries/LibCrypto/Curves/SECPxxxr1.h
Userland/Libraries/LibTLS/TLSv12.cpp

There are some websites (for example https://www.valleiautogroep.nl/) which supply SECP384r1 certificates where the signature is over a SHA256 hash. With the current implementation of the verify method this would fail as it expected the hash size to equal the curve size. With this PR we now accept any hash size in the verify method.
Additionally I have included a small change to the logging of invalid root certificates so that it actually logs the subject of the root certificate which is invalid. Instead of just printing "Certificate for  by  is invalid, ...".

LibCrypto: Fix verification of SECP384r1 certificate with SHA256 hash

---

Userland/Libraries/LibAccelGfx/Painter.cpp

Fixes memory leak in fill_rect_with_linear_gradient()

LibAccelGfx: Deallocate VAO and VBOs in fill_rect_with_linear_gradient

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h

This change ensures that the GPU painting executor follows the pattern of the CPU executor, where the state is stored for each stacking context, but a painter is created only for those with opacity.
Fixes crashing on apple.com because now save() and restore() are called on correct painters.

LibAccelGfx+LibWeb: Store state of all stacking contexts in GPU painter

---

Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp

In OpenGL newly allocated texture has undefined initial state so we need to clear it before stacking context painting.

LibWeb: Clear texture allocated for stacking context painting

---

Userland/Libraries/LibVideo/CodecID.h
Userland/Libraries/LibVideo/Containers/Demuxer.h
Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.cpp
Userland/Libraries/LibVideo/Containers/Matroska/MatroskaDemuxer.h
Userland/Libraries/LibVideo/Containers/Matroska/Reader.cpp
Userland/Libraries/LibVideo/PlaybackManager.cpp

This is required for detecting which decoder should be used. Only a small subset of codecs identifiers is added for now

LibVideo: Add the concept of codec identifiers

---

Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp

If `SkipStackingContext` is returned we also need to restore saved painter state because corresponding pop_stacking_context command that is supposed to do that will be skipped.
Fixes https://github.com/SerenityOS/serenity/issues/22092

LibWeb: Restore painter state if push_stacking_context() has failed

---

Kernel/Arch/init.cpp

Other arches don't use the prekernel, so don't try to unmap it on non-x86 platforms.
For some reason, this didn't cause aarch64 to crash, but on riscv64 this would cause a panic.

Kernel: Only unmap prekernel on x86_64

---

Kernel/Prekernel/init.cpp
Kernel/Syscalls/execve.cpp
Kernel/Syscalls/mmap.cpp
Kernel/Tasks/Coredump.cpp
Kernel/Tasks/Process.h
Userland/Libraries/LibC/link.h
Userland/Libraries/LibELF/DynamicLinker.cpp
Userland/Libraries/LibELF/DynamicLoader.cpp
Userland/Libraries/LibELF/DynamicLoader.h
Userland/Libraries/LibELF/DynamicObject.cpp
Userland/Libraries/LibELF/DynamicObject.h
Userland/Libraries/LibELF/ELFABI.h
Userland/Libraries/LibELF/Image.cpp
Userland/Libraries/LibELF/Image.h
Userland/Libraries/LibELF/Relocation.cpp
Userland/Libraries/LibELF/Validation.cpp
Userland/Libraries/LibELF/Validation.h
Userland/Utilities/file.cpp
Userland/Utilities/ldd.cpp
Userland/Utilities/readelf.cpp

This works around a `clang-format-17` bug which caused certain usages to
be misformatted and fail to compile.
Fixes https://github.com/SerenityOS/serenity/issues/8315

Everywhere: Replace `ElfW(type)` macro usage with `Elf_type`

---

Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h

This change introduces GPU painter support for rotate(), skew(), scale(), and other transformations that could be applied to stacking context.

LibAccelGfx+LibWeb: Support non-translation transforms in GPU painter

---

AK/BitStream.h
Tests/AK/TestBitStream.cpp
Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp

With the exception of [WebP](https://chromium.googlesource.com/webm/libwebp/+/24d7f9cb6ef1ef90a04d7b6c15d3477813f75ee0/src/utils/bit_reader_utils.c#220), being able to read null bits beyond the end of a Stream is almost always unintentional and can lead to infinite loops if `0` isn't the "end of stream" symbol by accident.
Fixes #21869.
Fixes [oss-fuzz issue 58046](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58046).
Fixes [oss-fuzz issue 62111](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62111).
Supersedes #18448.

AK: Reject BitStream reads beyond EOF

---

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Runtime/MathObject.cpp
Userland/Libraries/LibJS/Runtime/MathObject.h
Userland/Libraries/LibJS/Runtime/Realm.h

Allows the bytecode interpreter to call the builtins c++ implementation directly without making a javascript call just as the JIT.
Kraken test speedups: imaging-gaussian-blur.js (1.5x) and audio-oscillator.js (1.2x)

LIBJS: Call builtins directly in the bytecode interpreter

---

.github/workflows/cmake.yml

These tests almost always fail, and all we do is try to boot. Disable it for now until it can pass more reliably. Note we still compile aarch64, so the build shouldn't break unnoticed.

CI: Disable running aarch64 tests in CI for now

---

Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.cpp
Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.h
Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp

This removes a performance problem where we'd convert the style sheet's default namespace from DeprecatedFlyString to FlyString once per rule during selector matching.
The conversion now happens once, during CSS parse. It should eventually be removed from there as well, but one step at a time. :^)

LibWeb: Port CSSNamespaceRule to FlyString

---

Kernel/FileSystem/RAMFS/FileSystem.cpp
Kernel/FileSystem/RAMFS/FileSystem.h
Kernel/FileSystem/RAMFS/Inode.cpp
Userland/Libraries/LibCore/DirectoryEntry.cpp

- Fixes `echo /tmp/*/`
- Fixes a tiny boog in `Core::DirectoryEntry`

Kernel: Make RAMFS pass along the inode type when traversing as a dir

---

Userland/Libraries/LibWeb/CSS/CSSFontFaceRule.cpp
Userland/Libraries/LibWeb/CSS/CSSImportRule.cpp
Userland/Libraries/LibWeb/CSS/CSSImportRule.h
Userland/Libraries/LibWeb/CSS/CSSMediaRule.cpp
Userland/Libraries/LibWeb/CSS/CSSRule.h
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleRule.h
Userland/Libraries/LibWeb/CSS/MediaList.cpp
Userland/Libraries/LibWeb/CSS/MediaQueryList.cpp
Userland/Libraries/LibWeb/CSS/MediaQueryList.h
Userland/Libraries/LibWeb/CSS/Serialize.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleSheet.h
Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/ShadowStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/URLStyleValue.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
Userland/Libraries/LibWeb/DOM/StyleElementUtils.h
Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp

Assuming CLion isn't lying to me, this is all the uses of `Deprecated[Fly]String` in the LibWeb/CSS dir except for the Parser. (And also in `create_a_css_style_sheet()`, which maybe should be in the CSS dir too but that's a side issue.) No functional changes, just less deprecation.
It did mean I came across this, which made me chuckle:
```c++
return String::from_deprecated_string(m_media->media_text().to_deprecated_string()).release_value();
```

LibWeb: De-deprecate some CSS Strings

---

Userland/Libraries/LibGfx/ImageFormats/ILBMLoader.cpp

Multiplying two u16s will result in a i32 sized result, which will overflow to negative values for large input values.
Fixes ossfuzz-64198.

LibGfx: Eliminate multiplication integer overflow in planar_to_chunky

---

Userland/Libraries/LibPDF/Document.h

Since all parents held a reference pointer to their children, and all children held reference pointers to their parents, both objects would never get free'd once the document was no longer being used.
Fixes ossfuzz-63833.

LibPDF: Eliminate reference cycle between OutlineItem parent/children

---

Userland/Libraries/LibGfx/ICC/TagTypes.h
Userland/Libraries/LibPDF/Function.cpp

`lerp_nd()` is very similar to PDF::SampleFunction::evaluate(). But we
know that the result is a FloatVector3 in the ICC code (at least for
now), so we can save a bunch of redundant computation by returning
all three channels of the LUT at once.
This is enough for images using mAB with A curve / CLUT if the
profile connecting space is PCSXYZ, such as for Upper_Right.jpg
from https://www.color.org/version4html.xalter like so:
% Build/lagom/icc --name sRGB --reencode-to serenity-sRGB.icc
% Build/lagom/bin/image -o out.png \
--convert-to-color-profile serenity-sRGB.icc \
~/Downloads/Upper_Right.jpg
---
Also clean up the very similar code in SampleFunction::evaluate().

LibGfx/ICC: Support for A curves and CLUT in LutAToBTagData::evaluate()

---

Tests/LibWeb/Text/expected/Streams/ReadableByteStream-enqueue-respond.txt
Tests/LibWeb/Text/input/Streams/ReadableByteStream-enqueue-respond.html
Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.h
Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.idl
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.h
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.idl

This continues the work towards more full / usable support for readable byte streams and BYOB readers, adding support for enqueuing data onto a readable byte stream controller, and responding to a BYOB requests.

LibWeb: Implement ReadableStreamBYOBRequest.respond and ReadableByteStreamController.enqueue

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

The second commit fixes the ⧄ that you can see on both images of #22139

LibGfx/TIFF: Support String-based tags

---

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

Fixes regression introduced in:
https://github.com/SerenityOS/serenity/commit/681771d2108a6f82c138f1dbccc2a2d2ef5abae7

LibWeb/Painting: Use scaled font for selected text

---

Tests/LibWeb/Text/expected/DOM/TreeWalker-nextNode-with-detached-currentNode.txt
Tests/LibWeb/Text/input/DOM/TreeWalker-nextNode-with-detached-currentNode.html
Userland/Libraries/LibWeb/DOM/TreeWalker.cpp

This fixes a hang on https://reddit.com/
Spec bug: https://github.com/whatwg/dom/issues/1102

LibWeb: Don't get stuck in TreeWalker.nextNode() when current detached

---

Userland/Libraries/LibAccelGfx/GL.cpp
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp

With this change we match blending in LibGfx and it fixes rendering on all websites that use opacity < 1.
Webpage that renders text and box using rgba(0, 0, 0, 0.5) color.
Before:
After:

LibAccelGfx: Set blending for alpha separately to be sum of src and dst

---

Ladybird/AppKit/UI/LadybirdWebView.h
Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/AppKit/UI/Tab.mm

~~Use correct readable light/dark theme for top level browser UI when theme color is set. This results in always readable UI. As you can see the system theme is not used anymore it is purely set by the luminance of the theme color.~~
This removes the theme color changing background color because it is annoying.
I also used `gfx_color_to_ns_color` to clean up the code a bit.
This closes #21394 🥳

Ladybird/AppKit: Remove theme color changing background color

---

Userland/Services/WebWorker/DedicatedWorkerHost.cpp

Now, a load of `chat.openai.com` gives information that a blob url is the reason for failure to load the page:
```
ResourceLoader: Starting load of: "https://chat.openai.com/"
ResourceLoader: Failed load of: "https://chat.openai.com/", Error: Load failed: 403, Duration: 129ms
ResourceLoader: Starting load of: "https://chat.openai.com/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=830774141f30538c"
HTMLScriptElement: Refusing to run script because the src URL ':' is invalid.
ResourceLoader: Finished load of: "https://chat.openai.com/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=830774141f30538c", Duration: 4985ms
ResourceLoader: Starting load of: "https://chat.openai.com/favicon.ico"
ResourceLoader: Failed load of: "https://chat.openai.com/favicon.ico", Error: Load …
```

WebWorker: Log URL and reason for Worker script load failure

---

Userland/Libraries/LibAccelGfx/Painter.cpp

Since scissor clip rect is a part of OpenGL global state we need to update it after switching between painters.

LibAccelGfx: Update scissor test after switching between painters

---

Base/res/ladybird/inspector.js
Ladybird/AppKit/UI/Inspector.mm
Ladybird/Qt/InspectorWidget.cpp
Ladybird/Qt/InspectorWidget.h
Userland/Applications/Browser/InspectorWidget.cpp
Userland/Applications/Browser/InspectorWidget.h
Userland/Libraries/LibWeb/Internals/Inspector.cpp
Userland/Libraries/LibWeb/Internals/Inspector.h
Userland/Libraries/LibWeb/Internals/Inspector.idl
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Libraries/LibWebView/InspectorClient.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Services/WebContent/WebContentServer.ipc

This lets you:
* Remove DOM nodes
* Add DOM attributes
* Remove DOM attributes
* Instigate editing DOM node text/tag/attribute as an alternative to double-clicking
https://github.com/SerenityOS/serenity/assets/5600524/9f54e9fc-975c-4292-9816-3de70ada7559

LibWebView: Add an Inspector context menu to instigate editing the DOM tree

---

Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.h
Userland/Libraries/LibWeb/Painting/PaintContext.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

BorderRadiusCornerClipper usage to clip border radius is specific to
CPU painter so it should not be stored in painting commands.
Also with this change bitmaps for corner sampling are allocated during
painting commands replaying instead of commands recording.

LibWeb: Move BorderRadiusCornerClipper allocation into CPU executor

---

Userland/Libraries/LibPDF/ColorSpace.cpp

Previously, we were scaling palette indices from 0..(palette_size - 1) to 0..255 before using them as index into the palette. Instead, do not scale palette indices before using them as indices.
(Renderer::load_image() uses `component_value_decoders.empend( .0f, 255.0f, dmin, dmax)`, so to get an identity mapping, we have to return `0, 255` from IndexedColorSpace::default_decode()).
Fixes rendering of the gradient on page 5 of 0000277.pdf.

LibPDF: Fix decoding of IndexedColorSpace for palette sizes != 255

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/Forward.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h
Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIterator.cpp
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIterator.h
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.h
Userland/Libraries/LibJS/Runtime/Iterator.cpp
Userland/Libraries/LibJS/Runtime/Iterator.h
Userland/Libraries/LibJS/Runtime/IteratorConstructor.cpp
Userland/Libraries/LibJS/Runtime/IteratorHelper.cpp
Userland/Libraries/LibJS/Runtime/IteratorHelper.h
Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/Object.h
Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp

This patch makes IteratorRecord an Object. Although it's not exposed to author code, this does allow us to store it in a VM register.
Now that we can store it in a VM register, we don't need to convert it back and forth between IteratorRecord and Object when accessing it from bytecode.
The big win here is avoiding 3 [[Get]] accesses on every iteration step of for..of loops. There are also a bunch of smaller efficiencies gained.
20% speed-up on this microbenchmark:
function go(a) {
for (const p of a) {
}
}
const a = [];
a.length = 1_000_000;
go(a);

LibJS: Stop converting between Object <-> IteratorRecord all the time

---

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Bytecode/Generator.cpp
Userland/Libraries/LibJS/Bytecode/Generator.h
Userland/Libraries/LibJS/Bytecode/Instruction.h
Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
Userland/Libraries/LibJS/Bytecode/Op.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/Compiler.h

When iterating over an iterable, we get back a JS object with the fields "value" and "done".
Before this change, we've had two dedicated instructions for retrieving the two fields: IteratorResultValue and IteratorResultDone. These had no fast path whatsoever and just did a generic [[Get]] access to fetch the corresponding property values.
By replacing the instructions with GetById("value") and GetById("done"), they instantly get caching and JIT fast paths for free, making iterating over iterables much faster. :^)
26% speed-up on this microbenchmark:
function go(a) {
for (const p of a) {
}
}
const a = [];
a.length = 1_000_000;
go(a);

LibJS: Remove dedicated iterator result instructions in favor of GetById

---

Meta/CMake/common_compile_options.cmake
Userland/Libraries/LibJS/Heap/Cell.h
Userland/Libraries/LibJS/Runtime/Shape.h
Userland/Libraries/LibWasm/Wasi.h
Userland/Libraries/LibX86/Instruction.h

This would be a temporary solution until someone (most probably me) implements `[[gnu::gcc_struct]]` on `x86_64-pc-windows-msvc` in clang.

Userland: Make bit-fields compatible with MSVC C++ ABI

---

Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/HTML/Window.idl

This PR adds support for the now deprecated window.status JavaScript property in LibWeb. It is initially set to an empty string on every window, and when modified by the user, it is set to the new value converted to a string. As per the web standards, it does not do anything else.
MDN: https://developer.mozilla.org/en-US/docs/Web/API/Window/status
Spec: https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-window-status

LibWeb: Add window.status property

---

Userland/Libraries/LibELF/ELFBuild.cpp
Userland/Libraries/LibELF/ELFBuild.h
Userland/Libraries/LibJIT/CMakeLists.txt
Userland/Libraries/LibJIT/GDB.cpp
Userland/Libraries/LibJIT/GDB.h
Userland/Libraries/LibJIT/GDBElf.cpp
Userland/Libraries/LibJIT/GDBUnsupported.cpp
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/JIT/NativeExecutable.cpp
Userland/Libraries/LibJS/JIT/NativeExecutable.h

This is a MVP that allows the JIT in LibJS to register an ELF file with the GDB
JIT Interface, so that GDB can point to symbols created at runtime. Currently the
registered ELF image only has the bare minimum so that the JITted code section is
recognized with a symbol.
Through LibJIT I've added infrastructure to help with adding sections and
strings, and LibJS/JIT contains an example of both how to use those APIs and how
to create a symbol table.
I've omitted emitting DWARF and `.eh_header` sections for the moment since I'm
having trouble understanding how they work and how to integrate them into the
JIT.
The code for emitting the ELF metadata currently assumes an `X86_64` LSB target.
The following is a screenshot of GDB showing a backtrace after an `ud2` has been executed:

LibJS/JIT+LibJIT: Register ELF images for JITted code using the GDB JIT Interface

---

Userland/Libraries/LibJS/Runtime/Intrinsics.cpp
Userland/Libraries/LibJS/Runtime/Intrinsics.h
Userland/Libraries/LibJS/Runtime/Iterator.cpp
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Object.h

Instead of going through the steps of creating an empty new object, and adding two properties ("value" and "done") to it, we can pre-bake a shape object and cache the property offsets.
This makes creating iterator result objects in the runtime much faster.
47% speedup on this microbenchmark:
function go(a) {
for (const p of a) {
}
}
const a = [];
a.length = 1_000_000;
go(a);

LibJS: Use a premade shape when creating iterator result objects

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h
Userland/Libraries/LibWeb/CSS/Properties.json

The goal is that everything consistently uses TokenStreams. Right now, some places use streams, and others take an individual ComponentValue or a Vector of them. This means we have code where we mostly use streams but then have to manually pull tokens out and remember whether we consumed them or not. This has repeatedly led to bugs, so let's finally fix that.
This is a very small step, from what I got done today. I like the "parse using a stream, then treat it as a failure if we have any unconsumed tokens left over" pattern though.

LibWeb: Start converting all StyleValue parsing over to TokenStream

---

Kernel/Arch/riscv64/linker.ld

`MM.protect_kernel_image` would otherwise make the contents of these sections read-only, as they were for some reason placed before `.data` and after the start of `.text`.

Kernel/riscv64: Add `.{ro,unmap}_after_init` sections to linker script

---

Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/ArrayIterator.h
Userland/Libraries/LibJS/Runtime/ArrayIteratorPrototype.cpp
Userland/Libraries/LibJS/Runtime/Object.h

Time spent in `render()` on https://nwex.de/
Before: 5.017 sec
After: 4.677 sec

LibJS: Some optimizations for nwex.de to render faster

---

Ladybird/cmake/InstallRules.cmake

Companion to 05c8d5ba5727f106058722e6e7642b16ee18e7c7 which moved the files to Base/res/ladybird, and d81c531322c8413cb80aa6ef02943d5e97334705 which installed them in the GN build on macOS.

Ladybird: Install required html and inspector files in the CMake build

---

Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp

These two patches has the result of reducing the number of lines produced by 
` SERENITY_SOURCE_DIR=$PWD ./Build/lagom/bin/headless-browser -R $PWD/Tests/LibWeb 2>&1 | wc -l`
from 2471 to 677 on my machine.
Note that when piping to wc -l, we actually get a newline for each test. in a terminal, it goes to like, 20 lines.
```
Running 659 tests...
1/659: Layout/input/aspect-ratio-auto.htmlFontDatabase::load_all_fonts_from_uri('file:///home/andrew/.local/share/fonts'): open: No such file or directory (errno=2)
397/659: Layout/input/css-namespace-tag-name-selector.htmlPotential FIXME: Creating unknown generic element 'a' in namespace 'http://www.w3.org/2000/svg'
Potential FIXME: Creating unknown generic element 'a' in namespace 'http://www.w3.org/1998/Math/MathML'
508/659: …
```

LibWeb: Hide more debug messages behind SPAM_DEBUG

---

Base/usr/share/man/man7/Audio-subsystem.md
Base/usr/share/man/man8/sysctl.md
Documentation/Browser/ProcessArchitecture.md

Stumbled upon the outdated `sysctl` variable path and found more outdated paths during a quick check.

Base+Documentation: Correct some outdated paths

---

Userland/Libraries/LibWeb/Layout/Node.cpp

It is not needed because font matching algorithms adds fallback font anyway.

LibWeb: Remove default font assignment in NodeWithStyle constructor

---

Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Userland/Libraries/LibGfx/Font/OpenType/Font.h

These properties could be cached in the font object once they are decoded from the table for the first time to make subsequent access faster.
This change makes `Node::scaled_font()` in LibWeb go down from 6% to 1.5% in my profiles because building a font cache key is now a lot cheaper.

LibGfx: Cache family, width, weight, and slope for OpenType fonts

---

Tests/LibWeb/Layout/expected/input-element-with-display-inline.txt
Tests/LibWeb/Layout/expected/input-text-node-invalidation-on-value-change.txt
Tests/LibWeb/Layout/input/input-text-node-invalidation-on-value-change.html
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp

We now have the `stepUp()` and `stepDown()` functions, so lets use them in the `input[type=number]` element with up and down buttons. All other browsers have such up & down buttons for number fields so I have added them.
I used again inline SVG's for icons like I did in my pending select pr, is this something that we want or do we need some SVG file loading from res with the `resource://` scheme that would be better I think.
https://github.com/SerenityOS/serenity/assets/19894029/7fd9a668-214c-4441-b504-0e4c3cfb1d70
*There is a bug with the cursor, I will look into that in the future*

LibWeb: Add input number up down UI buttons

---

Tests/LibWeb/Text/expected/Messaging/Messaging-basic-channel.txt
Tests/LibWeb/Text/input/Messaging/Messaging-basic-channel.html
Userland/Libraries/LibWeb/Bindings/Intrinsics.cpp
Userland/Libraries/LibWeb/Bindings/Intrinsics.h
Userland/Libraries/LibWeb/Bindings/Transferable.h
Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Userland/Libraries/LibWeb/HTML/MessagePort.h
Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Userland/Libraries/LibWeb/HTML/StructuredSerialize.h

- Add a basic message channel test
- Start implementing the transfer steps for MessagePorts
- Add a first cut of the structured_serialize_with_transfer and structured_deserialize_with_transfer methods

LibWeb: Implement Structured{De}SerializeWithTransfer for transferables

---

Userland/Games/Solitaire/Game.cpp
Userland/Games/Solitaire/Game.h
Userland/Games/Solitaire/Solitaire.gml
Userland/Games/Solitaire/main.cpp
Userland/Libraries/LibGUI/Widget.cpp
Userland/Libraries/LibGUI/Widget.h

In Solitaire, when all cards are revealed (i.e. the stock stack is empty and all cards on the normal stacks are revealed), solving the game is trivial since you merely need to sort the cards to the foundation stacks. To make this less annoying, the game will now show a button once this condition is met, which will sort the cards automatically.

Solitaire: Option to solve the end of the game automatically

---

Userland/Libraries/LibJS/AST.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Object.h

There's no reason to use handles here, we can just mark private element values from Object::visit_edges().

LibJS: Don't use Handle<Value> for JS::Object private fields

---

Base/res/ladybird/inspector.css
Base/res/ladybird/inspector.js
Userland/Libraries/LibWebView/InspectorClient.cpp
Userland/Libraries/LibWebView/InspectorClient.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp

* After taking a screenshot, log the path to saved image to the Inspector console
* Fix editing of DOM comments
* Allow editing empty DOM text nodes
https://github.com/SerenityOS/serenity/assets/5600524/05dff3d7-dd84-4da9-8e59-8f8828b3dcd7

LibWebView: A couple Inspector fixes and QoL improvements

---

AK/FlyString.h
AK/String.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Userland/Services/DeviceMapper/DeviceEventLoop.cpp
Userland/Shell/ImmediateFunctions.cpp
Userland/Shell/PosixParser.cpp

I was working on https://github.com/SerenityOS/serenity/issues/21959 and noticed from_utf8 being called in some cases when we already had a FlyString/String.
A lot of this in the CSS Parser I had accidentally introduced in 6813dcaff8bdf164e0fb37567d36f6667c915627, assuming that this wouldn't compile. This MR fixes up all instances of that, and prevents such code from compiling in the future.

AK+Everywhere: Disallow calling {String,FlyString}::from_utf8 on String/FlyString

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

This allows us to successfully decode `cramps.tiff` from https://libtiff.gitlab.io/libtiff/images.html

LibGfx/TIFF: Add support for one PhotometricInterpretation tag

---

Tests/LibWeb/Layout/expected/block-and-inline/inline-block-with-negative-margin-left.txt
Tests/LibWeb/Layout/expected/block-and-inline/inline-block-with-negative-margin-right.txt
Tests/LibWeb/Layout/input/block-and-inline/inline-block-with-negative-margin-left.html
Tests/LibWeb/Layout/input/block-and-inline/inline-block-with-negative-margin-right.html
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp

Sizing already worked correctly, but before this change, we were too aggressive with inserting line breaks when negative margins would still an atomic inline to fit on the line.
Visual progression on [Canvas Cycle](http://www.effectgames.com/demos/canvascycle/) (Prev/Next buttons)
Before:
After:

LibWeb: Honor negative margins on atomic inlines

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp

These are just like Uint8Array, except Put values have to be clamped in the 0..255 range.
Takes CPU usage from 40% to 30% on the "Canvas Cycle" demo at http://www.effectgames.com/demos/canvascycle/ :^)

LibJS: Add fast path for Uint8ClampedArray Get/Put

---

AK/URLParser.cpp
Meta/CMake/unicode_data.cmake
Meta/Lagom/Tools/CodeGenerators/LibUnicode/CMakeLists.txt
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateIDNAData.cpp
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
Meta/Lagom/Tools/CodeGenerators/LibUnicode/GeneratorUtil.h
Tests/LibUnicode/CMakeLists.txt
Tests/LibUnicode/TestIDNA.cpp
Tests/LibUnicode/TestPunycode.cpp
Userland/Libraries/LibUnicode/CMakeLists.txt
Userland/Libraries/LibUnicode/IDNA.cpp
Userland/Libraries/LibUnicode/IDNA.h
Userland/Libraries/LibUnicode/Punycode.cpp
Userland/Libraries/LibUnicode/Punycode.h
Userland/Libraries/LibUnicode/URL.cpp
Userland/Libraries/LibUnicode/URL.h
Userland/Libraries/LibWebView/CMakeLists.txt
Userland/Libraries/LibWebView/URL.cpp

This set of commits implements Punycode conversion as well as the Unicode processing for domain names of UTS 46 and hooks it up to the user URL inputs of Browser & Ladybird (command line and address bar).
The parsing of these URLs is made opt-in through `Unicode::create_unicode_url` because it requires linking with LibUnicode.
Ideally the normal URL parser would handle them directly, but that would require a major overhaul, most likely involving moving `URL` out of AK.
This, while somewhat of a hack, seems to be the least invasive solution for now.

AK+LibUnicode+Ladybird+Browser: Handle converting domains from Unicode to ASCII

---

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateIDNAData.cpp
Userland/Libraries/LibUnicode/IDNA.cpp
Userland/Libraries/LibUnicode/IDNA.h
Userland/Libraries/LibUnicode/UnicodeUtils.cpp

Rather than using `#ifdef` blocks, update the fallback IDNA definitions to
use weak symbols to match the rest of LibUnicode / LibLocale.
(Neglected to realize this while reviewing #19414)

LibUnicode: Use weak symbols to provide default IDNA defintions

---

Tests/LibWeb/Text/expected/HTML/HTMLElement-offsetFoo-in-table-cell.txt
Tests/LibWeb/Text/input/HTML/HTMLElement-offsetFoo-in-table-cell.html
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLElement.h
Userland/Libraries/LibWeb/HTML/HTMLElement.idl

(Or rather, bring offsetLeft and offsetTop closer to spec, and implement the previously-missing offsetParent)
This makes mouse inputs on https://nerget.com/fluidSim/ work properly.

LibWeb: Bring HTMLElement.offset{Left,Top,Parent} closer to spec

---

Tests/LibWeb/Layout/expected/input-element-with-display-inline.txt
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMeterElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMeterElement.h
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

This pr changes the way internal elements that use a pseudo selector for there styles work. Currently a element needs to extend `DOM::Element` and implement the `pseudo_element()` virtual. This is quite clunky and results in many small class defines. I changed this to a `set_use_pseudo_selector()` function that can be applied to any element.
In `TreeBuilder.cpp` the psuedo selector is then used and the inline styles are merged back. This results in a clean base where more internal shadow dom elements that use pseudo selector can easily be added. Before some large `if`s checked this but with the setter and the inline style merge this is not needed any more.
First I wanted to add a new `psuedo` attribute like Chrome uses but I could not protect it to internal shadow doms only. So this …

LibWeb: Add internal use_pseudo_selector to element

---

Base/res/ladybird/inspector.js
Ladybird/Qt/Tab.cpp
Userland/Applications/Browser/Tab.cpp
Userland/Libraries/LibWebView/InspectorClient.cpp

A couple fixes related to navigating to new pages with an existing Inspector widget.

Ladybird+LibWebView: Ensure existing Inspector widgets inspect the page

---

Userland/Libraries/LibPDF/Parser.cpp
Userland/Libraries/LibPDF/Parser.h

This only adds some scaffolding, but it does reduce the number of crashes on 0000.pdf from 9 to 8, and the number of unique crash stacks from 6 to 5 (due to the third commit).

LibPDF: Baby steps toward better inline image support

---

Userland/Libraries/LibJS/Bytecode/BasicBlock.h
Userland/Libraries/LibJS/CyclicModule.cpp
Userland/Libraries/LibJS/Module.h
Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
Userland/Libraries/LibWeb/Loader/LoadRequest.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Userland/Libraries/LibWeb/Loader/ResourceLoader.h
Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
Userland/Libraries/LibWeb/Streams/ReadableStreamGenericReader.h

Fixes warnings found by LibJSGCVerifier

LibWeb+LibJS: Use JS::GCPtr for pointers to GC-allocated objects

---

Meta/CMake/lagom_install_options.cmake

This removes a CMake dev warning when building serenity via the Superbuild.

CMake: Don't try to enable install options if no languages are enabled

---

Userland/Libraries/LibJS/Bytecode/CommonImplementations.cpp
Userland/Libraries/LibJS/Bytecode/Executable.h
Userland/Libraries/LibJS/JIT/Compiler.cpp
Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Object.h
Userland/Libraries/LibJS/Runtime/Shape.cpp
Userland/Libraries/LibJS/Runtime/Shape.h

We previously had a concept of unique shapes, which meant that they
couldn't be shared between multiple objects.
Object shapes became unique in three situations:
- They were the shape of the global object.
- They had more than 100 properties added to them.
- They had one or more properties deleted from them.
Unfortunately, unique shapes presented an annoying problem for inline
caches, and we added a "unique shape serial number" for being able to
tell that a unique shape had been mutated.
This patch gets rid of the concept of unique shapes, simplifying all
the caching code, since inline caches can now simply perform a shape
check and then we're good.
To make this possible, we now have the concept of delete transitions,
which occur when a property is deleted from a shape.
Looks generally …

LibJS: Stop making shapes unique

---

Tests/LibWeb/Ref/positioned-elements-in-scroll-container.html
Tests/LibWeb/Ref/reference/positioned-elements-in-scroll-container-ref.html
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

Because positioned descendants are painted out-of-order we need to
separately apply offset of nearest scrollable box for them.
Fixes https://github.com/SerenityOS/serenity/issues/20554

LibWeb: Use offset of nearest scrollable ancestor for positioned boxes

---

Kernel/Devices/GPU/Bochs/Definitions.h

The `[[gnu::packed]]` attribute apparently lowered the required alignment of the structs, which caused the compiler to generate two 1 byte loads/stores on RISC-V.
This caused the kernel to read/write incorrect values, as the device only seems to accept 2 byte operations on `DISPIInterface`.

Kernel/Graphics: Don't use `[[gnu::packed]]` on Bochs VGA MMIO register structs

---

Ladybird/Qt/BrowserWindow.cpp
Userland/Libraries/LibJS/Heap/Heap.cpp
Userland/Libraries/LibJS/Heap/Heap.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc

Instead of displaying a massive JSON in stdout, it's more practical to save the GC-graph to a file.

LibJS+LibWebView+WebContent+Ladybird: Output GC-graph into a file

---

AK/Format.cpp
AK/Format.h
Ladybird/AppKit/main.mm
Ladybird/ImageDecoder/main.cpp
Ladybird/Qt/main.cpp
Ladybird/RequestServer/main.cpp
Ladybird/SQLServer/main.cpp
Ladybird/WebContent/main.cpp
Ladybird/WebDriver/main.cpp
Ladybird/WebSocket/main.cpp
Ladybird/WebWorker/main.cpp

This requires duplicating some logic from Core::Process::get_name() into AK, which seems unfortunate. But for now, this greatly improves the log messages for testing Ladybird on Linux.
Example dbgln output with this patch:
```
1317422.228 WebContent(1477609): FontDatabase::load_all_fonts_from_uri('file:///home/andrew/.local/share/fonts'): open: No such file or directory (errno=2)
1317422.244 WebContent(1477609): ResourceLoader: Starting load of: "https://chat.openai.com/"
1317422.376 WebContent(1477609): ResourceLoader: Failed load of: "https://chat.openai.com/", Error: Load failed: 403, Duration: 133ms
1317422.388 WebContent(1477609): ResourceLoader: Starting load of: "https://chat.openai.com/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8327de841f365200"
1317422.396 …
```

AK: Print timestamp, process name, and pid on all platforms

---

Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.cpp
Userland/Libraries/LibWeb/HTML/AnimatedBitmapDecodedImageData.h
Userland/Libraries/LibWeb/HTML/DecodedImageData.h
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
Userland/Libraries/LibWeb/HTML/ImageRequest.cpp
Userland/Libraries/LibWeb/HTML/ImageRequest.h
Userland/Libraries/LibWeb/HTML/ListOfAvailableImages.cpp
Userland/Libraries/LibWeb/HTML/ListOfAvailableImages.h
Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
Userland/Libraries/LibWeb/HTML/SharedImageRequest.h
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h

This change fixes GC-leak caused by following mutual dependency:
- SVGDecodedImageData owns JS::Handle for Page.
- SVGDecodedImageData is owned by visited objects. by making everything inherited from HTML::DecodedImageData and ListOfAvailableImages to be GC-allocated.
Generally, if visited object has a handle, very likely we leak everything visited from object in a handle.

LibWeb: Make HTML::DecodedImageData to be GC-allocated

---

Userland/Libraries/LibJS/Heap/Heap.cpp
Userland/Libraries/LibJS/Heap/Heap.h
Userland/Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/SourceTextModule.cpp
Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp

Partially reverts 3dc5f467a8200b7c4043cf01d78b08745ddf8528 to fix GC memory leak that happens because we treated all execution contexts as strong roots.

LibJS: Only consider VM-accessible execution contexts as strong roots

---

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp

Fixes crashes introduced in https://github.com/SerenityOS/serenity/pull/22236

LibWeb: Fix crashing in compute_font_for_style_values on SerenityOS

---

Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/BrowserWindow.h
Ladybird/Qt/InspectorWidget.cpp
Ladybird/Qt/InspectorWidget.h
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebContentView.h

This adds support for listening to dpi changes to the Ladybird Qt chrome. Sadly the Qt framework makes it quite hard to listen to dpi changes. You can only listen if the window changes screens and if a specific screens dpi changes. So I have added the code that the window listens to dpi changes and updates all the WebContentViews it has.

Ladybird/Qt: Listen to DPI changes and update WebContentView accordingly

---

Userland/Libraries/LibGUI/AbstractView.cpp

Resolves #10618.
Simply put, this is caused by a debug line that calls `Vector::first()` which fails a `VERIFY()` check when its provided an empty vector.
Because of how old this issue is, I had to do the following:
1. Rewrite the reproducible that was provided to the following modern version:
```cpp
#include "LibGUI/ConnectionToWindowServer.h"
#include <AK/StringBuilder.h>
#include <LibCore/MimeData.h>
#include <LibGUI/Action.h>
#include <LibGUI/Application.h>
#include <LibGUI/BoxLayout.h>
#include <LibGUI/Button.h>
#include <LibGUI/Event.h>
#include <LibGUI/Icon.h>
#include <LibGUI/Label.h>
#include <LibGUI/Menu.h>
#include <LibGUI/MessageBox.h>
#include <LibGUI/Widget.h>
#include <LibGUI/Window.h>
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include …
```

LibGUI: Fix debug line causing crash when drag event has no mime data

---

Userland/Libraries/LibCore/ResourceImplementation.cpp

The construct `adopt_ref(*new Obj(TRY(get_resource())))` is another manifestation of a classic anti-pattern. In old C++, you would leak the object's memory if the argument threw an exception, or if a member initializer threw an exception. In our case, we leak if the MappedFile returns an Error. This is pretty concerning, and we should avoid this pattern at all costs, and try to use the "safer" helpers whenever possible.

LibCore: Don't leak proto-Resources when loading non-existent paths

---

Userland/Libraries/LibAudio/Loader.cpp
Userland/Libraries/LibChess/UCICommand.cpp
Userland/Libraries/LibGUI/InputBox.cpp
Userland/Shell/Shell.cpp

Similar to d253beb2f72442f6d05e1b4b0711a37bfe68fdc7.
Found with Ali's clang-query script in Shell:
```
for $(find AK Userland -type f -name '*.h' -o -name '*.cpp') {
in_parallel -j 12 -- clang-query -p \
Build/lagom/compile_commands.json $it -c \
'm cxxNewExpr(has(cxxConstructExpr(hasAnyArgument(hasDescendant( \
allOf(isExpandedFromMacro("TRY"), stmtExpr()))))))' \
} | grep -v 'matches.' | tee results
```

Userland: Don't leak objects when constructor arguments throw

---

Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h

It is no longer used because we started using shadow dom for progress element.

LibWeb/Painting: Remove command to paint progress bar

---

Tests/LibWeb/Text/expected/get-bounding-client-rect.txt
Tests/LibWeb/Text/input/get-bounding-client-rect.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.h

This fixes the issue that occurred when, after clicking an inline paintable page would always scroll to the top. The problem was that `scroll_an_element_into_view()` relies on `get_bounding_client_rect()` to produce the correct scroll position and for inline paintables we were always returning zero rect before this change.

LibWeb: Implement getBoundingClientRect() for inline paintables

---

Userland/Applications/PixelPaint/ImageEditor.cpp
Userland/Applications/PixelPaint/ToolboxWidget.cpp

This pr fixes the following two issues:
- crash when the mouse is moved while a images is beeing loaded
- initial tool selection does not show the tool properties
For details see individual commits.

PixelPaint: Some small fixes

---

Userland/Libraries/LibCodeComprehension/Shell/ShellComprehensionEngine.cpp
Userland/Libraries/LibLine/Editor.cpp
Userland/Libraries/LibLine/SuggestionManager.cpp
Userland/Libraries/LibLine/SuggestionManager.h
Userland/Libraries/LibLine/XtermSuggestionDisplay.cpp
Userland/Shell/AST.cpp
Userland/Shell/Shell.cpp

Previously, we stored two representations of the same string in `CompletionSuggestion` object: one for the bytes and the other for the code points corresponding to those bytes. To minimize duplication, this patch combine both representations into a single UTF-8 string, which is already supported by our new String class.
Following this update, we successfully reduce the size of each object from 376 bytes to 256 bytes

LibLine: Remove duplicate members in `CompletionSuggestion`

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
Ladybird/AppKit/UI/LadybirdWebViewBridge.h
Ladybird/Qt/BrowserWindow.cpp
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebContentView.h
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Userland/Libraries/LibWeb/PixelUnits.cpp
Userland/Libraries/LibWeb/PixelUnits.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/OutOfProcessWebView.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentServer.ipc
Userland/Utilities/headless-browser.cpp

This is work towards clarifying the int types in WebContent IPC. Most IPC calls already used DevicePixels from `PageClient.h` into LibWeb I want to extend that to the chrome to make it more explicit if a value contains real pixels (DevicePixels) or scaled pixels (CSSPixels).

LibWeb: Refactor int types in WebContentServer to DevicePixels

---

Kernel/Arch/x86_64/Interrupts.cpp
Kernel/Syscalls/fork.cpp

Previously we would unintentionally leave them zero-initialized, resulting in any threads created post fork (but without execve) having invalid thread local storage pointers stored in their FS register.
Fixes #19118

Kernel: Copy over TLS region size and alignment when forking

---

Kernel/Syscalls/execve.cpp

If there's no loadable segments then there can't be any code to execute either. This resolves a crash these kinds of ELF files would cause from the directly following VERIFY statement.
Resolves #22294.

Kernel: Reject loading ELF files with no loadable segments

---

Tests/LibWeb/Text/expected/navigation/history-replace-push-state-race.txt
Tests/LibWeb/Text/input/navigation/history-replace-push-state-race.html
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp

bumped in the same crash as https://github.com/SerenityOS/serenity/issues/21355
```
543/674: VERIFICATION FAILED: i < m_size at /Users/vladimir/workspace/serenity/Meta/Lagom/../../AK/Vector.h:148
0   liblagom-core.0.0.0.dylib           0x00000001016e5c24 ak_verification_failed + 216
1   liblagom-web.0.0.0.dylib            0x0000000102a1eff8 Web::HTML::finalize_a_same_document_navigation(JS::NonnullGCPtr<Web::HTML::TraversableNavigable>, JS::NonnullGCPtr<Web::HTML::Navigable>, JS::NonnullGCPtr<Web::HTML::SessionHistoryEntry>, JS::GCPtr<Web::HTML::SessionHistoryEntry>) + 140
2   liblagom-web.0.0.0.dylib            0x0000000102a1f548 AK::Function<void ()>::CallableWrapper<Web::HTML::SessionHistoryTraversalQueue::SessionHistoryTraversalQueue()::'lambda'()>::call() + 156
3
```
when doing:
open …

LibWeb: History pushState/replaceState race crash

---

Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp

Today I found out that `Mod_Super` exists, so let's use that for the meta key in LibWeb!

LibWeb: Add support for the meta key modifier

---

Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
Ladybird/AppKit/UI/LadybirdWebViewBridge.h
Ladybird/Qt/WebContentView.cpp
Ladybird/Qt/WebContentView.h
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/WebContentServer.ipc

These changes convert to positions types of the mouse events in `WebContentServer.ipc` to DevicePixelPoint. This makes the IPC API more clear that unscaled / raw pixel coordinates are used. 
With these changes are all coordinates in `WebContentServer.ipc` are 'fixed'.

LibWeb: Refactor WebContentServer mouse input message to DevicePixel

---

Userland/Libraries/LibPDF/Fonts/PS1FontProgram.cpp

This regressed in 2b3a41be74a3e8 in #18031.
Fixes a crash rendering page 2 and onward of
https://pyx-project.org/presentation_dantemv35_en.pdf

LibPDF: Tolerate 0-sized Subrs in PS1 font subprograms

---

Userland/Libraries/LibJS/Runtime/Object.cpp
Userland/Libraries/LibJS/Runtime/Shape.cpp
Userland/Libraries/LibJS/Runtime/Shape.h
Userland/Libraries/LibJS/Tests/builtins/Object/Object.freeze.js

This is similar to "unique" shapes, which were removed in commit 3d92c26445d15d13599de5d20d2227a968fd675a.
The key difference is that dictionary shapes don't have a serial number, but instead have a "cacheable" flag.
Shapes become dictionaries after 64 transitions have occurred, at which point no further transitions occur.
As long as properties are only added to a dictionary shape, it remains cacheable. (Since if we've cached the shape pointer in an IC somewhere, we know the IC is still valid.)
Deleting a property from a dictionary shape causes it to become an uncacheable dictionary.
Note that deleting a property from a non-dictionary shape still performs a delete transition.
This fixes an issue on Discord where Object.freeze() would eventually OOM us, since they add more than 16000 …

LibJS: Introduce "dictionary" mode for object shapes

---

Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp

Removes usage of `RecordingPainter::state()` and makes it private.
No behavior change intended.

LibWeb: Make private `RecordingPainter::state()`

---

Tests/LibWeb/Text/expected/get-bounding-client-rect-display-none.txt
Tests/LibWeb/Text/input/get-bounding-client-rect-display-none.html
Userland/Libraries/LibWeb/DOM/Element.cpp

Fixes crashing on https://github.com/

LibWeb: Add missing paintable null check in get_bounding_client_rect()

---

Kernel/Arch/riscv64/FPUState.h

The [signal handling code](https://github.com/SerenityOS/serenity/blob/master/Kernel/Tasks/Process.cpp#L465) (and possibly other code as well) expects this struct to have an alignment of 16 bytes, as it pushes this struct on the stack.
Other architectures already specify the correct alignment, I just probably missed that when I first added this struct.

Kernel/riscv64: Specify correct alignment for `FPUState` struct

---

Userland/Libraries/LibJS/CyclicModule.cpp

The spec allows this scenario, so I don't know why we would want to assert that it doesn't happen.
Fixes #22317
Also, -1 crash, +1 pass on test262 :^)
```
test/language/expressions/dynamic-import/reuse-namespace-object-from-import.js 💥️ -> ✅
```

LibJS: Don't crash in CyclicModule::evaluate() when this == m_cycle_root

---

Userland/Libraries/LibAccelGfx/Context.cpp
Userland/Libraries/LibAccelGfx/Context.h
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h

Let's not assume there is one global OpenGL context because it might
change once we will start creating >1 page inside single WebContent
process or contexts for WebGL.

LibAccelGfx+LibWeb: Explicitly pass OpenGL context to Painter

---

Tests/LibWeb/Layout/expected/svg/objectBoundingBox-mask.txt
Tests/LibWeb/Layout/input/svg/objectBoundingBox-mask.html
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

Currently `calculate_mask()` fails to create bitmap when `maskContentUnits="objectBoundingBox"` is present.
Fixes https://github.com/SerenityOS/serenity/issues/22316

LibWeb: Do not crash when svg mask calculation failed

---

Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Userland/Libraries/LibWeb/HTML/Scripting/ModuleMap.cpp
Userland/Libraries/LibWeb/HTML/Scripting/ModuleMap.h

We were doing this synchronously, which was unsafe in that caused us to re-enter the module map entry setting code while iterating over the map's entries.
The fix is simply to do what the spec says and queue up a task. This way the processing gets deferred to a later time.
To avoid stepping into this problem again, I've also added a reentrancy check in ModuleMap.
This fixes a sporadic crash in HTML::ModuleMap::add() caught by ASAN. In particular, this was happening regularly on https://shopify.com/

LibWeb: Queue a task to proceed after module map entry finishes fetching

---

Userland/Libraries/LibLine/CMakeLists.txt
Userland/Libraries/LibLine/Editor.cpp
Userland/Libraries/LibLine/Editor.h
Userland/Libraries/LibLine/InternalFunctions.cpp
Userland/Libraries/LibLine/StringMetrics.h

This makes using the line editor much nicer when multi-code-point graphemes are present in the input (e.g. flag emojis, or some cjk glyphs), and avoids messing up the buffer when deleting text, or cursoring around.
Note that serenity's terminal seems to not like multi-code-point emojis (see #22297),  so the utility of this change is limited until that issue is fixed.

LibLine: Use grapheme clusters for cursor management / tiny boog fix

---

AK/StringUtils.cpp
Tests/AK/TestStringUtils.cpp

Previously, `replace` used `find_all` to find all of the positions to replace. But `find_all` finds all the *overlapping* instances of the needle, while `replace` assumed that the next position was always at least `needle.length()` away from the last one. This led to crashes like https://github.com/SerenityOS/jakt/issues/1159.

AK/StringUtils: Ensure needle positions don't overlap in `replace`

---

Tests/LibWeb/Layout/expected/element-use-pseudo-element.txt
Tests/LibWeb/Layout/input/element-use-pseudo-element.html
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/HTML/HTMLMeterElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

This fixes issue #22278.
I was looking for the root couse of the styling not applied for elements the use fake pseudo element selectors. The I saw that the styles where only applied at layout and not recomputed after that. So I guess that hover triggered a style recompute without the pseudo element override.
So I moved the logic from `TreeBuilder.cpp` to `StyleComputer.cpp`, as a nice benefit we can remove some `document().invalidate_layout();`. And the `property_id_by_index()` method that I introduced a week ago in favour for `parse_css_style_attribute()`.
So an amazing improvement in the end :^)

LibWeb: Move use pseudo element styles from TreeBuilder to StyleComputer

---

Userland/Libraries/LibAccelGfx/GL.cpp
Userland/Libraries/LibAccelGfx/GL.h
Userland/Libraries/LibAccelGfx/Painter.cpp
Userland/Libraries/LibAccelGfx/Painter.h
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h

It is implemented in the way identical to how it works in CPU painter:
1. SampleUnderCorners command saves pixels within corners into a
texture.
2. BlitCornerClipping command uses the texture prepared earlier to
restore pixels within corners.

LibWeb: Implement border radius corner clipping in GPU painter 

---

Userland/Libraries/LibGfx/TIFFGenerator.py

These tags are either part of the baseline specification or included by default by GIMP when exporting TIFFs. Note that we don't add support for them in the decoder yet. This commit only allows us to parse the metadata and display them gracefully.

LibGfx/TIFF: Parse more common tags

---

Tests/LibWeb/Text/expected/scroll-into-view-end.txt
Tests/LibWeb/Text/expected/scroll-into-view-start.txt
Tests/LibWeb/Text/input/scroll-into-view-end.html
Tests/LibWeb/Text/input/scroll-into-view-start.html
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Utilities/headless-browser.cpp

Fixes a bug when after clicking on a button/click the page is scrolled to start of the element.

LibWeb: Scroll to "nearest" instead of "start" in set_focused_element()

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibJS/Runtime/Value.h
Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
Userland/Libraries/LibWeb/Streams/TransformStream.cpp
Userland/Libraries/LibWeb/Streams/WritableStream.cpp
Userland/Libraries/LibWeb/WebIDL/DOMException.h

Similar to the constructors for ``JS::{Nonnull}GCPtr<T>``, this helper avoids unnecessary .ptr() clutter when we want to construct Values.

LibJS+LibWeb: Add JS::Value constructor for ``JS::Handle<T>``

---

Userland/Libraries/LibJS/Runtime/VM.h
Userland/Libraries/LibWeb/Bindings/Transferable.h
Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Userland/Libraries/LibWeb/HTML/MessagePort.h
Userland/Libraries/LibWeb/HTML/MessagePort.idl
Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Utilities/headless-browser.cpp

Use a LocalSocket to represent the connection between two message ports.
The concept of the port message queue is still missing, however. When
that concept is implemented, the "steps" in step 7 of the message port
transfer steps will need to send the serialized data over the connected
socketpair and run in the event loop of the process that holds onto the
other side of the message port. Doing this should allow centralizing the
behavior of postMessage for Window, MessagePorts and Workers.

LibWeb: Implement MessagePort.postMessage closer to the spec

---

Meta/run.py

This mirrors the behavior of the old run.sh script.
Fixes #22313.

Meta: Assume virgl support to not be present if ldconfig isn't found

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

Commits are from #22343
As per the specification, TIFF readers should gracefully skip samples that they are not able to interpret.

LibGfx/TIFF: Discard extra channels

---

Userland/Libraries/LibGUI/FilteringProxyModel.cpp

Currently, if we run CommandPalette, it's blank by default and it's not displaying all available commands for the app in which it has been opened. User has to enter something and then delete it to see all commands. This patch makes all available commands being displayed by default on start of CommandPalette, by allowing incoming empty string to be invalidated in FilteringProxyModel, instead of returning instantly.
This basically changes CommandPalette's behavior on startup from the behavior on the left of below image, to the behavior on the right of the image.

LibGUI: Display commands on CommandPalette's start up

---

Tests/LibPDF/CMakeLists.txt
Tests/LibPDF/TestPDF.cpp
Userland/Libraries/LibPDF/ColorSpace.cpp

Having some rendering test coverage is motivated by #22362, but this
test wouldn't have found the crashes over there (since colorspaces.pdf
does not contain pattern color spaces). Still, good to have some
in-repo test coverage of PDF rendering.
Also fix an UBSan report that the test produced.
(I think it's relatively benign in practice.)

LibPDF+Tests: Add a PDF rendering test

---

Userland/Libraries/LibWeb/DOM/Document.cpp

This change fixes a bug with running tests where, if one of the
previous tests changes the scroll position, all subsequent tests that
rely on the scroll position will fail. This is because the headless
browser never resets the viewport offset.

LibWeb: Scroll to the top after navigating to a new document

---

Userland/Libraries/LibPDF/Document.h
Userland/Libraries/LibPDF/Renderer.cpp

The idea is to massage the inline image data into something that looks like a regular image, and then use the normal image drawing code: We translate the inline image abbreviations to the expanded version at rendering time, then unfilter (i.e. uncompress) the image data at rendering time, and the go down the usual image drawing path.
Normal streams are unfiltered when they're first accessed, but inline image streams live in a page's drawing operators, and this fits the current approach of parsing a page's operators anew every time the page is rendered.
(We also need to add some special-case handling for color spaces of inline images: Inline images can use named color spaces, while regular images always use direct color space objects.)

LibPDF: Draw inline images

---

Meta/CMake/code_generators.cmake

This lets us fail early at configure time if a suitable Python 3 interpreter is not present, instead of delaying the error until Ninja attempts to run `embed_as_string_view.py` to generate a header in the middle of the build.
Refs #21791

CMake: Query Python interpreter with `find_package`

---

Userland/Utilities/headless-browser.cpp

Before this change, it was possible for a text test to finish before on_load_finish() was triggered, resulting in the subsequent test receiving the load event from the previous test.

headless-browser: Await `on_load_finish()` while running Text tests

---

Base/res/html/misc/input-range.html
Base/res/html/misc/input.html
Userland/Libraries/LibWeb/CSS/Default.css
Userland/Libraries/LibWeb/CSS/Selector.cpp
Userland/Libraries/LibWeb/CSS/Selector.h
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h

This adds basic rendering of the input range elements. I used a shadow dom impl with the webkit pseudo element selectors, this way we can benefit from custom styling used on many websites. 
**The UI elements are not interactable I will implement this is a future pr.**
~~The changes in #22210 can also be applied here, I will rebase this pr or the other on wich will be merged first.~~
Looking forward to feedback

LibWeb: Add basic input range rendering

---

AK/Checked.h

If we don't have `__builtin_add_overflow_p()`, we can also try using `__builtin_add_overflow()`. This makes debug builds with Clang significantly faster since they no longer need to use the generic implementation. Same for multiplication.

AK: Use fallback builtins for overflow checks in AK::Checked

---

Userland/Libraries/LibPDF/ColorSpace.cpp
Userland/Libraries/LibPDF/ColorSpace.h
Userland/Libraries/LibPDF/CommonNames.h
Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

Reverts the last two commits of #22197 for now due to causing #22362.

LibPDF: Revert pattern support

---

Kernel/Memory/AnonymousVMObject.cpp

Our existing AnonymousVMObject cloning flow contains an optimization wherein purgeable VMObjects which are marked volatile during the clone are created as a new zero-filled VMObject (as if it was purged), which lets us skip the expensive COW process.
Unfortunately, one crucial part was missing: Marking the cloned region as purged, (which is the value returned from madvise when unmarking the region as volatile) so the userland logic was left unaware of the effective zero-ing of their memory region, resulting in odd behaviour and crashes in places like our malloc's large allocation support.
Fixes #22334.

Kernel: Mark cloned volatile purgeable AnonymousVMOjects as purged

---

Userland/Libraries/LibPDF/Parser.cpp
Userland/Libraries/LibPDF/Parser.h

Pure code move, no intended behavior change.
The motivation is just to make Parser::parse_operators() less nested
and more focused.
Also tweak a comment.

LibPDF: Extract Parser::parse_inline_image()

---

AK/Format.cpp

Half the functions used are not readily available on windows, instead of creating more ifdef soup, this commit simply disables the rich debug stuff on windows.
cc @ADKaster

AK: Completely disable rich debug formats on Windows

---

Userland/Libraries/LibLine/SuggestionManager.cpp

This caused a dangling reference down the line, which lead to funny things like the following:
> cd Bui[tab]
> cd Bui^@^@
By returning a direct reference to the suggestion in question, we can be sure that the referenced object is alive until the next suggestion cycle.

LibLine: Avoid returning reference to cached suggestion

---

Userland/Libraries/LibWeb/HTML/Navigable.cpp

This is a bug. The value set here needs to be visible to later steps.

LibWeb: Stop shadowing location_url

---

Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
Ladybird/Qt/WebContentView.cpp
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Services/WebContent/WebContentServer.ipc

With this change, chrome no longer has to ask the WebContent process to paint the next frame into a specified bitmap. Instead, it allocates bitmaps and sends them to WebContent, which then lets chrome know when the painting is done.
This work is a preparation to move the execution of painting commands into a separate thread. Now, it is much easier to start working on the next frame while the current one is still rendering. This is because WebContent does not have to inform chrome that the current frame is ready before it can request the next frame.
Additionally, as a side bonus, we can now eliminate the did_invalidate_content_rect and did_change_selection IPC calls. These were used solely for the purpose of informing chrome that it needed to request a repaint.

LibWebView+WebContent: Drive repainting from WebContent process

---

Userland/Libraries/LibPDF/Renderer.cpp

LibPDF: Fix typo in a variable name

---

Base/res/html/misc/select.html
Ladybird/Qt/Tab.cpp
Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/Default.css
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h
Userland/Libraries/LibWebView/WebContentClient.cpp

With these changes the select element dropdown position on a scrolled page is better in the Qt chrome. On the AppKit chrome it is still bugged but more things are a little broken with that chrome.
Also the select element now supports the `appearance: none;` css property so custom styled select boxes now look some what better, for example https://bulma.io/documentation/form/select/ now doesn't contain the internal chevron icon.

LibWeb: Some select element fixes

---

Meta/CMake/time_zone_data.cmake
Meta/gn/secondary/Userland/Libraries/LibTimeZone/BUILD.gn

https://mm.icann.org/pipermail/tz-announce/2023-December/000080.html

LibTimeZone: Update to TZDB version 2023d

---

Tests/LibWeb/Text/expected/DOM/Text-methods.txt
Tests/LibWeb/Text/input/DOM/Text-methods.html
Userland/Libraries/LibWeb/DOM/CharacterData.cpp
Userland/Libraries/LibWeb/DOM/CharacterData.h
Userland/Libraries/LibWeb/DOM/CharacterData.idl
Userland/Libraries/LibWeb/DOM/Node.cpp

We were previously assuming that the input offsets and lengths were all in raw byte offsets into a UTF-8 string. While internally our String representation may be in UTF-8 from the external world it is seen as UTF-16, with code unit offsets passed through, and used as the returned length.
Beforehand, the insert-delete test included in this commit would crash ladybird, and `new Text('🙃').length` would return `4` instead of `2`.
The implementation here is very inefficient, I am sure there is a much smarter way to write it so that we would not need a conversion from UTF-8 to a UTF-16 string (and then back again).
Fixes: #20971

LibWeb: Use UTF-16 code unit offsets and lengths in CharacterData

---

Tests/LibWeb/Layout/expected/display-contents-with-in-children.txt
Tests/LibWeb/Layout/input/display-contents-with-in-children.html
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

With this change "display: contents" ancestors are not considered as insertion point for inline nodes similar to how we already ignore them for non-inline nodes.
Fixes https://github.com/SerenityOS/serenity/issues/22396

LibWeb: Ignore "display: contents" boxes while inserting inline nodes

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

This allows us to reject invalid images before trying to decode them. The spec requires more tag to be present[1] but as we don't use them for decoding I don't see the point.
[1] - XResolution, YResolution and ResolutionUnit
---
Solves oss-fuzz issue [64143](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64143)

LibGfx/TIFF: Ensure baseline tags presence before decoding

---

Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp

If a short string is used for the attribute value, then the result of:
```cpp
auto const view = element.attribute(attribute_name).value_or({})
.bytes_as_string_view().split_view(' ');
```
is an array of string views pointing into a temporarily allocated string.
With this change we keep string on stack until the end of scope.
Page that allows to reproduce the problem.
```html
<!DOCTYPE html><style>
div[data-info~="a"] {
background-color: yellow;
}
</style><div data-info="a">a</div>
```

LibWeb/CSS: Fix stack use after scope in matches_attribute()

---

Meta/Azure/Lagom.yml

We set the job-level timeout to 0, which means "max value" (6 hours). In the Serenity build, we do the same, but then limit the Test step to just 1 hour to prevent hung tests from hogging CI resources. When a job-level timeout was added to Lagom, the Test step timeout was forgotten.

CI: Lower the timeout for Lagom tests to 1 hour

---

Kernel/Memory/MemoryManager.h
Kernel/Syscalls/fork.cpp
Kernel/Syscalls/sigaction.cpp
Kernel/Tasks/Process.h
Kernel/Tasks/Thread.cpp
Kernel/Tasks/Thread.h

Since the POSIX sigaltstack manpage suggests allocating the stack region using malloc(), and many heap implementations (including ours) store heap chunk metadata in memory just before the vended pointer, we would end up zeroing the metadata, leading to various crashes.

Kernel: Shrink instead of expand sigaltstack range to page boundaries 

---

Userland/Libraries/LibLine/InternalFunctions.cpp

Prior to this commit, the loop would continue forever and try to remove the same index every time, eventually hitting a VERIFY and crashing.

LibLine: Use the correct loop conditions for erase_character_forwards()

---

Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.cpp
Userland/Libraries/LibWeb/Bindings/LegacyPlatformObject.h
Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Userland/Libraries/LibWeb/DOM/NamedNodeMap.cpp
Userland/Libraries/LibWeb/DOM/NamedNodeMap.h
Userland/Libraries/LibWeb/DOM/Node.h
Userland/Libraries/LibWeb/HTML/DOMStringMap.cpp
Userland/Libraries/LibWeb/HTML/DOMStringMap.h
Userland/Libraries/LibWeb/HTML/HTMLEmbedElement.h
Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
Userland/Libraries/LibWeb/HTML/MimeTypeArray.cpp
Userland/Libraries/LibWeb/HTML/MimeTypeArray.h
Userland/Libraries/LibWeb/HTML/Plugin.cpp
Userland/Libraries/LibWeb/HTML/Plugin.h
Userland/Libraries/LibWeb/HTML/PluginArray.cpp
Userland/Libraries/LibWeb/HTML/PluginArray.h
Userland/Libraries/LibWeb/HTML/Storage.cpp
Userland/Libraries/LibWeb/HTML/Storage.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/WebIDL/AbstractOperations.cpp

Here's a bundle of changes that lower how long takes before the cookie consent banner is active on https://twinings.co.uk/ from 22 seconds to 10 seconds (after hitting enter in the location bar)

LibWeb: Make cookie consent banner on Twinings interactive way sooner

---

Tests/LibWeb/Text/expected/window-scrollTo.txt
Tests/LibWeb/Text/input/window-scrollTo.html
Userland/Libraries/LibWeb/HTML/Window.cpp

This change fixes "vertical shift" in inspector.

LibWeb: Limit scroll position by overflow area in Window::scroll()

---

Base/res/html/misc/worker.js
Tests/LibWeb/TestConfig.ini
Tests/LibWeb/Text/expected/Worker/Worker-echo.txt
Tests/LibWeb/Text/input/Worker/Worker-echo.html
Tests/LibWeb/Text/input/Worker/worker.js
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Userland/Libraries/LibWeb/HTML/MessagePort.h
Userland/Libraries/LibWeb/HTML/Worker.cpp
Userland/Libraries/LibWeb/HTML/Worker.h
Userland/Libraries/LibWeb/HTML/Worker.idl
Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp
Userland/Libraries/LibWeb/HTML/WorkerAgent.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.idl
Userland/Libraries/LibWeb/Worker/WebWorkerServer.ipc
Userland/Services/WebWorker/ConnectionFromClient.cpp
Userland/Services/WebWorker/ConnectionFromClient.h
Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Userland/Services/WebWorker/DedicatedWorkerHost.h

This aligns Workers and Window and MessagePorts to all use the same mechanism for transferring serialized messages across realms.
It also allows transferring more message ports into a worker.
Re-enable the Worker-echo test, as none of the MessagePort tests have themselves been flaky, and those are now using the same underlying implementation.

LibWeb+WebWorker: Convert Workers to use MessagePorts for postMessage

---

Userland/Libraries/LibWebView/ViewImplementation.cpp

Fixes a bug when the Qt client does not repaint after resizing when the following sequence of IPC calls happens:
1. In the resize handler, the client sends set_viewport_rect to WebContent.
2. WebContent starts repainting in response to the changed viewport size.
3. In the resize handler, the client updates backing stores and sends new ids and shared bitmaps to WebContent using the add_backing_store call.
4. WebContent sends an acknowledgment to the client that painting finished using the old id.
5. The client discards the repaint because it expects a new backing store id.

LibWebView: Request repaint after replacing backing stores

---

Userland/Services/WebContent/PageClient.cpp

It polluted logs of headless-browser.

WebContent: Remove spammy debug message from paint handler

---

Tests/LibWeb/Layout/expected/block-and-inline/max-width-wrapped-in-max-content.txt
Tests/LibWeb/Layout/expected/table/cell-with-max-width.txt
Tests/LibWeb/Layout/input/block-and-inline/max-width-wrapped-in-max-content.html
Tests/LibWeb/Layout/input/table/cell-with-max-width.html
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp

Fixes https://github.com/SerenityOS/serenity/issues/22430

LibWeb: Apply min/max-widths to block container during intrinsic layout

---

Tests/LibWeb/Layout/expected/grid/max-width-grid-container-wrapper-in-max-content.txt
Tests/LibWeb/Layout/input/grid/max-width-grid-container-wrapper-in-max-content.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

Implements missing "redo" step defined in the spec.

LibWeb: Redo "tracks maximize" if initial run is over max-size in GFC

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.h

Builds on #22439.
These turned out to be easier than I expected. While converting these, I did notice a fair number of places we don't follow the spec fully, but I'll sort that out later. This is still just about making the parsing code more consistent and less confusing and error prone. (Hopefully!)

LibWeb: Parse remaining grid properties using TokenStream

---

Tests/LibWeb/Ref/reference/svg-use-defined-earlier.html
Tests/LibWeb/Ref/svg-use-defined-later.html
Userland/Libraries/LibWeb/DOM/Document.cpp

This stopped being called for anything without a navigable container after 76a97d8, due to the early return. This broke SVG `<use>` elements that reference elements defined later in the document.

LibWeb: Ensure DocumentObserver `document_completely_loaded()` is called

---

Userland/Applications/HexEditor/HexEditor.cpp
Userland/Applications/HexEditor/HexEditor.h

Discussion regarding this change was moved in this PR: https://github.com/SerenityOS/serenity/pull/22211, and also on #Userland channel, on serenity's discord.
These series of patches change cursor type from caret to black box for both Hex and Text modes, because right now the way how blinking caret looks like is more closer to "insert" mode in similar editors, whereas the real behavior of this cursor is more of a "replace" mode seen in similar editors like GHex.
There have also been fixed crashes when selecting last bytes with mouse and then writing something. Now the cursor is being moved to the last byte of selection, instead of moving the cursor to the byte one after last selected byte.

HexEditor: Change cursor type from blinking caret to black box

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h

Per:
https://dom.spec.whatwg.org/#concept-reflect
We should be calling `get_attribute_value` for reflected IDL strings.
No functional change as nowhere is performing a reflect on a nullable
type, and just ends up simplifying the code.

LibWeb+BindingsGenerator: Use `get_attribute_value` for reflected strings 

---

Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
Userland/Libraries/LibWeb/Painting/MarkerPaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h

Instead, we now pass String if we have one. In particular, this fixes an issue where image elements with a data: URL src would copy the entire URL string every time we painted (before the image had been decoded). This was very noticeable on "fully downloaded" web pages where every single image has been turned into a data: URL.

LibWeb: Don't pass StringView to RecordingPainter, to avoid copy

---

Userland/Applications/CrashReporter/CMakeLists.txt
Userland/Applications/CrashReporter/CrashReporterWindow.gml
Userland/Applications/CrashReporter/MainWidget.h
Userland/Applications/CrashReporter/main.cpp
Userland/Libraries/LibGUI/Progressbar.h

- Contributes towards: https://github.com/SerenityOS/serenity/issues/20518
- The reason for https://github.com/SerenityOS/serenity/pull/22442/commits/efca4991e7e9c645494ac66583102a90df6336df commit is that the compiler was complaining about `ByteString` and `String` types being incompatible

CrashReporter: Port CrashReporter to GML Compiler

---

Base/res/ladybird/directory.html
Base/res/ladybird/error.html
Ladybird/Android/src/main/cpp/WebContentService.cpp
Ladybird/WebContent/main.cpp
Ladybird/WebWorker/main.cpp
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.cpp
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.h
Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp

This pr removes the `@resource_directory_url@` template variable and uses the new `resource://` scheme to get to the right icons.
It also adds some code that when viewing a resource schemed directory url a generated directory page is responded instead of the browser crashing on a `VERIFY_NOT_REACH()` in `Resource.cpp`.
I also get the path to the `directory.html` and `error.html` page with resources to reduce code.

LibWeb: Fix bug where viewing resource schemed directory urls crashes

---

Ports/stpuzzles/package.sh

https://github.com/SerenityPorts/stpuzzles/pull/8 was just merged so we need to update the checksum.
Not sure if there is still a way to completely leave the checksum out? Re: a4d5745e2f378e298d902413e09e03d51ad2f315

Ports: Update checksum for stpuzzles

---

AK/ByteBuffer.h
Tests/AK/TestByteBuffer.cpp
Userland/Libraries/LibJS/Runtime/VM.cpp
Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.resize.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.every.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.set.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.some.js
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.toSorted.js

Otherwise, the newly allocated bytes are uninitialized, causing UB when
reading from the buffer immediately after an enlarging resize.
```
Diff Tests:
+17 ✅    -17 ❌   
test/built-ins/TypedArray/prototype/set/BigInt/typedarray-arg-set-values-same-buffer-same-type-resized.js ❌ -> ✅
test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-same-buffer-same-type-resized.js        ❌ -> ✅
test/staging/ArrayBuffer/resizable/access-out-of-bounds-typed-array.js                                    ❌ -> ✅
test/staging/ArrayBuffer/resizable/at.js                                                                  ❌ -> ✅
test/staging/ArrayBuffer/resizable/destructuring.js                                                       ❌ -> ✅
test/staging/ArrayBuffer/resizable/entries-keys-values-grow-mid-it …
```

LibJS: Ensure enlarged ArrayBuffers are filled with zeros

---

Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.subarray.js

Woops! With this,we now pass all of `test/staging/ArrayBuffer`.
```
Diff Tests:
test/staging/ArrayBuffer/resizable/subarray-parameter-conversion-grows.js   ❌ -> ✅
test/staging/ArrayBuffer/resizable/subarray-parameter-conversion-shrinks.js ❌ -> ✅
```

LibJS: Implement missing conditional when creating a TypedArray subarray

---

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp

Two fixes:
- Stop wasting time rendering URLs as `img alt` placeholders since they are not useful to anyone, and longer URLs (especially `data:` URLs) can waste a lot of time.
- Put a limit on how many image loads we're willing to batch up & defer before flushing processing. This makes "image gallery" like pages display something interesting *way* sooner.
Here's an example before/after of a 4chan board catalog page. Before these changes, it takes almost 5 seconds before we see images. After changes, it takes ~1.1sec.
https://github.com/SerenityOS/serenity/assets/5954907/5e0be796-9cac-4189-b21d-577abb7d3bee
https://github.com/SerenityOS/serenity/assets/5954907/ddc1e760-9042-4ead-927b-140fa3c7351d

LibWeb: Make pages with a lot of images display a lot faster

---

Meta/run.py

Still try parsing the now gone `-audio-help` output first, then attempt the new `-audiodev help` if stdout was empty. This fixes support for QEMU 8.2+ audio since `-audio-help` is now an invalid option: https://gitlab.com/qemu-project/qemu/-/commit/69a80279
For reference here's the outputs on Ubuntu 22.04 LTS:
```
$ qemu-system-x86_64 --version
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.15)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
$ qemu-system-x86_64 -audio-help
Environment variable based configuration deprecated.
Please use the new -audiodev option.
Equivalent -audiodev to your current environment variables:
(Since you didn't specify QEMU_AUDIO_DRV, I'll list all possibilities)
-audiodev id=pa,driver=pa
-audiodev id=alsa,driver=alsa
-audiodev …
```

Meta: Add support for QEMU 8.2 audio

---

Userland/Applications/FileManager/PropertiesWindow.cpp
Userland/Applications/FileManager/PropertiesWindowImageTab.gml

If the "ICC Profile" group is shown, no need to include the related line in the "Image" group.
---

FileManager: Conditionally display the "ICC profile:" line

---

Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h

This allows to remove checks whether translation has value, as it does not change anything because default value for point is zero.

LibWeb: Do not use Optional for aa_translation in RecordingPainter

---

Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
Userland/Libraries/LibJS/Runtime/ErrorTypes.h
Userland/Libraries/LibJS/Runtime/SharedArrayBufferPrototype.cpp
Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.detached.js
Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.slice.js
Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.transfer.js
Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.transferToFixedLength.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.wait.js
Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.waitAsync.js
Userland/Libraries/LibJS/Tests/builtins/SharedArrayBuffer/SharedArrayBuffer.prototype.byteLength.js
Userland/Libraries/LibJS/Tests/builtins/SharedArrayBuffer/SharedArrayBuffer.prototype.slice.js

We now pass all tests in `test/built-ins/ArrayBuffer`, `test/built-ins/DataView`, `test/built-ins/TypedArray`, and `test/built-ins/TypedArrayConstructors`.
```
Diff Tests:
+11 ✅    -11 ❌
test/built-ins/ArrayBuffer/prototype/detached/this-is-sharedarraybuffer-resizable.js    ❌ -> ✅
test/built-ins/ArrayBuffer/prototype/detached/this-is-sharedarraybuffer.js              ❌ -> ✅
test/built-ins/ArrayBuffer/prototype/slice/this-is-sharedarraybuffer.js                 ❌ -> ✅
test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-larger.js               ❌ -> ✅
test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-same.js                 ❌ -> ✅
test/built-ins/ArrayBuffer/prototype/transfer/from-resizable-to-smaller.js              ❌ -> ✅ …
```

LibJS: Implement missing checks for SharedArrayBuffer and missing steps from the ArrayBuffer transfer proposal

---

AK/Format.cpp
Userland/Libraries/LibCore/StandardPaths.cpp

This should eliminate the need for two of the three patches in https://cgit.freebsd.org/ports/tree/www/ladybird/files?id=16f2f4c4df2ddeefb9612870166e6f15237cc4d4
cc @nipos

AK+LibCore: Add some BSD portability patches

---

Meta/Lagom/CMakeLists.txt

This unbreaks ENABLE_LAGOM_LIBWEB=OFF again.
@trflynn89 GitHub doesn’t let me reopen the old pull request unfortunately...

Tests: Don't include LibWebView test if LibWeb is disabled

---

Tests/LibGfx/TestImageDecoder.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

We currently assume that the K (black) channel uses the same sampling
as the Y channel already, so this already works as long as we don't
error out on it.

LibGfx/JPEG: Make ycck jpegs with just cc subsampled decode correctly

---

Ladybird/Qt/Tab.cpp

According to Qt documentation, destruction of a QObject's children may happen in any order. In our case, the Tab's WebContentView is deleted before its InspectorWidget. The InspectorWidget performs cleanup on that WebContentView in its destructor; this causes use-after-free since it has already been destroyed.
From reading Qt threads, if a particular destruction order is required, it is okay to enforce that order with manual `delete`s. This patch does so with the InspectorWidget to ensure it is deleted before the WebContentView. Qt's object ownership is okay with this - it will remove the InspectorWidget from the Tab's children, preventing any double deletion.
Fixes #22279

Ladybird/Qt: Ensure the Inspector widget is deleted before the WebView

---

Kernel/Prekernel/multiboot.S

This is required for pretty much every bare metal install and doesn't seem to have any effect on running in QEMU, so let's enable it by default.

Kernel: Enable MULTIBOOT_VIDEO_MODE by default

---

Kernel/Memory/MemoryManager.cpp

riscv64 doesn't use a prekernel, so use the same code as aarch64 for determining the kernel virtual address range.

Kernel/riscv64: Return correct range in `kernel_virtual_range` on RISC-V

---

Tests/LibWeb/TestConfig.ini

LibWeb: Skip window-scrollTo test that keeps timing out on macOS

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

The decoder assumes that k's sampling factor matches y's at the moment. Better to error out than to silently render something broken.
For ycck, covered by ycck-2111.jpg in the tests.

LibGfx/JPEG: Reject ycck or cmyk jpegs with k subsampled for now

---

Tests/LibWeb/Ref/reference/scrollable-box-with-nested-stacking-context-ref.html
Tests/LibWeb/Ref/scrollable-box-with-nested-stacking-context.html
Userland/Libraries/LibGfx/TextLayout.h
Userland/Libraries/LibWeb/Painting/PaintContext.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
Userland/Services/WebContent/PageClient.cpp

With this change, instead of applying scroll offsets during the recording of the painting command list, we do the following:
1. Collect all boxes with scrollable overflow into a PaintContext, each with an id and the total amount of scrolling offset accumulated from ancestor scrollable boxes.
2. During the recording phase assign a corresponding scroll_frame_id to each command that paints content within a scrollable box.
3. Before executing the recorded commands, translate each command that has a scroll_frame_id by the accumulated scroll offset.
This approach has following advantages:
- Implementing nested scrollables becomes much simpler, as the recording phase only requires the correct assignment of the nearest scrollable's scroll_frame_id, while the accumulated offset from ancestors is …

LibWeb: Apply scroll boxes offsets after painting commands recording

---

Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp

With this change, we create substantially fewer border painting commands, which means fewer reallocations of the vector that stores commands.
This makes the rendering of
https://html.spec.whatwg.org/multipage/browsing-the-web.html visibly faster, where we allocated ~10 of such commands now vs ~8000 before.

LibWeb: Skip empty paint borders commands in RecordingPainter

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

Fixes https://github.com/SerenityOS/serenity/issues/22485
With this change WebContent does not crash when `location.reload()` is invoked but `Navigable::reload()` still not working because of spec issue (https://github.com/whatwg/html/issues/9869) so we can't add a test yet.

LibWeb: Wait until new document becomes active before running scripts

---

AK/SegmentedVector.h
Tests/AK/CMakeLists.txt
Tests/AK/TestSegmentedVector.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h

Using a vector to represent a list of painting commands results in many
reallocations, especially on pages with a lot of content.
This change addresses it by introducing a SegmentedVector, which allows
fast appending by representing a list as a sequence of fixed-size
vectors. Currently, this new data structure supports only the
operations used in RecordingPainter, which are appending and iterating.

AK+LibWeb: Use segmented vector to store commands in RecordingPainter

---

Userland/Demos/Mandelbrot/CMakeLists.txt
Userland/Demos/Mandelbrot/Mandelbrot.cpp

This allows us to stop using raw `FILE*` and reintroduce `unveil` calls.

Mandelbrot: Modernize code by using the FileSystemAccessClient

---

Userland/Libraries/LibGfx/ICC/Profile.cpp

In XYZ space, gray doesn't have three equal values. Instead, it is a line through the whitepoint.
(Multiplying by the whitepoint has the same effect as multiplying the sRGB matrix with a (g, g, g) vector, since the numbers on the matrix's rows add up to the whitepoint.)
Fixes the very slight red tint on all the figures in chapter 4 of the PDF 1.7 spec.

LibGfx/ICC: Improve XYZ coordinates of gray colors

---

Userland/Applications/Assistant/main.cpp
Userland/Applications/Spreadsheet/main.cpp
Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
Userland/Libraries/LibJS/Heap/BlockAllocator.h
Userland/Libraries/LibJS/Heap/CellAllocator.cpp
Userland/Libraries/LibJS/Heap/CellAllocator.h
Userland/Libraries/LibJS/Heap/Heap.h
Userland/Libraries/LibJS/Heap/HeapBlock.cpp
Userland/Libraries/LibJS/Heap/HeapBlock.h
Userland/Services/WebContent/main.cpp
Userland/Utilities/js.cpp

Instead of returning `HeapBlock` memory to the kernel (or a non-type specific shared cache), we now keep a `BlockAllocator` per `CellAllocator` and implement "deallocation" by basically informing the kernel that we don't need the physical memory right now.
This is done with `MADV_FREE` or `MADV_DONTNEED` if available, but for other platforms (including SerenityOS) we `munmap` and then re-`mmap` the memory to achieve the same effect. It's definitely clunky, so I've added a `FIXME` about implementing the `madvise` options on SerenityOS too.
The important outcome of this change is that GC types that use a type-specific allocator become immune to type confusion attacks, since their virtual addresses will only ever be re-used for the same exact type again and again.
Fixes #22274

LibJS: Never give back virtual memory once it belongs to a cell type

---

Userland/Libraries/LibHTTP/Job.cpp

Some servers decide to add newlines (and not \r\n) into that field, this commit makes us tolerate that and not crash in cases like in #22463.
Fixes #22463.

LibHTTP: Tolerate random whitespace in chunked encoding size field

---

Tests/LibWeb/Ref/calc-border-radius.html
Tests/LibWeb/Ref/reference/calc-border-radius-ref.html
Userland/Libraries/LibWeb/CSS/StyleValues/BorderRadiusStyleValue.cpp

`BorderRadiusStyleValue::absolutized` should not try to extract length from LengthPercentage that represents calculated.

LibWeb/CSS: Fix crashing when calc() is used for border-radius

---

Userland/Libraries/LibWeb/CSS/StyleValues/AbstractImageStyleValue.h
Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp

This yields a huge speedup on pages that use this weird but not-entirely-uncommon technique.
https://github.com/SerenityOS/serenity/assets/5954907/a72bbbb2-3878-4a54-a940-4491088bc63a

LibWeb: Paint 1x1 backgrounds as color fill instead of tiling bitmap

---

Userland/Libraries/LibWebView/InspectorClient.cpp

This was causing reproducible crashes, when closing the inspector window of ladybird running on macos.
````bash
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc98)
frame #0: 0x00000001013f9c4c liblagom-webview.0.dylib`::run_javascript() [inlined] operator! at RefPtr.h:226:38 [opt]
223          unref_if_not_null(ptr);
224      }
225
-> 226      bool operator!() const { return !m_ptr; }
227
228      [[nodiscard]] T* leak_ref()
229      {
Target 0: (Ladybird) stopped.
warning: liblagom-webview.0.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc98)
* frame #0: 0x00000001013f9c4c …
```

Ladybird+LibWebView: Cleanup missing callbacks in InspectorClient

---

Meta/run.py

This PR adds initial support for RISC-V in run.py, so `serenity.sh run riscv64` should work now!
Note: The current `Processor::halt` placeholder in `pre_init` seems to cause an an absolute jump when using GCC, so you will get a lot of `Invalid read at addr 0x2000211C98, size 2, region '(null)', reason: rejected` when using the gnu toolchain.
I am not entirely happy how architectures are handled in run.py, but this should be good enough for now (we can always refactor later!)

Meta: Add RISC-V support to run.py

---

Kernel/Arch/riscv64/CSR.h
Kernel/Arch/riscv64/CurrentTime.cpp
Kernel/Arch/riscv64/Timer.cpp
Kernel/Arch/riscv64/Timer.h
Kernel/CMakeLists.txt
Kernel/Time/HardwareTimer.h
Kernel/Time/TimeManagement.cpp

This PR adds support for the hart-local timer as defined by the privileged ISA.
This timer uses the SBI to set up the timer interrupts.
The code falls back to the legacy SBI extension, as we don't have any generic SBI extension probing code.

Kernel/riscv64: Add support for hart-local RISC-V Timer

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp

Fixes oss-fuzz issues [65392](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65392) and [65401](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65401)
The first one has a sample with a declared bit depth of more than 65 000 and the second one has two samples with null bit depth.

LibGfx/TIFF: Resolve more oss-fuzz issues

---

Meta/gn/secondary/Ladybird/BUILD.gn
Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
Meta/gn/secondary/Ladybird/enable_qt.gni
Meta/gn/secondary/Userland/Libraries/LibCompress/BUILD.gn
Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn

With this, it's possible to build Ladybird without having Qt installed.
(Previously, the build required `moc` to exist.)
In fact, it's possible to build Ladybird without anything off `brew`
as long as you have `ninja` and `gn` (both of which don't have any
dependencies themselves and are easy to build).

Meta/gn: Build WebContent Qt bits only if enable_qt is set

---

Tests/LibWeb/Ref/abspos-z-index-painting-order.html
Tests/LibWeb/Ref/reference/abspos-z-index-painting-order-ref.html
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

Instead of implementing stacking context painting order exactly as it is defined in CSS2.2 "Appendix E. Elaborate description of Stacking Contexts" we need to account for changes in the latest standards where a box can establish a stacking context without being positioned, for example, by having an opacity different from 1.
Fixes https://github.com/SerenityOS/serenity/issues/21137

LibWeb: Do not require box to be positioned to create stacking context

---

Base/res/ladybird/inspector.js

In the UI process, we encode generated HTML as Base64 to avoid having to deal with things like arbitrarily nested quotes. The HTML is encoded as UTF-8, and the raw bytes of that encoding are transcoded to Base64.
In the Inspector process, we are decoding the Base64 string using `atob`, which has awkward non-Unicode limitations. The resulting string is only a byte string. We must further decode the bytes as UTF-8, which we do using `TextDecoder`.
Fixes #22536 
Before:
After:

LibWebView: Properly decode Base64-encoded strings as UTF-8

---

Tests/LibPDF/TestPDF.cpp
Userland/Libraries/LibPDF/Parser.cpp

A local (non-public) PDF I have lying around contains this in a page's operator stream:
```
[<00b4003e> 3 <002600480051> 3 <005700550044004f0003> -29
<00330044> 3 <0055> -3 <004e0040> 4 <0003> -29 <004c00560003> -31
<0057004b> 4 <00480003> -37 <0050
>] TJ
```
That is, there's a newline in a hexstring after a character.
This led to `Parser error at offset 5184: Unexpected character`.
The spec says in 3.2.3 String Objects, Hexadecimal Strings: """Each pair of hexadecimal digits defines one byte of the string. White-space characters (such as space, tab, carriage return, line feed, and form feed) are ignored."""
But we didn't ignore whitespace before or after a character, only in between the bytes.
The spec also says:
"""If the final digit of a hexadecimal string is missing—that is, if there …

LibPDF: Improve hex string parsing

---

Userland/Libraries/LibPDF/Document.cpp
Userland/Libraries/LibPDF/DocumentParser.cpp
Userland/Libraries/LibPDF/DocumentParser.h

Other readers do this too, and files depend on this.
Fixes opening these four files from the PDFA 0000.zip dataset:
* 0000015.pdf Starts with `C:\web\webeuncet\_cat\_docs\_publics\` before header
* 0000408.pdf Starts with UTF-8 BOM
* 0000524.pdf Starts with 867 bytes of HTML containing a PHP backtrace
* 0000680.pdf Starts with `C:\web\webeuncet\_cat\_docs\_publics\` too
---
I've had this sitting in a local branch for 2.5 months now since it's kinda gross, but being able to open these files makes up for it. Right? Riiight???

LibPDF: Scan for PDF file start in first 1024 bytes

---

Meta/gn/secondary/Userland/Libraries/LibIPC/BUILD.gn
Userland/Libraries/LibIPC/CMakeLists.txt
Userland/Libraries/LibIPC/Connection.cpp
Userland/Libraries/LibIPC/Encoder.h
Userland/Libraries/LibIPC/Forward.h
Userland/Libraries/LibIPC/Message.cpp
Userland/Libraries/LibIPC/Message.h
Userland/Libraries/LibIPC/Stub.h
Userland/Libraries/LibWeb/HTML/MessagePort.cpp

For every IPC message sent, we currently prepend the message size to the IPC message buffer. This incurs the cost of copying the entire message to its newly allocated position. Instead, reserve the bytes for the size at the front of the buffer upon creation. Prevent dangerous access to the buffer with specific public methods.
Further, the actual transfer of the message is moved to a helper method. This removes copy-pasted duplication in LibWeb's MessagePort, and also ensures callers can't forget to set the buffer size before transfer.
Fixes #22358

LibIPC+LibWeb: Avoid redundant copy of every tranferred IPC message

---

Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h

The main change here is making use of `fast_u32_fill()` within the rasterizer for solid colors, which brought the above fullscreen (in SerenityOS) demo from 15 fps to around 25 (note the fps dropped to 22 while recording). 
Note: That there's quite a bit outside just the rasterizer that's a little slow here. Each rotation copies the path and invalidates the line segments, so that all gets regenerated. There's also uses of strokes that generate a new path per-frame. There's probably some low hanging fruit still.

LibGfx: Speed up filling solid color paths a little (and some misc changes)

---

Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/HTML/Window.h
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.h

This avoids an assertion that timers are not active when destroyed.

LibWeb: Stop timers when finalizing a Window or WorkerGlobalScope

---

Tests/LibCompress/TestBrotli.cpp
Userland/Libraries/LibCompress/Brotli.cpp

We previously skipped updating the lookback buffer when copying uncompressed data, which resulted in a wrong total byte count. With a wrong total byte count, our decompressor implementation ended up choosing a wrong offset into the dictionary.
Fixes #22355

LibCompress/Brotli: Update the lookback buffer with uncompressed data

---

Base/home/anon/.config/Taskbar.ini

As the name of the Browser app is now titled Ladybird this was resulting in a double up if installed fresh then rebooted (or likely after an upgrade). This change corrects this by using the Ladybird title

Taskbar: Use name of Ladybird as default QuickLaunch

---

Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp

These are valid per spec, and do sometimes occur in practice, e.g. in embedded fonts in 0000550.pdf and 0000246.pdf in 0000.zip in the PDFA test set.

LibGfx/OpenType: Survive simple glyphs with 0 contours

---

Tests/LibWeb/Text/expected/DOM/Range-to-string.txt
Tests/LibWeb/Text/input/DOM/Range-to-string.html
Userland/Libraries/LibWeb/DOM/AbstractRange.cpp
Userland/Libraries/LibWeb/DOM/AbstractRange.h
Userland/Libraries/LibWeb/DOM/Range.cpp
Userland/Libraries/LibWeb/DOM/Range.h

Similar to another problem we had in CharacterData, we were assuming
that the offsets were raw utf8 byte offsets into the data, instead of
utf16 code units. Fix this by using the substring helpers in
CharacterData to get the text data from the Range.
There are more instances of this issue around the place that we will
need to track down and add tests for, but this fixes one of them :^)
For the test included in this commit, we were previously returning:
llo💨😮
Instead of the expected:
llo💨😮 Wo

LibWeb: Use UTF-16 code unit offsets in Range::to_string

---

Userland/Libraries/LibPDF/Encoding.cpp

Per "TABLE 5.11 Entries in an encoding dictionary", /Differences is
optional.
(Per "Encodings for TrueType Fonts" in 5.5.5 Character Encoding,
nonsymbolic truetype fonts are even recommended to have "no Differences
array." But in practice, most seem to have it.)
Fixes crashes on:
* 0000001.pdf
* 0000574.pdf
* 0000337.pdf
All three don't render super great, but at least they no longer crash.
---
Just adds an if and indents the body, no other change.
Form 8 crashes with 5 distinct stacks to 5 crashes with 4 distinct stacks on the 1000 pdf 0000.zip PDFA test set.

LibPDF: An Encoding's /Differences entry is optional

---

Userland/Libraries/LibPDF/DocumentParser.cpp
Userland/Libraries/LibPDF/Reader.cpp
Userland/Libraries/LibPDF/Reader.h

The spec isn't super clear on if this is allowed:
"""Each cross-reference section shall begin with a line containing the
keyword xref. Following this line..."""
"""The two preceding lines shall contain, one per line and in order, the
keyword startxref and..."""
It kind of sounds like anything goes on both lines as long as they
contain `xref` and `startxref`.
In practice, both seem to always occur at the start of their line,
but in 0000780.pdf (and nowhere else), there's one space after each
keyword before the following linebreak, and this makes that file load.

LibPDF: Tolerate whitespace after `xref` and `startxref`

---

Userland/Libraries/LibPDF/DocumentParser.cpp

At first I tried implmenting the quirk from PDF 1.7 Appendix H,
3.4.4, "File Trailer": """Acrobat viewers require only that the %%EOF
marker appear somewhere within the last 1024 bytes of the file.""
This would've been like https://github.com/SerenityOS/serenity/pull/22548 but at end-of-file instead of at
start-of-file.
This helped a bunch of files, but also broke a bunch of files that
made more than 1024 bytes of stuff at the end, and it wouldn't have
helped 0000059.pdf, which has over 40k of \0 bytes after the %%EOF.
So just tolerate whitespace after the %%EOF line, and keep ignoring
and arbitrary amount of other stuff after that like before.
This helps:
* https://github.com/SerenityOS/serenity/commit/00005991f12356ba358801a87296c97b2d7b6148.pdf
One trailing \0 byte after %%EOF. Due to …

LibPDF: Tolerate trailing whitespace after %%EOF marker

---

Tests/LibWeb/Text/expected/DOM/DOMImplementation-create-xml-document.txt
Tests/LibWeb/Text/expected/DOM/DOMParser-xml-document.txt
Tests/LibWeb/Text/input/DOM/DOMImplementation-create-xml-document.html
Tests/LibWeb/Text/input/DOM/DOMParser-xml-document.html
Userland/Libraries/LibWeb/DOM/DOMImplementation.cpp
Userland/Libraries/LibWeb/DOM/XMLDocument.h
Userland/Libraries/LibWeb/HTML/DOMParser.cpp

I was playing around again trying to figure out why attributes are not having namespaces applied, and stumbled across these small fixes (and a crash).

LibWeb: Fix crash in DOMImplementation for null namespaces and actually create XML documents

---

Userland/Libraries/LibPDF/DocumentParser.cpp

0000440.pdf contains an xref stream object (at offset 3643676) starting:
```
294 0 obj <<
/Type /XRef
/Index [0 295]
/Size 295
```
and an object stream object (at offset 3640121) starting:
```
230 0 obj <<
/Type /ObjStm
/N 73
/First 614
```
In both cases, the `obj` and the `<<` are separated by non-newline whitespace.
633e1632d01a854 made parse_indirect_value() tolerate this, but it didn't update neither parse_xref_stream() (which parses xref streams) nor parse_compressed_object_with_index() (which parses object streams), despite all three changes being part of #14873.
Make parse_xref_stream() and parse_compressed_object_with_index() call parse_indirect_value() to pick up the fix over there. It's a bit less code too.
(0000440.pdf is the only PDF in my 1000 test PDFs that this helps, …

LibPDF: Port 59b50fa43f8c2 to xref and object streams

---

AK/Utf16View.cpp
AK/Utf16View.h
Tests/AK/TestUtf16.cpp
Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
Userland/Libraries/LibJS/Runtime/StringPrototype.h
Userland/Libraries/LibJS/Runtime/Value.cpp

There was recently a normative change to this AO in ECMA-262. See:
https://github.com/tc39/ecma262/commit/5eaee2f
It turns out we already implemented this to align with web-reality
before it was codified in the spec. This was a bit difficult to reason
without spec text and with a somewhat ad-hoc implementation. So this
patch aligns our implementation with the spec. There should not be any
behavior change.
No test262 diff.

AK+LibJS: Implement the GetSubstitution AO according to the spec

---

AK/ByteString.h
AK/StringUtils.cpp
AK/StringView.h
Tests/AK/TestStringUtils.cpp

The current algorithm is currently O(N^2) because we forward-search an
ever-increasing substring of the haystack. This implementation reduces
the search time of a 500,000-length string (where the desired needle is
at index 0) from 72 seconds to 2-3 milliseconds.

AK: Improve performance of StringUtils::find_last

---

Tests/LibWeb/TestMimeSniff.cpp
Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
Userland/Libraries/LibWeb/MimeSniff/Resource.h

Adds font-specific context sniffing and rules for distinguishing if a resource is text or binary.

LibWeb/MimeSniff: Add a few more MIME type sniffing algos

---

Userland/Libraries/LibPDF/Function.cpp

---
Maybe a bit easier to read? Not sure.

LibPDF: Use mix() in SampledFunction::evaluate()

---

Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

Let's consistently use available space from `m_available_space`.
No behavior change expected.

LibWeb: Remove available space from track sizing method params in GFC

---

Kernel/FileSystem/Ext2FS/FileSystem.cpp
Kernel/FileSystem/Ext2FS/FileSystem.h
Kernel/FileSystem/Ext2FS/Inode.cpp
Userland/Libraries/LibCore/DirIterator.cpp
Userland/Libraries/LibCore/DirectoryEntry.cpp
Userland/Libraries/LibCore/DirectoryEntry.h

Currently, we treat extended Ext2 attributes as if they are always available, which may not be the case for all Ext2 filesystems, such as those generated by `genext2fs`. With this PR, we avoid exposing extended attributes when the filesystem doesn't explicitly claim to support them.
`DirIterator::advance_next()` was also missing checks for valid file type attributes, so that has also been addressed.
Fixes #22533, though we should still store/expose file type attributes when possible for other filesystems.
cc @alimpfard

Kernel+LibCore: Fixes to file type attribute handling

---

Userland/Services/RequestServer/ConnectionCache.h
Userland/Services/RequestServer/ConnectionFromClient.cpp
Userland/Services/RequestServer/GeminiProtocol.cpp
Userland/Services/RequestServer/HttpCommon.h

Fixes #22582
Previously, the job and the (cache of them) would lead to a UAF, as after `.start()` was called on the job it'd be immediately destroyed.
Example of previous bug:
```
// Note due to the cache &jobA == &jobB
auto& jobA = Job::ensure("https://r.bing.com/");
auto& jobB = Job::ensure("https://r.bing.com/");
// Previously, the first .start() free'd the job
jobA.start();
// So the second .start() was a UAF
jobB.start();
```
I'm not too familiar with RequestServer, but as far as I can tell this fixes the issue.

RequestServer: Make pre-connection job refcounted

---

Tests/LibGfx/TestImageDecoder.cpp
Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp

This fixes an issue where GIF images without a global color table would have the first segment incorrectly interpreted as color table data.
Makes many more screenshots appear on https://virtuallyfun.com/ :^)
Before:
After:

LibGfx/GIF: Only parse global color table if header flag is set

---

Tests/LibWeb/Layout/expected/grid/line-placement-with-repeat.txt
Tests/LibWeb/Layout/input/grid/line-placement-with-repeat.html
Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
Userland/Libraries/LibWeb/CSS/GridTrackSize.h
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

Before this change, parsed grid-template-columns/grid-template-rows were represented as two lists: line names and track sizes. The problem with this approach is that it erases the relationship between tracks and their names, which results in unnecessarily complicated code that restores this data (incorrectly if repeat() is involved) during layout. This change solves that by representing line definitions as a list of sizes and names in the order they were defined.
Visual progression on https://genius.com/

LibWeb: Fix grid line name placement when repeat() is used

---

Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp

The specification uses awkward numbering, marking the first byte as 7, and the last one as 0, which caused me to misunderstand their ordering, and use the last byte's address as the first one, and so on.

Kernel: Replace incorrect RTL8168 multicast config registers address

---

Tests/LibWeb/Ref/inline-stacking-context.html
Tests/LibWeb/Ref/reference/inline-stacking-context-ref.html
Tests/LibWeb/Text/expected/hit_testing/inline-stacking-context.txt
Tests/LibWeb/Text/input/hit_testing/inline-stacking-context.html
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.h
Userland/Libraries/LibWeb/Painting/Paintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Userland/Libraries/LibWeb/Painting/StackingContext.h
Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp

With this change, a stacking context can be established by any
paintable, including inline paintables. The stacking context traversal
is updated to remove the assumption that the stacking context root is
paintable box.

LibWeb: Allow inline nodes to establish a stacking context

---

AK/Span.h
Userland/Libraries/LibWeb/HTML/MessagePort.cpp

Dispatching events can cause arbitrary JS to run, which could cause the
event loop to be re-entered, or even post another message to the same
message port.
Fixes #22381

LibWeb: Reset message port receive state before dispatching events

---

Userland/Libraries/LibLine/Editor.cpp
Userland/Libraries/LibLine/Editor.h
Userland/Libraries/LibLine/InternalFunctions.cpp

Before these used to skip only one non-alnum instead of all the consecutive
ones. Now it matches behaviour with bash/readline.
```
Two new internal functions `cursor_left_nonspace_word()` (`Ctrl+Alt+B`)
and `cursor_right_nonspace_word()` (`Ctrl+Alt+F`) that jump the cursor
left or right until a non-space character.
Same implementation as the alphanumeric word jump functions
`cursor_left_word()` (`Alt+B`) and `cursor_right_word()` (`Alt+F`).
```
```
Every cut operation (erase last word backward/forward, erase line till
start/end) stores the erased characters in `m_last_erased` byte string.
The last erased characters will get inserted into the buffer when
`Ctrl+Y` (`insert_last_erased()` internal function) is pressed.
```
gnu readline can do much more than this: whole stack of erased …

LibLine: Cursor jump non-space word and cut-and-paste functionality

---

Kernel/Net/NetworkTask.cpp

According to RFC 9293 Section 3.6.1. Half-Closed Connections, we should still accept incoming packets in the FinWait2 state. Additionally, we didn't handle the FIN+ACK case. We should handle this the same way we handle the FIN flag. The ACK is only added to signify successful reception of the last packet.

Kernel: Add unhandled cases for the FinWait2 state

---

Userland/Libraries/LibGUI/BoxLayout.cpp
Userland/Libraries/LibGUI/CMakeLists.txt
Userland/Libraries/LibGUI/Layout.cpp
Userland/Libraries/LibGUI/Margins.h
Userland/Libraries/LibGUI/Object.h
Userland/Libraries/LibGUI/PropertyDeserializer.cpp
Userland/Libraries/LibGUI/PropertyDeserializer.h
Userland/Libraries/LibGUI/TabWidget.cpp
Userland/Libraries/LibGUI/UIDimensions.h
Userland/Libraries/LibGUI/Widget.cpp
Userland/Libraries/LibGUI/Widget.h
Userland/Libraries/LibGUI/Window.cpp

Yes, I know, I am generally not really interested in Serenity-specific stuff. And yes, I know, I was porting `DeprecatedString` to `StringBase`. But suddenly task stack became really deep:
- port `DeprecatedString` to `StringBase`
- remove references to `StringImpl`
- port `JsonValue` to `Variant` and `StringBase`
- remove odd `T JsonValue::to_something(T default_value)` API
- make LibGUI not use this API
- do something so that GMLPlayground will not instantly crash on invalid input
Property deserializer is a small class which converts JsonValue to a required type while doing robust error checking at the same time. And previously that error checking in deserializing was basically "if something is supposed to be int but is not, a developer definitely wanted 0 there". What's more, if …

LibGUI: Introduce property deserializers to catch errors in GML property values

---

Userland/Libraries/LibGUI/AboutDialog.gml

Make all About dialogs show copyright up to the current year.
Happy New Year everyone!

LibGUI: Make AboutDialog Copyright 2018-2024

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/Tab.cpp
Userland/Applications/Browser/Tab.cpp
Userland/Libraries/LibWeb/HTML/ColorPickerUpdateState.h
Userland/Libraries/LibWeb/Page/Page.cpp
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentServer.ipc

The input color picker currently only sends an color value back on the picker close. This pr changes that so that the color picker can give a continues stream of update color value like other browser do.
https://github.com/SerenityOS/serenity/assets/19894029/1c1b820f-2841-4600-9228-cac0316e427f

LibWeb: Allow input color to give continues updates

---

Tests/LibWeb/Layout/expected/grid/grid-item-vertical-padding-and-margin-percentages.txt
Tests/LibWeb/Layout/input/grid/grid-item-vertical-padding-and-margin-percentages.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Percentage vertical margin and padding values are relative to the containing block *width*, not *height*. This has to be one of the most commonly recurring mistakes we make :^)
Visual progress on https://splice.com/
Before:
After:

LibWeb: Resolve grid item vertical margin/padding against CB width

---

Ladybird/AppKit/UI/LadybirdWebView.mm
Ladybird/Qt/Tab.cpp
Userland/Applications/Browser/Tab.cpp
Userland/Libraries/LibGUI/Dialog.h
Userland/Libraries/LibGUI/MessageBox.cpp
Userland/Libraries/LibGUI/MessageBox.h

People often ask "where did my screenshot go :(", so this displays where the screenshot is saved and presents an option
to open its containing folder.
In the future, it'd be nicer to have a downloads manager, and then we can pipe screenshots through that.
https://github.com/SerenityOS/serenity/assets/5600524/6c02c6e8-cc38-4e44-b1fb-580b9d256e97
https://github.com/SerenityOS/serenity/assets/5600524/650c9483-5518-4437-9559-d4d67d4816a1
https://github.com/SerenityOS/serenity/assets/5600524/266cabbb-4a5d-4227-849e-e7de883f7f5c

Ladybird: Show an informational dialog after taking a screenshot

---

Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp

We were trying to read exactly 5 pairs for some reason, instead of the number specified by the format 0 header.
Fixing this makes "OpenSans Condensed" load on my machine.

LibGfx/OpenType: Read the correct number of pairs from kern table

---

Tests/LibWeb/Layout/expected/grid/columns-auto-fill-with-gap-2.txt
Tests/LibWeb/Layout/input/grid/columns-auto-fill-with-gap-2.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

Fixes the mistake that gaps are counted as if they exist after each track, when actually gaps are present only between tracks.
Visual progression on https://kde.org/products/

LibWeb: Fix auto-fill track counting to correctly handle gaps in GFC

---

Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp

When navigating to a plain image url a simple HTML page is generated around it in `DocumentLoading.cpp`, I have added some CSS styling to make that page some what more pleasant to look at. It now features a dark background with a centered media element, clamped to the viewport width and height like Firefox and Chrome.
There is also still an issue that the page title is not updated but I think that has something to do with navigatables.

LibWeb: Improve media document styling to center image

---

Tests/LibWeb/Layout/expected/grid/auto-fill-rows.txt
Tests/LibWeb/Layout/input/grid/auto-fill-rows.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.h

This change fixes the function that calculates the number of auto-fill tracks, ensuring it uses height when applied to rows, instead of assuming that it always operates on columns.

LibWeb: Support auto-fill for rows in GFC

---

Userland/Libraries/LibWeb/CSS/PercentageOr.h

In 4bc38300ad9e7ca7665bd6afa0ab9c0557807286 this function was modified to accept only Angle instead of being templated, with the purpose of preventing Length from being passed.
This change reverts the function to being templated but adds a constraint specifically forbidding Length. This adjustment will allow for the future use of Frequency, Number, Time, etc., if we would want.
cc @AtkinsSJ

LibWeb/CSS: Revert to PercentageOr::resolve() to be templated

---

Base/res/html/misc/cookie.html
Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp

Previously, the cookie date validation did not validate days in the context of the month and year, resulting in dates that do not exist to be successfully parsed (e.g. February 31st). We now validate that the day does not exceed the number of days for the given month and year, taking leap years into account.

LibWeb: Fail to parse cookie date when date does not exist

---

Tests/LibWeb/Layout/expected/style-invalidation-line-height-propagation.txt
Tests/LibWeb/Layout/expected/table/style-invalidation-propagation-to-table-wrapper.txt
Tests/LibWeb/Layout/input/style-invalidation-line-height-propagation.html
Tests/LibWeb/Layout/input/table/style-invalidation-propagation-to-table-wrapper.html
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Layout/Node.h

- We now propagate changes in font and line-height to anonymous wrappers when doing a partial style update after invalidation.
- We no longer (incorrectly) propagate style from table wrapper boxes to the table root, since inheritance works in the other direction.
Fixes #22395

LibWeb: Improve style propagation to anonymous wrappers

---

Userland/Libraries/LibGfx/ICC/Profile.cpp
Userland/Libraries/LibGfx/ICC/TagTypes.h
Userland/Utilities/icc.cpp

This is enough to make these work:
for f in VideoHD VideoNTSC VideoPAL; do
Build/lagom/bin/icc --debug-roundtrip \
~/Downloads/Adobe\ ICC\ Profiles\ \(end-user\)/RGB/$f.icc
done
It's also possible to convert images to those color spaces:
Build/lagom/bin/image -o image-pal.png \
--convert-to-color-profile path/to/RGB/VideoPAL.icc \
image-srgb.png
(If there's no png file with an embedded sRGB profile at hand, do first:
Build/lagom/bin/icc --reencode-to serenity-sRGB.icc -n sRGB
Build/lagom/bin/image -o image-srgb.png \
--assign-color-profile serenity-sRGB.icc image-no-color-space.png
)
In color-managed viewers, images-srgb.png and image-pal.png should
look identical.
But if you either explicitly assign the sRGB profile to the pal
image, or strip the embedded color space, they'll look …

LibGfx/ICC: Implement LutBToATagData::evaluate() when there is no CLUT; also add --debug-roundtrip to `icc`

---

Tests/LibWeb/Ref/border-radius-with-padding.html
Tests/LibWeb/Ref/reference/border-radius-with-padding-ref.html
Userland/Libraries/LibWeb/Layout/LayoutState.cpp

Before this change, we were resolving border radii values based on content box + border widths only, ignoring padding.
Visual progression on https://splice.com ("Try free" button, top right)
Before:
After:

LibWeb: Take padding into account when resolving border radii

---

Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Userland/Applications/ImageViewer/ViewWidget.cpp
Userland/Applications/PixelPaint/Image.cpp
Userland/Libraries/LibCore/EventLoop.cpp
Userland/Libraries/LibGUI/CMakeLists.txt
Userland/Libraries/LibGUI/FileSystemModel.cpp
Userland/Libraries/LibImageDecoderClient/Client.cpp
Userland/Libraries/LibImageDecoderClient/Client.h
Userland/Services/ImageDecoder/ConnectionFromClient.cpp
Userland/Services/ImageDecoder/ConnectionFromClient.h
Userland/Services/ImageDecoder/ImageDecoderServer.ipc

Process separation is a great way to prevent malicious users to crash
the GUI with images file that makes one of our decoder crash.
It also makes life easier when developing image decoders.

LibGUI: Render thumbnails out of process

---

Userland/Libraries/LibWebView/ViewImplementation.cpp
Userland/Services/WebContent/ConnectionFromClient.cpp
Userland/Services/WebContent/ConnectionFromClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Services/WebContent/WebContentServer.ipc

When the WebContent process has painted to its shared bitmaps, it sends a synchronous IPC to the browser process to let the chrome paint. It is synchronous to ensure the WC process doesn't paint onto the backing bitmap again while it is being displayed.
However, this can cause a crash at exit if the browser process quits while the WC process is waiting for a response to this IPC.
This patch makes the painting logic asynchronous by letting the browser process broadcast when it has finished handling the paint IPC. The WC process will not paint anything again until it receives that message. If it had tried to repaint while waiting for that message, that paint will be deferred until it arrives.

LibWebView+WebContent: Let the WebView client broadcast when it painted

---

Tests/LibWeb/Ref/reference/space-glyph-width-ref.html
Tests/LibWeb/Ref/space-glyph-width.html
Userland/Libraries/LibGfx/TextLayout.h

Instead of assuming that the first font in the cascade font list will have a glyph for space, we need to find it in the list taking into account unicode ranges.

LibGfx: Take into account unicode ranges to find font for space glyph

---

Tests/LibWeb/Layout/expected/grid/implicit-lines.txt
Tests/LibWeb/Layout/input/grid/implicit-lines.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

According to spec each grid area implicitly defines 4 additional named
lines that could be used to specify items position.

LibWeb: Add support for implicit grid lines formed by grid areas in GFC 

---

Tests/LibWeb/Layout/expected/flex/reverse-with-justify-content-normal.txt
Tests/LibWeb/Layout/input/flex/reverse-with-justify-content-normal.html
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

Before this change, we used the wrong insertion point for flex items in reverse layouts with `justify-content: normal`. This caused flex items to overflow the flex containers "backwards" from the start edge.
Visual progression on Josh W Comeau's [interactive guide to flexbox](https://www.joshwcomeau.com/css/interactive-guide-to-flexbox/)
Before:
After:

LibWeb: Fix reverse flex layout with `justify-content: normal`

---

Tests/LibWeb/Layout/expected/css-values/calc-min-with-percentage.txt
Tests/LibWeb/Layout/input/css-values/calc-min-with-percentage.html
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp

Percentages should be resolved against the provided percentage basis instead of just returning the underlying value.
Fixes https://github.com/SerenityOS/serenity/issues/22654

LibWeb/CSS: Resolve percentages in NumericCalculationNode

---

Tests/LibWeb/Ref/reference/transform-calc-length-percentage-ref.html
Tests/LibWeb/Ref/transform-calc-length-percentage.html
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/StyleProperties.cpp

There were a few missing/incorrect checks for length percentage values when parsing transforms, which caused us to fail at parsing such values.
Fixes #22666.

LibWeb/CSS: Improve parsing of length percentage values for transforms

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h

Instead of serializing two calc() values to String and then comparing those strings, we can now compare calc() values by actually traversing their internal CalculationNode tree.
This makes style recomputation faster on pages with lots of calc() values since it's now much cheaper to check whether a property with some calc() value actually changed.

LibWeb: Implement calc() value equality check in a more efficient way

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/CSS/Parser/ParsingContext.cpp

Hi, I played around with Ladybird today and found an issue on one of my websites. I do not exactly know what is happening, but it looks like the page does something that causes the WebContent process to break.
On platinenmacher.tech it seams that there is a document without a window. During size attribute parsing the window pointer is dereferenced which causes a crash. This checks for the window to be actually there before dereferencing.
I am new to C++ and coming from C so if what I did is bollocks feel free to tell me the correct way to do this.

LibWeb/CSS: Remove nullpointer dereference in Parser

---

.github/workflows/lintcommits.yml

The newer version installs a specific version of octokit, since the latest version no longer supports the ruby installation in github actions vms. This should resolve the CI issues.
Relevant comment-on-pr commit: https://github.com/IdanHo/comment-on-pr/commit/dba728af7671011d7fd2c52acfc80f7217ae58b8
NOTE: Made this change on my phone, please review extra carefully

CI: Update comment-on-pr version

---

Meta/test_pdf.py

For every issue string, json['issues'][issue_string] contains a list of (page, count_of_issue_on_this_page) tuples.
To get the total number the issue appears in the current document, we need to add up all the count_of_issue_on_this_page, not multiply the page number with count_of_issue_on_this_page and add those (－‸ლ)

Meta: Let test_pdf.py be less dramatic about issue counts

---

Tests/LibGfx/CMakeLists.txt
Tests/LibGfx/TestPainter.cpp
Userland/Libraries/LibGfx/Painter.cpp

Before this, drawing a 1x1 bitmap scaled up to MxN would only fill M/2 x N/2 pixel, due to source_point going outside (0, 0).
---
This function uses low-quality sampling and some of this is subjective, but painting a 1x1 bitmap scaled by MxN should fill an MxN rect :)

LibGfx: Fix off-by-some in Painter::draw_scaled_bitmap_with_transform()

---

Userland/Applications/ImageViewer/ViewWidget.cpp
Userland/Libraries/LibGfx/CMYKBitmap.cpp
Userland/Libraries/LibGfx/CMYKBitmap.h
Userland/Libraries/LibGfx/CMakeLists.txt
Userland/Libraries/LibGfx/Forward.h
Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.h
Userland/Libraries/LibPDF/Filter.cpp
Userland/Libraries/LibPDF/Renderer.cpp

This handing the original jpeg channels to the color spaces, so this finally adds a way to get "raw" CMYK data from a jpeg, and also a way to know if jpeg data originally was grayscale.
The regula color codepath is fairly slow, so this makes pages with jpegs render subjectively quite a bit slower. Objectively, processing my 1000 file pdf test set goes from 45s to 1m57s. (But the majority of the time is spent on 0000849.pdf, a file with many many jpegs. If I filter that one file out in test_pdf.py, it's 45s -> 1m7s. Still 50% slower, but not 160% slower). In return, they're correct. And it provides additional incentive for making that codepath faster :^)
We now handle /Decode arrays on jpegs, and we now color-manage jpeg data in PDFs (including CMYK and grayscale jpegs).
Fixes all …

LibPDF+LibGfx (in particular, JPEG): Use regular color codepath for jpeg data too

---

Tests/LibWeb/Layout/expected/flex-item-with-cyclic-percentage-height.txt
Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
Userland/Libraries/LibWeb/Layout/FormattingContext.h
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h

Until now, we had implemented flex container sizing by awkwardly doing exactly what the spec said (basically having FFC size the container) despite that not really making sense in the big picture. (Parent formatting contexts should be responsible for sizing and placing their children)
This patch moves us away from the Flexbox spec text a little bit, by removing the logic for sizing the flex container in FFC, and instead making sure that all formatting contexts can set both width and height of flex container children.
This required changes in BFC and IFC, but it's actually quite simple! Width was already not a problem, and it turns out height isn't either, since the automatic height of a flex container is max-content. With this in mind, we can simply determine the height of flex containers …

LibWeb: Let parent formatting context determine size of flex containers

---

Userland/Libraries/LibPDF/Renderer.cpp

A certain PDF was drawing some text used `9 0 0 9 474.54 700.6801 Tm` to set the text matrix to a matrix that scaled by 9 in one text object.
Then, after ending that text object, it had the following new text object which contained nothing that invalidated the text matrix:
```
BT
/F1 7 Tf
/DeviceRGB CS
0 0 0 SC
10 TL
86.37849 21.908 Td
(Authorized licensed use limited to: ...) Tj
ET
```
`BT` did reset it as required, but since we didn't mark the matrix as dirty, we never recomputed it and drew the additional text scaled up 9x.
---
(`/F1` was built-in helvetica:
```
5 0 obj
<<
/Type /Font
/Encoding /WinAnsiEncoding
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj
```
)

LibPDF: Mark text rendering matrix dirty after changing it in text_begin

---

Userland/Libraries/LibPDF/Renderer.cpp

Images can't use Pattern color spaces, so we'll always have a Color.
No behavior (or perf) change.

LibPDF: Simplify load_image() a tiny bit

---

Userland/Libraries/LibProtocol/RequestClient.cpp

Allow it to fail, and return null if it does.
Fixes frequent crashes in unfavourable network conditions.
Offshoot fix for https://github.com/SerenityOS/serenity/issues/22607#issuecomment-1885222390.

LibProtocol: Don't assume request creation will succeed across IPC

---

Userland/Demos/Mandelbrot/Mandelbrot.cpp

If demos shouldn't be bloated with features then only consider the first 2 commits.
Feedback wanted for the architecture of one window updated by another window thing. The current implementation is very hackish.
---
```    
`sqrt()` was being used instead of `log()`. Because of that little
mistake, bands of colors are rendered and not smooth gradient as
expected with smooth coloring.
```
**Before**: 
**After**:
```    
The set should be calculated only when there is a paint event to keep
the number of times the set is calculated (which is compute expensive)
to the minimum.
```
This significantly reduces the amount of compute. Try spam zooming in and out.
```    
Colors get chaged by adding an offset to the hue of every color that is
calculated for the set. In other words: simply rotating …
```

Mandelbrot: Improvements and features

---

Userland/Libraries/LibGfx/ICC/Profile.cpp
Userland/Libraries/LibGfx/ICC/Profile.h

Fairly harmless code reorganizations. The third commit only helps matrix profiles. The fourth probably helps clut-based profiles too, but I haven't measured that.
A follow-up will help matrix profiles some more and be a bit more invasive.
In total, this PR takes time needed for
time Build/lagom/bin/pdf --page 3 --render out.png \
~/Downloads/0000/0000849.pdf
from ~1.8s to ~1.3s on my machine.

LibGfx/ICC: Speedups, round 1

---

Tests/LibRegex/Regex.cpp
Userland/Libraries/LibRegex/RegexByteCode.cpp
Userland/Libraries/LibRegex/RegexParser.cpp

This commit also fixes an incorrect test case from very early on, our behaviour now matches the ECMA262 spec in this case.
Fixes #21786.

LibRegex: Correct And/Or and inversion interplay semantics

---

Userland/Applications/Calculator/CalculatorWidget.cpp

Before the key events for shortcuts such as ALT-F4 did not work as the widget was swallowing up the shortcut. This changes ignores the event if nothing else matched

Calculator: Allow system shortcuts

---

Userland/Applications/SystemMonitor/ProcessModel.cpp
Userland/Applications/SystemMonitor/ProcessModel.h
Userland/Applications/SystemMonitor/ProcessStateWidget.cpp

Previously, some non-default process statistics were displayed in a long human readable format in the processes tab, which could negatively affect readability. A shorter format is now used in the processes tab, while the process properties window retains the longer format.
This fixes a regression introduced in #19346. I didn't realize that additional columns could be selected :facepalm:.
Before:
After:

SystemMonitor: Condense process statistics displayed in processes tab

---

Userland/Libraries/LibGfx/ICC/Profile.cpp
Userland/Libraries/LibGfx/ICC/Profile.h
Userland/Libraries/LibPDF/ColorSpace.cpp
Userland/Libraries/LibPDF/ColorSpace.h

Adds a dedicated matrix->matrix path. RGB profiles are usually matrix profiles, so this speeds up converting from most RGB colorspaces to sRGB (which is currently what LibPDF always converts to, but even if we make it support showing wide gamut colors on a wide gamut monitor, it'll still use a different RGB output profile) – that is, this is the common case.
Here are a few numbers from my local measurements. I timed four different workloads, at 5 different commits.
Workloads:
1. `time Build/lagom/bin/pdf --page 3 --render out.png ~/Downloads/0000/0000849.pdf`, ran a few times, eyeballed the min
2. `time Build/lagom/bin/pdf --debugging-stats ~/Downloads/0000/0000849.pdf`
3. `time Meta/test_pdf.py ~/Downloads/0000`
4. `time Meta/test_pdf.py ~/Downloads/0000` but with 0000849.pdf filtered …

LibGfx/ICC+LibPDF: Speedups, round 2

---

Userland/Shell/Shell.cpp

This makes e.g. `pwd | ...` behave as expected, where pwd doesn't add a hyperlink around the path.

Shell: Print paths in plain mode when stdout is not a tty

---

Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp

The issue noted here has been fixed in the same way that we previously
worked around it. Update the spec notes to match.

LibJS: Update spec notes for a resizable ArrayBuffer workaround

---

Userland/Applications/Calculator/CalculatorWindow.gml

Previously, it was possible for the user to input text into the calculator display. With this change, the calculator display is made read-only.
I've also included a change to make the equals button non-focusable. This isn't necessary, as pressing Enter will activate the button whether it is in focus or not. This makes the equals button behave the same as all other buttons.
As it is, this change breaks copy and paste functionality. This is fixed by #22572, which should be merged first.

Calculator: Make calculator display non-interactive

---

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h
Userland/Libraries/LibWeb/DOM/Document.cpp

Fetching the viewport rect is currently somewhat expensive, since it requires finding the navigable the document is active in.
We can avoid the cost of repeated calls by simply allowing StyleComputer to cache the viewport rect at the start of style computation.

LibWeb: Cache the viewport rect across all of style computation

---

Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
Ladybird/HelperProcess.cpp
Ladybird/HelperProcess.h
Ladybird/Qt/WebContentView.cpp
Ladybird/WebWorker/main.cpp
Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
Userland/Applications/Browser/main.cpp
Userland/Libraries/LibWeb/Forward.h
Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp
Userland/Libraries/LibWeb/HTML/WorkerAgent.h
Userland/Libraries/LibWeb/Page/Page.h
Userland/Libraries/LibWeb/Worker/WebWorkerClient.cpp
Userland/Libraries/LibWeb/Worker/WebWorkerClient.h
Userland/Libraries/LibWebView/CMakeLists.txt
Userland/Libraries/LibWebView/Forward.h
Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
Userland/Libraries/LibWebView/SocketPair.cpp
Userland/Libraries/LibWebView/SocketPair.h
Userland/Libraries/LibWebView/ViewImplementation.h
Userland/Libraries/LibWebView/WebContentClient.cpp
Userland/Libraries/LibWebView/WebContentClient.h
Userland/Services/WebContent/PageClient.cpp
Userland/Services/WebContent/PageClient.h
Userland/Services/WebContent/WebContentClient.ipc
Userland/Services/WebContent/main.cpp
Userland/Utilities/headless-browser.cpp

Instead of spawning these processes from the WebContent process, we now create them in the Browser chrome.
Part 1/N of "all processes are owned by the chrome".

LibWeb+WebContent: Spawn Worker processes from the chrome

---

Kernel/FileSystem/FATFS/Definitions.h
Kernel/FileSystem/FATFS/FileSystem.cpp
Kernel/FileSystem/FATFS/FileSystem.h
Kernel/FileSystem/FATFS/Inode.cpp
Kernel/FileSystem/FATFS/Inode.h

This PR extends the FATFS driver to support FAT 12 and FAT 16 versions of the FAT file system.
> Why?
Why not! But also, this enables use of the [QEMU VVFAT virtual drive](https://en.wikibooks.org/wiki/QEMU/Devices/Storage#Virtual_FAT_filesystem_(VVFAT)), which makes it really easy to share files between the host and guest:
```sh
SERENITY_BOOT_DRIVE="$SERENITY_BOOT_DRIVE -drive file=fat:16:rw:$SCRIPT_DIR/../Documentation/"
```
Note that this is still pretty slow driver. The driver doesn't do any caching, and frequently reads _all_ blocks associated with a file. There's a lot of room for optimization with some light caching of the FAT table and being more selective about which sectors/blocks are read.
* e834897b822d412b08bf0d2ca5f24480bed01074: Add support for different versions of the DOS …

FATFS: Add Support for FAT16/FAT12 File Systems

---

Kernel/Boot/CommandLine.cpp
Kernel/Devices/HID/PS2/KeyboardDevice.cpp

We do this by implementing the following fixes:
- The Key_Plus is assigned to a proper map entry index now which is 0x4e both on the keypad and non-keypad keys.
- Shift+Q now prints out "Q" properly on scan code set 2.
- Key BackSlash (or Pipe on shift key being pressed down) is now working properly as well.
Partially fixes #22599. I still don't know how to properly check the fi layout (do I need a keyboard with this layout?).

Kernel/HID: Fix PS2 keyboard scan code tables

---

Userland/Applications/Calculator/Calculator.cpp

```
Calculator: Finish operation-in-progress only on new binary operations
Because of this the unary operations got applied to the result of the
operation-in-progress instead of the current argument as shown here:
`16 + 9 <sqrt> =`
Previous output: `sqrt(16 + 9)` = `5`
Expected output: `16 + sqrt(9)` = `19`
```
this also fixes the following bug i found which i didn't mention in the commit message:
- do `5 * 5 = <MS>`
- then `100 - <MR> =` (output: `-75` instead of `75`)
---
should i open issues for bugs even if i have a fix for it ready?

Calculator: Finish operation-in-progress only on new binary operations

---

Userland/Libraries/LibELF/ELFABI.h
Userland/Libraries/LibELF/Validation.cpp

We have to skip our usual validations, as the checks might not hold for this program header type (and the checks wouldn't really make sense for PT_RISCV_ATTRIBUTES either).
PT_RISCV_ATTRIBUTES is defined here:
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/v1.0/riscv-elf.adoc#program-header-table

LibELF: Ignore RISC-V attribute section program header

---

Kernel/Arch/riscv64/PowerState.cpp
Kernel/Arch/riscv64/SBI.cpp
Kernel/Arch/riscv64/SBI.h
Kernel/Library/Panic.cpp

This PR adds support for rebooting and shutting down using the SBI.
I am not sure if there is a better (or preferred) way of formatting enums, but this method seems to be used in other places. Or should I just print the error code, not a message?

Kernel/riscv64: Add SBI-based shutdown and reboot support

---

Kernel/Net/NetworkTask.cpp

Fixed a mistake where we did not acknowledge a segment in the FinWait2 state.

Kernel: Properly ack segment

---

AK/Complex.h
AK/Random.cpp
AK/Random.h
Tests/AK/TestAllOf.cpp
Tests/AK/TestAnyOf.cpp
Tests/AK/TestBinaryHeap.cpp
Tests/AK/TestBinarySearch.cpp
Tests/AK/TestBitStream.cpp
Tests/AK/TestBitmap.cpp
Tests/AK/TestBuiltinWrappers.cpp
Tests/AK/TestCharacterTypes.cpp
Tests/AK/TestComplex.cpp
Tests/LibTest/TestGenerator.cpp
Userland/Libraries/LibTest/Randomized/Generator.h
Userland/Libraries/LibTest/Randomized/RandomRun.h
Userland/Libraries/LibTest/Randomized/RandomnessSource.h
Userland/Libraries/LibTest/Randomized/Shrink.h

These tests don't find any bugs currently; tests that _did_ find bugs were introduced in https://github.com/SerenityOS/serenity/pull/22025.
Because the Complex class deals with floating point numbers, this gave us the opportunity to add some LibTest `f64` generators. They could be improved (FIXMEs included in the PR), but will do the job for now!
Tangential: video detailing the process of writing these tests: https://www.youtube.com/watch?v=enxglLlALvI

AK: Cover TestComplex with more tests

---

Kernel/Arch/init.cpp
Kernel/Arch/riscv64/DebugOutput.cpp
Kernel/Arch/riscv64/MMU.cpp
Kernel/Arch/riscv64/MMU.h
Kernel/Arch/riscv64/pre_init.cpp
Kernel/Arch/riscv64/pre_init.h
Kernel/CMakeLists.txt

This PR makes the kernel progress far in enough to print an assertion failure:
```
[Kernel]: Loading kernel symbol table...
[Kernel]: ASSERTION FAILED: TODO_RISCV64
[Kernel]: Kernel/Arch/riscv64/Interrupts.cpp:44 in void Kernel::initialize_interrupts()
[Kernel]: KERNEL PANIC! :^(
[Kernel]: Aborted
[Kernel]: at Kernel/Arch/riscv64/Panic.cpp:23 in void __assertion_failed(const char *, const char *, unsigned int, const char *)
```
This PR adds a basic trap handler for `pre_init`, initializes the MMU for `init` and jumps into high virtual memory.
~`serenity.sh run` doesn't work yet, as I'm waiting for the run.py PR.
You should be able to run the kernel with `qemu-system-riscv64 -kernel Build/riscv64clang/Kernel/Kernel.bin -nographic -serial mon:stdio`~
You should be able to test this with …

Kernel/riscv64: Make the kernel progress further in the boot process

---

Userland/DevTools/HackStudio/Debugger/BacktraceModel.cpp

This fixes a bug where we previously would hang if we couldn't find a library containing the current program counter.
I came across this bug while trying to fix backtrace generation on RISC-V.

HackStudio: Correctly handle invalid addresses during backtrace creation

---

AK/Format.cpp
AK/GenericLexer.h
AK/JsonParser.cpp
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEasingFunctions.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp
Meta/Lagom/Tools/CodeGenerators/StateMachineGenerator/main.cpp
Tests/AK/TestGenericLexer.cpp
Userland/Applications/Spreadsheet/Readers/XSV.cpp
Userland/Applications/Spreadsheet/Writers/XSV.h
Userland/Libraries/LibCrypto/ASN1/PEM.cpp
Userland/Libraries/LibDiff/Hunks.cpp
Userland/Libraries/LibIDL/IDLParser.cpp
Userland/Libraries/LibLine/Editor.cpp
Userland/Libraries/LibXML/Parser/Parser.cpp
Userland/Utilities/pro.cpp

A bunch of users used consume_specific with a constant ByteString
literal, which can be replaced by an allocation-free StringView literal.
The generic consume_while overload gains a requires clause so that
consume_specific("abc") causes a more understandable and actionable
error.

AK: Remove ByteString from GenericLexer

---

Userland/Libraries/LibELF/DynamicObject.cpp
Userland/Utilities/readelf.cpp

This fixes the incorrect determination of the dynamic symbol amount when `DT_GNU_HASH` table is used. In this case the header no longer contains the amount of elements as with `DT_HASH` and therefore the amount has to be determined differently.
Before, running e.g. `readelf --dyn-syms /usr/bin/env` reported that there are 57 entries however only 44 were shown:
```
Symbol table '.dynsym' contains 57 entries.
Num: Value              Size               Type     Bind     Name
0: 0x0000000000000000 0x0000000000000000 NOTYPE   LOCAL    
1: 0x0000000000000000 0x0000000000000000 OBJECT   GLOBAL   _ZTVN10__cxxabiv120__si_class_type_infoE
2: 0x0000000000000000 0x0000000000000000 OBJECT   GLOBAL   stderr
3: 0x0000000000000000 0x0000000000000000 FUNC     GLOBAL …
```

LibELF: Correctly determine symbol amount for DT_GNU_HASH table

---

Userland/Games/Solitaire/main.cpp

`on_game_start` is not called until the player makes a move, so waiting until then means that the solve button would still be visible when starting a new game after completing one. By hiding the button in `on_game_end`, this happens when the game-over animation starts playing instead.

Solitaire: Hide solve button when game ends

---

AK/JsonValue.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEnums.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSTransformFunctions.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSValueID.cpp
Tests/AK/TestJSON.cpp
Userland/Applications/Presenter/Presentation.cpp
Userland/Applications/Presenter/SlideObject.cpp
Userland/Applications/Spreadsheet/HelpWindow.cpp
Userland/Applications/Spreadsheet/Spreadsheet.cpp
Userland/DevTools/Profiler/Profile.cpp
Userland/Libraries/LibGUI/DynamicWidgetContainer.cpp
Userland/Libraries/LibGUI/JsonArrayModel.cpp
Userland/Libraries/LibJS/Runtime/JSONObject.cpp
Userland/Libraries/LibWeb/WebDriver/Client.cpp
Userland/Services/WebDriver/Client.cpp
Userland/Shell/Shell.cpp
Userland/Utilities/json.cpp
Userland/Utilities/lsirq.cpp
Userland/Utilities/pmap.cpp

`JsonValue::to_byte_string` has peculiar type-erasure semantics which is not usually intended. Unfortunately, it also has a very stereotypical name which does not warn about unexpected behavior. So let's prefix it with `deprecated_` to make new code use `as_string` if it just wants to get string value or `serialized<StringBuilder>` if it needs to do proper serialization.
Revival of #21813, this is part of a bigger AK::JsonValue refactor with the end result pushed [here](https://github.com/DanShaders/serenity/tree/json-rewrite).

Everywhere: Add deprecated_ prefix to `JsonValue::to_byte_string`

---

Userland/Libraries/LibWeb/MimeSniff/Resource.cpp

A little whoopsie I did not see in 3aaa1c1. This is not erroneous behavior, but it's just not necessary.

LibWeb/MimeSniff: Remove unnecessary addition in mp4 signature match

---

Userland/DevTools/HackStudio/Editor.cpp
Userland/DevTools/HackStudio/Editor.h

Only adjust the cursor to respond to clickable text, if the mouse is over text.

HackStudio: Stop incorrectly overriding gutter cursors

---

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableFragment.h
Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp

Rather than resolving the text-shadow each time painting commands are
recorded, we can resolve it once during the layout commit and save the
resolved values in paintable fragments. This is also step towards
getting rid of layout node pointer in paintable fragment.

LibWeb: Resolve text shadows in LayoutState::commit()

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Document.h
Userland/Libraries/LibWeb/DOM/Document.idl
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
Userland/Libraries/LibWeb/DOM/HTMLFormControlsCollection.cpp
Userland/Libraries/LibWeb/DOM/Node.cpp
Userland/Libraries/LibWeb/Dump.cpp
Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Userland/Libraries/LibWeb/HTML/HTMLMetaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/Layout/Label.cpp
Userland/Libraries/LibWeb/Layout/Node.cpp

This MR gets Element pretty close to finally being rid of ByteString, and introduces caching of Element::name.
We also use the cached name and id in more places.

LibWeb: Port some more of Element from ByteString, add caching of Element::name

---

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.h

This is part of the efforts towards making the paintable tree independent of the layout tree.

LibWeb: Set box-shadow for inline paintables in LayoutState::commit()

---

Base/usr/share/man/man1/listdir.md
Kernel/FileSystem/DevPtsFS/FileSystem.cpp
Kernel/FileSystem/DevPtsFS/FileSystem.h
Kernel/FileSystem/DevPtsFS/Inode.cpp
Kernel/FileSystem/ProcFS/Definitions.h
Kernel/FileSystem/ProcFS/FileSystem.cpp
Kernel/FileSystem/ProcFS/FileSystem.h
Kernel/FileSystem/ProcFS/Inode.cpp
Kernel/FileSystem/ProcFS/ProcessExposed.cpp
Kernel/FileSystem/RAMBackedFileType.h
Kernel/FileSystem/RAMFS/FileSystem.cpp
Kernel/FileSystem/RAMFS/FileSystem.h
Kernel/FileSystem/RAMFS/Inode.cpp
Kernel/FileSystem/SysFS/Component.cpp
Kernel/FileSystem/SysFS/Component.h
Kernel/FileSystem/SysFS/FileSystem.cpp
Kernel/FileSystem/SysFS/FileSystem.h
Tests/Kernel/CMakeLists.txt
Tests/Kernel/TestFileSystemDirentTypes.cpp
Userland/Libraries/LibCore/DirIterator.cpp
Userland/Libraries/LibCore/DirIterator.h
Userland/Libraries/LibCore/DirectoryEntry.cpp
Userland/Libraries/LibCore/DirectoryEntry.h
Userland/Utilities/listdir.cpp

Should actually fix the problem being represented in #22533 (even though we just allow zeroed type now).
Still need to add a man page for the new `listdir` utility, but I will want to ensure I did write it correctly as well :)

Kernel+Userland: Propagate proper filetypes in SysFS, ProcFS and DevPtsFS, add the listdir utility

---

AK/CharacterTypes.h
Tests/AK/TestCharacterTypes.cpp
Tests/LibCrypto/TestBigInteger.cpp
Userland/Applications/Calculator/main.cpp
Userland/Libraries/LibCrypto/BigFraction/BigFraction.cpp
Userland/Libraries/LibCrypto/BigFraction/BigFraction.h
Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.cpp
Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.h
Userland/Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
Userland/Libraries/LibCrypto/BigInt/UnsignedBigInteger.h
Userland/Libraries/LibCrypto/NumberTheory/ModularFunctions.cpp
Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Userland/Libraries/LibJS/Runtime/Value.cpp
Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp

Previously, constructing a `UnsignedBigInteger::from_base()` could produce an incorrect result if the input string contained a valid Base36 digit that was out of range of the given base. The same method would also crash if the input string contained an invalid Base36 digit. An error is now returned in both these cases.
Constructing a BigFraction from string is now also fallible, so that we can handle the case where we are given an input string with invalid digits.
The motivation for this change was to fix the behavior of Calculator when pasting invalid numbers. 
Video showing the issues:
https://github.com/SerenityOS/serenity/assets/2817754/e15fc9b4-1673-41eb-ab40-427f1695eedb
NB: I have used `MUST` for the usages of these functions in LibJS and LibWeb, as I believe they are all …

AK+LibCrypto: Make constructing a BigInteger from string fallible

---

Userland/Applications/Calendar/AddEventDialog.gml
Userland/Applications/FontEditor/FontEditorWindow.gml
Userland/Libraries/LibGUI/FontPickerDialog.gml
Userland/Libraries/LibGUI/SpinBox.h

By default, a SpinBox's value should be unlimited, (or as close as we can get to that,) and then the GML or code can impose a limit if needed. This saves the developer from entering an arbitrary "big" max value when they want the value to have no maximum.
I've audited the use of SpinBox and added `min: 0`, and removed a `max`, where appropriate. All existing SpinBoxes constructed in code have a range set explicitly as far as I can tell.
(See the discussion here: https://github.com/SerenityOS/serenity/pull/22653#discussion_r1444485508 )

LibGUI+Applications: Default the SpinBox min/max to the full int range

---

Tests/LibCrypto/CMakeLists.txt
Tests/LibCrypto/TestBigFraction.cpp
Userland/Libraries/LibCrypto/BigFraction/BigFraction.cpp

Previously, when calling `BigFraction::from_string()`, the fractional part of the number was always treated as positive. This led to an incorrect result if the input string was negative.
I found this issue when attempting to paste a negative decimal value into the calculator.

LibCrypto: Parse negative input correctly in `BigFraction::from_string()`

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.h
Userland/Libraries/LibGfx/TIFFGenerator.py

While generating these two functions is not extremely profitable, having a single place that covers all information about the `Type` enum is really great!
This PR actually only add support for the `ExifIFD` tag, so not really a huge thing :sweat_smile:
I have some code to read the IFD, but it's too hackish to be upstreamed yet. But I promise it works:

LibGfx/TIFF: Add Exif (tag) support

---

Userland/Libraries/LibGUI/FileSystemModel.cpp

Some examples from the libtiff test suite.
Before:
After:

LibGUI: Use BoxSampling to draw thumbnails

---

Userland/Libraries/LibJIT/GDBElf.cpp
Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
Userland/Libraries/LibSQL/SQLClient.cpp

More tiny fixes for regressions on GNU/Hurd introduced since https://github.com/SerenityOS/serenity/pull/21780.
<details>
<summary>I'm still building with this additional patch on top</summary>
<pre><code>diff --git a/Meta/CMake/lagom_compile_options.cmake b/Meta/CMake/lagom_compile_options.cmake
index 2f7ba5213e..02cda3a33c 100644
--- a/Meta/CMake/lagom_compile_options.cmake
+++ b/Meta/CMake/lagom_compile_options.cmake
@@ -4,6 +4,8 @@ add_compile_options(-Wno-maybe-uninitialized)
add_compile_options(-Wno-shorten-64-to-32)
add_compile_options(-fsigned-char)
add_compile_options(-ggnu-pubnames)
+add_compile_options(-O2)
+add_compile_options(-mstack-alignment=16)
if (NOT WIN32)
add_compile_options(-fPIC)
endif()
diff --git a/Userland/Libraries/LibCore/System.cpp …

More tiny Hurd fixes

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp

When re-opening an existing file, we would reuse the document and register a new Editor with it, but never unregister that Editor.
Previously, this would cause a crash if you opened a binary file, closed its tab, then opened that binary file again. HackStudio would crash while calling `HackStudio::EditorWrapper::update_title()` on an invalid EditorWrapper. But now it doesn't!
Something still gets leaked each time, but we now don't crash at least.

HackStudio: Stop crash from leaking Editor widgets when closing tabs

---

Userland/Applications/SystemMonitor/main.cpp
Userland/Libraries/LibGUI/HeaderView.cpp
Userland/Libraries/LibGUI/HeaderView.h

Previously, any TableView column could be made visible through a context menu shown by right clicking on the table header. This change allows columns to be marked as non-selectable, so their visibility
cannot be toggled in this way. 
This marks the icon column in the SystemMonitor Processes tab as non-selectable. This means the icon column can no longer be selected, but is still visible in the process properties window.
Video showing the issue:
https://github.com/SerenityOS/serenity/assets/2817754/8dfc08f3-56a1-4aaa-b7bd-e1caf8690164

LibGUI+SystemMonitor: Make the icon column in the Processes tab non-selectable

---

Kernel/API/KeyCode.h
Kernel/Devices/HID/PS2/KeyboardDevice.cpp
Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Userland/Applications/Piano/MainWidget.cpp

I noticed SDL2 applications no longer had a working arrow key mapping, so let's fix that :^)
CC @supercomputer7

Kernel+Ports: Restore and improve SDL2 keyboard mapping

---

Tests/LibWeb/Text/expected/DOM/Element-getAttributeNodeNS.txt
Tests/LibWeb/Text/expected/DOM/Element-removeAttributeNS.txt
Tests/LibWeb/Text/input/DOM/Element-getAttributeNodeNS.html
Tests/LibWeb/Text/input/DOM/Element-removeAttributeNS.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Element.h
Userland/Libraries/LibWeb/DOM/Element.idl

Continue fleshing out support for attributes with namespaces

LibWeb: Implement Element.getAttributeNodeNS and Element.removeAttributeNS

---

Userland/DevTools/HackStudio/Debugger/Debugger.cpp
Userland/DevTools/HackStudio/Debugger/Debugger.h
Userland/DevTools/HackStudio/Editor.cpp

Rather than adding/removing a breakpoint indicator, and then telling the debugger about it and hoping it works, let the debugger tell us if it succeeded and then use that to update the indicator.
This prevents the user from adding breakpoints to invalid locations while the debugger is running. It also avoids a couple of scary VERIFY()s. We still allow creating breakpoints in invalid locations while the debugger is *not* running.

HackStudio: Make Editor ask Debugger if a breakpoint was added/removed

---

Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/DOM/Range.cpp
Userland/Libraries/LibWeb/HTML/AudioTrack.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Userland/Libraries/LibWeb/HTML/HTMLBodyElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/Layout/Box.cpp
Userland/Libraries/LibWeb/Layout/Box.h
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Layout/Node.h
Userland/Libraries/LibWeb/Page/EventHandler.cpp
Userland/Libraries/LibWeb/Page/EventHandler.h
Userland/Libraries/LibWeb/Painting/LabelablePaintable.cpp
Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/PaintableFragment.cpp
Userland/Libraries/LibWeb/Painting/TextPaintable.cpp
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.cpp

The use of layout nodes likely predated the paintable tree, but now there is no point in introducing another level of indirection.

LibWeb: Use paintable to represent event tracking node

---

Userland/Libraries/LibPDF/Renderer.cpp

0000342.pdf page 5 contains this snippet:
```
/T1_1 10.976 Tf
0 -31.643 TD
(This)Tj
1 0 0 1 54 745.563 Tm
22.181 -31.643 Td
[(vehicle)-270.926(uses)...
```
The `Tm` marked the text rendering matrix as dirty at the start, but it then calls calculate_text_rendering_matrix() almost in the next line, which recalculates the text rendering matrix and caches the new matrix. The `Td` used to not mark it as dirty, and we'd draw "vehicle" with an incorrect matrix.

LibPDF: Mark text rendering matrix dirty for Td operator

---

Tests/LibPDF/text.pdf
Userland/Libraries/LibPDF/Renderer.cpp

Mostly because I audited all places that assigned to `m_text_matrix` after #22760.
This one is very difficult to trigger in practice.
`show_text()` marks the text rendering matrix dirty already, so this only has an effect if the `TJ` array starts with a number, and the matrix isn't marked dirty going in.
`Tm` caches the text rendering matrix, so I changed text.pdf to contain:
```
1 0 0 1 45 130 Tm
[ 200 (Hello) -2000 (World) ] TJ T*
```
This first sets an x offset of 5 (on top of the normal 40), and then undoes it (`200` is multiplied by font size (25) / -1000, and `200 * 25 / -1000` is -5). Before this change, the topmost "Hello World" ended up slightly indented.
Likely no behavior change in practice, but makes the code easier to understand, and maybe it helps in the wild somewhere.

LibPDF: Mark text rendering matrix as dirty after TJ numbers

---

Tests/LibWeb/Layout/expected/flex/svg-flex-item-with-percentage-max-size.txt
Tests/LibWeb/Layout/input/flex/svg-flex-item-with-percentage-max-size.html
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h

There are a bunch of situations where we need to treat cross axis max-size properties as "none", notably percentage values when the reference containing block size is an intrinsic sizing constraint.
This fixes an issue where flex items with definite width would get shrunk to 0px by "max-width: 100%" in case the item itself is an SVG with no natural width or height.
For consistency, we now use the should_treat_max_width/height_as_none helpers throughout FFC.
This makes the search/account/cart icons show up in the top right on https://twinings.co.uk :^)

LibWeb: Treat flex item cross axis max-size as "none" in more cases

---

Userland/Libraries/LibC/arch/riscv64/setjmp.S

For some reason I decided to change the argument passing order before submitting my PR, but this would cause the oldset argument to always be 0x74 as a0 is overridden with 0 in that order.
Hopefully it stays at 2 attempts for setjmp.

LibC: Pass arguments correctly to sigprocmask in setjmp for riscv64

---

Tests/LibWeb/Layout/expected/misc/corner-radius.txt
Tests/LibWeb/Layout/input/misc/corner-radius.html
Userland/Libraries/LibGfx/AntiAliasingPainter.h
Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

Check needs to happen after conversion because non-zero radius in CSSPixels could turn into zero in device pixels.
Fixes https://github.com/SerenityOS/serenity/issues/22765

LibWeb: Check if corners have radius after converting to device pixels

---

Meta/Lagom/Contrib/MacPDF/MacPDFView.h
Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
Meta/Lagom/Contrib/MacPDF/MainMenu.xib

...and hook it up.
I opened MainMenu.xib in Xcode, added a new "Submenu Menu Item" from the Library (cmd-shift-l), added a User Defined "toggleShowClippingPaths:" action on First Responder and connected the menu item's action to that action.
(I first tried duplicating the existing Window menu and editing that, but the Window menu is marked as `systemMenu="window"` in the xib and I couldn't find a way to undo that in Xcode. So the Debug menu first acted as a second Window menu.)
I made "Debug" a toplevel menu to make it consistent with Ladybird.app for now, but I'll probably make it a submenu of "View" in the future.

MacPDF: Add a "Debug" menu with a "Show Clipping Paths" entry

---

Ladybird/CMakeLists.txt

Finding Cocoa.framework is the linker's job, not CMake's.

Ladybird/AppKit/CMake: Use a more civilized way of finding Cocoa

---

Tests/LibGfx/TestImageDecoder.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

We now allow all subsampling factors where the subsampling factors
of follow-on components evenly decode the ones of the first component.
In practice, this allows YCCK 2111, CMYK 2112, and CMYK 2111.

LibGfx/JPEG: Allow decoding more subsampling factors 

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

We missed this one in d184e6014ccd8.
No behavior change in valid JPEGs. No silent underflow in invalid ones.

LibGfx: Use read_effective_chunk_size() in skip_segment()

---

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp

Every time I read this, I'm like "wait, this does the wrong thing for images with bpp != 8". It doesn't, though.

LibGfx/PNG: Spec comment for PNGImageDecoderPlugin::unfilter_scanline()

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

When we want to walk everything, we can just do a linear walk.
---
A tiny separate simplification too.
It has no behavior change, it just simplifies some loops. I think it should be a no-op for real this time, and it might help the compiler vectorize these loops better.

LibGfx/JPEG: Simplify loops walking all pixels in all macroblocks

---

Userland/Utilities/cksum.cpp

This PR exists to handle an edge case where no file operands are given (so something like `echo "hello friends" | cksum`). I felt the need to make a couple touch-ups and other changes along the way :^)
An example:
Before:
After (while also having the checksum as a decimal instead of hexadecimal as the spec expects):
I tested this branch manually by comparing some commands run on my local master branch. After executing the following on my master branch (note that I just written these results while looking at Serenity's terminal printout since I haven't taken the time to figure out how to get the SpiceAgent to work):
```console
echo "well hello friends" | cksum -
33291047 19 -
echo "well hello friends" | cksum
33291047 19 -
cksum README.md
2483135952 10777 README.md
echo "well hello …
```

cksum: Consider empty file operand when printing

---

Userland/Libraries/LibPDF/ObjectDerivatives.cpp

Previously, all page contents ended up overprinting a single line over and over for PDFs that used only `\r` as line ending.
This is for example useful for 0000364.pdf.
---
I've locally added this many times. Might as well send it upstream.

LibPDF: Make `pdf --dump-contents` handle \r line endings better

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/Project.cpp
Userland/DevTools/HackStudio/main.cpp

Relies on #22775. Only the last 2 commits are really this PR.
Before, trying to launch HackStudio with a relative project path (eg, `HackStudio Source/little`) would crash, and now it doesn't, and generally works as you would expect. (As far as I can tell anyway!)
cc: @ADKaster

HackStudio: Fix launching with a relative project path

---

Tests/LibWeb/Layout/expected/grid/align-items.txt
Tests/LibWeb/Layout/expected/grid/align-self.txt
Tests/LibWeb/Layout/expected/grid/all-implicit-rows.txt
Tests/LibWeb/Layout/expected/grid/auto-flow-column-spanning-item.txt
Tests/LibWeb/Layout/expected/grid/auto-flow-column.txt
Tests/LibWeb/Layout/expected/grid/basic.txt
Tests/LibWeb/Layout/expected/grid/borders.txt
Tests/LibWeb/Layout/expected/grid/grid-gap-1.txt
Tests/LibWeb/Layout/expected/grid/grid-gap-2.txt
Tests/LibWeb/Layout/expected/grid/grid-item-percentage-width.txt
Tests/LibWeb/Layout/expected/grid/negative-grid-item-column-index.txt
Tests/LibWeb/Layout/expected/grid/place-self.txt
Tests/LibWeb/Layout/expected/grid/placement-using-named-tracks-1.txt
Tests/LibWeb/Layout/expected/grid/row-height.txt
Tests/LibWeb/Layout/expected/grid/row-span-2-maxcontent.txt
Tests/LibWeb/Layout/expected/grid/row-span-2-with-gaps.txt
Tests/LibWeb/Layout/expected/grid/row-span-2.txt
Tests/LibWeb/Layout/expected/grid/should-not-hang-in-size-distribution.txt
Tests/LibWeb/Layout/expected/grid/stretch-auto-tracks.txt
Tests/LibWeb/Layout/input/grid/stretch-auto-tracks.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Now, we will evenly distribute the remaining free space across tracks using the auto max-tracks sizing function, exactly as the specification states. Many tests are affected, but they are not visually broken.
Fixes https://github.com/SerenityOS/serenity/issues/22798

LibWeb: Align with spec "stretch auto tracks" step in GFC

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp

This is something I messed up, back in 77ad0fdb0726aba2ecaf7ea9764a642671d1fd6f. Oops!

HackStudio: Make Files and Classes tabs have the same border width

---

Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

Turns out the width/height in a `re` command can be negative. This results in rectangles with different winding orders. For example, a negative width results in a reversed winding order.
Previously, this was lost by passing the rect through an `AffineTransform` before constructing the path. So instead, this constructs the rect path, and then transforms the resulting path.

LibPDF: Fix paths with negatively sized `re` (rect) commands

---

Meta/Lagom/Contrib/MacPDF/MacPDFView.h
Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.h
Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
Meta/Lagom/Contrib/MacPDF/MainMenu.xib
Userland/Libraries/LibPDF/Renderer.cpp
Userland/Libraries/LibPDF/Renderer.h

This is a dramatic progression for some PDFs.
I'll port the debug toggles to PDFViewer once I'm back at a machine that can build serenity (which will take a couple of days).

LibPDF: Clip images against clipping path (…bounding box); MacPDF: Add debug toggle to turn off clipping

---

Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
Userland/Libraries/LibPDF/Fonts/Type1Font.cpp

The vertical coordinates for truetype fonts are different somehow. We compensated a bit for that; now we compensate some more.
This is still not 100% perfect, but much better than before.
---
Screenshots in a few hours.

LibPDF: Tweak vertical position of truetype fonts

---

Tests/LibWeb/Layout/expected/grid/columns-auto-fill-with-gap-3.txt
Tests/LibWeb/Layout/input/grid/columns-auto-fill-with-gap-3.html
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

Fixes a bug where gaps between repeated tracks were accounted for only once instead of multiple times, corresponding to the repeat count.
Fixes https://github.com/SerenityOS/serenity/issues/22823

LibWeb: Fix accounting for gaps in auto-fit count calculation in GFC

---

Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Userland/Libraries/LibWeb/Layout/FormattingContext.h
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h

Basically:
1. Give `UsedValues` a pointer to the `UsedValues` of the containing block.
2. Give `BFC::FloatingBox` a pointer to the box's `UsedValues`.
3. Use those in a bunch of hot places to avoid `m_state.get(box)` lookups.
This makes layout *significantly* faster on long Wikipedia articles with many floats.
Time spent in `LayoutState::get()` goes from 37% to 2% on 
https://en.wikipedia.org/wiki/George_Frideric_Handel

LibWeb: Reduce the number of UsedValue hash lookups during BFC/IFC layout

---

Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp

This refactoring simplifies the resolution of minimum and maximum sizes during the counting of auto tracks.
No changes in behavior are intended.

LibWeb: Remove duplicated code in grid auto track counting

---

Tests/LibWeb/Layout/expected/grid/css-calc-in-grid-position.txt
Tests/LibWeb/Layout/input/grid/css-calc-in-grid-position.html
Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp

Fixes reduction in https://github.com/SerenityOS/serenity/issues/22802 but does not result in visual improvement on https://kotlinlang.org/

LibWeb/CSS: Support calc() in grid placement values

---

Base/res/ladybird/templates/version.html
Ladybird/AppKit/main.mm
Ladybird/HelperProcess.cpp
Ladybird/Qt/main.cpp
Ladybird/Types.h
Ladybird/WebContent/main.cpp
Userland/Applications/BrowserSettings/Defaults.h
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.cpp
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.h
Userland/Utilities/headless-browser.cpp

This pr adds two new arguments to the `WebContent` process, so that the chrome can pass its complete command line and executable path. This information is then displayed in the `about:version` page.
This currently only works in Ladybird chromes outside SerenityOS but I'll fix this in the future.
I also change the default new tab URL to `about:newtab`, I forget to add this back when fixing my previous pr 😆

Ladybird+WebContent: Add chrome command line and exe path passing

---

Userland/Libraries/LibAudio/WavLoader.cpp

Fixes oss fuzz issue [65879](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65879)

LibAudio: Avoid UAF when loading WAV metadata

---

Meta/Lagom/Fuzzers/FuzzGIFLoader.cpp

Fixes oss fuzz issue: [65858](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65858).
I also included a small fix to ensure the conditional logging the fuzzer does is printed when GIF_DEBUG is enabled.

Fuzzers: Continue if frame is malformed in GIF fuzzer

---

Meta/CMake/common_compile_options.cmake

```
This patch removes the explicit compile flag that only works for g++
(`-fdiagnostics-color=always`; clang++ needs `-fcolor-diagnostics`) and
uses CMake's built in variable that can control color output.
Now both compilers should output colored diagnostics.
```

CMake: Set `CMAKE_COLOR_DIAGNOSTICS` to `ON` for colored diagnostics

---

Userland/Libraries/LibWeb/Animations/Animation.idl
Userland/Libraries/LibWeb/Animations/AnimationEffect.idl
Userland/Libraries/LibWeb/Animations/DocumentTimeline.idl
Userland/Libraries/LibWeb/Animations/KeyframeEffect.idl
Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.idl
Userland/Libraries/LibWeb/Clipboard/Clipboard.idl
Userland/Libraries/LibWeb/Crypto/SubtleCrypto.idl
Userland/Libraries/LibWeb/DOM/HTMLFormControlsCollection.idl
Userland/Libraries/LibWeb/HTML/NavigateEvent.idl
Userland/Libraries/LibWeb/HTML/Navigation.idl
Userland/Libraries/LibWeb/HTML/NavigationDestination.idl
Userland/Libraries/LibWeb/HTML/NavigationHistoryEntry.idl
Userland/Libraries/LibWeb/HTML/NavigationTransition.idl
Userland/Libraries/LibWeb/HTML/NavigationType.idl
Userland/Libraries/LibWeb/HTML/NavigatorConcurrentHardware.idl
Userland/Libraries/LibWeb/HTML/NavigatorID.idl
Userland/Libraries/LibWeb/HTML/NavigatorOnLine.idl
Userland/Libraries/LibWeb/HTML/SubmitEvent.idl
Userland/Libraries/LibWeb/SVG/SVGAnimatedNumber.idl
Userland/Libraries/LibWeb/SVG/SVGAnimatedString.idl
Userland/Libraries/LibWeb/SVG/SVGTextPathElement.idl

Nitpick pr incoming: I noticed that some `.idl` files where using 2 space indentation, but almost all other use four space indentation like the rest of the project. So let's fix that.
Also the IDL interfaces in the `Animations/` use whitespace differently to align names, this is in the spec but we transform also the whitespace of other specs so I also made that conform the rest of the `.idl` files.

LibWeb: Format all .idl files to use four space indentation

---

Userland/Libraries/LibPDF/DocumentParser.cpp

Previously, parsing an xref entry with a floating point subsection number would cause a crash.
No change when running `test_pdf.py` against the PDFA 0000.zip dataset
Fixes oss fuzz issue: [65856](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65856)

LibPDF: Ensure that xref subsection numbers are u32

---

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h

Prior to this change, we iterated through all fragments within each PaintableWithLines to resolve the relative position offset. This happened before transferring the fragments to their corresponding inline paintables.
With this change, we significantly reduce amount of work by attempting to resolve relative position offsets only for those contained within inline paintables.
Performance improvement on https://html.spec.whatwg.org/

LibWeb: Resolve relpos fragment offsets only for inline paintables

---

Tests/LibWeb/Text/expected/video-failed-load.txt
Tests/LibWeb/Text/input/video-failed-load.html
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp

The condition here is flipped. From the spec:
A network error is a response whose ... body is null ...
Fixes #22851

LibWeb: Correctly categorize Fetch responses as network errors

---

Tests/LibWeb/Text/expected/HTML/Window-set-properties.txt
Tests/LibWeb/Text/input/HTML/Window-set-properties.html
Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp

Window and other global objects are not technically legacy platform objects, and have other ways to override their setters and getters.
However, Window does need to share some code with the legacy platform object paths, and simply adding another bool check to the mix seems the shortest putt.
Fixes #22818

LibWeb: Exclude [Global] interfaces from legacy platform object methods

---

Tests/LibWeb/Text/expected/window-scroll-while-parsing.txt
Tests/LibWeb/Text/input/window-scroll-while-parsing.html
Userland/Libraries/LibWeb/HTML/Window.cpp

Fixes a crash seen on https://www.ekioh.com/

LibWeb: Update layout before looking at overflow in window.scroll()

---

Userland/Libraries/LibWeb/CSS/Default.css
Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Userland/Libraries/LibWeb/HTML/HTMLInputElement.h

To finish some unfinished business with the input range element, here is basic interactivity.
You can use the following methods to adjust the input range like other browsers:
- **Keyboard**: arrows left, right, up, down and page down, up
- **Scrolling**: up and down
- **Mouse**: clicking an dragging
**There is currently no value snapping to the step size!** This is a bug, but I'll fix it in the future.
https://github.com/SerenityOS/serenity/assets/19894029/4ad42b7f-0815-4931-9859-b17833b3646f

LibWeb: Add basic input range user interactivity

---

Tests/JSSpecCompiler/test-runner.cpp
Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/ProjectTemplate.cpp
Userland/DevTools/HackStudio/main.cpp
Userland/Libraries/LibCore/Process.cpp
Userland/Libraries/LibCore/Process.h

Because it's a lot nicer to use than manually calling `posix_spawn_file_actions_FOO()` functions.

HackStudio: Use the Process::spawn() API to spawn processes

---

Userland/Utilities/nohup.cpp

For any errors that occur during the runtime of nohup, POSIX uses a 127 return code.
I have actually tried to resolve this in the past (#20537) by manually checking for errors and returning a 127 exit code but the code started to look hard to read. Thanks to `Main::set_return_code_for_errors()`, I don't have to do any of this!

nohup: Use return code 127 for errors caught by serenity_main()

---

Userland/Libraries/LibWeb/DOM/Range.cpp
Userland/Libraries/LibWeb/DOM/Range.h
Userland/Libraries/LibWeb/DOM/Range.idl

Fixes "Application error: a client-side exception has occurred (see the browser console for more information)." on https://kotlinlang.org/

LibWeb: Stub Range::get_client_rects()

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/UIEvents/custom-keyboard-event.txt
Tests/LibWeb/Text/expected/UIEvents/custom-mouse-event.txt
Tests/LibWeb/Text/input/UIEvents/custom-keyboard-event.html
Tests/LibWeb/Text/input/UIEvents/custom-mouse-event.html
Userland/Libraries/LibWeb/UIEvents/EventModifier.h
Userland/Libraries/LibWeb/UIEvents/EventModifier.idl
Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.h
Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
Userland/Libraries/LibWeb/UIEvents/WheelEvent.h

This pr implements some missing LibWeb UIEvents features:
- Add missing EventModifierInit fields
- Add MouseEvent getModifierState
- Add MouseEvent constructor
Hope you like it :^)

LibWeb: Add missing EventModifierInit fields and MouseEvent constructor & getModifierState

---

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/PixelUnits.h
Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp

During parsing of size attributes step 5 was always skipped since step 4 did a return or continue. Removing the return led to divide by zero errors in layout. Radii get set to 0 and so dividing by those will fail. I don't know if this is meant to happen or if the continuing was the right way of doing it.
Please consider this an interesting find and not a solution :)

LibWeb: Last step of size parsing always get skipped

---

Userland/Libraries/LibAccelGfx/Context.cpp
Userland/Libraries/LibAccelGfx/Context.h
Userland/Libraries/LibWeb/CMakeLists.txt
Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/WebGL/OpenGLContext.cpp
Userland/Libraries/LibWeb/WebGL/OpenGLContext.h
Userland/Libraries/LibWeb/WebGL/Types.h
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContext.cpp
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContext.h
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.cpp
Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.h

This change makes WebGL to use LibGL only in SerenityOS, and the
platform's OpenGL driver in Ladybird if it is available.
This is implemented by introducing wrapper class between WebGL and
OpenGL calls. This way it will also be possible to provide more
complete support in Ladybird even if we don't yet have all needed
calls implemented in LibGL.
For now, the wrapper class makes all GL calls virtual. However, we
can get rid of this and implement it at compile time in case of
performance problems.
Fixes https://github.com/SerenityOS/serenity/issues/22670

LibWeb: Use platform's OpenGL in WebGL when it is available

---

Tests/LibWeb/Layout/expected/misc/create-iframes-using-innerhtml.txt
Tests/LibWeb/Layout/input/misc/create-iframes-using-innerhtml.html
Userland/Libraries/LibWeb/Layout/FrameBox.cpp

If the loading of iframe's navigable has not finished by the time FrameBox layout occurs, we should not crash.
Fixes https://github.com/SerenityOS/serenity/issues/22874

LibWeb: Stop assuming navigable's existance in FrameBox

---

Tests/LibWeb/Layout/expected/block-and-inline/leading-margin-on-inline-content-that-starts-with-collapsible-whitespace.txt
Tests/LibWeb/Layout/input/block-and-inline/leading-margin-on-inline-content-that-starts-with-collapsible-whitespace.html
Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp

When iterating inline level chunks for a piece of text like " hello ", we will get three separate items from InlineLevelIterator:
- Text " "
- Text "hello"
- Text " "
If the first item also had some leading margin (e.g margin-left: 10px) we would lose that information when deciding that the whitespace is collapsible.
This patch fixes the issue by accumulating the amount of leading margin present in any collapsed whitespace items, and then adding them to the next non-whitespace item in IFC.
It's a wee bit hackish, but so is the rest of the leading/trailing margin mechanism.
This makes the header menu on https://www.gimp.org/ look proper. :^)
Before:
After:

LibWeb: Don't lose track of inline margins when collapsing whitespace

---

Userland/Applications/PDFViewer/PDFViewerWidget.cpp
Userland/Applications/PDFViewer/PDFViewerWidget.h

This makes it easier to add more entries. Also, debug toggles don't need to be quite as visible as they were on the toolbar :^)

PDFViewer: Move debug actions from toolbar into a menu

---

Userland/Applications/DisplaySettings/MonitorSettings.gml
Userland/Applications/DisplaySettings/ThemesSettings.gml
Userland/Demos/WidgetGallery/GalleryGML/BasicsTab.gml

This PR fixes some errors in the GML files for `DisplaySettings` and `WidgetGallery`.  The main cause of these issues was boolean values being put in quotes, which led to the property declaration being ignored.

DisplaySettings+WidgetGallery: Remove quotes around GML boolean values

---

Userland/Utilities/ls.cpp

This change modifies how permissions are displayed in long mode, so that:
* An 'S' is shown if the SUID/SGID bit is set for non-executable files.
* A 'T' is shown if the sticky bit is set for non-executable files.
This matches the behavior of `ls` on Linux.
Example usage:

ls: Show correct permissions in long mode for non-executable files

---

Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
Userland/Applications/FileManager/PropertiesWindow.cpp
Userland/Applications/PixelPaint/Filters/Bloom.cpp
Userland/Applications/Presenter/SlideObject.h
Userland/Libraries/LibGfx/Font/FontDatabase.h
Userland/Libraries/LibGfx/Font/FontWeight.h
Userland/Libraries/LibWeb/CSS/StyleValue.cpp
Userland/Services/NotificationServer/CMakeLists.txt
Userland/Services/NotificationServer/NotificationWidget.gml
Userland/Services/NotificationServer/NotificationWidget.h
Userland/Services/NotificationServer/NotificationWindow.cpp

**Before:**
[Peek 2024-01-16 16-15 broken notifications.webm](https://github.com/SerenityOS/serenity/assets/222642/be5dd8c7-ec75-4c5b-aec6-ce1c29d36772)
**After:**
[Peek 2024-01-16 16-06 fixed notifications.webm](https://github.com/SerenityOS/serenity/assets/222642/6522f9ca-5688-44da-b7e6-406478f83bc8)
It's a little hacky to manually calculate the heights here, but it works, until the layout system can handle this better.

NotificationServer: Fix the layout for multi-line notifications

---

Userland/Libraries/LibWeb/WebGL/OpenGLContext.cpp
Userland/Libraries/LibWeb/WebGL/OpenGLContext.h

Destructor of AccelGfxContext needs to make sure that correct OpenGL
context is active so that destructors of its members could proceed
destroying they resources (for example framebuffer owned by
AccelGfx::Canvas).
Fixes https://github.com/SerenityOS/serenity/issues/22879

LibWeb/WebGL: Switch context in AccelGfxContext destructor

---

Tests/LibWeb/Layout/expected/zero_percent_width_nested_table.txt
Tests/LibWeb/Layout/input/zero_percent_width_nested_table.html
Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp

Previously, a crash could occur when computing the width of a table with cells that had a percentage width of 0.
Fixes #22813
Fixes #21607

LibWeb: Avoid division by zero when computing table width

---

Tests/LibWeb/Layout/expected/misc/set-display-null.txt
Tests/LibWeb/Layout/input/misc/set-display-null.html
Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp

Spec defines `[LegacyNullToEmptyString]` on `value` argument of `setProperty` but since `internal_set` calls `setProperty` directly instead of using IDL generated binding, we need to make sure that null is treated as empty string.
Fixes items grid loading on https://d.rsms.me/stuff/

LibWeb: Treat null as empty string in CSSStyleDeclaration::internal_set

---

Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h

For parameters that exist strictly as "locals", we can save time and space by not adding them to the function environment.
This is a speed-up across the board on basically every test. For example, ~11% on Octane/typescript.js :^)
```
Kraken      ai-astar.js                              1.032  0.810 ± 0.800 … 0.820     0.785 ± 0.780 … 0.790
Kraken      audio-beat-detection.js                  1.044  0.470 ± 0.460 … 0.480     0.450 ± 0.450 … 0.450
Kraken      audio-dft.js                             1      0.355 ± 0.350 … 0.360     0.355 ± 0.350 … 0.360
Kraken      audio-fft.js …
```

LibJS: Don't add uncaptured parameter bindings to environment

---

AK/BufferedStream.h
AK/Format.cpp
Tests/LibCore/TestLibCoreStream.cpp
Userland/Libraries/LibCore/Socket.h
Userland/Libraries/LibHTTP/Job.cpp

AK+LibCore+LibHTTP: Ensure the ending \r\n is present before trying to read a line

---

AK/JsonObject.cpp
AK/JsonObject.h
AK/JsonValue.cpp
AK/JsonValue.h
Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
Meta/Lagom/Tools/CodeGenerators/LibGL/GenerateGLAPIWrapper.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
Tests/AK/TestJSON.cpp
Userland/Applications/Maps/UsersMapWidget.cpp
Userland/Applications/PixelPaint/MainWidget.cpp
Userland/Applications/Presenter/Presentation.cpp
Userland/Applications/Presenter/SlideObject.cpp
Userland/DevTools/Profiler/Profile.cpp
Userland/Libraries/LibGUI/JsonArrayModel.cpp
Userland/Libraries/LibGUI/PropertyDeserializer.cpp
Userland/Libraries/LibGUI/PropertyDeserializer.h
Userland/Libraries/LibGUI/Variant.cpp
Userland/Libraries/LibGUI/Variant.h
Userland/Libraries/LibJS/Runtime/JSONObject.cpp
Userland/Libraries/LibSymbolication/Symbolication.cpp
Userland/Libraries/LibWeb/WebDriver/TimeoutsConfiguration.cpp
Userland/Services/WebContent/WebDriverConnection.cpp

These patches almost completely remove the ability to introspect how `AK::JsonValue` stores its numeric value. They also replace `to_X` functions which have implicit default value with the newly created `get_X` functions that return `Optional<X>`. Anything that is not explicitly marked `_with_precision_loss` will not truncate stored value but instead panic / return empty optional. In the result, we get much more intuitive and explicit interface which is also consistent with `JsonObject`.
The relevant parts of JsonValue interface with the changes from PR look like this:
- `Optional<X> get_X()` where X is one of `int`, `i32`, `i64`, `uint`, `u32`, `u64`. Empty optional if not a number or value is outside of T's domain.
- `Optional<T> get_integer<T>()`. Empty optional if not a number or …

AK+Everywhere: Better JsonValue numeric API

---

Base/usr/share/man/man1/base64.md
Userland/Utilities/base64.cpp

This is an option supported by coreutils, so we might as well support it too.
It allows users to wrap their encoded output after the "column" value they provide.
This commit also has the Markdown look more like what we see when running ArgsParser::print_usage_markdown() (and it fixes some of the examples).
Examples:

base64: Implement -w/--wrap

---

Tests/LibWeb/Ref/first-available-font-should-include-whitespace.html
Tests/LibWeb/Ref/reference/first-available-font-should-include-whitespace-ref.html
Userland/Libraries/LibWeb/Layout/Node.h

Fixes https://github.com/SerenityOS/serenity/issues/22853

LibWeb: Find font that has whitespace glyph in first_available_font()

---

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp

perform_call() wants a ReadonlySpan<Value>, so just grab a slice of the current register window instead of making a MarkedVector.
10% speed-up on this function call microbenchmark:
function callee(a, b, c) { }
function caller(callee) {
for (let i = 0; i < 10_000_000; ++i)
callee(1, 2, 3)
}
caller(callee)

LibJS: Avoid unnecessary MarkedVector in Bytecode::Op::Call::execute()

---

Userland/Libraries/LibGfx/ICC/Profile.cpp

Doesn't matter if both profiles are sRGB since
inv(A) * A == A * inv(A), but when converting e.g. a P3 image to sRGB, the colors are very off if the matrices are the wrong way round here.

LibGfx/ICC: Fix small mistake from #22700

---

Kernel/Arch/riscv64/MMU.cpp
Kernel/CMakeLists.txt

I am not sure why 096cecb95e disabled the stack protector and sanitizers for all files, but this is not necessary.
Only the pre_init code needs to run without them, as that code runs identity mapped.

Kernel/riscv64: Don't disable stack protector and sanitizers

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.h
Userland/Libraries/LibGfx/TIFFGenerator.py

Support for JPEGs embedded in TIFF images was introduced with TIFF 6.0. However, this implementation had major issues. It was so problematic that they decided to reimplement it from scratch in 1995, three years later. The two incarnations are obviously incompatible.
For more details see:
https://www.awaresystems.be/imaging/tiff/specification/TIFFTechNote2.txt

LibGfx/TIFF: Rename JPEG to OldJPEG and introduce a new JPEG tag

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.h
Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.h

This is fairly simple as the main task was to get the two decoder to communicate.

LibGfx/JPEG+TIFF: Expose Exif metadata from JPEGs

---

Meta/bochsrc

This allows using Bochs instances that are installed in non-standard directories.

Meta: Use BXSHARE instead of a hardcoded Bochs directory

---

Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Userland/Libraries/LibGfx/TIFFGenerator.py

We previously were considering Float and Doubles as non-supported types. But this was done in a sneaky way, by letting them hit the default case in the `read_type` method. So, when I ported this function to the generator we started to make this types flow into the system without a proper support there. Since 3124c161, we would have crashes on images containing tags with a floating point value.

LibGfx/TIFF: Add support for Float and Double types

---

Tests/LibWeb/Layout/expected/table-fixup-with-rowspan.txt
Tests/LibWeb/Layout/input/table-fixup-with-rowspan.html
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

Previously, our code for the fixup of table rows assumed that missing cells in a table row must be sequential. This may not be true if the table contains cells have a rowspan greater than one.
Fixes #22815

LibWeb: Remove invalid assertion in table fixup

---

Userland/Libraries/LibWeb/DOM/Document.cpp

This code appears to be leftover from times when layout and paintable trees were not GC-allocated.

LibWeb: Remove unnecessary layout tree disconnection during teardown

---

Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Userland/Libraries/LibWeb/Layout/LayoutState.h

Instead of using separate loops for each property, all the work can be completed in one loop.
Performance improvement on https://html.spec.whatwg.org/

LibWeb: Resolve all layout-dependent properties in one loop

---

Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
Userland/Libraries/LibWeb/HTML/MessageEvent.h

Also change a `Vector<Handle>` to a `Vector<NonnullGCPtr>` while we're here, since there's no need to use handles for members of a cell.
Fixes an ASAN error on the HTML/Window-postMessage.html test.

LibWeb: Add missing visits in MessageEvent

---

Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/Locator.cpp

Fixes a couple of issues with the Locator:
- It would lose focus after each character you type in the text box.
- Jumping to a symbol wouldn't scroll to the relevant line, and the Locator would remain focused.

HackStudio: Make Locator comfier to use

---

Userland/Applications/FontEditor/MainWidget.cpp
Userland/Applications/HexEditor/HexEditorWidget.cpp
Userland/Applications/ImageViewer/ViewWidget.cpp
Userland/Applications/PDFViewer/PDFViewerWidget.cpp
Userland/Applications/PixelPaint/MainWidget.cpp
Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
Userland/Applications/TextEditor/MainWidget.cpp
Userland/Applications/ThemeEditor/MainWidget.cpp
Userland/DevTools/GMLPlayground/MainWidget.cpp
Userland/DevTools/HackStudio/HackStudioWidget.cpp
Userland/DevTools/HackStudio/HackStudioWidget.h
Userland/DevTools/HackStudio/main.cpp
Userland/Libraries/LibGUI/Application.cpp
Userland/Libraries/LibGUI/Application.h
Userland/Libraries/LibGUI/Menu.cpp
Userland/Libraries/LibGUI/Menu.h

This was motivated by HackStudio crashing every time I clicked a recent project in the list. I noticed it wasn't using the LibGUI built-in way of handling recent files, so now it uses that instead! As a bonus: no crashing. :tada:

HackStudio+LibGUI: Stop crashing when opening a recent project

---

Userland/Libraries/LibAccelGfx/Context.cpp
Userland/Libraries/LibAccelGfx/Context.h
Userland/Libraries/LibWeb/WebGL/OpenGLContext.cpp
Userland/Services/WebContent/PageClient.cpp

Now, if OpenGL context fails, an error will be returned and a message printed, instead of crashing.

LibAccelGfx+LibWeb+WebContent: Handle OpenGL Context init errors

---

Userland/Libraries/LibC/dlfcn.cpp
Userland/Libraries/LibC/libcinit.cpp
Userland/Libraries/LibC/link.cpp
Userland/Libraries/LibC/ssp.cpp
Userland/Libraries/LibC/stdlib.cpp
Userland/Libraries/LibELF/DynamicLinker.cpp

This works by defining a set of weak symbols in dynamic linker whose value would be provided by it. This has the same effect as preloading library that magically knows right addresses of functions shared between dynamic linker and LibC.
We were previously passing the same information by rewriting symbols based on hardcoded library name, so the new approach seems a little nicer to me.
------
This initially popped up in my excessively intrusive LibRuntime PR and thus didn't get merged but I reasoned it might a good change on its own.
Answering potential review question: no, I can't make `MagicWeakSymbol` not ref-counted, since it is impossible to store `OwnPtr`s in `HashMap`.

LibC+LibELF: Pass information from linker via magic lookup

---

Userland/Libraries/LibWebView/InspectorClient.cpp

As of commit ccd701809fc168c90b2f74bdb3b3f2a3fd82d10e, the formatter for JsonValue now fully serializes the value. The serializer will surround the string value with quotes. We want control over when we add quotes to the generated Inspector HTML, so avoid formatting attributes as raw JSON values.

LibWebView: Prevent quoting attribute values twice in the Inspector

---

AK/NumberFormat.cpp
AK/NumberFormat.h
Base/usr/share/man/man1/uptime.md
Userland/Applications/FileManager/PropertiesWindow.cpp
Userland/Games/Minesweeper/Field.cpp
Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.cpp
Userland/Services/WebServer/Client.cpp
Userland/Utilities/dd.cpp
Userland/Utilities/ls.cpp
Userland/Utilities/uptime.cpp

Adds `-p/--pretty` for the previous human-readable output, with the longer Linux/BSD-like output for when this isn't present. And then adds `-s/--since` to just output the datetime we came online. This also means `uptime` now gets the standard `--version` and `--help` options.
Before that, convert the `human_readable_foo()` functions to return `String` instead of `ByteString`. Since these are in AK, I'm a little conflicted about whether they should return `ErrorOr<String>` instead, BUT they're not used in the kernel, and are already not OOM-safe, so I don't worry about that for now.

uptime: Add some nice options that Linux and the BSDs provide

---

Tests/LibWeb/Layout/expected/flex/space-between-with-negative-remaining-space-on-line.txt
Tests/LibWeb/Layout/input/flex/space-between-with-negative-remaining-space-on-line.html
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp

Before this change, it was possible for flex lines with negative remaining space (due to overflowing items) to put a negative amount of space between items for some values of `justify-content`.
This makes https://polar.sh/SerenityOS look much better :^)
Before:
After:

LibWeb: Clamp justification space between flex items to 0

---

Tests/LibWeb/Text/expected/hit_testing/nested-inline-paintables.txt
Tests/LibWeb/Text/input/hit_testing/nested-inline-paintables.html
Tests/LibWeb/Text/input/include.js
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp

Before this change we were ignoring nested paintables inside inline paintable during hit-testing, but now we recurse into subtree.
Fixes https://github.com/SerenityOS/serenity/issues/22927

LibWeb: Test nested elements in InlinePaintable::hit_test()

---

Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorCPU.h
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.cpp
Userland/Libraries/LibWeb/Painting/PaintingCommandExecutorGPU.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
Userland/Libraries/LibWeb/Painting/RecordingPainter.h

It was only used in ImagePaintable for alt text and now it is replaced by saving font inside DrawText command.

LibWeb: Remove SetFont painting command

---

Tests/LibWeb/TestConfig.ini
Tests/LibWeb/Text/input/HTML/Window-postMessage.html

For some reason on macOS with ASAN enabled, the test promises in HTML/Window-postMessage do not resolve. These promises wait for both the in-document and the blob url iframes to load. It's not clear why this works fine in Linux nor why the onload handler doesn't fire when the iframe has already loaded.

LibWeb: Resolve postMessage test promises if iframes already loaded

---

Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp

Usually x and u go horizontally and y and v go vertically.

LibGfx/JPEGWriter: Rename y<=>x, u<=>v

---

Tests/LibWeb/Text/expected/Streams/init-from-cloned-fetch-response.txt
Tests/LibWeb/Text/input/Streams/init-from-cloned-fetch-response.html
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.h

Fixes #22960
We still crash on chat.openai.com, but in CSS this time:
```
VERIFICATION FAILED: i < m_size at Meta/Lagom/../../AK/Vector.h:139
Build/lagom/lib/liblagom-ak.so.0(ak_verification_failed+0xc1) [0x7ff19c306da1]
Build/lagom/lib/liblagom-web.so.0 Web::CSS::SumCalculationNode::equals(Web::CSS::CalculationNode const&) const 0x9c) [0x7ff19b574cbc]
Build/lagom/lib/liblagom-web.so.0 Web::CSS::TransformationStyleValue::Properties::operator==(Web::CSS::TransformationStyleValue::Properties const&) const 0xba) [0x7ff19b59aa6a]
Build/lagom/lib/liblagom-web.so.0 Web::CSS::StyleValueList::Properties::operator==(Web::CSS::StyleValueList::Properties const&) const 0xba) [0x7ff19b59a66a]
Build/lagom/lib/liblagom-web.so.0 Web::DOM::Element::recompute_style() 0x13f) [0x7ff19b5dd91f]
```

LibWeb: Implement a slightly better ad-hoc `Body::clone` method

---

Tests/LibWeb/Text/expected/css/replace-calc-function-with-same-kind-but-fewer-arguments.txt
Tests/LibWeb/Text/input/css/replace-calc-function-with-same-kind-but-fewer-arguments.html
Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp

Before comparing the elements of two vectors, we have to check that they have the same length. :^)
Fixes a crash seen on https://chat.openai.com/

LibWeb: Fix vector OOB access when comparing some calc() values

---

Tests/LibWeb/Layout/expected/svg/nested-viewports.txt
Tests/LibWeb/Layout/expected/svg/svg-symbol-with-viewbox.txt
Tests/LibWeb/Layout/expected/svg/use-honor-outer-viewBox.txt
Tests/LibWeb/Layout/input/svg/nested-viewports.html
Tests/LibWeb/Layout/input/svg/use-honor-outer-viewBox.html
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.h
Userland/Libraries/LibWeb/Painting/SVGPathPaintable.cpp
Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
Userland/Libraries/LibWeb/SVG/SVGSVGElement.h
Userland/Libraries/LibWeb/SVG/SVGSymbolElement.h
Userland/Libraries/LibWeb/SVG/SVGViewport.h

Previously, we were handling viewBoxes/viewports in a slightly hacky way, asking graphics elements to figure out what viewBox to use during layout. This does not work in all cases, and can't allow for more complex SVGs where it is possible to have nested viewports.
This commit makes the SVGFormattingContext keep track of the viewport/boxes, and it now lays out each viewport recursively, where each nested `<svg>` or `<symbol>` can establish a new viewport.
This fixes some previous edge cases, and starts to allow nested viewports (there's still some issues to resolve there).
Fixes #22931

LibWeb: Add initial support for nesting SVG viewports

---

Userland/Libraries/LibWeb/ARIA/RoleType.cpp

This change allows `contentinfo`, `none`, `subscript` and `superscript` RoleTypes to be built. These were the only non-abstract role types missing from this function.
This fixes an issue where clicking on an element with one of these role types in Inspector would cause a crash.
Tested manually by clicking each of the elements on the following page in Inspector:
```html
<body>
<sub>sub</sub>
<sup>sup</sup>
<div role="contentinfo">contentinfo</div>
<div role="none">none</div>
```

LibWeb: Add missing ARIA roles to `RoleType::build_role_object()`

---

AK/JsonValue.h

Just because pointers don't use 64 bits doesn't mean the type FlatPtr will resolve to is the same as u32; instead of playing the guessing game, simply use whatever type FlatPtr is.
Of course it's because windows, what else <https://github.com/SerenityOS/jakt/actions/runs/7677815317/job/20926995435>.

AK: Use IsSame<FlatPtr, T> instead of __LP64__ to guess FlatPtr's type

---

AK/StdLibExtraDetails.h
Userland/Libraries/LibJS/Heap/HeapFunction.h
Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Userland/Libraries/LibWeb/Streams/AbstractOperations.h
Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultController.cpp
Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultController.h
Userland/Libraries/LibWeb/Streams/TransformStream.cpp
Userland/Libraries/LibWeb/Streams/TransformStreamDefaultController.cpp
Userland/Libraries/LibWeb/Streams/TransformStreamDefaultController.h
Userland/Libraries/LibWeb/Streams/WritableStream.cpp
Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.cpp
Userland/Libraries/LibWeb/Streams/WritableStreamDefaultController.h

This allow us to actually clear stream controller algorithms when needed as
now these functions are GC-allocated like everything else.

LibWeb: Port Stream algorithms from JS::SafeFunction to JS::HeapFunction

---

Tests/LibWeb/Ref/abspos-escapes-scroll-container.html
Tests/LibWeb/Ref/overflow-hidden-3.html
Tests/LibWeb/Ref/overflow-hidden-4.html
Tests/LibWeb/Ref/overflow-hidden-5.html
Tests/LibWeb/Ref/reference/abspos-escapes-scroll-container-ref.html
Tests/LibWeb/Ref/reference/overflow-hidden-3-ref.html
Tests/LibWeb/Ref/reference/overflow-hidden-4-ref.html
Tests/LibWeb/Ref/reference/overflow-hidden-5-ref.html
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/Painting/BorderRadiiData.cpp
Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.h
Userland/Libraries/LibWeb/Painting/PaintContext.h
Userland/Libraries/LibWeb/Painting/Paintable.cpp
Userland/Libraries/LibWeb/Painting/Paintable.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Userland/Libraries/LibWeb/Painting/ViewportPaintable.h

With this change, clip rectangles for boxes with hidden overflow or the clip property are no longer calculated during the recording of painting commands. Instead, it has moved to the "pre-paint" phase, along with the assignment of scrolling offsets, and works in the following way:
1. The paintable tree is traversed to collect all paintable boxes that have hidden overflow or use the CSS clip property. For each of these boxes, the "final" clip rectangle is calculated by intersecting clip rectangles in the containing block chain for a box.
2. The paintable tree is traversed another time, and a clip rectangle is assigned for each paintable box contained by a node with hidden overflow or the clip property.
This way, clipping becomes much easier during the painting commands recording phase, as …

LibWeb: Move clip rect calculation to happen before painting

---

Tests/LibWeb/Layout/expected/block-and-inline/button-with-min-height.txt
Tests/LibWeb/Layout/input/block-and-inline/button-with-min-height.html
Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp

This ensures that the vertical positioning of button text is correct if a `min-height` property is present.
This can be seen on the [Wikipedia login page](https://en.wikipedia.org/w/index.php?title=Special:UserLogin)
Before:
After:

LibWeb: Make button flex wrapper inherit `min-height` property

---

Tests/LibWeb/Ref/overflow-hidden-6.html
Tests/LibWeb/Ref/reference/overflow-hidden-6-ref.html
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

This is a fix for regression introduced in
0bf82f748f44c961eb03c76a97620783fef69a32
All CSS transforms need to be removed from the clip rectangle before applying it. However, it is still necessary to calculate it with applied transforms to find the correct intersection of all clip rectangles in the containing block chain.

LibWeb: Fix hidden overflow clipping with nested CSS transforms

---

Tests/LibWeb/Text/expected/hit_testing/overflow-scroll.txt
Tests/LibWeb/Text/input/hit_testing/overflow-scroll.html
Userland/Libraries/LibWeb/Internals/Internals.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.h
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp

The hit-testing position is now shifted by the scroll offsets before performing any checks for containment. This is implemented by assigning each PaintableBox/InlinePaintable an offset corresponding to the scroll frame in which it is contained. The non-scroll-adjusted position is still passed down when recursing to children because the assigned offset accumulated for nested scroll frames.
With this change, hit testing works in the Inspector.
Fixes https://github.com/SerenityOS/serenity/issues/22068

LibWeb: Account for scroll offset in hit-testing

---

Tests/LibWeb/Layout/expected/svg/svg-inside-svg-with-xy.txt
Tests/LibWeb/Layout/input/svg/svg-inside-svg-with-xy.html
Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
Userland/Libraries/LibWeb/CSS/ComputedValues.h
Userland/Libraries/LibWeb/CSS/Properties.json
Userland/Libraries/LibWeb/Layout/Node.cpp
Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp

This allows positioning a child SVG relative to its parent SVG.
Note: These have been implemented as CSS properties as in SVG 2, these are geometry properties that can be used in CSS (see https://www.w3.org/TR/SVG/geometry.html), but there is not much browser support for this. It is nicer to implement than the ad-hoc SVG attribute parsing though, so I feel it may make sense to port the rest of the attributes specified here (which should fix some issues with viewport relative sizes).
This fixes the logo position on the Azure pipelines badge:

LibWeb: Support `x` and `y` attributes on nested SVGs

---

Userland/Libraries/LibCore/ArgsParser.cpp
Userland/Libraries/LibCore/ArgsParser.h

This option is useful for parsing e.g. negative offsets. Wondering why this was missing but it works fine :)

LibCore: Refactor template definitions to header in ArgsParser

---

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp

That's all this function reads from Component.
Also rename from validate_luma_and_modify_context() to validate_sampling_factors_and_modify_context().
---
Related to some of #22780.

LibGfx/JPEGLoader: Pass SamplingFactors instead of Component to function

---

Tests/LibWeb/Layout/expected/select-with-option-selected.txt
Tests/LibWeb/Layout/input/select-with-option-selected.html
Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp

Previously, a select element's text would initially be empty if the `selected` property was set on one of its options.
This was affecting the search controls on the [Ladybird AUR page](https://aur.archlinux.org/packages/ladybird)
Before:
After:
Note: This change doesn't affect the layout of the search controls. I've opened a separate issue (#22992) for that.

LibWeb: Set select element text when an option is initially selected

---

Userland/Utilities/mktemp.cpp

Resolves #22773.
Previously, we ignored the -p argument if it was specified. This would resort in a crash because final_target_directory wasn't given a value.
This snapshot does away with giving this variable an Optional<> and just has the -p argument be its default value.

mktemp: Make sure to use target directory option argument

---

Tests/LibWeb/Text/expected/element-get-bounding-client-rect-css-transform.txt
Tests/LibWeb/Text/expected/element-get-client-rects.txt
Tests/LibWeb/Text/input/element-get-bounding-client-rect-css-transform.html
Tests/LibWeb/Text/input/element-get-client-rects.html
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp

Align getClientRects() and getBoundingClientRect() implementations with the spec more precisely and make them account for CSS transform.

LibWeb: Follow the spec more precisely in Element::getClientRects()

---

Userland/Applications/Maps/FavoritesPanel.cpp

This prevents a crash when attempting to add a favorite in Maps application

Maps: Add massage_for_display to latitude and longitude when loading favorites

---

Userland/Services/Taskbar/QuickLaunchWidget.cpp

This pr fixes a crash for me where dropping an item (`.af`, `bin` or symlink to a `bin`) in the Taskbar quick launch widget. An `OwnPtr::operator ->` and `OwnPtr::release_nonnull()` on the same line gives memory conflicts I think, putting the get name on a separated line fixes the issue.

Taskbar: Fix bug where dropping item in quick launch widget would crash

---

Userland/DevTools/HackStudio/CMakeLists.txt
Userland/DevTools/HackStudio/DeclarationsModel.cpp
Userland/DevTools/HackStudio/DeclarationsModel.h
Userland/DevTools/HackStudio/Locator.cpp
Userland/DevTools/HackStudio/Locator.h
Userland/DevTools/HackStudio/ProjectDeclarations.cpp
Userland/DevTools/HackStudio/ProjectDeclarations.h

Previously, we threw away and rebuilt the Model used for Locator suggestions, each time the input changed. That felt excessive to me, so this PR instead keeps a single DeclarationsModel around for the project, which the Locator accesses via a FilteringProxyModel that fuzzy-matches the declarations.
At some point maybe the "Classes" view could use this same source model, but I haven't looked into that.
Fuzzy-matching isn't perfect currently but that's outside the scope of this PR. The sorting of results definitely isn't worse than the previous unsorted list. :^)
ProjectDeclarations also seems like it should be part of Project, but one step at a time. Combining them would help with a small issue introduced here: The Locator will not list files until the first ComprehensionEngine results …

HackStudio: Use a single, filtered model for Locator output

---

Userland/Applications/HexEditor/AnnotationsModel.cpp
Userland/Applications/HexEditor/AnnotationsModel.h
Userland/Applications/HexEditor/CMakeLists.txt
Userland/Applications/HexEditor/EditAnnotationDialog.cpp
Userland/Applications/HexEditor/EditAnnotationDialog.h
Userland/Applications/HexEditor/EditAnnotationWidget.gml
Userland/Applications/HexEditor/HexDocument.cpp
Userland/Applications/HexEditor/HexDocument.h
Userland/Applications/HexEditor/HexEditor.cpp
Userland/Applications/HexEditor/HexEditor.h
Userland/Applications/HexEditor/HexEditorWidget.cpp
Userland/Applications/HexEditor/HexEditorWidget.gml
Userland/Applications/HexEditor/HexEditorWidget.h

Make the annotations a bit more useful. Clicking on one in the table will jump to its first byte, similar to how the search results panel works.
Hovering over an annotation will show its comment text as a tooltip.

HexEditor: Add comments to annotations, and show them in the GUI

---

Meta/Lagom/CMakeLists.txt
Meta/Lagom/Contrib/MacPDF/AppDelegate.mm
Userland/Utilities/pdf.cpp

This way, build files can install things into
`${CMAKE_BINARY_DIR}/Root/res/` and it'll work in both serenity and
lagom builds.
It allows using a single `Core::ResourceImplementation::install()`
call to install both checked-in and generated files (as long as both
get copied into this new build-time staging dir).
---
As discussed on Discord: I'd like to make LibPDF read a generated file. `Core::ResourceImplementation::install()` allows only  a single dir, so the thing we settled on was to make a new dir that has both pre-existing files and generated files and use that as ResourceImplementation dir.
This PR here copies the static files over. Other binaries can adopt this over time if they want.
I'll put the change to add a generated file in this new directory into a …

Meta: Create Build/lagom/Root/res with resources for lagom binaries

---

Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-1-ref.html
Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-2-ref.html
Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-1.html
Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-2.html
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

This change addresses an issue with overflow clipping in scenarios where `overflow: hidden` is applied to boxes nested within elements with `overflow: scroll`.
Fixes https://github.com/SerenityOS/serenity/issues/22733

LibWeb: Account for scroll offset in overflow clip rect calculation

---

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Userland/Libraries/LibWeb/Painting/PaintableFragment.h

No longer used after we made inline paintables own their fragments.

LibWeb: Remove contained_by_inline_node flag in PaintableFragment

---

Userland/Libraries/LibPDF/Document.cpp
Userland/Libraries/LibPDF/DocumentParser.cpp

https://llvm.org/devmtg/2022-11/slides/TechTalk5-WhatDoesItTakeToRunLLVMBuildbots.pdf has an xref table that starts like so:
```
xref
0 214
0000000002 65535 f
0000924663 00000 n
0000000003 00000 f
0000000000 00000 f
0000000016 00000 n
0000000160 00000 n
0000000263 00000 n
```
This is a list of objects in the PDF file. The lines ending with 'f' mean that this object is "free", that is it's not stored in the file. In this file, objects 0, 2, 3 are free. For free objects, the first number is the offset of the next free object: Object 0 refers to object 2, 2 to 3, and 3 back to 0 (since it's the last free object). The lines ending with "n" are actual objects; here the first number is a byte offset to where that object is stored in the file.
Furthermore, the file contains
```
/Outlines
2
0
R …
```

LibPDF: Return null for invalid refs, tolerate null objects as outline

---

Base/usr/share/man/man1/Applications/HexEditor.md
Userland/Applications/HexEditor/AnnotationsModel.cpp
Userland/Applications/HexEditor/AnnotationsModel.h
Userland/Applications/HexEditor/HexEditorWidget.cpp
Userland/Applications/HexEditor/HexEditorWidget.h
Userland/Applications/HexEditor/main.cpp

~Builds on #23001. Draft until that's merged.~
----
Because if you've spent time annotating a file or general format, you don't want to lose that work. :^)

HexEditor: Save and load annotations to/from JSON files

---

Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-and-opacity-ref.html
Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-and-opacity.html
Userland/Libraries/LibWeb/Painting/PaintableBox.h
Userland/Libraries/LibWeb/Painting/RecordingPainter.h
Userland/Libraries/LibWeb/Painting/StackingContext.cpp

In cases where the stacking context painting requires a separate bitmap, the destination position needs to be translated by the scrolling offset to ensure it ends up in the correct position.
Visual progress on Discord's chat scrolling:
https://github.com/SerenityOS/serenity/assets/45686940/d305c12e-2f9a-4826-bea5-a66a6390fd1b

LibWeb: Apply scroll offset to PushStackingContext command

---

Userland/Libraries/LibWeb/DOM/Element.cpp

Now when Window::scroll() could do actual scrolling we can remove these FIXMEs.

LibWeb: Use Window::scroll() in set_scroll_left() and set_scroll_top()

---

Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp
Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.h
Userland/Utilities/image.cpp

`image` can't transform from RGB to CMYK yet, so the only way to
do this is by having a CMYK input.
For example, this works now (and it does a full decode and re-encode):
Build/lagom/bin/image -o out.jpg \
Tests/LibGfx/test-inputs/jpg/buggie-cmyk.jpg
Using this to convert `.pam` files written by `mutool extract`
to jpegs is a somewhat convenient method of looking at these
.pam files.
---
Most of the commits are mechanical and tiny.

LibGfx+image: Allow saving CMYK jpegs

---

Userland/Utilities/image.cpp

The motivation was to make all parts of `serenity_main()` act at roughly the same level of abstraction.

image: Minor cleanups and reorganizations

---

Userland/Libraries/LibGfx/ImageFormats/PortableImageLoaderCommon.h

bab2113ec1f made read_whitespace() return ErrorOr, which makes this easy to do.
(7cafd7d177f, which added the fixmes, landed slightly after bab2113ec1f, so not quite sure why it wasn't like this immediately. Maybe commit order got changed during review; both commits were in #17831.)

LibGfx/PNM: Remove two fixmes

---

Userland/Services/SystemServer/Service.cpp

This causes us to use the "3 tries then give up" logic for services that crash, instead of infinitely attempting to respawn them.
---
Discovered this when going from [my branch changing the ClipboardHistory.json format](https://github.com/SerenityOS/serenity/pull/23030) to master. ClipboardHistory then sees the wrong JSON format, crashes, and... SystemServer would infinitely try to respawn it, giving me an overwhelming number of CrashReporter popups. :sweat_smile:
I'm still a Unix noobie so there may be other signals we should treat as "this program executed successfully", or maybe SIGPIPE shouldn't be there. I don't know! I just know this fixes the issue for me.

SystemServer: Treat services terminated by signals as not successful

---

Tests/LibWeb/TestMimeSniff.cpp
Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
Userland/Libraries/LibWeb/MimeSniff/Resource.h

This resolves a FIXME in HTMLObjectElement.cpp that has us sniff a resource using the [rules for distinguishing if a resource is text or binary](https://mimesniff.spec.whatwg.org/#rules-for-text-or-binary) if its HTTP Content-Type header is "text/plain".
I manually tested this change by using the following object element and a good old `dbgln()`:
```html
<object type="text/plain" data="binary_file.txt" width="600" height="140">
</object>
```
... where "binary_file.txt" is a file that contains the binary characters \x00 \x01. I just checked if the `binary` variable was set when I navigate to this HTML page and from looking at the runtime this appears to be the case.

LibWeb: Apply sniffing rules for text or binary resources in HTMLObjectElement

---

Userland/Services/WebContent/PageClient.cpp

Fixes silly bug when AccelGfx always was created twice.

LibWeb: Create AccelGfx context only once in PageClient

---

Userland/Libraries/LibPDF/ObjectDerivatives.cpp

For pages containing images or embedded fonts, --dump-contents used to dump a ton of binary data. That isn't very useful, so stop doing it.
Before:
% time Build/lagom/bin/pdf --render out.png \
~/Downloads/0000/0000711.pdf --dump-contents | wc -l
937972
Now:
% time Build/lagom/bin/pdf --render out.png \
~/Downloads/0000/0000711.pdf --dump-contents | wc -l
6566
Printing 7k lines is also much faster than printing 940k, 0.15s instead of 2s.

LibPDF: Make `pdf --dump-contents` dump less binary data

---

Tests/LibWeb/Ref/reference/scroll-iframe-ref.html
Tests/LibWeb/Ref/scroll-iframe.html
Userland/Libraries/LibWeb/DOM/Document.cpp
Userland/Libraries/LibWeb/DOM/Element.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/HTML/Navigable.cpp
Userland/Libraries/LibWeb/HTML/Navigable.h
Userland/Libraries/LibWeb/HTML/Window.cpp
Userland/Libraries/LibWeb/Page/EventHandler.cpp

With these changes `window.scroll()` works in iframe and iframes could be scrolled by mouse/trackpad.

LibWeb: Support scrolling of iframes

---

Tests/LibWeb/Ref/overflow-hidden-text-inside-translated-container.html
Tests/LibWeb/Ref/reference/overflow-hidden-text-inside-translated-container-ref.html
Userland/Libraries/LibWeb/Painting/PaintableBox.cpp

Painting command executor already accounts for CSS transforms so clip rect only needs to be adjusted by scroll offset.

LibWeb: Do not add CSS transforms into clip rect in PaintableWithLines

---

Userland/Libraries/LibWeb/Page/EventHandler.cpp

Previously, it was possible to enter various control characters into input elements by holding Ctrl and/or Alt. With this change, input elements ignore keypresses while Ctrl or Alt are pressed.
Note: This change doesn't affect the firing of `keydown` events, which are still fired if the keypress is ignored by the input. This matches the behavior of Chrome and Firefox.

LibWeb: Don't update input text if Ctrl or Alt are pressed

---

Ladybird/AppKit/Application/EventLoopImplementation.mm
Ladybird/Qt/EventLoopImplementationQt.cpp
Userland/Libraries/LibCore/Event.h
Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
Userland/Libraries/LibCore/Notifier.cpp
Userland/Libraries/LibCore/Notifier.h

As per Andrew's and Andreas' suggestion in #development. Also includes some trivial collateral damage to Notifier which will be useful later.

LibCore: Replace select(2) with poll(2) in the UNIX event loop impl

---

Userland/Utilities/image.cpp

This is useful for working with CMYK jpegs extracted from PDFs
by mutool. CMYK channels for jpegs in PDFs are inverted compared to
CMYK channels in standalone jpegs (!), and mutool doesn't compensate
for that.
You can now do:
mutool extract  ~/Downloads/0000/0000711.pdf 461
Followed by:
Build/lagom/bin/image -o out.png \
--invert-cmyk \
--assign-color-profile \
Build/lagom/Root/res/icc/Adobe/CMYK/USWebCoatedSWOP.icc \
--convert-to-color-profile serenity-sRGB.icc \
cmyk.jpg
Doesn't exactly roll off the keyboard, but at least it's possible.
(We should probably add an implicit default CMYK color profile if
the input file doesn't have one, and assume conversion to sRGB when
saving to a format that can only store RGB.)

image: Add an --invert-cmyk option

---

Userland/Libraries/LibGfx/ICC/TagTypes.h
Userland/Libraries/LibPDF/Function.cpp

Previously, if we wanted to to e.g. do linear interpolation in 2-D, we'd get a sample point like (1.3, 4.4), then get 4 samples around it at (1, 4), (2, 4), (1, 5), (2, 5), then reduce the 4 samples to 2 samples by computing the combined samples
`0.3 * f(1, 4) + 0.7 * f(2, 4)` and `0.3 * f(1, 5) + 0.8 * f(2, 5)`, and then 1-D linearly blending between these two samples with the factor 0.4. In the end we'd multiply the first value by 0.3 * 0.4, the second by 0.7 * 0.4, the third by 0.3 * 0.6, and the third by 0.7 * 0.6, and then sum them all up.
This requires computing and storing 2**N samples, followed by another 2**N iterations to combine the 2**N sampls to a single value. (N is in practice either 4 or 3, so 2**N isn't super huge.)
Instead, for every sample we can directly compute the …

LibGfx+LibPDF: Simpler and faster N-D linear sampling

---

.clang-tidy
Documentation/EmacsConfiguration.md
Documentation/HelixConfiguration.md
Documentation/VSCodeConfiguration.md

IncludeCleaner is a new feature of clang-tidy/clangd that adds upstream
support for the include-what-you-use (IWYU) tool's checks.
However, this tool is very noisy on our codebase. It can be enabled by
individual contributors at their leisure.
Also disable the cognitive complexity check, as folks have said on discord that it doesn't really help code quality.
fwiw, CC @BenWiederhake . There's now a native IWYU tool in clangd/clang-tidy :)

Meta: Disable misc-include-cleaner in clang-tidy and clangd

---

Ladybird/Qt/WebContentView.cpp

Previously, on systems where pressing Enter would generate "\r\n", only the '\r' character was being sent to the event handler. This change ensures consistent behavior across platforms regardless of their native line ending character.s
Before
After

Ladybird/Qt: Map Enter keypresses to the code point '\n'

---

AK/OptionParser.cpp
Meta/Lagom/CMakeLists.txt
Tests/AK/CMakeLists.txt
Tests/AK/TestOptionParser.cpp
Tests/LibCore/TestLibCoreArgsParser.cpp

Changes made to fix https://github.com/SerenityOS/serenity/issues/22759
Basically, there was an issue in OptionParser class where the positional argument was not shifted to the right, ending in reading an optional argument as the positional one.
Unit tests added to the existing ones for ArgsParser class using OptionParser class as an underlying parser.
Added ArgsParser unit tests to the unit test suite
New unit tests for OptionParser class

AK: Fix OptionParser argument shifting

---

Userland/Libraries/LibPDF/ObjectDerivatives.cpp

Sometimes, the "is mostly text" heuristic fails for images.
Before:
Build/lagom/bin/pdf --render out.png ~/Downloads/0000/0000521.pdf \
--page 10 --dump-contents 2>&1 | wc -l
25709
After:
Build/lagom/bin/pdf --render out.png ~/Downloads/0000/0000521.pdf \
--page 10 --dump-contents 2>&1 | wc -l
11376
(…and scrolling through, all these 11k lines look useful.)

LibPDF: Always treat `/Subtype /Image` as binary data when dumping

---

Userland/Libraries/LibWeb/XHR/ProgressEvent.h
Userland/Libraries/LibWeb/XHR/ProgressEvent.idl

Noticed this low hanging fruit FIXME while investigating some other changes - trivial to fix now that the IDL generator supports this :^)

LibWeb: Use unsigned long long for ProgressEventInit

---

Tests/LibWeb/Ref/overflow-hidden-7.html
Tests/LibWeb/Ref/reference/overflow-hidden-7-ref.html
Tests/LibWeb/Text/expected/resolve-css-overflow-effective-value.txt
Tests/LibWeb/Text/input/resolve-css-overflow-effective-value.html
Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Userland/Libraries/LibWeb/CSS/StyleComputer.h

Implements following rule from CSS Overflow Module Level 3: "The visible/clip values of overflow compute to auto/hidden (respectively) if one of overflow-x or overflow-y is neither visible nor clip."

LibWeb: Resolve effective overflow-x and overflow-y according to spec

---

Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
Userland/Libraries/LibWeb/HTML/BrowsingContext.h
Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Userland/Services/WebContent/WebDriverConnection.cpp

The spec steps to check if a browsing context is open have been updated for navigables.
Follow-up to #23063
(There have apparently been a good number of other WebDriver updates we should catch up on, :yakstack:++)

LibWeb: Make WebDriver check if the BC's navigable has been destroyed
