- Userland/Applications/Run/RunWindow.cpp
- Userland/Applications/Run/RunWindow.h
- Userland/Applications/Run/main.cpp
Currently the Run application is broken on the main branch for me, this pr fixes it.
**Explanation**: The set_main_widget<T>() function only calls the construct and not `try_create()` that the GMLCompiler generates so all calls to `find_descendant_of_type_named()` would result in null pointers that would resolve in a crash.
> Run: Fix bug where it would crash because uninitialized main widget

- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Per spec value of height should be resolved to used value if "display" property is not "none" or "contents".
> LibWeb/CSS: Resolve value of "height" in special way according to spec

- Tests/LibWeb/Text/expected/DOM/Element-from-point.txt
- Tests/LibWeb/Text/input/DOM/Element-from-point.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
This function uses our existing hit testing code to determine the topmost element at the given coordinates relative to the viewport.
https://regexr.com/ was complaining because we didn't have this.
> LibWeb: Implement `document.elementFromPoint()`

- Userland/Libraries/LibGfx/ICC/TagTypes.h
- Userland/Libraries/LibPDF/Function.cpp
Combined, take
Build/lagom/bin/image --no-output \
--assign-color-profile \
Build/lagom/Root/res/icc/Adobe/CMYK/USWebCoatedSWOP.icc \
--convert-to-color-profile serenity-sRGB.icc \
cmyk.jpg
from 2.81s to 2.66s on my machine, about 5.3% faster.
> LibGfx: Two micro-optimizations for lerp_nd()

- Ports/qt6-qt5compat/package.sh
They moved the file from `official_releases` to `archive` :^)
> Ports: Update URL for qt6-qt5compat

- AK/Endian.h
- Userland/Utilities/ntpquery.cpp
Instead of polluting global namespace with definitions from libkern/OSByteOrder.h and machine/endian.h on MacOS, just use AK functions for conversions.
---
Again, this is from https://github.com/SerenityOS/serenity/pull/21995
> ntpquery: Use AK::convert_between_host_and_network_endian

- Tests/LibWeb/Ref/button-inside-scroll-container.html
- Tests/LibWeb/Ref/reference/button-inside-scroll-container-ref.html
- Tests/LibWeb/Ref/reference/svg-inside-scroll-container-ref.html
- Tests/LibWeb/Ref/svg-inside-scroll-container.html
- Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
Rectangles should be recorded using absolute coordinates, including
the scroll offset.
> LibWeb: Fix clipping of svgs and buttons inside scroll containers

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/InspectorWidget.cpp
- Ladybird/Qt/InspectorWidget.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/WebContentView.h
Some Wayland compositors have support of fractional-scale-v1 protocol. The protocol allows compositor to announce a preferred fractional scale on a per-wl_surface basis. Qt forwards these Wayland events to an application using a usual DevicePixelRatioChange event. However, in contrast to the other platforms, this DevicePixelRatioChange event is issued directly on widgets and not screens. Additionally, the exact fractional scale is stored in QWindow object and not the current screen.
Note that in theory it is possible to obtain per-screen fractional scaling on Wayland by interpolating data provided by wl_output and xdg_output events but qtwayland does not do that.
If fractional-scale-v1 is not available, qtwayland will still fire per-Widget DevicePixelRatioChange events, but, obviously, …
> Ladybird/Qt: Properly listen for DPI changes on Wayland

- Userland/Libraries/LibCore/Socket.h
- Userland/Services/RequestServer/ConnectionFromClient.cpp
> RequestServer: Replace use of gethostbyname with Core::Socket::resolve_host

- Userland/Libraries/LibGfx/Font/OpenType/Cmap.h
- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Some fonts only contain unicode tables. This makes them work.
> LibGfx/OpenType: Support cmaps with format Unicode

- Base/home/anon/.config/Terminal.ini
- Userland/Applications/Terminal/main.cpp
- Userland/Applications/TerminalSettings/MainWidget.cpp
- Userland/Applications/TerminalSettings/MainWidget.h
- Userland/Libraries/LibVT/TerminalWidget.cpp
- Userland/Libraries/LibVT/TerminalWidget.h
This PR includes a few fixes for the new AutoMark setting TerminalSettings and Terminal to ensure we don't crash when opening the Terminal Settings window. 
The AutoMark setting is now propagated to the terminal when it is changed and is reverted when cancel is pressed.
CC: @alimpfard
> Terminal+TerminalSettings: Don't crash when opening TerminalSettings

- Tests/LibWeb/Ref/reference/resolve-paint-only-properties-after-layout-ref.html
- Tests/LibWeb/Ref/resolve-paint-only-properties-after-layout.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
Before this change, `set_needs_to_resolve_paint_only_properties()` was only called after style invalidation. However, since relayout can be triggered independently from style invalidation, we need to ensure that paint-only properties are updated in that case too.
> LibWeb: Invalidate paint-only property after relayout

- Userland/Libraries/LibGfx/Font/OpenType/Cmap.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Cmap.h
- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
Make them emit an error instead of silently drawing missing glyph boxes.
> LibGfx/OpenType: Reject fonts we can't render glyphs from earlier

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
I implemented CFF charset format 2 in 6f783929dd0 with the note "I haven't seen this being used in the wild". Now that I have seen it (0000658.pdf), I can say that this has never worked, despite me claiming "it's easy to implement".
But now it works!
---
Making fonts show up in 0000658.pdf needs a bunch of other changes too. I have those locally, but they aren't upstream yet. But this can land independently :)
> LibPDF: Fix small bug from #21452

- Kernel/Net/Intel/E1000ENetworkAdapter.cpp
The presence of EEPROM is detected by reading the EE_PRES bit from the EECD register.
> Kernel/Net: E1000ENetworkAdapter detect EEPROM

- Userland/Applications/KeyboardMapper/KeyboardMapperWidget.cpp
```
Ensure that the Utf-8 encoded "mapping character" in String (from
InputBox) gets converted to Utf-32 code point. Before, only the first
byte of Utf-8 char sequence was used as a Utf-32 code point.
That used to result in incorrect characters getting written in the
keymap file for all the "non-ascii" characters used as the mapping
character.
```
Had hard time coming up with a concise commit message even for (or
maybe because of? :thinking:) such a short diff.
> KeyboardMapper: Convert Utf-8 char in String to Utf-32 code point

- Kernel/Arch/init.cpp
This temporary memory map is a hack until we support device tree parsing.
> Kernel/riscv64: Add QEMU virt machine memory map

- Userland/Services/WindowServer/Overlays.cpp
- Userland/Services/WindowServer/WindowFrame.cpp
- Userland/Services/WindowServer/WindowManager.cpp
It has been over a month since stalebot closed #21393 so here it is again.
---
```
If the window is not resizable and you try to resize it (hovering over
borders or Super+Secondary-click) the disallowed cursor will be shown.
This conveys to the user that the window is not resizable.
```
Bug/feature: For the keyboard shortcut scenario the disallowed cursor will turn into arrow cursor immediately on mouse movements even though the Super and Secondary mouse button is held down.
A side-effect:
- Before `m_resize_candidate` was only ever a window that was resizable. But now it can also be window that cannot be resized. So only the former ones can turn into `m_resize_window`s.
I used the disallowed cursor for now but a resize cursor with a lock/cross on it would be cool too. (that's why I kept …
> WindowServer: Better resize behavior for fixed size and aspect ratio windows

- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Tests/invalid-lhs-in-assignment.js
Previously, attempting to load a value from an invalid reference would cause a crash. We now return a CodeGenerationError rather than hitting an assertion. This is not a complete solution, as ideally we would want to return a ReferenceError, but this now matches the behavior we see when we attempt to store something to an invalid reference.
I've written the test for this in a way that mirrors tests for other invalid assignments. I've left the message out, as the message displayed is not consistent across other browsers.
Fixes oss-fuzz issue [62067](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62067)
> LibJS: Don't crash when attempting to load from an invalid reference

- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
```
A markdown file gets loaded as an inline content document by
`create_document_for_inline_content()`, for which the default document
URL is "about:error". That breaks the fragment links.
Overriding "about:error" URL with the URL of the just loaded markdown
file ensures that the URL of the document is as expected.
```
I don't know if this is the right fix or not.
> LibWeb: Set document's URL when loading markdown file as inline content

- AK/JsonObject.h
- AK/JsonValue.cpp
- AK/JsonValue.h
As usual, more readable modern code, less unreadable C-style code, and less code in total!
The end goal of my AK refactoring PRs is to share memory layout of `ByteString` and `String` using now-merged (hooray!) `StringBase`. This patchset, in particular, removes the last remaining non-trivial user of `StringImpl` that complicated the process.
> AK: Store JsonValue's value in AK::Variant

- Kernel/Devices/HID/KeyboardDevice.cpp
We need to handle the character map to set the code point before we can reassign the correct key to the queued_event.key. This fixes keyboard shortcuts using the incorrect keys based on the keyboard layout.
Before this fix all shortcut keys would be using the default qwerty keyboard layout even when the keyboard
map was changed to dvorak
> Kernel/HID: Move code_point assignment before its use in key assignment

- Userland/Applications/Calendar/CMakeLists.txt
- Userland/Applications/Calendar/CalendarWidget.cpp
- Userland/Applications/Calendar/ViewEventDialog.cpp
- Userland/Applications/Calendar/ViewEventDialog.gml
- Userland/Applications/Calendar/ViewEventDialog.h
- Userland/Applications/Calendar/ViewEventWidget.cpp
- Userland/Applications/Calendar/ViewEventWidget.h
This addresses part of #22622. Created events can now be viewed by double clicking on a tile which has some events in it.
Events are currently arranged in the order they are added.
> Calendar: Add ability to view events

- Kernel/Arch/riscv64/boot.S
Multiple fields in sstatus are defined as WPRI "Reserved Writes Preserve Values, Reads Ignore Values", which means we have to preserve their values when writing to other fields in the same CSR.
We don't really need to touch any fields except SIE. Interrupts are probably already disabled, but just to be safe, disable them explicitly.
> Kernel/riscv64: Don't touch reserved fields of the sstatus CSR in boot.S

- Userland/Libraries/LibVT/TerminalWidget.cpp
```
... instead of inserting it into the current output character stream
that the terminal widget is going to render.
This ensures that the emoji gets sent to the foreground process of the
terminal.
```
> LibVT: Write emoji to the pseudo-terminal master fd on emoji input

- Ladybird/Android/src/main/cpp/RequestServerService.cpp
- Ladybird/Android/src/main/cpp/WebSocketService.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/main.mm
- Ladybird/HelperProcess.cpp
- Ladybird/HelperProcess.h
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/main.cpp
- Ladybird/RequestServer/main.cpp
- Ladybird/Types.h
- Ladybird/WebContent/main.cpp
- Ladybird/WebSocket/main.cpp
- Ladybird/WebWorker/main.cpp
- Userland/Libraries/LibTLS/Certificate.h
- Userland/Libraries/LibTLS/TLSv12.cpp
- Userland/Services/RequestServer/main.cpp
- Userland/Services/WebSocket/main.cpp
- Userland/Utilities/headless-browser.cpp
And extend this to Ladybird in Lagom. It's a bit awkward to figure out how to do this for Serenity's RequestServer, so let's pretend the problem doesn't exist :) 
This means you can run Ladybird like so:
```console
./Build/lagom/bin/Ladybird --certificate=$PWD/Tests/LibWeb/WPT/wpt/tools/certs/cacert.pem
```
To run with *only* the WPT custom Root CA cert. If you want to keep loading the default path, you'll need to pass it explicitly as another --certificate argument:
```console
./Build/lagom/bin/Ladybird --certificate=$PWD/Tests/LibWeb/WPT/wpt/tools/certs/cacert.pem --certificate=$PWD/Build/lagom/cacert.pem
```
This also means that packagers/distro people who want to force us to use a distro-wide cert can do so by adding the --certificate option to the default launch args.
Partially …
> RequestServer+LibTLS: Allow applications to specify multiple root certs

- AK/URLParser.cpp
- Meta/Lagom/Tools/CodeGenerators/GMLCompiler/main.cpp
- Tests/LibCrypto/TestChacha20Poly1305.cpp
- Userland/Libraries/LibCore/Version.cpp
Apparently I missed some places this change could have been made in #21078
> Everywhere: Prefer `_string` when constructing strings from literals

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
...and do string expansion at the call site.
CID-keyed fonts treat the charset as CIDs instead of as SIDs,
so having access to the SIDs in numberic form will be useful
when we implement support for CID-keyed CFF fonts.
> LibPDF: Make CFF::parse_charset() return SIDs 

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/InlinePaintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
In this commit we have optimized the handling of scroll offsets and
clip rectangles to improve performance. Previously, the process
involved multiple full traversals of the paintable tree before each
repaint, which was highly inefficient, especially on pages with a
large number of paintables. The steps were:
1. Traverse the paintable tree to identify all boxes with scrollable or
clipped overflow.
2. Gather the accumulated scroll offset or clip rectangle for each box.
3. Perform another traversal to apply the corresponding scroll offset
and clip rectangle to each paintable.
To address this, we've adopted a new strategy that separates the
assignment of the scroll/clip frame from the refresh of accumulated
scroll offsets and clip rectangles, thus reducing the workload:
1. Post-relayout: …
> LibWeb: Optimize scroll offset and clip state recalculation

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
This reverts commit 52afa936c48f62df8a9b7fec0e78fa75d55407ec.
No longer necessary after #23122 -- turns out things work better when you do them right.
> Revert "LibPDF: Don't over-read in charset formats 1 and 2"

- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditor.h
This is progress toward a destination I didn't get to yet. :sweat_smile: Some highlights:
- Calculate positions less often when painting. Many of them don't change for a row, and others don't change at all.
- Size the offsets column based on the size of the offset text, instead of using 2 hard-coded numbers, neither of which was the actual width of the column. :upside_down_face:
- Respond to the default monospace font changing.
- Get rid of a little kink in one of the column lines.
> HexEditor: Deduplicate repeated coordinate calculations, and fix some bugs in the process

- Userland/Applications/HexEditor/AnnotationsModel.cpp
- Userland/Applications/HexEditor/AnnotationsModel.h
- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.gml
- Userland/Applications/HexEditor/HexEditorWidget.h
Make the panels use DynamicWidgetContainers because those are cool and fancy, and then add a toolbar and context menu to the annotations panel. Also snuck in a tweak to the delete-annotation confirmation dialog so it tells you what you're about to delete.
> HexEditor: Make the panels :sparkles: fancy :sparkles: 

- Kernel/Devices/HID/KeyboardDevice.cpp
This restores Caps Lock functionality, while still ensuring that shortcut keys are remapped correctly.
This fixes a regression introduced in #23058
> Kernel/HID: Set Caps Lock state before doing code point remapping

- Tests/LibWeb/Ref/reference/scroll-using-mousewheel-event-ref.html
- Tests/LibWeb/Ref/scroll-using-mousewheel-event.html
- Userland/Libraries/LibWeb/Internals/Internals.cpp
- Userland/Libraries/LibWeb/Internals/Internals.h
- Userland/Libraries/LibWeb/Internals/Internals.idl
This function allows us to write tests for scrolling scenarios where the events are processed by the EventHandler.
> LibWeb: Add internals.wheel() to simulate mouse wheel events

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
With this change, clicking on an editable element, such as an `input` or `textarea` causes the cursor position to be updated to the current mouse position.
The behavior of the cursor still isn't perfect. It has a tendency to jump around unexpectedly if you drag at all when clicking. Dragging to create a selection also isn't currently working as expected.
Before:
https://github.com/SerenityOS/serenity/assets/2817754/9d60baff-0157-4778-a50a-ce8d37a4e7e5
After:
https://github.com/SerenityOS/serenity/assets/2817754/eb691e49-b690-4316-af89-ada3d5d36e11
> LibWeb: Update the cursor position when an editable element is clicked

- Userland/Libraries/LibLine/Editor.cpp
- Userland/Libraries/LibLine/Editor.h
- Userland/Libraries/LibLine/InternalFunctions.cpp
- Userland/Libraries/LibVT/Terminal.cpp
These are two the low-hanging (as i once thought; they turned out to be
not-so-low-hanging) internal functions that were yet to be implemented in LibLine.
---
*Edit: This is an old commit that has now been updated with new changes and commit message.*
```
The 128 (7 bits) ASCII codes are divided into 4 groups (with 2 upper
most significant bits) of 32 codes (5 least significant bits) each.
The first group (bit pattern: 00x'xxxx) consist of the "non-printable"
characters which are also the "control" characters. These control
characters don't have a dedicated key in keyboards; they are supposed to
be invoked with the "control" key.
Pressing the control key in combination with another character (which is
in one of the other three groups) sets the 2 upper most significant bits
of that …
```
> LibLine+LibVT: Internal functions to erase spaces and to search character. Also ASCII control characters.

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
No behavior change, except that we now dbgln() if we see a PrivDictOperator we don't know about. (I haven't seen this in practice, but I found this useful while debugging things.)
> LibPDF/CFF: Add enum values for remaining PrivDictOperators

- Tests/LibWeb/Layout/expected/grid/repeat-auto-fit-fill-cannot-have-auto.txt
- Tests/LibWeb/Layout/input/grid/repeat-auto-fit-fill-cannot-have-auto.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
> LibWeb: ignore repeat(auto-fit/auto-fill, auto) as it is not allowed

- AK/Array.h
- AK/FloatingPoint.h
- AK/Forward.h
- AK/StdLibExtraDetails.h
- AK/Tuple.h
- AK/TypeList.h
- AK/Types.h
- AK/Variant.h
- Kernel/API/Syscall.h
- Kernel/Arch/aarch64/PageDirectory.h
- Kernel/Arch/aarch64/RegisterState.h
- Kernel/Arch/aarch64/TrapFrame.h
- Kernel/Arch/riscv64/CSR.h
- Kernel/Arch/riscv64/RegisterState.h
- Kernel/Arch/riscv64/SBI.h
- Kernel/Arch/riscv64/TrapFrame.h
- Kernel/Devices/Storage/SD/Commands.h
- Tests/AK/TestArray.cpp
- Tests/AK/TestIndexSequence.cpp
- Userland/Libraries/LibC/arch/aarch64/fenv.cpp
- Userland/Libraries/LibC/arch/riscv64/fenv.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
This is useful if you want an array with an explicit type but still
want its size to be inferred.
---
…and random minor stuff along the way, such as making IndexSequence<> use size_t as it should, which requires not including StdLibExtras.h from Types.h. Went with a hack for that one for now; imho Types.h shouldn't use AK::Details metaprogramming at all. FlatPtr doesn't necessarily have to use Conditional<> and ssize_t could maybe be in its own header or something. But since it's tangential to this PR, not doing this here.
I have a use for this locally (in LibPDF, surprise), but let's keep this PR about AK.
> AK: Add to_array()

- Userland/Games/BrickGame/BrickGame.cpp
We previously never called event.ignore(), so the keydown event for F2 or F11 etc would be consumed by the BrickGame widget instead of bubbling up. Now you can start a new game, or escape fullscreen mode, even if you've paused the game. :^)
> BrickGame: Make action shortcuts work when the game is paused

- Tests/LibWeb/Text/expected/DOM/Document-set-designMode.txt
- Tests/LibWeb/Text/input/DOM/Document-set-designMode.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
Setting this attribute to "on" makes the entire document editable.
Demo:
https://github.com/SerenityOS/serenity/assets/2817754/43a11cd5-9730-4527-b40d-68fe4fa88332
Note: Trying to edit more complex websites doesn't work too well at the moment. Simpler websites like serenityos.org work as expected.
> LibWeb: Implement `document.designMode`

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
This is one of the two top dict entries we need for CID-keyed fonts.
We don't send any CID-keyed font data into the CFF parser yet,
so no behavior change.
> LibPDF/CFF: Add code for fdselect parsing

- Userland/Libraries/LibPDF/Fonts/SimpleFont.cpp
This fixes rendering of commas in 0000941.pdf page 1. The commas use the default width, and without this they show up very large, covering the page.
Also, it's nice that the code now looks like the regular case 4 lines further up.
> LibPDF: Scale default glyph width by font size and x scale

- Kernel/FileSystem/InodeFile.cpp
While investigating #23097 I found an unrelated issue in our `ftruncate` implementation.
> Kernel: Make `ftruncate` change `st_ctime` as per spec

- Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
- Userland/Libraries/LibGfx/TIFFGenerator.py
These three patches make us successfully decode all (non-corrupted) CCITT images from libtiff's test suite.
Yes, you've read that correctly: fax2d.tiff is encoded using CCITT3 1D :upside_down_face:
> LibGfx/TIFF+CCITT: Couple of fixes for CCITT3 1D

- Tests/LibWeb/Text/expected/hit_testing/button.txt
- Tests/LibWeb/Text/input/hit_testing/button.html
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Change 'dom_node_for_event_dispatch' to locate the closest layout node with a DOM node instead of only checking the direct ancestor.
This fixes hit-testing for buttons because they are wrapped into multiple anonymous layout nodes (internally we use flex formatting for them).
> LibWeb: Fix hit-testing for button element

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
- Userland/Libraries/LibWeb/CSS/Properties.json
Keyframes can be given in two separate forms:
- As an array of separate keyframe objects, where the keys of each keyframe represent CSS properties, and their values represents the values that those CSS properties should take, e.x.: `[{ color: 'red', offset: 0.3 }, { color: 'blue', offset: 0.7 }]`
- As a single monolithic keyframe object, where the keys of each keyframe represent CSS properties, and their values are arrays of values, where each index k represents the value of the given property at the k'th frame, e.x.: `{ color: ['red', 'blue'], offset: [0.3, 0.7] }`
This PR adds processing of both forms, and implements get/set_keyframes based on that processing.
Also, I _believe_ I filled out the `animatable` property of `Properties.json` correctly, but I figured it wasn't worth spending …
> LibWeb: Process JS keyframe objects

- Tests/LibPDF/BenchmarkPDF.cpp
- Tests/LibPDF/CMakeLists.txt
- Userland/Libraries/LibPDF/Function.cpp
Previously, we'd loop over the index of the output coordinate,
for example for a CMYK->RGB function, we'd loop over RGB. For
every output index, we'd then sample the function at the CMYK
input point.
Now, we sample at CMYK once and return a span for all outputs,
since they're stored in contiguous memory. And we then loop
over the outputs only to do weighting and mapping to the target
range at the end.
Reduces the runtime of
(cd Tests/LibPDF; \
../../Build/lagom/bin/BenchmarkPDF --benchmark_repetitions 5)
from 235.6±2.3ms to 103.2±3.3ms on my system, and makes
SampledFunction::evaluate() more similar to lerp_nd() in TagTypes.h.
---
In other words, this is now twice as fast.
As far as I know, this isn't in any hot loops; my main motivation is to make it look more like lerp_nd(). I'd like to …
> LibPDF: Reorder loops in SampledFunction::evaluate()

- Userland/Libraries/LibPDF/CommonNames.h
- Userland/Libraries/LibPDF/Filter.cpp
- Userland/Libraries/LibPDF/Filter.h
No behavior change (except for more granular errors – but in practice everything seems to be group 4).
> LibPDF: Add some plumbing for the CCITTFax decode filter

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebDriver/Session.cpp
There's a chance that we try to choose a navigable before a previously
destroyed navigable is fully destroyed and GC'd. Investigating why this
can happen is a separate endeavor, let's just not crash for now.
Make sure to mark the TraversableNavigable as destroyed in destroy_top_level_traversable.
Tolerate invalid page_ids in WebContent's ConnectionFromClient. This prevents crashes when the chrome sends messages to a client just after it's been closed, or when there were already pending messages in the queue.
This brings WPT's infrastructure tests to the following:
```
Ran 148 tests finished in 723.5 seconds.
• 45 ran as expected. 0 tests skipped.
• 14 tests had errors unexpectedly
• 21 tests failed unexpectedly
• 31 tests timed out unexpectedly
• 45 tests had unexpected subtest results …
```
> LibWeb: Don't choose destroyed navigables, and tolerate closed windows in IPC

- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
No behavior change, just more granular "not implemented" diagnostics.
> LibPDF: Separate Type0 CMap errors

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
We now check the type of the layout node at the current mouse position when determining which cursor to display during a mouse move event.
Before:
https://github.com/SerenityOS/serenity/assets/2817754/3eaa886f-cb7b-409c-aa9f-52cb7b606ecf
After:
https://github.com/SerenityOS/serenity/assets/2817754/09a32b65-816f-48f5-bc29-755524be3ec0
> LibWeb: Display an IBeam cursor by default when mousing over a text node

- Kernel/Devices/TTY/TTY.cpp
- Kernel/Devices/TTY/TTY.h
In a TTY's non-canonical mode, data availability can be configured by setting VMIN and VTIME to determine the minimum amount of bytes to read and the timeout between bytes, respectively. Some ports (such as SRB2) set VMIN to 0 which effectively makes reading a TTY such as stdin a non-blocking read. We didn't support this, causing ports to hang as soon as they try to read stdin without any data available.
Add a very duct-tapey implementation for the case where VMIN == 0 by overwriting the TTY's description's blocking status; 3 FIXMEs are included to make sure we clean this up some day.
You can test this behavior by installing the SRB2 port, and running `/usr/local/games/SRB2/srb2` from a Terminal window. The game should hang without this patch, only proceeding with new frames on (keyboard) …
> Kernel/TTY: Support non-blocking reads with termios VMIN == 0

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
These arrays store SIDs ("String IDs"), so give them that type now that we have to_array() and it's easy to do.
> LibPDF: Give CFF built-in encoding and charset arrays an underlying type

- Meta/Lagom/Tools/CodeGenerators/LibGL/GenerateGLAPIWrapper.cpp
- Userland/Libraries/LibGL/GLAPI.json
Adding these stubs gives us full API coverage for the SRB2 port (although it currently still crashes in OpenGL mode).
> LibGL: Add some API stubs

- Kernel/Arch/riscv64/Delay.cpp
This include was missed in 4409b33145.
RISC-V should build again now.
> Kernel/riscv64: Add missing include in Delay.cpp

- Meta/Lagom/Fuzzers/FuzzPAMLoader.cpp
- Meta/Lagom/Fuzzers/FuzzPAMLoader.dict
- Meta/Lagom/Fuzzers/fuzzers.cmake
- Userland/Utilities/test-fuzz.cpp
I've included a dictionary of constants taken from [the PAM format specification](https://netpbm.sourceforge.net/doc/pam.html) to improve coverage.
NB: The above link doesn't mention the CMYK TUPLTYPE. I included it in the dictionary because it's used in one of our test files.
> Fuzzers: Add PAM fuzzer

- Kernel/Bus/VirtIO/Device.cpp
- Kernel/Devices/Storage/ATA/AHCI/Controller.cpp
- Tests/LibGfx/BenchmarkGfxPainter.cpp
- Userland/Applications/Calendar/AddEventWidget.cpp
- Userland/Applications/FileManager/PropertiesWindow.cpp
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/Mail/MailWidget.cpp
- Userland/Applications/TerminalSettings/MainWidget.cpp
- Userland/Demos/ModelGallery/GalleryWidget.cpp
- Userland/DevTools/Profiler/main.cpp
- Userland/Services/RequestServer/ConnectionCache.h
This PR replaces calls to `release_value_but_fixme_should_propagate_errors()` with `TRY()` where it is trivial to do so.
> Everywhere: Propagate errors using `TRY()` where possible

- Tests/LibWeb/Text/expected/close-non-modal-dialog.txt
- Tests/LibWeb/Text/expected/form-method-dialog.txt
- Tests/LibWeb/Text/expected/show-non-modal-dialog.txt
- Tests/LibWeb/Text/input/close-non-modal-dialog.html
- Tests/LibWeb/Text/input/form-method-dialog.html
- Tests/LibWeb/Text/input/show-non-modal-dialog.html
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
This PR fleshes out `HTMLDialogElement::show()` and  `HTMLDialogElement::close()`, which were previously stubbed out. Support for submission of forms with the "dialog" method has also been added.
Note: The parts of these methods I have left unimplemented deal with non-modal dialogs, which we don't yet support.
Demo with this test page:
```html
<body>
<dialog id="test-dialog" open>
<form method="dialog">
<button>Close</button>
</form>
</dialog>
<button id="show-button" onClick="show()" hidden>Show</button>
</body>
<script>
const dialogElement = document.getElementById("test-dialog");
const showButton = document.getElementById("show-button");
dialogElement.addEventListener("close", (event) => {
showButton.hidden = false;
});
function show() {
dialogElement.show(); …
```
> LibWeb: Add support for opening and closing non-modal dialog elements

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
- Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
- Userland/Libraries/LibPDF/Fonts/Type1FontProgram.h
Almost there! But no behavior change yet, since we don't pass CID-keyed CFF data into the CFF parser yet.
The diff isn't as big as it looks: The first commit moves some code around, and that looks like a lot of movement, but it's just extracting existing code unchanged to a new function. The rest is small.
> LibPDF/CFF: Yet more CID-keyed fonts scaffolding

- Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
An SDL2 application is allowed to show a message box before the video subsystem is initialized. This change makes sure GUI::Application is initialized.
An example of this is SRB2: the process forks itself to let the child process install itself as the signal handler and deal with errors. This child process could try to show a message box long after the video subsystem was initialized, but since it is a forked process there is no static state for GUI::Application or the connection to the window server and the process would crash because of a null dereference.
| Before |
|---|
| ![crashycrashy](https://github.com/SerenityOS/serenity/assets/3210731/8cbd0942-e53f-4bef-ad13-32d3f03f419f) |
| After |
|---|
| ![crashy](https://github.com/SerenityOS/serenity/assets/3210731/a6069a0e-7e29-4e9b-8f6f- …
> Ports/SDL2: Support ShowMessageBox before VideoInit

- Tests/LibWeb/Text/expected/document-scrollingElement-quirks-mode.txt
- Tests/LibWeb/Text/expected/document-scrollingElement.txt
- Tests/LibWeb/Text/input/document-scrollingElement-quirks-mode.html
- Tests/LibWeb/Text/input/document-scrollingElement.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
This returns a reference to the element that scrolls the document. In standards mode it is equivalent to `document.documentElement`.
This property is used by [a number of WPT tests](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt+document.scrollingElement&type=code), so this should help us to run more of those tests.
> LibWeb: Implement `document.scrollingElement`

- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
- Userland/Libraries/LibGfx/Font/ScaledFont.h
- Userland/Libraries/LibGfx/Font/VectorFont.h
Makes this code look like the corresponding code in the ScaledFont ctor.
Similar to the last commit on https://github.com/SerenityOS/serenity/pull/20084.
> LibGfx/OpenType: Replace a magic number with a calculation

- AK/GenericLexer.cpp
- AK/GenericLexer.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/Lexer.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/SpecParser.h
- Userland/Libraries/LibIDL/IDLParser.cpp
- Userland/Libraries/LibIDL/IDLParser.h
- Userland/Libraries/LibIDL/Types.h
- Userland/Libraries/LibXML/DOM/Node.h
- Userland/Libraries/LibXML/Parser/Parser.cpp
- Userland/Libraries/LibXML/Parser/Parser.h
Duplicates can show up when copy-pasting IDL snippets into existing IDL
files, and the resulting error is extremely useless and misleading.
This commit makes it so the parser catches these cases, and emits a more
helpful error like "Overload set 'instantiate' contains multiple
identical declarations".
> LibIDL: Emit an error when two decls of the same function are present

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
Together with the already-merged https://github.com/SerenityOS/serenity/pull/23122, https://github.com/SerenityOS/serenity/pull/23128, https://github.com/SerenityOS/serenity/pull/23135, https://github.com/SerenityOS/serenity/pull/23136, https://github.com/SerenityOS/serenity/pull/23162,
and https://github.com/SerenityOS/serenity/pull/23167, https://github.com/SerenityOS/serenity/pull/23179, https://github.com/SerenityOS/serenity/pull/23190, https://github.com/SerenityOS/serenity/pull/23194 this adds initial support for
rendering some CFF-based Type0 fonts :^)
There's a long list of things that still need improving after this:
* A small number of CFF programs contain the charstring command 0,
which is invalid. Currently, this makes us reject the whole font.
* …
> LibPDF: Initial support for drawing CFF-based Type0 fonts

- Tests/LibWeb/Text/expected/DOM/Document-named-properties.txt
- Tests/LibWeb/Text/input/DOM/Document-named-properties.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/Element.cpp
We now cache potentially named elements on the Document when elements are inserted and removed. This allows us to do lookup of what names are supported much faster than if we had to iterate the tree every time.
This first cut doesn't implement the rules for 'exposed' object and embed elements.
Fixes #22232
> LibWeb: Implement Document named properties with light caching

- Tests/LibWeb/Text/expected/form-method-dialog.txt
- Tests/LibWeb/Text/expected/form-requestSubmit.txt
- Tests/LibWeb/Text/input/form-method-dialog.html
- Tests/LibWeb/Text/input/form-requestSubmit.html
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl
This PR implements the `HTMLFormElement.requestSubmit()` method, which can be used to programatically submit a form using a specific submit button.
My motivation for adding this is that I wanted to use it in a test I had previously written; I've taken the opportunity to update that test as part of this PR.
This method also appears to be used by [some WPT tests](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt%20requestSubmit&type=code).
> LibWeb: Implement `HTMLFormElement.requestSubmit()`

- Tests/LibWeb/Text/expected/Editing/execCommand-is-a-noop.txt
- Tests/LibWeb/Text/input/Editing/execCommand-is-a-noop.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
Per the specification, it's ok if we say that nothing is supported.
It's not ok if we say something is supported but do nothing, apparently.
First step towards #23176
> LibWeb: Stub out all the functions from the execCommand spec

- Userland/Libraries/LibGfx/CMakeLists.txt
CMake will cache the result here, so there's no need to look for both.
> Meta: Don't search for both Python and Python3 in CMake

- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Font.h
- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
From a LibPDF point of view, this is a _huge_ progression: Before this, 303 of my 1000 test files rendered without any diagnostics (which doesn't mean that they look 100% correct, but they probably look kinda decent). After this, 652 of my 1000 test files render without any diagnostics.
Disclaimers, similar to what's on #23202 (and most of the
prerequisites mentioned there are needed for this too):
* Only supports the `Identity-H` type0 cmap at the moment
* Doesn't support vertical text yet
* Only supports the `Identity` CIDToGIDMap at the moment
(this one is a truetype-only thing)
In other words, with this it's (barely, but still) more likely than not that a random PDF of the web will show up fine.
From a LibGfx point of view, this adds a way to provide an external opentype cmap, since …
> LibPDF+LibGfx: Add initial support for truetype-based type0 fonts

- Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf says "The behavior of undefined operators is unspecified." but https://learn.microsoft.com/en-us/typography/opentype/spec/cff2 says "When an unrecognized operator is encountered, it is ignored and the stack is cleared."
Some type 0 CIDFontType0C fonts (i.e. CID-keyed non-OpenType CFF fonts) depend on the latter, even though they're governed by the former spec.
Fixes rendering of text in 0000521.pdf (e.g. page 10 or 5). The font there has a bunch of 0 opcodes for some reason.
---
The fonts in the other documents shown below also only use opcode 0. But the newer spec says to ignore them all, so that's what we do now (with a log message).
> LibPDF: Ignore unknown CFF operators

- Tests/LibWeb/Text/expected/input-value.txt
- Tests/LibWeb/Text/input/input-value.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
The setter was missing an implementation for the default and default/on value attribute modes. This patch adds a method to get the current value attribute mode, and implements the value setter and getter based on that mode according to the spec.
Fixes #23234
> LibWeb: Fully implement the HTMLInputElement `value` setter and getter

- Userland/Games/2048/BoardView.cpp
Previously, during the start of the game BoardView component tried to get the font from the database passing empty string as a parameter. It caused a debug message informing user that the lookup failed.
> 2048: Ensure that correct font is requested

- Userland/Libraries/LibWeb/CSS/Default.css
This prevents an IBeam cursor being shown when these elements are moused over.
Fixes: #23191
> LibWeb: Set `cursor: default` for button and select elements

- Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Before:
```
Benchmark 1: ./Meta/Lagom/BuildLagom/bin/image TIFF/ccitt.tiff --no-output
Time (mean ± σ):      58.6 ms ±  13.4 ms    [User: 55.9 ms, System: 2.9 ms]
Range (min … max):    43.2 ms …  78.2 ms    40 runs
Benchmark 1: ./Meta/Lagom/BuildLagom/bin/image TIFF/deflate.tiff --no-output
Time (mean ± σ):      51.0 ms ±  14.4 ms    [User: 46.4 ms, System: 4.5 ms]
Range (min … max):    37.8 ms …  75.7 ms    50 runs
Benchmark 1: ../../Meta/Lagom/BuildLagom/bin/TestImageDecoder
Time (mean ± σ):      1.163 s ±  0.039 s    [User: 1.101 s, System: 0.062 s]
Range (min … max):    1.127 s …  1.259 s    10 runs
```
After:
```
Benchmark 1: ./Meta/Lagom/BuildLagom/bin/image TIFF/ccitt.tiff --no-output
Time (mean ± σ):       9.1 ms ±   3.6 ms    [User: 6.2 ms, System: 2.8 ms]
Range (min … max): …
```
> LibGfx/TIFF: Reduce execution time by 50% to 70%

- Userland/Utilities/tail.cpp
This commit adds the possibility to skip the first NUM lines of a file by calling `tail -n +NUM filename`.
> tail: Support skip from start mode

- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/xxd.cpp
Initial implementation of xxd. Some things are missing such as:
- patching a hexdump into a binary
- colorized output
- seeking relative to current stdin offset
- EBCDIC encoding (left this out since I don't think it is needed)
~~Pr depends on #22754~~
> Utilities: Add xxd utility

- Userland/Games/FlappyBug/Game.cpp
As the menus show that ALT-F4 quit and F1 brings up help, we should make the application do that instead of just undocumented ESC
> FlappyBug: Allow shortcuts for quitting and help

- Kernel/Arch/riscv64/MMU.cpp
- Kernel/Arch/riscv64/boot.S
- Kernel/Arch/riscv64/linker.ld
This PR also makes kernel backtraces appear before `init_stage2`, as we check if the frame pointer is below `kernel_mapping_base` in `dump_backtrace_impl`.
> Kernel/riscv64: Don't use the memory before .text as the initial stack

- Userland/Libraries/LibGfx/ICC/Profile.cpp
- Userland/Libraries/LibGfx/ICC/Profile.h
- Userland/Utilities/pdf.cpp
Our current CLUT code is pretty slow. A one-element cache can make
it quite a bit faster for images that have long runs of a single
color, such as illustrations.
It also seems to help with photos some (in `0000711.pdf` page 1) --
I suppose even them have enough repeating pixels for it to be worth
it.
Some numbers, with `pdf --render-bench`:
`0000711.pdf --page 1` (high-res photo)
before: 2.9s
after: 2.43s
`0000277.pdf --page 19` (my nemesis PDF, large-ish illustration)
before: 2.17s
after: 0.58s (!)
`0000502.pdf --page 2` (wat hoe dat)
before: 0.66s
after: 0.27s
`0000521.pdf --page 10 ` (japanese)
before: 0.52s
after: 0.29s
`0000364.pdf --page 1` (4 min test case)
before: 0.48s
after: 0.19s
Thanks to that last one, reduces the time for
`time Meta/test_pdf.py ~/Downloads/0000` from 4m22s …
> LibGfx/ICC: Add a one-element cache for CLUT conversions

- Tests/LibWeb/Text/expected/DOM/Document-createCDATASection.txt
- Tests/LibWeb/Text/input/DOM/Document-createCDATASection.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOMParsing/XMLSerializer.cpp
- Userland/Libraries/LibWeb/HTML/DOMParser.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.h
This PR adds `document.createCDATASection()` and includes some fixes to XML document serialization and deserialization, which were necessary to get the `createCDATASection` test to pass.
This method is used quite extensively by the WPT test harmess, so having it should allow us to run quite a few more WPT tests.
Before:
After:
> LibWeb: Implement `document.createCDATASection()`

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/Animations/Animatable.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Element.idl
There may be a bit of code duplication between `StyleComputer` and the Web Animations stuff for a bit, but that'll get resolved eventually.
Independent of #23184, but there may be merge conflicts (please merge that one first!).
Word towards #21570. Note that this PR doesn't close that issue yet because while you can now call `.animate()` on an element and get back an animation object, it will not affect how the element is rendered at all.
Also advances (closes?) #22014
> LibWeb: Implement Element::animate; Generate keyframes for Web Animations

- Meta/run.py
With 1GiB, we hit OOM loading GitHub in the browser. Increase the RAM size to support normal use.
> Meta: Increase default VM RAM size to 2GiB

- Tests/LibWeb/Text/expected/DOM/element-scroll-height.txt
- Tests/LibWeb/Text/expected/DOM/element-scroll-width.txt
- Tests/LibWeb/Text/input/DOM/element-scroll-height.html
- Tests/LibWeb/Text/input/DOM/element-scroll-width.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
Spec says that this function has to return "width/height of the element
scrolling area" which is width/height of "scrolling overflow rect" in our model.
> LibWeb: Return overflow rect width(height) from Element::scroll_width(height)

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/Animation.h
- Userland/Libraries/LibWeb/Animations/Animation.idl
This can apply to optional, nullable parameters of platform types. This will cause the generator to generate the type as `Optional<JS::GCPtr<T>>` rather than `JS::GCPtr<T>`, allowing the implementation to differentiate between the case where the argument was not passed, and the case where null or undefined was passed.
Needing to differentiate these two cases is quite niche, hence why it is an opt-in behavior.
Closes #23220
> LibWeb: Allow interfaces to differentiate between a null argument and no argument

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
We use `i - 1` to index these arrays, so that's what we should use
for the bounds check as well.
> LibPDF/CFF: Fix off-by-one when reading internal encoding

- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
This adapts our implementation to the editorial change in the temporal proposal: https://github.com/tc39/proposal-temporal/commit/737baf2d
The changes to CalendarMethodsRecordLookup had already been implemented, but we had followed the typo in the spec for CalendarMethodsRecordCall. The issue in CalendarMethodsRecordCall hasn't surfaced yet, as the AOs using Calendar Methods Record are currently not passing through a String to represent a Calendar builtin.
No change to test-262.
> LibJS: Fix copy paste errors in Temporal's Calendar Methods Record

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
This is required by the CFF spec, and is consistent with what we do for the encoding 24 lines down.
As far as I can tell, nothing in `Type1FontProgram::rasterize_glyph()` or in Type1Font.cpp implements the "If an encoding maps to a character name that does not exist in the Type 1 font pro- gram, the .notdef glyph is substituted." line from the PDF 1.7 spec (in 5.5.5 Character Encoding, Encodings for Type 1 Fonts) yet, so this does yet have an effect.
> LibPDF: Give CFF Glyph 0 the name .notdef

- Base/res/ladybird/inspector.js
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Layout/expected/document-write-incomplete-tag.txt
- Tests/LibWeb/Layout/input/document-write-incomplete-tag.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.h
- Userland/Libraries/LibWeb/Internals/Inspector.cpp
- Userland/Libraries/LibWeb/Internals/Inspector.h
- Userland/Libraries/LibWeb/Internals/Inspector.idl
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/InspectorClient.cpp
- Userland/Libraries/LibWebView/InspectorClient.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
There were 2 bugs with LibWeb and the Inspector on https://world-of-dungeons.net/:
1. `document.write` was not able to handle writing partial HTML tags. Doing so would ultimately generate invalid HTML.
2. The Inspector was unable to handle that HTML, as the HTML generated for the Inspector would itself become invalid.
This PR fixes (2) then (1). The former manifested itself in a couple places, but the end result here also nicely reduces the size of generated HTML (for example, the Inspector HTML on https://github.com/SerenityOS/serenity reduces by about 18%).
Fixes #23241
> LibWeb+LibWebView: Remove invalid HTML from Inspector, and allow `document.write` to generate invalid HTML

- Userland/Libraries/LibJS/Runtime/VM.h
128 KiB seems to not be enough for CI.
> LibJS: Further increase the free stack limit to 256 KiB

- Tests/LibWeb/Layout/expected/zero-size-replaced-box-with-aspect-ratio.txt
- Tests/LibWeb/Layout/input/zero-size-replaced-box-with-aspect-ratio.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Fixes crashes that occur in Discord after clicking on a direct messages conversation.
> LibWeb: Fix division by zero in `solve_replaced_size_constraint()`

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
This is what caused stack usage to increase so much with the new BC.
Revert it for now so we can restore our old stack limit.
> LibJS: Remove FLATTEN attribute from Interpreter::run_bytecode

- Tests/LibWeb/Text/input/clipboard.html
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/Internals/Internals.cpp
- Userland/Libraries/LibWeb/Internals/Internals.h
- Userland/Libraries/LibWeb/Internals/Internals.idl
We have a 5 second timeout between a user-activated event occurring and an activation-gated API being invoked in order for that API to succeed. This is quite fine in normal circumstances, but the machines used in CI often exceed that limit (we see upwards of 10 seconds passing between generating the user-activated event and the API call running).
So instead of generating a user-activated event, add a hook to allow tests to bypass the very next activation check.
> LibWeb: Allow bypassing transient activation checks for tests

- Tests/LibWeb/Layout/expected/grid/container-max-width-max-content.txt
- Tests/LibWeb/Layout/input/grid/container-max-width-max-content.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
With this change "max-width: max-content" is treated as "none" when the available width is also "max-content". This fix prevents a stack overflow in the grid track size maximization algorithm by avoiding recursive calls to calculate_max_width() when determining the maximum grid container size.
> LibWeb: Fix infinite recursion when grid has "max-width: max-content"

- Tests/LibWeb/WPT/metadata.txt
- Userland/Libraries/LibWeb/WebDriver/Screenshot.cpp
The default canvas size is 300x150 pixels. If the element or document
we are trying to screenshot for the WebDriver is not at least that size,
then we will create a canvas that is wider or taller than the actual
element we are painting, resulting in a bunch of transparent pixels
falling off the end.
This fixes 14 WPT css/CSS2/floats tests that we run in CI, and
presumably a ton of other reftests in the WPT test suite.
> LibWeb: Set size of canvas used to take WebDriver screenshots explicitly

- Tests/LibWeb/Text/expected/abortsignal-abort.txt
- Tests/LibWeb/Text/input/abortsignal-abort.html
- Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
- Userland/Libraries/LibWeb/DOM/AbortSignal.h
- Userland/Libraries/LibWeb/DOM/AbortSignal.idl
This returns an AbortSignal that is already set as aborted.
Progress towards #13355
> LibWeb: Implement `AbortSignal.abort()`

- Userland/Libraries/LibGfx/ICC/BinaryWriter.cpp
- Userland/Libraries/LibGfx/ICC/Profile.cpp
- Userland/Libraries/LibGfx/ICC/Profile.h
- Userland/Libraries/LibGfx/ICC/WellKnownProfiles.cpp
- Userland/Libraries/LibPDF/ColorSpace.cpp
- Userland/Utilities/icc.cpp
Before, we used to reject profiles where the creation datetime was
invalid per spec. But invalid dates happen in practice (most commonly,
all fields set to 0). They don't affect profile conversion at all,
so be lenient about this, in exchange for slightly more wordy code
in the places that want to show the creation datetime.
Fixes a crash rendering page 2 of
https://fredrikbk.com/publications/copy-and-patch.pdf
---
…and two more minor ICC-related tweaks.
> LibGfx/ICC+icc: Be lenient about invalid profile creation datetimes

- Ladybird/Qt/StringUtils.cpp
- Ladybird/Qt/Tab.cpp
This regressed in c75bd4ed.
QUrl does some unwanted ASCII->Unicode conversion, so let's take the QString which is already in the format we want.
This PR also contains a fix for some potential undefined behavior when the byte array provided by Qt is not followed by a null terminator.
> Ladybird/QT: Avoid round-tripping through QUrl to make Unicode URLs work again

- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/Window.idl
Adding these prevents pages that were built for popup windows from crashing.
> LibWeb: Add various window transformation methods

- Tests/LibWeb/Layout/expected/flex-item-with-cyclic-percentage-height.txt
- Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
- Tests/LibWeb/Layout/expected/flex/percentage-flex-basis-with-indefinite-reference-value.txt
- Tests/LibWeb/Layout/expected/flex/percentage-flex-item-height-with-indefinite-containing-block-height.txt
- Tests/LibWeb/Layout/input/flex/percentage-flex-basis-with-indefinite-reference-value.html
- Tests/LibWeb/Layout/input/flex/percentage-flex-item-height-with-indefinite-containing-block-height.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Height definiteness is now preserved as intended by CSS-SIZING-3
(assuming I've understood it correctly) and not implicitly granted by
layout algorithms when they assign height.
For the specific special/magical cases where some sizes become definite
during layout, the preceding commits have made them explicit in code.
This fixes a number of flex layout issues where we were previously
resolving percentage values against post-layout flex container heights,
but other browsers don't.
Note that `set_content_width()` still behaves the wrong way, and fixing it will be quite a task. :sweat_smile:
> LibWeb: Don't mark heights as definite in set_content_height()

- Kernel/Arch/aarch64/Interrupts.cpp
- Kernel/Bus/USB/UHCI/UHCIController.cpp
- Kernel/Bus/USB/UHCI/UHCIRootHub.cpp
- Kernel/Bus/USB/USBHub.cpp
- Kernel/Bus/USB/USBManagement.cpp
- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
- Userland/Libraries/LibDebug/Dwarf/AddressRanges.cpp
- Userland/Libraries/LibDeviceTree/Validation.cpp
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.cpp
- Userland/Utilities/icc.cpp
- Userland/Utilities/lsusb.cpp
- Userland/Utilities/strace.cpp
- Userland/Utilities/xxd.cpp
The former automatically adapts the prefix to binary and octal output, and is what we already use in the majority of cases.
Patch generated by:
rg -l '0x\{' | xargs sed -i '' -e 's/0x{:/{:#/'
I ran it 4 times (until it stopped changing things) since each invocation only converted one instance per line.
> Everywhere: Prefer {:#x} over 0x{:x} in format strings

- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Font.h
It turns out that hmtx and OS/2 table values _are_ used when rendering OpenType for PDFs: hmtx is used for the left-side bearing value (which is read in `Painter::draw_glyph()`), and OS/2 is used for the ascender, which Type0's CIDFontType2::draw_glyph() and TrueTypeFont::draw_glyph() read.
So instead of not trying to read these tables, instead try to read them but tolerate them failing to read and ignore them then.
Follow-up to #23276.
(I've seen weird glyph positioning from not reading the hmtx table. I haven't seen any problems caused by not reading the OS/2 table yet, but since the PDF code does use the ascender value, let's read that too.)
> LibGfx: Tweak semantics of some SkipTables enum values

- Userland/Libraries/LibWeb/Animations/Animatable.cpp
- Userland/Libraries/LibWeb/Animations/Animatable.h
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/Animation.h
- Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
- Userland/Libraries/LibWeb/Animations/AnimationEffect.h
- Userland/Libraries/LibWeb/Animations/AnimationTimeline.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
- Userland/Libraries/LibWeb/CSS/CSSAnimation.cpp
- Userland/Libraries/LibWeb/CSS/CSSAnimation.h
- Userland/Libraries/LibWeb/HTML/EventNames.h
In order to do so, we need to define animation composite ordering as well as some other misc helper methods.
Work towards #21570
> LibWeb: Implement Animatable::get_animations()

- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
Ceiling width or height of a chrome viewport (this function is only used when a chrome notifies LibWeb about a new viewport size) is never correct. If we do that, PageClient::page_did_layout will set content size to be 1 larger than an actual physical width or height respectively (it always ceils) and thus a spurious scrollbar will appear.
This prevents occasional scrollbar flickering in Ladybird/Qt on Wayland with fractional scaling enabled on compositors supporting wp-fractional-scale-v1.
This in a way "fixes up" #22957.
> LibWeb: Properly round CSSPixels values in device_to_css_rect

- Ports/milkytracker/package.sh
This was added for native apps in 4c02133ba857c92531e20bf693dfc6482756cf98, which caused a duplication of categories in this port.
> Ports: Add app category hotkey for Milkytracker

- Userland/Libraries/LibC/arch/riscv64/setjmp.S
- Userland/Libraries/LibC/setjmp.h
I totally forgot to save floating point registers in setjmp().
We only support the double-precision hardware floating-point ABI, so `fsd` and `fld` are used.
> LibC: Save callee-saved floating-point registers in setjmp for riscv64

- Userland/Applications/PixelPaint/ImageEditor.cpp
- Userland/Applications/PixelPaint/ImageEditor.h
- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Libraries/LibGUI/Application.cpp
Previously, we were attempting to add an empty string to the most recently open files list when no file was saved.
`Application::set_most_recently_open_file()` now asserts that the path you are trying to set isn't empty. Doing this doesn't make sense and trying to set an empty path causes a crash that isn't immediately obvious. Better to fail early in this case.
NB: #23131 stops the above-mentioned crash from happening.
Fixes #23130
> PixelPaint: Don't crash when cancel is pressed when saving a file

- Userland/Libraries/LibTest/TestMain.cpp
- Userland/Utilities/run-tests.cpp
```
Before, TEST_MAIN used to return the return value of TestSuite::main()
function (which returns the number of test cases that did not pass, so
it can be >=256) directly.
The run-tests utility determines the success / failure of a test suite
binary by examining its (or i.e. TEST_MAIN's) exit status.
But as exit status values are supposed to be between 0 and 255, values
>=256 will get wrapped around (modulo 256), converting a return value of
256 to 0.
So, in a rare case where exactly 256 test cases are failing in your test
suite, run-tests utility will display that the test suite passed without
any failures.
Now, TEST_MAIN just returns 0 if all of the test cases pass and returns
1 otherwise.
```
> LibTest: Return 0 if all test cases pass and 1 otherwise from TEST_MAIN

- Userland/Applications/HexEditor/FindDialog.cpp
- Userland/Applications/HexEditor/FindDialog.h
This PR ensures that errors are propagated from the HexEditor find dialog.
I also included a commit to change the `OptionId` enum to match our current code style.
> HexEditor: Prefer ErrorOr to Result in FindDialog

- Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Heap/ConservativeVector.cpp
- Userland/Libraries/LibJS/Heap/ConservativeVector.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
- Userland/Libraries/LibJS/Heap/HeapRoot.h
Fixes an issue caught by test-js -g + UBSAN.
The problem here was that `Vector<T>` doesn't protect fields of `T` from the GC.
We address this by introducing a new `ConservativeVector<T>` that is visible
to the GC conservative root gathering phase.
This works very similarly to `MarkedVector<T>`, but instead of expecting
`T` to be `Value` or a GC-allocated pointer type, `T` can be anything.
Every pointer-sized value in the vector's storage will be checked during
conservative root scanning.
In other words, this allows you to put something like this in a
`ConservativeVector<Foo>` and both `some_value` and `some_object`
will be protected from GC:
```cpp
struct Foo {
i64 number;
Value some_value;
GCPtr<Object> some_object;
};
```
> LibJS: Protect private elements from GC during class construction

- Kernel/Net/LocalSocket.cpp
- Tests/Kernel/TestTCPSocket.cpp
> Kernel: don't panic when LocalSocket is already bound

- Userland/Libraries/LibGUI/Application.cpp
Since it's possible to have less recently opened files than max_recently_open_files(), which causes us to crash when we try to access new_recent_files_list where index >= size.
Found while looking for a fix to #23130.
> LibGUI/Application:  Resize recent files list to max open file size

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
`EventHandler::handle_keyup()` and `EventHandler::handle_keydown()` return true if the event has been handled and false otherwise. This is the opposite behavior to `EventHandler::fire_keyboard_event()`. This change inverts the return value from `fire_keyboard_event` in these methods, allowing shortcut keys to be propagated to the Serenity Browser UI as expected.
Fixes #23159
> LibWeb: Invert return value from EventHandler key event handling methods

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Tests/builtins/Array/array-basic.js
- Userland/Libraries/LibJS/Tests/object-basic.js
When compiling code like this:
x = { foo: x }
We don't want to put a new `JS::Object` in `x` until *after* we've evaluated `x` for the `foo` field.
This fixes an issue when loading https://puter.com/ :^)
> LibJS/Bytecode: Don't clobber dst when assigning from object expression

- Base/res/html/misc/web-animations.html
- Base/res/html/misc/welcome.html
- Userland/Libraries/LibWeb/Animations/Animatable.h
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
This PR will fully transition `StyleComputer` to use the new Web Animations framework, meaning that calls to `Element.animate` will now produce a visual result. I tried to break this down into as many commits as possible, but at the end of the day it's a large refactor that requires a large commit.
Now that we rely on Web Animations, the `StyleComputer` has far less work to do, since we no longer need things like the fill-forward state and a container for initial styles. Also note that all of the timing function stuff was copied out in 66bd75f2b978ecc870d1b75e3ad69106bc7c9a8e. 
This is a draft for now, since I want to add a little demo to `/res/html` (or tests, but I'm not sure how well that'll work), and I'd also like to see if I can find some more websites to try. I am not confident …
> LibWeb: Transition StyleComputer to Web Animations

- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/Animation.h
- Userland/Libraries/LibWeb/Animations/Animation.idl
This PR omits `commitStyles()`, as it is quite a bit more complicated (and probably niche) than the other methods.
Independent of (and won't conflict with) #23311
> LibWeb: Implement almost all of the remaining Animation prototype methods

- Meta/run.py
This unbreaks `serenity.sh run aarch64`.
b2104361cf set the default RAM size to 2GiB, but the "raspi3b" QEMU machine only accepts 1GiB.
> Meta: Set the RAM size to 1G for aarch64 in run.py 

- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
Resolves a performance regression from
8ba18dfd404543290774f21ee3ed6c802e3371cd, where moving paint scheduling to `EventLoop::process()` led to unnecessary repaints.
This update introduces a flag to trigger repaints only when necessary, addressing the issue where repaints previously occurred with each event loop process, irrespective of actual changes.
> LibWeb: Paint page only if something that requires repaint happened

- Tests/LibWeb/Layout/expected/calc-negative-border-width.txt
- Tests/LibWeb/Layout/input/calc-negative-border-width.html
- Userland/Libraries/LibWeb/Layout/Node.cpp
Previously, a calculated CSS border-width property with a resolved value of less than zero pixels would cause a crash.
> LibWeb: Clamp calculated border width values to zero

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/css/CSSStyleSheet-addRule.txt
- Tests/LibWeb/Text/expected/css/CSSStyleSheet-constructor.txt
- Tests/LibWeb/Text/expected/css/CSSStyleSheet-removeRule.txt
- Tests/LibWeb/Text/expected/css/CSSStyleSheet-replace.txt
- Tests/LibWeb/Text/expected/css/CSSStyleSheet-replaceSync.txt
- Tests/LibWeb/Text/expected/css/insert-import-rule-into-constructed-stylesheet.txt
- Tests/LibWeb/Text/input/css/CSSStyleSheet-addRule.html
- Tests/LibWeb/Text/input/css/CSSStyleSheet-constructor.html
- Tests/LibWeb/Text/input/css/CSSStyleSheet-removeRule.html
- Tests/LibWeb/Text/input/css/CSSStyleSheet-replace.html
- Tests/LibWeb/Text/input/css/CSSStyleSheet-replaceSync.html
- Tests/LibWeb/Text/input/css/insert-import-rule-into-constructed-stylesheet.html
- Userland/Libraries/LibWeb/CSS/CSSRuleList.h
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.idl
- Userland/Libraries/LibWeb/CSS/MediaList.h
- Userland/Libraries/LibWeb/Forward.h
This PR adds the following methods and attributes to CSSStyleSheet:
* [`ownerRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/ownerRule)
* [`rules`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/rules)
* [`CSSStyleSheet()` constructor](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/CSSStyleSheet)
* [`replace()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replace)
* [`replaceSync()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/replaceSync)
* [`addRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/addRule)
I've also included some fixes in this PR to bring our implementation closer to the CSSOM specification. See the individual commits for details.
These changes increase the …
> LibWeb: Add missing CSSStylesheet methods

- Userland/Libraries/LibELF/Arch/riscv64/plt_trampoline.S
- Userland/Libraries/LibELF/DynamicLoader.cpp
This will allow us to run binaries linked without `-z now` (e.g. libgcc_s.so) on riscv64.
> LibELF: Add riscv64 PLT trampoline

- Kernel/API/FileSystem/FATStructures.h
- Kernel/FileSystem/FATFS/Definitions.h
- Meta/CMake/lagom_compile_options.cmake
- Meta/Lagom/CMakeLists.txt
- Userland/Applications/SoundPlayer/Playlist.cpp
- Userland/Libraries/LibFileSystem/FileSystem.cpp
- Userland/Libraries/LibFileSystem/FileSystem.h
- Userland/Services/WebServer/Client.cpp
- Userland/Services/WebServer/Client.h
- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/mkfs.fat.cpp
This adds a basic `mkfs.fat` utility, which can format FAT12, FAT16 and FAT32 partitions.
This does have a few limitations, namely in that FAT12 formatting is limited to a set known floppy disk sizes, and we can only generate 512-byte sectors.
While this does work in Serenity, it isn't particularly useful there yet, since we don't have loopback mounts or write support in FATFS.
This can be tested in lagom like so:
```
truncate -s 128M fat32.img
./Meta/serenity.sh run lagom mkfs.fat -F 32 $PWD/fat32.img
truncate -s 128M fat16.img
./Meta/serenity.sh run lagom mkfs.fat -F 16 $PWD/fat16.img
truncate -s 2880K fat12.img
./Meta/serenity.sh run lagom mkfs.fat -F 12 $PWD/fat12.img
```
To test out the integrated dummy boot code, you can simply use QEMU:
```
qemu-system-x86_64 fat32.img
```
> Utilities: Add `mkfs.fat`

- Userland/Libraries/LibELF/Arch/GenericDynamicRelocationType.h
- Userland/Libraries/LibELF/Arch/aarch64/GenericDynamicRelocationType.h
- Userland/Libraries/LibELF/Arch/riscv64/GenericDynamicRelocationType.h
- Userland/Libraries/LibELF/Arch/x86_64/GenericDynamicRelocationType.h
- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicObject.h
- Userland/Libraries/LibELF/ELFABI.h
- Userland/Libraries/LibELF/Relocation.cpp
- Userland/Utilities/readelf.cpp
This PR refactors how we handle dynamic relocations so we can support RISC-V relocations.
`GenericDyanmicRelocationType` is quite a long name, but should hopefully make its purpose of abstracting arch-specific enum values clearer.
> LibELF+readelf: Add support for RISC-V dynamic relocations

- Meta/serenity.sh
`Meta/serenity.sh gdb` will open `tmux` with 2 windows for GDB and emulator's logs. Once debugging is finished it will use `tmux kill-session` command for the current session.
The problem is that if there already is a tmux session it will be closed once `serenity.sh gdb` finishes. This happens due to `trap kill_tmux_session EXIT` is setup twice (for both windows/shells), but `trap` invokes the handler after the shell is exited, so it will kill current tmux session after GDB's shell or emulator's is exited and then, since another shell is also exited `trap` will invoke the handler again, but now for previously opened tmux session.
This PR tries to prevent such a behavior in the following way: `trap` handlers are still setup twice, but the only one of them is able to kill current tmux …
> Meta: Prevent "serenity.sh gdb" to close other tmux sessions

- Userland/Applications/Browser/BrowserWindow.cpp
Before shortcuts like ALT-F4, etc did not work. This makes the window ignore keydown events. In the future this may be altered to allow for custom shortcuts from within ladybird?
> Browser: Allow system shortcuts to function

- Kernel/Bus/PCI/BarMapping.h
- Kernel/Devices/Storage/ATA/AHCI/Definitions.h
This PR fixes a panic when an AHCI controller has a smaller BAR space size than the original HBA struct without the flexible array member.
I also added some `AssertSize`s to all the AHCI structs while fixing this bug.
> Kernel/Storage: Make AHCI::HBA::port_regs a flexible array member

- Kernel/Security/Random.cpp
Better entropy will require us to parse the riscv,isa devicetree property and then use the Zkr extension, if present.
This fallback code is the same as the aarch64 fallback.
> Kernel/riscv64: Use TimeManagement as an entropy source for now

- Kernel/Arch/riscv64/CSR.h
- Kernel/Arch/riscv64/FPUState.h
- Kernel/Arch/riscv64/Processor.cpp
- Kernel/Arch/riscv64/trap_handler.S
I originally wanted to refactor TLS before submitting this PR.
We need to refactor TLS, as we currently expect that every architecture has a thread pointer register for each privilege mode.
I'm going to delay RISC-V TLS until I have the energy to finish refactoring our TLS handling (the only major missing thing is freeing TLS memory after a thread exits).
A lot of this code is quite similar to aarch64.
This PR only adds support for context switching of kernel threads. I will submit my userspace context switching and trap handling support in a future PR.
> Kernel/riscv64: Implement RISC-V context switching

- Kernel/FileSystem/Ext2FS/Inode.cpp
- Kernel/FileSystem/Ext2FS/Inode.h
- Kernel/FileSystem/ISO9660FS/Inode.cpp
- Kernel/FileSystem/ISO9660FS/Inode.h
- Kernel/FileSystem/Inode.cpp
- Kernel/FileSystem/Inode.h
- Kernel/FileSystem/Plan9FS/Inode.cpp
- Kernel/FileSystem/Plan9FS/Inode.h
- Kernel/FileSystem/ProcFS/Inode.h
- Kernel/FileSystem/RAMFS/Inode.cpp
- Kernel/FileSystem/RAMFS/Inode.h
- Kernel/FileSystem/SysFS/Inode.cpp
- Kernel/FileSystem/SysFS/Inode.h
The first commit is from #23138 originally, but I also added a small fix for the ext2 driver.
> Kernel/FileSystem: Enforce proper inode locking when truncating, avoid mutex double locking in ext2 driver

- Documentation/VSCodeConfiguration.md
Turns out clangd supports code formatting using the clang-format engine (see [here](https://github.com/clangd/vscode-clangd?tab=readme-ov-file#formatting)). Because we also document another code formatter to install, when users use both extensions VSCode will ask to choose one or the other. Therefore, let's just choose clangd for code formatting since it is needed anyways for code comprehension.
> Documentation: Recommend using clangd for code formatting in VSCode

- Userland/Libraries/LibGUI/Calendar.cpp
- Userland/Libraries/LibGUI/Calendar.h
- Userland/Libraries/LibGUI/DatePicker.cpp
- Userland/Libraries/LibGUI/DatePickerDialog.gml
Calendar::toogle_mode function performed a call to Widget::resize with swapped width and height parameters as a quick way to trigger a resize_event (resize event is generated only when the new rect size is different from the old one, hence the swapped parameters).
This method does not work when width and height are equal, such as in the DatePicker widget where width and height are fixed to 200x200. In such case, calls to Calendar::toggle_mode would not generate a resize event, leaving tiles uninitialized, therefore the widget was not able to properly paint the Month view.
This commit replaces Widget::resize call with a manual triggering of the event.
> LibGUI: fix resize event trigger in calendar widget

- Userland/Libraries/LibWeb/Painting/SVGGraphicsPaintable.cpp
This one was annoying because it was printed before each repaint on pages where this FIXME is relevant.
> LibWeb: Remove spammy dbgln about unsupported SVG mask content units

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/DurationConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneMethods.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneMethods.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.compare.js
This updates some more AOs to latest spec, working towards fixing a test case in test262 timing out on a call to Instance.round. No change to test262, only aligns our implementation with editorial changes (such as the "Time Zone Methods Record") to make our implementation less confusing when comparing with latest spec.
> LibJS: More updates to Temporal, working towards Duration.round fixes

- Tests/LibWeb/Layout/expected/flex/flex-item-with-intrinsic-aspect-ratio-and-max-height.txt
- Tests/LibWeb/Layout/expected/flex/stretch-fit-width-for-column-layout-svg-item-that-only-has-natural-aspect-ratio.txt
- Tests/LibWeb/Layout/input/flex/stretch-fit-width-for-column-layout-svg-item-that-only-has-natural-aspect-ratio.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
This solves a particular issue with SVG as flex items, where the SVG has an intrinsic aspect ratio via its viewBox, but no explicit natural width or height.
Makes all corporate sponsor logos show up on https://ziglang.org/ :^)
Before:
After:
> LibWeb: Stretch-fit flex items with aspect ratio but no fixed sizes

- Tests/LibWeb/Text/input/clipboard.html
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/Internals/Internals.cpp
- Userland/Libraries/LibWeb/Internals/Internals.h
- Userland/Libraries/LibWeb/Internals/Internals.idl
It seems we were errantly mixing seconds and milliseconds in this
transient activation timeout. Increase it to 5 seconds, and be explicit
about its type - DOMHighResTimeStamp is by definition milliseconds.
> LibWeb: Increase the transient activation duration from 5ms to 5s

- Userland/Libraries/LibWeb/Animations/Animatable.h
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Fixes the button animations on https://null.com, specifically that they were always active and applied to the entire element instead of just the pseudo-elements.
Before:
https://github.com/SerenityOS/serenity/assets/28801118/c0aa4a12-69db-4984-ac8a-09ef80791433
After:
https://github.com/SerenityOS/serenity/assets/28801118/4a6fa29a-11f6-4d2d-9688-21c54b63e458
> LibWeb: Fix pseudo-element animations; Apply modified animation-* properties to existing animations

- Kernel/Devices/Storage/NVMe/NVMeController.cpp
- Kernel/Devices/Storage/NVMe/NVMeController.h
- Kernel/Devices/Storage/NVMe/NVMeQueue.cpp
- Kernel/Devices/Storage/NVMe/NVMeQueue.h
This will allow us to use NVMe on RISC-V.
Our RISC-V interrupts code does not yet implement those functions the NVMe driver tried to use.
> Kernel/Storage: Don't allocate IRQs in NVMeCntlr when nvme_poll passed

- AK/BinaryHeap.h
- Ladybird/AppKit/Application/EventLoopImplementation.h
- Ladybird/AppKit/Application/EventLoopImplementation.mm
- Ladybird/Qt/EventLoopImplementationQt.cpp
- Ladybird/Qt/EventLoopImplementationQt.h
- Userland/Libraries/LibCore/Event.h
- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibCore/EventLoop.h
- Userland/Libraries/LibCore/EventLoopImplementation.h
- Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
- Userland/Libraries/LibCore/EventLoopImplementationUnix.h
- Userland/Libraries/LibCore/EventReceiver.cpp
- Userland/Libraries/LibCore/EventReceiver.h
This PR contains a trivial cleanup of generic Core::Timer infrastructure and an overhaul of timer handling code in ELIUnix that makes it more extensible and faster in the case of large amounts of timers.
> LibCore: Some random work on ELIUnix

- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
If the GPU painter encounters a stacking context that requires the allocation of a framebuffer so large, it is likely due to a layout mistake, for now, we can skip it instead of crashing because of a failed allocation.
Fixes https://github.com/SerenityOS/serenity/issues/22608
> LibWeb: Skip StackingContext with erroneously large rect in GPU painter

- Userland/Libraries/LibProtocol/Request.cpp
- Userland/Libraries/LibProtocol/Request.h
- Userland/Libraries/LibProtocol/RequestClient.cpp
- Userland/Libraries/LibProtocol/RequestClient.h
- Userland/Services/RequestServer/ConnectionCache.cpp
- Userland/Services/RequestServer/ConnectionCache.h
- Userland/Services/RequestServer/ConnectionFromClient.cpp
- Userland/Services/RequestServer/ConnectionFromClient.h
- Userland/Services/RequestServer/GeminiProtocol.cpp
- Userland/Services/RequestServer/GeminiProtocol.h
- Userland/Services/RequestServer/GeminiRequest.cpp
- Userland/Services/RequestServer/GeminiRequest.h
- Userland/Services/RequestServer/HttpCommon.h
- Userland/Services/RequestServer/HttpProtocol.cpp
- Userland/Services/RequestServer/HttpProtocol.h
- Userland/Services/RequestServer/HttpRequest.cpp
- Userland/Services/RequestServer/HttpRequest.h
- Userland/Services/RequestServer/HttpsProtocol.cpp
- Userland/Services/RequestServer/HttpsProtocol.h
- Userland/Services/RequestServer/HttpsRequest.cpp
- Userland/Services/RequestServer/HttpsRequest.h
- Userland/Services/RequestServer/Protocol.h
- Userland/Services/RequestServer/Request.cpp
- Userland/Services/RequestServer/Request.h
- Userland/Services/RequestServer/RequestClient.ipc
- Userland/Services/RequestServer/RequestServer.ipc
This makes it so the client (e.g. LibWeb, etc) can proceed to do other things while RS tries to prepare the requested connection and start it. Fixes #23306.
I don't really see any perceptible difference on most servers; connection init performance still has quite a ways to go before it can be considered "fast".
> RequestServer: Defer connection initiation to after IPC processing

- Userland/Libraries/LibWebView/CookieJar.cpp
- Userland/Libraries/LibWebView/CookieJar.h
Getting a document's cookie value currently involves:
1. Doing a large `SELECT` statement and filtering the results to match the document and some query parameters based on the cookie RFC.
2. For every cookie selected this way, doing an `UPDATE` to set its last access time.
3. For every `UPDATE`, do a `DELETE` to remove all expired cookies.
There's no need to perform cookie expiration for every `UPDATE`. Instead, we can do the expiration once after all the `UPDATE`s are complete.
This reduces time spent waiting for cookies on https://twinings.co.uk from ~1.9s to ~1.3s on my machine.
Ref #23307
This is obviously not a full solution, but is a trivial change that should reduce the pain a bit.
> LibWebView: Reduce overhead of updating a cookie's last access time

- Userland/Libraries/LibWeb/Encoding/TextEncoder.cpp
- Userland/Libraries/LibWeb/Encoding/TextEncoder.h
- Userland/Libraries/LibWeb/FileAPI/FileList.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTableSectionElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableSectionElement.h
- Userland/Libraries/LibWeb/HTML/History.cpp
- Userland/Libraries/LibWeb/HTML/History.h
- Userland/Libraries/LibWeb/HTML/NavigatorConcurrentHardware.h
- Userland/Libraries/LibWeb/UIEvents/WheelEvent.h
Use the fancy WebIDL types where possible instead of C types
This commit is split of from https://github.com/SerenityOS/serenity/pull/22944 because that merge request is to big and getting stale
> LibWeb: Use WebIDL types where possible instead of C types

- Meta/run.py
The e1000 driver tries to use interrupt handling functions, which aren't implemented on RISC-V yet.
> Meta: Disable network hardware in run.py for RISC-V

- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/mkfs.fat.cpp
The first commit cleans up the parsing of utility names in CMake (as pointed out in #22810.)
As for the utility itself, this PR adds support for filling in the free cluster count hint and allows for autodetecting a suitable FAT variant if the user doesn't specify one.
> mkfs.fat: Some small improvements

- Meta/Lagom/CMakeLists.txt
This requirement was missed when AK was split into its own library in 5945cdc054e603214e9aeea9221888d523506c83
cc @trflynn89 
Fixes #23360
> Meta: Link AK to libexecinfo on BSDs and Haiku

- Tests/LibWeb/Text/expected/HTML/StructuredClone-serializable-objects.txt
- Tests/LibWeb/Text/input/HTML/StructuredClone-serializable-objects.html
- Userland/Libraries/LibWeb/Bindings/Serializable.h
- Userland/Libraries/LibWeb/FileAPI/Blob.cpp
- Userland/Libraries/LibWeb/FileAPI/Blob.h
- Userland/Libraries/LibWeb/FileAPI/File.cpp
- Userland/Libraries/LibWeb/FileAPI/File.h
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
This adds the abstract class `Serializable` which platform objects decorated with the `Serializable` IDL attribute can implement to support their appropriate serialization and deserialization steps.
To introduce the concept and implementation this PR makes `Blob` and `File` from the FileAPI spec serializable.
See individual commits for more details.
> LibWeb: Add support for serializable objects

- Ladybird/Qt/EventLoopImplementationQt.cpp
- Userland/Libraries/LibCore/ElapsedTimer.cpp
- Userland/Libraries/LibCore/ElapsedTimer.h
- Userland/Libraries/LibWeb/HighResolutionTime/Performance.cpp
- Userland/Libraries/LibWeb/HighResolutionTime/Performance.h
- Userland/Utilities/abench.cpp
- Userland/Utilities/dd.cpp
- Userland/Utilities/traceroute.cpp
This PR includes changes that improve the accuracy and precision of timer events. See the individual commits for details.
I used the following test page to test timer precision and accuracy:
```html
<script>
function sleepMilliseconds(delay) {
return new Promise((resolve) => setTimeout(resolve, delay));
}
async function testTimerPrecision() {
let previousTime = performance.now();
const outputElement = document.getElementById("output");
for (let i = 0; i < 10; ++i) {
await sleepMilliseconds(100);
const currentTime = performance.now();
outputElement.appendChild(document.createTextNode(`Time elapsed: ${currentTime - previousTime} milliseconds\n`));
previousTime = currentTime;
}
}
</script>
<body onload="testTimerPrecision()">
<pre id="output"></pre>
</body>
```
The results in …
> LibWeb+Ladybird/Qt: Improve timer precision

- Userland/Libraries/LibGfx/Font/OpenType/Glyf.cpp
- Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
```
Stacks:
0 crashes (0.0%)
0 distinct crash stacks
```
\o/
The type1 fonts crash triggered in a few places I hit in Real Life (mentioned in that commit's description).
> LibPDF+LibGfx: Fix last crashes on 1000 file test set

- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.h
- Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
- Userland/Libraries/LibPDF/Fonts/Type1Font.h
...and for fallback fonts too.
We use Liberation Sans (a truetype font) for standard and fallback
fonts. So we should use the standard PDF algorithm for mapping bytes
to truetype glyphs. TrueTypePainter knows how to do this.
Makes the "fi" ligature in the title on page 1 of 5014.CIDFont_Spec.pdf
or the dotless-i in the title of page 2 of ThinkingInPostScript.pdf
show up.
---
RIP PostScrõpt :(
> LibPDF: Let Type1Font use TrueTypePainter for standard fonts

- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.h
- Userland/Libraries/LibWeb/Layout/ImageBox.cpp
- Userland/Libraries/LibWeb/Layout/ImageBox.h
- Userland/Libraries/LibWeb/Layout/ImageProvider.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
- Userland/Libraries/LibWeb/Painting/ImagePaintable.h
- add `object-fit` and `object-position` into `ComputedValues` and get it from there instead of reaching into DOM node.
- save alt text and image provider in image paintable to avoid reaching into layout node while painting commands recording.
> LibWeb: Make ImagePaintable depend less on DOM and layout nodes

- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.h
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
- Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBRequest.h
With some fast-pathing, inlining, and avoiding some virtuals, this overall brings the runtime percentage of `IsValidIntegerIndex` on https://cyxx.github.io/another_js from 16% to 7% on my machine.
This also reduces the runtime of test-js from 3.6s to 3.4s consistently on my machine.
> LibJS: TypedArray speedups for https://cyxx.github.io/another_js

- Userland/Libraries/LibPDF/Renderer.cpp
- Userland/Libraries/LibPDF/Renderer.h
Makes text show up on 0000646.pdf pages 87-92, which for some reason
renders all text using 2x2 images with huge masks that contain
rendered text outlines.
> LibPDF: Resize images to the larger of image and mask dimensions

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
I did this for the creation of the key frame set in `KeyframeEffect` for Web Animations, but forgot to do it in `StyleComputer` for `@keyframes` rules.
Fixes #23367
> LibWeb: Expand shorthand PropertyIDs when creating keyframe set for @keyframes

- Tests/LibWeb/Text/expected/abortsignal-timeout.txt
- Tests/LibWeb/Text/input/abortsignal-timeout.html
- Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
- Userland/Libraries/LibWeb/DOM/AbortSignal.h
- Userland/Libraries/LibWeb/DOM/AbortSignal.idl
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
This method returns a signal that will automatically abort after a given number of milliseconds.
Progress towards #13355
> LibWeb: Implement `AbortSignal.timeout()`

- Tests/LibWeb/Ref/corner-clip-inside-scrollable.html
- Tests/LibWeb/Ref/reference/corner-clip-inside-scrollable-ref.html
- Userland/Libraries/LibWeb/Painting/ClipFrame.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
> LibWeb: Fix broken painting when corner radii clip happens inside scroll container

- Tests/LibWeb/Ref/abspos-escapes-scroll-container.html
- Tests/LibWeb/Ref/button-inside-scroll-container.html
- Tests/LibWeb/Ref/css-backgrounds.html
- Tests/LibWeb/Ref/overflow-hidden-7.html
- Tests/LibWeb/Ref/reference/scrollable-box-with-nested-stacking-context-ref.html
- Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-1-ref.html
- Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-2-ref.html
- Tests/LibWeb/Ref/reference/scrollable-contains-boxes-with-hidden-overflow-and-opacity-ref.html
- Tests/LibWeb/Ref/scroll-using-mousewheel-event.html
- Tests/LibWeb/Ref/scrollable-box-with-nested-stacking-context.html
- Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-1.html
- Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-2.html
- Tests/LibWeb/Ref/scrollable-contains-boxes-with-hidden-overflow-and-opacity.html
- Tests/LibWeb/Ref/svg-inside-scroll-container.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
Introduces the rendering of scroll thumbs in vertical and horizontal
directions. Currently, the thumbs are purely graphical elements that
do not respond to mouse events. Nevertheless, this is beneficial as it
makes it easier to identify elements that should respond to scrolling
events.
Painting of scrollbars uncovers numerous bugs in the calculation of
scrollable overflow rectangles highlighting all the places where
elements are made scrollable whey they shouldn't be. Positively, this
issue might motivate us to pay more attention to this problem to
eliminate unnecessary scrollbars.
Currently, the scrollbar style is uniform across all platforms: a
semi-transparent gray rectangle with rounded corners.
Also here we add `scrollbar-width: none` to all existing scrolling
ref-tests, so they keep …
> LibWeb: Implement scrollbar painting

- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.h
If we know the TA does not have a resizable ArrayBuffer, we can avoid most of the heavy lifting that IsValidIntegerIndex performs.
On https://cyxx.github.io/another_js, this reduces the runtime of IsValidIntegerIndex from 7.1% to 3.7%.
This also reverts a few of the previous optimizations that no longer apply / provide any measurable benefit after this change. Let's err on the side of having to track fewer optimized paths (i.e. wondering which AO to call) as long as there's no quantifiable benefit.
The animations on another_js are starting to look much smoother:
https://github.com/SerenityOS/serenity/assets/5600524/2f4fb7ad-762c-4d36-8744-60638bbbf7e5
> LibJS: Optimize IsValidIntegerIndex for TAs with non-resizable buffers

- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Font.h
- Userland/Libraries/LibGfx/FourCC.h
I tried implementing support for Type0 CIDFontType0 OpenType fonts in PDFs, but that works differently than I expected.
But these seem like ok changes in general, and I'll likely need them in the future.
> LibGfx: Several minor tweaks to the OpenType font loader

- Tests/LibWeb/Layout/expected/table/border-collapse-is-inherited.txt
- Tests/LibWeb/Layout/expected/table/inline-table-width.txt
- Tests/LibWeb/Layout/expected/table/nested-table-box-width.txt
- Tests/LibWeb/Layout/expected/table/row-span-and-nested-tables.txt
- Tests/LibWeb/Layout/expected/vertical-align-middle.txt
- Tests/LibWeb/Layout/input/vertical-align-middle.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
This rebaselines a few table-related layout tests since our default stylesheet applies 'vertical-align: middle' to a few table-related elements.
Fixes #23369.
> LibWeb: Improve support for 'vertical-align: middle'

- Tests/LibWeb/Text/expected/css/CSSConditionRule-conditionText-readonly.txt
- Tests/LibWeb/Text/input/css/CSSConditionRule-conditionText-readonly.html
- Userland/Libraries/LibWeb/CSS/CSSConditionRule.h
- Userland/Libraries/LibWeb/CSS/CSSConditionRule.idl
- Userland/Libraries/LibWeb/CSS/CSSMediaRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSMediaRule.h
- Userland/Libraries/LibWeb/CSS/CSSSupportsRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSSupportsRule.h
Previously, media rule conditions could be updated by assigning to `conditionText`. This change aligns our implementation with the CSSOM specification, which says `CSSConditionRule.conditionText` should be read-only.
Relevant CSSWG issue: https://github.com/w3c/csswg-drafts/issues/6819
Fixes this WPT test: https://wpt.live/css/cssom/CSSConditionRule-conditionText.html
> LibWeb: Make `CSSConditionRule.conditionText` read-only

- AK/Optional.h
- AK/StdLibExtras.h
- AK/Vector.h
- AK/Weakable.h
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
- Userland/Libraries/LibJS/Runtime/Environment.h
- Userland/Libraries/LibJS/Runtime/EnvironmentCoordinate.h
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
- Userland/Libraries/LibJS/Runtime/GlobalEnvironment.h
- Userland/Libraries/LibJS/Runtime/IndexedProperties.h
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ObjectEnvironment.h
- Userland/Libraries/LibJS/Runtime/Realm.h
With the LibJS JIT removed, let's not expose pointers to internal members.
> AK+LibJS: Remove OFFSET_OF and its users

- Userland/Libraries/LibLine/Editor.cpp
With `cleanup_suggestions()` we ensure that all variables related to suggestions are reset, preventing the crash.
Fixes #23382
> LibLine: Ensure suggestions are reset after ^C

- Tests/LibWeb/Text/expected/wheel-events-consumed-by-scrollable-should-not-be-propagated-to-body.txt
- Tests/LibWeb/Text/input/wheel-events-consumed-by-scrollable-should-not-be-propagated-to-body.html
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Fixes the bug when we scroll both scrollable box and page.
> LibWeb: Skip page scrolling for wheel events consumed by scrollable box

- Meta/Azure/Lagom.yml
- Tests/LibWeb/WPT/run.sh
This directory is about 600MB. Remove it after running WPT as an attempt to alleviate CI disk space issues.
> CI: Remove the WPT directory after tests have completed

- Tests/LibWeb/Text/expected/Element-offsetParent-of-iframe.txt
- Tests/LibWeb/Text/input/Element-offsetParent-of-iframe.html
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
The specification says the final step of this algorithm is to return null. Previously, the browser would crash if the content of an iframe was appended to the document before its offsetParent property was queried.
Fixes this WPT test (and probably others): [the-xhtml-syntax/parsing-xhtml-documents/adopt-while-parsing-001](http://wpt.live/html/the-xhtml-syntax/parsing-xhtml-documents/adopt-while-parsing-001.html)
This fix also prevents these WPT tests from crashing WebContent, although it doesn't fix them:
* [css/css-anchor-position/anchor-name-cross-shadow](http://wpt.live/css/css-anchor-position/anchor-name-cross-shadow.html)
* [css/css-anchor-position/anchor-name-in-shadow](http://wpt.live/css/css-anchor-position/anchor-name-in-shadow.html)
* …
> LibWeb: Don't crash in offset_parent() if no ancestor element found

- Tests/LibWeb/Text/expected/HTML/custom-elements-throw-in-constructor.txt
- Tests/LibWeb/Text/input/HTML/custom-elements-throw-in-constructor.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
If an exception occurs in a custom element constructor, we clear the reaction queue by destroying it, instead of emptying the Vector. https://github.com/SerenityOS/serenity/blob/3da6916383afc1c8a8b59dae38c4bc02680b50ba/Userland/Libraries/LibWeb/DOM/Element.cpp#L2033
This causes a UAF here, as async upgrades (i.e. custom elements not created by document.createElement) are performed in this loop: https://github.com/SerenityOS/serenity/blob/3da6916383afc1c8a8b59dae38c4bc02680b50ba/Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp#L657
Fixes crash when loading https://github.com/SerenityOS/serenity
> LibWeb: Empty CE reaction queue instead of destroying it on exception

- Tests/LibWeb/Text/expected/hit_testing/positioned-z-index-0-and-floats.txt
- Tests/LibWeb/Text/input/hit_testing/positioned-z-index-0-and-floats.html
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.h
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
By storing a list of positioned and floating descendants within the stacking context tree node, we can eliminate the need for costly paintable tree traversals during hit-testing.
This optimization results in hit-testing being 2 to 2.5 times faster on https://ziglang.org/documentation/master/
> LibWeb: Reduce paintable tree traversals during hit-testing

- AK/CharacterTypes.h
- Userland/Libraries/LibPDF/Fonts/AdobeGlyphList.cpp
- Userland/Libraries/LibPDF/Fonts/AdobeGlyphList.h
- Userland/Libraries/LibPDF/Fonts/PDFFont.cpp
- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.h
- Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
Turns out there's a spec that goes with the table.
The big change here is that we can now map `uni1234` to 0x1234 and
`u123456` to 0x123456.
The parts where we split a name on `_` and map each component
and the part where we're supposed to allow multiple groups of 4
after `uni` aren't implemented yet.
I haven't seen this have an effect in practice, but it's easy to
construct a PDF with a custom encoding where it would make a
difference.
Also implement the ZapfDingbats part of the algorithm.
Liberation Sans still doesn't have the vast majority of the Zapf Dingbats
glyphs, but now we map the Zapf Dingbats names to good unicode values.
So we only need to use a different font and all should work.
(And Liberation Sans has _some_ of the glyphs, like 13 of the 223.)
And we now render empty …
> LibPDF(+AK): LibPDF: Implement some of the AdobeGlyphList algorithm for slightly better truetype and zapf dingbats support

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Tests/var-scoping.js
`var` declarations can have duplicates, but duplicate `let` or `const` bindings are a syntax error.
Because of this, we can sink `let` and `const` directly into the preferred_dst if available. This is not safe for `var` since the preferred_dst may be used in the initializer.
This patch fixes the issue by simply skipping the preferred_dst optimization for `var` declarations.
> LibJS/Bytecode: Handle awkward initialization case for duplicate `var`

- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableFragment.cpp
- Userland/Libraries/LibWeb/Painting/SVGPaintable.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Every single client of this function was immediately calling `paintable()` on the result anyway, so there was no need to return a layout node!
This automatically leverages the cached containing block pointer we already have in `Paintable`, which melts away a bunch of unnecessary traversal in hit testing and painting. :^)
> LibWeb: Make Paintable::containing_block() return a PaintableBox*

- AK/HashMap.h
- Kernel/Bus/PCI/Access.cpp
- Kernel/Devices/Storage/NVMe/NVMeController.cpp
- Kernel/Devices/Storage/NVMe/NVMeController.h
- Tests/LibSemVer/TestFromStringView.cpp
- Tests/LibSemVer/TestSemVer.cpp
- Userland/Libraries/LibAudio/MP3Loader.h
- Userland/Libraries/LibGUI/Icon.h
- Userland/Libraries/LibPDF/DocumentParser.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
- Userland/Libraries/LibPDF/Fonts/PDFFont.h
- Userland/Libraries/LibTLS/Certificate.cpp
- Userland/Libraries/LibTLS/Certificate.h
- Userland/Libraries/LibTest/Randomized/Generator.h
- Userland/Libraries/LibWeb/DOM/AccessibilityTreeNode.cpp
- Userland/Services/WindowServer/ConnectionFromClient.cpp
- Userland/Services/WindowServer/ConnectionFromClient.h
- Userland/Services/WindowServer/Screen.cpp
- Userland/Services/WindowServer/WindowFrame.h
- Userland/Services/WindowServer/WindowManager.h
- Userland/Utilities/sed.cpp
Also cleans up the organizational_unit() helper to use `value_or({})`
instead of doing the same thing manually.
This makes `Access::rescan_hardware` look a bit nicer.
> Everywhere: Some Tuple cleanups and structured bindings for HashMaps

- Userland/Libraries/LibGfx/TextLayout.h
- Userland/Libraries/LibWeb/Layout/LineBox.cpp
- Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
- Userland/Libraries/LibWeb/Painting/Command.cpp
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.h
- Userland/Libraries/LibWeb/Painting/CommandList.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableFragment.h
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Before these changes, each glyph run was copied:
1. In paint_text_fragment() to scale position and font of each glyph by device pixel size.
2. In RecordingPainter::draw_glyph_run() to shift each glyph position by painter's transform.
Now, neither of these copies occurs and instead we save scale and offset in the painting command to apply it later when commands are executed.
Also, we do not copy the vector of glyphs from the layout tree into paintables tree and painting commands. Instead, we allocate ref-counted objects that are shared between them.
> LibWeb: Reduce number of glyph run copies made while painting commands recording

- Kernel/Tasks/Thread.cpp
- Userland/Utilities/strace.cpp
All found while investigating #23289 crashes
> strace: A couple of fixes and improvements

- Meta/Azure/Caches.yml
- Meta/Azure/Lagom.yml
We're still hitting low disk space issues after #23404. Let's reduce disk usage even further.
> CI: Strip binaries and libraries during the installation step, reduce ccache size

- Userland/Libraries/LibPDF/CommonNames.cpp
- Userland/Libraries/LibPDF/CommonNames.h
- Userland/Libraries/LibPDF/Fonts/PDFFont.h
- Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
- Userland/Libraries/LibPDF/Fonts/Type0Font.h
- Userland/Libraries/LibPDF/Renderer.cpp
Only for the named Identity-V cmap for now. As far as I can tell, in my 1000 file test sets, there are 4 files that use vertical text, and they all use Identity-V.
The drawing code is all done now, and the type0 cmap logic is now a bit abstracted away, so it's easy to add support for vertical text in more cmap encodings. (As easy as adding support for additional horizontal cmap encodings at least.)
> LibPDF: Add support for vertical text :^)

- Base/res/html/misc/web-animations.html
- Userland/Libraries/LibGfx/Matrix.h
- Userland/Libraries/LibGfx/VectorN.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
With this PR, we can interpolate between transforms whose functions don't match. For example: `translate(100px)` -> `scale(2) translateX(50px)`. 
New video of the demo:
https://github.com/SerenityOS/serenity/assets/28801118/fa1079af-50cd-43f0-b0ad-a2b80c21a376
(I'm assuming the GPU painter doesn't support circles or something, which is why the bouncing ball doesn't render)
> LibWeb: Support interpolation between arbitrary transform values

- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDate.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateISO.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainDateTimeISO.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.plainTimeISO.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getPlainDateTimeFor.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.getISOFields.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.offset.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.offsetNanoseconds.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toJSON.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toLocaleString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toString.js
This catches up the API of some AOs closer to the latest version of the spec. Split out from my branch continuing work towards fixing some Duration.Round test cases, as the amount of changes in there has been ballooning. No change to test262, but does improve some exception messages.
> LibJS: Port over some Temporal AOs to use TimeZoneMethodsRecord

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
`set_target` calls `associate_with_effect` in addition to setting the effect's `m_target_element`. Fixes #23424
Sidenote: I also noticed I broke the button effect rotations, but that's a separate PR :smile:
> LibWeb: Correctly set @keyframe rule's effect target

- Userland/Libraries/LibHTTP/Job.cpp
It was possible to reach this via the timer itself (when the client is only slightly busy), and then to have the timer fire before the deferred invocation fires.
This commit removes the race by disabling the timer when the final deferred-accept state is reached.
> LibHTTP: Disable finish repeat timer before deferring job completion

- Tests/LibWeb/Text/expected/css/changing-animation-name-crash.txt
- Tests/LibWeb/Text/input/css/changing-animation-name-crash.html
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/Animation.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
See the note added to Animation::cancel for more info. Fixes a regression on shopify.com.
> LibWeb: Do not invalidate elements with animations in the CSS cascade

- Userland/Applets/Keymap/KeymapStatusWidget.cpp
Otherwise it is dark and hard to read against dark themes.
Before:
After:
> Keymap: Draw the current keymap text with the correct theme color

- Userland/Libraries/LibPDF/Renderer.cpp
See the added comment for reasoning.
> LibPDF: Silently ignore BX / EX operators

- Tests/LibWeb/Text/expected/HTML/StructuredClone-object-primitives.txt
- Tests/LibWeb/Text/expected/HTML/StructuredClone-primitives.txt
- Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
- Tests/LibWeb/Text/input/HTML/StructuredClone-primitives.html
- Userland/Libraries/LibWeb/FileAPI/Blob.cpp
- Userland/Libraries/LibWeb/FileAPI/File.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
To avoid differing logic for serializing and deserializing similar types, move the logic into separate helpers.
Adds security checks like VERIFY to avoid reading past the end of the serialized data. If we try to read past the end of the serialized data, either our program logic is wrong or our serialized data has somehow been corrupted. Therefore, at least currently, it is better to crash by VERIFYing.
Also, added tests to prove that we can serialize and deserialize empty string + empty arrays.
PR spun out from review comment: https://github.com/SerenityOS/serenity/pull/23323#discussion_r1501944154
> LibWeb: Extract serialization and deserialization logic into separate helpers

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/Page/Page.cpp
Per spec, the change event shall only be issued once the change is finally committed by the user, that is by closing the color picker window. Previously this was not implemented and both `input` and `change` events occurred.
> LibWeb: Do not issue `change` event for every update of color input

- Userland/Libraries/LibWeb/CSS/StyleValues/ConicGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
- Userland/Libraries/LibWeb/Painting/GradientPainting.cpp
- Userland/Libraries/LibWeb/Painting/GradientPainting.h
These were adding unnecessary indirection, whereas recording painter could be called directly.
> LibWeb: Remove wrappers for gradient painting command recording

- Tests/LibWeb/Text/expected/css/box-shadow-resolves-length-functions.txt
- Tests/LibWeb/Text/expected/interpolation-longhand-properties.txt
- Tests/LibWeb/Text/input/interpolation-longhand-properties.html
- Userland/Libraries/LibGfx/Color.cpp
- Userland/Libraries/LibGfx/Color.h
- Userland/Libraries/LibWeb/CSS/Length.cpp
- Userland/Libraries/LibWeb/CSS/Ratio.cpp
- Userland/Libraries/LibWeb/CSS/Serialize.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/ShadowStyleValue.cpp
For all of the decimal changes (except color) I couldn't really find a spec that mandates any required precision, so I just copied what Firefox seems to do, which is limit the output to 5 decimal places.
> LibWeb: Support more interpolations and add an interpolation test

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Executable.cpp
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- `string` literals now become constant operands in bytecode
- `BigInt` literals now become constant operands in bytecode
- Bonus: `NewPrimitiveArray` is now a variable-length instruction
> LibJS/Bytecode: Make more primitives be constant operands

- Ports/SRB2/package.sh
This patch fixes the download error that recently started occuring with the asset file. The developers decided to disable the service we were using to download the asset so we had to find an other way.
This uses the link to the full Windows zip file that contain the libraries, executable and assets, we only copy the necessary assets over. It's not as pretty but it does the job at least! :^)
> Ports: Fix SRB2 asset file download

- Userland/Libraries/LibCore/Environment.cpp
b9dc2d7 accidentally broke Android builds, this fixes that regression.
A lot more than this is obviously broken in ladybird android land, this PR is strictly referring to LibCore.
> LibCore: Fix `AK_OS_ANDROID` build

- Userland/Applications/PDFViewer/PDFViewer.cpp
- Userland/Applications/PDFViewer/PDFViewer.h
- Userland/Applications/PDFViewer/PDFViewerWidget.cpp
- Userland/Applications/PDFViewer/PDFViewerWidget.h
- Userland/Libraries/LibPDF/Renderer.h
You can enable it in the Debug menu and we will remember your choice.
> PDFViewer: Hide the rendering diagnostics window by default

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Libraries/LibWebView/InspectorClient.cpp
- Userland/Libraries/LibWebView/InspectorClient.h
This reverts commit 2e8ff1855c470094bf6aa6448cbe8173f1d79f92.
We had some awkward timing around the merging of this commit and commit
b073fdd5707277d0cc23c75f494ae31a5242705e. With both commits in tree, we
are now processing hotkey activations twice. For example, ctrl+t will
open 2 tabs.
> Browser+LibWebView: Avoid double-activation of hotkeys, and protect Inspector against being doubly loaded

- Tests/LibWeb/Layout/expected/svg/objectBoundingBox-mask.txt
- Tests/LibWeb/Layout/expected/svg/svg-circle-percentage-attr.txt
- Tests/LibWeb/Layout/input/svg/svg-circle-percentage-attr.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
- Userland/Libraries/LibWeb/SVG/SVGCircleElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGCircleElement.h
- Userland/Libraries/LibWeb/SVG/SVGEllipseElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGEllipseElement.h
- Userland/Libraries/LibWeb/SVG/SVGGeometryElement.h
- Userland/Libraries/LibWeb/SVG/SVGLength.cpp
- Userland/Libraries/LibWeb/SVG/SVGLength.h
- Userland/Libraries/LibWeb/SVG/SVGLineElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGLineElement.h
- Userland/Libraries/LibWeb/SVG/SVGPathElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGPathElement.h
- Userland/Libraries/LibWeb/SVG/SVGPolygonElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGPolygonElement.h
- Userland/Libraries/LibWeb/SVG/SVGPolylineElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGPolylineElement.h
- Userland/Libraries/LibWeb/SVG/SVGRectElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGRectElement.h
- Userland/Libraries/LibWeb/SVG/SVGViewport.h
This PR adds the basic plumbing for SVG geometry properties and viewport relative values, then uses them to support percentages in SVG `<circle>` element attributes. The same fixes can be made to other SVG geometry elements, but those are left as a TODO.
Fixes #23121
> LibWeb: Start adding support for viewport relative values in SVG geometry elements

- Userland/Applications/Escalator/EscalatorWindow.cpp
- Userland/Applications/Escalator/EscalatorWindow.h
There is a limit of 3 attempts before quitting, but the user can try again after that.
The error messages now display to help the user understand the issue.
> Escalator: Allow failed password attempts to be retried

- Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
- Kernel/Net/Realtek/RTL8168NetworkAdapter.h
Instead of using C-arrays, and manually counting their lengths, use AK::Array. And pass these arrays around as spans, instead of as pointer-and-length pairs.
> Kernel: Replace C-idioms with AK types in RTL8168 network adapter

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Tests/assignment-evaluation-order.js
This fixes an issue where expressions like `a[i] = a[++i]` could evaluate `++i` before `a[i]`.
> LibJS/Bytecode: Always evaluate LHS first in assignment expressions

- Userland/Libraries/LibJS/Bytecode/Pass/Peephole.cpp
- Userland/Libraries/LibJS/Tests/optimizer-bugs.js
Fixes an issue where https://x.com/awesomekling crashed on load. :^)
> LibJS/Bytecode: Don't fuse unrelated compare and jump in peephole pass

- Tests/LibWeb/Text/expected/hit_testing/box-outside-of-abspos-containing-block-border-rect.txt
- Tests/LibWeb/Text/expected/hit_testing/open-details-by-clicking-on-triangle.txt
- Tests/LibWeb/Text/input/hit_testing/box-outside-of-abspos-containing-block-border-rect.html
- Tests/LibWeb/Text/input/hit_testing/open-details-by-clicking-on-triangle.html
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Children of a paintable box are not guaranteed to be contained within its border box. Therefore, during hit-testing, we must always check them.
Fixes https://github.com/SerenityOS/serenity/issues/23219
> LibWeb: Always check paintable boxes children during hit-testing

- Ports/zlib/package.sh
zlib.net uses DDoS protection, which results in broken downloads whenever a browser validation page is served instead. The tarballs that are uploaded to GitHub releases are identical with the ones that are served on zlib.net.
Fixes #23458.
> Ports/zlib: Switch to tarball copies hosted on GitHub

- Tests/LibWeb/Layout/expected/grid/placement-10.txt
- Tests/LibWeb/Layout/expected/grid/placement-5.txt
- Tests/LibWeb/Layout/expected/grid/placement-6.txt
- Tests/LibWeb/Layout/expected/grid/placement-7.txt
- Tests/LibWeb/Layout/expected/grid/placement-8.txt
- Tests/LibWeb/Layout/expected/grid/placement-9.txt
- Tests/LibWeb/Layout/input/grid/placement-10.html
- Tests/LibWeb/Layout/input/grid/placement-5.html
- Tests/LibWeb/Layout/input/grid/placement-6.html
- Tests/LibWeb/Layout/input/grid/placement-7.html
- Tests/LibWeb/Layout/input/grid/placement-8.html
- Tests/LibWeb/Layout/input/grid/placement-9.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Before this change, we only considering `grid-auto-flow` to determine whether a row or column should be added when there was not enough space in the implicit grid to fit the next unplaced item.
Now, we also choose the direction in which the "auto placement cursor" is moved, based on the auto flow property.
Improvement on https://www.shopify.com/pricing
Before:
After:
> LibWeb: Respect "auto flow" property in grid layout

- AK/HashMap.h
- Tests/LibWeb/Ref/css-keyframe-fill-forwards.html
- Tests/LibWeb/Ref/css-keyframe-invalid-transform-should-not-render.html
- Tests/LibWeb/Ref/reference/css-keyframe-fill-forwards-ref.html
- Tests/LibWeb/Ref/reference/css-keyframe-invalid-transform-should-not-render-ref.html
- Tests/LibWeb/Text/expected/invalid-transform-interpolation-does-not-crash.txt
- Tests/LibWeb/Text/input/invalid-transform-interpolation-does-not-crash.html
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
Fixes #23473, fixes #23471. Also fixes an overly-excited button on [shopify.com](https://shopify.com) (the hover animation was blinking on and off). Note that it uses transitions to animate on hover, so the fact that it now no longer animates at all is expected.
> LibWeb: More animation fixes

- Ladybird/Android/src/main/cpp/RequestServerService.cpp
- Ladybird/RequestServer/main.cpp
- Userland/Services/RequestServer/GeminiProtocol.cpp
- Userland/Services/RequestServer/GeminiProtocol.h
- Userland/Services/RequestServer/HttpProtocol.cpp
- Userland/Services/RequestServer/HttpProtocol.h
- Userland/Services/RequestServer/HttpsProtocol.cpp
- Userland/Services/RequestServer/HttpsProtocol.h
- Userland/Services/RequestServer/Protocol.cpp
- Userland/Services/RequestServer/Protocol.h
- Userland/Services/RequestServer/main.cpp
It's no change in application behavior to have these objects owned by the function-scope static map in Protocol.cpp, while allowing us to remove some ugly FIXMEs from time immemorial.
I thought about converting this to some kind of clever `RequestServer::register_protocols({"gemini"sv, "http"sv, "https"sv})` API or something, but this seems simpler :)
> RequestServer: Transfer ownership of Protocols to all_protocols map

- Ladybird/Qt/WebContentView.cpp
This allows ctrl+wheel events to zoom in and out of the page. This was ported incorrectly in commit c1476c3405518871be7a8f5f4feb0670d1051df8.
> Ladybird/Qt: Explicitly ignore wheel events with the ctrl key pressed

- Meta/gn/secondary/Ladybird/BUILD.gn
- Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
- Userland/Services/WebContent/ConnectionFromClient.cpp
When we coalesce mouse wheel events, we need to be sure to include the
previous event's wheel deltas. This was errantly excluded in commit
baf359354b4f55b33372951a2a60f797ad071071.
> WebContent: Update mouse event data when coalescing consecutive events

- Userland/Libraries/LibWebView/CookieJar.cpp
Note no test here, because this early return involves HTTP-only cookies, which we don't have the infrastructure to test (we would need to support custom HTTP headers in tests).
> LibWebView: Ensure we resolve cookie promises upon early returns

- Tests/LibWeb/Text/expected/element-get-bounding-client-rect-css-transform.txt
- Tests/LibWeb/Text/input/element-get-bounding-client-rect-css-transform.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
This fixes #23003
The select element uses the `get_bounding_client_rect()` for the location where it places the dropdown. In `get_client_rects()` the transform origin wasn't applied so when scaling the element the rects where not correct.
CC @kalenikaliaksandr
> LibWeb: Apply transform origin in Element::get_client_rects()

- Ladybird/CMakeLists.txt
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/WebWorker/CMakeLists.txt
After ea682207d099654dd0c5d1ed399e2060c4de1533, we need Userland/ included directly in these application executables. This only impacts the build with Ladybird/CMakeLists.txt as the top level CMakeLists, as the Lagom/ directory includes Userland/ globally.
> Ladybird: Include Userland/ in for Applications that use LibWeb

- Tests/LibWeb/Layout/expected/table/absolute-positioning-alignment.txt
- Tests/LibWeb/Layout/input/table/absolute-positioning-alignment.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
Table wrappers don't quite behave the same as most elements, in that their computed height and width are not meant to be used for layout. Instead, we now calculate suitable widths and heights based on the contents of the table wrapper when performing absolute layout.
Fixes the layout of
http://wpt.live/css/css-position/position-absolute-center-007.html
> LibWeb: Account for absolutely positioned table wrappers

- Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
- Userland/Libraries/LibPDF/Filter.cpp
`test_pdf` diff:
Before:
```
Rendering of feature not supported: Unimplemented option for the CCITTFaxDecode Filter, in 46 files, on 331 pages, 657 times
0000/0000084.pdf 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78
0000/0000605.pdf 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
0000/0000286.pdf 1 2 3 4 5 6 7 8 9 10 11 12 13 14 (2x) 15 (2x) 16 17 (6x) 18 19 21 22 23 (2x) 24 (2x) 25 (2x) 26
0000/0000031.pdf 1 (3x) 2 3 4 (3x) 5 (4x) 6 (4x) 7 (4x) 8 (4x) 9 (4x) 10 (3x) 11 (4x) 12 (4x) 13 (4x) 14 (4x) 15 (4x) 16
0000/0000001.pdf …
```
> LibGfx/CCITT: Fix most PDF files from 0000.zip

- Userland/Applications/FileManager/PropertiesWindow.cpp
- Userland/Applications/ImageViewer/ViewWidget.cpp
- Userland/Applications/Maps/MapWidget.cpp
- Userland/Libraries/LibGUI/ImageWidget.cpp
- Userland/Libraries/LibGfx/Bitmap.cpp
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h
- Userland/Services/ImageDecoder/ConnectionFromClient.cpp
- Userland/Services/SpiceAgent/SpiceAgent.cpp
- Userland/Utilities/file.cpp
- Userland/Utilities/icc.cpp
- Userland/Utilities/image.cpp
...from try_create_for_raw_bytes().
If a plugin returns `true` from sniff but then fails when calling its `create()` method, we now no longer swallow that error.
Allows `image` (and other places in the system) to print a more actionable error if early image headers are invalid.
(We now no longer try to find another plugin that can also handle the image.)
Fixes a regression from #20063 / #19893 -- before then, we didn't do fallible work this early.
---
I have only tried this in lagom, so relying on CI for the rest.
> LibGfx+Fallout: Make ImageDecoder return ErrorOr

- Userland/Libraries/LibPDF/Fonts/PDFFont.h
- Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
- Userland/Libraries/LibPDF/Fonts/Type1Font.cpp
Turns out the spec didn't mean that the whole range is populated, but that one of these ranges is populated. So take the argmax.
As fallout, explicitly mark the Liberation fonts as nonsymbolic when we use them for the 14 standard fonts. Else, we'd regress "PostScrõpt", since the Liberation fonts would otherwise go down the "is symbolic or doesn't have explicit encoding" codepath, since the standard fonts usually don't have an explicit encoding.
As a fallout from _that_, since the 14 standard fonts now go down the regular truetype rendering path, and since we don't implement lookup by postscript name yet, glyphs not present in Liberation now cause text to stop rendering with a diag, instead of rendering a "glyph not found" symbol. That isn't super common, only an additional 4 files appear …
> LibPDF: Make truetype fonts marked as symbol fonts actually work

- Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Fixes oss-fuzz issue 66844.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66844&sort=-opened&q=proj%3Aserenity%20TIFF&can=1
> LibGfx/TIFF: Reject images with a null value in tile's dimensions

- Userland/DevTools/GMLPlayground/main.cpp
- Userland/DevTools/HackStudio/main.cpp
- Userland/Libraries/LibConfig/Client.cpp
- Userland/Libraries/LibConfig/Client.h
- Userland/Services/ConfigServer/ConfigServer.ipc
- Userland/Services/ConfigServer/ConnectionFromClient.cpp
- Userland/Services/ConfigServer/ConnectionFromClient.h
When in permissive mode, the ConfigServer will not treat reads and
writes to non-pledged domains as errors, but instead turns them into
no-ops: Reads will act as if the key was not found, and writes will do
nothing. Permissive mode must be enabled before pledging any domains.
This is needed to make GUI Widgets nicer to work with in GML Playground:
a few Widgets include reads and writes to LibConfig in order to load
system settings (eg, GUI::Calendar) or to save and restore state
(eg, GUI::DynamicWidgetContainer). Without this change, editing a
layout that includes one of these Widgets will cause GML Playground to
crash when they try to access config domains that are not pledged.
The solution used previously is to make Playground pledge more domains,
but not only does this mean Playground …
> LibConfig+ConfigServer: Add permissive mode, fixing a GMLPlayground crash

- Tests/LibCrypto/TestASN1.cpp
- Userland/Applications/CertificateSettings/CertificateStoreWidget.cpp
- Userland/Libraries/LibCrypto/ASN1/ASN1.cpp
- Userland/Libraries/LibCrypto/ASN1/ASN1.h
- Userland/Libraries/LibTLS/Certificate.cpp
- Userland/Libraries/LibTLS/Certificate.h
- Userland/Libraries/LibTLS/TLSv12.cpp
We are currently using `Core::DateTime`, which is meant to represent local time. However, we are doing no conversion between the parsed time in UTC and local time, so we end up comparing time stamps from different time zones.
Instead, store the parsed times as `UnixDateTime`, which is UTC. Then we can always compare the parsed times against the current UTC time.
This also lets us store parsed milliseconds.
Fixes #23502
> LibCrypto: Store ASN1 certificate timestamps as UnixDateTime

- Tests/LibGfx/TestImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/TGALoader.h
> LibGfx: Make mime-based image loaders not throw away their error either

- Userland/Libraries/LibPDF/Renderer.cpp
Fixes pages 17-19 on
https://www.iro.umontreal.ca/~feeley/papers/ChevalierBoisvertFeeleyECOOP15.pdf
Calling the fill handler after painting the stroke as previously doesn't work, since we need to set up the clip before both stroke and fill, and unset it after both. The duplication is a bit unfortunate, but also minor.
> LibPDF: Clip stroke for B / B* operators

- Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
- Userland/Libraries/LibWeb/Fetch/Body.cpp
- Userland/Libraries/LibWeb/FileAPI/Blob.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamGenericReader.cpp
- Userland/Libraries/LibWeb/WebIDL/ExceptionOr.h
- Userland/Libraries/LibWeb/WebIDL/Promise.cpp
- Userland/Libraries/LibWeb/WebIDL/Promise.h
For a few of these, I replaced code that created a `JS::TypeError` with use of a `WebIDL::SimpleException` instead. As far as I can tell, they are equivalent:
> These correspond to all of the JavaScript [error objects](https://tc39.es/ecma262/#sec-error-objects) (apart from [SyntaxError](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-native-error-types-used-in-this-standard-syntaxerror) and [Error](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-error-objects), which are deliberately omitted as they are reserved for use by the JavaScript parser and by authors, respectively). The meaning of each [simple exception](https://webidl.spec.whatwg.org/#dfn-simple-exception) matches its corresponding error object in the JavaScript specification.
> - …
> LibWeb: Add and use a helper to reject a promise with an exception

- AK/StringView.cpp
- AK/StringView.h
- Tests/AK/TestStringView.cpp
- Userland/Applications/Spreadsheet/SpreadsheetView.cpp
- Userland/Libraries/LibGUI/Application.cpp
- Userland/Libraries/LibGUI/Label.cpp
- Userland/Libraries/LibGfx/TextLayout.cpp
- Userland/Libraries/LibRegex/RegexMatch.h
We were previously splitting lines on `\r` (while over-splitting lines on `\r\n`), but not considering `\r` at all when computing the height of the widget containing the split text. So when we drew text from the web containing `\r`, we would draw text that didn't fit in its container:
Now we handle `\r` and `\r\n` correctly:
> AK+LibGfx+LibGUI: Handle carriage returns better when drawing and measuring text

- Tests/LibWeb/Layout/expected/abspos-flex-margin-limits-1.txt
- Tests/LibWeb/Layout/expected/abspos-flex-margin-limits-2.txt
- Tests/LibWeb/Layout/expected/abspos-flexbox-with-auto-width.txt
- Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-align-items.txt
- Tests/LibWeb/Layout/expected/inline-size.txt
- Tests/LibWeb/Layout/input/abspos-flex-margin-limits-1.html
- Tests/LibWeb/Layout/input/abspos-flex-margin-limits-2.html
- Tests/LibWeb/Layout/input/abspos-flexbox-with-auto-width.html
- Tests/LibWeb/Layout/input/inline-size.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
As a whole, this PR fixes the following Web Platform Tests:
http://wpt.live/css/css-position/position-absolute-center-001.html
http://wpt.live/css/css-position/position-absolute-center-003.html
http://wpt.live/css/css-position/position-absolute-center-004.html
...and as a bonus, this also fixes some very subtle layout issues with `flex/abspos-flex-child-static-position-with-align-items.html`
> LibWeb: Improve the layout of absolutely positioned flex items

- Tests/LibWeb/Layout/expected/input-element-with-display-inline.txt
- Tests/LibWeb/Text/expected/shadow-root-adopted-style-sheets.txt
- Tests/LibWeb/Text/expected/shadow-root-style-sheets.txt
- Tests/LibWeb/Text/input/shadow-root-adopted-style-sheets.html
- Tests/LibWeb/Text/input/shadow-root-style-sheets.html
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/DOM/AdoptedStyleSheets.cpp
- Userland/Libraries/LibWeb/DOM/AdoptedStyleSheets.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/DocumentOrShadowRoot.idl
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
- Userland/Libraries/LibWeb/DOM/ShadowRoot.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.idl
- Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Userland/Libraries/LibWeb/DOM/StyleElementUtils.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/WebIDL/ObservableArray.h
- Support `ShadowRoot.styleSheets`
- Support `ShadowRoot.adoptedStyleSheets`
- Use style sheets from shadow root in StyleComputer if element belongs to shadow tree
Fixes https://github.com/SerenityOS/serenity/issues/23410
> LibWeb: Isolate style sheets of elements in shadow tree

- Meta/gn/secondary/Userland/Libraries/LibWeb/DOM/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/WebIDL/BUILD.gn
- Tests/LibWeb/Text/data/iframe-with-border-radius-svg.html
- Tests/LibWeb/Text/expected/border-radius-div-containing-iframe-with-border-radius-svg.txt
- Tests/LibWeb/Text/input/border-radius-div-containing-iframe-with-border-radius-svg.html
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
If the provided ID is smaller than the corner clipping vector, we would
shrink the vector to match. This causes a crash when we have nested
PaintContext instances (as these IDs are allocated by PaintContext),
each of which perform radius painting.
This is seen on https://www.strava.com/login when it loads a reCAPTCHA.
The outer div has a border radius, which contains the reCAPTCHA in an
iframe. That iframe contains an SVG which also has a border radius.
Fixes #23527
> LibWeb: Do not shrink the CPU painter's corner clipping vector

- Userland/Libraries/LibGfx/Painter.cpp
While IMO, the change makes sense on its own as flattening this function will just duplicate the code from `draw_glyph()` with no benefits, this is not what motivated this patch.
When compiling with debug information and ASAN, GCC 13.2 would issue this warning:
Userland/Libraries/LibGfx/Painter.cpp: In member function ‘void Gfx::Pai nter::draw_glyph(Gfx::FloatPoint, u32, Gfx::Color)’: Userland/Libraries/LibGfx/Painter.cpp:1354:14: note: variable tracking s ize limit exceeded with ‘-fvar-tracking-assignments’, retrying without
1354 | FLATTEN void Painter::draw_glyph(FloatPoint point, u32 code_poin
t, Color color)
|              ^~~~~~~
From what I've read online, this is caused by some limit on the number of symbols in the compiler's internal data structures. People at Google have fixed …
> LibGfx: Replace FLATTEN with ALWAYS_INLINE for `draw_glyph()` overload

- Tests/LibWeb/TestConfig.ini
These are flaky on CI, so disable them for now.
> LibWeb: Disable animations tests that depend on consistent timing

- Tests/LibWeb/Layout/expected/abspos-box-with-block-level-sibling.txt
- Tests/LibWeb/Layout/input/abspos-box-with-block-level-sibling.html
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
> LibWeb: Use the parent container's y offset when finding static position

- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Removes duplicated code that resolves position based on computed values.
No behaviour change intended.
> LibWeb: Use `resolve_grid_position` for abspos boxes layout in GFC

- Userland/Libraries/LibWeb/Animations/AnimationTimeline.cpp
- Userland/Libraries/LibWeb/Animations/AnimationTimeline.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
Fixes leakage of document in animation driver callback and animation updates running for inactive documents.
> LibWeb: Stop animation updates after navigating from document

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
If the "MMR" bit is set, the generic region decoding procedure just
uses ITU-T T.6 (2D CCITT), which we already have an implementation of.
In practice, this is used almost never in .jbig2 files and in none of
the PDFs I have.
The two files that do use MMR are:
1.) JBIG2_ConformanceData-A20180829/F01_200_TT9.jb2
2) 042_3.jb2 from the ghostpdl tests
The first uses an immediate _lossless_ generic region, which we don't
implement yet (but I think it should just forward to the normal
immediate generic region code? Not in this commit, though). The second
uses a regular immediate generic region, and we can decode it now:
Build/lagom/bin/image -o out.png \
path/to/ghostpdl/tests/jbig2/042_3.jb2
> LibGfx/JBIG2: Start implementing the generic region decoding procedure

- Ladybird/Qt/InspectorWidget.cpp
- Ladybird/Qt/InspectorWidget.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/WebContentView.h
Otherwise, the context menu is very out of position on devices with a
device pixel ratio other than 1.
> Ladybird/Qt: Adjust the Inspector context menu by the device pixel ratio

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
When navigating to about:srcdoc we try to populate the session history by calling populate_session_history_entry_document, if the resource is an about:srcdoc this method will rely on the document_resource in the SessionHistoryEntry to have a String in order for it call the right method to create navigation params.
However when navigating to about:srcdoc directly, document_resource will have an Empty, this leads populate_session_history_entry_document to call the wrong method to create navigation params.
This fixes the issue by populating document_resource with an empty string if it has an Empty and we're dealing with an about:srcdoc.
Issue: #23216
> LibWeb: Don't crash when visiting about:srcdoc

- AK/COWVector.h
- Userland/Libraries/LibRegex/RegexByteCode.cpp
- Userland/Libraries/LibRegex/RegexMatch.h
- Userland/Libraries/LibRegex/RegexMatcher.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.h
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
This applies more specifically to large wasm modules (so basically most of them in the wild), with lots of blocks and branches.
In a local test, validation perf improvement of up to 85% has been observed. effects are probably minimal overall, but startup times should be significantly shorter.
> LibWasm+AK: Make validation faster

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementDefinition.cpp
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementDefinition.h
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.h
Tiny bit of progress towards not leaking everything on Github.
> LibWeb: Use less of JS::Handle in CustomElements

- Meta/Azure/Lagom.yml
We are recently seeing SEGV crashes during the build (while running code generators) from within libasan itself. Turns out this is libasan bug seen with the Linux 6.5 kernel on Ubuntu.
> CI: Work around a libasan bug seen on Ubuntu with the Linux 6.5 kernel

- Tests/LibWeb/Text/expected/HTML/Window-opener.txt
- Tests/LibWeb/Text/input/HTML/Window-opener.html
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/Window.idl
This PR adds the [`window.opener`](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) attribute, which returns a reference to the window that opened the current window.
This property is used in a fair number of [WPT tests](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt+opener+language%3AJavaScript&type=code) and was previously causing tests to time out where it was used.
> LibWeb: Implement the `window.opener` attribute

- Userland/Games/Snake/Game.cpp
- Userland/Games/Snake/main.cpp
Recently, @OfficialPixelBrush remade the *Snake* image skin (#23467).
As the best looking skin, it deserves to be the default.
Another benefit is the color of the sprites align with the game's icon.
_**Before:**_
_**After:**_
> Snake: Set Snake as default skin

- Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
- Kernel/Net/Realtek/RTL8168NetworkAdapter.h
As in title. Please be aware that I only have NIC with chip version 6 so this is the only one that I have tested. Rest was implemented via looking at Linux rtl8169 driver.
Also thanks to IdanHo for some initial work.
> Kernel: Implement support for RTL8168 chip versions 4, 5 and 6

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
EXTTEMPLATE=1 was added later and doesn't seem to be used much in
practice -- it doesn't appear in no simple generic regions in any PDF
I tested so far at least. Since the spec contradicts itself on what
to do with these as far as I can tell, error out on them for now and
then add support once we find actual files using this, so that we can
check our implementation actually works.
Deduplicate the data reading for the different cases, and
zero-initialize all adaptive template pixels to zero to make that
possible.
Other than prohibiting EXTTEMPLATE=1, no behavior change.
> LibGfx/JBIG2: Simplify and restrict adaptive template pixel reading

- Meta/Lagom/Contrib/MacPDF/MacPDFView.h
- Meta/Lagom/Contrib/MacPDF/MacPDFView.mm
- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.h
- Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
- Meta/Lagom/Contrib/MacPDF/MainMenu.xib
PDFViewer has this, and it's useful for PDFs that have the same text both as a scanned bitmap in the background as well as using vector text in the foreground.
xib changes: Added a new menu entry connected to `toggleShowImages:`, and also toggled the initial state of two menu entries. (The latter part has no effect when the program runs since we dynamically update this state, but it makes the menu entries show their initial state in Xcode's menu editor.)
> MacPDF: Add "Show Images" debug menu entry

- Userland/Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
Fixes oss-fuzz issue [66588](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=66588).
> LibGfx/TIFF: Reject images with an incoherent number of BitsPerSample

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Meta/gn/secondary/Userland/Libraries/LibWeb/Crypto/BUILD.gn
- Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-exportKey.txt
- Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-generateKey.txt
- Tests/LibWeb/Text/input/Crypto/SubtleCrypto-exportKey.html
- Tests/LibWeb/Text/input/Crypto/SubtleCrypto-generateKey.html
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
- Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.h
- Userland/Libraries/LibWeb/Crypto/CryptoBindings.cpp
- Userland/Libraries/LibWeb/Crypto/CryptoBindings.h
- Userland/Libraries/LibWeb/Crypto/CryptoKey.h
- Userland/Libraries/LibWeb/Crypto/KeyAlgorithms.cpp
- Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
- Userland/Libraries/LibWeb/Crypto/SubtleCrypto.h
- Userland/Libraries/LibWeb/Crypto/SubtleCrypto.idl
With a bonus ASAN/UBSAN fix, and a boog fix for the previous PR.
Part of #23484
> LibWeb: Support SubtleCrypto.exportKey for RSA-OAEP in JsonWebKey format

- Tests/LibGfx/TestImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.h
I think the context normally changes for every bit. But this here is enough to correctly decode the test bitstream in Annex H.2 in the spec, which seems like a good checkpoint.
The internals of the decoder use spec naming, to make the code look virtually identical to what's in the spec. (Even so, I managed to put in several typos that took a while to track down.)
> LibGfx/JBIG2: Add arithmetic coding decoder

- Userland/Utilities/mount.cpp
Fixes 0734de9f9a1f3cd945e9df230eb52fc475810b53.
By mistake, I forgot to change this instance to "srchidden", so let's fix this.
> Userland/mount: Fix srcobfuscate => srchidden when printing mounts

- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditor.h
Add an extra gap every 4 bytes, to make it easier to keep track of where you are.
Slightly unintentionally, the gap is also visible when selecting, but I think this is actually a nice feature. I don't know if other people will share that opinion though. :laughing:
> HexEditor: Group bytes in 4s, for better readability

- AK/Span.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/CMakeLists.txt
- Ladybird/Qt/Tab.cpp
- Meta/gn/secondary/Ladybird/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn
- Tests/AK/TestSpan.cpp
- Tests/LibWeb/Text/expected/input-file-accept.txt
- Tests/LibWeb/Text/input/input-file-accept.html
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibCore/MimeData.cpp
- Userland/Libraries/LibCore/MimeData.h
- Userland/Libraries/LibGUI/FileTypeFilter.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/FileFilter.cpp
- Userland/Libraries/LibWeb/HTML/FileFilter.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Utilities/file.cpp
- Userland/Utilities/headless-browser.cpp
As used by GitHub's file upload:
> Ladybird+LibWeb: Support the `accept` attribute on `<input type=file>` elements

- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
- Userland/Libraries/LibWeb/Animations/AnimationEffect.h
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
Patch up existing style properties instead of using the regular style invalidation path, which requires rule matching for each element in the invalidated subtree.
Special handling is required for:
- !important properties: this change introduces a flag used to skip the update of animated properties overridden by !important.
- inherited animated properties: for now, these are invalidated by traversing animated element's subtree to propagate the update.
- if an animation has ended, patching is not possible, and complete invalidation of the element's style is required to remove cascaded animated properties.
> LibWeb: Add fast path for animated style properties update

- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Fixes GC-leak caused by cycle dependency between input callback and HTMLTextAreaElement that owns it.
> LibWeb: Capture weak `this` ptr in HTMLTextAreaElement input callback

- Ladybird/CMakeLists.txt
- Meta/gn/secondary/Ladybird/BUILD.gn
- Meta/gn/secondary/Ladybird/WebDriver/BUILD.gn
- Tests/LibWeb/WPT/run.sh
- Tests/LibWeb/rebaseline-libweb-test
These are standalone applications meant to be run by the user directly, as opposed to other libexec processes which are programmatically forked by the browser. To do this, we simply remove these processes from the `ladybird_helper_processes` list. We must also explicitly list the dependencies for these processes.
> Meta: Do not place headless-browser and WebDriver in libexec

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
* Handle super key combos the same as ctrl key combos for macOS
* Allow chromes to handle shortcuts after ignoring a key combo when an editable node has focus
Regarding the second commit, I have a WIP branch that continues the work of #23483 and will make these methods return an enum status - rather than having to keep remembering what true/false means here.
> LibWeb: A couple of shortcut handling fixes

- Tests/LibWeb/Text/expected/element-get-bounding-client-rect-scroll-offset.txt
- Tests/LibWeb/Text/input/element-get-bounding-client-rect-scroll-offset.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
There is no need to unconditionally resolve them whenever the function is called.
> LibWeb: Update paint-only props only when needed in get_client_rects()

- Tests/LibWeb/Layout/expected/input-placeholder.txt
- Tests/LibWeb/Layout/input/input-placeholder.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
The placeholder in the input element was not completly visible, this pr fixes that by hiding the inner text element when the placeholder is visible.
> LibWeb: Hide inner text of input element when showing placeholder

- Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp
- Userland/Libraries/LibGfx/Font/VectorFont.h
- Userland/Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp
- Userland/Libraries/LibGfx/Path.cpp
- Userland/Libraries/LibGfx/Path.h
- Userland/Libraries/LibPDF/Renderer.cpp
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPath.cpp
- Userland/Libraries/LibWeb/HTML/Path2D.cpp
- Userland/Libraries/LibWeb/SVG/SVGPathElement.cpp
Rather than make path segments virtual and refcounted let's store `Gfx::Path`s as a list of `FloatPoints` and a separate list of commands.
This reduces the size of paths, for example, a `MoveTo` goes from 24 bytes to 9 bytes (one point + a single byte command), and removes a layer of indirection when accessing segments. A nice little bonus is transforming a path can now be done by applying the transform to all points in the path (without looking at the commands).
Alongside this there's been a few minor API changes:
- `path.segments()` has been removed
* All current uses could be replaced by a new `path.is_empty()` API
* There's also now an iterator for looping over `Gfx::Path` segments
- `path.add_path(other_path)` has been removed
* This was a duplicate of `path.append_path(other_path)` …
> LibGfx: Simplify path storage and tidy up APIs

- Tests/LibWeb/Text/expected/HTML/HTMLProgressElement-detached.txt
- Tests/LibWeb/Text/expected/HTML/HTMLProgressElement-set-attributes.txt
- Tests/LibWeb/Text/input/HTML/HTMLProgressElement-detached.html
- Tests/LibWeb/Text/input/HTML/HTMLProgressElement-set-attributes.html
- Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
This PR changes to the progress element `max` and `value` attribute behavior to align it with the specification and other browsers.
> LibWeb: Ensure progress element attributes behave correctly

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebWorker/PageHost.h
Return true only if we are ready to repaint. This fixes the issue where requestAnimationFrame() was invoked more than once between repaints.
Before the fix (now it works the same as in chrome):
https://github.com/SerenityOS/serenity/assets/45686940/68bbf476-9272-41a1-aaf7-522244802a97
> LibWeb: Add basic implementation of has_a_rendering_opportunity()

- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
There is no need to run full table layout if we are only interested in calculating its width. New layout mode is needed because we can't tell if it's possible to early return only by looking at available space.
This change reduces `compute_table_box_width_inside_table_wrapper()` from ~30% to ~15% in profiles of "File changed" pages on github.
> LibWeb: Skip cells layout in table box width calculation

- Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.h
- Userland/Libraries/LibPDF/Filter.cpp
Fixes #23623
It was way harder than expected, I had to add two very small options to the decoder.
The PR is more than three times bigger than the size I called...
@nico
> LibGfx+LibPDF: Support CCITT3 1D images in PDFs

- Userland/Libraries/LibGfx/Path.cpp
- Userland/Libraries/LibGfx/Path.h
This is much more useful than the previous format, as you can now just paste the path into a site like https://svg-path-visualizer.netlify.app/ to debug issues.
> LibGfx: Output an SVG compatible string from `Path::to_byte_string()`

- Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleRule.h
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/Dump.cpp
This PR introduces a fast path version of `SelectorEngine` that only works for kinda-trivial non-recursive selectors.
Instead of recursing, it evaluates selectors through a combination of iteration and backtracking (for descendant combinators).
All these changes combined give us a 20% speed-up on the "descendant and child combinators" subtest of StyleBench.
The kind of selectors we can evaluate with the fast path are extremely common on the web. 56% of selectors evaluated while loading our GitHub repo are now done this way.
> LibWeb: Iterative fast path for non-recursive selectors

- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/StyleInvalidation.cpp
- Userland/Libraries/LibWeb/CSS/StyleInvalidation.h
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Compare only the animated properties
- Clone only the hash map containing animated properties, instead of the entire StyleProperties.
Reduces `KeyframeEffect::update_style_properties()` from 10% to 4% in GitHub profiles.
> LibWeb: Add fast path to calculate invalidations for animated css props

- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
- Userland/Libraries/LibWeb/DOM/HTMLCollection.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
Use a new DOM tree version mechanism to allow `HTMLCollection` to
remember its internal list of elements instead of rebuilding it on
every access.
This avoids thousands of full DOM walks while loading our GitHub repo.
Also ~15% speed-up on jQuery subtests in Speedometer 3.0 :^)
> LibWeb: Let HTMLCollection cache its element list

- Tests/LibWeb/Ref/reference/svg-invalid-number-arguments-ref.html
- Tests/LibWeb/Ref/reference/svg-path-incomplete-args-ref.html
- Tests/LibWeb/Ref/reference/svg-polygon-with-incomplete-points-ref.html
- Tests/LibWeb/Ref/svg-invalid-number-arguments.html
- Tests/LibWeb/Ref/svg-path-incomplete-args.html
- Tests/LibWeb/Ref/svg-polygon-with-incomplete-points.html
- Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
- Userland/Libraries/LibWeb/SVG/AttributeParser.cpp
- Userland/Libraries/LibWeb/SVG/AttributeParser.h
If an unexpected token is encountered when parsing an SVG attribute it is now immediately propagated with ErrorOr. Previously, some situations where an unexpected token was encountered could cause a crash.
This was a significant source of errors when fuzzing with Domato. After this change I haven't seen any crashes from `AttributeParser`.
As this PR was getting quite large I've left some things out. Here's some things we should do at some point
* Propagate all possible errors from `transform` functions - I left `parse_transform()` alone, as it wasn't causing crashes. It should be updated to propagate all possible errors, instead of being overly lenient.
* Report errors to the user - currently, we don't propagate parsing errors outside of `AttributeParser`. [The specification …
> LibWeb: Use ErrorOr to propagate SVG attribute parsing errors 

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.h
This value is at most 46, so a u8 is enough.
We have tens of thousands of these contexts.
(We could pack the is_mps bit into that u8 as well, but then the I() and MPS() functions need to return helper objects instead of a direct reference, so let's not do that part for now.)
> LibGfx/JBIG2: Make context index a u8

- Tests/LibWeb/Text/expected/HTML/StructuredClone-serializable-FileList.txt
- Tests/LibWeb/Text/expected/HTML/StructuredClone-serializable-objects.txt
- Tests/LibWeb/Text/input/HTML/StructuredClone-serializable-FileList.html
- Tests/LibWeb/Text/input/HTML/StructuredClone-serializable-objects.html
- Userland/Libraries/LibWeb/Bindings/Serializable.h
- Userland/Libraries/LibWeb/Crypto/CryptoKey.cpp
- Userland/Libraries/LibWeb/Crypto/CryptoKey.h
- Userland/Libraries/LibWeb/FileAPI/Blob.cpp
- Userland/Libraries/LibWeb/FileAPI/Blob.h
- Userland/Libraries/LibWeb/FileAPI/File.cpp
- Userland/Libraries/LibWeb/FileAPI/File.h
- Userland/Libraries/LibWeb/FileAPI/FileList.cpp
- Userland/Libraries/LibWeb/FileAPI/FileList.h
- Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.cpp
- Userland/Libraries/LibWeb/Geometry/DOMMatrixReadOnly.h
- Userland/Libraries/LibWeb/Geometry/DOMPointReadOnly.cpp
- Userland/Libraries/LibWeb/Geometry/DOMPointReadOnly.h
- Userland/Libraries/LibWeb/Geometry/DOMQuad.cpp
- Userland/Libraries/LibWeb/Geometry/DOMQuad.h
- Userland/Libraries/LibWeb/Geometry/DOMRectReadOnly.cpp
- Userland/Libraries/LibWeb/Geometry/DOMRectReadOnly.h
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Userland/Libraries/LibWeb/HTML/StructuredSerialize.h
This enables sub deserialization by adding the function `structured_deserialize_internal()`, we already have `structured_serialize_internal()` so no further changes is needed to enable sub serialization.
`SerializationMemory` and `DeserializationMemory` are now forwarded to `Serializable::serialization_steps()` and `Serializable::deserialization_steps()` to be used in the context of sub serialization and deseralization.
This adds serialization and deserialization steps to CryptoKey, DOMQuad, and FileList.
> LibWeb: Enable sub deserialization and add {,de}serialization steps for CryptoKey, DOMQuad, and FileList

- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
This causes compilation time with GCC to increase far too much.
> LibWeb: Remove FLATTEN attribute from SelectorEngine::fast_matches

- AK/Base64.cpp
- AK/Base64.h
- Tests/AK/TestBase64.cpp
This encoding scheme comes from section 5 of RFC 4648, as an alternative to the standard base64 encode/decode methods.
The only difference is that the last two characters are replaced with '-' and '_', as '+' and '/' are not safe in URLs or filenames.
Splitting this out from my crypto changes, as those are getting chonky and hard to manage.
> AK: Add base64url encoding and decoding methods

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-generateKey.txt
- Tests/LibWeb/Text/expected/abortsignal-abort.txt
- Userland/Libraries/LibWeb/HTML/Scripting/ExceptionReporter.cpp
As mandated in the WebIDL spec:
https://webidl.spec.whatwg.org/#js-DOMException-specialness
> LibWeb: Use correct prototype chain for DOMException, and make looking at them in the console a lot more pleasant

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
Instead of invalidating animated style properties whenever `Document::update_style()` is called, now we only do that when animations might have actually progressed. We still have to ensure animated properties are up-to-date in `update_style()` to ensure that JS methods can access updated style properties.
> LibWeb: Change update_style() to update animated style only if needed

- AK/Base64.cpp
- Meta/Lagom/CMakeLists.txt
- Userland/Utilities/base64.cpp
Using http://mattmahoney.net/dc/enwik8.zip (100MB unzipped) as a test:
Encoding runtime decreases from 1.192s to 0.303s (74.6% faster)
Decoding runtime decreases from 0.917s to 0.469s (48.9% faster)
> AK+base64: Performance improvements for base64 encoding and decoding

- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
Fixes regressed animation tests.
> LibWeb: Set animation update flag from Animation::invalidate_effect()

- Tests/LibGfx/TestImageDecoder.cpp
Instead of comparing to a reference bmp file, we accidentally were
comparing the file against itself. Luckily, after fixing this, things
still pass.
Also reorganize the tests to be more table-based. That makes it easier to add more tests later one.
> Tests/LibGfx: Fix a small typo in the jbig2 decode tests

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/HTML/button-attributes.txt
- Tests/LibWeb/Text/expected/HTML/crossOrigin-attribute.txt
- Tests/LibWeb/Text/input/HTML/button-attributes.html
- Tests/LibWeb/Text/input/HTML/crossOrigin-attribute.html
- Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.idl
Previously, the invalid value default wasn't taken into account when determining the value that should be returned from the getter of an enumerated attribute. This caused a crash when an enumerated attribute of type DOMString? was set to an invalid value.
I've also updated the values of `CrossOriginAttribute` to align it with the specification.
> LibWeb: Ensure enumerated attributes are always limited to known values

- Tests/LibWeb/Text/expected/IntersectionObserver/observe-box-inside-container-with-scrollable-overflow.txt
- Tests/LibWeb/Text/input/IntersectionObserver/observe-box-inside-container-with-scrollable-overflow.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
Fixes https://github.com/SerenityOS/serenity/issues/23631
> LibWeb: Do not include box's own scroll offset in get_client_rects()

- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/Selector.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Given a selector like `.foo .bar #baz`, we know that elements with the class names `foo` and `bar` must be present in the ancestor chain of the candidate element, or the selector cannot match.
By keeping track of the current ancestor chain during style computation, and which strings are used in tag names and attribute names, we can do a quick check before evaluating the selector itself, to see if all the required ancestors are present.
The way this works:
1. CSS::Selector now has a cache of up to 8 strings that must be present in the ancestor chain of a matching element. Note that we actually store string *hashes*, not the strings themselves.
2. When Document performs a recursive style update, we now push and pop elements to the ancestor chain stack as they are entered and exited.
3. When …
> LibWeb: Use an ancestor filter to quickly reject many CSS selectors

- Userland/Libraries/LibTLS/Socket.cpp
(NOTE: PR made from ladybird lol)
This was causing some racey behaviour in LibHTTP, and just generally lead to really bad stack traces; avoid that by switching to Core::Promise and using the existing event loop.
Possibly resolves #23524 and #23642.
> LibTLS: Avoid using new event loops when setting up connections

- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Enums.h
- Userland/Libraries/LibRIFF/ChunkID.h
Previously, ChunkID's from_big_endian_number() and
as_big_endian_number() weren't inverses of each other.
ChunkID::from_big_endian_number() used to take an u32 that contained
`('f' << 24) | ('t' << 16) | ('y' << 8) | 'p'`, that is
'f', 't', 'y', 'p' in memory on big-endian and 'p', 'y', 't', 'f'
on little-endian, and return a ChunkID for 'f', 't', 'y', 'p'.
ChunkID::as_big_endian_number() used to return an u32 that for a
ChunkID storing 'f', 't', 'y', 'p' was always 'f', 't', 'y', 'p'
in memory on both little-endian and big-endian, that is it stored
`('f' << 24) | ('t' << 16) | ('y' << 8) | 'p'` on big-endian and
`('p' << 24) | ('y' << 16) | ('t' << 8) | 'f'` on little-endian.
`ChunkID::from_big_endian_number(0x11223344).as_big_endian_number()`
returned 0x44332211.
This change makes the …
> LibRIFF+LibGfx/ISOBMFF: Make ChunkID (de)serialization self-consistent

- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.h
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Reader.cpp
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Reader.h
JPEG2000 uses this, and as far as I can tell it's also part of
ISO/IEC 14496-12.
--
With this, `isobmff` can dump .jp2 files I have flying around.
@Zaggy1024
> LibGfx/ISOBMFF: Support box header size 0 to mean "until end of data"

- Tests/LibWeb/Text/expected/DOM/Element-closest.txt
- Tests/LibWeb/Text/input/DOM/Element-closest.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
...instead of checking if all selectors match an element.
Fixes bug reduced from GitHub's "new issue" page.
> LibWeb: Change Element::closest() to check if any of selector matches

- Userland/Libraries/LibCore/EventReceiver.h
Sometimes caused a segfault when typing text in the emoji search window.
It also turned out to be unnecessary, since we would never want to write 0 to an address if it's null or after it has been set to 0 by remove_child.
32.599 CrashReporter(53:63): --- Backtrace for thread #0 (TID 52) ---
32.599 CrashReporter(53:63): 0x0000000e7dd9d86f: [/usr/lib/libcore.so.serenity] Core::EventReceiver::remove_all_children() +0x2f (EventReceiver.h:138 => EventReceiver.cpp:103)
32.599 CrashReporter(53:63): 0x0000001370418e4f: [/usr/lib/libgui.so.serenity] GUI::EmojiInputDialog::update_displayed_emoji() [clone .localalias] +0x4f (EmojiInputDialog.cpp:164)
32.604 CrashReporter(53:63): 0x0000001370429f38: [/usr/lib/libgui.so.serenity] AK::Function<void ()>::operator()() const +0x48 (Function.h:115)
32.604 …
> LibCore: Remove unnecessary or invalid write after child remove

- Tests/LibWeb/Text/expected/HTML/click-label-with-display-none-checkbox.txt
- Tests/LibWeb/Text/input/HTML/click-label-with-display-none-checkbox.html
- Userland/Libraries/LibWeb/HTML/HTMLLabelElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLabelElement.h
- Userland/Libraries/LibWeb/HTML/HTMLLabelElement.idl
- Userland/Libraries/LibWeb/Layout/Label.cpp
- Userland/Libraries/LibWeb/Layout/Label.h
- Userland/Libraries/LibWeb/Painting/TextPaintable.cpp
...because "change" event should be dispatched on control even if it has "display: none" style.
This change fixes selection in labels dropdown on GitHub's "new issue" page.
> LibWeb: Look for labeled control in DOM tree instead of layout tree

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.round.js
This is an editorial change in the temporal spec.
See: https://github.com/tc39/proposal-temporal/commit/712c449
Ticks off a box in https://github.com/SerenityOS/serenity/issues/15525
> LibJS: Separate validation of roundingIncrement option

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
This is an editorial change in the Temporal spec.
See: https://github.com/tc39/proposal-temporal/commit/60f1052
Ticks off a box in https://github.com/SerenityOS/serenity/issues/15525
> LibJS: Rename ToSecondsStringPrecision to ToSecondsStringPrecisionRecord

- AK/Enumerate.h
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Compiler/Passes/CFGBuildingPass.cpp
- Tests/AK/CMakeLists.txt
- Tests/AK/TestEnumerate.cpp
I'm sick of writing C-style loops in JSSC every time I need an index too.
I don't want to fully port JSSC to `enumerate` just yet since it will conflict with my main JSSC dev branch. I've changed one such loop though in order to not break the "unused code" rule.
The `AK::enumerate` itself is modeled loosely after C++23's std::views::enumerate but little attention was paid to the value categories and constness. We can always iterate on it in-tree when these things become an issue. First commit also introduces a bunch of stuff ~~inspired~~ copied from Ranges TS but leaves them as an implementation detail.
> AK: Introduce AK::enumerate similar to C++23's std::views::enumerate

- Tests/LibWeb/Layout/expected/inline-flex-with-aspect-ratio.txt
- Tests/LibWeb/Layout/input/inline-flex-with-aspect-ratio.html
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
If box is sized as replaced it still could be anything, not only SVG.
This fixes crashing on https://www.shopify.com/ that was caused by a missing paintable for a box that has a layout node. This occurred because the box was not laid out in dimension_box_on_line().
> LibWeb: Allow any FC type for replaced boxes in dimension_box_on_line()

- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
- Userland/Libraries/LibWebView/SourceHighlighter.cpp
Fixes #23683
First commit fixes the crash, second commit is so we can actually see the source.
View-source after the first commit:
View-source after the second commit:
> LibWeb+LibWebView: Properly handle EOF in the middle of a comment

- Tests/LibRegex/Regex.cpp
- Userland/Libraries/LibRegex/RegexParser.cpp
> LibRegex: Account for extra explicit And/Or in class parser assertion

- Userland/Shell/Parser.cpp
This adds all three common prefixes (\0, \o and \c).
> Shell: Add support for octal escapes in strings

- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Services/WebContent/PageClient.cpp
Fixes delayed repainting in the following case:
1. Style or layout invalidation triggers html event loop processing.
2. Event loop processing does nothing because there is no rendering opportunity.
3. Style or layout change won't be reflected until something else triggers event loop processing
> LibWeb: Reschedule repaint for navigables with ongoing painting

- AK/Traits.h
- Userland/Libraries/LibGfx/Font/OpenType/Font.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Font.h
- Userland/Libraries/LibGfx/Font/ScaledFont.cpp
- Userland/Libraries/LibGfx/Font/VectorFont.h
- Userland/Libraries/LibGfx/Font/WOFF/Font.h
- Userland/Libraries/LibGfx/Font/WOFF2/Font.h
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LineBox.cpp
- Userland/Libraries/LibWeb/Layout/LineBox.h
- Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
- Userland/Libraries/LibWeb/Layout/LineBuilder.h
This time we go back to the old default hash function, do less work when measuring glyph advances and avoid a vector copy.
> Yet more GitHub performance hacks

- Userland/Libraries/LibCore/EventReceiver.cpp
"Fixes" the RS crash with `!m_has_scheduled_finish`.
> LibCore: Ignore timer events after stop() has been called

- Tests/LibWeb/Ref/change-opacity.html
- Tests/LibWeb/Ref/reference/change-opacity-ref.html
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.h
...because it depends on computed values that could be changed without rebuilding paintable tree.
> LibWeb: Remove cache for Paintable::is_visible()

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
I missed putting this in #23696 while juggling local branches.
> LibGfx/JBIG2: Initialize POD members of refinement region input struct

- Meta/Azure/Lagom.yml
This reverts commit 5713c2ffdd7f0c701d7edb468d07f6cea5cd8770.
This workaround is reportedly now applied in the base image.
Fixes #23571
> CI: Revert ARCH_MMAP_RND_BITS libasan workaround

- Userland/Libraries/LibC/pthread_cond.cpp
Fix pthread_cond_broadcast() waking only one thread whereas it should wake all waiters immediately.
Uncovered while updating RVVM port which as of newly released v0.6 uses `pthread_cond_broadcast()` to shut down the IO threadpool, and would hang on exit without this patch. This port would also become an unkillable process somehow which is another issue to fix.
> LibC: Fix pthread_cond_broadcast() waking only one thread

- Userland/Applications/AnalogClock/AnalogClock.cpp
- Userland/Applications/AnalogClock/AnalogClock.h
- Userland/Applications/AnalogClock/main.cpp
```
The said time zone is local to each instance of the AnalogClock and is
separate from the system time zone.
This allows user to have clocks that use different time zones
simultaneously.
```
Wall of Clocks:
> AnalogClock: Add feature to change and show time zone

- Kernel/Arch/riscv64/Interrupts.cpp
sepc has to be incremented before the call to syscall_handler, as we otherwise would return to the ecall instruction, resulting in an infinite trap loop.
We can't increment it after syscall_handler, as sepc might get changed while handling the syscall.
> Kernel/riscv64: Handle syscalls

- Kernel/Arch/riscv64/RegisterState.h
- Kernel/Arch/riscv64/boot.S
- Kernel/Arch/riscv64/mcontext.h
- Kernel/Arch/riscv64/trap_handler.S
This required quite a bit of refactoring of the current trap handler.
The new trap handler has to be a bit spaghetti code-y, as we only have one shared trap handler for userspace and kernel.
But my comments should hopefully explain how it works.
> Kernel/riscv64: Add support for handling traps from userspace

- Kernel/Arch/PageFault.cpp
- Kernel/Arch/PageFault.h
- Kernel/Arch/riscv64/Interrupts.cpp
- Kernel/Memory/Region.cpp
- Userland/Applications/CrashReporter/main.cpp
With this PR, #23364 and #23359 merged and using u-boot to boot serenity, we now panic during the `exec` for SystemServer!
> Kernel/riscv64: Don't hard-code the page fault reason on RISC-V

- Kernel/Arch/init.cpp
- Kernel/Arch/riscv64/Delay.cpp
- Kernel/Arch/riscv64/Delay.h
- Kernel/Arch/riscv64/Processor.cpp
- Kernel/Arch/riscv64/Processor.h
This PR includes all necessary changes to make the NVMe driver work on RISC-V.
> Kernel/riscv64: Make the NVMe driver work on riscv64

- Kernel/Arch/riscv64/Interrupts.cpp
Always enabling interrupts is in hindsight obviously a bug, as trapping code that has interrupts disabled very likely expects that they stay disabled during trap handling as well.
The interrupt state will already correctly be restored on trap exit.
It would be nicer if we wouldn't have to keep interrupts disabled for potentially quite some time, but x86 is also keeping interrupts disabled if they were disabled while handling page faults.
This used to cause a panic when the following things happened:
user context switch (scheduler lock held) -> signal dispatch -> writing signal info to stack causes page fault -> while handling page faults interrupts are enabled -> timer interrupt -> deferred calls get executed -> thread block timer expects scheduler lock isn't locked -> :^(
> Kernel/riscv64: Only enable interrupts in trap handler if they were on

- Kernel/Arch/riscv64/boot.S
This allows us to boot via U-Boot's booti command.
> Kernel/riscv64: Add Linux boot header

- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/PromiseJobs.cpp
- Userland/Libraries/LibJS/Runtime/PromiseJobs.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
This is a speculative fix for a flake seen on CI where a JobCallback captured by a PromiseJob callback was GC'd prematurely.
> LibJS: Make PromiseJob store callback as a HeapFunction

- Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
- Userland/Libraries/LibWeb/DOM/AbortSignal.h
- Userland/Libraries/LibWeb/Fetch/Request.cpp
- Userland/Libraries/LibWeb/Fetch/Request.h
Since the introduction of `AbortSignal::any()`, the specification says `AbortSignal::create_dependent_abort_signal()` should be used where `AbortSignal::follow` was previously.
I made this change blindly assuming that it would fix a crash we're seeing in http://arstechnica.com.
It did not :sob:
> LibWeb/Fetch: Replace usages of AbortSignal::follow() in Fetch::Request 

- Meta/gn/secondary/Tests/LibWeb/BUILD.gn
- Tests/LibWeb/CMakeLists.txt
- Tests/LibWeb/TestFetchInfrastructure.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP.cpp
We were off-by-one when returning the result of parsing a quoted string in `Web::Fetch::Infrastructure::collect_an_http_quoted_string`. Instead of backtracking the lexer and consuming the backtracked string, do a simple substring operation.
> LibWeb: Return the correct substring when parsing an HTTP quoted string

- Userland/Libraries/LibCrypto/Cipher/Mode/Mode.h
This is in line with what the spec states, the previous implementation excluded the case where the original message's length is a multiple of block_size, which would lead to a full block of padding.
> LibCrypto: Allow CMS padding to span an entire block

- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
No effective change, as ValidateTypedArray would call the validation AO that the spec wants us to call manually. But no need to do it twice.
> LibJS: Do not unnecessarily revalidate a TypedArray

- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.cpp
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Boxes.h
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.h
- Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/Reader.cpp
No real behavior change. `isobmff` now prints some more output on jpeg2000 inputs.
> LibGfx/ISOBMFFF: Add two more jpeg2000 boxes

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
This should only happen on either invalid inputs or if our code has
a bug (gasp!). Printing an error instead of asserting seems nicer.
---
Probably also good for the fuzzer.
> LibGfx/JBIG2: Don't assert on unexpected OOB values in the bitstream

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
This is an editorial change in the Temporal spec.
See: https://github.com/tc39/proposal-temporal/commit/aca38be
Ticks off a box in https://github.com/SerenityOS/serenity/issues/15525
> LibJS: Remove ToTemporalDateTimeRoundingIncrement

- Tests/LibWeb/TestConfig.ini
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This is like my third attempt to get animation-play-state working correctly, so let's hope it actually sticks this time. Note that the new way this test works also functions as a test for the new `animation-play-state` behavior, as the test does not pass without these changes.
> LibWeb: Fix my flakey test case + another fix for animation-play-state

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
I found this interesting, and it also explains e.g. why some of the step numbers in 6.4 Text Region Decoding Procedure are off -- they added step 3) for COLEXTFLAG and forgot to update step references to later steps.
> LibGfx/JBIG2Loader: Add a short comment with spec history

- Userland/Utilities/headless-browser.cpp
```
For the normal non-test use case of headless-browser, the function 
`load_page_for_screenshot_and_exit()` didn't actually load the requested
webpage in the `WebView`, resulting in an all white pixels screenshot.
```
Next issue is that the screenshot produced isn't 800x600 size. The height is as big as the whole webpage.
> headless-browser: Don't forget to load webpage before taking screenshot

- Userland/Shell/Formatter.h
```
When the command line consists of only whitespace characters, the auto
formatter basically tries to trim the trailing whitespace. But due to a
subtle bug of decrementing an iterator (which is an unsigned integer)
past 0 (or the start of the buffer), that operation resulted in an index
out of bounds error and a crash.
```
Why no reverse iterator for `StringView`?
This behaviour is unexpected if you want leading whitespace command lines to not get added to the history.
> Shell: Correctly auto format command lines consisting of only whitespace

- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/Tab.mm
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
- Meta/gn/secondary/Ladybird/BUILD.gn
- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/IconBag.cpp
- Userland/Applications/Browser/IconBag.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibGUI/TabWidget.cpp
- Userland/Libraries/LibGUI/TabWidget.h
- Userland/Libraries/LibWeb/HTML/AudioPlayState.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
Modern browsers display some indicator on tabs that are playing audio, which I've always found nice, so this adds the same feature to Ladybird. The indicator is added as a button, though currently disabled. In the future, this button can be used to e.g. mute the tab.
Serenity:
https://github.com/SerenityOS/serenity/assets/5600524/7605dcbe-7598-4552-a1d2-8de66609ce85
Qt:
https://github.com/SerenityOS/serenity/assets/5600524/d33ccec5-c860-4477-b8fe-59649002bccd
AppKit:
https://github.com/SerenityOS/serenity/assets/5600524/33f82c65-bc48-49cf-b443-2c9095dcae2b
> Ladybird: Display an audio button on tabs that are playing audio

- Base/usr/share/man/man1/Applications/ImageViewer.md
- Userland/Applications/ImageViewer/CMakeLists.txt
Restore ImageViewer's new application icon, which was accidentally changed back to using the filetype icon by e800605ad3e4e9dfdc320c137e1beef1a66d2eb0.
Additionally, use the correct icon in the ImageViewer manpage.
> Base+ImageViewer: Restore correct app icon

- Tests/LibWeb/Layout/expected/top-layer.txt
- Tests/LibWeb/Layout/input/top-layer.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.h
Implements the "top layer" concept from "CSS Positioned Layout Module Level 4" specification.
- The tree builder is modified to ensure that layout nodes created by top layer elements are children of the viewport.
- Implements missing steps in `showModal()` to add an element top top layer.
- Implements missing steps in `close()` to remove an element from top layer.
Further steps could be:
- Add support for `::backdrop` pseudo-element.
- Implement the "inert" concept from HTML spec to block hit-testing when element from top layer is displayed.
With these changes we support displaying side panel on GitHub:
> LibWeb: Add basic "top layer" support

- Tests/LibWeb/Layout/expected/empty-image-should-be-zero-sized.txt
- Tests/LibWeb/Layout/expected/floating-replaced-element-percentage-padding-against-indefinite-width.txt
- Tests/LibWeb/Layout/expected/misc/corner-radius.txt
- Tests/LibWeb/Layout/expected/svg/svg-as-image-invalid.txt
- Tests/LibWeb/Layout/input/empty-image-should-be-zero-sized.html
- Userland/Libraries/LibWeb/Layout/ImageBox.cpp
This matches the behavior of other browsers.
Visual progression on https://futo.org
Before:
After:
> LibWeb: Make empty images (no bitmap, no alt text) take no layout space

- Meta/gn/secondary/Ladybird/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibCore/BUILD.gn
- Userland/Libraries/LibCore/CMakeLists.txt
We were able to keep LibCoreMinimal a bit smaller as an object library, but that is causing ODR violations in the fuzzer build (realistically, should be an issue in all builds, but only the fuzzer actively complains for some reason).
To make it a shared library, we have to add a couple more symbols to it, and make LibCore publicly depend on it.
> LibCore: Turn LibCoreMinimal into a normal shared library

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Tests/null-or-undefined-access.js
When a `GetById` / `GetByValue` / `PutById` / `PutByValue` bytecode operation results in accessing a nullish object, we now include the name of the property and the object being accessed in the exception message (if available). This should make
it easier to debug live websites.
For example, the following errors would all previously produce a generic error message of "ToObject on null or undefined":
```js
> foo = null
> foo.bar
Uncaught exception:
[TypeError] Cannot access property "bar" on null object "foo"
at <unknown>
> foo.bar = 1
Uncaught exception:
[TypeError] Cannot access property "bar" on null object "foo"
at <unknown>
```
```js
> foo = { bar: undefined }
> foo.bar.baz
Uncaught exception:
[TypeError] Cannot access property "baz" on undefined object "foo.bar"
at <unknown>
> …
```
> LibJS: Include identifier information in nullish property access

- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
Reduces the amount of code needed to add a new IPC by just a few lines on each side of the pipe, but that adds up to quite a bit here, and makes things simpler IMO.
> LibWebView+WebContent: Reduce IPC boilerplate

- Tests/LibWeb/Text/expected/WebAnimations/transitions/parse-transition-property.txt
- Tests/LibWeb/Text/input/WebAnimations/transitions/parse-transition-property.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Accidentally added this in #23762
> LibWeb: Fix infinite loop in CSS::Parser::parse_transition_value()

- Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/Layout/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/Painting/BUILD.gn
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
The current location of the IPC invocation is often too soon. We reach it before the audio file has completely finished downloading / loading, thus there isn't an `AudioTrack` object yet.
Instead, wait until we are actually playing the audio to invoke the IPC.
This is particularly frequent on bandcamp.
> LibWeb: Don't attempt to notify chromes about audio playing until ready

- Tests/LibWeb/Text/data/iframe-reload.html
- Tests/LibWeb/Text/expected/navigation/location-reload-fetch.txt
- Tests/LibWeb/Text/expected/navigation/location-reload-srcdoc.txt
- Tests/LibWeb/Text/expected/navigation/remove-iframe-from-timeout-callback.txt
- Tests/LibWeb/Text/input/navigation/location-reload-fetch.html
- Tests/LibWeb/Text/input/navigation/location-reload-srcdoc.html
- Tests/LibWeb/Text/input/navigation/remove-iframe-from-timeout-callback.html
- Userland/Libraries/LibWeb/HTML/DocumentState.cpp
- Userland/Libraries/LibWeb/HTML/DocumentState.h
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.cpp
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
While waiting for a task that populates a session history entry, we can't limit the processing of the event loop to the `NavigationAndTraversal` task source. This is because fetching uses the `Networking` task source, which also needs to be processed.
Since making a fetch request might take some time, we want to process everything on the event loop while waiting, to avoid blocking user interactions.
It is still possible to use `spin_processing_tasks_with_source_until()` on subsequent steps of `apply_the_history_step()`.
> LibWeb: Fix endless spinning in apply_the_history_step()

- Ladybird/AppKit/UI/Tab.mm
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Userland/Libraries/LibWeb/HTML/AudioPlayState.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/WebContentServer.ipc
We already display a speaker icon on tabs which are playing audio. This allows the user to click that icon to mute the tab, at which point the icon is replaced with a muted speaker icon.
We would previously hide the icon when audio stopped playing. We now do this only if the tab isn't muted. If it is muted, the muted speaker icon remains on the tab so that the page isn't stuck in a muted state.
Note: This is only supported in the Qt and AppKit chromes currently. The Serenity chrome will require more `GUI::TabWidget` work to make the speaker icon an actual button.
Qt (I couldn't get OBS to capture the tooltip on hover, but I promise it's there):
https://github.com/SerenityOS/serenity/assets/5600524/aa0e392c-bdeb-4049-9e12-fa56015eadce
AppKit (audio recorded on a microphone so it doesn't …
> Ladybird+LibWeb: Support muting an entire page

- Meta/Lagom/CMakeLists.txt
The fuzzer build has been failing for the past 4 days: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#serenity
> Meta: Fix the oss-fuzz build

- Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp
This aligns us with the current spec steps for serializable objects in StructuredSerializeInternal.
> LibWeb: Correct spec steps for serializable objects

- Tests/LibWeb/Ref/assets/nested-svg.svg
- Tests/LibWeb/Ref/nested-svg-as-img.html
- Tests/LibWeb/Ref/reference/nested-svg-as-img-ref.html
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Going via the `ViewportPaintable` missed some steps (in particular computing clip rects), which meant nested SVGs within SVGs-as-images were completely clipped.
This restores the rocket logo on the azure pipelines badge:
**Before:**
**After:**
> LibWeb: Paint `SVGDecodedImageData` via `Navigable::paint()`

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
This PR makes sure we interact with the correct tab when an audio play state changes and when clicking an audio icon on a tab. And makes sure we don't completely replace the "close tab" button on macOS.
> Ladybird/Qt: A couple of audio state button fixes specific to the Qt chrome

- Ports/OpenJDK/patches/0008-java.base-Enable-java.lang.Process-on-serenity.patch
- Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
- Ports/SDL2_image/package.sh
- Ports/SDL2_mixer/package.sh
- Ports/SDL2_ttf/package.sh
- Ports/Super-Mario/patches/0003-Use-pkgconfig-instead-of-find_package-to-look-for-de.patch
- Ports/c-ray/patches/0004-Link-with-the-needed-serenity-libraries.patch
- Ports/nesalizer/patches/0001-Add-Serenity-to-Makefile.patch
- Ports/nesalizer/patches/ReadMe.md
- Ports/openssh/package.sh
- Ports/perl5/patches/0003-configure-Add-hint-for-serenity.patch
- Ports/xmp-cli/patches/0001-Add-support-for-Serenity-LibAudio.patch
Looks like we need to be explicit for make-based ports.
I was not able to test the following ports as they depend on xz:
* OpenJDK
* SDL2_image
* Super-Mario
And xz is currently unavailable due to the backdoor mayhem.
```
=> Fetching xz...
[xz/fetch] Downloading URL: https://tukaani.org/xz/xz-5.4.4.tar.gz
[xz/fetch] /usr/bin/curl
[xz/fetch] + curl https://tukaani.org/xz/xz-5.4.4.tar.gz -L -o /home/flynn/workspace/serenity/Ports/xz/xz-5.4.4.tar.gz (nocd)
[xz/fetch]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[xz/fetch]                                  Dload  Upload   Total   Spent    Left  Speed
100   262  100   262    0     0    521      0 --:--:-- --:--:-- --:--:--   520
100  107k    0  107k    0     0   157k      0 --:--:-- --:--:-- --:--:--  157k …
```
> Ports: Update ports that depend on LibCore to depend on LibCoreMinimal

- Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
We've been reading `segment_page_association_size_is_32_bits` a bit further down for a while now.
> LibGfx/JBIG2: Remove a now-unneeded void cast

- Tests/LibWeb/Text/expected/HTML/WindowProxy-Get-after-detaching-from-browsing-context.txt
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
These changes do not solve hanging `location.reload()` and `location.go()` but only align implementation with the latest edits in the specification.
`WindowProxy-Get-after-detaching-from-browsing-context` test output is affected because `iframe.remove();` no longer synchronously does destruction of a document, but queues a task on event loop.
> LibWeb: Catch up with the spec on document destroy, abort and unload

- Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
- Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Instead of a new copy each time. On a synthentic benchmark of a page with ~500 link elements, this results in a 45% percent speedup on my machine.
```html
<body>
<ul>
<li><a href="#">Link 1</a></li>
...
<li><a href="#">Link N</a></li>
</ul>
<script>
window.onload = function() {
const startTime = performance.now();
for (let i = 0; i < 1_000_000; ++i) {
const numLinks = document.links.length;
}
const endTime = performance.now();
const timeTaken = endTime - startTime;
console.log(timeTaken);
};
</script>
</body>
</html>
```
> LibWeb: Avoid copying cached elements in HTMLCollection 

- Userland/Libraries/LibPDF/Renderer.cpp
We used to expand every bit in an 1bpp image to a 0 or 255 byte,
then map that to a float that's either 0.0f or 1.0f (or whatever's
in /DecodeArray), then multiply that by 255.0f to convert it to a
u8 and put that in the rgb channels of a Color.
Now we precompute the two possible outcomes (almost always Black
and White) and do a per-bit lookup.
Reduces time for
Build/lagom/bin/pdf --render-bench --render-repeats 20 --page 36 \
~/Downloads/Flatland.pdf
(the "decoded data cached" case) from 3.3s to 1.1s on my system.
Reduces time for
Build/lagom/bin/pdf --debugging-stats ~/Downloads/0000/0000231.pdf
(the "need to decode each page" case) from 52s to 43s on my machine.
Also makes paging through PDFs that contain a 1700x2200 pixel CCITT
or JBIG2 bitmap on each page noticeably snappier.
> LibPDF: Add a fastpath for 1bpp grayscale to load_image()

- Userland/Libraries/LibJS/Heap/GCPtr.h
This avoids the potential for unwanted implicit conversions to bool. It doesn't prevent if (m_ptr) checks though, as that invokes an explicit conversion to bool. This is how std::unique_ptr and std::optional work.
> LibJS: Mark GCPtr's operator bool as explicit

- Ladybird/AppKit/main.mm
- Ladybird/CMakeLists.txt
- Ladybird/HelperProcess.cpp
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/TaskManagerWindow.cpp
- Ladybird/Qt/TaskManagerWindow.h
- Ladybird/Qt/main.cpp
- Ladybird/cmake/ResourceFiles.cmake
- Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/BrowserWindow.h
- Userland/Applications/Browser/CMakeLists.txt
- Userland/Applications/Browser/IconBag.cpp
- Userland/Applications/Browser/IconBag.h
- Userland/Applications/Browser/TaskManagerWidget.cpp
- Userland/Applications/Browser/TaskManagerWidget.h
- Userland/Applications/Browser/main.cpp
- Userland/Libraries/LibWebView/CMakeLists.txt
- Userland/Libraries/LibWebView/Forward.h
- Userland/Libraries/LibWebView/ProcessHandle.cpp
- Userland/Libraries/LibWebView/ProcessHandle.h
- Userland/Libraries/LibWebView/ProcessManager.cpp
- Userland/Libraries/LibWebView/ProcessManager.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/WebContentClient.ipc
This simplistic implementation is just the UI part: it doesn't do any grabbing of per-process information yet.
AppKit was left as an exercise for ~~the reader~~ Tim :)
The UI also splats the information into a simple WebView widget instead of creating a native Table view for each chrome. If the performance penalty from having a web UI for this becomes annoying, we can probably port it in a straightforward way to native widgets, assuming the models and views are not too complex.
> Ladybird: Add a simple process manager widget to track helper processes

- Ladybird/Qt/BrowserWindow.cpp
- Meta/gn/secondary/Ladybird/BUILD.gn
If the left-hand side of the tab is already occupied with an audio state button, we would add a second button to the right-hand side. Prevent that by checking if the occupant is our audio state button.
> Ladybird/Qt: Prevent adding multiple audio state buttons

- Meta/jbig2_to_pdf.py
jbig2 data in PDFs is in the embedded organization, which is like the sequential organization with the file header removed.
That means jbig2 files using the random-access organization need to be transformed to be supported. A random-access jbig2 has all segment headers at the start, followed by the data of all segments. Decode all headers and rewrite them to the sequential organization, where each segment header is followed by that segment's data.
The motivation is that almost all of the jbig2 files in ghostpdl/test/jbig2 use the random-access organization.
And since we're now  parsing segment headers for random-access jbig2 inputs already, just always do that and get the image dimensions from the PageInformation segment data. Not all that much more code, and it makes this script much …
> Meta/jbig2_to_pdf.py: Allow jbig2 files with random-access organization

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/PerformanceObserver/PerformanceObserver-supportedEntryTypes.txt
- Tests/LibWeb/Text/input/PerformanceObserver/PerformanceObserver-supportedEntryTypes.html
- Userland/Libraries/LibIDL/IDLParser.cpp
- Userland/Libraries/LibIDL/IDLParser.h
- Userland/Libraries/LibIDL/Types.h
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
- Userland/Libraries/LibWeb/PerformanceTimeline/PerformanceObserver.cpp
- Userland/Libraries/LibWeb/PerformanceTimeline/PerformanceObserver.h
- Userland/Libraries/LibWeb/PerformanceTimeline/PerformanceObserver.idl
LibIDL+LibWeb: Add support for static readonly attributes
Support for settable attributes is a FIXME.
-----
LibWeb: Implement PerformanceObserver.supportedEntryTypes
> LibWeb: Implement PerformanceObserver.supportedEntryTypes 

- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
See for more details whatwg/html#10242
Before this change it only worked because of another bug in
`EventLoop::spin_processing_tasks_with_source_until()`
where we execute tasks regardless of whether they are runnable or not.
> LibWeb: Fix spec bug in "destroy child navigable"

- AK/Platform.h
- Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
This should fix the gigantic list of false positives dumped by LeakSanitizer on exit .
> LibJS+AK: Register GC memory as root regions for LeakSanitizer

- Userland/Libraries/LibWeb/WebIDL/Promise.h
SafeFunction was causing massive GC reference cycles here and leaking entire realms as a result.
Since we end up storing these reaction steps in a JS::NativeFunction (which uses JS::HeapFunction internally) there should be no need to protect the captures with SafeFunction.
This dramatically shrinks our memory footprint while running tests.
> LibWeb: Don't use JS::SafeFunction for WebIDL promise reaction steps

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
> LibWeb: Don't load fallback icon for SVG documents

- Userland/Libraries/LibC/unistd.cpp
Previously we weren't checking for nullptr from `malloc()` and we can precompute length of directory name instead of calling `strlen()` thrice in every loop iteration.
> LibC: Minor improvements in `ttyname_r_for_directory()`

- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
f66d33423bb3ce0526949668d6769e32f76d1908 was not sufficient to ensure document destruction when a child navigable is destroyed. This is because a navigable was remove from the set of all navigables too early which led to `Navigable::navigable_with_active_document()` being unable to find a navigable that is still in the process of destruction.
This change solves that by making all steps of a navigable destruction to happen in afterAllDestruction callback.
Unfortunately, writing a test to verify document destruction is challenging because no events are emitted to indicate that it has happened.
> LibWeb: Fix "destroy the child navigable" to call `Document::destroy()`

- Tests/LibWeb/Text/expected/fetch-request-url-search-params.txt
- Tests/LibWeb/Text/input/fetch-request-url-search-params.html
- Userland/Libraries/LibWeb/Fetch/BodyInit.cpp
With this, we can log into spotify, but get the following exceptions when landing on the home page:
```
33840.190 WebContent(220180): Unhandled JavaScript exception (in promise): [undefined] undefined
33840.334 WebContent(220180): Unhandled JavaScript exception (in promise): [EMEError] Platform does not support navigator.requestMediaKeySystemAccess
33840.334 WebContent(220180):     at Error
at v (https://open.spotifycdn.com/cdn/build/mobile-web-player/vendor~mobile-web-player.c7c1f610.js:1:301915)
at fatal (https://open.spotifycdn.com/cdn/build/mobile-web-player/vendor~mobile-web-player.c7c1f610.js:1:302176)
at https://open.spotifycdn.com/cdn/build/mobile-web-player/vendor~mobile-web-player.c7c1f610.js:1:325898
at Promise
at create …
```
> LibWeb: Avoid UAF when encoding a fetch request body via URLSearchParams

- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
This is a layering violation, and is not used. Caught by the gn build.
> LibWeb: Remove WebContent include from SVGDecodedImageData

- Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchAlgorithms.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
clang doesn't make all `Base::visit_edges()` calls `CXXMemberCallExprs`. This would lead to false positives like in HeapFunction, where the matcher would fail to match and report a warning.
Also previously the matcher would succeed if the visited class is missing the call to `Base::visit_edges()` but an included class has a correct method.
The new matcher checks the current class for declarations of `visit_edges`-methods and matches all `visit_edges`-memberExprs inside, checking for one starting with `Base::`.
This seems to get rid of the false positives and should be more correct detecting missing calls.
For consistency missing `Base::visit_edges()`-calls in `visit_edges` of FetchAlgorithms and Navitables were added too, although they are empty.
Should fix #23790
> LibJSGCVerifier+LibJS: Fix false positives in HeapFunction::visit_edges

- Userland/Libraries/LibWebView/Platform/ProcessStatisticsLinux.cpp
I noticed the task manager showed 0.0% CPU for all processes for me.
Turns out my `total_time_scheduled` is around `18446744073652762114` after 46d uptime.
Doing `18446744073652762114-18446744073652758919` in float results in `0` when it should be `3195`.
> LibWebView: Avoid CPU% precision loss by doing the float cast later

- Tests/LibWeb/Layout/expected/input-file.txt
- Tests/LibWeb/Layout/expected/input-image-to-text.txt
- Tests/LibWeb/Layout/expected/input-password-to-text.txt
- Tests/LibWeb/Layout/expected/input-placeholder.txt
- Tests/LibWeb/Layout/expected/input-text-to-image.txt
- Tests/LibWeb/Layout/expected/input-text-to-password.txt
- Tests/LibWeb/Layout/input/input-file.html
- Tests/LibWeb/Layout/input/input-image-to-text.html
- Tests/LibWeb/Layout/input/input-password-to-text.html
- Tests/LibWeb/Layout/input/input-placeholder.html
- Tests/LibWeb/Layout/input/input-text-to-image.html
- Tests/LibWeb/Layout/input/input-text-to-password.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
This makes us respond to the `type` attribute changing, and handles some fallout from the shadow tree now being more dynamic.
As seen on Spotify - the password field as a visibility toggle that flips the type between "password" and "text":
https://github.com/SerenityOS/serenity/assets/5600524/2be970af-45b7-4d03-ba8a-b1fdc13c78e9
> LibWeb: Handle dynamic changes to HTMLInputElement's `type` attribute

- Userland/Services/RequestServer/ConnectionCache.cpp
Part of this issue was fixed in 89877b3f406aaf0290cc98e122cab285c1175df6 but that only addressed the first layer of deferred_invoke, ignoring the second one (which would cause a race if a request was sent to a host immediately following a timeout event from the same host). Fixes #23840.
> RequestServer: Avoid race condition between timeout and socket creation

- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Supports.cpp
- Userland/Libraries/LibWeb/CSS/Supports.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/Fetch/Infrastructure/Task.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/Task.h
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
- Userland/Libraries/LibWeb/HTML/EventLoop/Task.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/Task.h
- Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
- Userland/Libraries/LibWeb/WebAudio/AudioContext.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioContext.h
- Make HTML's EventLoop, TaskQueue and Task all be GC-allocated
- Fix a GC realm leak in CSS `@supports` rules
> LibWeb: More work on GC leaks

- Userland/Libraries/LibCore/LocalServer.cpp
- Userland/Libraries/LibCore/Socket.h
- Userland/Libraries/LibWeb/HTML/MessagePort.cpp
While this is the default for an underlying socket, it doesn't seem good
to have this as the default for our socket wrapper.
This fixes a crash in ladybird when connecting to the python HTTP server
with HTTPS.
> LibCore: Prevent SIGPIPE on Sockets by default

- Userland/Libraries/LibURL/Parser.cpp
20% of CPU usage when loading https://utah.edu/ was spent doing these ASCII conversions in URL parsing.
> LibURL: Avoid expensive IDNA::to_ascii() for all-ASCII domain strings

- Meta/Lagom/Wasm/js_repl.cpp
- Userland/Applications/Spreadsheet/Spreadsheet.cpp
- Userland/Libraries/LibJS/Contrib/Test262/262Object.cpp
- Userland/Libraries/LibJS/ParserError.cpp
- Userland/Libraries/LibJS/ParserError.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Range.cpp
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/ModuleScript.cpp
- Userland/Libraries/LibWeb/HTML/Worker.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/WebGL/WebGLContextAttributes.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
- Userland/Utilities/js.cpp
A bunch of this is leftover from pre porting over to new AK::String. For example, for functions which previously took a ByteString const& now accepting a StringView.
Other places can have a relatively straightforward substituion of ByteString to String.
> LibWeb: Remove a bunch of calls to `to_byte_string`

- Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.cpp
- Userland/Libraries/LibJS/Heap/GCPtr.h
- Userland/Libraries/LibJS/Heap/HeapBlock.h
- Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp
- Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.h
- Userland/Libraries/LibJS/Runtime/RegExpObject.cpp
- Userland/Libraries/LibJS/Runtime/RegExpObject.h
- Userland/Libraries/LibJS/Runtime/WeakSet.h
- Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
- Userland/Libraries/LibWeb/Animations/AnimationEffect.h
- Userland/Libraries/LibWeb/HTML/AudioTrackList.cpp
- Userland/Libraries/LibWeb/HTML/AudioTrackList.h
- Userland/Libraries/LibWeb/HTML/VideoTrackList.cpp
- Userland/Libraries/LibWeb/HTML/VideoTrackList.h
- Userland/Libraries/LibWeb/MathML/MathMLElement.cpp
- Userland/Libraries/LibWeb/MathML/MathMLElement.h
Previously we would only warn about missing calls to visit inside visit_edges implementations, now we warn as well when there's no visit_edges implementation at all. (Resolves #23848)
Also fixes a couple of the new warnings that show up as a result.
> LibJSGCVerifier: Warn about missing visit_edges impls with GC members

- AK/FlyString.h
The member function `equals_ignoring_ascii_case` has a fast path which will return early if it is the same FlyString instance.
> AK: Simplify and optimize ASCIICaseInsensitiveFlyStringTraits::equals

- Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp
- Userland/Libraries/LibUnicode/Normalize.cpp
- Userland/Libraries/LibUnicode/Normalize.h
These 2 changes bring the runtime of Tim's test case from 70 seconds to 80 milliseconds on my machine.
Resolves #23863.
> LibUnicode: Optimize the canonical composition algorithm implementation

- Tests/LibWeb/Text/expected/WebAnimations/transitions/parse-transition-calc-duration-delay.txt
- Tests/LibWeb/Text/input/WebAnimations/transitions/parse-transition-calc-duration-delay.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/TransitionStyleValue.h
As the parser was trying to directly unwrap an unresolved duration. Currently we are outputting the wrong results for the serialized duration, but this is still a step forwards.
Fixes a crash seen on: https://evaparish.com/blog/how-i-edit
> LibWeb: Fix crash for calculated transition duration/delays

- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeTo-cannot-pipe-locked-stream.txt
- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeTo-cannot-pipe-to-locked-stream.txt
- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeTo.txt
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeTo-cannot-pipe-locked-stream.html
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeTo-cannot-pipe-to-locked-stream.html
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeTo.html
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStream.h
- Userland/Libraries/LibWeb/Streams/ReadableStream.idl
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
Currently the implementation of AO `readable_stream_pipe_to()` is quite naive compared to the guidelines in the spec and will a need a few iterations before it's up to par with the spec.
Also worth a note, to be able to write the chunks to `WritableableStream` in the same order they are read from `ReadableStream`, the `ByteBuffer` in `ReadLoopReadRequest` is now a `Vector<ByteBuffer>`. With that change we reflect the behavior of other browsers.
> LibWeb: Implement ReadableStream.pipeTo()

- Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
- Userland/Services/Clipboard/ClipboardServer.ipc
- Userland/Services/RequestServer/RequestClient.ipc
- Userland/Services/RequestServer/RequestServer.ipc
- Userland/Services/WebContent/WebContentServer.ipc
- Userland/Services/WindowServer/WindowClient.ipc
- Userland/Services/WindowServer/WindowServer.ipc
This PR includes a couple of changes to `IPCCompiler` that improve parameter type parsing:
* Parameter types can now contain spaces (like `HashMap<String, String>`, for example).
* An error is now shown if a parameter is given without a name.
Fixes #23744
> IPCCompiler: Improve parsing of parameter types

- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeThrough-cannot-pipe-locked-stream.txt
- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeThrough-cannot-pipe-to-locked-stream.txt
- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeThrough.txt
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeThrough-cannot-pipe-locked-stream.html
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeThrough-cannot-pipe-to-locked-stream.html
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeThrough.html
- Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStream.h
- Userland/Libraries/LibWeb/Streams/ReadableStream.idl
This implements `ReadableStream.pipeThrough()` and adds test to prove we can successfully pipe through a transform stream.
> LibWeb: Implement ReadableStream.pipeThrough()

- Meta/Lagom/Tools/LibJSGCVerifier/src/CellsHandler.cpp
- Userland/Libraries/LibJS/Runtime/Map.cpp
- Userland/Services/WebContent/ConsoleGlobalEnvironmentExtensions.cpp
A JS::Value can refer to a GC-allocated object, so let's ensure they are visited when necessary.
Also fix two issues found by adding this check.
> LibJSGCVerifier: Warn on missing visit of JS::Value members

- Userland/Libraries/LibCrypto/Cipher/Cipher.h
- Userland/Libraries/LibCrypto/Cipher/Mode/GCM.h
This is disallowed as from C++20. GCC 14 gives an error for these two.
See:
https://cplusplus.github.io/CWG/issues/2237.html
https://stackoverflow.com/questions/71978335/class-templates-constructor-declaration-doesnt-compile-for-c20-but-compiles
> LibCrypto: Remove simple-template-id from constructors

- Tests/LibWeb/Text/expected/navigation/populate-iframe-using-document-write.txt
- Tests/LibWeb/Text/input/navigation/populate-iframe-using-document-write.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
If initial src of an iframe is "about:blank", it does synchronous navigation that is not supposed to be interleaved by other navigation or usage of Document.open().
Fixes crashing in navigation on https://twinings.co.uk/
> LibWeb: Wait for initial navigation to complete before modifying iframe

- Tests/LibWeb/Layout/expected/css-namespace-tag-name-selector.txt
- Tests/LibWeb/Layout/expected/svg/svg-g-inside-g.txt
- Tests/LibWeb/Layout/expected/svg/svg-symbol-with-viewbox.txt
- Tests/LibWeb/Layout/expected/svg/use-honor-outer-viewBox.txt
- Tests/LibWeb/Layout/input/svg/svg-g-inside-g.html
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.h
Doing multiple `for_each_in_subtree()` passes was kind of a hack. We can resolve everything in a single pass with a little more control over the layout process. This also fixes a few minor issues like the sizing of nested `<g>` elements.
More work is needed here though as this is still fairly ad-hoc.
Note: This does regress `css-namespace-tag-name-selector.html`, previously SVG text within `<a>` elements would appear. However, this was only because `for_each_in_subtree()` would blindly look through the InlineNodes from the unimplemented `SVGAElement`s.
> LibWeb: Split `SVGFormattingContext` up into functions

- Base/res/html/misc/select.html
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Tests/LibWeb/Text/expected/select.txt
- Tests/LibWeb/Text/input/select.html
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h
- Userland/Libraries/LibWeb/HTML/SelectItem.cpp
- Userland/Libraries/LibWeb/HTML/SelectItem.h
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentServer.ipc
Currently the `<select>` dropdown ipc uses the option value attr to find which option is selected. This won't work when options don't have values or when multiple options have the same value. Also the `SelectItem` contained so weird recursive structures that are imposible to create with HTML. So I refactored `SelectItem` as a variant, and gave the options a unique id. That id is send back to `HTMLSelectElement` so it can find out exactly which option element is selected.
So now you can select the items in this select for example:
```html
<select>
<option value="">Lorem ipsum dolor sit amet.</option>
<option value="">Beatae minus sunt quae dolor.</option>
<option value="">Inventore nulla doloremque corrupti in?</option>
<option value="">Laudantium, error. Beatae, itaque sit!</option> …
```
> LibWeb: Allow selecting select options without value

- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditor.h
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.h
Adds two options to the View menu:
- "Show Offsets Column" lets you hide the byte offset shown to the left of each row of data.
- "Offset Format" lets you pick between showing those values in decimal (which is new) or hexadecimal.
> HexEditor: Make offsets column configurable to be hex, decimal, or hidden entirely

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
- Userland/Libraries/LibJS/Runtime/PromiseConstructor.h
- Userland/Libraries/LibJS/Tests/builtins/Promise/Promise.try.js
Stage 2.7 as of yesterday. See: https://github.com/tc39/proposal-promise-try
> LibJS: Implement Promise.try()

- Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
Doesn't really do terribly much yet.
It does print some debug output with `JPEG2000_DEBUG` defined to 1 at the top of the file:
```sh
% Build/lagom/bin/image --no-output Tests/LibGfx/test-inputs/jpeg2000/simple.jp2
JPEG2000ImageDecoderPlugin: marker 0xff52 not yet implemented
JPEG2000ImageDecoderPlugin: marker 0xff5c not yet implemented
JPEG2000ImageDecoderPlugin: marker 0xff64 not yet implemented
JPEG2000ImageDecoderPlugin: SOT marker segment: tile_index=0, tile_part_length=6273, tile_part_index=0, number_of_tile_parts=1
JPEG2000ImageDecoderPlugin: Tile bitstream length: 6259
Runtime error: JPEG2000ImageDecoderPlugin: Draw the rest of the owl
```
Next steps are decoding the SIZ, COD, QCD marker segments and then looking at the actual bitstream. Eventually we'll have peeled back enough …
> LibGfx/JPEG2000: Add some scaffolding for reading codestream markers

- Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
With this, we can decode all required marker segments, and also some that are very common in practice.
Still doesn't do anything except log data if JPEG2000_DEBUG is 1. If we dig through enough layers there's gotta be image data eventually I'm sure! But not yet.
(QCC is neither required nor super duper common, but it's used by `Tests/LibGfx/test-inputs/jpeg2000/buggie-gray.jpf`.)
> LibGfx/JPEG2000: Decode SIZ, COD, QCD, QCC, COM marker segments

- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
- Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.cpp
From HTML spec https://html.spec.whatwg.org/#definitions-3
"... Note that in this setup, the processing model still enforces that
the user agent would never process events from any one task source out
of order."
I can't come up with an example that is fixed by this change. However,
debugging a bug caused by violating this assumption from the spec is
likely to be very painful.
>  LibWeb: Forbid interleaving execution of HTML tasks with same source

- Tests/LibWeb/Text/expected/navigation/history-replace-push-state-race-3.txt
- Tests/LibWeb/Text/input/navigation/history-replace-push-state-race-3.html
- Userland/Libraries/LibWeb/HTML/History.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
"apply the history step" initiated by reloading or back/forward
navigation might require doing fetching while populating a document,
so it is not possible to restrict spin_until() to process only
NavigationAndTraversal task source.
"apply the history step" initiated by synchronous navigation keeps
processing only NavigationAndTraversal task source because it will
never have to populate a document. Another reason to keep synchronous
navigation blocking other task sources is that we crash if active SHE
changes in the middle of "apply the history step" initiated by sync
navigation. The new test is added to makes sure we don't regress that.
> LibWeb: Process all task source while waiting for document population 

- Tests/LibWeb/Text/expected/navigation/run-script-before-iframe-initial-navigation.txt
- Tests/LibWeb/Text/input/navigation/run-script-before-iframe-initial-navigation.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
Fixes https://github.com/SerenityOS/serenity/issues/23892
> LibWeb: Mark initial about:blank as ready to run scripts after creation 

- Tests/LibWeb/Layout/expected/abspos-with-static-position-in-one-axis.txt
- Tests/LibWeb/Layout/input/abspos-with-static-position-in-one-axis.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
When both insets in a given axis are auto, we should use the static position for absolutely positioned elements.
By doing this correctly, we exposed a bunch of other small bugs which had to be fixed to compensate for new test failures. Those fixes are included here as well:
- Don't apply margins twice.
- Compute the static position containing block chain correctly.
This makes https://brave.com/ look much better. :^)
Before:
After:
> LibWeb: Use static position for abspos box axes with auto insets

- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/TaskManager.h
- Ladybird/AppKit/UI/TaskManager.mm
- Ladybird/AppKit/UI/TaskManagerController.h
- Ladybird/AppKit/UI/TaskManagerController.mm
- Ladybird/CMakeLists.txt
- Meta/gn/secondary/Ladybird/BUILD.gn
Unlike the Inspector window, this is owned by the ApplicationDelegate as there should be only a single task manager for the entire application.
> Ladybird/AppKit: Implement a simple TaskManager window

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Event.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/Navigator.cpp
- Userland/Libraries/LibWeb/HTML/Navigator.h
- Userland/Libraries/LibWeb/HTML/Navigator.idl
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HighResolutionTime/TimeOrigin.cpp
- Userland/Libraries/LibWeb/HighResolutionTime/TimeOrigin.h
- Userland/Libraries/LibWeb/RequestIdleCallback/IdleDeadline.cpp
- Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
Further very minor steps towards: https://github.com/SerenityOS/serenity/issues/23632
Note that the actual timestamps are not correct as get_time_origin_timestamp and coarsen_time are not yet implemented / stubbed out.
> LibWeb: Stub out Navigator.maxTouchPoints, set event timestamps

- Tests/LibWeb/Layout/expected/flex/inline-flex-early-resolution-of-percentage-height.txt
- Tests/LibWeb/Layout/input/flex/inline-flex-early-resolution-of-percentage-height.html
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
There was no need to set an available height constraint when doing early height calculation for inline-flex boxes. It created a situation where the flex containers could wrongly get zero height early, and then resolve percentages against zero instead of the real intrinsic size.
Fixes #23942
> LibWeb: Don't limit available space during early height for inline-flex

- Tests/LibWeb/Text/data/iframe-reload.html
- Tests/LibWeb/Text/expected/navigation/location-reload-fetch.txt
- Tests/LibWeb/Text/expected/navigation/location-reload-srcdoc.txt
- Tests/LibWeb/Text/input/navigation/location-reload-fetch.html
- Tests/LibWeb/Text/input/navigation/location-reload-srcdoc.html
- Userland/Libraries/LibWeb/HTML/DocumentState.cpp
- Userland/Libraries/LibWeb/HTML/DocumentState.h
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.cpp
- Userland/Libraries/LibWeb/HTML/SessionHistoryEntry.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
See spec issue https://github.com/whatwg/html/issues/9869
Previous attempt on fixing reload had to be reverted because it broke Soundcloud and GitHub, but this change does not seem to introduce new crashes.
> LibWeb: Fix always hanging Navigable::reload()

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
> LibPDF: Make CFF.cpp use Stream instead of Reader

- Tests/LibWeb/Text/expected/DOM/Document-methods-that-must-do-nothing.txt
- Tests/LibWeb/Text/expected/DOM/Window-methods-that-must-do-nothing.txt
- Tests/LibWeb/Text/input/DOM/Document-methods-that-must-do-nothing.html
- Tests/LibWeb/Text/input/DOM/Window-methods-that-must-do-nothing.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/Window.idl
This PR adds the following methods to Window and Document:
* `document.clear()`
* `document.captureEvents()`
* `document.releaseEvents()`
* `window.captureEvents()`
* `window.releaseEvents()`
These are obsolete, but the HTML specification says they must do nothing.
With this change we now pass this WPT test: http://wpt.live/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/nothing.html
> LibWeb: Add methods to Window and Document that must do nothing

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWeb/HTML/History.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentServer.ipc
Before this change we had to keep session history on browser side to
calculate a url for back/forward/reload action.
Now, with a mature enough implementation of navigation algorithms from
the specification, there is no need to use
history on the browser side to calculate navigation URLs because:
- Traversable navigable owns session history that is aware of all
navigations, including those initiated by History API and Navigation
API
- TraversableNavigable::traverse_the_history_by_delta() uses
traversable's history to calculate the next URL based on delta, so
there is no need for UI to keep sesion history.
In the future, we will likely want to add a way to pull session history
from WebContent to make it browsable from the UI.
> Ladybird/Qt: Stop using history to drive navigation 

- Tests/LibWeb/Text/expected/fetch-timed-out-request.txt
- Tests/LibWeb/Text/input/fetch-timed-out-request.html
- Userland/Libraries/LibWeb/Fetch/FetchMethod.cpp
Previously, calling fetch with a signal object provided by `AbortSignal.timeout()` would cause a crash when the signal timed out.
We now push a `TemporaryExecutionContext` to the stack when we invoke the signal's abort steps, as an execution context is required when calling native functions.
This fixes a crash on https://arstechnica.com.
> LibWeb/Fetch: Don't crash when a fetch request times out

- Userland/Libraries/LibPDF/Fonts/CFF.cpp
- Userland/Libraries/LibPDF/Fonts/CFF.h
- Userland/Libraries/LibPDF/Fonts/PS1FontProgram.cpp
- Userland/Libraries/LibPDF/Fonts/PS1FontProgram.h
- Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
- Userland/Libraries/LibPDF/Fonts/Type1FontProgram.h
> LibPDF: Move Type1FontProgram and CFF to use AK::Error

- Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/WebIDL/Promise.cpp
This changes the signature of `queue_a_microtask()` from `AK:Function` to `JS::HeapFunction` to be more clear to the user of the functions that this is what it uses internally.
> LibWeb: Let queue_a_microtask() take a JS::HeapFunction

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOMParsing/InnerHTML.cpp
- Userland/Services/WebContent/ConnectionFromClient.cpp
Disconnected subtrees in the DOM don't need style or layout, so let's not invalidate the whole document they belong to when mutation happens inside them.
> LibWeb: Don't invalidate style & layout in disconnected subtrees

- Tests/LibWeb/Text/expected/css/CSSStyleRule-set-selectorText.txt
- Tests/LibWeb/Text/input/css/CSSStyleRule-set-selectorText.html
- Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
Previously, any change to the selectorText of a CSSStyleRule was not reflected in the document style.
Relevant WPT test: https://wpt.live/css/cssom/CSSStyleRule-set-selectorText.html 
(there are still some subtests that fail when matching `lang` attributes, but that's a separate issue).
> LibWeb: Invalidate style when CSSStyleRule selectorText changes

- Tests/LibGfx/TestImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.h
A tag tree is a data structure used for deserializing JPEG2000 packet headers.
We don't use them for anything yet, except from tests.
The implementation feels a bit awkward to me, but we can always polish it later.
The spec thankfully includes two concrete examples. The code is correct enough to pass those -- I added them as test.
> LibGfx/JPEG2000: Implement tag trees

- Userland/Utilities/w.cpp
This was missed in 6f972c1 since this file is not compiled as a part of  a Lagom build.
While we can successfully build Serenity using clang trunk with this patch (and one from Daniel regarding `IPC::encode`, and three first commits from #21182), newly compiled kernel unfortunately crashes just after it initializes memory manager.
> Utilities/w: Work around Clang 18 bug with templated lambda + Variant

- Tests/LibWeb/Text/expected/HTMLLinkElement-disabled.txt
- Tests/LibWeb/Text/input/HTMLLinkElement-disabled.html
- Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
- Userland/Libraries/LibWeb/CSS/StyleSheetList.h
- Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Userland/Libraries/LibWeb/DOM/StyleElementUtils.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Previously, the parent CSS stylesheet, owner node and owner CSS rule properties were not unset when removing a sheet from a StyleSheetList.
This change moves the methods for adding and removing sheets to and from a StyleSheetList, directly into the StyleSheetList class and ensures they are called as required by the CSSOM specification.
After this change we pass this WPT test: http://wpt.live/css/cssom/HTMLLinkElement-disabled-001.html
> LibWeb: Unset stylesheet properties when removing from a StyleSheetList 

- Tests/LibWeb/Ref/alternative-style-sheets.html
- Tests/LibWeb/Ref/reference/alternative-style-sheets-ref.html
- Tests/LibWeb/Text/expected/HTMLLinkElement-explicitly-enabled-alternative-stylesheets.txt
- Tests/LibWeb/Text/input/HTMLLinkElement-explicitly-enabled-alternative-stylesheets.html
- Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
- Userland/Libraries/LibWeb/CSS/StyleSheetList.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
Alternative style sheets are now fetched and are applied to the document if they are explicitly enabled by removing the disabled attribute.
With this change we now pass the following WPT tests (and stops timeouts on some others):
* http://wpt.live/css/cssom/HTMLLinkElement-disabled-002.html
* http://wpt.live/css/cssom/HTMLLinkElement-disabled-003.html
* http://wpt.live/css/cssom/HTMLLinkElement-disabled-005.html
* http://wpt.live/css/cssom/HTMLLinkElement-disabled-006.html
* http://wpt.live/css/cssom/HTMLLinkElement-disabled-007.html
> LibWeb: Support loading alternative style sheets

- Tests/LibWeb/Layout/expected/css-attr-typed-fallback.txt
- Tests/LibWeb/Layout/input/css-attr-typed-fallback.html
- Tests/LibWeb/Ref/css-attr-typed-fallback.html
- Tests/LibWeb/Ref/css-attr-typed.html
- Tests/LibWeb/Ref/reference/css-attr-typed-ref.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
When a string-type `attr()` substitution produces no value and no fallback
had been specified, the spec mandates we default to the empty string.
Fixes #23939
> LibWeb: Default to an empty string when a string attr substitution fails

- Tests/LibTLS/TestTLSHandshake.cpp
- Userland/Libraries/LibHTTP/Job.cpp
- Userland/Libraries/LibTLS/Socket.cpp
Some really cursed servers simply drop the TCP socket on the floor when they're trying to close an HTTP connection going through a TLS socket. This commit makes LibTLS tolerate these silly servers, and LibHTTP accept their idea of "EOF == connection closed".
Fixes loading wpt.live/acid/acid3/test.html.
> LibTLS+LibHTTP: Tolerate improperly closed TLS sockets

- Toolchain/Patches/gcc/0008-Include-safe-ctype.h-after-C-standard-headers-to-avo.patch
Port the fix for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111632 which was committed to gcc/master as
https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=9970b576b7e4ae337af1268395ff221348c4b34a
This fixes the GCC Toolchain build on macOS hosts, and presumably FreeBSD-15 as well.
> Toolchain: Cherry-pick gcc patch for poisoned includes on libc++ hosts

- Tests/LibWeb/Text/expected/css/text-transform-invalidation-on-media-query-change.txt
- Tests/LibWeb/Text/input/css/text-transform-invalidation-on-media-query-change.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
There were two things going wrong here:
- Transformed text (via CSS text-transform) was not invalidated after a `@media` rule changed state.
- Removing the `style` attribute from an element didn't trigger a style update.
This fixes the regression in subtest 46 of Acid3.
Fixes #21777
> LibWeb: Fix two problems where media queries didn't invalidate properly

- Tests/LibWeb/Text/data/bad.xml
- Tests/LibWeb/Text/expected/XML/error-page.txt
- Tests/LibWeb/Text/input/XML/error-page.html
- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
This fixes a regression on Acid3, since we are not expected to "best effort" parse XML. The test specifically checks that you don't create an incomplete, incorrect DOM.
> LibWeb: Generate a simple error page when XML decode/parse fails

- Tests/LibWeb/Text/expected/DOM/Element-setAttribute-capitalization.txt
- Tests/LibWeb/Text/expected/DOM/Element-setAttribute-name-validation.txt
- Tests/LibWeb/Text/input/DOM/Element-setAttribute-capitalization.html
- Tests/LibWeb/Text/input/DOM/Element-setAttribute-name-validation.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
Hello, we are students at the University of Utah working on fixing a bug for Professor Panchekha's Web Browser class. We have implemented the FIXME's previously described in the setAttributes method.
> LibWeb: Add name validation and document check to setAttribute.

- Userland/DevTools/HackStudio/LanguageClient.cpp
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGfx/ShareableBitmap.cpp
- Userland/Libraries/LibIPC/Decoder.cpp
- Userland/Libraries/LibIPC/Encoder.cpp
- Userland/Libraries/LibIPC/Encoder.h
- Userland/Libraries/LibIPC/File.h
- Userland/Libraries/LibWeb/HTML/MessagePort.cpp
- Userland/Libraries/LibWeb/HTML/SelectedFile.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/Worker/WebWorkerClient.cpp
- Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Services/FileSystemAccessServer/ConnectionFromClient.cpp
- Userland/Services/RequestServer/ConnectionFromClient.cpp
- Userland/Services/WebWorker/ConnectionFromClient.cpp
The implicit constructor for IPC::File does not take ownership of the file, which is surprising.
> LibWeb: Stop leaking socket fds when sending them over IPC

- Tests/LibWeb/Text/data/iframe-unload-event.html
- Tests/LibWeb/Text/expected/navigation/iframe-unloading-order.txt
- Tests/LibWeb/Text/input/navigation/iframe-unloading-order.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
Fixes crashing when "unload" event handler tries to access active document that has already been destroyed.
> LibWeb: Do not destroy document until whole subtree completed unloading

- Tests/LibWeb/Text/expected/DOM/Range-deleteContents.txt
- Tests/LibWeb/Text/input/DOM/Range-deleteContents.html
- Userland/Libraries/LibWeb/DOM/Range.cpp
With this change children are no longer skipped in tree traversal when start node of range equals to end node of range.
Fixes https://github.com/SerenityOS/serenity/issues/24036
> LibWeb: Fix nodesToRemove collecting traversal in Range::delete_contents

- Userland/Libraries/LibCrypto/Cipher/Mode/CBC.h
- Userland/Libraries/LibGfx/Size.h
The C++ standard does not allow specifying the template parameters in constructor declarations, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97202#c8.
Converting constructors have a higher priority that user-defined conversion functions; let's constrain `Gfx::Size<T>(Gfx::Size<U>)` to only be considered when `U` is convertible to `T`. This lets us fall back to conversion operators in the case of `UISize` -> `IntSize`, for instance. Clang is still okay without this, but MSVC would error out similarly: https://godbolt.org/z/PTbeYPM7s
Note that a not-yet-committed patch is required for full compilation: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114784#c3
> LibCrypto+LibGfx: Fix GCC 14 compile errors

- AK/String.cpp
- AK/String.h
- Meta/Azure/Lagom.yml
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.repeat.js
Currently crashes with an assertion failure in `String::repeated` if malloc can't serve a `count * input_size` sized request, so propagate the error then thow a `RangeError`.
This can happen when
```js
"A".repeat(0xffffffffff);
```
```
VERIFICATION FAILED: !_temporary_result.is_error() at /home/jess/code/serenity/AK/String.cpp:313
/home/jess/code/serenity/Build/lagom/bin/../lib64/liblagom-ak.so.0(ak_verification_failed+0x86) [0x7ffff7767f2f]
/home/jess/code/serenity/Build/lagom/bin/../lib64/liblagom-ak.so.0 AK::String::repeated(AK::String const&, unsigned long) 0x5e) [0x7ffff77983ba]
/home/jess/code/serenity/Build/lagom/bin/../lib64/liblagom-js.so.0 JS::StringPrototype::repeat(JS::VM&) 0x3bf) [0x7ffff7b9f3bb]
Build/lagom/bin/js() [0x40e707] …
```
> LibJS: throw RangeError in `StringPrototype::repeat` if OOM

- Userland/Libraries/LibJS/Console.cpp
- Userland/Libraries/LibJS/Console.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Runtime/ConsoleObject.cpp
- Userland/Libraries/LibJS/Runtime/ConsoleObject.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/WorkerDebugConsoleClient.cpp
- Userland/Libraries/LibWeb/HTML/WorkerDebugConsoleClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentConsoleClient.cpp
- Userland/Services/WebContent/WebContentConsoleClient.h
- Userland/Services/WebWorker/DedicatedWorkerHost.cpp
- Userland/Services/WebWorker/DedicatedWorkerHost.h
- Userland/Utilities/headless-browser.cpp
- Userland/Utilities/js.cpp
We were inadvertently keeping all documents alive by installing a
console client for them. This patch fixes the issue by adding a
finalizer to Document, and having that be the way we detach console
clients. This breaks the cycle.
With this change, we can spam set .innerHTML in a loop and memory
usage remains stable.
Fixes #14612
> LibWeb+WebContent: Don't let PageClient keep documents alive

- Tests/LibWeb/Text/data/iframe-popstate-event.html
- Tests/LibWeb/Text/expected/navigation/history-popstate-event.txt
- Userland/Libraries/LibWeb/DOM/Document.cpp
Seems like a specification bug, but other browsers update url before popstate event is fired and so should we.
Fixes back/forward navigation on GitHub.
> LibWeb: Update document url after same-document back/forward navigation

- Kernel/FileSystem/FATFS/FileSystem.cpp
- Kernel/FileSystem/FATFS/FileSystem.h
- Kernel/FileSystem/FATFS/Inode.cpp
- Kernel/FileSystem/FATFS/Inode.h
- Userland/Libraries/LibFileSystem/FileSystem.cpp
This continues where #22852 left off, so the majority of the commits here are based on those in that PR. I've tested the write support on all the FAT variants we support, and `fsck_msdos` on macOS comes up with no errors when checking a filesystem that has been modified by this driver.
> Kernel: Add FATFS write support

- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Capturing a struct that owns bunch of JS::Handle makes it very hard to understand what keeps these handles alive in the GC-graph.
Instead let's capture only members of a struct used in the callback.
> LibWeb: Remove changing_navigable_continuation capture in callback

- Userland/Libraries/LibWebView/CookieJar.cpp
When WebDriver accesses cookies, it specifically says to run:
the first step of the algorithm in RFC6265 to compute cookie-string
So we should skip subsequent steps. We already skip step 2, which sorts the cookies, but neglected to skip step 3 to update their last access time.
> LibWebView: Do not update cookie access time when fetched with WebDriver

- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicLoader.h
The strategy of recreating an object for the second time after DynamicLoader::map is interesting, of course, but it doesn't help comprehensibility of the code, unfortunately.
> LibELF: Get rid of DynamicLoader::m_cached_dynamic_object

- Kernel/Arch/riscv64/CSR.h
- Kernel/Arch/riscv64/Processor.h
This simply reads the current cycle count from the cycle CSR.
x86-64 uses the similar rdtsc instruction here, which also may or may
not tick at a constant rate.
> Kernel/riscv64: Implement Processor::read_cpu_counter

- Tests/LibWeb/Text/expected/css/move-loaded-link-stylesheet-between-documents.txt
- Tests/LibWeb/Text/input/css/move-loaded-link-stylesheet-between-documents.html
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
We have to unregister link element stylesheets from the old document's StyleSheetList when moving them into a new document.
This makes it possible to load GitHub contributor graphs. :^)
> LibWeb: Allow moving StyleSheets between documents without falling apart

- Ladybird/AppKit/main.mm
- Ladybird/HelperProcess.cpp
- Ladybird/Qt/main.cpp
- Ladybird/Types.h
- Ladybird/WebContent/main.cpp
- Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/main.cpp
- Tests/LibJS/test-test262.cpp
- Tests/LibJS/test262-runner.cpp
- Userland/Applications/CrashReporter/main.cpp
- Userland/Libraries/LibCore/ArgsParser.h
- Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp
- Userland/Libraries/LibTest/TestSuite.cpp
- Userland/Shell/main.cpp
- Userland/Utilities/comm.cpp
- Userland/Utilities/du.cpp
- Userland/Utilities/grep.cpp
- Userland/Utilities/headless-browser.cpp
- Userland/Utilities/icc.cpp
- Userland/Utilities/ls.cpp
- Userland/Utilities/paste.cpp
- Userland/Utilities/rm.cpp
- Userland/Utilities/run-tests.cpp
- Userland/Utilities/tar.cpp
- Userland/Utilities/wasm.cpp
Sometimes I like to play around with running Ladybird tests using full
blown Ladybird instead of just headless browser to interactively mess
around with the test page. One problem with this is that the internals
object is not exposed in this mode.
This supports this usecase by adding an option to specifically
expose the internals object without needing to run headless-browser
in test mode.
Also make it optional to pass through 'short_option' to args parser
as I questioned for a second what all of the 0's were at the end of all
of the `add_options`
> Ladybird: Add an option to enable internals object outside of test mode

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/DocumentLoading.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigationParams.cpp
- Userland/Libraries/LibWeb/HTML/NavigationParams.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Fixes GC-leak caused by using JS::Handle for navigable.
> LibWeb: Make NavigationParams be GC-allocated

- Tests/LibWeb/Layout/expected/hidden-root-element.txt
- Tests/LibWeb/Layout/input/hidden-root-element.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
Previously, setting the `hidden` property on the `<html>` element would cause a crash.
Fixes a crash on: https://downloadmoreram.com/
> LibWeb: Don't crash if the document element is not visible

- Tests/LibWeb/Ref/inline-paintable-background-clip-text.html
- Tests/LibWeb/Ref/reference/inline-paintable-background-clip-text-ref.html
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
Moves background mask calculation into `paint_background()` that is shared between PaintableBox and InlinePaintable.
> LibWeb: Add `background-clip: text` support for InlinePaintable

- Userland/Libraries/LibJS/Runtime/PromiseJobs.cpp
- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/Fetch/Body.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
More `HeapFunction` goodness. With these changes, we are down from 91 to 13 leaked `Window` objects at the end of a full test run. :^)
> LibJS+LibWeb: Fix some more GC leaks

- Ladybird/Qt/WebContentView.cpp
Previously the 'device independent pixels' (which consider scaling) were used, and then scaling would be applied again when calculating the screen width for CSS.
> Ladybird: Calculate the 'physical pixels' for screens

- Userland/Applications/PixelPaint/MainWidget.cpp
After 8b4e2e20 `Combobox::set_text()` invokes the `on_change` event by default. This led to an infinite loop at program startup which caused a crash.
Fixes #23998
> PixelPaint: Avoid infinite loop when updating zoom level ComboBox text

- Ladybird/ImageCodecPlugin.cpp
- Ladybird/ImageCodecPlugin.h
- Tests/LibWeb/Text/input/createBitmap.html
- Userland/Applications/ImageViewer/ViewWidget.cpp
- Userland/Applications/PixelPaint/Image.cpp
- Userland/Applications/SoundPlayer/SoundPlayerWidget.cpp
- Userland/Libraries/LibGUI/FileSystemModel.cpp
- Userland/Libraries/LibImageDecoderClient/Client.cpp
- Userland/Libraries/LibImageDecoderClient/Client.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/Platform/ImageCodecPlugin.cpp
- Userland/Libraries/LibWeb/Platform/ImageCodecPlugin.h
- Userland/Services/ImageDecoder/ConnectionFromClient.cpp
- Userland/Services/ImageDecoder/ConnectionFromClient.h
- Userland/Services/ImageDecoder/ImageDecoderClient.ipc
- Userland/Services/ImageDecoder/ImageDecoderServer.ipc
- Userland/Services/WebContent/ImageCodecPluginSerenity.cpp
- Userland/Services/WebContent/ImageCodecPluginSerenity.h
- Userland/Utilities/pixelflut.cpp
ImageDecoder now queues up image decoding requests and returns the
images back to the caller later. ImageDecoderClient has a new
promise-based API that allows callers to attach their own resolve/reject
handlers to the responses from ImageDecoder.
> ImageDecoder: Handle decoding of images in an asynchronous manner

- AK/FloatingPoint.h
- Tests/LibC/CMakeLists.txt
- Tests/LibC/TestFenv.cpp
- Tests/LibC/TestMath.cpp
- Userland/Libraries/LibC/arch/aarch64/fenv.cpp
- Userland/Libraries/LibC/arch/riscv64/fenv.cpp
- Userland/Libraries/LibC/arch/riscv64/fenv.h
- Userland/Libraries/LibC/arch/x86_64/fenv.cpp
- Userland/Libraries/LibC/arch/x86_64/fenv.h
- Userland/Libraries/LibC/fenv.cpp
- Userland/Libraries/LibC/fenv.h
- Userland/Libraries/LibC/math.cpp
Revival of #21161, original description:
Because the new tests failed on x86 extended floating point (a truly cursed float format), you're getting two x87 fixes for free!
> LibC: Add fenv+rounding support for RISC-V (and test fenv in the first place)

- .github/workflows/cmake.yml
- Meta/Azure/Caches.yml
- Meta/Azure/Lagom.yml
- Meta/Azure/Serenity.yml
- Toolchain/BuildClang.sh
This should allow us to keep the ccache as lean as possible without having to rely on manually balanced size information (or on the cleanup logic that apparently isn't that cache friendly).
The cache sizes change roughly as follows:
```
(GCC, x86_64, ALL_DEBUG)     | 1.36G -> 0.70G
(GCC, x86_64, NORMAL_DEBUG)  | 1.02G -> 0.46G
(GCC, aarch64, NORMAL_DEBUG) | 1.02G -> 0.46G
(Lagom, Linux, NoFuzz)       | 1.80G -> 0.74G
(Lagom, Linux, Fuzz)         | 1.82G -> 0.25G
(Lagom, macOS, NoFuzz)       | 1.90G -> 0.30G
(Clang, x86_64, Toolchain)   | 0.88G -> 0.23G
(Clang, x86_64, Serenity)    | 4.45G -> 0.33G
```
> Meta: Trim the CI ccache down to files used in the current build

- Meta/Azure/Lagom.yml
- Meta/Azure/nightly-pipeline.yml
- azure-pipelines.yml
Azure Experiment that panned out nicely. A GCC build on Lagom Linux is about 30-40% slower than a Clang build.
> CI: Test using Clang for ASAN+UBSAN on linux

- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicLoader.h
There is no need to defer unresolved weak relocations until stage 3 -- it is not like we will magically find new symbols in the same objects.
> LibELF: Perform weak relocations in much more straight-forward manner

- Userland/Libraries/LibJS/Heap/CellAllocator.cpp
- Userland/Libraries/LibJS/Heap/CellAllocator.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
This allows to skip iterating through all allocated blocks in `find_min_and_max_block_addresses()`.
With this change `collect_garbage()` in profiles of Discord goes down from 17% to 8%.
> LibJS: Save min and max block addresses in CellAllocator

- .github/workflows/cmake.yml
- Meta/Azure/Caches.yml
If there is a cache miss while downloading the ccache from GitHub/Azure, the .ccache directory won't exist when we try to update the modification time of its contents. Configure the ccache size first, which will create the .ccache directory if it doesn't exist.
> CI: Configure ccache before modifying its contents (if any)

- Tests/LibWeb/Text/expected/get-bounding-client-rect-display-none.txt
- Tests/LibWeb/Text/input/get-bounding-client-rect-display-none.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
This small patch should fix #23829 where we try to get a paintable for elements that don't have one. 
Not 100% sure if this is actually correct as I've slightly changed the checks for the `containing_block` call
> LibWeb: Fix get_client_rects() on elements that are not paintable

- Meta/Azure/Caches.yml
- Meta/Azure/Serenity.yml
Currently, if the prebuilt toolchain cache gets used, we will not try to build the toolchain. Thus, the toolchain's ccache does not get used, and is then pruned entirely at the end of the run.
So for now, let's just not prune the toolchain ccache. After a few years it only reached 0.8 GB in size. And now that we are starting from empty again, it will likely be a few more years before we reach 0.8 GB again.
Then, we can clear the toolchain ccache when the toolchain's major version changes. This would ultimately be a clean build anyways, so we can take that opportunity to stop carrying the previous version's ccache forward.
> CI: Do not prune the toolchain ccache

- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.h
- Userland/Libraries/LibWeb/MathML/MathMLElement.cpp
- Userland/Libraries/LibWeb/MathML/MathMLElement.h
- Userland/Libraries/LibWeb/SVG/SVGElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGElement.h
Most elements never need a dataset object, so we can avoid creating lots of objects by making them lazy.
> LibWeb: Allocate dataset lazily for HTML/SVG/MathML elements

- Tests/LibWeb/Text/expected/css/move-loaded-link-stylesheet-between-documents.txt
- Tests/LibWeb/Text/expected/favicon-in-inactive-document.txt
- Tests/LibWeb/Text/input/favicon-in-inactive-document.html
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Fixes crashing after following steps:
1. Open https://github.com/SerenityOS/serenity
2. Click on "Pull requests" tab
The problem was `navigable` null pointer dereferencing in `decode_favicon()`. But navigable is null because the document was created by `parseFromString()` DOMParser API.
With this change we skip fetching initiated by HTMLLinkElement if document is not fully active:
- Favicons are not displayed for inactive documents so no need to fetch.
- Stylesheets fetching won't affect inactive document because style or layout does not run for them.
> LibWeb: Skip HTMLLinkElement resource fetching for inactive documents

- Ladybird/ImageDecoder/CMakeLists.txt
- Meta/gn/secondary/Ladybird/ImageDecoder/BUILD.gn
- Userland/Libraries/LibThreading/BackgroundAction.cpp
- Userland/Libraries/LibThreading/BackgroundAction.h
- Userland/Services/ImageDecoder/CMakeLists.txt
- Userland/Services/ImageDecoder/ConnectionFromClient.cpp
- Userland/Services/ImageDecoder/ConnectionFromClient.h
This allows the ImageDecoder service to handle new IPC requests while decoding in parallel.
To make this happen, I needed to add a way to cancel and join the LibThreading background thread. This allows processes using BackgroundAction to actually exit when all their threads have exited.
> ImageDecoder: Schedule decode jobs on the LibThreading background thread

- Ladybird/AppKit/main.mm
- Ladybird/Types.h
This really only affects headless-browser when it is linked with Qt. In
that case, it currently uses Qt networking by default and does not have
a flag to use RequestServer instead. Change the default to use RS so it
can undergo sanitized testing in CI.
> Ladybird: Use RequestServer for networking by default

- Tests/LibWeb/Text/data/video-gc-frame.html
- Tests/LibWeb/Text/expected/video-gc.txt
- Tests/LibWeb/Text/input/video-gc.html
- Userland/Libraries/LibVideo/PlaybackManager.cpp
- Userland/Libraries/LibVideo/PlaybackManager.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h
- Userland/Libraries/LibWeb/HTML/VideoTrack.cpp
- Userland/Libraries/LibWeb/HTML/VideoTrack.h
- Userland/Libraries/LibWeb/HTML/VideoTrackList.h
Otherwise, the thread will continue to run and access the media data
buffer, which will have been freed.
Fixes #24044
> LibWeb: Stop the video decoder thread when the video element is GC'd

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
We partially supported this feature, but not enough for the chrome's context menu to open. We now propagate the event back to the chrome.
With this, we can use the chrome's context menu on discord, which is a feature I use in firefox all the time:
https://github.com/SerenityOS/serenity/assets/5600524/cd5e7d6d-2582-49b0-9aae-9f0665012d1f
> LibWeb: Run page activation behavior when skipping context menu events

- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Link elements that aren't "browsing-context connected" should not trigger a resource fetch when their attributes change.
This fixes an issue where we'd waste time by loading every style sheet twice! :^)
> LibWeb: Only react to link element attribute changes when BC connected

- Tests/LibWeb/Text/expected/DOM/HTMLCollection-order.txt
- Tests/LibWeb/Text/input/DOM/HTMLCollection-order.html
- Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp
- Userland/Libraries/LibWeb/DOM/HTMLCollection.h
Previously we would look for a matching ID, and then for a matching name. If there was an element in the collection which had a matching ID as well as an element with a matching name, we would always return the element with a matching ID irrespective of what order that element was in.
> LibWeb: Look for first ID _or_ name in HTMLCollection::named_item

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/WebAssembly/Instance.cpp
- Userland/Libraries/LibWeb/WebAssembly/Instance.h
- Userland/Libraries/LibWeb/WebAssembly/Memory.cpp
- Userland/Libraries/LibWeb/WebAssembly/Module.cpp
- Userland/Libraries/LibWeb/WebAssembly/Module.h
- Userland/Libraries/LibWeb/WebAssembly/Table.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.idl
Previously, items in the cache would persist after all `WebAssemblyNamespace` objects had been garbage collected. This led to a UAF when accessing cached objects.
This should unblock #23835 and #24006, which currently cause CI failures.
> LibWeb: Clear WebAssembly cache when all namespace objects are GCed 

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibIDL/IDLParser.cpp
- Userland/Libraries/LibIDL/Types.h
Previously, all `#import` statements generated two identical includes in the generated C++ source code.
> LibIDL+IDLGenerators: Don't duplicate include statements for each import 

- Userland/Libraries/LibTLS/Socket.cpp
- Userland/Libraries/LibTLS/TLSv12.h
We should not expect the server to respond immediately after connecting, this can manifest as random requests failing (e.g. on https://null.com).
> LibTLS: Ignore empty reads from underlying socket while connecting

- Userland/Libraries/LibWeb/HTML/AudioTrack.cpp
- Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h
- Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
When trying to load ogg/vorbis files the MP3 Loader is used, what is resulting in decoding errors. To stop crashing the whole browser i added error handling with the on_decoder_error function.
@trflynn89 and @Zaggy1024 helped me.
The ogg/vorbis audios are "garbage" now but this will be fixed in the future when ogg/vorbis streams are implemented.
Also notable is that the stream won't stop playing on a decode error.
> LibWeb: Set decoder error when decoding fails

- Tests/LibWeb/Ref/inline-paintable-inside-translated-container.html
- Tests/LibWeb/Ref/reference/inline-paintable-inside-translated-container-ref.html
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
Fixes bug when CSS transform is applied twice to clip rect:
- While calculating absolute clip rectangles in `refresh_clip_state()`
- While executing `PushStackingContext` painting command.
Duplicated transform is already removed for PaintableBox and this change adds this for InlinePaintable.
> LibWeb: Remove CSS transform from InlinePaintable's clip rectangle

- Tests/LibWeb/Text/expected/HTML/Window-iterate-properties.txt
- Tests/LibWeb/Text/input/HTML/Window-iterate-properties.html
- Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp
Previously, [Global] interfaces were not excluded from the `internal_own_property_keys()` call. This caused a crash when iterating over the properties of the Window object.
Fixes #22973
> LibWeb: Exclude [Global] interfaces from legacy platform object method

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/namespace-object-prototype.txt
- Tests/LibWeb/Text/input/namespace-object-prototype.html
Previously, namespace objects were constructed with no prototype, so calling methods like `toString()` on them would unexpectedly throw an exception.
After this change we now pass this test: http://wpt.live/css/cssom/CSS-namespace-object-class-string.html
> IDLGenerators: Set namespace object prototype to Object.prototype

- Kernel/Arch/riscv64/MMU.cpp
"register asm" variables don't preserve the register value, so the call to calculate_physical_to_link_time_address_offset in the asm input operands is allowed to clobber a0.
> Kernel/riscv64: Don't clobber the boot info argument in enable_paging

- AK/StdLibExtras.h
- Tests/AK/TestStdLibExtras.cpp
`ceil_div(-1, 2)` used to return -1.
Now it returns 0, which is the correct ceil(-0.5).
(C++'s division semantics have floor semantics for numbers > 0,
but ceil semantics for numbers < 0.)
This will be important for the JPEG2000 decoder eventually.
> AK: Make ceil_div() handle one argument being negative correctly 

- Ladybird/HelperProcess.cpp
- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibCore/Process.h
This broke due to the way we now use posix_spawn under the hood. This
moves the handling of the callgrind option to the launcher helper where
we iterate over the candidate process paths, as we need to augment the
way we fork the process for callgrind based on those paths.
This also opens the door for running other processes under callgrind in
the future.
Fixes #24130
> Ladybird: Restore ability to run WebContent under callgrind

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/InlinePaintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Makes 5% of `compute_combined_css_transform()` in Discord profiles gone.
> LibWeb: Cache combined CSS transform on pre-paint phase 

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Tests/postfix-increment-eval-order.js
For this case to work correctly in the current bytecode world:
func(a, a++)
We have to put the function arguments in temporaries instead of allowing the postfix increment to modify `a` in place.
This fixes a problem where jQuery.each() would skip over items.
> LibJS: Fix bug where argument++ happened before call

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/Tab.h
Rather than getting the tab name from the tab container. This resolves an issue where ampersands were being introduced to the window title when changing tabs.
cc @trflynn89 as he also mentioned this occurring on Discord.
- Open new tab
- Switch to original tab
- See ampersand (`&` in window title)
> Ladybird: Retreive the tab title from the underlying Tab

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.h
Before this change we were recording and executing sample/blit commands for each painting phase, even if there are no painting commands in-between sample and blit that produce result visible on a canvas.
This change adds an optimization pass that goes through recorded painting commands list and marks sample and blit commands that could be skipped.
Reduces sample and blit corners executing from 17% to 8% on Discord.
> LibWeb: Skip unnecessary sample corner and blit corner commands

- Tests/Utilities/CMakeLists.txt
- Tests/Utilities/TestUniq.cpp
- Userland/Utilities/uniq.cpp
There were several bugs and inconsistencies with coreutils that this pull request addresses. First, lines were capped at 1024 bytes, which is addressed by using the `read_line_with_resize` method instead of `read_line`. Second, there were a couple of off-by-one errors that caused the `-c` and `-f` flags to not function as expected. Finally, the final line of a series of repeated lines was being written instead of the first, as specified by [the spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/uniq.html). The test file was adapted from `TestSed` and covers all of these changes.
> Utilities: Fix various bugs in uniq

- Tests/LibGfx/TestImageDecoder.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
...and add a test case that shows why it's incorrect.
If one dimension is 2^n + 1 and the other side is just 1, then the topmost node will have 2^n x 1 and 1 x 1 children. The first child will have n levels of children. The 1 x 1 child could end immediately, or it could require that it also has n levels of (all 1 x 1) children. The spec isn't clear on which of the two alternatives should happen. We currently have n levels of 1 x 1 blocks.
This test case shows that a VERIFY we had was incorrect, so remove it.
The alternative implementation is to keep the VERIFY and to add a
if (x_count == 1 && y_count == 1)
level = 0;
to the top of TagTreeNode::create(). Then we don't have multiple levels of 1 x 1 nodes, and we need to read fewer bits.
The images in the spec suggest that all nodes should …
> LibGfx/JPEG2000: Remove an incorrect VERIFY in TagTree construction

- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/main.cpp
- Meta/gn/secondary/Userland/Libraries/LibWebView/BUILD.gn
- Userland/Libraries/LibCore/LocalServer.cpp
- Userland/Libraries/LibCore/LocalServer.h
- Userland/Libraries/LibCore/Process.cpp
- Userland/Libraries/LibCore/Process.h
- Userland/Libraries/LibIPC/MultiServer.h
- Userland/Libraries/LibWebView/CMakeLists.txt
- Userland/Libraries/LibWebView/ChromeProcess.cpp
- Userland/Libraries/LibWebView/ChromeProcess.h
- Userland/Libraries/LibWebView/UIProcessClient.ipc
- Userland/Libraries/LibWebView/UIProcessServer.ipc
This allows main UI processes created while there is a currently
running one to request a new tab or a new window with the initial urls
provided on the command line. This matches (almost) the behavior of
Chromium and Firefox.
Add a new IPC protocol between two UI processes. The main UI process
will create an IPC server socket, while secondary UI processes will
connect to that socket and send over the URLs and action it wants the
main process to take.
Bikeshedding on these names is welcome, because the ones I chose for the LibWebView class and the IPC protocol are pretty awful :)
https://github.com/SerenityOS/serenity/assets/8388494/9080fd68-3a70-49dc-bc0d-bc7890f36958
> LibWebView: Create plumbing for a single UI process 

- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Changes compute_absolute_padding_rect_with_css_transform_applied() to use cached absolute rect and CSS transform instead of doing expensive containing block chain traversal.
Reduces refresh_clip_state() from 4% to 2% in Discord profiles.
> LibWeb: Use cached absolute rect and transform in refresh_clip_state()

- Tests/LibWeb/Ref/non-positioned-stacking-context-with-z-index-0.html
- Tests/LibWeb/Ref/reference/non-positioned-stacking-context-with-z-index-0-ref.html
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Fixes the bug when non-positioned boxes that establish a stacking context and have z-index=0 are ignored during paint commands recording.
> LibWeb: Paint non-positioned SC with z-index=0 in paint_descendants()

- Kernel/Bus/USB/USBPipe.cpp
- Kernel/Bus/USB/USBPipe.h
The USB::Pipe is abstracted from the actual USB host controller implementation, so don't include the UHCIController.h file. Also, we missed an include to UserOrKernelBuffer.h, so this is added to ensure the code can still compile.
This patch was taken from #23448, in attempt to make that PR less clunky to review.
> Kernel/USB: Don't include UHCIController.h in USBPipe.h

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Ladybird/Qt/TabBar.cpp
- Ladybird/Qt/TabBar.h
The first commit here increases the minimum tab width, so that more is shown that the favicon when lots of tabs are open (at least Firefox shows some of the title too).
| --- | --- |
| ![image](https://github.com/SerenityOS/serenity/assets/5103549/7bb2e47a-5c44-43be-abad-a33b8bea75bb) | ![image](https://github.com/SerenityOS/serenity/assets/5103549/364a310c-2453-4dd9-910a-7e0ad2cacb95) |
I can open this change in a separate pull request if desired :)
---
The main part of this pull request is to add a context menu to tabs in the tab bar.
I have based the layout and naming of the context menu after Firefox's.
> Ladybird: Add a context menu to the tab bar

- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGfx/Bitmap.cpp
- Userland/Libraries/LibGfx/Bitmap.h
Using `malloc()` instead of `mmap()` is faster and avoids wasting memory by rounding up every bitmap allocation to a multiple of 4096 bytes.
> LibGfx: Make non-shared Bitmaps be malloc-backed (+ cleanups)

- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
...if its box is positioned and has z-index=0.
> LibWeb: Fix paint recording to stop visiting stacking context twice

- Userland/Libraries/LibWeb/Painting/PaintContext.cpp
- Userland/Libraries/LibWeb/Painting/PaintContext.h
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.h
Duplicated stacking context painting is easy to introduce because of a bit complicated traversal order and very painful to debug.
> LibWeb: Verify in runtime that stacking context is not painted twice

- AK/BufferedStream.h
- Userland/Utilities/sort.cpp
With this PR `sort` can now handle arbitrarily long lines. Previously, lines would be truncated at 4096 bytes.
My implementation of this feature avoids string allocations when building `Line` objects.
I have also replaced all remaining usages of `DeprecatedString` with `StringView`
Tested with lines up to 1MB.
> sort: Allow sorting of arbitrarily long lines

- Userland/Utilities/mount.cpp
I found this while working on #19867, so I consider this as immediate patch to this regression I introduced by mistake.
> Utilities/mount: Resolve regression on mounting non-storage-backed FSes

- Kernel/Arch/aarch64/FPUState.S
- Kernel/Arch/aarch64/FPUState.h
- Kernel/Arch/aarch64/Processor.cpp
- Kernel/CMakeLists.txt
LLVM 18 otherwise throws errors, as we use '-mgeneral-regs-only' in the kernel.
The functions had to be moved into a .S, as there is no '-mno-general-regs-only' and also no nice way to remove '-mgeneral-regs-only' for a single .cpp file.
> Kernel/aarch64: Explicitly allow float instrs in {load,store}_fpu_state

- Tests/LibWeb/TestConfig.ini
This seems related to CSS resources and the load event.
Ref: #24163
> Tests: Skip flaky unicode-range LibWeb Ref test

- Userland/Applications/Run/RunWindow.cpp
- Userland/Applications/Run/RunWindow.h
Should resolve #5587.
When we try to start a long-running child process (e.g. a GUI app) using a combination of the POSIX spawn and waitpid API, the Run process ends up waiting for it to end before making any changes to the path history. This leads to some confusion when trying to fire up another Run process only to see that it did not save the path to this program.
This PR resolves this by saving the path after it was created using the POSIX spawn API and removes it from the history list if it fails while the Run process waits for it to exit.
I tested both the `run_as_launch()` and `run_as_command()` and it appears to do the job.
> Run: Don't wait for child process to end when adding it to history

- Ladybird/AppKit/Application/ApplicationDelegate.h
- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/Qt/main.cpp
- Userland/Applications/Browser/main.cpp
- Userland/Libraries/LibWebView/CookieJar.cpp
- Userland/Libraries/LibWebView/CookieJar.h
- Userland/Utilities/headless-browser.cpp
Now that the chrome process is a singleton on all platforms, we can safely add a cache to the CookieJar to greatly speed up access. The way this works is we read all cookies upfront from the database. As cookies are updated by the web, we store a list of "dirty" cookies that need to be flushed to the database. We do that synchronization every 30 seconds and at shutdown.
There's plenty of room for improvement here, some of which is marked with FIXMEs in the CookieJar.
Before these changes, in a SQL database populated with 300 cookies, browsing to https://twinings.co.uk/ WebContent spent:
19,806ms waiting for a get-cookie response
505ms waiting for a set-cookie response
With these changes, it spends:
24ms waiting for a get-cookie response
15ms waiting for a set-cookie response
This is …
> Ladybird+LibWebView: Introduce a cache for cookies backed by SQL storage

- Tests/LibWeb/Text/expected/css/media-query-serialization-basic.txt
- Userland/Libraries/LibWeb/CSS/CSSMediaRule.cpp
- Userland/Libraries/LibWeb/CSS/MediaQuery.cpp
This PR makes 2 changes to align the serialization of media queries with other modern browsers:
* We now include a space between media feature name and value. This follows the specification.
* If a media at-rule contains no CSS rules we don't include a final newline. This deviates from the specification, but all modern browsers do this. [This web platform test](http://wpt.live/css/cssom/serialize-media-rule.html) relies on this behavior.
This makes the following WPT test pass: http://wpt.live/css/cssom/MediaList.html
and increases the number of subtest passes for this WPT test: http://wpt.live/css/cssom/serialize-media-rule.html
> LibWeb: Improve serialization of media queries

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
Further work towards GH-23632.
Serenity doesn't have any APIs for structured headers introduced in RFC 8941, so this creates the headers as they would ultimately be made.
> LibWeb/Fetch: Append fetch metadata headers

- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
Ref https://github.com/SerenityOS/serenity/pull/24132#issuecomment-2086477483
These patches were done as part of making fetch use streams to read response bodies. That ultimately has some issues to be worked out, but in the meantime, this affords some cleanup that aligns us back closer to the spec.
> LibWeb: Add and use an ad-hoc ReadableStreamDefaultReader::read_all_chunks AO

- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGenerator.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
- Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
- Userland/Libraries/LibJS/Runtime/GeneratorObject.h
- Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
Before this change both ExecutionContext and CallFrame were created before executing function/module/script with a couple exceptions:
- executable created for default function argument evaluation has to run in function's execution context.
- `execute_ast_node()` where executable compiled for ASTNode has to be executed in running execution context.
This change moves all members previously owned by CallFrame into ExecutionContext, and makes two exceptions where an executable that does not have a corresponding execution context saves and restores registers before running.
Now, all execution state lives in a single entity, which makes it a bit easier to reason about and opens opportunities for optimizations, such as moving registers and local variables into a single array.
> LibJS: Merge CallFrame into ExecutionContext

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Tests/try-catch-finally-nested.js
- Userland/Libraries/LibJS/Tests/try-finally-break.js
> LibJS: Propagate finalizers into nested try-catch blocks without them

- Kernel/Arch/riscv64/PCI/Initializer.cpp
- Kernel/Bus/PCI/Controller/HostController.cpp
- Kernel/Bus/PCI/Controller/HostController.h
- Kernel/Bus/PCI/Definitions.h
- Kernel/Memory/MemoryManager.cpp
- Meta/run.py
- Userland/Libraries/LibDeviceTree/DeviceTree.cpp
- Userland/Libraries/LibDeviceTree/DeviceTree.h
Mainly extracted from #23703
CC: @spholz Fixed the phandle bug here as well
----
We need to set them after we've created the full tree, as otherwise the
HashMap containing the nodes may reallocate and invalidate the pointers.
This new Stream class adds an interface to work in cell-sized chunks,
which is useful for parsing the data in a DeviceTreeProperty.
Crashing seems a bit harsh, so let's just skip them instead, as they
actually show up in the device tree of RPis.
These seem to be actually used in the RPi FTDs
> LibDeviceTree+Kernel: Some devicetree related work

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/SVG/SVGCircleElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
This improves debuggability by converting a SIGSEGV into a verification failed on a null dereference.
edit: feels worthwhile as I've run into this one a bunch! latest ref: https://github.com/SerenityOS/serenity/issues/24186
> LibWeb: Use GCPtr for Element::layout_node

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.cpp
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
If a function has the following properties:
- uses only local variables and registers
- does not use `this`
- does not use `new.target`
- does not use `super`
- does not use direct eval() calls
then it is possible to entirely skip function environment allocation because it will never be used
This change adds gathering of information whether a function needs to access `this` from environment and updates `prepare_for_ordinary_call()` to skip allocation when possible.
For now, this optimisation is too aggressively blocked; e.g. if `this` is used in a function scope, then all functions in outer scopes have to allocate an environment. It could be improved in the future, although this implementation already allows skipping >80% of environment allocations on Discord, GitHub and Twitter.
> LibWeb+LibJS: Skip function environment allocation if possible

- Tests/LibWeb/Text/expected/WebAudio/OscillatorNode.txt
- Tests/LibWeb/Text/input/WebAudio/OscillatorNode.html
- Userland/Libraries/LibWeb/WebAudio/AudioNode.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioNode.h
- Userland/Libraries/LibWeb/WebAudio/AudioNode.idl
- Userland/Libraries/LibWeb/WebAudio/AudioParam.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioParam.h
- Userland/Libraries/LibWeb/WebAudio/AudioScheduledSourceNode.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioScheduledSourceNode.h
- Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
- Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
- Userland/Libraries/LibWeb/WebAudio/OfflineAudioContext.cpp
- Userland/Libraries/LibWeb/WebAudio/OscillatorNode.cpp
- Userland/Libraries/LibWeb/WebAudio/OscillatorNode.h
- Userland/Libraries/LibWeb/WebAudio/OscillatorNode.idl
Implement more of of OscillatorNode, enough to get us up to: `createDynamicsCompressor`.
Further work to: https://github.com/SerenityOS/serenity/issues/22902 / https://github.com/SerenityOS/serenity/issues/23632
> LibWeb: Implement some more interfaces towards OfflineAudioContext

- Tests/LibWeb/Ref/reference/svg-non-local-clip-path-display-none-ref.html
- Tests/LibWeb/Ref/reference/svg-non-local-clip-path-ref.html
- Tests/LibWeb/Ref/svg-non-local-clip-path-display-none.html
- Tests/LibWeb/Ref/svg-non-local-clip-path.html
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
- Userland/Libraries/LibWeb/Painting/SVGPathPaintable.cpp
The crash has already been fixed, so this PR simply fixes the painting issues found in [#24070](https://github.com/SerenityOS/serenity/issues/24070).
So a non-local `clipPath` like:
```html
<!doctype html>
<svg>
<clippath id="jeez">
<circle cx="50" cy="50" r="50" />
</clippath>
</svg>
<svg>
<g clip-path="url(#jeez)">
<rect fill="red" width="100" height="100">
</rect>
</g>
</svg>
```
Is applied correctly:
> LibWeb: Fix painting non-local SVG clipPaths/masks

- Userland/Libraries/LibPDF/Parser.cpp
While fuzzing, found the following PDF that causes a crash 
[crash-025e245bd05e9b291b031417fb941c797086f0ba.pdf](https://github.com/SerenityOS/serenity/files/15211437/crash-025e245bd05e9b291b031417fb941c797086f0ba.pdf)
Its a simple fix for the bug.
> LibPDF: Added empty read check to parse_hex_string

- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Turns out this mistake happens fairly often, so it is more preferable to log message and proceed instead of crashing.
> LibWeb: Log error instead of crashing if stacking context painted twice

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
This is a normative change in the Temporal spec.
See: https://github.com/tc39/proposal-temporal/commit/8fc8130
> LibJS: Truncate roundingIncrement before range check 

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
If all lexical declaration use local variables then there is no need to allocate declarative environment.
With this change we skip ~3x more environment allocations on Github.
> LibJS: Skip some declarative env allocations in function instantiation

- Ladybird/Qt/Tab.cpp
**Before:**
Note: Little arrow in corner (looks unbalanced)
**After:**
> Ladybird: Remove menu indicator on hamburger icon

- .github/actions/setup/action.yml
This is needed to update brew's internal list of formulae, otherwise it does not know about llvm-18.
This fixes the JS artifacts build:
https://github.com/trflynn89/serenity/actions/runs/8968586657/job/24628304185?pr=7
> CI: Run `brew update` before installing macOS packages

- AK/Find.h
- Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
- Tests/LibGfx/CMakeLists.txt
- Tests/LibGfx/TestImageWriter.cpp
- Userland/Libraries/LibGfx/Bitmap.h
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.h
- Userland/Utilities/image.cpp
This doesn't use any transforms yet (in particular not the predictor
transform), and doesn't do anything else that actually compresses the
data.
It also give all 256 values code length 8 unconditionally. This means
the huffman trees are not data-dependent at all and provide no
compression. It also means we can just write out the image data
unmodified.
So the output is fairly large. But it _is_ a valid lossless webp file.
Possible follow-ups, to improve compression later:
1. Use actual byte distributions to create huffman trees, to get
huffman compression.
2. If the distribution has just 1 element, write a simple code length
code (that way, images that have alpha 0xff everywhere need to store
no data for alpha).
3. Add backref support, to get full deflate(ish) compression of pixels.
4. Add …
> LibGfx/WebPWriter+image: Implement basic lossless webp writing 

- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.h
This is part of the spec but was missed. This fixes a crash on: https://www.kevs3d.co.uk/dev/phoria/test1d.html
> LibWeb: Ignore setting zero, negative, or non-finite CRC2D.lineWidths

- Ladybird/Qt/BrowserWindow.cpp
This was accidentally removed in 5da9af4.
> Ladybird: Add the "Debug" category back to the menubar

- Base/home/anon/Source/little/Makefile
- Base/res/devel/templates/cpp-basic.postcreate
- Base/res/devel/templates/cpp-library.postcreate
- CONTRIBUTING.md
- Documentation/BuildInstructions.md
- Documentation/BuildInstructionsLadybird.md
- Documentation/Links.md
- Documentation/NvimConfiguration.md
- Documentation/QtCreatorConfiguration.md
- Documentation/VSCodeConfiguration.md
- Ladybird/Android/build.gradle.kts
- Meta/CMake/common_compile_options.cmake
- Meta/gn/build/BUILD.gn
- Ports/OpenJDK/patches/0002-make-Build-with-c-23-when-targeting-serenity.patch
- Ports/OpenJDK/patches/ReadMe.md
- Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
- Ports/stpuzzles/package.sh
- Ports/xmp-cli/patches/0001-Add-support-for-Serenity-LibAudio.patch
Now that oss-fuzz is on a clang commit > the 17.x release candidates, we can start looking at some shiny new features to enable.
> Meta+Documentation+Ports: Move from C++20 to C++23

- Userland/Libraries/LibGfx/Font/BitmapFont.cpp
- Userland/Libraries/LibGfx/Font/BitmapFont.h
- Userland/Libraries/LibGfx/Font/Font.h
- Userland/Libraries/LibGfx/Font/ScaledFont.cpp
- Userland/Libraries/LibGfx/Font/ScaledFont.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.cpp
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
For bitmap fonts, we will often not have an exact match for requested sizes. Return the closest match instead of a nullptr.
LibWeb is currently the only user of this API. If it needs to be configurable in the future to only allow exact matches, we can add a parameter or another method at that time.
Fixes #24238
> LibGfx+LibWeb: Allow inexact size lookups when requesting scaled fonts

- AK/String.cpp
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/BasicBlock.cpp
- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/Executable.cpp
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/IdentifierTable.cpp
- Userland/Libraries/LibJS/Bytecode/IdentifierTable.h
- Userland/Libraries/LibJS/Bytecode/Instruction.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Label.cpp
- Userland/Libraries/LibJS/Bytecode/Label.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGenerator.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
- Userland/Libraries/LibJS/Runtime/GeneratorObject.cpp
- Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
- Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
tl;dr:
- Flatten the bytecode from disjoint basic blocks to contiguous byte sequence.
- Elide 0-length jumps
- Reorder codegen a bit to take advantage of 0-length jump elision
- Make bytecode interpreter threaded (as in "direct threaded", not multi-threaded)
- Make instructions smaller in various ways
Result: everything much faster!
Benchmark results before/after:
```
Kraken      ai-astar.js                              1.707  4.960 ± 4.950 … 4.970        2.905 ± 2.860 … 2.950
Kraken      audio-beat-detection.js                  1.544  2.610 ± 2.560 … 2.660 …
```
> LibJS: Flatten the bytecode representation and make interpreter fast

- Tests/LibWeb/Ref/box-without-scrollable-overflow-should-not-consume-scroll-events.html
- Tests/LibWeb/Ref/reference/box-without-scrollable-overflow-should-not-consume-scroll-events-ref.html
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Specifically, without scrollable overflow.
Fixes https://github.com/SerenityOS/serenity/issues/24009, both on brave.com and on the reduction.
This fixes the bug that on old reddit with an expando open you could not scroll when having the cursor over the expando. Behaviour is now the same as on Chromium and Firefox.
The issue minimized to the following code: (Where with mouse over the blue box scroll inputs have no effect.)
```html
<body>
<div style="overflow: auto; height: 250px; width: 250px; background-color: blue;"></div>
<div style="height: 1080px; width: 50px; background-color: black;"></div>
</body>
</html>
```
A process question:
My commit title is less then 70 characters as the pre commit hook required. Would it be okay to expand the github title to longer to …
> LibWeb: Do not consume scroll event in PaintableBox without overflow

- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
When I wrote the webp lossless decoder, I left some feedback on the spec about things I found confusing or about things that were missing. Most of that actually got fixed! So update spec comments to match the current spec. Tweak some code in minor ways to look more like the spec, too.
No behavior change intended.
> LibGfx/WebPLossless: Update spec comments with newest version of spec

- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
That way, we can write 0 instead of 8 bits for every alpha byte.
Reduces the size of sunset-retro.png when saved as a webp file
from 3 MiB to 2.25 MiB, without affecting encode speed.
Once we use CanonicalCodes we'll get this for free for all channels,
but opaque images are common enough that it feels worth it to do this
before then.
> LibGfx/WebPWriter: Use one-element huffman tree for opaque images

- Meta/gn/build/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibJS/BUILD.gn
Xcode clang doesn't understand the -std=c++23 spelling yet, and this
is what CMake's `set(CMAKE_CXX_STANDARD 23)` translates to too.
Unbreaks building with Xcode clang on macOS.
---
Also port one change.
> Meta: Use -std=c++2b on mac hosts in the GN build

- .github/actions/cache-restore/action.yml
- .github/actions/cache-save/action.yml
- .github/workflows/cmake.yml
- .github/workflows/libjs-test262.yml
- .github/workflows/pvs-studio-static-analysis.yml
- .github/workflows/serenity-js-artifacts.yml
- .github/workflows/sonar-cloud-static-analysis.yml
- .github/workflows/wasm.yml
Main differences between this and #24188:
* Fixed some output variable references with the toolchain and QEMU caches
* Enable ccache for the lagom builds (JS and WASM REPLs). There was a comment that the lagom ccache is for sanitized builds, but we can just use a separate cache for these by keying them differently.
* Run the cache-save action before running tests. This was intentionally done before to ensure e.g. our ccache is updated even if tests flake.
* Added cache-save action where it was missing
* Renamed the `toolchain_cache_*` variables to `toolchain_prebuilt_*`. Just to avoid mixups with `toolchain_ccache_*` for my poor eyes
* Renamed toolchain parameters from `gcc` and `clang` to `GNU` and `Clang`. This will more easily allow migrating the clang toolchain over to GHA, as we can …
> CI: Use common cache restore and cache save action on GitHub Actions

- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.gml
- Userland/Applications/HexEditor/HexEditorWidget.h
- Userland/Applications/HexEditor/ValueInspectorModel.h
It's clearer to have the choice here than hidden away in a menu. It also means we don't need the column heading to say the endianness.
> HexEditor: Move endianness selector to Value Inspector panel

- Kernel/Memory/Region.h
- Kernel/Syscalls/execve.cpp
- Kernel/Syscalls/mmap.cpp
- Userland/DynamicLoader/main.cpp
Previously, if DynamicLoader were invoked directly, it wasn't able to perform syscalls after the point just before the call to the main executable entry. This made dlopen to crash if it were called from within an executable that was itself executed using `/usr/lib/Loader.so <executable>`.
> Kernel+DynamicLoader: Allow syscalls from dynamic loader more often

- AK/IntegralMath.h
- Tests/AK/TestIntegerMath.cpp
The existing approach was causing failures particularly for `base != 2`:
The fix now allows those tests to pass, as well as adding more explicit testing for the edge cases:
> AK: Replace FP math in `is_power_of` with a purely integral algorithm

- Userland/Libraries/LibDebug/Dwarf/CompilationUnit.cpp
- Userland/Libraries/LibDebug/Dwarf/CompilationUnit.h
- Userland/Libraries/LibDebug/Dwarf/DwarfInfo.cpp
- Userland/Libraries/LibDebug/Dwarf/LineProgram.cpp
- Userland/Libraries/LibDebug/Dwarf/LineProgram.h
This causes CrashReporter to no longer crash (and therefore creating an infinite crash loop) on riscv64 clang, as riscv64 clang for some reason inserts an empty line program entry at the beginning and end of `.debug_line` of libc.so that has no matching compilation unit entry.
> LibDebug: Don't assume compilation unit index == line program index

- Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
- Userland/Libraries/LibWeb/DOM/ShadowRoot.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.idl
- Userland/Libraries/LibWeb/Fetch/Enums.cpp
- Userland/Libraries/LibWeb/Fetch/Enums.h
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/PortBlocking.cpp
- Userland/Libraries/LibWeb/Fetch/Request.cpp
- Userland/Libraries/LibWeb/Fetch/Request.h
- Userland/Libraries/LibWeb/Fetch/Request.idl
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
This is a follow up to a previous commit (https://github.com/SerenityOS/serenity/commit/da8d0d82c0c0e733e6485717f12a3956f1776881) I made as part of https://github.com/SerenityOS/serenity/pull/24164. This completes more of the implementation of the following spec changes:
- https://github.com/whatwg/fetch/commit/49bff76
- https://github.com/whatwg/html/commit/37659e9
> LibWeb/Fetch: Use "json" destination

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.h
https://github.com/SerenityOS/serenity/assets/11597044/f668ef52-5d71-46ff-a63a-d59cf9f4be19
Found the old behaviour a little odd (and knew how to hack around it). I saw this mentioned on Discord too (so if someone already has a patch WIP I'm happy to close this). 
cc @jamierocks
> Ladybird: Ensure hamburger menu is placed within the browser window

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Tests/try-return-finally.js
Also removes a bunch of related old FIXMEs.
----
Test262:
```
test/built-ins/AsyncGeneratorPrototype/throw/throw-suspendedYield-try-finally.js                       ❌ -> ✅
test/built-ins/GeneratorPrototype/return/try-finally-nested-try-catch-within-inner-try.js              ❌ -> ✅
test/built-ins/GeneratorPrototype/throw/try-finally-nested-try-catch-within-catch.js                   ❌ -> ✅
test/built-ins/GeneratorPrototype/throw/try-finally-nested-try-catch-within-outer-try-after-nested.js  ❌ -> ✅
test/built-ins/GeneratorPrototype/throw/try-finally-nested-try-catch-within-outer-try-before-nested.js ❌ -> ✅
test/built-ins/GeneratorPrototype/throw/try-finally-within-try.js                                      ❌ -> ✅
````
> LibJS: Save and restore exceptions on yields in finalizers

- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Bytecode/Operand.h
- Userland/Libraries/LibJS/Bytecode/ScopedOperand.cpp
- Userland/Libraries/LibJS/Bytecode/ScopedOperand.h
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/IndexedProperties.cpp
- Userland/Libraries/LibJS/Runtime/IndexedProperties.h
- Userland/Libraries/LibJS/Runtime/Value.h
See individual commits.
Benchmark results before/after:
```
Kraken      ai-astar.js                              0.998  2.905 ± 2.860 … 2.950        2.910 ± 2.900 … 2.920
Kraken      audio-beat-detection.js                  1.112  1.690 ± 1.690 … 1.690        1.520 ± 1.520 … 1.520
Kraken      audio-dft.js                             1.106  1.620 ± 1.620 … 1.620        1.465 ± 1.460 … 1.470
Kraken      audio-fft.js                             1.106  1.565 ± 1.540 … 1.590        1.415 ± 1.410 … 1.420
Kraken      audio-oscillator.js                      1.064  1.820 ± …
```
> LibJS: Mixed bag of optimizations

- Kernel/FileSystem/SysFS/Subsystems/Kernel/Network/Adapters.cpp
- Kernel/Net/NetworkAdapter.cpp
- Kernel/Net/NetworkAdapter.h
- Userland/Applications/SystemMonitor/NetworkStatisticsWidget.cpp
The dropped packets status is shown in the last column of the network adapter column in the SystemMonitor app.
> Kernel/net: Add tracking of dropped packets per adapter 

- Tests/LibWeb/Text/input/HTML/form-image-submission.html
We are often trying to click the image before it has finished loading. This results in us trying to click a 0x0 rect. Instead, wait until the image load event.
This fixes a flake with form-image-submission.html often seen on CI.
> LibWeb: Don't try to click a form image until it has loaded

- AK/Optional.h
- AK/Platform.h
- AK/Variant.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/Builtins.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Bytecode/ScopedOperand.h
- Userland/Libraries/LibJS/Bytecode/StringTable.h
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/AsyncGeneratorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Completion.cpp
- Userland/Libraries/LibJS/Runtime/Completion.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/GeneratorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/IteratorHelperPrototype.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp
Lots of data structure shrinking + peephole optimizations today!
Some really nice benchmark progressions:
```
Kraken      ai-astar.js                              1.066  2.910 ± 2.900 … 2.920        2.730 ± 2.700 … 2.760
Kraken      audio-beat-detection.js                  0.849  1.520 ± 1.520 … 1.520        1.790 ± 1.790 … 1.790
Kraken      audio-dft.js                             1.089  1.465 ± 1.460 … 1.470        1.345 ± 1.340 … 1.350
Kraken      audio-fft.js                             0.835  1.415 ± 1.410 … 1.420        1.695 ± 1.690 … 1.700
Kraken …
```
> LibJS: Another big bag of optimizations

- Documentation/BuildInstructions.md
- Documentation/BuildInstructionsLadybird.md
- Meta/Lagom/BuildFuzzers.sh
- Meta/Lagom/Tools/LibJSGCVerifier/CMakeLists.txt
- Meta/find_compiler.sh
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
(Follow up to https://github.com/SerenityOS/serenity/pull/24276 which was merged prematurely)
Instructions now have a static `MayThrow` bool member that tells the
interpreter whether it needs to check exceptions after executing it.
Instructions that can't throw now return void from execute_impl(),
which lets us enforce the fact that nothing does get thrown.
Thanks Leon for suggesting this!
> LibJS/Bytecode: Make execute_impl() return void for non-throwing ops + Update docs to require Clang 17+

- Tests/LibWeb/Text/expected/css/FontFace.txt
- Tests/LibWeb/Text/input/css/FontFace.html
- Userland/Libraries/LibWeb/CSS/FontFace.cpp
- Userland/Libraries/LibWeb/CSS/FontFace.h
- Userland/Libraries/LibWeb/CSS/FontFace.idl
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
We only support parsing half of these, so the ones we don't recognize
get a friendly exception thrown.
> LibWeb: Implement or stub FontFace interface's attribute getters/setters 

- Userland/Games/Chess/ChessWidget.cpp
- Userland/Libraries/LibChess/Chess.cpp
Fix the incorrect parsing in `Chess::Move::from_algebraic` of moves with a capture and promotion (e.g. gxf8=Q) due to the promoted piece type not being passed through to the `Board::is_legal` method.
> LibChess: Fix crash when importing PGN 

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
This code was a leftover from AST interpreter.
> LibJS: Delete named_evaluation_if_anonymous_function()

- Meta/Lagom/CMakeLists.txt
- Tests/LibGfx/TestImageWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.h
- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/animation.cpp
The high-level design is that we have a static method on WebPWriter that
returns an AnimationWriter object. AnimationWriter has a virtual method
for writing individual frames. This allows streaming animations to disk,
without having to buffer up the entire animation in memory first.
The semantics of this function, add_frame(), are that data is flushed
to disk every time the function is called, so that no explicit `close()`
method is needed.
For some formats that store animation length at the start of the file,
including WebP, this means that this needs to write to a SeekableStream,
so that add_frame() can seek to the start and update the size when a
frame is written.
This design should work for GIF and APNG writing as well. We can move
AnimationWriter to a new header if we add writers for …
> LibGfx+Utilities: Add animation utility, make it write animated webps

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Runtime/PrivateEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/PrivateEnvironment.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
```
Duration:
-0.39s
Summary:
Diff Tests:
+20 ✅    -20 💥   
Diff Tests:
test/language/expressions/class/accessor-name-inst-computed-yield-expr.js                                     💥 -> ✅
test/language/expressions/class/accessor-name-static-computed-yield-expr.js                                   💥 -> ✅
test/language/expressions/class/cpn-class-expr-accessors-computed-property-name-from-await-expression.js      💥 -> ✅
test/language/expressions/class/cpn-class-expr-accessors-computed-property-name-from-yield-expression.js      💥 -> ✅
test/language/expressions/class/cpn-class-expr-computed-property-name-from-await-expression.js                💥 -> ✅
test/language/expressions/class/cpn-class-expr-computed-property-name-from-yield-expression.js                💥 -> ✅ …
```
> LibJS: Remove VM::execute_ast_node()

- Kernel/Bus/VirtIO/Device.cpp
- Kernel/Devices/GPU/Console/VGATextModeConsole.cpp
The following command was used to clang-format these files:
clang-format-18 -i $(find . \
-not \( -path "./\.*" -prune \) \
-not \( -path "./Base/*" -prune \) \
-not \( -path "./Build/*" -prune \) \
-not \( -path "./Toolchain/*" -prune \) \
-not \( -path "./Ports/*" -prune \) \
-type f -name "*.cpp" -o -name "*.mm" -o -name "*.h")
There was a recent release of clang-format version 18.1.5 which fixes errant spaces around `->` in these files.
> Kernel: Run clang-format

- Userland/Applications/Browser/main.cpp
This fixes a crash when attempting to display thumbnails for image files in the FilePicker if thread is not pledged.
> Browser: Pledge thread for FilePicker

- Tests/LibWeb/Text/expected/Worker/Worker-blob.txt
- Tests/LibWeb/Text/input/Worker/Worker-blob.html
- Userland/Libraries/LibIPC/Decoder.cpp
- Userland/Libraries/LibIPC/Encoder.cpp
- Userland/Libraries/LibURL/Forward.h
- Userland/Libraries/LibURL/URL.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/FileAPI/BlobURLStore.cpp
- Userland/Libraries/LibWeb/FileAPI/BlobURLStore.h
Not really sure on approach of this going forward, but it does at least make more stuff work.
Further progress towards: https://github.com/SerenityOS/serenity/issues/23632
> LibWeb: Add support for blob URL in web workers

- Meta/Lagom/Tools/CodeGenerators/LibLocale/GenerateNumberFormatData.cpp
- Meta/Lagom/Tools/CodeGenerators/LibLocale/GeneratePluralRulesData.cpp
When building `LibLocale`, I noticed a couple of the headers were putting includes before the `#pragma once` statement. Most of the generators were doing it correctly, but here is a fix for the remaining that weren't.
Before:
After:
> LibLocale: Move includes below `#pragma once` in generated headers

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Executable.cpp
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
- Userland/Libraries/LibJS/Runtime/GlobalEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/Reference.cpp
Another batch of small optimizations.
Roughly 3% speed-up across all of Octane while Kraken looks neutral.
```
----------  -----------------------------------  ---------  ---------------------------  --------------------------
Kraken      ai-astar.js                              1.011  2.710 ± 2.700 … 2.720        2.680 ± 2.660 … 2.700
Kraken      audio-beat-detection.js                  0.994  1.770 ± 1.760 … 1.780        1.780 ± 1.780 … 1.780
Kraken      audio-dft.js                             1.008  1.340 ± 1.340 … 1.340        1.330 ± 1.310 … 1.350
Kraken      audio-fft.js                             0.997  1.670 ± 1.670 … 1.670        1.675 ± 1.670 … 1.680
Kraken …
```
> LibJS: Weekend optimization pack

- Userland/Applications/MouseSettings/ThemeWidget.cpp
To align the cursor theme tab to how DisplaySettings themes tab works, this change forces the theme combo box to not allow free-text. Currently on a click it puts the text cursor in the box to allow typing anything rather than acting as a dropdown when clicking anywhere on the field.
Fixes #24306
> MouseSettings: Only allow valid cursor themes

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Bytecode/Operand.h
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
Merging registers, constants and locals into single vector means:
- Better data locality
- No need to check type in Interpreter::get() and Interpreter::set() which are very hot functions
Performance improvement is visible in almost all Octane and Kraken tests.
```
Kraken      ai-astar.js                              1.047  1.660 ± 1.580 … 1.740     1.585 ± 1.580 … 1.590
Kraken      audio-beat-detection.js                  1.06   1.240 ± 1.240 … 1.240     1.170 ± 1.170 … 1.170
Kraken      audio-dft.js                             1.057  0.920 ± 0.890 … 0.950     0.870 ± 0.870 … …
```
> LibJS: Join locals, constants and registers into single vector

- Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
- Userland/Libraries/LibWeb/CSS/FontFaceSet.h
- Userland/Libraries/LibWeb/CSS/FontFaceSet.idl
WPT wants to check these properties before running ref tests. This fixes a ton of crashes in our CI WPT runs.
Output from ./Tests/LibWeb/run.sh:
This PR:
```
Ran 120 tests finished in 22.7 seconds.
• 109 ran as expected. 0 tests skipped.
• 8 tests failed unexpectedly
• 1 tests passed unexpectedly
• 2 tests had unexpected subtest results
```
Current master:
```
Ran 120 tests finished in 139.7 seconds.
• 13 ran as expected. 0 tests skipped.
• 105 tests crashed unexpectedly
• 2 tests had unexpected subtest results
```
> LibWeb: Stub out FontFaceSet.status and .ready attributes

- Tests/LibGfx/CMakeLists.txt
- Tests/LibGfx/TestColor.cpp
- Userland/Libraries/LibGfx/Color.h
Truncating the value is mathematically incorrect, this error made the conversion to grayscale unstable. In other world, calling `to_grayscale` on a gray value would return a different value. As an example, `Color::from_string("#686868ff"sv).to_grayscale()` used to return #676767ff.
> LibGfx: Correctly round values when computing the luminosity of a Color

- Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
- Userland/Libraries/LibWeb/DOM/AbortSignal.h
- Userland/Libraries/LibWeb/DOM/AbortSignal.idl
This allows some boilerplate code to be generated automatically.
I'm not sure why this didn't work when I first implemented this method, but it works now :shrug:
> LibWeb: Specify the correct argument type in IDL for AbortSignal::any()

- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
No need for separate instuction to set a local.
> LibJS: Replace SetLocal instruction usage with Mov

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
This means that `SetVariable` instructions will now remember which (relative) environment contains the targeted binding, letting it bypass the full binding resolution machinery on subsequent accesses.
Small but decent speed-ups across the board in Kraken and Octane:
```
Kraken      ai-astar.js                              1.018  2.575 ± 2.550 … 2.600     2.530 ± 2.510 … 2.550
Kraken      audio-beat-detection.js                  1.042  1.505 ± 1.500 … 1.510     1.445 ± 1.440 … 1.450
Kraken      audio-dft.js                             1.004  1.235 ± 1.230 … 1.240     1.230 ± …
```
> LibJS/Bytecode: Add environment coordinate caching to SetVariable

- Tests/LibWeb/Text/expected/DOM/Document-dir.txt
- Tests/LibWeb/Text/input/DOM/Document-dir.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
This was seen getting called on stuff.co.nz and resulting in an exception getting thrown due to no String being returned (before ladybird crashes later on due to an unrelated navigation bug) https://github.com/SerenityOS/serenity/issues/24198
> LibWeb: Implement Document.dir

- Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
- Tests/LibGfx/TestImageWriter.cpp
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/ImageFormats/AnimationWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/AnimationWriter.h
- Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPShared.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.h
- Userland/Utilities/animation.cpp
For example, for 7z7c.gif, we now store one 500x500 frame and then
a 94x78 frame at (196, 208) and a 91x78 frame at (198, 208).
This reduces how much data we have to store.
We currently store all pixels in the rect with changed pixels.
We could in the future store pixels that are equal in that rect
as transparent pixels. When inputs are gif files, this would
guaranteee that new frames only have at most 256 distinct colors
(since GIFs require that), which would help a future color indexing
transform. For now, we don't do that though.
The API I'm adding here is a bit ugly:
* WebPs can only store x/y offsets that are a multiple of 2. This
currently leaks into the AnimationWriter base class.
(Since we potentially have to make a webp frame 1 pixel wider
and higher due to this, it's possible to …
> LibGfx+animation: Only store changed pixels in animation frames

- CMakeLists.txt
- Meta/CMake/clang_development.cmake
- Meta/CMake/utils.cmake
- Meta/Lagom/CMakeLists.txt
- Meta/Lagom/ClangPlugins/CMakeLists.txt
- Tests/ClangPlugins/CMakeLists.txt
:partying_face: 
As a note, the Lambda capture one is *very* noisy.
And the warnings from these plugins don't seem to respect -Werror which is... good(?)
> CI+CMake: Enable Clang plugins for Serenity Clang builds

- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
More work towards going fast. See individual commits.
Benchmarks move in the right direction :^)
```
Kraken      ai-astar.js                              1.053  2.575 ± 2.570 … 2.580     2.445 ± 2.430 … 2.460
Kraken      audio-beat-detection.js                  1.017  1.455 ± 1.440 … 1.470     1.430 ± 1.430 … 1.430
Kraken      audio-dft.js                             1.034  1.225 ± 1.210 … 1.240     1.185 ± 1.170 … 1.200
Kraken      audio-fft.js                             0.975  1.355 ± 1.350 … 1.360     1.390 ± 1.390 … 1.390
Kraken      audio-oscillator.js …
```
> LibJS: Another day, another pack of optimizations

- AK/StackInfo.cpp
> AK: Add stack size fixup for musl libc

- Toolchain/default.nix
Currently, if building under `nix-shell Toolchain`, serenityOS'
gcc won't build because of hardening options added in nix,
more specifically the breaking format-security.
> nix-shell: Disable gcc hardening to be able to build toolchain

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
With this only `ContinuePendingUnwind` needs to dynamically check if a
scheduled return needs to go through a `finally` block, making the
interpreter loop a bit nicer
> LibJS: Make the return path CF more static

- Tests/LibGfx/TestImageWriter.cpp
This removes the somewhat awkward is_gif that got added in
2513a1b83f68ceecb56074a26cdbc039c658e01f again.
> Tests/TestImageWriter: Remove is_gif parameter again

- Userland/Libraries/LibGUI/Toolbar.cpp
This prevents a crash in GML Playground that would occur when previewing a GUI with a collapsible toolbar.
Fixes #24303
> LibGUI: Don't crash when rendering a collapsible toolbar with no items

- .github/actions/setup/action.yml
- .github/workflows/lagom-template.yml
- .github/workflows/serenity-template.yml
- Meta/gn/secondary/Ladybird/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/WebAudio/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
- Toolchain/BuildClang.sh
This was used to create a .tar of the built Clang toolchain, but now we
just upload the built toolchain artifacts (same as the GNU toolchain).
Ref https://github.com/SerenityOS/serenity/pull/24263#discussion_r1594302549
> Toolchain+CI: Remove unused TRY_USE_LOCAL_TOOLCHAIN parameter

- Tests/LibWeb/Text/expected/css/FontFace-load-urls.txt
- Tests/LibWeb/Text/input/css/FontFace-load-urls.html
- Userland/Libraries/LibWeb/CSS/FontFace.cpp
- Userland/Libraries/LibWeb/CSS/FontFace.h
- Userland/Libraries/LibWeb/CSS/Parser/ParsingContext.cpp
- Userland/Libraries/LibWeb/CSS/Parser/ParsingContext.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.h
- Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.h
And make a bit of a mess out of StyleComputer::FontLoader in the process :^)
> LibWeb: Implement FontFace.load() for url() based font sources

- Userland/Libraries/LibWeb/HTML/Canvas/CanvasImageData.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasImageData.idl
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
It is now possible to pass an optional `ImageDataSettings` object to the `CanvasImageData.createImageData()` and
`CanvasImageData.getImageData()` methods.
> LibWeb: Use correct IDL definition for CanvasImageData methods

- Tests/LibWeb/Text/expected/HTML/HTMLOptionElement-form.txt
- Tests/LibWeb/Text/input/HTML/HTMLOptionElement-form.html
- Userland/Libraries/LibWeb/HTML/HTMLOptionElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLOptionElement.h
- Userland/Libraries/LibWeb/HTML/HTMLOptionElement.idl
This returns the parent form of a HTMLOptionElement or null if the element has no parent form.
Fixes this WPT test: http://wpt.live/html/semantics/forms/the-option-element/option-form.html
> LibWeb: Implement the `HTMLOptionElement.form` attribute

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/HTML/MessageEvent.cpp
- Userland/Libraries/LibWeb/HTML/MessageEvent.h
- Userland/Libraries/LibWeb/HTML/MessageEvent.idl
- Userland/Libraries/LibWeb/HTML/MessagePort.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
This didn't work previously because the IDL generator used the incorrect type for some types of sequences within dictionaries.
> LibWeb: Use correct type for `MessageEventInit.ports`

- Tests/LibWeb/Text/expected/HTML/relList-attribute.txt
- Tests/LibWeb/Text/input/HTML/relList-attribute.html
- Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
- Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLAreaElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.h
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.idl
This PR implements the `relList` attribute for the `<a>`, `<area>`, `<link>` and `<form>` elements.
This returns a DOMTokenList that reflects the `rel` attribute.
> LibWeb: Implement the `relList` attribute

- Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPShared.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.h
This is in preparation of implementing some actual compression one day.
3-5% faster since we make fewer copies.
<details>
<summary>perf measurements</summary>
(`test.bmp` is `Base/res/wallpapers/sunset-retro.png` converted to .bmp format using `image`. `giphy.gif is the gif at https://giphy.com/gifs/XT9HMdwmpHqqOu1f1a downloaded with `curl`.)
```
~/src/hack/bench.py -n 50 -o bench_before.txt Build/lagom/bin/image -o test.webp test.bmp         
~/src/hack/bench.py -n 50 -o bench_anim_before.txt Build/lagom/bin/animation -o wow.webp giphy.gif
% ministat -q bench_before.txt bench_after.txt
x bench_before.txt
+ bench_after.txt
N           Min           Max        Median           Avg        Stddev
x  50   0.024741173   0.027699947   0.026391983   0.026248369 0.00078138374 …
```
> LibGfx/WebPWriter: Clean up internal APIs a bit and move lossless compression code to WebPWriterLossless.{h,cpp}

- Userland/Games/Chess/CMakeLists.txt
- Userland/Games/Chess/Chess.gml
- Userland/Games/Chess/ChessWidget.cpp
- Userland/Games/Chess/ChessWidget.h
- Userland/Games/Chess/MainWidget.h
- Userland/Games/Chess/PromotionDialog.cpp
- Userland/Games/Chess/PromotionDialog.h
- Userland/Games/Chess/PromotionWidget.gml
- Userland/Games/Chess/PromotionWidget.h
- Userland/Games/Chess/main.cpp
This PR adds the chess application to the `Chess` namespaces and then ports the 
chess application to GML in order to facilitate the addition of widgets in the future.
> Chess: Port application to GML

- Toolchain/CMake/meson-cross-file-Clang.txt.in
- Toolchain/CMake/meson-cross-file-GNU.txt.in
Noticed these were still set to `x86` while playing around with enabling the dynamic core on our `dosbox-staging` port.
EDIT:
Switching to the environment variable `SERENITY_ARCH` instead of the hardcoded value for `cpu_family`. Seems that both `cpu_family` and `cpu` is supposed have the value `x86_64 in our case`: https://mesonbuild.com/Cross-compilation.html#cross-compilation
> Toolchain: Set cpu_family in meson cross files to SERENITY_ARCH

- Tests/LibWeb/Text/expected/HTML/HTMLLabelElement-form.txt
- Tests/LibWeb/Text/expected/HTML/HTMLObjectElement-form.txt
- Tests/LibWeb/Text/input/HTML/HTMLLabelElement-form.html
- Tests/LibWeb/Text/input/HTML/HTMLObjectElement-form.html
- Userland/Libraries/LibWeb/HTML/HTMLLabelElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLLabelElement.h
- Userland/Libraries/LibWeb/HTML/HTMLLabelElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.idl
This PR adds the `form` attribute to the `<label>` and `<object>` elements. In the case of `<object>` we are simply exposing functionality that already exists in `FormAssociatedElement`.  
With these changes we now pass the following WPT test:  http://wpt.live/html/semantics/forms/form-control-infrastructure/form.html
> LibWeb: Implement the `form` attribute for `<label>` and `<object>` elements

- Tests/LibWeb/Text/expected/HTML/HTMLOutputElement-htmlfor.txt
- Tests/LibWeb/Text/input/HTML/HTMLOutputElement-htmlfor.html
- Userland/Libraries/LibWeb/HTML/HTMLOutputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLOutputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLOutputElement.idl
This returns a DOMTokenList that reflects the `for` attribute.
> LibWeb: Implement the `HTMLOutputElement.htmlFor` attribute

- Tests/LibWeb/Text/expected/HTML/HTMLElement-labels.txt
- Tests/LibWeb/Text/input/HTML/HTMLElement-labels.html
- Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLMeterElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLOutputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLProgressElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
This returns a `NodeList` of all the labels associated with the given element.
With this change we now pass this WPT test: http://wpt.live/html/semantics/forms/the-label-element/labelable-elements.html
> LibWeb: Implement the `labels` attribute for all labelable elements

- AK/Checked.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Tests/math/integer-overflow-basic.js
It wasn't safe to use addition_would_overflow(a, -b) to check if subtraction (a - b) would overflow, since it doesn't cover this case.
I don't know why we didn't have subtraction_would_overflow(), so this patch adds it. :^)
> LibJS+AK: Fix integer overflow UB on (any Int32 - -2147483648)

- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
#24359 was merged just as I pushed the fix for this :sweat_smile:
> LibWeb: Add missing visit to `m_labels` in HTMLElement

- AK/Statistics.h
- Tests/LibGfx/CMakeLists.txt
- Tests/LibGfx/TestImageWriter.cpp
- Tests/LibGfx/TestMedianCut.cpp
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/Color.h
- Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp
- Userland/Libraries/LibGfx/MedianCut.cpp
- Userland/Libraries/LibGfx/MedianCut.h
You can clearly see the lack of diversity in the colors due to the size of the table being limited to 256 elements.
> LibGfx/GIF: Support Colors

- AK/FixedArray.h
This not only makes code easier to follow but also makes it faster.
PS: I haven't actually tried to find FixedArray's current users in the codebase but this makes my WIP async inflate 5% faster.
> AK: Don't put element count next to heap-allocated data in FixedArray

- Tests/LibWeb/Layout/expected/zero-height-viewport-svg-image.txt
- Tests/LibWeb/Layout/expected/zero-width-viewport-svg-image.txt
- Tests/LibWeb/Layout/input/zero-height-viewport-svg-image.html
- Tests/LibWeb/Layout/input/zero-width-viewport-svg-image.html
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
We were previously crashing by a division by zero due to an aspect ratio of zero on https://comicbookshop.co.nz/
> LibWeb: Fix division by zero on a zero-width viewport SVG image

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
So that when we need add a new namespace in LibWeb we only have a single place that needs to be changed.
> LibWeb: Factor out IDL generator using namespace hack into a function

- Tests/LibWeb/Text/expected/scroll-into-view-center.txt
- Tests/LibWeb/Text/input/scroll-into-view-center.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
This fixes a crash on:
https://docs.github.com/en/get-started/learning-about-github/githubs-plans
> LibWeb: Implement scrollIntoView with 'center' block position

- Userland/Libraries/LibWeb/DOMParsing/InnerHTML.cpp
This will help us in detecting potential web compatability issues from not having this implemented.
While we're at it, update the spec link, as it was moved from the DOM parsing spec to the HTML one, and implement this function in a manner that closr resembles spec text.
> LibWeb: Log a FIXME when parsing fragments for XML documents

- Tests/LibWeb/Text/expected/WebAudio/DynamicsCompressorNode.txt
- Tests/LibWeb/Text/input/WebAudio/DynamicsCompressorNode.html
- Userland/Libraries/LibWeb/WebAudio/DynamicsCompressorNode.cpp
- Userland/Libraries/LibWeb/WebAudio/DynamicsCompressorNode.h
- Userland/Libraries/LibWeb/WebAudio/DynamicsCompressorNode.idl
This gets us up to the AudioNode::connect in the testcase for https://github.com/SerenityOS/serenity/issues/22902, also further progress towards: https://github.com/SerenityOS/serenity/issues/23632
> LibWeb: Implement AudioParams for DynamicsCompressorNode

- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Tests/try-finally-break.js
The VERIFY assumed that we either have a finally block which we already
visited through a previous boundary or have no finally block what so
ever; But since 301a1fc7631bb862f003cc2ebfab37a42e5fdbc5 we propagate
finalizers through unwind scopes breaking that assumption.
---
Fixes the crash seen on facebook.com
CC: @shannonbooth
> LibJS: Remove an old VERIFY from break handling in try-finally blocks

- Ladybird/RequestServer/CMakeLists.txt
- Tests/LibCrypto/TestAES.cpp
- Userland/Libraries/LibCore/DeferredInvocationContext.h
- Userland/Libraries/LibCore/ElapsedTimer.cpp
- Userland/Libraries/LibCore/ElapsedTimer.h
- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibCore/EventLoop.h
- Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
- Userland/Libraries/LibCore/Notifier.h
- Userland/Libraries/LibCore/ThreadEventQueue.cpp
- Userland/Libraries/LibCrypto/Authentication/GHash.cpp
- Userland/Libraries/LibTLS/Socket.cpp
- Userland/Libraries/LibTLS/TLSv12.cpp
- Userland/Libraries/LibThreading/MutexProtected.h
- Userland/Libraries/LibThreading/RWLock.h
- Userland/Libraries/LibThreading/RWLockProtected.h
- Userland/Libraries/LibThreading/ThreadPool.h
- Userland/Services/RequestServer/CMakeLists.txt
- Userland/Services/RequestServer/ConnectionCache.cpp
- Userland/Services/RequestServer/ConnectionCache.h
- Userland/Services/RequestServer/ConnectionFromClient.cpp
- Userland/Services/RequestServer/ConnectionFromClient.h
- Userland/Services/RequestServer/GeminiProtocol.cpp
- Userland/Services/RequestServer/HttpCommon.h
- Userland/Services/RequestServer/main.cpp
> LibCore+RS+LibCrypto: Make RS (crash) faster

- Tests/LibWeb/Text/expected/UIEvents/mouse-events.txt
- Tests/LibWeb/Text/input/UIEvents/mouse-events.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
This returns the secondary target of a mouse event. For `onmouseenter` and `onmouseover` events, this is the EventTarget the mouse exited from. For `onmouseleave` and `onmouseout` events, this is the EventTarget the mouse entered to.
This seen gets rid of a FIXME message seen on https://bbc.co.uk.
> LibWeb: Implement the `MouseEvent.relatedTarget` attribute

- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
By doing this, we can remove all the special-case checks for `length` from the generic GetById and GetByIdWithThis code paths, making every other property lookup a bit faster.
Small progressions on most benchmarks, and some larger progressions:
- 12% on Octane/crypto.js
- 6% on Kraken/ai-astar.js
```
Kraken      ai-astar.js                              1.065  2.450 ± 2.450 … 2.450     2.300 ± 2.290 … 2.310
Kraken      audio-beat-detection.js                  1.014  1.455 ± 1.450 … 1.460     1.435 ± 1.420 … 1.450
Kraken      audio-dft.js                             1.013  1.195 …
```
> LibJS/Bytecode: Add dedicated instruction for getting `length` property

- Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn
- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPSharedLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPSharedLossless.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
We still construct the code length codes manually, and now we also
construct a PrefixCodeGroup manually that assigns 8 bits to all
symbols (except for fully-opaque alpha channels, and for the
unused distance codes, like before). But now we use the CanonicalCodes
from that PrefixCodeGroup for writing.
No behavior change at all, the output is bit-for-bit identical to
before. But this is a step towards actually huffman-coding symbols.
I thought this would be a nice and easy patch, but it regressed
perf quite a bit! I mitigated this a bit, so in total it's "only"
a 7-12% regression for exactly the same output. But a local
branch that builds actual data-dependent optimal huffman
trees is perf-neutral and adds at least some compression.
(I still haven't implemented backrefs.)
`hyperfine 'image …
> LibGfx/WebP(+LibCompress): Add CanonicalCode::write_symbol(), use it in writer

- Userland/Libraries/LibThreading/Thread.cpp
I get 64 of these guys starting the browser, which is a bit much when e.g. running a single test in headless-browser
> LibThreading: Remove extra spammy log message upon starting a thread

- Tests/LibWeb/Text/expected/Streams/ReadableStream-pipeTo-Writer-close-callback-called.txt
- Tests/LibWeb/Text/input/Streams/ReadableStream-pipeTo-Writer-close-callback-called.html
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
- Userland/Libraries/LibWeb/Fetch/Body.cpp
- Userland/Libraries/LibWeb/Fetch/BodyInit.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h
- Userland/Libraries/LibWeb/Fetch/Infrastructure/IncrementalReadLoopReadRequest.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/IncrementalReadLoopReadRequest.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStream.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
This implements:
- the concept incrementally read a body, and uses that implementation in XHR::send().
- the missing steps for TransformStream in fetch_response_handover().
Fixes a couple bugs:
- LibWeb: Provide an UInt8Array to AO writable_stream_default_writer_write
- LibWeb: Close acquired writer in AO readable_stream_pipe_to()
> LibWeb: Integrate TransformStream into fetch_response_handover() and Streams into XHR::send()

- AK/IntegralMath.h
- Tests/AK/TestIntegerMath.cpp
Previously, certain values of `ceil_log2(x)` would be 1 smaller than `ceil(log2(x))`.
In addition to the test cases I've included in this PR, I also tested `ceil_log2()` exhaustively (for all `u32`) with the following test case: 
```c++
TEST_CASE(ceil_log2_exhaustive)
{
for (u32 i = 1; i < NumericLimits<u32>::max(); i++)
{
if (AK::ceil_log2(i) != ceil(log2(i)))
FAIL(MUST(String::formatted("AK::ceil_log2(i) != ceil(log2(i) for i = {}, LHS = {}, RHS = {}", i, AK::ceil_log2(i), ceil(log2(i)))));
}
}
```
Before this PR, the above test generated the following output:
```
Running test 'ceil_log2_exhaustive'.
FAIL: /home/tim/repos/serenity/Tests/AK/TestIntegerMath.cpp:82: AK::ceil_log2(i) != ceil(log2(i) for i = 1, LHS = 1, RHS = 0
FAIL: /home/tim/repos/serenity/Tests/AK/TestIntegerMath.cpp:82: …
```
> AK: Fix off by one error in integral ceil_log2()

- Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/GIFWriter.h
- Userland/Utilities/animation.cpp
We are not writing any control block for frame duration or loop count, so the resulting image is not the best for a demonstration :sweat_smile:
But still here it is (loop count is 1, so you need to reload the page to see the animation again):
> LibGfx/GIF+animation: Support animated GIFs

- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
This allows us to skip allocating a function environment in cases where it was previously impossible because the arguments object needed a binding.
This change does not bring visible improvement in Kraken or Octane benchmarks but seems useful to have anyway.
> LibJS: Use a local variable for arguments object when possible

- Userland/Services/RequestServer/ConnectionCache.h
A connection's socket is allowed to be null if it's being recreated after a failed connect(), this was handled correctly in request_did_finish but not in recreate_socket_if_needed; this commit fixes this oversight.
> RequestServer: Account for null sockets in recreate_socket_if_needed()

- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
This is a follow up for 210a5d77dccdbbb53ab3fc705cd0c5bc07586ffc that actually allows to skip function environment allocation.
> LibJS: Do not count arguments as env binding when local variable is used

- Userland/Libraries/LibCore/DeferredInvocationContext.h
- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibCore/EventLoop.h
- Userland/Libraries/LibCore/ThreadEventQueue.cpp
This reverts commit a362c37c8b3d2c8f0d5e23276bfe81cb1c24d384.
The commit tried to add an unused function that continued our tradition of not properly waiting for things but instead flooding event loop with condition checks that delay firing of the event. I think this is a fundamentally flawed approach. See also checks for `fire_when_not_visible` in LibCore/EventLoopImplementationUnix.cpp.
> Revert "LibCore: Add Core::deferred_invoke_if(F, Condition)"

- Tests/LibGfx/TestImageWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/AnimationWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/GIFLoader.cpp
Creating a completely empty bitmap fails. Just write a 1x1 bitmap
if the bitmap ends up empty for now.
> LibGfx/AnimationWriter: Survive animations with two identical frames

- Userland/Libraries/LibCrypto/Checksum/Adler32.cpp
Otherwise Zlib decompression would have spent half of the time computing the checksum if it had checked it. (New asynchronous decompression does check the checksum and there this became a real problem)
> LibCrypto: Don't compute 2*N remainders in Adler32

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.cpp
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Allows to skip function environment allocation for non-arrow functions if the only reason it is needed is to hold `this` binding.
The parser is changed to do following:
- If a function is an arrow function and uses `this` then all functions in a scope chain are marked to allocate function environment for `this` binding.
- If a function uses `new.target` then all functions in a scope chain are marked to allocate function environment.
`ordinary_call_bind_this()` is changed to put `this` value in execution context when function environment allocation is skipped.
35% improvement in Octane/typescript.js
50% improvement in Octane/deltablue.js
19% improvement in Octane/raytrace.js
``` …
```
> LibJS: Get `this` from execution context for non-arrow functions

- Kernel/Prekernel/init.cpp
I did a mistake and set the kernel_physical_base value to be just on the actual linked kernel ELF start offset, while this value should represent together with KERNEL_MAPPING_BASE the actual higher-half load address.
Fixes #24395.
cc @timschumi @spholz
> Kernel: Actually set physical base pointer correctly in prekernel stage

- Ports/file/package.sh
We should build file natively as well so it can be used to compile the target build (for serenity). The Makefile doesn't do this automatically so to ensure it will not fail due to version mismatch between the host version and target version, we ensure we always have a native binary at hand.
Some funny backstory - I looked on the Internet something related to bashisms and dash, and was interested to see the state of the `dash` port, and (surprise surprise) I saw it did the `host_env` trickery @timschumi suggested to do and simply copied the procedures and changed it a bit to work according to the `README.DEVELOPER` guidelines in the port.
Closes #18415.
> Ports/file: Build host version to ensure we can properly cross compile

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/HTML/reflected-integer-attributes.txt
- Tests/LibWeb/Text/input/HTML/reflected-integer-attributes.html
This fixes an oversight from #24402.
> IDLGenerators: Use spec-compliant algorithm to parse integer values

- Userland/Games/Chess/Chess.gml
- Userland/Games/Chess/ChessWidget.cpp
- Userland/Games/Chess/ChessWidget.h
- Userland/Games/Chess/main.cpp
Adds a TextEditor widget to the chess application to display move
history. It is updated whenever Board::apply_move is called to reflect
the current board state.
> Chess: Add display widget for moves

- Userland/Libraries/LibWeb/WebAssembly/Instance.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
As it's not uncommon for users to drop the module instance on the floor after having grabbed the few exports they need to hold on to. Fixes a few UAFs that show up as "invalid" accesses to memory/tables/etc.
> LibWeb: Make exported Wasm functions keep the module instance alive

- Meta/find_compiler.sh
- Meta/gn/README.md
The logic in this script was *intended* to use the system's default compiler if it was sufficiently new, and only start searching for the latest installed if the default was not suitable.
However, the `cxx` program does not exist on Unixes, so the version check always failed. We should be using the standard `c++` program name instead.
After this change, the `CC` and `CXX` environment variables will have to be used if someone wants to force a newer compiler version.
> Meta: Fix detection of default compiler versions

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Userland/Libraries/LibJS/Runtime/FunctionConstructor.cpp
- Userland/Libraries/LibJS/SourceTextModule.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.cpp
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
If during parsing it was found that function won't use `this` then
there is no need to initialise `this_value` during call.
```
Kraken      ai-astar.js                              1      1.855 ± 1.850 … 1.860     1.855 ± 1.840 … 1.870
Kraken      audio-beat-detection.js                  1.014  1.440 ± 1.440 … 1.440     1.420 ± 1.410 … 1.430
Kraken      audio-dft.js                             1.063  1.270 ± 1.260 … 1.280     1.195 ± 1.190 … 1.200
Kraken      audio-fft.js                             1.023  1.335 ± 1.330 … 1.340     1.305 ± 1.300 … 1.310
Kraken …
```
> LibJS: Skip ordinary_call_bind_this() when possible

- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
We enqueue a microtask for this readable stream AO, and the methods that we call from the chunk steps manipulate promises. As such, we need to enable callbacks for the entire microtask's temporary execution context.
Fixes #24419
Now the nytimes website spins on something instead of crashing outright :)
> LibWeb: Enable callbacks in chunk steps for ReadableStreamDefaultTee

- Tests/LibWeb/Text/expected/WebAnimations/misc/animation-events-basic.txt
- Tests/LibWeb/Text/input/WebAnimations/misc/animation-events-basic.html
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
This patch fixes two issues:
- Animation events that should go to the target element now do (some were previously being dispatched on the animation itself.)
- We update the "previous phase" and "previous iteration" fields of animation effects, so that we can actually detect phase changes. This means we stop thinking animations always just started, something that caused each animation to send 60 animationstart events every second (to the wrong target!)
> LibWeb: Stop spamming animation events on the wrong event target

- Userland/Libraries/LibJS/Runtime/ExecutionContext.cpp
- Userland/Libraries/LibJS/Runtime/ExecutionContext.h
...that maintains a list of allocated execution contexts so malloc() does not have to be called every time we need to get a new one.
20% improvement in Octane/typescript.js
16% improvement in Kraken/imaging-darkroom.js
```
Kraken      ai-astar.js                              1.006  1.800 ± 1.790 … 1.810     1.790 ± 1.790 … 1.790
Kraken      audio-beat-detection.js                  1      1.410 ± 1.410 … 1.410     1.410 ± 1.410 … 1.410
Kraken      audio-dft.js                             1.018  1.155 ± 1.150 … 1.160     1.135 ± 1.130 … 1.140
Kraken      audio-fft.js …
```
> LibJS: Add fast ExecutionContext allocator

- Kernel/Bus/PCI/IDs.h
- Kernel/Bus/VirtIO/Transport/PCIe/Detect.cpp
- Kernel/Bus/VirtIO/Transport/PCIe/TransportLink.cpp
- Kernel/CMakeLists.txt
- Kernel/Devices/HID/VirtIO/EvDevDefinitions.h
- Kernel/Devices/HID/VirtIO/Input.cpp
- Kernel/Devices/HID/VirtIO/Input.h
- Meta/check-style.py
- Meta/lint-clang-format.sh
- Meta/run.py
This PR makes keyboard and (absolute) mouse input work on RISC-V!
The QEMU virtio keyboard, mouse and tablet (absolute mouse) work on both x86-64 and riscv64.
I only tested the keyboard driver with my german keyboard (+german layout), but that should hopefully not be an issue. I would still appreciate it if someone could test this with a different layout.
We could also consider changing run.py to use the virtio input devices on x86-64 in the future, since those might be a better option than using PS/2 when running in QEMU.
The new virtio driver is not in the Bus/VirtIO directory, as #24152 will move all other virtio drivers out of there.
> Kernel/HID: Add support for virtio input devices (+ use them for RISC-V in run.py)

- Kernel/Arch/riscv64/Interrupts.cpp
This means that userspace breakpoint traps no longer panic the kernel. This also causes us to no longer panic on failed assertions in userspace when using gcc, as gcc compiles __builtin_trap to breakpoint instructions on RISC-V.
> Kernel/riscv64: Handle breakpoint traps

- Tests/LibWeb/Text/expected/css/sending-animationcancel-event-crash.txt
- Tests/LibWeb/Text/input/css/sending-animationcancel-event-crash.html
- Userland/Libraries/LibWeb/Animations/Animation.cpp
- Userland/Libraries/LibWeb/Animations/Animation.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
The if statement in the dispatch implies we are in the idle state, so of course the active time will always be undefined. If this was cancelled via a call to cancel(), we can save the time at that point. Otherwise, just send 0.
I'm not sure if the FIXME is totally necessary. It does seem wrong to just send zero, but this matches what WebKit seems to do, so at least it can't be _that_ wrong. Calculating the time if `cancel()` wasn't called is quite a bit harder, as deriving the current state happens when we invoke `phase()`. At that point, the phase is already idle; there's no telling when the switch from the previous state happened.
Fixes #24424
> LibWeb: Save time for animationcancel event before transitioning to idle

- Tests/LibGfx/TestImageWriter.cpp
...and use a different color name until a (relatively harmless) bug writing fully-opaque frames to an animation that also has transparent frames is fixed. (I've had a local fix for that for a while, but I'm waiting for #24397 to land.)
> Tests/LibGfx: Don't use a color name as an ARGB32 value

- Tests/LibGfx/TestImageWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp
> LibGfx/GIF: Correctly write frames with a non-null position

- Userland/Libraries/LibWasm/Parser/Parser.cpp
The previous version of the function read the tag as a u8. However, as per the spec, the tag of the data section should be a u32, LEB128 encoded. This fixes at least one spectest (binary-leb128_4).
https://webassembly.github.io/spec/core/binary/modules.html#data-section
> LibWasm: Properly read data section tags

- Tests/LibWeb/Ref/reference/scrolled-text-with-clipped-corners-ref.html
- Tests/LibWeb/Ref/scrolled-text-with-clipped-corners.html
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Fixes bug when corner clip mask moves along with the scrolled text.
Before:
After:
> LibWeb: Apply corner clip before scroll offset for PaintableWithLines

- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Tests/classes/class-inheritance.js
Happened to stumble across this when trying to make another fix (for strict mode).
It seems that we are now spec compliant enough to be able to remove this code block :^)
Diff Tests:
+2 ✅    -2 ❌
> LibJS: Remove non-spec compliant code from internal_construct

- Tests/LibWeb/Ref/paintablewithlines-corner-clip-in-scroll-container.html
- Tests/LibWeb/Ref/reference/paintablewithlines-corner-clip-in-scroll-container-ref.html
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
> LibWeb: Fix clip box calculation in PaintableWithLines

- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
- Userland/Libraries/LibCompress/Huffman.h
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPSharedLossless.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
This implements some of the basic webp compression: Huffman coding.
(The other parts of the basics are backreferences, and color cache
entries; and after that there are the four transforms -- predictor,
subtract green, color indexing, color.)
How much huffman coding helps depends on the input's entropy.
Constant-color channels are now encoded in constant space, but
otherwise a huffman code always needs at least one bit per symbol.
This means just huffman coding can at the very best reduce output
size to 1/8th of input size.
For three test input files:
sunset-retro.png (876K): 2.25M -> 2.02M
(helps fairly little; from 2.6x as big as the png input to 2.36x)
giphy.gif (184k): 11M -> 4.9M
(pretty decent, from 61x as big as the gif input to 27x as big)
7z7c.gif (11K): 775K -> 118K
(almost as …
> LibGfx/WebPWriter: Use huffman compression

- Userland/Libraries/LibCompress/Huffman.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
Deflate and WebP can store at most 15 bits per symbol, meaning their
huffman trees can be at most 15 levels deep.
During construction, when we hit this level, we used to try again
with an ever lower frequency cap per symbol. This had the effect
of giving the symbols with the highest frequency lower frequencies
first, causing the most-frequent symbols to be merged. For example,
maybe the most-frequent symbol had 1 bit, and the 2nd-frequent
two bits (and everything else at least 3). With the cap, the two
most frequent symbols might both have 2 symbols, freeing up bits
for the lower levels of the tree.
This has the effect of making the most-frequent symbols longer at
first, which isn't great for file size.
Instead of using a frequency cap, ignore ever more of the low
bits of the frequency. …
> LibCompress: When limiting huffman tree depth, sacrifice bottom of tree

- Userland/Libraries/LibGfx/AntiAliasingPainter.h
- Userland/Libraries/LibWeb/Painting/BorderRadiiData.h
- Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.h
- Userland/Libraries/LibWeb/Painting/CommandList.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
...instead of allocating separate BorderRadiusCornerClipper for each executed sample/blit commands pair.
With this change a vector of BorderRadiusCornerClipper has far fewer items. For example on twitter profile page its size goes down from ~3000 to ~3 items.
> LibWeb: Use stack to represent blit/sample corners commands state

- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
This removes a lot of the error handling boilerplate, and is more consistent with the rest of the codebase. Hopefully I'm not just being an idiot with this PR if there was a reason TRY isn't supposed to be used in these cases...
> LibWasm: Use TRY macro when possible

- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.h
- Userland/Libraries/LibWeb/Painting/CommandList.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.h
Now after making a change in a painting command we could avoid updating method's parameters list across 3 classes.
> LibWeb: Pass whole command by reference into painting command executor

- Tests/LibWeb/Text/input/HTML/StructuredClone-object-primitives.html
This initializes 'arrayBuffer' to an UInt8Array so that we can manipulate the contents of 'arrayBuffer'. The test verifies that the internal buffer is an ArrayBuffer.
Also:
* Correct comparison in test so that we compare arrayBuffer to arrayClone, not to itself.
* Remove FIXME, this outputs [object ArrayBuffer] in Firefox and Chrome too.
> Tests/LibWeb: Initialize 'arrayBuffer' to an UInt8Array

- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
Implemented the rest of the element parsing variants. Previously, the implementation had 7 cases for each element type, and had three of the seven finished. I changed the implementation to use the semantic meaning of each part of the tag. Is that okay implementation-wise? It definitely cuts down on the amount of code, but I'm not sure if this approach was ruled out for a different reason. The control flow is uh... well... I can try to find ways to simplify it if needed.
This PR isn't ready to be merged yet because I still need to delete the old code (for the 7 cases thing). I wanted to wait for the okay for this implementation before I did that. Anyway, some more spec tests pass now, and a lot more spec tests get past the parsing stage (but fail in the validator)!
> LibWasm: Implement parsing all element variants

- Tests/LibWeb/Text/expected/HTML/click-label-to-focus-text-input.txt
- Tests/LibWeb/Text/input/HTML/click-label-to-focus-text-input.html
- Userland/Libraries/LibWeb/Layout/Label.cpp
Previously, we assumed that all label control paintables were of type  `LabelablePaintable`. This caused a crash when clicking on a label with a text input control.
I encountered this crash on reddit and gmail when interacting with text inputs.
Fixes #24056
> LibWeb: Don't crash on clicking a label with an associated text input

- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Tests/LibWeb/Text/expected/css/getComputedStyle-relative-property-values.txt
- Tests/LibWeb/Text/input/css/getComputedStyle-relative-property-values.html
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
The resolved value is now correctly calculated for all margin, padding and width properties of a `ResolvedCSSStyleDeclaration`.
This means the correct values are returned when these properties are accessed from a `getComputedStyle()` call.
This allows the following WPT tests to pass:
* https://wpt.live/css/cssom/computed-style-001.html
* https://wpt.live/css/cssom/computed-style-002.html
* https://wpt.live/css/cssom/computed-style-003.html
* https://wpt.live/css/cssom/computed-style-004.html
* https://wpt.live/css/cssom/getComputedStyle-layout-dependent-removed-ib-sibling.html
* https://wpt.live/css/cssom/getComputedStyle-layout-dependent-replaced-into-ib-split.html
> LibWeb: Improve resolution of `ResolvedCSSStyleDeclaration` properties

- Meta/Lagom/CMakeLists.txt
Fixes compilation failure on musl due to missing `backtrace` symbols
Tested with glibc and noticed no regression
> Meta: Use ```find_package``` for configuring backtraces

- AK/CheckedFormatString.h
- Userland/Utilities/sql.cpp
Format string checking was disabled in Clang-based builds due to a compiler bug: https://github.com/llvm/llvm-project/issues/51182. Now that the requirement has been raised to Clang 17, that is no longer necessary.
This has been tested to work correctly with Apple Clang 15.0.0 (which is the *least modern* supported compiler), as well as CLion 2024.1's bundled Clangd.
> AK: Enable format string checking in Clang builds

- Userland/Libraries/LibWasm/Parser/Parser.cpp
Turns out, we don't need a new i33 reading algorithm (see #24462). The actual fix was just fixing a typo... using `new_stream` instead of `stream`.
> LibWasm: Properly read blocktypes

- Ladybird/Qt/WebContentView.cpp
This fixes a regression introduced by GH-23855 in [1], and re-applies a previous change I made [2].
[1] https://github.com/SerenityOS/serenity/commit/dfc7534
[2] https://github.com/SerenityOS/serenity/commit/b7bd3fd
> Ladybird/Qt: Calculate the 'physical pixels' for screens

- Tests/LibWeb/WPT/metadata.txt
- Tests/LibWeb/WPT/run.sh
Previously, it was not possible to run `wpt` locally with a python version >= 3.12.
Our `metadata.txt` file now reflects the results we currently get, this should make CI output look a bit nicer.
> WPT: Update to latest master and update test expectations

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
Previously, the WPT client didn't quite understand the error responses we were sending. With the `wpt` version we were using prior to #24487 this led to a CRASH being logged rather than an ERROR. When using the latest version, this change makes no difference to the kind of result that is logged, but it does make the logged error messages easier to understand, so I think the change is still worthwhile.
Relevant WPT code:
https://github.com/web-platform-tests/wpt/blob/5930e386a5e1e59456dc810c9b21adf18bc1b6fe/tools/webdriver/webdriver/error.py#L189-L218
> LibWeb/WebDriver: Ensure error responses are serialized correctly

- Tests/LibGfx/TestImageWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPSharedLossless.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriter.h
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
- Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.h
- Userland/Utilities/image.cpp
If an image has 256 or fewer colors, WebP/Lossless allows storing
the colors in a helper image, and then storing just indexes into that
helper image in the main image's green channel, while setting
r, b, and a of the main image to 0.
Since constant-color channels need to space to store in WebP,
this reduces storage needed to 1/4th (if alpha is used) or 1/3rd
(if alpha is constant across the image).
If an image has <= 16 colors, WebP lossless files pack multiple
color table indexes into a single pixel's green channel, further
reducing file size.
GIFs can store at most 256 colors per frame, so animated gifs
often have 256 or fewer colors, making this effective when
transcoding gifs.
This adds support for writing that color index transform.
It also fixes a general encoding bug that the tests …
> LibGfx/WebP+image: Add support for writing color index transforms, and fix an encoding bug

- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.h
The spec allows the maximum size of the linear memory to be 2^16. However, we previously only allowed 2^16-1, which caused a spec compliance issue.
See the [relevant spec entry](https://webassembly.github.io/spec/core/valid/types.html#memory-types). This makes one more test pass.
> LibWasm: Fix memory limits validator discrepancy

- Userland/Libraries/LibJS/Bytecode/BasicBlock.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Bytecode/ScopedOperand.cpp
- Userland/Libraries/LibJS/Tests/copy-this-to-local.js
Three main things here:
- The cached `this` register is now pre-populated when entering a bytecode executable.
- We no longer emit `ResolveThisBinding` at all when we know the pre-populated cache is non-empty (this is true for any function that doesn't require a unique function environment)
- When we do have `ResolveThisBinding`, it no longer has a `dst`, but instead always just populates the cached `this` register.
Net result: fewer instructions! Same result! Go faster! Whee! (And also fixes a bug, included a test for that!)
Benchmark results:
```
Kraken      ai-astar.js …
```
> LibJS/Bytecode: Better codegen for `this`

- Userland/Libraries/LibWeb/HTML/Scripting/ImportMap.cpp
Follow up to GH-23954, identified while working on SRI for import maps.
> LibWeb: Set import map scopes when parsing

- Ladybird/Qt/FindInPageWidget.cpp
The non-flat version of these buttons look a bit out-of-place.
Before:
After:
> Ladybird/Qt: Flatten the buttons in the find-in-page panel
