SerenityOS/serenity

Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
The benefit of the color indexing transform is to have only one
varying channel after it (the green channel, which after the
transform serves as index into the color table).
If there is only one varying channel before the transform, it's
not beneficial. (...except if there are <= 16 colors, then the
pixel bundling presumably still works.)
---
Small FIXME-fix after #24483.
=> LibGfx/WebPWriter: Do not write color index if only one channel varies

Meta/generate-libwasm-spec-test.py, Tests/LibWasm/test-wasm.cpp, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h, Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp, Userland/Libraries/LibWeb/WebAssembly/Table.cpp
Implements `table.get`, `table.set`, `elem.drop`, `table.size`, and `table.grow`. Also fixes a few issues when generating ref-related spectests. Also changes the `TableInstance` type to use `Vector<Reference>` instead of `Vector<Optional<Reference>>`, because the ability to be null is already encoded in the `Reference` type.
This makes a few hundred more spectests pass!
=> LibWasm: Improve table support

Kernel/CMakeLists.txt, Kernel/FileSystem/CustodyBase.cpp, Kernel/FileSystem/CustodyBase.h, Kernel/FileSystem/Inode.cpp, Kernel/FileSystem/Inode.h, Kernel/FileSystem/VirtualFileSystem.cpp, Kernel/FileSystem/VirtualFileSystem.h, Kernel/Forward.h, Kernel/Syscalls/chdir.cpp, Kernel/Syscalls/chmod.cpp, Kernel/Syscalls/chown.cpp, Kernel/Syscalls/faccessat.cpp, Kernel/Syscalls/link.cpp, Kernel/Syscalls/mkdir.cpp, Kernel/Syscalls/mknod.cpp, Kernel/Syscalls/open.cpp, Kernel/Syscalls/rename.cpp, Kernel/Syscalls/stat.cpp, Kernel/Syscalls/unlink.cpp, Kernel/Syscalls/utimensat.cpp, Kernel/Tasks/Coredump.cpp, Kernel/Tasks/Process.cpp, Kernel/Tasks/Process.h
To be able to do this, we add a new class called CustodyBase, which can be resolved on-demand internally in the VirtualFileSystem resolving path code.
When being resolved, CustodyBase will return a known custody if it was constructed with such, if that's not the case it will provide the root custody if the original path is absolute.
Lastly, if that's not the case as well, it will resolve the given dirfd to provide a Custody object.
Fixes #24328.
=> Kernel: Ignore dirfd if absolute path is given in VFS-related syscalls

Userland/Libraries/LibWasm/Parser/Parser.cpp, Userland/Libraries/LibWasm/Types.h
Sections in WebAssembly give their length in bytes after they're declared. This commit makes sure that length is upheld.
=> LibWasm: Check section lengths when parsing

Kernel/Devices/FUSEDevice.cpp, Kernel/Devices/FUSEDevice.h, Kernel/FileSystem/FUSE/Definitions.h, Kernel/FileSystem/FUSE/FUSEConnection.h
Previously, it was assumed that only a single request can be pending for a FUSE instance, but we actually need to be able to send more requests even if there may be older requests pending response since requests can be blocked on other requests. In short, this means that recursively trying to list the mountpoint with the `passthrough` example from libfuse now works properly.
This also does some other cleanups, including clarifying the license of `Definitions.h`, doing a better job at filling out the request header, and improving debug output.
=> Kernel/FUSE: Allow buffering multiple requests

Tests/LibWeb/Text/expected/WebAnimations/misc/animate-with-mixed-percentages.txt, Tests/LibWeb/Text/input/WebAnimations/misc/animate-with-mixed-percentages.html, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This is much simpler than the previous solution I came up with for this, which was to introduce a new `StyleValue` type that then somehow had to propagate through all of the `CalculatedOr`/`PercentageOr` stuff. 
Fixes #23543
=> LibWeb: Support interpolation of mixed percentage dimension units

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Bytecode/Generator.cpp, Userland/Libraries/LibJS/Bytecode/Generator.h, Userland/Libraries/LibJS/Bytecode/ScopedOperand.h
Basically:
- Constant folding of binary expressions.
- Fewer avoidable `Mov` instructions.
- Rewrite `Jump`-to-`End` or `Jump`-to-`Return` as just `End` or `Return`.
- Fix a dumb O(n^2) issue in constant deduplication.
Benchmarks move in the right direction:
```
Kraken      ai-astar.js                              0.995  2.145 ± 2.120 … 2.170     2.155 ± 2.130 … 2.180
Kraken      audio-beat-detection.js                  1.018  1.440 ± 1.410 … 1.470     1.415 ± 1.410 … 1.420
Kraken      audio-dft.js                             1.009  1.150 ± 1.140 … 1.160     1.140 ± 1.140 … …
```
=> LibJS/Bytecode: First random optimization pack for June

Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Before, it was possible to crash the VM during instantiation when an active data segment requested to put data in memory at an invalid offset.
=> LibWasm: Properly check active data segment offset in instantiation

Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Offset is now checked using saturating addition to avoid overflow. This prevents a crash in the VM during instantiation.
=> LibWasm: Properly check table bounds in element instantiation

Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Prevents overflow when checking that `memory.copy` addresses are valid. This prevents a potential crash in the VM.
=> LibWasm: Properly check `memory.copy` addresses

Userland/Libraries/LibSyntax/Highlighter.cpp, Userland/Libraries/LibSyntax/Language.cpp
This was the only stuff that made it look like LibSyntax depends on LibGUI, when it really doesn't.
=> LibSyntax: Remove minor unnecessary use of LibGUI

Ladybird/AppKit/UI/Event.h, Ladybird/AppKit/UI/Event.mm, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/Qt/WebContentView.cpp, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Layout/Label.cpp, Userland/Libraries/LibWeb/Layout/RadioButton.cpp, Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/EventHandler.h, Userland/Libraries/LibWeb/Page/InputEvent.cpp, Userland/Libraries/LibWeb/Page/InputEvent.h, Userland/Libraries/LibWeb/Painting/AudioPaintable.cpp, Userland/Libraries/LibWeb/Painting/ButtonPaintable.cpp, Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp, Userland/Libraries/LibWeb/Painting/LabelablePaintable.cpp, Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp, Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.cpp, Userland/Libraries/LibWeb/Painting/VideoPaintable.cpp, Userland/Libraries/LibWeb/UIEvents/MouseButton.h, Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp, Userland/Libraries/LibWebView/OutOfProcessWebView.cpp
This was the only thing LibWeb needed from LibGUI, and we can just duplicate the enum in LibWeb and get rid of a bogus dependency.
=> LibWeb: Add Web::UIEvents::MouseButton enum, drop dependency on LibGUI

Meta/gn/build/BUILD.gn, Meta/gn/build/toolchain/BUILD.gn, Meta/gn/secondary/Ladybird/WebContent/BUILD.gn
Without the last commit, loading xkcd.com in the GN build resulted in:
It's not clear why the Qt event loop is needed even when we use RequestServer for networking. But the same issue is reproducible in the CMake build if the Qt event loop is not installed. In any case, we need to define the `HAVE_QT` flag for `--enable-qt-networking` to work (we currently crash).
=> Meta: Update GN CC flags to match CMake, and fix WebContent's event loop in the GN build

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
Fixes `animation` asserting when reading a webp input.
(The other order of operations is still covered by TestImageWriter.cpp.)
=> LibGfx/WebPLoader: Survive calling loop_count() before other accessors

Userland/Libraries/LibWasm/Parser/Parser.cpp
The extension bit for the memory index present in memargs is at position 6, but we previously checked position 5, which caused a few spec issues.
=> LibWasm: Fix memarg multi-memory reading

Kernel/Memory/Region.cpp
Removes a VERIFY() that is already checked earlier in the function
=> Kernel: Remove redundant VERIFY()

Userland/Games/Chess/CMakeLists.txt, Userland/Games/Chess/Chess.gml, Userland/Games/Chess/ChessWidget.cpp, Userland/Games/Chess/ChessWidget.h, Userland/Games/Chess/NewGameDialog.cpp, Userland/Games/Chess/NewGameDialog.h, Userland/Games/Chess/NewGameWidget.gml, Userland/Games/Chess/NewGameWidget.h, Userland/Games/Chess/main.cpp
This PR adds the ability to play with time controls. All rules related to this have been implementing, including losing on time and getting time bonuses after moves. The settings for this functionality were placed in a `NewGameDialog` widget instead of the `GameSettings` application due to the fact that the user should only be able to change the time controls when making a new game, which is very hard to enforce if going through `GameSettings`.
Edit: here is a screenshot:
=> Chess: Add time controls

Meta/Lagom/CMakeLists.txt, Userland/Libraries/LibCore/Environment.cpp, Userland/Libraries/LibCore/System.h, Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
NetBSD and FreeBSD get upset when we don't set the fd to an invalid
value when using a non-shared mapping.
FreeBSD and NetBSD don't have secure_getenv(3), same as macOS.
FreeBSD 13 and lower also don't allow setting environ pointers to null.
Ref: #23375
cc @0-wiz-0
cc @clausecker
=> LibJS+LibCore: Some BSD Compatibility updates

Tests/LibWeb/TestConfig.ini
Ref https://github.com/LadybirdWebBrowser/ladybird/issues/19
---
`git cherry-pick -x 41c9cb032f56a306bdc3098a2a0d203acb0dd0ff` after
git remote add ladybird https://github.com/LadybirdWebBrowser/ladybird.git
git fetch ladybird
Currently red on every CI / Lagom (macOS, macos-14, NO_FUZZ) run.
=> Test: Skip flakey Text/input/WebAnimations/misc/DocumentTimeline test

Kernel/Memory/AnonymousVMObject.cpp, Kernel/Memory/InodeVMObject.cpp, Kernel/Memory/SharedFramebufferVMObject.cpp, Kernel/Memory/VMObject.cpp, Kernel/Memory/VMObject.h
In the VMObject code there are multiple examples of loops over the VMObject's regions (using for_each_region()) that call remap() on each region.
To clean up usage of this pattern, this patch adds a method in VMObject that does this remapping loop. VMObject code that needs to remap its regions call the new method.
=> Kernel: Add method to clean up remapping region loops

Tests/LibWeb/Text/expected/Streams/ReadableStream-from-asyncIterator.txt, Tests/LibWeb/Text/input/Streams/ReadableStream-from-asyncIterator.html, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp, Userland/Libraries/LibWeb/Streams/AbstractOperations.h, Userland/Libraries/LibWeb/Streams/ReadableStream.cpp, Userland/Libraries/LibWeb/Streams/ReadableStream.h, Userland/Libraries/LibWeb/Streams/ReadableStream.idl
Adds the static method ReadableStream.from() which can be used to wrap iterable and async iterable objects as readable streams.
Commits cherry picked from: https://github.com/LadybirdWebBrowser/ladybird/pull/108
=> LibWeb: Implement static method ReadableStream.from(asyncIterable)

.github/workflows/libjs-test262.yml
The new Wasm test generation script needs this.
=> Meta: Use Python>=3.10 in the test262 action

Kernel/Memory/InodeVMObject.cpp
There are 2 methods in InodeVMObject that are almost identical. This commit makes them both use the same code path.
=> Kernel: Clean up duplicated code

Userland/Libraries/LibGfx/AntiAliasingPainter.h, Userland/Libraries/LibGfx/CornerRadius.h, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/Path.h, Userland/Libraries/LibGfx/Quad.h, Userland/Libraries/LibWeb/Painting/AffineCommandExecutorCPU.cpp, Userland/Libraries/LibWeb/Painting/AffineCommandExecutorCPU.h, Userland/Libraries/LibWeb/Painting/BorderPainting.cpp, Userland/Libraries/LibWeb/Painting/BorderPainting.h, Userland/Libraries/LibWeb/Painting/BorderRadiiData.cpp, Userland/Libraries/LibWeb/Painting/BorderRadiiData.h, Userland/Libraries/LibWeb/Painting/Command.h, Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp, Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp, Userland/Libraries/LibWeb/Painting/RecordingPainter.h
This PR continues work to get the `AffineCommandExecutorCPU` to a usable state...  Implementing support for stacking context opacity and clip rects. Clip rects are quite tricky to handle as unlike the regular painter they're actually clip convex quadrilaterals. See commits for details.
**Demo:**
https://github.com/SerenityOS/serenity/assets/11597044/1998faa9-e6ba-4916-a55f-524c828432cd
The HTML is:
```html
<div id="foo" style="background-color: green; transform: scale(4);">
<div id="box20" class="box" style="overflow: hidden; opacity: 0.4;">
<div style="background-color: red;">
</div>
</div>
</div>
```
=> LibWeb: Support clip rects and opacity in the `AffineCommandExecutorCPU`

Tests/LibWeb/Text/expected/Streams/ReadableStream-can-cancel.txt, Tests/LibWeb/Text/expected/Streams/TransformStream-cancelled-by-readable-side.txt, Tests/LibWeb/Text/expected/Streams/TransformStream-cancelled-by-writable-side.txt, Tests/LibWeb/Text/input/Streams/ReadableStream-can-cancel.html, Tests/LibWeb/Text/input/Streams/TransformStream-cancelled-by-readable-side.html, Tests/LibWeb/Text/input/Streams/TransformStream-cancelled-by-writable-side.html, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp, Userland/Libraries/LibWeb/Streams/AbstractOperations.h, Userland/Libraries/LibWeb/Streams/TransformStreamDefaultController.cpp, Userland/Libraries/LibWeb/Streams/TransformStreamDefaultController.h, Userland/Libraries/LibWeb/Streams/Transformer.cpp, Userland/Libraries/LibWeb/Streams/Transformer.h
This implements the cancel callback for TransformStream. The cancel callback is raised when the readable side of the TransformStream is cancelled, or the writable side is aborted.
Also added a test to prove a ReadableStream can be cancelled, noticed this behavior lacked a test.
Commits are cherry-picked from: https://github.com/LadybirdBrowser/ladybird/pull/95
=> LibWeb: Implement and wire up TransformStream's cancel callback

Userland/Libraries/LibGfx/Font/ScaledFont.cpp, Userland/Libraries/LibGfx/Font/ScaledFont.h, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/Path.h, Userland/Libraries/LibWeb/Painting/AffineCommandExecutorCPU.cpp
**Demo:**
https://github.com/SerenityOS/serenity/assets/11597044/83662807-688b-4ce7-bc89-5ec0910ebd7c
=> LibWeb: Add support for text in the `AffineCommandExecutorCPU`

Userland/Applications/CrashReporter/main.cpp
This prevents a crash that could happen if crash reporter was closed while generating a crash report.
Fixes #23748
=> CrashReporter: Don't update window progress if window has been closed

AK/AsyncStream.h, AK/AsyncStreamBuffer.h, AK/AsyncStreamHelpers.h, AK/AsyncStreamTransform.h, AK/Badge.h, AK/Coroutine.h, AK/Forward.h, AK/Generator.h, AK/GenericLexer.cpp, AK/StdLibExtras.h, Documentation/AsynchronousDesign.md, Meta/CMake/common_compile_options.cmake, Meta/Lagom/CMakeLists.txt, Tests/AK/CMakeLists.txt, Tests/AK/TestCoroutine.cpp, Tests/AK/TestGeneratorAK.cpp, Tests/LibHTTP/CMakeLists.txt, Tests/LibHTTP/TestHttp11Connection.cpp, Tests/LibTest/CMakeLists.txt, Tests/LibTest/TestAsyncTestStreams.cpp, Userland/Libraries/LibCore/EventLoop.h, Userland/Libraries/LibHTTP/CMakeLists.txt, Userland/Libraries/LibHTTP/Http11Connection.cpp, Userland/Libraries/LibHTTP/Http11Connection.h, Userland/Libraries/LibTest/AsyncTestCase.h, Userland/Libraries/LibTest/AsyncTestStreams.cpp, Userland/Libraries/LibTest/AsyncTestStreams.h, Userland/Libraries/LibTest/CMakeLists.txt
You thought you mastered idiosyncrasies of AK::Stream? This PR gets you covered by adding a similar but completely unrelated way of doing datastreams.
You thought you figured out how to write event-driven asynchronous code in Serenity? This PR gets you covered by adding a similar but subtly different way for dealing with asynchronousness.
You thought you knew how and when lifetimes are ended? This PR gets you covered by complicating things so much you would start to question your C++ skills.
You thought you knew how to read backtraces in GDB? This PR gets you covered by converting backtraces into an unreadable mess ~~going both in call-stack and reverse call-stack directions while~~ interleaving actual calls with visual clutter.
You thought you knew what I would upstream first? This PR …
=> AK+LibHTTP+LibTest: Introduce more bugs in asynchronous code

Toolchain/BuildMold.sh
[Mold issue 1178](https://github.com/rui314/mold/issues/1178) is now fixed, so Serenity is able to build fine using Mold
=> Build: Update mold version to fix build problems

Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
Use AK helpers instead of reimplementing them.
No behavior change. Slightly nicer and easier to read code.
=> LibGfx/WebPWriter: Use AK's count_required_bits(), align_up_to()

Meta/Lagom/BuildFuzzers.sh
By unsetting `CXXFLAGS` in order to build Lagom code generators without
instrumentation, we were also removing `-stdlib=libc++`, so Clang ended
up using the runner image's libstdc++ 9 headers. These are too old, and
don't contain `<coroutine>`, leading to a build failure.
Fixes #24578
=> Fuzzers: Use libc++ on OSS-Fuzz for Lagom code generators

Userland/Applications/SystemMonitor/main.cpp
Revives #22745.
I changed things slightly - when pausing the window title will include the "Paused" word and when selecting a refresh frequency again, it will disappear :)
cc @tcl3 as this is your patches and I'd want to see if you think we should change them somehow :)
=> SystemMonitor: Add pause and refresh actions

Meta/gn/build/BUILD.gn
8263e0a6199 added `-Wno-coroutine-missing-unhandled-exception` to the cmake build, and the coroutine code does not build without it.
Unbreaks building e.g. `js` with GN.
=> Meta: Add a warning suppression used in the cmake build to the gn build

AK/Types.h, Base/usr/share/man/man1/sizefmt.md, Userland/Utilities/sizefmt.cpp
This utility takes a human-readable size and converts it into a raw integer that can be used on commandline utilities.
I want to see if this utility makes sense before I write a manual page with examples.
This could be used for example on the utility from this PR #24570, but probably on other utilities in the system (like `truncate`).
=> Utilities: Introduce the sizefmt utility

Userland/Libraries/LibJS/Heap/Heap.cpp
We pass all fields of `buf` to `add_possible_value()`, and at least on Linux `setjmp()` does not initialize all fields.
Fixes #24560.
=> LibJS: Initialize fields of on-stack `buf` structure

Kernel/Memory/MMIOVMObject.cpp, Kernel/Memory/MMIOVMObject.h, Kernel/Memory/Region.cpp, Kernel/Memory/VMObject.h
This is required for example when write combine is enabled on a region after the initial mapping.
=> Kernel: Support re-mapping MMIOVMObject-backed regions

Userland/Libraries/LibIPC/Connection.cpp, Userland/Libraries/LibIPC/Connection.h, Userland/Libraries/LibIPC/Message.cpp, Userland/Libraries/LibIPC/Message.h
The expectation with these messages is that no other code is allowed to run while we're waiting for the response to arrive. Not meeting this requirement did not degrade any (observable) functionality, however.
(see https://github.com/LadybirdBrowser/ladybird/pull/213)
=> LibIPC: Allow sync messages to completely block the event loop

Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/Loader.cpp, Userland/Libraries/LibAudio/LoaderError.h, Userland/Libraries/LibAudio/MP3Loader.cpp, Userland/Libraries/LibAudio/QOALoader.cpp, Userland/Libraries/LibAudio/WavLoader.cpp
This addresses part of #22447 by replacing a `DeprecatedFlyString` with a `FlyString` in LibAudio's `LoaderError`.
=> LibAudio: Replace DeprecatedFlyString with FlyString

Kernel/Devices/Storage/StorageManagement.cpp
This is helps bringing up bare metal devices without having to use the serial console.
=> Kernel/Storage: Dump storage devices to the framebuffer console as well

Userland/Libraries/LibProtocol/RequestClient.cpp, Userland/Libraries/LibProtocol/RequestClient.h, Userland/Libraries/LibWebSocket/ConnectionInfo.h, Userland/Libraries/LibWebSocket/WebSocket.cpp, Userland/Services/RequestServer/ConnectionFromClient.cpp, Userland/Services/RequestServer/ConnectionFromClient.h, Userland/Services/RequestServer/RequestServer.ipc
(cherry picked from commit 0d22e0703f4d668fab78b6e4960dfdc2b607369d)
---
Cherry-picks the commit from https://github.com/LadybirdBrowser/ladybird/pull/247
=> Cherry-pick "LibWebSocket: Use HTTP::HeaderMap in WebSocket code"

Userland/Applications/PixelPaint/ImageMasking.cpp
This change fixes an issue where pixelpaint was crashing when trying to refine an editing mask with the "Color Masking" feature because we where accessing pixel coordinates that where beyond the boundaries. Furthermore a change was made to make the color masking hue selection work again with mouse clicks directly on the color wheel.
=> PixelPaint: Fixed some Color Masking issues

Userland/Libraries/LibWeb/DOM/Document.cpp
If the Document's navigable has been destroyed since we started this timer, or it's no longer the active document of its navigable, we shouldn't navigate to it.
(cherry picked from commit 7b67fa706fd2dabfda3c72a752ac70d8c95bb060; amended commit message to say "LibWeb:" instead of "DOM:")
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/69
=> Cherry-pick "LibWeb: Check for navigable destruction in declarative refresh timer"

Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp
Previously, navigating to or from `about:newtab` caused a crash due to inadvertent null dereferences when checking whether a request or response to a request should be blocked as mixed content.
(cherry picked from commit 572ebe00eacd5aaeecc17207c75c6bf2327a3897)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/161
=> Cherry-pick "LibWeb: Avoid null dereference when performing mixed content checks"

Tests/LibWeb/Text/expected/css/cssFloat-property.txt, Tests/LibWeb/Text/expected/css/keyframes-css-rules.txt, Tests/LibWeb/Text/expected/css/style-declaration-parent-rule.txt, Tests/LibWeb/Text/input/css/cssFloat-property.html, Tests/LibWeb/Text/input/css/keyframes-css-rules.html, Tests/LibWeb/Text/input/css/style-declaration-parent-rule.html, Userland/Libraries/LibWeb/CSS/CSSKeyframeRule.cpp, Userland/Libraries/LibWeb/CSS/CSSKeyframeRule.h, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.cpp, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.h, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.idl, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.idl, Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Cherry-picks the commits from https://github.com/LadybirdBrowser/ladybird/pull/168
=> Cherry-pick "LibWeb: A handful of CSSOM web compatibility fixes"

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLImageElement.h, Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Implements enough of HTMLImageElement::decode for it to not break websites and actually load an image :)
(cherry picked from commit 862fc91b2cf9bee9b7f180cdf930c6c99b5dd053)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/66
=> Cherry-pick "LibWeb: Implement HTMLImageElement::decode with a few FIXMEs"

Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/input/HTML/form-image-submission.html
This makes the `form-image-submission.html` test pass more reliably.
(cherry picked from commit 2fed064791d3117e0571453210000d285ee9359c)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/104
=> Cherry-pick "Tests/LibWeb: Wait until document fully loaded before simulating click"

Tests/LibWebView/TestWebViewURL.cpp, Userland/Libraries/LibWebView/URL.cpp
Allow navigation to data URLs from browser UI.
(cherry picked from commit 6014727c20ad108e8345e89cba8e9eace3c157b3)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/266
=> Cherry-pick "LibWebView: Allow data URLs in sanitize_url"

Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp
Apple Clang doesn't like this, rather than waiting for their version of random-clang-commit-to-call-a-release to catch up with llvm trunk, just work around the issue.
Fixes https://github.com/LadybirdBrowser/ladybird/pull/186.
(cherry picked from commit 8c9d3b30cf62016ffb03e425f1e7e3f2461262bf)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/203
=> Cherry-pick "LibWeb/CSS: Avoid capturing structured binding in generic lambda"

Userland/Libraries/LibWeb/Page/EventHandler.cpp
(cherry picked from commit 8969f2e34af196e935c57257ef7eec8f00b45d33)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/237
=> Cherry-pick "LibWeb: Disallow pasting into non-editable text nodes"

Ladybird/AppKit/UI/LadybirdWebView.mm
Whoopsie!
See next two methods and previous one method to see that this is right. As a manual test, try right-clicking into https://javascript.info/mouse-events-basics
Noticed while looking at mouse handling while trying to test #24613.
=> Ladybird/AppKit: Send correct mouse event on right click

Ladybird/AppKit/UI/LadybirdWebView.mm
My external mouse also has a 4th and 5th button, but the `Web::UIEvents::MouseButton::` abstraction doesn't support that yet, so I'm just early-outing for those.
With this and #24613, middle-clicking does open links in a new tab. (The more natural cmd-left-clicking doesn't work, though.)
=> Ladybird/AppKit: Send mouse event on middle click

Userland/Libraries/LibWeb/HTML/Navigation.cpp
See:
- https://github.com/whatwg/html/pull/10393
(cherry picked from commit 4c5fa102a381c3687e677f9b6b13752c2bcea867)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/246
=> Cherry-pick "LibWeb: Don't set hashChange for classic history navigate events"

Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h, Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl
Adds the showPicker() function for select elements. This doesn't do the check for "being rendered" which is in the spec.
(cherry picked from commit 5098ed6b1f881659dbdab10c74a0e17b362ce7a8)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/153
=> Cherry-pick "LibWeb: Add HTMLSelectElement showPicker()"

Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
No other browser allows opening the select element dropdown with the select.click() function.
This change stops this happening in Ladybird.
(cherry picked from commit 564e546ff0bd78cc7ba770b53377457bf1ef88d6)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/154
=> Cherry-pick "LibWeb: Prevent select.click() opening the dropdown"

Userland/Libraries/LibWeb/HTML/CloseWatcher.h, Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Dialog elements now correctly establish a close watcher when shown modally.
This means modal dialogs now correctly close with an escape key press.
(cherry picked from commit d86a6e1bec858a35935ba6839c154ba2482d33e6)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/250
=> Cherry-pick "LibWeb: Implement dialog element's close watcher"

Tests/LibWeb/Ref/css-case-insensitive-html-attributes-selector.html, Tests/LibWeb/Ref/reference/css-case-insensitive-html-attributes-selector-ref.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
(cherry picked from commit 2b30414c1d8641eaf4212db69e40a4381005314c)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/243
=> Cherry-pick "LibWeb: Add attribute list that must always be compared without casing"

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/Document.idl, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/DOM/Element.h, Userland/Libraries/LibWeb/DOM/Element.idl, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/Node.h, Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp, Userland/Libraries/LibWeb/DOM/ShadowRoot.h, Userland/Libraries/LibWeb/DOM/ShadowRoot.idl, Userland/Libraries/LibWeb/HTML/DOMParser.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
Both Element's and ShadowRoot's setHTMLUnsafe, and Document's static parseHTMLUnsafe methods are implemented.
(cherry picked from commit ce8d3d17c4f2fcca8fac0ff4a832c8f50a011fc7)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/282
=> Cherry-pick "LibWeb: Implement unsafe HTML parsing methods"

Meta/shell_include.sh, Toolchain/BuildCMake.sh, Toolchain/BuildQemu.sh
With this, `Toolchain/BuildQemu.sh` makes it past the download on macOS (and then falls over building fairly quickly).
=> Meta+Toolchain: Let BuildQemu.sh use `shasum -a 256` instead of `sha256sum` on macOS

Base/usr/share/man/man1/crash.md, Tests/Kernel/crash.cpp
TODO_RISCV64 is a boring crash, let's crash in fun and interesting ways! There's actually more crashes we should check for, like misaligned stacks and memory accesses, priviledged CSRs, etc., for now only the generic ones are implemented.
Rebase of #22880 
CC @spholz
- Document exactly which crash features are available on which
architectures. There's several interesting crash tests we will want to
add for specific architectures, such as misaligned memory accesses.
- Don't compile the divide by zero crash test on RISC-V, as they simply
don't crash here.
- Rename the test for "x86 User Mode Instruction Prevention" to a more
generic "try to execute a priviledged instruction"; whatever that
specifically entails on any given architecture.
- Rename a bunch of internal variables to more generic …
=>  crash: RISC-V-ification, /usr/Tests/Kernel/crash edition

AK/Span.h, Kernel/FileSystem/Ext2FS/FileSystem.cpp, Kernel/FileSystem/Ext2FS/FileSystem.h, Kernel/FileSystem/Ext2FS/Inode.cpp, Kernel/FileSystem/Ext2FS/Inode.h
... and also do a thorough refactor to be able to accomplish that, because the old implementation was extremely dependent on all blocks being sequential. There's a fairly long explanation of that in the relevant commit message.
This also accidentally fixes various situations where the filesystem would get slightly corrupted, such as when running the second of the following two commands:
```
dd if=/usr/lib/libweb.so.serenity of=foo.bin bs=1M count=50
truncate -s 35M foo.bin
```
Here's a more complete script that I used to test the correctness of this PR:
```
dd status=none if=/usr/lib/libweb.so.serenity of=foo.bin bs=1M count=50
dd status=none if=/usr/lib/libweb.so.serenity of=/tmp/foo.bin bs=1M count=50
sha512sum /tmp/foo.bin | sed 's,/tmp/,,' | sha512sum -c
rm /tmp/*.bin
dd status=none …
```
=> Kernel/Ext2FS: Allocate blocks lazily + support writing holes

AK/FixedStringBuffer.h, AK/Format.cpp, AK/StringUtils.cpp, Kernel/Arch/x86_64/DebugOutput.cpp, Kernel/Library/MiniStdLib.h, Kernel/Library/StdLib.h, Kernel/Prekernel/Assertions.cpp, Kernel/Prekernel/CMakeLists.txt, Kernel/Prekernel/DebugOutput.cpp, Kernel/Prekernel/DebugOutput.h, Kernel/Prekernel/Prekernel.h, Kernel/Prekernel/Random.cpp, Kernel/Prekernel/Random.h, Kernel/Prekernel/Runtime.cpp, Kernel/Prekernel/Runtime.h, Kernel/Prekernel/init.cpp, Kernel/Prekernel/kmalloc.cpp
I realized recently that we could use the `FixedStringBuffer` class to perform string formatting without doing any memory allocations, which suits the use-case of the prekernel stage quite elegantly.
Therefore, I add a way to print debug logs (to serial console currently, and to bochs serial debug as well), and by doing so, we can actually see now debug prints during assertion failed scenarios, which is very nice imho :)
cc @ADKaster @timschumi
=> Prekernel: Make the prekernel stage more elegant and debuggable

Userland/Utilities/wc.cpp
If the user only wants to get the byte count of a set of files, then for each file we can simply seek it to get the byte count instead of iterating over all the bytes.
Revives #21961. The original PR had a bug in which `-c` wouldn't be able to handle standard input stream, but now I added a condition to handle `ESPIPE` error as well.
=> Utilities/wc: Seek the input file(s) if only -c is passed

Meta/build-root-filesystem.sh, Userland/BuggieBox/CMakeLists.txt, Userland/BuggieBox/main.cpp, Userland/Services/SystemServer/main.cpp, Userland/Utilities/CMakeLists.txt, Userland/Utilities/init.cpp
~~The BuggieBox program is now the first program to run in the system, so it will initialize all the basic stuff once so SystemServer doesn't need to worry about this again in its main code.~~
The `init` program is now the first program to run in the system, so it will initialize all the basic stuff once so `SystemServer` doesn't need to worry about this again in its main code.
In case the user requests this, `init` can drop directly to a shell without trying to spawn SystemServer.
To test this on x86-64, run:
```
Meta/serenity.sh run x86_64 GNU "init_args=emergency"
```
This functionality can be useful in many cases:
- If the user needs to perform a command that must not alter a corrupted filesystem state, then this mode is useful as the filesystem should be mounted in read-only mode.
- …
=> Userland: Move base system initialization from SystemServer to separate program, add "drop to shell" feature

AK/Coroutine.h, AK/Platform.h, Tests/AK/TestCoroutine.cpp, Userland/Libraries/LibHTTP/Http11Connection.h, Userland/Libraries/LibTest/AsyncTestCase.h
There are three compiler bugs that influence this decision:
- Clang writing to (validly) destroyed coroutine frame with -O0 and -fsanitize=null,address under some conditions (https://godbolt.org/z/17Efq5Ma5) (AK_COROUTINE_DESTRUCTION_BROKEN);
- GCC being unable to handle statement expressions in coroutines (AK_COROUTINE_STATEMENT_EXPRS_BROKEN);
- GCC being unable to deduce template type parameter for TryAwaiter with nested CO_TRYs (AK_COROUTINE_TYPE_DEDUCTION_BROKEN).
Instead of growing an ifdef soup in AK/Coroutine.h and LibTest/AsyncTestCase.h, define three macros in AK/Platform.h that correspond to these bugs and use them accordingly in the said files.
=> AK+LibTest: Choose definition of CO_TRY and CO_TRY_OR_FAIL more robustly

AK/MemoryStream.h, Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.cpp, Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h, Userland/Libraries/LibCore/Process.h, Userland/Libraries/LibGUI/Event.cpp, Userland/Libraries/LibGUI/Event.h, Userland/Libraries/LibGUI/HeaderView.cpp, Userland/Libraries/LibGUI/HeaderView.h
You guessed it, this fixes compilation with LLVM trunk.
=> Everywhere: Define even more destructors out of line

Meta/run.py
VirtIO was probably broken on Windows versions of QEMU, but this seems to no longer be the case. Enabling VirtIO is currently required for RISC-V mouse and keyboard support.
**Requests for testing:** If you use Windows QEMU (i.e. build SerenityOS with WSL, but have a Windows QEMU installed), please test this commit and make sure it still boots and works fine! I have tested both RISC-V and x86 under QEMU 8.1.0.
=> Meta: Enable VirtIO on Windows QEMU

Userland/Libraries/LibWasm/WASI/Wasi.cpp
Doing so results in incorrect values being created, ultimately leading to traps or errors.
=> LibWasm/WASI: Don't convert enums and u8s into i64

AK/BinaryHeap.h, Userland/Libraries/LibCompress/Huffman.h, Userland/Libraries/LibGfx/ImageFormats/WebPLoaderLossless.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
This implements the start of lossless webp's compression scheme,
which is almost, but not quite, entirely unlike deflate.
The green channel is now green-or-length, and has up to 280
entries, instead of up to 256 before. We now use the 40-entry
distance code (even though it only ever stores 1s now).
Due to this, a few places change to taking spans instead of
Array<256>s.
The spec only has the transform from prefix or distance code
to value. The inverse prefix_decompose() in this patch is
my own invention. I checked with a python script that it's
a true inverse (see PR for the script).
We now look for back-references with a distance of 1, which is
equivalent to run-length encoding. It's fairly fast to compute,
but leaves compression on the table. Full window-based
back references will be in …
=> LibGfx/WebPWriter: Implement run-length encoding

Tests/LibWeb/Text/expected/HTML/HTMLTrackElement-kind-attribute.txt, Tests/LibWeb/Text/input/HTML/HTMLTrackElement-kind-attribute.html, Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
This reflects the HTML `kind` attribute.
(cherry picked from commit bdaa7f0e8ed738ad0bd6e19878f296436fe40377)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/316
=> Cherry-pick "LibWeb: Implement the `HTMLTrackElement.kind` attribute"

Ladybird/Qt/BrowserWindow.cpp
This avoids a segfault that would previously occur when middle clicking to close a tab if only 1 tab was open.
(cherry picked from commit b95c05b6115c8eb84fe6fec55f5152db852fe743)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/312
=> Cherry-pick "UI/Qt: Ignore tab bar middle clicks if the user didn't click on a tab"

Kernel/Memory/AnonymousVMObject.cpp
The methods try_create_with_size() and try_create_purgeable_with_size() on AnonymousVMObject are almost identical, other than one member that gets set (m_purgeable).
This PR makes try_create_purgeable_with_size() call try_create_with_size() so that both methods re-use the same code.
=> Kernel/Memory: Remove duplicate code in try_create_purgeable_with_size()

Userland/Services/AudioServer/Mixer.cpp, Userland/Services/AudioServer/Mixer.h, Userland/Services/AudioServer/main.cpp
On several platforms, we don't yet have audio support, so audio devices are missing. Instead of having AudioServer crash repeatedly, and not having the ability to open any app that relies on it, we should instead handle missing devices gracefully. This implementation is minimal, audio device hotplugging support and such should be implemented together with multi-device support. AudioServer will start up and seem to function normally without an audio device, but it will pretend the device has a sample rate of 44.1 kHz and all audio input is discarded.
=> AudioServer: Handle missing audio device gracefully

Userland/Utilities/comm.cpp, Userland/Utilities/cut.cpp, Userland/Utilities/grep.cpp, Userland/Utilities/sed.cpp
This PR adds support for reading arbitrarily long lines in the `comm`, `cut`, `grep` and `sed` utilities.
Previously, these utilities wouldn't behave correctly when working with input containing lines longer than 4KiB.
I've also included a drive-by commit to fix an off-by-one error in `cut`, which led to the last character on each line being skipped when the `-b` or `-c` option was used.
=> Utilities: Support reading arbitrarily long lines

Tests/LibWeb/Text/expected/geometry/domrect-create.txt, Tests/LibWeb/Text/input/geometry/domrect-create.html, Userland/Libraries/LibWeb/Geometry/DOMQuad.cpp, Userland/Libraries/LibWeb/Geometry/DOMRect.idl, Userland/Libraries/LibWeb/Geometry/DOMRectReadOnly.idl
(cherry picked from commit bff6c0680aff5862e05c68af03a653f2250328b4)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/337
=> Cherry-pick "LibWeb/Geometry: Make DOMRect doubles unrestricted"

Meta/shell_include.sh
BSD `du` can also print apparent size, it just needs a different flag.
Makes `serenity.sh run` get a bit farther trying to build the disk image on macOS without brew installed. No intended behavior change elsewhere.
=> Meta: Make disk_usage() not depend on GNU du

Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
This avoids an unnecessary lossy conversion for the current time from double to i32. And avoids an UBSAN failure on macOS that's dependent on the current uptime.
(cherry picked from commit 55c1b5d1f4d7c82f0a68323260cb2e0f7de2faae,
amended to fix a typo in the commit message)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/335
=> Cherry-pick "LibWeb: Use double as the argument for AnimationFrameCallbacks"

Documentation/BuildInstructions.md, Documentation/Kernel/RAMFS.md, Kernel/Syscalls/jail.cpp, Userland/Libraries/LibCore/Socket.h, Userland/Libraries/LibLine/InternalFunctions.cpp
There are a few instances where comments and documentation have minor grammar
issues likely resulting from English being the author's second language.
This PR fixes several such cases, changing to idiomatic English and resolving
where it is unclear whether the user or program/code is being referred to.
=> Grammar fixes

Ladybird/AppKit/UI/TabController.mm
Is necessary, since history navigation was refactored
(cherry picked from commit 8a7afffdd357b3fb16c7e6c6ff32198165294b60)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/363
=> Cherry-pick "Ladybird/AppKit: Enable reload action"

Ladybird/AppKit/UI/TabController.mm
By Setting setBordered propperty on header buttons to `Yes` this path makes the whole button clickable. Previously the only the icon was clickable, now it's easy to click.
(cherry picked from commit af909784547c4f0ea8218ce464f45b3a1b0f4cb7)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/328
=> Cherry-pick "UI/AppKit: Make the header buttons more accessible"

Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
This is an attempt to fix the hanging CI on macOS caused by some screenshot requests being stuck unprocessed. With this change, we at least make sure that the HTML event loop processing, which triggers repainting, will happen as long as there are navigables that need to be repainted.
(cherry picked from commit 72b4d44d07e12cc04bde90872e2f31aaab64aa00)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/361
=> Cherry-pick "LibWeb: Reschedule HTML event loop processing if navigable needs repaint"

Userland/Libraries/LibGfx/ImageFormats/AnimationWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/AnimationWriter.h, Userland/Libraries/LibGfx/ImageFormats/GIFWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPWriter.cpp, Userland/Utilities/animation.cpp
AnimationWriter already only stores the smallest rect that contains
changing pixels between two frames. For example, when doing a screen
recording and only the mouse cursor moves, we already only encode
the pixels in the (single) rectangle containing old and new mouse cursor
positions.
Within that rectangle, there can still be many pixels that are identical
over the two frames. When possible, we now replace all identical pixels
with transparent black. This has two advantages:
1. It can reduce the number of colors in the image. In particular,
for wow.gif (and likely many other gifs), new frames had more
than 256 colors before, and have fewer than 256 colors after this
change.
2. Long run of identical pixels compress better.
In some cases, this transform might make things slighly worse,
for …
=> LibGfx/AnimationWriter+WebPWriter: Compress identical pixels in consecutive frames 

AK/Assertions.cpp
See [this](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/36722) for more context; the libexecinfo package got removed from Alpine last year, and for recent builds I've resorted to using a version from one of the old repositories. Looks like there's no point in building with it considering that it's broken anyways.
=> AK: Do not build against libexecinfo on non-glibc systems

Userland/Applications/FileManager/main.cpp
This patch adds the common Ctrl-N shortcut to FileManager for opening a new window.
=> FileManager: Add keyboard shortcut for new window

AK/Assertions.cpp
Spiritual continuation of #24669 (I couldn't add more commits to the previous branch, so a new MR it is...)
Adds an explicit check for Hurd due to previous regression. 
@ADKaster do you see any way this could break? I think that Hurd is an outlier and otherwise nothing (that's not Linux) uses glibc; If I'm wrong, then maybe the correct way is to stop checking for Linux and just check for glibc itself?
=> AK: Re-enable execinfo for GNU Hurd

Userland/Libraries/LibAudio/Sample.h
Sample::clip() now uses clamp().
=> LibAudio: Use clamp() in Sample::clip()

Documentation/BuildInstructionsLadybird.md, Ladybird/README.md, README.md
As it has been a month since the migration, I believe it is safe to remove the warning and specify the state of the SerenityOS version of the Ladybird browser.
=> Meta: Update the Ladybird repo notice and remove it from the README

Userland/Services/WindowServer/Window.cpp
Userland/Services/WindowServer/Window.cpp contained two TODO comments about disabling the min/maximize buttons on windows. This feature has been added, so I removed the comments.
The feature was added on lines 237 and 240 of Window.cpp, in Window::update_window_menu_items().
[This pull request](https://github.com/SerenityOS/serenity/commit/74ae6ac94b990037ae5ef412781e74e4c896af2f#diff-ee8b9ee1447ca3309e2ff182ed1a16a553b519a598548e98d72288279a6bc605) first implemented the feature. Some pull requests later on, like [this one](https://github.com/SerenityOS/serenity/commit/5aa9f128fca5a377d88323e7e4a5dc57efdae547), updated it.
=> Window.cpp: Remove TODOs

Kernel/Memory/InodeVMObject.cpp, Kernel/Memory/InodeVMObject.h, Kernel/Memory/Region.cpp, Kernel/Memory/Region.h, Kernel/Memory/SharedInodeVMObject.cpp, Kernel/Memory/SharedInodeVMObject.h, Tests/Kernel/TestEmptyPrivateInodeVMObject.cpp, Tests/Kernel/TestEmptySharedInodeVMObject.cpp, Tests/Kernel/TestPrivateInodeVMObject.cpp, Tests/Kernel/TestSharedInodeVMObject.cpp
This PR fixes this issue https://github.com/SerenityOS/serenity/issues/15951
* Pages of file mmap regions with no writes to them are marked as clean
* Writing to a clean page will mark the page as dirty
* When msync() is called:
* Only dirty pages are flushed to storage
* The flushed pages are now synced with storage, so they are marked clean and remapped
* NOTE: This only applies to SharedInodeVMObjects
* When purge() is called, only clean pages are evicted from memory
This PR also adds a few more test cases for private and shared file mmaps
=> Kernel/Memory: Make mmap objects track dirty and clean pages

AK/GenericLexer.h, AK/JsonParser.cpp, Tests/AK/TestJSON.cpp
For example, such use is seen on Twitter.
----
Cherry-Picked from: https://github.com/LadybirdBrowser/ladybird/pull/369
=> AK: Decode paired UTF-16 surrogates in a JSON string

AK/ConstrainedStream.h, Meta/generate-libwasm-spec-test.py, Tests/LibWasm/test-wasm.cpp, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h, Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp, Userland/Libraries/LibWasm/AbstractMachine/Operators.h, Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp, Userland/Libraries/LibWasm/Parser/Parser.cpp, Userland/Libraries/LibWasm/Types.h, Userland/Libraries/LibWasm/WASI/Wasi.cpp, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp, Userland/Utilities/wasm.cpp
=> LibWasm+AK: Sync Wasm changes from ladybird

Userland/Libraries/LibWeb/Page/EventHandler.cpp
This now matches the behavior of did_request_link_context_menu and friends. Previously the coordinates relative to the page rather than viewport were sent to the chrome.
(cherry picked from commit 990cf9b4e9476d15494a9538614762119d759b2d)
Depends on #24554
=> LibWeb: Use viewport position for did_enter_tooltip_area

Userland/Applications/Calendar/EventManager.cpp
This PR allows Calendar to display Events in chronological order.
Before: 
After:
=> Calendar: Sort Events by start DateTime

Userland/Utilities/cat.cpp
Adds the -n line numbering feature to cat, with the same formatting as gnu's cat function.
=> cat: Add the -n line numbering feature

Kernel/Memory/AddressSpace.cpp, Kernel/Memory/AnonymousVMObject.cpp, Kernel/Memory/AnonymousVMObject.h, Kernel/Memory/Region.cpp, Kernel/Memory/Region.h, Kernel/Memory/VMObject.cpp, Kernel/Memory/VMObject.h, Tests/Kernel/CMakeLists.txt, Tests/Kernel/TestAnonymousMmap.cpp
This PR fixes the following problems related to anonymous mmaps:
* After a fork, writes to an anonymous mmap  cause redundant page faults (#24637)
* Writes to a shared anonymous mmap are not visible to other processes that share the mmap (#24638)
* VMObject::try_clone() overcommits pages to m_shared_committed_cow_pages
This PR also adds more test cases for anonymous mmaps.
=> Kernel/Memory: Various fixes for anonymous mmaps

Userland/Libraries/LibPDF/Renderer.cpp
Using the path rasterizer here is much slower than simply drawing four lines. This also more accurately shows the (real) clip as the bounding box is truncated to an int before adding it as a clip rect.
Fixes #23056
=> LibPDF: Use `draw_rect()` to show debug clipping rects

Userland/Applications/Browser/BrowserWindow.cpp, Userland/Applications/KeyboardMapper/main.cpp, Userland/Applications/PixelPaint/MainWidget.cpp, Userland/Applications/Terminal/main.cpp, Userland/Demos/CatDog/main.cpp, Userland/Libraries/LibGUI/Action.h, Userland/Libraries/LibGUI/CommonActions.cpp
This patch adds the common Ctrl-W shortcut to `make_quit_action` as an alternate shortcut by default.
The shortcut can be disabled in programs using this key binding for a different purpose, e.g. closing tabs, or instances where the "close window" concept would not be applicable, such as CatDog.
To the best of my knowledge, I have disabled the shortcut for any existing programs in the system where the aforementioned examples or any additional conflicts would apply.
=> LibGUI: Add alt shortcut for make_quit_action

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPLoader.cpp
This matches libwebp (see ZeroFillCanvas() call in libwebp/src/demux/anim_decode.c:355 and ZeroFillFrameRect() call in line 435, but in WebPAnimDecoderGetNext()) and makes files written e.g. by asesprite look correct -- even though the old behavior is also spec-compliant and arguably makes more sense. Now nothing looks at the background color stored in the file.
See PR for an example image where it makes a visible difference.
=> LibGfx/WebPLoader: Use transparent black as animation background color

Userland/Libraries/LibMedia/Color/ColorConverter.cpp, Userland/Libraries/LibMedia/PlaybackManager.cpp, Userland/Libraries/LibMedia/VideoFrame.cpp
(cherry picked from commit 7a03ef45c2fa7f416a26955593fda34c4521f123)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/383
=> Cherry-pick "LibMedia: Support videos with BT470BG color matrix"

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/419
(cherry picked from commit 9c80326053356ddeb986df275a19468c16a8469a)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/436
=> Cherry-pick "LibWeb: Ensure EC on stack when resolving/rejecting image decode promise"

Tests/LibWeb/Layout/expected/input-placeholder.txt, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
So that it is closer to the spec.
https://www.w3.org/TR/css-ui-4/#input-rules
(cherry picked from commit 13cd653d1ccf9ef486f4622e350614361e275a0c)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/433
=> Cherry-pick "LibWeb/HTML: Update Text Input Styling"

Userland/Libraries/LibWeb/CSS/Default.css
Instead of using fixed arbitrary colors for the background of the bar, AccentColor and Background are now used.
(cherry picked from commit 062a266574a24fe13f2a77401b97f833c3cdd099)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/486
=> Cherry-pick "LibWeb: Use system colors for input type range and progress as default"

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
The style of input and textarea elements is now invalidated when focus is changed to a new element. This ensures any `:focus` selectors are applied correctly.
(cherry picked from commit 572324d47b99bcfbc5db5ff6aef0d6c4eb15ce4c)
--
https://github.com/LadybirdBrowser/ladybird/pull/499
=> Cherry-pick "LibWeb: Invalidate input element style on focus change"

Tests/LibWeb/Layout/expected/dialog-open-modal.txt, Tests/LibWeb/Layout/expected/dialog-open-non-modal.txt, Tests/LibWeb/Layout/expected/top-layer.txt, Tests/LibWeb/Layout/input/dialog-open-modal.html, Tests/LibWeb/Layout/input/dialog-open-non-modal.html, Userland/Libraries/LibWeb/CSS/PseudoClasses.json, Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp, Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Adds the :modal pseudo class which matches dialogs opened with showModal().
(cherry picked from commit 63a5ff70e5f3bee10839415885a158e304719fec)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/345
=> Cherry-pick "LibWeb: Implement :modal pseudo class"

Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp
Per https://github.com/whatwg/webidl/commit/3fb6ab4dbc6a42517c84acf0909, this step in the spec didn't reflect the reality in mainstream browsers. This change fixes a failure in WPT/dom/collections/
(cherry picked from commit fac82119dff6f8063490698934ddd4243970eea3)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/550
=> Cherry-pick "LibWeb: Legacy Platform Objects don't force [[Configurable]]"

Userland/Libraries/LibJS/Bytecode/CommonImplementations.h, Userland/Libraries/LibJS/Bytecode/Executable.h
This allows global `let` and `const` variable accesses to be cached by the GetGlobal instruction, and works even when the access is in a different translation unit from the declaration.
Knocks a ~10% item off the profile on https://ventrella.com/Clusters/
(cherry picked from commit 9448c957c136e62b374a0f8998d1d51906e59fb5)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/488
=> Cherry-pick "LibJS: Cache environment index for global declarative bindings"

Tests/LibWeb/Text/expected/no-window-resize-on-load.txt, Tests/LibWeb/Text/input/no-window-resize-on-load.html, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h
The first time Document learns its viewport size, we now suppress firing of the resize event.
This fixes an issue on multiple websites that were not expecting resize events to fire so early in the loading process.
(cherry picked from commit 4e7558c88b7a993686bb3dc173731e677efe5e26)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/547
=> Cherry-pick "LibWeb: Don't fire resize event until document actually resizes once"

Tests/LibWeb/Layout/expected/abspos-box-bottom-with-max-height.txt, Tests/LibWeb/Layout/input/abspos-box-bottom-with-max-height.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Solving using the unconstrained height, when solving for bottom, would either leave a gap over overflow its container.
(cherry picked from commit bee42160c5e2cdb949e6057f029391ee7e0fa9fa)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/553
=> Cherry-pick "LibWeb: When solving abspos lengths, use min max constrained height"

Tests/LibWeb/Text/expected/DOM/Node-normalize.txt, Tests/LibWeb/Text/input/DOM/Node-normalize.html, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/Node.h, Userland/Libraries/LibWeb/DOM/Node.idl
This method puts the given node and all of its sub-tree into a normalized form. A normalized sub-tree has no empty text nodes and no adjacent text nodes.
(cherry picked from commit 0a0651f34ea927a0ca44dc5d2c7786f3dcf8da25)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/588
=> Cherry-pick "LibWeb: Implement `Node.normalize()`"

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp, Userland/Libraries/LibWeb/UIEvents/MouseEvent.h, Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp, Userland/Libraries/LibWeb/UIEvents/WheelEvent.h
These methods were overriding properties specified by the EventInit property bags in the constructor for WheelEvent and MouseEvent.
They appear to be legacy code and no longer relevant, as they would have been used for ensuring natively dispatched events had the correct properties --- This is now done in separate create methods, such as MouseEvent::create_from_platform_event.
This fixes a couple WPT failures (e.g. in
/dom/events/Event-subclasses-constructors.html)
(cherry picked from commit 2c396b5378fec5f4470e1e1e950806dff8005f08)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/586
=> Cherry-pick "LibWeb: Remove set_event_characteristics()"

Userland/Libraries/LibWeb/UIEvents/FocusEvent.cpp
This fixes some WPT failures caused by the "view" parameter not being initialized from the property bag.
(cherry picked from commit 932a7d4d819fac9d0acfe4184574488dd69f94ec)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/576
=> Cherry-pick "LibWeb: Pass event_init to base class constructor in FocusEvent"

Userland/Libraries/LibWeb/CSS/Default.css, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Previously the entire slider track was colored.
Now only the lower part of the slider track (left side of the thumb) is colored.
Chrome and Firefox do the same.
(cherry picked from commit 7766909415312b971252f8c7750b0a1873fd5ba0)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/513
=> Cherry-pick "LibWeb: Harmonize look of range input element"

Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt, Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Previously, when `WindowOrWorkerGlobalScope.reportError()` was called the `filename` property of the dispatched error event was blank. It is now populated with the full path of the active script.
(cherry picked from commit 34b987366449313c96a73ec1d70e88e60f2c4510)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/493
=> Cherry-pick "LibWeb: Populate filename in `WindowOrWorkerGlobalScope.reportError()`"

Userland/Libraries/LibWeb/CSS/Default.css
Fixes https://github.com/LadybirdBrowser/ladybird/issues/512
(cherry picked from commit b5e80db2259448bc0b3dc48d88f53e8d1880987e)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/518
=> Cherry-pick "LibWeb: Define width for -webkit-slider-runnable-track"

Tests/LibWeb/Layout/expected/input-range.txt, Tests/LibWeb/Layout/input/input-range.html, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Previously the input element was displayed with value 0, when no value was set in the HTML. Now it uses `value_sanitization_algorithm()`, which will calculate the default value.
In `value_sanitization_algorithm()` there was a logical mistake/typo. The comment from the spec says "unless the maximum is less than the minimum".
The added layout test would fail without the code changes. Fixes #520
(cherry picked from commit 191531b7b18d2edf97dc7bf88a9c19903eeae2d5)
--
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/555
=> Cherry-pick "LibWeb: Use correct default value for <input type=range>"

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/DOM/derived-interface-prototype.txt, Tests/LibWeb/Text/input/DOM/derived-interface-prototype.html
Following the rules in the algorithm from
https://webidl.spec.whatwg.org/#js-platform-objects, "To Internally create a new object implementing the interface interface", this change incorporates the steps to load a prototype from new.target, and write it to the created instance returned from constructor_impl(). This mirrors the code for generate_html_constructor(), which incorporates additional steps needed by Custom Elements.
Bug https://github.com/LadybirdBrowser/ladybird/issues/334
(cherry picked from commit 80cd3712c2c52bf749a19cbd21af0c5c479a87c9)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/379
=> Cherry-pick "LibWeb: Implement WebIDL constructor flow for derived classes"

Tests/LibWeb/Layout/expected/flex/justify-content-on-min-content-with-gap.txt, Tests/LibWeb/Layout/input/flex/justify-content-on-min-content-with-gap.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
The remaining space is in addition to, not of in place of the main gap.
(cherry picked from commit 47aee289d87add9784a2d722cb529774cdfb54e2)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/437
=> Cherry-pick "LibWeb: Change flex remaining space distribution to include gap"

Userland/Libraries/LibWebView/URL.cpp
Previously, the presence of surrounding whitespace would give file paths the `https` schema instead of the `file` schema, making navigation unsuccessful.
(cherry picked from commit ff7ca5c48c316e07b1bf631b2d7ed14c358dfa42)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/631
=> Cherry-pick "LibWebView: Trim whitespace when sanitizing file paths"

Userland/Libraries/LibWeb/DOM/Document.cpp
The spec doesn't explicitly forbid calling this when the document doesn't have a node navigable, so let's handle that situation gracefully by just returning an empty list of ancestors.
I hit this VERIFY somewhere on the web, but I don't know how to reproduce it.
---
Cherry-picks PR-less (!) https://github.com/LadybirdBrowser/ladybird/commit/b118c99c271e
Without this, the render process crashes when going to "resource://asdf" or "google.com:22" when testing https://github.com/SerenityOS/serenity/pull/24702.
=> Cherry-pick "LibWeb: Add null check in Document::ancestor_navigables()"

Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.h, Userland/Utilities/image.cpp
Lossless WebP allows having a 1-bit to 11-bit addressed
"color cache", where pixels are inserted into a content-addressed
cache of size `1 << color_cache_bits`. Pixels in the color
cache can be addressed using their index. This can be used
to refer to literal pixels using a single color_cache_bits
large symbol, instead of up to 4 symbols for GBRA.
We default to always using a color cache with 6 bits, unless
the input image already uses only a single channel already
(either as-is, or if we write a color indexing transform).
sunset_retro.png (876K):
1.6M -> 1.4M, 29.1 ms ± 0.9 ms -> 31.7 ms ± 0.9 ms
From 83% larger than the input file to 60% larger (12.5% smaller),
for a 9% slowdown.
The two gifs I usually test with don't change: Files using the
color _index_ transform (i.e. that have < 256 …
=> LibGfx/WebPWriter: Add support for writing color cache symbols

Tests/LibWeb/Text/expected/Streams/ReadableStreamBYOBReader-read-min.txt, Tests/LibWeb/Text/input/Streams/ReadableStreamBYOBReader-read-min.html, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp, Userland/Libraries/LibWeb/Streams/AbstractOperations.h, Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp, Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h, Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp, Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.h, Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.idl
When the min option is given the read will only be fulfilled when there are min or more elements available in the readable byte stream.
When the min option is not given the default value for min is 1.
(cherry picked from commit 907dc84c1e8c3c236ade581f46dabdb144915c1d)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/557
=> LibWeb: Implement min option for ReadableStreamBYOBReader.read()

.github/workflows/lagom-template.yml
This step runs a small subset of WPT. Several of the tests it runs fail, but the step doesn't fail, indicating that nobody looks at the step's output.
The step takes 3 minutes to run. We can add it back later if someone is interested in looking at the output.
=> CI: Stop running WPT on Lagom (Linux, ubuntu-22.04, NO_FUZZ) / CI)

Userland/Libraries/LibC/stdlib.cpp
Since be2bf055 the ThreadEventQueue is now destroyed via a phread key destructor, which leads to many other objects being destroyed. A bunch of these destructors reference globals, but exit() calls destructors on globals before phread destructors, this bad state leads to the hangs seen in #24694.
Fixes #24694
=> LibC: Call pthread key destructors before global destructors

Kernel/FileSystem/OpenFileDescription.cpp
This commit merges 2 if statements that check the same condition in OpenFileDescription::~OpenFileDescription().
=> Kernel/FileSystem: Clean up duplicated if statements

Meta/Lagom/CMakeLists.txt
- `_free` is no longer exported by default, export it manually
- `allocateUTF8` is deprecated, and replaced with `stringToNewUTF8`
=> Meta: Update Wasm LibJS build for "recent" emscripten changes

Userland/Libraries/LibGUI/SpinBox.cpp
Negative numbers now display correctly in SpinBox.
Previously, they displayed as the negative sign only (no number).
Now the user can also type negative numbers into the SpinBox.
=> LibGUI: Improve how SpinBox handles negative numbers

Base/usr/share/man/man1/watchfs.md, Userland/Utilities/CMakeLists.txt, Userland/Utilities/watchfs.cpp
This utility is meant mainly for debugging purposes, to watch regular files and directories being modified.
I still need to write the manual page, but I'd like to know if this is a good idea or not.
Related to #24210.
=> Utilities: Introduce the watchfs utility

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp, Tests/LibWeb/Ref/css-has-compound.html, Tests/LibWeb/Ref/css-has-descendant.html, Tests/LibWeb/Ref/css-has-direct-child.html, Tests/LibWeb/Ref/css-has-next-sibling.html, Tests/LibWeb/Ref/css-has-subsequent-sibling.html, Tests/LibWeb/Ref/css-nested-has.html, Tests/LibWeb/Ref/css-pseudo-element-in-has.html, Tests/LibWeb/Ref/reference/css-has-compound.html, Tests/LibWeb/Ref/reference/css-has-descendant.html, Tests/LibWeb/Ref/reference/css-has-direct-child.html, Tests/LibWeb/Ref/reference/css-has-next-sibling.html, Tests/LibWeb/Ref/reference/css-has-subsequent-sibling.html, Tests/LibWeb/Ref/reference/css-nested-has.html, Tests/LibWeb/Ref/reference/css-pseudo-element-in-has.html, Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Userland/Libraries/LibWeb/CSS/PseudoClasses.json, Userland/Libraries/LibWeb/CSS/Selector.cpp, Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp, Userland/Libraries/LibWeb/CSS/SelectorEngine.h, Userland/Libraries/LibWeb/Dump.cpp
See https://drafts.csswg.org/selectors-4/#relational.
(cherry picked from commit f63a945ba0300551417c740e450957f29c9b73d1)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/613
=> Cherry-pick "LibWeb: Implement the `:has()` pseudo-class"

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Tests/loops/for-scopes.js
Implement for CreatePerIterationEnvironment for 'for' loops per the Ecma Standard. This ensures each iteration of a 'for' loop has its own lexical environment so that variables declared in the loop are scoped to the current iteration.
(cherry picked from commit dbc2f7ed48f00234f5f94a30b06b83842d9cf4dd)
---
https://github.com/LadybirdBrowser/ladybird/pull/675
=> Cherry-pick "LibJS: Implement CreatePerIterationEnvironment for 'for' statements"

Tests/LibWeb/Text/expected/DOM/getElementById-multiple.txt, Tests/LibWeb/Text/input/DOM/getElementById-multiple.html, Userland/Libraries/LibWeb/DOM/NonElementParentNode.h
We had a const and non-const version of this function, with slightly different behavior (oops!)
This patch consolidates the implementations and keeps only the correct behavior in there.
Fixes an issue where comments were not collapsible on Hacker News.
(cherry picked from commit 98f88d49de852e1e524655accb39724f1134a23f)
---
https://github.com/LadybirdBrowser/ladybird/pull/746
=> Cherry-pick "LibWeb: Make getElementById() always return first match in tree order"

Userland/Libraries/LibJS/Runtime/VM.h
The JS::Error types all store their exception messages as a String. So by using ByteString, we hit the StringView constructor, and end up allocating the same string twice.
(cherry picked from commit c3f8202d0ca7761caaabf0af5f413dc25337801f)
---
https://github.com/LadybirdBrowser/ladybird/pull/684
=> Cherry-pick "LibJS: Create exception messages as Strings"

Userland/Applications/Calendar/CalendarWidget.cpp, Userland/Applications/Calendar/EventManager.cpp, Userland/Applications/Calendar/EventManager.h
This PR adds basic support for loading iCalendar (.ics) files and parsing VEVENT properties that are currently supported by Calendar Events: summary, start and end.
=> Calendar: Initial support for iCalendar format

Tests/LibWeb/Layout/expected/grid/define-area-using-line-names.txt, Tests/LibWeb/Layout/input/grid/define-area-using-line-names.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Areas are disassembled into boundary lines on `build_grid_areas()` step, so we can always use them to find grid item's position during placement. This way we support both ways to define area: `grid-template-areas` and implicitly using `-start` and `-end` boundary line names.
(cherry picked from commit 7a1f3f7ae3af2744e2f99df29baf09153d631b24)
---
https://github.com/LadybirdBrowser/ladybird/pull/691
=> Cherry-pick "LibWeb: Change grid item placement to look for area by boundary lines"

Tests/LibWeb/Layout/expected/grid/1fr-1000px.txt, Tests/LibWeb/Layout/input/grid/1fr-1000px.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Change min track sizing function to be "auto" when flex size is specified.
- Never check if min track sizing funciton is flexible, because only max is allowed to be flexible.
- Address FIXME in automatic_minimum_size to avoid regressions after making two fixes mentioned above.
(cherry picked from commit 3270df476dd46b140e1b9de1e8328647744b56ab)
---
https://github.com/LadybirdBrowser/ladybird/pull/685
=> Cherry-pick "LibWeb: Fix flexible track sizing in GFC"

Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp
The EntryType has three possible values: Fetching, Failed or ModuleScript. It is possible that we transition from Fetching to Failed as in #13.1. Change the assertion to include the failed scenario.
Fixes: https://github.com/LadybirdBrowser/ladybird/issues/661 (cherry picked from commit 319bb6353e0ba64fc5e54b32ddb2b38736cedef9)
---
https://github.com/LadybirdBrowser/ladybird/pull/704
=> Cherry-pick "LibWeb: Fix assertion failure on telekom.de"

Base/res/ladybird/inspector.js, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp, Userland/Libraries/LibWeb/DOM/Utils.cpp, Userland/Libraries/LibWeb/DOM/Utils.h
Now keep a track of the DOM nodes which are actually visible in the Inspector, and allow the user to navigate the tree using the keyboard.
<hr>
Cherry-picks LadybirdBrowser/ladybird#628
Cherry-picks LadybirdBrowser/ladybird#706
Cherry-picks LadybirdBrowser/ladybird#748
=> Cherry-pick "LibWebView: Add keyboard navigation to the Inspector" + 2 others

Base/res/ladybird/inspector.css, Base/res/ladybird/inspector.js
We currently display scroll bars for the JS console and its parent tab container. We want the console output to be separately scrollable from the tab content, but since both containers are scrollable, we end up with nested scroll bars. This also makes actually scrolling feel pretty awkward.
Prevent this by making the tab container non-scrollable when the JS console is shown.
Before:
After:
<hr>Cherry-picks LadybirdBrowser/ladybird#749<br><sub>Generated with LBSync, did I do well?</sub>
=> Cherry-pick "LibWebView: Prevent displaying two scroll bars in the inspector console"

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Update `update_for_history_step_application` to meet some of the specs changes introduced in https://github.com/whatwg/html/pull/9856 and in https://github.com/whatwg/html/pull/9990
Fixes https://github.com/LadybirdBrowser/ladybird/issues/740
<hr>
Cherry-picks LadybirdBrowser/ladybird#757<br><sub>Generated with LBSync, did I do well?</sub>
=> Cherry-pick "LibWeb: Update 'update_for_history_step_application' to meet new specs"

Tests/LibWeb/Layout/expected/svg-text-with-percentage-values.txt, Tests/LibWeb/Layout/expected/svg/svg-line-with-percentage-values.txt, Tests/LibWeb/Layout/input/svg-text-with-percentage-values.html, Tests/LibWeb/Layout/input/svg/svg-line-with-percentage-values.html, Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp, Userland/Libraries/LibWeb/SVG/SVGLineElement.cpp, Userland/Libraries/LibWeb/SVG/SVGLineElement.h, Userland/Libraries/LibWeb/SVG/SVGTextPositioningElement.cpp, Userland/Libraries/LibWeb/SVG/SVGTextPositioningElement.h
Text element before:
After:
Line element before:
\<blank page\>
After:
<hr>Cherry-picks LadybirdBrowser/ladybird#752<br><sub>Generated with LBSync, did I do well?</sub>
=> Cherry-pick "LibWeb: Support percentage values in SVG text/line element"

Userland/Libraries/LibWeb/CSS/Default.css, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h, Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
Fixes #466
(cherry picked from commit 9df8e1f22468884db353f55d10823cd3d15c511b)
---
https://github.com/LadybirdBrowser/ladybird/pull/587
=> Cherry-pick "LibWeb: Support `accent-color` for range input and progress element"

Tests/LibWeb/Text/expected/ShadowDOM/remove-style-element-inside-shadow-tree.txt, Tests/LibWeb/Text/input/ShadowDOM/remove-style-element-inside-shadow-tree.html, Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp, Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp, Userland/Libraries/LibWeb/DOM/StyleElementUtils.h, Userland/Libraries/LibWeb/HTML/HTMLStyleElement.cpp, Userland/Libraries/LibWeb/SVG/SVGStyleElement.cpp
Before this change, removing a style element from inside a shadow tree
would cause it to be unregistered with the document-level list of sheets
instead of the shadow-root-level list.
This would eventually lead to a verification failure if someone tried to
update the text contents of that style element, since it was still in
the shadow-root-level list, but now with a null owner element.
Fixes a crash on https://www.swedbank.se/<hr>Cherry-picks LadybirdBrowser/ladybird#784<br><sub>Generated with LBSync, did I do well?</sub>
=> Cherry-pick "LibWeb: Use correct scope when removing style sheet inside a shadow tree"

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Runtime/VM.cpp, Userland/Libraries/LibJS/Runtime/VM.h, Userland/Libraries/LibJS/Runtime/Value.cpp, Userland/Libraries/LibJS/Runtime/Value.h
The typeof operator has a very small set of possible resulting strings, so let's make it much faster by caching those strings on the VM.
~8x speed-up on this microbenchmark:
for (let i = 0; i < 10_000_000; ++i) {
typeof i;
}
<hr>Cherry-picks LadybirdBrowser/ladybird#783<br><sub>Generated with LBSync, did I do well?</sub>
=> Cherry-pick "LibJS: Make `typeof` a lot faster by caching all possible results"

Kernel/Tasks/Scheduler.cpp
This is likely a leftover from the i686-only days. Also rename the get_eip function to get_pc to be more arch-agnostic.
=> Kernel: Don't truncate the pc value in the scheduler state dump

Kernel/Arch/x86_64/Interrupts/APIC.cpp
This avoids spurious interrupts during APIC timer calibration, as the timer might otherwise immediately generate an interrupt when enabling interrupts if the initial count was at a low enough value.
=> Kernel/x86: Stop the APIC timer before configuring it

Userland/Applications/Mail/MailWidget.cpp, Userland/Applications/Mail/MailWidget.h
This PR fixes a bug where selecting a mailbox node would send multiple repeated IMAP commands, ultimately hanging the parser.
=> Mail: Don't spam commands on mailbox node selection

Kernel/FileSystem/Ext2FS/Definitions.h, Kernel/FileSystem/Ext2FS/FileSystem.cpp, Kernel/FileSystem/OpenFileDescription.cpp, Kernel/FileSystem/OpenFileDescription.h
This PR adds some small code cleanups to the FileSystem code.
The 2 commits do the following:
* Update the placement of some const keywords to match the 'const placement' rule of the style guide.
* Replace a hardcoded offset in the Ext2FS code with a constexpr
=> Kernel/FileSystem: Small code cleanups

Userland/Libraries/LibIMAP/Parser.cpp
This PR fixes a crash where the parser assumes parenthesized lists of address structures should be separated by whitespace. Per RFC-9051, there is no indication of this.
=> LibIMAP: Properly parse parenthesized address lists

Kernel/Bus/USB/USBConfiguration.cpp, Kernel/Bus/USB/USBDescriptors.h, Kernel/Bus/USB/USBInterface.h
This PR fixes incorrect assumptions about the layout of descriptors and gets rid of all the pointer arithmetic by using an AK::Stream instead.
The USB spec doesn't define a strict order for all descriptors to appear in.
It just says that endpoint descriptors follow its interface descriptor.
We also have to skip all unknown descriptors (which also can appear anywhere), not just HID descriptors.
=> Kernel/USB: Correctly parse USB descriptors

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
In `PaintableBox::set_scroll_offset()` the scrollport size was measured by `content_size()` instead of `absolute_padding_box_rect()`.
Fixes #788
(cherry picked from commit 54066ec5a454f33d8c5e4ea1f8695942b95b1b82)
---
https://github.com/LadybirdBrowser/ladybird/pull/789
=> Cherry-pick "LibWeb: Use absolute padding box to calculate max scroll offset"

Userland/Libraries/LibTextCodec/Decoder.cpp
This way, we still perform UTF-8 validation, but don't go through the slow generic code path that rebuilds the decoded string one code point at a time.
This was a bottleneck when loading a canned copy of reddit.com, which ended up being ~120 MiB large.
- Time spent decoding UTF-8 before this change: 1192 ms
- Time spent decoding UTF-8 after this change:  154 ms
That's still a long time, but 7.7x faster is nothing to sneeze at! :^)
Note that if the input fails UTF-8 validation, we still fall back to the slow path and insert replacement characters per the WHATWG Encoding spec: https://encoding.spec.whatwg.org/#utf-8-decode
(cherry picked from commit 1a46d8df5fc81eb2c320d5c8a5597285d3d8fb3a)
---
https://github.com/LadybirdBrowser/ladybird/pull/733
=> Cherry-pick "LibTextCodec: Use String::from_utf8() when decoding UTF-8 to UTF-8"

Tests/LibWeb/Layout/expected/details-closed.txt, Tests/LibWeb/Layout/expected/details-open.txt, Tests/LibWeb/Layout/expected/details-summary-default-ua-style.txt, Tests/LibWeb/Layout/input/details-summary-default-ua-style.html, Userland/Libraries/LibWeb/CSS/Default.css
This is the expected behavior per the HTML spec. Fixes an issue where styling these elements wouldn't have the expected effect unless you also set the display property.
(cherry picked from commit 3faff34bf6a290e4df1c73f92e8c7d992a78a8e0)
---
https://github.com/LadybirdBrowser/ladybird/pull/730
=> Cherry-pick "LibWeb: Make details and summary elements display:block in the UA style"

Userland/Applications/Mail/MailWidget.cpp
This PR removes the CRLF characters from the message body data before passing it to `decode_base64()` so that we can properly display the message contents.
=> Mail: Remove CRLF chars from base64 data before decoding

Tests/LibWeb/Text/expected/canvas/invalid-font-property.txt, Tests/LibWeb/Text/input/canvas/invalid-font-property.html, Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
Checking that the string parsed for the `font` property is not enough, the spec also wants to rule out CSS-wide keywords like `inherit`. The simplest way to do so is to check if it's a ShorthandStyleValue, which also rules out use of `var()`; this matches other browsers' behaviour.
The newly-added test would previously crash, and now doesn't. :^)
(cherry picked from commit 64d45afd8a650981d4dbab98aa49d47629568f5b)
---
https://github.com/LadybirdBrowser/ladybird/pull/791
=> Cherry-pick "LibWeb: Check CanvasTextDrawingStyles.font assignment is valid"

Tests/LibWeb/Text/expected/HTML/submit-button-click-when-disabled.txt, Tests/LibWeb/Text/input/HTML/submit-button-click-when-disabled.html, Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Fixes an infinite reload loop on some of the dom/events/ tests in WPT.
(cherry picked from commit 273593afba71a42f1d760ac5b6664b77f74ffb7a)
---
https://github.com/LadybirdBrowser/ladybird/pull/841
=> Cherry-pick "LibWeb: Don't proceed with Element.click() on disabled form controls"

Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
(cherry picked from commit cdfc7a92f72165ad530bfaf920f1caf18974692f)
---
https://github.com/LadybirdBrowser/ladybird/pull/825
=> Cherry-pick 'LibWeb: Fix typo "rtr" -> "rtl"'

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
It turns out we were already generating all the necessary include statements, and we can simply remove all this goofy code soup that uses the C preprocessor to speculatively look for include files.
(cherry picked from commit 2daaa22a15c69b89120a64d1144f99ca13ac689c)
---
https://github.com/LadybirdBrowser/ladybird/pull/844
=> Cherry-pick "LibWeb: Stop trying to guess include paths in IDL codegen"

Tests/LibWeb/Layout/expected/block-and-inline/relpos-inline-element-js-offsets.txt, Tests/LibWeb/Text/expected/DOM/Offset-of-empty-inline-element.txt, Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
We now follow the rules from the spec more closely, along with an unspecified quirk for when the offsetParent is a non-positioned body element. (Spec bug linked in a comment.)
This fixes a whole bunch of css-flexbox tests on WPT, which already had correct layout, but the reported metrics from JS API were wrong.
(cherry picked from commit d49ae5af32044cb83bc14073b92676a1662c3bc1)
---
https://github.com/LadybirdBrowser/ladybird/pull/831
=> Cherry-pick "LibWeb: Make offsetTop and offsetLeft behave more like other browsers"

Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/WebPWriterLossless.cpp
...for images that don't use a color indexing transform.
For now, write the predictor transform unconditionally, and predict every pixel as its left neighbor (that is, use predictor 1 everywhere).
This will grow a better heuristic in time, and eventually we might want to use more than 1 of the 13 different predictor modes. But on average, doing this unconditionally is better than not doing it unconditionally. (Also, it's possible to disable this transform using `image`'s `--webp-allowed-transforms` flag.)
Using the same benchmark as in #24819, this reduces the total size of the test images further, from 88M to 69M (21.6%). It does increase runtime for compressing all these images from about 4.4s to 4.7s, a 6.8% slowdown.
For the usual test image (no effect on the two animations, which use …
=> LibGfx/WebPWriterLossless: Use predictor transform

Userland/Libraries/LibLine/Editor.cpp, Userland/Libraries/LibLine/Editor.h, Userland/Libraries/LibLine/InternalFunctions.cpp, Userland/Libraries/LibLine/KeyCallbackMachine.cpp, Userland/Utilities/js.cpp
Apparently this is common in the js repl world.
Fixes #743.
(cherry picked from commit d3f089dc268931e670ea6a00ac8bcb06ed9822e6)
---
https://github.com/LadybirdBrowser/ladybird/pull/839
=> Cherry-pick "Utilities/js: Make it possible to exit via two consecutive ^C's"

Tests/LibWeb/Text/expected/Element-toggleAttribute-invalid-name.txt, Tests/LibWeb/Text/input/Element-toggleAttribute-invalid-name.html, Userland/Libraries/LibWeb/DOM/Element.cpp
This resolves a test in https://wpt.live/dom/nodes/attributes.html.
(cherry picked from commit f774d75f890e89a8483e5c7459de4fd96ce1b479)
---
https://github.com/LadybirdBrowser/ladybird/pull/819
=> Cherry-pick "LibWeb/DOM: Check if name is valid in Element.toggleAttribute"

Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
...otherwise we send out HTTP requests with duplicates of these headers.
(cherry picked from commit 847243b7065b80739fdd4d015bc6559b0581bb66)
---
https://github.com/LadybirdBrowser/ladybird/commit/847243b7065b80739fdd4d015bc6559b0581bb66 (sneak commit without PR)
=> Cherry-pick "LibWeb: Only inject "User-Agent"/"Accept" headers when they're missing"

Tests/LibWeb/Text/expected/DOM/Document-createElementNS-uppercase.txt, Tests/LibWeb/Text/input/DOM/Document-createElementNS-uppercase.html, Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
Previously, when creating a HTML element with
`document.createElementNS()` we would convert the given local name to lowercase before deciding which element type to return. We now no longer perform this lower case conversion, so if an uppercase local name is provided, an element of type `HTMLUnknownElement` will be returned. This aligns our implementation with the specification.
(cherry picked from commit 5a796629c61221261c1856e19dd829973e6158f0)
---
https://github.com/LadybirdBrowser/ladybird/pull/818
=> Cherry-pick "LibWeb: Make `document.createElementNS()` case-sensitive"

Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.cpp, Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.h, Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Fetch requests from web workers fail CORS checks because the origin is not inherited from the outside settings. Ensure web worker origin is correctly inherited from outside settings
(cherry picked from commit 24adb1c4526fe29bbc332780272251be1635cf05)
---
https://github.com/LadybirdBrowser/ladybird/pull/408
=> Cherry-pick "LibWeb: Add Web Worker Origin Inheritance"

Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp, Userland/Services/RequestServer/ConnectionFromClient.cpp
Ultimately it's RequestServer who knows which kind of encodings it can handle and decompress, so let's have it set the Accept-Encoding.
(cherry picked from commit 2c918b540db2efcef4751084592ae1cf3be0999f)
---
https://github.com/LadybirdBrowser/ladybird/pull/658
=> Cherry-pick "LibWeb+RequestServer: Let RequestServer set HTTP Accept-Encoding header"

Documentation/Browser/BrowsingContextsAndNavigables.md
(cherry picked from commit 7c0aa88e99cbc70942b07870fcb44b88e0f162dc)
---
https://github.com/LadybirdBrowser/ladybird/pull/677
=> Cherry-pick "Documentation: Fixed typo at BrowsingContextsAndNavigables"

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Choose a better name for private members which were added in https://github.com/LadybirdBrowser/ladybird/pull/513
(cherry picked from commit b1d7a27468e5dca58039c79a455c9f8ac1b80680)
---
https://github.com/LadybirdBrowser/ladybird/pull/669
=> Cherry-pick "LibWeb: Rename HTMLInputElement members related to range shadow tree"

Tests/LibWeb/Text/expected/Worker/Worker-location.txt, Tests/LibWeb/Text/input/Worker/Worker-location.html, Tests/LibWeb/Text/input/Worker/Worker-location.js, Userland/Libraries/LibWeb/HTML/WorkerLocation.cpp, Userland/Libraries/LibWeb/HTML/WorkerLocation.h
(cherry picked from commit 354e5a6624a92952b1f3b86f98d9b1d0cb0ec048)
---
https://github.com/LadybirdBrowser/ladybird/pull/877
=> Cherry-pick "LibWeb: Set correct prototype for `WorkerLocation`"

Kernel/Bus/USB/USBDescriptors.h
AArch64 Clang otherwise complains that this anonymous union is more aligned than the struct.
=> Kernel/USB: Make USBHubDescriptor::hub_characteristics union packed

Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.h, Userland/Utilities/image.cpp
Also give `image` a `--png-compression-level` flag.
The wins come from:
1. Writing only RGB instead of RGBA data for opaque images
2. Switching the compression from Best to Default
With 1, 2 is still a small size win and a huge speedup. See commits for detailed numbers.
=> LibGfx/PNGWriter+image: Make PNG writing 4-5x as fast while reducing output size 2-9%

Kernel/Bus/PCI/Device.cpp
This allows us to boot without putting the NVMe drive behind a i82801b11-bridge when using recent SeaBIOS versions with more than 4GiB RAM (context: #22720, #22710).
=> Kernel/PCI: Handle 64-bit MSI-X BARs

Userland/Applications/ImageViewer/ViewWidget.cpp
We need to do this to stop the animation timer and delete the current animation, otherwise the new image will be shown only for a moment before the previous animation continues.
=> ImageViewer: Call clear() in the ViewWidget before loading a new image

Userland/Libraries/LibThreading/BackgroundAction.cpp
This prevents a crash in ImageDecoder when it's closed before any image decoding requests have been made.
(cherry picked from commit 88176d4be2339108d9d54b8af62f5438f9c82f30)
---
https://github.com/LadybirdBrowser/ladybird/pull/834
=> Cherry-pick "LibThreading: Guard closing the background thread on the thread existing"

Userland/Applications/Terminal/main.cpp
Access to portal/config is no longer needed since the connection is already established earlier.
=> Terminal: Remove unveiling portal/config

Kernel/Arch/x86_64/SyscallEntry.cpp
The sysret instruction restores the rflags value from the r11 register. Before, we expected that the value in RegisterState::r11 is still the rflags value saved by syscall and therefore didn't copy RegisterState::rflags to r11 before the sysret.
But signal handlers and ptrace can change the value in RegisterState::r11 while we are handling a syscall, so we shouldn't assume that it still contains the saved rflags.
While handling a syscall the contents of RegisterState::rflags may also have been updated by e.g. ptrace in which case we should restore the updated rflags, not the original state on syscall entry.
=> Kernel/x86: Properly restore rflags in the syscall handler

Userland/Libraries/LibGfx/Bitmap.cpp, Userland/Libraries/LibGfx/Bitmap.h, Userland/Libraries/LibImageDecoderClient/Client.cpp, Userland/Libraries/LibImageDecoderClient/Client.h, Userland/Services/ImageDecoder/ConnectionFromClient.cpp, Userland/Services/ImageDecoder/ConnectionFromClient.h, Userland/Services/ImageDecoder/ImageDecoderClient.ipc
https://github.com/LadybirdBrowser/ladybird/pull/688 , and the 3rd commit from https://github.com/LadybirdBrowser/ladybird/pull/233
=> Cherry-pick "ImageDecoder: Pass decoded images as Gfx::Bitmap over IPC"

Userland/Libraries/LibELF/DynamicObject.cpp
In the current code, these are treated as if they were a bitmap. They are not, and (DT_REL & DT_RELA) is actually nonzero. This causes the linker to treat all sections as having addends, which is not correct.
=> LibELF: Fix incorrect treatment of DT_REL&DT_RELA

Ports/epsilon/patches/0001-Add-serenity-toolchain-information-and-makefile-file.patch, Ports/git/package.sh, Ports/ja2/patches/0001-Make-it-build-with-SDL-2-instead-of-1.2.patch, Ports/openssl/package.sh, Ports/sam/patches/0002-Manually-set-the-SDL2-include-path-and-library-dir.patch, Ports/sl/package.sh, Ports/stress-ng/package.sh, Toolchain/Patches/llvm/0001-clang-Add-support-for-SerenityOS.patch
So i went to compare behavior between GNU and Clang, and it seems that GNU has `/usr/local/lib` and `/usr/local/include` in the search paths by default, while Clang only has `/usr/lib` and `/usr/include`. Various packages are broken on Clang because of this, and while we could patch each one of them to include the proper paths manually, IMO a more centarlized approach is in order.
Incomplete list of packages that this concerns:
- SDL2 (this supersedes e128d8efef6031d6b9b6b8b6a33661eb036b5850 from #24891)
- libpng (upgraded in this MR)
- aria2 (zlib is an optional dependency and it wasn't linking properly with Clang builds)
Open to comments, I may be misunderstanding *something* here :)
=> Toolchain: Fix default library paths when building with clang

Ports/SuperTuxKart/package.sh
Removed redundant link flags from CXXFLAGS, which was necessary due to clang treating them as errors.
This depends on #24893 for some dependencies.
=> Ports/SuperTuxKart: Fix building on Clang

Toolchain/BuildClang.sh
It can now run on a system that has just ninja and cmake and Xcode
installed.
No intended behavior change.
=> Toolchain: On macOS, remove dependency on coreutils from BuildClang.sh

Userland/Applications/Presenter/Presentation.cpp, Userland/Applications/Presenter/PresenterWidget.cpp
This PR modifies the style for the `slide` class generated in `Presentation::render()` to hide the scrollbars.
Before:
After:
=> Presenter: Modify CSS to hide scrollbars

Userland/Services/RequestServer/ConnectionFromClient.cpp, Userland/Services/RequestServer/ConnectionFromClient.h
Previously we made one thread pool per ipc client, which is excessive and can eat up all the available fds very fast.
This is a manual port of commit 18499c4eac301db7e8915284f33766ca96cdeef2 from Ladybird.
=> RequestServer: Make the ThreadPool global

AK/Format.cpp
Just casting an integer type to a char pointer does not work on big endian.
Instead, the value needs to be properly converted into a char.
I uncommented the 7-bit ASCII check while at it. I think it's better to be safer than necessary to spot cases where high ASCII/UTF-8 support would be needed earlier.
-----
This is a copy of LadybirdBrowser/Ladybird#434 and has not been tested in SerenityOS, because I don't have a system running SerenityOS.
=> AK: Fix {:c} formatter for big-endian

AK/SIMDExtras.h, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp
Produces exactly the same output, but a bit faster.
The speedup is relatively bigger for worse compression:
image -o sunset_retro.png sunset_retro.bmp --png-compression-level 0
56.8 ms ±  1.5 ms ->  34.8 ms ± 0.9 ms (38.7% faster)
image -o sunset_retro.png sunset_retro.bmp --png-compression-level 1
84.6 ms ±  1.7 ms ->  64.2 ms ± 4.9 ms (24.1% faster)
image -o sunset_retro.png sunset_retro.bmp --png-compression-level 2
212.1 ms ±  2.5 ms -> 190.3 ms ± 1.6 ms (10.3% faster)
image -o sunset_retro.png sunset_retro.bmp --png-compression-level 3
671.4 ms ± 12.3 ms -> 646.5 ms ± 4.7 ms (3.7% faster)
Compression level 2 is the default, so about a 10% speedup in practice.
For comparison, `sips` needs 49.9 ms ± 3.0 ms to convert sunset_retro.bmp to sunset_retro.png, and judging from the output …
=> AK+LibGfx: Use SIMD for PNG score calculation

Tests/Kernel/TestExt2FS.cpp
This commit adds a new test case which carries out the following steps:
* write() to a block of an ext2 file, verify the write() was successful
* read() the same block back, verify the read() was successful
* verify that the data from the read() is identical to the data that was written in the write()
The test runs the above steps on the following blocks of an ext2 file:
* the first and last direct blocks
* the first and last singly indirect blocks
* the first and last doubly indirect blocks
* the first and last triply indirect blocks
=> Tests/Kernel: Add test for Ext2FS reads and writes

Meta/build-root-filesystem.sh
This directory was introduced with commit a43b115a6c99881c964daa5012cd076e82a7d72f and is no longer needed.
=> Meta: Remove /mod

Kernel/Tasks/Coredump.cpp
This unbreaks coredump generation, because we need to use the VFS root context of the crashed process and not of the FinalizerTask, as it will hold an empty VFS root context that is assigned to kernel processes.
=> Kernel: Create coredump by using the crashed process VFS root context

Userland/Applications/PDFViewer/OutlineModel.cpp
This PR fixes an off-by-one in the outline tree view, where the page number did not match the corresponding page in the document.
=> PDFViewer: Fix outline page number off-by-one

AK/SIMDMath.h, Tests/LibGfx/BenchmarkPNG.cpp, Tests/LibGfx/CMakeLists.txt, Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGShared.h
Takes
(cd Tests/LibGfx; ../../Build/lagom/bin/BenchmarkPNG)
from 59ms to 32ms on my system.
Adds AK::SIMD::bitselect() (modeled after the wasm SIMD equivalent),
and AK::SIMD::abs() implemented on top of it.
---
I'll wait for #24909 to land and will then rebase this on top of that once it's in.
=> LibGfx/PNGWriter+AK: SIMDify paeth predictor more

Kernel/Bus/USB/xHCI/xHCIController.cpp
The quirk previously only worked when USBLEGSUP was present and the BIOS owned the host controller.
=> Kernel/USB: Always check for the Intel xHCI port routing quirk

Userland/Libraries/LibCore/System.cpp, Userland/Libraries/LibWebView/ChromeProcess.cpp
Cherry-picks LadybirdBrowser/ladybird#914<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>
=> Cherry-pick "LibCore+LibWebView: Use Error::from_syscall to report get/setrlimit errors, and make non-fatal"

Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Cherry-picks LadybirdBrowser/ladybird#906<br><sub>Generated with [LBSync](https://github.com/circl-lastname/LBSync), did I do well?</sub>
=> Cherry-pick "LibWeb: Account for header size when reading MessagePort message payload"

Userland/Utilities/du.cpp
This change should help forcing basic alignment either on human readable sizes (or just raw number).
=> Utilities/du: Set minimum width when printing sizes

Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.h, Userland/Utilities/animation.cpp, Userland/Utilities/image.cpp, Userland/Utilities/pdf.cpp
Based on #24021.
To not make this need unbounded memory, convert PNGWriter to use a stream-based API first.
Here's wow.png as written by `Build/lagom/bin/animation -o wow.apng wow.gif`. I had to rename it to `.png`, else GitHub wouldn't let me attach it. Let's see if it shows up as animating. (Edit: It does!)
On my system, it takes `animation` 167ms to write this file and it's 606K. For comparison, writing wow.webp currently takes 88ms and produces a 255K file. (The webp file sadly can't be displayed inline on github though, https://github.com/orgs/community/discussions/5470.) The input wow.gif is 184K.
=> LibGfx/PNGWriter: Implement support for writing animated PNGs

Kernel/Arch/Processor.cpp, Kernel/Arch/Processor.h, Kernel/Arch/aarch64/Processor.h, Kernel/Arch/riscv64/Processor.h, Kernel/Arch/x86_64/Processor.cpp, Kernel/Arch/x86_64/Processor.h
This function was only used to verify that we are running in kernel mode. But it is pretty much impossible that we will ever end up in kernel code and actually are able to execute it in user mode. A lot of stuff must go completely wrong to end up in such a situation.
Getting the current privilege level is also impossible on RISC-V by design.
=> Kernel: Remove Processor::is_kernel_mode

CONTRIBUTING.md
From my previous interactions with the Serenity community, it was clear to me that this rule (for better or worse) was introduced by the author that wanted to focus on the code and not let an open-source operating system project be used as a 'political vehicle' and so as to not have to possess a political science degree to operate the project thought to be a technical exercise, like building a sandcastle.
For better or worse.
Unfortunately, the wording as-is can be interpreted as a dogwhistle in the direction of "keep politics out of tech", which has been present in communities like, as of recently, NixCPP - and this seems to have caused the problems that Serenity has been intentionally trying to avoid.
It might also disregard cases of technical arguments, arguments involving how people …
=> Documentation: Improve 'On ideologically motivated changes'

Userland/Libraries/LibCore/AnonymousBuffer.cpp, Userland/Libraries/LibCore/Command.cpp, Userland/Libraries/LibCore/Command.h, Userland/Libraries/LibCore/EventLoopImplementationUnix.h, Userland/Libraries/LibCore/MappedFile.cpp, Userland/Libraries/LibCore/ThreadedPromise.h
This PR contains small fixes in LibCore: more verbose return value in Command, adding missing include, closing some resources on error (manually and with ScopeGuards) and following clang-tidy hint.
=> Minor fixes in LibCore

Documentation/BuildInstructionsOther.md
`fuse2fs` comes from the `e2fsprogs` package in Fedora:
```
AlgorithmWolf@neon:~/Documents/github-com/serenity$ which fuse2fs
/usr/bin/fuse2fs
AlgorithmWolf@neon:~/Documents/github-com/serenity$ dnf provides /usr/bin/fuse2fs
[...]
e2fsprogs-1.47.0-5.fc40.x86_64 : Utilities for managing ext2, ext3, and ext4
: file systems
Repo        : @System
Matched from:
Filename    : /usr/bin/fuse2fs
e2fsprogs-1.47.0-5.fc40.x86_64 : Utilities for managing ext2, ext3, and ext4
: file systems
Repo        : fedora
Matched from:
Filename    : /usr/bin/fuse2fs
```
=> Documentation: Correct fuse2fs instructions for Fedora

Kernel/Bus/USB/Drivers/MassStorage/MassStorageDriver.cpp, Kernel/Bus/USB/USBPipe.cpp, Kernel/Bus/USB/USBPipe.h, Kernel/Bus/USB/USBTransfer.cpp, Kernel/Bus/USB/USBTransfer.h, Kernel/Devices/Storage/USB/BulkSCSIInterface.cpp, Kernel/Devices/Storage/USB/BulkSCSIInterface.h, Kernel/Devices/Storage/USB/SCSIComands.h, Kernel/Devices/Storage/USB/SCSIVitalProductData.h
This makes sending commands less repetitive
This is apparently what bootloaders do before using a USB storage device
so we should likely do so as well, especially when no BIOS is present,
like on riscv.
----
@spholz Still no clue why I don't need your signaling PR and timing hacks for x86 to work
Can you verify again that this makes xhci work for you on all platforms
=> Kernel/USB: Get MassStorage working on riscv

Userland/Applications/ImageViewer/ViewWidget.h, Userland/Applications/ImageViewer/main.cpp
This provides a way better experience when visualizing images. At some point, we should probably remove the option to control it from the GUI.
Old default on the left (Nearest Neighbor) new default on the right "Box Sampling".
=> ImageViewer: Set scaling mode's default value to "Box Sampling"

Kernel/API/Syscall.h, Kernel/Arch/x86_64/SyscallEntry.cpp, Kernel/Tasks/Thread.cpp
Using sysretq clobbers rcx and r11 as this instruction loads the rip and
rflags from those registers. This is fine for normal syscalls.
Signal dispatching works like this:
The kernel makes userspace jump to the signal trampoline when a signal
is dispatched. That trampoline then executes the sigreturn syscall after
calling the signal handler to continue executing the code before the
signal was dispatched.
Since e71c320154 the sigreturn syscall is done via the syscall
instruction (and int 0x82 support was removed in the next commit),
which causes the kernel to currently use sysretq to return to userspace.
But signals can happen at any time, not just during syscalls, so the
sigreturn syscall shouldn't clobber the contents of those registers when
returning to userspace.
=> Kernel/x86: Don't clobber rcx and r11 when handling signals

AK/CPUFeatures.cpp, AK/CPUFeatures.h, Userland/Libraries/LibCrypto/Cipher/AES.cpp, Userland/Libraries/LibCrypto/Cipher/AES.h
Related to:
- https://github.com/SerenityOS/serenity/pull/24522
- https://github.com/SerenityOS/serenity/pull/23958
- https://github.com/SerenityOS/serenity/issues/23949
- https://discord.com/channels/830522505605283862/843825120216743947
=> LibCrypto: Implement AES by using x86 intrinsics

Meta/Lagom/CMakeLists.txt
Useful for profiling deflate performance for enwik8.zip.
=> Meta: Make `unzip` buildable on lagom

AK/FuzzyMatch.cpp, Tests/AK/TestFuzzyMatch.cpp
This fixes cases where fuzzy matching would return a better score for
a different pattern than a needle perfectly matching the haystack.
As an example, when searching for "fire" in emojis:
- "Fire Engine" would have scored 168
- While "Fire" was only 160.
This patch makes the latter have the best possible score.
=> AK/FuzzyMatch: Return the best possible score for equality

Userland/Libraries/LibVT/Attribute.h, Userland/Libraries/LibVT/Terminal.cpp, Userland/Libraries/LibVT/TerminalWidget.cpp
This implements concealed and not concealed ANSI escape sequences: 8 and 28 respectively, as per https://en.wikipedia.org/wiki/ANSI_escape_code
=> LibVT: Handle concealed ANSI escape codes

Userland/Applications/Mail/AccountHolder.cpp, Userland/Applications/Mail/AccountHolder.h, Userland/Applications/Mail/InboxModel.cpp, Userland/Applications/Mail/InboxModel.h, Userland/Applications/Mail/MailWidget.cpp, Userland/Applications/Mail/MailWidget.h, Userland/Applications/Mail/MailboxTreeModel.cpp, Userland/Libraries/LibIMAP/Client.cpp, Userland/Libraries/LibIMAP/Client.h, Userland/Libraries/LibIMAP/Objects.h, Userland/Libraries/LibIMAP/Parser.cpp, Userland/Utilities/test-imap.cpp
This PR implements the standard behavior of displaying the mailbox name and parenthesized unseen message count in bold when the unseen message count is greater than zero.
=> LibIMAP+Mail: Show unseen message count for mailboxes

Userland/Utilities/shot.cpp
This allows the selection to appear above all normal window types including the task bar.
**Before** (taskbar never faded):
**After**:
=> shot: Use "popup" window type for screenshot area selection

AK/Platform.h
This bug was fixed on GCC trunk.
=> AK: Make workaround for broken coroutine type deduction more specific

.github/workflows/ci.yml, .github/workflows/serenity-template.yml
Don't run any tests on riscv64 for now, since some tests still fail (mostly due to missing generic AK/Math.h implementations).
=> CI: Build riscv64 in CI

Kernel/Syscalls/execve.cpp, Kernel/Tasks/Process.h
Instead, start by trying to read a buffer with size of Elf_Ehdr, and check it for the shebang sign. If it's indeed an executable with shebang then read again from the file, now with PAGE_SIZE size, which should suffice for finding the interpreter path.
However, if the executable is an ELF, we quickly validate it and then pass the preliminary buffer to the find_elf_interpreter_for_executable method.
That method calculates the last byte offset which is needed to read all of the program headers, so we don't just assume 4096 bytes is sufficient anymore. The same pattern is applied when loading the interpreter ELF main header and its program headers.
=> Kernel: Don't assume sizes of needed buffers early in the execve syscall

Base/usr/share/man/man1/du.md, Base/usr/share/man/man1/elfdeps.md, Userland/Utilities/du.cpp, Userland/Utilities/elfdeps.cpp
The purpose of this PR is to enable running of the following line in the shell:
`du -ch $(elfdeps -s /bin/BuggieBox)`
This is somewhat useful in assessment of what can be reduced further after #24815.
=> Utilities: Add an option to get total size in `du`, Add option to only print paths in `elfdeps`

Kernel/Arch/riscv64/linker.ld, Kernel/CMakeLists.txt
This PR does not depend on any of the other EFI Prekernel PRs.
=> EFI Prekernel (4/N): Kernel/riscv64: Kernel linker script preparations

Userland/Libraries/LibCompress/Deflate.h
I added this check in #18216 in commit 6d388249851e71.
Back then, I mentioned that `m_bit_codes` is only used for writing, but only added reading support. `CanonicalCode::from_bytes()` sets up both tables for reading and writing, so I needed the construction of the writing tables to not crash. This check in
`CanonicalCode::write_symbol()` was dead code back then though.
Later, #24700 added support for writing WebP files, and it can create canonical codes with more than 288 symbols. This works just fine, is now under test, and this check in `write_symbol()` isn't needed (and never was). So remove it again.
(I saw this in the profiler once, so maybe a tiny speedup for writing deflate-compressed data, but on the order of < 2%.)
=> LibCompress: Remove needless check

Kernel/Bus/PCI/Device.h
`VariadicFormatParams` only stores pointers to the parameters, so the `device.device_name()` parameter will dangle.
This fixes broken `dmesgln_pci` output on riscv64 GCC.
=> Kernel/PCI: Stop using a dangling pointer in dmesgln_pci

Kernel/Arch/riscv64/boot.S
First time contributor here. Just fixing a small comment  typo: "Fevice Tree" -> "Devicetree". :)
=> Kernel/riscv64: Fix typo in naming of Devicetree

AK/IPv6Address.h, Kernel/API/POSIX/sys/socket.h, Kernel/FileSystem/SysFS/Subsystems/Kernel/Network/Adapters.cpp, Kernel/Net/IPv4/Socket.cpp, Kernel/Net/Intel/E1000ENetworkAdapter.cpp, Kernel/Net/Intel/E1000NetworkAdapter.cpp, Kernel/Net/NetworkAdapter.cpp, Kernel/Net/NetworkAdapter.h, Kernel/Net/NetworkingManagement.cpp, Kernel/Net/NetworkingManagement.h, Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp, Kernel/Net/VirtIO/VirtIONetworkAdapter.cpp, Tests/AK/TestIPv6Address.cpp, Userland/Applications/SystemMonitor/NetworkStatisticsWidget.cpp, Userland/Utilities/ifconfig.cpp
This set of commits adds minimal IPv6 address support to network interfaces, as well as some userland support to query and set them. This is not compliant with even a single RFC: multiple addresses are not supported, and using a full IPv6 address for a network mask is pointless. Both will be addressed in further changes. This will be enough for initial link-local communications.
CC @famfo @sdomi 
IPv6Address can now determine the broad address
categories as defined in various RFCs, and check
if addresses belong to certain subnets.
Since we take a socket address with an address
type, this allows us to support setting an IPv6
address using an IPv4 socket without a
particularly hacky API. This deviates from Linux's
behavior (see
https://www.man7.org/linux/man-pages/man7/netdevice.7.html
) …
=> Kernel/Net+ifconfig+SystemMonitor: Add IPv6 address support to network interfaces

Kernel/Arch/riscv64/SafeMem.cpp, Tests/Kernel/CMakeLists.txt, Tests/Kernel/TestEFault.cpp
This PR causes the riscv64 kernel to no longer panic on failed (userspace) memory accesses!
=> Kernel/riscv64: Actually implement safe SafeMem functions

Kernel/Net/EthernetFrameHeader.h
This PR removes an obsolete gcc directive that is no longer required
=> Kernel/Net: Remove obsolete diagnostic trick

Userland/Libraries/LibCompress/Deflate.cpp, Userland/Libraries/LibCompress/Deflate.h
Symbols that need <= 8 bits hit a fast path as of #18075, but the slow path has done a full binary search over all symbols ever since this code was added in #2963. (#3405 even added a FIXME for doing this, but #18075 removed it.)
Instead of doing a binary search over all codes for every single bit read, this implements the Moffat-Turpin approach described at https://www.hanshq.net/zip.html#huffdec, which only requires a table read per bit.
hyperfine 'Build/lagom/bin/unzip ~/Downloads/enwik8.zip'
1.008 s ± 0.016 s  =>  957.7 ms ± 3.9 ms, 5% faster
Due to issue #25005, we can't peek the full 15 bits at once but have to read them one-by-one. This makes the code look a bit different than in the linked article.
I also tried not changing CanonicalCode::from_bytes() too much. It does 15 passes …
=> LibCompress: Speed up CanonicalCode::read_symbol() slow path

Userland/Utilities/image.cpp
Without this, image formats that can't sniff data can't be read by `image`.
The only such format we currently have is TGA, so this effectively allows `image` to read tga files.
---
TGALoader has a validate_before_create() method that
ImageDecoder::try_create_for_raw_bytes() calls instead of a sniff()
method. Maybe we should just have TGALoader::sniff() do what
validate_before_create() does? That's what BMPLoader does, and
bmp files only have two magic 'BM' bytes at file start. But TGA
doesn't have any magic bytes, so it kind of makes sense.
=> image: Guess mime type based on file extension

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
As written in the spec (B.2.2 Frame header syntax), only values between 0 and 4 are allowed.
This fixes oss-fuzz issue 68784:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68784
=> LibGfx/JPEG: Make sure sampling factors are in the allowed range

Userland/Libraries/LibLine/Editor.cpp, Userland/Libraries/LibLine/Editor.h, Userland/Libraries/LibLine/SuggestionManager.cpp
=> LibLine: Correctly slice completion substrings as unicode strings

Userland/Games/Chess/Chess.gml, Userland/Games/Chess/ChessWidget.cpp
When playing the chess game for the first time, the thing i found most interesting was the move history widget. My first thought was to try and copy the text to write it down somewhere else (at this point I didn't know you could copy it in a more "computer-readable" format with the Ctrl+C keybind) - I was very sad to find that this wasn't possible.
My second thought was to try and resize that weird looking column that changed my cursor when hovered. And, to my despair, it allowed me to! Creating a huge black gap between the board and the moves! Ahhh!
This PR fixes both issues, in a hopefully good way (code wise).
=> Chess: Some small usablity improvements

Kernel/Bus/USB/USBConfiguration.cpp, Kernel/Bus/USB/USBConfiguration.h, Kernel/Bus/USB/USBDevice.cpp, Kernel/Bus/USB/USBDevice.h, Kernel/Bus/USB/USBInterface.h
A lot of USB structures contain back pointers to their parents, so we need to be careful about how we copy them around, and update the back pointers as necessary.
---
Also Fix lsusb
=> Kernel: Be a bit more judicious about how we copy USB structures

Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
We added support for raw jpeg2000 codestreams in #24016.
=> LibGfx/JPEG2000: Remove an outdated comment

Kernel/Bus/USB/Drivers/HID/MouseDriver.cpp, Kernel/Bus/USB/Drivers/MassStorage/MassStorageDriver.cpp, Kernel/Bus/USB/UHCI/UHCIController.cpp, Kernel/Bus/USB/USBController.cpp, Kernel/Bus/USB/USBController.h, Kernel/Bus/USB/USBPipe.cpp, Kernel/Bus/USB/USBPipe.h, Kernel/Bus/USB/USBRequest.h, Kernel/Bus/USB/xHCI/xHCIController.cpp, Kernel/Bus/USB/xHCI/xHCIController.h, Kernel/CMakeLists.txt, Kernel/Debug.h.in, Kernel/Devices/Storage/USB/BulkSCSIInterface.cpp, Kernel/Devices/Storage/USB/BulkSCSIInterface.h, Kernel/Devices/Storage/USB/BulkSCSIStorageDevice.cpp, Kernel/Devices/Storage/USB/BulkSCSIStorageDevice.h, Meta/CMake/all_the_debug_macros.cmake, Meta/gn/secondary/Kernel/BUILD.gn
This makes our USB mass storage driver work with 3 of my USB drives (all SanDisk), which always STALL after a short packet (probably a weird firmware quirk, as it also happens on linux).
=> Kernel/USBMS: Handle STALLs

Userland/Libraries/LibGUI/Clipboard.cpp
This PR adds support for reading and writing metadata in `Clipboard::DataAndType:::from_json()` and `Clipboard::DataAndType::to_json()`, respectively.
The `metadata` field will only be set if there is metadata to store.
=> LibGUI: Read and write clipboard metadata to json

Tests/LibPDF/paths.pdf
Lovingly hand-written. Uses various line cap and line join styles.
Offsets fixed up with:
mutool clean Tests/LibPDF/paths.pdf Tests/LibPDF/paths.pdf
=> Tests: Add a (manual) test pdf for paths

Tests/LibWeb/Text/expected/css/revert-all.txt, Tests/LibWeb/Text/input/css/revert-all.html, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h
Not every value in a StyleProperties will be non-null by the time we perform `revert`, so let's make a specialized function for reverting a property instead of using the path that requires the value to be non-null.
(cherry picked from commit a10610a1cad56294089fc9457e713eb7083312cd)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/953
=> Cherry-pick "LibWeb: Don't crash on CSS `all: revert`"

Ladybird/AppKit/Application/ApplicationDelegate.h, Ladybird/AppKit/Application/ApplicationDelegate.mm, Ladybird/AppKit/UI/LadybirdWebView.h, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp, Ladybird/AppKit/UI/LadybirdWebViewBridge.h, Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/BrowserWindow.h, Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/PreferredMotion.cpp, Userland/Libraries/LibWeb/CSS/PreferredMotion.h, Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/ConnectionFromClient.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/PageClient.h, Userland/Services/WebContent/WebContentServer.ipc, Userland/Services/WebWorker/PageHost.cpp, Userland/Services/WebWorker/PageHost.h
This adds a motion preference to the browser UI similar to the existing ones for color scheme and contrast.
Both AppKit UI and Qt UI has this new preference.
The auto value is currently the same as NoPreference, follow-ups can address wiring that up to the actual preference for the OS.
(cherry picked from commit 099b77d60f6c30b4d533872fda29ea6d660ed358)
---
https://github.com/LadybirdBrowser/ladybird/pull/151
=> Cherry-pick "LibWeb: Add motion preference"

AK/TypeCasts.h, Base/res/html/misc/pseudo-elements.html, Tests/LibWeb/Text/expected/css/getComputedStyle-pseudo-element.txt, Tests/LibWeb/Text/input/css/getComputedStyle-pseudo-element.html, Userland/Applications/PDFViewer/PDFViewerWidget.cpp, Userland/Libraries/LibWeb/CSS/Parser/Helpers.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/DOM/Element.h, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp, Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp, Userland/Services/WebContent/ConnectionFromClient.cpp
https://github.com/LadybirdBrowser/ladybird/pull/994
https://github.com/LadybirdBrowser/ladybird/pull/1010 too, since else this doesn't build. And I can't merge that one first, since it seems to depend on changes in this PR.
It looks like in ladybird, 994 was landed, then 1010, then gcc got updated.
We apparently updated gcc first, so 994 doesn't build without 1010 due to new gcc, but 1010 (the fix for new gcc's) doesn't build without 994. So this PR here has a point in its commit sequence where things don't build with new-enough gcc's (like on one of our CI bots). That's unfortunate, but there isn't too much we can do about it. (The Ladybird repo has the same issue, it just didn't have a new-enough gcc on CI when it happened.)
=> Cherry-pick "Implement getComputedStyle() for pseudo-elements"

Ladybird/AppKit/UI/Event.mm, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/WebContentView.cpp, Userland/Libraries/LibWeb/DOM/EventTarget.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/EventHandler.h, Userland/Libraries/LibWeb/Page/InputEvent.cpp, Userland/Libraries/LibWeb/Page/InputEvent.h, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWeb/UIEvents/KeyCode.h, Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.h, Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp, Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
Cherry-picks most of the second commit from https://github.com/LadybirdBrowser/ladybird/pull/86, which will make future cherry-picks easier.
No intended behavior change.
=> LibWeb: Add a UIEvents/KeyCode.h forwarding header, and cherry-pick using Web::UIEvents::KeyCode in LibWeb

Kernel/Net/LocalSocket.cpp
These options are generally used for QoS tuning by Apache, NGINX, MySQL etc. (insert anything that scales here)
=> Kernel/Net: Implement SO_SNDBUF and SO_RCVBUF for AF_LOCAL

Kernel/Net/ICMP.h, Kernel/Net/NetworkTask.cpp
this may be a bit opinionated, but I think it improves readability by quite a lot + the cast is safer :)
---
This change fixes up handle_icmp to use a bit_cast instead of a reinterpret_cast, which got used due to legacy reasons.
A few dbgln's got turned into dbgln_if's, in accordance with the behavior throughout the rest of the file.
Furthermore, we revert a part of commit ad73adef5d2f8 which introduced inconsistency between struct names. There's no ICMPv4, only ICMP and ICMPv6. Thus, it makes more sense to revert the ICMPv4Type back to ICMPType.
We also remove the FIXME about the TTL - as per RFC1700, TTL of 64 is a recommended default, so the current behavior can stay.
=> Kernel/Net: Cleanup the ICMP handler

Userland/Libraries/LibGfx/Bitmap.cpp, Userland/Libraries/LibGfx/Bitmap.h, Userland/Services/WindowServer/Compositor.cpp
Up until now, the only way to create a Bitmap with a non-standard pitch was to use the wrapper; This was unsuitable for back and temp buffers within WindowServer.
This commit adds another optional parameter for specifying the pitch in a backwards-compatible way. The change in WindowServer will likely fix most cases of screen misalignment when running on baremetal.
=> WindowServer+LibGfx: Improve non-standard bitmap pitch handling

Documentation/BuildInstructions.md
This was missing at least llvm-19-dev. Also,
mention the LLVM apt repositories.
=> Documentation: Document all deps for a Clang build on Debian/Ubuntu

Userland/Utilities/du.cpp
Certain virtual filesystems (RAMFS) always report 0 used blocks, even for files that are not empty. In this case, we should fall back to reporting the apparent size, as showing zero is somewhat misleading.
Before:
After:
Alternatively, we could make RAMFS report some fake block size. I'm open for discussion and suggestions.
=> Utilities/du: Fix displaying size on devices that don't report blocks

Tests/Kernel/crash.cpp, Tests/LibC/TestAbort.cpp, Userland/Libraries/LibC/stdlib.cpp
`__builtin_trap()` gets compiled to a breakpoint instruction on
riscv64 GCC, aarch64 GCC, and aarch64 Clang.
=> Tests/LibC+LibC+crash: Don't assume `__builtin_trap` causes SIGILL

Kernel/Syscalls/socket.cpp
This goes in accordance with OpenBSD specification
https://man.openbsd.org/pledge.2#inet
=> Kernel/syscalls: Require `inet` promise for AF_INET6 domain

Userland/Libraries/LibWeb/SVG/SVGRectElement.cpp
No behavior change at the moment, but once we add support for linecaps for SVG paths, this will prevent stroked rects with a wider stroke from missing one corner.
=> LibWeb: Always close the path created for an SVG <rect>

Userland/Applications/Magnifier/MagnifierWidget.cpp, Userland/Applications/ThemeEditor/PreviewWidget.cpp, Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibGfx/Painter.h, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerCPU.cpp, Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
Painter always has a target bitmap, so let's return a reference.
(cherry picked from commit f42c18bc4c4a5d49fccbfab996bf04d77476b366; amended to resolve conflicts in Painter due to us having more APIs, and to update code no longer in ladybird: DisplayListPlayerCPU, and Magnifier and ThemeEditor)
---
Cherry-picks another commit from https://github.com/LadybirdBrowser/ladybird/pull/50
=> Cherry-pick "LibGfx: Make Painter::target() return a Bitmap&"

Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp, Meta/Lagom/Tools/CodeGenerators/LibTextCodec/GenerateEncodingIndexes.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateAriaRoles.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMathFunctions.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GeneratorUtil.h
This cherry-picks the CodeGenerators changes from the second commit in https://github.com/LadybirdBrowser/ladybird/pull/626
We'll want to enable -Wmissing-declarations (gcc) / -Wmissing-prototypes (lagom) for Lagom too, but that can happen in a separate PR.
(cherry picked from commit c62240aa80dceddd7e6ba5bf779a56c84ab8c624; amended to remove half of the changes. Many of them were in ladybird-only code. Changed commit message.)
=> Meta: Cherry-pick lagom -Wmissing-declarations prep

Userland/Libraries/LibAccelGfx/Painter.cpp, Userland/Libraries/LibAccelGfx/Painter.h, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/TextLayout.cpp, Userland/Libraries/LibGfx/TextLayout.h, Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp, Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h, Userland/Libraries/LibWeb/Layout/LineBox.cpp, Userland/Libraries/LibWeb/Layout/LineBox.h, Userland/Libraries/LibWeb/Layout/LineBoxFragment.h, Userland/Libraries/LibWeb/Layout/LineBuilder.cpp, Userland/Libraries/LibWeb/Layout/LineBuilder.h, Userland/Libraries/LibWeb/Layout/TextNode.cpp, Userland/Libraries/LibWeb/Layout/TextNode.h, Userland/Libraries/LibWeb/Painting/AffineDisplayListPlayerCPU.cpp, Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp, Userland/Libraries/LibWeb/Painting/DisplayList.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerCPU.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerGPU.cpp, Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp, Userland/Libraries/LibWeb/Painting/PaintableFragment.h, Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
The ChunkIterator now limits a chunk to using only one font (before, it was possible to have a chunk with >1 font, when `unicode-range` CSS property is used).
This change allows us to reduce some complexity in the text shaping and painting code and makes us compatible with the APIs in Skia and HarfBuzz.
(cherry picked from commit 7181c3f2ea5fba73e77d98acbf9e46640b4a9015, minorly amended to fix conflicts caused by:
* Our VectorFont not being renamed to Typeface
* Us cherry-picking https://github.com/LadybirdBrowser/ladybird/pull/502 first
* Us still having bitmap fonts, and hence needing glyph_spacing()
Also amended for:
* AffineDisplayListPlayerCPU changes
* Removing pure virtuals for glyph_id_for_code_point and glyph_id_for_code_point in Font.h again since we still have BitmapFont which …
=> Cherry-pick "Everywhere: Limit layout text fragments to use one font for all glyphs"

Tests/LibWeb/Ref/reference/text-overflow.html, Tests/LibWeb/Ref/text-overflow.html, Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Identifiers.json, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/Node.cpp
https://github.com/LadybirdBrowser/ladybird/pull/813
=> Cherry-pick "CSS: Add support for text-overflow property"

Tests/LibWeb/Layout/expected/css-counters/counters-function-single-argument.txt, Tests/LibWeb/Layout/input/css-counters/counters-function-single-argument.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/887.
(cherry picked from commit 5abe246385dc70e9b69426cd19302d28b7d869d0)
---
Cherry-picks https://github.com/LadybirdBrowser/ladybird/pull/890
=> LibWeb/CSS: Treat counters() function with 1 argument as invalid

Tests/LibWeb/Ref/text-overflow.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Fixes out of bound access to glyph run when `last_glyph_index` is 0.
Fixes crashing on https://github.com/LadybirdBrowser/ladybird/pulls
(cherry picked from commit fa605ef22577d92bbfc3f4a809bb1b4072bb0048)
---
https://github.com/LadybirdBrowser/ladybird/pull/944
=> Cherry-pick "LibWeb: Fix OOB access in "text-overflow: ellipsis" clip"

Tests/LibWeb/Text/expected/HTML/HTMLInputElement-invalid-time-digits.txt, Tests/LibWeb/Text/input/HTML/HTMLInputElement-invalid-time-digits.html, Userland/Libraries/LibWeb/HTML/Dates.cpp
(cherry picked from commit fe42e2719f1ba92e04a530ca3910a7c8bfbbf1af)
---
https://github.com/LadybirdBrowser/ladybird/pull/1150
=> Cherry-pick "LibWeb: Don't crash when parsing `HTMLInputElement` invalid time values"

Tests/LibWeb/Layout/expected/grid/grid-placement-shorthand-single-custom-ident.txt, Tests/LibWeb/Layout/input/grid/grid-placement-shorthand-single-custom-ident.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h
According to https://www.w3.org/TR/css-grid-2/#placement-shorthands when setting the 'grid-row' and 'grid-column' shorthand property to a single <custom-ident> value, both 'grid-row-start'/'grid-column-start' and 'grid-row-end'/'grid-column-end' should be set to that <custom_ident>.
(cherry picked from commit 3e92ec80f3873bb81cbc8b0dc93bb3a6a145172c)
---
https://github.com/LadybirdBrowser/ladybird/pull/1214
=> Cherry-pick "LibWeb: Set correct longhand values when using grid-placement shorthand"

Ports/SDL2/package.sh, Ports/xmp-cli/patches/0001-Add-support-for-Serenity-LibAudio.patch
Due to the LibCoreBasic split it is now needed to add -lcorebasic when the EventLoop is used, this will fix at least 2 ports from building: SDL2 and xmp-cli
=> Ports: Link LibCoreBasic when included

Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
Sometimes applications will try to destroy the framebuffer twice causing a crash.
I noticed the crash on RetroArch when changing video settings and loading content.
=> Ports/SDL2: Fix crash when closing an SDL2 window

AK/Math.h, Tests/AK/CMakeLists.txt, Tests/AK/TestAKMath.cpp
(1) remove UB by only taking the integer fast path if the exponent fits in the i64 integer limits.
(2) use exponentiation by squaring for the integer fast path, thereby actually making it fast (and not time out on the new tests...)
=> AK: pow() with less UB and more performance

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Keywords.json, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Painting/SVGPathPaintable.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
SVGGraphicsElement then goes ahead and does nothing with it for now.
(cherry picked from commit cc0cfd044b3a04c021f8810f7e96d98a05f7146a; amended to fix minor conflict in getComputedStyle-print-all.txt)
---
https://github.com/LadybirdBrowser/ladybird/pull/1714 (which is the 2nd commit of #25045 really).
=> Cherry-pick "LibWeb: Add stroke-linecap attribute and plumb it to SVGGraphicsElement"

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
(cherry picked from commit b4d996680a24e6ecb8d0dc755e1208838ee88601)
---
https://github.com/LadybirdBrowser/ladybird/pull/1398
=> Cherry-pick 'LibJS: Allow date format "YYYY-M-DD"'

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
This allows date strings like "01 February 2013" to be parsed. auth0.com also loads now because of this :^)
Add test for date parsing
(cherry picked from commit 179641a297ab0b4bafcce3a6361be2c4ed0c51ea)
---
https://github.com/LadybirdBrowser/ladybird/pull/1466
=> Cherry-pick "LibJS: Add extra date format "d B Y""

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Seen on https://www.skaping.com/valloire/galibier.
(cherry picked from commit c0102aa818b98d4d608e195837aefdb698540427)
---
https://github.com/LadybirdBrowser/ladybird/pull/1804
=> Cherry-pick 'LibJS: Support date strings of the form "Wed Apr 17 2019 23:08:53""'

Meta/Lagom/CMakeLists.txt, Meta/Lagom/Tools/CodeGenerators/GMLCompiler/CMakeLists.txt, Userland/Libraries/LibCore/CMakeLists.txt, Userland/Libraries/LibIDL/CMakeLists.txt
https://github.com/LadybirdBrowser/ladybird/pull/257, commits 1 and 4. (Plus an original GMLCompiler commit to keep things building.)
This is a dependency of #25119 (or otherwise, we'd have to build LibTextCodec earlier too, which is also an option.)
=> Cherry-pick two commits from https://github.com/LadybirdBrowser/ladybird/pull/257

Tests/LibTextCodec/TestTextEncoders.cpp, Userland/Libraries/LibTextCodec/Encoder.cpp, Userland/Libraries/LibTextCodec/Encoder.h
They are similar to their already existing decoder counterparts.
(cherry picked from commit 96de4ef7e00f44b3f7913db221625940da7f561a)
---
https://github.com/LadybirdBrowser/ladybird/pull/1704
=> Cherry-pick "LibTextCodec: Add SingleByteEncoders"

Kernel/Net/Intel/E1000NetworkAdapter.cpp
Fix incorrect casts of (e1000_rx_desc*) to (e1000_tx_desc*) in functions related to frame receive path.
Previous code appears to work because only fields common to both the TX and RX descriptor types are used in the affected code and happen to be at the same offset inside the packed structs.
=> E1000NetworkAdapter: Fix incorrect cast of RX buffer descriptor pointer

Meta/Lagom/Contrib/MacPDF/MacPDFOutlineViewDataSource.mm, Userland/Applications/FileManager/PropertiesWindow.cpp, Userland/Libraries/LibPDF/Document.cpp, Userland/Libraries/LibPDF/Document.h
It returns UTF-8 text, so make that clear in its return type,
and propagate this to clients.
This part has no behavior change.
Also make it fallible.
TextCodec does not return Error for invalid UTF-8 or UTF-16, so
this only propagates allocation errors. No expected behavior change
in practice even for invalid PDFs. Removes three calls to
`release_value_but_fixme_should_propagate_errors()`, mostly for
aesthetic reasons.
=> LibPDF+Clients: Make Document::text_string_to_utf8() return String

Meta/gn/secondary/Userland/Libraries/LibTextCodec/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibURL/BUILD.gn
4167d1214aa LibTextCodec+LibURL: Implement `utf-8` and `euc-jp` encoders
=> Meta: Port recent changes to the GN build

AK/Utf16View.cpp, AK/Utf16View.h, Tests/AK/TestUtf16.cpp, Userland/Libraries/LibWeb/DOM/CharacterData.h, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
https://github.com/LadybirdBrowser/ladybird/pull/901 (except it's missing the actual "make go fast" part – but we can do that later.)
=> Cherry-pick "AK+LibWeb: Avoid allocating UTF-16 strings only the UTF-16 length is needed", kinda

Tests/LibPDF/CMakeLists.txt, Tests/LibPDF/TestPDF.cpp, Tests/LibPDF/offset.pdf, Userland/Libraries/LibPDF/DocumentParser.cpp
History:
* https://github.com/SerenityOS/serenity/commit/72f693e9ed6b106e0760a3b1869f92d3267ddd41 from https://github.com/SerenityOS/serenity/pull/6974 added the initial XRefTable. Here, -1
was used for byte_offset of invalid entries. has_object() compared
byte_offset to -1.
* https://github.com/SerenityOS/serenity/commit/e23bfd72521258921978134bfef88285dcb2f9ec from https://github.com/SerenityOS/serenity/pull/7675 added invalid_byte_offset (equal to
LONG_MAX) and initialized byte_offset with it, but forgot to update
has_object(). has_object() still compared to -1, so has_object would
now never return false.
* https://github.com/SerenityOS/serenity/commit/d1bc89e30b962d2e4805c0fcc7f2caf4d51267b7 from https://github.com/SerenityOS/serenity/pull/16150 added …
=> LibPDF: Don't fail on files where object 0 is not in the xref table

Tests/LibWeb/TestConfig.ini
Mac CI is currently timing out. Downstream disabled all worker tests; @trflynn89 says that helped there. Let's try doing that over here too.
https://github.com/LadybirdBrowser/ladybird/pull/297
https://github.com/LadybirdBrowser/ladybird/pull/1305
https://github.com/LadybirdBrowser/ladybird/pull/1567
https://github.com/LadybirdBrowser/ladybird/pull/1626 (even though we don't have the commit that motivated that yet)
First commit of https://github.com/LadybirdBrowser/ladybird/pull/1627
=> Cherry-pick changes to Tests/LibWeb/TestConfig.ini

Userland/Libraries/LibWeb/Page/EventHandler.cpp
This patch implements basic keyboard functionality for page scrolling and history traversal.
(cherry picked from commit 1759b82114febe82b1da4ea35c2d3657555f631b)
---
https://github.com/LadybirdBrowser/ladybird/pull/340
=> Cherry-pick "LibWeb: Scroll page and nav history with keyboard"

Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
The SDL_ShowMessageBox function was already implemented but was forgot to be referenced in the video bootstrap
=> Ports/SDL2: Add missing ShowMessageBox reference

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
(cherry picked from commit cca03e484be96a3d833beff5834416c3c07dfbb2)
---
https://github.com/LadybirdBrowser/ladybird/pull/949
=> Cherry-pick "LibWeb: Also invalidate placeholder style on focus change"

Ports/RetroArch/patches/0002-Add-strlcat.patch, Ports/RetroArch/patches/0003-Disable-pthread_attr_setschedpolicy.patch, Ports/RetroArch/patches/0004-Use-SDL-software-instead-of-hardware-rendering.patch, Ports/RetroArch/patches/0005-Set-default-options-for-SerenityOS.patch, Ports/RetroArch/patches/0006-Enable-unix-platform.patch, Ports/RetroArch/patches/ReadMe.md
This will make arguments from shell (like `--help`) work.
The commit also changes other patches' hashes but that is probably because the patches weren't updated when RetroArch was updated to v1.19.1
=> Ports/RetroArch: Enable unix platform

Meta/run.py
This restores the behaviour to that of the old run.sh and allows the spice agent to _somewhat_ work again, though file transfers are currently fairly unreliable.
=> Meta/run.py: Prefer `spicevmc` over `qemu-vdagent`

Userland/Applications/AnalogClock/AnalogClock.cpp, Userland/Applications/PixelPaint/HistogramWidget.cpp, Userland/Applications/PixelPaint/ImageEditor.cpp, Userland/Applications/PixelPaint/Tools/GradientTool.cpp, Userland/Applications/SystemMonitor/GraphWidget.cpp, Userland/Demos/LibGfxDemo/main.cpp, Userland/Games/Chess/ChessWidget.cpp, Userland/Libraries/LibGUI/TabWidget.cpp, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibGfx/Painter.h, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibWeb/Painting/AffineDisplayListPlayerCPU.cpp
No behavior change. Follow-up to #25065.
=> LibGfx+Clients: Remove Painter::{WindingRule,LineStyle} forwarding declarations

Userland/Utilities/cat.cpp
Before, when we tried to use cat -n, if there were unicode characters we would crash. This was due to us outputting bytes one at a time using the out function. However, when the out function runs into a unicode byte on its own, it has no idea what to do with it.
=> cat: Allow for multibyte characters when numbering lines

Userland/Libraries/LibGfx/Path.cpp
Previously, when stroking closed paths, we'd create a single
path where the inner stroke and the outer stroke were connected
with round linecaps. Since we currently only support round line joins,
this looked ok.
Now, we don't draw caps when stroking closed paths, but instead
generate a closed inner path and an independent closed outer path.
This has the advantage that it produces slightly less geometry, and
it's a prerequisite for implementing non-round line joins.
No visual difference.
=> LibGfx: Clean up geometry when stroking closed paths

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
These are legacy name aliases for the properties without the 'grid-' prefix. See https://drafts.csswg.org/css-align-3/#gap-legacy
(cherry picked from commit c79f261bec40a61373d45508c1935f839454c95d)
---
https://github.com/LadybirdBrowser/ladybird/pull/1785
=> Cherry-pick "LibWeb/CSS: Mark grid-[gap, column-gap, row-gap] properties as aliases"

Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp, Userland/Libraries/LibJS/Runtime/Utf16String.cpp, Userland/Libraries/LibJS/Runtime/Utf16String.h, Userland/Libraries/LibJS/Runtime/VM.h
We were already caching UTF-8 and byte strings, so let's add a cache for UTF-16 strings as well. This is particularly profitable whenever we run regular expressions, since the output of regex execution is a set of UTF-16 strings.
Note that this is a weak cache like the other JS string caches, meaning that strings are removed from the cache as they are garbage collected.
This avoids billions of PrimitiveString allocations across a run of WPT, significantly reducing GC activity.
(cherry picked from commit 206479b2b5fc2641a619eb0d05c1185d869ef844)
---
https://github.com/LadybirdBrowser/ladybird/pull/1948
=> Cherry-pick "LibJS: Cache UTF-16 strings on the VM"

Tests/LibWeb/Ref/css-color-functions.html, Tests/LibWeb/Ref/reference/css-color-functions-ref.html, Userland/Libraries/LibWeb/CSS/StyleValues/CSSRGB.cpp
Example of the difference:
50 * 2.55      --> 127.4999 --> round towards +∞ --> 127
50 * 255 / 100 --> 127.5000 --> round towards +∞ --> 128
Now, 9 failing WPT tests in /css/css-color/ pass.
(cherry picked from commit 6c3ecf6a342cbc0a83c1deac89e1a7edf6d959c4; amended because css-color-functions.html is a reftest for us, not a screenshot test)
---
https://github.com/LadybirdBrowser/ladybird/pull/1857
=> Cherry-pick "LibWeb/CSS: Tweak in CSSRGB::to_color() to avoid floating point errors"

Kernel/Devices/HID/PS2/MouseDevice.cpp, Kernel/Devices/HID/PS2/MouseDevice.h
When using spice with `virt-viewer` the mouse rarely works on the first initialization attempt. Simply retrying a few times makes it succeed most of the time (although it can still fail, it's pretty rare now).
=> Kernel: Try to reset the PS2 mouse multiple times before giving up

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
Loading Ladybird on Github results in 37 debug logs about being unable to parse an empty Date string. This log is intended to catch Date formats we do not support to detect web compatability problems, which makes this case not particuarly useful to log.
Instead of trying to parse all of the different date formats and logging that the string is not valid, let's just return NAN immediately.
(cherry picked from commit ee35e93eb23996923db12f39ba17ece61da4e39b)
---
https://github.com/LadybirdBrowser/ladybird/pull/1756
=> Cherry-pick "LibJS: Early return from Date string parsing on empty string"

Userland/Applications/DisplaySettings/MonitorSettingsWidget.cpp, Userland/Applications/DisplaySettings/MonitorSettingsWidget.h, Userland/Libraries/LibEDID/EDID.cpp
Before, the DisplaySettings app hardcoded a bunch of resolutions without checking what the monitor supports. This PR makes it so that they're parsed directly from the selected monitor's EDID, which up to this point had only been used for getting the monitor's name.
Additionally, it changes the way LibEDID handles incorrect or truncated data. Before this, the data would be deemed as invalid and thrown out unless it could parse all established timings, standard timings, detailed timings, short video descriptors and coordinated video timings. This, coupled with the buffer being seemingly too small to capture the entire EDID descriptor that QEMU provides, would result in the parser failing to provide any resolutions at all no matter what. 
For now, I made it so that failing to parse the …
=> DisplaySettings+LibEDID: Automatically generate monitor resolution list

Userland/Services/SpiceAgent/SpiceAgent.cpp, Userland/Services/SpiceAgent/SpiceAgent.h
Previously, the spice agent would attempt to read all chunks for a message as soon as the spice chardev became readable. This generally was fine for small messages but unreliable for large transfers such as files. If at any point a read failed, the entire message would be abandoned, then when notified that there's more data, the agent would try to read it as a new chunk/message. If the data was the rest of a file transfer it would end up parsing that as a chunk header, and crashing when it tried to allocate a random amount of bytes.
This is resolved by making the agent only read what's available and keeping track of how much data it's read. Then only once there's a complete message does it attempt to handle it.
=> SpiceAgent: Make message handling much more reliable

Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/Node.cpp
This will let us start to begin applying this during text shaping.
(cherry picked from commit da42c19cb66656e3b2531c29542b4bb27b21ec94)
---
https://github.com/LadybirdBrowser/ladybird/pull/1860
=> Cherry-pick "LibWeb: Apply the word-spacing css property to Node"

Kernel/Arch/riscv64/Processor.h, Kernel/Arch/riscv64/boot.S, Tests/Kernel/crash.cpp
This option is now available on both our toolchains.
=> Kernel/riscv64+crash: Use '.option arch'

Documentation/Browser/ProcessArchitecture.md
The commit removes an unnecessary newline character in the documentation that was breaking the bold formatting.
(cherry picked from commit 23428c0b9ace27e989ee90109d336852786e3155)
---
https://github.com/LadybirdBrowser/ladybird/pull/29
=> Cherry-pick "Documentation: Remove unnecessary newline in documentation"

Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/BrowserWindow.h, Ladybird/Qt/Tab.cpp, Ladybird/Qt/Tab.h
Previously, line box borders were only set for the current tab when the option was toggled.
(cherry picked from commit d480355b573a589ac4ddd10270da9fc495d146bd)
---
https://github.com/LadybirdBrowser/ladybird/pull/40
=> Cherry-pick "Ladybird/Qt: Draw line box borders for all tabs when option is toggled"

Tests/LibWeb/Text/expected/DOM/getElementsByClassName-multiple.txt, Tests/LibWeb/Text/input/DOM/getElementsByClassName-multiple.html, Userland/Libraries/LibWeb/DOM/ParentNode.cpp
(cherry picked from commit 96c0cbf584e99d5c1c9b894d0317d8c2887ade83)
---
https://github.com/LadybirdBrowser/ladybird/pull/947
=> Cherry-pick "LibWeb: Ensure `ParentNode.getElementsByClassName()` matches all classes"

Tests/LibWeb/Text/data/bad.xml, Tests/LibWeb/Text/expected/XML/error-page.txt, Userland/Libraries/LibXML/Parser/Parser.cpp, Userland/Libraries/LibXML/Parser/Parser.h
(cherry picked from commit c0f30f31d109ba1420421b3de9e47560fcb3e65f)
---
https://github.com/LadybirdBrowser/ladybird/pull/943
=> Cherry-pick "LibXML: Include line and column numbers in parse error messages"

Tests/LibWeb/Text/expected/quirks-mode-case-insensitive-class-selector.txt, Tests/LibWeb/Text/input/quirks-mode-case-insensitive-class-selector.html, Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
This align our implementation with the CSSWG Selectors Level 4 specification.
(cherry picked from commit 82ed2534776406872337b34ddf2dfaa0b3332c32)
---
https://github.com/LadybirdBrowser/ladybird/pull/937
=> Cherry-pick "LibWeb: Match class selectors case insensitively in quirks mode"

Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp, Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp, Userland/Libraries/LibWasm/Parser/Parser.cpp, Userland/Libraries/LibWasm/Printer/Printer.cpp, Userland/Libraries/LibWasm/Types.h, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp, Userland/Utilities/wasm.cpp
Remove `for_each_section_of_type` in favor of making the module's sections defined as distinct fields. This means it is no longer possible to have two of the same section (which is invalid in WebAssembly, for anything other than custom sections).
(cherry picked from commit 23cfee22058880f8251d9627e7f6640d466c37a9)
---
https://github.com/LadybirdBrowser/ladybird/pull/895
=> Cherry-pick "LibWasm: Clean up module sections API"

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/Node.cpp
To avoid expensive lookups, we now cache a weak pointer from document to the last known node navigable. Before using the cache, we validate that the document is still the navigable's active document.
(cherry picked from commit e746b2b133758b3552ae07941cc6d14332c64d59)
---
https://github.com/LadybirdBrowser/ladybird/pull/936
=> Cherry-pick "LibWeb: Cache the Document's node navigable when possible"

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h
Instead of throwing all pseudo-element rules in one bucket, let's have one bucket per pseudo-element.
This means we only run ::before rules for ::before pseudo-elements, only ::after rules for ::after, etc.
Average style update time on https://tailwindcss.com/ 250ms -> 215ms.
(cherry picked from commit 87056ee0d2505c26149a36fc5b69446504b172bb)
---
https://github.com/LadybirdBrowser/ladybird/pull/1362
=> Cherry-pick "LibWeb: Bucket CSS rules by pseudo-element"

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSKeyword.cpp, Tests/LibWeb/Text/expected/css/revert-layer.txt, Tests/LibWeb/Text/input/css/revert-layer.html, Userland/Libraries/LibWeb/CSS/CSSStyleValue.h, Userland/Libraries/LibWeb/CSS/Keywords.json, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSKeywordValue.h
With the introduction of the cascade layer, the 5th CSS-wide keyword, `revert-layer`, has been added.
(cherry picked from commit bea7eec5183a816a100d190e409a622f429d7405)
---
https://github.com/LadybirdBrowser/ladybird/pull/1371
=> Cherry-pick "LibWeb/CSS: Implement revert-layer"

Ladybird/Qt/BrowserWindow.cpp
On my system `QKeySequence::StandardKey::ZoomIn` includes both `Ctrl++` and `Ctrl+=`, so explicitly adding the secondary `Ctrl+=` shortcut ourselves results in an ambiguous shortcut error message being shown.
According to the Qt documentation the key bindings returned by `QKeySequence::StandardKey::*` are platform specific, so we may still need to add the secondary shortcut on some systems. Therefore, we now check whether our secondary shortcut is already in the shortcut list before adding it.
(cherry picked from commit ebfb847d347b40e377900658795442797c7e14e9)
---
https://github.com/LadybirdBrowser/ladybird/pull/122
=> Cherry-pick "UI/Qt: Ensure we don't add the same zoom shortcut key more than once"

Userland/Libraries/LibWeb/DOM/Range.cpp
This fixes an issue where clearing the find in page query would not always visually clear the selection.
(cherry picked from commit 0b33331f3678eb69bc3448949dfc2c1e1e7671e6)
---
https://github.com/LadybirdBrowser/ladybird/pull/263
=> Cherry-pick "LibWeb: Ensure a repaint occurs when the current selection is cleared"

Ladybird/Qt/LocationEdit.cpp
The placeholder text is there to prompt the user as to what could be added in the address bar. The current text tells the user that they can "Search or enter web address" even when the search setting is disabled. When attempting to "Search" the user is instead sent to page ":", with an error in the console:
WebContent(575249): (FIXME) Don't know how to navigate to :
This patch fixes this by checking whether the search feature is enabled and setting the placeholder appropriately. This provides a slightly better user experience.
Closes #132
(cherry picked from commit cb657a038f0c0f598993d6c3c3b8ff21f344ac40)
---
https://github.com/LadybirdBrowser/ladybird/pull/133
=> Cherry-pick "UI/Qt: Update placeholder text if search disabled"

Userland/Libraries/LibJS/Console.cpp
Corresponds to the change in this PR:
https://github.com/whatwg/console/pull/241
(cherry picked from commit 99c66f49fb35b8415e13d3bef638487fb8c7238f)
---
https://github.com/LadybirdBrowser/ladybird/pull/2076
=> Cherry-pick "LibJS: Update console spec's use of "Type()" -> "is a""

Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/LocationEdit.cpp, Ladybird/Qt/LocationEdit.h, Ladybird/Qt/Tab.cpp, Ladybird/Qt/Tab.h
The URL is now not shown when a new tab is initially activated until the location bar loses focus. This allows the user to see the location bar placeholder text when opening a new tab. It also makes it easier to paste URLs into the location bar after opening a new tab.
(cherry picked from commit 808784092c552518fe1d9a83543c40cd13e8ac09)
---
https://github.com/LadybirdBrowser/ladybird/pull/137
=> Cherry-pick "UI/Qt: Don't show URL when a new tab is initially focused"

Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/FindInPageWidget.cpp, Ladybird/Qt/FindInPageWidget.h, Ladybird/Qt/Tab.cpp, Ladybird/Qt/Tab.h
This commit adds the standard shortcuts for the Find Next and Find Previous buttons on the find in page panel. These shortcuts are usually F3 and Shift+F3 respectively, although Qt standard shortcuts may vary across platforms.
(cherry picked from commit 88d134a4dab6ff272ff73b5de6f40d4295577259)
---
https://github.com/LadybirdBrowser/ladybird/pull/158
=> Cherry-pick "UI/Qt: Add standard shortcuts for find in page actions"

Userland/Libraries/LibWebView/SourceHighlighter.cpp
Since "Character" tokens do not have an "end position", viewing source drops the source contents following the final non-"Character" token.
By handling the EOF token and breaking out of the loop, we avoid this issue.
(cherry picked from commit 7de669dc07956c402e0ddec76e3f214f622cf2c4)
---
https://github.com/LadybirdBrowser/ladybird/pull/353
=> Cherry-pick "LibWebView: Append remaining source after consuming all tokens"

Userland/Libraries/LibIDL/IDLParser.cpp
IDL enumerations are one of the rare list types in the IDL spec that allow for a trailing comma:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=17508 (cherry picked from commit 47597d0fb83d78eaf43be549cd7fe23e9b239b78)
---
https://github.com/LadybirdBrowser/ladybird/pull/2097
=> Cherry-pick "LibIDL: Allow trailing comma in enumerations"

Ladybird/Qt/LocationEdit.cpp, Ladybird/Qt/LocationEdit.h, Ladybird/Qt/Settings.cpp, Ladybird/Qt/Settings.h
The placeholder text shows "Search or enter web address" which doesn't tell the user about *how* the search will be performed. Other popular open source browsers show the search engine that will be used. For example:
Chromium: "Search **engine** or type a URL"
Firefox: "Search with **engine** or enter address"
This change changes the placeholder text of the location bar to show "Search with **engine** or enter web address".
(cherry picked from commit 637ccbec3524727e22d07da5331f627165759791)
---
https://github.com/LadybirdBrowser/ladybird/pull/140
=> Cherry-pick "UI/Qt: Show search engine name in location bar"

Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
... to prevent that left-floating elements inside the list element push the list marker into the (non-floating) content of the list element.
(cherry picked from commit b7e505365c768b70ce830fbe3a6eac93b2364cd8)
---
https://github.com/LadybirdBrowser/ladybird/pull/396
=> Cherry-pick "LibWeb: Save float-intrusion for marker before list elements layout"

Ladybird/WebDriver/main.cpp
This allows multiple WPT tests to be run in parallel with using the `--processes` option.
(cherry picked from commit c14dc77349eca6f9cddd7fbb1d8e216cc9fa6cf8)
---
https://github.com/LadybirdBrowser/ladybird/pull/196
=> Cherry-pick "WebDriver: Launch Ladybird with `--force-new-process`"

Meta/gn/secondary/Userland/Libraries/LibWeb/HTML/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
This should've been in #24721.
Makes Text/input/all-window-properties.html pass with the GN build.
=> Meta: Add DragEvent to GN build

Userland/Libraries/LibMedia/Containers/Matroska/Reader.cpp
(cherry picked from commit 0879489084e883dbadcdeca814480dceea1d6eb9)
---
https://github.com/LadybirdBrowser/ladybird/pull/279
=> Cherry-pick "LibMedia: Hide Matroska debug message behind a flag"

Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/HTML/HTMLElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLElement.h, Userland/Libraries/LibWeb/HTML/HTMLElement.idl
The popover property now reflects the attribute.
It cannot currently use the Reflect IDL concept because the empty string value is special cased.
(cherry picked from commit a9669639cee27e81640fe7a37d9d1f319db6b666)
---
https://github.com/LadybirdBrowser/ladybird/pull/336, except for the unintentional change to Tests/LibWeb/rebaseline-libweb-test
=> Cherry-pick "LibWeb: Implement popover property and attribute"

Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn
This should have been part of #25241.
=> Meta: Make GN build actually refer to StorageAPI

Tests/LibWeb/Text/expected/CSSOMView/getClientRects-in-detached-document.txt, Tests/LibWeb/Text/input/CSSOMView/getClientRects-in-detached-document.html, Userland/Libraries/LibWeb/DOM/Element.cpp
I previously believed there was no way a detached document should have layout information, but it turns out there is a way: getComputedStyle().
So we need to account for cases where we have a layout node, but no navigable, since that is a state we can get into at this moment.
Fixes #354
(cherry picked from commit 1e7b17f15024d0618f1a1e17e3e927856febde28)
---
https://github.com/LadybirdBrowser/ladybird/pull/971
=> Cherry-pick "LibWeb: Don't crash on getClientRects() in document without navigable"

Tests/LibWeb/Text/expected/SVG/getBBox-outermost-svg-element-crash.txt, Tests/LibWeb/Text/input/SVG/getBBox-outermost-svg-element-crash.html, Userland/Libraries/LibWeb/SVG/SVGElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
https://github.com/LadybirdBrowser/ladybird/pull/1307
=> Cherry-pick "LibWeb: Don't crash when calling getBBox() on the outermost SVG element"

Tests/LibWeb/Text/expected/css/small-aspect-ratio.txt, Tests/LibWeb/Text/input/css/small-aspect-ratio.html, Userland/Libraries/LibWeb/Layout/Box.cpp, Userland/Libraries/LibWeb/PixelUnits.h
Previously, a crash would occur in the if `CSSPixelFraction` was given a denominator value less than the resolution of `CSSPixels` (1/64).
We now divide both parts of the ratio by the denominator in this case.
(cherry picked from commit 2c5d626b2125ffea49e06735e2f93279d0dfa0e1)
---
https://github.com/LadybirdBrowser/ladybird/pull/1160
=> Cherry-pick "LibWeb: Don't crash when converting small CSS::Ratio to CSSPixelFraction"

Userland/Libraries/LibWeb/Page/EventHandler.cpp
to make the code more readable
(cherry picked from commit a2e42590990b91c492c68792e086a789fe3bb083)
---
First commit form https://github.com/LadybirdBrowser/ladybird/pull/1125 (the 2nd commit was reverted in https://github.com/LadybirdBrowser/ladybird/pull/1195)
=> Cherry-pick "LibWeb: Introduce variable `dom_node` in EventHandler::handle_mousedown"

Kernel/Arch/aarch64/InterruptManagement.cpp, Kernel/Arch/aarch64/InterruptManagement.h, Kernel/Arch/aarch64/RPi/InterruptController.cpp, Kernel/Arch/aarch64/RPi/Timer.cpp, Kernel/Arch/aarch64/RPi/Timer.h, Kernel/Arch/init.cpp, Kernel/Bus/USB/USBDevice.cpp, Kernel/Bus/USB/USBManagement.cpp, Kernel/Bus/USB/USBManagement.h, Kernel/CMakeLists.txt, Kernel/Firmware/DeviceTree/Device.h, Kernel/Firmware/DeviceTree/DeviceRecipe.h, Kernel/Firmware/DeviceTree/Driver.h, Kernel/Firmware/DeviceTree/Management.cpp, Kernel/Firmware/DeviceTree/Management.h, Kernel/Time/TimeManagement.cpp, Kernel/Time/TimeManagement.h, Userland/Libraries/LibDeviceTree/DeviceTree.cpp, Userland/Libraries/LibDeviceTree/DeviceTree.h
This PR should make writing devicetree drivers a lot simpler and keep code duplication minimal.
This PR does *not* depend on #25103. But we will need that PR to actually get the physical addresses from the 'reg' properties.
=> Kernel: Introduce a new model for writing devicetree drivers

Kernel/FileSystem/FATFS/FileSystem.cpp, Kernel/FileSystem/FATFS/Inode.cpp, Kernel/FileSystem/FATFS/Inode.h
This mostly consists of file name handling improvements (e.g. better long file name -> short file name conversion), but there are a bunch of other fixes thrown in as well. See individual commits for details.
=> Kernel/FATFS: Various correctness/stability fixes

Ports/.port_include.sh
Some distros still don't ship ImageMagick 7
=> Ports: Fallback to 'convert' if 'magick' doesn't exist in install_icon

Meta/run.py, Toolchain/BuildQemu.sh
This updates `run.py` so that it will configure the `qemu-vdagent` (QEMU's built-in spice agent for clipboard support) when it's available.
Setting `SERENITY_SPICE=1` is only needed to use `spicevmc`, which implements more features (such as file transfers), but requires more setup to get working (see Documentation/SpiceIntegration.md).
This matches the behaviour of the old `run.sh` script, the logic was changed (perhaps unintentionally) in the `run.py` rewrite.
Note: For copy/paste to work you may need to rebuild QEMU with `--enable-gtk-clipboard` (which is added to `Toolchain/BuildQemu.sh` for Linux as part of this patch).
=> Meta: Enable `qemu-vdagent` (for copy/paste support) by default on Linux

Tests/LibWeb/Layout/expected/css-appearance-none.txt, Tests/LibWeb/Layout/input/css-appearance-none.html, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Per css-ui-4, setting `appearance: none` is supposed to suppress the creation of a native-looking widget for stuff like checkboxes, radio buttons, etc.
This patch implements this behavior by simply falling back to creating a layout node based on the CSS `display` property in such cases.
This fixes an issue on the hey.com imbox page where we were rendering checkboxes on top of sender profile photos.
(cherry picked from commit 58c523ae46af90ab17d6b98966d97fa776ae2bf4)
---
https://github.com/LadybirdBrowser/ladybird/pull/1883
=> Cherry-pick "LibWeb: Honor `appearance: none` when creating input element layout node"

Tests/LibWeb/TestNumbers.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/Numbers.cpp, Userland/Libraries/LibWeb/HTML/Numbers.h
This change adds checking for the following spec requirements:
- https://html.spec.whatwg.org/#number-state-(type=number):value-sanitization-algorithm
- https://html.spec.whatwg.org/#range-state-(type=range):value-sanitization-algorithm
That is, it adds checking that HTMLInputElement.value is what the spec defines as a “valid floating-point number” when the “type” attribute for the HTMLInputElement is either “number” or “range”.
This change causes Ladybird to pass all the failing tests at https://wpt.fyi/results/html/semantics/forms/the-input-element/number.html?run_id=5080423051034624 and to match the relevant behavior in Webkit, Blink, and Gecko.
Otherwise, without this change, Ladybird fails those tests, and the relevant Ladybird behavior isn’t interoperable with other engines.
(cherry …
=> Cherry-pick "LibWeb: Add “valid floating-point number” for HTMLInputElement.value"

Tests/LibWeb/Text/expected/HTML/HTMLInputElement-radio-groups.txt, Tests/LibWeb/Text/input/HTML/HTMLInputElement-radio-groups.html, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Previously, we were searching for other radio buttons from the document root, rather than the element root.
(cherry picked from commit 67981af276cf55d69d51a872ec83e5b59d793b6c)
---
https://github.com/LadybirdBrowser/ladybird/pull/1366
=> Cherry-pick "LibWeb: Don't group radio buttons from different trees together"

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
(cherry picked from commit c31f9815b46a12c931f7d446f7e4e42c71eacf5d)
---
https://github.com/LadybirdBrowser/ladybird/pull/1602
=> Cherry-pick "LibWeb: Readonly input element's arrow buttons don't change the value"

Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h, Userland/Libraries/LibWeb/Page/EventHandler.cpp
https://github.com/LadybirdBrowser/ladybird/pull/1273
=> Cherry-pick "LibWeb: Don't propagate key events that are handled by the media player"

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/DOM/Element.cpp
Previously, we set the "needs style update" flag to false at the beginning of recomputing the style. This meant that if any code within the cascade set this flag to true, then we would end style computation thinking the element still needed its style updating. This could occur when starting a transition, and would make TreeBuilder crash.
By ensuring that we always set the flag to false at the very end of style computation, this is avoided, along with any similar issues - I noticed a comment in `Animation::cancel()` which sounds like a workaround was needed for a similar problem previously.
(cherry picked from commit 8c79edac085ee164aca5ca7cf287e68e93e03217)
---
https://github.com/LadybirdBrowser/ladybird/pull/1573
=> Cherry-pick "LibWeb: Ensure Elements don't need style update after computing style"

Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/BrowserWindow.h
Previously, new tabs always had the `auto` color scheme, regardless of what the user has selected before.
Replace the 3 individual slots with a `set_preferred_color_scheme` method.
(cherry picked from commit 82915e1914bd9a8d4a6dcbec53982b3ba2caa68d)
---
https://github.com/LadybirdBrowser/ladybird/pull/462
=> Cherry-pick "Ladybird/Qt: Apply selected color scheme for new tabs"

Tests/LibCore/TestLibCoreFileWatcher.cpp
This include was unused when it was added in #6993, probably copy-pasta from Tests/LibC/TestLibCInodeWatcher.cpp where it is used.
=> Tests: Remove unused Kernel/ include

Ladybird/Qt/Tab.cpp
This resolves a bug where if you opened a link in a new tab and quickly went back to the original, the navigation buttons would update for the new page shortly after.
(cherry picked from commit 7abf47f4bf5039869a8f38c12f1be62bba97e463)
---
https://github.com/LadybirdBrowser/ladybird/pull/609
=> Cherry-pick "Ladybird/Qt: Only update navigation buttons for current tab"

Ladybird/Qt/Tab.cpp
This prevents the user being able to shrink the window to the point that the location bar and other controls are no longer visible.
(cherry picked from commit 4ed46adeeec4860b55d455da49aa93aff26bf1a3)
---
https://github.com/LadybirdBrowser/ladybird/pull/516
=> Cherry-pick "UI/Qt: Set a minimum size policy for the navigation control toolbar"

Meta/lb-cherry-picks.py
See comments in the script for details.
Screenshot:
```
% time ./cherry-pick-report.py                                                  
Report of Ladybird commits and their cherry-pick status in SerenityOS:
=====================================================================
[...]
Pull Request: https://github.com/LadybirdBrowser/ladybird/pull/910
🚫 5f8d852daeae9129d2873b4fce306be3f0599a06 LibWebView+UI: Migrate Ladybird's command line flags to LibWebView
Pull Request: https://github.com/LadybirdBrowser/ladybird/pull/899
🚫 f735c464d3fe02ac43a1fa46c82ae9a3bb5de8b1 LibWeb/Fetch: Don’t cache redirects
[...]
=====================================================================
1440 PRs, 407 cherry-picked PRs, 113 unwanted PRs
920 to go …
```
=> Meta: Add a script that prints potential Ladybird cherry-picks

Ladybird/Qt/Application.cpp, Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/main.cpp
The location bar URL is no longer hidden when creating a new tab or opening a new window that has an associated URL. Conversely, the location bar is now always focused and the URL hidden when creating a window or tab without an associated URL.
The location bar is focused when:
* Opening the browser from the command line with no URL arguments
* Opening a new tab (Ctrl+T)
* Opening a new window (Ctrl+N)
The location bar is not focused when:
* Opening the browser from the command line with one or more URLs
* Opening hyperlinks in a new tab
* Clicking a hyperlink with `target="_blank"`
This matches the behavior of other major browsers.
(cherry picked from commit efce3d967183f7071d47f27ce93310662217ef5e)
---
https://github.com/LadybirdBrowser/ladybird/pull/228
=> Cherry-pick "UI/Qt: Don't hide the location bar URL when creating a tab from a URL"

Tests/LibWeb/Text/expected/WebAnimations/transition-unknown-property.txt, Tests/LibWeb/Text/input/WebAnimations/transition-unknown-property.html, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
If we don't recognize a given transition-property value as a known CSS property (one that we know about, not necessarily an invalid one), we should not extrapolate the other transition-foo values for it.
Fixes #1480
(cherry picked from commit 9765a733d0bc297815fc1a7fce562e3d8f69cd84)
---
https://github.com/LadybirdBrowser/ladybird/pull/1514
=> Cherry-pick "LibWeb: Don't extrapolate transition properties for unknown properties"

Kernel/CMakeLists.txt, Kernel/FileSystem/Ext2FS/BlockView.cpp, Kernel/FileSystem/Ext2FS/BlockView.h, Kernel/FileSystem/Ext2FS/FileSystem.cpp, Kernel/FileSystem/Ext2FS/FileSystem.h, Kernel/FileSystem/Ext2FS/Inode.cpp, Kernel/FileSystem/Ext2FS/Inode.h, Userland/Libraries/LibFileSystem/FileSystem.cpp
See individual commits for details. The biggest change here is that we no longer store entire block lists in memory, since that can OOM way too easily. Instead, we now keep a 'view' to the actual block list, which can hold up to 10 000 blocks at once.
=> Ext2FS+LibFileSystem: Make working with large files manageable

Tests/LibGfx/TestPath.cpp, Tests/LibPDF/paths.pdf, Userland/Libraries/LibGfx/Path.cpp, Userland/Libraries/LibGfx/Path.h, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
This adds support for dash patterns to Path::stroke_to_fill().
This is used in PDFs, `<canvas>`, and `<svg>`.
The implementation is based on the <canvas> spec. It seems to do
the right thing for PDF files too.
This is hooked up in LibPDF. Future commits will do `<canvas>` and `<svg>`.
=> LibGfx+LibPDF: Add support for stroke dash patterns 

Kernel/Arch/aarch64/MMU.cpp, Kernel/Arch/aarch64/boot.S, Kernel/Arch/aarch64/linker.ld, Kernel/Arch/init.cpp, Kernel/Arch/x86_64/linker.ld
This moves the initial aarch64 stack similar to how #23205 moved it for RISC-V.
I also included some small improvements to the aarch64 linker script while I'm here.
=> Kernel/aarch64: Don't use the memory before .text as the initial stack (+ some linker script fixes)

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp, Userland/Libraries/LibWeb/HTML/NavigatorBeacon.cpp
https://github.com/LadybirdBrowser/ladybird/pull/899
https://github.com/LadybirdBrowser/ladybird/pull/955
https://github.com/LadybirdBrowser/ladybird/pull/1025
https://github.com/LadybirdBrowser/ladybird/pull/1056
https://github.com/LadybirdBrowser/ladybird/pull/1073
=> Cherry-pick 5 fetch-related ladybird PRs

Meta/lb-cherry-picks.py
* Use argparse to add flags for printing cherry-picked and rejected upstream PRs
* Add a few more entries to PRs we don't want, and for PRs that we already have through non-cherrypicks
=> Meta: Tweak lb-cherry-picks.py script

Userland/Utilities/fortune.cpp
=> Utilities/fortune: Fix typo

Meta/CMake/jakt.cmake, Toolchain/BuildJakt.sh, Userland/Libraries/LibShell/Builtin.cpp, Userland/Libraries/LibShell/Shell.h
Unrelated Shell commit, plus fix for `serenity.sh recreate` deleting the jakt runtime with no way to get it back automatically.
=> Jakt fixes

Userland/Libraries/LibTimeZone/TimeZone.cpp
https://github.com/LadybirdBrowser/ladybird/pull/72
Even though the 2nd commit says "Remove AK_OS_SERENITY ifdef", it still works for serenity – the code added in the 1st commit makes that ifdef redundant.
=> Cherry-pick "LibTimeZone: Read /etc/timezone for current TZ"

Meta/CMake/all_the_debug_macros.cmake, Meta/Lagom/CMakeLists.txt, Meta/Lagom/Tools/CMakeLists.txt, Meta/Lagom/Tools/PrekernelPEImageGenerator/CMakeLists.txt, Meta/Lagom/Tools/PrekernelPEImageGenerator/PEDefinitions.h, Meta/Lagom/Tools/PrekernelPEImageGenerator/main.cpp, Userland/Libraries/LibELF/ELFABI.h, Userland/Libraries/LibELF/Image.cpp, Userland/Libraries/LibELF/Image.h
This tool will be used to convert the Prekernel into an EFI PE32+ image.
This PR does not depend on any of the other EFI Prekernel PRs.
=>  EFI Prekernel (2/N): Meta: Add the PrekernelPEImageGenerator tool

Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.idl
This allows us to run Speedometer 3.0 to completion. :^)
(cherry picked from commit 72320be1240039822693aa1659c4adbb24cde87f)
---
Another sneaky PR-less commit, https://github.com/LadybirdBrowser/ladybird/commit/72320be1240039822693aa1659c4adbb24cde87f
=> Cherry-pick "LibWeb: Stub out SVGGraphicsElement.getScreenCTM()"

Tests/LibWeb/Text/expected/DOM/Node-lookupPrefix.txt, Tests/LibWeb/Text/input/DOM/Node-lookupPrefix.html, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/DOM/Element.h, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/Node.h, Userland/Libraries/LibWeb/DOM/Node.idl
https://github.com/LadybirdBrowser/ladybird/pull/870
Previously at #24859, but back then the new test didn't pass yet. Now it does.
=> Cherry-pick "LibWeb/DOM: Implement Node.lookupPrefix", reloaded

Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp, Userland/Libraries/LibWeb/Page/DragAndDropEventHandler.cpp, Userland/Libraries/LibWeb/Page/DragAndDropEventHandler.h, Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/EventHandler.h, Userland/Libraries/LibWeb/Page/EventResult.h, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/ConnectionFromClient.h, Userland/Services/WebContent/WebContentClient.ipc
UI event handlers currently return a boolean where false means the event was cancelled by a script on the page, or otherwise dropped. It has been a point of confusion for some time now, as it's not particularly clear what should be returned in some special cases, or how the UI process should handle the response.
This adds an enumeration with a few states that indicate exactly how the WebContent process handled the event. This should remove all ambiguity, and let us properly handle these states going forward.
There should be no behavior change with this patch. It's meant to only introduce the enum, not change any of our decisions based on the result.
(cherry picked from commit 541968b30dc50208f473566498100769711f10c8; amended to fix tiny conflict in ConnectionFromClient.h due to serenity …
=> LibWeb+LibWebView+WebContent: Return a named enum from UI event handlers

Userland/Libraries/LibVT/TerminalWidget.cpp, Userland/Libraries/LibVT/TerminalWidget.h, Userland/Libraries/LibVT/XtermColors.h
This fixes a bug where `VT::Color::Kind::Indexed` colors from index 16 to 255 were not being rendered because their alpha channel was set to zero.
Before:
After:
Testing script:
```python
for i in range(16, 256):
print(f"Index: {i}: \033[38;5;{i}mWHF :^)\033[0m")
```
=> Terminal: Set alpha channel to 0xFF

Ports/python3/patches/0007-Backport-gh-126688-Reinit-import-lock-after-fork.patch, Ports/python3/patches/ReadMe.md
https://github.com/python/cpython/pull/126765
Closes #25263
Make sure to revert this commit before updating Python.
=> Ports/python3: Backport gh-126688: Reinit import lock after fork

Tests/LibWeb/Text/expected/DOM/shadow-root-boundary-of-inserted-node-is-traversed.txt, Tests/LibWeb/Text/expected/HTML/iframe-successfully-loads-in-shadow-root.txt, Tests/LibWeb/Text/input/DOM/shadow-root-boundary-of-inserted-node-is-traversed.html, Tests/LibWeb/Text/input/HTML/iframe-successfully-loads-in-shadow-root.html, Userland/Libraries/LibWeb/CSS/MediaQueryList.cpp, Userland/Libraries/LibWeb/CSS/MediaQueryList.h, Userland/Libraries/LibWeb/DOM/ShadowRoot.h, Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp, Userland/Libraries/LibWeb/WebAudio/AudioContext.cpp, Userland/Libraries/LibWeb/WebAudio/AudioContext.h, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
https://github.com/LadybirdBrowser/ladybird/pull/1839
https://github.com/LadybirdBrowser/ladybird/pull/1991
https://github.com/LadybirdBrowser/ladybird/pull/2310
https://github.com/LadybirdBrowser/ladybird/pull/2313
=> Cherry-pick 4 ladybird PRs

Userland/Games/BrickGame/BrickGame.cpp
This is for people who prefer to play with the arrow keys.
Using Z for rotating the piece left is also the default binding on [tetris.com](https://tetris.com).
=> Games/BrickGame: Bind `Key_Z` to rotate left

Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp, Userland/Libraries/LibWeb/HTML/AudioTrack.cpp, Userland/Libraries/LibWeb/HTML/AudioTrack.h, Userland/Libraries/LibWeb/HTML/EventSource.cpp, Userland/Libraries/LibWeb/HTML/EventSource.h, Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLVideoElement.cpp, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/VideoTrack.cpp, Userland/Libraries/LibWeb/HTML/VideoTrack.h, Userland/Libraries/LibWeb/Loader/LoadRequest.h, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.cpp, Userland/Libraries/LibWeb/Platform/AudioCodecPlugin.h, Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp, Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.h, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h, Userland/Services/WebContent/WebDriverServer.ipc, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h, Userland/Services/WebDriver/WebContentConnection.cpp, Userland/Services/WebDriver/WebContentConnection.h
https://github.com/LadybirdBrowser/ladybird/pull/676 7th commit
https://github.com/LadybirdBrowser/ladybird/pull/1021
https://github.com/LadybirdBrowser/ladybird/pull/1030
https://github.com/LadybirdBrowser/ladybird/pull/1209
https://github.com/LadybirdBrowser/ladybird/pull/1234
https://github.com/LadybirdBrowser/ladybird/pull/1389
---
Not quite sure about if we want https://github.com/LadybirdBrowser/ladybird/pull/676. At least while we're cherry-picking, it helps reduce conflicts, so I'll pick the ones that do help – in this case, the 7th commit. Maybe we'll actually want all of it. And if not, it's easy to undo once we no longer cherry-pick.
=> Cherry-pick 5.0625 webdriver-related ladybird PRs

Kernel/Firmware/EFI/EFI.cpp, Kernel/Firmware/EFI/EFI.h, Kernel/Firmware/EFI/Protocols/ConsoleSupport.h, Kernel/Firmware/EFI/Protocols/DevicePath.h, Kernel/Firmware/EFI/Protocols/LoadedImage.h, Kernel/Firmware/EFI/Protocols/MediaAccess.h, Kernel/Firmware/EFI/Protocols/RISCVBootProtocol.h, Kernel/Firmware/EFI/Services/BootServices.h, Kernel/Firmware/EFI/SystemTable.h
These headers will be used by the EFI Prekernel to communicate with the platform firmware.
The definitions are adapted from the [UEFI specification](https://uefi.org/specs/UEFI/2.10/index.html) to match our code style.
This PR does not depend on any of the other EFI Prekernel PRs.
=>  EFI Prekernel (3/N): Kernel/EFI: Add EFI service and protocol headers

Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.h
Also added proper spec comments.
Fixes at least one WPT test that was failing previously: https://wpt.live/encoding/single-byte-decoder.window.html?document
(cherry picked from commit c1a14f66adf4b5e55a0e2a78068749e7d8b3ed98)
---
https://github.com/LadybirdBrowser/ladybird/pull/1707
=> Cherry-pick "HTMLEncodingDetection: Use mime type in encoding sniffing"

AK/DeprecatedFlyString.h, AK/FlyString.h
This avoid unnecessairy reference counting.
(cherry picked from commit 22a66bb1c2afde93096d9866d6386e2bca955f71)
---
https://github.com/LadybirdBrowser/ladybird/issues/1987
=> Cherry-pick "AK: Pass `(Deprecated)FlyString::is_one_of` arguments by reference"

Ladybird/Qt/AutoComplete.cpp, Ladybird/RequestServer/main.cpp, Tests/AK/TestJSON.cpp, Userland/Libraries/LibAudio/FlacWriter.cpp, Userland/Libraries/LibAudio/MultiChannel.h, Userland/Libraries/LibAudio/VorbisComment.cpp, Userland/Libraries/LibCore/Process.cpp, Userland/Libraries/LibCore/ResourceImplementation.cpp, Userland/Libraries/LibCore/System.cpp, Userland/Libraries/LibCrypto/ASN1/DER.h, Userland/Libraries/LibCrypto/Hash/MGF.h, Userland/Libraries/LibCrypto/Hash/PBKDF2.h, Userland/Libraries/LibCrypto/Padding/OAEP.h, Userland/Libraries/LibTLS/Certificate.cpp, Userland/Libraries/LibWeb/ARIA/RoleType.cpp, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp, Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Services/WebDriver/Client.cpp, Userland/Utilities/aconv.cpp, Userland/Utilities/animation.cpp, Userland/Utilities/image.cpp
(cherry picked from commit 229b64a4b723a391c21f247d72d78cd575ace6ff; minorly amended to fix conflict in image.cpp due to serenity in the meantime adding webp writing support, and due to changes in Android and Vulkan-related files that serenity doesn't have)
---
https://github.com/LadybirdBrowser/ladybird/pull/457
=> Everywhere: Convert from_string_view -> from_string_literal where static

Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp, Userland/Libraries/LibWeb/HTML/BrowsingContext.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp
I originally believed that this could never receive a null URL and the spec was inaccurate, but it seems like it can indeed.
I don't have a distilled test, but this makes logging in with GitHub work on https://v0.dev/
(cherry picked from commit 1a4b0ded1f802fdcc3ef9b919b5749b086471fc2; amended to also cherry-pick LadybirdBrowser/ladybird#2358)
---
https://github.com/LadybirdBrowser/ladybird/pull/1537 (first commit was in #25345).
=> Cherry-pick "LibWeb: Let determine_the_origin() take an optional URL after all", second commit

.devcontainer/devcontainer.json
This patch fixes this error when trying to SSH into the devcontainer with [`gh codespaces ssh`](https://cli.github.com/manual/gh_codespace_ssh):
```
error getting ssh server details: failed to start SSH server: Please check if an SSH server is installed in the container.
```
=> Meta: Add a SSH server to the devcontainer

Ladybird/Qt/WebContentView.cpp, Ladybird/Qt/WebContentView.h
This forwards all drag-and-drop events from the UI to the WebContent process. If the page accepts the events, the UI does not handle them. Otherwise, we will open the dropped files as file:// URLs.
(cherry picked from commit 4833ba06eaef20053f85343a13c0307394d67ded)
---
Last commit of https://github.com/LadybirdBrowser/ladybird/pull/1111 (first 13 were in #25243).
=> Cherry-pick "UI/Qt: Process drag-and-drop events through the web view"

AK/StringView.h, AK/Utf8View.h, Tests/AK/TestStringView.cpp, Tests/AK/TestUtf8.cpp, Userland/Libraries/LibCore/MimeData.cpp, Userland/Libraries/LibJS/SourceTextModule.cpp, Userland/Libraries/LibJS/Tests/builtins/ShadowRealm/ShadowRealm.prototype.importValue.js, Userland/Libraries/LibJS/Tests/builtins/ShadowRealm/async-module.mjs
~~https://github.com/LadybirdBrowser/ladybird/pull/2366~~
https://github.com/LadybirdBrowser/ladybird/pull/2365
https://github.com/LadybirdBrowser/ladybird/pull/2362
https://github.com/LadybirdBrowser/ladybird/pull/2368
=> Cherry-pick 3 ladybird PRs

Userland/Libraries/LibGUI/Notification.cpp, Userland/Libraries/LibGUI/Notification.h, Userland/Services/NotificationServer/CMakeLists.txt, Userland/Services/NotificationServer/ConnectionFromClient.cpp, Userland/Services/NotificationServer/ConnectionFromClient.h, Userland/Services/NotificationServer/NotificationServer.ipc, Userland/Services/NotificationServer/NotificationWidget.h, Userland/Services/NotificationServer/NotificationWindow.cpp, Userland/Services/NotificationServer/NotificationWindow.h, Userland/Services/NotificationServer/main.cpp, Userland/Services/SpiceAgent/CMakeLists.txt, Userland/Services/SpiceAgent/FileTransferOperation.cpp, Userland/Services/SpiceAgent/main.cpp
Rather than (re-)open the Downloads folder on every completed file transfer, send a notification when a transfer is complete. The notification includes the file's name, and clicking it will open the Downloads folder (with the file highlighted).
=> SpiceAgent: Send notification when file transfer is complete 

Tests/LibGfx/TestPainter.cpp, Userland/Libraries/LibGfx/Painter.cpp
I think this regressed in #5018. It easily triggered when scrolling a page that uses `text-decoration-style: wavy`.
=> LibGfx: Fix crash when calling draw_triangle_wave() offscreen

Tests/LibWeb/TestConfig.ini
It is consistently hanging on mac. See LadybirdBrowser/ladybird#1306 for details.
(cherry picked from commit feaf2feab8fbd855f526a5a4eec2395fdec6a749)
---
https://github.com/LadybirdBrowser/ladybird/pull/1867
#25390 brought the test in, and it's failing on our CI too: https://github.com/SerenityOS/serenity/actions/runs/11872575369/job/33086444958?pr=25410
=> Cherry-pick "LibWeb: Skip DedicatedWorkerGlobalScope-instanceof test"

Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/Worker/Worker-close-after-postMessage.txt, Tests/LibWeb/Text/input/Worker/Worker-close-after-postMessage.html, Tests/LibWeb/Text/input/Worker/worker-close-after-postMessage.js, Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
The spec expects `postMessage()` to act as if it is invoked immediately. Since `postMessage()` isn't actually invoked immediately, keep tasks with source `PostedMessage` in the task queue, so that these tasks are processed. Fixes a hang when `WorkerGlobalScope.close()` is called immediately after `postMessage()`.
(cherry picked from commit fd8d350b4756817598ee49a11b9efc3b953dbb00)
---
https://github.com/LadybirdBrowser/ladybird/pull/1661
=> Cherry-pick "LibWeb: Don't discard PostedMessage tasks when closing a worker"

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMathFunctions.cpp, Tests/LibWeb/CMakeLists.txt, Tests/LibWeb/TestCSSTokenStream.cpp, Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/TokenStream.h
When the TokenStream code was originally written, there was no such concept in the CSS Syntax spec. But since then, it's been officially added, (https://drafts.csswg.org/css-syntax/#css-token-stream) and the parsing algorithms are described in terms of it. This patch brings our implementation in line with the spec. A few deprecated TokenStream methods are left around until their users are also updated to match the newer spec.
There are a few differences:
- They name things differently. The main confusing one is we had `next_token()` which consumed a token and returned it, but the spec has a `next_token()` which peeks the next token. The spec names are honestly better than what I'd come up with. (`discard_a_token()` is a nice addition too!)
- We used to store the index of the token that …
=> Cherry-pick "LibWeb/CSS: Bring TokenStream in line with spec"

AK/Concepts.h, AK/FixedPoint.h, AK/SIMD.h, AK/StdLibExtraDetails.h
We build KERNEL without floats, so that context switches don't have to save float registers. As a side effect of that, _Float16 results in a "_Float16 is not supported on this target" diagnostic.
Having IsFloatingPoint<> be false for the upcoming f16 type, but true for other floating point types seems strange, so just stop having these concepts in kernel code altogether.
---
Prerequisite for #25434.
=> AK: Don't define IsFloatingPoint and the FloatingPoint concept in KERNEL

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/DocumentLoading.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp, Userland/Libraries/LibWeb/HTML/CrossOrigin/OpenerPolicy.h, Userland/Libraries/LibWeb/HTML/CrossOrigin/OpenerPolicyEnforcementResult.h, Userland/Libraries/LibWeb/HTML/CrossOrigin/Reporting.cpp, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/NavigationParams.h, Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
(cherry picked from commit de31ea5852e3fc0aca1e86e06c6bc019f27824de)
---
https://github.com/LadybirdBrowser/ladybird/pull/1399
=> Cherry-pick "LibWeb: Rename 'cross-origin opener policy' to 'opener policy'"

Meta/gn/secondary/Userland/Libraries/LibWeb/ServiceWorker/BUILD.gn, Tests/LibWeb/Text/expected/ServiceWorker/service-worker-register.txt, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/ServiceWorker/Job.cpp, Userland/Libraries/LibWeb/ServiceWorker/Job.h, Userland/Libraries/LibWeb/ServiceWorker/Registration.cpp, Userland/Libraries/LibWeb/ServiceWorker/Registration.h, Userland/Libraries/LibWeb/ServiceWorker/ServiceWorker.cpp, Userland/Libraries/LibWeb/ServiceWorker/ServiceWorker.h, Userland/Libraries/LibWeb/StorageAPI/StorageKey.h
https://github.com/LadybirdBrowser/ladybird/pull/1674
=> Cherry-pick "LibWeb: Implement most of Service Worker registration"

Meta/Lagom/Tools/CodeGenerators/LibUnicode/GenerateUnicodeData.cpp, Tests/LibUnicode/TestUnicodeCharacterTypes.cpp, Userland/Libraries/LibUnicode/CharacterTypes.cpp, Userland/Libraries/LibUnicode/CharacterTypes.h, Userland/Libraries/LibUnicode/Forward.h, Userland/Libraries/LibWeb/DOM/Element.cpp
Before this commit, GenerateUnicodeData generated a
`BidirectionalClass` enum directly from UnicodeData.txt.
Now, GenerateUnicodeData instead generates `BidirectionalClassInternal`
and CharacterTypes.h has an explicit enum `BidiClass` with nicer names
-- no underscores, but also names more similar to ICUs names.
(Since CharacterTypes.h is included in some of LibUnicode's generators,
it can't refer to generated `BidirectionalClassInternal`, so we instead
have a big manual mapping switch in UnicodeData.cpp.)
`bidirectional_class()` used to return an `Optional<BidirectionalClass>`
for when unicode data was disabled. Now we return `BidiClass` and
just return `BidiClass::LeftToRight` instead of making every client
do this.
It also updates LibWeb's Element.cpp to this new system.
Also remove …
=> LibUnicode+LibWeb: Rework bidirectional_class() API a bit

Tests/LibWeb/Layout/expected/input-placeholder-with-line-height.txt, Tests/LibWeb/Layout/expected/input-placeholder.txt, Tests/LibWeb/Layout/input/input-placeholder-with-line-height.html, Userland/Libraries/LibWeb/CSS/Default.css, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Before this change, we transferred the input element's line-height to both the editable text *and* the placeholder. This caused some strange doubling of the effective line-height when the editable text was empty, pushing down the placeholder.
(cherry picked from commit 13ba491924c4fc3831d5a8986673d832a721f545; amended some slighly different horizontal sizes in the expectations file. Maybe due to serenity not using harfbuzz for shaping, or due to not have another earlier change yet. If it's the latter, this will fix itself when that's brought in.)
---
https://github.com/LadybirdBrowser/ladybird/pull/1675
=> Cherry-pick "LibWeb: Don't let input element placeholders influence line-height"

Tests/LibWeb/Text/expected/css/FontFaceSet-load.txt, Tests/LibWeb/Text/input/css/FontFaceSet-load.html, Userland/Libraries/LibWeb/CSS/FontFace.h, Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
This implementation is incomplete in that we do not fully implement the steps to match the given font against the fonts in the set.
This is used by fonts.google.com to load the fonts used for sample text.
(cherry picked from commit 9bdf2e928c448585a6349bef36d7cb98ccc0607b)
---
https://github.com/LadybirdBrowser/ladybird/pull/1937
=> Cherry-pick "LibWeb: Begin implementing FontFaceSet.prototype.load"

Tests/LibWeb/Layout/expected/svg/svg-inside-inline-block.txt, Tests/LibWeb/Layout/input/svg/svg-inside-inline-block.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
This condition was included to implement flex containers with auto height, but it actually can reset the definitive height to 0 for inline blocks with only replaced elements such as an SVG. Removing the condition does not break any in-tree test, so let's improve the situation on the SVG side of things for now.
(cherry picked from commit 352a66390f27fb7bbbfa823364fefc9af00d4b63)
---
https://github.com/LadybirdBrowser/ladybird/pull/1942
=> Cherry-pick "LibWeb: Do not resolve inline block height early if height is definite"

Meta/gn/secondary/Userland/Libraries/LibIDL/BUILD.gn
Reduces the number of build steps after touching a file in LibUnicode from 915 to 87.
---
Ports the LibIDL cmake change in #25121 to the GN build.
=> Meta: Make LibIDL depend on LibCoreMinimal in GN build

Meta/gn/secondary/Userland/Libraries/LibLocale/BUILD.gn, Tests/LibLocale/CMakeLists.txt, Tests/LibLocale/TestSegmenter.cpp, Userland/Libraries/LibJS/Print.cpp, Userland/Libraries/LibJS/Runtime/Intl/SegmentIterator.cpp, Userland/Libraries/LibJS/Runtime/Intl/SegmentIterator.h, Userland/Libraries/LibJS/Runtime/Intl/SegmentIteratorPrototype.cpp, Userland/Libraries/LibJS/Runtime/Intl/Segmenter.cpp, Userland/Libraries/LibJS/Runtime/Intl/Segmenter.h, Userland/Libraries/LibJS/Runtime/Intl/SegmenterConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/SegmenterPrototype.cpp, Userland/Libraries/LibJS/Runtime/Intl/Segments.cpp, Userland/Libraries/LibJS/Runtime/Intl/Segments.h, Userland/Libraries/LibJS/Runtime/Intl/SegmentsPrototype.cpp, Userland/Libraries/LibJS/Tests/builtins/Intl/Segmenter/Segmenter.prototype.segment.js, Userland/Libraries/LibLocale/CMakeLists.txt, Userland/Libraries/LibLocale/Forward.h, Userland/Libraries/LibLocale/Segmenter.cpp, Userland/Libraries/LibLocale/Segmenter.h, Userland/Libraries/LibWeb/DOM/CharacterData.cpp, Userland/Libraries/LibWeb/DOM/CharacterData.h, Userland/Libraries/LibWeb/DOM/Position.cpp, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
This in a way cherry-picks the first three commits of https://github.com/LadybirdBrowser/ladybird/pull/218 – except it doesn't use ICU for it.
This is behavior-preserving for now (in the future we can make Segmenter locale-dependent and improve it). The main motivation is that this makes it easier to cherry-pick later ladybird patches.
=> Add Locale::Segmenter, and cherry-pick two ladybird PRs

Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/EventHandler.h
We currently use a naive word segmentation, looking for ASCII spaces to mark a word boundary. Use LibUnicode's complete implementation instead.
(cherry picked from commit 430c9d3e3fb6ec9e2aa3d962381672b70957c395; amended to use Locale::Segmenter instead of Unicode::Segmenter due to LibLocale and LibUnicode being two distinct libraries in serenity)
---
https://github.com/LadybirdBrowser/ladybird/pull/1205 1st commit; the other commits were in #25371 already)
=> Cherry-pick "LibWeb: Use a Unicode text segmenter to select words on double-click"

Tests/LibLocale/BenchmarkSegmenter.cpp, Tests/LibLocale/CMakeLists.txt, Tests/LibLocale/TestSegmenter.cpp, Userland/Libraries/LibLocale/Segmenter.cpp
Instead of recomputing boundaries on every iteration, this now
computes boundaries once and then searches that vector.
This is still O(n^2) for now, but already much faster (at the expense
of using O(n) memory): `BenchmarkSegmenter.for_each_boundary` stays
at around 3ms, but `forward` and `backward` go from ~13s to ~60ms
on my system.
Also add BenchmarkSegmenter, and improve test coverage a bit.
Note that code that still uses LibUnicode/Segmentation.h directly still has the slower behavior.
=> LibLocale: Make Segmenter store segment boundaries

Kernel/Bus/VirtIO/Queue.cpp, Kernel/Bus/VirtIO/Queue.h, Kernel/Memory/TypedMapping.h, Kernel/Net/Intel/E1000ENetworkAdapter.cpp, Kernel/Net/Intel/E1000ENetworkAdapter.h, Kernel/Net/Intel/E1000NetworkAdapter.cpp, Kernel/Net/Intel/E1000NetworkAdapter.h, Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp, Kernel/Net/Realtek/RTL8168NetworkAdapter.h
This mainly adds users of this in the Network code, as those were the easiest to find
Other places in the kernel may profit off of this in the future, like the ring buffers across other drivers
=> Kernel: Add and use TypedMapping<T*[]*>

.github/workflows/serenity-template.yml, Kernel/FileSystem/Ext2FS/Definitions.h, Kernel/FileSystem/Ext2FS/FileSystem.cpp, Kernel/FileSystem/Ext2FS/FileSystem.h, Kernel/FileSystem/Ext2FS/Inode.cpp, Kernel/FileSystem/Ext2FS/Inode.h, Meta/build-image-extlinux.sh, Meta/build-image-grub.sh, Meta/build-image-limine.sh, Meta/build-image-qemu.sh
The extra data provided by large inodes has almost exclusively to do with timestamps, which means that you can now get nanosecond precision on your root file system, and the capability to support dates beyond 2038 or so in a standards-compliant way. This is also basically a pre-requisite for ext3/ext4, since the 128-byte inodes we've been using are more-or-less deprecated.
This PR also fixes up serialization of epoch offsets, so if you have a filesystem that has inodes with negative timestamps, then those should now be reported correctly.
Lastly, this also adds a CI step to validate filesystem consistency after running tests, since we shouldn't be seeing any filesystem corruption after all the recent work that's been put into `Ext2FS`.
=> Kernel/Ext2FS: Add full support for large inodes

Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
AK::Duration is simply an integer, and does not need to be passed by reference.
(cherry picked from commit 6ce473af72ba666a8bae80a7f7691d233bdd2a43)
---
https://github.com/LadybirdBrowser/ladybird/pull/1771 commit 2 (another PR depends on that, and the other two commits currently cause conflicts)
=> Cherry-pick "LibIPC: Pass AK::Duration by value over IPC"

Meta/run.py
This is quite a crude check and may lead to false positives. But it's better than having a black screen on systems with NVIDIA graphics.
=> Meta: Don't use the `gtk,gl=on` display backend with NVIDIA graphics

Kernel/CMakeLists.txt, Kernel/EFIPrekernel/CMakeLists.txt, Kernel/EFIPrekernel/DebugOutput.cpp, Kernel/EFIPrekernel/DebugOutput.h, Kernel/EFIPrekernel/Error.h, Kernel/EFIPrekernel/Globals.h, Kernel/EFIPrekernel/KernelImage.S.in, Kernel/EFIPrekernel/Panic.cpp, Kernel/EFIPrekernel/Panic.h, Kernel/EFIPrekernel/Runtime.cpp, Kernel/EFIPrekernel/Runtime.h, Kernel/EFIPrekernel/VirtualMemoryLayout.h, Kernel/EFIPrekernel/init.cpp, Kernel/EFIPrekernel/kmalloc.cpp, Kernel/EFIPrekernel/linker.ld, Kernel/Prekernel/UBSanitizer.cpp
This skeleton is already bootable on all our supported architectures.
~~This PR depends on #24984 and #24985, therefore draft.~~
=> EFI Prekernel (5/N): EFIPrekernel: Add basic skeleton

Kernel/EFIPrekernel/CMakeLists.txt
This target was removed in 175f9dc5c3, but the dependency on it wasn't removed from faeb9ff521 before PR #24995 was merged. This should make everything build again.
=> EFIPrekernel: Don't depend on `install_libc_headers`

Kernel/API/serenity_limits.h, Userland/Libraries/LibELF/ELFABI.h
ELFABI.h gets included during the toolchain build, so we shouldn't
include AK headers from that file.
SERENITY_PAGE_SIZE also isn't really related to ELF ABI, so move it to
the serenity_limits.h header.
=> LibELF+Kernel: Don't define SERENITY_PAGE_SIZE in ELFABI.h

Userland/Libraries/LibGfx/Rect.h
The CenterRight and TopCenter alignment cases were mistakenly identical due to a copy-paste error, causing the function to behave unexpectedly.
Rather than attempting to fix it, remove aligned_within entirely.
Copies https://github.com/LadybirdBrowser/ladybird/pull/2829
=> LibGfx: Remove aligned_within from Rect

Kernel/Bus/USB/USBDevice.cpp, Kernel/Bus/USB/USBDevice.h, Kernel/Bus/USB/USBHub.cpp
These members were never set and are redundant because you can just read them directly from the device descriptor.
=> Kernel/USB: Remove never-initialized USB::Device::m_{vendor,product}_id

Kernel/Bus/USB/UHCI/UHCIController.cpp, Kernel/Bus/USB/USBPipe.cpp, Kernel/Bus/USB/xHCI/xHCIController.cpp, Kernel/Devices/Audio/AC97/AC97.cpp, Kernel/Devices/Audio/IntelHDA/RingBuffer.h, Kernel/Devices/Audio/IntelHDA/Stream.cpp, Kernel/Devices/Storage/AHCI/Port.cpp, Kernel/Devices/Storage/NVMe/NVMeController.cpp, Kernel/Devices/Storage/NVMe/NVMeQueue.cpp, Kernel/Devices/Storage/SD/SDHostController.cpp, Kernel/Memory/MemoryManager.cpp, Kernel/Memory/MemoryManager.h, Kernel/Memory/TypedMapping.h, Kernel/Net/Intel/E1000NetworkAdapter.cpp, Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
Drivers using DMA buffers are currently broken on bare metal since
d3a0ae5c57b and b3bae90e71c made DMA buffers use the NonCacheable memory
type.
We should investigate each of these drivers and and add proper fences
where needed.
=> Kernel: Use MemoryType::IO for DMA regions everywhere

Kernel/Arch/aarch64/Dummy.cpp, Kernel/Arch/aarch64/Interrupts.cpp, Kernel/Arch/aarch64/Processor.cpp, Kernel/Bus/PCI/DeviceTreeInitializer.cpp, Kernel/CMakeLists.txt, Kernel/Devices/Storage/AHCI/Definitions.h
This is enough to enumerate PCI devices, and to read/write from/to the PCI configuration space on the virt machine.
I did try to get PCI interrupts working, and so I've included a few commits that resulted from that, but ultimately it seems that we'd need to support the GICv2m extension if we want to get MSI(-X) working, or then we'd need to figure out how to get pin-based interrupts to work with the plain GICv2.
Also, I couldn't really find any specs for the aarch64 devicetree stuff included here (I mostly worked off of [this blog post](https://michael2012z.medium.com/understanding-pci-node-in-fdt-769a894a13cc) and some trial and error), so do take this with a grain of salt.
=> Kernel/aarch64: Implement basic PCI support

Kernel/Arch/aarch64/Registers.h, Kernel/Arch/aarch64/Time/ARMv8Timer.cpp
The physical timer might not be accessible to us if we are running in a
hypervisor.
=> Kernel/aarch64: Use the EL1 virtual timer for ARMv8Timer

Userland/Libraries/LibC/pthread.cpp
The AArch64 and RISC-V ABI use a caller-saved register to store the return address instead of (always) storing it on the stack. All non-special registers of newly created threads are zero by default, so we don't need to anything special for those architectures here.
This change also causes the stack pointer to no longer be misaligned for secondary threads on those architectures.
=> LibC: Don't push a fake return address in `create_thread` on non-x86

Userland/Services/WindowServer/Menu.cpp, Userland/Services/WindowServer/Menu.h
The old calculation was unnecessarily complicated and didn't handle flipped menus correctly. To determine the two triangle corners at the submenu, we can simply use the submenu's rect() and subtract the position of the parent menu to get the correct relative coordinates.
If the submenu is flipped at its vertical axis, we need to use the opposite corners of the window rect.
Before:
[Screencast_20241208_010239.webm](https://github.com/user-attachments/assets/10720d38-6fd1-415e-aeb7-a90ff3147fe4)
After:
[Screencast_20241208_010106.webm](https://github.com/user-attachments/assets/05627a31-c9c0-447b-8cf6-b419d80aa060)
=> WindowServer: Handle flipped submenus during safe submenu navigation

Kernel/Memory/MemoryManager.cpp, Kernel/Syscalls/thread.cpp
This also removes the explicit decrementing of the stack pointer in `sys$create_thread` before passing it to `validate_user_stack`, as it's unnecessary now.
This unbreaks programs using threads on AArch64 and RISC-V after 070534c3ee74995d5fb82ca9f9ffd86ad814305d (oops).
=> Kernel: Recognize a stack pointer pointing to the top of stack as valid

Kernel/Arch/aarch64/ASM_wrapper.h
Changes to ARM system registers are not guaranteed to be visible until a context synchronization event, like performing an ISB.
=> Kernel/aarch64: Perform an ISB after setting TTBR*_EL1

Ports/jakt/package.sh
Note: Once inside SerenityOS, ` jakt ` will not launch, to fix this issue, do:
```
$ su root
```
Enjoy!
=> Ports: Update jakt to latest as of 19-Dec-2024

Kernel/Arch/Processor.h, Kernel/Arch/aarch64/PlatformInit/RaspberryPi.cpp, Kernel/Arch/aarch64/Processor.cpp, Kernel/Arch/aarch64/Processor.h, Kernel/Arch/aarch64/RPi/SDHostController.cpp, Kernel/Arch/aarch64/RPi/SDHostController.h, Kernel/Arch/init.cpp, Kernel/Arch/riscv64/Processor.h, Kernel/Arch/x86_64/Processor.h, Kernel/Devices/Storage/StorageManagement.cpp, Kernel/Devices/Storage/StorageManagement.h, Kernel/Security/Random.h
You can try booting it with the following command:
`qemu-system-aarch64 -s -m 2G -cpu max -M virt -serial mon:stdio -d guest_errors,unimp -kernel Build/aarch64/Kernel/kernel8.img -drive file=Build/aarch64/_disk_image,format=raw,if=none,id=boot-drive -device nvme,drive=boot-drive,serial=deadbeef -append 'serial_debug nvme_poll root=block3:0' -device VGA -device virtio-tablet -device virtio-keyboard`
Even virtio keyboard and mouse work!
We should probably split the init section into a non-early and early section and add a devicetree driver for the MiniUART in the future. This would also allow us to get rid of the `DeviceRecipe` for the RPi::SDHostController.
=> Kernel/aarch64: Make the kernel boot on the virt machine

Documentation/SmartPointers.md
- To transform **a** known-non-null ...
- a reference-counted object **can** be ...
=> Documentation: Fix typos in SmartPointers.md

AK/Atomic.h, AK/Function.h, AK/ScopeGuard.h, Tests/AK/CMakeLists.txt, Tests/AK/TestFunction.cpp
Just enough to make it possible to pass a lambda to a constexpr function
taking an AK::Function parameter and have that constexpr function call
the passed-in AK::Function.
The main thing is that bit_cast<>s of pointers aren't ok in constexpr
functions, and neither is placement new. So add a union with stronger
typing for the constexpr case.
The body of the `if (is_constexpr_evaluated())` in
`init_with_callable()` is identical to the `if constexpr` right
after it. But `if constexpr (is_constexpr_evaluated())` always
evaluates `is_constexpr_evaluated()` in a constexpr context, so
this can't just add ` || is_constexpr_evaluated()` to that
`if constexpr`.
=> AK: Make Function a little bit constexpr

Meta/gn/build/toolchain/BUILD.gn
Linking liblagom-web.so produces a ~132K long command line. Ninja passes the whole command line as a single arg to `sh -c <arg>`, and the limit for single arguments (`MAX_ARG_STRLEN`) on Linux is `PAGE_SIZE * 32` == 128K.
A response file passes the list of files in a file on disk, which lets us sidestep this problem. Ninja writes response files before invoking commands, and deletes them after (unless `-d keeprsp` is passed to ninja, then it keeps them on disk).
=> Meta: Use response file for linking shared libraries in GN build

AK/Math.h
This is a pretty naive implementation of exp2() that can be improved
a lot, but hey, it beats the sin() and cos() implementation on non-x86.
It also implements exp(x) as exp2(x * log2(e)), with the same
disclaimer.
---
With this, it's possible to open Text Editor and Video Player (and probably more, but not yet Browser) in aarch64 builds.
=> AK: Add implementations of exp2() and exp() on non-x86

Base/etc/fstab, Base/usr/share/man/man2/mount.md, Kernel/API/POSIX/unistd.h, Kernel/FileSystem/Mount.cpp, Kernel/FileSystem/Mount.h, Kernel/FileSystem/VFSRootContext.cpp, Kernel/FileSystem/VFSRootContext.h, Kernel/FileSystem/VirtualFileSystem.cpp, Kernel/FileSystem/VirtualFileSystem.h, Kernel/Syscalls/unshare.cpp, Kernel/Tasks/PowerStateSwitchTask.cpp, Kernel/Tasks/Process.cpp, Userland/Utilities/init.cpp, Userland/Utilities/mount.cpp
I decided to try #24915 again. This should be part of security hardening in the `VFSRootContext` mechanism, and prevent unmounting crucial filesystems or changing their mountpoints' flags while the system runs.
=> Kernel+Userland: Add immutable mounts

AK/Math.h, Tests/LibC/TestMath.cpp, Userland/Libraries/LibC/math.cpp
atan2() is implemented in terms of atan(), so the implementation isn't super useful yet.
=> AK: fmod(), sin(), cos(), atan2() for non-x86

AK/Math.h
asin() now no longer relies on atan(), and atan() is now implemented in terms of asin().
With atan() implemented, Browser starts up, and paths can be stroked.
`/usr/Tests/LibC/TestMath` now passes 7 of 14 tests, compared to 2 of 14 before.
(While here, also implement tan() as sin() / cos().)
=> AK: Implement asin(), atan(), tan() on non-x86

Ports/jakt/package.sh
No change in version, just added menu entry
Note:
If after building the jakt port, it doesn't launch inside **Serenity**OS:
- switch to root account
- unlink / remove `/usr/local/bin/jakt`
- soft link `/usr/local/bin/jakt_stage1` as `/usr/local/bin/jakt`
- enjoy
=> Ports: Add menu entry for Jakt

Meta/build-image-qemu.sh
If you run `serenity.sh run` with missing fuse2fs and/or fusermount3,
then install the needed packages, and then try to run the script
again, rmdir step will fail with "non-empty directory" error
causing QEMU to not start. The patch avoids this by recursively
removing disk mount directory instead of just unlinking it.
=> Meta: Use `rm -rf` instead of `rmdir` in QEMU image build script

Userland/Applications/SystemMonitor/SystemMonitor.gml, Userland/Applications/SystemMonitor/main.cpp
=> SystemMonitor: Grow CPU and memory charts to window size

Userland/Libraries/LibDeviceTree/FlattenedDeviceTree.h
=> LibDeviceTree: Fix a typo in comment

Meta/download_file.py
When downloading pnp_ids.csv from https://uefi.org/uefi-pnp-export it needs to have a User-Agent string set, or it will return an 403: Forbidden error.
=> Meta: Add User-Agent string on request for download_file

Tests/LibC/TestSnprintf.cpp
Most RISC-V floating-point operations only generate the canonical NaN, so the sign bit was cleared in this test.
The sign injection instruction does keep the NaN payload and sign bit, so doing `-v.f` to get a negative NaN works as expected.
=> Tests/LibC: Don't implicitly convert float to double in TestSnprintf

Ports/SDL2/patches/0001-Add-SerenityOS-platform-support.patch
We got out of sync in 965e1baa8c1ec99a591e2c93a27b59f8db0b7fc5. Sync the names in order to fix build.
=> Ports/SDL2: Sync scancode map with Kernel/API/KeyCode.h

Meta/run.py
This option causes the window to not resize automatically on guest display resolution changes.
QEMU has this option enabled by default when using virtio-gpu.
=> Meta: Disable "Zoom To Fit" when using the gtk display backend

Userland/Libraries/LibGfx/GlassWindowTheme.cpp, Userland/Libraries/LibGfx/PlasticWindowTheme.cpp
Previously, the title bar text could be painted under the buttons for small window sizes (or long titles).
=> LibGfx: Fix title bar text clipping in Redmond Glass/Plastic

Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn, Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000ProgressionIterators.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000ProgressionIterators.h
The math isn't used at all yet; the iterators are only used in tests for now.
The near-term goal is to read packet data, which requires knowing how many code-blocks are in a packet (to be able to give the TagTrees the right size). And while I have that all working locally, it's quite a mess, and I figure it's better to incrementally land this code as it becomes ready instead of a big PR with everything once everything's nice and tidy.
=> LibGfx/JPEG2000: Add some more code

Kernel/Arch/aarch64/MMU.cpp, Kernel/Arch/aarch64/Processor.cpp, Kernel/Arch/aarch64/boot.S, Kernel/Arch/aarch64/linker.ld, Kernel/Arch/aarch64/pre_init.cpp, Kernel/Arch/riscv64/MMU.cpp, Kernel/Arch/riscv64/boot.S, Kernel/CMakeLists.txt, Kernel/Prekernel/boot.S, Userland/Libraries/LibC/arch/x86_64/setjmp.S
Only aarch64 and riscv64 had a few simple to remove text relocations left.
(The riscv64 one actually will cause problems when trying to boot with the EFIPrekernel because the generated textrel is broken for some reason)
=> Kernel: Don't allow text relocations

Userland/Libraries/LibGfx/AffineTransform.h, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibWeb/Painting/AffineDisplayListPlayerCPU.cpp
If we're drawing a transform with a negative scale, we have to go through the slow path since draw_scaled_bitmap() is unable to flip images.
Fixes a regression from the 2nd commit in #24465.
=> LibGfx: Only use draw_scaled_bitmap() fast path when not flipping image

AK/Random.cpp
The algorithm is updated to not require increased word size in the intermediate calculations.
- get_random_uniform_64 is no longer calling into heavy `div_mod_internal`
- get_random_uniform is equivalent to original (on 64-bit targets)
For reference, same calculations as implemented in
- OpenBSD
https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/lib/libc/crypt/arc4random_uniform.c?rev=1.3
- PCG random
https://github.com/imneme/pcg-c/blob/83252d9c23df9c82ecb42210afed61a7b42402d7/include/pcg_variants.h#L848-L861
=> AK: Improve performance of u64 randoms

Meta/run.py
ee891462b84 accidentally changed the path to the Pi 3 devicetree blob to an incorrect one.
=> Meta: Correct the Pi 3 devicetree blob path

Kernel/CMakeLists.txt, Kernel/Devices/GPU/Generic/SimpleFramebuffer.cpp
This "driver" gives us a framebuffer when running in RVVM.
simple-framebuffer nodes describe pre-initialized framebuffers that we can use without any special setup code.
=> Kernel/GPU: Add a simple-framebuffer devicetree driver

Kernel/Net/Realtek/RTL8168NetworkAdapter.cpp
Crash caused by erroneous reading of a few 8bit registers as 32bit, which then asserts. 
This PR allows the OS to boot on a Lenovo Ideapad 700!
=> Kernel/RTL8168: Change invalid u32 mmio reads to u8

Userland/Libraries/LibJS/Parser.cpp, Userland/Libraries/LibJS/Tests/var-scoping.js
Previously it only deoptimized the parent scope if the current scope contains direct eval, which is incorrect because code ran in direct eval mode has access to the entire scope chain it was executed in. The fix is to also propagate direct eval's presence if the current scope is marked as being screwed by direct eval.
This fixes Google's botguard failing to complete on Google sign in, as it tried to access local variables outside of a direct parent function with eval, causing it throw "unhandled" exceptions. Unhandled is in quotes because their bytecode VM _technically_ caught it, but it was considered an unhandled exception. This was determined by removing get optimizations and then adding debug output for every get operation. Using this, I noticed that for these errors, it would access …
=> Cherry-pick "LibJS: Propagate direct eval presence if the current scope is screwed"

Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp, Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.h
For the the jpeg2000 file in object 71 in 0000190.pdf from the PDF dataset (here: 
[out_71.zip](https://github.com/user-attachments/files/18462602/out_71.zip)), before:
```
% Build/lagom/bin/isobmff out_71.jpx  
('jP  ')
- signature = 0x0d0a870a
('ftyp')
- major_brand = 'jp2 '
- minor_version = 0
- compatible_brands = { 'jp2 ', 'jpxb', 'jpx ' }
Unknown Box ('rreq')
[ 22 bytes ]
('jp2h')
('ihdr')
- height = 264
- width = 14
- num_components = 1
- are_components_signed = false
- bits_per_component = 8
- compression_type = 7
- is_colorspace_unknown = 1
- contains_intellectual_property_rights = 0
('colr')
- method = 1
- precedence = 2
- approximation = 1
- enumerated_color_space = 12
('pclr')
[ 627 bytes ]
('cmap')
[ 16 bytes ]
('jp2c')
- codestream = 2448 bytes
```
After:
```
% …
```
=> LibGfx/ISOBMFF: Add JPEG2000PaletteBox

Userland/Services/Taskbar/TaskbarFrame.cpp
To be consistent with WindowServer, the background color should be "button", not "window". This fixes the painting for themes like Nord.
=> Taskbar: Fix applet/clock area background color

Ports/boost/package.sh, Ports/boost/patches/0001-Add-platform-support-for-SerenityOS.patch, Ports/boost/patches/0002-Fix-building-Boost.Interprocess.patch
Boostorg's artifactory instance is down, let's switch to github instead.
=> Ports/boost: Fix download link, fix paths in patches

Userland/Libraries/LibPDF/Parser.cpp
0000337.pdf contains:
/DecodeParms[(null)<</K -1/Columns 2545>>]
where the array's first entry `(null)` is a string with the characters `"null"`. Casting the string to a dict used to crash.
Instead, treat non-dict array entries as if no decode parms were present for the filter at that array position.
This will fix a crash for 0000337.pdf once we can decode /JPXDecode filters.
=> LibPDF: Check DecodeParms array element type before casting

Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp, Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.h
This completes support for all jpeg2000 boxes in I.5.3.
cmap demo, for the file attached to #25656, before:
```
% Build/lagom/bin/isobmff out_71.jpx  
...
('cmap')
[ 16 bytes ]
('jp2c')
- codestream = 2448 bytes
```
After:
```
% Build/lagom/bin/isobmff out_71.jpx  
...
('cmap')
- component_index = 0
- mapping_type = 1
- palette_component_index = 0
- component_index = 0
- mapping_type = 1
- palette_component_index = 1
- component_index = 0
- mapping_type = 1
- palette_component_index = 2
- component_index = 0
- mapping_type = 1
- palette_component_index = 3
('jp2c')
- codestream = 2448 bytes
```
I haven't seen the bpcc box in the wild yet, but it's the only missing box type in I.5.3 and it's similar to to a subset of palette box in I.5.3.4, so maybe the implementation is not completely …
=> LibGfx/ISOBMFF: Add support for jpeg2000 cmap and bpcc boxes

.clang-tidy
This change causes the “readability-implicit-bool-conversion” check to be completely skipped by clang-tidy.
(cherry picked from commit 94a8b635c95270f93d5f8904fe4c73d4df414116)
---
https://github.com/LadybirdBrowser/ladybird/pull/3351
=> Cherry-pick "Meta: Disable clang-tidy “implicit-bool-conversion” check"

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000BitplaneDecoding.h, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.h
This is currently only used in tests. It will be used to decode
the bitplanes in a codeblock, to produce the coefficients that
are inputs to the inverse discrete wavelet transform.
This uses the QMArithmeticDecoder class that's also used in JBIG2 :^)
---
This is enough to decode the example bitplanes in J.10.4 of [T.800.pdf](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.800-201511-S!!PDF-E&type=items), and in a local branch this is part of a full decoder that can decode all jpeg2000 files I've tried so far. (This PR is part of upstreaming that branch.)
The best way to review this would be to read Annex D Coefficient bit modelling once, then focus on "D.8 Flow diagram of the code-block coding" and comparing to that.
This is currently not at all optimized for performance, but …
=> LibGfx/JPEG2000: Implement jpeg2000 bitplane decoding algorithm

Kernel/Arch/aarch64/Exceptions.cpp, Kernel/Arch/aarch64/MMU.cpp, Kernel/Arch/aarch64/PageDirectory.cpp, Kernel/Arch/aarch64/Processor.cpp, Kernel/Arch/aarch64/pre_init.cpp, Kernel/Arch/init.cpp, Kernel/Arch/riscv64/MMU.cpp, Kernel/Arch/riscv64/PageDirectory.cpp, Kernel/Arch/riscv64/Processor.cpp, Kernel/Arch/x86_64/PageDirectory.cpp, Kernel/Arch/x86_64/linker.ld, Kernel/EFIPrekernel/EFIPrekernel.h, Kernel/Firmware/ACPI/Initialize.cpp, Kernel/Firmware/DeviceTree/DeviceTree.cpp, Kernel/Firmware/DeviceTree/DeviceTree.h, Kernel/Firmware/DeviceTree/PlatformInit.cpp, Kernel/KSyms.cpp, Kernel/Memory/MemoryManager.cpp, Kernel/Memory/MemoryManager.h, Kernel/Prekernel/Prekernel.h
This PR includes all kernel changes necessary for making the kernel bootable with the EFIPrekernel.
=> EFI Prekernel (6/N): Kernel: Preparations for booting with the EFIPrekernel

AK/StdLibExtras.h, Tests/AK/TestStdLibExtras.cpp, Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000BitplaneDecoding.h, Userland/Libraries/LibGfx/ImageFormats/JPEG2000InverseDiscreteWaveletTransform.h, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Span2D.h
Only used in tests for now.
This is also written to look close to the spec.
The API is fairly allocation- and copy-heavy. We can improve this later
once everything works and we have solid tests.
Making this testable requires having a few structs that are similar
to some structs internal to JPEG2000Loader.
Also move `Transformation` to the new header file.
=> LibGfx/JPEG2000+AK: Add an implementation of the jpeg2000 IDWT algorithm; add AK::floor_div()

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
This uses the previously landed TagTree, grid coordinate math, progression iterators, bitplane decoding, and IDWT code to implement a working jpeg2000 decoder :^)
We already had code to:
1. (Optional) Decoding an ISOBMFF box container structure.
Used to store metadata such as icc profiles.
2. Decode the jpeg2000 codestream, which consists of several marker segments.
This now also adds these steps:
3. Compute coordinate for all tiles, precincts, resolution levels, components to determine how many code-blocks are in a packet.
4. Decode packet headers to find packet metadata and compressed data, using TagTrees of the right dimension.
5. Run the bitplane decompression algorithm to convert the compressed data into coefficients.
6. Run IDWT algorithm (and some postprocessing) to convert to …
=> LibGfx/JPEG2000: The rest of the owl

Userland/Libraries/LibGUI/FileTypeFilter.h, Userland/Libraries/LibGfx/Bitmap.h, Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.h, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
[LibGfx+LibGUI: Add .jpf to known image extensions](https://github.com/SerenityOS/serenity/commit/50e871724bc3111f0e8a26dfef12bd52f4b9d81b) 
This should have been part of https://github.com/SerenityOS/serenity/commit/f2e381ae19255a7df298476951af2fce58894b5c in https://github.com/SerenityOS/serenity/pull/24016.
The Bitmap.h change has the effect that FileManager now shows a
preview of buggie-gray.jpf when opening
/usr/Tests/LibGfx/test-inputs/jpeg2000.
---
[LibGfx/JPEG2000: Dump ISOBMFF boxes in JPEG2000_DEBUG builds](https://github.com/SerenityOS/serenity/commit/945eb178578aae93024da50f8fba0117fe1fa579)
---
[LibGfx/ISOBMFF/JPEG2000: Add a few known values](https://github.com/SerenityOS/serenity/commit/23e113b192b0eab2793bdb5000050a1dcf6f9ab1) 
...for compression_type and …
=> LibGfx+LibGUI: Small grabbag of jpeg2000-related tweaks

Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn, Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.h, Userland/Libraries/LibGfx/ImageFormats/JPEG2000TagTree.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000TagTree.h
=> LibGfx/JPEG2000: LibGfx/JPEG2000: Move TagTree to its own file, and other minor cleanups

Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
I now think these FIXMEs aren't necessary.
=> LibGfx/JPEG2000: Add two spec comments, and remove two FIXMEs

Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp, Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.h, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp, Userland/Libraries/LibPDF/Filter.cpp
No behavior change. Slowly working towards decoding JPEG2000s in PDFs.
=> LibGfx+LibPDF: Some prep work to become better at color conversion, and a small LibPDF cleanup

Kernel/Arch/x86_64/Hypervisor/BochsDisplayConnector.cpp, Kernel/Arch/x86_64/Hypervisor/BochsDisplayConnector.h, Kernel/Devices/GPU/3dfx/VoodooDisplayConnector.cpp, Kernel/Devices/GPU/Bochs/QEMUDisplayConnector.cpp, Kernel/Devices/GPU/DisplayConnector.cpp, Kernel/Devices/GPU/DisplayConnector.h, Kernel/Devices/GPU/Generic/DisplayConnector.cpp, Kernel/Devices/GPU/Intel/NativeDisplayConnector.cpp, Kernel/Devices/GPU/Management.cpp, Kernel/Devices/GPU/VMWare/DisplayConnector.cpp, Kernel/Devices/GPU/VirtIO/DisplayConnector.cpp, Meta/run.py
This should fix the huge framebuffer performance regression caused by 0d11e70cfeb0a77fcc4cb351d5af5e81209ed1fd.
=> Kernel+Meta: Make the x86 framebuffer fast again

Ladybird/Qt/FindInPageWidget.cpp, Ladybird/Qt/SettingsDialog.cpp
(cherry picked from commit 07400b515c3d8d03bf3d6e35c26ec8a3d7317560; amended to omit change to code added in LadybirdBrowser/ladybird#1497 since we don't have that yet)
---
https://github.com/LadybirdBrowser/ladybird/pull/1807
=> Cherry-pick most of "Qt: Fix -Werror=deprecated-declarations when using Qt > 6.7"

Kernel/API/Syscall.h, Kernel/Arch/x86_64/InterruptManagement.cpp
This definition and the accompanying VERIFY is unnecessary since bfbb4bcd9bd removed support for `int 0x82` syscalls.
=> Kernel: Remove leftovers from x86 software interrupt-based syscalls

Kernel/Arch/aarch64/vector_table.S
This gets rid of the following linker warning:
"warning: vector_table_el1 changed binding to STB_WEAK"
There is no reason for the vector table to be weak. We don't override it anywhere.
=> Kernel/aarch64: Don't make the vector table weak

Meta/Lagom/Contrib/MacPDF/MacPDFWindowController.mm
I broke this in a7fbb7fd0bb02e of #22791.
Almost all of MacPDFWindowController's IBActions are forwarded to `_pdfView`, but `showGoToPageDialog:` isn't and needs to be explicitly handled in `validateMenuItem:`.
---
This not working was bugging me quite a bit. I'm glad I finally figured it out; `git bisect` is the best.
Also a bonus commit that fixes the cause of the weird "keyboard shortcut does not work, but clicking the menu item does" state that "Go to Page…" was in before the first commit in this PR.
=> MacPDF: Unbreak "Go to Page…" keyboard shortcut

Userland/Libraries/LibJS/Runtime/RegExpLegacyStaticProperties.cpp, Userland/Libraries/LibJS/Runtime/RegExpLegacyStaticProperties.h
These properties are always substrings of the RegExp input string, and so we can store them as views and lazily construct strings if they're actually accessed (which most of the time they aren't).
This avoids a bunch of unnecessary memory copying, saving roughly 2.1 seconds per iteration of Speedometer.
(cherry picked from commit dbf52a1b5fa9d7e81816ffc6c5a587c832148bd8)
---
https://github.com/LadybirdBrowser/ladybird/pull/3506
=> Cherry-pick "LibJS: Allocate RegExp.{lastMatch,leftContext,rightContext} lazily"

Kernel/KSyms.cpp
The x86 kernel.map is 6.1 MiB big when building with GCC and ENABLE_EXTRA_KERNEL_DEBUG_SYMBOLS is enabled.
I had this patch applied locally for quite a long time now and didn't want to upstream it.
But solving this properly (instead of hardcoding the size) isn't very easy, since calculating the size needed for the symbol table is a chicken and egg problem.
We could maybe link the kernel multiple times: First with an empty symbol table, then with the symbol table from the first linked kernel and finally replace the section contents with the real symbol table.
But the linker could potentially move things around and cause the symbol table to grow too much.
=> Kernel: Increase the ksyms section size to 8 MiB

README.md
=> Meta: Update the OSS-Fuzz badge URL

Userland/Libraries/LibThreading/BackgroundAction.h
Commits 3 and 4 of https://github.com/LadybirdBrowser/ladybird/pull/3519
Commit 1 is nice too, but doesn't apply cleanly because we don't pass through color spaces yet, like upstream does.
(Commit 2 is upstream-specific.)
=> Cherry-pick some of "ImageDecoder+LibThreading: Fix ImageDecoder memory leaks"

Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.h, Userland/Libraries/LibPDF/Filter.cpp
This allows us to render 000871.pdf correctly!
This means that we no longer have this error when running `test_pdf.py`:
```
Rendering of feature not supported: Unimplemented option for the CCITTFaxDecode Filter, in 1 files, on 11 pages, 11 times
0000/0000871.pdf 1 2 3 4 5 6 7 8 9 10 11
```
And thus go from `829 files without issues (82.9%)` to `830 files without issues (83.0%)`.
=> LibPDF+LibGfx/CCITT: Add support for byte aligned Group4 images

Meta/gn/secondary/Userland/Libraries/LibPDF/BUILD.gn, Userland/Libraries/LibPDF/CMakeLists.txt, Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Shading.cpp, Userland/Libraries/LibPDF/Shading.h
Adds a `Shading` class, which is supposed to be implemented similarly to LibPDF's ColorSpace class: `Shading::create()` will return a Shading subclass for every shading type, and they'll all implement some future pure virtual method for drawing the shading.
Shadings are used with both the `sh` operator and as part of pattern color spaces. We don't implement the latter yet either, and `Shading` will assume that its used with the `sh` operator for now.
For now, `Shading::create()` returns a `rendering_unsupported_error` for every shading type, so this commit doesn't do a whole lot. It does produce different errors for different shading types though, making it possible to see which shading types are common.
It also removes the last use of `RENDERER_TODO`, so remove that :^)
=> LibPDF: Add some scaffolding for the `sh` operator

Userland/Libraries/LibGfx/Forward.h, Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Function.cpp, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Shading.cpp, Userland/Libraries/LibPDF/Shading.h
Or, as they're called elsewhere, linear gradients.
Since this uses PDF function objects and PDF color spaces, it can't use
the existing gradient code in LibGfx.
The way shadings are drawn with the `sh` operator is that one sets a
clip path that's to be filled with the shading and the calls the `sh`
operator.
However, we only support clip rects at the moment, not yet arbitrary
clip paths. So this leads to rectangles with linear gradients
appearing, which sometimes can overlap other page elements. This will
improve once we implement support for arbitrary clip paths.
This is also still missing support for the optional additional /BBox
shading dict entry, which further constrains the clip rect.
Also improve `StitchingFunction` a bit, since that's heavily used with axial shadings to create …
=> LibPDF: Implement painting of axial shadings; stitching function improvements

Kernel/Arch/Processor.h, Kernel/Arch/aarch64/Processor.h, Kernel/Arch/riscv64/Processor.h, Kernel/Arch/x86_64/PageDirectory.h, Kernel/Arch/x86_64/Processor.h
PAT is an x86-specific feature, so it doesn't make sense to have that function for all processor classes.
The only current user of this function can instead check for `CPUFeature::PAT` directly.
=> Kernel: Remove `Processor::has_pat()`

Userland/Libraries/LibHID/ReportDescriptorParser.cpp, Userland/Libraries/LibHID/ReportDescriptorParser.h
Calling the `Collection` destructor otherwise can end up causing a stack overflow, as each `Collection` destructor will recursively call the destructor of each child collection.
This fixes the following OSS-Fuzz issue:
https://issues.oss-fuzz.com/issues/397488020
=> LibHID: Limit the maximum collection tree depth

Kernel/Arch/riscv64/MMU.cpp, Kernel/Arch/riscv64/PageDirectory.h, Kernel/Arch/riscv64/VirtualMemoryDefinitions.h, Kernel/Arch/riscv64/linker.ld, Kernel/Arch/riscv64/pre_init.cpp, Kernel/CMakeLists.txt, Kernel/EFIPrekernel/Arch/Boot.h, Kernel/EFIPrekernel/Arch/MMU.h, Kernel/EFIPrekernel/Arch/aarch64/Boot.cpp, Kernel/EFIPrekernel/Arch/aarch64/MMU.cpp, Kernel/EFIPrekernel/Arch/riscv64/Boot.cpp, Kernel/EFIPrekernel/Arch/riscv64/MMU.cpp, Kernel/EFIPrekernel/Arch/x86_64/Boot.cpp, Kernel/EFIPrekernel/Arch/x86_64/MMU.cpp, Kernel/EFIPrekernel/CMakeLists.txt, Kernel/EFIPrekernel/ConfigurationTable.cpp, Kernel/EFIPrekernel/ConfigurationTable.h, Kernel/EFIPrekernel/Relocation.cpp, Kernel/EFIPrekernel/Relocation.h, Kernel/EFIPrekernel/VirtualMemoryLayout.h, Kernel/EFIPrekernel/init.cpp, Kernel/Firmware/EFI/SystemTable.h, Userland/Libraries/LibELF/Relocation.cpp, Userland/Libraries/LibELF/Relocation.h
This adds all the remaining code necessary to actually boot the kernel.
This only works on riscv64 for now (as booting the RISC-V kernel is the easiest).
GOP, x86-64, and AArch64 support will be in a future PR.
I didn't add any build/run scripts (yet), so you have to run it manually like so:
- Build a RISC-V image like normal with `Meta/serenity.sh image riscv64`
- Build U-Boot (EDK2 doesn't provide a devicetree configuration table but we need one)
- `git clone https://source.denx.de/u-boot/u-boot.git --depth 1 --branch v2025.01; cd u-boot`
- `make CROSS_COMPILE=riscv64-linux-gnu- qemu-riscv64_smode_defconfig`
- `make CROSS_COMPILE=riscv64-linux-gnu- -j$(nproc)`
- Run QEMU with U-Boot as the firmware:
`qemu-system-riscv64 -M virt -kernel <u-boot file> -m 2G -drive …
=> EFI Prekernel (7/N): EFIPrekernel: Make it boot the RISC-V kernel

Kernel/Arch/init.cpp, Kernel/Arch/x86_64/Boot/ap_setup.S, Kernel/Prekernel/Arch/x86_64/ArchSpecificBootInfo.h, Kernel/Prekernel/init.cpp
The AP setup code no longer uses the Prekernel GDT, so these variables and arch-specific boot info members are unnecessary.
=> Kernel/x86: Remove `gdt64ptr` and `code64_sel`

Kernel/Arch/x86_64/ISABus/I8042Controller.cpp
On reset request the controller first sends an ack and only then actually resets. My guess is that on fast resets we ended up missing this ack. On slower controllers we need to handle this ack appropriately
=> Kernel: Properly parse ACK to PS2 reset

Kernel/Arch/x86_64/Interrupts/IOAPIC.cpp, Kernel/Arch/x86_64/PCI/MSI.cpp
On Meteor Lake it has id 0x20 and interrupts end up nowhere without
this patch
=> Kernel: Don't assume that bsp has ID 0

Userland/Applications/PixelPaint/Tools/GradientTool.cpp, Userland/Applications/PixelPaint/VectorscopeWidget.cpp, Userland/Libraries/LibGfx/AntiAliasingPainter.cpp, Userland/Libraries/LibGfx/Rect.h
I have chosen `centered_on` to prevail for it is the older one.
=> LibGfx+PixelPaint: Unify `Rect::centered_at` and `Rect::centered_on`

Kernel/EFIPrekernel/CMakeLists.txt, Kernel/EFIPrekernel/GOP.cpp, Kernel/EFIPrekernel/GOP.h, Kernel/EFIPrekernel/init.cpp
The GOP framebuffer (if present) is passed to the kernel so it can use it as the boot framebuffer.
=> EFIPrekernel: Add GOP support

Kernel/Heap/kmalloc.cpp, Kernel/Memory/MemoryManager.cpp
On my darp10-b the memory map ends up breaking the early init routines. Here are the fixes
=> Kernel: Support Meteor Lake memory map

Meta/CMake/utils.cmake
Appending "id_" to the datetime part gives you a raw copy without the navigational toolbar:
https://en.wikipedia.org/wiki/Help:Using_the_Wayback_Machine#Specific_archive_copy
Otherwise we get an HTML file.
This should prevent the PNP download from failing CI when uefi.org is down again.
=> Meta: Use the raw archive.org copy for the download_file fallback

Meta/shell_include.sh
This effectively keeps a failing `du --help` from printing user-visible messages.
=> Meta: Merge errors from `du --help` into stdout

Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
I missed to do this in #25734.
No behavior change, just an optimization.
=> LibGfx/JPEG2000: Do not run bit depth conversion for 8 bpp channels

Userland/Libraries/LibPDF/DocumentParser.cpp, Userland/Libraries/LibPDF/Parser.h
`parse_value()` expects to start on the value.
It's a bit surprising that the object_offset in the compressed stream would point at whitespace instead of the value directly, but it seems to happen in at least one file: This allows us to open 0001215.pdf from the CC-MAIN-2021-31-PDF-UNTRUNCATED test corpus.
=> LibPDF: Skip whitespace before values in compressed stream

Tests/LibC/TestEnvironment.cpp, Userland/Libraries/LibC/stdlib.cpp
Hi, I tried SerenityOS with [my C project](https://github.com/matyalatte/c-env-utils) today.
A unit test found that `setenv` accepted an empty string as a variable name.
I think this is unexpected behavior since `unsetenv` rejects empty strings.
=> LibC: Disallow environment variable names that are empty or contain '='

Tests/LibPDF/colorspaces.pdf, Userland/Libraries/LibPDF/Document.cpp
add_page_tree_node_to_page_tree() had a heuristic where it would decide that a page tree node where number of items in the /Kids array was equal of the number of total children stored in /Count in that same node must be the final non-leaf level of the page tree.
That seems sensible, but it is e.g. possible to have a page tree node that has one kid and one page tree node total below it. Such a node isn't useful, but it can exist, and it does exist e.g. in 0000037.pdf page 37:
```
505 0 obj
<<
/Type /Pages
/Count 37
/Kids [ 503 0 R 504 0 R ]
>>
endobj
504 0 obj
<<
/Type /Pages
/Count 1
/Parent 505 0 R
/Kids [ 467 0 R ]
>>
endobj
467 0 obj
<<
/Type /Pages
/Count 1
/Parent 504 0 R
/Kids [ 464 0 R ]
>>
endobj
```
Object 504 is useless here and object 505 could just reference object 467 …
=> LibPDF: Remove incorrect page tree heuristic

Userland/Services/ImageDecoder/ConnectionFromClient.cpp
This fixes the crash in FileManager, when a thumbnail couldn't be generated.
=> Services/ImageDecoder: Return an error if no frame was decoded

Userland/Libraries/LibJS/SyntaxHighlighter.cpp, Userland/Libraries/LibJS/Token.h, Userland/Libraries/LibWebView/SourceHighlighter.cpp
Trivia is whatever whitespace and comments appear before a token. Previously this was always given a TokenCategory of Invalid, so it would be displayed as an error in the view-source page, with red wiggly underlines. Instead, treat it as what it actually is: whitespace and comments!
(cherry picked from commit 9b7fb0850d952ceedca693cb65456cd00ee33389)
---
https://github.com/LadybirdBrowser/ladybird/pull/3803
=> Cherry-pick "LibJS+LibWebView: Treat trivia tokens as comments"

Kernel/Bus/USB/xHCI/PCIxHCIController.cpp
Otherwise, MMIO accesses will not work if these bits weren't already set.
=> Kernel/xHCI: Enable memory space accesses before trying to access MMIO

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
I realized that I didn't upstream my last work on modular images, so instead of making progress in this area, I decided to work on VarDCT. More specifically, I worked on [this](https://github.com/libjxl/conformance/blob/master/testcases/bike/input.jxl) conformance test.
The image is composed of two frames, one kReferenceOnly (modular) and one kNormalFrame (VarDCT). With these commits, we can decode everything until the VarDCT-specific data in the LfGlobal of the second frame.
=> LibGfx/JPEGXL: VarDCT-related progress

Userland/Services/ImageDecoder/ConnectionFromClient.cpp
Manual cherry-pick of the second change in aa521c8e@ladybird [1], the first part was already done independently in this repo in b499dc18.
[1] https://github.com/LadybirdBrowser/ladybird/pull/3519/commits/aa521c8ec5bd11d2b2ec67ed222b43024991f4d9
=> Services/ImageDecoder: Move bitmaps instead of copying them

Userland/Libraries/LibC/stdlib.cpp
I noticed that `clearenv` did not free resources allocated by `setenv`.
=> LibC: Free variables with clearenv()

Kernel/Devices/Storage/StorageManagement.cpp
m_storage_devices might be empty if USB devices weren't detected yet
(USB devices are probed asynchronously in a separate kernel process).
The code already handles cases were m_storage_devices is empty.
This also causes us to print a nicer panic message when no storage
devices were found.
Similarly, s_storage_device_minor_number might be non-zero if storage
devices were constructed before this VERIFY. The Atomic constructor
already ensures this variable is initially zero.
The !m_controllers.is_empty() VERIFYs fail if only USB drives are
attached, since we don't create StorageControllers for those.
The m_controllers.is_empty() assertion shouldn't cause any issues
currently, but it also shouldn't be necessary.
Removing these VERIFYs should make booting from USB more reliable.
I also …
=> Kernel: Remove some unnecessary VERIFYs from StorageManagement

Base/res/apps/ImageViewer.af, Userland/Libraries/LibGfx/Bitmap.h
I first tried doing this in the second commit of #24016, but I only updated LibCore/MimeData.cpp there.
I then tried to update Bitmap.h in the first commit of #25671 but gave it type `jpeg` instead of `jpeg2000`. Fix that. (That commit did successfully update FileTypeFilter.h though!)
And I forgot to update ImageViewer.af, so do this too.
With this, double-clicking a jpf file in File Manager now opens the image in Image View instead of in Text Editor :^)
=> LibGfx+Base: Try harder to add .jpf to known image extensions

Base/res/apps/PixelPaint.af
Allows "Open With>Pixel Paint" in the context menu for these file extensions in File Explorer.
=> Base: Add ilbm, jbig2, jpeg2000, tiff to Pixel Paint file type list

Ports/ca-certificates/package.sh
Some ports (e.g. wget and python3) do not read `/etc/ssl` with the default settings.
They work fine if there is a symlink to `ca-certificates.crt` in `/usr/local/ssl`.
I confirmed that Ubuntu24.04 used the same workaround.
I also confirmed that SerenityOS can now build [my meson project](https://github.com/matyalatte/c-env-utils) which uses python's ssl module to download GoogleTest.
=> Ports/ca-certificates: Create symlinks in /usr/local/ssl

Userland/Utilities/ln.cpp
I noticed that the ncurses port used `ln -svf` but SerenityOS didn't support it.
https://github.com/SerenityOS/serenity/blob/175697ac207664be7886900bcd5796c11aae678c/Ports/ncurses/package.sh#L79
You can use the `-v` flag now.
(edit)
Sorry, I accidentally merged the master branch here. I’ve fixed it now.
=> Utilities/ln: Add verbose option

Base/res/apps/TextEditor.af
As suggested by nico in #25756.
=> TextEditor: Add gmi to TextEditor file type list

Kernel/FileSystem/BlockBasedFileSystem.cpp, Kernel/FileSystem/BlockBasedFileSystem.h, Kernel/FileSystem/Ext2FS/FileSystem.cpp, Kernel/FileSystem/ISO9660FS/FileSystem.cpp
This breaks the reference cycle between BlockBasedFileSystem and DiskCache, which means that filesystem drivers no longer need to call `remove_disk_cache_before_last_unmount` in order to get destroyed. I've confirmed that this is now the case with both loop device and block device-backed instances of FATFS.
Fixes #25761.
CC @spholz (also, thanks for debugging the reference cycle!)
=> Kernel: BlockBasedFilesystem cleanup

Userland/Libraries/LibC/CMakeLists.txt
This prevents flaky "cannot find -lubsan: No such file or directory" error.
=> LibC: Add missing dependency on LibUBSanitizer

Documentation/ClangdConfiguration.md, Documentation/EmacsConfiguration.md, Documentation/HelixConfiguration.md, Documentation/NvimConfiguration.md, Documentation/README.md, Documentation/VSCodeConfiguration.md
These were previously spread over multiple editor documentation files, so we consolidate them into one while dropping outdated (or unexplained) options. A new ClangdConfiguration file is created that will house the common config.
Furthermore, since clangd 20 supports the header style options (implemented by yours truly), document that this feature is now available and what AngledHeaders globs to use for Serenity specifically.
=> Documentation: Consolidate and extend clangd configuration docs

Kernel/Arch/aarch64/PSCI.cpp, Kernel/Arch/aarch64/PSCI.h, Kernel/Arch/aarch64/PowerState.cpp, Kernel/CMakeLists.txt
I'm not too familiar with the Aarch64 platform in general, but with this PR, it's now possible to shut down and reboot the QEMU virt machine, at least when running under HVF.
=> Kernel/aarch64: Add basic support for PSCI and HVC calls

Kernel/Arch/Processor.h, Kernel/Arch/ProcessorFunctions.include, Kernel/Arch/aarch64/Processor.cpp, Kernel/Arch/riscv64/Processor.cpp, Kernel/Arch/x86_64/Processor.cpp, Kernel/Memory/Region.cpp
Clang compiles that builtin to an abort for freestanding environments because RISC-V does not have an instruction to the flush the instruction cache for all harts.
We don't support SMP on RISC-V currently, so simply use a `fence.i` for now.
=> Kernel/riscv64: Don't use __builtin___clear_cache on RISC-V

Kernel/KSyms.cpp
c0d70a6e24 made the kernel linked at address zero, but forgot to change the symbol address calculation accordingly.
=> Kernel/riscv64: Correctly calculate symbol addresses again

Ports/AvailablePorts.md, Ports/fribidi/package.sh
This is a reworked version of #22963.
It has the following changes from the first PR.
- Upgraded the version number from 1.0.13 to 1.0.16.
- No patches. (I noticed that `-Dc_args=-std=c99` was able to overwrite the `-ansi` flag.)
- Enabled release build.
- Disabled tests and docs.
I confirmed that I was able to build cairo and pango (which used fribidi) without subproject fallbacks.
(edit)
Sorry, I forgot to change the permission of package.sh. I've fixed it now.
=> Ports: Add fribidi

CMakeLists.txt, Documentation/AdvancedBuildInstructions.md, Documentation/RunningOnRaspberryPi.md, Kernel/CMakeLists.txt, Meta/build-image-raspberry-pi.sh, Meta/run.py
This should make running serenity on Raspberry Pis easier.
Note that at least on my Raspberry Pi 3 and 4, we currently fail to initialize the SD card:
```
FIXME: The SD Host Controller does not provide the base clock frequency; get this frequency using another method
```
=> Meta: Add a script for building Raspberry Pi 3 and 4 images

Kernel/Arch/aarch64/Time/PL031.cpp, Kernel/Arch/aarch64/Time/PL031.h, Kernel/CMakeLists.txt, Kernel/Time/TimeManagement.cpp
With this, it's now possible to properly set the system time on boot when using the QEMU virt machine.
=> Kernel/aarch64: Add support for the PL031

Kernel/Arch/init.cpp, Kernel/Arch/riscv64/InterruptManagement.cpp, Kernel/Arch/riscv64/InterruptManagement.h, Kernel/Arch/riscv64/Interrupts/PLIC.cpp, Kernel/Arch/riscv64/Interrupts/PLIC.h, Userland/Libraries/LibDeviceTree/DeviceTree.cpp, Userland/Libraries/LibDeviceTree/DeviceTree.h
The JH7110/U74-MC (used in the VisionFive 2) uses hart ID 0 for the S7 monitor core, which can't run a general purpose OS, so the boot hart ID is 1 on that system.
=> Kernel/riscv64: Support systems where the boot hart ID isn't 0 

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Before these patches, we would raise an error when trying to decode the channels in the GlobalModular section, we now realize that there is no work to do there and crash on a TODO a little bit further.
In terms of log, before:
```cpp
Decoding a JPEG XL image with size 555x751 and 3 channels.
Frame: 555x751 Modular - type(0) - flags(0) - is_last
Decoding modular sub-stream (global tree, 1 transforms):
- Channel 0: 555x751
- Channel 1: 555x751
- Channel 2: 555x751
JPEGXLLoader: ANS decoder left in invalid state
Runtime error: Reached end-of-stream without collecting the required number of bits
```
After:
```cpp
Decoding a JPEG XL image with size 555x751 and 3 channels.
Frame: 555x751 Modular - type(0) - flags(0) - is_last
Decoding modular sub-stream (global tree, 1 transforms):
* Palette: …
```
=> LibGfx/JPEGXL: Enough work on the decoder to reach the point where it sees there is no work to do in the GlobalModular section

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000Loader.cpp
We still don't support CIELab and CIEJab, but now we fail with
a nicer error message.
Before:
% Build/lagom/bin/image -o tmp.webp \
Tests/LibGfx/test-inputs/jpeg2000/kakadu-lossless-lab-u*.jp2
Reader did not consume all data for box type 'colr',
28 bytes remaining
Runtime error: Reader did not consume all data
After:
% Build/lagom/bin/image -o tmp.webp \
Tests/LibGfx/test-inputs/jpeg2000/kakadu-lossless-lab-u*.jp2
Runtime error: JPEG2000ImageDecoderPlugin:
Only sRGB, grayscale, and CMYK enumerated color spaces
supported yet
This _does_ have the effect of `JPEG2000ImageDecoderPlugin::create()`
now succeeding for these files, and only `frame()` on the plugin
failing. That means e.g. that `file` can now print the dimensions
of a CIELab JPEG2000 file, and `test_jpeg2000_decode_unsupported` …
=> LibGfx/JPEG2000: Read EP field for CIELab and CIEJab

AK/IntegralMath.h, Userland/Libraries/LibAudio/FlacLoader.cpp, Userland/Libraries/LibAudio/FlacLoader.h, Userland/Libraries/LibDisassembly/CMakeLists.txt, Userland/Libraries/LibDisassembly/Disassembler.h, Userland/Libraries/LibDisassembly/riscv64/Encoding.cpp, Userland/Libraries/LibDisassembly/riscv64/Encoding.h, Userland/Libraries/LibDisassembly/riscv64/Formatting.cpp, Userland/Libraries/LibDisassembly/riscv64/Formatting.h, Userland/Libraries/LibDisassembly/riscv64/IM.cpp, Userland/Libraries/LibDisassembly/riscv64/IM.h, Userland/Libraries/LibDisassembly/riscv64/Instruction.cpp, Userland/Libraries/LibDisassembly/riscv64/Instruction.h, Userland/Libraries/LibDisassembly/riscv64/Registers.h, Userland/Libraries/LibGfx/ImageFormats/ISOBMFF/JPEG2000Boxes.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp, Userland/Libraries/LibHID/ReportParser.cpp, Userland/Libraries/LibJS/Runtime/Value.h
As per popular request, #21540 is being split up to be easier to review. This is probably the smallest I can make the initial work without leaving a ton of dead code.
Actually, this is RV64IMZifencei and RV32IMZifencei:
- As per RISC-V, RV64I of course includes RV32I
- The M extension is not separable in a good way since it just adds more arithmetic instructions that are represented in a common class with other I instructions.
- Zifencei is just one instruction (FENCE.I) that doesn't need its own file.
=> LibDisassembly: RISC-V disassembly 4-1/4-5: Disassemble base ISA

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
The first commit, while being a bugfix for multi-frame images like VarDCT ones, is used as a refactoring commit here. It's just easier to get access to GlobalModular's decoder when it's stored in the GlobalModular struct.
With the same image as in #25819, it gives this output:
```cpp
Decoding a JPEG XL image with size 555x751 and 3 channels.
Frame: 555x751 Modular - type(0) - flags(0) - is_last
TOC: index |  size | offset
0 |  3359 |      0
1 |     0 |   3359
2 |     0 |   3359
3 | 14052 |   3359
4 | 17154 |  17411
5 |  1952 |  34565
6 | 19462 |  36517
7 | 20323 |  55979
8 |  2859 |  76302
9 | 12377 |  79161
10 | 13920 |  91538
11 |  2404 | 105458
Decoding modular sub-stream (global tree, 1 transforms):
* Palette: begin_c=0 - num_c=3 - nb_colours=0 - nb_deltas=0 - d_pred=13
- Channel 0: …
```
=> LibGfx/JPEGXL: General bugfixes for the decoder :^)

Kernel/Arch/aarch64/RPi/MiniUART.cpp
This gets rid of the "bcm2835_aux_write: Bad offset 64" QEMU warning while we attempt to set the baud rate.
=> Kernel/aarch64: Correct the RPi Mini UART register map

Kernel/Arch/aarch64/RPi/Timer.cpp, Kernel/Arch/aarch64/RPi/Timer.h, Kernel/Arch/aarch64/Time/ARMv8Timer.cpp, Kernel/Arch/aarch64/Time/ARMv8Timer.h, Kernel/Time/TimeManagement.cpp
AArch64 already implements `monotonic_time(TimePrecision::Precise)`, but
didn't advertise support for it by setting `m_can_query_precise_time`.
This causes SystemMonitor to no longer claim that all CPU time is spent
in the kernel.
This PR basically is basically #25821 ported to AArch64.
=> Kernel/aarch64: Make TimePrecision::Precise work (+resolve some TODO_AARCH64s in the timer drivers)

Kernel/Bus/PCI/Controller/HostController.cpp
These configuration space registers are 16-bit.
=> Kernel/PCI: Use correct access width during PCI-to-PCI bridge setup

Userland/Libraries/LibGfx/ImageFormats/JPEGXLChannel.h, Userland/Libraries/LibGfx/ImageFormats/JPEGXLEntropyDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGXLEntropyDecoder.h, Userland/Libraries/LibGfx/ImageFormats/JPEGXLICC.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
This allows us to progress a lot on the same test image as #25819, we are now able to reach the end of the bitstream without an error! We now crash on a TODO in `apply_transformation()` because we don't still don't know how to apply the inverse palette transform.
New log:
```cpp
Decoding a JPEG XL image with size 555x751 and 3 channels.
Frame: 555x751 Modular - type(0) - flags(0) - is_last
TOC: index |  size | offset
0 |  3359 |      0
1 |     0 |   3359
2 |     0 |   3359
3 | 14052 |   3359
4 | 17154 |  17411
5 |  1952 |  34565
6 | 19462 |  36517
7 | 20323 |  55979
8 |  2859 |  76302
9 | 12377 |  79161
10 | 13920 |  91538
11 |  2404 | 105458
Decoding modular sub-stream (global tree, 1 transforms, stream_index=0):
* Palette: begin_c=0 - num_c=3 - nb_colours=0 - nb_deltas=0 - d_pred=13
- …
```
=> LibGfx/JPEGXL: Read pass groups and two other bug fixes

Kernel/Arch/riscv64/CSR.h, Kernel/Arch/riscv64/Delay.cpp, Kernel/Arch/riscv64/Interrupts/PLIC.cpp, Kernel/Arch/riscv64/Processor.cpp, Kernel/Arch/riscv64/Processor.h, Kernel/Arch/riscv64/SmapDisabler.cpp, Kernel/Arch/riscv64/Timer.cpp, Kernel/Arch/riscv64/pre_init.cpp, Kernel/Memory/MemoryManager.h, Kernel/Memory/PhysicalRAMPage.h, Kernel/Syscalls/SyscallHandler.cpp
The `[[gnu::packed]] alignas(u64)` where a no-op, and the SATP
comparator is just the default one
* The CSR address is now mandated to be a compile time constant as a
template argument, so we don't rely on inlining to make it a constant,
which caused compilation failures in the past.
* `CSR::[set|clear]_bits` now acts on enums which makes them a bit
easier to use.
* SSTATUS now provides a pre-shifted Bit enum instead of an Offset one
making that safer/easier to use.
* SIE reading/writing in now decoupled from the SCAUSE enum, removing
some bit-fiddling in some places
* Added the remaining SCAUSE/SIE values
It already takes a `FlatPtr` so no need to c-cast it to one...
=> Kernel/riscv64: Clean up the CSR interface a bit + drive-by stuff

Kernel/Devices/Input/HID/KeyboardDriver.cpp
Since 7a7e77cc4b, the bitmap array is only 4 elements big, meaning that we only accepted keys with a usage ID below 4.
This should make the HID keyboard driver work again.
(apparently I totally forgot to test this, oops)
=> Kernel/Input: Correct the HID keyboard driver usage ID range check

Tests/LibGfx/TestImageDecoder.cpp
Here is the log when decoding `icc.jxl`:
```
Decoding a JPEG XL image with size 32x32 and 3 channels.
Frame: 32x32 Modular - type(0) - flags(0) - is_last
TOC: index |  size | offset
0 |    33 |      0
Decoding modular sub-stream (global tree, 1 transforms, stream_index=0):
* Palette: begin_c=0 - num_c=3 - nb_colours=2 - nb_deltas=0 - d_pred=0
- Channel 0: 2x3
- Channel 1: 32x32
Discarding 0 remaining bytes
```
=> Tests/LibGfx: A JPEG XL palette test sooner than expected

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
This would otherwise lead to wrong results for an image of [64x138] with a group_dim of 128.
=> LibGfx/JPEGXL: Correctly compute groups' y index from the group index

Tests/LibPDF/shade-coons.pdf, Tests/LibPDF/shade-tensor.pdf
We can neither parse nor draw these yet.
Also, they're very basic, they're both just a single patch.
Both contain a patch with a direct color, and a patch with a (nonlinear) function object for the color.
=> Tests/LibPDF: Add a shading type 6 and 7 test file each

Kernel/Arch/aarch64/PlatformInit.h, Kernel/Arch/aarch64/PlatformInit/RaspberryPi.cpp, Kernel/Arch/aarch64/RPi/Mailbox.cpp, Kernel/Arch/aarch64/RPi/Mailbox.h, Kernel/Firmware/DeviceTree/PlatformInit.cpp
These changes are enough to make us reach the "Couldn't find a suitable device to boot from" panic on the Pi 5.
=> Kernel/aarch64: Add basic Raspberry Pi 5 support

Kernel/Bus/USB/Drivers/HID.cpp
This previous check would always return `{}` after it found and initialized an hid interface from any USB device, since m_hid_interfaces is a member of the driver, not the device.
The HID driver should now only be attached to HID devices.
=> Kernel/USB: Correct the HID driver probe success check

Kernel/Interrupts/UnhandledInterruptHandler.cpp
Interrupt handlers don't take a `RegisterState` anymore since 0482f4e1170.
=> Kernel: Remove reference to RegisterState from UnhandledInterruptHandler

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
It makes it a bit easier to work on images with multiple frames:
```cpp
Decoding a JPEG XL image with size 1600x1096 and 4 channels.
Frame: 198x198 Modular - ReferenceOnly - flags(0)
TOC: index |  size | offset
0 | 14407 |      0
Decoding modular sub-stream (global tree, 4 transforms, stream_index=0):
* Palette: begin_c=0 - num_c=1 - nb_colours=181 - nb_deltas=0 - d_pred=0
* Palette: begin_c=2 - num_c=1 - nb_colours=186 - nb_deltas=0 - d_pred=0
* Palette: begin_c=4 - num_c=1 - nb_colours=184 - nb_deltas=0 - d_pred=0
* Palette: begin_c=3 - num_c=4 - nb_colours=326 - nb_deltas=0 - d_pred=0
- Channel 0: 326x4
- Channel 1: 184x1
- Channel 2: 186x1
- Channel 3: 181x1
- Channel 4: 198x198
Discarding 0 remaining bytes
Frame: 1600x1096 Modular - RegularFrame - flags(2) - is_last
[...]
```
=> LibGfx/JPEGXL: Add a custom formatter for FrameHeader::FrameType

Meta/serenity_gdb.py
The variable `elements` is never reassigned in this scope.
flake8 started warning about unused global/nonlocal statements since https://github.com/PyCQA/pyflakes/commit/cadcd60a70c118c1d8b6dc8c09e53dc8f32b1666.
This should fix CI, since we apparently don't pin our flake8 version and fail the lint even if the affected files weren't touched.
=> Meta: Remove unnecessary nonlocal from serenity_gdb.py

Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.h, Userland/Utilities/image.cpp
The flag can be used to force the presence of an alpha channel in the encoded image. This is only supported by the PNG encoder for the moment.
=> image+LibGfx/PNG: Add a --force-alpha flag

Userland/Libraries/LibGfx/ImageFormats/TGALoader.cpp
* Replace `byte_count() > 0` with `!is_empty()`
* Add FIXME for non-utf8 identifiers
Follow up to: #25870
=> LibGfx/TGALoader: A couple of minor fixups (NFC)

Tests/AK/TestSyncGenerator.cpp
Both #25740 and #25865 passed CI on their own, but when we merged both, TestSyncGenerator started failing.
For now, just update the test to green up CI.
=> Tests: Make TestSyncGenerator pass after constexpr Optional

AK/ByteBuffer.h
This fixes the following warning caused by the call to `ByteBuffer::overwrite` in https://github.com/SerenityOS/serenity/blob/93ca4bc9d1a4fb9db21c3d26fb93e238476016f6/Userland/Libraries/LibCrypto/Hash/PBKDF2.h#L57 "error: writing 64 bytes into a region of size 48"
It seems like GCC incorrectly thinks that the ByteBuffer is using the inline storage in that case.
This error doesn't appear in CI since it enables UBSan.
=> AK: Silence false positive -Wstringop-overflow GCC warning in ByteBuffer

Ports/AvailablePorts.md, Ports/cairo/package.sh
We can build Cairo without patches. (However, #25795 should be merged first since Cairo uses `scanf` to parse strings.)
I confirmed that an example code worked fine.
```c
#include <cairo/cairo.h>
int main() {
int width = 400, height = 300;
// Create a Cairo surface and context
cairo_surface_t *surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
cairo_t *cr = cairo_create(surface);
// Set background color to white
cairo_set_source_rgb(cr, 1, 1, 1);
cairo_paint(cr);
// Draw a rectangle with a blue fill
cairo_set_source_rgb(cr, 0, 0, 1);
cairo_rectangle(cr, 50, 50, 200, 100);
cairo_fill(cr);
// Draw a red circle
cairo_set_source_rgb(cr, 1, 0, 0);
cairo_arc(cr, 200, 150, 50, 0, 2 * 3.1416);
cairo_fill(cr);
// Draw a black line
cairo_set_source_rgb(cr, 0, 0, 0); …
```
=> Ports: Add cairo

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
This makes clang-format produce a way nicer output.
---
Can't live without it, now that you showed me that @nico.
=> LibGfx/JPEGXL: Add a comma at the end of designated initializer lists

Ports/qt6-qtbase/package.sh, Ports/qt6-qtsvg/package.sh
from https://download.qt.io/official_releases/qt
to https://download.qt.io/archive/qt
#25774
=>  Ports/qt6-qtbase and Ports/qt6-qtsvg: Change the URLs from official_releases to archive

Ports/harfbuzz/package.sh
I added `BUILD_SHARED_LIBS=ON` to cmake options since I got the "recompile with -fPIC" errors while building pango.
```
.../libharfbuzz.a(harfbuzz.cc.o): relocation R_X86_64_PC32 against symbol `_ZN11hb_buffer_t19_cluster_group_funcERK15hb_glyph_info_tS2_' can not be used when making a shared object; recompile with -fPIC
```
I also fixed `configure()` since `sh -c "cd build && cmake .. ${configopts[@]}"` ignored cmake options except for `CMAKE_TOOLCHAIN_FILE`.
I confirmed that the `SuperTuxKart` port and pango worked fine with this PR.
=> Ports/harfbuzz: Enable optimized shared build

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
These patches allow us to decode `grayscale_public_univeristy` from the `libjxl/conformance` repo.
Note that it is not perfect yet, as we don't decode `ModularLFGroup`s and we don't apply restorations filters. The image has two `ModularLFGroup`s that compose one residual channel from the squeeze transform (a Haar-like transform). I just left the channel zero-initialized.
Still, this is what we get now:
And this is the original:
=> LibGfx/JPEGXL: Progress on libjxl/conformance

Tests/LibPDF/shade-coons.pdf, Userland/Libraries/LibPDF/Shading.cpp
We now create an CoonsPatchShading object and read all required
parameters and build objects for them, but we don't use them for any
rendering yet.
=> LibPDF: Read coons patch mesh shading dict entries

Tests/LibPDF/shade-tensor.pdf, Userland/Libraries/LibPDF/Shading.cpp
We now create an TensorProductPatchShading object and read all required
parameters and build objects for them, but we don't use them for any
rendering yet.
---
We can now parse all shading types :^)
(We still can't paint shading types 4-7 though.)
This file has some duplication. Once we can paint everything and check we don't regress things, I'll factor out some of the common bits.
=> LibPDF: Read tensor-product patch mesh shading dict entries

Ports/pixman/patches/0001-libtool-Enable-shared-library-support-for-SerenityOS.patch, Ports/pixman/patches/ReadMe.md
Related to https://github.com/SerenityOS/serenity/pull/14178.
I noticed that `configure` disabled the shared build for pixman, so I made the libtool patch the same way as in other ports.
I confirmed that shared build was enabled in `config.log`.
```
configure:13089: checking if libtool supports shared libraries
configure:13091: result: yes
configure:13094: checking whether to build shared libraries
configure:13119: result: yes
```
=> Ports/pixman: Import the libtool patch

Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGWriter.h
Using [this](https://github.com/libjxl/conformance/blob/master/testcases/grayscale_public_university/ref.png) test image, it reduces its size from 2.3 MB to 1.5 MB, a nice 33% improvement :^)
=> LibGfx/PNG: Write grayscale images when sufficient

Userland/Libraries/LibC/utime.h
<sys/types.h> declares the `utimbuf` struct used by this header.
Fixes #25899
=> LibC: Add missing include in utime.h

Userland/Libraries/LibDisassembly/CMakeLists.txt, Userland/Libraries/LibDisassembly/riscv64/A.cpp, Userland/Libraries/LibDisassembly/riscv64/A.h, Userland/Libraries/LibDisassembly/riscv64/FD.cpp, Userland/Libraries/LibDisassembly/riscv64/FD.h, Userland/Libraries/LibDisassembly/riscv64/Formatting.cpp, Userland/Libraries/LibDisassembly/riscv64/Formatting.h, Userland/Libraries/LibDisassembly/riscv64/Instruction.cpp, Userland/Libraries/LibDisassembly/riscv64/Zicsr.cpp, Userland/Libraries/LibDisassembly/riscv64/Zicsr.h
This second PR in the collection deals with all the remaining non-priviledged extensions we need right now. I encourage anyone with three years of free time to tackle V :3
Note that CSR pretty-printing is not yet implemented, since we aim to establish shared CSR utilities in AK in the near future.
Again, no point in splitting these two since the orthagonal instruction set makes supporting both in common abstractions convenient.
=> LibDisassembly: RISC-V disassembly 4-2/4-5: Disassemble extensions FD (floating-point), A (atomic) and Zicsr (CSRs)

Kernel/Memory/Region.cpp
The shift operations were originally introduced in af3d3c5 to record the permission bits set for Region, but now has been replaced by the method introduced in 5194ab59b, so the shift operations can be removed.
=> Kernel: Remove unnecessary shift operations in Region constructor

Userland/Services/SystemServer/CMakeLists.txt, Userland/Utilities/CMakeLists.txt
Moving this definition from SystemServer to init was missed in 1e73a584a7b.
=> init: Define ENABLE_KERNEL_COVERAGE_COLLECTION if KCOV enabled

Kernel/Bus/PCI/Access.cpp, Kernel/Bus/PCI/Access.h, Kernel/Bus/PCI/Controller/GenericECAMHostController.cpp, Kernel/Bus/PCI/Definitions.h, Kernel/Bus/PCI/DeviceTreeHelpers.cpp, Kernel/Bus/PCI/DeviceTreeHelpers.h, Kernel/Bus/PCI/DeviceTreeInitializer.cpp, Kernel/CMakeLists.txt
This should be the last devicetree driver that wasn't a `DeviceTree::Driver`.
This PR also adds support for systems with multiple host controllers (we will need this for the VisionFive 2 and Raspberry Pi 5) and makes us no longer panic on invalid PCI host controller nodes.
=> Kernel/PCI: Modernize the devicetree PCI host controller initialization code

Tests/AK/CMakeLists.txt, Tests/AK/TestFloatingPointStringConversions.cpp, Userland/Libraries/LibC/stdlib.cpp
Removed the impossible assertion of sizeof(double) == sizeof(long double) in strtold, and made it use c_str_to_floating_point casted to long double. This fixes the crash but suffers from lack of precision. Our eisel-lemire implementation on FloatingPointStringConversions needs a big overhaul to work properly with long doubles, especially with x87 80-bit extended precision format. As discussed in Discord, this is an acceptable first contribution/fix for the crash while we don't get around to overhauling our eisel-lemire implementation
Also added tests missing for FloatingPointStringConversions.cpp.
Fixes #25791
=> LibC: Remove strtold impossible assert and add tests

Tests/LibPDF/TestPDF.cpp, Tests/LibPDF/colorspaces.pdf, Userland/Libraries/LibPDF/ColorSpace.cpp, Userland/Libraries/LibPDF/ColorSpace.h
We have to use the scale of the underlying color space. For most
color spaces, that's [0.0, 1.0], but not for lab color spaces.
The spec comment at the start of this function already tells us
what to do, but the code used to not do it. Now it does.
---
And some minor prep commits that might also make indexed color spaces a bit faster.
=> LibPDF: Make indexed lab color spaces work

Kernel/Arch/riscv64/boot.S
This essentially reverts ec5cfc031ed.
We don't need this header anymore since we now have UEFI support.
Booting via U-Boot is still possible with its `bootefi` command. QEMU `-kernel Kernel.bin` also still works because it doesn't parse this header.
=> Kernel/riscv64: Remove the Linux boot header

AK/DOSPackedTime.cpp, AK/DOSPackedTime.h, AK/Time.cpp, AK/Time.h, Kernel/FileSystem/FATFS/Inode.cpp, Kernel/FileSystem/FATFS/Inode.h, Tests/AK/CMakeLists.txt, Tests/AK/TestDOSPackedTime.cpp
The most interesting thing here is probably the improved timestamp support (which is now better than what macOS has, since macOS apparently doesn't bother reading the record that we call `creation_time_seconds` at all), but as usual, I've also thrown in some other miscellaneous changes.
=> Kernel+AK: Another pack of FATFS improvements

Documentation/BuildInstructions.md, Ports/.port_include.sh, Ports/AvailablePorts.md, Ports/msttcorefonts/package.sh
An easy way to isntall `*.ttf` files (e.g. `arial.ttf`) into `/usr/local/share/fonts`.
https://corefonts.sourceforge.net/
=> Ports: Add msttcorefonts

AK/EnumBits.h, Kernel/Arch/aarch64/PCI/Controller/BCM2712HostController.cpp, Kernel/Arch/aarch64/RPi/RP1.cpp, Kernel/Arch/aarch64/RPi/RP1.h, Kernel/Bus/PCI/API.cpp, Kernel/Bus/PCI/API.h, Kernel/Bus/PCI/Access.cpp, Kernel/Bus/PCI/Access.h, Kernel/Bus/PCI/BarMapping.h, Kernel/Bus/PCI/Controller/HostController.cpp, Kernel/Bus/PCI/Controller/HostController.h, Kernel/Bus/PCI/DeviceTreeHelpers.cpp, Kernel/Bus/PCI/IDs.h, Kernel/Bus/USB/USBManagement.cpp, Kernel/Bus/USB/USBManagement.h, Kernel/Bus/USB/xHCI/DeviceTreexHCIController.cpp, Kernel/Bus/USB/xHCI/DeviceTreexHCIController.h, Kernel/Bus/USB/xHCI/PCIxHCIController.cpp, Kernel/Bus/USB/xHCI/PCIxHCIController.h, Kernel/Bus/USB/xHCI/xHCIController.cpp, Kernel/Bus/USB/xHCI/xHCIController.h, Kernel/CMakeLists.txt, Userland/Libraries/LibDeviceTree/DeviceTree.h
This PR adds support for the Pi 5 PCIe host controller and the xHCI USB host controllers inside the RP1 I/O controller.
=> Kernel/aarch64: Add USB support for the Raspberry Pi 5

Documentation/BuildInstructionsOther.md
Replaced deprecated package group names in Fedora's prerequisites install command with updated group names.
This has been tested on Fedora 42.
PS: `@development-tools` might not be necessary but I decided to install it anyway.
=> Documentation: Update Fedora package group names

Userland/Libraries/LibPDF/ColorSpace.cpp, Userland/Libraries/LibPDF/ColorSpace.h, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Shading.cpp
Assembles triangle coordinates and colors and calls a new
`draw_gouraud_triangle()` function that will do the actual drawing.
That last function is not implemented yet though, so no behavior
change yet.
---
There are a bunch of options for how to implement `draw_gouraud_triangle()`, so I'd like to put that in its own PR. (I tested the code with the impl in https://github.com/nico/serenity/commit/4f9a7139f765b2fbdae70c5bf79f80e7b32a0b42 but I'm currently not sure that's the right approach.)
=> LibPDF: Prep work for {Free,Lattice}FormGouraudShading::draw()

Ports/AvailablePorts.md, Ports/pango/package.sh
You can now build pango without patches.
I confirmed that examples worked fine with `-Dbuild-examples=true` and [msttcorefonts](https://github.com/SerenityOS/serenity/pull/25905).
=> Ports: Add pango

Userland/Applications/PixelPaint/ImageEditor.cpp, Userland/Libraries/LibGUI/AbstractZoomPanWidget.cpp
I've noticed some image editors allow you to pan with spacebar. So I thought why not bring it to PixelPaint.
This change allows you to drag the canvas by pressing space. It essentially is the same behaviour as dragging with the middle mouse button (this feature is still there).
=> PixelPaint: Allow panning with space

Userland/Utilities/uptime.cpp
Add the number of users (active terminal sessions) to `uptime`.
The number of users is fetched from `/var/run/utmp`:
=> uptime: Add the number of users

Userland/Libraries/LibC/bits/getopt.h, Userland/Libraries/LibC/getopt.cpp
515f31339ca incorrectly made getopt only reset its state when `optind` is set to 1. However, the Linux man page says that setting it to 0 also reinitializes its state and additionally checks for some GNU extensions. stress-ng relies on this behavior.
The POSIX man page only says that setting it to 0 results in undefined behavior.
=> LibC: Correctly reset the getopt state on optind = 0

Userland/Libraries/LibPDF/Fonts/Type1FontProgram.cpp
This should never fail in practice, so hopefully no behavior change.
=> LibPDF: Be stricter about flex size in type 1 fonts

Userland/Services/WindowServer/EventLoop.cpp
Otherwise, all mouse devices would be removed when a keyboard is found because we clear `m_keyboard_devices` at the beginning of `refresh_keyboard_devices()`.
=> WindowServer: Don't insert mouse devices in the keyboard device list

Userland/Libraries/LibPDF/Shading.cpp
Reverts d26686ccc9be and tweaks draw_gouraud_triangles() a bit.
It's fairly easy to compute number_of_components locally in draw_gouraud_triangles(), so let's do that.
=> LibPDF: Stop storing number of components in gouraud shadings

Userland/Libraries/LibGfx/Point.h, Userland/Libraries/LibPDF/ColorSpace.cpp, Userland/Libraries/LibPDF/Shading.cpp
Coons patches are drawn as special cases of tensor product patches.
With this, we support all shadings that can be passed to `sh` :^)
This is a pretty simple implementation for now: It just subdivides
patches 5 levels deep, then draws them as gouraud triangles.
In a follow-up, we should change the subdivision depth to be
adaptive based on curvature. The main thing to figure out is to
prevent T-junctions, probably by inserting additional triangles
along edges with T-junctions.
In another follow-up, we should probably also use a better technique
for drawing gouraud quads instead of using two gouraud triangles.
Also, this awkwardly writes out all the bezier terms for subdivision.
In yet another follow-up, we probably want to use ✨ loops ✨ or
separable De Casteljau.
Despite all these …
=> LibPDF: Implement {Coons,TensorProduct}PatchShading::draw()

Kernel/FileSystem/FATFS/Inode.cpp, Kernel/FileSystem/FATFS/Inode.h
This makes it possible to work with FAT12/16 filesystems again after the regression in 7fa12df7. The last commit is the actual fix here, while the others (save for the typo fix) are just groundwork.
=> Kernel/FATFS: Don't confuse the root directory with clusterless entries

Userland/Services/KeyboardPreferenceLoader/main.cpp, Userland/Utilities/keymap.cpp
... and read it on system startup.
Previously, the active keymap was set as the first of the defined keymaps, which was annoying for users of multiple keymaps.
=> Utilities/keymap: Write active keymap to config file

Userland/Libraries/LibPDF/Shading.cpp
Now that we can paint all shading functions and test that changes don't completely break things, start sharing some code.
Also fixes some minor corner case bugs in the process. But the main motivation is to use less code.
=> LibPDF: Share function reading code across shading functions

Meta/CMake/get_cxx_includes.py, Meta/CMake/jakt.cmake, Toolchain/BuildJakt.sh
This is not an issue with clang, but when gcc is used as the c++ compiler, jakt can't know its builtin include paths; so come up with a nice and hacky cmake blob to fix the problem.
Warning: hacky!
=> Meta: Pass compiler's builtin includes to jakt too

Userland/Shell/main.cpp
Generally, wait for the init script to do whatever it wants before initializing the editor, to make sure we capture the correct terminal state.
=> Shell: Initialize the line editor after running the init script

Tests/LibPDF/CMakeLists.txt
That way, they show up in /home/anon/Documents/pdf and can be admired within SerenityOS.
=> Tests/LibPDF: Add recently added test files to CMakeLists.txt

Userland/Demos/Mandelbrot/Mandelbrot.cpp
`save_file` expects a file extension without a leading period.
=> Mandelbrot: Don't add a superfluous period to the file extension

Kernel/Bus/USB/USBManagement.cpp, Kernel/Bus/USB/USBManagement.h, Kernel/Bus/USB/xHCI/DeviceTreexHCIController.cpp
This is no longer necessary since aa7ea972ed8.
=> Kernel/xHCI: Don't use a DeviceRecipe for DeviceTreexHCIController

Userland/Libraries/LibShell/Shell.cpp, Userland/Libraries/LibShell/Shell.h, Userland/Shell/main.cpp
1c7233f1481e38de71e537049a444621f32d2526 broke this by moving the initialization later, while still having the shell use the invalid termios data.
Also, this commit makes it so *only* the init script is run without the termios populated, as 'Shell -c ...' should still behave like running the command in the shell.
=> Shell: Don't use uninitialized termios data

Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
Not used for anything yet, so no behavior change.
Some other very minor cleanups too, also behavior-preserving.
=> LibPDF: Read some transparency imaging model graphics state dict entries

Userland/Libraries/LibPDF/CommonNames.h, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
This adds support for loading the smask mode parameter of the transparent image model described in chapter 7 of the PDF 1.7 spec. With this, we read all transparency-related entries in graphics state dicts as far as I can tell :^)
(...but an /SMask dict refers to a transparency group XObject, and we don't read the /Group subdirectory entries at all yet. See 7.5.5 and TABLE 7.13 in the PDF 1.7 spec.)
We don't use it for anything yet, so no behavior change.
=> LibPDF: Read /SMask from graphics state dicts

Userland/Libraries/LibPDF/Renderer.cpp
We're supposed to also use this for paths, texts, and shadings, but we don't do that part yet. We're also still missing support for most other things in the transparent imaging model (using a transparency group as the graphic's state SMask, support for transparency groups at all, blend modes, etc.) But this is a small first step towards more support.
=> LibPDF: Use constant alpha for painting images

Kernel/Arch/riscv64/CSR.h, Kernel/Arch/riscv64/FPUState.h, Kernel/Arch/riscv64/Processor.cpp, Kernel/Arch/riscv64/ProcessorInfo.cpp, Kernel/Arch/riscv64/ProcessorInfo.h, Kernel/Arch/riscv64/ThreadRegisters.h, Kernel/Tasks/Process.cpp
This PR enables the V extension (if supported) and adds context switching for vector registers.
=> Kernel/riscv64: Add V support

Kernel/Arch/riscv64/CSR.h, Kernel/Arch/riscv64/Timer.cpp
This means that we no longer need to make an SBI call to start the timer if Sstc is supported.
=> Kernel/riscv64: Add Sstc support

Tests/LibPDF/clip.pdf
Rotating a `re` in a temporary graphics state before the `W n` does not work per spec, see #25988.
Instead, just make a rotated rect with `l`s.
=> Tests/LibPDF: Use pre-rotated rect in clip.pdf

Userland/Libraries/LibGUI/TabWidget.cpp, Userland/Libraries/LibGUI/TabWidget.h
When the user scrolls on a TabWidget, it will cycle through the tabs.
EDIT: Currently, it will cycle when the user tries to scroll anywhere inside the tabwidget. But it will not scroll if the child has a custom scroll handler. I don't find any functional issues but just a reminder.
Also, should it activate with `SHIFT` or `CTRL` to prevent accidental scrolls?
=> LibGUI: Scroll to cycle tabs

Userland/Libraries/LibGfx/Path.h, Userland/Libraries/LibPDF/Renderer.cpp
Apply the fill and then stroke. The close_all_subpaths() API always adds the closes to the end of the path, so with the addition of a simple .trim() method, we can just pop them off the path before stroking.
Fixes #25989
=> LibPDF: Apply fill+stroke in the correct order (without extra copies)

Tests/LibPDF/paths.pdf
This is based on the idea in
https://github.com/SerenityOS/serenity/issues/25989#issuecomment-2963872561 and shows that the `close_all_subpaths()` calls are in fact necessary.
=> Tests/LibPDF: Add a path that needs closing to paths.pdf

Userland/Libraries/LibC/arch/aarch64/setjmp.S, Userland/Libraries/LibC/arch/riscv64/setjmp.S, Userland/Libraries/LibC/arch/x86_64/setjmp.S, Userland/Libraries/LibC/setjmp.h
This implementation is based on the riscv64 version.
It passes all tests in TestLibCSetjmp.
=> LibC: Implement setjmp and longjmp for aarch64

Userland/Libraries/LibShell/Shell.cpp
The old timeout was too low when running in riscv64 QEMU (with TCG).
=> LibShell: Increase program-aware completion timeout

Base/usr/share/shell/completion/builtin.sh
fork/exec is very slow in emulation mode, avoid doing so many of them.
=> Base: Use fewer external commands in default shell completions

Kernel/Tasks/Process.cpp
The new return value slot offset calculation I added in b07d8163a96 doesn't actually use the high 20 bits and only uses an (incorrect) low displacement for the `sd` instruction.
=> Kernel/riscv64: Correctly calculate signal trampoline return slot offset

Tests/LibPDF/clip.pdf, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
W / W* just set a "add next path as clip" flag (which is *not*
stored in the graphics state), which is then used after a path
is painted.
Improves the appearance of the pattern in the upper right of
Tests/LibPDF/clip.pdf to almost match Acrobat Reader and PDFium.
(Firefox gets it mostly right; Preview.app is a bit confused.)
---
…and txpand Tests/LibPDF/clip.pdf to test various possible implementations of this feature.
=> LibPDF: Add path clip in end_path_paint(), not in W / W* handler

Tests/LibPDF/clip.pdf
It now tests clipping all basic PDF objects to a path: Paths, bitmaps, text, shadings.
(…but not shadings via a pattern or non-shading patterns since we don't support patterns yet; not forms and not type 3 fonts, both of which would be interesting to test.)
=> Tests: Let LibPDF/clip.pdf test clipping text, bitmap to a path

Kernel/Arch/aarch64/SafeMem.cpp, Kernel/Arch/riscv64/SafeMem.cpp, Tests/Kernel/CMakeLists.txt
This causes the aarch64 kernel to no longer panic on failed (userspace) memory accesses.
=> Kernel/aarch64: Actually implement safe SafeMem functions

Kernel/Net/TCPSocket.cpp, Kernel/Net/TCPSocket.h
This implementation currently aborts the whole transfer instead of caching pending packets in the kernel (see also #22524). We currently don't have a mechanism for caching pending packets in general and instead rely on userspace retrying the sendmsg syscall if the returned number of bytes sent is smaller than expected. However, 2bec281ddc3 made sys$sendmsg return an error (sys$write and sys$pwritev catch this error and retry), causing applications like WebServer to print an error instead of retrying the send operation.
So fixing Nagle's algorithm for sys$sendmsg requires adding a pending packet cache in the kernel.
For sys$write and sys$pwritev we currently busy loop in the kernel until we sent all bytes of the packet. This isn't really ideal either and especially problematic for Nagle's …
=> Kernel/Net: Remove broken Nagle's algorithm implementation

Tests/LibPDF/transparency.pdf, Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
This puts opacity in the current stroke and fill colors, which is
where most of the effect comes from.
(The `Gfx::PaintStyle` branch in stroke_current_path / fill_current_path
are from incomplete pattern support that I probably want to rewrite
in a different way eventually.)
While this is incomplete (no support for transparency groups yet,
no support for custom blend modes, stroke-and-fill doesn't do the
right thing -- see included FIXME), it's still a decent step forward.
=> LibPDF: Use graphic state opacity for text, and path stroke and fill

Toolchain/BuildGNU.sh
Otherwise, ports that expect a relatively standard GCC installation will go looking for `libgcc_s.so`.
Fixes #26018.
Pending validation on macOS from my side, maybe @iniw wants to help out?
Also, probably the first commit authored by me in well over a year?
=> Toolchain: Build GCC with static libraries on the host only

Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
While a clip is active, we now paint into a single additional bitmap
(m_clipped_bitmap, allocated once at first use, same size as the output
bitmap, but has a clip rect equal to the clip's bounding box applied for
efficiency). When the clip is popped, or when a new clip becomes active,
we paint this background buffer to the main output, using the clip path
as alpha channel.
The clip path is rasterized eagerly to graphics state.
m_clipped_bitmap_painter and m_clipped_bitmap_anti_aliasing_painter
are non-null if a clip is active, and painter()  and
anti_aliasing_painter() return those in that case.
(m_clipped_bitmap can be non-null even if there's no clip, since
it's allocated when the first clipping path is added and then kept
around for future clips.)
The rasterized clipping path is …
=> LibPDF: Implement support for clipping to arbitrary paths

Userland/Libraries/LibPDF/Renderer.cpp, Userland/Libraries/LibPDF/Renderer.h
Make read_smask_dict() a member function of Renderer for this.
Not yet used for anything, so no behavior change.
Also add a few spec comments.
=> LibPDF: Read transparency group attribs for graphics state smask group

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp, Userland/Utilities/pdf.cpp
This matches what we do in the lossless symbol and text region handlers.
Like in https://github.com/SerenityOS/serenity/pull/23864, no test yet since I still haven't found a way to create
halftone jbig2 files.
But this lets us decode the jbig2 file in castle_halftone.pdf linked
to from https://github.com/mozilla/pdf.js/pull/8491
=> LibGfx/JBIG2: Let lossless halftone handler call regular one

Kernel/Arch/aarch64/ASM_wrapper.h
Reading RNDRRS sets the NZCV condition flags.
This unbreaks booting on AArch64 Clang after c5d713864b5.
=> Kernel/aarch64: Add missing "cc" clobber in read_rndrrs()

Kernel/Arch/aarch64/SafeMem.cpp
These functions all use the CMP instruction, which sets the NZCV condition flags.
=> Kernel/aarch64: Add missing "cc" clobbers in SafeMem.cpp

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
If a pattern was drawn with a negative x but was still wide enough to reach into the frame (and analogously for y), we both increased the start x that the pattern was drawn at and set the origin x to 0. But then, `position.x() + x` didn't start at 0 but at the absolute value of the negative offset.
Instead, only increase the start offset in the pattern, but don't change the negative x coordinate. This way, `position.x() + x` will start at 0.
Improves e.g. the appearance of the upper left image edges of 200-20-45.jb2.
=> LibGfx/JBIG2: Fix incorrect composition with negative coordinates

Meta/jbig2_to_pdf.py
This teaches Meta/jbig2_to_pdf.py these things:
- It now writes segments associated with page 0 (i.e. global segments) into the JBIG2Globals stream
- For multi-page jbig2 files, it now creates one PDF page per jbig2 page
- For each jbig2 stream, it rewrites the page numbers in the PDF to 1, as required by the PDF spec
- It drops EndOfPage and EndOfPage segments
- It can now handle striped jbig2 files
Except for the last bullet, this is all things described on page 81 in the PDF 1.7 spec.
=> Meta: Several tweaks to jbig2_to_pdf.py

.github/workflows/lagom-template.yml
All recent macOS CI jobs have been reaching the GitHub actions time limit.
Set the CTest timeout to 30 minutes to hopefully get more info about which test is timing out.
=> CI: Set CTest timeout to 30 minutes

Toolchain/Patches/binutils/0001-Add-support-for-SerenityOS.patch, Userland/Libraries/LibC/arch/aarch64/setjmp.S, Userland/Libraries/LibC/arch/riscv64/setjmp.S, Userland/Libraries/LibC/arch/x86_64/setjmp.S
The `_stack` symbol change will only work after a manual toolchain rebuild (or the next forced toolchain update).
=> LibC: Clean up exported symbols a bit

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Most JBIG2 files that use huffman-encoded symbol regions also use
huffman-encoded text regions, which we don't yet support.
But page 2 of annex-h.jbig2 uses a huffman-encoded global symbol
dictionary and arithmetic coding for everything else, so this
is enough to let us decode page 2 of annex-h.jbig2 :^)
---
Progress towards https://library.sciencemadness.org/library/books/ignition.pdf
=> LibGfx/JBIG2: Support huffman-encoded symbol regions

Tests/LibWeb/Text/input/include.js
This catches errors that occur within async tests so that we fail faster rather than timing out due to `done()` not being called.
We use `Promise.resolve()` because `f` isn't guaranteed to be an async function.
(cherry picked from commit 0de910784e498594f99017880b914b4cc2d4ad42)
---
https://github.com/LadybirdBrowser/ladybird/pull/3270
=> Tests/LibWeb: Finish async test when an error is caught

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
With this, we can decode 144 of ignition.pdf's 233 pages (up from 9 – and most of the 9 pages we previously were able to decode were empty).
Somewhat similar to #26068.
=> LibGfx/JBIG2: Add (some) support for huffman-coded text segments

README.md
The main CI workflow was renamed from "Build, lint, and test" to "CI" by 660e3ccb1c4 ("Build, lint, and test" => "SerenityOS") and ae6025987d5 ("SerenityOS" => "CI").
The new badge is based on the markdown created by the CI workflow page "Create status badge" menu item.
=> Meta: Update CI status badge URL

Userland/Libraries/LibGfx/ImageFormats/JPEGXLCommon.h
oss-fuzz's clang does not yet support _Float16.
We don't currently have a jpeg xl fuzzer, so this code should currently be unreachable anyways.
=> LibGfx/JPEGXL: Try to unbreak the oss-fuzz bot

Kernel/EFIPrekernel/CMakeLists.txt, Kernel/EFIPrekernel/Filesystem.cpp, Kernel/EFIPrekernel/Filesystem.h, Kernel/EFIPrekernel/init.cpp, Kernel/Firmware/EFI/EFI.cpp
This makes it possible to install Serenity to removable media without using GRUB or having to manually pass the cmdline in the UEFI shell.
We always need a cmdline for finding the correct root drive.
There is no way to set the load options when booting from automatically generated boot menu entries for `\EFI\BOOT\BOOT<ARCH>.EFI`.
=> EFIPrekernel: Read cmdline from cmdline.txt if load options are empty

Userland/Libraries/LibGfx/ImageFormats/JPEGXLCommon.h
The `stream` variable is unused in this new code path.
#26087 forgot to add this `(void)stream`.
=> LibGfx/JPEGXL: Try to unbreak the oss-fuzz bot again

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/CCITTDecoder.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
The main motivation for this is that it's used in page 1 of the test
bitstram in Annex H. Pages 1 and 2 decode to the same bitmap, so
having support for this allows us to compare the two bitmaps, and
we get test coverage for quite a few JBIG2 features that way.
This can also decode amb_2.jb2 from the power jbig2 test dataset.
I'm not aware of any other files using this feature.
An MMR graymap is the only case where the size of the a generic region
is not known in advance, and where the data is immediately followed by
more MMR data. We need to have the MMR decoder skip the EOFB marker at
the end, so that the following bitplanes can be decoded.
To make this possible, we teach the CCITT group 4 decoder to optionally
require the EOFB marker at the end of a stream (to make sure it's
consumed) …
=> LibGfx/JBIG2+CCITT: Support decoding MMR-coded JBIG2 graymaps

CMakeLists.txt, Documentation/RunningOnRaspberryPi.md, Meta/build-image-raspberry-pi.sh, Meta/build-image-uefi.sh
These targets use the new cmdline.txt reading support introduced by #26084.
The `uefi-image` target can be used to build a UEFI image suitable for removable media if you don't want to use GRUB. This target could also be used for Raspberry Pis, but you would need to install the Raspberry Pi firmware files and EDK II manually.
That's why I added the `raspberry-pi-4-edk2-image` target.
Like `raspberry-pi-image`, it installs the Raspberry Pi firmware files next to SerenityOS. But unlike that target, it also installs EDK II. Since USB support currently requires booting with EDK II, this makes it a lot easier to boot SerenityOS on the Pi 4.
I also updated RunningOnRaspberryPi.md to mention this new target.
=> Meta: Add targets for building UEFI images for the Pi 4 and generic UEFI systems without GRUB

Tests/LibC/CMakeLists.txt, Tests/LibC/TestSignal.cpp, Userland/Libraries/LibC/signal.cpp
Now we also assert that signal names fit within SIG2STR_MAX.
=> Tests+LibC: Add tests for `sig2str()` and `str2sig()`

Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/video-failed-load.txt, Tests/LibWeb/Text/input/DOM/Document-named-properties.html, Tests/LibWeb/Text/input/css/FontFace-load-urls.html, Tests/LibWeb/Text/input/video-failed-load.html
RFC2606 and RFC6761 define .invalid as a guaranteed-invalid TLD, so let's use it. Theoretically this should make the request fail much faster.
(cherry picked from commit ea95e325390cefd4e1289e8c3de6b56d2c34473f)
---
https://github.com/LadybirdBrowser/ladybird/pull/1597
=> Cherry-pick "Tests: Use .invalid TLD for invalid requests"

Userland/Services/WindowServer/WindowManager.cpp
This PR fixes an inconsistency where the previewed window dimensions during tiling operations differ from the final window size, caused by `tiled_window_rect()` not taking into account the windows minimum size.
Before:
https://github.com/user-attachments/assets/4f4ee10e-7511-4439-8c2f-fabf8551f660
After:
https://github.com/user-attachments/assets/042dc823-d76e-4aa1-98a7-d0e5e83e4391
=> WindowServer: Fix inconsistency in previewed window dimensions during tiling operations

Userland/Libraries/LibPDF/Fonts/Type0Font.cpp
If Type0Font::initialize() returns an error,  PDFFont::create() will
fail and Renderer::set_font() will keep the previous font object as
current font. But the previous font object will likely be a simple font,
and the simple font will have a hard time with the multi-byte text
encoding usually used with type 0 fonts, leading to attempts to look up
e.g. char_code 0 for every second byte in an UCS2 string.
Instead, let Type0Font::initialize() succeed and then error out later,
either at decode or paint time.
---
Doesn't change the number of files with diagnostics, but reduces the number of bogus follow-on diagnostics in files that already emitted "Type0 font: unimplemented named type 0 cmap", "support for general type 0 cmaps not yet implemented", or "CIDFontType0: missing FontFile3":
From …
=> LibPDF: Diagnose type 0 issues later

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Rename field in page information segment to maximum_stripe_size
to match its name in the spec.
7.4.8.6 Page striping information:
> the maximum size of each stripe (the distance between an end of stripe
> segment's end row and the end row of the previous end of stripe
> segment, or 0 in the case of the first end of stripe segment) must be
> no more than the page's maximum stripe size.
That means that the maximum stripe _height_ is one more than the
maximum strip size, so update the code accordingly.
This lets us decode https://github.com/SerenityOS/serenity/commit/0001341cd6dfcbf6a6b92ed0901f0dcff892693b.pdf page 6, which has a page information
segment with height=1408 and max_stripe_size=1407.
=> LibGfx/JBIG2: Fix off-by-one in max stripe height computation

Userland/Libraries/LibGfx/Font/BitmapFont.h, Userland/Libraries/LibGfx/Font/Font.h, Userland/Libraries/LibGfx/Font/OpenType/Font.cpp, Userland/Libraries/LibGfx/Font/OpenType/Font.h, Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp, Userland/Libraries/LibGfx/Font/OpenType/Tables.h, Userland/Libraries/LibGfx/Font/ScaledFont.cpp, Userland/Libraries/LibGfx/Font/ScaledFont.h, Userland/Libraries/LibGfx/Font/VectorFont.h, Userland/Libraries/LibGfx/Font/WOFF/Font.h, Userland/Libraries/LibGfx/Font/WOFF2/Font.h, Userland/Libraries/LibGfx/Painter.cpp, Userland/Libraries/LibGfx/Painter.h, Userland/Libraries/LibPDF/Fonts/TrueTypeFont.cpp
Addresses a long-standing FIXME in TrueTypePainter::draw_glyph(), and
gets us from 880 files without issues (88.0%) to 905 files without
issues (90.5%) for my 1000 file test set :^)
---
Based on a branch that's nearly 2 years old.
It's nice to be over 90% now, but see #26133 for a disclaimer. With #26133 patched in, this gets us from 63.7% to 65.1%.
=> LibGfx+LibPDF: For TrueType, look up by postscript name after unicode value

Userland/Applications/Piano/AudioPlayerLoop.cpp, Userland/Applications/Piano/AudioPlayerLoop.h, Userland/Applications/Piano/TrackManager.h, Userland/Applications/Piano/main.cpp
For actually testing this, I highly recommend decreasing the internal volume in Piano before exporting or playing anything, because apparently the various synths tend to clip quite easily. The clipping is even more pronouced in exported files, because those don't get extra headroom from AudioServer.
Fixes #26123.
=> Piano: Fix exporting while paused

Documentation/README.md, Documentation/RISC-V.md
This documents the current state of the RISC-V port and notes current limitations and what extensions are required.
=> Documentation: Document the RISC-V port

Userland/Libraries/LibPDF/Function.cpp
=> LibPDF: Use AK::first_is_one_of() in Function.cpp

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
They have to be smaller than the current segment's segment number.
No real behavior change, just a bit stricter.
---
Also log a tiny bit more in JBIG2_DEBUG mode.
=> LibGfx/JBIG2: Check that referred-to segment numbers are small enough

AK/Array.h, AK/DOSPackedTime.cpp, AK/StdLibExtraDetails.h, AK/StdShim.h, AK/Time.h, AK/Tuple.h, Tests/AK/TestArray.cpp, Tests/AK/TestTuple.cpp, Userland/Libraries/LibC/time.cpp
Fixes #26079 (#12729 should probably also be closed at this point even without this PR, because I don't think there's been a noticable performance issue with `time_to_tm()` since at least #16760. Also, the existing loop based approaches were pretty fast already to be fair, but this does slightly speed those up).
The newly added `AK::days_to_time()` returns a `Tuple` (since this seems better to me than returning a disposable struct), but that sent me on a yak shave since I quickly ran into the fact that we don't really have support for structured bindings in AK. Thus this also brings back #24993 (rebased for 2025 and updated to include for more `namespace std` stuff that's needed in the Kernel).
=> AK+LibC: Optimize time component conversion

Userland/Applications/ThemeEditor/main.cpp
The ThemeEditor uses `GUI::FilePicker` directly this results in a crash because of the unveils and the missing config pledge_domain. This pr fixes the crash by removing the unveils for now, this is not very elegant but I'm thinking about unifying the `GUI::FilePicker` and `FileSystemAccessServer` API's so that always will work in restricted processes.
=> ThemeEditor: Add pledge and remove unveils to fix GUI:FilePicker crash

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
...and only allow regions of unknown size for immediate generic regions. (We might have to allow this for ImmediateLosslessGenericRegion in the future if that's used in practice, but I haven't seen it so far. The spec seems to only allow it for ImmediateGenericRegion though.)
The two files with segments with unknown size (0000033.pdf pages 1-2, and 0000600.pdf pages 1-3) store the same height in the region segment information field and after the data.
The four bytes with the actual row count are only present in immediate generic regions of unknown size. Immediate generic regions with known size (the common case) don't store these four bytes.
---
No test since I currently don't know how to make a file with a immediate generic region segment of unknown size (but JBIG2Writer will hopefully …
=> LibGfx/JBIG2: Read row count in ImmediateGenericRegion of unknown size

Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn, Tests/LibGfx/TestImageDecoder.cpp, Tests/LibGfx/TestImageWriter.cpp, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/ICC/WellKnownProfiles.cpp, Userland/Libraries/LibGfx/ICC/WellKnownProfiles.h, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.cpp, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Shared.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Writer.cpp, Userland/Libraries/LibGfx/ImageFormats/JPEG2000BitplaneDecoding.h, Userland/Libraries/LibGfx/ImageFormats/QMArithmeticCoder.cpp, Userland/Libraries/LibGfx/ImageFormats/QMArithmeticCoder.h
JBIG2Writer can now write arithmetically-coded image data.
This lets it write basically all images; all remaining stuff is
just for better compression (and for adding more test files for
the decoder, which is the main motivation here, really).
generic_region_encoding_procedure() is very similar to
generic_region_decoding_procedure(), only the loop at the end is
different (to compress data instead of to decompress it). Maybe
we can find a way to share more code in the future. Quite a bit
of support code is already shared, though.
I also need to come up with a way to pass many, many options to
the encoder. For now, this just hardcodes all the options to
somewhat useful defaults.
Likewise, we also need a mechanism to manually pick which segments
to write. A fully white or fully black image …
=> LibGfx: Teach JBIG2Writer to write generic immediate regions 

Base/usr/share/man/man5/GML/Widget/DynamicWidgetContainer.md, Userland/Applications/HexEditor/main.cpp, Userland/Applications/Weather/main.jakt
When working on #26170 I saw that the `HexEditor` app didn't close the detach windows after the main window was closed. This was caused because `close_all_detached_windows()` wasn't called. So I've added the call to all apps that use `DynamicWidgetContainer`, I've also added a paragraph to the GML manual.
=> HexEditor+Weather: Cleanup detached windows on main window close

Base/etc/DeviceMapper.ini
Unlike with the `phys` group, no users are a part of this one by default. This means that anon can no longer bypass filesystem access restrictions by directly modifying the underlying block device.
=> Base: Add a new `disk` group for limiting direct storage device access

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
…and a few minor cleanups.
For writing JBIG2Writer, it's useful if the loader is pretty strict, to catch mistakes. (But not too strict to break real-world files, of course. If this does break any files in practice, we need to weaken it. I'm not aware of any files that this fires on though.)
=> LibGfx/JBIG2: Validate more things

Kernel/Memory/MemoryManager.cpp, Toolchain/Patches/llvm/0001-clang-Add-support-for-SerenityOS.patch, Toolchain/Patches/llvm/0004-compiler-rt-Enable-profile-instrumentation-for-Seren.patch
The toolchain support for this seems to have been accidentally removed in fa1eef8b, so first of all this restores that, and secondly this fixes deadlocks in `MemoryManager::initialize_kasan_shadow_memory()` that were caused by d10fcfb7.
A toolchain rebuild should only be necessary if you want to use KASAN.
=> Kernel+Toolchain: Fix KASAN regressions

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
The extra validation in #26191 was added at the end of decode_segment_headers(). But in decode_embedded(), that can be called several times, once for each data chunk.
We want to decode segment headers from all chunks first before we do validation, so that segments in later chunks can refer to segments in earlier chunks.
Add a new complete_decoding_all_segment_headers() to house the validation code, and call it after all segment chunks have been decoded.
Unbreaks rendering 0000372.pdf page 11 and 0000857.pdf pages 1-4.
=> LibGfx/JBIG2: Fix cross-chunk segment refs in embedded organization

Ports/libopenal/package.sh
The project's website's certificate expired a few months ago, and it is yet to be renewed.
=> Ports/libopenal: Download sources from GitHub

Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Instead, detect files from the Power JBIG2 test set and enable
_more_ quirks for those, and disable all quirks for all other files.
Happily, the files in the Power JBIG2 test stet contain an extension
segment with an identifying string.
Sadly, it contained a typo that's fixed in some of the t89-halftone/
files, so we need to check for two different signatures.
This lets us decode 042_22.jb2 and, with a second commit to add standard huffman table O, 042_11.jb2.
We can now decode all files from the Power JBIG2 test set except for 042_13.jb2 and 042_14.jb2, which PDFium, Preview.app, and pdf.js all can't decode either. (PDFium also fails decoding 042_3.jb2, and Preview.app shows that one slightly wrong, but we get it right. PDFium can only decode the t89-halftone files with rotation …
=> LibGfx/JBIG2: Disable quirks handling by default

Userland/Applications/GamesSettings/main.cpp
The CardSettingsWidget uses ImageDecoder for decoding bitmaps for card backs, and that requires this unveil.
=> GamesSettings: Unveil portal/image

Userland/Libraries/LibGUI/TextEditor.cpp
Previously it was pretty annoying to type on programs like LineEditor because after every space the trailing whitespace visualizer kicked in and a red square showed up right where the cursor was.
Now it's only rendered when the cursor is not at the end of the line, which makes typing feel better!
Before:
https://github.com/user-attachments/assets/3e468bb6-fbae-4ec7-96df-f89eb85d920e
After:
https://github.com/user-attachments/assets/2b0c3c03-ae7f-46d6-82fc-6633b7ae4278
=> LibGUI: Don't render trailing whitespace when cursor is at last column

Kernel/Syscalls/execve.cpp, Kernel/Tasks/Scheduler.cpp, Kernel/Tasks/Scheduler.h, Kernel/Tasks/Thread.cpp, Kernel/Tasks/Thread.h, Kernel/Tasks/ThreadBlockers.cpp, Tests/Kernel/CMakeLists.txt, Tests/Kernel/TestWait.cpp
As discussed in #26160, it isn't possible for a thread to go right from being blocked to being stopped (or the other way around), so this PR codifes that invariant. This PR also disallows calling `Thread::set_state()` when that would turn out to be a no-op.
=> Kernel: Be more strict about thread states

Userland/Libraries/LibGfx/ImageFormats/JBIG2Shared.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Writer.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Writer.h
Mostly a no-op, much less code, slightly better compression.
=> LibGfx/JBIG2: Re-implement JBIG2Writer::encode(), use nominal AT pixel locations

Userland/Applications/PixelPaint/ModeBilevelDialog.cpp, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.cpp, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.h, Userland/Utilities/image.cpp
2x2, 4x4, 8x8 for now. Might want to add 16x16 later.
---
In part to see what's up with mac CI :P
Details for 2x2:
4x4:
8x8:
=> LibGfx+image+PixelPaint: Add ordered bayer dither for bilevel conversion

Userland/Libraries/LibGUI/DynamicWidgetContainer.cpp, Userland/Libraries/LibGUI/DynamicWidgetContainer.h
The section_label prop is used as config key. But sometimes it contains spaces. Spaces in config keys are quite ugly and not following the .ini spec I think, so this commit filters them out.
Commit split of from #26170
=> LibGUI: Remove spaces from DynamicWidgetContainer config key

Kernel/Arch/aarch64/linker.ld, Kernel/Arch/riscv64/linker.ld, Kernel/Arch/x86_64/linker.ld, Kernel/EFIPrekernel/linker.ld, Kernel/Prekernel/linker.ld
All of these linker scripts assume 4K pages.
If these linker scripts would be used with MAXPAGESIZE > 4K, the sections would not be aligned correctly.
=> Kernel: Assert that MAXPAGESIZE == 4K in all linker scripts

Kernel/Devices/Input/PS2/KeyboardDevice.cpp
This PR associates `Key_Plus` with `0x0D`; previously it was listed in `shifted_scan_code_set1_key_map` twice with `0x4E`, its scancode on the numpad.
This fixes being unable to type the closing brace `}` in the Dvorak keyboard layout.
=> Kernel/Input: Associate non-numpad scancode with Key_Plus

Userland/Libraries/LibGfx/ImageFormats/BilevelImage.cpp, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
Related to #26082
This is only about making blending `BilevelImage`s faster. Taking it from ~20% of the profile to ~2% :^)
From:
```
Benchmark 1: BuildLagom/bin/pdf --render out.png PDF/Mellor_ACTITC_10.pdf --page 4
Time (mean ± σ):     630.9 ms ±   9.7 ms    [User: 582.8 ms, System: 47.7 ms]
Range (min … max):   622.1 ms … 655.9 ms    10 runs
```
To:
```
Benchmark 1: BuildLagom/bin/pdf --render out.png PDF/Mellor_ACTITC_10.pdf --page 4
Time (mean ± σ):     521.2 ms ±   4.0 ms    [User: 475.4 ms, System: 45.5 ms]
Range (min … max):   516.3 ms … 527.9 ms    10 runs
```
=> LibGfx: Decode Mellor_ACTITC_10.pdf faster, again

Userland/Libraries/LibGfx/ImageFormats/BilevelImage.cpp, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp, Userland/Libraries/LibGfx/ImageFormats/JBIG2Writer.h, Userland/Utilities/jbig2-from-json.cpp
Related to #26082
Before:
``` bash
Benchmark 1: BuildLagom/bin/pdf --render out.png PDF/Mellor_ACTITC_10.pdf --page 4
Time (mean ± σ):     427.7 ms ±   8.4 ms    [User: 381.2 ms, System: 46.3 ms]
Range (min … max):   410.3 ms … 438.6 ms    10 runs
```
After:
``` bash
Benchmark 1: BuildLagom/bin/pdf --render out.png PDF/Mellor_ACTITC_10.pdf --page 4
Time (mean ± σ):     337.2 ms ±   3.0 ms    [User: 295.2 ms, System: 41.8 ms]
Range (min … max):   332.0 ms … 340.7 ms    10 runs
```
=> LibGfx: Decode Mellor_ACTITC_10.pdf faster [3/N]

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
We now check the table presence only once per scan instead of once per component value.
This reduces Valgrind's Ir count by 0.5%. Not much, but I was tired of seeing the `HashTable` in profiles.
Very similar to 14a0703924a14c47230d5d6cef207f5c7c18fdd6.
=> LibGfx/JPEG: Check earlier for huffman tables presence

Userland/Libraries/LibGfx/ImageFormats/BilevelImage.cpp, Userland/Libraries/LibGfx/ImageFormats/BilevelImage.h, Userland/Libraries/LibGfx/ImageFormats/JBIG2Loader.cpp
This allows a simple conversion to the `BilevelSubImage` type.
@nico
=> LibGfx: Add BilevelImage::as_subbitmap()
