SerenityOS/serenity

- Kernel/Heap/Heap.h
When the ExpandableHeap calls the remove_memory function, the
subheap is assumed to be removed and freed entirely. remove_memory
may drop the underlying memory at any time, but it also may cause
further allocation requests. Not removing it from the list before
calling remove_memory could cause a memory allocation in that
subheap while remove_memory is executing. which then causes issues
once the underlying memory is actually freed.
> Kernel: Remove subheap from list before removing memory

- Libraries/LibTextCodec/Decoder.cpp
- Libraries/LibTextCodec/Decoder.h
Adding implementation of Latin2 to UTF-8 conversion.
> LibTextCodec: Add Latin2 text decoder

- Applications/Terminal/main.cpp
- Libraries/LibGUI/AppFile.cpp
- Libraries/LibGUI/AppFile.h
- Libraries/LibGUI/CMakeLists.txt
- Libraries/LibVT/TerminalWidget.cpp
- Services/LaunchServer/CMakeLists.txt
- Services/LaunchServer/Launcher.cpp
- Services/LaunchServer/Launcher.h
- Services/LaunchServer/main.cpp
- Services/SystemMenu/main.cpp
- Services/Taskbar/TaskbarWindow.cpp
This is an attempt to make the common task of opening and reading an `.af` file easier and more fail-proof.
> LibGUI: Add GUI::AppFile, a simple wrapper around .af files

- Libraries/LibJS/Runtime/CommonPropertyNames.h
- Libraries/LibJS/Runtime/ObjectPrototype.cpp
- Libraries/LibJS/Runtime/ObjectPrototype.h
- Libraries/LibJS/Tests/builtins/Object/Object.prototype.isPrototypeOf.js
Spec: https://tc39.es/ecma262/#sec-object.prototype.isprototypeof
> LibJS: Implement Object.prototype.isPrototypeOf

- Applications/Spreadsheet/CellSyntaxHighlighter.cpp
- Applications/Spreadsheet/CellSyntaxHighlighter.h
- Applications/Spreadsheet/JSIntegration.cpp
- Applications/Spreadsheet/JSIntegration.h
- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/Spreadsheet.h
- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/SpreadsheetWidget.h
- Base/res/js/Spreadsheet/runtime.js
- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Interpreter.cpp
- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Runtime/Exception.h
- Libraries/LibJS/Runtime/VM.h
- Libraries/LibJS/SourceRange.h
An image is worth some words, so here's an image :P
---
Now one might ask, "why not work on the multitude of issues about the Spreadsheet?", and to that I say "NOT FUN"
> LibJS: Track source position down to exceptions / Spreadsheet: Some fancy cell editor features :P 

- Base/usr/share/man/man1/pape.md
> Base: Add pape man page documentation

- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
> LibJS: `save_state()' before creating a RulePosition

- Userland/readelf.cpp
There are a few things marked `TODO`. The `LibELF` API requires a bit of a rework first.
> Userland: Add readelf utility

- Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
This fixes 4 issues:
- RECONSUME_IN_RETURN_STATE was functionally equivalent to
SWITCH_TO_RETURN_STATE, which caused us to lose characters.
For example, &test= would lose the =
- & characters by themselves would be lost. For example, 1 & 2
would become 1 2. This is because we forgot to flush
characters in the the ANYTHING_ELSE path in CharacterReference
- Named character references didn't work at all in attributes.
This is because there was a path that was checking the entity
code points instead of the entity itself. Plus, the path that
was checking the entity itself wasn't quite spec compliant.
- If we fail to match a named character reference, the first
character is lost. For example &test would become &est.
However, this relies on a little hack since I can't wrap my
head around on how …
> LibWeb: Fix character references losing characters in certain situations

- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/Element.idl
Exposes removeAttribute, hasAttribute and hasAttributes.
> LibWeb: Expose three more attribute methods on Element

- AK/StackInfo.cpp
Seems Rust and OpenJDK both had issues with getting accurate stack size
for the main thread with MacOS Maverick and above. Apply a variant of
their workarounds. We could probably assume 8MB in all cases just to
be safe, as the only user of AK::StackInfo right now is lib JS's heap
for determining possible pointer candidates. But, this approach should
work if userspace apps start trying to add custom guard pages, as well.
Applying this patch allows test-js to run to completion on MacOS (with failures). New issue for that incoming :D
> AK: Use MacOS pthread_get_stacksize_np to get stack size for StackInfo

- Applications/Terminal/main.cpp
This is my first experience with pull requests, i hope i didn't break anything
> Terminal: Fix bell mode in Terminal Settings

- Kernel/Heap/kmalloc.cpp
If a heap expansion is triggered by allocating from e.g. the
RangeAllocator, which may be holding a spin lock, we cannot
immediately allocate another block of backup memory, which could
require the same locks to be acquired. So, defer allocating the
backup memory
Fixes #4675
> Kernel: Fix heap expansions deadlock

- Applications/PixelPaint/Image.cpp
- DevTools/UserspaceEmulator/Emulator.cpp
- Kernel/Devices/AsyncDeviceRequest.cpp
- Kernel/WaitQueue.cpp
- Libraries/LibELF/DynamicLoader.cpp
- Libraries/LibELF/DynamicObject.cpp
- Libraries/LibJS/Tests/builtins/Array/Array.prototype.sort.js
- Libraries/LibRegex/RegexParser.cpp
- Libraries/LibTTF/Glyf.cpp
A little clean up before 2021 hits.
> Everywhere: Fix more typos

- Libraries/LibGemini/Job.cpp
- Libraries/LibHTTP/Job.cpp
- Libraries/LibProtocol/Download.cpp
- Libraries/LibWeb/Loader/ResourceLoader.cpp
- Services/ProtocolServer/GeminiProtocol.cpp
- Services/ProtocolServer/HttpProtocol.cpp
- Services/ProtocolServer/HttpsProtocol.cpp
- Services/ProtocolServer/Protocol.cpp
- Services/ProtocolServer/Protocol.h
> LibProtocol: Ensure download is finished before invoking on_finished

- AK/Array.h
- AK/ByteBuffer.h
- AK/Format.h
- AK/Tests/TestFormat.cpp
- AK/Tests/TestMemoryStream.cpp
- AK/Utf8View.cpp
- AK/Utf8View.h
- Userland/test-compress.cpp
Just a few annoyances that I put on my to-do list at some point.
> AK: A few minor tweaks.

- Base/usr/share/man/man1/Terminal.md
> Base: Add Terminal man page documentation

- Applications/Spreadsheet/HelpWindow.cpp
- Applications/Spreadsheet/HelpWindow.h
- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/main.cpp
This addresses https://github.com/SerenityOS/serenity/issues/4277#issuecomment-753436495 and fixes #4716.
> Spreadsheet: Tiny fixes

- Libraries/LibWeb/HTML/Parser/HTMLDocumentParser.cpp
Required to view the Spotify home page
> LibWeb: Fully implement end tag parsing in foreign content

- Meta/Lagom/Fuzzers/FuzzJs.cpp
This should help us get a lot more coverage in LibJS.
> FuzzJs: If the program successfully parsed, try running it

- Kernel/FileSystem/ProcFS.cpp
There is a window between dropping the last reference and removing
a ProcFSInode from the lookup map. So, when looking up we need to
check if that Inode is being destructed.
_This solved almost all the odd crashes I kept running into..._
> Kernel: Fix ProcFS returning Inodes that are being deleted

- Applications/Calculator/CMakeLists.txt
- Applications/Calculator/CalculatorWidget.cpp
- Applications/Calculator/CalculatorWidget.h
- Applications/Calculator/CalculatorWindow.gml
Introduce GML ui for the calculator app
> Calculator: Port interface to GML

- Userland/crash.cpp
These do not crash the process anymore. Fixes #4685.
> crash: Remove -x and -y which do not crash (write to / read from freed memory)

- Base/home/anon/.config/LaunchServer.ini
- Base/usr/share/man/man1/Playground.md
- DevTools/Playground/main.cpp
Might be useful for integration into `HackStudio`.
> Playground: Support opening gml file by path as command line argument

- Demos/Screensaver/Screensaver.cpp
There were some changes to the graphics library about 6 months ago which broke `Screensaver`. `Screensaver` failed to draw when run in full screen (default) when double buffering was enabled. This PR disables double buffering.
However, something else also changed six months ago which prevents more than one paint event when windows are full screen (#4810). As such, only the first frame is drawn.
This PR also disables the cursor. However, this doesn't actually hide the cursor until the cursor is redrawn (#4809).
This PR also moves the global `#define` settings into the Screensaver Widget constructor.
> Screensaver: Disable double buffering and hide cursor

- Base/usr/share/man/man1/tar.md
> Base: Add tar man page documentation

- Base/usr/share/man/man1/ddate.md
- Userland/ddate.cpp
Today is Boomtime, day 7 of Chaos, in the YOLD 3187
> Userland: Add ddate utility

- Services/WindowServer/WindowManager.cpp
> WindowServer: Start blocked modal animation when clicking on frame

- DevTools/Profiler/Profile.cpp
We don't need to `assert` when the profile input file is malformed. We can easily validate the JSON and return an error message instead.
Given that coredumps are expensive it makes sense to handle errors gracefully rather than straight up crash.
Bonus: the error message is more user friendly.
Before this PR, `Profiler /etc/passwd` would crash :
```
USERSPACE(27) ASSERTION FAILED: json.has_value()
../DevTools/Profiler/Profile.cpp:262
[Profiler(27:27)]: 0x00000000  (?)
[Profiler(27:27)]: 0xc0181fc4  Kernel::Process::crash(int, unsigned int, bool) +0x2d2
[Profiler(27:27)]: 0xc018855d  Kernel::Process::sys$abort() +0x1f
[Profiler(27:27)]: 0xc01881ba  syscall_handler +0x6be
[Profiler(27:27)]: 0xc0187af4  syscall_asm_entry +0x31
[Profiler(27:27)]: Process regions:
[Profiler(27:27)]: BEGIN …
```
> Profiler: load_from_perfcore_file: handle invalid JSON gracefully

- DevTools/Profiler/DisassemblyModel.cpp
- DevTools/Profiler/DisassemblyModel.h
- DevTools/Profiler/Profile.cpp
- DevTools/Profiler/Profile.h
- Libraries/LibCoreDump/Reader.cpp
- Libraries/LibCoreDump/Reader.h
- Libraries/LibELF/Image.cpp
> Profiler: Fix function disassembly

- Applications/SpaceAnalyzer/main.cpp
- Base/res/apps/SpaceAnalyzer.af
> SpaceAnalyzer: use "Proper Noun" name style

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/FunctionPrototype.cpp
- Libraries/LibJS/Runtime/JSONObject.cpp
- Libraries/LibJS/Runtime/ReflectObject.cpp
- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
> LibJS: Remove to_size_t()

- Kernel/Process.h
- Kernel/Syscalls/execve.cpp
> Kernel: Avoid collision between dynamic loader and main program

- Userland/wc.cpp
Also replace uses of `printf`-functions with the new `String::formatted` print functions.
> wc: Remove a memory leak.

- Userland/Libraries/LibCore/EventLoop.cpp
There's no reason to have this, and it will most likely fail anyway
(since there's likely no /tmp/rpc).
cc @linusg - your bug report.
> LibCore: Don't create an RPC server when built for lagom

- Documentation/HighDPI.md
I have a local branch that gets us past implementation stage 1
in this doc, and it seems like a useful enough checkpoint to
upstream it and then iterate in tree.
> Docs: Add design doc and implementation plan for highdpi

- Documentation/UsingQtCreator.md
Required after moving most of the code base into `Userland/`.
> Documentation: UsingQtCreator: Include Userland in includes paths

- Userland/Demos/LibGfxScaleDemo/main.cpp
I thought this wouldn't work yet, but it already does.
> LibGfxScaleDemo: Add Emoji to window title bar

- Base/usr/share/man/man1/TextEditor.md
- Userland/Applications/TextEditor/TextEditorWidget.cpp
> TextEditor: Add help documentation

- Userland/Applications/SoundPlayer/main.cpp
This fixes a crash that occured when opening any sound file due to that
> SoundPlayer: Added 'shared_buffer' to pledge

- Meta/Lagom/CMakeLists.txt
- Userland/Shell/AST.cpp
- Userland/Shell/AST.h
- Userland/Shell/Builtin.cpp
- Userland/Shell/Shell.cpp
- Userland/Shell/Shell.h
- Userland/Shell/Tests/backgrounding.sh
- Userland/Shell/Tests/brace-exp.sh
- Userland/Shell/Tests/builtin-redir.sh
- Userland/Shell/Tests/control-structure-as-command.sh
- Userland/Shell/Tests/function.sh
- Userland/Shell/Tests/if.sh
- Userland/Shell/Tests/loop.sh
- Userland/Shell/Tests/match.sh
- Userland/Shell/Tests/sigpipe.sh
- Userland/Shell/Tests/special-vars.sh
- Userland/Shell/Tests/subshell.sh
- Userland/Shell/Tests/test-commons.inc
- Userland/Shell/Tests/valid.sh
This PR fixes some issues surfaced by actual use of the Shell (!) in #4921.
> Shell: Fix some bugs encountered in #4921

- Documentation/HighDPI.md
This is more RfC than actual pull request. Does anyone have any opinion or preference here?
@tomuta
> Docs: Start outlining options for highdpi resource handling

- Kernel/Process.h
- Userland/Applications/CrashReporter/main.cpp
- Userland/Libraries/LibELF/CoreDump.h
I thought this might be useful :)
> Kernel+CrashReporter: Store pledge violations in coredumps

- Userland/Libraries/LibGfx/Painter.cpp
> LibGfx: Implement scaling support for draw_tiled_bitmap()

- Userland/Demos/LibGfxScaleDemo/main.cpp
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/Painter.h
- Userland/Libraries/LibGfx/Point.h
- Userland/Libraries/LibGfx/Rect.h
- Userland/Libraries/LibGfx/Size.h
- Userland/Services/WindowServer/Compositor.cpp
> Make stretching low-res desktop images work much better.

- Meta/build-root-filesystem.sh
- Userland/Games/Conway/Game.cpp
- Userland/Games/Conway/Game.h
We have a beautiful `Welcome` program. Put a spotlight on it, show it to the world! :)
Make `Conway` interactive. Left-clicking makes cells alive (although they likely die again due to loneliness). Right-clicking kills cells.
> Desktop+Conway: Be a little more fun :)

- Userland/Applications/HexEditor/CMakeLists.txt
- Userland/Applications/HexEditor/FindDialog.cpp
- Userland/Applications/HexEditor/FindDialog.h
- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditor.h
- Userland/Applications/HexEditor/HexEditorWidget.cpp
Added search submenu with options to find or find again.
Find allows to search for ASCII string or sequence of Hex value.
Closes #4122
> HexEditor: Find

- Userland/Utilities/grep.cpp
While doing so, make grep spin a little less on stdin, if that's where it's getting the input from.
> Userland: Implement grep -v

- Base/usr/share/man/man1/crash.md
Update the outdated list of options, mention UserspaceEmulator, update example shell output.
> Base: Update crash(1) man page

- Userland/Shell/AST.cpp
Fixes #5119
(pls wait until ci passes before merge, kthx)
> Shell: Do not bail on signaled if condition

- Kernel/Random.cpp
- Kernel/Random.h
This adds an optional argument to get_good_random_bytes that can be
used to only return randomness if it doesn't have to block.
Also add a SpinLock around using FortunaPRNG.
Fixes #5132
> Kernel: Make KernelRng thread-safe

- Userland/Utilities/pmap.cpp
> pmap: Add shared flag to access column and align-right numeric columns

- Userland/Libraries/LibELF/DynamicLoader.cpp
Previously regions were stored in a vector and then a pointer to regions in this vector were taken and stored. The problem is the vector were still appended after pointers were taken, if enough regions were present the vector would grow so large that it needed a resize, this cause his memory to moved and now the previous pointers are now pointing to old memory we just freed.
This closes: #5160 and get `jq` finaly running.
Thx to @BenWiederhake for figuring out the vector resize issue and explaning me a bit of c++.
> DynamicLoader: load_program_headers use variables to store regions

- Userland/Applications/Calculator/main.cpp
- Userland/Applications/Calendar/main.cpp
- Userland/Applications/DisplaySettings/main.cpp
- Userland/Applications/FileManager/main.cpp
- Userland/Applications/HexEditor/HexEditorWidget.cpp
> Everywhere: Add missing parent window to about dialogs

- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/WindowManager.cpp
> WindowManager: Restore a window's geometry when untiling it using keyboard shortcuts

- Userland/DevTools/Inspector/main.cpp
Check if the target process has pledged `accept` before attempting to connect.
Attempting to inspect a process which has not pledged `accept` is doomed to failure. Worse, the process will crash.
> Inspector: Exit if inspected process has not pledged accept

- Kernel/FileSystem/ProcFS.cpp
I have no idea when it broke.
Inspired by https://www.thanassis.space/bashheimer.html
> Kernel: Make /proc/self/ work again

- AK/URL.h
- AK/URLParser.cpp
- AK/URLParser.h
- Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
> AK: Extend URL encoding capabilities / LibWeb: Unbreak crash error page link

- Kernel/FileSystem/ProcFS.cpp
- Kernel/PCI/Access.cpp
- Kernel/PCI/Access.h
- Kernel/PCI/Definitions.h
- Kernel/PCI/IOAccess.cpp
- Kernel/PCI/MMIOAccess.cpp
- Userland/Applications/SystemMonitor/main.cpp
- Userland/Utilities/lspci.cpp
While this works on bare-metal and on QEMU, somebody that knows a bit more about PCI than me should check if this is correct (or at least more correct than before).
Fixes #5190.
> Fix PCI enumeration and terminology

- Userland/Tests/LibGfx/CMakeLists.txt
- Userland/Tests/LibGfx/image-decoder.cpp
This currently doesn't test much, although it would be nice to know if these functions break for some reason.
> Tests: Add Tests/LibGfx/image-decoder tests

- Meta/lint-keymaps.py
> Meta: Remove now-obsolete import from lint script

- Userland/Applications/DisplaySettings/DisplaySettings.cpp
- Userland/Applications/DisplaySettings/DisplaySettings.h
I felt like this needed some kind of confirmation message :)
> DisplaySettings: Show a confirmation message when applying changes

- Userland/Libraries/LibC/netdb.cpp
- Userland/Services/LookupServer/CMakeLists.txt
- Userland/Services/LookupServer/ClientConnection.cpp
- Userland/Services/LookupServer/ClientConnection.h
- Userland/Services/LookupServer/DNSAnswer.cpp
- Userland/Services/LookupServer/DNSAnswer.h
- Userland/Services/LookupServer/DNSPacket.h
- Userland/Services/LookupServer/DNSRequest.cpp
- Userland/Services/LookupServer/DNSRequest.h
- Userland/Services/LookupServer/DNSResponse.cpp
- Userland/Services/LookupServer/DNSResponse.h
- Userland/Services/LookupServer/LookupClient.ipc
- Userland/Services/LookupServer/LookupServer.cpp
- Userland/Services/LookupServer/LookupServer.h
- Userland/Services/LookupServer/LookupServer.ipc
- Userland/Services/LookupServer/main.cpp
"Am I proud of this code? No. Am I sure that it works? No. But did I write tests for it? Also no."
cc @alimpfard @linusg
> Adventures in LookupServer, pt. 1

- Kernel/CMakeLists.txt
- Kernel/UBSanitizer.cpp
- Kernel/UBSanitizer.h
This didn't find anything in the current source.
> Kernel: KUBSAN implementation of returns-nonnull-attribute

- Userland/Libraries/LibLine/Editor.cpp
- Userland/Libraries/LibLine/Editor.h
- Userland/Libraries/LibLine/InternalFunctions.cpp
- Userland/Shell/Parser.cpp
Hopefully straight-forward fixes, so I decided to just put them in one PR.
Fixes bugs.chromium.org/p/oss-fuzz/issues/detail?id=30405
Fixes #5233
> Shell: One more history assertion fix / LibLine: Search editor fixes

- Userland/Services/WindowServer/Button.cpp
- Userland/Services/WindowServer/Button.h
- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/WindowFrame.cpp
- Userland/Services/WindowServer/WindowManager.cpp
Button now can handle middle and right clicks.
Added 2 new handlers in button class: on_right_click for Right mouse
button and on_aux_click for middle mouse button.
Added functionality to vertically maximize window with middle mouse
click on the maximize window button
Closes #4123
> WindowServer: Vertically maximize window

- Userland/Libraries/LibGfx/SystemTheme.cpp
- Userland/Services/WindowServer/Compositor.cpp
- Userland/Services/WindowServer/WindowFrame.cpp
- Userland/Services/WindowServer/WindowFrame.h
- Userland/Services/WindowServer/WindowManager.cpp
We didn't properly determine whether a window was fully covered, which
caused some artifacts in certain cases.
Fixes #5283
> WindowServer: Occlusion calculation fixes

- Userland/DevTools/HackStudio/main.cpp
- Userland/Services/NotificationServer/NotificationWindow.cpp
We previously popped a MessageBox for this, but a notification is less disruptive.
> HackStudio: Show notification if 'make' is not available

- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.h
- Userland/Libraries/LibCpp/AST.h
- Userland/Libraries/LibCpp/Parser.cpp
- Userland/Libraries/LibCpp/Parser.h
- Function & struct/class names
- Include declarations from headers
- Autocomplete request on an empty token brings up all available names
> C++ autocomplete - Continued

- Kernel/CMakeLists.txt
- Kernel/UBSanitizer.cpp
- Kernel/UBSanitizer.h
A step to add more ubsan support in the kernel.
Missing handlers:
* cfi_bad_type
* cf_bad_icall
* cfi_chack_fail
Some use of the "ValueHandel"s is included, but with or with out boot crashes
Build succeeds at the moment, but boot fails to early for backtracing:
<details>
<summary>Error output</summary>
```
Executing task in folder serenity: qemu-system-i386 -L "C:\Program Files\qemu" -s -m 4G -cpu max -d cpu_reset,guest_errors -no-reboot -smp 2 -device VGA,vgamem_mb=64 -drive file=_disk_image,format=raw,index=0,media=disk -device ich9-ahci -usb -debugcon stdio -soundhw pcspk -device sb16 -netdev user,id=breh,hostfwd=tcp:127.0.0.1:8888-10.0.2.15:8888,hostfwd=tcp:127.0.0.1:8823-10.0.2.15:23 -device e1000,netdev=breh -kernel Kernel/Kernel -append hello <
CPU Reset (CPU 0)
EAX=00000000 …
```
> KUBSAN: Add nearly all missing -fsanitize handlers

- Userland/Libraries/LibGUI/Window.h
- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
> WindowServer: Recompute occlusions when changing window's alpha channel

- Kernel/Net/NetworkTask.cpp
* We don't have to lock the "all IPv4 sockets" in exclusive mode, shared mode is enough for just reading the list (as opposed to modifying it).
* We don't have to lock socket's own lock at all, the `IPv4Socket::did_receive()` implementation takes care of this.
* Most importantly, we don't have to hold the "all IPv4 sockets" across the `IPv4Socket::did_receive()` call(s). We can copy the current ICMP socket list while holding the lock, then release the lock, and then call `IPv4Socket::did_receive()` on all the ICMP sockets in our list.
These changes fix a deadlock triggered by receiving ICMP messages when using tap
networking setup (as opposed to QEMU's default user/SLIRP networking) on the host.
cc @alimpfard @tomuta
> Kernel: Hold less locks when receiving ICMP packets

- Base/home/anon/.config/FileManager.ini
- Base/home/anon/.config/TextEditor.ini
- Userland/Applications/FileManager/FileManagerWindow.gml
- Userland/Applications/FileManager/main.cpp
- Userland/Applications/TextEditor/TextEditorWidget.cpp
- Userland/Applications/TextEditor/TextEditorWidget.h
- Userland/Applications/TextEditor/TextEditorWindow.gml
> TextEditor+FileManager: a few new menu features and fixes

- Meta/Lagom/Fuzzers/CMakeLists.txt
- Meta/Lagom/Fuzzers/FuzzRSAKeyParsing.cpp
> Lagom/Fuzzers: Add RSA key parser fuzzer

- Kernel/Syscalls/select.cpp
- Userland/Utilities/syscall.cpp
#5323 will take some time to implement properly. Until then, this PR tries to bring in all the uncontroversial commits.
> "Small" Fuzz-related fixes

- Ports/ReadMe.md
As requested in https://github.com/SerenityOS/serenity/pull/5346#issuecomment-778810665.
> Ports: Document build_{all,installed}.sh

- Userland/Libraries/LibGUI/ScrollableWidget.cpp
> LibGUI: Set correct ranges for hidable scrollbars

- Base/res/apps/PixelPaint.af
> Base: Make PixelPaint launch handler for .pp files

- Kernel/Net/Routing.cpp
- Userland/Services/DHCPClient/DHCPv4.h
- Userland/Services/DHCPClient/DHCPv4Client.cpp
- Userland/Services/DHCPClient/main.cpp
cc @bugaevc 
Might also deal with #4412, should probably be checked.
> DHCPClient: Make it work on TAP interfaces (aka real interfaces) 

- Userland/Applications/PixelPaint/main.cpp
This is obviously a requirement for #5374, oops :^)
Also handle errors gracefully, opening a file that isn't PixelPaint JSON would previously crash.
Closes #5388.
> PixelPaint: Open image file passed as argument

- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/WindowFrame.cpp
> WindowServer: Apply the backing bitmap's scale when alpha hit-testing

- Userland/Services/WindowServer/WindowManager.cpp
> WindowServer: Ignore other button presses while moving/resizing windows

- Userland/Applications/DisplaySettings/DisplaySettings.cpp
There's no point in showing the revert dialog for strictly wallpaper changes.
> DisplaySettings: Show revert dialog only for resolution/dpi changes.

- CMakeLists.txt
- Ports/gcc/patches/gcc.patch
- Toolchain/Patches/gcc.patch
> Toolchain: Use -ftls-model=initial-exec by default

- Base/usr/share/man/man7/Mitigations.md
Document:
* Unmap After Init
* RELRO
* -fstack-clash-protection
* -fstack-protector / -fstack-protector-strong
> Base: Document more the mitigations in man7/Mitigations.md

- Ports/AvailablePorts.md
> Please make sure to keep this list up to date when adding and updating ports. :^)
> Ports: Update vttest version in AvailablePorts.md

- Userland/Libraries/LibGUI/IconView.cpp
- Userland/Libraries/LibGUI/ScrollableWidget.cpp
- Userland/Libraries/LibGUI/ScrollableWidget.h
- Userland/Libraries/LibGUI/TreeView.cpp
> LibGUI: iron out some more scrollable wrinkles

- Userland/Services/WindowServer/WindowFrame.cpp
This fixes some artifacts with very small tooltip windows.
> WindowServer: Improve small tooltips/windows shadows a bit

- Userland/Demos/Cube/Cube.cpp
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGUI/Window.h
- Userland/Services/Taskbar/TaskbarWindow.cpp
- Userland/Services/WindowServer/ClientConnection.cpp
- Userland/Services/WindowServer/ClientConnection.h
- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/WindowServer.ipc
_This also exposes a weird menu bug. When you right-click the context menu, you'll see the app menu button highlighted. But what's worse is when you subsequently open it through the menu bar it'll open at the last context menu position._
> Cube: Add an option to render a frameless cube

- AK/ByteBuffer.cpp
__builtin_memcmp is already heavily utilised in AK.
P.S. I'm new with contributing to open source – I hope I'm doing it the right way with branches etc., otherwise please let me know.
> AK: Alter ByteBuffer to utilise memcmp.

- Userland/Applications/Run/RunWindow.cpp
> Run: Prefill text field with last command on launch

- Userland/Libraries/LibGUI/LinkLabel.cpp
- Userland/Libraries/LibGUI/LinkLabel.h
> LibGUI: Show context menu when right-clicking a LinkLabel

- Base/usr/share/man/man1/Inspector.md
- Userland/DevTools/Inspector/CMakeLists.txt
- Userland/DevTools/Inspector/main.cpp
> Inspector: Add help documentation

- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
- Userland/Libraries/LibWeb/OutOfProcessWebView.h
- Userland/Libraries/LibWeb/WebContentClient.cpp
- Userland/Libraries/LibWeb/WebContentClient.h
- Userland/Libraries/LibWeb/WebViewHooks.h
- Userland/Services/WebContent/ClientConnection.cpp
- Userland/Services/WebContent/ClientConnection.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentServer.ipc
Implements the view source functionality for out of process mode.
> Browser: Implement view source for out of process mode.

- Userland/DevTools/Profiler/ProfileTimelineWidget.cpp
If you drag-select a slice of the profile off of the side of the
Profiler window, the profiler will try to render a negative start time,
which will overflow. This commit fixes that bug by clamping timestamps
to the start/end of the profile before rendering.
This fixes the rendering bug that was seen in the most recent video. I have no idea about the crashes though.
> Profiler: Make sure rendered timestamps don't overflow

- Userland/Libraries/LibLine/Editor.cpp
- Userland/Libraries/LibLine/InternalFunctions.cpp
> LibLine: Less laziness, even though we really want it to be lazy

- Userland/Libraries/LibELF/DynamicLinker.cpp
- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicObject.cpp
- Userland/Libraries/LibELF/Image.cpp
Most of these won't have perf impact, but the optimization is
practically free, so no harm in fixing these up.
> LibELF: Convert more string literals to StringView literals.

- Base/usr/share/man/man1/Profiler.md
- Userland/DevTools/Profiler/CMakeLists.txt
- Userland/DevTools/Profiler/main.cpp
> Profiler: Add help documentation

- Userland/Applications/Spreadsheet/JSIntegration.cpp
- Userland/Applications/Spreadsheet/Position.h
- Userland/Applications/Spreadsheet/Spreadsheet.cpp
- Userland/Applications/Spreadsheet/Spreadsheet.h
- Userland/Applications/Spreadsheet/SpreadsheetModel.cpp
- Userland/Applications/Spreadsheet/SpreadsheetView.cpp
- Userland/Applications/Spreadsheet/main.cpp
- Userland/Libraries/LibGUI/TableView.cpp
> Spreadsheet: Store the column index in a Position instead of its name / LibGUI: Don't paint all the table when headers are visible

- Userland/Applications/FileManager/main.cpp
A small detail to match with the new File Manager icon in context menu. :^)
> FileManager: change icon for Show in File Manager

- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Applications/Browser/WindowActions.cpp
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.h
- Userland/Applications/HexEditor/main.cpp
- Userland/Applications/Spreadsheet/main.cpp
- Userland/Applications/Terminal/main.cpp
- Userland/Applications/TextEditor/TextEditorWidget.cpp
- Userland/Applications/TextEditor/TextEditorWidget.h
- Userland/Applications/TextEditor/main.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/Libraries/LibGUI/LinkLabel.cpp
Standardizes menus across a couple apps and fixes #5177
> Menu Clean-up

- Documentation/CLionConfiguration.md
> Documentation: Update CLion configuration documentation

- Userland/Applications/Browser/ConsoleWidget.cpp
- Userland/Applications/Browser/ConsoleWidget.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
- Userland/Libraries/LibWeb/OutOfProcessWebView.h
- Userland/Libraries/LibWeb/WebContentClient.cpp
- Userland/Libraries/LibWeb/WebContentClient.h
- Userland/Libraries/LibWeb/WebViewHooks.h
- Userland/Services/WebContent/CMakeLists.txt
- Userland/Services/WebContent/ClientConnection.cpp
- Userland/Services/WebContent/ClientConnection.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentConsoleClient.cpp
- Userland/Services/WebContent/WebContentConsoleClient.h
- Userland/Services/WebContent/WebContentServer.ipc
First attempt at implementing multi-process JS console.
> Browser: Multi-process JS console implementation.

- Base/usr/share/man/man1/mktemp.md
- Userland/Utilities/mktemp.cpp
> Userland: Add a simple mktemp(1) utility

- Userland/Libraries/LibGUI/TextEditor.cpp
Drawing text with spans was previously very inefficient.
To see the full difference disable kvm, open up a large c++ File in HackStudio and drag the scroll bar around.
> LibGUI: Faster spanned text

- Userland/Applications/FileManager/PropertiesWindow.cpp
- Userland/Applications/FileManager/main.cpp
- Userland/Libraries/LibGUI/Model.h
- Userland/Services/LaunchServer/Launcher.cpp
> FileManager+Everywhere: Add starting filemanager with focus on file

- Userland/Libraries/LibWeb/Layout/BlockBox.cpp
- Userland/Libraries/LibWeb/Layout/BlockBox.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
- Userland/Libraries/LibWeb/OutOfProcessWebView.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/WebContentClient.cpp
- Userland/Libraries/LibWeb/WebContentClient.h
- Userland/Services/WebContent/PageHost.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentClient.ipc
> LibWeb: Handle scrolling an OutOfProcessWebView

- Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
- Userland/Applications/SpaceAnalyzer/TreeMapWidget.h
- Userland/Libraries/LibGfx/Rect.h
-Adds take_from_{left,right,top,bottom} to Rect.
Before:
After:
> SpaceAnalyzer: Reduce thickness of black borders between cells.

- Userland/Libraries/LibJS/Runtime/BigIntConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibJS/Tests/custom-@@toPrimitive.js
> LibJS: Support @@toPrimitive in ToPrimitive abstract operation

- Userland/DevTools/HackStudio/HackStudioWidget.cpp
At first, I think this will be an interesting hack but it turns out I just need to change the selection mode, the library has handled all the thing. Anyways, I am going to dig in the code to see how ctrl + clicking is handled. By the way, thank you guys for such a great project.
> HackStudio: Allow multi-selection in project view tree

- Ports/AvailablePorts.md
- Ports/libpng/package.sh
- Ports/libpng/patches/detect.patch
Port of libpng that i used under Serenity for my experiments
> Ports: Add libpng 1.6.37

- Userland/Libraries/LibGUI/TextEditor.cpp
> TextEditor: Don't attempt to stop the autocomplete timer if it is null

- Userland/Applications/SystemMonitor/ProcessModel.cpp
- Userland/Applications/SystemMonitor/ProcessModel.h
- Userland/Libraries/LibGUI/AbstractTableView.cpp
- Userland/Libraries/LibGUI/AbstractTableView.h
- Userland/Libraries/LibGUI/ColumnsView.h
- Userland/Libraries/LibGUI/TableView.cpp
> LibGUI: Increase row height in Table/ColumnViews and center icons 

- Userland/DevTools/Profiler/main.cpp
> Profiler: Get perfcore file from ArgsParser

- AK/StdLibExtras.h
- AK/Tests/TestTypeTraits.cpp
I needed these meta-programming type traits while working on something else
add basic support as well as some tests.
> AK: Implement IsEnum<T> and UnderlyingType<T> type traits

- Userland/Services/WebContent/PageHost.cpp
> WebContent: Set correct scroll offset for PageHost painting

- Ports/AvailablePorts.md
- Ports/bzip2/package.sh
Saw that it can be included with the freetype port, so I added it.
> Ports: Add bzip2 port

- Userland/Libraries/LibGfx/Painter.cpp
This fixes some precision issues in Painter::draw_triangle()
that caused the Cube demo to leave pixels empty between triangles
under certain angles.
Also adds some extra comments for clarity and early returns when
parts of the triangle do not need to be drawn.
fixes #5647
> LibGfx: Fix draw_triangle() precision issues

- Userland/Applications/Serendipity/SerendipityWindow.gml
- Userland/Applications/Serendipity/main.cpp
> Serendipity: Make main window resizable

- Userland/Applications/FileManager/DirectoryView.cpp
- Userland/Applications/FileManager/DirectoryView.h
- Userland/Applications/FileManager/main.cpp
> FileManager: Disable view change actions when directory is unreadable

- Ports/AvailablePorts.md
- Ports/genemu/package.sh
- Ports/genemu/patches/genemu.patch
I didn't notice any genesis/megadrive emulator ports for Serenity, so I decided to do it myself!
This is a Basic Genesis / MegaDrive Emulator, that only requires SDL2 to run it.
You can run this using `genemu /path/to/game.bin` command.
Screenshots: 
Games I tested so far are Sonic 1 and 2.
This is my first contribution, so I hope I'm doing this right!
> Ports: Add Genemu

- Ports/AvailablePorts.md
- Ports/libogg/package.sh
- Ports/libogg/patches/configure.patch
This library will allow us to port more multimedia programs and games,
since it's a common dependency of such projects. I was looking at
Scummvm's dependencies in particular, with a goal of porting them all
eventually, so that we can have Myst running in Serenity!
It's my first time trying to port something, so hopefully I did it somewhat correctly. 😅
> Ports: Add libogg

- Userland/DevTools/HackStudio/Editor.cpp
> HackStudio: Add language client check in identifier click

- Base/res/fortunes.json
- Userland/Utilities/fortune.cpp
I told you, we need a quotes ~~page~~ file! :D
This even comes with fancy formatting and a tasteful selection ready to go! :^)
And look at this wonderful integration: It even links directly to the quote on logbot! (However, it can't be opened in Browser yet, probably a TLS thing is missing I guess.)
CC everyone in #5698, especially @linusg
Even though the IRC channel is publicly logged, I would still think it is nice to first ask before you quote someone out of context, so either check whether they have agreed to do so in #5698, or just ask them in person. Thanks!
> Utilities: Add a quotes database and 'fortunes' program

- Meta/serenity.sh
This uses tmux for a split screen setup, which makes it easy do debug
the kernel while viewing the QEMU output in the same terminal.
Example uses:
```
./Meta/serenity.sh gdb
```
Or, if you want to automatically set a break point and boot with `smp=on`:
```
./Meta/serenity.sh gdb i686 smp=on -ex 'hb *init_stage2'
```
> Meta: Add gdb command to serenity.sh

- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
F2XM1
FYL2X
FYL2XP1
FDECSTP
FINCSTP
FSCALE
> UserspaceEmulator: SoftCPU: Add support for several x86 FPU instructions

- Meta/serenity.sh
cc @tomuta, hope you agree with these :)
> Meta: serenity.sh tweaks and better Lagom support

- Base/usr/share/man/man1/QuickShow.md
- Userland/Applications/QuickShow/main.cpp
> QuickShow: Add help documentation

- Ports/klong/package.sh
> Ports: Fix klong's package.sh

- AK/BinaryHeap.h
- AK/BitStream.h
- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
Several small changes and optimizations to AK::BitOutputStream, AK::BinaryHeap and Compress::DeflateCompressor based on Hans Wennborg's comments in #5750.
> AK+LibCompress: tidbits and optimizations

- Userland/Utilities/readelf.cpp
`readelf` now supports core notes and relocations. Perhaps the must immediately useful feature is the ability to read notes from core dump files.
This also adds minimal output for the dynamic section (simply printing the number of dynamic entries, but not displaying these entries).
This also adds output for unwind which simply prints a message stating that unwind info is not supported. This is the same as GNU `readelf` which supports unwind info only for a very limited number of architectures (ie, not x86 and x86_64). However, GNU `readelf` attempts to parse unwind information as part of `-a` (all) (even though it will usually fail) and so does our `readelf`. Thus adding a message related to unwind info is included for consistency.
> readelf: Add support for core notes and relocations

- Userland/DevTools/UserspaceEmulator/Emulator.cpp
> UserspaceEmulator: Increase stack size from 64 * KiB to 1 * MiB

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Interpreter.cpp
- Userland/Libraries/LibJS/Interpreter.h
- Userland/Libraries/LibJS/Tests/eval-basic.js
- Userland/Libraries/LibWeb/DOM/Document.cpp
*see commit messages for details*
> LibJS: Implement non-value-producing statements properly

- Userland/Libraries/LibLine/Editor.cpp
At the cost of using more read() syscalls, process the DSR response
character-by-character.
This avoids blocking forever waiting for an 'R' that will never come :P
cc @awesomekling: you can have your prompt now.
Let's at least fix this bug until we can come up with the line editor of our dreams lol
> LibLine: Make the DSR response parser a bit more robust

- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Tests/builtins/BigInt/bigint-basic.js
Thanks to @IdanHo for pointing this out!
> LibJS: BigInt division/modulo/exponentiation exceptions

- Userland/Libraries/LibCompress/Deflate.cpp
Fixes:
- Since we were not checking for error flags set by read_bits we would just always read 0 as the bits' value, which in some edge cases could lead to an infinite loop.
Found as a result of investigating https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31750, and should fix it
- Fail gracefuly instead of VERIFYing when the huffman code is missing from the provided huffman tree
Found as a result of investigating https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32119, and should fix it
> LibCompress: Fixes for several fuzzing bugs

- Userland/Applications/QuickShow/QSWidget.cpp
- Userland/Applications/QuickShow/QSWidget.h
- Userland/Libraries/LibGUI/ImageWidget.cpp
*\* some additional lag introduced by making a GIF of a GIF*
> QuickShow: Animate animated images :^)

- Userland/Libraries/LibCompress/Deflate.cpp
fixes #5838 (which was also just found by oss-fuzz https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32143) and fixes #5839.
> LibCompress: More fuzz fixes

- Userland/Applications/Spreadsheet/SpreadsheetView.cpp
- Userland/Libraries/LibGUI/AbstractTableView.cpp
- Userland/Libraries/LibGUI/AbstractTableView.h
- Userland/Libraries/LibGUI/HeaderView.cpp
- Userland/Libraries/LibGUI/HeaderView.h
> LibGUI: Support double-click resizing column headers 

- Userland/Utilities/readelf.cpp
Based on [checksec](https://github.com/slimm609/checksec.sh) utility.
> readelf: Add --checksec flag to display security hardening info

- Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
> LibJS: Support month and day arguments of Date.setFullYear

- Userland/Libraries/LibCompress/Deflate.cpp
This way a deflate blob that contains a large amount of small blocks wont cause a stack overflow.
(Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32223)
> LibCompress: Convert DeflateDecompressor from recursive to iterative

- Ports/AvailablePorts.md
- Ports/vitetris/package.sh
- Ports/vitetris/patches/workaround.patch
A quick port of vitetris. Only one small hack had to be done to get it to compile and run.
> Ports: vitetris

- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
Extremely small change, all I did is check for application/json, mime type and parsed it as text.
> LibWeb: Add support to view JSON.

- Userland/DevTools/HackStudio/EditorWrapper.cpp
- Userland/DevTools/HackStudio/EditorWrapper.h
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/DevTools/HackStudio/ProjectFile.cpp
- Userland/DevTools/HackStudio/ProjectFile.h
- Userland/Libraries/LibGUI/TextDocument.cpp
- Userland/Libraries/LibGUI/TextDocument.h
> HackStudio: Display warning when opening binary files

- Kernel/CMakeLists.txt
- Kernel/CommandLine.cpp
- Kernel/CommandLine.h
- Kernel/Devices/AsyncDeviceRequest.h
- Kernel/PCI/Access.cpp
- Kernel/PCI/Definitions.h
- Kernel/Storage/AHCI.h
- Kernel/Storage/AHCIController.cpp
- Kernel/Storage/AHCIController.h
- Kernel/Storage/AHCIPort.cpp
- Kernel/Storage/AHCIPort.h
- Kernel/Storage/IDEChannel.cpp
- Kernel/WorkQueue.cpp
- Kernel/WorkQueue.h
- Kernel/init.cpp
Thanks to @tomuta, and his great work in #5184, I'm able to provide interrupt-based solution for the AHCI code, so performance is not so bad and things seem to work on real hardware just fine :)
> Kernel/AHCI: Prepare for working on real hardware and VMWare

- Userland/Libraries/LibCompress/Gzip.cpp
This way a gzip compressed file that contains a large amount of small blocks wont cause a stack overflow.
(This is similar to #5872 and found by/fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32298)
Sorry for the large amount of LibCompress deflate/gzip decompresion fixes lately, looks like our existing decompressors werent as robust as i'd like them to be, but all of these fixes should help with that :)
> LibCompress: Convert GzipDecompressor from recursive to iterative

- Userland/Applications/Spreadsheet/ImportDialog.cpp
- Userland/Applications/Spreadsheet/JSIntegration.cpp
- Userland/Applications/Spreadsheet/Spreadsheet.cpp
- Userland/Applications/Spreadsheet/SpreadsheetView.h
- Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
- Userland/Applications/Spreadsheet/SpreadsheetWidget.h
- Userland/Applications/Spreadsheet/main.cpp
Fixes #5909.
Fixes #5905.
Fixes #5910.
Fixes #4822 (as far as I can tell).
Also fixes an undocumented crash when trying to run some cells with invalid syntax (like `1+`).
> Spreadsheet: A few more fixes

- Kernel/CommandLine.cpp
- Kernel/CommandLine.h
- Kernel/Interrupts/SpuriousInterruptHandler.cpp
- Kernel/Interrupts/SpuriousInterruptHandler.h
- Kernel/Storage/AHCIController.cpp
@Lubrsi can you please test this patch and tell if it works for you?
> Kernel: Make VMWare to boot with AHCI

- AK/JsonArray.h
- Userland/Applications/Browser/BookmarksBarWidget.cpp
- Userland/Applications/Browser/BookmarksBarWidget.h
- Userland/Applications/Browser/CMakeLists.txt
- Userland/Applications/Browser/EditBookmark.gml
- Userland/Libraries/LibGUI/JsonArrayModel.cpp
- Userland/Libraries/LibGUI/JsonArrayModel.h
Hello - learning my way around the system, figured a fun starting point was to add a widget to edit bookmarks in the Browser :)
> Browser: Add right-click context menu item for editing bookmarks

- Userland/Utilities/gunzip.cpp
Several small fixes to the gunzip utility:
- Fail gracefully instead of asserting on a missing input file
- Fail gracefully instead of looping forever on a bad (not gzip compressed) input file
- Fail gracefully instead of asserting on a permission problem in the output file
> gunzip: Fail gracefully on bad input

- Base/usr/share/man/man2/module_unload.md
`modunload.md` has moved to `man8`
> Base: Update `modunload` path

- Userland/Applications/Spreadsheet/ExportDialog.cpp
- Userland/Applications/Spreadsheet/ExportDialog.h
- Userland/Applications/Spreadsheet/ImportDialog.cpp
- Userland/Applications/Spreadsheet/ImportDialog.h
- Userland/Applications/Spreadsheet/Readers/XSV.cpp
- Userland/Applications/Spreadsheet/Readers/XSV.h
- Userland/Applications/Spreadsheet/csv_import.gml
- Userland/Libraries/LibGUI/StackWidget.cpp
...and don't try to read from a CSV that has errors.
Fixes #5942.
Edit: 5942 != 4592.
> Spreadsheet: Show the error (if any) in csv import dialog's preview 

- Userland/Utilities/dd.cpp
Recently started to work on Serenity and really missed this tool, so I implemented it:
> Utilities:  Added my version of 'dd'

- Ports/AvailablePorts.md
- Ports/libvorbis/package.sh
- Ports/libvorbis/patches/01-add-serenity-system.patch
> Ports: add libvorbis

- Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Userland/Libraries/LibJS/Runtime/RegExpPrototype.h
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.replace.js
"Eh the spec for `replace` can't be that bad" - me, living in a simpler past :)
> LibJS: Implement most of String.prototype.replace

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Reference.cpp
- Userland/Libraries/LibJS/Runtime/Reference.h
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibJS/Tests/strict-mode-errors.js
By-product of another investigation.
> LibJS: Reference assignment error changes

- Documentation/BuildInstructions.md
The existing macOS documentation is pretty good, but incomplete. This fills in some of the gaps.
> Improve macOS build docs

- Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.slice.js
Hey :wave: I'm a long-time observer, first-time contributor to Serenity :)
I've implemented this as to the specification as I could, I hope that this meets expectations.
---
Implements the aforementioned native Javascript function, following the
specification's [1] implementation.
[1] https://tc39.es/ecma262/#sec-arraybuffer.prototype.slice
> LibJS: ArrayBuffer.prototype.slice

- Ports/AvailablePorts.md
- Ports/cmatrix/package.sh
- Ports/cmatrix/patches/fix_cmakelists.patch
- Ports/cmatrix/patches/fix_include_header.patch
> Ports: Added a cmatrix port

- Ports/AvailablePorts.md
- Ports/SDLPoP/package.sh
- Ports/SDLPoP/patches/disable_extra_features.patch
- Ports/SDLPoP/patches/link_against_serenity_libs.patch
- Ports/SDLPoP/patches/remove_fscanf_unknwn_conversion_specfier.patch
- Ports/SDLPoP/patches/remove_strtoimax.patch
This is a port of the dissasembly version of the DOS prince of persia
game :)
> Ports: Added a Prince of Persia (SDLPoP) port.

- Ports/AvailablePorts.md
- Ports/scummvm/package.sh
- Ports/scummvm/patches/config.sub.patch
- Ports/scummvm/patches/configure.patch
- Userland/Libraries/LibC/netdb.h
- Userland/Libraries/LibC/scanf.cpp
- Userland/Tests/LibC/scanf.cpp
Add ScummVM to the ports! Being able to play Day of the Tentacle inside of Serenity is something else :-) [list of supported games](https://wiki.scummvm.org/index.php/Category:Supported_Games).
> Ports: Add ScummVM

- Userland/Services/WindowServer/AppletManager.cpp
- Userland/Services/WindowServer/AppletManager.h
- Userland/Services/WindowServer/WindowManager.cpp
These changes fix #6061 and #6056.
> WindowServer: Applet area fixes

- Userland/Libraries/LibJS/Tests/builtins/RegExp/RegExp.prototype.exec.js
- Userland/Libraries/LibRegex/RegexMatcher.cpp
- Userland/Libraries/LibRegex/RegexParser.cpp
Fixes #6131, and another undocumented conformance bug.
> LibRegex: MOAR fixes

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ReflectObject.cpp
- Userland/Libraries/LibJS/Tests/builtins/Reflect/Reflect.ownKeys.js
Back to LibJS internals for my 1000th commit here :^)
> LibJS: Some object refactoring and a fix for Reflect.ownKeys()

- Ports/AvailablePorts.md
- Ports/oksh/package.sh
- Ports/oksh/patches/disable_flock.patch
- Ports/oksh/patches/disable_rlimit.patch
- Ports/oksh/patches/disable_tty.patch
- Ports/oksh/patches/implement_isblank.patch
- Ports/oksh/patches/remove_issetugid.patch
- Ports/oksh/patches/remove_redeclarations.patch
Currently has some problems such as not killing jobs when (ctrl + c) and depends on an implementation of sigsuspend.
> Ports: Added an oksh port

- Ports/AvailablePorts.md
- Ports/Super-Mario/package.sh
- Ports/Super-Mario/patches/disable_graphic_acceleration.patch
- Ports/Super-Mario/patches/disable_music.patch
- Ports/Super-Mario/patches/fix_cmakelists.patch
- Ports/Super-Mario/patches/fix_fireball_header.patch
Added a minimal dependency super mario port. (Only depends on SDL, SDL_image and SDL_mixer).
I do have some questions about this port tho. Currently I created an $install_location variable in the package.sh, which is where all the game files and executable will be installed, as currently the game seems to only work when the game files are in the same place as the executable.
Is there any better way to do this? Currently it feels kinda hackish in the bad way :^(
> Ports: Added a Super-Mario clone port.

- Kernel/Storage/RamdiskController.cpp
- Kernel/Storage/RamdiskDevice.cpp
- Kernel/Storage/RamdiskDevice.h
> Kernel: Fix ramdisk support

- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.cpp
- Userland/Libraries/LibCpp/AST.cpp
- Userland/Libraries/LibCpp/AST.h
- Userland/Libraries/LibCpp/Parser.cpp
- Userland/Libraries/LibCpp/Parser.h
- Userland/Libraries/LibGUI/AutocompleteProvider.cpp
- Userland/Libraries/LibGUI/AutocompleteProvider.h
Various parser improvements with the goal of parsing the `strace.cpp` source.
Marking this as draft for now as we can't yet parse everything that's in there.
> LibCpp: Various parser improvements

- Userland/Applications/FontEditor/CMakeLists.txt
- Userland/Applications/FontEditor/FontEditor.cpp
- Userland/Applications/FontEditor/FontEditor.h
- Userland/Applications/FontEditor/FontEditorWindow.gml
- Userland/Applications/FontEditor/GlyphEditorWidget.cpp
- Userland/Applications/FontEditor/GlyphEditorWidget.h
- Userland/Applications/FontEditor/GlyphMapWidget.cpp
- Userland/Applications/FontEditor/GlyphMapWidget.h
- Userland/Applications/FontEditor/main.cpp
- Userland/Libraries/LibGUI/CheckBox.cpp
- Userland/Libraries/LibGUI/CheckBox.h
- Userland/Libraries/LibGUI/FilePicker.cpp
- Userland/Libraries/LibGUI/FilePicker.h
> FontEditor: Improved interface and edit commands

- Kernel/Arch/x86/CPU.h
- Kernel/CommandLine.cpp
- Kernel/PCI/MMIOAccess.cpp
- Kernel/PCI/WindowedMMIOAccess.cpp
- Kernel/Storage/IDEChannel.cpp
Still a draft, but getting closer to fix issue #6116.
> Kernel: More bare metal fixes #3

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Runtime/Array.cpp
- Userland/Libraries/LibJS/Runtime/Array.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.h
- Userland/Libraries/LibJS/Runtime/ReflectObject.cpp
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.freeze.js
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.isFrozen.js
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.isSealed.js
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.seal.js
(not related to Dromaeo :smile:)
> LibJS: Implement Object.freeze(), Object.seal(), Object.isFrozen() and Object.isSealed()

- Userland/Libraries/LibTLS/Record.cpp
The debug console was full of 'Update hash with message of size x'.
> LibTLS: Hide some debug spam, use more dbgln_if and if constexpr

- Documentation/NetworkBoot.md
Add dnsmasq configuration instructions to network boot guide
> Documentation: Add dnsmasq configuration instructions to network boot guide

- Kernel/StdLib.cpp
- Userland/DevTools/UserspaceEmulator/Emulator_syscalls.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
- Userland/DevTools/UserspaceEmulator/SoftMMU.h
- Userland/Libraries/LibC/string.cpp
- Userland/Libraries/LibJS/Heap/Heap.cpp
Trying to fix everything I found in #5929
Problems:
1. ~the "fix" to exclude malloc and free in the malloc tracker does not seems to work~ It throws complaints in malloc and free, but malloc and free are specifically exempt form these "errors"
2. ~Hashmap does seem to use "uninitialized data" even though everything should be memeset to 0~
regarding 2:  
the error apears in test-js->Heap.cpp and seems to points at
https://github.com/SerenityOS/serenity/blob/2f9321a0d43f3543a50aabb75bb5b6f601ac7b94/AK/HashTable.h#L340
but again every thing should be set to 0 or is a reference to a value, which should be set
> UE: Some bug fixes

- Userland/Libraries/LibRegex/RegexParser.cpp
- Userland/Libraries/LibRegex/RegexParser.h
Thanks to @GMTA: https://github.com/SerenityOS/serenity/commit/1b071455b1793dbfc7039a9090540ba0aeaf3221#r49343474
> LibRegex: Remove 'ReadDigitFollowPolicy' as it's no longer needed

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.h
- Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
- Userland/Libraries/LibJS/Runtime/ProxyObject.h
- Userland/Libraries/LibJS/Runtime/ReflectObject.cpp
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.create.js
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.defineProperties.js
- Userland/Libraries/LibJS/Tests/loops/for-in-basic.js
- Userland/Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/EventTarget.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.h
Not quite there yet, it currently chokes on missing `cloneNode()` - but this is getting crowded already, so here's a first PR.
> LibJS+LibWeb: Implement various missing things to get a Vue.js hello world running

- .github/workflows/cmake.yml
These are similar to the existing irc notifications.
(the accompanying discord channel + webhook + github secret has to be created as well)
> Meta: Add discord notifications for pushes and pull requests

- Userland/Applications/FontEditor/CMakeLists.txt
- Userland/Applications/FontEditor/FontEditor.cpp
- Userland/Applications/FontEditor/FontEditor.h
- Userland/Applications/FontEditor/FontEditorWindow.gml
- Userland/Applications/FontEditor/GlyphEditorWidget.h
- Userland/Applications/FontEditor/GlyphMapWidget.h
- Userland/Applications/FontEditor/NewFontDialog.cpp
- Userland/Applications/FontEditor/NewFontDialog.h
- Userland/Applications/FontEditor/NewFontDialogPage1.gml
- Userland/Applications/FontEditor/NewFontDialogPage2.gml
- Userland/Applications/FontEditor/main.cpp
- Userland/Libraries/LibGUI/FontPicker.cpp
- Userland/Libraries/LibGUI/FontPickerWeightModel.h
- Userland/Libraries/LibGfx/BitmapFont.cpp
- Userland/Libraries/LibGfx/BitmapFont.h
> FontEditor: Comfy Wizard Edition

- Ports/AvailablePorts.md
- Ports/yasm/package.sh
- Ports/yasm/patches/patch-configure.patch
This is a required dependency for many libraries such as libx264
which i'm interested in porting in the future
> Ports: Add Port for the yasm assembler

- Userland/Applications/Browser/ConsoleWidget.cpp
- Userland/Applications/Spreadsheet/JSIntegration.cpp
- Userland/Applications/Spreadsheet/JSIntegration.h
- Userland/Libraries/LibJS/MarkupGenerator.cpp
- Userland/Libraries/LibJS/MarkupGenerator.h
- Userland/Libraries/LibJS/Runtime/Error.cpp
- Userland/Libraries/LibJS/Runtime/Error.h
- Userland/Libraries/LibJS/Runtime/ErrorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ErrorConstructor.h
- Userland/Libraries/LibJS/Runtime/ErrorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ErrorPrototype.h
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
- Userland/Libraries/LibJS/Runtime/ProxyObject.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/Tests/runtime-error-call-stack-size.js
- Userland/Libraries/LibWeb/Bindings/CSSStyleDeclarationWrapperCustom.cpp
- Userland/Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
- Userland/Services/WebContent/WebContentConsoleClient.cpp
- Userland/Utilities/js.cpp
cc @Lubrsi, can you confirm that this fixes the error you had on a website earlier?
> LibJS: Make Errors fully spec compliant

- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
> LibJS: Memoize failed calls of try_parse_arrow_function_expression()

- Userland/Libraries/LibWeb/CSS/Parser/DeprecatedCSSParser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/DeprecatedCSSParser.h
- Userland/Libraries/LibWeb/CSS/StyleResolver.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
Before: ![image](https://user-images.githubusercontent.com/30466983/114411403-d0892700-9bb4-11eb-8e2e-457b97f99245.png)
After:
> LibWeb: Improve border rendering

- Kernel/Net/NE2000NetworkAdapter.cpp
- Kernel/Storage/AHCIController.h
- Kernel/Storage/IDEController.h
- Kernel/Storage/PATADiskDevice.h
- Kernel/Storage/Partition/EBRPartitionTable.h
- Kernel/Storage/Partition/GUIDPartitionTable.h
- Kernel/Storage/Partition/MBRPartitionTable.h
- Kernel/Storage/Partition/PartitionTable.h
- Kernel/Storage/RamdiskController.h
- Kernel/Storage/RamdiskDevice.h
- Kernel/Storage/SATADiskDevice.h
- Kernel/Storage/StorageController.h
- Kernel/Storage/StorageDevice.h
- Kernel/Storage/StorageManagement.cpp
- Kernel/Storage/StorageManagement.h
- Userland/Games/Minesweeper/Field.cpp
- Userland/Games/Minesweeper/Field.h
- Userland/Libraries/LibCore/AnonymousBuffer.cpp
Mostly stuff that I've stumbled upon while browsing the code and I'm too lazy to open three PRs for these.
> All: Various fixes and cleanups

- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleResolver.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Some improvements to make acid2 render more correctly
> LibWeb: Various improvements

- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
- Userland/Libraries/LibWeb/DOM/ProcessingInstruction.h
This concludes my efforts towards getting a Vue.js hello world running in the browser :^)
([part 1](https://github.com/SerenityOS/serenity/pull/6218), [part 2 (secretly)](https://github.com/SerenityOS/serenity/pull/6284))
> LibWeb: Implement Node.cloneNode()

- Ports/AvailablePorts.md
- Ports/nasm/package.sh
- Ports/nasm/patches/config.sub.patch
This update gets around the build issues i was facing
as reported in issue #6157
Merging this commit will fix and close issue #6157
> Ports: Update nasm port to version 2.15.05

- Ports/AvailablePorts.md
- Ports/gnupg/package.sh
- Ports/gnupg/patches/configure.patch
- Ports/libassuan/package.sh
- Ports/libassuan/patches/configure.patch
- Ports/libassuan/patches/includes.patch
- Ports/libassuan/patches/socketpair.patch
- Ports/libgcrypt/package.sh
- Ports/libgcrypt/patches/configure.patch
- Ports/libgpg-error/package.sh
- Ports/libgpg-error/patches/configure.patch
- Ports/libgpg-error/patches/includes.patch
- Ports/libgpg-error/patches/syntax-error.patch
- Ports/libgpg-error/patches/syscfg.patch
- Ports/libiconv/package.sh
- Ports/libksba/package.sh
- Ports/libksba/patches/configure.patch
- Ports/npth/package.sh
- Ports/npth/patches/configure.patch
- Ports/ntbtls/package.sh
- Ports/ntbtls/patches/configure.patch
- Userland/Libraries/LibC/CMakeLists.txt
- Userland/Libraries/LibC/bits/stdint.h
- Userland/Libraries/LibC/netdb.cpp
- Userland/Libraries/LibC/netdb.h
- Userland/Libraries/LibC/syslog.h
- Userland/Libraries/LibELF/DynamicLinker.cpp
- Userland/Libraries/LibPthread/CMakeLists.txt
- Userland/Libraries/LibPthread/semaphore.cpp
- Userland/Libraries/LibPthread/semaphore.h
This adds GnuPG and a number of libraries this port depends on. I've also implemented some of the `sem_*()` functions for this to work.
> Ports: Add gnupg port

- AK/Hex.cpp
- AK/Hex.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.h
- Userland/Libraries/LibJS/Tests/builtins/functions/uriEncodeDecode.js
These are generally useful and in particular needed for twitter.com
> LibJS: Implement the encode/decodeURI(Component) family of functions 

- Userland/Libraries/LibJS/AST.cpp
This has the nice side effect of giving us a decent error message for something like `undefined.foo()` - another useless "ToObject on null or undefined" gone. :^)
Also turn the various ternary operators into two separate if branches, they don't really share that much.
> LibJS: Use references in CallExpression::compute_this_and_callee()

- Base/res/html/misc/cookie.html
- Userland/Applications/Browser/CookieJar.cpp
- Userland/Applications/Browser/CookieJar.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/StyleValue.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/Loader/CSSLoader.cpp
- Userland/Libraries/LibWeb/Loader/FrameLoader.cpp
- Userland/Libraries/LibWeb/Loader/ImageLoader.cpp
- Userland/Libraries/LibWeb/Loader/ImageLoader.h
- Userland/Libraries/LibWeb/Loader/LoadRequest.cpp
- Userland/Libraries/LibWeb/Loader/LoadRequest.h
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
- Userland/Utilities/test-web.cpp
> Browser+LibWeb: Spec compliant cookie retrieval + set the Cookie HTTP header

- Documentation/NetworkBoot.md
This method seems useful for bare-metal debugging.
> Documentation: Describe how to use the iPXE bootloader for network boot

- Userland/Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.h
- Userland/Libraries/LibWeb/HTML/HTMLElement.idl
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
This is continuing #6347, the game is now fully playable, but still not completely functional:
- document.location.reload() is not implemented, so the game does not restart on a lose/win
- keyboard events are not implemented, so the paddle can only be moved via the mouse
> LibWeb: Small additions and improvements

- Userland/Libraries/LibDebug/Dwarf/LineProgram.cpp
- Userland/Libraries/LibDebug/Dwarf/LineProgram.h
handle_sepcial_opcode -> handle_special_opcode :)
> LibDebug: Fix typo in handle_special_opcode method name

- AK/Format.h
- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
These are pendants to dbgln_if and should be compiled away when they are dissabled
> Everywhere: Add outln_if and warnln_if

- Userland/Libraries/LibJS/Runtime/IteratorOperations.cpp
- Userland/Libraries/LibJS/Runtime/IteratorOperations.h
- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.js
Used by twitch.tv and based on these specifications:
https://tc39.es/ecma262/#sec-typedarray
https://tc39.es/ecma262/#sec-initializetypedarrayfromarraylike
https://tc39.es/ecma262/#sec-initializetypedarrayfromlist
> LibJS: Implement initializing a TypedArray from iterable and array-like objects

- Ports/AvailablePorts.md
- Ports/imgcat/package.sh
- [imgcat's GitHub repository](https://github.com/eddieantonio/imgcat)
> Ports: Add imgcat port

- Userland/Utilities/ls.cpp
> ls: list files in cwd before listing directories when listing paths

- Ports/cmake/package.sh
> Ports: Enable building cmake on the host

- Ports/SDL2_image/package.sh
- Ports/libtiff/package.sh
- Ports/nasm/package.sh
- Userland/Libraries/LibC/scanf.cpp
* Fixes the tarball hash for the `nasm` port.
* Fixes dependency and linker options for `SDL2_image`.
* Implements the `*` modifier for `vsscanf()`.
> Ports: Some minor ports fixes

- Base/res/html/misc/cursor.html
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Correctly handle the `<thead>` and `<tfooter>` HTML tags within the `<table>` tag.
These tags are treated the same as `<tbody>` in most cases.
This also adds a HTML test page including a `<thead>` to verify the change.
> LibWeb: Support thead & tfooter HTML Table tags

- Userland/DevTools/HackStudio/ClassViewWidget.cpp
Entries in the ClassView tree are now sorted by declaration name.
> HackStudio: Sort ClassView entries

- .github/workflows/discord.yml
The previous check i wrote was broken
> Meta: Actually check for draft PRs before sending discord notifications

- Meta/lint-ports.py
- Ports/SDL2/package.sh
- Ports/nesalizer/package.sh
- Ports/quake/package.sh
Otherwise we'd have to update them in this repository every time something changes.
> Ports: Remove auth_type for our own packages

- Toolchain/BuildIt.sh
This fixes a regression introduced by #6424.
> Toolchain: Build GCC with optimizations

- AK/IntrusiveList.h
- AK/Tests/TestIntrusiveList.cpp
Continues #6376 and fixes the bug noticed in #6509.
(Please wait until the build passes)
> AK: Fix IntrusiveList<...NonnullRefPtr...>

- Userland/Libraries/LibWeb/CSS/StyleResolver.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
> LibWeb: More rendering improvements

- AK/BinaryHeap.h
- AK/BitStream.h
- AK/IntrusiveRedBlackTree.h
- AK/RedBlackTree.h
- AK/Tests/TestBinaryHeap.cpp
- AK/Tests/TestIntrusiveRedBlackTree.cpp
- AK/Tests/TestRedBlackTree.cpp
- Userland/Applications/MouseSettings/MouseSettingsWindow.cpp
- Userland/Applications/MouseSettings/MouseSettingsWindow.h
- Userland/Applications/MouseSettings/main.cpp
- Userland/Libraries/LibArchive/Tar.h
- Userland/Libraries/LibArchive/TarStream.cpp
- Userland/Libraries/LibArchive/TarStream.h
- Userland/Libraries/LibArchive/Zip.cpp
- Userland/Libraries/LibArchive/Zip.h
- Userland/Libraries/LibCompress/Deflate.cpp
- Userland/Libraries/LibCompress/Deflate.h
- Userland/Libraries/LibCompress/DeflateTables.h
- Userland/Libraries/LibCompress/Gzip.cpp
- Userland/Libraries/LibCompress/Gzip.h
- Userland/Utilities/gzip.cpp
- Userland/Utilities/mktemp.cpp
- Userland/Utilities/traceroute.cpp
- Userland/Utilities/zip.cpp
> AK+Userland: Use idan.horowitz@serenityos.org for my copyright headers

- Userland/DevTools/HackStudio/Debugger/DisassemblyModel.cpp
- Userland/DevTools/HackStudio/Debugger/DisassemblyModel.h
- Userland/DevTools/HackStudio/Debugger/DisassemblyWidget.cpp
- Userland/DevTools/HackStudio/Debugger/DisassemblyWidget.h
- Userland/DevTools/HackStudio/Debugger/RegistersModel.cpp
- Userland/DevTools/HackStudio/Debugger/RegistersModel.h
- Userland/Libraries/LibWeb/Bindings/NodeWrapperFactory.cpp
- Userland/Libraries/LibWeb/DOM/DocumentFragment.cpp
- Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
> LibWeb+HackStudio: Use lukew@serenityos.org for my copyright headers

- Base/res/fortunes.json
Note that @ADKaster _has_ signed away all his quotes to the Fortunes demon
> Base: Add a quote to the fortunes database

- Userland/Libraries/LibTLS/Socket.cpp
Otherwise the notification would be deferred until the next read event,
which means the client will not get any events if the server initiates
the appdata transfers.
> LibTLS: Call the read hooks after processing messages too

- Userland/Utilities/syscall.cpp
The `syscall-arguments` positional arg being required was
breaking the scenario where the user just passes the
`--list-syscalls` argument.
Instead, make the argument not required, and manually handle
the error path our selves. The actual implementation for the
`--list-syscalls` option was also missing. 
Closes: #6574
> Utilities: Fix the --list-syscalls option to syscall(1)

- Userland/Libraries/LibC/unistd.cpp
- Userland/Utilities/pathchk.cpp
Adds [pathchk](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pathchk.html) - one of the remaining few missing POSIX utilities.
Test script:
```
#!/bin/sh
pathchk '/doesnotexist'
pathchk '/root/a'
pathchk --portability '/a/@'
pathchk --portability 'a'
pathchk --portability '/a/'
pathchk --portability '/-a/'
pathchk --portability ''
pathchk --portability '/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
pathchk --portability '/a/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
```
> Utilities: Add pathchk

- Kernel/Syscalls/sigaction.cpp
Userspace can provide a null value for the `act` argument to the`sigaction` syscall to not set any new behavior. This is described here:
https://pubs.opengroup.org/onlinepubs/007904875/functions/sigaction.html
Without this fix, the `copy_from_user(...)` invocation on `user_act` fails and makes the syscall return early.
> Kernel: Support null act argument for sigaction syscall

- Ports/AvailablePorts.md
- Ports/tcl/package.sh
- Ports/tcl/patches/ipv6.patch
- Userland/Libraries/LibC/dirent.cpp
- Userland/Libraries/LibC/dirent.h
Because, well, who doesn't love Tcl. Remember eggdrop?
> Port: Add port for tcl

- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.h
Just all things I could do without changing the structure of UE
Adds:
* CMC
* POPA
* POPAD
* POPF
* PUSHA
* PUSHAD
* PUSHF
* PUSH_RM16
* SAHF
* FPU:
* FNOP
* FPREM
* FSINCOS
* FCMOVxx
* FISTTP
> UserspaceEmulator: Add more Instructions

- Userland/Applications/Piano/KnobsWidget.cpp
- Userland/Applications/Piano/KnobsWidget.h
- Userland/Applications/Piano/Music.h
- Userland/Applications/Piano/Track.cpp
- Userland/Applications/Piano/Track.h
This patch implements a couple of enhancements to the synthesizer engine:
- Each track has a volume control.
- The input and tooltips for all controls are improved.
- The noise channel is pitched, which allows for basic drum synthesis.
> Piano: Add track Volume and improve QOL

- Userland/Applications/FileManager/main.cpp
- Userland/Utilities/unzip.cpp
Can't really call this my first PR anymore after forgetting to format the old one properly :facepalm:, sorry for the trouble, still new to this.
This PR adds a new context menu action to FileManager that allows for extracting zip archives without having to open the terminal. I thought this would make a good first contribution after playing around a bit with SerenityOS and finding this quality of life feature that can be found in other file managers like those of Gnome and Windows to be lacking.
"Extract Here" in Gnome
My implementation in SerenityOS
Future improvements may include support for more archive formats like .tar and .tar.gz as well as integration with the new file operation progress tracking.
> FileManager+unzip: Unzip from context menu

- README.md
"GUI" = graphical user interface
"GUI interface" = graphical user interface interface :^)
> Documentation: Fix "GUI interface" wording

- Userland/Utilities/ls.cpp
When specifying more than one path (e.g. with `ls -l /usr /bin`) `ls` would ignore other display options and fall back to showing the files in short mode. This fixes that.
Examples:
```
$ ls -l /usr tests
tests:
-rwxr-xr-x   1    anon   users        927   2021-04-23 21:15:10  run-tests-and-shutdown.sh
/usr:
drwxr-xr-x   2    1000    1000       4096   2021-04-25 06:40:12  Ports
drwxr-xr-x  12    1000    1000       4096   2021-04-22 14:12:03  Tests
drwxr-xr-x   2    1000    1000       4096   2021-04-25 06:54:41  bin
drwxr-xr-x  48    1000    1000       4096   2021-04-26 06:51:26  include
drwxr-xr-x   3    1000    1000       4096   2021-04-26 07:03:47  lib
drwxr-xr-x  14    1000    1000       4096   2021-04-22 19:04:06  local
drwxr-xr-x   3    1000    1000       4096   2021-04-10 10:20:02 …
```
> Utilities: Make ls respect options when specifying more than one path

- Meta/build-root-filesystem.sh
Those should either belong to the root user or not be suid.
> Meta: Make sure traceroot and ping belong to the root user

- Userland/Libraries/LibGUI/VimEditingEngine.cpp
This patch adds handling of the arrow, Home/End, and PageUp/PageDown
keys to the Vim emulation mode.  Home acts as 0, End acts as $, arrow
keys act as their HJKL variants, and PageUp/Down behaves as you would
expect.
This patch also moves the default handling of the aforementioned keys
to insert mode, since regular `EditingEngine` semantics are more
appropriate there.
~~This PR depends on #6674.~~
> VimEditingEngine: Handle arrow, Home/End and Page keys

- Ports/AvailablePorts.md
- Ports/libtheora/package.sh
- Ports/libtheora/patches/config.sub.patch
- Ports/scummvm/package.sh
Also make it a dependency for the ScummVM port.
#6129 included this, but that PR has gone stale and it made more sense to me to create a smaller changeset for this.
> Ports: Add libtheora

- Documentation/BuildInstructions.md
Turns out #6069 wasn't quite as cut-and-dried as I thought it was. Whoops!
> Fix some typos from #6069

- Userland/Utilities/tac.cpp
> Userland: Implement tac command

- Userland/Libraries/LibDebug/DebugInfo.cpp
- Userland/Libraries/LibDebug/Dwarf/CompilationUnit.cpp
- Userland/Libraries/LibDebug/Dwarf/CompilationUnit.h
- Userland/Libraries/LibDebug/Dwarf/DIE.cpp
- Userland/Libraries/LibDebug/Dwarf/DIE.h
- Userland/Libraries/LibDebug/Dwarf/DwarfInfo.cpp
- Userland/Libraries/LibDebug/Dwarf/DwarfInfo.h
- Userland/Libraries/LibDebug/Dwarf/DwarfTypes.h
- Userland/Libraries/LibDebug/Dwarf/LineProgram.cpp
- Userland/Libraries/LibDebug/Dwarf/LineProgram.h
I have a hunch we might need support for DWARF 5 soon. So here it is:
> LibDebug: Implement support for DWARF 5

- AK/Vector.h
We re-write (almost) every operation in AK::Vector that performs allocations to return a boolean stating whether it succeeded it or not, so that allocation failures may be handled. All of these new operations are named `try_<operation_name>`. The old operation names are now thin wrappers that `VERIFY()` the result of the fallible operation.
The only issues are things like copy constructors, where we can't easily expose whether or not the allocation failed (without using something like exceptions, yuck!).
This should help us accomplish #6369 , with this implemented we should now be able to start fixing kernel components that use vectors to make sure they check their allocations. I think in the long term, we should eventually only make the wrappers and copy constructors exist in userspace …
> AK: Make AK::Vector expose allocation failures in API

- Base/home/anon/.config/Browser.ini
- Userland/Applications/Browser/Browser.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/main.cpp
* Save search engine setting to preferences
* Display search engine format in statusbar
* Fix small typo in GitHub format
> Search engines, p. 2

- Kernel/API/Syscall.h
- Kernel/Process.h
- Kernel/Syscalls/setuid.cpp
- Ports/AvailablePorts.md
- Ports/quake2/package.sh
- Userland/Libraries/LibC/unistd.cpp
- Userland/Libraries/LibC/unistd.h
> Ports: Quake II Port :^)

- Userland/Libraries/LibLine/InternalFunctions.cpp
I have no idea how this _ever_ worked, and I also have no idea why past
me didn't use FileStream to begin with.
Fixes the issue where lots of junk data would be written to the temp
file, causing the external editor to crash.
> LibLine: Fix writing to temporary file in ^X^E handler

- Userland/Shell/AST.h
- Userland/Shell/Parser.cpp
~~Also work around what appears to be a weird compiler bug:~~
Turns out it's just good old CxByte-being-dumb, the compiler is perfectly fine :P
> Shell: Fix some bugs found by oss-fuzz

- Userland/Applications/PixelPaint/EllipseTool.cpp
- Userland/Applications/PixelPaint/EllipseTool.h
Functionality was already there, just had to hook it up!
> PixelPaint: Add fill mode for the ellipse tool

- Userland/DevTools/HackStudio/EditorWrapper.cpp
- Userland/DevTools/HackStudio/EditorWrapper.h
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.h
- Userland/DevTools/HackStudio/main.cpp
& Also some small refactoring of how we get the "currently active file".
> HackStudio: Add "document dirty" indicator & warn when exiting/building with unsaved changes

- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
> LibWeb: Expose Node.ownerDocument

- AK/DistinctNumeric.h
Part 2/n of #6673 
It's just a nice thing to have, and it's literally free (just a bunch of 'constexpr' markings)
> AK: Make DistinctNumeric constexpr-capable

- Userland/Utilities/head.cpp
- Userland/Utilities/strace.cpp
> Misc fixes, pt. 7

- Userland/Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.cpp
- Userland/Libraries/LibWeb/DOM/EventTarget.h
- Userland/Libraries/LibWeb/DOM/EventTarget.idl
Used by Web Platform Tests to test events
> LibWeb: Implement EventTarget.dispatchEvent

- Base/usr/share/man/man2/pledge.md
- Base/usr/share/man/man2/unveil.md
- Base/usr/share/man/man7/Mitigations.md
- Base/usr/share/man/man7/boot_parameters.md
-  __Base: Add a boot_parameters(7) to document kernel boot parameters.__
-   __Base: Minor cleanup of a few man pages.__
- Fix some typos and formatting.
- Add links to Mitigations from unveil / pledge.
> Base: Add a boot_parameters(7) to document kernel boot parameters. 

- .github/workflows/twitter.yml
- Meta/tweet-commits.js
Before this is merged @bgianfo will have to give @awesomekling the tokens (CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET) so he can add them to the repository secrets
> Meta: Add action to tweet each commit on push

- Base/etc/SystemServer.ini
- Kernel/Net/IPv4Socket.cpp
- Kernel/Net/IPv4Socket.h
- Kernel/Net/NetworkTask.cpp
- Kernel/UnixTypes.h
- Userland/Libraries/LibC/netinet/in.h
- Userland/Services/LookupServer/CMakeLists.txt
- Userland/Services/LookupServer/DNSName.cpp
- Userland/Services/LookupServer/DNSName.h
- Userland/Services/LookupServer/LookupServer.cpp
- Userland/Services/LookupServer/LookupServer.h
- Userland/Services/LookupServer/MulticastDNS.cpp
- Userland/Services/LookupServer/MulticastDNS.h
- Userland/Services/LookupServer/main.cpp
Well, hello friends! :^)
This is the part 4, where we get basic mDNS support :tada:
Caveat usor: the mDNS implemention is not complete or comprehensive; it's just enough to get `.local` name resolution working. It should be a bit less terrible than the [Terrible mDNS responder](https://github.com/bugaevc/terrible-mdns-responder) though :smile:
> Adventures in LookupServer, pt. 4

- Userland/DevTools/Profiler/Profile.cpp
- Userland/DevTools/Profiler/Profile.h
- Userland/DevTools/Profiler/main.cpp
> Profiler: Let the user select more than one process

- Base/usr/share/man/man1/TextEditor.md
This documents the feature added in c2872766f2322aa38490160b571059f05e7dcb2d
> Base: Update TextEditor man page to include line and column arguments

- Ports/AvailablePorts.md
- Ports/harfbuzz/package.sh
- Ports/harfbuzz/patches/unused.patch
I was going to port Warzone 2100 and while that doesn't work yet here is yet another dependency.
> Ports: Add port for harfbuzz

- Ports/ffmpeg/package.sh
- Ports/libtiff/package.sh
This builds shared libraries for ffmpeg, e.g. `libavcodec` and various others.
> Ports: Build shared libraries for ffmpeg

- Kernel/FileSystem/Ext2FileSystem.cpp
Instead of reading in the entire contents of a directory into a large
buffer, we can iterate block by block. This only requires a small
buffer.
Because directory entries are guaranteed to never span multiple blocks
we do not have to handle any edge cases related to that.
This reduces the startup time of Space Analyzer to about~700ms from
~1000ms.
> Kernel: Traverse ext2 directories blockwise.

- Userland/DevTools/UserspaceEmulator/main.cpp
> UserspaceEmulator: Allow running executables not in PATH

- Userland/Demos/CatDog/CMakeLists.txt
- Userland/Demos/CatDog/CatDog.cpp
- Userland/Demos/CatDog/CatDog.h
- Userland/Demos/CatDog/SpeechBubble.cpp
- Userland/Demos/CatDog/SpeechBubble.h
- Userland/Demos/CatDog/main.cpp
> CatDog: Help the user debug their programs

- Userland/Utilities/tac.cpp
Implements concatinating multiple files for the tac utility.
> tac: Support concatenating multiple files

- Ports/AvailablePorts.md
- Ports/ffmpeg/package.sh
- Ports/libopenal/package.sh
I was going to port Warzone 2100 and while that doesn't work yet here is yet another dependency.
> Ports: Add port for libopenal

- Base/etc/shellrc
- Base/usr/share/man/man7/Shell-vars.md
- Userland/Shell/Shell.cpp
- Userland/Shell/Shell.h
...and set it to 10 seconds by default.
> Shell: Add an option to autosave history every N ms

- Userland/Libraries/LibCrypto/Authentication/HMAC.h
- Userland/Libraries/LibCrypto/CMakeLists.txt
- Userland/Libraries/LibCrypto/Cipher/AES.h
- Userland/Libraries/LibCrypto/Cipher/Cipher.h
- Userland/Libraries/LibCrypto/Hash/HashFunction.h
- Userland/Libraries/LibCrypto/NumberTheory/ModularFunctions.cpp
- Userland/Libraries/LibCrypto/PK/Code/EMSA_PSS.h
- Userland/Libraries/LibCrypto/PK/RSA.cpp
- Userland/Libraries/LibTLS/CMakeLists.txt
- Userland/Libraries/LibTLS/ClientHandshake.cpp
- Userland/Libraries/LibTLS/Exchange.cpp
- Userland/Libraries/LibTLS/Handshake.cpp
> LibTLS+LibCrypto: Remove all VLAs and enable -Wvla

- AK/ByteBuffer.h
Creating a `ByteBuffer` involves two allocations:
* One for the `ByteBufferImpl` object
* Another one for the actual byte buffer
This changes the `ByteBuffer` and `ByteBufferImpl` classes so only one allocation is necessary.
> AK: Avoid allocations in ByteBuffer

- Userland/DevTools/HackStudio/LanguageServers/AutoCompleteEngine.cpp
- Userland/DevTools/HackStudio/LanguageServers/AutoCompleteEngine.h
- Userland/DevTools/HackStudio/LanguageServers/ClientConnection.cpp
- Userland/DevTools/HackStudio/LanguageServers/ClientConnection.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/CMakeLists.txt
- Userland/DevTools/HackStudio/LanguageServers/Cpp/ClientConnection.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/LexerAutoComplete.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/LexerAutoComplete.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/Tests.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/Tests.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/main.cpp
- Userland/DevTools/HackStudio/LanguageServers/FileDB.cpp
- Userland/DevTools/HackStudio/LanguageServers/Shell/AutoComplete.cpp
- Userland/DevTools/HackStudio/LanguageServers/Shell/AutoComplete.h
- Userland/DevTools/HackStudio/LanguageServers/Shell/ClientConnection.h
Just testing some simple things now, but it's a start :smile: 
To run the tests: `CppLanguageServer -t`
> Cpp LanguageServer: Add Tests

- Userland/Libraries/LibGL/GL/gl.h
- Userland/Libraries/LibGL/GLContext.h
- Userland/Libraries/LibGL/GLUtils.cpp
- Userland/Libraries/LibGL/SoftwareGLContext.cpp
- Userland/Libraries/LibGL/SoftwareGLContext.h
Picking some low hanging fruit from #7062
> LibGL: Implement glFlush() and glFinish()

- Ports/AvailablePorts.md
- Ports/brogue/package.sh
- Ports/brogue/patches/config.patch
> Ports: Add port for Brogue (BrogueCE)

- Userland/Utilities/netstat.cpp
First time contributing to Serenity, welcome all the critiques!
> Utilities: Implement a netstat command

- Userland/Libraries/LibGUI/TextEditor.cpp
Previously when entering a newline, previous indentation would be left,
leaving a line consisting only of whitespace. This fixes that
When watching Andreas build something inside of Serenity itself, it always irked me that there was a not insignificant amount of time correcting whitespace leftover by the autoindent. Hopefully this fixes that :^)
I haven't delved deep into the code for the TextEditor widget, so if there's a better way of doing this let me know!
> TextEditor: Clear leftover whitespace when inserting newlines

- Documentation/HardwareCompatibility.md
This notebook started working with the recent AHCI fixes.
> Documentation: Add a working notebook to Hardware Compatibility List

- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/ParserAutoComplete.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/Tests.cpp
- Userland/Libraries/LibCpp/Parser.cpp
- Userland/Libraries/LibCpp/Token.cpp
- Userland/Libraries/LibCpp/Token.h
Various small fixes & improvements, mainly around auto-completing namespaces & taking scopes into consideration.
> LibCpp+LanguageServer: Various improvements to autocomplete

- Userland/Utilities/errno.cpp
> Utilities: Add errno utility

- Userland/Applications/Debugger/main.cpp
This adds the "bt" command to the debugger which displays a backtrace of the current thread.
This currently relies on usage of the frame pointer, so debugged programs compiled with `-fomit-frame-pointer` aren't supported.
> Debugger: Add basic backtrace support

- Userland/Libraries/LibVT/Terminal.cpp
> LibVT: Implement ST (ESC \)  escape sequence

- AK/Debug.h.in
- Meta/CMake/all_the_debug_macros.cmake
- Userland/Games/Solitaire/Card.cpp
- Userland/Games/Solitaire/Card.h
- Userland/Games/Solitaire/CardStack.cpp
- Userland/Games/Solitaire/CardStack.h
- Userland/Games/Solitaire/Game.cpp
- Userland/Games/Solitaire/Game.h
- Userland/Games/Solitaire/main.cpp
> Solitaire: Add three card draw mode

- Userland/Applications/SystemMonitor/NetworkStatisticsWidget.cpp
- Userland/Applications/SystemMonitor/NetworkStatisticsWidget.h
Creates a new TableView in the socket list for UDP information.
Resolves #6980.
> SystemMonitor: Show UDP sockets

- Userland/Utilities/find.cpp
Previously `find` would follow symlinks when iterating over directories even though the `-L` argument was not specified.
> Utilites: Make find respect lack of -L when iterating over directories

- Userland/Games/2048/Game.cpp
- Userland/Games/2048/Game.h
- Userland/Games/2048/GameSizeDialog.cpp
- Userland/Games/2048/GameSizeDialog.h
- Userland/Games/2048/main.cpp
A hard mode for 2048 in which the tile generator hates you. It generates new tiles with the worst possible place and value.
New PR (#7142, #7143) because I somehow keep closing PRs before doing force-pushes (maybe I'm doing something wrong with the force-pushes?). Sorry for that. I did finally fix the commit messages, hopefully.
> 2048: Evil AI

- Kernel/Net/NetworkAdapter.cpp
- Kernel/Net/NetworkAdapter.h
This avoids two allocations when receiving network packets. One for inserting a `PacketWithTimestamp` into `m_packet_queue` and another one when inserting buffers into the list of unused packet buffers.
With this fixed the only allocations in `NetworkTask` happen when initially allocating the `PacketWithTimestamp` structs and when switching contexts.
> Kernel: Avoid allocations when receiving network packets

- Kernel/Devices/PCISerialDevice.cpp
This commit adds support for initializing multiple serial ports per PCI board, as well as initializing multiple different pci serial boards
Currently we just choose the first PCI serial port seen as the debug port, but this should probably be made configurable some how in the future.
> Kernel: Add support for multiple serial ports per device

- Kernel/DoubleBuffer.cpp
- Kernel/TTY/TTY.cpp
Some miscellaneous ~one/two-line~ small fixes for the write syscall path. Fixes #7069 .
> Kernel: Some small fixes for the write syscall path

- Userland/Games/Solitaire/Game.cpp
- Userland/Games/Solitaire/Game.h
- Userland/Games/Solitaire/Solitaire.gml
- Userland/Games/Solitaire/main.cpp
Got a bit tired of having to change to 3 card mode all the time :)
> Solitaire: Persist game mode and high score

- Userland/Games/Pong/Game.cpp
- Userland/Games/Pong/Game.h
- Visual fixes:
- score display;
- AI paddle movement.
- Control improvements:
- mouse controls honor maximum paddle speed;
- some indication for where the paddle will end up when following cursor;
- remember if arrow keys are held across resets.
- AI improvements:
- or is it the opposite? AI is now dumber and can actually miss balls.
- Misc.:
- a touch slower ball.
> Pong: Visual, controls & AI improvements

- Kernel/FileSystem/VirtualFileSystem.cpp
This modifies the error checks in VFS::open after the call to resolve_path to ignore a null parent custody if there is no error, as this is expected when the path to resolve points to "/". Rather, a null parent custody only constitutes an error if it is accompanied by ENOENT. This behavior is documented in the VFS::resolve_path_without_veil method.
To accompany this change, the order of the error checks have been changed to more naturally fit the new logic.
Previously, opening `/` as root would return ENOENT rather than EISDIR, which lead to `cp` displaying:
```
cp: unable to copy '/bin/id': No such file or directory
```
Furthermore, if `/` wasn't mounted read-only, root would have still not been able to create any files there.
This fixes #6808.
> Kernel: Ignore null parent custody without error in VFS::open

- AK/Variant.h
- Tests/AK/TestVariant.cpp
This changes Variant::visit() to forward the value returned by the
selected visitor invocation. By perfectly forwarding the returned value,
this allows for the visitor to return by value or reference.
Note that all provided visitors must return the same type - the compiler
will otherwise fail with the message: "inconsistent deduction for auto
return type".
> AK: Allow AK::Variant::visit to return a value

- Userland/Libraries/LibCrypto/Hash/HashManager.h
And simplify the code _even further_!
I'll change LibWasm later :P
> LibCrypto: Use the new return-from-Variant::visit() mechanism

- Userland/DevTools/Inspector/main.cpp
Fixes #7171. This is my first PR here. I've went through the contributing guidelines but please let me know if I missed something! :)
> Inspector: Throw an error when inspecting a process it has no access to

- .mailmap
.mailmap files are documented here: https://git-scm.com/docs/gitmailmap
> Meta: Add a .mailmap file to map email addresses to the same comitter

- .mailmap
Also map the author name I used before to my current proper name.
> Meta: Add my email(s) to .mailmap

- Kernel/Thread.cpp
There is a window between dropping a thread's last reference and it
being removed from the list.
Found in #5541
> Kernel: Close a Thread tid lookup race

- Userland/Libraries/LibGL/GL/gl.h
- Userland/Libraries/LibGL/GLContext.h
- Userland/Libraries/LibGL/GLUtils.cpp
- Userland/Libraries/LibGL/SoftwareGLContext.cpp
- Userland/Libraries/LibGL/SoftwareGLContext.h
> LibGL: Implement glHint()

- .github/workflows/cmake.yml
Tired of seeing all these failing builds.
> CI: Clang tweaks

- Kernel/Graphics/GraphicsManagement.cpp
- Kernel/PCI/Access.cpp
- Kernel/PCI/Access.h
- Kernel/PCI/IOAccess.cpp
- Meta/run.sh
> Kernel: More bare metal fixes

- AK/Utf8View.cpp
- AK/Utf8View.h
- Userland/Libraries/LibWeb/DOM/Position.cpp
- Userland/Libraries/LibWeb/DOM/Position.h
- Userland/Libraries/LibWeb/Layout/TextNode.cpp
- Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
- Userland/Libraries/LibWeb/Page/EditEventHandler.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/Frame.cpp
- Userland/Libraries/LibWeb/Page/Frame.h
This pull request improves the Unicode compatibility of editable DOM nodes, such as those with the `contenteditable` attribute. It is mainly about being careful when splitting strings, as splitting them inside multi-byte UTF-8 codepoints will create invalid strings.
Previously, the browser would crash in a lot of cases when traversing, editing and deleting non-ASCII characters in those DOM nodes. Now, most of it works fine, and I can't find any more crashes at the moment.
* I improved `Utf8View` by changing some return and argument types from `int` to `size_t` where they should be `size_t` and by adding new substring methods which take their offset in codepoints rather than bytes. Furthermore, I also added `Utf8CodepointIterator interator_at_byte_offset(size_t)`, which can provide an …
> LibWeb: Improve general usability and Unicode compatibility of editable DOM nodes

- Kernel/Arch/i386/CPU.cpp
- Kernel/CommandLine.cpp
- Kernel/CommandLine.h
- Kernel/TTY/VirtualConsole.cpp
The goal is to aid us in bare metal development.
Therefore, I'll add a way to add an embedded kernel commandline. Also, adding history for `VirtualConsole` would be nice so I decided to work on it too.
> Kernel: More misc bare metal fixes

- Kernel/FileSystem/VirtualFileSystem.cpp
This uses GenericLexer to replace a call to StringView::split which returned its result using a heap allocated Vector.
Here are the results of a couple of profiling runs, each taken during the startup of the SpaceAnalyzer program. The percentages indicate the amount of time that was spent on string splitting per call to VFS::resolve_path_without_veil.
* before changes: 20%
* after changes: 1%
> Kernel: Remove an allocation from VFS::resolve_path_without_veil

- AK/Vector.h
I think this should be `const`.
> AK/Vector: Constify `find_first_index()`

- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditor.h
- Userland/Applications/HexEditor/HexEditorWidget.cpp
Submitting this a separate PR rather than ninja editing in with other changes.
> HexEditor: Add 'Select All' action

- Meta/serenity_gdb.py
Before:
<details><summary>Expand for unreadable mess</summary>
```
<AK::Detail::InheritFromPacks<AK::Detail::IntegerSequence<unsigned int, 0, 1, 2, 3, 4, 5>, AK::Detail::ParameterPack<AK::Detail::VariantConstructors<int, AK::Variant<int, long, float, double, AK::DistinctNumeric<unsigned long, Wasm::__FunctionAddress_tag, true, true, false, false, false, true>, AK::DistinctNumeric<unsigned long, Wasm::__ExternAddress_tag, true, true, false, false, false, true> > > >, AK::Detail::ParameterPack<AK::Detail::VariantConstructors<long, AK::Variant<int, long, float, double, AK::DistinctNumeric<unsigned long, Wasm::__FunctionAddress_tag, true, true, false, false, false, true>, AK::DistinctNumeric<unsigned long, Wasm::__ExternAddress_tag, true, true, false, false, false, true> > > >, …
```
> Meta: Add GDB pretty printer for Variant & show less useless type information

- Userland/Applications/HexEditor/CMakeLists.txt
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.h
- Userland/Applications/HexEditor/HexEditorWindow.gml
> HexEditor: Construct user interface from GML

- Userland/Utilities/nc.cpp
Allow the user to pass in a hostname to the connect functionality
instead of just an IP address. The call to `gethostbyname(..)` handles
both seamlessly for us.
Update the argument name / usage message accordingly.
> Userland: Allow `nc` to connect by hostname instead of just address

- Userland/Libraries/LibProtocol/Request.cpp
- Userland/Services/ImageDecoder/ClientConnection.cpp
- Userland/Services/LookupServer/LookupServer.cpp
- Userland/Services/LookupServer/MulticastDNS.cpp
- Userland/Utilities/fgrep.cpp
- Userland/Utilities/test-unveil.cpp
Yet another bunch of various fixes, courtesy of #7085. Follow-up of #7189.
> Userland: Various portability/correctness fixes, part 3

- Userland/Applications/HexEditor/CMakeLists.txt
- Userland/Applications/HexEditor/GoToOffsetDialog.cpp
- Userland/Applications/HexEditor/GoToOffsetDialog.gml
- Userland/Applications/HexEditor/GoToOffsetDialog.h
- Userland/Applications/HexEditor/HexEditor.h
- Userland/Applications/HexEditor/HexEditorWidget.cpp
- Userland/Applications/HexEditor/HexEditorWidget.h
> HexEditor: Add 'Go to Offset...' dialog

- Userland/Libraries/LibGfx/Painter.cpp
This PR replaces the old (and really very neat) algorithm to draw elliptic arcs with a way more naive one.
We now just sweep the angle and calculate the coordinates of each point on the ellipse.
The new implementation pretty much copes with everything you throw at it, most notably circles which infinite-looped the drawing before.
The old algorithm seems to be very good at roughly approximated ellipses as well as drawing huge ellipses. Both things we don't do in Serenity.
This fixes #6984
> LibGfx: Replace ellipse drawing algorithm

- Userland/Libraries/LibGfx/Matrix.h
This adds `Matrix.inverse()`; see commit message for more details. This is my first encounter with C++ templates, so I'd love some feedback on this (where applicable).
> LibGfx/Matrix: Add inverse() and friends

- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGfx/Bitmap.cpp
- Userland/Libraries/LibGfx/Bitmap.h
- Userland/Libraries/LibGfx/ShareableBitmap.cpp
- Userland/Services/WindowServer/ClientConnection.cpp
Instead of using a low-level, proprietary API inside LibGfx, let's use Core::AnonymousBuffer which already abstracts anon_fd and offers a higher-level API too.
I haven't noticed any regressions with this, but it does modify a fairly critical piece of Serenity's windowing stack. Done as part of #7085.
> LibGfx: Use anonymous buffer instead of raw anon_fd for Gfx::Bitmap

- Userland/Utilities/stty.cpp
`AK::Result` does not work if both the error and value types are
integers.
> Userland: Fix `stty` not setting control characters

- Userland/Games/Hearts/CMakeLists.txt
- Userland/Games/Hearts/Game.cpp
- Userland/Games/Hearts/Game.h
- Userland/Games/Hearts/Player.cpp
- Userland/Games/Hearts/Player.h
- Userland/Games/Hearts/ScoreCard.cpp
- Userland/Games/Hearts/ScoreCard.h
https://user-images.githubusercontent.com/388571/119350979-3e3e6d80-bca0-11eb-93fb-2e3c96c73e69.mp4
> Hearts: Implement passing cards to other players and playing more than one hand per game

- Userland/Utilities/js.cpp
Having load() present is required in order to run test262.
> js: Define load() in global object for scripts

- AK/ByteBuffer.h
Previously GCC came to the conclusion that we were reading `m_outline_capacity` via `ByteBuffer(ByteBuffer const&)` -> `grow()` -> `capacity()` even though that could never be the case because `m_size` is `0` at that point which means we have an inline buffer and `capacity()` would return `inline_capacity` in that case without reading `m_outline_capacity`.
This makes GCC inline parts of the `grow()` function into the `ByteBuffer` copy constructor which seems sufficient for GCC to realize that `m_outline_capacity` isn't actually being read.
The compiler error with `-Og` was:
```
FAILED: Kernel/CMakeFiles/Kernel.dir/Random.cpp.o 
/usr/bin/ccache /home/gunnar/serenity/Toolchain/Local/i686//bin/i686-pc-serenity-g++ -DDEBUG -DENABLE_COMPILETIME_FORMAT_CHECK -DKERNEL -DSANITIZE_PTRS …
```
> AK: Convince GCC that m_outline_capacity isn't being read

- Kernel/Net/TCPSocket.cpp
Previously we wouldn't release the buffer back to the network adapter in all cases. While this didn't leak the buffer it would cause the buffer to not be reused for other packets.
> Kernel: Release packet buffer in TCPSocket::send_tcp_packet

- README.md
Think this is fleshed out and cool enough to warrant being
in the README :^)
> Meta: Add `LibGL` to README :^)

- Userland/Demos/Cube/Cube.cpp
- Userland/Libraries/LibGL/DepthBuffer.cpp
- Userland/Libraries/LibGL/DepthBuffer.h
- Userland/Libraries/LibGL/GLBlend.cpp
- Userland/Libraries/LibGL/GLColor.cpp
- Userland/Libraries/LibGL/GLContext.cpp
- Userland/Libraries/LibGL/GLContext.h
- Userland/Libraries/LibGL/GLLights.cpp
- Userland/Libraries/LibGL/GLMat.cpp
- Userland/Libraries/LibGL/GLUtils.cpp
- Userland/Libraries/LibGL/GLVert.cpp
- Userland/Libraries/LibGL/SoftwareGLContext.cpp
- Userland/Libraries/LibGL/SoftwareGLContext.h
- Userland/Libraries/LibGL/SoftwareRasterizer.cpp
- Userland/Libraries/LibGL/SoftwareRasterizer.h
- Userland/Libraries/LibGfx/Font.h
- Userland/Libraries/LibGfx/Matrix4x4.h
- Userland/Libraries/LibGfx/Typeface.cpp
- Userland/Libraries/LibGfx/Typeface.h
- Userland/Libraries/LibGfx/Vector2.h
- Userland/Libraries/LibGfx/Vector3.h
- Userland/Libraries/LibGfx/Vector4.h
- Userland/Libraries/LibJS/Lexer.cpp
- Userland/Libraries/LibJS/Lexer.h
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Runtime/ScriptFunction.cpp
- Userland/Libraries/LibJS/Token.cpp
- Userland/Libraries/LibJS/Token.h
> Everywhere: Use s.unverwerth@serenityos.org :^)

- Userland/Applications/HexEditor/HexEditor.cpp
- Userland/Applications/HexEditor/HexEditor.h
- Userland/Applications/HexEditor/HexEditorWidget.cpp
> HexEditor: Add find_all_strings() function

- Userland/Libraries/LibGUI/TreeView.cpp
This adds an implementation for the Home, End, Page Up and Page Down cursor movements for TreeView.
Also, the Up and Down movement implementations are replaced by a more efficient traversal mechanism: whereas the old code would walk over all visible nodes every time, the new code only evaluates relevant sibling and parent indices.
> LibGUI/TreeView: Implement Home/End/PageUp/PageDn navigation

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/AST.h
- Userland/Libraries/LibJS/Interpreter.cpp
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Runtime/FunctionPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ScriptFunction.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/Tests/functions/function-destructuring-parameters.js
- Userland/Libraries/LibJS/Tests/syntax/destructuring-assignment.js
This should be behaving entirely to-spec now.
> LibJS: Implement destructuring assignments and arguments

- Kernel/Scheduler.cpp
- Kernel/VM/RangeAllocator.cpp
- Kernel/VM/Space.cpp
- Userland/DevTools/UserspaceEmulator/RangeAllocator.cpp
- Userland/Libraries/LibLine/Editor.h
- Userland/Shell/Shell.cpp
- Userland/Shell/SyntaxHighlighter.cpp
- Userland/Utilities/tr.cpp
> Everywhere: Sort out superfluous QuickSort.h imports

- Userland/Utilities/pls.cpp
Recent changes to `unveil` broke `pls`. This PR fixes it.
> pls: Unveil search paths with browse permissions

- Userland/Services/WebServer/main.cpp
With this we can make the Webserver listen on another address than the default of `0.0.0.0`. If we for example pass `127.0.0.1` as the listen address, the WebServer can only be reached from within Serenity itself and not from outside hosts.
This is my first contribution so I picked a small feature to contribute, I hope I did everything okay :)
> WebServer: Add optional listen address argument

- AK/SourceLocation.h
- Tests/AK/TestSourceLocation.cpp
- Userland/Libraries/LibC/cxxabi.cpp
- Userland/Libraries/LibELF/DynamicLoader.cpp
- Userland/Libraries/LibELF/DynamicLoader.h
- Userland/Libraries/LibELF/DynamicObject.cpp
- Userland/Libraries/LibELF/DynamicObject.h
- Userland/Libraries/LibELF/Hashes.h
- Userland/Libraries/LibELF/Validation.cpp
- Userland/Libraries/LibELF/Validation.h
> AK+Userland: Use akaster@serenityos.org for my copyright headers

- Userland/Libraries/LibGfx/JPGLoader.cpp
`JPGLoader` used to store component information in a `HashTable`, indexed
by the ID assigned by the JPEG file.  This was fine for most purposes,
however after f89e8fb7 this was revealed to be a flawed implementation
which causes non-deterministic iteration over components.
This issue was previously masked by a perfect storm of `int_hash` being
stable for the integer values 0, 1 and 2; and `AK::HashTable` having just
the right amount of buckets for the components to be ordered correctly
after being hashed with int_hash. However, after f89e8fb7,
`malloc_good_size` was used for determining the amount of space for
allocation; this caused the ordering of the components to change, and
images started showing up with the red and blue channels reversed. The
issue was finally determined to be …
> LibGfx: Make JPGLoader iterate components deterministically

- Documentation/Kernel/AHCILocking.md
- Kernel/Storage/AHCIPort.cpp
Still not complete, I'm working on it as @bgianfo suggested this after a discussion on the Discord server.
> Documentation: Add explanation about AHCI locking

- Ports/AvailablePorts.md
- Ports/stpuzzles/package.sh
This PR adds a port of Simon Tatham's Portable Puzzle Collection. The port is missing a few features (such as the customization menu), however, all games are completely playable.
> Ports: Add Simon Tatham's Puzzle Collection

- Userland/DevTools/HackStudio/LanguageServers/Cpp/CppComprehensionEngine.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/CppComprehensionEngine.h
- Userland/Libraries/LibCpp/AST.cpp
This refactors some of the logic of `CppComprehensionEngine`. I think this change is important to allow us to support working with "more serious" code in the future.
> CppLanguageServer: Work with a HashMap of Symbols in each document

- Kernel/FileSystem/AnonymousFile.h
- Kernel/FileSystem/DevFS.cpp
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/ProcFS.h
- Kernel/FileSystem/TmpFS.cpp
- Kernel/FileSystem/TmpFS.h
- Kernel/Syscalls/anon_create.cpp
- Kernel/Syscalls/mount.cpp
More progress on #6369, details in the commits.
> Kernel: More OOM safety improvements in FileSystem subsystem 

- Userland/Games/Chess/ChessWidget.cpp
This is a pretty minor change but it was bothering me :^)
Changes the cursor style when hovering over or dragging a piece.
> Chess: Change cursor style when interacting with a valid piece

- Userland/Utilities/open.cpp
**Utilities: Open now supports relative path as an argument**
Previously `open` command won't work with relative paths. This code firstly checks if the file exists, if not then it tries to open given URL.
> Utilities: Add support for relative paths in open command

- Documentation/Browser/ProcessArchitecture.md
- Documentation/Kernel/AHCILocking.md
Minor edits to some of the docs I found while reading through them. 
👍🏽 on the project! I am excited on contributing more in the future.
> Documentation: Minor edits, grammar fixes in Kernel and Browser Docs

- Userland/Libraries/LibWasm/AbstractMachine/Interpreter.cpp
Implements a few random missing instructions.
> LibWasm: more instructions

- AK/IntrusiveList.h
- Kernel/Process.cpp
- Kernel/ProcessGroup.cpp
- Kernel/ProcessGroup.h
- Tests/AK/TestIntrusiveList.cpp
- Userland/Libraries/LibC/malloc.cpp
- Userland/Libraries/LibC/mallocdefs.h
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/WindowManager.cpp
- Userland/Services/WindowServer/WindowManager.h
This is a continuation of #7479, progress towards converging `AK::InlineLinkedList` usages with `AK::IntrusiveList`.
> AK + LibC + WindowsServer + Kernel: Move more InlineLinkedList usages to IntrusiveList

- Kernel/Graphics/Console/Console.h
- Kernel/Graphics/Console/FramebufferConsole.cpp
- Kernel/Graphics/Console/FramebufferConsole.h
- Kernel/Graphics/Console/TextModeConsole.cpp
- Kernel/Graphics/Console/TextModeConsole.h
- Kernel/kprintf.cpp
> Kernel: Support new lines in critical prints

- Userland/Utilities/ps.cpp
This updates `ps` so that it calculates the ideal column width instead of relying on hard-coded values. Previously the `STATE` column was too small to fit the state for `FinalizerTask`.
> Utilities: Make sure columns for ps are properly aligned

- CONTRIBUTING.md
@awesomekling @linusg 
I think this is a pretty reasonable guideline, so we can effectively solve bare metal issues.
However, you might want to suggest to fix it somehow, hence this is a draft.
> Meta: Add a guideline about bare metal issues

- Userland/Games/Solitaire/Game.cpp
Fixes some missing code from when I attempted to resolve the merge conflict from PR #7649, where the newer version of `draw_cards` was missing the undo logic when resolving the two PR conflicts.
> Solitaire: Fixes undo feature from incorrect merge conflict resolution

- Ports/AvailablePorts.md
- Ports/p7zip/package.sh
- Ports/p7zip/patches/fixes.patch
Port of p7zip. This port uses https://github.com/jinfeihan57/p7zip as it's source which is a fork from the sourceforge version. This version receives updates and has additional codecs.
> Ports: p7zip

- Userland/Libraries/LibWeb/Layout/TextNode.cpp
This patch completely reworks TextNode::compute_text_for_rendering(). It removes the unnecessary usage of Utf8View to find spaces in a String. Furthermore, it adds a couple fast return paths for common but trivial cases such as empty, single-character and whitespace-less strings.
For the HTML spec bookmarks, around two thirds of all function calls (which amounts to around 10'000) use the fast paths and thus avoid allocating a StringBuilder just to build a copy of the already present String.
> LibWeb: Remove Utf8View usage and try avoiding StringBuilder in TextNode

- Ports/scummvm/package.sh
- Toolchain/Dockerfile
Perhaps slightly inspired by 9c0cfede.
> Ports: Embed ScummVM icons into the binary

- Kernel/Graphics/BochsGraphicsAdapter.cpp
- Kernel/Graphics/BochsGraphicsAdapter.h
- Kernel/Graphics/IntelNativeGraphicsAdapter.cpp
> Kernel: Misc graphics fixes

- Kernel/Net/IPv4Socket.cpp
- Kernel/Net/NetworkAdapter.cpp
- Kernel/Net/NetworkAdapter.h
- Kernel/Net/NetworkTask.cpp
- Kernel/Net/TCPSocket.cpp
- Kernel/Net/UDPSocket.cpp
> Kernel: Make sure we increment the TX counter

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/NumberConstructor.cpp
This makes 53 new test262 test cases pass.
> LibJS: Add the Number.{MAX, MIN}_VALUE constants

- Ports/gcc/package.sh
Credit goes to matthewbjones#8780 on Discord.
> Ports: fix gcc for mac users

- Ports/AvailablePorts.md
- Ports/SDL2_ttf/package.sh
- Ports/freeciv/package.sh
- Ports/freeciv/patches/configure.patch
- Ports/freeciv/patches/log.patch
- Ports/freetype/package.sh
- Userland/Libraries/LibC/locale.cpp
**Ports: Build shared library for freetype**
**Ports: Specify missing library when linking SDL2_ttf**
**LibC: Let setlocale() pretend that setting the locale succeeded**
By returning nullptr we're telling the caller that setlocale() failed. Some programs expect setlocale() to succeed so let's pretend that it did.
**Ports: Add port for freeciv**
> Ports: Add port for freeciv

- .github/workflows/libjs-test262.yml
- .github/workflows/manpages.yml
> CI: Run libjs-test262 and update results on every push to master

- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Identifiers.json
- Userland/Libraries/LibWeb/CSS/Parser/DeprecatedCSSParser.cpp
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/CSS/StyleResolver.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Libraries/LibWeb/Dump.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
[This spec algorithm](https://www.w3.org/TR/css-flexbox-1/#layout-algorithm) got implemented, and supersedes the very naive and simple way flex boxes got layout.
There are a lot of `FIXME`s to tackle and a lot of shortcuts got taken in the implementation.
> LibWeb: Implement somewhat spec compliant FlexBoxes

- Ports/AvailablePorts.md
- Ports/sam/package.sh
- Ports/sam/patches/sam.patch
Added port for SAM (Software Automatic Mouth).
Is there a better way to specify include and library directories?
> Ports: Add SAM

- Base/res/html/misc/border-radius.html
- Base/res/html/misc/custom-properties.html
- Base/res/html/misc/flex.html
- Base/res/html/misc/welcome.html
I added HTML pages to test/showcase the border-radius, custom properties and flexbox features in the Browser to the start page.
> Browser: Add various test pages to welcome

- Userland/Applications/Magnifier/MagnifierWidget.cpp
- Userland/Applications/Magnifier/MagnifierWidget.h
- Userland/Services/WindowServer/ClientConnection.cpp
- Userland/Services/WindowServer/ClientConnection.h
- Userland/Services/WindowServer/WindowServer.ipc
Fixes broken magnification when scale was changed to 2x.
Added a getter to detect when display scale changes.
> Magnifier: Add desktop display scale awareness

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Date.cpp
- Userland/Libraries/LibJS/Runtime/Date.h
- Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
- Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/DatePrototype.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setDate.js
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setFullYear.js
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setMonth.js
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.prototype.setTime.js
This fixes 141 test262 test cases :D
> LibJS: Date additions and fixes

- Ports/freeciv/package.sh
> Ports: Install launcher for Freeciv

- Userland/Libraries/LibLine/Editor.cpp
> LibLine: Teeny tiny fixes

- AK/IntrusiveList.h
- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/Syscalls/fork.cpp
- Tests/AK/TestIntrusiveList.cpp
This is a continuation of #7479 & #7728, progress towards converging `AK::InlineLinkedList` usages with `AK::IntrusiveList`.
> AK + Kernel: Move Process InlineLinkedList usages to IntrusiveList

- CONTRIBUTING.md
This is an attempt to clarify general pull request etiquette.
Answers are copied verbatim from `@awesomekling`'s responses in [Discord](https://discord.com/channels/830522505605283862/830522505605283866/851162182250922004).
> CONTRIBUTING.md: Add Pull Request Q&A section

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Adds in assignment operators for recently added bitwise ops.
> LibJS: Add <<, >> and >>> assignment operators

- Userland/Demos/CatDog/SpeechBubble.cpp
Enable cat dog to greet you, and help you with yak shave sessions.
CC: @gunnarbeutner
> CatDog: Enhance the speech bubble artificial intelligence

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Interpreter.cpp
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.h
- Userland/Libraries/LibJS/Runtime/LexicalEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/LexicalEnvironment.h
- Userland/Libraries/LibJS/Runtime/Reference.cpp
- Userland/Libraries/LibJS/Runtime/Reference.h
- Userland/Libraries/LibJS/Runtime/ScopeObject.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/Runtime/WithScope.cpp
- Userland/Libraries/LibJS/Runtime/WithScope.h
- Userland/Libraries/LibJS/Tests/operators/delete-local-variable.js
This fixes 81 test262 test cases :)
> LibJS: With statement and delete operator fixes

- AK/Forward.h
- AK/Iterator.h
- AK/Vector.h
- Tests/AK/TestVector.cpp
- Userland/Applications/Browser/CookieJar.cpp
- Userland/Applications/Browser/CookieJar.h
- Userland/Applications/KeyboardMapper/KeyboardMapperWidget.cpp
- Userland/Applications/Spreadsheet/CellTypeDialog.cpp
- Userland/Applications/Spreadsheet/Spreadsheet.cpp
- Userland/Applications/Spreadsheet/SpreadsheetWidget.cpp
- Userland/Applications/SystemMonitor/main.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/Libraries/LibCore/EventLoop.cpp
- Userland/Libraries/LibGUI/ColorPicker.cpp
- Userland/Libraries/LibGUI/ColorPicker.h
- Userland/Libraries/LibGUI/Splitter.cpp
- Userland/Libraries/LibGUI/Widget.cpp
- Userland/Libraries/LibGUI/Widget.h
- Userland/Libraries/LibGUI/Window.cpp
- Userland/Libraries/LibGUI/Window.h
- Userland/Libraries/LibTLS/HandshakeClient.cpp
- Userland/Services/WindowServer/MenuManager.cpp
- Userland/Services/WindowServer/MenuManager.h
- Userland/Services/WindowServer/Menubar.cpp
- Userland/Services/WindowServer/Menubar.h
- Userland/Services/WindowServer/WindowManager.h
> AK+Everywhere: Make Vector capable of holding reference types 

- Userland/Libraries/LibJS/AST.cpp
Previously SwitchStatement::execute() would return <empty> when hitting
break, continue or empty consequent block. This was not in line with
the standard.
> LibJS: Make SwitchStatement::execute() return undefined for empty blocks

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
This ensures that "while", do...while, "for" and scope expressions have a properly initialized result value even if the user terminated the loop body via break or the loop body wasn't executed at all.
> LibJS: Make sure loop results are initialized

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/MarkupGenerator.cpp
- Userland/Libraries/LibJS/Runtime/ArrayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/JSONObject.cpp
- Userland/Libraries/LibJS/Runtime/ProxyConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ProxyConstructor.h
- Userland/Libraries/LibJS/Runtime/ProxyObject.h
- Userland/Libraries/LibJS/Runtime/StringConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibJS/Tests/builtins/Array/Array.isArray.js
- Userland/Libraries/LibJS/Tests/builtins/Proxy/Proxy.js
- Userland/Libraries/LibJS/Tests/builtins/Proxy/Proxy.revocable.js
- Userland/Utilities/js.cpp
Some random things I came across.
> LibJS: 🦬🦬🪒🪒

- Ports/stpuzzles/package.sh
This depends on https://github.com/SerenityOS/serenity/pull/7834 and https://github.com/SerenityOS/stpuzzles/pull/3.
> Ports: Embed icons for the stpuzzles port

- Ports/scummvm/package.sh
Possible now that #7834 is merged!
> Ports: Use shared icon logic for ScummVM

- Userland/Libraries/LibAudio/WavLoader.cpp
Fixes https://github.com/SerenityOS/serenity/issues/6666 (probably, not 100% sure)
This enables support for playing float32 and float64
`WAVE_FORMAT_EXTENSIBLE` files.
The PCM data format is encoded in the
first two bytes of the SubFormat GUID inside of the
WAVE_FORMAT_EXTENSIBLE `fmt` chunk.
Also, fixed the RIFF header size check to allow up to
`maximum_wav_size` (currently defined as 1 GiB).
The RIFF header size is the size of the entire
file, so it should be checked against the largest Wave size.
Tested with audio files from this website: http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Samples.html
> LibAudio: Add support for WAVE_FORMAT_EXTENSIBLE

- Ports/AvailablePorts.md
- Ports/zsh/package.sh
- Ports/zsh/patches/0001-add-serenity-config-sub.patch
- Ports/zsh/patches/0002-add-serenity.patch
- Userland/Libraries/LibC/signal.cpp
- Userland/Libraries/LibC/termcap.cpp
Hi. This is my first port to the system, so if I've made something wrong, please tell me :)
To test it out, I tried to run the Oh My Zsh extension (which I use daily), and it was a little harder because the git port doesn't support remote clones yet.
> Ports: Add ZSH

- Ports/.port_include.sh
- Ports/AvailablePorts.md
- Ports/llvm/ReadMe.md
- Ports/llvm/package.sh
- Ports/llvm/patches/ReadMe.md
- Ports/llvm/patches/insert-ifdef-serenity.patch
- Ports/llvm/patches/remove-wstring.patch
- Userland/Libraries/LibC/sysexits.h
This PR adds LLVM port to SerenityOS. This PR is marked draft because some things still don't work:
- Clang can't print anything
- I still need to figure out how to link programs with lld (Using clang + gcc ld works fine)
> Ports: Add LLVM port

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/AggregateError.cpp
- Userland/Libraries/LibJS/Runtime/AggregateError.h
- Userland/Libraries/LibJS/Runtime/AggregateErrorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/AggregateErrorConstructor.h
- Userland/Libraries/LibJS/Runtime/AggregateErrorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/AggregateErrorPrototype.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Error.cpp
- Userland/Libraries/LibJS/Runtime/Error.h
- Userland/Libraries/LibJS/Runtime/ErrorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ErrorConstructor.h
- Userland/Libraries/LibJS/Runtime/ErrorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ErrorPrototype.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.h
- Userland/Libraries/LibJS/Tests/builtins/AggregateError/AggregateError.js
- Userland/Libraries/LibJS/Tests/builtins/AggregateError/AggregateError.prototype.message.js
- Userland/Libraries/LibJS/Tests/builtins/AggregateError/AggregateError.prototype.name.js
This fixes... Discord will tell us how many test262 tests :^)
> LibJS: Implement AggregateError (+ a minor rename)

- Userland/Utilities/du.cpp
Add -h/--human-readable option to du.
> Utilities/du: Add -h option

- Userland/Libraries/LibJS/Runtime/AggregateError.cpp
- Userland/Libraries/LibJS/Runtime/AggregateError.h
- Userland/Libraries/LibJS/Runtime/AggregateErrorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Error.cpp
- Userland/Libraries/LibJS/Runtime/Error.h
- Userland/Libraries/LibJS/Runtime/ErrorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Tests/builtins/AggregateError/AggregateError.js
- Userland/Libraries/LibJS/Tests/builtins/Error/Error.js
Currently stage 3. https://github.com/tc39/proposal-error-cause
> LibJS: Implement the Error Cause proposal

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
Bytecode is now generated for object literals which only contain simple key-value pairs (i.e. no spread, getters or setters).
> LibJS: Add bytecode generation for simple ObjectExpressions

- Userland/Games/2048/BoardView.cpp
- Userland/Games/2048/BoardView.h
- Userland/Games/2048/Game.cpp
- Userland/Games/2048/Game.h
- Userland/Libraries/LibGfx/Rect.h
Tiles now slide around merrily and new ones pop in. It's a delight.
https://user-images.githubusercontent.com/18616863/121723684-7f7fab80-caef-11eb-9a0b-e91844790f82.mp4
Drive-by changes:
* Convert 2048 to east const
* `LibGfx::Rect::centered_on(Point, Size)`
> 2048: Animations

- Tests/LibJS/test-js.cpp
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Heap/Heap.cpp
- Userland/Libraries/LibJS/Heap/Heap.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/WeakContainer.h
- Userland/Libraries/LibJS/Runtime/WeakMap.cpp
- Userland/Libraries/LibJS/Runtime/WeakMap.h
- Userland/Libraries/LibJS/Runtime/WeakMapConstructor.cpp
- Userland/Libraries/LibJS/Runtime/WeakMapConstructor.h
- Userland/Libraries/LibJS/Runtime/WeakMapPrototype.cpp
- Userland/Libraries/LibJS/Runtime/WeakMapPrototype.h
- Userland/Libraries/LibJS/Runtime/WeakSet.cpp
- Userland/Libraries/LibJS/Runtime/WeakSet.h
- Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.js
- Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.prototype.delete.js
- Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.prototype.get.js
- Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.prototype.has.js
- Userland/Libraries/LibJS/Tests/builtins/WeakMap/WeakMap.prototype.set.js
- Userland/Libraries/LibTest/JavaScriptTestRunner.h
This fixes 84 test262 test cases.
> LibJS: Add the WeakMap built-in object

- AK/Ptr32.h
This adds a transparent dereference operator, aswell as a constant
arrow operator
Also increaces the verbosity of the code
Yes these are a lot of cpp casts,
and yes that `operator T const *`was clang format (it looks normal in west-const)
> AK: Make Ptr32 more transparent

- Ports/AvailablePorts.md
- Ports/composer/package.sh
This makes the `composer` command available.
> Ports: Add Composer

- Userland/Games/Solitaire/Game.cpp
- Userland/Games/Solitaire/Game.h
- Userland/Games/Solitaire/main.cpp
This fixes #7792, and several other bugs that don't have issues logged. Feedback welcome! For one thing, I'm not certain that `set_background_fill_enabled()` is the right solution, or the right name.
Hopefully I can stop obsessing over Solitaire now. :^)
EDIT: Sorry about the initial check fails. This whole time I've been using `clang-format` without the `-i` parameter. 🤦‍♂️
> Solitaire: Various bug fixes

- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/IteratorOperations.cpp
- Userland/Libraries/LibJS/Runtime/IteratorOperations.h
- Userland/Libraries/LibJS/Runtime/VM.h
This fixes 10 test262 test cases
> LibJS: Implement the IteratorClose abstract op and use it where needed

- AK/Forward.h
- AK/HashMap.h
- AK/HashTable.h
Adds a IsOrdered flag to Hashtable, which allows iteration in insertion
order
> AK: Add Ordering support to HashTable etc

- Userland/Applications/HexEditor/HexEditorWidget.cpp
Use Yes/No/Cancel prompts in message box for saving changes on closing a file with unsaved changes.
Fixes #7169
> HexEditor: Use Yes/No/Cancel prompts for message boxes

- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Tests/builtins/Object/Object.defineProperty.js
This fixes 38 test262 test cases
> LibJS: Misc object fixes

- Userland/Applications/Help/main.cpp
Also fixes a bug where the page was not selected in the tree view during startup.
Note: First PR so all suggestions are welcome :)
> Help: Make sure the home page is actually shown when opening the app

- Userland/Utilities/js.cpp
js only accepted a single script file to run before this.  With this
patch, multiple scripts can be run in the same execution environment,
allowing the user to specify a "preamble script" to be executed before
the main script.
> Userland: Allow multiple files to be run by js

- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/ArrayBuffer.h
- Userland/Libraries/LibJS/Runtime/TypedArray.h
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.BYTES_PER_ELEMENT.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.BYTES_PER_ELEMENT.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.at.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.buffer.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.byteLength.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.byteOffset.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.length.js
- Userland/Utilities/js.cpp
This fixes ~297 test262 test cases :^)
More details in the individual commits.
> LibJS: Add BigInt64Array and BigUint64Array

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/ObjectPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ObjectPrototype.h
This fixes 69 test262 test cases :)
> LibJS: Add all of the missing Object.prototype methods from Annex B

- Userland/Applications/Spreadsheet/JSIntegration.cpp
- Userland/Applications/Spreadsheet/JSIntegration.h
- Userland/DevTools/HackStudio/Debugger/DebuggerGlobalJSObject.cpp
- Userland/DevTools/HackStudio/Debugger/DebuggerGlobalJSObject.h
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/IndexedProperties.cpp
- Userland/Libraries/LibJS/Runtime/IndexedProperties.h
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
- Userland/Libraries/LibJS/Runtime/ProxyObject.h
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.h
- Userland/Libraries/LibWeb/Bindings/CSSStyleDeclarationWrapperCustom.cpp
- Userland/Libraries/LibWeb/Bindings/HTMLCollectionWrapperCustom.cpp
- Userland/Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
As requested by @awesomekling :^)
(This depends on #8098 and will stay draft until it is merged, at which point i will rebase this and the first 3 commits will disappear :)
> LibJS: Replace boolean without_side_effects parameters with an enum

- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/TypedArrayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayConstructor.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.of.js
This fixes 20 test262 test cases.
> LibJS: Add the TypedArray.of() method

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/BrowserWindow.h
This adds a setting to change the initial starting page in tabs
> Browser: Add setting to change homepage URL

- Ports/AvailablePorts.md
- Ports/dosbox-staging/package.sh
- Ports/dosbox-staging/patches/glob.patch
- Ports/dosbox-staging/patches/gus.patch
- Ports/dosbox-staging/patches/sdl.patch
- Ports/dosbox-staging/patches/swrender.patch
- Ports/dosbox-staging/patches/wchar.patch
- Userland/Libraries/LibC/inttypes.h
**LibC: Add definition for PRIuPTR**
**Ports: Add port for DOSBox Staging**
What works:
* Doom (that's pretty much all I've tested so far).
What doesn't work:
* Typing `:` and several other characters.
> Ports: Add port for DOSBox Staging

- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.h
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.h
This fixes ~60 test262 test cases.
> LibJS: Add a couple of TypedArray.prototype properties/methods

- Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
This fixes 37 test262 test cases.
> LibJS: A couple of Array.prototype fixes

- AK/Format.cpp
- AK/Format.h
- Tests/AK/TestFormat.cpp
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/NumberPrototype.cpp
- Userland/Libraries/LibJS/Runtime/NumberPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Number/Number.prototype.toFixed.js
This fixes 10 test262 test cases
> LibJS: Add the Number.prototype.toFixed method

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
According to https://262.ecma-international.org/10.0/#sec-if-statement-runtime-semantics-evaluation the return value for if expressions should be undefined when the branch statements don't yield a value.
> LibJS: Let if yield undefined for branches that don't yield a value

- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/Value.cpp
test262 runner is being updated in https://github.com/linusg/libjs-test262/pull/20.
> LibJS: Implement support for the [[IsHTMLDDA]] internal slot

- Userland/Utilities/js.cpp
Needed to have correct ASI behaviour in the CLI
> js: Insert newline after each line in REPL mode

- Userland/Utilities/cp.cpp
Previously, copying a file to a directory, like this:
```cp README.md Desktop```
correctly copied it to Desktop/README.md, but would fail if the source was also a directory, for example:
```cp -R Documents Desktop```
Now, that correctly copies it to Desktop/Documents, as you would expect. :^)
> cp: Copy sources into destination if it is already a directory

- Userland/Services/WindowServer/Cursor.cpp
- Userland/Services/WindowServer/Cursor.h
_I thought for sure I had pushed a fix for this to #8032 but it got lost somehow..._
> WindowServer: Fix animated cursor regression

- Userland/DevTools/UserspaceEmulator/CMakeLists.txt
- Userland/DevTools/UserspaceEmulator/Emulator.cpp
- Userland/DevTools/UserspaceEmulator/Emulator.h
- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
- Userland/DevTools/UserspaceEmulator/main.cpp
This is somewhat inspired by gdb's functionality.
Current Features:
* Pause upon Startup (currently at the very beginning not in main(...))
* Pause on SIGINT
* Any size stepping
* run until this function returns returns
* current function name
TODO's:
* Execute until function or address
* maybe a nicer way to kill the program on `quit` and double SIGINT
> UserspaceEmulator: Add a DebugConsole

- Base/home/anon/tests/run-tests-and-shutdown.sh
now that tests run on their respective directories
> Tests: Enable AK/TestJSON back

- Userland/Applications/HexEditor/HexEditorWidget.cpp
**HexEditor: Prompt the user to save changes when opening a file**
**HexEditor: Change name for unsaved files to 'Untitled'**
> HexEditor: Prompt the user to save changes when opening a file

- Userland/DevTools/HackStudio/AutoCompleteResponse.h
- Userland/DevTools/HackStudio/CMakeLists.txt
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.h
- Userland/DevTools/HackStudio/LanguageClient.cpp
- Userland/DevTools/HackStudio/LanguageClient.h
- Userland/DevTools/HackStudio/LanguageServers/CodeComprehensionEngine.cpp
- Userland/DevTools/HackStudio/LanguageServers/CodeComprehensionEngine.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/ClientConnection.h
- Userland/DevTools/HackStudio/LanguageServers/Cpp/CppComprehensionEngine.cpp
- Userland/DevTools/HackStudio/LanguageServers/Cpp/CppComprehensionEngine.h
- Userland/DevTools/HackStudio/LanguageServers/LanguageClient.ipc
- Userland/DevTools/HackStudio/LanguageServers/Shell/ClientConnection.h
- Userland/DevTools/HackStudio/ToDoEntries.cpp
- Userland/DevTools/HackStudio/ToDoEntries.h
- Userland/DevTools/HackStudio/ToDoEntriesWidget.cpp
- Userland/DevTools/HackStudio/ToDoEntriesWidget.h
- Userland/Libraries/LibCpp/Parser.cpp
- Userland/Libraries/LibCpp/Parser.h
- Userland/Libraries/LibCpp/Preprocessor.h
Now it's possible to see all FIXME and TODO of the project.
Signed-off-by: Federico Guerinoni <guerinoni.federico@gmail.com>
> HackStudio: Implement ToDoEntriesWidget

- Userland/Services/WindowServer/WindowManager.cpp
This doesn't yet restrict rendering to the screen it's being maximized
on.
> WindowServer: Make vertical maximize work on other screens

- Userland/Services/WindowServer/Compositor.cpp
This accidentally was broken by 38af4c29e
> WindowServer: Fix regression flushing scaled displays

- AK/CharacterTypes.h
- AK/String.cpp
- Tests/LibCrypto/TestBigInteger.cpp
- Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.cpp
- Userland/Libraries/LibCrypto/BigInt/SignedBigInteger.h
- Userland/Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
- Userland/Libraries/LibCrypto/BigInt/UnsignedBigInteger.h
- Userland/Libraries/LibCrypto/NumberTheory/ModularFunctions.cpp
- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/Op.cpp
- Userland/Libraries/LibJS/Runtime/BigInt.h
- Userland/Libraries/LibJS/Runtime/BigIntPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibTLS/Certificate.cpp
- Userland/Utilities/test-crypto.cpp
This fixes 2 test262 test cases.
> LibJS: Support the radix argument in BigInt.prototype.toString

- Userland/Utilities/run-tests.cpp
TestProcFs expects to be able to stat its stdout and stderr. The new
ProcFS implemetnation properly forwards the symlinks for
/proc/pid/fd/[1,2] to the temporary file that we had unlinked prior to
spawning the process. However, this makes it so that a normal stat on
the symlink to that file fails (as expected). Move the unlink to after
we've waited on the child, so that we know it won't be trying any funny
business with its stdout/stderr anymore.
> Userland: Unlink file after waiting for child in run-tests

- Kernel/PCI/MMIOAccess.cpp
There is a check in map_bus_region to make sure we don't pointlessly
remap the bus region if the previous mapping was for the same bus.
This is tracked with `m_mapped_bus`.
However, nothing was actually updating `m_mapped_bus`, and it is
initialised to 0. This means that if we start with a device on bus 0,
the read in data will be valid. If we map say bus 1 then bus 0 again,
the map for bus 0 will now be ignored and invalid data will be read in.
Fixed by updating `m_mapped_bus` with the currently mapped bus.
> Kernel/PCI: Keep track of the currently mapped bus in MMIO mode

- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
Specifically, we immediately return an empty string when `this` is an empty string, instead of wasting time in a loop doing nothing N times.
This fixes 1 flaky test262 test case.
> LibJS: Optimize & Bring String.prototype.repeat closer to the spec

- Userland/Applications/Debugger/main.cpp
- Userland/DevTools/CMakeLists.txt
- Userland/Libraries/LibX86/Instruction.h
- Userland/Utilities/functrace.cpp
- Userland/Utilities/test_io.cpp
**Userland: Disable Hackstudio and UE on x86_64**
**Debugger: Compile on x86_64**
This is not guaranteed to work at all
**Utilities: Fix Build on x86_64**
Not quite sure about the VirtualAddress changes though
> Kernel: X86 64 part8.5 -- Build fixes for Userland

- Userland/Libraries/LibJS/Runtime/ArrayBufferConstructor.cpp
This fixes 3 test262 test cases.
> LibJS: Check for DataView in ArrayBuffer.isView()

- Userland/Libraries/LibJS/Runtime/FunctionPrototype.cpp
This fixes 1 test262 test case.
> LibJS: Stop coercing this to object in Function's Symbol.hasInstance

- Userland/Libraries/LibJS/Runtime/JSONObject.cpp
This fixes 9 test262 test cases.
> LibJS: Bring JSON.stringify closer to the specification

- Userland/Libraries/LibJS/Runtime/JSONObject.cpp
This PR does not fix the main issue with our current implementation: The specification requires that we first check the JSON string for validity with an ECMA-404 compliant parser, and then evaluate it as if it was javascript code, of which we do neither at the moment.
This fixes 2 test262 test cases.
> LibJS: Bring JSON.parse slightly closer to the specification

- Kernel/Arch/x86/TrapFrame.h
- Kernel/Arch/x86/common/Interrupts.cpp
> Kernel: Fix building the kernel with LTO

- Userland/Applications/Assistant/Providers.cpp
- Userland/Applications/Assistant/Providers.h
- Userland/Applications/Assistant/main.cpp
Prefix text with "$" in the Assistant text box to run a command in a
forked terminal. For example, "$ top" or "$ top -s pid".
> Assistant: Add provider to run a command in a terminal

- Kernel/Arch/x86/x86_64/Boot/boot.S
> Kernel/x86_64: Halt if we happen to boot on non-x86_64 machine

- .github/workflows/libjs-test262.yml
- Documentation/SelfHostedRunners.md
- Meta/run.sh
This should speed it up quite a bit and give us more consistent performance. (So this workflow could eventually be used for perf regression testing as well)
> CI: Run the test262 workflow on a self-hosted runner 

- Userland/Applications/Assistant/Providers.h
**Assistant: Add missing bitmap accessor for terminal actions**
**Assistant: Make the bitmap accessor pure virtual**
Assistant looks broken when a result doesn't have an icon.
**Assistant: Make more of the classes final**
> Assistant: Add missing bitmap accessor for terminal actions

- Userland/Libraries/LibWeb/DOM/Document.cpp
We must hook `on_call_stack_emptied` after the interpreter was created, as the initialization of the WindowsObject can invoke some internal calls, which will eventually lead to this hook being called without `m_interpreter` being fully initialized yet. (This fixes the browser crash)
> LibWeb: Hook on_call_stack_emptied after m_interpreter was initialized

- Userland/Applications/Assistant/main.cpp
This is my first PR, so please help me out if I get stuck.
This fixes #8407.
> Assistant: Show a border around the window

- Userland/Libraries/LibJS/Runtime/TypedArrayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayConstructor.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.from.js
This fixes 41 test262 test cases :^)
> LibJS: Add the TypedArray.from() method

- Userland/Libraries/LibWeb/Bindings/WindowObjectHelper.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/DOMParser.cpp
- Userland/Libraries/LibWeb/HTML/DOMParser.h
- Userland/Libraries/LibWeb/HTML/DOMParser.idl
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTemplateElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTemplateElement.h
I went till I hit the next major roadblock: mutation observers.
This library is used by YouTube.
Details in the individual commits.
> LibWeb: Implement/fix a bunch of stuff required by Web Components Polyfills

- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Runtime/TypedArray.h
This fixes 13 test262 test cases.
> LibJS: Typed array constructor fixes

- Kernel/Arch/x86/common/Interrupts.cpp
- Kernel/Arch/x86/i386/Processor.cpp
Looks like a tab snuck in. :)
cc @alimpfard :stuck_out_tongue:
> Kernel: Fix incorrect indentation

- Userland/Services/WindowServer/WindowManager.cpp
Calling Window::is_modal requires the window to be on a window stack,
so we need to check this before removing it from the window stack.
> WindowServer: Fix crash removing modal windows

- Kernel/Thread.cpp
This provides more crucial information to be able to do an addr2line
lookup on a backtrace captured with Thread::backtrace.
_Example:_
```
0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +1708
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +1038
0xdeadc0de  Kernel::Scheduler::pick_next() +1056
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +537
0xdeadc0de  Kernel::Thread::die_if_needed() +562
0xdeadc0de  syscall_handler +11230
0xdeadc0de  syscall_asm_entry +49
0x1ff8e335  libc.so: .text +172853
0x1ff77856  libc.so: .text +79958
0x1ff7833b  libc.so: .text +82747
0x200c44fc  libipc.so: .text +25852
0x5d225b27  libgui.so: .text +793383
0x5d23688d  libgui.so: .text +862349
0x5d33c90a  libgui.so: .text +1935626
0x5d33ca44  libgui.so: …
```
> Kernel: Print region name+offset for user addresses in thread backtrace

- Kernel/KSyms.cpp
> Kernel: Fix method name load_kernel_{sybols => symbols}_from_data()

- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.reverse.js
> LibJS: Add %TypedArray%.prototype.reverse

- Userland/Libraries/LibJS/Runtime/PropertyName.h
- Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Tests/builtins/Proxy/Proxy.handler-apply.js
- Userland/Libraries/LibJS/Tests/object-expression-numeric-property.js
...and a small Proxy fix, because why not.
> LibJS: Fixes for numeric properties

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ObjectConstructor.h
This fixes 16 test262 test cases :)
(This also includes a small rename commit)
> LibJS: Implement Object.getOwnPropertyDescriptors()

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.h
- Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.h
- Userland/Libraries/LibJS/Runtime/Temporal/Now.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Now.h
- Userland/Libraries/LibJS/Runtime/Temporal/Temporal.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Temporal.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.h
- Userland/Utilities/js.cpp
Fixes 8 of the currently 15 Temporal test262 tests :^)
> LibJS: Start implementing the Temporal proposal :^)

- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/ProxyConstructor.cpp
- Userland/Libraries/LibJS/Runtime/ProxyObject.cpp
This fixes 3 test262 test cases.
> LibJS: Miscellaneous Proxy fixes

- Userland/DynamicLoader/main.cpp
- Userland/Libraries/LibELF/DynamicLoader.cpp
**DynamicLoader: Don't use LibELF to do the initial relocations**
Using LibELF to do the initial relocations doesn't work when building SerenityOS with Clang. We seem to be accessing a global symbol that hasn't been relocated yet somewhere along the path to ELF::DynamicObject::create().
**LibELF: Fix loading libs with a .text segment that's not page-aligned**
It's perfectly acceptable for the segment's vaddr to not be page aligned as long as the segment itself is page-aligned. We'll just map a few more bytes at the start of the segment that will be unused by the library.
We didn't notice this problem because because GCC either always uses 0 for the .text segment's vaddr or at least aligns the vaddr to the page size.
LibELF would also fail to load really small libraries (i.e. smaller than …
> DynamicLoader: Don't use LibELF to do the initial relocations

- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.copyWithin.js
> LibJS: Add %TypedArray%.prototype.copyWithin

- Userland/Applications/ImageViewer/ViewWidget.cpp
- Userland/Applications/ImageViewer/ViewWidget.h
- Userland/Applications/ImageViewer/main.cpp
- Fix path iteration when run from terminal
- Fix window size consistency when iterating over images
> ImageViewer: Changes to improve navigation

- Documentation/BuildInstructions.md
I ended up building on my Void Linux box today, hopefully I can save someone else five minutes!
> Documentation: Added build instructions for Void Linux

- Userland/Libraries/LibJS/Runtime/RegExpConstructor.cpp
- Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Userland/Libraries/LibJS/Runtime/RegExpPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/RegExp/RegExp.js
- Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.split.js
- Userland/Libraries/LibRegex/RegexMatcher.cpp
- Userland/Libraries/LibRegex/RegexMatcher.h
> LibJS+LibRegex: Some more RegExp spec fixes and implement @@split

- Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
- Userland/Libraries/LibJS/Runtime/ObjectPrototype.cpp
- Userland/Libraries/LibJS/Runtime/PromisePrototype.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/TypedArrayPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.toLocaleString.js
This fixes 22 test262 test cases.
> LibJS: Add %TypedArray%.prototype.toLocaleString

- Tests/LibRegex/RegexLibC.cpp
- Userland/Libraries/LibRegex/C/Regex.cpp
- Userland/Libraries/LibRegex/RegexByteCode.h
- Userland/Libraries/LibRegex/RegexMatcher.cpp
- Userland/Libraries/LibRegex/RegexParser.cpp
- Userland/Libraries/LibRegex/RegexParser.h
- Userland/Utilities/expr.cpp
- Userland/Utilities/grep.cpp
TL;DR: Dr.POSIX needs to stop using regular expressions from the good old '86 UNIX.
> LibRegex: Add support for the Basic POSIX regular expressions 

- Userland/Libraries/LibJS/Runtime/Temporal/InstantConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.h
Just a couple of tiny changes to start :)
> LibJS: Add Temporal.Instant.prototype.valueOf

- Userland/Utilities/chres.cpp
> Make chres usable again after recent regressions

- Userland/Libraries/LibJS/Runtime/Date.h
- Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.now.js
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Fixes... *some* test262 tests.
> LibJS: Date fixes

- Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
> SpaceAnalyzer: Show folder total size

- Userland/DevTools/HackStudio/LanguageServers/Cpp/CppComprehensionEngine.cpp
- Userland/Libraries/LibCpp/AST.cpp
- Userland/Libraries/LibCpp/AST.h
- Userland/Libraries/LibCpp/Parser.cpp
As suggested by @alimpfard in #8260.
> LibCpp: Refactor - Make fields of AST nodes private and use verify_cast<T>

- Userland/Games/FlappyBug/Game.cpp
- Userland/Games/FlappyBug/Game.h
`wsctl -f 1` is such a great feature!
> FlappyBug: Only paint areas which need to be painted

- Kernel/FileSystem/VirtualFileSystem.cpp
Previously, `VirtualFileSystem::mkdir()` would always return ENOENT if no parent custody was returned by `resolve_path()`. This is incorrect when e.g. the user has no search permission in a component of the path prefix (=> EACCES), or if on component of the path prefix is a file (=> ENOTDIR). This patch fixes that behavior.
> Kernel: Return correct error numbers for the mkdir syscall

- Base/usr/share/man/man1/ls.md
- Userland/Libraries/LibCore/File.cpp
- Userland/Libraries/LibCore/File.h
- Userland/Utilities/ls.cpp
List subdirectories encountered using -R or --recursive flags with ls.
> ls: Add option to list subdirectories recursively

- Userland/Applications/ImageViewer/main.cpp
- Userland/Applications/SoundPlayer/SoundPlayerWidgetAdvancedView.cpp
- Userland/DevTools/HackStudio/Editor.cpp
Follow up to the discussion from #8689
> HackStudio+SoundPlayer+ImageViewer: Activate windows only on file drops

- Userland/Shell/Builtin.cpp
- Userland/Shell/Shell.cpp
- Userland/Shell/Shell.h
Add unalias builtin to remove aliases
> Shell: Add unalias builtin

- Meta/build-root-filesystem.sh
Unfortunately we can't just use `--chown` everywhere because only rsync version 3.1 and newer support it and the default rsync on macOS is 2.6.9.
Fixes #8711.
> Meta: Make sure files are installed with the right UID and GID

- Userland/DynamicLoader/main.cpp
GCC doesn't seem to rely on those to work, but Clang does.
> DynamicLoader: Add RELA support for self-relocations

- Ports/AvailablePorts.md
- Ports/epsilon/package.sh
- Ports/epsilon/patches/SHOULD_USE_DYNAMIC_SDL.patch
- Ports/epsilon/patches/build-serenity.patch
- Ports/epsilon/patches/ion-linux.patch
Reverted https://github.com/SerenityOS/serenity/commit/15d5c629158fd598d162f5acba26ffee7a923ff8 for libpng usage in epsilon
> Ports : Add epsilon 15.5.0

- Userland/Applications/Piano/AudioPlayerLoop.cpp
- Userland/Applications/Piano/AudioPlayerLoop.h
- Userland/Applications/Piano/CMakeLists.txt
- Userland/Applications/Piano/MainWidget.cpp
- Userland/Applications/Piano/MainWidget.h
- Userland/Applications/Piano/PlayerWidget.cpp
- Userland/Applications/Piano/PlayerWidget.h
- Userland/Applications/Piano/TrackManager.cpp
- Userland/Applications/Piano/TrackManager.h
- Userland/Applications/Piano/main.cpp
Piano now has a toolbar allowing the playback to be paused, or to be stepped forward or back a note.
In the future I would like to add more to control the playback such as manipulating playback speed without changing the tempo of the audio.
Will hopefully contribute towards issue #6528
> Piano: Play/Pause, Forward and Back buttons

- Base/usr/share/man/man1/comm.md
- Userland/Utilities/CMakeLists.txt
- Userland/Utilities/comm.cpp
> Utilities: Add comm

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/BrowserWindow.h
- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibWeb/InProcessWebView.cpp
- Userland/Libraries/LibWeb/InProcessWebView.h
- Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
- Userland/Libraries/LibWeb/OutOfProcessWebView.h
- Userland/Libraries/LibWeb/Page/BrowsingContext.cpp
- Userland/Libraries/LibWeb/Page/BrowsingContext.h
- Userland/Services/WebContent/ClientConnection.cpp
- Userland/Services/WebContent/ClientConnection.h
- Userland/Services/WebContent/WebContentServer.ipc
https://user-images.githubusercontent.com/5600524/125628596-2544a8df-6a43-4d3b-b360-ed8b68a4c95a.mp4
> Browser+LibWeb: Add select-all and copy actions to context menu

- Meta/run.sh
Sorry for breaking everyone's builds (yet again) :(
> Meta: Don't use SPICE if QEMU doesn't support it

- Userland/Applications/Browser/Tab.cpp
- Userland/Libraries/LibGfx/Painter.cpp
…aand fix LibGfx to show this set of characters correctly.
> Browser: Escape an ampersand in the menu to avoid making a shortcut

- Meta/run.sh
The previous fix did not work for me, but this does. :^)
Credit goes to @X-yl for actually figuring it out.
> Meta: Fix SPICE detection in run.sh

- Ports/epsilon/package.sh
Adds a launcher for Epsilon  under category 'Utilities' and missing dependency 'freetype'
> Ports: Add launcher and missing dependency 'freetype' epsilon

- Base/usr/share/man/man8/groupadd.md
- Base/usr/share/man/man8/groupdel.md
- Userland/Libraries/LibC/grp.cpp
- Userland/Libraries/LibC/grp.h
- Userland/Utilities/groupadd.cpp
- Userland/Utilities/groupdel.cpp
This PR adds the `groupadd` and `groupdel` utilities. It also adds the `putgrent` LibC function. This closes issue #4898.
> LibC+Utilities: Add groupadd and groupdel

- Userland/DevTools/HackStudio/CodeDocument.cpp
- Userland/DevTools/HackStudio/CodeDocument.h
- Userland/DevTools/HackStudio/EditorWrapper.cpp
- Userland/DevTools/HackStudio/EditorWrapper.h
- Userland/DevTools/HackStudio/HackStudioWidget.cpp
- Userland/DevTools/HackStudio/HackStudioWidget.h
- Userland/DevTools/HackStudio/Language.cpp
- Userland/DevTools/HackStudio/Language.h
The statusbar will show the line and column number of the cursor position
as well as the number of selected words/characters.
The language of the opened file will also be displayed.
> HackStudio: Add statusbar with file and selected text information

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Userland/Libraries/LibJS/Runtime/RegExpPrototype.h
- Userland/Libraries/LibJS/Runtime/RegExpStringIterator.cpp
- Userland/Libraries/LibJS/Runtime/RegExpStringIterator.h
- Userland/Libraries/LibJS/Runtime/RegExpStringIteratorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/RegExpStringIteratorPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.matchAll.js
> LibJS: Implement RegExpStringIterator and RegExp.prototype [ @@matchall ]

- Kernel/Time/TimeManagement.h
- Kernel/init.cpp
> Kernel: Initialize TimeManagement before using KernelRNG

- Kernel/Thread.cpp
When a Thread is being unblocked and we need to re-lock the process
big_lock and re-locking blocks again, then we may end up in
Thread::block again while still servicing the original lock's
Thread::block. So permit recursion as long as it's only the big_lock
that we block on again.
Fixes #8822
> Kernel: Fix blocking relock of the big_lock while unlocking other Lock

- Userland/Services/WindowServer/Compositor.cpp
> WindowServer: Fix crash rendering fullscreen window

- Kernel/Prekernel/init.cpp
This copies the ELF header because we might end up overwriting when loading the ELF sections.
> Prekernel: Make sure we're not overwriting the ELF header

- Ports/.port_include.sh
- Ports/cmatrix/package.sh
- Ports/nyancat/package.sh
- Ports/python3/package.sh
- Ports/vitetris/package.sh
- Userland/Libraries/LibDesktop/AppFile.cpp
- Userland/Libraries/LibDesktop/AppFile.h
- Userland/Services/Taskbar/TaskbarWindow.cpp
- Userland/Services/Taskbar/main.cpp
> Ports: Add a launcher for Python

- Userland/Libraries/LibJS/AST.cpp
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.reduce.js
- Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.reduceRight.js
- Userland/Libraries/LibJS/Tests/builtins/Proxy/Proxy.handler-setPrototypeOf.js
- Userland/Libraries/LibJS/Tests/duplicated-variable-declarations.js
- Userland/Libraries/LibJS/Tests/iterators/string-iterator.js
- Userland/Libraries/LibJS/Tests/program-non-strict.js
- Userland/Libraries/LibJS/Tests/program-strict-mode.js
This started from investigation for #8509
And ended up with first a bunch of strict mode fixes on top of the this value changes.
cc @trflynn89 Are you ok with the commit like this?
> LibJS: Strict mode and this value fixes

- Userland/Libraries/LibGUI/TextDocument.cpp
Previously, pressing 'x' for deletion on an otherwise empty line insinuated a crash in TextEditor because TextRange aimed to select and use a nonexistent code point -- likewise for visual mode with 'v'.
This patch fixes #8769.
> VimEditingEngine: Prevent crash upon 'x' or 'v' on blank lines

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
- Userland/Libraries/LibJS/Runtime/Value.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.dateFromFields.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.equals.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.valueOf.js
(This also implements a Temporal.Calendar.prototype method that was implicitly required by an Abstract Operation)
> LibJS: Implement some Temporal.PlainDate.prototype methods

- Userland/Applications/FileManager/DirectoryView.cpp
- Userland/Applications/FileManager/DirectoryView.h
- Userland/Applications/FileManager/FileOperationProgress.gml
- Userland/Applications/FileManager/FileOperationProgressWidget.cpp
- Userland/Applications/FileManager/FileOperationProgressWidget.h
- Userland/Applications/FileManager/FileUtils.cpp
- Userland/Applications/FileManager/FileUtils.h
- Userland/Applications/FileManager/PropertiesWindow.cpp
- Userland/Applications/FileManager/PropertiesWindow.h
- Userland/Applications/FileManager/main.cpp
- Userland/Services/FileOperation/main.cpp
This is a bigger change than my previous ones, so there's a greater chance I'm doing things wrong. Apologies in advance. :^)
While doing this, #8203 has become quite prominent, but wasn't caused by my changes as far as I'm aware.
> FileManager+FileOperation: Show progress dialogs for all file Move/Copy/Delete operations

- AK/AllOf.h
- AK/AnyOf.h
- AK/Concepts.h
- AK/Find.h
- AK/StdLibExtraDetails.h
- AK/Vector.h
- Tests/AK/TestAllOf.cpp
- Tests/AK/TestAnyOf.cpp
- Tests/AK/TestTypeTraits.cpp
cc @awesomekling, you asked for this and I liked it :P
> AK: Implement {any,all}_of(IterableContainer&&, Predicate) 

- AK/SIMD.h
- Userland/DevTools/UserspaceEmulator/CMakeLists.txt
- Userland/DevTools/UserspaceEmulator/SoftCPU.cpp
- Userland/DevTools/UserspaceEmulator/SoftCPU.h
- Userland/DevTools/UserspaceEmulator/SoftFPU.cpp
- Userland/DevTools/UserspaceEmulator/SoftFPU.h
- Userland/Libraries/LibX86/Instruction.cpp
- Userland/Libraries/LibX86/Instruction.h
- Userland/Libraries/LibX86/Interpreter.h
This is to replace and revamp #6593, with a lot of the unnecessary changes removed and the commit-history cleaned up.
> UserspaceEmulator: SoftFPU take 2

- Kernel/Arch/x86/common/SafeMem.cpp
This ensures that we can properly take the address of these symbols in other code.
> Kernel: Add missing .globl definitions

- Userland/Games/Hearts/Game.cpp
- Userland/Games/Solitaire/Game.cpp
- Userland/Games/Spider/Game.cpp
Because playing the same game over and over again is somewhat less fun. :)
> Spider: Properly seed the random number generator

- Base/res/html/misc/opacity.html
- Base/res/html/misc/welcome.html
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.h
This PR implements the CSS opacity property. ~~Currently selecting text is a bit buggy, so I'll leave it as a draft for now.~~ That will be dealt with in another PR.
> LibWeb: Add CSS opacity property

- Kernel/Net/NE2000NetworkAdapter.cpp
- Kernel/Net/NE2000NetworkAdapter.h
- Meta/run.sh
NE2000 was broken because the OS thought the link was always down. Fixed that and improved a few things, see the commits.
Sorry for the archeology, but this seemed like nice stuff for me to get more acquainted with the project :)
> NE2000 working again and improved 

- Userland/Applications/SystemMonitor/NetworkStatisticsWidget.cpp
Had Office Hours running in the background and felt the need to address :)
> SystemManager: Separate sockets GroupBox into TCP/UDP

- Userland/Libraries/LibGUI/FilePicker.cpp
- Userland/Libraries/LibGUI/MultiView.cpp
Taken shortcuts from FileManager.
> LibGUI: Add keyboard shortcuts to FilePicker and MultiView

- Base/usr/share/man/man7/Mitigations.md
Update the man page to describe more mitigations that we have applied.
> Base: Mitigations(7) add -fzero-call-used-regs and Process Protection

- Userland/Applications/Mail/MailWidget.cpp
- Userland/Libraries/LibGUI/InputBox.cpp
- Userland/Libraries/LibGUI/InputBox.h
This allows the user to create a mail configuration without having
to save the password in clear text (or any other form) to disk.
_I wanted to try out Mail but couldn't get myself to actually save my clear text password to _disk...__
> Mail: Prompt for password if no password was saved

- .github/workflows/cmake.yml
This should prevent 5 unnecessary downloads for each CI run.
> CI: Cache UnicodeData files on GitHub Actions runs

- Userland/Games/Spider/Game.cpp
- Userland/Games/Spider/Game.h
- Userland/Games/Spider/main.cpp
In the future, I will work on a nice window to display these statistics - similar to what KPatience has.
> Spider: Track more statistics

- Userland/Libraries/LibGUI/FilePicker.cpp
- Userland/Libraries/LibGUI/FilePicker.h
> LibGUI: Show an error message on open error in the FilePicker

- Userland/Libraries/LibGUI/FilePickerDialog.gml
> LibGUI: Align FilePickerDialog's common locations with file list view

- Userland/Applications/SpaceAnalyzer/TreeMapWidget.cpp
> SpaceAnalyzer: Adjust the `text_rect`

- Tests/LibUnicode/TestUnicodeCharacterTypes.cpp
- Userland/Libraries/LibUnicode/CharacterTypes.cpp
- Userland/Libraries/LibUnicode/CodeGenerators/GenerateUnicodeData.cpp
- Userland/Libraries/LibUnicode/unicode_data.cmake
With this, all `String.prototype.to{Lower,Upper}Case` and `String.prototype.toLocale{Lower,Upper}Case` pass :grinning: 
Sigma sure is a special character!
> LibUnicode: Use PropList and WordBreakProperty in special case folding

- Userland/Libraries/LibCore/LockFile.cpp
> LibCore: Prevent leaking LockFile fd into child process

- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.getISOFields.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.getISOFields.js
This ticks two checkboxes in #8982.
> LibJS: Implement Temporal.Plain{Date,Time}.prototype.getISOFields()

- Documentation/BuildProfilingInstructions.md
After discussing on Discord about how to speed up the build time, I
received lots of helpful advice on measuring the build time, but none of
it was easily accessible. I thought other people might find it useful,
so I've written it down! :^)
Thanks goes to @bgianfo and @nico.
> Documentation: Add BuildProfilingInstructions.md

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.toPlainTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.withCalendar.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.withPlainDate.js
> LibJS: Implement 3 Temporal.PlainDateTime.prototype methods

- Userland/Utilities/shot.cpp
The hyperlink only gets printed when stdout is a TTY, so e.g. something like `shot | cat` will not get the hyperlink escapes.
(this is a small improvement I thought would be nice while watching the July update video)
> shot: Make output filename a hyperlink when applicable

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/Now.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZoneConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getOffsetStringFor.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.prototype.getPlainDateTimeFor.js
Ticks three checkboxes in #8982.
> LibJS: Implement Temporal.TimeZone.{from,prototype.get{OffsetString,PlainDateTime}For}()

- Userland/Applications/FileManager/PropertiesWindow.cpp
- Userland/Applications/FileManager/main.cpp
> FileManager: Refresh DirectoryView after applying changes

- Userland/Applications/3DFileViewer/main.cpp
> 3DFileViewer: Display frame rate optionally

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
- Userland/Libraries/LibJS/Runtime/Temporal/Now.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Now.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Temporal.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimeConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimeConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.zonedDateTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Now/Now.zonedDateTimeISO.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.@@toStringTag.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.calendar.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.timeZone.js
- Userland/Utilities/js.cpp
> LibJS: Start implementing Temporal.ZonedDateTime

- Kernel/FileSystem/VirtualFileSystem.cpp
According to Linux man pages, rename shouldn't succeed if newpath is a
non-empty directory.
> VirtualFileSystem: Don't let rename() overwrite non-empty directory

- Base/res/html/misc/welcome.html
Previously, it was a big list of test pages in no particular order, and
it was hard to find anything. This commit breaks it up into sections,
and renames some of the links to be more consistent.
The categories are slightly arbitrary, and I'm sure everyone will have a
different opinion on what they should be, and which links should go
where. But hopefully we can all agree that this is an improvement!
This also wraps the list into multiple columns on browsers that support
it, which unfortunately does NOT include Browser. :^( But hey, once we
do it'll be good!
> Base: Organize welcome.html

- Documentation/CLionConfiguration.md
I've been struggling with following these docs a bit on macOS, so here's a paragraph that would help me-1-day-ago 🙃
> Documentation: Make docs for CLionConfiguration more understandable

- Userland/Utilities/arp.cpp
**Utilities: Add pledge and unveil protections in arp**
**Utilities: Improve the arp information output**
This updates the arp command to use output styles similar to other
utilities.
> Utilities: Improve arp command output 

- Userland/Games/Solitaire/Game.cpp
- Userland/Games/Spider/Game.cpp
> Spider+Solitaire: Clear selection when starting new game

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.getISOFields.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toInstant.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toPlainDate.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toPlainDateTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toPlainTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.valueOf.js
> LibJS: Implement more of ZonedDateTime

- Userland/Applications/Browser/BrowserWindow.cpp
- Userland/Applications/Browser/Tab.cpp
- Userland/Applications/Browser/Tab.h
- Userland/Libraries/LibGUI/TabWidget.cpp
- Userland/Libraries/LibGUI/TabWidget.h
Add more tab options to the browser: "Duplicate Tab" and "Close Other Tabs".
> Browser+LibGUI: Add more tab options

- Kernel/API/Syscall.h
- Kernel/Process.h
- Kernel/Syscalls/beep.cpp
- Kernel/Syscalls/clock.cpp
- Kernel/Syscalls/debug.cpp
- Kernel/Syscalls/execve.cpp
- Kernel/Syscalls/fork.cpp
- Kernel/Syscalls/get_stack_bounds.cpp
- Kernel/Syscalls/getrandom.cpp
- Kernel/Syscalls/keymap.cpp
- Kernel/Syscalls/pledge.cpp
- Kernel/Syscalls/sysconf.cpp
- Kernel/kprintf.cpp
This continues the great work done by @bgianfo in #8864.
> Kernel: Continue breaking up the big process lock

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.add.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.subtract.js
Ticks two checkboxes in #8982.
> LibJS: Implement Temporal.Instant.prototype.{add,subtract}()

- Userland/Services/LaunchServer/Launcher.cpp
This lets us launch proper handler application for symlinks :^)
> LaunchServer: Resolve symlinks when querying for handler application

- Userland/Services/LaunchServer/Launcher.cpp
> LaunchServer: Make sure launching absolute symlinks works

- Userland/Services/SystemServer/main.cpp
> SystemServer: Change group ownership on all framebuffer devices 

- Kernel/FileSystem/FIFO.cpp
Previously, non-blocking read operations on pipes returned EOF instead of EAGAIN and non-blocking write operations blocked. This fixes pkgsrc's bmake "eof on job pipe!" error message when running in non-compatibility mode.
> Kernel: Properly handle non-blocking I/O on pipes

- Userland/DevTools/Profiler/DisassemblyModel.cpp
Previously the view would've cut off at the last instruction that was
hit in the profile, which is not the right behaviour for functions.
> Profiler: Disassemble the entire function if the symbol is a function

- AK/String.cpp
- AK/String.h
- Userland/Utilities/tr.cpp
It's not quite POSIX-compliant, but hopefully it's enough to tame pkgsrc's bootstrap script infrastructure.
> Userland: Improve tr implementation

- Base/etc/passwd
- Documentation/RunningTests.md
- Ports/gcc/package.sh
- Ports/mawk/package.sh
- Userland/Applications/Terminal/main.cpp
- Userland/DevTools/HackStudio/main.cpp
- Userland/Libraries/LibC/CMakeLists.txt
- Userland/Libraries/LibC/regex.cpp
- Userland/Services/TelnetServer/main.cpp
- Userland/Shell/Shell.cpp
A whole bunch of various small things blocking pkgsrc and not warranting a dedicated PR for each.
> Userland: Various POSIX/environment issues

- Userland/Utilities/grep.cpp
> Utilities: Add option to control when to use colored output for grep

- Documentation/Kernel/ProcFSIndexing.md
- Kernel/FileSystem/FileDescription.cpp
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/ProcFS.h
- Kernel/GlobalProcessExposed.cpp
- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/ProcessExposed.cpp
- Kernel/ProcessExposed.h
- Kernel/ProcessSpecificExposed.cpp
- Kernel/Syscalls/disown.cpp
- Kernel/Syscalls/execve.cpp
- Kernel/Syscalls/exit.cpp
- Kernel/Syscalls/fork.cpp
- Kernel/Syscalls/getuid.cpp
- Kernel/Syscalls/pledge.cpp
- Kernel/Syscalls/process.cpp
- Kernel/Syscalls/setpgid.cpp
- Kernel/Syscalls/setuid.cpp
- Kernel/Syscalls/umask.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
- Kernel/UnixTypes.h
- Userland/Libraries/LibC/dirent.cpp
- Userland/Libraries/LibC/sys/types.h
- Userland/Utilities/ls.cpp
- Userland/Utilities/stat.cpp
> Kernel: Steer away from heap-allocations in the ProcFS

- AK/StdLibExtraDetails.h
- AK/Variant.h
- Meta/generate-libwasm-spec-test.py
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
- Userland/Libraries/LibWasm/AbstractMachine/Configuration.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Configuration.h
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
Profiler/UE stuff split into #9319.
What remains here (as of editing) is the Wasm stuff, which ends up giving some perf improvements, a bunch of correctness fixes, and huge readability improvements :)
> LibWasm: Bunch of Performance and Niceness (tm) improvements

- Userland/Services/SystemServer/main.cpp
Relies on #9232 to be merged first.
> SystemServer: Ensure we change group ownership on all TTY device nodes

- Base/res/devel/templates/cpp-basic.postcreate
- Base/res/devel/templates/cpp-gui.postcreate
- Base/res/devel/templates/cpp-library.postcreate
- Userland/Shell/Parser.cpp
- Userland/Shell/Parser.h
Includes a bonus Shell bugfix.
> Base: Convert postcreate scripts to use heredoc

- Userland/Libraries/LibC/signal.cpp
- Userland/Libraries/LibC/unistd.cpp
- Userland/Libraries/LibC/unistd.h
> LibC: Implement sigsuspend, pause

- Meta/build-image-qemu.sh
Having lots of small files in Base/ may require more inodes in the ext2 filesystem than the format utility sets aside by default. Let's make a more educated guess since we have a rough idea of how many inodes we need by counting files and directories.
> Meta: Better disk size/inode count defaults for QEMU image

- Ports/neofetch/patches/add-serenity-support.patch
- Userland/Libraries/LibCore/ArgsParser.cpp
- Userland/Libraries/LibCore/ArgsParser.h
Before:
After:
(Look at the "Shell" line.)
> Make `neofetch` output look better.

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/Temporal.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.month.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.@@toStringTag.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.calendar.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.day.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.getISOFields.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.monthCode.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.valueOf.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.js
> LibJS: Start implementing Temporal.PlainMonthDay 

- Kernel/Process.cpp
Once we remove the process from the process list, we're free to do
whatever we want without any locks.
> Kernel: Don't hold the process list lock while destructing the process

- README.md
> Meta: Add sin-ack to the contributors list :^)

- Kernel/Net/Routing.cpp
Previously when trying to debug the system's routing, the ARP
information would clutter the output and make it difficult to focus on
the routing decisions. It would be better to specify these
debug messages under ARP_DEBUG.
> Kernel: Move ARP debug information to ARP_DEBUG

- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.fields.js
Ticks one checkbox in #8982, and fixes one test262 test.
> LibJS: Implement Temporal.Calendar.prototype.fields()

- Userland/Utilities/pls.cpp
Commands may be executed as a specific user by passing the user's UID to the '-u' flag in pls.
> Userland: Add as-user execution to the pls utility

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.mergeFields.js
Ticks one checkbox in #8982, and fixes one test262 test.
> LibJS: Implement Temporal.Calendar.prototype.mergeFields()

- Userland/Libraries/LibCore/File.cpp
- Userland/Libraries/LibCore/File.h
- Userland/Utilities/cp.cpp
- Userland/Utilities/ls.cpp
> Userland: Improve POSIX compliance of ls, cp

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Calendar.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.toString.js
> LibJS: Implement Temporal.PlainDate.prototype.toString()

- Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.toJSON.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.toLocaleString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.toString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.toJSON.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.toLocaleString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.toString.js
> LibJS: Implement Temporal.Plain{YearMonth,MonthDay}.prototype.to{String,LocaleString,JSON}()

- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Runtime/PromiseAllResolveElementFunction.cpp
- Userland/Libraries/LibJS/Runtime/PromiseAllResolveElementFunction.h
- Userland/Libraries/LibJS/Runtime/PromiseConstructor.cpp
- Userland/Libraries/LibJS/Runtime/PromiseReaction.cpp
- Userland/Libraries/LibJS/Tests/builtins/Promise/Promise.all.js
:smile: 
```
test/built-ins/Promise/all    96/96    (100.00%) [ ✅ 96 ] 
```
> LibJS: Implement Promise.all

- Userland/Utilities/gzip.cpp
This option specifies that we should perform decompression instead of compression.
We use it in the build process to extract the PCI & USB databases.
cc @IdanHo
> Utilities: Add -d option to gzip

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimeConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimeConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.from.js
Fixes one bug and ticks one checkbox in #8982.
> LibJS: Implement Temporal.PlainDateTime.from()

- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.toPlainMonthDay.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.toPlainYearMonth.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toPlainMonthDay.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.toPlainYearMonth.js
Ticks four checkboxes in #8982.
> LibJS: Implement Temporal.{Plain,Zoned}DateTime.prototype.toPlain{YearMonth,MonthDay}()

- Kernel/CMakeLists.txt
- Kernel/Prekernel/CMakeLists.txt
- Kernel/VirtualAddress.h
I've started working on my KASAN support again, and needed these changes. 
I'm sending them to master now to keep my KASAN WIP branch as small as possible. 
Minor progress towards #5351
> CMake+Kernel: Minor improvements which KASAN WIP depends upon

- Userland/Libraries/LibJS/Heap/Heap.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.h
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/Object.h
This provides a ~30% (on my Linux host, a bit more on Serenity) performance improvement during global object initialization.
> LibJS: Optimize global object construction time

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.dateAdd.js
> LibJS: Implement Temporal.Calendar.prototype.dateAdd()

- Userland/DevTools/Profiler/CMakeLists.txt
- Userland/DevTools/Profiler/FlameGraphView.cpp
- Userland/DevTools/Profiler/FlameGraphView.h
- Userland/DevTools/Profiler/main.cpp
- Userland/Libraries/LibGfx/Color.h
https://user-images.githubusercontent.com/275397/131128822-2b493964-1eb5-4500-b120-3f0c43fb9a9a.mp4
The flamegraph makes it easier to quickly spot expensive functions,
based on the width of their bar.
> Profiler: Add a flamegraph view for the stack.

- Userland/Libraries/LibGUI/TabWidget.cpp
> LibGUI: Tab bar text/focus rect alignment improvements redux

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.h
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZonePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toJSON.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toLocaleString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toString.js
Big <img src="https://cdn.discordapp.com/emojis/855017260779438091.png" height="20">. Ticks three checkboxes in #8982.
> LibJS: Implement Temporal.Instant.prototype.to{String,LocaleString,JSON}()

- Userland/Applications/SoundPlayer/main.cpp
Removed the old custom checkbox selection code in the Visualization
menu and replaced them with GUI::ActionGroup with set_exclusive
enabled instead :^)
> SoundPlayer: Use GUI::ActionGroup for Visualization menu

- Userland/Libraries/LibGUI/ComboBox.cpp
- Userland/Libraries/LibGUI/Scrollbar.cpp
- Userland/Libraries/LibGUI/SpinBox.cpp
> LibGUI: Caps, nice and Thicc

- Userland/Applications/PixelPaint/PaletteWidget.cpp
- Userland/Applications/PixelPaint/PaletteWidget.h
Found some behaviour really annoying while trying to use PixelPaint to create some graphics, so I fixed it :^) I think it feels much better this way, but please let me know if there's any suggestions.
The commit messages describe the behaviour changes.
> PixelPaint: Change palette color selection behavior

- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Tests/operators/modulo-basic.js
> LibJS: Handle +Infinity, -Infinity, +0 and -0 in modulo operator

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.with.js
Once again not all of them affect us as a bunch of stuff isn't implemented in LibJS yet - turns out that's mostly stuff that still needed spec fixes. Lucky us :^)
> LibJS: More normative Temporal spec changes

- Userland/Libraries/LibSyntax/Highlighter.cpp
> LibSyntax: Fix bug in matching cursor highlighting

- Meta/Lagom/Tools/CodeGenerators/LibWeb/WrapperGenerator.cpp
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl
- Userland/Libraries/LibWeb/Tests/HTML/HTMLScriptElement.supports.js
LibWeb: Add support for IDL static functions
-----
LibWeb: Add support HTMLScriptElement.supports
See https://github.com/whatwg/html/commit/33ff054a6caa014f4cce2912c93a19547a2e2717
> LibWeb: Add support for IDL static functions and HTMLScriptElement.supports

- Userland/Applications/Piano/RollWidget.cpp
> Piano: Draw note names on top of notes

- Userland/Applications/Piano/ProcessorParameterSlider.cpp
> Piano: Format slider values when initially set

- Userland/Applications/PixelPaint/Image.cpp
- Userland/Applications/PixelPaint/Image.h
- Userland/Applications/PixelPaint/RectangleTool.cpp
- Userland/Applications/PixelPaint/RectangleTool.h
- Userland/Applications/PixelPaint/main.cpp
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/Painter.h
Making a separate PR for each one of the relatively concise commits was feeling a bit much, so I'm grouping a few together here. Probably a bit easier since there's less context switching when reviewing as there would be with multiple PRs?
In any case, if you'd like me to break these up separately please let me know! The commit messages describe the different changes.
> PixelPaint+LibGfx: Miscellaneous additions

- Userland/Applications/PDFViewer/CMakeLists.txt
- Userland/Applications/PDFViewer/PDFViewerWidget.cpp
- Userland/Applications/PDFViewer/PDFViewerWidget.h
- Userland/Applications/PDFViewer/main.cpp
Not much else to say here, just updating the applications to use the newest libraries :^)
> PDFViewer: Use FileSystemAccessClient to open files

- Userland/Applications/PixelPaint/FilterParams.h
- Userland/Applications/PixelPaint/main.cpp
- Userland/Libraries/LibGfx/Filters/InvertFilter.h
I followed #9621 's steps to implement  a "Invert" filter in PixelPaint.
> PixelPaint: Add invert filter

- Userland/Utilities/grep.cpp
Previously, the recursive flag always searched for file contents from the current directory, ignoring the path argument entirely.
> Utilities: Support grepping recursively from paths in the argument

- Userland/Libraries/LibJS/Runtime/Array.h
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Intl/DisplayNamesConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DisplayNamesConstructor.h
- Userland/Libraries/LibJS/Tests/builtins/Intl/DisplayNames/DisplayNames.supportedLocalesOf.js
> LibJS: Implement Intl.DisplayNames.supportedLocalesOf()

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/Constants.h
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyObject.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyTableConstructor.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyTableConstructor.h
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyTableObject.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyTableObject.h
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyTablePrototype.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssemblyTablePrototype.h
Currently impl'd:
- `WebAssembly.Table`
TODO:
> LibWeb+LibWasm: Some more JS API

- Userland/Libraries/LibC/cxxabi.cpp
In 553361d we started mprotecting the atexit handlers when they are not
being modified or executed. As part of that commit, we unintentionally
changed the max number of global destructors from 1024 to 256 (on x86,
only 128 on x86_64). This patch expands the initial size of the global
destructors page to 2 pages from 1, and allows the pool to be expanded
at runtime by mapping a new set of pages and copying the AtExitEntries
over.
Fixes #9094
Supersedes #9096
> LibC: Expand region for global destructors when it reaches capacity

- Userland/Libraries/LibWeb/DOM/CharacterData.idl
See https://dom.spec.whatwg.org/#characterdata
> LibWeb: Add [LegacyNullToEmptyString] to CharacterData.data

- Userland/Libraries/LibJS/Lexer.cpp
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Tests/parser-line-terminators.js
- Userland/Libraries/LibJS/Token.cpp
- Userland/Libraries/LibJS/Token.h
And some small cleanup because those two constructors are way too similar for me.
> LibJS: Fix small issue with windows style line endings

- Kernel/Prekernel/Arch/aarch64/boot.S
- Kernel/Prekernel/Arch/aarch64/init.cpp
- Kernel/Prekernel/CMakeLists.txt
- Meta/run.sh
Originally wanted to make this a bit bigger, but have to run a surprise errand instead.
> Let aarch64 port call into C++

- Meta/debug-kernel.sh
- Meta/serenity.sh
- Toolchain/BuildIt.sh
- Toolchain/Patches/gdb.patch
This is pretty useful when working on the aarch64 port.
> Toolchain: Build aarch64-gdb for cross-debugging on x86

- Userland/Applications/PixelPaint/EllipseTool.cpp
- Userland/Applications/PixelPaint/EllipseTool.h
- Userland/Applications/PixelPaint/ImageEditor.cpp
- Userland/Applications/PixelPaint/LineTool.cpp
- Userland/Applications/PixelPaint/MainWidget.cpp
- Userland/Applications/PixelPaint/RectangleTool.cpp
- Userland/Applications/PixelPaint/RectangleTool.h
Just polishing up some things that were not behaving as expected, each of the individual commits contain details on what's changed.
> PixelPaint: Miscellaneous fixes

- Kernel/MiniStdLib.cpp
- Kernel/Prekernel/CMakeLists.txt
- Kernel/Prekernel/UBSanitizer.cpp
This pulls the first few parts of AK and Kernel headers into the aarch64 build :^)
> Build MiniStdLib and deps in aarch64 builds

- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Temporal/CalendarPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.h
- Userland/Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.dateAdd.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Calendar/Calendar.prototype.fields.js
There's more, and I don't want to make tons of small PRs, so I'll draft this for now and accumulate more changes.
> LibJS: Even more normative Temporal spec changes

- Userland/Libraries/LibJS/Runtime/ErrorTypes.h
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.with.js
Ticks off one box in #8982 and fixes one test262 case.
> LibJS: Implement Temporal.PlainTime.prototype.with

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDate.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTime.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainTimePrototype.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.toJSON.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.toLocaleString.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainTime/PlainTime.prototype.toString.js
Ticks three checkboxes in #8982.
> LibJS: Implement Temporal.PlainTime.prototype.to{String,LocaleString,JSON}()

- Userland/Libraries/LibGUI/FilePicker.cpp
The existing behaviour is that filename_textbox is cleared if a node of
the wrong type is selected. Here we reflect that state update in the
state of the ok_button.
This change helps the user to avoid confirming (and seeing an alert) if
they press "Open" after clicking on an invalid node.
> LibGUI: Disable Open/Save button in FilePicker when nothing is selected

- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/Temporal/Instant.h
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/InstantPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toZonedDateTime.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Instant/Instant.prototype.toZonedDateTimeISO.js
> LibJS: Implement Temporal.Instant.prototype.toZonedDateTime{,ISO}()

- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonth.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.compare.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.equals.js
Ticks three checkboxes in #8982
> LibJS: Implement ToTemporalYearMonth AO and three PlainYearMonth methods that use it

- Ports/openssl/package.sh
> Ports: Disable IPV6 in OpenSSL

- Userland/Libraries/LibDebug/DebugSession.cpp
Linking with `-z separate-code` broke the way we parsed the libraries of the debugee process, and this PR fixes it.
> LibDebug: Use the first memory segment of a library as the ELF's base

- Userland/Services/WindowServer/Window.cpp
- Userland/Services/WindowServer/Window.h
- Userland/Services/WindowServer/WindowManager.cpp
This fixes #9933 and some dead code I accidentally left over.
Thanks, @Maato!
> WindowServer: Fix 'sticky' mouse after resize

- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDay.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayConstructor.h
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.equals.js
This ticks off two checkboxes in #8982
> LibJS: Implement ToTemporalMonthDay AO and the two methods that use it

- Userland/Applications/TextEditor/MainWidget.cpp
- Userland/Applications/TextEditor/MainWidget.h
- Userland/Libraries/LibGUI/TextEditor.cpp
- Userland/Libraries/LibGUI/TextEditor.h
> LibGUI+TextEditor: Allow cursor line highlighting to be toggled

- Kernel/API/Syscall.h
- Kernel/CMakeLists.txt
- Kernel/FileSystem/File.h
- Kernel/FileSystem/FileSystem.cpp
- Kernel/FileSystem/Inode.cpp
- Kernel/FileSystem/Inode.h
- Kernel/FileSystem/InodeFile.cpp
- Kernel/FileSystem/InodeFile.h
- Kernel/FileSystem/OpenFileDescription.cpp
- Kernel/FileSystem/OpenFileDescription.h
- Kernel/Process.h
- Kernel/Syscalls/fsync.cpp
- Userland/Libraries/LibC/unistd.cpp
This is my first time contributing to the FileSystem subsystem in the kernel, so any suggestions are greatly appreciated.
> Kernel+LibC: Implement fsync

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.h
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Forward.h
- Userland/Libraries/LibJS/Interpreter.cpp
- Userland/Libraries/LibJS/Interpreter.h
- Userland/Libraries/LibJS/Runtime/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Userland/Libraries/LibJS/Runtime/FunctionObject.h
- Userland/Libraries/LibJS/Runtime/GlobalEnvironment.cpp
- Userland/Libraries/LibJS/Runtime/GlobalEnvironment.h
- Userland/Libraries/LibJS/Runtime/GlobalObject.cpp
- Userland/Libraries/LibJS/Runtime/GlobalObject.h
- Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
- Userland/Libraries/LibJS/Runtime/NativeFunction.h
- Userland/Libraries/LibJS/Runtime/OrdinaryFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/OrdinaryFunctionObject.h
- Userland/Libraries/LibJS/Runtime/Realm.cpp
- Userland/Libraries/LibJS/Runtime/Realm.h
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibTest/JavaScriptTestRunner.h
- Userland/Utilities/js.cpp
Accompanying test262 runner change: https://github.com/linusg/libjs-test262/pull/36
> LibJS: Introduce Realms

- Userland/Applications/PixelPaint/ImageEditor.cpp
This patch fixes the behavior of zooming. Now the cursor stays over the same spot in the image when zooming.
I have a headache now, offset math with about 4 different origins is hard...
This fixes #9900
> PixelPaint: Fix zooming to cursor

- Userland/Libraries/LibWeb/CSS/ComputedCSSStyleDeclaration.cpp
After watching Andreas' video, I took the very relaxing task upon me to implement a whole bunch of other declarations.
Those aren't all the Declarations there are and only the easy ones, but very relaxing and a step forward. Sometimes doing repetitive tasks is just soothing :^)
> LibWeb: Add support for a bunch of ComputedCSSStyleDeclarations
