- Userland/uptime.cpp
Just like the -p option on linux
> Uptime: making the ouput prettier

- Userland/Makefile
The makefile does't need new apps to be added manually.
It's magic :D
> Userland: making the makefile smarter

- Userland/killall.cpp
I implemented the killall command according to the issue #27.
> Added killall command

- Kernel/makeall.sh
- ReadMe.md
Just since I was looking at the script. Also updated the README with the stuff I missed.
> Some improvements to the build process

- LibGUI/GTextEditor.cpp
- LibGUI/GTextEditor.h
- Servers/WindowServer/WSWindowManager.cpp
Along the way, fix up a small bug in double click support that resulted in repeated delivery.
> Introduce triple click to select to GTextEditor

- LibC/arpa/inet.h
- LibC/string.cpp
- LibC/string.h
- LibC/sys/socket.h
- LibC/time.h
Just a few portability improvements from trying to compile some external code. Note that I haven't actually validated them on anything at runtime, since there were some other deeper (more scary) problems like missing dlfcn.h.
> LibC: Portability improvements

- Servers/WindowServer/WSWindowManager.cpp
This contains more stuff, and is easier to add to since it's just a vector :)
> WindowServer: Add a more dynamic app list

- Servers/WindowServer/WSEventLoop.cpp
> WSEventLoop: Don't assert when being told to construct a crazy window type

- Applications/TextEditor/main.cpp
- LibGUI/GFilePicker.cpp
- LibGUI/GFilePicker.h
(the commit history got a bit weird)
> Dont return string paths

- Userland/ls.cpp
Still needs some clean up & support for list mode
> Ls: Add single file and multiple path support

- Ports/.bash-serenity-disable-locale.patch
- Ports/.bash-serenity-include-stdio.patch
- Ports/.bash-serenity-system.patch
- Ports/.port_include.sh
- Ports/bash.sh
Doesn't link successfully, and I currently have no idea why...
> WIP: bash port

- .travis.yml
- ReadMe.md
This will let us know how builds go when it's set up.
> Meta: Add .travis.yml

- Ports/less/less.sh
This is a very simple port of less. I needed it as part of solving #136 (working on it at #140), and thought I'd make a PR for it as well.
> Port: less

- LibC/stdio.h
- LibM/math.cpp
- LibM/math.h
- Ports/lua/.gitignore
- Ports/lua/lua.patch
- Ports/lua/lua.sh
Finally ported Lua. It kinda works but Serenity's terminal handling a bit weird.Needs more debugging.
> Add Lua port. 

- AK/AKString.h
- AK/BufferStream.h
- AK/FileSystemPath.cpp
- AK/FileSystemPath.h
- AK/String.cpp
- AK/StringBuilder.cpp
- AK/StringBuilder.h
- AK/StringView.cpp
- AK/StringView.h
- Applications/FileManager/DirectoryView.cpp
- Applications/FileManager/DirectoryView.h
- Applications/FileManager/main.cpp
- Kernel/Process.cpp
- LibCore/CDirIterator.cpp
- LibCore/CDirIterator.h
- LibCore/CFile.cpp
- LibCore/CFile.h
- LibCore/CIODevice.h
- Servers/LookupServer/main.cpp
- Userland/dmesg.cpp
- Userland/mm.cpp
- Userland/ps.cpp
- Userland/sysctl.cpp
Haven't tested after rebase, as I don't have grub-install working.
> Use more LibCore in Userland, and sprinkle some StringView love

- Userland/.gitignore
- Userland/rm.cpp
Solves #161, by adding an option to recursively remove directories (and the files inside them).
> Userland: Implement recursive `rm`

- Applications/Terminal/Terminal.cpp
- Applications/Terminal/Terminal.h
- Applications/Terminal/main.cpp
- Kernel/.gitignore
- LibC/unistd.h
Working on fixing the scrolling and drawing abilities of the Terminal app, so that Vim works properly within it.
> Terminal: Implement Scroll Regions & Scrolling Properly

- Userland/tail.cpp
Addresses #208.
Default tail to 10 lines if -n not specified.
> Default tail behavior with no arguments

- AK/String.cpp
- AK/StringView.cpp
- AK/StringView.h
- Kernel/FileSystem/VirtualFileSystem.cpp
- Kernel/KResult.h
- Shell/main.cpp
Fix/implement better globbing in the shell:
Plus a bunch of fixes needed for this to work.
> Shell: Implement more advanced globbing

- LibC/stdio.cpp
- LibC/stdio.h
- Userland/wc.cpp
Added an implementation of wc to fix #159. Uses STL rather than C style functions (ifstream rather than FILE*, cout rather than printf, iterators, etc.)
Uses https://www.gnu.org/software/cflow/manual/html_node/Source-of-wc-command.html as inspiration
> Add wc program

- Kernel/FileSystem/ProcFS.cpp
- Kernel/run
- Servers/SystemServer/main.cpp
Right now, this just waits a while and shuts down.
> Add a testmode to init

- Applications/PaintBrush/BucketTool.cpp
- Applications/PaintBrush/BucketTool.h
- Applications/PaintBrush/Makefile
- Applications/PaintBrush/PaintableWidget.cpp
- Applications/PaintBrush/PaintableWidget.h
- Applications/PaintBrush/PenTool.cpp
- Applications/PaintBrush/PenTool.h
- Applications/PaintBrush/SprayTool.cpp
- Applications/PaintBrush/SprayTool.h
- Applications/PaintBrush/Tool.h
- Applications/PaintBrush/ToolboxWidget.cpp
Could do with some more tweaking no doubt, and it'd be nice to have a
circular spray, but this is better than nothing.
> Add a simple spray fill tool

- Shell/main.cpp
Added a history file for the Shell, which fixes #174. Saves every executed command to the file, loads the last n capacity commands into the history buffer for each new shell (seeking from near the end of the file). File is saved to /home/[user]/.history
> Add ~/.history file for Shell

- LibM/math.cpp
I made some mistakes the first time I implemented this, now that we have an application that uses these functions I was able to figure out the bug
> LibM: Switch sin() for fast sin()

- Applications/About/Makefile
- Applications/Downloader/Makefile
- Applications/FileManager/Makefile
- Applications/FontEditor/Makefile
- Applications/IRCClient/Makefile
- Applications/Launcher/Makefile
- Applications/Makefile.common
- Applications/PaintBrush/Makefile
- Applications/ProcessManager/Makefile
- Applications/QuickShow/Makefile
- Applications/Taskbar/Makefile
- Applications/Terminal/Makefile
- Applications/TextEditor/Makefile
Further consolidation is of course possible, eg the Games/ programs
follow the rules.
> Move common Application build steps into their own Makefile.common

- Applications/PaintBrush/EraseTool.cpp
- Applications/PaintBrush/EraseTool.h
- Applications/PaintBrush/Makefile
- Applications/PaintBrush/SprayTool.cpp
- Applications/PaintBrush/SprayTool.h
- Applications/PaintBrush/ToolboxWidget.cpp
New erase tool (that just does a rect fill of white), and a size context menu for spray tool.
> Some small additions to PaintBrush

- Userland/id.cpp
Added simple flags for the id command in issue #158
> Added flags to id command #158

- Games/Minesweeper/Field.cpp
- Games/Minesweeper/Field.h
- Games/Minesweeper/main.cpp
- LibCore/CConfigFile.cpp
Not too big a deal, though I'm not sure where it's at with code style or whether refactoring the configuration code was the right thing to do.
> Minesweeper: Allow single-click chording and refactor some configuration code

- Applications/Launcher/main.cpp
- Base/home/anon/Launcher.ini
> Launcher can now be vertical or horizontal

- Applications/Launcher/main.cpp
- Base/home/anon/Launcher.ini
Fixes a bug in PR 267, brought up in #258.
> Launcher: Bugfix in reading config

- AK/AKString.h
- AK/Tests/TestString.cpp
> AKString: add missing comparison operators

- Userland/chmod.cpp
Added understanding of simple permission strings like `chmod u+x file`, `chmod u=rwx,g+x,o=rw file`, `chmod +r file`, etc for issue #162.
> Userland: "chmod": add understanding of simple permission strings.

- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/TextEditorWidget.h
- Libraries/LibGUI/GFilePicker.cpp
- Libraries/LibGUI/GFilePicker.h
No more saving to a temp file. Though I'm not sure if I handled the error codes properly.
> TextEditorWidget: Added improved save feature. Fixes #282

- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/main.cpp
- Libraries/LibGUI/GFilePicker.cpp
Looking back at my pull requests I made some oversights, wanted to fix these. If there is any problem just close the request, I don't want to waste your time.
> TextEditor & FilePicker: Quality of life fixes.

- AK/BufferStream.h
This will be required in AudioServer
> BufferStream: Add signed int overloads for read/write

- Kernel/Process.cpp
Rather than limiting it to two shared processes, store a Vector of
references, so we can add more if we want. Makes the code a little
more generic.
No actual change to the syscall interface yet, so nothing takes
advantage of this yet.
> Kernel: SharedBuffer sharing cleanup

- Kernel/Makefile
- Kernel/Process.cpp
- Kernel/SharedBuffer.cpp
- Kernel/SharedBuffer.h
I had a feeling this went too easily, and sure enough it did.
> Fix some bad stuff that I messed up with the SharedBuffer refactoring

- Libraries/LibAudio/ABuffer.h
- Libraries/LibAudio/AClientConnection.cpp
- Libraries/LibAudio/AWavLoader.cpp
- Servers/AudioServer/ASClientConnection.cpp
- Servers/AudioServer/ASMixer.cpp
Just so these don't get lost :)
> AudioServer: Fix review comments

- Kernel/Devices/FloppyDiskDevice.cpp
- Kernel/Devices/FloppyDiskDevice.h
- Kernel/Makefile
- Kernel/init.cpp
@awesomekling @rburchell Don't merge this yet, it's still under development. I thought I'd open the PR anyways so that I can at least get a bit of feedback on the code I have so far (and not get beaten to implementing it. I'm looking at you @rburchell with your SB16 driver goddamnit :P)
Currently very much WIP, the datasheet (https://wiki.qemu.org/images/f/f0/29047403.pdf) is 70+ pages long (including the timing diagrams) so it's a bit to get chew through. Let me know if there's anything I need to change as I add stuff into the PR :P
> Initial FDC Device Driver

- Applications/TextEditor/main.cpp
Missed this when fixing the mess I made previously. Whoops :P
> TextEditor: Show window icon

- Applications/ProcessManager/ProcessModel.cpp
- Applications/ProcessManager/ProcessModel.h
- Kernel/FileSystem/ProcFS.cpp
- Libraries/LibCore/CProcessStatisticsReader.cpp
- Libraries/LibCore/CProcessStatisticsReader.h
- Servers/WindowServer/WSCPUMonitor.cpp
- Userland/ps.cpp
- Userland/top.cpp
ps: Widen state field to fit "Condition" and other fields
ps: Port to using CProcessStatisticsReader and /proc/all
CProcessStatisticsReader: Be consistent about terminology from the kernel down
> Improvements to ps

- Kernel/Process.cpp
- Kernel/Scheduler.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
Rather than asserting, which really ruins everyone's day.
> Kernel: Add a new block state for accept() on a blocking socket

- Libraries/LibAudio/AWavLoader.cpp
Fixes #333
I'm not totally sure I'm doing this in the best possible way, but at least my reference 24bit file makes noise that sounds reasonable.
> AWavLoader: Support 24 bit wav files (mono & stereo)

- Kernel/Devices/SB16.cpp
- Kernel/FileSystem/ProcFS.cpp
- Kernel/Net/IPv4Socket.cpp
- Kernel/Net/NetworkTask.cpp
- Kernel/Net/TCPSocket.cpp
- Kernel/Process.cpp
- Kernel/Scheduler.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
- Kernel/init.cpp
Make blocking a little nicer to extend/understand :)
> Scheduler blocking cleanup

- Kernel/Process.cpp
- Libraries/LibCore/CEventLoop.cpp
- Libraries/LibCore/CIODevice.cpp
- Libraries/LibCore/CSyscallUtils.h
- Libraries/LibCore/CoreIPCClient.h
- Servers/LookupServer/main.cpp
We added EINTR to select/poll. This is good, although it wasn't quite perfect. Few fixes to that.
In addition, userspace now re-calls select() on EINTR.
Fixes #353, and probably #348 too.
> Fix EINTR handling in userspace

- AK/FileSystemPath.cpp
- AK/FileSystemPath.h
- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/TextEditorWidget.h
- Libraries/LibGUI/GFilePicker.cpp
- Libraries/LibGUI/GFilePicker.h
I dunno if I should have separated the CFile stuff into a separate commit.
> TextEditor: SaveAs Tweaks

- Libraries/LibGUI/GFilePicker.cpp
- Libraries/LibGUI/GFilePicker.h
> GFilePicker: Edit file name on opening window

- ReadMe.md
Thanks to WSL2, SerenityOS can be worked on on Windows.
> Added instructions for WSL in the README.

- Libraries/LibGUI/GWindow.cpp
- Libraries/LibGUI/GWindow.h
Fixes #330. Not sure if this is what you had in mind :thinking:
> LibGUI: Allow setting window icon before show().

- Applications/Piano/Music.h
- Applications/Piano/PianoWidget.cpp
- Applications/Piano/PianoWidget.h
> Piano: Add mouse support for playing notes

- Libraries/LibCore/CSocketAddress.h
- Libraries/LibCore/CTCPServer.cpp
- Libraries/LibCore/CTCPServer.h
- Libraries/LibCore/CTCPSocket.cpp
- Libraries/LibCore/CTCPSocket.h
- Libraries/LibCore/Makefile
This is pretty much a find/replace copy of CLocalServer, and some
modifications to CTCPSocket and CSocketAddress to support it.
> LibCore: Add CTCPServer

- Kernel/Devices/PATAChannel.cpp
Apparently we need to poll the drive for its status after each sector we
read if we're not doing DMA. Previously we only did it at the start, which
resulted in every sector after the first in a batch having 12 bytes of
garbage on the end. This manifested as silent read corruption.
Bonus content: cleaner logs!
> Kernel: Fix PATA reads without DMA

- Kernel/Devices/PATAChannel.cpp
Our logic for using the ATA_CMD_CACHE_FLUSH functionality was a bit wrong,
and now it's better.
The ATA spec says these two things:
> The device shall enter the interrupt pending state when:
> 1) any command except a PIO data-in command reaches command completion
>    successfully;
> ...
> The device shall exit the interrupt pending state when:
> 1) the device is selected, BSY is cleared to zero, and the Status
>		 register is read;
This means that our sequence of actions was probably never going to work.
We were waiting in a loop checking the status register until it left the
busy state, _then_ waiting for an interrupt. Unfortunately by checking the
status register, we were _clearing_ the interrupt we were about to wait
for.
Now we just wait for the interrupt - we don't poll the status …
> Kernel: Fix non-DMA writes to IDE drives

- Kernel/FileSystem/ProcFS.cpp
- Kernel/PCI.cpp
- Kernel/PCI.h
- Userland/lspci.cpp
This adds a basic lspci command, and converts /proc/pci to JSON.
> Userland: Implement simple lspci command

- Applications/SystemMonitor/DevicesModel.cpp
- Applications/SystemMonitor/DevicesModel.h
- Applications/SystemMonitor/Makefile
- Applications/SystemMonitor/main.cpp
- Kernel/Devices/Device.cpp
- Kernel/Devices/Device.h
- Kernel/FileSystem/DevPtsFS.cpp
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
- Kernel/FileSystem/VirtualFileSystem.h
- Kernel/Process.cpp
> /proc/devices & devices tab

- Userland/cut.cpp
**After the failure the last pull request was, I opened a new one and I added the cut.cpp file with a single commit.**
The current version supports only the -b list option for a single file.
Ranges are also supported.
> Userland: Implemented a simple cut command.

- Libraries/LibGUI/GTextEditor.cpp
Fixed a bug in find_prev and when pressing Key_Right.
Details are in commit messages.
> GTextEditor: Fixed two bugs

- Userland/which.cpp
Added the command to find the location of an executable in the PATH.
Feel free to deny if this functionality already exists somewhere else.
> Created a light version of the 'which' command.

- Applications/Terminal/main.cpp
This allows a user to specify a command to run after opening the terminal
program. By default it will still spawn an interactive shell.
> Terminal: Add -e (execute) command line option

- Libraries/LibGUI/GAction.cpp
- Libraries/LibGUI/GAction.h
I'd like your opinion on how I'm handling custom actions, and also what I'm doing wrong. Also...
Why is m_document_dirty always true in the QuitAction?
How would i properly reference window() in the QuitAction?
I also have a feeling that we should move these custom actions into a new parent class of common actions.
> GAction: Added common actions

- Applications/FileManager/main.cpp
- Applications/IRCClient/IRCAppWindow.cpp
- Applications/PaintBrush/main.cpp
- Applications/Piano/main.cpp
- Applications/QuickShow/main.cpp
- Applications/SystemMonitor/main.cpp
- Applications/Terminal/main.cpp
- Applications/TextEditor/TextEditorWidget.cpp
- DevTools/VisualBuilder/main.cpp
- Games/Minesweeper/main.cpp
- Games/Snake/main.cpp
- Libraries/LibGUI/GTextEditor.cpp
I think we do separate commits like this, not sure. Fixes #388
> Apply common actions to applications

- DevTools/VisualBuilder/VBForm.cpp
- Libraries/LibGUI/GTextEditor.cpp
Fixing some minor stuff I looked over.
> VBForm & TextEditor: Small fixes

- Applications/TextEditor/TextEditorWidget.cpp
It asks if you want to save a dirty file before you create a new one.
[Here's a 53 second youtube video showing that it works.](https://www.youtube.com/watch?v=Cb-eHqIB44s&feature=youtu.be)
> TextEditor: Implemented File/New Action

- Userland/cp.cpp
For recursive copying, I went with an explicit -r switch ala the POSIX standard.
> Userland: Update cp with proper arg parsing and recursive directory copying

- Kernel/build-root-filesystem.sh
- Kernel/makeall.sh
- Servers/TelnetServer/Client.cpp
- Servers/TelnetServer/Client.h
- Servers/TelnetServer/Command.h
- Servers/TelnetServer/Makefile
- Servers/TelnetServer/Parser.cpp
- Servers/TelnetServer/Parser.h
- Servers/TelnetServer/main.cpp
Fixes #407
Depends on #530 to run reliably.
> TelnetServer: Implement basic telnet server

- Kernel/Arch/i386/CPU.cpp
- Kernel/Process.cpp
- Kernel/Scheduler.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
Because of the new way signals are handled some old code is no longer necessary.
> Kernel: remove redundant signal code.

- Userland/wc.cpp
I've been watching your YouTube videos and I felt inspired to do a bit of hacking. I'm new to C++ and my C is a bit rusty, so please don't hesitate to call me out for anything bone headed. :wink: 
I basically just mimicked the code in the `head` program so `wc` can read from `stdin`.
> Add stdin support to wc program

- Shell/main.cpp
...and allow switching back to it with `cd -`
Partially addresses #397
> Shell: Remember previous working dir

- Shell/main.cpp
Fixed a few issues with both `pushd` and `popd`. There was a few
typos etcetera causing it to behave errantly in certain situations.
> Shell: Fixed `pushd` and `popd`

- Applications/DisplayProperties/DisplayProperties.cpp
A few fixes as recommended by @danboid in #556
> DisplayProperties: Auto-resolution and graphical fix

- Kernel/VM/MemoryManager.cpp
- Kernel/VM/PhysicalRegion.cpp
> Kernel: Fix two errors on systems with lots (> ~2GB) of memory

- Kernel/Process.cpp
We now no longer hardcode the sigreturn syscall in
the signal trampoline. Because of the way inline asm inputs
work, I've had to enclose the trampoline in the function
signal_trampoline_dummy.
> Kernel: Stop hardcoding syscall in signal trampoline.

- Kernel/VM/MemoryManager.cpp
We were just blindly trusting that the bootloader would only give us
page-aligned memory regions. This is apparently not always the case,
so now we can try to repair those regions.
Fixes #601
@danboid can you give this a go on the machine from #601? I don't have any hardware to reproduce it right now :)
> Kernel: Repair unaligned regions supplied by the boot loader

- Kernel/FileSystem/Ext2FileSystem.cpp
- Userland/disk_benchmark.cpp
> Kernel: Support writing doubly-indirect ext2 blocks

- Kernel/RTC.cpp
It turns out some BIOS vendors don't support non-BCD date/time mode, but
we were relying on it being available. We no longer do this, but instead
check whether the BIOS claims to provide BCD or regular binary values for
its date/time data.
> Kernel: Fix BIOS date/time on hardware

- Libraries/LibDraw/PNGLoader.cpp
- Implemented support for more PNG formats including 16-bit per channel and 8-bit indexed with palette.
- Made the library a little more resistant to crashes by returning false for known but unsupported formats.
Fixes #584.
> LibDraw: Implemented support for more PNG formats.

- Ports/libexpat/fix-autoconf.patch
- Ports/libexpat/package.sh
port that fetches, configures, builds and installs the expat library
> Add expat port

- Ports/curl/package.sh
- Ports/zlib/package.sh
adds zlib to ports and add dependancy to curl
> Ports: Add zlib port

- Base/home/anon/www/images.html
- Base/home/anon/www/welcome.html
- Libraries/LibHTML/DOM/Document.cpp
- Libraries/LibHTML/DOM/Document.h
- Libraries/LibHTML/DOM/HTMLImageElement.cpp
- Libraries/LibHTML/DOM/HTMLImageElement.h
- Libraries/LibHTML/HtmlView.cpp
- Libraries/LibHTML/Layout/LayoutImage.cpp
> LibHTML: Support width/height attributes on images

- Kernel/Devices/DiskPartition.cpp
- Kernel/Devices/DiskPartition.h
- Kernel/Devices/GPTPartitionTable.cpp
- Kernel/Devices/GPTPartitionTable.h
- Kernel/Devices/MBRPartitionTable.cpp
- Kernel/Devices/MBRPartitionTable.h
- Kernel/Makefile
- Kernel/build-gpt-image-grub.sh
- Kernel/grub_gpt.cfg
- Kernel/init.cpp
Hi,
I talked with AK in the IRC channel about such feature (GPT partition table support).
Now you can choose to generate MBR partitioned disk or GPT partitioned disk.
About block restriction - Block limit definition (variables) is currently not finished. I need to address potential access out of partition boundaries in read_block & write_block methods later. For now I just define a class member but will later provide a solution as needed.
> Partition Table Enhancement: Initial GPT Support, Adding Block Limit

- Kernel/FileSystem/DiskBackedFileSystem.cpp
The Cache entries found in `DiskBackedFileSystem` are now stored in a
`KBuffer` object, instead of relying on `kmalloc_eternal`. The number
of entries was exceeding that of the number of bytes allocated to
`kmalloc_eternal`, which in turn caused `mount()` to fail epically
when called.
> Kernel: Made DiskCache entries a KBuffer

- AK/Atomic.h
- AK/Tests/Makefile
- AK/Tests/TestAtomic.cpp
- Kernel/Lock.cpp
- Kernel/Lock.h
- Libraries/LibThread/Lock.h
> AK: Add Atomic.h

- Applications/PaintBrush/EraseTool.cpp
- Applications/PaintBrush/EraseTool.h
Comes with a checkbox to turn it off if you dislike it.
> PaintBrush: Use secondary color for eraser (like in ms paint)

- Kernel/Arch/i386/APIC.cpp
- Kernel/Arch/i386/APIC.h
- Kernel/Arch/i386/CPU.cpp
- Kernel/Arch/i386/CPU.h
- Kernel/Makefile
- Kernel/VM/MemoryManager.cpp
- Kernel/VM/MemoryManager.h
- Kernel/init.cpp
This is work in progress. The goal is to support multi-core processors.
> WIP: APIC: Enable APIC and start APs

- Libraries/LibC/string.cpp
My testing has shown this to be fully functional. I have no idea if anyone will ever use this, but hey, more of the C library is implemented!
> LibC: strtok is now implemented (string.h)

- Kernel/Devices/KeyboardDevice.cpp
- Kernel/Devices/KeyboardDevice.h
This PR replaces my last PR (#644). It is cleaner and also adds Num Lock key support.
> KeyboardDevice: Caps Lock and Num Lock key handling

- AK/ELF/ELFLoader.cpp
- Kernel/Process.cpp
ElfLoader::layout has a "failed" variable that is never set.
This patch checks the return value of each hook (alloc/map section
and tls) and fails the load if they return null.
For some reason, I also needed to patch Kernel/Process.cpp so that
the alloc_section_hook and map_section_hook actually return nullptr
when allocating their regions fails? Not sure why vaddr.as_ptr()
wouldn't be nullptr when that call fails...
This should resolve #664 :)
> ELF: Fail layout when program header hooks return nullptr

- Applications/HexEditor/HexEditor.cpp
- Applications/HexEditor/HexEditor.h
- Applications/HexEditor/HexEditorWidget.cpp
- Applications/HexEditor/main.cpp
- Libraries/LibGUI/GStatusBar.cpp
- Libraries/LibGUI/GStatusBar.h
-  LibGUI: Add very limited multi-label support to GStatusBar 
-  HexEditor: Added a multi-label status bar, and a new copy option.
-  HexEditor: Fixed startup error
> GStatusBar enhancement and hex editor enhancements

- Applications/HexEditor/HexEditor.cpp
- Applications/HexEditor/HexEditor.h
- Applications/HexEditor/HexEditorWidget.cpp
- HexEditor: Added new file action.
- HexEditor: Added fill selection action.
> HexEditor: More enhancements

- Userland/cat.cpp
Before cat could only open one file so I modified it a bit to output 
multiple like other cat versions. Now it iterates through each file 
with a for loop.
> Userland: cat updated to open multiple files

- Servers/SystemServer/main.cpp
SystemServer didn't reap its child processes. This commit adds
sigchld_handler, which reaps children when appropriate.
> SystemServer: reap dead processes.

- Libraries/LibGUI/GTextEditor.cpp
- Libraries/LibGUI/GTextEditor.h
I'm almost done with the undo behavior & I'd like to know if I'm making any big mistakes before I add the other features.
> TextEditor: Implementation of undo behavior

- Libraries/LibC/stdlib.cpp
`atof()` has now been implemented as part of the standard C library.
It supports scientific notation such as `1.2e-3` etc, ala the version
found as part of `glibc`.
It's a bit chunky, so there's probably room for optimisations here
and there, however, for now it works as intended (and allows Quake
to run).
> LibC: Implemented atof()

- Userland/nl.cpp
I wrote a version of nl for Serenity with a lot but not all of the posix options.
Includes line count type (-b), increment (-i), delimiter (-s), start number (-v), and width (-w).
> Userland: Add the utility nl "number line"

- Libraries/LibC/bits/stdint.h
- Libraries/LibC/inttypes.h
- Libraries/LibC/stdio.cpp
- Libraries/LibC/stdio.h
- Libraries/LibC/time.cpp
- Ports/nasm/package.sh
This PR contains, as the name says, a port package of nasm. It also includes a few changes done to LibC to make it properly compile and actually work.
Also here's a screenshot of it working in Serenity:
> Ports: nasm port

- Toolchain/BuildIt.sh
The indentation was off, it's fixed now
> meta: Fix coding style in BuildIt.sh

- Libraries/LibC/stdlib.cpp
- Libraries/LibC/stdlib.h
- Libraries/LibC/time.cpp
- Libraries/LibC/time.h
- Libraries/LibC/wchar.cpp
- Libraries/LibC/wchar.h
- Libraries/LibM/math.cpp
- Ports/python-3.6/README.md
- Ports/python-3.6/config.site
- Ports/python-3.6/package.sh
- Ports/python-3.6/patches/0001-Adapt-configuration.patch
- Ports/python-3.6/patches/0002-Remove-not-compiling-asserts.patch
- Ports/python-3.6/patches/0003-Remove-locale-setup-and-use-utf-8-as-default.patch
- Ports/python-3.6/patches/0004-Remove-wrong-ifdef.patch
- Ports/python-3.6/patches/0005-Use-dev-random-instead-of-dev-urandom.patch
This port is experimental and not all python modules are working.
But this is an initial shot which can be further worked on, as
SerenityOS gets more mature. :^)
The main limitation is that locales, threading and time related
functions are not working.
> Ports: Add initial Python 3.6 port

- Applications/Terminal/main.cpp
- DevTools/HackStudio/TerminalWrapper.cpp
- Kernel/Devices/BXVGADevice.cpp
- Kernel/Devices/BXVGADevice.h
- Kernel/Devices/MBVGADevice.cpp
- Kernel/Devices/MBVGADevice.h
- Servers/WindowServer/WSScreen.cpp
Nothing too interesting, except this is my first code contribution since https://github.com/SerenityOS/serenity/pull/640.
cc @Quaker762
> VGA and CLOEXEC fixes

- Ports/.port_include.sh
Add support for zip files and ensure configure is executable
> Ports: Add support for zip files and ensure configure is executable

- Kernel/Process.cpp
- Kernel/Syscall.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
Please do test & review carefully, I'm not sure I didn't mess something up.
To test: type `cat`, Enter, Ctrl-C, Ctrl-D, the terminal should close.
> Unwind kernel stacks before dying

- DevTools/HackStudio/TerminalWrapper.cpp
- DevTools/HackStudio/TerminalWrapper.h
- DevTools/HackStudio/main.cpp
- Kernel/Process.cpp
- Kernel/Process.h
Closes https://github.com/SerenityOS/serenity/issues/771
Does not quite work without https://github.com/SerenityOS/serenity/pull/778
> Stop button for the HackStudio

- Libraries/LibVT/TerminalWidget.cpp
- Libraries/LibVT/TerminalWidget.h
> Terminal: Add selecting whole line on triple click

- Kernel/Process.cpp
Remove explicit checking for pending signals from writing code paths, since this is handled automatically when blocking, and should not happen if the `write()` call is "short", i.e. doesn't block. All the other syscalls already work like this.
Fixes (really, works around) https://github.com/SerenityOS/serenity/issues/797
> Kernel: Don't interrupt short writes

- Servers/AudioServer/Makefile
This fixes race conditions & failures during build.
> AudioServer: Make all source files depend on generated sources

- Applications/FileManager/DirectoryView.h
- Applications/FileManager/Makefile
- Applications/FileManager/PropertiesDialog.cpp
- Applications/FileManager/PropertiesDialog.h
- Applications/FileManager/main.cpp
- Libraries/LibGUI/GDirectoryModel.cpp
- Libraries/LibGUI/GDirectoryModel.h
Right now the dialog only shows some basic information, but it does let the user rename the file/change permissions
> FileManager: Added properties dialog

- Libraries/LibC/stdlib.cpp
Nothing fancy, just a simple implementation of bsearch(3).
> LibC: Implement bsearch

- Libraries/LibC/unistd.cpp
- Libraries/LibC/unistd.h
- Libraries/LibVT/Terminal.cpp
- Ports/vttest/package.sh
- Ports/vttest/patches/fix-autoconf.patch
Ported this over to assist in the improvement of LibVT.
> Ports: VTTEST

- Applications/FileManager/main.cpp
Fixes #825
The logic already existed. I just moved it to a separate lambda then added it
to the appropriate action. Note that when the tree view refreshes, it seems to
randomly open trees. I would like to fix this in a separate PR.
> FileManager: Refresh tree view when deleting directories

- Kernel/makeall.sh
Check for Toolchain presence when running makeall.sh
> Meta: Check for Toolchain presence when running makeall.sh

- Applications/TextEditor/TextEditorWidget.cpp
Just a few lines, this commit should be a fix of issue #892
> TextEditor: Ask before opening a file if current document is dirty

- Makefile.common
- Ports/.port_include.sh
- Ports/gcc/package.sh
- Ports/gcc/patches/gcc.patch
The self-hosted build is still broken to me; it aborts with
```
USERSPACE(26) ASSERTION FAILED: value >= 0
stdlib.cpp:690 in long long unsigned int strtoull(const char*, char**, int)
```
I guess `strtoull()` is not supposed to do that when given `-something` as input.
> Upgrade the GCC port and misc stuff

- Meta/refresh-serenity-qtcreator.sh
https://youtu.be/efjuLD_L-Ho?t=129
> Meta: refresh-serenity-qtcreator.sh now checks if SERENITY_ROOT is set

- Base/usr/share/man/man1/cal.md
- Userland/cal.cpp
_Note: This pull request supersedes #840 with a cleaner branch/commit history. Pasting the original message here:_ 
I've added arguments to specify day, month and/or year as well as support to print an entire year in a grid.
It's definitely not a beautiful code as I don't really know what I'm doing but well... it does the trick.
I also added a man page for it.
> Userland: Improvements to the cal command

- Applications/Piano/PianoWidget.cpp
- Applications/Piano/PianoWidget.h
This is slightly pedantic but I don't feel like adding features without cleaning up a bit first
> Piano: Refactoring

- Libraries/LibC/stdio.cpp
- Libraries/LibC/stdlib.cpp
- Libraries/LibC/stdlib.h
- Libraries/LibHTML/Parser/CSSParser.cpp
Also make __generate_unique_filename() function for generating unique filenames
In the future it might be nice to use O_TMPFILE instead.
> LibC: Implement tmpfile()

- Kernel/build-image-qemu.sh
- Kernel/build-root-filesystem.sh
- Libraries/LibCore/CEventLoop.cpp
- Libraries/LibCore/CIODevice.h
- Libraries/LibCore/CLocalServer.cpp
- Libraries/LibCore/CLocalSocket.cpp
- Libraries/LibCore/CObject.h
- Makefile
- Makefile.common
- ReadMe.md
- Toolchain/BuildFuseExt2.sh
- Toolchain/BuildIt.sh
This pull request enables building serenity toolchain, kernel, userland and rootfs on macOS.
Some background discussion can be found visiting #808.
This involves using clang as bootstrap compiler to build GCC and the IPCCompiler tools, build everything and then mount and create the rootfs.
Notes:
- I have explicitly downloaded GCC dependencies to static link them, building a gcc cross-compiler that doesn't depend on any dylib installed. I've had problems in the past with brew installing different and incompatible versions of the support libraries (isl, mpfr etc.) so that's my suggested way of building GCC on macOS. Also the Linux build could statically link them to, to mitigate similar issues, if they exist.
- Patches in the build-root-filesystem.sh shell scripts are needed because macOS …
> Build serenity Toolchain, Kernel, Userland and Root FS natively on macOS

- Libraries/LibPthread/pthread.cpp
Just feels like the right thing to do, you know.
> LibPthread: Change debug log to output to debug console instead of cluttering terminal output

- Libraries/LibC/sys/time.h
This commit add macros for the timeval operations timeradd, timersub,
timercmp, timerisset, timerclear.
> LibC: Add timeval operations

- Applications/DisplayProperties/main.cpp
Added a menubar to the `DisplayProperties` application to make it
more consistent with the other programs in the system.
> DisplayProperties: Added a menubar

- Userland/crash.cpp
I was testing with this and must have forgotten to remove it :(
I'm a big dummy
> Crash: Woops! Remove a misplaced if (true)

- INSTALL.md
Update link to build instructions in INSTALL.md
> Meta: Update link to build instructions in INSTALL.md

- AK/Tests/Makefile
- DevTools/FormCompiler/Makefile
- DevTools/IPCCompiler/Makefile
- Documentation/BuildInstructions.md
- Kernel/build-image-qemu.sh
- Kernel/build-root-filesystem.sh
- Kernel/makeall.sh
- Libraries/LibC/limits.h
- Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_cpp/Makefile
- Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_h/Makefile
- Makefile.common
- Toolchain/BuildIt.sh
@Pagghiu: can you verify this still builds for you on macOS?
> Build: add OpenBSD host support

- Userland/cut.cpp
The user can now give more than one files to the cut command.
> Userland: Support multiple input files.

- Libraries/LibHTML/DOM/Document.cpp
- Libraries/LibHTML/DOM/Document.h
- Libraries/LibHTML/HtmlView.cpp
- Libraries/LibHTML/Layout/LayoutListItemMarker.cpp
- Libraries/LibHTML/Layout/LayoutText.cpp
> LibHTML: Respect the system theme

- Userland/keymap.cpp
Correct the number of keymap entries and initialize them.
Fixes #1017
> Keymap: Fix map initialization

- Applications/FileManager/DirectoryView.h
- Applications/FileManager/main.cpp
- Libraries/LibGUI/GAbstractView.cpp
- Libraries/LibGUI/GAbstractView.h
> Filemanager: Add Ctrl+A select all action

- Libraries/LibGUI/GItemView.cpp
- Libraries/LibGUI/GItemView.h
After lurking for a while I thought I might give a simple issue a try :) Its a pretty uncomplicated patch but I tried to stick to the repo convention as much a possible. Let me know if I have made any mistakes.
Closes #1029
> LibGUI: Retain existing selection in GItemView on rubberband when the ctrl key is held

- Applications/SystemMonitor/main.cpp
- Base/etc/fstab
- Base/usr/share/man/man2/mount.md
- Base/usr/share/man/man8/mount.md
- Kernel/FileSystem/Custody.cpp
- Kernel/FileSystem/Custody.h
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
- Kernel/FileSystem/VirtualFileSystem.h
- Kernel/Process.cpp
- Kernel/Syscall.h
- Libraries/LibC/fcntl.h
- Libraries/LibC/unistd.cpp
- Libraries/LibC/unistd.h
- Userland/mount.cpp
* Cleanup
* Mount flags (`MS_NODEV`, `MS_NOEXEC`, `MS_NOSUID`, `MS_BIND`)
* Bind mounts!
* Docs
> Mounts, part 2

- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/TextEditorWidget.h
- Libraries/LibGUI/GTextEditor.h
This pull request provides improvements for the text editor and is consisted of two parts:
- Implement replacement functionality
- Replace text in find textbox with selection
I understand that @christopherdumas was already assigned on the first part of this pull request (#259), but he's been inactive for a few months so I hope it's okay if I just do it instead :P 
PS: I've publicized insert_at_cursor_or_replace_selection() for the replacement functionality, will this cause any problems :/ ?
[Closes #259]
> TextEditor: Miscellaneous improvements

- Userland/chgrp.cpp
- Userland/chown.cpp
This pull request improves file ownership modification in two ways:
- Allow the user to provide `chown` with a named `uid` and/or `gid`
- Use `pledge` in `chown`
- Add the `chgrp` command
> Userland: File ownership improvements

- Userland/ls.cpp
- Userland/man.cpp
- Userland/md.cpp
- Userland/more.cpp
- Userland/tail.cpp
Enables pledge in:
- ls
- md
- tail
- more
- man
> Pledge-ify more of the userland utilities.

- Base/usr/share/man/man2/pledge.md
- tty promise was listed twice.
- Fix a few typos
> man: Fix minor inconsistencies in pledge(2) man page

- AK/String.cpp
- AK/StringView.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
This should fix https://github.com/SerenityOS/serenity/issues/970 as well as multiple issues I've found related to mount point handling — and also make the code easier to follow / reason about.
I've checked and this doesn't seem to break any of the test cases I've previously fixed in https://github.com/SerenityOS/serenity/pull/226, but please give it some more testing.
cc @shannonbooth
> Fix/rewrite VFS::resolve_path()

- Userland/ls.cpp
> Userland/ls: escape non-printable characters

- Applications/Help/main.cpp
- Libraries/LibGUI/GTreeView.cpp
- Servers/WindowServer/WSMenuManager.cpp
- Servers/WindowServer/WSMenuManager.h
- Servers/WindowServer/WSWindowManager.cpp
* Make Mod_Logo toggle the system menu instead of only opening it
* Fix Window switcher not closing after switching windows
* Support Key_Return toggling tree views
* Give focus to tree view widget in help on open
Closes #1090
> More key improvements

- AK/StdLibExtras.h
- Servers/WindowServer/WSMenu.cpp
- Servers/WindowServer/WSMenu.h
I love the new scroll feature! Just some small tweaks to WSMenu, and a new clamp() function that can hopefully be used as a neater way of writing that annoying clamping math.
> WindowServer: Small menu improvements

- Kernel/Process.cpp
... and as always, some drive-by tweaks.
> Fix bash closing its stdin

- Kernel/Devices/FloppyDiskDevice.cpp
- Kernel/Devices/FloppyDiskDevice.h
Thought I'd fix this up as you were encouraging people to add their names to things that they've added/changed significantly (plus then I'm the one that takes the blame for this abomination).
> Meta: Change copyright holder of `FloppyDiskDevice.*

- Ports/mawk/package.sh
- Ports/mawk/patches/fix-autoconf.patch
An awk implementation would be good to have.
MAWK is a fast, POSIX-compliant awk implementation.
> Add mawk port

- Ports/byacc/package.sh
- Ports/byacc/patches/fix-autoconf.patch
- Ports/byacc/patches/fix-main.patch
A yacc package would be useful.
byacc is a standard yacc implementation.
> Ports: Add byacc port

- Applications/FileManager/DirectoryView.cpp
- Libraries/LibGUI/GAbstractView.cpp
- Libraries/LibGUI/GFileSystemModel.cpp
- Libraries/LibGUI/GFileSystemModel.h
Nothing big, just fixes/changes for the two things we've talked about.
> Executable and selection fixes

- MenuApplets/CPUGraph/main.cpp
This is a very naive implementation. Feel free to ask for improvements.
> CPUGraph.MenuApplet: execute SystemMonitor on left mousebutton click

- Demos/DynamicLink/LinkDemo/main.cpp
- Demos/DynamicLink/LinkLib/DynamicLib.cpp
- Libraries/LibC/cxxabi.cpp
- Libraries/LibELF/ELFDynamicLoader.cpp
- Libraries/LibELF/ELFDynamicLoader.h
- Libraries/LibELF/ELFDynamicObject.cpp
- Libraries/LibELF/ELFDynamicObject.h
Demos/DynamicLink, LibC/cxxabi.cpp, and LibELF/ELFDynamic*.[cpp/h]
> Meta: Claim copyright on files added by me

- Kernel/Devices/PS2MouseDevice.cpp
- Kernel/Devices/PS2MouseDevice.h
- Kernel/Devices/VMWareBackdoor.cpp
- Kernel/Devices/VMWareBackdoor.h
- Kernel/IO.h
- Kernel/Makefile
- Kernel/MousePacket.h
- Kernel/init.cpp
- Servers/WindowServer/WSEventLoop.cpp
- Servers/WindowServer/WSScreen.cpp
- Servers/WindowServer/WSScreen.h
Closes #1155 
Thanks to @bugaevc for the help with the WindowServer stuff!
> VMMouse support

- Applications/Piano/AudioEngine.cpp
- Applications/Piano/AudioEngine.h
- Applications/Piano/KnobsWidget.cpp
- Applications/Piano/KnobsWidget.h
- Applications/Piano/MainWidget.cpp
- Applications/Piano/Music.h
This PR implements the rest of the volume envelope and exposes the parameters with millisecond accuracy.
> Piano: Full volume envelope implementation

- AK/BufferStream.h
- AK/LogStream.cpp
- AK/LogStream.h
- AK/String.h
- AK/Types.h
- Applications/FileManager/FileUtils.cpp
- Applications/FileManager/FileUtils.h
- Applications/FileManager/PropertiesDialog.cpp
- Applications/FileManager/PropertiesDialog.h
- Applications/HexEditor/HexEditor.h
- Applications/Piano/RollWidget.h
- Applications/SystemMonitor/DevicesModel.cpp
- Applications/Welcome/Makefile
- DevTools/IPCCompiler/main.cpp
- Libraries/LibC/sys/stat.h
- Libraries/LibC/sys/types.h
- Libraries/LibCore/CEventLoop.cpp
- Libraries/LibCore/CNetworkJob.cpp
- Libraries/LibDraw/Font.cpp
- Libraries/LibDraw/GIFLoader.h
- Libraries/LibDraw/GraphicsBitmap.h
- Libraries/LibDraw/Painter.cpp
- Libraries/LibGUI/GWidget.h
- Libraries/LibGUI/GWindow.cpp
- Libraries/LibIPC/IEncoder.h
- Libraries/LibThread/Thread.cpp
- Libraries/LibThread/Thread.h
- Makefile.common
- Servers/TTYServer/main.cpp
- Servers/WindowServer/WSMenu.cpp
Here are a bunch of cherry-picked commits from my hosted branch for 64-bit `size_t` support, building with clang, etc.
Tested on a regular build (cross-compiled under OpenBSD) and seems to work fine in qemu.
> Portability fixes

- Makefile.common
> Build: clean .d files based on SUFFIXED_OBJS and EXTRA_OBJS

- Userland/chown.cpp
chown takes 2 arguments, not 1.
> Userland: Fix segfault in chown

- Libraries/LibGfx/Bitmap.cpp
- Servers/WindowServer/Menu.cpp
- Servers/WindowServer/Window.cpp
- Servers/WindowServer/Window.h
While I was messing around with the code a little with #1165 I triggered a few bugs where I didn't understand at first what went wrong. Just add some asserts hopefully help in the future and a little bit of cleanup.
> WindowServer/LibGfx: Add some asserts and codecleanup

- AK/String.cpp
- AK/String.h
- AK/Tests/TestString.cpp
- Libraries/LibCore/DirIterator.cpp
- Libraries/LibCore/DirIterator.h
- Shell/main.cpp
Try simplify advance_next() a little bit and add a SkipParentAndBaseDir flag for the case that we want to include dot-files, but not the parent or base directory.
> Some DirIterator improvements

- Applications/Piano/KnobsWidget.cpp
- Libraries/LibGUI/Slider.cpp
- Libraries/LibGUI/Slider.h
This PR implements mouse wheel events for sliders and adds a new step property to them. The Piano app has also been updated to use this new property.
> Mouse wheel event for sliders

- Applications/HexEditor/HexEditor.cpp
Fixes out of bounds cursor and uncleared change tracking (red marks).
> HexEditor fixes

- Base/usr/share/man/man1/host.md
- Userland/host.cpp
@awesomekling  Fixes #1246. Add man page.
> host: Use ArgsParser to parse arguments, and add man page

- Base/usr/share/man/man8/lspci.md
- Userland/lspci.cpp
@deoxxa @awesomekling The `db` pointer could be null, and cause UB. Fixes #1247. Additionally, add man page for lspci.
> Userland: check null pointer, and add man page for the lspci program

- Userland/mv.cpp
@awesomekling Use ArgsParser to parse arguments. Check `lstat` for possible failure. 
Fixes #1265.
> mv: Use ArgsParser, and check lstat for failure

- Userland/truncate.cpp
> Userland: Delete redundant code in truancate

- Libraries/LibCore/DateTime.cpp
> DateTime: Fix a typo

- Applications/DisplayProperties/DisplayProperties.cpp
- Applications/DisplayProperties/DisplayProperties.h
- Applications/DisplayProperties/ItemListModel.h
- Applications/DisplayProperties/main.cpp
If anyone's machine blows up setting their wallpaper, they know to blame
me and not AK :P
> Meta: Claim copyright on `DisplayProperties` files

- Toolchain/BuildIt_x86_64.sh
> Toolchain: Add amd64 cross compiler build script

- AK/Tests/TestRefPtr.cpp
> Tests: Fix a typo in TestRefPtr

- Applications/DisplayProperties/DisplayProperties.cpp
- Kernel/Devices/BXVGADevice.cpp
- Kernel/Devices/BXVGADevice.h
- Servers/WindowServer/ClientConnection.cpp
- Servers/WindowServer/Compositor.cpp
- Servers/WindowServer/Compositor.h
- Servers/WindowServer/Screen.cpp
- Servers/WindowServer/Screen.h
- Servers/WindowServer/WindowManager.cpp
- Servers/WindowServer/WindowManager.h
- Servers/WindowServer/WindowServer.ipc
> Kernel & WindowServer: Validate the changed framebuffer resolution in BXVGA device

- AK/String.cpp
- AK/String.h
- AK/StringUtils.cpp
- AK/StringUtils.h
- AK/StringView.cpp
- AK/StringView.h
- AK/TestSuite.h
- AK/Tests/Makefile
- AK/Tests/TestStringUtils.cpp
- DevTools/FormCompiler/Makefile
- DevTools/IPCCompiler/Makefile
- Kernel/Makefile
- Libraries/LibC/Makefile
- Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_cpp/Makefile
- Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_h/Makefile
- Shell/main.cpp
Wildcard pattern matching is widely used in many programs. It would be beneficial to provide this functionality.
> StringView: Implement wildcard pattern matching

- Userland/cut.cpp
Avoid creating SingleIndexes in case of byte ranges. This, boosts the performance
significantly in case a byte range is too big(e.g 666-123123).
Also, claim copyright over this mess since I am the one responsible for it.
> Userland: Speed up the execution of the cut command.

- Kernel/ACPI/MultiProcessorParser.cpp
- Kernel/Arch/i386/CPU.cpp
- Kernel/Devices/PATAChannel.cpp
- Kernel/Devices/PATAChannel.h
- Kernel/Devices/SB16.cpp
- Kernel/Interrupts/APIC.cpp
- Kernel/Interrupts/GenericInterruptHandler.cpp
- Kernel/Interrupts/IOAPIC.cpp
- Kernel/Interrupts/IOAPIC.h
- Kernel/Interrupts/InterruptManagement.cpp
- Kernel/Interrupts/InterruptManagement.h
- Kernel/Interrupts/SpuriousInterruptHandler.h
- Kernel/init.cpp
This is related to #1321 too, and possibly can fix that issue entirely.
> Kernel: Fix IRQ problems - part 2

- Libraries/LibC/time.cpp
Forgot to fix a indentation problem in the last PR.
> LibC: Fix a indentation problem in time.cpp

- Libraries/LibJS/Value.cpp
Hi! I guess this PR is pretty self-explanatory.
Stopped watching the video (which is a lot of fun!) to submit this ^_^
Cheers!
> LibJS: Fix string representation for value of type undefined

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
This patch does the following: 
- Implements if statements
- Implements logical expressions
- Adds the typed comparison operator
- Allows the dumping of literals that aren't numbers
> LibJS: Multiple improvements relating to the AST

- Kernel/Process.cpp
This fixes race conditions in the syscalls `select` and `waitid`, similar to [the one in clock_nanosleep](https://github.com/SerenityOS/serenity/pull/1341).
Like in #1341, it verifies that the output memory is writable before blocking, and writes to it after blocking. In the meantime, a concurrent thread can make the output buffer unwritable, e.g. by deallocating it.
I think these are all such cases! :)
I took the liberty of not implementing Proof of Concepts in `Kernel/Tests/`.  If you would like them anyway I'd be happy to oblige.
> More kernel races (select and waitid)

- AK/StringBuilder.cpp
- AK/StringBuilder.h
> StringBuilder: Improve API and reduce code duplication

- Userland/js.cpp
Minor thing I noticed in the last video.
> Fixed JS Program comment

- Userland/stat.cpp
The '-L' option can be used for calling stat instead of lstat
> Userland: Use ArgParser in stat and support multiple files + links

- AK/String.h
- AK/StringImpl.h
- AK/StringView.h
Now it's possible to use range-based for loops with String and StringView.
> AK: Improve string access member functions

- Games/Solitaire/SolitaireWidget.cpp
Ok, I think this will fix #1398
> Solitaire crash fix

- Libraries/LibGUI/FontDatabase.cpp
- Libraries/LibGfx/Font.cpp
- Libraries/LibWeb/CSS/StyleProperties.cpp
These were giving me asserts when I accidentally dropped a font license text file into my fonts directory.
> Font handling fixes

- Kernel/ACPI/ACPIParser.cpp
- Kernel/ACPI/ACPIParser.h
- Kernel/ACPI/ACPIStaticParser.cpp
- Kernel/ACPI/ACPIStaticParser.h
- Kernel/ACPI/Definitions.h
- Libraries/LibBareMetal/IO.h
This fix will also be used in #1396 and #1361.
> Kernel: Various ACPI fixes - part 2

- Libraries/LibGUI/ItemView.cpp
- Libraries/LibGUI/ItemView.h
> LibGUI: Take scroll offset into account on ItemView rubberband selection

- Libraries/LibGUI/CppSyntaxHighlighter.cpp
- Libraries/LibGUI/CppSyntaxHighlighter.h
- Libraries/LibGUI/JSSyntaxHighlighter.cpp
- Libraries/LibGUI/JSSyntaxHighlighter.h
- Libraries/LibGUI/SyntaxHighlighter.cpp
- Libraries/LibGUI/SyntaxHighlighter.h
> LibGUI: Add missing copyright headers

- Applications/FileManager/PropertiesDialog.cpp
- Applications/FileManager/main.cpp
- Applications/Help/main.cpp
- Applications/HexEditor/HexEditorWidget.cpp
- Applications/IRCClient/IRCAppWindow.cpp
- Applications/QuickShow/main.cpp
- Applications/SoundPlayer/SoundPlayerWidget.cpp
- Applications/TextEditor/TextEditorWidget.cpp
- DevTools/Inspector/main.cpp
- Games/Solitaire/main.cpp
> Applications: Use "Document - AppName" window title format

- Libraries/LibGUI/JSSyntaxHighlighter.cpp
- Libraries/LibJS/Token.cpp
Bleeding edge syntax highlighting.
> LibGUI: Highlight new JS tokens

- Base/home/anon/js/strings.js
- Libraries/LibJS/Lexer.cpp
- Libraries/LibJS/Lexer.h
- Libraries/LibJS/Token.cpp
- Libraries/LibJS/Token.h
also add error handling to lexer
> LibJS: Lex single quote strings, escaped chars and unterminated strings

- ReadMe.md
This will add missing system services and libraries to the readme. There's no particular order (was the list ordered alphabetically once?).
The descriptions might need refinement, so feel free to point that out along with suggestions.
> Meta: Update ReadMe.md

- Base/home/anon/js/simple-scopes.js
- Base/home/anon/js/type-play.js
- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Cell.cpp
- Libraries/LibJS/Cell.h
- Libraries/LibJS/HeapBlock.h
- Libraries/LibJS/Interpreter.cpp
- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Lexer.cpp
- Libraries/LibJS/Object.cpp
- Libraries/LibJS/Object.h
- Libraries/LibJS/ObjectPrototype.cpp
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/StringObject.h
- Libraries/LibJS/Token.cpp
- Libraries/LibJS/Token.h
- Libraries/LibJS/Value.cpp
- Libraries/LibJS/Value.h
This patch implements a few miscellaneous things, fixes a few bugs and most importantly, loosens the typing system and implements abstract equality.
> LibJS: Loosened typing and miscellaneous changes

- Applications/Calendar/AddEventDialog.cpp
- Applications/Calendar/AddEventDialog.h
- Applications/Calendar/Calendar.cpp
- Applications/Calendar/Calendar.h
- Applications/Calendar/CalendarWidget.cpp
- Applications/Calendar/CalendarWidget.h
- Applications/Calendar/Makefile
- Applications/Calendar/main.cpp
- Kernel/build-root-filesystem.sh
- Libraries/LibCore/DateTime.cpp
- Libraries/LibCore/DateTime.h
- Userland/cal.cpp
I messed up the previous pull request (#1399), sorry about that :disappointed:
> Calendar: Implement basic GUI calendar application

- Applications/Calendar/Calendar.cpp
- Applications/Calendar/CalendarWidget.cpp
- Applications/Calendar/CalendarWidget.h
- Applications/Calendar/main.cpp
I don't know if this is appropriate to ask in a pull request but I also have a few questions:
For the top right container, how should I approach orienting the add_event button to the right? Should I just push the right container (make the left container wider) over to move the button over?
Also, there is sometimes a gap during resize (rounding error?), is it possible to avoid this?
> Calendar: Allow resize & code improvements

- Kernel/build-image-qemu.sh
- Kernel/build-root-filesystem.sh
- Kernel/makeall.sh
- Toolchain/BuildIt.sh
- Toolchain/BuildIt_x86_64.sh
I use these small changes to some of the build scripts so they run fine under FreeBSD. Thought I might put them all into a pull request.
> BuildSystem: Add FreeBSD support

- Kernel/ACPI/ACPIDynamicParser.cpp
- Kernel/ACPI/ACPIDynamicParser.h
- Kernel/ACPI/ACPIParser.cpp
- Kernel/ACPI/ACPIStaticParser.cpp
- Kernel/ACPI/ACPIStaticParser.h
- Kernel/ACPI/DMIDecoder.h
- Kernel/ACPI/Definitions.h
- Kernel/ACPI/MultiProcessorParser.h
- Kernel/Arch/i386/CPU.cpp
- Kernel/FileSystem/ProcFS.cpp
- Kernel/Interrupts/APIC.cpp
- Kernel/Interrupts/APIC.h
- Kernel/Interrupts/SpuriousInterruptHandler.h
- Kernel/KParams.h
- Kernel/Net/E1000NetworkAdapter.h
- Kernel/Net/IPv4.h
- Kernel/Net/NetworkAdapter.h
- Kernel/Net/Routing.h
- Kernel/Net/Socket.h
- Kernel/PCI/Access.cpp
- Kernel/PCI/Definitions.h
- Kernel/PerformanceEventBuffer.cpp
- Kernel/Syscall.cpp
- Kernel/Syscall.h
- Kernel/VM/PhysicalPage.cpp
> Kernel: Run clang-format on files

- Servers/WindowServer/WindowFrame.cpp
A very nitpicky change to make the close button actually square. :)
(If you like the other one better, I'm okay with that too :+1:)
> WindowServer: Improve the close button shape

- Kernel/Makefile
- Ports/gcc/package.sh
- Toolchain/BuildIt.sh
- Toolchain/BuildIt_x86_64.sh
Ever closer to C++20! Also fix up some of those pesky "'s
> Toolchain: Update gcc to 9.3.0

- Base/home/anon/www/position-absolute-top-left.html
- Base/home/anon/www/welcome.html
- Libraries/LibWeb/CSS/StyleProperties.cpp
- Libraries/LibWeb/CSS/StyleProperties.h
- Libraries/LibWeb/CSS/StyleValue.h
- Libraries/LibWeb/Layout/BoxModelMetrics.h
- Libraries/LibWeb/Layout/LayoutBlock.cpp
Probably not the most important thing for CSS right now, but I somehow ended up working on this.
With this change it is possible to place elements where ever you want on the page and they don't interfere non-absolute positioned elements. Right now it is not perfect of course and it will need some further changes, but it works quite well so far.
I'm quite unsure about the places I put all the new things, so I am happy about all the feedback I can get. :)
>  LibWeb: CSS: Add "position: absolute" with top and left

- Base/usr/share/man/man1/js.md
- Libraries/LibC/stdio.cpp
- Userland/js.cpp
Here's a man page and a fix for Ctrl-D'ing in the middle of a line. Hope that gets me back the GBPs I've lost when I didn't even check it compiles before pushing ^)
> JS REPL pt. 2

- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/Array.h
- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Tests/Array.prototype.pop.js
- Libraries/LibJS/Tests/Array.prototype.shift.js
Add `shift` and `pop` methods to the `Array` prototype.
> LibJS: Implement Array.prototype.{shift,pop}

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.startsWith.js
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
- https://tc39.es/ecma262/#sec-string.prototype.startswith
> LibJS: Implement String.prototype.startsWith()

- Base/home/anon/js/date.js
- Libraries/LibJS/Interpreter.cpp
- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Makefile
- Libraries/LibJS/Runtime/Date.cpp
- Libraries/LibJS/Runtime/Date.h
- Libraries/LibJS/Runtime/DateConstructor.cpp
- Libraries/LibJS/Runtime/DateConstructor.h
- Libraries/LibJS/Runtime/DatePrototype.cpp
- Libraries/LibJS/Runtime/DatePrototype.h
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Tests/Date.now.js
- Libraries/LibJS/Tests/Date.prototype.getDate.js
- Libraries/LibJS/Tests/Date.prototype.getDay.js
- Libraries/LibJS/Tests/Date.prototype.getFullYear.js
- Libraries/LibJS/Tests/Date.prototype.getHours.js
- Libraries/LibJS/Tests/Date.prototype.getMilliseconds.js
- Libraries/LibJS/Tests/Date.prototype.getMinutes.js
- Libraries/LibJS/Tests/Date.prototype.getMonth.js
- Libraries/LibJS/Tests/Date.prototype.getSeconds.js
- Libraries/LibJS/Tests/Date.prototype.getTime.js
- Userland/Makefile
This adds:
- A global `Date` object (with `length` property and `now` function)
- The `Date` constructor (no arguments yet)
- The `Date` prototype (with `get*` functions)
- A bunch of tests
This is the most C++ I've ever written, so it's probably not perfect - I hope it's a good start however, and it works :^)
> LibJS: Start implementing Date

- Libraries/LibJS/Runtime/DatePrototype.cpp
- Libraries/LibJS/Runtime/DatePrototype.h
> LibJS: Implement Date.prototype.toString()

- Libraries/LibJS/Runtime/Date.h
- Libraries/LibJS/Runtime/DatePrototype.cpp
- Libraries/LibJS/Runtime/DatePrototype.h
...and sorry for the "pull request spam" :smile:
> LibJS: Implement Date.prototype.to{Date,Time}String()

- Userland/df.cpp
`/bin/df` optional command line flags to support human readable output. Fixes #735.
The "incorrect" size calculations mentioned in #735 are also resolved by using the appropriate device `block_size` for human readable output.
These changes do not modify the existing default behaviour for `df` output. That is, when `/bin/df` is run without the human readable flag, the "incorrect" size (the number of blocks) is printed without mention of the `block_size`. Comparitively, `df` on Linux defaults to printing a column titled `1K-Blocks`, for example.
Much of this code was stolen from [Userland/ls.cpp](https://github.com/SerenityOS/serenity/blob/master/Userland/ls.cpp).
> Userland: Add optional human readable output to /bin/df

- Applications/IRCClient/IRCClient.cpp
- Applications/IRCClient/IRCClient.h
Add support for `/HOP` and `/TOPIC` commands.
> IRCClient: Add support for /HOP and /TOPIC commands

- MenuApplets/Clock/main.cpp
Execute the new Calendar app upon click, but only if it's on the date side of the widget.
We also might want a Clock app for fun and profit.
> Clock menu applet: launch the new Calendar on click

- DevTools/HackStudio/FindInFilesWidget.cpp
> HackStudio: Move the "Find in files" button in line with the search box

- Kernel/Time/HPET.cpp
> Kernel: Align read operation in HPET registers' block

- Libraries/LibJS/Makefile
- Libraries/LibJS/Runtime/ErrorConstructor.cpp
- Libraries/LibJS/Runtime/ErrorConstructor.h
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Tests/Error.js
https://www.ecma-international.org/ecma-262/5.1/#sec-15.11
> LibJS: Implement Error function/constructor

- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Tests/NaN-basic.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN#Description
> LibJS: Add NaN to global object

- Userland/js.cpp
~~Add the option to load in a global repl object by calling interpreter.enable_repl_session(print); where print is a function that accepts a JS::Value for use in displaying evaluated output. The repl command are: repl.exit(code), repl.load("file1", "file2", "fileEtc"), and repl.help()~~
CC: @awesomekling @bugaevc
> Userland/JS: Extend the global object when using a REPL 

- Applications/IRCClient/IRCClient.cpp
The /part, /hop, /topic, /kick commands will now default to the
currently active window if a channel name was not provided.
> IRCClient: Use active channel window for part,hop,topic,kick commands

- Applications/SystemMonitor/main.cpp
- Base/etc/fstab
- Base/usr/share/man/man2/mount.md
- Base/usr/share/man/man8/mount.md
- Kernel/FileSystem/DiskBackedFileSystem.cpp
- Kernel/FileSystem/Ext2FileSystem.cpp
- Kernel/FileSystem/Ext2FileSystem.h
- Kernel/FileSystem/FileBackedFileSystem.cpp
- Kernel/FileSystem/FileBackedFileSystem.h
- Kernel/FileSystem/FileDescription.cpp
- Kernel/FileSystem/FileSystem.h
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
- Kernel/Makefile
- Kernel/Process.cpp
- Kernel/Syscall.h
- Kernel/init.cpp
- Libraries/LibC/unistd.cpp
- Libraries/LibC/unistd.h
- Userland/mount.cpp
Fixes #1351.
cc @bugaevc for this PR :)
> Kernel: Ensure non-pseudo file systems are backed by a file

- Applications/IRCClient/IRCAppWindow.cpp
- Applications/IRCClient/IRCAppWindow.h
- Applications/IRCClient/IRCClient.cpp
- Applications/IRCClient/IRCClient.h
Add menu options to invite user, op/deop/voice/devoice user,
and cycle channel.
> IRCClient: Add channel operations to Channel application menu

- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Tests/Infinity-basic.js
- Libraries/LibJS/Tests/NaN-basic.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity
> LibJS: Implement Infinity

- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Tests/binary-bitwise-operators-basic.js
The Lexer and AST already have all the functionality required in place, so this is just updating `Parser::match_secondary_expression()` and `Parser::parse_expression()` to handle `TokenType::{Ampersand,Pipe,Caret}`, as well as adding some tests.
> LibJS: Parse binary bitwise operators

- Libraries/LibWeb/HtmlView.cpp
> LibWeb: Handle invalid URL in HtmlView::load()

- AK/JsonParser.cpp
> AK: Break on end of input in JsonParser::consume_quoted_string

- Libraries/LibGUI/ColorPicker.cpp
- Libraries/LibGUI/ColorPicker.h
> LibGUI: Add color palette and custom color selection in the ColorPicker

- Userland/js.cpp
I'm surprised how easy this was! :smiley:
Very useful IMO. We could add history loading/saving like `Shell` has it as well.
> js: Add lines to history

- AK/MACAddress.h
- Base/etc/SystemServer.ini
- Kernel/Net/ARP.h
- Kernel/Net/EthernetFrameHeader.h
- Kernel/Net/ICMP.h
- Kernel/Net/IPv4Socket.cpp
- Kernel/Net/NetworkAdapter.h
- Kernel/Net/Routing.cpp
- Kernel/Net/Routing.h
- Kernel/Net/Socket.cpp
- Kernel/Net/Socket.h
- Kernel/Net/TCPSocket.cpp
- Kernel/Net/UDPSocket.cpp
- Kernel/UnixTypes.h
- Kernel/build-root-filesystem.sh
- Libraries/LibC/sys/socket.h
- Servers/DHCPClient/DHCPv4.cpp
- Servers/DHCPClient/DHCPv4.h
- Servers/DHCPClient/DHCPv4Client.cpp
- Servers/DHCPClient/DHCPv4Client.h
- Servers/DHCPClient/Makefile
- Servers/DHCPClient/main.cpp
- Userland/test-bindtodevice.cpp
This patchset adds a new DHCP client
This is part of the GimmeDHCPBecause10.0.2.15IsAnnoying series of patches :^)
> Servers: Add a new DHCP client

- Applications/QuickShow/QSWidget.cpp
- Libraries/LibGfx/Painter.cpp
- Libraries/LibGfx/Painter.h
How this PR looks with light and dark themes:
> QuickShow: Checkerboard background for transparency

- DevTools/HackStudio/TerminalWrapper.cpp
- DevTools/HackStudio/TerminalWrapper.h
- DevTools/HackStudio/main.cpp
- Libraries/LibGUI/TabWidget.cpp
- Libraries/LibGUI/TabWidget.h
> HackStudio: Add new Terminals

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.toLowerCase.js
- Libraries/LibJS/Tests/String.prototype.toUpperCase.js
All the hard work was already done by @awesomekling in https://github.com/SerenityOS/serenity/commit/cb18b2c74df21f6d7e9677bd9e4eb0252f163f4d :^)
> LibJS: Add String.prototype.toUpperCase()

- Applications/IRCClient/IRCWindow.cpp
- Applications/IRCClient/IRCWindow.h
> IRCClient: Add right-click context menu to IRCWindow member list

- Applications/IRCClient/IRCChannelMemberListModel.cpp
- Applications/IRCClient/IRCChannelMemberListModel.h
- Applications/IRCClient/IRCClient.cpp
- Applications/IRCClient/IRCClient.h
- Applications/IRCClient/IRCWindow.cpp
* Add nick_without_prefix and nick_at helpers
* Open query on double click of nick in channel member list
> IRCClient: UI improvements

- Kernel/Devices/DiskPartition.cpp
- Kernel/Devices/DiskPartition.h
- Kernel/init.cpp
> Misc Kernel fixes - part 3

- Applications/IRCClient/IRCClient.cpp
- Applications/IRCClient/IRCClient.h
- Applications/IRCClient/IRCWindow.cpp
- Base/home/anon/IRCClient.ini
Allow IRCClient user to opt out of notifications.
> IRCClient: Add NotifyOnMessage/NotifyOnMention config options

- Libraries/LibJS/Tests/Object.defineProperty.js
I think this needs an extra assert.
> Fix non-configurable js attribute test

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Userland/js.cpp
name says all.
I think LibLine is quickly becoming my "escape from implementing LibCrypto/TLS" place...
> LibLine+JS repl: completion fixup, primitive completion

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Shell/main.cpp
- Userland/js.cpp
Fixes an issue @awesomekling noticed (with pasting into the buffer)
Also fixes an issue @linusg mentioned and builds up on it.
As screenshots are quite trendy today,
> LibLine: fix DSR spam; suggestion fix and beautification

- AK/Tests/TestURL.cpp
- AK/URL.cpp
- AK/URL.h
This is going to be useful for the Browser :^)
>  AK: Support fragment in URL / Parse query and fragment in URL::parse()

- Libraries/LibJS/Runtime/MathObject.cpp
- Libraries/LibJS/Runtime/NumberConstructor.cpp
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Tests/Number.js
- Libraries/LibJS/Tests/to-number-basic.js
Also add `js_negative_infinity()`, `Value(-js_infinity().as_double())` is kind of awkward.
> LibJS: Handle Infinity in Value::to_number()

- Userland/js.cpp
The work I did to add assert as a native function in js
was a step in the wrong direction. Now that js supports
load() it makes sense to just move assert and anything
we want to add to the test harness into pure javascript.
> js: Make load() available when running with --test-mode

- Shell/main.cpp
...when no matching executable could be found in $PATH
> Shell: Suggest local executables and directories

- Libraries/LibJS/Lexer.cpp
- Libraries/LibJS/Lexer.h
- Libraries/LibJS/Tests/comments-basic.js
> LibJS: Handle HTML-style comments

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/Array.h
- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Tests/Array.prototype.filter.js
- Libraries/LibJS/Tests/Array.prototype.forEach.js
- Libraries/LibJS/Tests/Array.prototype.map.js
- Libraries/LibJS/Tests/Array.prototype.push.js
- Libraries/LibJS/Tests/Array.prototype.unshift.js
- Libraries/LibWeb/Bindings/DocumentWrapper.cpp
Also we already have 97 tests, all of them passing :eyes:
> LibJS: More Array.prototype functions

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
> LibLine: Properly handle multiline suggestions

- Kernel/Devices/PATAChannel.cpp
The IOAPIC manual states that "Interrupt Mask-R/W. When this bit is 1,
the interrupt signal is masked. Edge-sensitive interrupts signaled on
a masked interrupt pin are ignored." - Therefore we have to ensure that
we disable interrupts globally with cli(), but also to ensure that we
invoke enable_irq() before sending the hardware command that generates
an IRQ almost immediately.
Fixes #1744.
> Kernel: Ensure that we receive IRQs in PIO mode when IOAPIC is enabled

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Tests/void-basic.js
- https://www.ecma-international.org/ecma-262/5.1/#sec-11.4.2
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
> LibJS: Implement void operator

- Libraries/LibJS/Tests/Function.js
https://github.com/SerenityOS/serenity/commit/ed80952cb6e2b32e2541198134ffc98d282a559d :tada:
> LibJS: Remove outdated FIXME now that we have lexical environments

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.concat.js
Added concat function in String.prototype. :)
> LibJS: String.prototype.concat

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.substring.js
Added substring function in String.prototype.
> LibJS: String.prototype.substring

- Libraries/LibWeb/Bindings/WindowObject.cpp
- Libraries/LibWeb/Bindings/WindowObject.h
- Libraries/LibWeb/DOM/Window.cpp
- Libraries/LibWeb/DOM/Window.h
Based on the following API docs: https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm
> LibWeb: Implement JS confirm()

- AK/StringView.cpp
- AK/StringView.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
This implements one of the weirder parts of the Javascript spec.
> LibJS: Implement automatic semicolon insertion

- Libraries/LibJS/Parser.cpp
> LibJS: Fix semicolon insertion

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.concat.js
Added concat function in Array.prototype. :)
> LibJS: Array.prototype.concat

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Tests/logical-expressions-basic.js
I know, we're still in a phase where the parser can't even parse some of the basic stuff - but you gotta have [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) :D
> LibJS: Implement nullish coalescing operator (??)

- Libraries/LibGfx/Painter.cpp
Fixes #1839 
Always remember PEMDAS, kids!
> LibGfx: Fix draw_triangle() clipping calculations

- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Tests/automatic-semicolon-insertion.js
I said it was something silly :^)
> LibJS: Fix parsing of IfStatement, fixes #1829

- Applications/IRCClient/IRCAppWindow.cpp
- Applications/IRCClient/IRCWindow.cpp
> IRCClient: Use sub-menus for app channel menu and member context menu

- Libraries/LibGUI/Window.cpp
- Servers/WindowServer/ClientConnection.cpp
- Servers/WindowServer/WindowServer.ipc
> WindowServer/LibGUI: Enforce minimum window size

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.slice.js
Added slice function in Array.prototype.
> LibJS: Array.prototype.slice

- AK/URL.cpp
- AK/URL.h
- Applications/Browser/main.cpp
- Applications/FileManager/DirectoryView.cpp
- Applications/FileManager/main.cpp
- Base/usr/share/man/man1/open.md
- Libraries/LibCore/DesktopServices.cpp
- Libraries/LibCore/DesktopServices.h
- Libraries/LibCore/Makefile
- Libraries/LibGUI/Makefile
- Userland/open.cpp
> open(1) & stuff

- Base/usr/share/man/man1/js.md
- Include all options
- Update example REPL session to match current output
- Mention REPL's help()
- Add test mode section
> Base: Update js(1) manpage

- Shell/main.cpp
thanks @alimpfard for noticing :upside_down_face:
> Shell: Don't return early if command is in PATH and a directory

- Libraries/LibJS/Interpreter.cpp
> LibJS: Do not assume that a call frame exists in {get,set}_variable

- Base/res/apps/Cube.af
- Base/res/apps/Fire.af
- Base/res/apps/HelloWorld.af
- Base/res/apps/Screensaver.af
- Base/res/apps/WidgetGallery.af
> Base: Add Demo applications to system menu

- Libraries/LibLine/Editor.cpp
- Shell/main.cpp
> Shell + LibLine: Fixups

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.indexOf.js
Added indexOf function in Array.prototype. :)
> LibJS: Array.prototype.indexOf

- Applications/FileManager/DirectoryView.cpp
- Applications/FileManager/main.cpp
- Libraries/LibGUI/AbstractView.cpp
Basically allows drag & drop outside a node in DirectoryView
> FileManager improvements

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.reverse.js
Added reverse function in Array.prototype. :)
> LibJS: Array.prototype.reverse

- .travis.yml
- Libraries/LibJS/Tests/run-tests
- Meta/Lagom/build-js.sh
Not sure if this works yet, let's see.
> Meta: Build Lagom js and run LibJS tests on Travis

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.lastIndexOf.js
Added lastIndexOf function in Array.prototype. :)
> LibJS: Array.prototype.lastIndexOf

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.includes.js
Added includes function in Array.prototype. :)
> LibJS: Array.prototype.includes

- Applications/Browser/Tab.cpp
- Applications/Browser/Tab.h
- Applications/Browser/main.cpp
- Applications/Help/main.cpp
- Libraries/LibWeb/DOM/HTMLAnchorElement.h
- Libraries/LibWeb/HtmlView.cpp
- Libraries/LibWeb/HtmlView.h
Hopefully I got this mostly right. I couldn't get `create_new_tab`'s `bool activate = true` default parameter working though as it now needs to be declared before the lambda is defined :confused:
> Browser/LibWeb: Open links with target="_blank" in a new tab

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.find.js
Added find function in Array.prototype. :)
> LibJS: Array.prototype.find

- Userland/js.cpp
Currently...
- The evaluation in the REPL cannot be interrupted by the user ("non-violently", that is) as we handle and then ignore `SIGINT`
- The running script can be interrupted, but it won't be able to react to that (`Shell: js(PID) exited due to signal 'Interrupt'`)
Now...
- `^C` will throw an `Error` and thus aborting the current evaluation unless explicitly ignored by the program. This is similar to Python's `KeyboardInterrupt`. The Node.js REPL prints ``Uncaught Error: Script execution was interrupted by `SIGINT` ``.
Minimal example program to reproduce:
```js
try {
while (true) { /* do something over and over */ }
} catch (e) {
// Error: Received SIGINT
}
console.log("Bye!")
```
> js: Interrupt running script or REPL evaluation when receiving SIGINT

- Userland/ls.cpp
>  Userland/ls: Remove unnecessary output

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.includes.js
Added includes in String.prototype.
> LibJS: String.prototype.includes

- Libraries/LibGfx/GIFLoader.cpp
The LZW decode step will now copy and pad LZW data out to 4 bytes if there are
less than 4 bytes remaining in the buffer. This means it will now also work when
the total size of the LZW image data is less than 4 bytes.
> LibGfx: Fix crash on decoding small gifs

- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/Syscall.h
- Libraries/LibC/unistd.cpp
- Libraries/LibC/unistd.h
- Shell/GlobalState.h
- Userland/hostname.cpp
Kernel: Added the ability to set the hostname via new syscall
Userland/hostname: Now takes parameter to set the hostname
LibC/unistd: Added sethostname function
> Added ability to modify hostname

- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/ObjectConstructor.h
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Tests/Object.is.js
Basically === with two particularities: comparing NaN to itself is is considered equal and comparing +0 and -0 is not.
> LibJS: Implement Object.is()

- Userland/js.cpp
Am I understanding https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md#names correctly? :^)
> js: Follow Serenity C++ naming conventions

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.findIndex.js
Added findIndex in Array.prototype
> LibJS: Array.prototype.findIndex

- Ports/neofetch/package.sh
- Ports/neofetch/patches/add-serenity-support.patch
- Ports/neofetch/patches/fix-shebang.patch
Adding colour to Buggie was a pain in the a\*\*, but hopefully worth it :^)
> Ports: Add neofetch

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.some.js
Added some in Array.prototype. :)
> LibJS: Array.prototype.some

- Libraries/LibLine/Editor.cpp
> LibLine: Unbreak the build

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.slice.js
Added slice in String.prototype. :)
> LibJS: String.prototype.slice

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Tests/String.prototype-generic-functions.js
Follow-up commit for https://github.com/SerenityOS/serenity/commit/58f6f50de48965a6bf0113c7e9ba79889dba09ac / https://github.com/SerenityOS/serenity/commit/cfdb7b8806da36520f2b43fb979b9bdadd09a73a.
> LibJS: Make String.prototype.slice() generic

- Shell/main.cpp
LibLine: where every fix brings about another bug.
> Shell: Provide the correct invariant length to the line editor

- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Runtime/ConsoleObject.cpp
- Libraries/LibJS/Runtime/ConsoleObject.h
count: https://developer.mozilla.org/en-US/docs/Web/API/Console/count
countReset: https://developer.mozilla.org/en-US/docs/Web/API/Console/countReset
Again, sorry for the PR spam (#2041 #2042).
This code now works properly:
```js
var lol = console
console.count() // default: 1
lol.count()     // default: 2
console = ""
lol.count()     // default: 3
console.count() // TypeError
```
> LibJS: Implement console.count() and console.countReset()

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/String.prototype.lastIndexOf.js
Added lastIndexOf in String.prototype. :)
> LibJS: String.prototype.lastIndexOf

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Interpreter.cpp
- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Makefile
- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/FunctionPrototype.cpp
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/ReflectObject.cpp
- Libraries/LibJS/Runtime/ReflectObject.h
- Libraries/LibJS/Runtime/Uint8ClampedArray.cpp
- Libraries/LibJS/Runtime/Uint8ClampedArray.h
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Tests/Reflect.apply.js
- Libraries/LibJS/Tests/Reflect.construct.js
- Libraries/LibJS/Tests/Reflect.defineProperty.js
- Libraries/LibJS/Tests/Reflect.deleteProperty.js
- Libraries/LibJS/Tests/Reflect.get.js
- Libraries/LibJS/Tests/Reflect.getOwnPropertyDescriptor.js
- Libraries/LibJS/Tests/Reflect.getPrototypeOf.js
- Libraries/LibJS/Tests/Reflect.has.js
- Libraries/LibJS/Tests/Reflect.ownKeys.js
- Libraries/LibJS/Tests/Reflect.set.js
- Libraries/LibJS/Tests/Reflect.setPrototypeOf.js
- Libraries/LibJS/Tests/indexed-access-string-object.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect
A few FIXMEs here and there, but I think this is a good start :^)
> LibJS: Implement most of the Reflect object

- Applications/DisplaySettings/DisplaySettings.cpp
- Applications/FileManager/DirectoryView.cpp
- Applications/FileManager/DirectoryView.h
- Applications/FileManager/main.cpp
- Libraries/LibGUI/AbstractTableView.cpp
- Libraries/LibGUI/AbstractView.h
- Libraries/LibGUI/FilePicker.cpp
- Libraries/LibGUI/Forward.h
- Libraries/LibGUI/IconView.cpp
- Libraries/LibGUI/IconView.h
- Libraries/LibGUI/Makefile
- Libraries/LibGUI/MultiView.cpp
- Libraries/LibGUI/MultiView.h
- Libraries/LibGUI/ScrollableWidget.cpp
Many small consistency changes, most notably:
- Fix GUI elements that didn't get initialized properly (several very small commits)
- Rename ItemView to IconView, because the hover text says "Icon View" (one very large commit)
> LibGUI: File picker and manager

- Libraries/LibJS/Runtime/Function.cpp
- Libraries/LibJS/Runtime/FunctionConstructor.cpp
- Libraries/LibJS/Runtime/FunctionPrototype.cpp
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/GlobalObject.h
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/ScriptFunction.cpp
- Libraries/LibJS/Runtime/ScriptFunction.h
- Libraries/LibJS/Tests/Array.js
- Libraries/LibJS/Tests/Boolean.js
- Libraries/LibJS/Tests/Date.js
- Libraries/LibJS/Tests/Error.js
- Libraries/LibJS/Tests/Function.js
- Libraries/LibJS/Tests/Number.js
- Libraries/LibJS/Tests/Object.js
- Libraries/LibJS/Tests/String.js
- Libraries/LibJS/Tests/function-name.js
- Libraries/LibWeb/Bindings/WindowObject.cpp
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name
>  LibJS: Add "name" property to functions (and a few other things)

- Servers/WindowServer/WindowManager.cpp
Fixes #2073.
cc @supercomputer7
> WindowServer: Update desktop window rect on resolution change

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Runtime/ScriptFunction.h
- Libraries/LibJS/Tests/function-name.js
> LibJS: Set name of anonymous functions during assignment

- Userland/keymap.cpp
> Userland: Fix leak in keymap

- AK/NumberFormat.h
- Applications/FileManager/DirectoryView.cpp
- DevTools/IPCCompiler/main.cpp
- Libraries/LibCore/NetworkJob.cpp
- Libraries/LibCore/NetworkJob.h
- Libraries/LibHTTP/HttpJob.cpp
- Libraries/LibHTTP/HttpsJob.cpp
- Libraries/LibProtocol/Download.cpp
- Libraries/LibProtocol/Download.h
- Servers/ProtocolServer/Download.cpp
- Servers/ProtocolServer/Download.h
- Servers/ProtocolServer/HttpDownload.cpp
- Servers/ProtocolServer/HttpsDownload.cpp
- Servers/ProtocolServer/HttpsProtocol.cpp
- Servers/ProtocolServer/PSClientConnection.cpp
- Servers/ProtocolServer/ProtocolClient.ipc
- Userland/pro.cpp
This patchset ultimately allows `pro` to show download progress.
- `Optional<T>` in IPCCompiler
- `human_readable_size` thingy in AK (a better name for its file is appreciated)
- a whole bunch of on_progress changes
> ProtocolServer: Implement and handle download progress

- Libraries/LibWeb/HtmlView.cpp
> LibWeb: Add basic support for redirects

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Runtime/ScriptFunction.cpp
- Libraries/LibJS/Tests/function-rest-params.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters
> LibJS: Implement rest parameters

- Base/home/anon/www/canvas-path-quadratic-curve.html
- Base/home/anon/www/welcome.html
- Libraries/LibGfx/Painter.cpp
- Libraries/LibGfx/Painter.h
- Libraries/LibGfx/Path.cpp
- Libraries/LibGfx/Path.h
- Libraries/LibGfx/Point.h
- Libraries/LibWeb/Bindings/CanvasRenderingContext2DWrapper.cpp
- Libraries/LibWeb/Bindings/CanvasRenderingContext2DWrapper.h
- Libraries/LibWeb/DOM/CanvasRenderingContext2D.cpp
- Libraries/LibWeb/DOM/CanvasRenderingContext2D.h
I ended up implementing quadratic bezier curve drawing, and figured I'd add it to LibWeb's canvas and serve it as a separate PR :)
> LibGfx: Quadratic Bezier curve; LibWeb: canvas.quadraticCurveTo

- Libraries/LibHTTP/Forward.h
- Libraries/LibHTTP/HttpJob.cpp
- Libraries/LibHTTP/HttpsJob.cpp
- Libraries/LibHTTP/HttpsJob.h
- Libraries/LibHTTP/Job.cpp
- Libraries/LibHTTP/Job.h
- Libraries/LibHTTP/Makefile
No more copies <sub>mostly</sub>
> LibHTTP: Unify and generalise response handling logic

- Libraries/LibTLS/Record.cpp
- Libraries/LibTLS/TLSv12.cpp
- Libraries/LibTLS/TLSv12.h
> can we get a bit more informative TLS handshake failure errors maybe?
Maybe :^)
> LibTLS: Try to disambiguate errors in case of failure

- Applications/SystemMonitor/main.cpp
In addition to being less surprising, this sets up some groundwork for #1676
> SystemMonitor: Replace details with message when process isn't accesible

- Applications/Browser/Tab.cpp
Hello all! This is my first PR thought something simple would be a good way to get started.
This PR adds a "Copy Link" context menu item that will copy the right clicked href url to the clipboard.
> Browser: Add "Copy link" context menu item

- Base/home/anon/www/canvas-path-quadratic-curve.html
- Libraries/LibGfx/FloatPoint.h
- Libraries/LibGfx/Painter.cpp
- Libraries/LibGfx/Painter.h
- Libraries/LibGfx/Path.cpp
- Libraries/LibGfx/Path.h
- Libraries/LibWeb/Bindings/CanvasRenderingContext2DWrapper.cpp
- Libraries/LibWeb/Bindings/CanvasRenderingContext2DWrapper.h
- Libraries/LibWeb/DOM/CanvasRenderingContext2D.cpp
- Libraries/LibWeb/DOM/CanvasRenderingContext2D.h
Next in the line of rasterising paths.
This makes the generated curves much more pretty, and adds filling paths.
There are some issues with for_each_line_segment_on_bezier_curve creating non-simple shapes, because of fitting points onto an int grid, but they are mostly okay...ish.
> LibGfx: Filling paths; LibWeb: canvas.fill

- Applications/Browser/Tab.cpp
Basically a window containing a read-only `GUI::TextEditor` containing the source code of the current webpage. No temporary file needed :^)
Fixes #1103.
> Browser: Add dedicated "view source" window

- AK/StringView.cpp
- AK/StringView.h
- AK/Tests/TestBinarySearch.cpp
- AK/Tests/TestString.cpp
- AK/Tests/TestStringUtils.cpp
* Make test suite compatible to build for target
* Add to_string() method to StringView
> Small AK Improvements

- DevTools/HackStudio/Project.cpp
- DevTools/HackStudio/Project.h
- DevTools/HackStudio/main.cpp
- Libraries/LibGUI/JSSyntaxHighlighter.h
- Libraries/LibGUI/SyntaxHighlighter.h
> HackStudio+LibGUI: Rename ProjectType/SyntaxLanguage::{Javascript -> JavaScript} & syntax-highlight .ini files

- DevTools/HackStudio/Debugger.cpp
- DevTools/HackStudio/Debugger.h
- DevTools/HackStudio/main.cpp
- Libraries/LibC/ulimit.cpp
- Libraries/LibDebug/DebugInfo.cpp
- Libraries/LibDebug/DebugInfo.h
- Libraries/LibDebug/Dwarf/DIE.h
- Libraries/LibDebug/Dwarf/DwarfInfo.cpp
- Libraries/LibDebug/Dwarf/DwarfInfo.h
- Libraries/LibELF/Image.h
> HackStudio: Inspect local variables in the debugger - fixes

- Libraries/LibWeb/Layout/LayoutText.cpp
Grabbing the low-hanging fruits while they're still available :^)
> LibWeb: Implement "text-transform: {upper,lower}case"

- Userland/date.cpp
… mumble mumble many eyes mumble mumble … :)
> Userland: Remove double-'#include' in date.cpp

- AK/Memory.h
- AK/Tests/TestStringUtils.cpp
- Applications/Browser/WindowActions.cpp
- Applications/Browser/WindowActions.h
- Demos/Mouse/main.cpp
- Kernel/Ptrace.cpp
- Libraries/LibIPC/Makefile
- Libraries/LibWeb/Makefile
- Meta/Lagom/Fuzzers/FuzzJs.cpp
- Userland/disasm.cpp
- Userland/test-crypto.cpp
Please don't merge right away, let's give these people some time to confirm they want to be copyright holders of the files they created, otherwise I'll change it to the generic `Copyright (c) YYYY, the SerenityOS developers.`.
---
- @awesomekling 
- `AK/Memory.h`
- `Applications/Browser/WindowActions.cpp`
- `Applications/Browser/WindowActions.h`
- `Demos/Mouse/main.cpp`
- `Userland/disasm.cpp`
- @itamar8910 
- `Kernel/Ptrace.cpp`
- Written by @predmond but no header with their info already exists
- `Meta/Lagom/Fuzzers/FuzzJs.cpp`
- ~~@alimpfard~~
- ~~`Userland/test-crypto.cpp`~~
- @howar6hill 
- `AK/Tests/TestStringUtils.cpp`
---
I'd also like to propose a script that runs on CI and fails the build if `.{cpp,h}` files in certain directories don't contain a copyright header. (yes, I like …
> Misc: Add missing copyright headers

- .travis.yml
- DevTools/HackStudio/Debugger/Debugger.h
- Meta/check-license-headers.sh
Depends on https://github.com/SerenityOS/serenity/pull/2169 being merged first!
> Meta: Add script to enforce license headers & run it on Travis

- Libraries/LibDesktop/Launcher.cpp
- Userland/open.cpp
Can we make OwnPtr -> bool explicit?
This sort of thing shouldn't really happen...
> LibDesktop + open: Tiny fixes

- Base/res/apps/LibGfxDemo.af
- Demos/LibGfxDemo/Makefile
- Demos/LibGfxDemo/main.cpp
- Kernel/build-root-filesystem.sh
- Libraries/LibGfx/Painter.cpp
- Libraries/LibGfx/Painter.h
- Libraries/LibWeb/Layout/LayoutBox.cpp
(not related to https://github.com/SerenityOS/serenity/issues/2176 but fixing dotted lines is one step into that direction)
> LibGfx: Fix dotted lines and add a LibGfx demo

- Base/home/anon/www/borders.html
- Demos/LibGfxDemo/main.cpp
- Libraries/LibGfx/Painter.cpp
- Libraries/LibGfx/Painter.h
- Libraries/LibWeb/Layout/LayoutBox.cpp
Granted it's not perfect yet, but one step at a time. But then again the spec doesn't dictate every detail here so we can do whatever we want! (to some extend) :^)
---
Serenity Browser:
---
Firefox:
---
Chromium:
---
Fixes https://github.com/SerenityOS/serenity/issues/2176.
> LibGfx/LibWeb: Dashed lines/borders

- Base/res/apps/FontEditor.af
This was forgotten in 6f2837cb130261da5747716bddaaefc75793c8ab :P
> FontEditor: Fix link to icon after it moved

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Libraries/LibVT/Terminal.h
- Libraries/LibVT/TerminalWidget.cpp
@awesomekling 
> looks at the first line in history
> This line in the terminal buffer is clean, no need to update it
Fixes #2185
> LibVT: Fix wrong line lookup when updating; LibLine: Add paging to suggestions

- Libraries/LibGfx/Painter.cpp
In theory, this should make dithering a teensy bit faster.
> LibGfx: Eliminate conditional branch in dither

- Toolchain/BuildIt.sh
Back in 36ba0a35eecec73c3347c43aeb18f3ea4849117d I thought that Travis would
automagically delete the oldest files. Apparently it does not. This patch implements that.
Note that no dummy changes are needed, because BuildIt.sh lists itself
as a dependency for the Toolchain. Hooray for something that works!
Isn't it ironic how the approach that was meant to speed up builds slowed everything down? Anyway, this should make the build speedy again, and the overhead costs negligible.
> Travis: Fix Cache spam

- Libraries/LibWeb/Layout/LayoutBlock.cpp
Closes https://github.com/SerenityOS/serenity/issues/2201
> LibWeb: Fixed non-spec processing of margin and padding

- Shell/Shell.cpp
- Shell/Shell.h
cc @bugaevc 
I'm definitely glad I did that `ENUMERATE_SHELL_BUILTINS` thing :^)
> Shell: Treat builtin names as programs and suggest them

- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/GlobalObject.h
- Libraries/LibJS/Runtime/NumberConstructor.cpp
- Libraries/LibJS/Tests/Number.isFinite.js
- Libraries/LibJS/Tests/Number.isNaN.js
- Libraries/LibJS/Tests/Number.parseFloat.js
- Libraries/LibJS/Tests/parseFloat.js
Back to our back to our regularly scheduled programming that is LibJS.
> LibJS: Add parseFloat() / Number.parseFloat()

- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/Value.cpp
That's gonna cost me a few GBP.
> LibJS: Fix stupid mistakes

- Services/WindowServer/ClientConnection.h
- Services/WindowServer/Compositor.cpp
- Services/WindowServer/Menu.cpp
- Services/WindowServer/MenuItem.cpp
- Services/WindowServer/MenuItem.h
- Services/WindowServer/MenuManager.cpp
- Services/WindowServer/WindowManager.cpp
- Services/WindowServer/WindowManager.h
- Services/WindowServer/WindowSwitcher.cpp
hopefully a little less asleep this time round
> WindowServer: Making things const (part2)

- Kernel/FileSystem/Ext2FileSystem.cpp
- Kernel/FileSystem/Ext2FileSystem.h
- Kernel/FileSystem/FileBackedFileSystem.cpp
- Kernel/FileSystem/FileBackedFileSystem.h
- Kernel/FileSystem/FileSystem.cpp
- Kernel/FileSystem/FileSystem.h
- Kernel/FileSystem/Inode.cpp
- Kernel/FileSystem/Inode.h
- Kernel/FileSystem/ProcFS.cpp
Will probably eat your data though — yet appears to work in my brief testing.
cc @supercomputer7
> Less copying in Ext2FS

- Libraries/LibLine/Editor.cpp
Previously, we would concatenate all the commands together:
```
> sleep 5
echo well
echo hello
echo friends
> echo wellecho helloecho friends
```
Thanks, @bugaevc
> LibLine: Handle <return>s in incomplete data correctly

- Libraries/LibTLS/Record.cpp
As I was trying to push before ninja-merge,
This seems like a better compromise between throughput and latency, and it doesn't _really_ affect the performance, so let's just compromise.
> LibTLS: Flush some packets as soon as more packets are written

- Base/etc/SystemServer.ini
Notably, adjust service priorities.
> Base: Tweak SystemServer.ini

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.every.js
Adds every to Array.prototype.
> LibJS: Add Array.prototype.every

- AK/FileSystemPath.cpp
We shouldn't just drop leading `..`-s for relative paths. At the same time,
we should handle paths like
../foo/../../bar
correctly: the first `..` after the `foo` cancels out the `foo`, but the second
one should get treated as a leading one and not get dropped.
Note that since this path resolution is purely lexical, it's never going to be
completely correct with respect to symlinks and other filesystem magic. Better
don't use it when dealing with files.
> AK: Fix .. handling in FileSystemPath

- Applications/Debugger/main.cpp
- Libraries/LibDebug/DebugInfo.cpp
- Libraries/LibDebug/DebugSession.cpp
- Libraries/LibDebug/DebugSession.h
- Libraries/LibDebug/Dwarf/DwarfInfo.cpp
- Meta/build-root-filesystem.sh
- Userland/functrace.cpp
Some LibDebug fixes that fix regressions we've had in `sdb` and `functrace` :smiley:
> Unbork sdb & functrace

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Runtime/Accessor.h
- Libraries/LibJS/Runtime/Object.cpp
This changes `Accessor`'s `m_{getter,setter}` from `Value` to `Function*` which seems like a better API to me - a getter/setter must either be a function or missing, and the creation of an accessor with other values must be prevented by the parser and `Object.defineProperty()` anyway.
Also add `Accessor::set_{getter,setter}()` so we can reuse an already created accessor when evaluating an ObjectExpression with getter/setter shorthand syntax.
---
I assume `Value` was initially chosen as the parser (incorrectly) allows `{ get foo: bar }`.
> LibJS: Refactor Accessor

- Kernel/Scheduler.cpp
- Services/WindowServer/WindowManager.cpp
cc @alimpfard for the waiting fix
> Misc fixes, pt. 4

- Demos/Eyes/EyesWidget.cpp
- Demos/Eyes/main.cpp
cc @bugaevc I WILL NOT FORGET TO CC
Old:
New (xeyes for comparison)
> Eyes: Correctly calculate the eye bounds for arbitrary number of eyes

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype-generic-functions.js
- Libraries/LibJS/Tests/Array.prototype.splice.js
Adds splice to Array.prototype according to the specification:
https://tc39.es/ecma262/#sec-array.prototype.splice
I'm not sure what to do about the casts on lines 663, 665 and 678. It isn't pretty :(
> LibJS: Add Array.prototype.splice

- ReadMe.md
> Meta: Add github link to the man pages from ReadMe.md

- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/ArrayPrototype.h
- Libraries/LibJS/Tests/Array.prototype.fill.js
- Libraries/LibJS/Tests/test-common.js
I open a new PR because LibJS has seen some changes since I last attempted to implement this, and I wanted a clean commit.
> LibJS: Add Array.prototype.fill

- Libraries/LibWeb/Parser/HTMLParser.cpp
®, ß and all the lowercase and uppercase umlaut characters.
> LibWeb: Add more HTML entities

- Libraries/LibTLS/TLSv12.cpp
Adds more TLS 1.2 error descriptions according to the specification:
https://tools.ietf.org/html/rfc5246#section-7.2.2
This changes the DecryptionFailed description, as the specification
says that this alert should NEVER be sent by a compliant server.
> LibTLS: Add more TLS 1.2 error descriptions

- Applications/Browser/ConsoleWidget.cpp
- Applications/Browser/ConsoleWidget.h
- DevTools/HackStudio/Locator.cpp
- DevTools/HackStudio/Locator.h
- Libraries/LibGUI/TextBox.cpp
- Libraries/LibGUI/TextBox.h
With this patch, gone are the days of re-typing every command in the JS Console, just navigate with the up & down arrow keys!
> LibGUI/Browser: Add history to the JS Console

- CMakeLists.txt
- INSTALL.md
- Kernel/Arch/i386/Boot/boot.S
- Meta/build-image-grub.sh
- Meta/grub-ebr.cfg
- Meta/grub-gpt.cfg
- Meta/grub-mbr.cfg
> Meta: Update grub image building for CMake

- AK/StringView.cpp
- AK/StringView.h
- Base/usr/share/man/man1/xargs.md
- Libraries/LibC/stdio.cpp
- Userland/xargs.cpp
This adds a basic implementation of xargs.
This xargs is not particularly Dr. POSIX-compliant.
cc @bugaevc pls nitpick the heck out of my badly written manpage
> Userland: Add a basic xargs program

- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
As suggested in #2431's code review.
> LibJS: Make Object::invoke() non-const

- Libraries/LibCrypto/ASN1/DER.h
- Libraries/LibCrypto/Cipher/AES.h
- Libraries/LibCrypto/Cipher/Cipher.h
- Libraries/LibCrypto/Cipher/Mode/CBC.h
- Libraries/LibCrypto/PK/RSA.h
- Userland/test-crypto.cpp
> LibCrypto: Fix some issues preventing compilation with clang 10

- Userland/js.cpp
Closes #2452
Not sure who to tag for this, so I'll just...not.
> Userland/js: Prompt for more input on labels and object keys

- Shell/Shell.cpp
@bugaevc Here's your bugfix :^)
> Shell: Treat ^D as builtin_exit when not in a continuation

- Libraries/LibJS/Runtime/StringConstructor.cpp
- Libraries/LibJS/Runtime/StringConstructor.h
- Libraries/LibJS/Tests/String.fromCharCode.js
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode
- https://tc39.es/ecma262/#sec-string.fromcharcode
> LibJS: Add String.fromCharCode()

- Kernel/Time/HPET.cpp
This resolves a bochs panic during bootup:
[Kernel]: HPET @ P0x07ff0fc0
00691951632p[HPET  ] >>PANIC<< Unsupported HPET read at address 0x0000fed00100
These changes however don't fully resolve #2162
> HPET: Fix accessing HPET registers

- Base/usr/share/man/man3/getopt.md
> Fix misspelling

- Applications/FontEditor/FontEditor.cpp
> FontEditor: Fix typo in comment

- Applications/Browser/BrowserConsoleClient.cpp
- Libraries/LibJS/Console.cpp
- Libraries/LibJS/Console.h
- Libraries/LibJS/Interpreter.cpp
- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Runtime/Exception.cpp
- Libraries/LibJS/Runtime/Exception.h
- Userland/js.cpp
> LibJS+js: Exception traces

- Libraries/LibWeb/Parser/HTMLTokenizer.cpp
Also fixes RAWTEXTLessThanSign having a separate emit and reconsume.
> LibWeb: Fully implement all script tokenizer states

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Libraries/LibLine/SuggestionDisplay.h
- Libraries/LibLine/XtermSuggestionDisplay.cpp
> LibLine: Correctly handle line content overflow when on last line

- Shell/Parser.cpp
- Shell/Parser.h
- Shell/Shell.cpp
- Userland/functrace.cpp
- Userland/ls.cpp
Some teeny tiny misc fixes and improvements
- emitting plaintext when `!isatty(stdout)` in a few places
- highlighting `foo >bar` and co.
:thinking: I guess @bugaevc might know of some other places to do this in...I summon thee!
> Misc fixes

- AK/Atomic.h
- AK/NonnullOwnPtr.h
- AK/OwnPtr.h
- AK/RefCounted.h
- AK/Tests/TestNonnullRefPtr.cpp
- AK/Tests/TestRefPtr.cpp
- AK/Types.h
- AK/Weakable.h
- Applications/Calendar/CalendarWidget.cpp
- Applications/Calendar/CalendarWidget.h
- Applications/Calendar/main.cpp
- MenuApplets/Audio/main.cpp
cc @rhin123 — you authored those Calendar changes in https://github.com/SerenityOS/serenity/pull/1721
> RefCounted fixes

- Libraries/LibC/unistd.cpp
- Libraries/LibC/unistd.h
Implemented in user space for now.
> LibC: Add truncate().

- Applications/FileManager/PropertiesDialog.cpp
- Base/etc/group
- Base/usr/share/man/man1/readlink.md
- Base/usr/share/man/man2/readlink.md
- Kernel/FileSystem/FileDescription.cpp
- Kernel/FileSystem/InodeMetadata.h
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/TmpFS.cpp
- Kernel/Process.cpp
- Kernel/UnixTypes.h
- Libraries/LibC/unistd.cpp
- Libraries/LibCore/File.cpp
- Libraries/LibCore/File.h
- Libraries/LibGUI/FileSystemModel.cpp
- Meta/build-root-filesystem.sh
- Userland/cat.cpp
- Userland/chown.cpp
- Userland/ls.cpp
- Userland/readlink.cpp
- Userland/su.cpp
- Userland/test_io.cpp
- Userland/wc.cpp
Yay for some less `PATH_MAX`s!
cc @balatt for wc(1) changes, cc @alimpfard for meowing and whatnot :smile:
> readlink, goodboys and meow

- Applications/QuickShow/QSWidget.cpp
- Applications/QuickShow/QSWidget.h
- Applications/QuickShow/main.cpp
- Libraries/LibGUI/Window.cpp
- Libraries/LibGUI/Window.h
- Services/WindowServer/ClientConnection.cpp
- Services/WindowServer/ClientConnection.h
- Services/WindowServer/WindowServer.ipc
- if image is larger then window size resize it to fit the image 
- "Set as desktop wallpaper" menu item
> QuickShow: Small Improvements (vol:2)

- AK/Base64.cpp
- AK/Tests/TestBase64.cpp
- Base/usr/share/man/man1/base64.md
- Userland/base64.cpp
Adds a simple base64 encoder.
This is still a work-in-progress because I want to add support the modified base64 encoding for IMAP protocol.
Maybe the name of the PR is not the best because I've also added test cases for the existing base64 decoder..
> [WIP] Add base64 encoder

- .gitignore
I saw some discussion on IRC about these two directories and realized that I've just been manually ignoring them for some strange reason instead of just submitting a PR :)
P.S.: Should my commit have a prefix? `Meta: `?
> Add CLion directories to .gitignore

- AK/Time.h
- Kernel/Process.cpp
- Kernel/Scheduler.cpp
- Kernel/Syscall.h
- Kernel/Thread.h
- Libraries/LibC/sys/select.cpp
- Libraries/LibC/sys/select.h
- Libraries/LibC/sys/time.h
@bugaevc As far as I can tell you didn't touch any of these files, but it looks like the kind of thing you might find interesting, so be cc'd.
> LibC: Implement pselect.

- .travis.yml
I hope this works.
Docs:
- https://docs.travis-ci.com/user/notifications/#conditional-notifications
- https://docs.travis-ci.com/user/conditions-v1#integration
> Travis: Limit notifications to SerenityOS/serenity repo

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Shell/Shell.cpp
This commit also updates Shell, which uses actual_rendered_length.
Now we can edit all the lines!
> LibLine: LibMultipleLines! (Support multiline editing)

- Applications/QuickShow/QSWidget.cpp
> QuickShow: Fix for zooming with mouse wheel

- Libraries/LibGUI/FilePicker.cpp
> LibGUI: Update FilePicker location textbox when changing directory

- AK/JsonPath.cpp
- AK/JsonPath.h
- DevTools/Inspector/RemoteObjectPropertyModel.cpp
- DevTools/Inspector/RemoteObjectPropertyModel.h
- DevTools/Inspector/main.cpp
- Libraries/LibGUI/TreeView.cpp
Finally, after fighting `GUI::Model` for a long time, and sneaking `AK::JsonPath` in from my stream json parser, _proper_ inspection :^)
(yes, I couldn't think of any more long-running programs, sue me)
> Inspector: Expand and show properties in a TreeView 

- AK/Atomic.h
- AK/ByteBuffer.h
- AK/LogStream.cpp
- AK/LogStream.h
- Kernel/Arch/i386/CPU.cpp
- Kernel/Arch/i386/CPU.h
- Kernel/Arch/i386/ProcessorInfo.cpp
- Kernel/Arch/i386/ProcessorInfo.h
- Kernel/FileSystem/ProcFS.cpp
- Kernel/Heap/kmalloc.cpp
- Kernel/Lock.cpp
- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/Random.cpp
- Kernel/Scheduler.cpp
- Kernel/SpinLock.h
- Kernel/Thread.cpp
- Kernel/Thread.h
- Kernel/VM/MemoryManager.cpp
- Kernel/VM/MemoryManager.h
- Kernel/VM/Region.cpp
- Kernel/WaitQueue.cpp
- Kernel/init.cpp
- Kernel/kprintf.cpp
This fixes a regression with signal delivery (e.g. for strace) introduced by #2513
> Kernel: Fix signal delivery

- Kernel/Arch/i386/CPU.cpp
- Kernel/Arch/i386/CPU.h
- Kernel/FileSystem/ProcFS.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
> Kernel: Fix /proc/PID/stack

- Kernel/UnixTypes.h
- Libraries/LibC/termios.cpp
- Libraries/LibC/termios.h
- Userland/strace.cpp
Just minor relevant fixes I encountered while trying to port tcl.
`cfgetispeed` and friends might not be interesting enough to add right now, so I can drop that commit if it's not wanted.
> Tiny misc fixes (strace: ArgsParser, SO_KEEPALIVE, cfgetispeed and co) 

- .travis.yml
To gather more data about #2691, let's have the failing tests tell us what failed~
(hopefully this actually does what the cmake docs say it does...)
> Meta: Show the outputs of failing tests in travis

- Kernel/Arch/i386/CPU.cpp
- Kernel/Arch/i386/CPU.h
- Kernel/Devices/PATAChannel.cpp
- Kernel/Devices/SB16.cpp
- Kernel/Heap/SlabAllocator.cpp
- Kernel/Lock.cpp
- Kernel/Net/E1000NetworkAdapter.cpp
- Kernel/Net/NetworkTask.cpp
- Kernel/Process.cpp
- Kernel/Random.cpp
- Kernel/Scheduler.cpp
- Kernel/Scheduler.h
- Kernel/SpinLock.h
- Kernel/Tasks/FinalizerTask.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
- Kernel/WaitQueue.cpp
- Kernel/WaitQueue.h
I believe this should fix the hanging processes issue as reported in #2693
> Kernel: Fix a number of problems with the software context switching

- Shell/AST.cpp
- Shell/AST.h
- Shell/Parser.cpp
- Shell/Shell.cpp
- Shell/Shell.h
- Shell/main.cpp
Also fixes a slight mistake with comments eating their ending newlines.
> Shell: no error on missing init

- Shell/main.cpp
Normally, this should not happen, as the child should stay around until we do a waitid on it.
So for the sake of keeping it working, slap a fixme on it and adapt to the problem until it goes away :P
> Shell: Handle the case where the child we're waiting for doesn't exist

- Kernel/VM/MemoryManager.cpp
- Kernel/VM/PageDirectory.cpp
MemoryManager::quickmap_pd and MemoryManager::quickmap_pt can only
be called by one processor at the time anyway, since anything using
these must have the MM lock held. So, no need to inform the other
CPUs to flush their TLBs, we can just flush our own.
> Kernel: Minor MM optimization for SMP

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Shell/AST.cpp
- Shell/Shell.cpp
- Shell/Shell.h
- Shell/main.cpp
```sh
> cat
^D
> # Shell should not have the wrong idea about the terminal size
```
@awesomekling  :^)
> LibLine+Shell: SIGWINCH and stuff

- Libraries/LibLine/Editor.cpp
b/f go backward/forward by one character, d deletes one character.
Also do some minor preparatory changes to make it easier to support these shortcuts.
> LibLine: Support Ctrl-b/f and Ctrl-d

- Base/usr/share/man/man1/js.md
- Base/usr/share/man/man1/test-js.md
cc @bugaevc who is not much into LibJS stuff (I think) but likes man pages and might want to have a look :slightly_smiling_face:
> Base: Add man page for test-js(1)

- Userland/test-js.cpp
This was a nice feature the old `run-tests.sh` script had - let's add it to `test-js` as well! :^)
> test-js: Show progress in taskbar

- Base/etc/shellrc
- Remove "`alias sd=SystemDialog`" from `/etc/shellrc`
- Add "`alias ll='ls -l'`" to `/etc/shellrc`
> Base: Update /etc/shellrc aliases

- Shell/Shell.cpp
Closes #2732
Also fixes the case where nothing would be suggested if `PATH` was unset or empty (even builtins).
> Shell: Suggest aliases when completing program names :^)

- Kernel/FileSystem/Inode.cpp
Fixes crashes when a context switch happens in the middle
of modifying it, or when another thread on another processor
modifies it at the same time.
Should fix this crash I ran into:
```
[SyncTask(5:5)]: ASSERTION FAILED: node == m_tail
.././AK/InlineLinkedList.h:217 in void AK::InlineLinkedList<T>::remove(T*) [with T = Kernel::Inode]
[SyncTask(5:5)]: 0xc011c8b9  _Z18__assertion_failedPKcS0_jS0_ +185
[SyncTask(5:5)]: 0xc0132e5d  _ZN6Kernel5InodeD2Ev +117
[SyncTask(5:5)]: 0xc012ed9a  _ZN6Kernel11Ext2FSInodeD1Ev +84
[SyncTask(5:5)]: 0xc012edc0  _ZN6Kernel11Ext2FSInodeD0Ev +28
[SyncTask(5:5)]: 0xc019baab  _ZN2AK7HashMapIjNS_6RefPtrIN6Kernel11Ext2FSInodeEEENS_6TraitsIjEEE6removeERKj +193
[SyncTask(5:5)]: 0xc012ceb8  _ZN6Kernel6Ext2FS13uncache_inodeEj +52
[SyncTask(5:5)]: 0xc0130377 …
```
> Kernel: Protect INode list with SpinLock

- AK/HashMap.h
- AK/HashTable.h
- Libraries/LibCore/EventLoop.cpp
- Libraries/LibCore/EventLoop.h
- Shell/Shell.cpp
- Shell/Shell.h
- Shell/main.cpp
> Shell: Fix hanging (signal handling fixes)

- Applications/FontEditor/FontEditor.cpp
- Applications/FontEditor/FontEditor.h
- Applications/FontEditor/main.cpp
This adds Open..., Save, Save as... to FontEditor.
> FontEditor: Add a few menu items

- Applications/Piano/KnobsWidget.cpp
- Applications/Piano/MainWidget.cpp
- Applications/Piano/MainWidget.h
- Applications/Piano/RollWidget.cpp
- Applications/Piano/TrackManager.cpp
- Applications/Piano/TrackManager.h
- Libraries/LibGUI/Widget.cpp
> Piano: miscellaneous bug fixes

- Ports/neofetch/patches/add-serenity-support.patch
- Userland/ini.cpp
> Userland: Add "ini" command to read and write .ini config files

- Shell/AST.cpp
Fun story: aliases were initially recursive, but I got rid of that to disallow an alias resolving to itself.
That's no longer an issue though :shrug:
> Shell: Recursively resolve aliases

- Ports/ncurses/package.sh
> Ports: Build ncurses with sigwinch enabled

- AK/Utf8View.h
- Libraries/LibJS/CMakeLists.txt
- Libraries/LibJS/Forward.h
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/StringIterator.cpp
- Libraries/LibJS/Runtime/StringIterator.h
- Libraries/LibJS/Runtime/StringIteratorPrototype.cpp
- Libraries/LibJS/Runtime/StringIteratorPrototype.h
- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.h
- Libraries/LibJS/Tests/iterators/array-iterator.js
- Libraries/LibJS/Tests/iterators/string-iterator.js
Adds `StringIterator` and `%StringIteratorPrototype%` builtin objects.
> LibJS: Add StringIterator

- Userland/tree.cpp
After watching @awesomekling's youtube videos about serenity for a while I got inspired to start contributing myself.
One of the first things I tried after building the system was the "tree" command, but sadly it was missing. So I thought why not add it myself. Obviously it's not compliant to the original, and it could probably be written better, but it's a start! :)
> Userland: Add a basic version the tree command

- Applications/FileManager/DirectoryView.cpp
- Applications/FileManager/DirectoryView.h
- Applications/FileManager/main.cpp
- Libraries/LibDesktop/Launcher.cpp
- Libraries/LibDesktop/Launcher.h
- Libraries/LibGUI/Action.h
- Libraries/LibGUI/Menu.cpp
- Services/LaunchServer/ClientConnection.cpp
- Services/LaunchServer/ClientConnection.h
- Services/LaunchServer/LaunchServer.ipc
- Services/LaunchServer/Launcher.cpp
- Services/LaunchServer/Launcher.h
> FileManager: Add "Open with" menu

- Applications/FileManager/main.cpp
This action was already present when running FileManager in desktop mode, but now it's also available in windowed mode. :)
There appears to be some code duplication between desktop mode and windowed mode, which should be probably be fixed by someone more knowledgeable of the application.
> FileManager: Add a new file action to FileManager GUI

- AK/LexicalPath.cpp
> LexicalPath: Simplify a loop

- Libraries/LibGUI/TextEditor.cpp
> LibGUI: Disallow typing in DisplayOnly TextEditors

- Libraries/LibGUI/ComboBox.cpp
> LibGUI: Remove on_activity_change from ComboBox

- Kernel/Devices/KeyboardDevice.cpp
- Kernel/TTY/VirtualConsole.cpp
- Kernel/TTY/VirtualConsole.h
- Kernel/init.cpp
These changes make the kernel more robust as it was possible to crash the OS just by trying to switch to a not initialized VirtualConsole.
> Some improvements to the VirtualConsole(s)

- Shell/AST.cpp
- Shell/AST.h
> Shell: Mark ForLoop as would_execute (#2825)

- Demos/WidgetGallery/main.cpp
- Libraries/LibGUI/InputBox.cpp
- Libraries/LibGUI/Slider.cpp
Adds more widgets and combinations to the gallery for theming/testing convenience.
> WidgetGallery: Spruce up SerenityOS's flagship application

- Libraries/LibTLS/Socket.cpp
Previously, we would not care if the handshake timer timed out because
the server was too slow, or because we were too slow, this caused
connections to fail when the system was under heavy load.
This patch fixes this behaviour (and closes #2843) by checking if the
timeout delay was within margin of error of the max timeout.
> LibTLS: Reschedule the timeout if we're too slow

- Libraries/LibTextCodec/Decoder.cpp
> LibTextCodec: Simplify Latin1Decoder::to_utf8

- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Tests/operators/binary-bitwise-and.js
- Libraries/LibJS/Tests/operators/binary-bitwise-xor.js
And fix some edge case conversion bugs found by the tests.
> LibJS: Add tests for bitwise & and ^

- Libraries/LibWeb/Tests/Document/Doctype.js
- Libraries/LibWeb/Tests/Window/Base64.js
Thanks to #2862, it's now easy to write a test for #2854 :)
> LibWeb: Add tests for atob() and btoa()

- Applications/PixelPaint/CMakeLists.txt
- Applications/PixelPaint/Filters/BoxBlurFilter.cpp
- Applications/PixelPaint/Filters/BoxBlurFilter.h
- Applications/PixelPaint/Filters/Filter.cpp
- Applications/PixelPaint/Filters/Filter.h
- Applications/PixelPaint/Filters/GenericConvolutionFilter.cpp
- Applications/PixelPaint/Filters/GenericConvolutionFilter.h
- Applications/PixelPaint/Filters/LaplacianFilter.cpp
- Applications/PixelPaint/Filters/LaplacianFilter.h
- Applications/PixelPaint/Filters/SharpenFilter.cpp
- Applications/PixelPaint/Filters/SharpenFilter.h
- Applications/PixelPaint/Filters/SpatialGaussianBlurFilter.cpp
- Applications/PixelPaint/Filters/SpatialGaussianBlurFilter.h
- Applications/PixelPaint/Layer.h
- Applications/PixelPaint/main.cpp
- Libraries/LibGfx/Matrix.h
- Libraries/LibGfx/Matrix4x4.h
_/me blurs the entire layer_
whoo fun
It should be noted that the single dialog added (a matrix input dialog) is _bad_.
> PixelPaint: Add a bunch of spatial filters

- Demos/Eyes/EyesWidget.h
> Eyes: Fix division by zero when invoked as 'Eyes'

- .gitignore
Makes `git status` less noisy for vim users.
> .gitignore: Add .swo

- Meta/build-image-grub.sh
- Meta/build-image-qemu.sh
Oops. I didn't know there was a style guide for the scripts.
> Meta: Fix style of image building scripts

- .gitattributes
This file is used to configure Git to properly handle line endings.
> Meta: Add .gitattributes file

- Libraries/LibCrypto/CMakeLists.txt
- Libraries/LibCrypto/Checksum/Adler32.cpp
- Libraries/LibCrypto/Checksum/Adler32.h
- Libraries/LibCrypto/Checksum/CRC32.cpp
- Libraries/LibCrypto/Checksum/CRC32.h
- Libraries/LibCrypto/Checksum/ChecksumFunction.h
- Userland/test-crypto.cpp
Namely CRC32 and Adler32
Does some work towards #362 by implementing some of the sub-algorithms used.
> LibCrypto: Add some checksum algorithms

- Kernel/Syscalls/sysconf.cpp
- Kernel/UnixTypes.h
I don't actually know what lead to their sudden breakage, but this fixes them.
> Ports: Fix binutils and gcc ports

- Applications/FileManager/PropertiesDialog.cpp
- Applications/FileManager/PropertiesDialog.h
> FileManager: Build new path of renamed files correctly

- AK/MappedFile.cpp
- AK/MappedFile.h
- AK/StringView.cpp
- AK/StringView.h
- Applications/Help/ManualModel.cpp
- Applications/Help/ManualModel.h
- Applications/Help/main.cpp
- Kernel/StdLib.cpp
- Kernel/StdLib.h
- Libraries/LibC/string.cpp
- Libraries/LibC/string.h
- Libraries/LibGUI/CMakeLists.txt
- Libraries/LibGUI/FilteringProxyModel.cpp
- Libraries/LibGUI/FilteringProxyModel.h
- Libraries/LibGUI/Model.h
- Libraries/LibGUI/TextEditor.cpp
- Libraries/LibGUI/TextEditor.h
- Tests/LibC/memmem-tests.cpp
This closes #2685.
~~There is a minor issue where the scrollbar on the ListView is updated _after_ the contents change, but I couldn't figure out how to fix that.~~
cc for people that I know are interested: @bugaevc @linusg @awesomekling
> Help: Search-as-you-type and full text search

- Applications/PixelPaint/Filters/BoxBlurFilter.cpp
- Applications/PixelPaint/Filters/BoxBlurFilter.h
- Applications/PixelPaint/Filters/Filter.h
- Applications/PixelPaint/Filters/GenericConvolutionFilter.cpp
- Applications/PixelPaint/Filters/GenericConvolutionFilter.h
- Applications/PixelPaint/Filters/LaplacianFilter.cpp
- Applications/PixelPaint/Filters/LaplacianFilter.h
- Applications/PixelPaint/Filters/SharpenFilter.cpp
- Applications/PixelPaint/Filters/SharpenFilter.h
- Applications/PixelPaint/Filters/SpatialGaussianBlurFilter.cpp
- Applications/PixelPaint/Filters/SpatialGaussianBlurFilter.h
- Applications/PixelPaint/main.cpp
Also tweaks the GUI to look a bit less...bad.
those types tho...they look horrible...
> PixelPaint: Make `GenericConvolutionFilterInputDialog` cancellable

- Applications/SystemMonitor/MemoryStatsWidget.cpp
- Applications/SystemMonitor/MemoryStatsWidget.h
- Applications/SystemMonitor/ProcessStacksWidget.cpp
- Applications/SystemMonitor/main.cpp
This makes the SystemMonitor GUI a bit more beautiful (new actions, better usability, better readability).
> SystemMonitor: More beautiful

- AK/Time.h
- Kernel/FileSystem/Plan9FileSystem.cpp
- Kernel/FileSystem/Plan9FileSystem.h
- Kernel/Ptrace.cpp
- Kernel/Scheduler.cpp
- Kernel/Scheduler.h
- Kernel/Thread.cpp
- Kernel/Thread.h
- Libraries/LibIPC/ServerConnection.h
On my quest to finally solve the occasional Terminal hang, I found some possible races with `Thread::block`. But fixing all these still didn't solve the problem. It turned out to be a problem with LibIPC. This subtle log message ended up giving it away:
```
WindowServer(14): AddMenuItem: Bad menu ID: 1982
```
> Fix terminal hang

- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Shell/Builtin.cpp
- Shell/Shell.cpp
- Shell/Shell.h
Pipes and such.
This closes #2989.
> Shell+LibLine: Do not assume that stdin/stdout is a TTY

- Meta/CLion/CMakeLists.txt
Also bumps the CXX Standard to C++20.
> Meta: Update CLion configuration to include LibM and generated files

- Documentation/UsingQtCreator.md
This was already in video form, but I figured it might be nice to
have this here as well, to make it easier to discover.
> Documentation: Add a guide for setting up Qt Creator

- Libraries/LibLine/Editor.cpp
@alimpfard questions the utility of these shortcuts on IRC, to which I reply: Nonsense, nonsense, NONSENSE.
> LibLine: Add bindings for Alt-u, Alt-l, Alt-c

- Userland/aplay.cpp
- Userland/avol.cpp
- Userland/basename.cpp
- Userland/chgrp.cpp
- Userland/disasm.cpp
- Userland/hostname.cpp
- Userland/jp.cpp
- Userland/md.cpp
- Userland/modload.cpp
- Userland/modunload.cpp
- Userland/ping.cpp
- Userland/pro.cpp
- Userland/purge.cpp
- Userland/realpath.cpp
- Userland/rmdir.cpp
- Userland/su.cpp
- Userland/tr.cpp
- Userland/tt.cpp
- Userland/uname.cpp
- Userland/which.cpp
- Userland/yes.cpp
This is most of `Userland`, more to follow. Summoning @bugaevc :)
> Userland: Core::ArgsParser all the things

- Libraries/LibLine/Editor.cpp
It backward-deletes a word like Ctrl-W, but it has a slightly
different definition of what a word is. For example, with the
caret behind `gcc -fsanitize=address`, Ctrl-W would delete
'-fsanitize=address' but Alt-backspace would only delete 'address'.
> LibLine: Add binding for Alt-backspace

- Libraries/LibLine/Editor.cpp
It feels like this should be possible to implement this much shorter, but I don't see it right now.
Probably should extract a few "move left/right by a word" functions and use them in a few places (including here), which would probably help too.
> LibLine: Add Alt-t shortcut for transposing words

- Applications/KeyboardSettings/main.cpp
And the cherry on top. KeyboardSettings now checks `/proc/keymap` to see which keymap is currently in use,
and shows it preselected on the list. Neat!
> KeyboardSettings: Preselect the current keymap in the dropdown menu.

- Base/res/html/misc/welcome.html
Hi.
I thought the links to the test pages in browser homepage could use another color other than the default blue for better visibility. I used a system color here instead. If that's not okay, the PR can be closed; it's a very minor thing after all!
Regards,
Sakib
> change test page link colors for better visibility

- Libraries/LibTLS/Record.cpp
https://github.com/SerenityOS/serenity/commit/bc7a149039538f26e10444f38db6682d5df57333#r41386045
Oops...(first time making a PR from GitHub's web interface, it's weiiiird)
> LibTLS: Re-silence a debug log

- Kernel/Syscalls/setpgid.cpp
- Shell/AST.cpp
- Shell/AST.h
- Shell/Builtin.cpp
- Shell/Forward.h
- Shell/Job.cpp
- Shell/Job.h
- Shell/Shell.cpp
> Shell: Move pipelined processes into one process group (+tiny fixes)

- Services/WindowServer/WindowManager.cpp
In the case of an ongoing window drag/move/resize action `WindowManager::process_mouse_event()` would return early, even before delivering mouse events to windows with global cursor tracking enabled. They would only continue to receive new mouse events once those actions were completed.
Fixes #3116.
> WindowServer: Handle global cursor tracking before ongoing drag/move/resize

- Kernel/FileSystem/ProcFS.cpp
Pledges and Veil state don't really make sense for kernel mode
processes, as they can do what ever they want since they are in
kernel mode. Make this clear in the system monitor UI by keeping
them empty.
> Kernel: Emit ProcFS pledge/veil properties as null for kernel processes

- Libraries/LibLine/Editor.h
- Shell/Shell.cpp
- Shell/Shell.h
Just a small quality of life improvement.
cc @vkoskiv, IIRC you asked for this.
> Shell: Fancy no-newline indicators and such

- Documentation/BuildInstructions.md
Inspired by #3047, and my struggles to understand how cmake is supposed to work ^^
CC @Dexesttp, because he wrote the original description, and probably knows better commands for day-to-day use.
> Meta: Explain how to build with ninja

- Libraries/LibCore/ConfigFile.cpp
- Libraries/LibCore/ConfigFile.h
- Libraries/LibLine/CMakeLists.txt
- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Libraries/LibLine/InternalFunctions.cpp
- Shell/main.cpp
This PR adds configurable keybindings.
My current favourite keybinding is `e=internal:finish_edit`, it makes almost everything impossible to do lol
> LibLine: Allow the user to override (or add) keybinds in the config file

- Applications/Calendar/main.cpp
Adds "Help" menuitem and "About" dialogue.
> Calendar: Add help menuitem

- Kernel/API/Syscall.h
- Kernel/Net/IPv4Socket.cpp
- Kernel/Net/IPv4Socket.h
- Kernel/Net/LocalSocket.cpp
- Kernel/Net/LocalSocket.h
- Kernel/Net/Socket.cpp
- Kernel/Net/Socket.h
- Kernel/Process.h
- Kernel/Syscalls/socket.cpp
More progress on the Userspace<T> all the things long term goal.
> Kernel: Use Userspace<T> for the sendto + recvfrom syscalls

- Kernel/CMakeLists.txt
- Kernel/Process.cpp
- Kernel/Process.h
- Kernel/ProcessGroup.cpp
- Kernel/ProcessGroup.h
- Kernel/Syscalls/fork.cpp
- Kernel/Syscalls/setpgid.cpp
- Kernel/TTY/TTY.cpp
- Kernel/TTY/TTY.h
- Shell/AST.cpp
- Shell/Job.h
- Shell/Shell.cpp
This fixes #3160 
I'm not sure if the "let everyone read from and write to a tty with no controlling process" thing is a very good idea though.
> Shell+Kernel: TTY signals, ProcessGroup's and pipe stuff

- Services/SystemServer/Service.cpp
Removes unused header files
Add Socket.h header file
> Services: Clean include files inclusion in SystemService

- Applications/Spreadsheet/CMakeLists.txt
- Applications/Spreadsheet/CellSyntaxHighlighter.cpp
- Applications/Spreadsheet/CellSyntaxHighlighter.h
- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/SpreadsheetView.cpp
- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/main.cpp
The highlighter is just a conditional javascript highlighter, so I had to mark that guy non-final
Fixes two crashes as well.
> Spreadsheet: Hotfixes & expression highlight

- Documentation/BuildInstructions.md
Add missing `cmake ..' line before compiling with make
> Documentation: Update BuildInstructions.md

- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/Spreadsheet.h
- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/SpreadsheetWidget.h
- Applications/Spreadsheet/main.cpp
- Libraries/LibGUI/Action.cpp
- Libraries/LibGUI/Action.h
> Spreadsheet: load&save

- Libraries/LibGUI/ScrollBar.cpp
- Libraries/LibGUI/ScrollBar.h
In preparation for continuous scrolling by page while the mouse is down in the gutter.
> LibGUI: Minor ScrollBar tweaks

- Libraries/LibGUI/ScrollBar.cpp
- Libraries/LibGUI/ScrollBar.h
The middle commit is the one with the interesting behavior change.
I think it'd be nice if the gutter also had both a "hover" highlight and a "pressed" highlight, but I haven't yet found one I like.
> LibGUI: Scrollbar painting tweaks

- AK/Bitmap.h
- AK/NeverDestroyed.h
- AK/Noncopyable.h
- AK/RefCounted.h
- AK/Tests/TestChecked.cpp
- Applications/Piano/Track.h
- Applications/Piano/TrackManager.h
- DevTools/HackStudio/Project.h
- DevTools/HackStudio/Tool.h
- Games/Minesweeper/Field.h
- Libraries/LibC/stdlib.cpp
- Libraries/LibCore/Event.h
- Libraries/LibCore/Object.h
- Libraries/LibGUI/Widget.h
- Libraries/LibGfx/Bitmap.h
- Libraries/LibGfx/Palette.h
- Libraries/LibJS/Runtime/Symbol.h
Another mixed bag – I assume this is preferred these over three individual PRs.
> Nicer AK_MAKE_NONXXXABLE, remove dead data, document test

- Kernel/Interrupts/GenericInterruptHandler.h
- Kernel/Interrupts/IRQHandler.h
- Kernel/Interrupts/SharedIRQHandler.cpp
> Kernel: Remove the enabled concept of IRQ handlers

- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/SpreadsheetWidget.h
Just a tiny fix for the ctrl-select bug @awesomekling found~
> Spreadsheet: Do not clear cells when ctrl-selecting

- Kernel/FileSystem/Ext2FileSystem.cpp
- Kernel/FileSystem/Ext2FileSystem.h
- Kernel/UnixTypes.h
Previously, we were unable to stage untracked files in the git port.
This fixes this behavior with a small change to Ext2FS code.
We can now create a new git repo and then stage and commit new files :smile:
> Fix git port

- Base/res/js/Spreadsheet/runtime.js
you get stats and you get stats
have some more basic stats
> Spreadsheet: Add a whole bunch of basic statistical functions

- Applications/Browser/BookmarksBarWidget.cpp
- Applications/Browser/BookmarksBarWidget.h
- Applications/Browser/Tab.cpp
- Applications/Browser/Tab.h
- DevTools/HackStudio/main.cpp
- Libraries/LibVT/TerminalWidget.cpp
Inspired by 1c1ab716921d8c6c200a1298364903388929fd0a.
Let's see how controversial these are ^^
> More "default" context menus

- Demos/HelloWorld/main.cpp
- Demos/LibGfxDemo/main.cpp
As we have nice icons for all the demos in the system menu now (#3344, courtesy of @thankyouverycool) we can also use them for their windows.
> Demos: Set HelloWorld and LibGfxDemo window icons

- Libraries/LibGfx/GIFLoader.cpp
1. Fix issues with GIF frame disposal modes (fixes file download animation reported in #3291).
2. Add support for interlaced GIFs (fixes Google Doodle in #3291).
3. GIFLoader now uses a single frame buffer to cache the last decoded frame. This drastically reduces memory usage at the small expense of re-decoding frames on each loop.
> LibGfx: GIF decoding fixes and improvements

- Kernel/Syscalls/shutdown.cpp
Source: https://wiki.osdev.org/Shutdown
> Kernel: Add shutdown commands for other virtualizers

- DevTools/HackStudio/Debugger/DebugInfoWidget.cpp
- DevTools/HackStudio/Debugger/DisassemblyWidget.cpp
- DevTools/HackStudio/Debugger/RegistersModel.cpp
- DevTools/HackStudio/Debugger/RegistersModel.h
Also adds shortcuts for step in (F11), step out (Shift-F11) and
step over (F10).
Demo:
> HackStudio: Highlight register changes, minor disassembly view fix

- AK/PrintfImplementation.h
- Userland/ntpquery.cpp
Mind if I try to register serenityos.pool.ntp.org at https://manage.ntppool.org/manage/vendor ?
From what I understand, that's so that we can be blacklisted if we do something silly (but I might be wrong).
> Add a bare-bones NTP client to Userland

- Libraries/LibC/stdio.cpp
- Userland/pro.cpp
From #3341 I realised that `pro` needs some love too.
This PR adds support for:
- ~~`-o filename` (Save to given file)~~
- `-O` (Save to a file named as the server or the URL suggests)
and also partially implements `freopen()`.
No more `pro url > filename`!
> Userland: Make 'pro' capable of guessing a filename

- Applications/ThemeEditor/main.cpp
- DevTools/VisualBuilder/VBPropertiesWindow.cpp
- DevTools/VisualBuilder/main.cpp
> Apps: Set correct icons for ThemeEditor and VisualBuilder

- Kernel/Net/E1000NetworkAdapter.cpp
Also adds FIXME for VirtualBox.
> Kernel: Add more detailed debug output for E1000 {in,out}{8,16,32}

- Kernel/Heap/Heap.h
- Kernel/Heap/kmalloc.cpp
- Kernel/VM/MemoryManager.cpp
- Kernel/VM/MemoryManager.h
- Kernel/VM/Region.cpp
- Kernel/VM/Region.h
Some follow-up changes for #3370 to handle low-memory situations a little more gracefully.
> Kernel: More low memory fixes

- AK/Bitmap.h
- AK/Tests/TestBitmap.cpp
I was surprised to see that there is no method to count bitmap values or clear/set them for a specific a range (other than checking or setting each bit in a loop). This provides a somewhat faster way of obtaining that information and setting/clearing ranges of bits.
> AK: Add Bitmap::count_in_range and Bitmap::fill_range

- Libraries/LibGfx/Color.h
- Libraries/LibGfx/Painter.cpp
- Libraries/LibGfx/Painter.h
- Services/WindowServer/Compositor.cpp
This makes it easier to see the minimize animation, e.g. above a maximized TextEditor.
> WindowServer: Inverted minimize animation

- Libraries/LibGUI/AbstractView.cpp
Just to make it look cleaner :)
> LibGUI: small calling change

- Services/WindowServer/ClientConnection.cpp
There is a window between windows disappearing (e.g. closing or crashes)
and the Taskbar process being notified. So it is entirely possible that
it may call SetWindowTaskbarRect() for a window that no longer exists.
As the Taskbar process does not own these windows, this should not be
treated as a misbehaving application request. Instead, just silently
ignore the request. The Taskbar will be notified shortly after that the
window no longer exist and remove it from its list.
Fixes #3494
> WindowServer: Make SetWindowTaskbarRect tolerant to non-existing windows

- Libraries/LibIPC/Connection.h
Writing to the socket may trigger a close of the socket descriptor
if a disconnect was detected. We need to check if it is still valid
when waiting for a response after attempting to send a synchronous
message.
Fixes #3515
> LibIPC: Check if socket is still open before using socket descriptor

- Libraries/LibJS/AST.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Tests/test-common.js
cherry-picking a few things from #3518 that don't really belong to that PR anyway.
> LibJS: Misc changes

- Kernel/KResult.h
We need to track whether we actually own the storage.
I ran into some odd problems returning a `KResultOr` from a function as-is. I traced it to move semantics not being properly implemented.
> Kernel: Fix KResultOr move semantics

- Shell/Shell.cpp
- Shell/main.cpp
I finally found where `setsid()` goes!
Fixes #3530.
> Shell: text mode fixes

- DevTools/UserspaceEmulator/Emulator.cpp
The kernel doesn't support msg_iovlens != 1 yet and nothing passes
an amount != 1, but if anyone ever adds support for this they won't
have to worry about ue at least.
> UserspaceEmulator: Support all msg_iovlens in recvmsg and sendmsg

- DevTools/HackStudio/CMakeLists.txt
- DevTools/HackStudio/Debugger/DebugInfoWidget.h
- DevTools/HackStudio/EditorWrapper.cpp
- DevTools/HackStudio/FindInFilesWidget.cpp
- DevTools/HackStudio/FindInFilesWidget.h
- DevTools/HackStudio/HackStudio.h
- DevTools/HackStudio/HackStudioWidget.cpp
- DevTools/HackStudio/HackStudioWidget.h
- DevTools/HackStudio/Locator.cpp
- DevTools/HackStudio/Project.cpp
- DevTools/HackStudio/main.cpp
I felt like some refactoring work was due in the GUI code of HackStudio.
This quite a big diff, but there's nothing dramatic here, just moving stuff that was previously all in the `main` function into the `HackStudioWidget`.
> HackStudio: Refactoring GUI logic

- Applications/SystemMonitor/DevicesModel.cpp
- Applications/SystemMonitor/NetworkStatisticsWidget.cpp
- Applications/SystemMonitor/NetworkStatisticsWidget.h
- Applications/SystemMonitor/ProcessFileDescriptorMapWidget.cpp
- Applications/SystemMonitor/ProcessFileDescriptorMapWidget.h
- Applications/SystemMonitor/ProcessMemoryMapWidget.cpp
- Applications/SystemMonitor/ProcessUnveiledPathsWidget.cpp
- Applications/SystemMonitor/ProcessUnveiledPathsWidget.h
Now every table in SystemMonitor can properly be sorted.
> SystemMonitor: Fix table sorting

- DevTools/UserspaceEmulator/main.cpp
It allows us to set emulation settings from command line in future.
> UserspaceEmulator: Use Core::ArgsParser

- Applications/Spreadsheet/CMakeLists.txt
- Applications/Spreadsheet/Cell.cpp
- Applications/Spreadsheet/Cell.h
- Applications/Spreadsheet/CellType/Date.cpp
- Applications/Spreadsheet/CellType/Date.h
- Applications/Spreadsheet/CellType/Numeric.cpp
- Applications/Spreadsheet/CellType/Type.cpp
- Applications/Spreadsheet/CellType/Type.h
- Applications/Spreadsheet/CellTypeDialog.cpp
- Applications/Spreadsheet/CellTypeDialog.h
- Applications/Spreadsheet/CondFormatting.json
- Applications/Spreadsheet/CondView.json
- Applications/Spreadsheet/ConditionalFormatting.h
- Applications/Spreadsheet/Forward.h
- Applications/Spreadsheet/JSIntegration.cpp
- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/SpreadsheetModel.cpp
- Applications/Spreadsheet/SpreadsheetView.cpp
- Libraries/LibGUI/AbstractView.cpp
- Libraries/LibGUI/Widget.cpp
Images, as I have no idea how to describe this:
---
I cannot get `ScrollableWidget` to play nice and lay these conditional formatting thingies out vertically, some help on that would be nice.
Also the GUI looks rather crap, hopefully I can put my GUI making hat on again and make a styling dialog/preview...eventually.
> Spreadsheet: Conditional Formatting

- Kernel/Process.cpp
- Kernel/Scheduler.cpp
- Kernel/Syscalls/thread.cpp
- Kernel/Thread.cpp
- Kernel/Thread.h
The thread joining logic hadn't been updated to account for the subtle
differences introduced by software context switching. This fixes several
race conditions related to thread destruction and joining, as well as
finalization which did not properly account for detached state and the
fact that threads can be joined after termination as long as they're not
detached.
Fixes #3596
> Kernel: Fix thread joining issues

- DevTools/HackStudio/Debugger/DebugInfoWidget.cpp
- DevTools/HackStudio/Debugger/Debugger.cpp
- DevTools/HackStudio/Debugger/Debugger.h
- DevTools/HackStudio/HackStudioWidget.cpp
- DevTools/HackStudio/HackStudioWidget.h
- Libraries/LibDebug/DebugSession.cpp
- Libraries/LibDebug/DebugSession.h
- Libraries/LibThread/Thread.h
Fixes #3308 and some issues with icon loading in the FormEditor.
~~Currently a draft, waiting on #3603 to get merged as it's required for this fix to work.~~
> HackStudio: Detach from debugged process before terminating

- Toolchain/CMakeToolchain.txt
remove call to action comment to define SERENITY_ROOT
> remove call to action comment to define SERENITY_ROOT

- Applications/Spreadsheet/Cell.h
- Applications/Spreadsheet/JSIntegration.cpp
- Applications/Spreadsheet/Position.h
- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/Spreadsheet.h
- Base/res/js/Spreadsheet/runtime.js
This PR adds `lookup` (which, according to [Excel's docs](https://support.microsoft.com/en-us/office/excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb), is one of the top ten most used functions in excel...huh), and its indirect friend `reflookup` without its weird parts.
TIL that excel (and whatever copies it) treats `A1` as a relative address, I had a blast finding ways to make a better interface than "imagine the topleft cell is here".
Achievement unlocked: Worst DBMS on the planet!
Be amazed (the conditional formatting is there to make it look better than it actually is):
> Spreadsheet: A few more functions

- Applications/TextEditor/CMakeLists.txt
- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/TextEditorWidget.h
- DevTools/HackStudio/CMakeLists.txt
- DevTools/HackStudio/HackStudioWidget.cpp
- Libraries/LibGUI/CMakeLists.txt
- Libraries/LibGUI/ShellSyntaxHighlighter.cpp
- Libraries/LibGUI/ShellSyntaxHighlighter.h
- Shell/AST.cpp
- Shell/AST.h
- Shell/Builtin.cpp
- Shell/CMakeLists.txt
- Shell/Parser.cpp
- Shell/Parser.h
- Shell/Shell.cpp
- Shell/Shell.h
- Shell/main.cpp
Title says all.
Draft for the time being, until I squash some bugs in it :P
> Shell+LibGUI: Syntax highlighting in text editors

- Base/usr/share/man/man1/Shell.md
Basically an "improve docs" PR, but a serious one.
cc @alimpfard
> Base: Add missing options to the Shell(1) man page

- Shell/main.cpp
Why is this a separate PR? I dunno, your first guess is probably right.
(this actually annoyed me once I saw it lol)
> Shell: IMPROVE HELP STRING - or something like that

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Interpreter.cpp
- Libraries/LibJS/Interpreter.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Runtime/ScriptFunction.cpp
- Libraries/LibJS/Runtime/ScriptFunction.h
- Libraries/LibJS/Runtime/VM.h
- Libraries/LibJS/Tests/strict-mode-blocks.js
> LibJS: Strict mode should be function- or file-level, not block-level

- AK/Format.h
- AK/URL.h
- Applications/Browser/BrowserConsoleClient.cpp
- Applications/Browser/ConsoleWidget.cpp
- Applications/Browser/DownloadWidget.cpp
- Applications/Browser/History.cpp
- Applications/Browser/Tab.cpp
- Applications/Browser/main.cpp
This is part of my crusade to spread the use of format.
> Browser: Use format functions instead of printf.

- AK/Format.cpp
- AK/Format.h
- AK/LogStream.cpp
- AK/LogStream.h
- AK/TestSuite.h
- Applications/IRCClient/IRCClient.cpp
- DevTools/UserspaceEmulator/Emulator.cpp
- DevTools/UserspaceEmulator/Emulator.h
- DevTools/UserspaceEmulator/MallocTracer.cpp
- DevTools/UserspaceEmulator/MmapRegion.cpp
- DevTools/UserspaceEmulator/SoftCPU.cpp
- DevTools/UserspaceEmulator/SoftMMU.cpp
- DevTools/UserspaceEmulator/main.cpp
- Services/TelnetServer/main.cpp
- Services/WebServer/main.cpp
- Shell/Shell.cpp
- Shell/main.cpp
- Userland/tar.cpp
[I brought this up in the IRC chat.][1]
There is an quite elaborate description of these changes in the commit message of 1d7039acc2a34c0c8d1e2ecef8309b27863b0c3d.
[1]: https://freenode.logbot.info/serenityos/20201004
> AK: Don't add newlines in outf/dbgf/warnf.

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Heap/Heap.cpp
- Libraries/LibJS/MarkupGenerator.cpp
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Runtime/ArrayPrototype.cpp
- Libraries/LibJS/Runtime/BigInt.h
- Libraries/LibJS/Runtime/BoundFunction.cpp
- Libraries/LibJS/Runtime/Date.h
- Libraries/LibJS/Runtime/ErrorPrototype.cpp
- Libraries/LibJS/Runtime/ErrorTypes.h
- Libraries/LibJS/Runtime/FunctionConstructor.cpp
- Libraries/LibJS/Runtime/FunctionPrototype.cpp
- Libraries/LibJS/Runtime/IteratorOperations.cpp
- Libraries/LibJS/Runtime/JSONObject.cpp
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/ObjectPrototype.cpp
- Libraries/LibJS/Runtime/ProxyConstructor.cpp
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/Reference.cpp
- Libraries/LibJS/Runtime/ReflectObject.cpp
- Libraries/LibJS/Runtime/RegExpObject.cpp
- Libraries/LibJS/Runtime/ScriptFunction.cpp
- Libraries/LibJS/Runtime/StringPrototype.cpp
- Libraries/LibJS/Runtime/Symbol.h
- Libraries/LibJS/Runtime/SymbolConstructor.cpp
- Libraries/LibJS/Runtime/VM.cpp
- Libraries/LibJS/Runtime/VM.h
- Libraries/LibJS/Runtime/Value.cpp
Supporting @asynts in his [crusade](https://github.com/SerenityOS/serenity/pull/3679).
> LibJS: Use String::formatted() / dbgf()

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Tests/operators/assignment-operators.js
> LibJS: Evaluate AssignmentExpression LHS before RHS according to the spec

- Applications/FileManager/DirectoryView.cpp
- Applications/FileManager/FileUtils.cpp
- Applications/FileManager/PropertiesDialog.cpp
- Applications/FileManager/main.cpp
I am now aiming to create smaller pull requests instead of a fewer larger ones like #3684. If you prefer larger pull requests, just say so, it's the same effort on my end.
> FileManager: Use new format functions.

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Lexer.cpp
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Tests/operators/assignment-operators.js
- Libraries/LibJS/Token.h
TC39 proposal, stage 4 as of 2020-07. https://tc39.es/proposal-logical-assignment/
> LibJS: Implement logical assignment operators (&&=, ||=, ??=)

- AK/JsonParser.cpp
Resolves edge case found via fuzzing in #3670
> AK: check fractional string has_value() in JsonParser

- AK/Format.cpp
- AK/Format.h
- AK/Tests/TestFormat.cpp
- Applications/HexEditor/HexEditor.cpp
- Applications/HexEditor/HexEditorWidget.cpp
- Applications/IRCClient/IRCAppWindow.cpp
- Applications/IRCClient/IRCChannel.cpp
- Applications/IRCClient/IRCClient.cpp
- Applications/IRCClient/IRCLogBuffer.cpp
- Applications/IRCClient/IRCWindowListModel.cpp
- Applications/IRCClient/main.cpp
- Applications/KeyboardSettings/main.cpp
- Applications/Piano/SamplerWidget.cpp
- Applications/Piano/main.cpp
- Applications/PixelPaint/ToolboxWidget.cpp
- Applications/PixelPaint/main.cpp
- Applications/QuickShow/QSWidget.cpp
- Applications/QuickShow/main.cpp
- Applications/SoundPlayer/PlaybackManager.cpp
- Applications/SoundPlayer/SoundPlayerWidget.cpp
- Applications/Spreadsheet/CellTypeDialog.cpp
- Applications/Spreadsheet/HelpWindow.cpp
- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/main.cpp
Recently, I said, that I wanted to create smaller pull requests... Hmm... :^)
There are really two interesting commits here, 18cd462ca014866395dcecf7e7643846b83e752f and 9716ffa7103b2e12df082ee9ab55631b4b152f9c. I explained my thoughts in the commits themselves.
The rest is just me replacing more usages.
> AK+Format: Exclude prefix from width calculation, and the "crusade" continues.

- Applications/SystemMonitor/MemoryStatsWidget.cpp
- Applications/SystemMonitor/ProcessFileDescriptorMapWidget.cpp
- Applications/SystemMonitor/ProcessMemoryMapWidget.cpp
- Applications/SystemMonitor/ProcessModel.cpp
- Applications/SystemMonitor/ProcessUnveiledPathsWidget.cpp
- Applications/SystemMonitor/ThreadStackWidget.cpp
- Applications/SystemMonitor/main.cpp
- Applications/Terminal/main.cpp
- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/main.cpp
- Applications/Welcome/main.cpp
- Libraries/LibGUI/TextPosition.h
- Libraries/LibGUI/TextRange.h
That's one top-level directory dealt with.
> Use new format functions in remaining applications.

- AK/Format.cpp
- AK/Format.h
- AK/IPv4Address.h
- AK/JsonObject.h
- AK/MACAddress.h
- AK/MappedFile.cpp
- AK/NumberFormat.h
- AK/PrintfImplementation.h
- AK/SharedBuffer.cpp
- AK/StringImpl.cpp
- AK/StringImpl.h
- AK/TestSuite.h
- AK/Tests/TestFormat.cpp
- AK/URL.cpp
- AK/URLParser.cpp
- AK/Utf8View.cpp
- Demos/Cube/Cube.cpp
- Demos/DynamicLink/LinkDemo/main.cpp
- Demos/DynamicLink/LinkLib/DynamicLib.cpp
- Demos/Eyes/main.cpp
- Demos/Fire/Fire.cpp
- Demos/WebView/main.cpp
- Kernel/KBufferBuilder.h
I am trying to make smaller pull requests and yet they become larger and larger...
This pull request also adds a `FormatIfSupported` wrapper which should be really nice (although the SFINAE stuff looks crappy.)
> Use new format functions in AK and Demos.

- Applications/Help/main.cpp
- Applications/TextEditor/MainWindow.json
- Applications/TextEditor/TextEditorWidget.cpp
- Applications/TextEditor/TextEditorWidget.h
- DevTools/HackStudio/Editor.cpp
- DevTools/HackStudio/Editor.h
- Libraries/LibWeb/Forward.h
- Libraries/LibWeb/InProcessWebView.cpp
- Libraries/LibWeb/Loader/FrameLoader.cpp
- Libraries/LibWeb/Loader/FrameLoader.h
- Libraries/LibWeb/OutOfProcessWebView.cpp
- Libraries/LibWeb/OutOfProcessWebView.h
- Libraries/LibWeb/Page/Frame.cpp
- Libraries/LibWeb/Page/Page.cpp
- Libraries/LibWeb/Page/Page.h
- Services/WebContent/ClientConnection.cpp
- Services/WebContent/ClientConnection.h
- Services/WebContent/WebContentServer.ipc
- Userland/html.cpp
Well, not *all* the things, but quite a few. Inspired by TextEditor crashing because of some LibWeb thing - not anymore. :^)
> Web::OutOfProcessWebView all the things

- Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
--
I watched the "Let's write a HTML parser!" video this morning. It is one of my favorites so far, really nicely done.
> LibWeb: In the HTML tokenizer, pretty up ON_WHITESPACE a tiny bit

- AK/Format.cpp
- AK/Format.h
- AK/LexicalPath.h
- DevTools/HackStudio/CursorTool.cpp
- DevTools/HackStudio/Debugger/BacktraceModel.cpp
- DevTools/HackStudio/Debugger/DebugInfoWidget.cpp
- DevTools/HackStudio/Debugger/Debugger.cpp
- DevTools/HackStudio/Debugger/DisassemblyModel.cpp
- DevTools/HackStudio/Debugger/RegistersModel.cpp
- DevTools/HackStudio/Debugger/VariablesModel.cpp
- DevTools/HackStudio/Editor.cpp
- DevTools/HackStudio/EditorWrapper.cpp
- DevTools/HackStudio/Git/DiffViewer.cpp
- DevTools/HackStudio/Git/GitRepo.cpp
- DevTools/HackStudio/Git/GitWidget.cpp
- DevTools/HackStudio/HackStudioWidget.cpp
- DevTools/HackStudio/LanguageServers/Cpp/AutoComplete.cpp
- DevTools/HackStudio/LanguageServers/Cpp/ClientConnection.cpp
- DevTools/HackStudio/LanguageServers/Shell/AutoComplete.cpp
- DevTools/HackStudio/LanguageServers/Shell/ClientConnection.cpp
- DevTools/HackStudio/Locator.cpp
- DevTools/HackStudio/ProcessStateWidget.cpp
- DevTools/HackStudio/Project.cpp
- DevTools/HackStudio/TerminalWrapper.cpp
- DevTools/HackStudio/WidgetTool.cpp
- DevTools/HackStudio/WidgetTreeModel.cpp
- Libraries/LibGfx/Rect.h
The commit 04386134db7d88edb32d75d16dccb52c11dfd25e might be of interest, the rest is just more replacing.
> HackStudio: Use new format functions.

- Applications/FileManager/main.cpp
Added action to show dotfiles in the context menu of the directory view. :)
> FileManager: Added action to show dotfiles in directory view context menu

- Ports/pkgconf/package.sh
- Ports/pkgconf/patches/build-system.patch
> Ports: add pkgconf for pkg-config support

- Userland/aplay.cpp
A tiny feature, useful when listening to your favorite song.
> Userland: Add --loop option for aplay

- Applications/PixelPaint/BrushTool.cpp
- Applications/PixelPaint/BrushTool.h
- Applications/PixelPaint/BucketTool.cpp
- Applications/PixelPaint/CMakeLists.txt
- Applications/PixelPaint/PenTool.cpp
- Applications/PixelPaint/PenTool.h
- Applications/PixelPaint/SprayTool.cpp
- Applications/PixelPaint/SprayTool.h
- Applications/PixelPaint/Tool.h
- Applications/PixelPaint/ToolPropertiesWidget.cpp
- Applications/PixelPaint/ToolPropertiesWidget.h
- Applications/PixelPaint/main.cpp
Each tool can have its own set of properties that can be modified
through a panel on the right side.
The tools I've added properties for are:
Pen:
Thickness
Brush:
Size
Hardness
Spray:
Thickness
Density
Bucket:
Threshold
> PixelPaint: Tool properties panel

- Kernel/VM/PhysicalRegion.cpp
> Kernel: Ensure PhysicalRegion free page hint is within valid range

- AK/Format.cpp
- AK/Format.h
- AK/NonnullOwnPtr.h
- AK/Tests/TestFormat.cpp
- AK/WeakPtr.h
- Games/2048/main.cpp
- Games/Snake/SnakeGame.cpp
- Games/Solitaire/main.cpp
- Libraries/LibAudio/WavLoader.cpp
- Libraries/LibAudio/WavWriter.cpp
- Libraries/LibChess/UCICommand.cpp
- Libraries/LibChess/UCIEndpoint.cpp
- Libraries/LibCore/Account.cpp
- Libraries/LibCore/ArgsParser.cpp
- Libraries/LibCore/Command.cpp
- Libraries/LibCore/ConfigFile.cpp
- Libraries/LibCore/DateTime.cpp
- Libraries/LibCore/DirIterator.cpp
- Libraries/LibCore/EventLoop.cpp
- Libraries/LibCore/Object.cpp
- Libraries/LibCore/Object.h
9b03ad40d26b7e129a721dbaa189fd831d80440f is probably interesting, the rest is just replacing more `printf` and `LogStream` stuff.
> Use new format functions in LibChess, LibAudio, Games and a bit of LibCore.

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/Tests/switch-basic.js
How this went unnoticed and untested is beyond me. Nice find @Lubrsi :)
Fixes #3790.
> LibJS: Handle return value / continue in switch statement unwinding

- Toolchain/BuildIt.sh
...oops. maybe let this one run to completion before hitting the green button :)
> Toolchain: Set CACHED_TOOLCHAIN_ARCHIVE after computing hash

- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Tests/classes/class-errors.js
- Libraries/LibJS/Tests/object-basic.js
See commit messages for detailed descriptions. TL;DR: Two test262-parser-test failures less :^)
> LibJS: Function parameter parsing stuff

- Libraries/LibJS/AST.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Tests/numeric-literals-basic.js
- Libraries/LibJS/Tests/parser-declaration-in-single-statement-context.js
My daily dose of LibJS improvements!
---
Fixes 40 (:smiley:) test262-parser-tests tests.
> LibJS: Various parser fixes

- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Tests/string-escapes.js
- Libraries/LibJS/Tests/try-catch-finally.js
- Libraries/LibJS/Tests/use-strict-directive.js
- Libraries/LibJS/Token.cpp
- Libraries/LibJS/Token.h
test262-parser-tests that should fail but don't: 343 -> 320
> LibJS: More parser things

- Libraries/LibGUI/Splitter.cpp
We need to skip over widgets that are not visible as the layout does
not update their location. This fixes finding the correct widgets
surrounding the splitter.
Fixes #3491
> LibGUI: Fix Splitter sometimes not working after widgets were resized

- Shell/Shell.cpp
> Shell: Fix off-by-one in EOL mark printing

- Base/etc/LookupServer.ini
- Services/LookupServer/DNSResponse.cpp
- Services/LookupServer/LookupServer.cpp
- Services/LookupServer/LookupServer.h
Best reviewed as individual commits as I also did some other things. Closes #3843.
> LookupServer: Support multiple nameservers

- Libraries/LibMarkdown/Document.cpp
> LibMarkdown: Flush the pending paragraphs when encountering empty lines

- Base/home/anon/.shellrc
- Base/usr/share/man/man7/Shell-vars.md
- Libraries/LibLine/Editor.cpp
- Libraries/LibLine/Editor.h
- Shell/Builtin.cpp
- Shell/Shell.cpp
- Shell/Shell.h
- Shell/main.cpp
- Userland/js.cpp
Details in commit messages. cc @alimpfard
> LibLine+Shell: Support HISTCONTROL and HISTFILE env vars / js: load and save history

- Games/Solitaire/Card.cpp
- Games/Solitaire/Card.h
- Games/Solitaire/CardStack.cpp
- Games/Solitaire/CardStack.h
- Games/Solitaire/SolitaireWidget.cpp
- Games/Solitaire/SolitaireWidget.h
This PR adds a simple animation that is played when a new game is started.
I also used this opportunity to fix some uglyness in the code that lays out the cards on a card stack.
> Solitaire: Add new game animation

- DevTools/Profiler/main.cpp
This will help us identify which View(Top functions, Invert tree, Show percentages) that we are currently looking at.
> Profiler: Set window title based on the selected View

- Applications/Spreadsheet/SpreadsheetWidget.h
- Applications/Spreadsheet/main.cpp
> Spreadsheet: Add Help menu

- Libraries/LibWeb/DOM/XMLHttpRequest.cpp
`DOM::XMLHttpRequest` now checks if the requested URL has the same
`Origin` as the requesting `Document`. If the requested URL is in
violation of SOP the request is rejected and an "error" `DOM::Event`
is dispatched.
Resolves #1615
---
This is a rudimentary implementation. It is restrictive. CORS requests are not supported.
I added a `dbg()` debugging statement as, given that `Browser` has not enforced SOP until now, I presume rejecting requests due to SOP violations will be unexpected and confusing for developers.
Perhaps most importantly, this change prevents random websites stealing files (https://github.com/SerenityOS/serenity/issues/1615#issuecomment-610782263 #3632).
```html
<html>
<head>
<title>hello friends</title>
</head>
<body>
Logs 1: <pre id="logs1"></pre>
<hr/>
Logs 2: <pre …
```
> LibWeb: Enforce Same-Origin Policy (SOP) for XMLHttpRequest requests

- Applications/SoundPlayer/PlaybackManager.cpp
- Applications/SoundPlayer/PlaybackManager.h
- Applications/SoundPlayer/main.cpp
Now you can listen to your Piano creations on loop once exported.
> SoundPlayer: Optionally allow playback to loop indefinitely

- DevTools/HackStudio/HackStudioWidget.cpp
When a file is deleted from the project it will also be removed from the list of open files
> HackStudio: Removes the file from the list of open files

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
- Libraries/LibJS/Runtime/ScriptFunction.cpp
- Libraries/LibJS/Tests/functions/function-new-target.js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target
Also did some cleanup around syntax error line/columns.
> LibJS: Implement 'new.target'

- Applications/Spreadsheet/Position.h
- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/Spreadsheet.h
- Applications/Spreadsheet/SpreadsheetModel.cpp
- Applications/Spreadsheet/SpreadsheetModel.h
- Applications/Spreadsheet/SpreadsheetView.cpp
- Applications/Spreadsheet/SpreadsheetWidget.h
- Applications/Spreadsheet/main.cpp
- Libraries/LibGUI/AbstractView.cpp
> LibGUI: Shift-select / Spreadsheet: Copy/Paste and Drag'n'Drop

- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/RegExpObject.cpp
- Libraries/LibJS/Runtime/RegExpObject.h
- Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Libraries/LibJS/Runtime/RegExpPrototype.h
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Tests/builtins/RegExp/RegExp.prototype.toString.js
- Libraries/LibJS/Tests/ordinary-to-primitive.js
https://tc39.es/ecma262/#sec-ordinarytoprimitive
> LibJS: Implement spec-compliant OrdinaryToPrimitive

- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Tests/builtins/Object/Object.js
- Libraries/LibJS/Tests/builtins/Proxy/Proxy.handler-get.js
- Libraries/LibJS/Tests/builtins/Proxy/Proxy.handler-set.js
> LibJS: Implement Object(value) constructor, fix crash in Proxy get/set with symbol properties

- Libraries/LibWeb/HTML/HTMLFormElement.cpp
Form submissions to `file://` URLs are now permitted only if the
submitting document is also a `file://` URL and the form method is "get".
Form submissions to URLs with a `http(s)://` URL protocol are permitted.
Form submissions for all other URL protocols are rejected.
> LibWeb: Restrict HTML form submissions to permitted URL protocols

- AK/StringView.h
- Kernel/Time/TimeManagement.cpp
- Libraries/LibCore/ArgsParser.cpp
- Libraries/LibCore/ArgsParser.h
A bit of a grab bag. This is all useful for something I'm hacking on every now and then, but it's arguably (minorly) useful in itself, so I'm trying to reduce my local diff a bit :)
> Teach ArgsParser about options taking doubles; tweak epoch time update; remove unused methods

- Libraries/LibWeb/CodeGenerators/WrapperGenerator.cpp
- Libraries/LibWeb/HTML/AttributeNames.cpp
- Libraries/LibWeb/HTML/AttributeNames.h
- Libraries/LibWeb/HTML/HTMLButtonElement.idl
- Libraries/LibWeb/HTML/HTMLDetailsElement.idl
- Libraries/LibWeb/HTML/HTMLDialogElement.idl
- Libraries/LibWeb/HTML/HTMLElement.idl
- Libraries/LibWeb/HTML/HTMLFormElement.idl
- Libraries/LibWeb/HTML/HTMLIFrameElement.idl
- Libraries/LibWeb/HTML/HTMLImageElement.idl
- Libraries/LibWeb/HTML/HTMLInputElement.idl
- Libraries/LibWeb/HTML/HTMLLinkElement.idl
- Libraries/LibWeb/HTML/HTMLMediaElement.idl
- Libraries/LibWeb/HTML/HTMLOListElement.idl
- Libraries/LibWeb/HTML/HTMLOptGroupElement.idl
- Libraries/LibWeb/HTML/HTMLOptionElement.idl
- Libraries/LibWeb/HTML/HTMLScriptElement.idl
- Libraries/LibWeb/HTML/HTMLSelectElement.idl
- Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
- Libraries/LibWeb/HTML/HTMLTrackElement.idl
- Libraries/LibWeb/HTML/HTMLVideoElement.idl
Also throw in some missing reflected DOMString values
> LibWeb: Add support for reflected boolean values

- Ports/indent/package.sh
- Ports/indent/patches/disable-docs.patch
- Ports/indent/patches/fix-autoconf.patch
plist:
```
/usr/local/bin/indent
/usr/local/share/man/man1/indent.1
/usr/local/share/locale/ca/LC_MESSAGES/indent.mo
/usr/local/share/locale/da/LC_MESSAGES/indent.mo
/usr/local/share/locale/de/LC_MESSAGES/indent.mo
/usr/local/share/locale/eo/LC_MESSAGES/indent.mo
/usr/local/share/locale/et/LC_MESSAGES/indent.mo
/usr/local/share/locale/fi/LC_MESSAGES/indent.mo
/usr/local/share/locale/fr/LC_MESSAGES/indent.mo
/usr/local/share/locale/gl/LC_MESSAGES/indent.mo
/usr/local/share/locale/hu/LC_MESSAGES/indent.mo
/usr/local/share/locale/it/LC_MESSAGES/indent.mo
/usr/local/share/locale/ja/LC_MESSAGES/indent.mo
/usr/local/share/locale/ko/LC_MESSAGES/indent.mo
/usr/local/share/locale/nl/LC_MESSAGES/indent.mo
/usr/local/share/locale/pl/LC_MESSAGES/indent.mo …
```
> Ports: Add GNU indent

- Kernel/Syscalls/unveil.cpp
This addresses the issue first enountered in #3644. If a path is
first unveiled with "c" permissions, we should NOT return ENOENT
if the node does not exist on the disk, as the program will most
likely be creating it at a later time.
> Kernel: Prevent `unveil` returning ENOENT with cpath permissions

- Libraries/LibGUI/IconView.cpp
Set the max height of the text_rect to be the height difference
between two icons. Calculate the number of text lines that can be 
displayed in this height and display only that many.
One line
Two lines
Max lines:
Todo:
Related to #3964
> LibGUI: Limit the height of item text in IconView

- Userland/ls.cpp
> ls: Add -A flag to show dot files excluding implied . and .. directories

- Base/usr/share/man/man1/ls.md
- Userland/ls.cpp
> Userland: ls: Add `-d` / `--directory` flag

- Kernel/Arch/i386/CPU.cpp
- Kernel/Arch/i386/CPU.h
- Kernel/Lock.cpp
- Kernel/SpinLock.h
- Kernel/VM/MemoryManager.cpp
- Kernel/VM/MemoryManager.h
- Kernel/VM/PageDirectory.h
- Kernel/VM/RangeAllocator.cpp
- Kernel/VM/RangeAllocator.h
- Kernel/VM/Region.cpp
This is a collection of commits from #3864 that should be safe to get in now. Trying to keep that other PR manageable while working on the countless of other related issues.
> Various SMP related fixes

- Userland/Tests/Kernel/filesystem-strips-file-suid-sgid-bits-when-modified.cpp
> Userland: Add test for file SUID+SGID bits stripped when modified

- Kernel/Thread.cpp
This fixes a lot of crashes in Bochs, which is more likely to
preempt thread destruction.
```
[FinalizerTask(3:3)]: ASSERTION FAILED: ptr
.././AK/NonnullRefPtr.h:257 in T* AK::NonnullRefPtr<T>::as_nonnull_ptr() const [with T = Kernel::Process]
[FinalizerTask(3:3)]: 0xc011ef05  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[FinalizerTask(3:3)]: 0xc0185f07  Kernel::Thread::pid() const [clone .part.0] +47
[FinalizerTask(3:3)]: 0xc0185f1a  Kernel::Process::for_each_thread<Kernel::Process::has_tracee_thread(AK::DistinctNumeric<int, false, true, true, false, false, false, __ProcessID_tag>) const::{lambda(Kernel::Thread&)#1}>(Kernel::Process::has_tracee_thread(AK::DistinctNumeric<int, false, true, true, false, false, false, __ProcessID_tag>) …
```
> Kernel: Fix race during thread destruction if it is preempted

- Meta/Lagom/CMakeLists.txt
- Meta/Lagom/Fuzzers/CMakeLists.txt
- Meta/Lagom/Fuzzers/FuzzGemini.cpp
- Meta/Lagom/ReadMe.md
Most interesting bugs I found by my fuzzers are now independently fixed, and the remaining ones are mostly harmless, so I can probably start landing more of fuzzer stuff.
> Add a gemini fuzzer, and tweak fuzzer docs and flags a bit

- AK/StringUtils.cpp
- AK/Tests/TestStringUtils.cpp
- DevTools/HackStudio/Locator.cpp
- Libraries/LibGUI/FileIconProvider.cpp
- Libraries/LibGUI/FileSystemModel.cpp
- Libraries/LibGfx/Bitmap.cpp
- Libraries/LibGfx/Bitmap.h
Various small fixes and improvements.
> HackStudio+LibGfx+LibGUI/FileIconProvider: QOL improvements

- .github/workflows/cmake.yml
- Meta/notify_irc.py
thakis runs the bridge, so if it goes down blame him instead of me :P
See #4072 for the toolchain topic.
> IRC bridge without joins/parts, and fix toolchain caching

- Meta/notify_irc.py
What a silly mistake. How did I manage to do that?
Candidate for the shortest, silliest PR this year.
> Meta: Fix IRC notification script

- Libraries/LibGfx/PPMLoader.cpp
- Meta/Lagom/Fuzzers/CMakeLists.txt
- Meta/Lagom/Fuzzers/FuzzPPMLoader.cpp
It only found one bug and that's been fixed at head (and the checked-in fix is better than the one I had locally too).
> Add a PPM fuzzer

- Libraries/LibGUI/TextEditor.cpp
When clicking empty space (beneath any used lines) in the TextEditor, the cursor would jump to the start of the last line, rather than the correct column, or the end of the line where appropriate. This was because the for_each_visual_line callback would return IterationDecision::Continue if the clicked point wasn't in the line's rect. Thus the callback would continue on each iteration and at the end, would set the cursor to the default column of 0. To fix this I added a bool to the callback's signature which tells the callback if the for_each_visual_line method is on the last visual line. The callback now does not return IterationDecision:Continue if for_each_visual_line method is on the last line and the correct column is then calculated with the line passed.
Resolves #4048
> TextEditor: Change cursor behaviour when clicking empty space

- AK/Tests/TestNeverDestroyed.cpp
Problem:
- It is difficult to refactor because there are no tests to bind the
functionality.
- Arguments are not forwarded correctly to the constructor.
Solution:
- Add tests.
- Change constructor to take forwarding references.
> NeverDestroyed: Add tests

- Libraries/LibGUI/FilePicker.cpp
> FilePicker: Set Icon Based On Mode

- Meta/notify_irc.py
> Meta: Reduce IRC spam

- .github/codeql/config.yml
- .github/workflows/cmake.yml
CodeQL is a static analysis technology that was purchased by GitHub
and has been tightly integrated into the platform. It's different
from most other static analysis solutions because it's based on a
database built from your codebase, and then language specific rules
can be executed against that database. The rules are fully user
extensible, and are written in a datalog/query language.
The default cpp language rules coming from CodeQL will probably find
some issues, the ability to easily write custom rules/queries will
lend it self nicely to allowing us to validate Serenity specific
semantics are followed throughout the code.
References:
- https://www.youtube.com/watch?v=AMzGorD28Ks
- https://securitylab.github.com/tools/codeql
> Meta: Enable CodeQL static analysis for Serenity

- Libraries/LibWeb/TreeNode.h
Follow-up to #4182
Uhm... I focused a little too much on the edge case that caused my crashed and missed two other edge cases.
I hope this is all of them.
> LibWeb: Two more edge cases for TreeNode::insert_before.

- Base/usr/share/man/man1/find.md
- Userland/find.cpp
cc @alimpfard @danboid
https://github.com/SerenityOS/serenity/issues/4191
> find -name

- Libraries/LibRegex/RegexMatcher.h
- Libraries/LibRegex/RegexParser.cpp
- Meta/Lagom/Fuzzers/CMakeLists.txt
- Meta/Lagom/Fuzzers/FuzzRegexECMA262.cpp
- Meta/Lagom/Fuzzers/FuzzRegexPosixExtended.cpp
cc @alimpfard and @Lubrsi (this should solve the LibRegex-related issues in https://github.com/SerenityOS/serenity/pull/4181)
> Lagom: Add Regex fuzzers

- Userland/mv.cpp
> Userland: Make `mv` capable of moving multiple files

- ReadMe.md
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge
> Once your project has started building, we’d love it if you added our badge in your project’s README. This allows you to see bugs found by your OSS-Fuzz integration at a glance.
[![Fuzzing Status](https://oss-fuzz-build-logs.storage.googleapis.com/badges/serenity.svg)](https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:serenity)
---
It's also a nice reminder to get #4181 done & the OSS-Fuzz build fixed :)
> Meta: Add OSS-Fuzz badge to ReadMe.md

- Meta/Lagom/ReadMe.md
We added OSS-Fuzz integration in #4154, but documentation about it
is spread across several pull requests, IRC, and issues. Let's collect
the important bits in the ReadMe.
> Lagom: Mention OSS-Fuzz in ReadMe

- AK/StringImpl.h
- Libraries/LibCore/IODevice.cpp
- Libraries/LibRegex/RegexParser.cpp
- Userland/grep.cpp
- Userland/mount.cpp
> LibCore: Add File::get_line()
cc @bugaevc - you've been asking for something like this since forever.
> LibCore+Userland: Implement -I/-a (binary-mode) and -i (insensitive) for grep

- Applications/Terminal/main.cpp
This solves utmpupdate zombies hanging around until Terminal
terminates.
Found this while working on #4113. We don't (consistently?) show as zombies in `master`, but in PR #4113 these dead/zombie processes rightfully show up in SystemManager.
> Terminal: Wait on the utmpupdate process to finish

- Meta/Lagom/Fuzzers/CMakeLists.txt
- Meta/Lagom/Fuzzers/FuzzURL.cpp
> Lagom/Fuzzers: Add URL fuzzer

- Libraries/LibGfx/JPGLoader.cpp
This patch rids us of the ugly hack that we had to go through while handling table redefinitons.
> JPGLoader: Use HashMaps to store huffman tables

- Applications/FileManager/DirectoryView.cpp
> FileManager: Call on_selection_change with the correct view

- Meta/Lagom/ReadMe.md
Follow-up to #4242
Hey @devsh0, what do you think about moving the jpg fuzz testcases there? :)
Hey @everybodyelse, what do you think about this? ^^
> Meta: Document fuzz dump

- Libraries/LibGfx/BMPLoader.cpp
These changes fixed various asserts when I ran the fuzzer locally a
while ago.
> LibGfx: Add some validation to BMPLoader

- .github/workflows/cmake.yml
Makes watching build output on Actions on PRs slightly more pleasant.
---
No idea if this actually works, but I guess the PR CI Action will tell me.
> CI: Use Ninja for buildling

- Libraries/LibJS/CMakeLists.txt
- Libraries/LibJS/Forward.h
- Libraries/LibJS/Runtime/CommonPropertyNames.h
- Libraries/LibJS/Runtime/ErrorTypes.h
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/GlobalObject.h
- Libraries/LibJS/Runtime/ProxyConstructor.cpp
- Libraries/LibJS/Runtime/TypedArray.cpp
- Libraries/LibJS/Runtime/TypedArray.h
- Libraries/LibJS/Runtime/TypedArrayConstructor.cpp
- Libraries/LibJS/Runtime/TypedArrayConstructor.h
- Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Libraries/LibJS/Runtime/TypedArrayPrototype.h
- Libraries/LibJS/Tests/builtins/Proxy/Proxy.js
- Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.BYTES_PER_ELEMENT.js
- Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.js
See commit messages for gory details. Someone was really winging it :)
> LibJS: TypedArray fixes

- Services/SystemServer/main.cpp
We need to call waitpid until no more waitable children are available.
This is necessary because SIGCHLD signals may coalesce into one when
multiple children terminate almost simultaneously.
This fixes random zombie processes sticking around after e.g. closing
Browser.
Also, switch to EventLoop's asynchronous signal handling mechanism,
which allows more complex operations in the signal handler.
> SystemServer: Wait on all waitable children in SIGCHLD handler

- Libraries/LibJS/CMakeLists.txt
- Libraries/LibJS/Forward.h
- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/ArrayBuffer.cpp
- Libraries/LibJS/Runtime/ArrayBuffer.h
- Libraries/LibJS/Runtime/ArrayBufferConstructor.cpp
- Libraries/LibJS/Runtime/ArrayBufferConstructor.h
- Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp
- Libraries/LibJS/Runtime/ArrayBufferPrototype.h
- Libraries/LibJS/Runtime/ArrayConstructor.cpp
- Libraries/LibJS/Runtime/CommonPropertyNames.h
- Libraries/LibJS/Runtime/ErrorTypes.h
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/TypedArray.cpp
- Libraries/LibJS/Runtime/TypedArray.h
- Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Tests/builtins/Array/Array.js
- Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.isView.js
- Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.js
- Libraries/LibJS/Tests/builtins/ArrayBuffer/ArrayBuffer.prototype.byteLength.js
- Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.js
> LibJS: Add ArrayBuffer and use it for typed arrays

- Games/Breakout/CMakeLists.txt
- Games/Breakout/Game.cpp
- Games/Breakout/Game.h
- Games/Breakout/LevelSelectDialog.cpp
- Games/Breakout/LevelSelectDialog.h
Added a level select menu which is shown when the game start where
either of the 2 available levels may be selected.
> Games: Added level select and aditional level to Breakout

- Applications/SoundPlayer/SoundPlayerWidget.cpp
- Applications/SoundPlayer/SoundPlayerWidget.h
- Applications/SoundPlayer/main.cpp
- Libraries/LibAudio/WavLoader.cpp
SoundPlayer will now accept dropped files and handle loading errors a bit better. Also, I screwed up in my last PR, WAV files can now be parsed correctly when reading from memory :)
> LibAudio+SoundPlayer: Fix loading errors

- Libraries/LibGUI/Variant.cpp
- Libraries/LibGUI/Variant.h
Fix a simple FIXME from a year ago.
> LibGUI: Optimize GUI::Variant move constructor

- Libraries/LibVT/TerminalWidget.cpp
- Libraries/LibVT/TerminalWidget.h
> LibVT: Auto-scroll the terminal

- Base/home/anon/.config/bookmarks.json
Google can't have all the fun can it?
> Browser: Add DuckDuckGo to bookmarks

- Games/Chess/ChessWidget.cpp
- Games/Chess/ChessWidget.h
- Games/Chess/main.cpp
- Libraries/LibChess/Chess.cpp
- Libraries/LibChess/Chess.h
Started to add some features I wanted to the Chess game. This is just the start, I'm planing on adding a lot more in the future.
Hope that everything is okay, I'm willing to take any recommendations/advice and change the code accordingly if needed.
> Added resign, flip board and export game as PGN to Chess game

- Libraries/LibGUI/Action.h
- Libraries/LibGUI/WindowServerConnection.cpp
- Libraries/LibVT/TerminalWidget.cpp
- Libraries/LibVT/TerminalWidget.h
See commit messages for details.
Screenshots:
> LibVT+Terminal: Enable Copy/paste actions conditionally / Add "Copy name" action to terminal link context menu

- Userland/cp.cpp
> Userland: Fix overly-eager loop detection in cp

- Libraries/LibGfx/Painter.cpp
This patchset fixes:
- Some parts of the path being skipped and not drawn (often horizontal)
- The filled shape moving around on an int grid depending on the winding
number
- Winding number mess-up with four-way intersections
Our boi Chess (see notes on e119d7d):
(can't really demo it, but `canvas-path-quadratic-curve.html` shouldn't be moving around anymore)
> LibGfx: Make fill_path() less bad at filling paths

- DevTools/UserspaceEmulator/Emulator.cpp
- DevTools/UserspaceEmulator/Emulator.h
> UserspaceEmulator: Implement beep syscall

- DevTools/UserspaceEmulator/Emulator.cpp
- DevTools/UserspaceEmulator/Emulator.h
Two steps closer to emulating `Terminal`.
> UserspaceEmulator: Implement geteuid, getegid, ptsname syscalls

- Games/Chess/ChessWidget.cpp
- Games/Chess/ChessWidget.h
- Games/Chess/main.cpp
> Chess: Prevent board changes when waiting for ChessEngine to move

- DevTools/HackStudio/LanguageServers/Cpp/ClientConnection.cpp
- DevTools/HackStudio/LanguageServers/Shell/ClientConnection.cpp
- Libraries/LibGUI/TextDocument.cpp
- Libraries/LibGUI/TextDocument.h
- Libraries/LibGUI/TextEditor.h
> HackStudio: Fix desync between hackstudio texteditor widget and language server

- Libraries/LibGfx/Point.h
- Libraries/LibGfx/Rect.h
- Libraries/LibGfx/Size.h
Not used yet, but useful and I might use them later. (Looking at scale support for Painter.)
> LibGfx: Give Rect and Size scale operators, slightly improve the ones in Point

- AK/FlyString.cpp
- AK/FlyString.h
- AK/JsonParser.cpp
- AK/String.cpp
- AK/String.h
- AK/StringUtils.cpp
- AK/StringUtils.h
- AK/StringView.cpp
- AK/StringView.h
- AK/Tests/TestStringUtils.cpp
> AK: Generalize AK::String::to_int() for more types

- Kernel/VM/MemoryManager.cpp
Quite similar to what we had with #742, just less severe.
> Kernel: Don't skip if found free page to allocate from a super physical region

- Userland/userdel.cpp
Not a big deal, but if we're going to validate whether the user's home directory is `/` we may as well do it properly.
> Userland: userdel: Resolve home directory realpath before removal

- Kernel/Net/E1000NetworkAdapter.cpp
Since they're all covered by the same spec sheet, we can expect
the same code to cover most of the devices.
It can't currently differentiate between them, which would be nice to
add for determining what registers we can access.
> Kernel/Net: Support all E1000 devices in the spec sheet

- Applications/Spreadsheet/Spreadsheet.cpp
- Applications/Spreadsheet/SpreadsheetWidget.cpp
- Applications/Spreadsheet/SpreadsheetWidget.h
- Applications/Spreadsheet/Workbook.cpp
- Applications/Spreadsheet/Workbook.h
- Applications/Spreadsheet/main.cpp
> Spreadsheet: Prompt user before closing with unsaved changes

- Base/home/anon/.config/LaunchServer.ini
- Base/res/apps/Browser.af
- Services/LaunchServer/Launcher.cpp
- Services/LaunchServer/Launcher.h
- Userland/open.cpp
Some small improvements for `LaunchServer` and `open(1)`.
> open+LaunchServer: Improvements

- Userland/DynamicLoader/main.cpp
This fixes a regression introduced with dynamic libraries, where the following command stopped working due to us no longer flushing standard streams on exit.
```sh
$ echo foo > bar
```
> DynamicLoader: Call libc's exit when exitting, to flush standard streams

- Libraries/LibGfx/StandardCursor.h
- Services/WindowServer/ClientConnection.cpp
- Services/WindowServer/Cursor.cpp
> WindowServer: Validate cursor type in SetWindowCursor message handler

- AK/Tests/CMakeLists.txt
- AK/Tests/TestTrie.cpp
- AK/Trie.h
- Kernel/FileSystem/ProcFS.cpp
- Kernel/FileSystem/VirtualFileSystem.cpp
- Kernel/FileSystem/VirtualFileSystem.h
- Kernel/Process.h
- Kernel/Syscalls/fork.cpp
- Kernel/Syscalls/unveil.cpp
- Kernel/UnveilNode.h
- Meta/lint-ci.sh
- Userland/test-unveil.cpp
> (PoC) Kernel: Implement unveil() as a prefix-tree

- AK/StdLibExtras.h
- AK/Tests/TestTrie.cpp
- AK/Trie.h
This wasn't testing anything ^^'
> AK: Fix busted Trie test
